### ISSUE TITLE
GetSSSR interrupts by segmentation fault

### ISSUE THREAD

**Issue by PiotrDabr** [rdkit/rdkit#1023]
When I'm trying to get the smallest set of simple rings in order to initialize RingInfo for a specific molecule the program interrupts with segmentation faul.

```
In [1]: from rdkit.Chem import AllChem

In [2]: mol = AllChem.MolFromPDBFile(/home/piotr/Desktop/test.pdb.txt', sanitize=False)

In [3]: mol is not None
Out[3]: True

In [4]: AllChem.GetSSSR(mol)
Segmentation fault
```
Error code printed by PyCharm:
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

Molecule that causes the problem:
[test.pdb.txt](https://github.com/rdkit/rdkit/files/415176/test.pdb.txt)

**Comment by greglandrum** [comment]
Thanks for the bug report.
I can reproduce this and will look into fixing it.

**Comment by greglandrum** [comment]
This isn't an excuse for the seg fault, but that molecule, which has features like a C atom with 13 bonds, isn't really chemically reasonable. This is unlikely to ever really work well with the RDKit.

**Comment by PiotrDabr** [comment]
Sure. Maybe the molecule isn't proper, but, as you said, it isn't an excuse for the segmentation fault. Thanks for help!

**Comment by bp-kelley** [comment]
RDKIT does a reasonable job determining the connectivity if the CONNECT records are removed.  I ran the same structure through COOT and ended up with the same connectivity.  Perhaps we could add a PDB sanitize step that compares the connect records versus the perceived ones?  Might be useful information in any case.
