### ISSUE TITLE
Aromaticity of non-protein molecules in PDB not detected

### ISSUE THREAD

**Issue by salotz** [rdkit/rdkit#1031]
The PDB reader does not seem to assign aromaticity correctly for non-protein molecules, see this example which reads in 3 different versions of the small molecule benzamidine:

The .pdb file retrieved from rcsb (rcsb: 3ptb):

```
BEN_pdb_rdkit = Chem.MolFromPDBFile("3ptb_BEN.pdb", removeHs=False, sanitize=True)
AllChem.Compute2DCoords(BEN_pdb_rdkit)
Chem.Draw.MolToFile(BEN_pdb_rdkit, osp.join(masttmpdir, "BEN_pdb.png"))
```

![ben_pdb](https://cloud.githubusercontent.com/assets/7883146/17707519/c8bc9428-63ae-11e6-9ba7-7f36bf06391f.png)

The same .pdb file as before with hydrogens added:

```
BEN_Hs_pdb_rdkit = Chem.MolFromPDBFile("BEN+Hs_3ptb.pdb", removeHs=False, sanitize=True)
AllChem.Compute2DCoords(BEN_Hs_pdb_rdkit)
Chem.Draw.MolToFile(BEN_Hs_pdb_rdkit, osp.join(masttmpdir, "BEN_Hs_pdb.png"))
```

![ben_hs_pdb](https://cloud.githubusercontent.com/assets/7883146/17707534/d38d739a-63ae-11e6-98fc-edd8ca5c110e.png)

The .mol file retrieved from chemspider (chemspiderID: 2242).

```
BEN_mol_rdkit = Chem.MolFromMolFile("benzamidine.mol", removeHs=False, sanitize=True)
AllChem.Compute2DCoords(BEN_mol_rdkit)
Chem.Draw.MolToFile(BEN_mol_rdkit, osp.join(masttmpdir, "BEN_mol.png"))
```

![ben_mol](https://cloud.githubusercontent.com/assets/7883146/17707539/d7cf5f40-63ae-11e6-8e04-c5f6bc581978.png)

The first two (pdbs) incorrectly do not assign aromaticity to the ring

The mol correctly identifies the aromatic rings. 

I would just use the .mol but the atom ordering is different making it a real pain to translate them.

Additionally the protein has the correct assignments as far as I can tell.

[3ptb_BEN.pdb.txt](https://github.com/rdkit/rdkit/files/420802/3ptb_BEN.pdb.txt)
[BEN+Hs_3ptb.pdb.txt](https://github.com/rdkit/rdkit/files/420801/BEN.Hs_3ptb.pdb.txt)
[benzamidine.mol.txt](https://github.com/rdkit/rdkit/files/420803/benzamidine.mol.txt)

**Comment by greglandrum** [comment]
Assigning bond orders to arbitrary molecules from PDB data is a subtle and difficult thing. The RDKit doesn't even try.

What you can do is use the combination of a mol file or a SMILES together with the PDB molecule to get a version of the molecule with the PDB atom numbering and coordinates but correct bond orders. The function to do this is `AllChem.AssignBondOrdersFromTemplate`. 
The documentation is here: 
http://www.rdkit.org/Python_Docs/rdkit.Chem.AllChem-module.html#AssignBondOrdersFromTemplate
There are some examples of using it here:
http://www.rdkit.org/docs/Cookbook.html#d-functionality-in-the-rdkit

**Comment by salotz** [comment]
Thanks Greg! Just another reason to _love_ the PDB format.

**Comment by greglandrum** [comment]
I'm going to close this because I think the question is answered. Please re-open if you want to followup.

**Comment by salotz** [comment]
BEN_MOL_rdkit = Chem.MolFromMolBlock("benzamidine.mol", sanitize=True)
    BEN_PDB_rdkit = Chem.MolFromPDBBlock("BEN+Hs_3ptb," removeHs=False, sanitize=True)
    BEN_rdkit = AllChem.AssignBondOrdersFromTemplate(BEN_MOL_rdkit, BEN_PDB_rdkit)

This almost works for me, up until the call to `SanitizeMol` in `AllChem.AssignBondOrdersFromTemplate` (line 503) I get this error message:

    ValueError: Sanitization error: Explicit valence for atom # 2 N, 4, is greater than permitted

I used `GetTotalValence` on each atom before the call to `SanitizeMol` and the Ns both returned 3. However, after the call (in ipdb debugger) the second one had been altered to 4. I couldn't step into `SanitizeMol`, so that is all I know.

I think the unsanitized molecule would give me all I need anyhow as I only need if the atom is aromatic, which is already set.

**Comment by greglandrum** [comment]
This is related to #1029, but unfortunately the fix for that is unlikely to help here.
The specific problem here is that the amidine group in the PDB ligand is protonated: both Ns have two Hs attached. This means that one has to have a + charge, which it doesn't in that PDB file.
The + charge that's required to make the ligand sensible will make it so that the benzamidine from the mol file, which doesn't have that + charge, isn't a match. To be fair, it's *not* a match.

Since the solution to #1029 is going to end up working only for amino acids (where the connectivity is known in advance), managing the same thing for the ligand is likely going to require a different implementation. I'm going to have to think about it for a bit, but I don't *think* this is a general use case. It's probably better to write some special-purpose code to manage these situations.

**Comment by bp-kelley** [comment]
FYI, there is at least one extension to the PDB where the connect records are duplicated to indicate single, double and triple bonds.  It is not a bad thing to support for internal round tripping.  I'll see if I can get an example.

**Comment by mwojcikowski** [comment]
Have you tried the AssignBondOrdersFromTemplate function from #886 ? You can just copy it to your code and it should work. I found it to be more robust, but yet needs some polish on my side to merge it to master. What it does is removing extra bonds an disconnected fragments from your template using inverse matching (mol -> template) and/or MCS.
