### ISSUE TITLE
Wrong version info in patch release 2016.03.4 

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#1038]
Not a very critical problem, but the revision currently tagged as Release_2016_03_4 doesn't include updated version info in the main CMakeLists.txt (it still builds as 2016.03.3)

**Comment by greglandrum** [comment]
Damn. Thanks for catching that.
I just updated CMakeLists.txt (and conf.py for the docs) and deleted and re-created the release.

**Comment by rvianello** [comment]
I wouldn't have noticed it, but the conda recipe labels the package based on the version returned by the code.

It works now, but when building the postgres cartridge it fails test rdkit-91with an output that looks like it could be related to #986 and b9fbd0b (maybe this latter was to be included?).

**Comment by greglandrum** [comment]
<sigh> That's what I get for just being used to seeing that test fail and not investigating.
Fixed now. At least it's just an expected test result this time.

Thanks again Riccardo.

**Comment by greglandrum** [comment]
This is, I believe, resolved.
