### ISSUE TITLE
Missing Windows binaries for recent updates

### ISSUE THREAD

**Issue by shangzhi-hong** [rdkit/rdkit#1040]
Is there a guide for building Windows binaries on my own?
I can't find Windows binaries from the 2016.03.2 release to the recent 2016.03.4 release

**Comment by greglandrum** [comment]
https://github.com/rdkit/rdkit/blob/master/Docs/Book/Install.md
is the best that I'm aware of.

**Comment by greglandrum** [comment]
Creating windows binaries is a fair amount of work. I do them for the main releases, but creating them for the patch releases (which are a new thing for the RDKit) isn't something I plan to do.

**Comment by hszest** [comment]
Thanks for the answer!

**Comment by JimSEOW** [comment]
https://github.com/rdkit/rdkit/pull/1152

I have tried the recommended 24 files modifications to make it compatible with VisualStudio2015 (boost 1.59) for the latest [Release_2016_09_1](https://github.com/rdkit/rdkit/releases/tag/Release_2016_09_1) 

It compiles and the tests passed all except 2 (testPgSQL and pythonTestDirChem)

Currently investigating why the two tests failed

**Comment by greglandrum** [comment]
We will certainly do binaries for the 2016_09 release, we just aren't quite there yet (which is why I haven't announced the release yet). It's likely we'll start the binaries with 2016_09_2.

**Comment by liwt31** [comment]
I can't find the binary release for windows for 2018_03_1 (Q1 2018) Release. I understand it'll be a lot of work to build a binary release, but I think it'll be a good idea to rephrase "Windows binaries are available with each release." in README.md file to something more accurate. Maybe something pointing to the lastest available binary?

**Comment by greglandrum** [comment]
@liwt31 you're right, the wording is a big misleading now that we provide binaries for windows, the Mac, and Linux via conda.

**Comment by d-b-w** [comment]
RDKit is now regularly built on Windows.

Please move further questions to the "discussion" tab.
