### ISSUE TITLE
Segfault for atom with no owner

### ISSUE THREAD

**Issue by richlewis42** [rdkit/rdkit#1041]
```python
from rdkit import Chem
a = Chem.Atom(6)
a.GetOwningMol()
```

Gives me a `Segmentation fault: 11` from Anaconda Python 3.5 RDKit from 2016.03.1

I guess it is not that relevant for most applications, but I was hoping for `None` (or similar)!

**Comment by greglandrum** [comment]
Which operating system does this happen on?

**Comment by richlewis42** [comment]
OS X El Capitan (10.11.6), sorry meant to say that.

**Comment by greglandrum** [comment]
Interesting. I wasn't able to reproduce that yesterday, but today I can.
I'll look into it. Thanks.
