### ISSUE TITLE
python2 code in python3 install

### ISSUE THREAD

**Issue by kcamnairb** [rdkit/rdkit#1042]
Hi, I've installed 2016.03.4-np110py35_1 using "conda install -c https://conda.anaconda.org/rdkit rdkit" for Ubuntu. When i run this within python 3: 
`from rdkit import Chem
from rdkit.Chem import Draw
m = Chem.MolFromSmiles('Cn1cnc2c1c(=O)n(c(=O)n2C)C')
Draw.MolToFile(m, '/home/brian/eurotiomycetes_jgi/smi_test.svg')`
I get: 
`AttributeError                            Traceback (most recent call last)
<ipython-input-6-484776a9da10> in <module>()
      2 from rdkit.Chem import Draw
      3 m = Chem.MolFromSmiles('Cn1cnc2c1c(=O)n(c(=O)n2C)C')
----> 4 Draw.MolToFile(m, '/home/brian/eurotiomycetes_jgi/smi_test.svg')

/home/brian/anaconda3/lib/python3.5/site-packages/rdkit/Chem/Draw/**init**.py in MolToFile(mol, fileName, size, kekulize, wedgeBonds, imageType, fitImage, options, **kwargs)
    165     options.radicalSymbol = '.' #<- the sping canvas doesn't support unicode well
    166     canvas = Canvas(size=size,name=fileName,imageType=imageType)
--> 167   drawer = MolDrawing(canvas=canvas,drawingOptions=options)
    168   if kekulize:
    169     from rdkit import Chem

/home/brian/anaconda3/lib/python3.5/site-packages/rdkit/Chem/Draw/MolDrawing.py in **init**(self, canvas, drawingOptions)
     97                                     (0,canvas.size[1])),
     98                                    color=self.drawingOptions.bgColor,
---> 99                                    fill=True,stroke=False)
    100 
    101 

/home/brian/anaconda3/lib/python3.5/site-packages/rdkit/Chem/Draw/spingCanvas.py in addCanvasPolygon(self, ps, color, fill, stroke, **kwargs)
     90     else:
     91       fillColor = color
---> 92     self.canvas.drawPolygon(ps,edgeColor=edgeColor,edgeWidth=int(edgeWidth),fillColor=fillColor,closed=1)
     93 
     94   def addCanvasDashedWedge(self,p1,p2,p3,dash=(2,2),color=(0,0,0),

/home/brian/anaconda3/lib/python3.5/site-packages/rdkit/sping/SVG/pidSVG.py in drawPolygon(self, pointlist, edgeColor, edgeWidth, fillColor, closed, dash, **kwargs)
    346     # draw it
    347     outStr = '<svg:polygon %s %s points="%s">'%(fillStr,edgeStr,pointStr)
--> 348     if kwargs.has_key('bodyText'):
    349       outStr+=kwargs['bodyText']
    350     outStr += '/svg:polygon\n'

AttributeError: 'dict' object has no attribute 'has_key'`
It seems that pidSVG.py has python 2 code in it.

**Comment by greglandrum** [comment]
Though this is certainly a bug, I'd recommend that you use the new drawing code to generate SVGs.
The docs are unfortunately out of date on this one, but you can see examples of how to use it here:
http://rdkit.blogspot.ch/2016/04/changes-in-201603-release-improvements.html
Search for "prepareMol"

**Comment by gedeck** [comment]
Submitted a pull requests for this: #1132 Replace has_key use in Python (#issue1042)

**Comment by gedeck** [comment]
This issue can be closed now.
