### ISSUE TITLE
Importing Composite raises error during initial import

### ISSUE THREAD

**Issue by jo-sm** [rdkit/rdkit#1061]
If you don't have the sqlite module installed in your Python package in Python 3 (the `pyPgSql` module isn't supported in Python 3) an error is raised when importing the `Composite` module from `rdkit.ML.Composite`:

`ImportError: Neither sqlite nor PgSQL support found.`

This is a really strange error because it's due to the side effect of importing `DbModule` a few modules down. This seems like a big, especially if you're not directly using the database functionality of `rdkit`. 

Would it be possible to refactor `DbModule` to be a function that returns an object with the various database configs, e.g. `placeHolder`, and deal with the errors in the respective usages instead? In the mean time I am compiling Python with `sqlite3` but ideally I would not need to because I don't use it in my environment.

**Comment by greglandrum** [comment]
This is definitely fixable.
As a general point: the code in `rdkit.ML.Composite` is pretty dusty. It was quite useful years ago when we wrote it, but with the improvements in scikit-learn I don't think it is really still worth using and is likely to be deprecated at some point in the future.

If you can switch to scikit-learn, it's definitely worth doing so.

**Comment by jo-sm** [comment]
Ah makes sense. The code is our codebase is also a bit older, so I'm not sure the difficulty of switching to `scikit-learn` for this specific case. For the time being I'll compile my Python version with sqlite3 support to keep the error message quiet.
