### ISSUE TITLE
cis-trans configuration ignored by pyAvalonTools.Generate2DCoords

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#1062]
For example, if a molecule is created from CCC/C=C\CCC the configuration of the double bond is ignored by a later call to pyAvalonTools.Generate2DCoords.

It was suggested that this may be due to RDKit passing a mol block as input to the AvalonTools code, and that it could/should instead pass an isomeric smiles.

The change doesn't look complex to implement, and I would be happy to contribute a small patch, but I was wondering if it could have any known side effects on other functions that depend on molToReaccs.

**Comment by bp-kelley** [comment]
Is this an interaction between rdkit<->avalon in this specific regards?  Or is it that avalon ignores stereo info for cis-trans from mol blocks?

I wonder if this will affect Avalon's struchk which would be my larger concern.  I don't know the interface between them.

**Comment by rvianello** [comment]
As far as I understood, the Avalon tools do not take the cix/trans configuration of double bonds into account when generating a 2D layout from a mol block where no chiral centers are at the same time specified. I presume it's not necessarily related to struchk, but we can ask.

**Comment by apahl** [comment]
Are there any news on this issue?

I always use PyAvalon for 2D coordinate generation because in my opinion it gives "nicer" structures and just realized this issue with an example today.

[PyAvalon_E_Z.pdf](https://github.com/rdkit/rdkit/files/1317215/PyAvalon_E_Z.pdf)

Kind regards,  
Axel
