### ISSUE TITLE
Atom/Get*Valence wrapper docstrings

### ISSUE THREAD

**Issue by JLVarjo** [rdkit/rdkit#1088]
In GraphMol/Wrap/Atom.cpp, both GetExplicitValence and GetImplicitValence docstrings state that the functions return the number of explicit/implicit Hs on the atom (which they obviously do not...)

**Comment by greglandrum** [comment]
Good catch. GetExplicitValence() was wrong, but GetImplicitValence() is correct (the implicit valence is equal to the number of implicit Hs).
