### ISSUE TITLE
The RunStruchk function is not exposed in pyAvalonTools

### ISSUE THREAD

**Issue by pulveni1** [rdkit/rdkit#1130]
It seems like the RunStruchk function from AvalonTools.cpp is not exposed in pyAvalonTools.cpp.
The alternative function, checkMol, which is exposed in pyAvalonTools is lacking the possibility to provide a data list object as argument and thus does not return the full validation details of bad structures.

Would it be possible to extend the pyAvalonTools module to also expose the RunStruchk function and passing a data list object to it?

Thanks
Nico

**Comment by greglandrum** [comment]
Shouldn't be a problem to add this. I will take a look

**Comment by bp-kelley** [comment]
I can do this as well if you don't have the time, I'm motivated due to internal needs.

**Comment by greglandrum** [comment]
I'd never argue with a PR. :-)

**Comment by pulveni1** [comment]
Thanks for fixing this
