### ISSUE TITLE
code error in pidSVG.py and pdfmetrics.py for python3.5 ( Draw.MolToFile function)

### ISSUE THREAD

**Issue by Birdlet** [rdkit/rdkit#1144]
I'm using Python 3.5.2 + RDkit 2016.03.4 installed by conda in Ubuntu 14.04 LTS.
When I run these commands:
`from rdkit import Chem`
`from rdkit.Chem import Draw`
`m = Chem.MolFromSmiles('OC1C2C1CC2')`
`Draw.MolToFile(m, "test.svg")`

Some Errors occurred, and I found there are caused by some python2 code in pidSVG.py amd pdfmetrics.py file. I replaced some python2 function and it seems worked ok. 

In pidSVG.py:

1. `xrange`    ->    `range`
2. `if kwargs.has_key(key1)`    ->     `if key1 in kwargs`
3. `if isinstance(font.face,siz.string_types)`  ->    `if isinstance(font.face,six.string_types) `
4. `string.split(str1)`    ->    `str1.split()`

In pdfmetrics.py
1. `string.lower(str2)`    ->     `str2.lower`

I'll attach modfied file here.
[pdfmetrics.py.txt](https://github.com/rdkit/rdkit/files/566656/pdfmetrics.py.txt)
[pidSVG.py.txt](https://github.com/rdkit/rdkit/files/566657/pidSVG.py.txt)

**Comment by greglandrum** [comment]
Thanks for taking the time to report this.
We engaged our time machine and went back a few days to fix the problem. ;-)

Jokes aside: a pull request that was merged a few days ago should have already fixed this. Please do let us know if you have time to look at the current github version of the code and still see problems.

**Comment by gedeck** [comment]
The dictionary issues are resolved, the string module use not. Greg, you can assign the issue to me and I will look through all occurrences of the string module in the code, replace them and make a PR.
