### ISSUE TITLE
Sanitizer rejects higher valency halides

### ISSUE THREAD

**Issue by dan2097** [rdkit/rdkit#115]
Cl(=O)O -->Explicit valence for atom # 0 Cl, 3, is greater than permitted
(http://en.wikipedia.org/wiki/Chlorous_acid)

Cl(=O)(=O)O  --> Explicit valence for atom # 0 Cl, 5, is greater than permitted
(http://en.wikipedia.org/wiki/Chloric_acid)

Cl(=O)(=O)(=O)O --> [O-][Cl+3]([O-])([O-])O
(http://en.wikipedia.org/wiki/Perchloric_acid)
This isn't exactly wrong but also isn't what I personally expected.

However Valency 7 bromine (e.g. perbromic acid) gives a valency error

If the sanitizer is disabled these are read exactly as written.

**Comment by dan2097** [comment]
Greg, I see you've fixed #510. Can this be fixed in the same way?

**Comment by greglandrum** [comment]
Wow, this one slipped through the cracks. Sorry I missed it.
I will take a look over the next couple of days.

**Comment by dan2097** [comment]
What was your conclusion?
Would adding valencies 3,5,7 to chlorine/bromine/iodine (assumdly in atomic_data.cpp) be likely to cause any unexpected consequences?
As well as the compounds I mentioned hypervalent iodine is also important in certain reagents e.g. IBX and the Dess-Martin periodinane

**Comment by greglandrum** [comment]
@dan2097 : I opted for a generic fix that converts chlorous, chloric, and perchloric acids as well as the Br and I equivalents to the zwitterionic form.
There's a bit more info in PR #839 and the associated commits.

**Comment by dan2097** [comment]
If I'm understanding the code correctly the zwitterionic form is adopted if all neighbors are oxygen. What about the situation where one of the bonds is to carbon as in the Dess-Martin periodinane and IBX. Are these still rejected by the sanitizer?

**Comment by greglandrum** [comment]
@dan2097 Iodine already supports valence 5, so the Dess-Martin periodinane and IBX are fine:
```
In [2]: Chem.CanonSmiles('CC(=O)OI1(c2ccccc2C(=O)O1)(OC(=O)C)OC(=O)C')
Out[2]: 'CC(=O)OI1(OC(C)=O)(OC(C)=O)OC(=O)c2ccccc21'
In [3]: Chem.CanonSmiles('O=C1OI(=O)(O)c2ccccc12')
Out[3]: 'O=C1OI(=O)(O)c2ccccc21'

```
