### ISSUE TITLE
Visual Studio 2008 compatibility

### ISSUE THREAD

**Issue by mcs07** [rdkit/rdkit#1163]
Just a heads up, there are a couple of changes in the 2016_09_1b1 release that break compilation with Visual Studio 2008 for me. I know it's a pretty old VS version, but I get the impression that it's strongly recommended to use this version in conjunction with python 2.7. It would be nice to keep support for it at least until support for python 2 is dropped.

First, the use of `# include <stdint.h>` in a few places related to the new reaction enumeration code - this file is not present in VS2008. It's possible to use msinttypes or a manual typedef, but seeing as it's used elsewhere, would it be possible to instead use `#include <boost/cstdint.hpp>` and adjust the namespace of the occurrences to `boost::uint64_t` etc.?

Secondly, there is some problem with the way the FPB reader uses the Ranking code. The error I get is:

    MultiFPBReader.cpp
    C:\projects\rdkit\Code\RDGeneral/Ranking.h(30) : error C2143: syntax error : missing ',' before '<'
            C:\projects\rdkit\Code\RDGeneral/Ranking.h(35) : see reference to class template instantiation 'Rankers::pairGreater<T1,T2>' being compiled
    C:\projects\rdkit\Code\RDGeneral/Ranking.h(41) : error C2143: syntax error : missing ',' before '<'
            C:\projects\rdkit\Code\RDGeneral/Ranking.h(46) : see reference to class template instantiation 'Rankers::pairLess<T1,T2>' being compiled
    C:\projects\rdkit\Code\RDGeneral/Ranking.h(49) : error C2143: syntax error : missing ',' before '<'
            C:\projects\rdkit\Code\RDGeneral/Ranking.h(56) : see reference to class template instantiation 'Rankers::argless<T>' being compiled

**Comment by greglandrum** [comment]
Thanks for bring this up Matt. As painful as it may be, it is indeed important to (at least try and) maintain support for VS2008 because of the python2.7 issue.
I'll pull the handbrake on the release and fix at least the stdint problem.

The second one is more difficult since I'm not quite sure where the problem is, but I will try to get that one cleared up.
