### ISSUE TITLE
wrong version numbering in the current master CMakeLists.txt

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#1191]
the cmake configuration files on the current master label the code as version 2016.09.1 

https://github.com/rdkit/rdkit/blob/master/CMakeLists.txt#L73

but (assuming that the 2016.09 series are located on a separate release branch) it should be something like 2017.03.1.dev1 ?

**Comment by greglandrum** [comment]
Thanks!

**Comment by rvianello** [comment]
Thank you @greglandrum
