### ISSUE TITLE
instability of pyAvalonTools.InitCheckMol

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#1196]
The struchk initialization function in the C++ bindings to the AvalonTools package

`  int initCheckMol(const std::string &optString) {
    return InitCheckMol((char *) optString.c_str());
  }`

receives the options string as a `const std::string &` and casts the result of `optString.c_str()` to `(char *)` before passing it to the C implementation.

A comment in the AvalonTools code (also present in version 1.2.0 from sourceforge) includes the following warning:

`Note: The opt string is modified and used to provide storage for '\0' terminated strings
collected as 'argument' strings.`

I suspect the current C++ `initCheckMol` implementation could be therefore responsible for some of the instabilities related to this struchk initialization step and that it should be therefore modified to forward a copy of the options string.

**Comment by bp-kelley** [comment]
I saw these emails floating by, could you provide a test case that shows the issue?

**Comment by bp-kelley** [comment]
It looks like the fix should be:

```
  int initCheckMol(const std::string &optString) {
    std::string optCopy(optString);
    return InitCheckMol((char *) optCopy.c_str());
  }
```
or perhaps without casting away const:

```
  int initCheckMol(const std::string &optString) {
    char *optBuffer = new char[optString.size()+1];
    optString.copy(optBuffer, optString.size());
    optBuffer[optString.size()] = '\0';
    int res = InitCheckMol(optBuffer);
    delete [] optBuffer;
    return res;
  }
```

Could you try this with your test?

**Comment by rvianello** [comment]
Like other bugs that include writing things at random into someone else's dynamically allocated memory, the problem is not strictly reproducible, so I don't know if a specific test-case would make sense, the code fails at performing a basic init operation. If pyAvalonTools.InitCheckMol is passed an ill-formed random string, you may get a successful return value (that would be unexpected), garbage error messages and more rarely a segmentation fault terminating the interpreter.

**Comment by bp-kelley** [comment]
Time to run valgrind :)

**Comment by bp-kelley** [comment]
@rvianello I think I resolved this issue.  Could you verify?  It's been a while.

**Comment by rvianello** [comment]
@bp-kelley apologies, I lost track of this issue on github. yes, I think it's resolved, thanks again for your help with this.
