### ISSUE TITLE
Support valences of 4 and 6 for Te

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/rdkit#1204]
I have some SMILES from ZINC database, but it seems that some of them are invalid or RDKit is unable to parse (read + canonicalize) them. I collect them in this [file](https://gist.github.com/hsiaoyi0504/d13c5f880cf769f8495360827dfca6dc). Additionally, I have tried to submit these SMILES to [PubChem Standardization Service](https://pubchem.ncbi.nlm.nih.gov/standardize/standardize.cgi). Only `CC12O[Te]34OC(C)(C1(C)O3)C2(C)O4` can be standardized (but RDKit can't do this).

**Comment by greglandrum** [comment]
@hsiaoyi0504 all of those molecules have chemistry problems (i.e. invalid valence states on main-group elements). What do you expect to happen with them?

There's documentation out there on the web about why these are rejected by the RDKit and how to process them anyway. Does that not help you?

**Comment by jir322** [comment]
None of those in your file (Te, Al, ...) will be in ZINC. Just wanted to
make that clear.

**Comment by hsiaoyi0504** [comment]
@jir322 Sorry, I finally found it should be from chembl22

**Comment by hsiaoyi0504** [comment]
@greglandrum Yes, when I parse all of them through RDKit, they all report that there are invalid valence states, but is it really an invalid valence state in `CC12O[Te]34OC(C)(C1(C)O3)C2(C)O4`? I found that when I use this as a query searching against PubChem, I will find this [record](https://pubchem.ncbi.nlm.nih.gov/compound/358627)

**Comment by jir322** [comment]
Thanks. I am hono(u)red to be confused with ChEMBL.

On Dec 15, 2016 7:16 AM, "hsiao yi" <notifications@github.com> wrote:

@jir322 <https://github.com/jir322> Sorry, I finally found it should be
from chembl22

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/rdkit/rdkit/issues/1204#issuecomment-267352333>, or mute
the thread

**Comment by hsiaoyi0504** [comment]
@jir322 Ha, you deserve it. It's also an interesting project [here](https://github.com/maxhodak/keras-molecules) called keras-molecules trying to reproduce result from one of deep learning paper [here](https://arxiv.org/abs/1610.02415). It uses the datasets from ZINC and ChEMBL.

**Comment by greglandrum** [comment]
Pubchem is a great public resource, but it's not necessarily the best source to cite for to indicate that something is reasonable chemistry. :-)
I can add acceptable valences of 4 and 6 to Te in order to make it analogous to Se and S.

**Comment by hsiaoyi0504** [comment]
@greglandrum  Thanks, I think I didn't clearly point out my point. I think the valence of Te here is acceptable. I also now testing the functionality of reading SMILES from ZINC. Maybe will add more things to current list later.

**Comment by hsiaoyi0504** [comment]
I update the list [here](https://gist.github.com/hsiaoyi0504/d13c5f880cf769f8495360827dfca6dc).
More examples from ZINC database are added. All of them are due to N valence of  4 and 5.

**Comment by greglandrum** [comment]
Those structures are chemically wrong. What exactly do you expect the RDKit to do with them?

**Comment by hsiaoyi0504** [comment]
@greglandrum I know they are chemical wrong, but is it possible to correct them? In my opinion, correct some cases is possible. For instance, if I input CC(=O)Nc1ccc(cc1)S(=O)(=O)N=N=N to pubchem standardization service, I will get CC(=O)NC1=CC=C(C=C1)S(=O)(=O)N=[N+]=N. Thus, I think it is possible to do that.

**Comment by greglandrum** [comment]
The RDKit generally does not "guess" about these things unless it's really clear what the user intended and the incorrect form is a more or less standard one. I don't think either of those conditions applies here. This is one where, if you care about correctness, a human being needs to look at what's intended and fix the input. If you don't care about correctness, it's easy to write some RDKit code that reads a molecule in without sanitizing it and adds a charge to neutral four-valent nitrogens.

The pubchem solution, as you present, it actually changes the overall charge on the molecule. I'm pretty sure that's not correct.

**Comment by hsiaoyi0504** [comment]
OK, I got your point, but I really thought it is good for a software to notify user checking or modifying the input data. How about adding some suggestion for some cases? In most case here, it occurs for `N=N=N`, which is a common error for not showing the charge of the N in the middle. These errors are common even in Chemistry textbook. Also, advanced features for guessing this could be possible.
