### ISSUE TITLE
all-atom RMSD used to prune conformers in embedding code, docs say heavy-atom RMSD is used

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1227]
reported by JW Feng, here's the thread: http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg06404.html

The docs say one thing, the code does another. One is wrong and should be fixed; either way the fix is not hard.

I believe that the right thing to do is calculate heavy-atom RMSD instead of all-atom RMSD, but this will change the results that are generated by the code, so I'm going to leave this open for a bit to see if any discussion pops up.

**Comment by jw-feng** [comment]
Hi Greg,

I tested version 2017.03.1 and generated conformers are identical to 2016.09.2.  I verified that I am running 2017.03.1.  I try setting onlyHeavyAtomsForRMS=True as a parameter for AllChem.EmbedMultipleConfs() but that resulted in signature mismatch error?  Attached is my python script and test case.  Will you please take a look? 

Thanks,

JW

[conf_test.zip](https://github.com/rdkit/rdkit/files/954009/conf_test.zip)

**Comment by greglandrum** [comment]
Hi JW,
Rather than further increase the number of optional arguments to that function, the new capability is only exposed through the `EmbedParameters` object.

Here's a minor change to your file that should do what you want:
```
        mol = Chem.AddHs(mol)
        #EmbedMultipleConfs((Mol) mol[, (int) numConfs = 10[, (int) maxAttempts = 0[, (int) randomSeed = -1[, (bool)
        #  clearConfs = True[, (bool) useRandomCoords = False[, (float) boxSizeMult = 2.0[, (bool) randNegEig = True[, (int)
        #  numZeroFail = 1[, (float) pruneRmsThresh = -1.0[, (dict) coordMap = {}[, (float) forceTol = 0.001[, (bool)
        #  ignoreSmoothingFailures = False[, (bool) enforceChirality = True[, (int) numThreads = 1[, (bool)
        #  useExpTorsionAnglePrefs = False[, (bool) useBasicKnowledge = False[, (bool) printExpTorsionAngles = False
        # ]]]]]]]]]]]]]]]]]) -> _vecti:
        params = AllChem.ETKDG()
        # params.onlyHeavyAtomsForRMS=True <- This isn't necessary because it's the default
        params.pruneRmsThresh = args.prune_rmsd
        params.randomSeed = 1
        conf_ids = AllChem.EmbedMultipleConfs(mol, args.confs, params)
        #conf_ids = AllChem.EmbedMultipleConfs(mol, args.confs, AllChem.ETKDG())
```

**Comment by jw-feng** [comment]
Thanks for the clarification.  Works as expected now.

**Comment by greglandrum** [comment]
Great; glad to hear it!
