### ISSUE TITLE
SMILES with positively charged carbon not round trip-able through SDF

### ISSUE THREAD

**Issue by coleb** [rdkit/rdkit#1229]
```
smi='O=[C+]1=NC=Nc2[nH]nc(Br)c21'
mol=Chem.MolFromSmiles(smi, sanitize=True)
assert mol is not None
sdf=Chem.MolToMolBlock(mol)
m2=Chem.MolFromMolBlock(sdf)
assert m2 is not None
```

MolFromMolBlock throws this warning: 

```
RDKit ERROR: [09:59:39] Explicit valence for atom # 1 C greater than permitted
```

Which isn't entirely correct since the carbon is properly marked positively charged in the SDF file with this line: 

```
M  CHG  1   2   1
```

**Comment by d-b-w** [comment]
Thanks for the report! This has been addressed at some point. Testing in 2024.09pre shows:

<img width="535" alt="Screenshot 2024-09-15 at 9 50 28 AM" src="https://github.com/user-attachments/assets/2d6024b6-d57a-463a-84a3-a64cc0b40787">
