### ISSUE TITLE
SMARTS failing to compile

### ISSUE THREAD

**Issue by eloyfelix** [rdkit/rdkit#1260]
Hi,

I tested it in rdkit '2016.03.4' and in current status master branch.

I'm implementing QED(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3524573/) using RDKit.

There is one step in which you need to calculate structure alerts. They provide a list of SMARTS. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3524573/bin/NIHMS50746-supplement-UnwantedGroups.sma

There is one of them that is not compiling.

`smarts = '(C(=O)O[C,H1]).(C(=O)O[C,H1]).(C(=O)O[C,H1])'`
`patt = Chem.MolFromSmarts(smarts)`
`SMARTS Parse Error: syntax error for input: '(C(=O)O[C,H1]).(C(=O)O[C,H1]).(C(=O)O[C,H1])'`

Do you have any clue why is this happening?

Thanks.

**Comment by gedeck** [comment]
Hello Felix,

You might like to try this SMARTS:

smarts = 'C(=O)O[C,H1].C(=O)O[C,H1].C(=O)O[C,H1]'
patt = Chem.MolFromSmarts(smarts)

This will work.

There is actually a RDkit implementation of QED:
http://silicos-it.be.s3-website-eu-west-1.amazonaws.com/software/biscu-it/qed/1.0.1/qed.html

Best,

Peter

**Comment by eloyfelix** [comment]
Hi Peter,

But according to this http://daylight.com/dayhtml_tutorials/languages/smarts/index.html (6. Component-Level Grouping ) is not exactly the same. Isn't it?

Thank you, I'll check silicos-it implementation.

**Comment by gedeck** [comment]
For the QED implementation, the SMARTS without component level grouping should be fine. I suggest you close this issue and open a new one about the missing support of component-level grouping with reference to the Daylight tutorial.

**Comment by eloyfelix** [comment]
Ok, thanks!
