### ISSUE TITLE
PMI descriptors incorrect

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1262]
Reported by Chris Earnshaw here: http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg06433.html
This is a really stupid one, but the method being used is just wrong.

**Comment by bp-kelley** [comment]
I think we can close this one now :)

**Comment by greglandrum** [comment]
Yep. I forgot to include the relevant commit comment in #1265
