### ISSUE TITLE
Reactions don't modify isotope unless chemical element is specified for the product

### ISSUE THREAD

**Issue by i-tub** [rdkit/rdkit#1266]
Let's say I want to use a reaction to change atoms with isotope 13 to isotope 14, regardless of the chemical element. I would expect the reaction SMARTS `'[13:1]>>[14:1]'` to do the trick. Or maybe `'[13*:1]>>[14*:1]'`. But as shown below, it doesn't, even though the reaction matches and yields a product. If I specify the element on the product side of the reaction SMARTS, as in `'[13:1]>>[14C:1]'`, I do get a product with the desired isotope.

```
>>> from rdkit import Chem
>>> from rdkit.Chem import AllChem
>>> mol = Chem.MolFromSmiles('C[13CH2]C')
>>> Chem.MolToSmiles(mol, isomericSmiles=True)
'C[13CH2]C'
>>> rxn = AllChem.ReactionFromSmarts('[13:1]>>[14:1]')
>>> prod = rxn.RunReactants([mol])[0][0]
>>> Chem.MolToSmiles(prod, isomericSmiles=True)
'C[13CH2]C'
>>> rxn2 = AllChem.ReactionFromSmarts('[13:1]>>[14C:1]')
>>> prod2 = rxn2.RunReactants([mol])[0][0]
>>> Chem.MolToSmiles(prod2, isomericSmiles=True)
'C[14CH2]C'
```

Why would I know which isotope I want to change and yet not know the chemical element of the atom? Admittedly, this was part of a hack where I tried using the isotope as an atom label of sorts (similar to what ReplaceCore() does).

**Comment by greglandrum** [comment]
After a quick look through the code, I believe that this should work, so I think this is a bug.
It certainly works ok with charge:
```
>>> rxn = AllChem.ReactionFromSmarts('[+1:1]>>[+2:1]')
>>> Chem.MolToSmiles(rxn.RunReactants((Chem.MolFromSmiles('CC[NH3+]'),))[0][0])
'CC[NH3+2]'
```

**Comment by i-tub** [comment]
Thank you for looking into this so quickly!
