### ISSUE TITLE
RDKit gets stuck on PubChem CID 102128817 

### ISSUE THREAD

**Issue by TuomoKalliokoski** [rdkit/rdkit#1281]
RDKit fails to parse PubChem CID 102128817. It gets stuck and starts eating up RAM until is killed by the kernel.

The issue occurs both when creating Mol-object from SMILES and SDF. 
To reproduce the bug in SMILES:

```
from rdkit import Chem
mol = Chem.MolFromSmiles("COC1=CC=C(C=C1)C2C3=C(C=CC4=CC=CC=C43)OC5=CC6=C(C=C5)C7=NC8=C9C=CC1=CC9=C(N8)N=C3C4=C5C=CC(=C4)OC4=C(C(C8=C(C=CC9=CC=CC=C98)OC8=CC9=C(C=C8)C8=NC9=NC9=C%10C=C(C=CC%10=C(N9)N=C9C%10=C(C=C(C=C%10)OC%10=C2C2=CC=CC=C2C=C%10)C(=N9)NC2=NC(=N8)C8=C2C=C(C=C8)OC2=C(C(C8=C(C=CC9=CC=CC=C98)OC8=CC9=C(C=C8)C(=NC5=N3)N=C9NC6=N7)C3=CC=C(C=C3)OC)C3=CC=CC=C3C=C2)OC2=C(C(C3=C(O1)C=CC1=CC=CC=C13)C1=CC=C(C=C1)OC)C1=CC=CC=C1C=C2)C1=CC=C(C=C1)OC)C1=CC=CC=C1C=C4")
```

I have attached the problematic SDF as well:
[rdkit_bug.zip](https://github.com/rdkit/rdkit/files/741206/rdkit_bug.zip)

We are running CentOS Linux release 7.3.1611 (Core) (x86_64) and RDKit is installed from RPMs contributed by Gianluca Sforna, python version is 2.7.5:

  python2-rdkit-2016.03.1-1.el7.centos.x86_64
  rdkit-2016.03.1-1.el7.centos.x86_64

**Comment by tentrillion** [comment]
I confirm the problem using python 2.7.13, rdkit 2016.09.02, macOS Sierra 10.10.2.

The problem is related to a ring with index 8 and or 9; removing either all rings with index 8 or all rings with index 9 solves the problem.
```
from rdkit import Chem
import re

smiles = '''
COC1=CC=C(C=C1)C2C3=C(C=CC4=CC=CC=C43)OC5=CC6=C(C=C5)C7=NC8=C9C=CC1=CC9=C(N8)
N=C3C4=C5C=CC(=C4)OC4=C(C(C8=C(C=CC9=CC=CC=C98)OC8=CC9=C(C=C8)C8=NC9=NC9=C%10
C=C(C=CC%10=C(N9)N=C9C%10=C(C=C(C=C%10)OC%10=C2C2=CC=CC=C2C=C%10)C(=N9)NC2=NC
(=N8)C8=C2C=C(C=C8)OC2=C(C(C8=C(C=CC9=CC=CC=C98)OC8=CC9=C(C=C8)C(=NC5=N3)N=C9
NC6=N7)C3=CC=C(C=C3)OC)C3=CC=CC=C3C=C2)OC2=C(C(C3=C(O1)C=CC1=CC=CC=C13)C1=CC=C
(C=C1)OC)C1=CC=CC=C1C=C2)C1=CC=C(C=C1)OC)C1=CC=CC=C1C=C4
'''.replace('\n', '')

# works
no8 = re.sub('[8]{1,2}', '', smiles)
Chem.MolFromSmiles(no8)

# works
no9 = re.sub('[9]{1,2}', '', smiles)
Chem.MolFromSmiles(no9)

# fails
Chem.MolFromSmiles(smiles)
```

**Comment by greglandrum** [comment]
Confirmed. Thanks for the report

**Comment by greglandrum** [comment]
This molecule is one of those demonstrations of why finding the symmetric smallest rings can be a bad idea. There's a discussion here:
https://github.com/rdkit/UGM_2016/blob/master/Presentations/Flachsenberg_RingDecomposerLib.pdf
It's not really fixable with the current ring-finding code but should be addressed if/when I finish integrating the new code.

**Comment by exaexa** [comment]
Hello,
I've hit this today while going scanning through pubchem. Is there some kind of existing fix or a workaround? (I'll probably try patching it myself otherwise.)
Thanks!

**Comment by greglandrum** [comment]
@exaexa The real solution to this (replacing the ring finding algorithm) has proven to be more difficult to integrate than I had hoped.
What we'll try instead for the next release is a change to the code so that it fails for this molecule (and others like it) in a reasonable amount of time instead of running for a very long time and probably exhausting the memory available on your machine.
