### ISSUE TITLE
Rdkit java wrapper availability

### ISSUE THREAD

**Issue by mayankBIL** [rdkit/rdkit#1283]
Hi there, 
I just wanted to know the location from where I can download java wrapper for Rdkit (Rdkit.jar) for latest version of rdkit. I tried to build it using SWIG but getting several problems. Please help!

**Comment by greglandrum** [comment]
At the moment, the best place to get the wrappers is from the github repo for the KNIME nodes.
The jar file is here: https://github.com/rdkit/knime-rdkit/tree/master/org.rdkit.knime.types/lib
and the binaries that you will also need are in the appropriate .bin subdirectory here: https://github.com/rdkit/knime-rdkit
For example, the 64bit windows binaries are: https://github.com/rdkit/knime-rdkit/tree/master/org.rdkit.knime.bin.win32.x86_64/os/win32/x86_64
You will need all of the files in one of those binary directories.

This probably isn't the best approach for this and if you have other suggestions, please let me know.

**Comment by JimSEOW** [comment]
Are there interest to consider using e.g. JavaCPP to build[ Java Bindings to Rdkit C/C++ Libraries](http://bytedeco.org/)?

Likewise, perhaps it may be of interest to use [CppSharp ](https://github.com/mono/CppSharp)instead of SWIG to create .NET binding to Rdkit C/C++ Libraries.

=> For a concrete example of how to create a .NET wrapper using CppSharp that does not requires regular manual update to catch up with the latest c++ code change, please take a look on UrhoSharp wrapper using CppSharp from Urho3D c++ libraries.

**Comment by greglandrum** [comment]
These are interesting technologies, but (I assume) cannot be replacements to the current SWIG wrappers since they would require all downstream code to be rewritten.

**Comment by mayankRaghav** [comment]
Hey, big thanks greglandrum. Right now I don't have any good suggestion, but will post it if I find something interesting and useful.

**Comment by mayankBIL** [comment]
Hi Greglandrum, I tried with jar and libraries mention above and got the this exception(details below). Looks like something is broken in java wrapper:

**Code:**
`public class Test1 {
	public static void main(String[] args) throws IOException {
             System.loadLibrary("GraphMolWrap");
             ROMol mol; Atom a; String smi;
             smi = "COc1cc(cc(OC)c1O)c3[o+]c2cc(O)cc(O)c2cc3O";
	     mol = RWMol.MolFromSmiles(smi);			    
             String svg = mol.ToSVG(10,100);			
             System.out.println(svg);
`
**Error:**
`Exception in thread "main" org.RDKit.ConformerException
	at org.RDKit.RDKFuncsJNI.ROMol_ToSVG__SWIG_3(Native Method)
	at org.RDKit.ROMol.ToSVG(ROMol.java:901)
	at com.test.Test1.main(Test1.java:36)`

Please help!

**Comment by greglandrum** [comment]
Molecules generated from SMILES have no coordinates.
You need to generate 2D coordinates first by calling `mol.compute2DCoords();`

**Comment by mayankBIL** [comment]
Great it worked. Thanks. I was also looking for the molecules information (rdkit Descriptors) such as MolWt, NumAliphaticHeterocycles, Kappa1,Chi1 and other available info.  Can you please help me to figureout(or guide to a tutorial) how can I get this molecular info using this Java wrappers.

**Comment by greglandrum** [comment]
there isn't currently a tutorial.
Your best bet is to look at the source for the KNIME nodes.
Though this can be a bit complex due to the extra code for dealing with KNIME, there's a fair amount of RDKit code there.
For example, the descriptors are all defined here:
https://github.com/rdkit/knime-rdkit/blob/master/org.rdkit.knime.nodes/src/org/rdkit/knime/nodes/descriptorcalculation/Descriptor.java

**Comment by mayankBIL** [comment]
Thanks a lot. will look into this link and try.

**Comment by mayankBIL** [comment]
Hey Greglandrum, Looks like KNIME is GPLv3 (as per link : https://tech.knime.org/community/rdkit). Is there any open source solution available for same functionality?

**Comment by greglandrum** [comment]
I don't understand the question. GPLv3 is certainly an open-source license.

**Comment by mayankBIL** [comment]
As per my understanding, GPLv3 is open-source untill used for commercial purposes(correct me if I am wrong). We have a small application but it is commercial one. For now we are  bound to use only open-source free softwares.

**Comment by greglandrum** [comment]
This isn't a good discussion for the RDKit bug tracker, but you can read more on open-source licenses here: https://opensource.org/licenses

The important question for here is: do you want to use the RDKit in your commercial application or KNIME itself?

**Comment by mayankBIL** [comment]
I want to use RDKit only but since it doesn't have descriptors API for molecules(as java wrapper), I thought of using KNIME and then came across license issue. I will look for some solution. Thanks for all your help!

**Comment by greglandrum** [comment]
You can certainly calculate RDKit descriptors from Java. That's why I pointed you to the KNIME code above: that shows how to do it.

**Comment by phidias51** [comment]
It would be nice if the RDKit jars were available either through bintray or mvnrepository, since these are usually the first place that Java developers will look for the library.

**Comment by greglandrum** [comment]
Yep, but since I'm not a java developer I don't know how to work with those systems.
If someone can provide a PR with instructions for how to submit binaries in an automated way, I would be very happy to try it out.

**Comment by phidias51** [comment]
What build system are you using? Gradle or Maven? If you let me know I can track down the instructions for publishing to them.

**Comment by greglandrum** [comment]
None of the above. The RDKit is a C++ project where we just happen to generate artifacts for Java. We use cmake as a build system and this creates the .jar files (and shared libraries) that we use.

**Comment by contrebandeco** [comment]
Are you aware if SWIG can be configure to output jars with the source, documentation and platform-specific binaries ?[ I'm not even able to use the generated/compiled code from the "official" java projects here](https://github.com/rdkit/rdkit/issues/3555).

**Comment by d-b-w** [comment]
Please move further questions to the "discussion" tab.
