### ISSUE TITLE
no ECFP6 implementation in rdkit?

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1295]
There is one in cdk: https://github.com/cdk/cdk/blob/master/descriptor/fingerprint/src/main/java/org/openscience/cdk/fingerprint/CircularFingerprinter.java

That would make me quite sad.

**Comment by gedeck** [comment]
No need to get sad about this. RDkit has you covered:
 http://www.rdkit.org/docs/GettingStartedInPython.html#morgan-fingerprints-circular-fingerprints

**Comment by UnixJunkie** [comment]
cool, thanks a lot for the Python sample code!
