### ISSUE TITLE
what's the best way to feed molecules to rdkit?

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1296]
I mean: what's the preferred way to read molecules?

What the best supported file format?
I suspect is it sdf, from previous interactions with some rdkit people.

But what should have produced those sdf file? Which software?
Which version of the software?
I prefer open source software, if possible.

I'd like all my molecules to be read in correctly ...

PS: I asked to join the rdkit-discuss ML but I'm still not in there

**Comment by greglandrum** [comment]
I'd suggest starting with the documentation: http://rdkit.org/docs/GettingStartedInPython.html
SMILES or SDF should be fine.

Re: the mailing list
Did you subscribe here? https://lists.sourceforge.net/lists/listinfo/rdkit-discuss

**Comment by UnixJunkie** [comment]
Yes, I subscribed there. Thanks for the info.
