### ISSUE TITLE
How to add the unset 3 fields in bond block in SDF?

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/rdkit#1310]
As title, I found that RDKit outputs SDF and lefts 3 fields blank in the bond block. However, in some conditions, this will cause error. For example, if you use [Mold2](http://www.fda.gov/scienceresearch/bioinformaticstools/mold2/ucm143513.htm) from FDA, the program will raise a error. Is it possible to do that in RDKit or I should hard-code this?

**Comment by greglandrum** [comment]
The document describing the CTAB format is quite clear that those fields only need to be in the file when they have non-zero values. This helps keep the size of the files down a bit and, IMO, makes them easier for a human to read. We've actually talked about making the RDKit more aggressive in terms of when it leaves things blank.

If this causes problems for other software, it should be regarded as a bug in that software, not an RDKit problem. In cases where the other program is particularly widely used or important, it is worth thinking about adding a compatibility option to the RDKit, but I don't think that's the case here.

Your best bet is probably to try and report the bug to the authors of the other software and to hand code it in the meantime.

**Comment by hsiaoyi0504** [comment]
OK, thanks for helping this. I agree with you that it's Mold2's problem. However, it seems that Mold2 is not actively maintained (based on my previous experiences), and in my opinion, I really appreciate what RDKit done before, but I think adding this feature make RDKit greater. Under the circumstance that you want to build pipelines based some outdated or not well maintained, it's more convenient to handle this in a cheminformatic toolbox. It's sad that Mold2 is not a open source software and I only can report this to them and wait them. At the same time, maybe I should try to fix this through extra codes written by my hand. Thank you again.
