### ISSUE TITLE
RemoveStereochemistry after mol fragmentation

### ISSUE THREAD

**Issue by JLVarjo** [rdkit/rdkit#1324]
Would it be feasible to force RemoveStereochemistry (maybe re-assign as well?) for mol outputs of all molecule-fragmenting functions? Otherwise, the bonds retain their stereo information vs. the atom indices of the original molecule, which may cause subsequent issues. I got into problems when making fragment with Chem.PathToSubmol and later attempting Chem.MolToInchi for this fragment, which tried to call GetBondBetweenAtoms for non-existing indices.

**Comment by proteneer** [comment]
Does this include simple things like RemoveBond and RemoveAtom? Often times fragmentation/addition is done in batch mode: make a bunch of transformations all at once, then worry about sanitization. Forcing it on each modification can be unnecessarily expensive.

**Comment by JLVarjo** [comment]
After I posted this, I found #890, and see the point therein. However, SanitizeMol doesn't help here since it doesn't remove the stereo info.

**Comment by proteneer** [comment]
Correct - you need to reassign stereochemistry with forceIt = true

**Comment by JLVarjo** [comment]
Following the consensus in #890, I agree that this might not need any fix after all, but I would suggest it to be documented in the "list of things to do after modifying molecules". At least for me it was quite difficult (had to use debugger) to figure out the actual reason.
