### ISSUE TITLE
SMARTS for FP Bits?

### ISSUE THREAD

**Issue by spadavec** [rdkit/rdkit#1334]
Is there a way to understand what SMARTS patterns are being used for a given bit in a circular/morgan FP? I've seen some explanations about how to extract which atoms were hit via why FPbit by using bitInfo dictionaries, but there doesn't seem to be any easy to to know which patterns represent each bit. Is there a way to do this?

**Comment by greglandrum** [comment]
http://www.rdkit.org/docs/GettingStartedInPython.html#explaining-bits-from-morgan-fingerprints
Does this not do what you want?

**Comment by spadavec** [comment]
As far as I understand, that is a process that can only be done in retrospect at an atom level. The code will retrieve atoms in a given molecule that match a given pattern, but not what the actual pattern is. 

What I was hoping for was some kind of SMARTS-like pattern that was assosciated with each bit position in the FP; essentially, I would like to be able to, for a given FP bit index, retrieve a SMARTS pattern that I can use to find other compounds with that substructure (a bit convoluted, I understand).

**Comment by greglandrum** [comment]
Ah, I think I get it. That's not the way those fingerprints work.
The fingerprinting algorithm enumerates all the atomic environments and hashes each of them to come up with a bit id. The only way back from ID -> atom environment is using the approach described in the documentation.

I believe that the best way to do the search you want to do is to just generate and store the fingerprints for all the molecules you would want to search and then just check to see if they have the bit(s) set that you care about.

**Comment by spadavec** [comment]
Ah, gotcha. Much appreciated.
