### ISSUE TITLE
RunReactants not producing expected result

### ISSUE THREAD

**Issue by kovasap** [rdkit/rdkit#1337]
I am trying to understand why the following reaction smiles string does not generate any products:

![yne_rxn](https://cloud.githubusercontent.com/assets/8763010/23383118/c06bc642-fcf9-11e6-9a8a-9e324091d730.png)

    from rdkit import Chem
    from rdkit.Chem import AllChem
    
    rxn_s = '[H][O:4][C:3](=[O:2])[C:7]#[C:6][*:5]>>[H][C:7]([H])([H])[C:6](=[O:1])[*:5]'
    rxn = AllChem.ReactionFromSmarts(rxn_s)
    c = Chem.MolFromSmiles('[H][O:3][C:2](=[O:1])[C:4]#[C:5][C:6](=[O:7])[O:8][H]')
    print(rxn.RunReactants([c]))

Any ideas?

**Comment by tentrillion** [comment]
When molecules are read by default using `Chem.MolFromSmiles()` , extraneous `[H]` atoms are removed during sanitization, which is on by default for molecules created from `MolFromSmiles()`.  

SMILES, SMARTS, and rdkit all really are designed to avoid specifying hydrogen atoms except when you really need to.  

Here's an example:
```
rxn_s = '[H][O:1][C:2]>>[O:1]=[C:2]'
rxn = AllChem.ReactionFromSmarts(rxn_s)

rxn_no_h_s = '[O:1][C:2]>>[O:1]=[C:2]' 
rxn_no_h = AllChem.ReactionFromSmarts(rxn_no_h_s)

meoh_1 = Chem.MolFromSmiles('CO')
meoh_2 = Chem.MolFromSmiles('[H]OC')
meoh_3 = Chem.MolFromSmiles('[H]OC', sanitize=False)
print(Chem.MolToSmiles(meoh_1))
print(Chem.MolToSmiles(meoh_2))
print(Chem.MolToSmiles(meoh_3))


print(rxn.RunReactants((meoh_1, )))
print(rxn.RunReactants((meoh_2, )))
print(rxn.RunReactants((meoh_3, )))

print(rxn_no_h.RunReactants((meoh_1, )))
print(rxn_no_h.RunReactants((meoh_2, )))
print(rxn_no_h.RunReactants((meoh_3, )))
```

**Comment by kovasap** [comment]
Right, I forgot!  Thanks.  This helped me clear up some other related issues too.  It looks like an '[H+:1]' SMARTs string does not match a '[H+:1]' SMILES string when both are made into mols...

**Comment by tentrillion** [comment]
I think that there may in fact be a bug of how rdkit's SMARTS parser handles `[H]`.  According to most SMARTS documentation I can find online, `H` has multiple meanings in SMARTS.  It can sometimes mean a specifier for a heavy atom (`[OH]` means an oxygen atom with at least one attached hydrogen), and sometimes mean a specific H atom (`[H]` is supposed to mean an explicit hydrogen atom).  However, rdkit doesn't treat it that way; instead always interpreting `[H]` in **SMARTS** queries but not SMILES queries as a heavy atom specifier.

**Comment by bp-kelley** [comment]
Note that

AllChem.SanitizeRxn(rxn)

fixes a bunch of issues like this.  In this case, it calls MergeQueryHs on
the reactants.  This changes any explicit H into a query H as long as the
hydrogen isn't explicitly mapped in the reaction.  Note that in this case,
it will fail on the unsanitized molecule with an RDKit exception:

  getNumImplicitHs() called without preceding call to calcImplicitValence()

But I think that is a small price to pay.

It mostly does nothing else for smarts reactions, but it is a godsend for
the various forms and abuses of rxn blocks, but you can call it explicitly
like SanitizeMol

SanitizeRxn(rxn, SanitizeFlags.SANITIZE_MERGEHS)

Cheers,
 Brian

**Comment by bp-kelley** [comment]
Smiles and Smarts treat hydrogens very similarly in the RDKit, [H] always
means explicit:

>>> Chem.MolFromSmiles("[H]").HasSubstructMatch(Chem.MolFromSmarts("[H]"))

True

>>> Chem.MolFromSmiles("[OH]").HasSubstructMatch(Chem.MolFromSmarts("[H]"))

False

>>> Chem.MolFromSmiles("[OH]").HasSubstructMatch(Chem.MolFromSmarts("[OH]"))

True

**Comment by tentrillion** [comment]
Thanks @bp-kelley!  I didn't know about AllChem.SanitizeRxn() and will likely be using it in the future.

The possible bug is actually related to `[H+]` in SMARTS reactions.  Rdkit currently interprets this as a dummy atom with one attached hydrogen and a charge of +1, necessitating use of `[#1+]`  to represent a proton in Smarts.  Pages like http://www.daylight.com/meetings/summerschool02/course/basics/smarts_talk/index.html make it seem like `[H+]`should be an OK way to specify a proton, but since they aren't authoritative or exhaustive about what really counts as "official" SMARTS, I guess I could be wrong.

**Comment by bp-kelley** [comment]
@kovasap, SanitizeRxn has some other goodies as well as it allows applying
the QueryAdjustParams to a reaction as well.  This allows only allowing
RGroups (*) to match and have the rest be set to be fully valent and the
like.

If this seems interesting, I can send you some details.

@tentrillion, As you can see, single [H]'s aren't removed as there is
nothing to merge them with, so I was cheating here.  However, mols that
come from SDF files will have explicit hydrogens.



Cheers,
 Brian

**Comment by bp-kelley** [comment]
>>> q = Chem.MolFromSmarts("[H+]")

>>> for atom in q.GetAtoms():

...   print atom.DescribeQuery()

...

AtomAnd

  AtomHCount 1 = val

  AtomFormalCharge 1 = val

Ouch.  That does look like a bug :)

https://github.com/rdkit/rdkit/issues/1338

**Comment by bp-kelley** [comment]
btw, if you want to keep explicit Hs on your smiles strings, this is the
proper RDKit way:

>>> m = Chem.MolFromSmiles("[H]C([H])([H])[H]", sanitize=False)

>>> Chem.SanitizeMol(m,
Chem.SanitizeFlags.SANITIZE_ALL^Chem.SanitizeFlags.SANITIZE_ADJUSTHS)

rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

>>> m.GetNumAtoms()

5

>>>

**Comment by greglandrum** [comment]
I agree that the behavior with `[H+]` is a bug. As was already mentioned above, the workaround is to do `[#1+]`. I actually prefer the workaround since `H` is otherwise very ambiguous and it's generally safer to use atomic numbers in SMARTS (to avoid the aromatic/aliphatic thing).

**Comment by kovasap** [comment]
@bp-kelley if there is something I could read about sanitize reaction that would be very interesting!  I've done something earlier with just mol matching using the QueryParameters, and I liked the control it gave for that application.

**Comment by bp-kelley** [comment]
If you only want to match at RGroups, try this.

```
from rdkit.Chem import AllChem,rdChemReactions
rdChemReactions.SanitizeRxn(rxn, 
                                                    params=rdChemReactions.GetChemDrawRxnAdjustParams())
```

I will note that naming this ChemDrawRxnAdjustParams in retrospect seems to have been a mistake in practice as it doesn't match how chem draw searches, say, sciquest.  This will be deprecated most likely and become:  GetOnlyMatchAtRGroupsParams in the near future.  To old one will still be around, but probably give a logging error.

Note I have only tried this on RxnBlocks, let me know if it works for smarts and I'll add some better examples to the documentation.

**Comment by bp-kelley** [comment]
@kovasap see message above (adding your tag just in case)

**Comment by kovasap** [comment]
@bp-kelley That looks like it works well to match only R groups!  What about matching implicit hydrogens in the input molecules?  Here is an example:

    rxn = [PH0:1]([OH0:2][*:6])([OH:3])(=[OH0:4])[OH:5].[OH2:7]>>[*:6][OH:7].[PH0:1]([OH:2])([OH:3])(=[OH0:4])[OH:5]
    
    react1 = [PH0:1]([OH0:2][CH3:6])([OH:3])(=[OH0:4])[OH:5]
    rxn.apply(react1)  ==> gives [CH3:6][OH:7]
    
    react2 = [PH0:1]([OH1:2])([OH:3])(=[OH0:4])[OH:5]
    rxn.apply(react2)  ==> gives nothing

Is there a way to detect the presence of an implicit hydrogen on an atom where the R group is attached in the reaction?  Even just detecting that the atom in question is "full" in terms of valence I think would work here.

**Comment by bp-kelley** [comment]
@kovasap I'll have to look at your use case a little more, but I think I understand what you are getting at.  How are you actually making react1 and react2?  MolToSmiles?

**Comment by kovasap** [comment]
Yes.  For my example, I just copied the relevant parts of the reaction smarts.  Here is a more accurate example of what I would feed in:

    react1 = [P:1]([O:2][CH3:6])([OH:3])(=[O:4])[OH:5]
    rxn.apply(react1)  ==> gives [CH3:6][OH:7]
    
    react2 = [P:1]([OH1:2])([OH:3])(=[O:4])[OH:5]
    rxn.apply(react2)  ==> gives nothing

**Comment by bp-kelley** [comment]
@kovasap I understand your issue.

One point is that defining the reactant molecules in the smiles string with an implicit H count of 0 is very confusing, so I'm going to do the example with fully valent molecules.

```
react1 = "P(OC)(O)(=O)O"
react2 = "P(O)(O)(=O)O"
```

The reaction you would like is to match atoms or explicit hydrogens.  (For simplicity I've removed the second reactant below ( [OH2:7] )

```
[PH0:1]([OH0:2][*:6])([OH:3])(=[OH0:4])[OH:5]>>[*:6][OH:7].[PH0:1]([OH:2])([OH:3])(=[OH0:4])[OH:5]
```

The thing to remember about smarts is that "*" only matches atoms that exist in the graph.  Implicit hydrogens are treated as properties of a molecule, not as atoms that can be matched.  This gives us really only one viable solution, which is to call AddHs and make the hydrogens explicitly in the graph.  Unfortunately, the reaction has no way of knowing that hydrogens are required.   We are considering adding this to the EnumerateLibrary code where we can support more styles of enumeration or reaction workflows.

Here is an example:

```
rxn = "[PH0:1]([OH0:2][*:6])([OH:3])(=[OH0:4])[OH:5]>>[*:6][OH:7].[PH0:1]([OH:2])([OH:3])(=[OH0:4])[OH:5]"

r = AllChem.ReactionFromSmarts(rxn)
m1 = AllChem.MolFromSmiles(smi1)
m2 = AllChem.MolFromSmiles(smi2)

print "*"*44
print "react1 reaction"
for prods in r.RunReactants([m1]):
    for mol in prods:
        print AllChem.MolToSmiles(mol, isomericSmiles=True)


print "*"*44
print "react2 reaction"
for prods in r.RunReactants([m2]):
    for mol in prods:
        print AllChem.MolToSmiles(mol, isomericSmiles=True)        

print "*"*44
print "AddHs(react2) reaction"
m2 = AllChem.AddHs(m2)
print AllChem.MolToSmiles(m2)

for prods in r.RunReactants([m2]):
    for mol in prods:
        print AllChem.MolToSmiles(mol, isomericSmiles=True)        
```

output:

```
********************************************
react1 reaction
CO
O=P(O)(O)O
CO
O=P(O)(O)O
********************************************
react2 reaction
********************************************
AddHs(react2) reaction
[H]OP(=O)(O[H])O[H]
```

**Comment by kovasap** [comment]
Darn : /.  Good to know this is the only way right now to do this.  I may just try to change my reactions so that they do not expect to match hydrogens.
