### ISSUE TITLE
SMARTS proton query parsed incorrectly

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#1338]
This looks like a bug (from the mailing list):

>>> q = Chem.MolFromSmarts("[H+]")
>>> for atom in q.GetAtoms():
...   print atom.DescribeQuery()
... 
AtomAnd
  AtomHCount 1 = val
  AtomFormalCharge 1 = val

**Comment by greglandrum** [comment]
Agreed. That's a bug.
I will take a look.

**Comment by greglandrum** [comment]
In the meantime the workaround is always to just do `[#1+]`
