### ISSUE TITLE
Speed up RWMol::removeHs() for large molecules 

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1359]
the problem is repeated calls to `removeBond()`, each of which ends up renumbering all the other bonds.
Profiling says that ~1/3 of the run time is in `getBondWithIdx()`

**Comment by proteneer** [comment]
I had no idea getBondWithIdx() is so bloody expensive - presumably it has to do a neighborlist lookup underneath boost::graph somewhere?

**Comment by greglandrum** [comment]
It's not actually that expensive, it's just that it is being called *a lot*:
For every bond that is removed (>1000 of them), every higher numbered bond needs to be fetched and renumbered.
There is a very small edit that gets rid of all the calls to `getBondWithIdx()` and should speed things up dramatically and then a larger change that switches modes so that the bonds are only re-numbered once. I may not do this last one because it requires introducing a change that makes it entirely too easy to shoot yourself in the foot.
