### ISSUE TITLE
MolFromMolFile error -> old mol file format?

### ISSUE THREAD

**Issue by mpwaller** [rdkit/rdkit#1361]
```$ python ```

```>>>from rdkit import Chem```

``` >>>m = Chem.MolFromMolFile('50-21-5.mol')```

error message is "[14:02:18] CTAB version string invalid at line 4" 

where 50-21-5.mol is: 

```Propanoic acid, 2-hydroxy-, ID: 50-21-5
  NIST    04032514482D 1   1.00000     0.00000      
NIST Standard Reference Data
  6  5  0     0  0              1 v2000
   32.0000   18.0000    0.0000 C   0  0  0  0  0  0           0  0  0
   11.0000   18.0000    0.0000 C   0  0  0  0  0  0           0  0  0
    0.0000    1.0000    0.0000 C   0  0  0  0  0  0           0  0  0
    1.0000   35.0000    0.0000 O   0  0  0  0  0  2           0  0  0
   42.0000   34.0000    0.0000 O   0  0  0  0  0  2           0  0  0
   41.0000    0.0000    0.0000 O   0  0  0  0  0  2           0  0  0
  1  2  1  0     0  0
  1  5  1  0     0  0
  1  6  2  0     0  0
  2  3  1  0     0  0
  2  4  1  0     0  0
M  END
```

**Comment by greglandrum** [comment]
Hi,

The RDKit is pretty strict about what it accepts as input. The specification for mol files says that the version tag should be either V2000 or V3000. Your file says "v2000". The quickest fix would be to correct the file(s), but I can add support for this type of thing as part of the "strictParsing=False" mode for `MolFromMolFile()`.

**Comment by mpwaller** [comment]
Great, that works, thanks for taking to time to explain!
