### ISSUE TITLE
atom->getHybridization() return 0

### ISSUE THREAD

**Issue by thegodone** [rdkit/rdkit#1365]
In cpp:

          std::cout << atom->getHybridization() << ",";
          switch(atom->getHybridization()) {
          case Atom::SP:  frag += " sp";break;
          case Atom::SP2: frag += " sp2";break;
          case Atom::SP3: frag += " sp3";break;
          default: frag += " ?";break;
          }

always return 0 and switch case "?" 

I compile using those command lines in os sierra
export BOOST=/usr/local/Cellar/boost/1.61.0/include/
export RDBASEINCLUDE=/usr/local/Cellar/rdkit/HEAD-4e0271a/include/rdkit/
export RDBASELIB=/usr/local/Cellar/rdkit/HEAD-4e0271a/lib
export BOOSTINCLUDE=/usr/local/Cellar/boost/1.61.0/include/boost/
export BOOSTLIB=/usr/local/Cellar/boost/1.61.0/lib/
clang++ -g -Wall -I$RDBASEINCLUDE -I$BOOSTINCLUDE gav.cpp -o gav  -L$RDBASELIB -L$BOOSTLIB -lRDGeneral -lGraphMol -lSmilesParse  -lFileParsers -lSubstructMatch -lForceField -lForceFieldHelpers -lboost_thread-mt -lboost_system-mt

Any idea why it's like that ?

I used brew rdkit installation / compilation

**Comment by JLVarjo** [comment]
Value 0 denotes unspecified hybridization. Has the molecule gone through sanitation? Hybridization types are set in MolOps::setHybridization (and, AFAIK, nowhere else).

**Comment by thegodone** [comment]
Yes, I deactivate the SDMolSupplier sanitation! Thanks a lot it works now.


2017-03-13 12:24 GMT+01:00 JLVarjo <notifications@github.com>:
