### ISSUE TITLE
ChemicalParserException: initMatchers() must be called first

### ISSUE THREAD

**Issue by yccai** [rdkit/rdkit#1377]
This is my code:
`from rdkit import Chem
from rdkit.Chem import AllChem

smi = '[OH:1][CH2:2][CH:3]=[C:4]([CH:5]=[CH:6][CH:7]=[C:8]([CH:9]=
[CH:10][C:11]1=[C:12]([CH3:13])[CH2:14][CH2:15][CH2:16][C:17]1([CH3:18])
[CH3:19])[CH3:20])[CH3:21]>>[O:1]=[CH:2][CH:3]=[C:4]([CH:5]=[CH:6][CH:7]=
[C:8]([CH:9]=[CH:10][C:11]1=[C:12]([CH3:13])[CH2:14][CH2:15][CH2:16][C:17]1([CH3:18])
[CH3:19])[CH3:20])[CH3:21]'
rxn = AllChem.ReactionFromSmarts(smi, useSmiles = True)
seq = rxn.GetReactingAtoms()
print seq
`
But when I run it, an error is thrown: ChemicalParserException: initMatchers() must be called first. How can I solve it? 
Please help me! Thanks!

**Comment by gedeck** [comment]
I cannot get your reaction to work. However, as you report a different error, something must have been lost in the rendering.
```
smi = ('[OH:1][CH2:2][CH:3]=[C:4]([CH:5]=[CH:6][CH:7]=[C:8]([CH:9]='
'[CH:10][C:11]1=C:12[CH2:14][CH2:15][CH2:16][C:17]1([CH3:18])'
'[CH3:19])[CH3:20])[CH3:21]>>[O:1]=[CH:2][CH:3]=[C:4]([CH:5]=[CH:6][CH:7]='
'[C:8]([CH:9]=[CH:10][C:11]1=C:12[CH2:14][CH2:15][CH2:16][C:17]1([CH3:18])'
'[CH3:19])[CH3:20])[CH3:21]')
rxn = AllChem.ReactionFromSmarts(smi, useSmiles = True)
```
gives this error for me:
```
>>> rxn = AllChem.ReactionFromSmarts(smi, useSmiles = True)
[09:35:41] 

****
Pre-condition Violation
bond already exists
Violation occurred on line 350 in file .../rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: !(boost::edge(bond_pin->getBeginAtomIdx(), bond_pin->getEndAtomIdx(), d_graph).second)
****

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Pre-condition Violation
	bond already exists
	Violation occurred on line 350 in file Code/GraphMol/ROMol.cpp
	Failed Expression: !(boost::edge(bond_pin->getBeginAtomIdx(), bond_pin->getEndAtomIdx(), d_graph).second)
	RDKIT: 2017.03.1.dev1
	BOOST: 1_56
```

With a working reaction definition, an additional call to **`rxn.Initialize()`** makes it work
```
>>> smi = '[OH:1][CH2:2][CH:3]=[C:4][CH3:5]>>[O:1]=[CH:2][CH:3]=[C:4][CH3:5]'
>>> rxn = AllChem.ReactionFromSmarts(smi, useSmiles = True)
>>> rxn.Initialize()
>>> seq = rxn.GetReactingAtoms()
>>> print(seq)
((0, 1),)
```

**Comment by yccai** [comment]
Thank you very much. I add `rxn.Initialize()` to my script and I try several mapped reaction SMILES. It works.

**Comment by greglandrum** [comment]
So is it ok to close this?

**Comment by yccai** [comment]
OK! @greglandrum Thanks
