### ISSUE TITLE
No wedge indication in fused ring system

### ISSUE THREAD

**Issue by shubbey** [rdkit/rdkit#1379]
Consider the following isomers:
![1](https://cloud.githubusercontent.com/assets/24950802/24313307/871ec9b2-1099-11e7-9bc4-fdd62974d66c.png)
![2](https://cloud.githubusercontent.com/assets/24950802/24313312/8c620038-1099-11e7-80be-bd2ec1401492.png)

I've put red dots to indicate the trans (1) and cis (2) cases (pardon me if my nomenclature in incorrect as I am not a chemist!)  

When I run this through rdkit

    mol = AllChem.MolFromMol2File('in.mol2')
    AllChem.Compute2DCoords(mol)
    Draw.MolToFile(mol,'out.png')

both cases give the same result:
![1](https://cloud.githubusercontent.com/assets/24950802/24313475/266855b0-109a-11e7-808d-9853d9bc57ca.png)

Even keeping the hydrogens does not clear it up:
    
    mol = AllChem.MolFromMol2File('in.mol2',True,False)
    ...

![1h](https://cloud.githubusercontent.com/assets/24950802/24313485/303a7b54-109a-11e7-8dcd-d2b7bd7cd8a2.png)

I would expect wedges to appear in this case to distinguish the isomers.  Ideally they would be on the hydrogens (and I believe your library does do that when those are displayed for other examples).  

I am actually not using this from the python library but directly in C++.  The problem appears to be due to to this line: 

    assignStereochemistry(mol,true,true);

which is called from Draw.MolToFile for the python  wrapper.  I had to add it to my C++ code prior to the compute2DCoords() in order to correct wedging in other examples.  But in this case, omitting the line actually produces the correct result.

If you want the test cases, I've posted them to https://github.com/shubbey/rdkit_bughunt.  Or if I am doing something wrong or misunderstanding here, please let me know!  Thanks.

**Comment by shubbey** [comment]
To clarify my final comment, note that the following code "fixes" the output for this example:

    Chem.AssignAtomChiralTagsFromStructure(mol)
    #Chem.AssignStereochemistry(mol,True,True)
    AllChem.Compute2DCoords(mol)
    Chem.WedgeMolBonds(mol,mol.GetConformer())
    Draw.MolToFile(mol,'out.png')

(with the WedgeMolBonds() call only being necessary to extract the data displayed in the picture)

However, uncommenting that AssignStereochemistry() line causes the wedges to disappear.  Unfortunately, that line is necessary to get other examples to orient their wedges properly.

Basically I am just not sure which functions I am supposed to be calling here, and in which order.  I suspect this may well work and I am just not doing the right thing.  So I guess what I really would like to know is: given the 3d coordinates of a molecule, what set of functions should I call to get the 2d output including stereochemistry information?  This is my current (C++) ordering, mostly gleaned from inspecting the Draw.MolToFile function:

    mol.updatePropertyCache(false); 
    MolOps::assignChiralTypesFrom3D(mol); 
    MolOps::cleanUp(mol);
    MolOps::sanitizeMol(mol);
    DetectBondStereoChemistry(mol, &mol.getConformer());

    mol.updatePropertyCache(false);
    MolOps::assignStereochemistry(mol, true, true);
    RDDepict::compute2DCoords(mol,
                                       NULL,      // ignore
                                       true,   // canonOrient
                                       true,   // clearConfs 
                                       0,      // nFlipsPerSample
                                       0,      // nSample
                                       0,      // sampleSeed
                                       false); // permuteDeg4Nodes

    const Conformer &conf = mol.getConformer();
    WedgeMolBonds2(mol,&conf);
   ...

I'm sure some of this is redundant, unnecessary, or just plain wrong but it seems to work for most cases.  Would love your input!  Thanks.

**Comment by shubbey** [comment]
Here is an example where the assignStereochemistry() routine produces a better picture:

![spartan](https://cloud.githubusercontent.com/assets/24950802/24481053/cd6d051c-149c-11e7-9ceb-7fb0433fd9e4.png)
vs
![spartan](https://cloud.githubusercontent.com/assets/24950802/24481058/d70ba498-149c-11e7-9c86-2b7901702138.png)

for input 3.mol2 on my site.  The only difference here is that the second picture includes the   
    Chem.AssignStereochemistry(mol,True,True)
line I commented out above.  It's actually unclear to me why these routines are making a difference since I thought these calls were made as part of the mol2 file reading.  For my actual purposes though, all I have is raw coordinates so I am having to recreate the cleanup done in those file routines.

**Comment by greglandrum** [comment]
Answered in this mailing list thread:
http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg06718.html
