### ISSUE TITLE
ChemicalReaction.RunReactant(ChemicalReaction, Mol) did not match C++ signature

### ISSUE THREAD

**Issue by yccai** [rdkit/rdkit#1383]
`from rdkit import Chem
from rdkit.Chem import AllChem

smi = '[OH:1][C:2]:1:[CH:3]:[CH:4]:[CH:5]:[CH:6]:[C:7]1[OH:8].[O:9]=[O:10]>>[CH:5]:1:[CH:6]:[C:7]:2[O:8][C:15]=3[C:14](=[CH:13][C:12](=[O:11])[C:17]([CH:16]3)=[O:18])[O:1][C:2]2:[CH:3]:[CH:4]1'
rxn = AllChem.ReactionFromSmarts(smi, useSmiles = True)
react = Chem.MolFromSmiles('OC1=C(O)C=CC2=C1CCCC2')
product = rxn.RunReactant(react)
print len(product)
`
When I run the above code, an error is thrown. Why?
Thanks!

**Comment by yccai** [comment]
the reaction smiles is '[OH:1][C:2]:1:[CH:3]:[CH:4]:[CH:5]:[CH:6]:[C:7]1[OH:8].[O:9]=[O:10]>>[CH:5]:1:[CH:6]:[C:7]:2[O:8][C:15]=3[C:14](=[CH:13][C:12](=[O:11])[C:17]([CH:16]3)=[O:18])[O:1][C:2]2:[CH:3]:[CH:4]1'

**Comment by greglandrum** [comment]
The smiles provided for the reaction is invalid.

**Comment by greglandrum** [comment]
but what `RunReactant()` expects is a reactant and the index of that reactant. So you would need `rxn.RunReactant(react,0)`

**Comment by yccai** [comment]
I copy my reaction SMILES into the input area, but this SMILES is always truncated. 
I do as what you say, it runs correctly. Thanks a lot.

**Comment by greglandrum** [comment]
The general way to quote multi-line blocks of text is to put them inside of triple backquotes:
```
like
this
```

**Comment by yccai** [comment]
Get it. Thanks.
