### ISSUE TITLE
Bond from reactant not added to product

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1387]
Reported by @sroughley here:
http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg06697.html

Here's a simple example:
https://gist.github.com/greglandrum/a44f692bda8d110df309e561ea35f364

Going to have to be careful not to screw up ring opening reactions, but there are already tests for those.

**Comment by sroughley** [comment]
Thanks @greglandrum
