### ISSUE TITLE
Enhancement request: volsurf like descriptors

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/rdkit#1398]
Hello, I am curious about is it possible to add volSurf-like descriptors in the future RDKit release ? In my opinion, they are useful descriptors. The origin theory of volSurf is included below: 

Cruciani, Gabriele, Manuel Pastor, and Wolfgang Guba. "VolSurf: a new tool for the pharmacokinetic optimization of lead compounds." European Journal of Pharmaceutical Sciences 11 (2000): S29-S39.

**Comment by gedeck** [comment]
RDkit comes with an implementation of the VSA descriptors developed by Paul Labute: https://www.chemcomp.com/journal/vsadesc.htm 

These descriptors are not identical, however pretty similar and may be suitable for your applications.
