### ISSUE TITLE
Could we have the AM1-BCC charge model in rdkit?

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1400]
Hello, as an alternative to the Gasteiger-Marsili (PEOE) model, that would be quite nice.

**Comment by greglandrum** [comment]
Agreed. The problem is that we'd need an open-source implementation of the AM1 method that is useable as a C library. I'm not aware of any such thing.
Porting the open-mopac code to do that would be cool, but it seems like a non-trivial amount of work.

**Comment by thegodone** [comment]
Dear both,

I found this c++ package interesting, but not complete/finish (not all
atoms AM1 availables) and close enought to MOPAC.

https://github.com/thegodone/molds-branch

this is an improved version of a svn japan project molds not lot supported.

BR,

Guillaume

2017-04-22 16:43 GMT+02:00 Greg Landrum <notifications@github.com>:

**Comment by UnixJunkie** [comment]
Antechamber from Amber Tools has it.
I think it's C.
http://ambermd.org/antechamber/ac.html#am1bcc

**Comment by UnixJunkie** [comment]
This charge model is too slow, and crashes on many molecules, so probably most people won't need it.
