### ISSUE TITLE
rdkit can't recognize some elements

### ISSUE THREAD

**Issue by yccai** [rdkit/rdkit#1403]
This is my code.
'''
from rdkit import Chem
smi = 'O=\[Te\](O)O'
mol = Chem.MolFromSmiles(smi)
print type(mol)
'''
It return '<type 'NoneType'>'. Does not rdkit  recognize the element 'Te'?

**Comment by greglandrum** [comment]
That works fine for me:
```
In [2]: Chem.MolFromSmiles('O=[Te](O)O')
Out[2]: <rdkit.Chem.rdchem.Mol at 0x10838ba80>
```
What error/warning message do you see in the console when you do that?

**Comment by yccai** [comment]
It just return '<type 'NoneType'>' and no error thrown.

**Comment by greglandrum** [comment]
There should be an error/warning message in the console.
Which version of the RDKit are you using?

**Comment by yccai** [comment]
I am using RDKit_2016_03_1.

**Comment by greglandrum** [comment]
That version is rather old (one year out of date at this point), but I would still expect there to be something in the console.

**Comment by yccai** [comment]
I rerun my code again in IDLE. It work correctly and just return <type 'NoneType'>.

**Comment by greglandrum** [comment]
I don't know IDLE, but the RDKit does generate messages to the console when errors are encountered. Please put your exact code in a file and run it at the command line; you should see something there.

**Comment by richlewis42** [comment]
I remember having issues with valence states for metals(fixed now!) , so I bet it's that it. With 2016.03.1:

```python
>>> type(Chem.MolFromSmiles('O=[Te](O)O'))
[17:05:44] Explicit valence for atom # 1 Te, 4, is greater than permitted
<type 'NoneType'>
>>> type(Chem.MolFromSmiles('O=[Te](=O)=O'))
[17:06:32] Explicit valence for atom # 1 Te, 6, is greater than permitted
<type 'NoneType'>
```

**Comment by yccai** [comment]
Thanks for your suggestion! @richlewis42 . I will upgrade it to the latest RDKit.

**Comment by yccai** [comment]
@greglandrum , I run it at the command line. It return 
'''C:\Users\yccai\Desktop>python try.py
[08:28:18] Explicit valence for atom # 1 Te, 4, is greater than permitted
<type 'NoneType'>
'''
Yes, you are right. There is some other message returned. Maybe it is because that my RDKit version is old. I   should upgrade it.
