### ISSUE TITLE
Possible bug in SMARTS matches with explicit 'H' atoms

### ISSUE THREAD

**Issue by sroughley** [rdkit/rdkit#1404]
I have just come across the following unexpected behaviour in SMARTS matching.  Firstly, the simple case, which works as expected:

```
# Glycine with explicit H
gly=Chem.MolFromSmiles("OC(=O)CN")
gly=AllChem.AddHs(gly)

m=Chem.MolFromSmarts("[H]")
gly.GetSubstructMatches(m)
((5,), (6,), (7,), (8,), (9,))
```

Expected behaviour - the 5 H's of Gly.  Now, defining our 'H' query as part of a recursive SMARTS pattern:

```
m=Chem.MolFromSmarts("[$([H])]")
gly.GetSubstructMatches(m)
((5,), (6,), (7,), (8,), (9,))
```

Again, expected behaviour.  So far, so good, but here is where things seem to go a little strange.  Let's try a recursive query first, simply combining those two forms with a logic AND (`;`) operation:

```
m=Chem.MolFromSmarts("[H;$([H])]")
gly.GetSubstructMatches(m)
()     #No matches
```

Surely this should still match the 5x 'H', as it is only a logic combination of the two above?
Stranger still:

```
m=Chem.MolFromSmarts("[$([H]-!@C)]")
gly.GetSubstructMatches(m)
((6,), (7,))
```
Seems to work -i.e. H's attached to a C, but in the KNIME `RDKit Substructure Filter` node only `[1]` is returned, as shown below:

![image](https://cloud.githubusercontent.com/assets/8321832/25708111/6b736844-30dd-11e7-9976-17850fe36eba.png)

Finally, if we try to force the H-match:
```
m=Chem.MolFromSmarts("[H;$([H]-!@C)]")
gly.GetSubstructMatches(m)
()     #No matches
```
Again, as for the previous recursive 'AND' combination above, we have no matches.  In KNIME, there are also no matches.

So - two questions:
-Why does the addition of a logic `;` operator and a recursive SMARTS pattern stops the matching of 'H'?
-Why does the KNIME code work differently where indicated above? (All the other cases seem to agree between Python and KNIME)

**Comment by greglandrum** [comment]
First the easy one:
Something different is happening in KNIME because there was a bug fixed in the last release - #1338  - and we haven't updated the binaries that the KNIME nodes are using. That's coming.

**Comment by greglandrum** [comment]
Now the more difficult one.
Understanding the interpretation of Hs in SMARTS is non-trivial. There's some discussion of this, along with some very useful pointers from @johnmay in the commentary on PR #1339 .

The key paragraph, found by John on the Daylight website, is this one:
> These differences in interpretation would make SMIRKS unintelligible. Hence, a single change to SMARTS interpretation, for expressions of the form:` [<weight>]H<charge><map>]`. In SMARTS, these expressions now are interpreted as a hydrogen atom, rather than as any atom with one hydrogen attached. All other SMARTS hydrogen expressions retain their pre-4.51 meanings.

http://www.daylight.com/dayhtml/doc/theory/theory.smirks.html

Demonstrating this with your examples:
```
In [4]: Chem.MolToSmarts(Chem.MolFromSmarts("[H]"))
Out[4]: '[#1]'

In [5]: Chem.MolToSmarts(Chem.MolFromSmarts("[$([H])]"))
Out[5]: '[$([#1])]'

In [6]: Chem.MolToSmarts(Chem.MolFromSmarts("[H;$([H])]"))
Out[6]: '[H1&$([#1])]'
```

If you want things to always be handled properly, use `#1` when you want Hs.
```
In [7]: Chem.MolToSmarts(Chem.MolFromSmarts("[#1;$([#1])]"))
Out[7]: '[#1&$([#1])]'
```

**Comment by sroughley** [comment]
Thanks @greglandrum  - I *think* I follow that now - those links are useful, even if the phrase
>Note that both hydrogens attached to the nitrogen of the reaction are shown as explicit. Based on the SMIRKS rules, the expression [H:99] must be interpreted as SMILES, since the bonding to this node changes during the reaction. The expression [H:100] may be interpreted as SMARTS, since its bonding does not change in the reaction. Recall that in versions of the Daylight system prior to 4.51, [H] as SMARTS meant: "any atom with a single attached hydrogen", while in SMILES it is a lone explicit hydrogen. 

from the preceding paragraph at http://www.daylight.com/dayhtml/doc/theory/theory.smirks.html is surely designed to bewilder!  The legacy version of [H] meaning any atom with 1 H attached seems itself somewhat strange

**Comment by sroughley** [comment]
Any idea for the timing of the KNIME binaries update?

**Comment by greglandrum** [comment]
The new binaries should be in the nightly "soon".
(I need to make the time to do the required testing)

**Comment by ct-gh** [comment]
Hi,@greglandrum, I tried the latest rdkit 2019.09.03 with SMARTS on the explicit 'H' atom, seems that there is something wrong. Like the folllowing:
>>> q1 = Chem.MolFromSmarts('O=C([#1])[#6,#1]')
>>> t1 = Chem.MolFromSmiles('C=O') # formaldehyde
>>> t1.HasSubstructMatch(q1) # True is expected
False

I then tried several examples with '[#6,#1]', but just found that it was always matched '[#6]'. Did I do something wrong?

Thanks

**Comment by greglandrum** [comment]
@ct-gh: you need to explicitly add Hs to the molecule if you want to be able to match Hs:
```
In [2]: m = Chem.MolFromSmiles('C=O')                                                                                        

In [3]: p = Chem.MolFromSmarts('O=C([#1])[#6,#1]')                                                                           

In [4]: m.HasSubstructMatch(p)                                                                                               
Out[4]: False

In [5]: mh = Chem.AddHs(m)                                                                                                   

In [6]: mh.HasSubstructMatch(p)                                                                                              
Out[6]: True
```

**Comment by ct-gh** [comment]
Hi @greglandrum, it works. Many thanks.
