### ISSUE TITLE
Can rdkit calculate whether a molecule is symmetric?

### ISSUE THREAD

**Issue by zealseeker** [rdkit/rdkit#1411]
I looked over the API and the document to find whether rdkit can calculate the descriptor whether the molecule is symmetric. But.. I failed.

Symmetry is an interesting topic since its definition can be diverse, including 2D symmetry (axisymmetry and rotational symmetry in graph) without considering chirality, and 3D symmetry which may be more complex.

I'd like to get whether a scaffold is symmetric such as `*c1ccccc1*`(asisymmetric) or `c1cc(*)ccc1*` (rotational symmetric)
Is it possible to use rdkit to get this descriptor?

**Comment by proteneer** [comment]
Formally you're asking if the only element in the automorphism group G is the identity element. As you've noted, this is not exactly straightforward to compute. If you include hydrogens then it is very likely to be symmetric (since any atom with 2 hydrogens necessarily implies an automorphism). Otherwise, a *really* dumb and ~approximate thing you do for the time being:

if rdmolops.canonicalRankAtoms with breakTies=False gives you a discrete coloring (i.e. no two atoms are ranked equivalently), if so then the molecule is likely to be asymmetric

**Comment by greglandrum** [comment]
I think it depends on which axis you are thinking about rotating around.
`*c1ccccc1*` is wonderfully symmetrical in 3D. I've (crudely) indicated a rotation axis - also a symmetry plane - here with an arrow:
![image](https://cloud.githubusercontent.com/assets/540511/25954917/fe19c60e-3667-11e7-9e76-01de2deb76a9.png)

Handling this for real would, I think, require some actual symmetry analysis code, like what one uses to assign point groups. The RDKit doesn't have that.

You can ignore coordinates and find the graph automorphisms using @proteneer's suggestion or by using the substructure search code: doing a substructure match of a molecule onto itself with the uniquify argument set to `False` will also tell you which atoms can map to which others.

**Comment by greglandrum** [comment]
closing this since it seems answered. please re-open if you still have questions

**Comment by jw-feng** [comment]
I tried the example code on "CCN(C)c1ccccc1" and it returned true for both methods.  However, that molecule is not symmetric.

**Comment by zealseeker** [comment]
@greglandrum I cannot reopen the issue. It seems that my original example was too perfect to illustrate the question.

@jw-feng Good example. What I know is that four carbons in the benzene ring are symmetric as the c-C bond is rotatable, leading to the "True" in my code. 
If you look at the `z` variable `[0, 7, 9, 1, 8, 5, 3, 2, 3, 5]`, you can find that there are two pairs which are the same, the 5th atom with the last atom, the 6th and the 8th.

**Comment by bp-kelley** [comment]
What’s the definition of symmetry here?  Is CC1CC1 symmetric?  Are you looking for 3D symmetry or graph symmetry?

**Comment by jw-feng** [comment]
Ideally, what I am looking for is a measurement of graph symmetry between 0 and 1, ignoring stereochemistry.  For example, C1CCC(CC1)OC1CCCCC1 would return 1.  CC1CCCC(C1)OC1CCCCC1 would return a value slightly less than 1.  CC1CC1 would return 1 as well.  Is it true that calculating exact symmetry is easier than calculating relative symmetry?

**Comment by IchiruTake** [comment]
> Ideally, what I am looking for is a measurement of graph symmetry between 0 and 1, ignoring stereochemistry. For example, C1CCC(CC1)OC1CCCCC1 would return 1. CC1CCCC(C1)OC1CCCCC1 would return a value slightly less than 1. CC1CC1 would return 1 as well. Is it true that calculating exact symmetry is easier than calculating relative symmetry?

I want to make use of symmetric but like @greglandrum said, you want to make it symmetry in what?
In mean time, I have been thinking a nice way to calculate but it only work on one atom at the cutting center. Related to line symmetric as image above. (Assuming it is close-shelled), it is hard to search whether two atoms should be in the same ring (must-have) and same symbol (optional). In the code below is an example to validate the result. You can clarify it better using GetSubstructMatch with two times on opposite (a.GetSubstructMatch(b) and b.GetSubstructMatch(a)) direction

```
def checkSymmetryByAtom(SMILES):
    mol = MolFromSmiles(SMILES)

    symmetryList = []
    counter = 0
    for atom in mol.GetAtoms():
        previousCounter = counter
        idx = atom.GetIdx()
        neighborList = [neighbor.GetIdx() for neighbor in atom.GetNeighbors()]
        if len(neighborList) < 2:
            continue
        neighborCombinations = list(combinations(neighborList, 2))

        for neighborSet in neighborCombinations:
            CopiedMol = RWMol(mol)
            CopiedMol.RemoveBond(neighborSet[0], idx)
            CopiedMol.GetAtomWithIdx(neighborSet[0]).SetNoImplicit(True)
            CopiedMol.RemoveBond(neighborSet[1], idx)
            CopiedMol.GetAtomWithIdx(neighborSet[1]).SetNoImplicit(True)
            CopiedMol.GetAtomWithIdx(idx).SetNoImplicit(True)

            SanitizeMol(CopiedMol) # Update the mol

            Fragmented_SMILES = str(MolToSmiles(CopiedMol))
            FragA, FragB, FragC = sorted(Fragmented_SMILES.split('.'))
            if (FragA == FragB and FragA != '[H]') or (FragA == FragC and FragA != '[H]') \
                    or (FragB == FragC and FragB != '[H]'):
                if previousCounter == counter:
                    symmetryList.append([idx])
                    symmetryList[counter].append(neighborSet)
                    counter = counter + 1
                else:
                    symmetryList[counter - 1].append(neighborSet)
    if symmetryList:
        return symmetryList
    else:
        return None
```
