### ISSUE TITLE
removeHs should not remove Hs with atom maps

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1420]
This should not happen:
```
In [19]: Chem.CanonSmiles('CO[H:3]')
Out[19]: 'CO'
```

**Comment by bp-kelley** [comment]
I'm not convinced here.  This makes perfect sense for mergeQueryHs and reactions, but I might be surprised that removeHs doesn't actually remove all Hs.  However, I think the option should exist, but perhaps not be the default.

**Comment by bp-kelley** [comment]
I could go either way here, I'm just considering what I consider least surprising.

**Comment by greglandrum** [comment]
Yeah, I'm a bit torn as well. I think the argument for making it the default is that adding an atom map number to an H makes it somehow special, so the default behavior (which is what happens when you build a mol from smiles or mol block) would be to leave it there.

**Comment by greglandrum** [comment]
Let's leave this the way it is
