### ISSUE TITLE
Is it possible to have per atom (even H) contribution to CLogP out of rdkit?

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1428]
Hello,
Using the Wildman and Crippen model, is it possible to extract
the per atom contribution?
Especially, is it possible to get it for all atoms (not only heavy atoms)?
Thanks,
F.

**Comment by greglandrum** [comment]
Sure, there's a function `rdMolDescriptors._CalcCrippenContribs()` that you can use:
```
In [15]: dh = rdMolDescriptors._CalcCrippenContribs(Chem.AddHs(Chem.MolFromSmiles('CCO')))

In [16]: dh
Out[16]: 
[(0.1441, 2.503),
 (-0.2035, 2.753),
 (-0.2893, 0.8238),
 (0.123, 1.057),
 (0.123, 1.057),
 (0.123, 1.057),
 (0.123, 1.057),
 (0.123, 1.057),
 (-0.2677, 1.395)]

# the first entry in each of those tuples is logp, so we can calculate logp like this:
In [17]: sum(x for x,y in dh)
Out[17]: -0.0014000000000000123
```

Note that you need to call Chem.AddHs() in order to see the contributions by the atoms.

**Comment by UnixJunkie** [comment]
amazing! openbabel cannot do that.

**Comment by UnixJunkie** [comment]
I assume the contribs are returned in the same order as atoms are ordered in the input molecule.

**Comment by greglandrum** [comment]
Yep; that's correct
