### ISSUE TITLE
Improvement suggestions for SaltRemover

### ISSUE THREAD

**Issue by ribeaud** [rdkit/rdkit#1431]
Hi,

`SaltRemover` should be improved by following features:

1. Other format than **SMARTS** should be supported. **SDF** (for file input) or **SMILES** (as array input)  should be supported as well. Or is there any reason I am not aware of that currently only **SMARTS** format is supported?

1. A method returning the fragments which have been deleted should be added. What about `StripMolAndReturnRemoved`? This method would return then a _tuple_.

I will make a push request and link to this issue.

Cheers and have a beautiful day. Best regards,

christian

**Comment by greglandrum** [comment]
Closed by PR #1432
