### ISSUE TITLE
_isCallable clashes with Celery

### ISSUE THREAD

**Issue by momeara** [rdkit/rdkit#1434]
with Celery version `4.0.2`

    from celery import Celery
    from rdkit.Chem import Descriptors

gives this error:

```
Traceback (most recent call last):
  File "/tmp/abc.py", line 5, in <module>
    from seacore.run.scoring import (
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/seacore/run/scoring.py", line 23, in <module>
    from fpcore.rdkit_common import tc_matrix_rdkit
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/fpcore/rdkit_common.py", line 20, in <module>
    from rdkit.Chem import Descriptors, inchi
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/rdkit/Chem/Descriptors.py", line 195, in <module>
    _setupDescriptors(locals())
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/rdkit/Chem/Descriptors.py", line 62, in _setupDescriptors
    if _isCallable(thing):
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/rdkit/Chem/Descriptors.py", line 25, in _isCallable
    return (hasattr(collections,'Callable') and isinstance(thing,collections.Callable)) or \
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/abc.py", line 144, in __instancecheck__
    return cls.__subclasscheck__(subtype)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/abc.py", line 161, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/celery/utils/abstract.py", line 54, in __subclasshook__
    return cls._subclasshook_using(CallableTask, C)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/celery/utils/abstract.py", line 23, in _subclasshook_using
    all(_hasattr(C, attr) for attr in cls.__required_attributes__)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/celery/utils/abstract.py", line 23, in <genexpr>
    all(_hasattr(C, attr) for attr in cls.__required_attributes__)
  File "/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/celery/utils/abstract.py", line 12, in _hasattr
    return any(attr in B.__dict__ for B in C.__mro__)
AttributeError: class _Feature has no attribute '__mro__'
```

Modifying `rdkit/Chem/Descriptors.py` by replacing

```
def _isCallable(thing):
  return (hasattr(collections,'Callable') and isinstance(thing,collections.Callable)) or \
                hasattr(thing,'__call__')
```

with 

```
def _isCallable(thing):
  try:
    is_callable = (hasattr(collections,'Callable') and isinstance(thing,collections.Callable)) or \
              hasattr(thing,'__call__')
  except:
    return False
  return is_callable
```

no longer gives an error.

**Comment by gedeck** [comment]
Hello,

When you apply your fix, do you still have access to all descriptors? _isCallable is important to make the descriptors available.

**Comment by gedeck** [comment]
What happens if you reverse the import statements?

**Comment by gedeck** [comment]
`_Feature` is part of celery and not RDkit. What Python, RDkit, and Celery version do you use?

**Comment by momeara** [comment]
I am using

     Python 2.7.11 :: Anaconda 4.1.0 (64-bit)
     celery: 4.0.2
     conda install -c rdkit rdkit=2016.09.2
     
With the original `Descriptors.py`, reversing the import statements no longer raises an exception.

With the modification, I am not sure if I have access to all the descriptors, but 

    >>> from celery import Celery
    >>> from rdkit.Chem import Descriptors
    >>> len(Descriptors.descList)
    206

**Comment by gedeck** [comment]
That is interesting. Let's try to find out what causes the exception. Can you add a `print` statement before the `is_callable` line and print `thing`?

**Comment by momeara** [comment]
entering the debugger `pdb.set_trace()` after it catches the exception

    (pdb) thing
     _Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)
    (pdb) up
    (pdb) name
    print_function
    (pdb) mod
    <module 'rdkit.Chem.GraphDescriptors' from '/nfs/work/momeara/tools/anaconda2/envs/sea16/lib/python2.7/site-packages/rdkit/Chem/GraphDescriptors.pyc'>
    (pdb) isinstance(thing, collections.Callable)
    *** AttributeError: class _Feature has no attribute '__mro__'
    (Pdb) dir(thing)
    ['__doc__', '__init__', '__module__', '__repr__', 'compiler_flag', 'getMandatoryRelease', 'getOptionalRelease', 'mandatory', 'optional']

**Comment by gedeck** [comment]
I cannot find Feature or _Feature in the code. ( @greglandrum, do you have an idea?) 

Can you paste in your `Descriptors.py` file? The line numbers in your traceback don't correspond to the ones I see in master or any historical versions of the file. 

The `_isCallable` function is called from the `_setupDescriptors` file. There is always a name associated with each thing. Can you find out which one that is?
```
  for mod in mods:
    tmp = dir(mod)

    for name in tmp:
      if name[0] != '_' and name[-1] != '_' and name not in others:
        # filter out python reference implementations:
        if name[:2] == 'py' and name[2:] in tmp:
          continue
        thing = getattr(mod, name)
        if _isCallable(thing):
          namespace[name] = thing
          _descList.append((name, thing))
  descList = _descList
```

**Comment by greglandrum** [comment]
Interestingly, this error does not occur when using Python 3.6 (I assume it also doesn't happen with Python 3.5).
This seems likely to be a celery bug, not an RDKit problem.

**Comment by gedeck** [comment]
Did you try with celery on python3? The trackback shows that celery adds a hook (subclasshook) and is therefore part of the game. The celery code requires the __mro__ attribute and as whatever is tested doesnt have it fails. I assume that whatever causes the problem is an old style class (Feature or _Feature = not derived from object). On python 3 this is therefore no longer a problem.

I tried to identify where Feature is defined, however couldn't find it on the pythons side. Guess it comes from C++

The suggested fix only hides the problem and doesn't address the cause.

**Comment by gedeck** [comment]
Got it:
```
<module 'rdkit.Chem.GraphDescriptors' from '.../rdkit/Chem/GraphDescriptors.py'>
print_function
_Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)
```
The problem is therefore caused by ```from __future__ import print_function```.  The fix is to include this specific function as an exception in the `_setupDescriptors` function.

**Comment by gedeck** [comment]
I've created the PR #1443 which contains a simple fix. I no longer have Python 2.7 on my system, so it would be great if @momeara could check the fix. The modification are the two lines
```
        if name == 'print_function':
          continue
```
in the last test block of `_setupDescriptors`.
```
  for mod in mods:
    tmp = dir(mod)

    for name in tmp:
      if name[0] != '_' and name[-1] != '_' and name not in others:
        # filter out python reference implementations:
        if name[:2] == 'py' and name[2:] in tmp:
          continue
        if name == 'print_function':
          continue
        thing = getattr(mod, name)
        if _isCallable(thing):
          namespace[name] = thing
          _descList.append((name, thing))
  descList = _descList
```

**Comment by momeara** [comment]
PR #1443 solves the problem on my machine, nice work!
