### ISSUE TITLE
ImportError: cannot import name 'format' on File "/opt/RDKit/rdkit/Chem/PandasTools.py"

### ISSUE THREAD

**Issue by darkcircle** [rdkit/rdkit#1436]
as I was try to use PandasTools in rdkit.Chem with >=pandas-0.20.0, I've met an error like you can see above title.
I tried to find why this message shows, I've got a link below,

https://github.com/pandas-dev/pandas/commit/1f812e37f33bf79beacbbfd2b1e0fa38958006e2

which explains that,

```
/rdkit/Chem/PandasTools.py
155     from pandas.formats import format as fmt
```

referring name 'format'  in the pandas.formats, which line is in /rdkit/Chem/PandasTools.py file, line 155, is moved to pandas.io.formats, and this change is applied from version 0.20.0-rc1 of pandas.

so, I think that It should be changed from **pandas.formats** to **pandas.io.formats**

```
/rdkit/Chem/PandasTools.py
155     from pandas.io.formats import format as fmt
```
and I checked that errorneous message is disappeared.
after this line changed, it should work.

~~I wish someone to submit pull requests for this issue, because i'm so much lazy ;)~~
I will submit my pull request, because it's very simple thing. -,.-;

**Comment by darkcircle** [comment]
I found that It's already fixed https://github.com/rdkit/rdkit/commit/236f9e6ee85fefebd3c578e913c7dc8b4fd5c771

sorry, this issue is duplicated.

**Comment by greglandrum** [comment]
Thanks for doing the investigation and figuring out what was going on yourself !
