### ISSUE TITLE
Add support for other datatypes to  ConvertToNumpyArray

### ISSUE THREAD

**Issue by pyeguy** [rdkit/rdkit#1447]
I like to use HashedMorganFingerprints for working with them in scikit-learn and end up having to write something like : 

```python
nbits = fp.GetLength()
elements = fp.GetNonzeroElements()
arr = np.zeros(nbits,dtype=int)
for idx,val in elements.items():
        arr[idx] = val
```
and using `np.put` might be better. 

Is there a reason ConvertToNumpyArray only excepts `ExplicitBitVect`'s?

**Comment by greglandrum** [comment]
There doesn't seem to be a good reason for that function not being there.
It should be easy enough to add.

**Comment by pyeguy** [comment]
let me know if you want a Python PR. I would offer for the C++ but I don't think it would qualify as an "enhancement" ;)

**Comment by greglandrum** [comment]
Thanks for offering, but this makes sense to have in C++.
I'll do it.

**Comment by pyeguy** [comment]
thanks. 
also it might be a good idea to throw a warning if the length is long as in the non-hashed morgan fingerprints or else it will consume quite a bit of memory...

**Comment by greglandrum** [comment]
I would do this the same was as the current code: the calling code needs to allocate the memory (you pass in the array to be filled).
