### ISSUE TITLE
Is there any detailed description of how RDKit find maximum common substructure?

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/rdkit#1449]
As title, I am curious about that if is there any detailed description of how RDKit find maximum common substructure ?

**Comment by greglandrum** [comment]
There isn't a complete description of the algorithm, but it is inspired by/derived from Andrew Dalke's FMCS algorithm: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3606201/

**Comment by hsiaoyi0504** [comment]
OK, thanks a lot
