### ISSUE TITLE
Feature request: #defines to test RDKit version

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1454]
It would be great to have compile-time macros for version checking. A related project has macros that may be useful (https://github.com/openbabel/openbabel/blob/master/src/config.h.cmake).

I see that there are runtime checks I can do, and will use these as a workaround.

**Comment by baoilleach** [comment]
Hmmm...just realised that it's not possible to work around the issue we're having (see #1453) at runtime as our fix relies on the presence of the protected variable numBonds.

**Comment by baoilleach** [comment]
In the meanwhile, I've figured out how to set the variable myself, and am posting it here if it's of use to anyone:
```
  # Find what version of RDKit
  try_run(RUNOK COMPILEOK "${CMAKE_BINARY_DIR}/getrdkitversion" "${CMAKE_SOURCE_DIR}/cmake/ReportRDKitVersion.cpp"
                          LINK_LIBRARIES ${TOOLKIT_LIBS}
                          RUN_OUTPUT_VARIABLE RDKITVERSION)
  if(COMPILEOK)
    message(STATUS "The RDKit version is ${RDKITVERSION}")
  else()
    message(FATAL_ERROR "Compiling a test program using RDKit failed. Are the library paths correct? (${TOOLKIT_LIBS})")
  endif()

  add_definitions(-DNMS_RDKIT_VERSION=${RDKITVERSION})
```
The test program, ReportRDKitVersion.cpp, is as follows:
```
#include "stdio.h"

// Taken from <RDGeneral/versions.h>
namespace RDKit
{
  extern const char * rdkitVersion;
}  

unsigned int todigit(char p)
{
  if (p >= '0' && p <= '9')
    return p - '0';
  return 0;
}

int main()
{
  unsigned int parts[3] = {0, 0, 0};
  
  const char* version = RDKit::rdkitVersion;
  const char *p = version;
  unsigned int part = 0;
  while(*p) {
    parts[part] *= 10;
    parts[part] += todigit(*p);
    p++;
    if (*p == '.') {
      part++;
      if (part == 3)
        break;
    }
  }

  printf("%d", parts[0]*10000 + parts[1]*100 + parts[2]);
  return 0;
}
```
In our cpp code, we can test as follows:
```
#if (NMS_RDKIT_VERSION > 20170000)
  // version-specific code
#endif
```

**Comment by bp-kelley** [comment]
If this is due to the currently broken RWMol::clear, you can reset using
operator= in c++

RWMol mol;
...
mol = RWMol();

not elegant but solves the numbonds issue.

If this is python, the above will also work but behaves differently.

Cheers,
 Brian

**Comment by baoilleach** [comment]
(Bump.) I need to do this again for release 2018.03.

I note that RDKit uses such compile-time #defines to switch-in functionality from Boost, e.g.
```
#if BOOST_VERSION >= 104000
#if (BOOST_VERSION / 100000) > 1 or ((BOOST_VERSION / 100) % 1000) >= 53
```

**Comment by greglandrum** [comment]
Yeah, sorry, didn't have a chance to get this into the last release.
I will definitely add it for the 2018.09 release. If @bp-kelley is ok with it, I think we could also say that it's a bug that this isn't already possible and git it into one of the patch releases.

**Comment by baoilleach** [comment]
That'd be great.
