### ISSUE TITLE
URANGE_CHECK not doing its job in RWMol::addBond

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1461]
The following code fails a PRECONDITION in addBond with "bond already exists". 
```
  RDKit::RWMol mol;
  unsigned int b0 = mol.addBond(0U, 1U);
```

In fact, the atoms don't exist, but the URANGE_CHECK is underflowing.

**Comment by bp-kelley** [comment]
And in python it's a seg fault.  Thanks for the bug report!

```
>>> m = AllChem.RWMol()
>>> print m.AddBond(0,1,AllChem.BondType.SINGLE)
```
