### ISSUE TITLE
Doc bug, perhaps? RWMol::addAtom does not return the number of atoms

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1462]
For the following test code:
```
  RDKit::RWMol mol;
  unsigned int a0 = mol.addAtom();
```
the value of a0 is 0, but the docs say that the method "returns the new number of atoms". I note that addBond() does return a value of 1.

**Comment by bp-kelley** [comment]
I just perused the source code and you are correct.

addAtom returns the index of the atom (which is num atoms -1 )
addBond returns the number of bonds.

The ship may have sailed on being consistent, but the docs are indeed
incorrect.   Could you file this as an issue?

**Comment by baoilleach** [comment]
It's already an issue (you must be reading this in an email client, I'm guessing). If it's any comfort, this behavior is consistent with Open Babel. :-)
