### ISSUE TITLE
ExplainPairScore does not support includeChirality=True

### ISSUE THREAD

**Issue by xiaotaw** [rdkit/rdkit#1466]
### I write down this test code according to [Getting Started with the RDKit in Python](http://rdkit.readthedocs.io/en/latest/GettingStartedInPython.html)
`from rdkit.Chem.AtomPairs.Pairs import GetAtomPairFingerprint`
`from rdkit.Chem.AtomPairs import Pairs`
`m = Chem.MolFromSmiles('CCOCC')`
`apfps1 = GetAtomPairFingerprint(Chem.RemoveHs(m)).GetNonzeroElements()`
`print apfps1`
**{558113: 2, 558146: 1, 558115: 2, 541732: 1, 1606721: 2, 1606690: 2}** 
`print Pairs.ExplainPairScore(558113)`
**(('C', 1, 0), 1, ('C', 2, 0))**
### However it does not work with includeChirality=True
`apfps2 = GetAtomPairFingerprint(Chem.RemoveHs(m), includeChirality=True).GetNonzeroElements()`
`print apfps2`
**{2229281: 2, 2229314: 1, 2229283: 2, 2163748: 1, 6423617: 2, 6423586: 2}**
`print Pairs.ExplainPairScore(2229281)`
**(('C', 1, 0), 1, ('F', 0, 1))**
### So, How to explain the AtomPairFingerprint with includeChirality=True? Is there an alternative to Pairs.ExplainPairScore in this case?

**Comment by greglandrum** [comment]
This is a bug. Thanks for reporting it!

**Comment by greglandrum** [comment]
Moving this to the next release since the fix requires adding functionality.
