### ISSUE TITLE
RDKit version out of date

### ISSUE THREAD

**Issue by mkputul** [rdkit/rdkit#1469]
Hello
I have installed the rdkit latest version (2017) but when I am making RMG-Py, it keeps giving me this error.

Makefile:43: *** RDKit version out of date, please install RDKit version 2015.03.1 or later with InChI support.  Stop.

I appreciate if you could help me with that.

**Comment by bp-kelley** [comment]
I expect the rdkit in your path may actually be out of date, try this
command (taken from the Makefile)


python -c 'import rdkit; print rdkit.__version__'

And see what your version is.

-Brian

**Comment by bp-kelley** [comment]
Looking at the makefile more closely, this looks as if rdkit is not found
in the path at all.  You need to be able to run rdkit from python prior to
running the makefile.

Cheers,
 Brian

**Comment by mkputul** [comment]
Thank you for your quick response. I installed the rdkit using Conda. So with activating environment for rdkit using "source activate my-rdkit-env" and running your command "python -c 'import rdkit; print rdkit.__version__'" I get:

2017.03.2

When I am installing RMG-py, I first activated the pydqed_env environment. When I ran "make" command I got that error. Should I also activate the rdkit env (or is it possible to do that?) before running make?

Thanks

**Comment by bp-kelley** [comment]
Short answer, "yes" :)

----
Brian Kelley

**Comment by mkputul** [comment]
Thanks. So I think my problem is that when I activate one, the other one deactivates. Is there specific command to activate multiple environments?

**Comment by bp-kelley** [comment]
No.  You need all the dependencies in one environment.

----
Brian Kelley

**Comment by gedeck** [comment]
In general, you install all the required packages in one environment. Conda
will use symbolic links if packages are used in multiple environments, so
it doesn't waste much space. There are cases where this is not possible;
just check the environment using `ls -alh`.

Peter

**Comment by bp-kelley** [comment]
@mkputul Did this answer your question?

**Comment by mkputul** [comment]
Thank you all. Sorry for late answer. Yes the problem is solved. 

Bests,
