### ISSUE TITLE
AdjustQueryProperties() removing properties from dummy atoms

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1474]
**Description:**

- RDKit Version: master
- Platform: Mac (El Capitan)

Here's the demo/reproducible:
```
In [9]: core = Chem.MolFromSmiles('[*:1]C1N([*:2])C([*:3])O1')

In [10]: core.GetAtomWithIdx(0).SetProp('foo','bar')

In [11]: core.GetAtomWithIdx(1).SetProp('foo','bar')

In [12]: ap = Chem.AdjustQueryProperties(core)

In [13]: ap.GetAtomWithIdx(0).GetPropsAsDict()
Out[13]: {}

In [14]: ap.GetAtomWithIdx(1).GetPropsAsDict()
Out[14]: 
{'_ChiralityPossible': 1,
 '__computedProps': <rdkit.rdBase._vectSs at 0x10b1976f0>,
 'foo': 'bar'}
```

This is particular bad because atom-map info is getting lost.

**Comment by greglandrum** [comment]
This is because of the calls to `replaceAtom()`. There will be similar problems with bonds that are made generic too.

**Comment by bp-kelley** [comment]
I just got hit with this for the rgroup decomposition a few hours ago :)

My fix was to add a flag in replace atom to keep existing properties.

**Comment by greglandrum** [comment]
@bp-kelley : I like that solution. Can you easily do a PR or is it easier for me to just re-do it?

**Comment by bp-kelley** [comment]
I'll do a PR.

----
Brian Kelley
