### ISSUE TITLE
Smarts representation question

### ISSUE THREAD

**Issue by kovasap** [rdkit/rdkit#1475]
With my version of RDKit, when a SMARTS string is written out, many small atoms will be described by their atomic numbers as opposed to their symbol (#6 vs C, for example).  Is there a reason why this is?  On my local RDKit, I changed some code in Code/GraphMol/SmilesParse/SmartsWrite.cpp to change this to the way it is for SMILES writing, but want to make sure there isn't a problem with doing this.  Thanks!

**Comment by bp-kelley** [comment]
One of the main differences is that "C" will only match aliphatic carbon and #6 will hit both aliphatic or aromatic.

----
Brian Kelley

**Comment by kovasap** [comment]
Ah I see...  I changed it back for now.

On the topic of SMARTS aromaticity, I have noticed that many SMARTS strings I've tried to build end up throwing this type of error when I try to sanitize them (before either doing a substructure match or modifying the SMARTS-derived molecule):

    ValueError: Sanitization error: Explicit valence for atom # 10 N, 4, is greater than permitted

Here is the string that caused this particular error:

    [#8H:28]-[#15:26](-[#8:25]-[#15:22](-[#8H:24])(-[#8:21]-[#6H2:20]-[#6H:19]1-[#8:18]-[#6H:17](-[#7+:16]2:[#6H:15]:[#6H:14]:[#6H:13]:[#6:12](:[#6H:11]:2)-[#6:52](-[#7H2:53])=[#8:54])-[#6H:50](-[#6H:48]-1-[#8H:49])-[#8H:51])=[#8:23])(=[#8:27])-[#8:29]-[#6H2:30]-[#6H:31]1-[#8:32]-[#6H:33](-[#7:38]2:[#6H:39]:[#7:40]:[#6:41]3:[#6:47]:2:[#7:46]:[#6H:45]:[#7:44]:[#6:42]:3-[#7H2:43])-[#6H:34](-[#6H:36]-1-[#8H:37])-[#8H:35]

I think this has to do with the aromatic (:) bonds in SMARTS (the nitrogen in question looks to be number 38 in the SMARTS I gave).  I have tried `Chem.Kekulize(mol)` to no avail, hoping that it would make RDKit see that nitrogen as having only 3 bonds.  Is sanitization of molecules from SMARTS supported, or am I making some mistake with my input?

**Comment by bp-kelley** [comment]
You should not really try and sanitize smarts patterns, they are not really molecules, rather they are expressions of partial molecules that may or may not have enough information to sanitize.

I expect you are trying to do something else.  What are you trying to accomplish?

----
Brian Kelley

**Comment by kovasap** [comment]
My goal here is to take some SMILES strings I have with general (*) groups that are used to define certain chemical transformations, read them in as SMARTS, and use the resulting SMARTS to apply the chemical transformations to molecules.  I want to make some standardizations to the SMILES/SMARTS before I use them, but perhaps this is best done while they are still in their SMILES state...

I think I'll try that now.

**Comment by bp-kelley** [comment]
SMILES and Smarts have different meanings.  You can read a molecule in as SMILES and then use AdjustQueryProperties to make certain changes such as allowing dummy atoms to behave as dummy atoms.

It seems, however, that you really want to define reactions though.

**Comment by kovasap** [comment]
Yeah I do.  Basically, I've inherited reactions that have been encoded in reaction SMILES and want to convert them to SMARTS before making some changes (that SMARTS allows with it's expanded vocabulary) to them.  Moving forward, I want to also make new reactions with SMARTS.  I think what I have going is working so far, if a little hacky.  I understand that they encode for different things (I've read the daylight pages on them).

**Comment by greglandrum** [comment]
Ok to close this issue?
