### ISSUE TITLE
MolDraw2D wedge bonds

### ISSUE THREAD

**Issue by ivan-chernyshoff** [rdkit/rdkit#1482]
Hello!
I was surprised to find that MolDraw2D is not able to draw wedged bonds in contrast to Draw.MolToImage. Is there any way to display stereochemistry using MolDraw2D?

**Comment by greglandrum** [comment]
Hmm, MolDraw2D can draw wedged bonds. How are you invoking it?

**Comment by ivan-chernyshoff** [comment]
I used the code below:

`from rdkit import Chem
from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG

smiles = '[*]O[C@@H]1O[C@@H](C)[C@H](O)[C@@H](O[C@H]2O[C@@H](C)[C@H](O)[C@@H](O)[C@H]2O[C@@H]2O[C@@H](C)[C@H](O)[C@@H](O)[C@H]2O[C@@H]2O[C@H](CO)[C@@H](O)[C@H]([*])[C@H]2NC(C)=O)[C@H]1O'
mol = Chem.MolFromSmiles(smiles)
rdDepictor.Compute2DCoords(mol)

drawer = rdMolDraw2D.MolDraw2DSVG(500,320)
drawer.DrawMolecule(mol)
drawer.FinishDrawing()
svg = drawer.GetDrawingText().replace('svg:','')
SVG(svg)`

that produce the image without stereo-info. Then I tried to find the appropriate parameters in DrawMolecule method and MolDrawOptions object, but unsuccessfully, and I have no idea where to find it
￼

**Comment by ivan-chernyshoff** [comment]
My apologies, I haven't seen `PrepareMolForDrawing` function. Thanks for the help!

**Comment by greglandrum** [comment]
Yep, that one's the key. Glad you found it!
