### ISSUE TITLE
Reaction SMARTS Hydrogen Changes

### ISSUE THREAD

**Issue by kovasap** [rdkit/rdkit#1500]
I'm interested in what the "right" way to encode hydrogen changes for a given atom across a reaction is with RDKit's reaction SMARTS.  Specifically, is there some sort of syntax that can be used to say a given atom loses a hydrogen across a reaction, or that a given atom gains a hydrogen?

Here is an example of what I mean (this is just a made up example to illustrate my issue):

    Reaction SMARTS:
    [C;H3,H2,H1:1][Cl:2].[O;H1,H2:3]>>[C:1][O:3].[Cl:2]

In this SMARTS, I am trying to say that a carbon bonded to a chlorine and 1, 2, or 3 hydrogens breaks it's Cl bond and bonds itself to an oxygen with 1 or 2 attached hydrogens.  

My issue here is that there doesn't seem to be a way to say that oxygen 3 loses a hydrogen across the reaction and that chlorine 2 gains one.  Am I missing something?

I have come up with a solution to this issue, which involves writing hydrogens that change explicitly in the SMARTS, then removing them from the SMARTS when I parse the SMARTS and storing the fact that they existed in a separate data structure so I can track changes for a given atom number.  This works, but seems like a hack.  It also doesn't answer the question for other atom properties, like charge.  

Thanks!

**Comment by bp-kelley** [comment]
@kovasap When you sanitize the outputs, does this get resolved?

**Comment by bp-kelley** [comment]
Molecules coming out of the reaction engine need to be sanitized.  This will fix valences and hydrogens.  This is an important step anyway to see where your reaction definitions mess up, and from years of experience they **_will_** mess up :)

**Comment by kovasap** [comment]
I can try doing a sanitization step again, but I remember having some trouble with it in the past.  Here is a quick example of it failing to work on a carbon with too many hydrogens (I remember having similar issues with reaction products):

    m = Chem.MolFromSmiles('[CH8:1]', sanitize=False)
    display(Draw.MolToImage(m))
    Chem.SanitizeMol(m)

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-20-342c9c8002c4> in <module>()
          1 m = Chem.MolFromSmiles('[CH8:1]', sanitize=False)
          2 display(Draw.MolToImage(m))
    ----> 3 Chem.SanitizeMol(m)
    
    ValueError: Sanitization error: Explicit valence for atom # 0 C, 8, is greater than permitted

**Comment by greglandrum** [comment]
Looks like this has been answered. Please re-open if that's not the case.
