### ISSUE TITLE
MMPA error during fragment generation

### ISSUE THREAD

**Issue by tantrev** [rdkit/rdkit#1502]
- RDKit Version:017.03.3
- Platform: MacOS 

When running the command:
`python $RDBASE/Contrib/mmpa/rfrag.py < smiles.txt > frags.txt`
as suggested by [this](http://rdkit.blogspot.com/2014/08/mmpa-on-chembl-herg-data-using-pandas.html) tutorial, the follow error results:
```
Traceback (most recent call last):
  File "/Users/owner/anaconda/share/RDKit/Contrib/mmpa/rfrag.py", line 223, in <module>
    cmpd_id = line_fields[1]
IndexError: list index out of range
```
A sample smiles.txt file may be found [here](https://pastebin.com/raw/ARW4Geby).  Any help would be more than appreciated.

**Comment by bp-kelley** [comment]
This smiles file appears to be private.

**Comment by bp-kelley** [comment]
However, my guess looking at the source code is that your input file is not quite correct.

If you want the code to skip malformed lines, you could try the following:

Change

```
    line_fields = re.split('\s|,', line)
    smiles = line_fields[0]
    cmpd_id = line_fields[1]
```

to

```
    line_fields = re.split('\s|,', line)
    if len(line_fields) < 2:
       print("Malformed line: %s"%line, file=sys.stderr)
       continue
    smiles = line_fields[0]
    cmpd_id = line_fields[1]
```

**Comment by tantrev** [comment]
You are absolutely right!  My stupid self just didn't have a second column in the structures file.  Also, just fixed the private status for the pastebin - sorry about that.  Thanks for the fix!
