### ISSUE TITLE
discrete solvent excluded surface

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1503]
Hello,
Sometimes, I need to compute the SES for small molecules or protein binding sites.
Usually, I use an external tool like chimera or else, but it would be better if my code
doesn't require one more external tool in addition to rdkit.
Recently, there is a new algorithm implemented in ChimeraX, it could be a source of inspiration.
Bonus points: if the user can control atoms' radii and the surface discretization resolution in
nb. points/ Angstrom^2 prior to launching the discretization.
Regards,
Francois.

**Comment by bp-kelley** [comment]
We are almost finished with a freeSASA integration.  

http://freesasa.github.io

The hiccup has been windows integration, but if you would like to play with the current Linux/osx extension, let me know.

**Comment by gedeck** [comment]
The request is for solvent excluded surface and not solvent accessible surface. SAS is a lot easier to calculate than SES.

**Comment by UnixJunkie** [comment]
I was talking about points in 3D: the surfacing of a molecule by points and optionally surface normals. Like Connolly surface if you prefer.

**Comment by UnixJunkie** [comment]
I found this open source implementation recently:
Website: https://zhanglab.ccmb.med.umich.edu/EDTSurf/
C++ Code: https://zhanglab.ccmb.med.umich.edu/EDTSurf/EDTSurf.zip
Paper: "Generating Triangulated Macromolecular Surfaces by Euclidean Distance Transform"
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0008140

**Comment by UnixJunkie** [comment]
I do not need this anymore, so closing.
