### ISSUE TITLE
ExpandQuery logic

### ISSUE THREAD

**Issue by kovasap** [rdkit/rdkit#1508]
Using the QueryAtom expandQuery function, is there a way to go into a lower level of the logic tree to change QueryAtom matching logic?

Here is the DescribeQuery result for SMARTS= '[C;H1,H2]'
```
AtomAnd
  AtomAnd
    AtomAtomicNum 6 = val
    AtomIsAliphatic 1 = val
  AtomOr
    AtomHCount 1 = val
    AtomHCount 2 = val
```

I would like to edit the lower AtomOr entry to say 3 Hs are also allowed.  I have tried to do this with the following code (I tried a COMPOSITE_OR as well, which led to a crash, which kinda makes sense here given what it says about the atom):
```
m = Chem.MolFromSmarts('[C;H1,H2]')
m2 = Chem.MolFromSmarts('[H3]')
a2 = list(m2.GetAtoms())[0]
for a in m.GetAtoms():
    print(a.DescribeQuery())
    a.ExpandQuery(a2, Chem.COMPOSITE_AND)
    print(a.DescribeQuery())

------------------- output -----------------------
AtomAnd
  AtomAnd
    AtomAtomicNum 6 = val
    AtomIsAliphatic 1 = val
  AtomOr
    AtomHCount 1 = val
    AtomHCount 2 = val

AtomAnd
  AtomAnd
    AtomAnd
      AtomAtomicNum 6 = val
      AtomIsAliphatic 1 = val
    AtomOr
      AtomHCount 1 = val
      AtomHCount 2 = val
  AtomHCount 3 = val
```

This code seems to only allow me to add logic at the outermost level of the tree.  Anyone have any tips about how I could have more control here?

Thanks!

See also issue #1470.

**Comment by greglandrum** [comment]
This isn't currently possible from Python. 
You can do it from C++, but that functionality has not been exposed to Python due to the complexity it would add to the wrapper.

**Comment by kovasap** [comment]
I was looking through some of the C++ code for SMARTS parsing, and (assuming I read it right) saw that extendQuery was used to change the Query logic tree as a query mol was being built up.  The way I read it, a new query atom/bond would be created with a desired query property, then the current (under construction) atom/bond would have extendQuery called on it to modify it with the new atom/bond.  

While I was reading, I didn't see any examples of where an already built query atom/bond had parts of it's query logic tree changed after the fact.  Did I just miss something?  Or must you do this kind of query manipulation at time of mol construction?

**Comment by kovasap** [comment]
I may try to change the C++ to get this functionality from Python if I can figure out how.
