### ISSUE TITLE
Installation problem after boost 1_64_0

### ISSUE THREAD

**Issue by telukir** [rdkit/rdkit#1509]
**Description:**
Trying to follow this procedure to install rdkit:

RDKit Installation in Ubuntu

Tested in 16.04

Prerequisites 

sudo apt install python-rdkit librdkit1 rdkit-data build-essential python-numpy cmake python-dev sqlite3 libsqlite3-dev libeigen3-dev

Boost installation:

Download boost
cd /usr/local/src/
sudo tar zxvf <boost tar file>
Set the environment variable for PYTHONPATH and BOOST in .bashrc and then make new settings to work execute following command
source .bashrc

**############ Python exports ##################**
export PYTHONPATH="/usr/local/lib:/usr/lib/:/usr/local/lib/python2.7/";

**############ RDKit configuration ###############**
export BOOST="/usr/local/src/boost_1_64_0/"

Ćhange to boost directory cd $BOOST
If you want to use the python wrappers: (this was tested) . Check if you might require sudo
./bootstrap.sh --with-libraries=python,regex,thread,serialization
If not using the python wrappers: 
./bootstrap.sh --with-libraries=regex,thread,serialization
After the above step it will give the next step as ./b2 if not use this option 
./b2 install   (This step taken from RDKit installation link this link is suppose to be comprehensive link). Check here also you would require sudo.
Download RDKit based on latest version available generic download link would be wget https://github.com/rdkit/rdkit/archive/Release_XXXX.XX.X.tar.gz (to know the latest version of rdkit check here based on which you can edit the rdkit download link and use as given below. Here the version was 2017_03_3)
wget https://github.com/rdkit/rdkit/archive/Release_2017_03_3.tar.gz
Extract it 
tar zxvf rdkit-Release_2017_03_3.tar.gz
Move it to /usr/local/rdkit/ (here rdkit can be a symbolic link if you want to install other versions in future else a folder, make sure that rdkit older is owned by root user). 
Set the RDKit Environment variables in .bashrc

export RDBASE="/usr/local/rdkit"
export PYTHONPATH="$RDBASE:$PYTHONPATH"
export LD_LIBRARY_PATH="$RDBASE/lib"
export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
source .bashrc (to apply the environment variable settings)

Change to rdkit directory
cd $RDBASE
Create build directory and build it with cmake as follows:
sudo mkdir build
cd build
sudo cmake .. (this is standard option. For non standard options look Advanced section in this link)
sudo make : this builds all libraries, regression tests, and wrappers (by default).

- RDKit Version: 2017_03_3
- Platform: Ubuntu 16.04

**RDKit make is breaking:**
 21%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Atom.cpp.o
[ 21%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/QueryAtom.cpp.o
[ 22%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/QueryBond.cpp.o
[ 22%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Bond.cpp.o
[ 22%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/MolOps.cpp.o
[ 22%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/FindRings.cpp.o
[ 22%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/ROMol.cpp.o
[ 22%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/RWMol.cpp.o
[ 22%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/PeriodicTable.cpp.o
[ 22%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/atomic_data.cpp.o
[ 23%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/QueryOps.cpp.o
[ 23%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/MolPickler.cpp.o
[ 23%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Canon.cpp.o
[ 23%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/AtomIterators.cpp.o
[ 23%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/BondIterators.cpp.o
[ 23%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Aromaticity.cpp.o
[ 23%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Kekulize.cpp.o
[ 24%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/MolDiscriminators.cpp.o
[ 24%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/ConjugHybrid.cpp.o
[ 24%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/AddHs.cpp.o
[ 24%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Matrices.cpp.o
[ 24%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Chirality.cpp.o
[ 24%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/RingInfo.cpp.o
[ 24%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Conformer.cpp.o
[ 24%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Renumber.cpp.o
[ 25%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/AdjustQuery.cpp.o
[ 25%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/Resonance.cpp.o
[ 25%] Building CXX object Code/GraphMol/CMakeFiles/GraphMol.dir/new_canon.cpp.o
[ 25%] Linking CXX shared library ../../lib/libRDKitGraphMol.so
[ 25%] Built target GraphMol
Scanning dependencies of target SubstructMatch
[ 25%] Building CXX object Code/GraphMol/Substruct/CMakeFiles/SubstructMatch.dir/SubstructMatch.cpp.o
In file included from /usr/local/include/boost/numeric/ublas/vector.hpp:21:0,
                 from /usr/local/include/boost/numeric/ublas/matrix.hpp:18,
                 from /usr/local/rdkit/Code/GraphMol/Substruct/ullmann.hpp:41,
                 from /usr/local/rdkit/Code/GraphMol/Substruct/SubstructMatch.cpp:25:
/usr/local/include/boost/numeric/ublas/storage.hpp: In member function 'void boost::numeric::ublas::unbounded_array<T, ALLOC>::serialize(Archive&, unsigned int)':
/usr/local/include/boost/numeric/ublas/storage.hpp:299:18: error: 'make_array' is not a member of 'boost::serialization'
             ar & serialization::make_array(data_, s);
                  ^
/usr/local/include/boost/numeric/ublas/storage.hpp: In member function 'void boost::numeric::ublas::bounded_array<T, N, ALLOC>::serialize(Archive&, unsigned int)':
/usr/local/include/boost/numeric/ublas/storage.hpp:494:18: error: 'make_array' is not a member of 'boost::serialization'
             ar & serialization::make_array(data_, s);
                  ^
In file included from /usr/local/rdkit/Code/GraphMol/Substruct/ullmann.hpp:41:0,
                 from /usr/local/rdkit/Code/GraphMol/Substruct/SubstructMatch.cpp:25:
/usr/local/include/boost/numeric/ublas/matrix.hpp: In member function 'void boost::numeric::ublas::c_matrix<T, M, N>::serialize(Archive&, unsigned int)':
/usr/local/include/boost/numeric/ublas/matrix.hpp:5977:18: error: 'make_array' is not a member of 'boost::serialization'
             ar & serialization::make_array(data_, N);
                  ^
Code/GraphMol/Substruct/CMakeFiles/SubstructMatch.dir/build.make:62: recipe for target 'Code/GraphMol/Substruct/CMakeFiles/SubstructMatch.dir/SubstructMatch.cpp.o' failed
make[2]: *** [Code/GraphMol/Substruct/CMakeFiles/SubstructMatch.dir/SubstructMatch.cpp.o] Error 1
CMakeFiles/Makefile2:3756: recipe for target 'Code/GraphMol/Substruct/CMakeFiles/SubstructMatch.dir/all' failed
make[1]: *** [Code/GraphMol/Substruct/CMakeFiles/SubstructMatch.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bp-kelley** [comment]
Boost normally needs to be compiled, this looks odd to me:

cd /usr/local/src/
sudo tar zxvf
Set the environment variable for PYTHONPATH and BOOST in .bashrc and then
make new settings to work execute following command
source .bashrc

I expect you are using two versions of boost without realizing it.

Cheers,
 Brian

**Comment by nigel-cresset** [comment]
Its a bug in boost 1.64 https://github.com/boostorg/ublas/issues/47.

To workaround it add
`#include <boost/serialization/array_wrapper.hpp>`
before
`#include "ullmann.hpp"`
in rdkit/Code/GraphMol/Substruct/SubstructMatch.cpp

**Comment by greglandrum** [comment]
Going to close this because it looks like it's been answered.
Please re-open if that's not correct.
