### ISSUE TITLE
Endless conformer search for small molecule citronellal

### ISSUE THREAD

**Issue by mkoenis** [rdkit/rdkit#1511]
**Description:**
Running conformer searches with RDKit and for some molecules takes extremely long (citronellal). The 2nd filter step (after optimization) takes hours even for relatively small numbers of generated conformers. This makes a proper conformer search nearly impossible to run since it will take weeks. This should take only a few seconds for such a small molecule. Interestingly conformational searches for another molecule (thyroxine) finished within 5 minutes while this molecule has more atoms.

- RDKit Version: 2016.09.3
- Platform: Mac (via ADF suite) (also happens on linux systems)

The second similarity filter is way to slow when doing a conformational search on some molecules.
The molecule used was citronellal which is a simple small organic molecule.
My guess is that the code searches to many atom orderings in the subroutine "Chem.AllChem.GetBestRMS". In principle only 2 atom orderings are relevant for this small molecule (when ignoring the hydrogens).  The molecule and runfile are given below. 

```
#!/bin/sh
cat <<eor > molecule.mol
butaan
SCM ADF package: www.scm.com

 29 28  0  0  0  0  0  0  0  0999 V2000
   -0.3755   -3.5496    0.8781 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4440   -2.5632    1.2778 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1519   -1.2589    1.4362 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0658   -0.1307    1.8264 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5036    0.7341    2.9728 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1970   -0.0135    4.2828 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4679   -0.6230    4.9136 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1470   -1.6002    6.0138 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6221   -1.5858    7.1349 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.8139   -3.1647    1.4579 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4804    0.9049    5.2815 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6031   -3.0666    0.7620 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6299   -4.0456   -0.0727 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2780   -4.3512    1.6288 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.5716   -2.4375    1.7715 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7874   -3.9777    2.2013 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1598   -3.6204    0.5159 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1111   -0.9599    1.2579 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2144    0.5324    0.9559 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0675   -0.5030    2.0857 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2049    1.5598    3.1797 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5687    1.2073    2.6285 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5216   -0.8511    4.0330 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1161    1.7621    5.5511 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.4519    1.2995    4.8540 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2270    0.3786    6.2125 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0113   -1.2011    4.1451 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1451    0.1523    5.3013 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4046   -2.3936    5.7271 H   0  0  0  0  0  0  0  0  0  0  0  0
  1 12  1  0
  1 13  1  0
  1 14  1  0
  1  2  1  0
  2  3  2  0
  2 10  1  0
  3 18  1  0
  3  4  1  0
  4 20  1  0
  4 19  1  0
  4  5  1  0
  5 22  1  0
  5 21  1  0
  5  6  1  0
  6 23  1  0
  6 11  1  0
  6  7  1  0
  7 28  1  0
  7 27  1  0
  7  8  1  0
  8 29  1  0
  8  9  2  0
 10 15  1  0
 10 16  1  0
 10 17  1  0
 11 25  1  0
 11 26  1  0
 11 24  1  0
M  END
eor
"$ADFBIN/rdkit.sh" generate-conformers molecule.mol "Conformers.sdf" "conformers.run" 1000 0.2 uff 0.1 True
```

**Comment by greglandrum** [comment]
I'm not sure what the ADF-supplied generate-conformers script is doing, so it's difficult to debug this one. 
If I just do the conformation generation step on my Mac I get the following:
```
In [12]: m = Chem.MolFromMolBlock(mb)
In [13]: ps = AllChem.ETKDG()
In [14]: %timeit AllChem.EmbedMultipleConfs(m,100,ps)
68.2 ms +- 1.2 ms per loop (mean +- std. dev. of 7 runs, 10 loops each)
```
That's for 100 conformations.

**Comment by mkoenis** [comment]
For me it takes much longer for 100 conformers (30 min roughly).
In principle ADF does nothing but sending the input to RDkit (I'm not the sure exactly how this is done). The problem seems to be in the command:
newrms = AllChem.GetBestRMS(m, m, id, jd). 
Maybe It helps if I add the code that is run as well (I indicated the line with the with the problem. Could the problem be that it uses 'removeHs=False'? have you tried first adding the chirality tag?

`
#!/usr/bin/env startpython
from rdkit import Chem
from rdkit.Chem import AllChem

class Conformer:
    def __init__(self, m, id=-1):
        self.mol = m
        self.id = id
        self.degen = 1
        self.energy = 999999999.9

def GenerateConformers(in_file, out_file, adf_file, n=100, rms=0.5, opt='uff', rmsopt=0.1, fixchiral='True'):

    print('Input file:', in_file)
    print('Result file:', out_file)
    print('.adf file name:', adf_file)
    print('Number of conformers to generate: ', n)
    print('Miniumum rms difference: ', rms)
    print('Optimization: ', opt)
    print('Miniumum rms difference after opt: ', rmsopt)
    print('Keep chirality fixed: ', fixchiral)

    print('Reading input molecule from ', in_file)
    m = Chem.MolFromMolFile(in_file, removeHs=False)
    if (fixchiral == 'True'):
        print('Assign atom chiral tags')
        Chem.AssignAtomChiralTagsFromStructure(m)
    print('Generating raw conformers')
    ids = list(AllChem.EmbedMultipleConfs(m, numConfs=n, pruneRmsThresh=rms))
    print('-->', m.GetNumConformers(), 'conformers generated')

    if opt=='uff':
        print('UFF')
    mocs = []
    for id in ids:
        moc = Conformer(m,id)
        mocs.append(moc)
        moc.energy = 0.0
        if opt=='uff':
            ff = AllChem.UFFGetMoleculeForceField(m, confId=id)
            n = 10
            if n > 0: more = ff.Minimize()
            while n and more:
                more = ff.Minimize()
                n -= 1
            e = ff.CalcEnergy ()
            moc.energy = e

    print('Sort by energy')
    mocs.sort(key=lambda x: x.energy)

    print('Filter out duplicates by rms, threshold: ', rmsopt)
    todelete = []
    mols = [mocs[0]]
    del mocs[0]
    for item in mocs:
        id = item.id
        e = item.energy
        minrms = 1000000.0
        for jitem in mols:
            jd = jitem.id
            if (rmsopt < 0.0):
                newrms = 99999.0
            else:
                newrms = AllChem.GetBestRMS(m, m, id, jd) #THIS LINE IS SLOW FOR CITRONELLAL
            if (newrms < minrms): minrms = newrms
            if (newrms < rmsopt): jitem.degen += 1
        if (minrms >= rmsopt):
            mols.append(item)
        else:
            todelete.append(id)

    for id in todelete: m.RemoveConformer(id)

    print('-->',len(mols), 'conformers remaining')

    print('Align conformers to lowest energy conformer')
    mref = mols[0].mol
    idref = mols[0].id
    for item in mols: AllChem.AlignMol (item.mol, mref, prbCid=item.id, refCid=idref)`

**Comment by greglandrum** [comment]
Ah... I can guess what the problem is here.

`AllChem.GetBestRMS()` finds all possible substructure matches of a molecule onto itself. If your molecule is highly symmetric (topologically) this can lead to a lot of matches. If your molecule has Hs attached, things blow up very quickly.

The solution is to remove Hs before calling `GetBestRMS()`. This means that you're calculating a heavy-atom RMS, but that's generally not so much of a problem.

Here's an untested modification of the script above that should at least give the idea:
```
#!/usr/bin/env startpython
from rdkit import Chem
from rdkit.Chem import AllChem

class Conformer:
    def __init__(self, m, id=-1):
        self.mol = m
        self.id = id
        self.degen = 1
        self.energy = 999999999.9

def GenerateConformers(in_file, out_file, adf_file, n=100, rms=0.5, opt='uff', rmsopt=0.1, fixchiral='True'):

    print('Input file:', in_file)
    print('Result file:', out_file)
    print('.adf file name:', adf_file)
    print('Number of conformers to generate: ', n)
    print('Miniumum rms difference: ', rms)
    print('Optimization: ', opt)
    print('Miniumum rms difference after opt: ', rmsopt)
    print('Keep chirality fixed: ', fixchiral)

    print('Reading input molecule from ', in_file)
    m = Chem.MolFromMolFile(in_file, removeHs=False)
    if (fixchiral == 'True'):
        print('Assign atom chiral tags')
        Chem.AssignAtomChiralTagsFromStructure(m)
    print('Generating raw conformers')
    ids = list(AllChem.EmbedMultipleConfs(m, numConfs=n, pruneRmsThresh=rms))
    print('-->', m.GetNumConformers(), 'conformers generated')
    if opt=='uff':
        print('UFF')
    mocs = []
    for id in ids:
        moc = Conformer(m,id)
        mocs.append(moc)
        moc.energy = 0.0
        if opt=='uff':
            ff = AllChem.UFFGetMoleculeForceField(m, confId=id)
            n = 10
            if n > 0: more = ff.Minimize()
            while n and more:
                more = ff.Minimize()
                n -= 1
            e = ff.CalcEnergy ()
            moc.energy = e

    print('Sort by energy')
    mocs.sort(key=lambda x: x.energy)

    print('Filter out duplicates by rms, threshold: ', rmsopt)
    todelete = []
    mols = [mocs[0]]
    del mocs[0]
    m_nohs = Chem.RemoveHs(m)

    for item in mocs:
        id = item.id
        e = item.energy
        minrms = 1000000.0
        for jitem in mols:
            jd = jitem.id
            if (rmsopt < 0.0):
                newrms = 99999.0
            else:
                newrms = AllChem.GetBestRMS(m_nohs, m_nohs, id, jd) #THIS LINE IS SLOW FOR CITRONELLAL
            if (newrms < minrms): minrms = newrms
            if (newrms < rmsopt): jitem.degen += 1
        if (minrms >= rmsopt):
            mols.append(item)
        else:
            todelete.append(id)

    for id in todelete: m.RemoveConformer(id)

    print('-->',len(mols), 'conformers remaining')

    print('Align conformers to lowest energy conformer')
    mref = mols[0].mol
    idref = mols[0].id
    for item in mols: AllChem.AlignMol (item.mol, mref, prbCid=item.id, refCid=idref)
```

**Comment by mkoenis** [comment]
Thanks for your help. The issue is fixed with these changes. I have one small question left.
Does "Chem.RemoveHs(m)" remove all Hydrogens or only the ones connected to a carbon atom? In my field the orientation of the N-H and O-H bonds are key so those hydrogens should remain in the filter step.

**Comment by greglandrum** [comment]
`Chem.RemoveHs()` removes all hydrogen atoms.
If you wanted to just remove the ones connected to C, you could do something like this:
```
  COMING IN A MINUTE
```
(note that terminal NH3+ groups are going to still keep leading to slow calculations if you do this)

**Comment by mkoenis** [comment]
oke thanks a lot
