### ISSUE TITLE
An algorithm to identify functional groups in organic molecules

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1512]
Maybe interesting to have in rdkit:
https://jcheminf.springeropen.com/articles/10.1186/s13321-017-0225-z

**Comment by greglandrum** [comment]
Agreed, that is an interesting paper

**Comment by thegodone** [comment]
Very interesting, that would be great to have it.

BR, guillaume

2017-07-28 5:52 GMT+02:00 Greg Landrum <notifications@github.com>:

**Comment by greglandrum** [comment]
Resolved by #1813

**Comment by UnixJunkie** [comment]
thanks a lot!
