### ISSUE TITLE
Missing def_readwrite for backgroundColour in rdMolDraw2D.cpp

### ISSUE THREAD

**Issue by phenethyl** [rdkit/rdkit#1519]
Description:
RDKit Version: 2017.09
Platform: All

It seems there is a no option to access drawOptions().backgroundColour using the python wrapper.
It would be nice to be able to set the backgroundColour in rdkit.Chem.Draw.MolDraw2D.MolDrawOptions.

Regards
Jacob

**Comment by greglandrum** [comment]
Fixed in #1525
