### ISSUE TITLE
CanonicalRankAtoms unintended behavior?

### ISSUE THREAD

**Issue by kovasap** [rdkit/rdkit#1526]
I'm attempting to find a way to map the atoms of a given mol in a canonical way (the same way for any way the mol is generated).  I was looking at CanonicalRankAtoms to do this, but seem to be having some trouble.  Here is an example:

```
from rdkit import Chem
def canonical_remap(smi):
    mol = Chem.MolFromSmiles(smi)
    for j, i in enumerate(list(Chem.CanonicalRankAtoms(mol, breakTies=True))):
        mol.GetAtomWithIdx(i).SetIntProp('molAtomMapNumber', j)
    print(Chem.MolToSmiles(mol))
    print()
s = '[NH2:1][CH2:2][CH2:3][CH2:4][CH2:5][CH2:6][C:7](=[O:8])[OH:9]'
canonical_remap(s)
s = '[NH2:5][CH2:2][CH2:3][CH2:4][CH2:1][CH2:6][C:7](=[O:8])[OH:9]'
canonical_remap(s)
s = '[NH2][CH2][CH2][CH2][CH2][CH2][C](=[O])[OH]'
canonical_remap(s)
s = '[OH][C](=[O])[CH2][CH2][CH2][CH2][CH2][NH2]'
canonical_remap(s)
s = Chem.MolToSmiles(Chem.MolFromInchi('InChI=1S/C6H13NO2/c7-5-3-1-2-4-6(8)9/h1-5,7H2,(H,8,9)'))
canonical_remap(s)
s = 'OC(=O)CCCCCN'
canonical_remap(s)

-----OUTPUT-----
[NH2:0][CH2:1][CH2:2][CH2:3][CH2:4][CH2:5][C:6](=[O:7])[OH:8]

[CH2:0]([CH2:3][CH2:2][CH2:1][NH2:4])[CH2:5][C:6](=[O:7])[OH:8]

[NH2:0][CH2:7][CH2:8][CH2:1][CH2:2][CH2:3][C:4](=[O:5])[OH:6]

[O:0]=[C:2]([CH2:7][CH2:6][CH2:5][CH2:4][CH2:3][NH2:1])[OH:8]

[NH2:0][CH2:7][CH2:8][CH2:1][CH2:2][CH2:3][C:4](=[O:5])[OH:6]

[O:0]=[C:2]([CH2:7][CH2:6][CH2:5][CH2:4][CH2:3][NH2:1])[OH:8]

```

As you can see, the output strings I am getting for different inputs clearly don't have the same mapping!  Am I making any obvious mistakes with my code or misinterpreting the CanonicalRankAtoms function?

**Comment by greglandrum** [comment]
There are a number of things going on here:

1) One of the things going on here is that atom map information is used in the canonicalization process. So `[NH2:1][CH2:2][CH2:3][CH2:4][CH2:5][CH2:6][C:7](=[O:8])[OH:9]` and `[NH2:5][CH2:2][CH2:3][CH2:4][CH2:1][CH2:6][C:7](=[O:8])[OH:9]` generate different canonical orderings. If you would like the canonical ordering to ignore the atom mapping (which you aren't using in your code anyway), you need to just remove it.

2) You've got the mapping returned by `Chem.CanonicalRankAtoms()` backwards. If you get a list like `[1, 2, 0, 3]` back it means that atom 0 in the molecule is ranked 1, atom 1 is ranked 2, atom 2 is ranked 0, and atom 3 is ranked 3.

3) I would ensure that the atom mapping numbers start from 1, not 0.

Here's an updated version of your code that, I think, does what you expect:
```
from rdkit import Chem
def canonical_remap(smi):
    mol = Chem.MolFromSmiles(smi)
    for atom in mol.GetAtoms():
      if atom.HasProp('molAtomMapNumber'):
          atom.ClearProp('molAtomMapNumber')
    ranks = list(Chem.CanonicalRankAtoms(mol, breakTies=True))
    for j, i in enumerate(ranks):
        mol.GetAtomWithIdx(j).SetIntProp('molAtomMapNumber', i+1)
    print(Chem.MolToSmiles(mol))
    print()
s = '[NH2:1][CH2:2][CH2:3][CH2:4][CH2:5][CH2:6][C:7](=[O:8])[OH:9]'
canonical_remap(s)
s = '[NH2:5][CH2:2][CH2:3][CH2:4][CH2:1][CH2:6][C:7](=[O:8])[OH:9]'
canonical_remap(s)
s = '[NH2][CH2][CH2][CH2][CH2][CH2][C](=[O])[OH]'
canonical_remap(s)
s = '[OH][C](=[O])[CH2][CH2][CH2][CH2][CH2][NH2]'
canonical_remap(s)
s = Chem.MolToSmiles(Chem.MolFromInchi('InChI=1S/C6H13NO2/c7-5-3-1-2-4-6(8)9/h1-5,7H2,(H,8,9)'))
canonical_remap(s)
s = 'OC(=O)CCCCCN'
canonical_remap(s)
```
the output I get:
```
[NH2:1][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][C:9](=[O:2])[OH:3]

[NH2:1][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][C:9](=[O:2])[OH:3]

[NH2:1][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][C:9](=[O:2])[OH:3]

[NH2:1][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][C:9](=[O:2])[OH:3]

[NH2:1][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][C:9](=[O:2])[OH:3]

[NH2:1][CH2:4][CH2:5][CH2:6][CH2:7][CH2:8][C:9](=[O:2])[OH:3]
```

**Comment by kovasap** [comment]
That looks great!  Thank you!  Just for my reference, is the canonical ordering algorithm used by this function the one described in this paper: http://pubs.acs.org/doi/full/10.1021/acs.jcim.5b00543 ?

**Comment by greglandrum** [comment]
Yeah, that's the algorithm.
