### ISSUE TITLE
WrapLogs() works on Linux but not on Windows

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1561]
(As discussed on rdkit-discuss)

The following raises an AssertionError, but should not.

```
import sys
from rdkit import Chem
Chem.WrapLogs()
from StringIO import StringIO

old_stderr = sys.stderr
sio = sys.stderr = StringIO()

mol = Chem.MolFromSmiles("c1ccccc")
sys.stderr = old_stderr

assert sio.getvalue() != ""
```

I'm using this from a Windows 7 conda environment, Python 2.7 64-bit, RDKit 2017.03.3. I note that this code works on Linux (with a similar Conda environment), so appears to be a Windows-specific problem.

**Comment by bp-kelley** [comment]
The wraplogs do "work", but the buffer takes a long while to get flushed.  As to date I have been unable to solve the issue.
