### ISSUE TITLE
SMILES valence model for iodine not respected

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1569]
**Description:**

- RDKit Version: 2017.03.3
- Platform: Windows (conda) 64-bit

The SMILES valence model specifies 1 for halides. After this, no hydrogens should be added implicitly.

RDKit adds 1 for explicit valence 0, 0 for valence 1, 0 for valence 2, 2 for valence 3, 1 for valence 4, 0 for valence 5. That is to say, it rounds up to 1 for valence 0/1, doesn't add anything for 2, and rounds up to 5 for valence 3/4/5.

```
from rdkit import Chem

mol = Chem.MolFromSmiles("O1I(C)c2ccccc2C1")
for atom in mol.GetAtoms():
    if atom.GetAtomicNum() == 53: # iodine
        print atom.GetTotalNumHs(False)

```
produces
```
2
```
instead of 0.

**Comment by baoilleach** [comment]
(Hope you're having a good RDKit UGM.)

As a sort of follow-on, I've been comparing a whole bunch of toolkits with respect to the SMILES valence model as descibed by Daylight and more clearly by OpenSMILES. RDKit has three differences:
1. P(C)(C)(C)(C)(C)C - spec says 0 hydrogens on P, but RDKit says 1
2. I(C)(C)C - 0 vs 2 (as discussed above)
3. I(C)(C)(C)C - 0 vs 1 (as discussed above)

**Comment by baoilleach** [comment]
My new year's resolution is to write up the current status of this benchmark and file a few more bugs. Any chance of a comment on this?

**Comment by greglandrum** [comment]
I think there are two things going on here:

- Which valence states are "supported" for individual atoms
For reasons I no longer remember, and really can't defend, the RDKit recognizes the valence states 1, 2, and 5 on I.
Similarly P supports 3, 5, and 7. 
It's worth discussing these states, but it's tough to change them (restricting what's accepted could break existing molecules). Still, if there's a rational (and chemical) way to come up with a set of allowed valence states for the atoms that have more than one, I'd love to hear it.

- What should happen with implicit Hs for valences that are higher than the default.
Assume, for the sake of this argument, that 5 is a reasonable oxidation state for I but that 1 is the default (lowest) state. In this case the SMILES `I(C)(C)C` really needs to have 2 Hs on the I, which is valence state 5 and has three explicit neighbors. Similarly `I(C)(C)(C)C` should have 1 H on the I. Do you disagree with this?

**Comment by baoilleach** [comment]
I don't think I have anything useful to say on the first topic, as I would be happy for a toolkit to just accept data as provided, which of course makes this particular problem go away. (Though I have been thinking about providing a function to warn about unusual valence, which could be used as an input filter.)

Regarding the second, I think when reading SMILES we should do whatever Daylight did. As a surrogate, we have Dave Weininger's CEX code, and its reading of SMILES strings (https://github.com/nextmovesoftware/CEX/blob/665522b4cd3a7ee77707fcfee5be18368b2b81b7/src/molecule/cx_molecule.c#L1681). TLDR; don't add any hydrogens.

**Comment by baoilleach** [comment]
Actually, regarding the first one, Daniel gave me code some time ago, which I adapted for Open Babel for use when reading PDB files (for example):
https://github.com/openbabel/openbabel/blob/771b917388b9fa282af1494ddf6434b8e584c2c9/src/obfunctions.cpp#L76
...there iodine has 1, 3, 5, 7 when neutral. I think Daniel came up with the list by inspection when trying to identify dodgy molecules. If interested, I can look up the original source of that file.
