### ISSUE TITLE
rdMCS particularly slow in some examples

### ISSUE THREAD

**Issue by coleb** [rdkit/rdkit#1585]
These two molecules are exceptionally slow at calculating the MCS (23 seconds on my laptop). Yet the molecules don't look particularly pathological at all.  

![image](https://user-images.githubusercontent.com/127899/30702673-dd85b1fc-9eed-11e7-99ff-2e754e95d152.png)

![image](https://user-images.githubusercontent.com/127899/30702698-e6fb967a-9eed-11e7-9310-cdbd99233ee4.png)

```
from __future__ import print_function
import time
from rdkit import Chem
from rdkit.Chem import rdFMCS

reference_mol = Chem.MolFromSmiles('c1cc(c(c(c1)Cl)N2c3cc(cc(c3CNC2=O)c4ccc(cc4F)F)N5CCNCC5)Cl')
assert reference_mol is not None
reference_num_atoms = reference_mol.GetNumAtoms()

fit_mol = Chem.MolFromSmiles('CCNc1cc(c2c(c1)N(C(=O)NC2)c3ccc(cc3)n4ccc-5ncnc5c4)c6ccnnc6')
assert fit_mol is not None
fit_num_atoms = fit_mol.GetNumAtoms()

bgn = time.time()
res = rdFMCS.FindMCS([reference_mol, fit_mol])
print(time.time() - bgn, 'seconds to run')
print(res.numAtoms)
```

**Comment by adalke** [comment]
I was able to repeat this timing in the original Python implementation, which also has more statistics enabled.

The annoying thing is that the best match is available within 0.1 seconds, after 1361 substructure enumerations, while the full search (to prove nothing else is possible) takes 34729 enumerations.

I remember cases like this during development, but my tests found places where the fmcs code was significantly faster than the other packages I tested, so the fmcs implementation overall wasn't that bad.

There's no easy fix to the code. It will require understanding it (again), and looking for additional algorithm improvements, likely to do with pruning search space.

If you think you can get away with it, set the timeout to 1 second or even less.
