### ISSUE TITLE
3D structure generation for big (> ~ 100 non-hydrogen atoms) molecules

### ISSUE THREAD

**Issue by ivan-chernyshoff** [rdkit/rdkit#1593]
As I'm working with natural glycans, I need to generate 3D coordinates of molecules containing up to 200 non-hydrogen atoms. However, both 3D structure generation algorithms (default and ETKDG) are not able to generate 3D coordinates for big molecules, e.g. hectane C100H202:

    mol = Chem.AddHs(Chem.MolFromSmiles('C'*100))
    AllChem.EmbedMolecule(mol, maxAttempts = 10000)
    Out[15]: -1

It would be great, if this opportunity will appear in future versions.

**Comment by greglandrum** [comment]
For large molecules, it's a good idea to use the `useRandomCoords` keyword argument to `EmbedMolecule()`:
```
AllChem.EmbedMolecule(mol, useRandomCoords=True)
```
On my linux box C100H202 embeds in about 2 seconds using random coords.

Note that the time required for embedding increases rapidly with molecular size - C200H402 takes about 17s.

Unless you plan a molecular mechanics minimization of the conformations, it's generally a good idea to use the ETKDG parameter set:
```
params = AllChem.ETKDG()
params.useRandomCoords=True
AllChem.EmbedMolecule(mol, params)
```
This takes a bit longer (4 seconds for the C100 case), but the conformations are significantly better.

**Comment by ivan-chernyshoff** [comment]
Thank you very much for the prompt reply!
