### ISSUE TITLE
Can't import QED module

### ISSUE THREAD

**Issue by sergsb** [rdkit/rdkit#1611]
rdkit: 2017.03.3
platform: linux x64

Hi,

I can't import QED module. But it is in documentation: http://www.rdkit.org/Python_Docs/rdkit.Chem.QED-module.html
```

Traceback (most recent call last):
  File "/home/me/q.py", line 1, in <module>
    import rdkit.Chem.QED
ModuleNotFoundError: No module named 'rdkit.Chem.QED'
```

**Comment by greglandrum** [comment]
The QED descriptor was added for the 2017.09 release

**Comment by sergsb** [comment]
Hi, 

In [documentation](http://www.rdkit.org/Python_Docs/rdkit.Chem.QED-module.html) mentioned that module was added in 2012 and moved in 2013 year, Is there an error?

> History:
>   2012-04 Adapted to internal RDkit implementation
>   2013-05 moved to rdkit.Chem.QED

**Comment by greglandrum** [comment]
Sorry for the confusion about that. That's from the pre-open-source version of the code (when it was in use within Novartis).

You can see the open-source history of the file here:
https://github.com/rdkit/rdkit/commits/master/rdkit/Chem/QED.py

**Comment by greglandrum** [comment]
Closing this because I think it's answered. Please re-open if you disagree.
