### ISSUE TITLE
Draw._moltoSVG() raises an exception

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1625]
**Description:**

The usage of the `kekulize` argument is wrong.

Reported by Markus Metz. Here's the mailing list thread:
https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg07400.html

**Comment by coleb** [comment]
Pull request 1641 fixes this. But the larger issue is we need to set up https://github.com/rdkit/rdkit-tutorials to pull HEAD and the latest release from anaconda.org for travis-ci testing.

**Comment by greglandrum** [comment]
Though it definitely wouldn't be bad to be able to do that, I suspect that we could also figure out a way to add tests for some of the Draw and IPythonConsole functionality as part of the normal test suite.

**Comment by greglandrum** [comment]
Fixed by #1641
