### ISSUE TITLE
Add Atom.SetPDBResidueInfo() to Python wrappers

### ISSUE THREAD

**Issue by hjuinj** [rdkit/rdkit#1631]
I wish to use rdkit to work with peptides. I can create a peptide sequence using `Chem.MolFromSequence()`. I can get and set PDB properties like chain number, atom type for each atom in the peptide via the `GetPDBResidueInfo()` class in `rdkit.Chem.rdchem.Atom`.

However, I also wish to perform some chemical transformations on the peptide, which I can do either using reactions or turn the peptide into a RWMol object. Let's say I just want to methylate an residue and I do it via RWMol, I can add a new atom and the new connectivity. But then I face a problem: the newly added atom has no `AtomPDBResidueInfo()` object associated to it so when I call `GetPDBResidueInfo()` I get a None type back. And there is no corresponding setter such as ``SetPDBResidueInfo()` in `rdkit.Chem.rdchem.Atom` for me to associate an `AtomPDBResidueInfo` object to the newly created atom.

Is there a way to work around this?

**Comment by greglandrum** [comment]
At the moment there's no way to add `AtomPDBResidueInfo` to an atom. That would be a good thing to add to the RDKit, so I'm going to change the description of this issue to reflect that.

The workaround that I think should work for you is to start with an atom that already has `AtomPDBResidueInfo`, add that to the molecule, then get the atom you added and edit the info.
Here's a snippet showing how you would start doing that:
```
In [30]: m = Chem.MolFromPDBFile('./2FVD.pdb')

In [31]: at = m.GetAtomWithIdx(0)

In [32]: rwm = Chem.RWMol(m)

In [33]: idx = rwm.AddAtom(at)

In [34]: newat = rwm.GetAtomWithIdx(idx)

In [35]: newat.GetPDBResidueInfo()
Out[35]: <rdkit.Chem.rdchem.AtomPDBResidueInfo at 0x7ff30e5c83a0>
```
This works because `AddAtom()` copies the atom you give it.

Does that help?

**Comment by hjuinj** [comment]
thanks Greg. This is essentially what I am doing now, I deepcopy my molecule and basically 'borrow ' atoms from the original molecules to add onto the copy. 

It will be great to add this feature into rdkit. I will note if I try to add atoms to a molecule via reaction SMARTS, not only do the newly added atom has no `AtomPDBResidueInfo` info, it seems all the other atoms I included in my SMARTS string lose their `AtomPDBResidueInfo` info too.I have not read the source code so properly this can be fixed with the same enhancement.

**Comment by greglandrum** [comment]
that second bit: atoms losing their `AtomPDBResidueInfo` when they go through a reaction, is a bug.
Would you mind filing a bug report for that?

**Comment by hjuinj** [comment]
like this? #1632

**Comment by greglandrum** [comment]
perfect. thanks!

**Comment by hjuinj** [comment]
@greglandrum actually, regarding this particular issue, @mwojcikowski 's solution in #1632  would work.

**Comment by satary** [comment]
Hello!
I subscribe to the commentary, such a function is very lacking to create polymer models for various near biological problems.

**Comment by MaxGreil** [comment]
Hi @greglandrum ,
I would like to take on this issue. Can you please explain what needs to be done here?
