### ISSUE TITLE
ImportError: No module named 'rdkit.rdBase'

### ISSUE THREAD

**Issue by xiaohongniua** [rdkit/rdkit#1634]
**Description:**
hello. I am win10 user and downloaded rdkit-Release_2017_09_1.zip and unzipped in c:
and i added path with github instructions.
RDBASE : c:\rdkit-Release_2017_09_1
PYTHONPATH : %RDBASE%
PATH : %PATH%; c:\rdkit-Release_2017_09_1\lib

import rdkit
-->Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\rdkit-Release_2017_09_1\rdkit\__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ModuleNotFoundError: No module named 'rdkit.rdBase'

what should I do?
thanks

**Comment by greglandrum** [comment]
Does the answer provided in #1402 , which you've also commented on, not work for you?

**Comment by bannanc** [comment]
@greglandrum 
I'm running into the same issue today, I'm on a mac using anaconda, initially I was trying to add rdkit to an existing environment, but when that didn't work I started from a completely clean one following your install instructions. 
I also tried an environment where I specified python 3.5.3 since that worked for someone in issue #1402 

In the most recent iteration I installed with the conda instructions in the RDKit documentation again:
```
conda create -c rdkit -n my-rdkit-env rdkit
source activate my-rdkit-env
```
After trying to install rdkit:
```
In [1]: import rdkit
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e537e29c64f4> in <module>()
----> 1 import rdkit

/Users/bannanc/gitHub/rdkit/rdkit/__init__.py in <module>()
      1 try:
----> 2   from .rdBase import rdkitVersion as __version__
      3 except ImportError:
      4   __version__ = 'Unknown'
      5   raise

ImportError: No module named 'rdkit.rdBase'
```

Here's my environment list
```
(my-rdkit-env) gitHub/rdkit (MDL_test)$ conda list
# packages in environment at /Users/bannanc/anaconda3/envs/my-rdkit-env:
#
boost                     1.63.0                   py35_1    rdkit
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.1.18                     0    conda-forge
cairo                     1.14.6                        0    conda-forge
certifi                   2018.1.18                py35_0    conda-forge
fontconfig                2.11.1                        6    conda-forge
freetype                  2.6.3                         1    conda-forge
icu                       56.1                          4    conda-forge
intel-openmp              2018.0.0                      8
jpeg                      9b                            2    conda-forge
libgfortran               3.0.1                h93005f0_2
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libtiff                   4.0.9                         0    conda-forge
libxml2                   2.9.4                         3    conda-forge
mkl                       2018.0.2                      1
ncurses                   5.9                          10    conda-forge
numpy                     1.14.2           py35ha9ae307_0
olefile                   0.45.1                   py35_0    conda-forge
openssl                   1.0.2n                        0    conda-forge
pandas                    0.22.0                   py35_0    conda-forge
pillow                    4.0.0                    py35_1    conda-forge
pip                       9.0.1                    py35_1    conda-forge
pixman                    0.32.6                        0    rdkit
python                    3.5.5                         0    conda-forge
python-dateutil           2.3                      py35_0    bioconda
pytz                      2018.3                     py_0    conda-forge
rdkit                     2017.09.3.0              py35_1    rdkit
readline                  7.0                           0    conda-forge
setuptools                39.0.1                   py35_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
wheel                     0.30.0                   py35_2    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by greglandrum** [comment]
@bannanc It looks like you have the rdkit conda package installed (this is good) but that you either have an RDKit source distribution in your `PYTHONPATH` or you're running python from inside an RDKit source distribution.

I can guess this because this part of the error message:
```
/Users/bannanc/gitHub/rdkit/rdkit/__init__.py in <module>()
      1 try:
----> 2   from .rdBase import rdkitVersion as __version__
      3 except ImportError:
      4   __version__ = 'Unknown'
      5   raise
```
indicates that it's importing the rdkit package from the directory `/Users/bannanc/gitHub/rdkit/rdkit`, which is almost certainly *not* where conda installed it.

If you need to do your own build on the Mac, let me know and I will track down a set of instructions I have for doing that. (I need to do this anyway)

**Comment by bannanc** [comment]
@greglandrum 
Thanks so much for the help. That must be left over from another project. 
I don't need my own build for now, if that becomes necessary and can't get it working I'll get back in contact. 
I'm working on my laptop today and this process worked fine (I was on my work desktop last night, I'll uninstall the github version on my desktop, but I bet you're right that is the problem).

**Comment by MrML1986** [comment]
@greglandrum 

Hello,

i have same problem, but on windows. How to fix it. ? can you pleas help out with. ? Following is the error


import rdkit
Traceback (most recent call last):

  File "<ipython-input-1-6b72bd8913ab>", line 1, in <module>
    import rdkit

  File "C:\Anaconda3\lib\site-packages\rdkit\__init__.py", line 2, in <module>
    from rdBase import rdkitVersion as __version__

ModuleNotFoundError: No module named 'rdBase'

**Comment by greglandrum** [comment]
@MrML1986 Did you do your own build or are you using a conda package?

**Comment by MrML1986** [comment]
@greglandrum, Thanks for your reply.  I used Conda package following the instructions on 

http://rdkit.org/docs/Install.html#cross-platform-under-anaconda-python-fastest-install

**Comment by ErikCVik** [comment]
I got this error message out of the blue one day after using rdkit successfully in the past. I should note that I use pycharm, and after updating pycharm the error message went away.

**Comment by JurajMa** [comment]
This still persists, in 2020. 
It would be better to switch to absolute imports within the package.

**Comment by sandrine-muller-research** [comment]
Thanks for your feedback JurajMa! Very decieved that Windows users get segregated like that!

**Comment by greglandrum** [comment]
I want to correct some of the statements in one of the previous comments, so they aren't just sitting here.

> In fact `rdkit.Chem.__init__` is trying to import rdBase with:
> 
> `from rdkit import rdBase`
> 
> while clearly `rdBase` **doesn't exist** there.

`rdBase` doesn't exist if you start from a source distribution until you've done a successful build, that's true. If you install a build using conda (which @JurajMa has said they cannot do), then the file will be there.

> 
> This package is completely messed up.
> Also, in the documentation for the Windows installation it says
> 
> > PATH: add ;%RDBASE%\lib to the end
> 
> while a `lib` folder also doesn't exist within the latest release.

Again, this is only relevant if you are installing from source. The `lib` directory is created if you successfully build and install the code.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by TalWac** [comment]
Hello 

I think having a similar problem, when running my script from Pycharm with conda environment  it seems to work,
However, when using Compound Discover software to run the script I see those warnings (should be read bottom-up)
 

 Processing Node | Level | Message
-- | -- | -- | --
(49): Scripting Node | Warning | ImportError: DLL load failed: The specified module could not be found.
(49): Scripting Node | Warning | from .rdBase import rdkitVersion as __version__
 (49): Scripting Node | Warning | File "C:\Users\BCDD\AppData\Local\Continuum\anaconda3\lib\site-packages\rdkit\__init__.py", line 2, in <module>
(49): Scripting Node | Warning | from rdkit import Chem
(49): Scripting Node | Warning | File "D:\BCDD\Documents\Tal\CD\Scripting\cd-scripting-node-python\node\ScriptingNode1.py", line 5, in <module>
(49): Scripting Node | Warning | Traceback (most recent call last):


Any idea how to make it work?
