### ISSUE TITLE
Atom index type is to low for big molecules

### ISSUE THREAD

**Issue by mwojcikowski** [rdkit/rdkit#1642]
**Description:**
The atom indices are uint16 type, which effectively limits the number of atoms to 65535. Crazy enough there is no single precondition that guards it. You can without error (although with sanitize=False for speed) create molecule with more atoms. The magic starts when you want to actually use the atoms.

First this issue started surfacing when I worked with PDB for #1629. When removing hydrogens I started to get "no owner" error for atoms. When I wanted to create self-contained sample I didn't even get this far, as smiles encode all bonds .

```python
smi = 'C.' * 68000 + 'C'
mol = Chem.MolFromSmiles(smi, sanitize=False)
mol = Chem.RWMol(mol)
for i in reversed(range(mol.GetNumAtoms())):
    mol.RemoveAtom(i)
```

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-48-fd00d89bcb52> in <module>()
>       3 mol = Chem.RWMol(mol)
>       4 for i in reversed(range(mol.GetNumAtoms())):
> ----> 5     mol.RemoveAtom(i)
> 
> RuntimeError: Pre-condition Violation
> 	no owner
> 	Violation occurred on line 125 in file Code/GraphMol/Atom.h
> 	Failed Expression: dp_mol
> 	RDKIT: 2018.03.1.dev1
> 	BOOST: 1_63

```python
smi = 'C' * 68000
mol = Chem.MolFromSmiles(smi, sanitize=False)
mol = Chem.RWMol(mol)
for i in reversed(range(mol.GetNumAtoms())):
    mol.RemoveAtom(i)
```

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-47-07f69b10a29c> in <module>()
>       1 smi = 'C' * 68000
>       2 mol = Chem.MolFromSmiles(smi, sanitize=False)
> ----> 3 mol = Chem.RWMol(mol)
>       4 for i in reversed(range(mol.GetNumAtoms())):
>       5     mol.RemoveAtom(i)
> 
> RuntimeError: Pre-condition Violation
> 	bond already exists
> 	Violation occurred on line 350 in file Code/GraphMol/ROMol.cpp
> 	Failed Expression: !(boost::edge(bond_pin->getBeginAtomIdx(), bond_pin->getEndAtomIdx(), d_graph).second)
> 	RDKIT: 2018.03.1.dev1
> 	BOOST: 1_63

I hereby propose to raise the atom index to `uint32`, although the `Mol` memory footprint might be a bit bigger. If this is not an option, then we need a validation of actual number of atoms when adding them.

**Comment by bp-kelley** [comment]
This is an implementation detail.  Changing it will not affect any code that uses the index.

I think we should just make the change.

----
Brian Kelley

**Comment by bp-kelley** [comment]
In any case, not throwing an error is an issue.  This is also related to the ring closure error.
