### ISSUE TITLE
Issue with sanitising large number of molecules containing sulphur group

### ISSUE THREAD

**Issue by samocooper** [rdkit/rdkit#1645]
**Description:**

- RDKit Version: 2017.03.2
- Platform: mac OSX, conda env

Having an issue calculating S valency when converting chemicals containing sulphur groups from smiles to molecules / sanitising. This issue also prevents valency being extracted from the S atom. Would be really grateful if someone could please help fix this or suggest a possible workaround.

This is effecting a large number of chemicals from excapeDB, an example of these is below:

[SH]=1(O)(=O)N=C2N(CC1)C=NC=3SC4=C(CCCC4)C23
[SH](O)(=O)(N1CCN(CC1)C(=O)C=2SC=CC2)=CCC
[SH](O)(=O)(=CC(=O)C=1C=CC=CC1)C2=CC=C(C=C2)C
ClC=1C=CC(C=2N=C(O)C=CC2[NH2](O)O)=CC1
[SH](O)(=O)(C1=C(N)C=CC=C1)=C(F)F
[SH](O)(=O)(N1CC(CCC1)C(=O)NC2CCCC2)=CC
[SH]1(O)(=O)=CC/C(=N\O)/C2=C1C=CC=C2
ON(=CC1=C(C(=C(C(=C1C)C)C)C)C)=C
S1C(C(N(C1=S)C)=N(O)=CC2=CC=CN=C2)(C)C
BrC1=CC=C([SH](O)(=O)=C(C=NCC)C#N)C=C1
ClC1=CC=C(OC(=O)C2CCN([SH](O)(=O)=CC)CC2)C=C1
[SH](O)(=O)(N1CCC(CC1)C(=O)N2CCOCC2)=CC
[SH](O)(=O)(N1N=C(C=C1N)C=2C=CC(=CC2)C)=CCC
ClC=1C(C=[SH](O)(=O)N2C(CCCC2)C)=CC=CC1
O=C1N(CCN(CC1)CC2=CC=CC=C2)CC=NN#N
[SH](O)(=O)(N1CCN(C2CCC(CC2)C)CC1)=CCC

```
temp_chem = Chem.MolFromSmiles('[SH](O)(=O)(N1CCN(C2CCC(CC2)C)CC1)=CCC',sanitize=False)
temp_chem = Chem.SanitizeMol(temp_chem)


> ValueError: Sanitization error: Explicit valence for atom # 0 S, 7, is greater than permitted
```

**Comment by proteneer** [comment]
You're missing formal charges on the Sulfur.
[SH](O)(=O)(N1CCN(C2CCC(CC2)C)CC1)=CCC should be
[SH+](O)(=O)(N1CCN(C2CCC(CC2)C)CC1)=CCC

**Comment by samocooper** [comment]
Ahh simple, thanks added brackets and formal charge and it works, I guess this is an issue with the excape dataset output format?

[SH+](=O)(N1CCN(C2CCC(CC2)C)CC1)=CCC

**Comment by samocooper** [comment]
given I'm now just writing out a set of rules to try and account for this is there any way a function could get added for doing this automatically for some more simple cases?

**Comment by samocooper** [comment]
This solution seem to work well:

https://gist.github.com/greglandrum/7f546d1e35c2df537c68a64d887793b8

Would be awesome to be formalised and brought into the package, for people like myself who are pretty useless at chemistry and had no idea formal charge relates to valency or even wha tthe two things really are :).

**Comment by greglandrum** [comment]
@samocooper: I'm glad that gist was helpful. I was going to suggest that.

We're unlikely to add this kind of functionality directly into the RDKit. There are just too many ways that molecules can be expressed incorrectly for the code to try to fix them all automatically without making mistakes. The general approach we take is to only make automated structure corrections when it's really, really obvious what was intended. There is a very small number of these.

In other cases, it's best when the person who understands the "strangeness" of their dataset can write a small script (like that gist above) that fixes things for their situation.
