### ISSUE TITLE
Fingerprints fail substructure test.

### ISSUE THREAD

**Issue by BetaRavener** [rdkit/rdkit#1646]
- RDKit Version: 2017.09.1
- Platform: Win10, 64bit

Hi, I'm trying to use fingerprints to speed up substructure searching, but I stumbled upon some strange behavior. From what I understand, fingerprints (at least those with bit representation) should be able to discard large set of molecules that don't contain pattern by simply checking if all bits set in pattern are set in molecule. There might be false positives (only full substructure algorithm can decide these), but fingerprints should never discard molecule that DOES contain the pattern. Considering this, I get rather surprising results from code below:
``` 
Match found: (0, 1, 2, 3, 4, 5, 6, 8, 9)
FP indicates match: False
#On bits in FP1: 17
#On bits in FP2: 19
```
In the sample code, I'm using these 2 structures:
1) https://pubchem.ncbi.nlm.nih.gov/compound/992
2) https://pubchem.ncbi.nlm.nih.gov/compound/13

One thing that doesn't even make sense for me is that the first structure, has less bits set than the second. It is impossible then to satisfy substructure condition. I extracted these from larger set after I noticed that I'm getting less matches than I should.

```
smiles1 = "C1(=C(C(=C(C(=C1Cl)Cl)Cl)Cl)Cl)O"
smiles2 = "C1=CC(=C(C=C1Cl)Cl)Cl"

mol1 = Chem.MolFromSmiles(smiles1)
mol2 = Chem.MolFromSmiles(smiles2)

print("Match found: {}".format(mol1.GetSubstructMatch(mol2)))

fp1 = Pairs.GetAtomPairFingerprintAsBitVect(mol1)
fp2 = Pairs.GetAtomPairFingerprintAsBitVect(mol2)

print("FP indicates match: {}".format((fp1 & fp2) == fp2))
print("#On bits in FP1: {}\n#On bits in FP2: {}".format(
    fp1.GetNumOnBits(), fp2.GetNumOnBits()
))
```
Also, I get the ~~same~~ result when I try to use `FingerprintMols.FingerprintMol` instead. ~~Now, the number of On bits is larger in first, but still no match indication.~~ After folding the molecule fingerprint to the size of pattern's fingerprint, it does indicate match:
```
Match found: (0, 1, 2, 3, 4, 5, 6, 8, 9)
FP indicates match: True
#On bits in FP1: 102
#On bits in FP2: 63
```
However, I also tried MACCS fingerprint before and while it's working for this combination, there are others where it will fail.

**Comment by bp-kelley** [comment]
You need to use the Pattern Fingerprints for substructure search filtering.  This is built into the SubstructLibrary.  In general it isn’t true that larger molecules contain all of the smaller substructure’s bits, this has to be a property of the fingerprint method

http://www.rdkit.org/Python_Docs/rdkit.Chem.rdSubstructLibrary.SubstructLibrary-class.html

See PatternHolder at the bottom of the documentation.

----
Brian Kelley

**Comment by BetaRavener** [comment]
You're right, I just realized that Atom Pairs fail for this task because shortest route between 2 atoms may be different in molecule and pattern. However, why would MACCS fail? I thought that these are crafted for the job.

And does this mean that the only valid way to create a fingerprint for substructure search is `PatternHolder.MakeFingerprint`? What kind of fingerprint does this make? 

Just for the sake of completeness, I have extracted MACCS example:
```
smiles1 = "CNC(=O)CCC(=O)C1=CN=CC=C1"
smiles2 = "C(CC=O)CN"
```
which are these:
1) https://pubchem.ncbi.nlm.nih.gov/compound/436
2) https://pubchem.ncbi.nlm.nih.gov/compound/118

produce this with `MACCSkeys.GenMACCSKeys` (note: I added code for printing total number of bits):
```
Match found: (4, 5, 6, 7, 2, 1)
FP indicates match: False
#bits in FP1: 167
#bits in FP2: 167
#On bits in FP1: 32
#On bits in FP2: 16
```

**Comment by BetaRavener** [comment]
I have spent most of the day trying to configure different fingerprints and see which worked for the substructure. I read [here](http://www.rdkit.org/UGM/2012/Landrum_RDKit_UGM.Fingerprints.Final.pptx.pdf) that at least **RDKit** and **Avalon** fingerprints should be suitable for substructure search, but they aren't. Only fingerprint method that worked for my tests is the one mentioned by @bp-kelley `Chem.PatternFingerprint`. Avalon performed better than RDKit FP comparing number of cases in which FPs missed, but then the test set is just 500 queries against database of 10000 (all from PubChem so I can reference them). Note that I couldn't find case where both fingerprints fail at the same time (using the other fingerprint in cases below leads to correct indication), so it seems like the algorithms have specific shortcomings. Is that correct? Why are then these fingerprints described as **substructure** in the presentation?

**Avalon fails for these:**
```
smiles1 = "CCN1C=CC(=NC1=O)NS(=O)(=O)C2=CC=C(C=C2)N"
smiles2 = "C1=C(NC(=O)N=C1)N"
```
1) https://pubchem.ncbi.nlm.nih.gov/compound/5322
2) https://pubchem.ncbi.nlm.nih.gov/compound/597
```
Match found: (4, 5, 6, 7, 8, 2, 3, 9)
FP indicates match: False
#bits in FP1: 2048
#bits in FP2: 2048
#On bits in FP1: 286
#On bits in FP2: 61
```
using:
`pyAvalonTools.GetAvalonFP(mol1, 2048, isQuery=False, bitFlags=pyAvalonTools.avalonSSSBits)` 
and 
`pyAvalonTools.GetAvalonFP(mol2, 2048, isQuery=True, bitFlags=pyAvalonTools.avalonSSSBits)`

**RDKit FP fails for these:**
```
smiles1 = "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CSC=C3)C(=O)O)C(=O)O)C"
smiles2 = "CC(C=O)C(=O)O"
```
1) https://pubchem.ncbi.nlm.nih.gov/compound/5471
2) https://pubchem.ncbi.nlm.nih.gov/compound/296
```
Match found: (13, 12, 10, 11, 18, 19, 20)
FP indicates match: False
#bits in FP1: 2048
#bits in FP2: 2048
#On bits in FP1: 235
#On bits in FP2: 20
```
using:
`Chem.RDKFingerprint(..., maxPath=5, fpSize=2048, nBitsPerHash=1, minSize=2048)`

**Comment by greglandrum** [comment]
I'm still wrapped up at a conference, so I'm replying slowly and in pieces.
Two quick things:

1) The pattern fingerprint is certainly designed to be a substructure fingerprint and is the one I recommend people use.
2) The Avalon example seems like it should work, so that may be a bug. I will investigate a bit more closely though.

**Comment by greglandrum** [comment]
Another quick one.
The public MACCS keys, at least as I understand them, are *not* a substructure fingerprint. An easy demonstration of why is provided by bit 84, which is defined to be `NH2`. In your example your query - `C(CC=O)CN` - has an NH2 group, but your molecule - `CNC(=O)CCC(=O)C1=CN=CC=C1`) - does not have an NH2 (it has an NH).

**Comment by greglandrum** [comment]
On the RDKit fingerprint. The slide you found from 2012 is, unfortunately, no longer accurate. The RDKit fingerprint uses aromaticity for both the atom and bond descriptions. This renders it unsuitable as a substructure fingerprint.

**Comment by BetaRavener** [comment]
Many Thanks!

For some reason I was in impression that hydrogens are ignored in the algorithms (and probably are in the full substructure search, hence the difference in MACCS example).

So, if I got it right, the RDKit FP is failing because the pattern is touching (one atom being part of) aromatic thiopene, and this gets encoded differently. I wonder if excluding aromaticity from encoded properties would make it possible to use this FP.

Anyway, I'll probably stick to pattern fingerprint, being the only option. The goal was to compare and select fingerprint which would provide best screening on average. For this, RDKit FP seemed to perform much better, but it does miss so the results are probably skewed. I'll leave this open if there is any development about Avalon but feel free to close it.

**Comment by greglandrum** [comment]
Yes, excluding aromaticity from both the atom and bond hashes would likely convert the RDKit fingerprint into a substructure fingerprint. I'm curious how you're determining that the RDKit FP is performing "much better" than the pattern FP; that certainly has not been my experience (see below). If you have some shareable examples where the pattern fp performs poorly it would be interesting to see if I can incorporate features from them into the pattern fp.

About screenout rates: have you seen the blog posts I've done on this topic already?

http://rdkit.blogspot.de/2013/11/fingerprint-based-substructure.html
http://rdkit.blogspot.de/2013/11/substructure-fingerprints-and-cartridge.html
http://rdkit.blogspot.de/2013/11/substructure-fingerprints-and-chembl.html

The jupyter notebooks for those are here:
https://github.com/greglandrum/rdkit_blog/tree/master/notebooks
