### ISSUE TITLE
RunReactants as a generator

### ISSUE THREAD

**Issue by hmarlo** [rdkit/rdkit#1648]
**Description:**

- RDKit Version: 2017.09.1
- Platform: Ubuntu 16.04 LTS (conda environment)

I need to merge two fragments which has undefined dummy links as you can see in the example. I check if a molecule is suitable and then break the loop and continue with the process. The type of links used leads to a huge number of molecules being created. I repeat this for a lot of pair fragments, so every time, `RunReactants` create a huge list of molecules. This decreases a lot the performance of the algorithm.

I'm wondering if there is another way to do the exact same thing (I tried with `CombineMols` and `RunReactant` but it isn't the same output), without having to create all the possible molecules. If not, I think that this function can return a generator, which will do the work every time is asked, not all at once, improving the performance of certain cases in which the full list is not required.

If the source were available in Python (as BRICS module do, for example), I will implement it myself and do the testing, but I don't know C++.

**Code:**

```
import rdkit
from rdkit.Chem.rdChemReactions import ReactionFromSmarts

reactants = (
    Chem.MolFromSmiles("[*]c1nnc([*])n1N"),
    Chem.MolFromSmiles("[*]S(=O)(=O)c1cccs1")
)

rxn = ReactionFromSmarts("[*]~[*:1].[*]~[*:2]>>[*:1]-[*:2]")
products = rxn.RunReactants(reactants)

for prod_group in products:
    for prod in prod_group:
        if is_suitable(prod):
            break

# Do something with the product
```

**Comment by bp-kelley** [comment]
The problem you are seeing is that the wildcard in the Smarts is matching
way more then you want.  A silly approach is to simply add isotopes to the
wildcards you want to match:

reactants = (
    Chem.MolFromSmiles("[1*]c1nnc([1*])n1N"),
    Chem.MolFromSmiles("[1*]S(=O)(=O)c1cccs1")
)

rxn = ReactionFromSmarts("[1*]~[*:1].[1*]~[*:2]>>[*:1]-[*:2]")
products = rxn.RunReactants(reactants)

for prod_group in products:
    for prod in prod_group:
        print Chem.MolToSmiles(prod, True)

outputs

[1*]c1nnc(n1N)S(=O)(=O)c1cccs1
[1*]c1nnc(n1N)S(=O)(=O)c1cccs1

Note that the left over wildcard is from the dummy atom that didn't match
which is why it has a isotope of 1.

Hopefully this helps.  If you don't want or can't add isotopes, I can show
you how to make a Reaction that does the same thing, although it is a bit
more complicated.

Cheers,
 Brian

**Comment by hmarlo** [comment]
Oh! So you are saying that the wildcards in the SMARTS not only match my SMILES wildarcs but all the atoms in both SMILES? Wow, now I understand why it leads to all these huge lists.

Thursday I will test it with isotopes, since I won't be able to do it tomorrow, I will post my results and close if needed. I think that isotopes will solve my problem :)

Thanks!

PD: the proposal of converting `RunReactants` in a generator still there :)

**Comment by hmarlo** [comment]
Hello again!

```
import rdkit
from rdkit import Chem
from rdkit.Chem.rdChemReactions import ReactionFromSmarts

reactants = (Chem.MolFromSmiles("[1*]c1nnc([1*])n1N"), Chem.MolFromSmiles("[1*]S(=O)(=O)c1cccs1"))

rxn = ReactionFromSmarts("[1*]~[*:1].[1*]~[*:2]>>[*:1]-[*:2]")
products = rxn.RunReactants(reactants)
```

Using the isotope strategy, the number of products reduced from 288 to 2, so the performance was great again :D Plus now the results are correct, because the links are used (these dummies come from BRICS).

Thank you!

PD: I close this issue.

**Comment by bp-kelley** [comment]
Making RunReactants be a generator is harder than it may seem as it is a C++ function wrapped via python.  There may be something clever we can do, but it is a low priority right now.

----
Brian Kelley
