### ISSUE TITLE
Move off of epydoc

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1656]
**Description:**

epydoc is python2 only and no longer maintained.

A suggestion on the debichem list was to look into the napoleon package for Sphinx:
http://sphinxcontrib-napoleon.readthedocs.io/en/latest/sphinxcontrib.napoleon.html

https://bitbucket.org/cedarsolutions/cedar-backup3/src/73037a2/util/sphinx-convert?fileviewer=file-view-default

**Comment by pronovic** [comment]
Just so there's a back-reference, I started this conversation in [Debian bug #881562](https://bugs.debian.org/881562).

**Comment by hmarlo** [comment]
Napoleon is already in the sphinx extensions http://www.sphinx-doc.org/en/stable/ext/napoleon.html, but I suggest to take a look at the official numpy sphinx package https://github.com/numpy/numpydoc . I've been working with both (numpydoc and sphinx.ext.napoleon), and the output is slightly different from numpydoc.

Sphinx is also the builder of Python docs, so while Python lives I think that sphinx will live too.

**Comment by greglandrum** [comment]
@hmarlo : we're already using sphinx for the majority of the documentation and to build the final packages. epydoc is just used for the automatically generated Python API docs.

**Comment by hmarlo** [comment]
Ops! My bad.

Then yeah, napoleon and numpydoc are really powerful to generate the reference for the API based on docstrings as epydoc.

**Comment by greglandrum** [comment]
I'm doing some work on this issue on this branch:
https://github.com/greglandrum/rdkit/tree/dev/usinx_sphinx_autodoc
