### ISSUE TITLE
Test 130 Failure for 2017_09_01 on i386 arch

### ISSUE THREAD

**Issue by giallu** [rdkit/rdkit#1661]
**Description:**
Test 130 fails on i386 arch like this (x86_64 passed it)

130: ======================================================================
130: FAIL: testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable (__main__.TestCase)
130: ----------------------------------------------------------------------
130: Traceback (most recent call last):
130:   File "UnitTestMol3D.py", line 218, in testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable
130:     self.assertEqual(smiles, expected)
130: AssertionError: Items in the first set but not the second:
130: 'C/C(F)=C/[C@@H](Cl)/C=C(\\Br)[C@@H](N)I'
130: 'C/C(F)=C\\[C@H](Cl)/C=C(\\Br)[C@@H](N)I'
130: Items in the second set but not the first:
130: 'C/C(F)=C/[C@@H](Cl)/C=C(/Br)[C@@H](N)I'
130: 'C/C(F)=C/[C@H](Cl)/C=C(\\Br)[C@H](N)I'

**Comment by greglandrum** [comment]
Ah the fun of still needing to support 32bit systems.
I suspect that both this and #1662 are caused by the same problem. Should be an easy fix.

**Comment by giallu** [comment]
And I didn't even start filing the test failures for ARM...

**Comment by greglandrum** [comment]
Yeah, I can imagine that those will be numerous and painful. Is there a way I could get access to those test machines so that I can help deal with that?

**Comment by giallu** [comment]
Package maintainers have SSH access to some resources that could help: https://fedoraproject.org/wiki/Test_Machine_Resources_For_Package_Maintainers
but I need to ask whether I am allowed to put a (trusted) upstream in the ssh allowed keys. If not, we can still work it out something different.
However, I think most issues are related the the ones I opened; in fact, until the 2016.09.04  tests passed on all architectures (and boy, we have quite some of them... https://koji.fedoraproject.org/koji/buildinfo?buildID=861476).
BTW, if you think I can collect more/different info just let me know where to look and I will do.
Thanks for you help
