### ISSUE TITLE
EnumerateStereoisomers test failure on i386 arch

### ISSUE THREAD

**Issue by giallu** [rdkit/rdkit#1662]
**Description:**
RDKit 2017_09_01
Test 130 fails on i386 arch (x86_64 is fine) as follows:

130: ======================================================================
130: FAIL: EnumerateStereoisomers (rdkit.Chem.EnumerateStereoisomers)
130: Doctest: rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
130: ----------------------------------------------------------------------
130: Traceback (most recent call last):
130:   File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
130:     raise self.failureException(self.format_failure(new.getvalue()))
130: AssertionError: Failed doctest test for rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
130:   File "/builddir/build/BUILD/rdkit-Release_2017_09_1/python2/rdkit/Chem/EnumerateStereoisomers.py", line 97, in EnumerateStereoisomers
130: 
130: ----------------------------------------------------------------------
130: File "/builddir/build/BUILD/rdkit-Release_2017_09_1/python2/rdkit/Chem/EnumerateStereoisomers.py", line 189, in rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
130: Failed example:
130:     for smi in sorted(Chem.MolToSmiles(x, isomericSmiles=True) for x in isomers):
130:         print(smi)
130: Expected:
130:     F[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)Br
130:     F[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)Br
130:     F[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)Br
130: Got:
130:     F[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)Br
130:     F[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)Br
130:     F[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)Br
130: 
130: 
130: ----------------------------------------------------------------------

**Comment by greglandrum** [comment]
@giallu : since I don't have straightforward access to a 32bit machine for testing: would you be able to test a proposed fix before we merge it?

**Comment by giallu** [comment]
Sure. Just point me to the patchset and I will let you know.
