### ISSUE TITLE
the deb packages created from sources install libraries under a different name

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1666]
Hello,

When using cpack -G DEB, the produced packages install
/usr/lib/libRDKitRDGeneral.so
instead of
/usr/lib/libRDGeneral.so (that's what the vanilla Ubuntu debs install).

This is not supposed to be the case.
How can I change this?

Regards,
F.

**Comment by UnixJunkie** [comment]
@psavery

**Comment by UnixJunkie** [comment]
related to https://github.com/rdkit/rdkit/pull/1655 and https://github.com/rdkit/rdkit/pull/1580

**Comment by greglandrum** [comment]
The renaming of the libraries happened a couple of releases ago. The Debian version is from before this change was made

**Comment by greglandrum** [comment]
Specifically: the change was in the 2017.03 release cycle

**Comment by UnixJunkie** [comment]
ok, sorry for the noise then
