### ISSUE TITLE
NumAmideBonds descriptor missing

### ISSUE THREAD

**Issue by malteseunderdog** [rdkit/rdkit#1670]
I am showing some students how to do a PCA on molecular descriptors, so I am using the ones from http://www.rdkit.org/docs/GettingStartedInPython.html#list-of-available-descriptors

Mostly this is ok, but I can't get NumAmideBonds -- is this not accessible via Descriptors?

Apologies if I am missing something obvious.

```
import rdkit 
from rdkit import rdBase
print(rdBase.rdkitVersion)
from rdkit.Chem import Descriptors
m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
Descriptors.NumHAcceptors(m)
Descriptors.NumAmideBonds(m)
```

Output:

> 2017.09.1
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-13-7f5d497b2281> in <module>()
>       5 m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
>       6 Descriptors.NumHAcceptors(m)
> ----> 7 Descriptors.NumAmideBonds(m)
> 
> AttributeError: module 'rdkit.Chem.Descriptors' has no attribute 'NumAmideBonds'

**Comment by bp-kelley** [comment]
@malteseunderdog You aren't missing anything obvious, although the functionality you want is available in a non-obvious way.
@malteseunderdog, There are really two places to get descriptors in the RDKit one is the Descriptors module the other is the rdMolDescriptors module.

It looks like these are a bit out of sync.

```
from rdkit.Chem import rdMolDescriptors
from rdkit.Chem import MolFromSmiles
print (rdMolDescriptors.CalcNumAmideBonds(MolFromSmiles("O=CNC")))
```

**Comment by jp-uom** [comment]
Do you think there is a case to be made for accessing all descriptors from one place (say Descriptors?).  Or at least point out that, unlike the other Descriptors listed in the Getting Started guide, this comes from elsewhere?

**Comment by bp-kelley** [comment]
At the minimum there should be a comprehensive descriptor list available.  There is a function in Descriptors.py "fr_amide" which does the same work, but it isn't that obvious what it does.  I agree in principle that Descriptors should have access to most of the calculations it not all.

I'll talk to @greglandrum about it.

**Comment by MaxGreil** [comment]
Hi @bp-kelley  / @greglandrum ,
I would like to take on this issue. Can you please explain what needs to be done here?

**Comment by joseerlang** [comment]
Could you explain me briefly what you intend to solve in the ticket? it seems that you want to move or wrapper the calculations done in rdMolDescriptors to Descriptors but I am not sure. I am very beginner in the project.
