### ISSUE TITLE
NameError: name 'kekulize' is not defined

### ISSUE THREAD

**Issue by psychemedia** [rdkit/rdkit#1675]
**Description:**

- RDKit Version: 2017.09.1 from anaconda
- Platform: Linux

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/srv/conda/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    307             method = get_real_method(obj, self.print_method)
    308             if method is not None:
--> 309                 return method()
    310             return None
    311         else:

/srv/conda/lib/python3.6/site-packages/rdkit/Chem/Draw/IPythonConsole.py in _toSVG(mol)
    113   else:
    114     highlightAtoms = []
--> 115   return Draw._moltoSVG(mol,molSize,highlightAtoms,"",kekulize)
    116 
    117 

NameError: name 'kekulize' is not defined
```

```
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG=True

# displaying an SVG structure (in a Jupyter notebook)
mol = Chem.MolFromSmiles('O=C(O)c1ccccc1OC(=O)C')
mol
```

[mybinder example](https://mybinder.org/v2/gh/psychemedia/showntell/chemistry?filepath=index_chemistry.ipynb)

**Comment by greglandrum** [comment]
This is a duplicate with #1625 . It's already fixed and will be in the 2017_09_2 release.

**Comment by EswarKalaga** [comment]
Hi, I am trying to read an sdf file using rdkit , please see the code below. Thanks in advance.
Input: suppl = SDMolSupplier('Desktop\svm_figures\One.sdf')
Output:
NameError                                 Traceback (most recent call last)
<ipython-input-3-ddfd84893a4e> in <module>
----> 1 suppl = SDMolSupplier('Desktop\svm_figures\One.sdf')

NameError: name 'SDMolSupplier' is not defined

**Comment by greglandrum** [comment]
@EswarKalaga : This is a basic Python question, not an RDKit question. We can’t provide Python training here. Please take a look at the RDKit documentation, particularly the “Getting started in Python” document. That should help.
