### ISSUE TITLE
Mol with query atom cannot be pickled.

### ISSUE THREAD

**Issue by googhgoo** [rdkit/rdkit#1678]
- RDKit Version: 2017.03.1.dev1
- Platform: Tried in both Linux and Windows 8

Hello, I have trouble pickling molecule with query atoms. For example,

```
from rdkit import Chem
from rdkit.Chem import rdqueries
import pickle
mol = Chem.RWMol(Chem.Mol())
atom = rdqueries.HasPropQueryAtom('foo')
mol.AddAtom(atom)
pickle.dumps(mol)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/shared/python/2.7.8/lib/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/opt/shared/python/2.7.8/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/shared/python/2.7.8/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
RuntimeError: std::exception
```
I also tried setting pickle option for rdkit:
"""
Chem.SetDefaultPickleProperties(rdkit.Chem.rdchem.PropertyPickleOptions.QueryAtomData)
Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)
"""
These two options don't help...

**Comment by bp-kelley** [comment]
Geun - I think it is that subset of query atoms that can't be pickled, not
all query atoms.  I added the HasPropQueryAtom without making the
corresponding pickler.

For example:

>>> atom = rdqueries.AtomNumEqualsQueryAtom(0)

>>> mol.AddAtom(atom)

0

>>> pickle.dumps(mol)

"crdkit.Chem.rdchem\nRWMol\np0\n(S'\\xef\\xbe\\xad\\xde\\x00\\x00\\x00\\x00\\x08\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x80\\x01\\x00\\x10\\x19\\r\\x00\\x00\\x00AtomAtomicNum!\\x1a\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x1c\\x00+\\x0b\\x17\\x00\\x00\\x00\\x00\\x16'\np1\ntp2\nRp3\n."

@greg we should make it a feature request to add the missing rdqueries if
possible.

**Comment by googhgoo** [comment]
Aaah okay, I figured.. that not all queries work. I'm planning on writing a wrapper around mol->pickle so I'm okay, but that feature would certainly be nice!
