### ISSUE TITLE
Can rdkit set parameter for fuzzy bond match in Substructure

### ISSUE THREAD

**Issue by luckboylys** [rdkit/rdkit#1680]
1、I define a bond that is a ring bond in query structure, but there is a chain bond in results
![qq 20171205125458](https://user-images.githubusercontent.com/34260484/33590605-8f836bee-d9bb-11e7-8b7f-b22fb21c8c8a.jpg)

2、I define a bond that is a aromatic bond in query structure, but there is a double bond in results
![qq 20171205130114](https://user-images.githubusercontent.com/34260484/33590765-668614fc-d9bc-11e7-90f5-46b09ed77e04.jpg)

How do I set parameter for fuzzy bond match（especially aromatic bond 、chain bond and ring bond）

**Comment by bp-kelley** [comment]
We would have to see the mol blocks or smarts that the sketcher is
outputting.  The sketcher kind of looks like MarvinSketch.  If this is the
case you can ask for "smarts" from marvin assuming you have the full
package.

The smarts output from the partial aromatic is "[#6]-1-[#6]-[#6]-cc-[#6]-1"
which works as I expect.

For the ring bond example it is "[H]\[#6]([H])=[#6](@/[#6])@-[#6]" which
oddly has stereochemistry which is really not applicable here (might have
to ping chemaxon on that one).

Note you may have to call MergeQueryHs if you allow sketching of explicit
hydrogens.

I hope this helps.

 -Brian
