### ISSUE TITLE
Stereo information lost

### ISSUE THREAD

**Issue by marinaglr** [rdkit/rdkit#1685]
Hi,
I am using the following C++ script to read a molecule from a SD file (with defined stereochemistry), but the information about the stereochemistry gets lost. The file I am using is from glucose (ZINC03833800; http://zinc.docking.org/substance/3833800)
When I check the chiral information of the atoms, all of them have the chiral tag 0.

How can I keep the stereo information?

SCRIPT:
```
std::fstream infilestr;
infilestr.open(in_file_name.c_str( ));

RDKit::SDMolSupplier mol_supplier( in_file_name , true );

for (unsigned i = 0; i < mol_supplier.length(); ++i) {
        RDKit::ROMOL_SPTR mol(mol_supplier[i]);

        if (!mol){
            std::cout << "Error, molecule not found!" << std::endl;
            continue;
        }


        for (unsigned int j = 0; j < mol->getNumAtoms(); j++){
            RDKit::Atom* atom = mol->getAtomWithIdx(j);
            std::cout << "Chirality atom " << j+1  << ": " << atom->getChiralTag() << std::endl;
        }

        std::string usmiles = RDKit::MolToSmiles (*mol);
        std::cout << "Mol: " << usmiles << std::endl;
}
```

OUTPUT FOR GLUCOSE (ZINC03833800):

Chirality atom 1: 0
Chirality atom 2: 0
Chirality atom 3: 0
Chirality atom 4: 0
Chirality atom 5: 0
Chirality atom 6: 0
Chirality atom 7: 0
Chirality atom 8: 0
Chirality atom 9: 0
Chirality atom 10: 0
Chirality atom 11: 0
Chirality atom 12: 0
Mol: OCC1OC(O)C(O)C(O)C1O

**Comment by greglandrum** [comment]
There are a couple of things going on here.
Currently if you want the RDKit to figure out the stereochemistry from the 3D coordinates, you need to make a call to `MolOps::assignStereochemistryFrom3D()` after reading in the molecule.
If you do this, the individual atoms should have chirality present.
If you want to see that chirality in the SMILES, you need to set the optional second argument to `MolToSmiles`: `std::string usmiles = RDKit::MolToSmiles(*mol,true)`

These defaults are set as they are for historical reasons and we're in the process of changing them as part of #1679.

**Comment by marinaglr** [comment]
Thanks for your answer!
But I would need to read the stereochemistry information from the SD file and not calculate the chirality from the coordinates, since this way the information about racemates would get lost.
Is there a way to do that?
