### ISSUE TITLE
Play nice with naughty MOL blocks

### ISSUE THREAD

**Issue by jw-feng** [rdkit/rdkit#1689]
**Description:**

- RDKit Version:  2017.09.1
- Platform:  Python 3.6.2 on CentoOS 7

RDKit's SD file reader errors on MOL blocks that insert a blank line before "M END".  I don't think inserting a blank line is fully compliant with MDL's CTfile format.  However, some chemical editor does insert a blank line and that results in RDKit throwing an error trying to convert a blank line into an int.  Can you make RDKit play nice when there is a blank line before "M END".  Attached is a SD file of ethyl and it contains an offending blank line in line 8.  Many other programs including ChemDraw, openbabel, pymol, MOE read the attached file without error.

Below is code to reproduce this error: " ERROR: Cannot convert  to int on line 8" error

```
from rdkit import Chem
suppl=Chem.SDMolSupplier("rdkit_blank_line_before_M_END_test.sdf")
for mol in suppl:
   Chem.MolToSmiles(mol)

```

In addition to code above, I also attached a test script.  
[rdkit_test_reader.py.zip](https://github.com/rdkit/rdkit/files/1569010/rdkit_test_reader.py.zip)

Attached is the input file.
[rdkit_blank_line_before_M_END_test.sdf.zip](https://github.com/rdkit/rdkit/files/1569005/rdkit_blank_line_before_M_END_test.sdf.zip)

To reproduce the error, execute "rdkit_test_reader.py -in rdkit_blank_line_before_M_END_test.sdf"

**Comment by greglandrum** [comment]
@jw-feng : out of curiosity, which programs generate these?

**Comment by jw-feng** [comment]
@greglandrum: these molecules are sent to me in a SD file generated by a partner.  I believe they are exported by ISIS for Excel.
Looking at MolFileParser.cpp, changing line 1462 from 
` if (lineBeg != "M  END") `
to 
```
 //make sure line length is not 0
 if (lineBeg != "M  END" && lineBeg.length()>0)
```
maybe sufficient to fix this problem.

**Comment by gjgetzinger** [comment]
> @jw-feng : out of curiosity, which programs generate these?

I am getting a similar error for sdf files described as "NIST compatible". 
Examples can be found here: [mona.fiehnlab.ucdavis.edu](http://mona.fiehnlab.ucdavis.edu/downloads)

**Comment by greglandrum** [comment]
@gjgetzinger The RDKit should now be able to parse these correctly.

**Comment by gjgetzinger** [comment]
@greglandrum Is it a problem with my version of rdkit? 
```bash
Python 3.7.1 | packaged by conda-forge | (default, Feb 25 2019, 21:02:05) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> from rdkit import rdBase
>>> rdBase.rdkitVersion
'2018.09.2'
>>> from rdkit import Chem
>>> suppl = Chem.SDMolSupplier('MoNA-export-LC-MS-MS_Positive_Mode.sdf')
>>> len(suppl)
61709
>>> mols = [x for x in suppl if x is not None]
[10:48:42] ERROR: Cannot convert >   to int on line 42
[10:48:42] ERROR: moving to the begining of the next molecule
```
Lots more error messages...
```python
>>> len(mols)
0
```
