### ISSUE TITLE
Acetylenic hydrogens not given appropriate 2D coordinates

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#1691]
The R-C-H angle should be 180 degrees, but comes out much differently.

```
m = Chem.MolFromSmiles('CCCCCC#C')
m2=Chem.rdmolops.AddHs(m)
m2
```

![image](https://user-images.githubusercontent.com/16337306/34131906-3676fe8c-e413-11e7-96df-853b43e7bceb.png)

**Comment by greglandrum** [comment]
Confirmed. There's a similar problem with just `C#C`.
Curiously `FC#CF` is fine, so it's not just a problem with `C#C` with a single extra substituent on one (or both) of the Cs.

**Comment by greglandrum** [comment]
The fix that was just merged covers that one too.
