### ISSUE TITLE
AUTOCORR2D.h not installed unless RDK_BUILD_DESCRIPTORS3D but is required

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1702]
MolDescriptors.h has the line:
```
#include <GraphMol/Descriptors/AUTOCORR2D.h>
```
but this header file is only installed if the Cmake build flag "RDK_BUILD_DESCRIPTORS3D" was specified. Where this is not specified, importing MolDescriptors.h causes a build error in client code.

A potential fix would be to put an #ifdef guard around the line above and any others that are dependent on the cmake build flag. Alternatively, if that is not a 3D descriptor, it should perhaps be installed even where RDK_BUILD_DESCRIPTORS3D is False.

**Comment by greglandrum** [comment]
Nice catch @baoilleach. Thanks!

It looks like the autocorr2d descriptors should work without eigen being available (this is the main technical reason to not include the 3D descriptors all the time). I'll try enabling them all the time.

**Comment by bp-kelley** [comment]
For some reason I thought we have fixed this a while ago.  Perhaps it was
never merged.  Thanks for the catch!
