### ISSUE TITLE
MACCSKeys() generates 167 binary values?

### ISSUE THREAD

**Issue by qks1lver** [rdkit/rdkit#1726]
**Description:**
I'm new to analyzing chemical structures, and I'm trying to generate MACCS keys with rdkit. Based on my understanding MACCS keys should have 166 binary values but when I tried it with MACCSkeys.GenMACCSKeys(), it returned a variable with 167 binary elements. Based on the source code (MACCSkeys.py), it looks like index 0 should just be ignored, because it's really setting values to positions 1 to 166... I'm guessing for ease of use. Please correct me if I'm wrong. Thank you!

- RDKit Version: 2017.09.3
- Platform: Python 3.6.4 on Red Hat Enterprise Linux Server release 6.6 (Santiago)

```
>>> from rdkit import Chem
>>> from rdkit.Chem import MACCSkeys
>>> key = MACCSkeys.GenMACCSKeys(Chem.MolFromSmiles('C1(=C(SSC1=O)Cl)Cl'))
>>> len(key)
167
```

**Comment by adalke** [comment]
Your understanding is correct. RDKit preserves the MACCS key numbers, so that MACCS key 23 (for example) is bit number 23. Bit 0 is always unset and may be ignored. Only bits 1-166 will be set.

**Comment by qks1lver** [comment]
Thanks for the verification!
