### ISSUE TITLE
xlocale.h not needed to compile with clang

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#1728]
clang-4.0 fails to compile Code/RDGeneral/LocaleSwitcher.cpp on a newly installed Ubuntu box because of a "fatal error: 'xlocale.h' not found". I commented out the clang-only <xlocale.h> that @giallu suggested in the thread at https://github.com/rdkit/rdkit/pull/1494 , and it compiles without a problem.

It compiled just fine with gcc.

This system uses glibc 2.26-0ubuntu2.1 which is why it doesn't have an xlocale.h (as the thread says, that header file was removed in glibc 2.26). A "find /usr -name xlocal.h -print" fails to find that header file.

- RDKit Version: 2017_09_03
- Platform: Ubuntu 17.10
- C++ compiler: clang++ 4.0.1-6
- libc: glibc 2.26-0ubuntu2.1

**Comment by greglandrum** [comment]
Thanks for the bug report @adalke
