### ISSUE TITLE
Issue with unicode characters in filenames for MolFromMol2File

### ISSUE THREAD

**Issue by pyeguy** [rdkit/rdkit#1729]
**Description:**

- RDKit Version: '2017.09.3'
- Platform: Windows 10 (Anaconda Python 3.6) 

I'm working with a database of individual mol2 files where the compound name is the file name. While attempting to read them in I discovered that `Chem.MolFromMol2File` can't seem to handle unicode in the file name. 

If you open the file and use the mol2 block `string` everything is copacetic. Might be an acceptable work around?

```python
file_name = "(-)-ent-12b-hydroxykaur-16-en-19-oic acid,19-O-beta-D-xylopyranosyl-(1í≈6)-O-beta-D-glucopyranoside.mol2"
In [23]: path_to_file = os.path.join(folder,fname)

In [24]: Chem.MolFromMol2File(path_to_file)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-24-09515c9c97e6> in <module>()
----> 1 Chem.MolFromMol2File(path_to_file)

OSError: Bad input file TCMcmps\(-)-ent-12b-hydroxykaur-16-en-19-oic acid,19-O-beta-D-xylopyranosyl-(1í≈6)-O-beta-D-glucopyranoside.mol2

In [25]: block = open(path_to_file).read()

In [26]: Chem.MolFromMol2Block(block)
Out[26]: <rdkit.Chem.rdchem.Mol at 0x28b0fd23f80>

```

**Comment by greglandrum** [comment]
I can't manage to reproduce this. Using that filename works fine for me on both windows and linux if I create the file first and try to read from it.
The `OSError` indicates that the file does not exist. Are you sure that there is a file with that name?

**Comment by pyeguy** [comment]
hmm that's interesting... there was definitely a file there with that name b/c  
 `block=open(path_to_file).read()`  worked just fine... Python & Unicode make my head hurt sometimes... I'll dig in a little more and see if i can figure out what's going on...
