### ISSUE TITLE
rdmolfiles.CanonicalRankAtoms segfaults on 0 atom molecules.

### ISSUE THREAD

**Issue by lilleswing** [rdkit/rdkit#1735]
**Description:**

- RDKit Version:2017.09.01
- Platform:64 bit linux ubuntu installed through conda install -c rdkit rdkit=2017.09.01

``` python
from rdkit import Chem
from rdkit.Chem import rdmolfiles
from rdkit.Chem import rdmolops

mol = Chem.MolFromSmiles("")
print(mol) # <rdkit.Chem.rdchem.Mol object at 0x7fa4e203c670>
new_order = rdmolfiles.CanonicalRankAtoms(mol) # This segfaults
mol = rdmolops.RenumberAtoms(mol, new_order)
```

rdmolfiles.CanonicalRankAtoms(mol) segfaults upon 0 atom molecules.  I think it should either return an empty list or throw a ValueError.

**Comment by bp-kelley** [comment]
Thanks for letting us know.  I’ll fix this later today and make a pr

**Comment by bp-kelley** [comment]
It looks like RenumberAtoms is the culprit here.

```
>>> from rdkit import Chem
>>> mol = Chem.RWMol()
>>> mol = rdmolops.RenumberAtoms(mol, [])
```

**Comment by bp-kelley** [comment]
There were two issues that needed to be resolved.  One in rank atoms, one in renumber.
