### ISSUE TITLE
removeHs removing bond stereo atoms

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#1737]
**Description:**

Using RDKit release 2017_09_2

I'm trying to set double bond stereochemistry by setting the stereo atoms and the bond stereo value.  This seems to work, and it's respected by the depiction and embedding code.  But if I try to remove the hydrogens, then it gets removed.

void testCis() {

	RWMol *mol = new RWMol();

	for (int i : {17, 6, 6, 17, 1, 1}) {
		mol->addAtom();
		mol->getLastAtom()->setAtomicNum(i);
	}
	mol->addBond(0,1,Bond::BondType::SINGLE);
	mol->addBond(1,2,Bond::BondType::DOUBLE);
	mol->addBond(2,3,Bond::BondType::SINGLE);
	mol->addBond(1,4,Bond::BondType::SINGLE);
	mol->addBond(2,5,Bond::BondType::SINGLE);

	mol->getBondWithIdx(1)->setStereoAtoms(0,3);
	mol->getBondWithIdx(1)->setStereo(Bond::BondStereo::STEREOZ);

	MolOps::sanitizeMol(*mol); // this had no effect on the problem at hand

	mma::mout << mol->getBondWithIdx(1)->getStereoAtoms().size()  << std::endl;
	// prints 2

	RWMol *copy = new RWMol(*mol);
	MolOps::removeHs(*copy); // changing the options here seemed to have no effect
	mma::mout << copy->getBondWithIdx(1)->getStereoAtoms().size()  << std::endl;
	// prints 0

	delete mol;
	delete copy;
}

Obviously in this case I could just create the molecule without the hydrogens from the start, but this brings up the fact that setting the stereo atoms and bond stereo doesn't seem to be enough to **really** set the bond stereo.  From experimenting it seems the only way to set the bond stereo manually is by adjusting the directions of the single bonds, but that seems to get hairy if you have multiple double bonds.

**Comment by greglandrum** [comment]
As you've discovered, manipulating double bond stereochemistry is decidedly non-trivial.
There's an active PR (#1626) that I'm working on with @coleb that will help with some of this, but it's never going to be super simple.
