### ISSUE TITLE
deprecated apply() function causes GetRDKFingerprint to fail in Python 3

### ISSUE THREAD

**Issue by clinntt** [rdkit/rdkit#1747]
**Description:**

- RDKit Version: 2017.09.3
- Platform: Python 3.6.1 in Jupyter Notebook on Mac OS 10.13.13

I am getting **'NameError: name 'apply' is not defined'** for

```
from rdkit import Chem
from rdkit.Chem import Fingerprints
from rdkit.Chem.Fingerprints import FingerprintMols

mol = Chem.MolFromSmiles("CC(C)=O")
FingerprintMols.GetRDKFingerprint(mol)
```
The full error returned by Jupyter Notebook is -

> <ipython-input-5-5724b23cae09> in <module>()
>       4 
>       5 mol = Chem.MolFromSmiles("CC(C)=O")
> ----> 6 FingerprintMols.GetRDKFingerprint(mol)
> 
> /Users/clinntt/anaconda3/lib/python3.6/site-packages/rdkit/Chem/Fingerprints/FingerprintMols.py in GetRDKFingerprint(mol)
>      45   """ uses default parameters """
>      46   details = FingerprinterDetails()
> ---> 47   return apply(FingerprintMol, (mol, ), details.__dict__)
>      48 
>      49

**Comment by adalke** [comment]
A few other places use apply():
```
Fingerprints/FingerprintMols.py
47:  return apply(FingerprintMol, (mol, ), details.__dict__)
223:      fps = apply(FingerprintsFromSmiles, (data, idCol, smiCol), details.__dict__)
225:      fps = apply(FingerprintsFromPickles, (data, idCol, smiCol), details.__dict__)
227:    fps = apply(FingerprintsFromMols, (dataSet, ), details.__dict__)

Fingerprints/MolSimilarity.py
59:    probeFp = apply(FingerprintMols.FingerprintMol, (mol, ), details.__dict__)
167:      probeFp = apply(FingerprintMols.FingerprintMol, (mol, ), details.__dict__)
```

It looks like these should be replaced with variations of FingerprintMol(mol, **details.__dict__)

There are also uses under rdkit/sping:
```
rdkit/sping/pid.py
521:        pointList.extend(apply(self.arcPoints, args))
523:        pointList.extend(apply(self.curvePoints, args))

rdkit/sping/TK/pidTK.py
207:    apply(tk.Canvas.__init__, (self, master), kw)  # use kw to pass other tk.Canvas options
414:        new_item = apply(self.create_line, pointlist, d)
425:        new_item = apply(self.create_line, pointlist, d)
470:      self._tkcanvas = apply(TKCanvas, (size, name, master), kw)
```
