### ISSUE TITLE
out of range fromAtom causes GetMorganFingerprintAsBitVect to segfault

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#1749]
GetMorganFingerprintAsBitVect does not check if the fromAtoms elements are in range. The following:
```
import sys
from rdkit import Chem
from rdkit.Chem import rdMolDescriptors

mol = Chem.MolFromSmiles("c1ccccc1O")
for i in range(10000):
    sys.stderr.write("\rdied at %d  " % i)
    rdMolDescriptors.GetMorganFingerprintAsBitVect(mol, 3, fromAtoms=[i])
```

generates output like "died at 192  Segmentation fault". (The number varies depending on the state of memory).

The other fingerprinters (GetHashedTopologicalTorsionFingerprintAsBitVect, GetHashedAtomPairFingerprintAsBitVect, and RDKFingerprint) do not have this problem. They instead raise a ValueError("list element larger than allowed value").

This is most likely because GetMorganFingerprintAsBitVect does:
```
  std::vector<boost::uint32_t> *froms = 0;
  if (fromAtoms) {
    unsigned int nFrom =
        python::extract<unsigned int>(fromAtoms.attr("__len__")());
    if (nFrom) {
      froms = new std::vector<boost::uint32_t>();
      for (unsigned int i = 0; i < nFrom; ++i) {
        froms->push_back(python::extract<boost::uint32_t>(fromAtoms[i]));
      }
    }
  }
```
instead of the size-checking code the other fingerprinters use, which is:
```
  rdk_auto_ptr<std::vector<boost::uint32_t> > fvect =
      pythonObjectToVect(fromAtoms, mol.getNumAtoms());
```

**Comment by greglandrum** [comment]
Confirmed. I'll have the fix done shortly.
