### ISSUE TITLE
python tests fail

### ISSUE THREAD

**Issue by cmauney** [rdkit/rdkit#1753]
**Description:**

I've built on a machine, using my own boost installation. I've set up the RDBASE and python/lib directories correctly. It builds without errors.

When I try
```
$>python
>>> from rdkit import rdBase
```

I get the error:

ImportError: dlopen($RDBASE/rdkit/rdBase.so, 2): Library not loaded: libRDKitRDBoost.1.dylib
  Referenced from: $RDBASE/rdkit/rdBase.so
  Reason: image not found

I can see libRDKitRDBooks.1.dylib in $RDBASE/lib

**Comment by greglandrum** [comment]
This looks like you haven't set `DYLD_FALLBACK_LIBRARY_PATH` to include `$RDBASE/lib`

**Comment by cmauney** [comment]
running 

$>DYLD_FALLBACK_LIBRARY_PATH=$RDBASE/lib python

results in the same error.

**Comment by gedeck** [comment]
Can you try this:
```
RDBASE=$RDBASE DYLD_FALLBACK_LIBRARY_PATH="$RDBASE/lib" PYTHONPATH=$RDBASE  python
```

**Comment by cmauney** [comment]
I did try, same result.

However, I have make progress. First, I switched from the MacPort installation of python to the apple version:

```
$> port select --list python
Available versions for python:
	none
	python26-apple
	python27 (active)
	python27-apple
$> sudo port select --set python python27-apple
Selecting 'python27-apple' for 'python' succeeded. 'python27-apple' is now active.
```

this gives the new message for the error:

```
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/share/RDKit/rdkit/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: dlopen(/usr/local/share/RDKit/rdkit/rdkit/rdBase.so, 2): Library not loaded: libRDKitRDGeneral.1.dylib
  Referenced from: /usr/local/share/RDKit/rdkit/lib/libRDKitRDBoost.1.dylib
  Reason: unsafe use of relative rpath libRDKitRDGeneral.1.dylib in /usr/local/share/RDKit/rdkit/lib/libRDKitRDBoost.1.dylib with restricted binary
>>>
```

after some digging it seems I need to do things like:

`$> sudo install_name_tool -change libboost_atomic.dylib /usr/local/lib/libboost_atomic.dylib /usr/local/share/RDKit/rdkit/rdkit/rdBase.so`

However, this is tedious, and appears to need doing on EVERY rdkit library (which link to many of the same boost libraries).

Obviously, there should be something in the configure/build process that does this. is there?

**Comment by greglandrum** [comment]
I believe that cmake builds normally do this.
