### ISSUE TITLE
Create test cases in rdkit.Avalon

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1760]
At the moment the only testing of the AvalonTools integration is together with the wrapper build in `$RDBASE/External/AvalonTools/Wrap`. We should also have some test code available in `$RDBASE/rdkit/Avalon`.

Ideally these tests will include a collection of molecules that fail some of the struchk tests. These can be stored in SMILES or SD files in `$RDBASE/rdkit/Avalon/test_data`.

**Comment by joseerlang** [comment]
Hi Greg,
I'm just starting with the project, my background is Java and C, but I think this ticket can come in handy to deepen in the Avalon tool. I wanted to ask you 2 things:

-  Is the test context you want to introduce in rdki/Avalon/ something similar to what you already have in def testStruChk(self) of the testAvalonTools.py file? 

-  Would you consider upgrading the Avalon Toolkit project to an updated Java framework version. I have seen that the original source code is deployed as war inside a tomcat and is a bit outdated from current standards.
