### ISSUE TITLE
3 Error got when running ctest after installed in Windows 10

### ISSUE THREAD

**Issue by NKUCodingCat** [rdkit/rdkit#1766]
**Description:**

- RDKit Version: 2017.09.3
- Platform: Windows 10 16299

VS 2017, boost 1.66.0, cmake-3.11,  Python 2.7.14-x64 w/ latest packages

Compiled from latest release source code

```
The following tests FAILED:
	 52 - testEnumeration (Exit code 0xc0000409)
	107 - pyGraphMolWrap (Failed)
	125 - pythonTestDirChem (Failed)
```
Full ctest -V -R result and all env variant are attached 

[test-full-output.log](https://github.com/rdkit/rdkit/files/1772210/test-full-output.log)
[env.txt](https://github.com/rdkit/rdkit/files/1772211/env.txt)

By the way, I don't got any error when I compile and test on centos7

**Comment by bp-kelley** [comment]
@coleb 

Looks like the testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable is zero for two :)

```

125: FAIL: testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable (__main__.TestCase)
125: ----------------------------------------------------------------------
125: Traceback (most recent call last):
125:   File "UnitTestMol3D.py", line 218, in testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable
125:     self.assertEqual(smiles, expected)
125: AssertionError: Items in the first set but not the second:
125: 'C/C(F)=C/[C@@H](Cl)/C=C(\\Br)[C@@H](N)I'
125: 'C/C(F)=C\\[C@H](Cl)/C=C(\\Br)[C@@H](N)I'
125: Items in the second set but not the first:
125: 'C/C(F)=C/[C@@H](Cl)/C=C(/Br)[C@@H](N)I'
125: 'C/C(F)=C/[C@H](Cl)/C=C(\\Br)[C@H](N)I'

```

**Comment by bp-kelley** [comment]
Note: Enumeration error

```
52: ****
52: Test Assert
52: Expression Failed: 
52: Violation occurred on line 146 in file C:\rdkit-2017_09_3\Code\GraphMol\ChemReactions\Enumerate\testEnumerate.cpp
52: Failed Expression: even.getNumPermutations() == R1 * R2 * R3
52: ****
```

**Comment by bp-kelley** [comment]
@NKUCodingCat I'm curious if you are doing a 32 bit build or a 64 bit.

**Comment by coleb** [comment]
As I don't have a Windows machine to test on I'm fine to get rid of the testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable test case, it has only been noisy and unhelpful. The Python random number generator refuses to be deterministic and portable.

**Comment by NKUCodingCat** [comment]
@bp-kelley I think I am doing a 64Bit Build by Visual Studio 2017.....maybe....Let me double-check it....
