### ISSUE TITLE
how to change the swig type to types in c#

### ISSUE THREAD

**Issue by greatlse** [rdkit/rdkit#1782]
**Description:**

- RDKit Version: 2017.9 alpha from nuget
- Platform: win 7

how to output the type of SWIGTYPE_p_std__vectorT_unsigned_int_t

```
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            RDKit.Initialize();
            RWMol mol = RWMol.MolFromSmiles("C1CCCC1");
            uint num = mol.getNumBonds();
            double mw = RDKFuncs.calcMolLogP(mol);
            uint ringnum= RDKFuncs.calcNumRings(mol);
            SWIGTYPE_p_std__vectorT_unsigned_int_t hehe = RDKFuncs.calcMQNs(mol);
            Console.WriteLine(num);
            Console.WriteLine(hehe);

        }
    }
}

```
output:
5
GraphMolWrap.SWIGTYPE_p_std__vectorT_unsigned_int_t

**Comment by bp-kelley** [comment]
@greatlse It looks like this isn't properly wrapped in C#.  I can take a look in a few days and see if I can resolve this, and I assume, some other missing wrappings.

**Comment by greglandrum** [comment]
It’s a bit strange, because the java build uses exactly the same code and that works fine for me on windows

**Comment by greglandrum** [comment]
Of course, I am building from github and this is an old build

**Comment by greglandrum** [comment]
But the same thing happens to me when I build the csharp wrappers from the github modern_cxx builds.
