### ISSUE TITLE
Conformer indexing bug in RDFreeSASA.cpp?

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#1786]
**Description:**

- RDKit Version: 2017.09.3
- Platform: MacOS, python3.6

External/FreeSASA/RDFreeSASA.cpp has the following pre-condition:
```
PRECONDITION(confIdx < rdcast<int>(mol.getNumConformers()),
+               "Conformer index out of range");
```
However, I don't believe there is a requirement that conformer indexes be contiguous and therefore this condition doesn't make sense. For example, if a mol had 100 conformers, and then 95 of them were later dropped, mol might be left with 5 conformers having IDs [6,16,74,80,82]. In this case every one of the existing indexes is clearly > NumConformers, yet all are valid.

**Comment by greglandrum** [comment]
You're exactly correct. This is a bug (and something I should have caught during the code review).
Thanks for pointing it out.

**Comment by bp-kelley** [comment]
Also something I should have caught when I wrote it!
