### ISSUE TITLE
Fingerprint segfaults with branchedPaths=False and useHs=False

### ISSUE THREAD

**Issue by chrishmorris** [rdkit/rdkit#1793]
$ python -c 'import rdkit; print(rdkit.__version__)'
2017.09.2

- Platform: Windows 10
- Also observed in Centos 7.2 VirtualBox VM

```
from rdkit import Chem
from rdkit.Chem import rdmolops

mol = Chem.MolFromSmiles('C')  
Chem.rdmolops.RDKFingerprint(mol,
    useHs=False,
    branchedPaths=False
)
# Segmentation fault
```

Also LayeredFingerprint with 
```
from rdkit import Chem
from rdkit.Chem import rdmolops

mol = Chem.MolFromSmiles('C')  
Chem.rdmolops.LayeredFingerprint(mol, 
    branchedPaths=False
)
# segfault
```

**Comment by greglandrum** [comment]
I can't reproduce this with either 2017.09.2 or 2017.09.3 using python 3.6 and Windows 10::
```
In [4]: from rdkit import rdBase

In [5]: import rdkit

In [6]: rdkit.rdBase.rdkitVersion
Out[6]: '2017.09.3'

In [7]: Chem.RDKFingerprint(Chem.MolFromSmiles('C'),branchedPaths=False)
Out[7]: <rdkit.DataStructs.cDataStructs.ExplicitBitVect at 0x269d04ec440>
```
Did you build the RDKit yourself or is this a conda build?
Which version of Python are you using?

**Comment by chrishmorris** [comment]
This is a conda build of rdkit:
   rdkit=2017.09.2.0=py35h67c6137_1

$ python --version
Python 3.5.4 :: Anaconda, Inc.

We are on this version of python because we were trying to use Theano, which fails on 3.6. 

Thank you for rdkit, which is awesome.

**Comment by greglandrum** [comment]
Ah... it's actually the combination of `useHs=False` and `branchedPaths=False` that causes the problem:
```
In [2]: Chem.RDKFingerprint(Chem.MolFromSmiles('CC'),branchedPaths=False,useHs=False)
Segmentation fault (core dumped)
```
That's using the current version of master.
