### ISSUE TITLE
Unexpected behavior with hydrogen counts

### ISSUE THREAD

**Issue by bannanc** [rdkit/rdkit#1794]
I'm trying to get the total hydrogen count on an atom and I am getting some rather unexpected behavior after I have used the `AddHs` function.  What I'm seeing is that after adding Hs to my molecule, I get a 0 hydrogen count for total, explicit, and implicit (obviously the 0 is expected for the implicit). 

After I found this, I tried a substructure search on methane with implicit and total hydrogen counts. 
When I don't use the `addHs` the molecules has a substructure match with `"[#6H4]"` and `"[#6h4]"` (as it should), but when I  do use the `addHs` function, the molecule only matches the implicit SMARTS. 

Here's the code snippet I'm using to check this:
```python
from rdkit import Chem
def rdk_mol(smiles, addHs=True):
    """
    Returns an RDKit Mol of methane
    """
    m = Chem.MolFromSmiles(smiles)
    if addHs:
        m = Chem.AddHs(m)
    return m

for opt in [True, False]:
    mol = rdk_mol('C', opt)
    for a in mol.GetAtoms():
        if a.GetAtomicNum() == 6:
            c = a
            break
    print('I used Chem.AddHs:', opt)
    print('Total  Explicit  Implicit')
    print('%i\t%i\t%i  ' % (c.GetTotalNumHs(), c.GetNumExplicitHs(), c.GetNumImplicitHs()))
    
    for smarts in ['[#6H4]', '[#6h4]']:
        print('Queries matching %s:  %s' % (smarts, mol.HasSubstructMatch(query)))
        query = Chem.MolFromSmarts(smarts)
        
    print('\n\n')
```
print out:
```
I used Chem.AddHs: True
Total  Explicit  Implicit
0	0	0  
Queries matching [#6H4]:  False
Queries matching [#6h4]:  True



I used Chem.AddHs: False
Total  Explicit  Implicit
4	0	4  
Queries matching [#6H4]:  True
Queries matching [#6h4]:  True
```

I'm using RDKit version:  2017.09.3.0 
with python 3.5.3 on a mac.

**Comment by greglandrum** [comment]
There are two things here.

## `GetTotalNumHs()`

By default this doesn't look at neighbors (i.e. Hs that are actually in the graph), but  you can easily make it do so:
```
In [7]: m = Chem.AddHs(Chem.MolFromSmiles('C'))

In [10]: m.GetAtomWithIdx(0).GetTotalNumHs()
Out[10]: 0

In [11]: m.GetAtomWithIdx(0).GetTotalNumHs(includeNeighbors=True)
Out[11]: 4
```

## The `H` query in SMARTS
This does do the right thing:
```
In [7]: m = Chem.AddHs(Chem.MolFromSmiles('C'))

In [8]: m.HasSubstructMatch(Chem.MolFromSmarts('[#6H4]'))
Out[8]: True

In [9]: m.HasSubstructMatch(Chem.MolFromSmarts('[#6h4]'))
Out[9]: False
```

I think the problem is that you've got two lines in the wrong order in your example above, you have:
```
    for smarts in ['[#6H4]', '[#6h4]']:
        print('Queries matching %s:  %s' % (smarts, mol.HasSubstructMatch(query)))
        query = Chem.MolFromSmarts(smarts)
```
but you want:
```
    for smarts in ['[#6H4]', '[#6h4]']:
        query = Chem.MolFromSmarts(smarts)
        print('Queries matching %s:  %s' % (smarts, mol.HasSubstructMatch(query)))
```

**Comment by bannanc** [comment]
Sorry that was a really silly mistake with the smarts query. 

Thank you so much again for your quick replies and explaining how the total number call works!
