### ISSUE TITLE
Unexpected behavior with Reaction

### ISSUE THREAD

**Issue by fyms107** [rdkit/rdkit#1796]
**Description:**

![tim 20180328162105](https://user-images.githubusercontent.com/37279712/38017311-3f99c8d4-32a4-11e8-9fe4-a99d1ae1cb77.jpg)
## The result should be
![tim 20180328162252](https://user-images.githubusercontent.com/37279712/38017390-7cee2d10-32a4-11e8-9b81-0b9f1f100f81.png)

## Thanks for helping me.

```
from __future__ import print_function
from rdkit import Chem
from rdkit.Chem import AllChem as Chem  
testrxn = Chem.ReactionFromSmarts("[*:1][2*][*:2].[Rb][*:3][Cs]>>[*:1][*:3][*:2]")
testmol = Chem.MolFromSmiles('[1*][2*][3*]C(=O)N([4*])[5*]') 
testproduct=[]
for node in node2.mol:
        #mm = Chem.MolFromSmiles(m)
        result = rxn.RunReactants( [testmol,node] )
        for product1 in result:
            for mmm in product1:
                m1 = Chem.MolToSmiles(mmm,isomericSmiles=True)
                testproduct.append(m1)
```

**Comment by greglandrum** [comment]
What is the SMILES for `node2.mol`?

**Comment by fyms107** [comment]
@greglandrum 
Sorry. It's '[Rb][Cs]'
![tim 20180329101448](https://user-images.githubusercontent.com/37279712/38066387-4bfae16c-333a-11e8-9578-ec5d014d707a.png)

**Comment by greglandrum** [comment]
`[Rb][Cs]` doesn't match the second reactant in `testrxn`. 
In input 72 above, you are using `rxn`, not `testrxn`. How is `rxn` defined?

**Comment by greglandrum** [comment]
I just noticed that the `rxn`/`testrxn` confusion is also in your original sample

**Comment by fyms107** [comment]
Sorry. It's my carelessness. 
After I check three results, I realize I have to increase discrimination mechanism.
Thanks.
![tim 20180329143410](https://user-images.githubusercontent.com/37279712/38073712-c63f072c-335e-11e8-9ca0-954735e8cfc7.jpg)

![tim 20180329143530](https://user-images.githubusercontent.com/37279712/38073719-cb03a18c-335e-11e8-8b96-3f2e70712271.jpg)

![tim 20180329143555](https://user-images.githubusercontent.com/37279712/38073726-cf670804-335e-11e8-8b62-71f0d97f9451.jpg)

**Comment by greglandrum** [comment]
So is it ok to assume that this isn't an RDKit problem and close this issue?

**Comment by fyms107** [comment]
@greglandrum 
There is a question just like this.
![tim 20180329211420](https://user-images.githubusercontent.com/37279712/38090836-64b5de58-3396-11e8-95ac-7bae8eecb54b.jpg)
It doesn't react because [testmol,testnode] doesn't match the Reaction
```
testrxn = Chem.ReactionFromSmarts('[*:1][3*][*:2].[Rb][*:3][Cs]>>[*:1][*:3][*:2]')
testmol = Chem.MolFromSmiles('[4*]N([5*])C(=O)[3*]c1cc[nH]n1') 
testnode = Chem.MolFromSmarts('[Rb]c1cc([Cs])c2c(c1)CCC2')
testresult = None
testresult = testrxn.RunReactants( [testmol,testnode] )

```
Then I simplify this problem further.
![tim 20180329212432](https://user-images.githubusercontent.com/37279712/38091391-02f7c080-3398-11e8-9e9d-fe9c5fbef79b.jpg)
It seems like it matched only if there is an atom between [Rb] and [Cs].
```
tt=['[Rb]c1n[nH]cc1[Cs]',
 '[Rb]c1cc([Cs])c2c(c1)CCC2',
 '[Rb]c1c[nH]nc1[Cs]',
 '[Rb]c1ccc([Cs])cc1',
 '[Rb]n1ccc([Cs])n1',
 '[Rb]c1ccnn1[Cs]',
 '[Rb]c1cc([Cs])[nH]n1',
 '[Rb]C1CCc2cccc([Cs])c21',
 '[Rb]c1ccc2c(c1)C([Cs])CC2',
 '[Rb]C1([Cs])Cc2ccccc2C1',
 '[Rb]C1Cc2cccc([Cs])c2C1',
 '[Rb]c1cc2c(cc1[Cs])CCC2',
 '[Rb]c1cc([Cs])n[nH]1',
 '[Rb]c1cccc([Cs])c1',
 '[Rb]c1ccc2c(c1)CC([Cs])C2',
 '[Rb]c1cc([Cs])cc2c1CCC2',
 '[Rb]C1CCc2ccc([Cs])cc21',
 '[Rb]C1c2ccccc2CC1[Cs]',
 '[Rb]c1cc([Cs])co1',
 '[Rb]c1cccc2c1CC([Cs])C2',
 '[Rb]c1cocc1[Cs]',
 '[Rb]c1[nH]ncc1[Cs]',
 '[Rb]c1cn[nH]c1[Cs]',
 '[Rb]c1occc1[Cs]',
 '[Rb]c1coc([Cs])c1',
 '[Rb]C1CCc2cc([Cs])ccc21',
 '[Rb]c1c([Cs])ccc2c1CCC2',
 '[Rb]C1([Cs])CCc2ccccc21',
 '[Rb]c1cccc2c1CCC2[Cs]',
 '[Rb]c1ccoc1[Cs]',
 '[Rb]c1ccc([Cs])o1',
 '[Rb]c1cnn([Cs])c1',
 '[Rb]n1nccc1[Cs]',
 '[Rb]c1ccc2c(c1)CCC2[Cs]',
 '[Rb]c1ccccc1[Cs]',
 '[Rb]n1cc([Cs])cn1',
 '[Rb]c1ccc2c(c1[Cs])CCC2',
 '[Rb]c1cccc2c1C([Cs])CC2',
 '[Rb]C1Cc2ccccc2C1[Cs]',
 '[Rb]c1ccc([Cs])c2c1CCC2',
 '[Rb]c1ccn([Cs])n1',
 '[Rb]C1Cc2ccc([Cs])cc2C1',
 '[Rb]C1CC([Cs])c2ccccc21',
 '[Rb]C1CCc2c([Cs])cccc21']
ttp = Chem.MolFromSmarts('[Rb][*:1][Cs]')
for tttt in tt:
    m=Chem.MolFromSmiles(tttt)
    print(tttt)
    print(m.HasSubstructMatch(ttp))
    tt.append(m)
```

**Comment by greglandrum** [comment]
The pattern ‘[Rb][*:1][Cs]’ indeed only matches if there is exactly one atom between the Rb and the Cs. That’s what the query specifies. SMARTs and the RDKit do not support queries matching an unknown number of atoms.

**Comment by fyms107** [comment]
Get
