### ISSUE TITLE
anaconda & python2

### ISSUE THREAD

**Issue by rmrmg** [rdkit/rdkit#1799]
I've installed newest RDkit with anaconda and (within the enviroment) it works only with python3. In python2 I have ImportError: No module named rdkit. Is it possible to use python2 in conda env?

**Comment by greglandrum** [comment]
yes, it should work with Python2.
Which operating system are you using and how did you install the RDKit in the python2 environment?

**Comment by rmrmg** [comment]
I've installed anaconda2 (https://repo.continuum.io/archive/Anaconda2-5.1.0-Linux-x86_64.sh) and  followed instruction on http://www.rdkit.org/docs/Install.html. The OS is Mint 18, but as far as I understood conda make installation independent from OS.

**Comment by greglandrum** [comment]
It's important to know the OS (linux, windows, or Mac) in order to be able to diagnose problems.

From inside the shell where you are trying to run the RDKit, can you please do:
`conda list | egrep "rdkit|python"`
and send the output?

**Comment by rmrmg** [comment]
I assumed that everyone use one of Linux distros ;) In conda list I had:
python                    3.6.4                hc3d631a_3  
python-dateutil           2.7.2                    py36_0  
rdkit:           2017.09.3.0-py36_1    rdkit
I recreate env with following command:
conda create -c rdkit -n my-rdkit-env rdkit python=2.7
now rdkit is available in python2.7 (and python command executes 2.7.x version).
It solved me problem (I think it will be good to add this information to install page), however in such env I cannot used rdkit in python3 (which is not problem for me).

By the way: I am not familiar with conda, so I ask this question to be 100% sure: are the conda env truly independent from each other and from system's library?

**Comment by greglandrum** [comment]
You have to have separate environments for python2 and python3 (not separate conda installs, just separate environments).

And, yes, they are quite independent of each other and reasonably independent of the OS libraries.

**Comment by JulianNaumann** [comment]
I had the same problem under linux, but not under Mac: both have (mini)conda2 installed. When installing rdkit under Mac, using ```condo install -c rdkit -n <env-name> rdkit``` was sufficient and it installed for python2.7 and worked fine. When I used exactly the same command under linux, it installed rdkit for python3.6 which it also installed in the environment. Adding the ```python=2.7```solved this for me. Seems more like an issue with anaconda.

**Comment by d-b-w** [comment]
RDKit no longer supports Python2.

Please move further questions to the "discussion" tab.
