### ISSUE TITLE
Aromaticity Model Choice During Substructural Search

### ISSUE THREAD

**Issue by hjuinj** [rdkit/rdkit#1803]
I am experimenting with the outcome of using different aromaticity models, namely between the default aromaticity model in rdkit and the newly implemented MDL model. I can see differences due to the aromaticity model manifesting when I do simple queries but this does not seem to extend to when I perform substructural search queries.

For example I use a mol2 file that contains 1,2,3-triazole, I indeed see the difference in aromaticity perception depending on the model I choose in the line with `SetAromaticity`  below : 
```python
rdkmol = Chem.MolFromMol2Block(list(RetrieveMol2Block(open('./3448.mol2', "r")))[0], sanitize = False, removeHs = False)
rdkmol.UpdatePropertyCache(strict=False)
Chem.SetAromaticity(rdkmol, Chem.AromaticityModel.AROMATICITY_MDL) # AROMATICITY_DEFAULT

for atom in rdkmol.GetAtoms():
    print(atom.GetIsAromatic())
```

The MDL model **does not** recognize the 5-membered ring as aromatic while the default rdkit model does.

However, when I try to do substructural search on this mol, I do not observe any difference when I alter the aromaticity model. It seems the ring is regarded aromatic regardless of the model:
```python
rdkmol = Chem.MolFromMol2Block(list(RetrieveMol2Block(open('./3448.mol2', "r")))[0], sanitize = False, removeHs = False)
rdkmol.UpdatePropertyCache(strict=False)
smarts = "[#7:1]:[#7:2]"
qmol = Chem.MolFromSmarts(smarts)   
Chem.SetAromaticity(rdkmol, Chem.AromaticityModel.AROMATICITY_MDL) # AROMATICITY_DEFAULT
Chem.SetAromaticity(qmol, Chem.AromaticityModel.AROMATICITY_MDL) # AROMATICITY_DEFAULT
rdkmol.GetSubstructMatches(qmol)
```
Is this maybe because rdkit forces sanitization of my input `rdkmol` when doing the the substructural search (I tried to find this in the source code but was not successful)? I observe if I read in the molecule with sanitize set to True, then the molecule is aromatic regardless of the aromaticity model, even during the first test (per atom aromaticity checking) above.

Or am I neglecting other settings I should change when I do a substructural search?

I installed the `modern_cxx` branch (which contains the new MDL aromaticity) via the method detailed in the [conda-rdkit repository](https://github.com/rdkit/conda-rdkit).

The mol2 file I used is here: 
```
@<TRIPOS>MOLECULE
DrugBank_3448
   33    33     0     0     0
SMALL
NO_CHARGES

@<TRIPOS>ATOM
      1 C5         -4.3466    4.1816    0.2815 C.ar      1 <0>         0.0000
      2 C4         -3.9099    2.9125    0.5675 C.ar      1 <0>         0.0000
      3 C8         -3.3447    3.1722   -4.6728 C.2       1 <0>         0.0000
      4 C7         -2.4608    2.3604   -4.0850 C.2       1 <0>         0.0000
      5 C9         -3.2878    3.3582   -6.1350 C.2       1 <0>         0.0000
      6 C10        -0.0437    1.9460   -2.2852 C.2       1 <0>         0.0000
      7 C1         -3.0484   -0.1138   -0.7992 C.3       1 <0>         0.0000
      8 C3         -1.6160    1.7811    0.2114 C.3       1 <0>         0.0000
      9 C6         -1.3563    1.1749   -2.2680 C.3       1 <0>         0.0000
     10 C2         -1.7158    0.6446   -0.8484 C.3       1 <0>         0.0000
     11 N2         -3.3304    4.9005   -0.2843 N.ar      1 <0>         0.0000
     12 N3         -2.2650    4.1106   -0.3610 N.ar      1 <0>         0.0000
     13 N1         -2.6146    2.9190    0.1501 N.pl3     1 <0>         0.0000
     14 N4         -2.3663    2.0783   -2.7946 N.pl3     1 <0>         0.0000
     15 O1         -4.0728    4.0898   -6.7263 O.2       1 <0>         0.0000
     16 O3          0.0640    3.1447   -2.0577 O.2       1 <0>         0.0000
     17 O4         -0.8807   -0.9925    0.9655 O.2       1 <0>         0.0000
     18 O5         -0.6563   -1.6201   -1.4937 O.2       1 <0>         0.0000
     19 O2          1.0198    1.1601   -2.5945 O.3       1 <0>         0.0000
     20 S1         -0.3916   -0.6212   -0.4046 S.o2      1 <0>         0.0000
     21 H7         -5.3232    4.6089    0.4513 H         1 <0>         0.0000
     22 H6         -4.3858    2.0487    1.0092 H         1 <0>         0.0000
     23 H11        -4.1069    3.7031   -4.1151 H         1 <0>         0.0000
     24 H10        -1.7041    1.8365   -4.6594 H         1 <0>         0.0000
     25 H12        -2.4989    2.8017   -6.6682 H         1 <0>         0.0000
     26 H1         -3.1043   -0.9099   -1.5500 H         1 <0>         0.0000
     27 H2         -3.2154   -0.5998    0.1688 H         1 <0>         0.0000
     28 H3         -3.8899    0.5649   -0.9748 H         1 <0>         0.0000
     29 H4         -1.7176    1.3435    1.2136 H         1 <0>         0.0000
     30 H5         -0.6040    2.2112    0.1980 H         1 <0>         0.0000
     31 H8         -1.2754    0.3457   -2.9820 H         1 <0>         0.0000
     32 H9         -3.0242    2.5111   -2.1539 H         1 <0>         0.0000
     33 H13         0.8146    0.2149   -2.7570 H         1 <0>         0.0000
@<TRIPOS>BOND
     1    1    2 2
     2    1   11 1
     3    2   13 1
     4    3    4 2
     5    3    5 1
     6    4   14 1
     7    5   15 2
     8    6    9 1
     9    6   16 2
    10    6   19 1
    11    7   10 1
    12    8   10 1
    13    8   13 1
    14    9   10 1
    15    9   14 1
    16   10   20 1
    17   11   12 2
    18   12   13 1
    19   17   20 2
    20   18   20 2
    21    1   21 1
    22    2   22 1
    23    3   23 1
    24    4   24 1
    25    5   25 1
    26    7   26 1
    27    7   27 1
    28    7   28 1
    29    8   29 1
    30    8   30 1
    31    9   31 1
    32   14   32 1
    33   19   33 1
```

**Comment by greglandrum** [comment]
I think that the problem (though I can't reproduce it) is that you shouldn't be calling `SetAromaticity()` on the query.
Here's what I get:
```
In [24]: rdkmol = Chem.MolFromMol2File("/home/glandrum/blah.mol2",sanitize=False,removeHs=False)

In [25]: rdkmol.UpdatePropertyCache(False)

In [26]: Chem.SetAromaticity(rdkmol, Chem.AromaticityModel.AROMATICITY_MDL) # AROMATICITY_DEFAULT

In [27]: qmol = Chem.MolFromSmarts('[#7]:[#7]')

In [28]: rdkmol.GetSubstructMatch(qmol)
Out[28]: ()

In [29]: Chem.MolToSmiles(rdkmol)
Out[29]: '[H]OC(=O)[C@]([H])(N([H])C([H])=C([H])C([H])=O)[C@]([S+](=O)=O)(C([H])([H])[H])C([H])([H])N1N=NC([H])=C1[H]'
```

Can you please try that very simple test to confirm you get the same thing?

**Comment by hjuinj** [comment]
Hi Greg, thanks for the reply. I have tried that before and I have retested it now, I get the same outcome whether or not I set aromaticity of `qmol`.

How do you mean you "cannot reproduce it"? Do you get different results when calling `rdkmol.GetSubstructMatch(qmol)` depending on aromaticity setting of `rdkmol`?

**Comment by greglandrum** [comment]
I assume from the question that you get matches when you call `rdkmol.GetSubstructMatch(qmol)`.
This I can't reproduce, I don't get any matches.

**Comment by hjuinj** [comment]
Ah, I now see a odd behaviour. If the aromaticity of a molecule has ever been set to default (via SetAromaticity), it cannot be changed. i.e. I thought the two snippets below should have the same outcome but they do not:
```python

rdkmol = Chem.MolFromMol2File("/home/glandrum/blah.mol2",sanitize=False,removeHs=False)

rdkmol.UpdatePropertyCache(False)

Chem.SetAromaticity(rdkmol, Chem.AromaticityModel.AROMATICITY_MDL) 

qmol = Chem.MolFromSmarts('[#7]:[#7]')

rdkmol.GetSubstructMatch(qmol)

```


```python

rdkmol = Chem.MolFromMol2File("/home/glandrum/blah.mol2",sanitize=False,removeHs=False)

rdkmol.UpdatePropertyCache(False)

Chem.SetAromaticity(rdkmol, Chem.AromaticityModel.AROMATICITY_DEFAULT) #added this line

Chem.SetAromaticity(rdkmol, Chem.AromaticityModel.AROMATICITY_MDL) 

qmol = Chem.MolFromSmarts('[#7]:[#7]')

rdkmol.GetSubstructMatch(qmol)

```

This is suggesting default aromaticity model has some kind of dominating power over MDL (and perhaps other models too). Can you reproduce this? If so is this the intended behaviour?

**Comment by greglandrum** [comment]
Yes, the current (=released) version of `SetAromaticity()` immediately returns if it sees an atom that has aromaticity already set.
This has been changed for the next release: #1730

**Comment by hjuinj** [comment]
Thank you Greg. Am I correct in thinking currently this change is merged to the `master` branch while the MDL model is still only available in the `modern_cxx` branch?

Is there already some formal way where I can have both of these features together other than me manually editing the respective files modeified by #1730 you mentioned above in order to combine the features (this is not a lot of changes and I think I can safely do without making mistakes)?

**Comment by greglandrum** [comment]
I also merged that change onto the modern_cxx branch, so you should just be able to use that.

Sometime in the next couple of days the modern_cxx branch will replace the master branch (which will be renamed legacy), so things will get a bit simpler.

**Comment by hjuinj** [comment]
Ah yeah! Sorry I released I was looking at the wrong place (`modern_cxx` branch from the source of pull request #1730 )... Thank you :)
