### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by dkoes** [rdkit/rdkit#1804]
https://github.com/rdkit/rdkit/blob/b5595611a6edd931b987baf901d8172bead3386c/Code/GraphMol/FilterCatalog/CMakeLists.txt#L3

I think you want `boost_serialization` instead of `Boost::serialization` here, otherwise you get `-lBoost::serialization` passed on the commandline and it doesn't build.

**Comment by dkoes** [comment]
Also `Code/GraphMol/ChemReactions/CMakeLists.txt`

**Comment by dkoes** [comment]
And rather than setting to `boost_serialization`, which will break if the library is named something different (e.g., the -mt version installed by default by macports), probably need to do something like:
```
    find_package(Boost 1.39.0 COMPONENTS serialization)    
    include_directories(SYSTEM ${Boost_INCLUDE_DIRS})
    link_directories(${Boost_LIBRARY_DIRS})
    set(RDKit_SERIALIZATION_LIBS ${Boost_LIBRARIES})
```
It seems to me that `${Boost_serialization_LIBRARY}` should work.. but it doesn't.

**Comment by avaucher** [comment]
`Boost::serialization` is correct. This is the modern way of importing dependencies with CMake, using `IMPORTED` targets. More information [here](https://cmake.org/cmake/help/latest/module/FindBoost.html). Plus it will set automatically the correct boost library name.

**Comment by bp-kelley** [comment]
Annoyingly, there is also a dependency between boost version and cmake version.

Details here:

https://github.com/Microsoft/vcpkg/issues/2459

Most of the issues can be resolved by updating cmake to a more recent version.

**Comment by bp-kelley** [comment]
We're using cmake 3.9.2 on travis (osx/linux) which is building correctly
using "Boost::serialization"

Hopefully this isn't a cmake regression somewhere.

**Comment by bp-kelley** [comment]
What version of boost are you using?

**Comment by dkoes** [comment]
1.61, but I just did a fresh checkout of rdkit and rebuilt without a problem.  I guess there was some old cruft lying around in my regular checkout from older versions.  I apologize.
