### ISSUE TITLE
Cannot read molecules containing phosphate groups from Mol2

### ISSUE THREAD

**Issue by lyu18** [rdkit/rdkit#1806]
**Description:**

RDKit Version:  2017.09.3.0

I have some Mol2 files which I want to convert to SMILES strings. I am doing it simply by:

```python
from rdkit import Chem

def mol2_to_smiles(path_to_mol2_file):
    mol = Chem.MolFromMol2File(path_to_mol2_file)
    smi = Chem.MolToSmiles(mol)
    return smi
```

It all worked fine except for molecules with phosphate groups. An example is the ligand in PDB entry [1IIH](https://www.rcsb.org/structure/1iih), for which the Mol2 file is:

```
@<TRIPOS>MOLECULE
1iih_ligand
   15    14     1     0     0
SMALL
GAST_HUCK

@<TRIPOS>ATOM
      1 C1         46.4510   15.2650   -8.7440 C.2       1 MOL         0.0659
      2 O1         47.3220   15.8050   -8.0570 O.co2     1 MOL        -0.5663
      3 O2         45.2700   15.2200   -8.4480 O.co2     1 MOL        -0.5663
      4 C2         46.8730   14.6890  -10.0830 C.3       1 MOL         0.1348
      5 O3         47.2570   13.3250  -10.0540 O.3       1 MOL        -0.3751
      6 C3         48.0670   15.5450  -10.4800 C.3       1 MOL         0.1159
      7 O1P        47.6780   16.7860  -11.1160 O.3       1 MOL        -0.2718
      8 P          47.7670   16.9710  -12.7130 P.3       1 MOL         0.2009
      9 O2P        49.2390   16.7440  -12.9640 O.co2     1 MOL        -0.5537
     10 O3P        46.8860   15.8500  -13.2130 O.co2     1 MOL        -0.5537
     11 O4P        47.3480   18.3830  -12.9890 O.co2     1 MOL        -0.5537
     12 H1         46.0538   14.8041  -10.8080 H         1 MOL         0.0790
     13 H2         47.9557   13.2073   -9.4211 H         1 MOL         0.2125
     14 H3         48.6935   14.9723  -11.1797 H         1 MOL         0.0657
     15 H4         48.6477   15.7800   -9.5758 H         1 MOL         0.0657

@<TRIPOS>BOND
     1    1    4 1  
     2    1    3 ar 
     3    1    2 ar 
     4    4    6 1  
     5    4    5 1  
     6    6    7 1  
     7    7    8 1  
     8    8   11 ar 
     9    8   10 ar 
    10    8    9 ar 
    11    4   12 1  
    12    5   13 1  
    13    6   14 1  
    14    6   15 1  

@<TRIPOS>SUBSTRUCTURE
     1 MOL         1
```

When I put this file into `Chem.MolFromMol2File()` it gives the error message below and returns `None`:

```
[04:48:37] 1iih_ligand: warning - O.co2 with non C.2 or S.o2 neighbor.
```

Obviously, the `Chem.MolFromMol2File()` function assumes `O.co2` to only appear in carboxylates (C.2) and sulfones (S.o2). This is not the case as Mol2 documentation suggests it also encodes oxygens in phospates.

**Comment by greglandrum** [comment]
Since we only claim to support mol2 files that are produced by Corina, and since I no longer have access to that, could someone please share a corina-generated mol2 file that includes a phosphate group?

**Comment by lyu18** [comment]
Hi Greg, 

I don't have access to Corina as well but was able to obtain an evaluation copy. I converted the ligand in PDB 1IIH shown above to mol2 by Corina and this is what I got:

```
#	Name: 3PG
#	Creating user name:	root
#	Creation time:	04. 04. 2018 17:19

#	Modifying user name:	root
#	Modification time:	04. 04. 2018 17:19

#	Program:	corina_eval_x86-64_rhel6_2018_05_05 4.1.0 0066  01.08.2017

@<TRIPOS>MOLECULE
3PG
  18   17    0    0    0
SMALL
NO_CHARGES


@<TRIPOS>ATOM
   1 C1             1.4011     1.6074    -0.0027 C.2     
   2 O2             1.7520     2.3842    -0.8591 O.2     
   3 O3             2.2706     1.2091     0.9392 O.3     
   4 C4            -0.0127     1.0858     0.0080 C.3     
   5 O5            -0.7038     1.5592    -1.1497 O.3     
   6 C6            -0.7288     1.5792     1.2668 C.3     
   7 O7            -2.0295     0.9914     1.3363 O.3     
   8 P8            -3.0634     1.2889     2.5340 P.3     
   9 O9            -3.2748     2.7490     2.6520 O.2     
  10 O10           -4.4682     0.5667     2.2221 O.3     
  11 O11           -2.4627     0.7203     3.9152 O.3     
  12 H12            3.1661     1.5708     0.8911 H       
  13 H13            0.0021    -0.0041     0.0020 H       
  14 H14           -0.7557     2.5229    -1.2101 H       
  15 H15           -0.1536     1.2938     2.1476 H       
  16 H16           -0.8222     2.6646     1.2299 H       
  17 H17           -5.1405     0.7036     2.9035 H       
  18 H18           -2.2986    -0.2327     3.9100 H       
@<TRIPOS>BOND
   1    1    2 2
   2    1    3 1
   3    1    4 1
   4    3   12 1
   5    4    5 1
   6    4    6 1
   7    4   13 1
   8    5   14 1
   9    6    7 1
  10    6   15 1
  11    6   16 1
  12    7    8 1
  13    8    9 2
  14    8   10 1
  15    8   11 1
  16   10   17 1
  17   11   18 1

#	End of record
```

Looks like Corina specifies the phosphate oxygens only as sp2 (O.2) or sp3 (O.3), instead of using O.co2.

I still recommends you to add compatibility to O.co2 in phosphates since many software do use this atom type for phosphates.

Thanks

**Comment by greglandrum** [comment]
Thanks for looking into that.
We can’t hope to correctly support all possible mol2 dialects, and so we opted to only do the one we (at the time) were using frequently and could thoroughly test.

Starting to add extensions in an ad hoc manner is a recipe for corrupt chemical data, something we try hard to avoid.

If there are other mol2 “flavors” that the RDKit should support and someone is available to do all the testing (including writing new tests) I would be happy to answer questions and provide support for that.

**Comment by tbalius** [comment]
Hi,  

Here are two examples of molecules that have phosphates run with the latest version of Corina.

The first molecule does not have O.co2 atom type, however the second molecule "Cc1nc2ccc(cc2s1)P(=O)([O-])[O-]" does contain O.co2 when converted to mol2 with Corina.

The second molecule fails to open in Rdkit with this error: 
319: warning - O.co2 with non C.2 or S.o2 neighbor.

Molecule 1: 
>>   echo 'CCOP(=O)(=O)[O-]' | corina -i t=smiles -o t=mol2
ERROR ioopen(): Can't open trace file corina.trc
corina     4.2.0 0026  27.09.2018  username 07. 05. 2020 05:33  machine.org

Input file type  SMILES
Output file type SYBYL MOL2

INFORMATION corina(): Annual license expires on August 9, 2022

Options:
   Canonicalizing molecules before 3D generation
   Max. atoms per fragment: 999

Standard values, version 3.4 January, 2006
Ring templates, version 3.0 March, 2001
Torsion angle library version December, 1999 (1088 patterns), all rights CCDC, Cambridge, UK
International Chemical Identifier (InChI) Software version 1.05 (January 2017), copyright (C) IUPAC and InChI Trust Limited
WARNING smilesct(): Unnormal valence state
   CCOP(=O)(=O)[O-]
      ^

*** RECORD no.:  1 read ***********************
   7 atoms
#       Name: NoName
#       Creating user name:     tbalius
#       Creation time:  07. 05. 2020 05:33

#       Modifying user name:    tbalius
#       Modification time:      07. 05. 2020 05:33

#       Program:        corina 4.2.0 0026  27.09.2018

@<TRIPOS>MOLECULE
NoName
   7    6    0    0    0
SMALL
NO_CHARGES


@<TRIPOS>ATOM
   1 C1            -2.2571     2.0448     3.2417 C.3
   2 C2            -1.7416     1.2566     2.0359 C.3
   3 O3            -0.7722     2.0383     1.3350 O.3
   4 P4            -0.0186     1.5191     0.0104 P.3
   5 O5             0.0021    -0.0041     0.0020 O.2
   6 O6             1.4105     2.0464    -0.0004 O.2
   7 O7            -0.7554     2.0237    -1.2237 O.3
@<TRIPOS>BOND
   1    1    2 1
   2    2    3 1
   3    3    4 1
   4    4    5 2
   5    4    6 2
   6    4    7 1

#       End of record

   Elapsed time: 0 ms

1 record(s) read, 1 converted
   Totally elapsed time: 0 s


############

Molecule 2: 
>> echo 'Cc1nc2ccc(cc2s1)P(=O)([O-])[O-]' | corina -i t=smiles -o t=mol2
ERROR ioopen(): Can't open trace file corina.trc
corina     4.2.0 0026  27.09.2018  username   07. 05. 2020 05:34  machine.org

Input file type  SMILES
Output file type SYBYL MOL2

INFORMATION corina(): Annual license expires on August 9, 2022

Options:
   Canonicalizing molecules before 3D generation
   Max. atoms per fragment: 999

Standard values, version 3.4 January, 2006
Ring templates, version 3.0 March, 2001
Torsion angle library version December, 1999 (1088 patterns), all rights CCDC, Cambridge, UK
International Chemical Identifier (InChI) Software version 1.05 (January 2017), copyright (C) IUPAC and InChI Trust Limited

*** RECORD no.:  1 read ***********************
   14 atoms
#       Name: NoName
#       Creating user name:     tbalius
#       Creation time:  07. 05. 2020 05:34

#       Modifying user name:    tbalius
#       Modification time:      07. 05. 2020 05:34

#       Program:        corina 4.2.0 0026  27.09.2018

@<TRIPOS>MOLECULE
NoName
  14   15    0    0    0
SMALL
NO_CHARGES


@<TRIPOS>ATOM
   1 C1            -1.2321    -0.8688     0.0096 C.3
   2 C2             0.0021    -0.0041     0.0020 C.2
   3 N3             1.1984    -0.4572    -0.0118 N.2
   4 C4             2.2083     0.4335    -0.0167 C.ar
   5 C5             3.6010     0.2154    -0.0311 C.ar
   6 C6             4.4640     1.2688    -0.0342 C.ar
   7 C7             3.9918     2.5739    -0.0227 C.ar
   8 C8             2.6369     2.8170    -0.0080 C.ar
   9 C9             1.7390     1.7516    -0.0051 C.ar
  10 S10           -0.0211     1.7022     0.0114 S.3
  11 P11            5.1612     3.9606    -0.0264 P.3
  12 O12            6.4827     3.5313     0.6973 O.co2
  13 O13            5.4837     4.3678    -1.5044 O.co2
  14 O14            4.5270     5.1805     0.7248 O.co2
@<TRIPOS>BOND
   1    1    2 1
   2    2   10 1
   3    2    3 2
   4    3    4 1
   5    4    9 ar
   6    4    5 ar
   7    5    6 ar
   8    6    7 ar
   9    7    8 ar
  10    7   11 1
  11    8    9 ar
  12    9   10 1
  13   11   12 ar
  14   11   13 ar
  15   11   14 ar

#       End of record

   Elapsed time: 0 ms

1 record(s) read, 1 converted
   Totally elapsed time: 0 s
#############

Take care,

Trent
