### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/rdkit#1809]
It seems that recent changes break the CMake/make. Here is a log from one of the travis build of homebrew-rdkit (https://travis-ci.org/hsiaoyi0504/homebrew-rdkit/jobs/362614009).

```
==> make -j2
Last 15 lines from /Users/travis/Library/Logs/Homebrew/rdkit/02.make:
                      ^
/tmp/rdkit-20180405-5805-1cky97r/Code/RDGeneral/LocaleSwitcher.cpp:75:5: error: use of undeclared identifier 'recursion'
    recursion++;
    ^
/tmp/rdkit-20180405-5805-1cky97r/Code/RDGeneral/LocaleSwitcher.cpp:77:5: error: use of undeclared identifier 'recursion'
    recursion--;
    ^
/tmp/rdkit-20180405-5805-1cky97r/Code/RDGeneral/LocaleSwitcher.cpp:78:10: error: use of undeclared identifier 'recursion'
  return recursion;
         ^
5 errors generated.
make[2]: *** [Code/RDGeneral/CMakeFiles/RDGeneral.dir/LocaleSwitcher.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Code/RDGeneral/CMakeFiles/RDGeneral.dir/all] Error 2
make: *** [all] Error 2
Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by bp-kelley** [comment]
I’ll take a look at this today.

**Comment by bp-kelley** [comment]
I'm not duplicating this issue locally.  Could you point me at the travis builds please?  I'm having troubles finding them.

**Comment by bp-kelley** [comment]
I'm blind, it's the link at the top.

**Comment by bp-kelley** [comment]
It looks like some c++11 code snuck into the legacy branch:

https://github.com/rdkit/rdkit/blob/020024ee5cb612781239e4ca152a4a51f6ff1b1d/Code/RDGeneral/StreamOps.h#L371

we can fix this for brew by building the modern_cxx branch, I'll start this update.

**Comment by thegodone** [comment]
Dear All,

I have those types lf errors with the new beta too with or without the brew install on my mac.

BR

Guillaume

Envoyé de mon iPhone

**Comment by bp-kelley** [comment]
We'll fix this in our cmakelists.txt, but setting these environment
variables will help the non-brew builds for now (that recipe is finally
fixed I think)

    export CXXFLAGS= "-std=c++11 -stdlib=libc++ -Wno-parentheses
-Wno-logical-op-parentheses -Wno-format"
    export CFLAGS="-Wno-parentheses -Wno-logical-op-parentheses -Wno-format"
    cmake ...
