### ISSUE TITLE
Kekule structure enumeration

### ISSUE THREAD

**Issue by somous-jhzhao** [rdkit/rdkit#1817]
Does anybody know there is module or methods for Kekule structure enumeration? I have looked for the rdkit documention and didn't find suitable methods. If anybody knows, please let me know. Thank you very much!!!

**Comment by greglandrum** [comment]
There is not currently any code to specifically allow Kekule structure enumeration.
There is code to do resonance structures in general, but I don't think it can be limited to just do Kekule forms. @ptosco may be able to correct me on this one.

**Comment by ptosco** [comment]
Greg is correct, currently the resonance structure enumeration takes place on the whole molecule. It wouldn't be difficult to modify the code to only take into account certain substructures (e.g., aromatic rings), and leave the rest untouched. I'll have a look in my copious free time - please don't expect a PR tomorrow ;-)

**Comment by somous-jhzhao** [comment]
Thank you all! I will go into the resonance structure enumeration and try to use it to solve my problem.
