### ISSUE TITLE
Chiral hydrogens are mostly facing inwards the ring in 2d depiction

### ISSUE THREAD

**Issue by lpravda** [rdkit/rdkit#1818]
I'm generating 2D depictions and I have noticed that when chiral hydrogens are depicted, often they face inside the ring rather than outside. Is that intended, or is that a bug?

**Setup**:
Mac OS: 10.13.4
Rdkit: 2017.09.03
Python 3.6.1

the **drawing code** is:

drawer = rdMolDraw2D.MolDraw2DSVG(500, 500)
rdMolDraw2D.PrepareMolForDrawing(self._2dmol, wedgeBonds=True, kekulize=True, addChiralHs=True)
drawer.DrawMolecule(copy)
drawer.FinishDrawing()

**Examples**:

http://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/21T
![screen shot 2018-04-11 at 13 50 21](https://user-images.githubusercontent.com/16133456/38617641-78f2effc-3d8f-11e8-8163-cd0536492ba5.png)

http://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/19V
![screen shot 2018-04-11 at 13 53 45](https://user-images.githubusercontent.com/16133456/38617794-ce29fc72-3d8f-11e8-80b8-4905a8a603c1.png)

http://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/0NR
![screen shot 2018-04-11 at 13 54 43](https://user-images.githubusercontent.com/16133456/38617831-eada1fb4-3d8f-11e8-8e61-80cc1db3821c.png)

**Comment by greglandrum** [comment]
oh my, that's horrible. It's certainly not intentional and looks like a bug.

**Comment by bp-kelley** [comment]
It looks like these were resolved a while ago (tested on 2024.9)
