### ISSUE TITLE
Add GetBestRMS function

### ISSUE THREAD

**Issue by chmnk** [rdkit/rdkit#1820]
**Description:**

- RDKit Version: 2017.03.3
- Platform: Ubuntu 16.04

If I understand everything correctly, `GetBestRMS` function is the only RMSD computing function in RDKit that takes symmetry into account. I often use its modification to calculate RMSDs in the docking experiments, where
- symmetry is important since the atom ids and names may be not the same for the same ligand poses generated by different algorithms,
- additional alignment which is done by default in `GetBestRMS` should not be applied.

So I added a `bool doAlignment=true` parameter to all the functions and wrappers related to `GetBestRMS` starting from `def GetBestRMS(...)` and ending in `double getAlignmentTransform(...)` ,

and this naive piece of code to `getAlignmentTransform`:

```c++
double getAlignmentTransform(const ROMol &prbMol, const ROMol &refMol,
                             RDGeom::Transform3D &trans, int prbCid, int refCid,
                             const MatchVectType *atomMap,
                             const RDNumeric::DoubleVector *weights,
                             bool reflect, unsigned int maxIterations, bool doAlignment) {
// ... 
// Some original getAlignmentTransform code is not copied (see `./Code/GraphMol/MolAlign/AlignMolecules.cpp`)
// ... 

double ssr;
  if (!doAlignment) {
      ssr = 0.;
      unsigned int npt = refPoints.size();
      PRECONDITION(npt == prbPoints.size(), "Mismatch in number of points");

      const RDGeom::Point3D *rpt, *ppt;
      for (unsigned int i = 0; i < npt; i++) {
        rpt = refPoints[i];
        ppt = prbPoints[i];
    
        ssr += ((ppt->x) - (rpt->x))*((ppt->x) - (rpt->x));
        ssr += ((ppt->y) - (rpt->y))*((ppt->y) - (rpt->y));
        ssr += ((ppt->z) - (rpt->z))*((ppt->z) - (rpt->z));
      }
  }
  else ssr = RDNumeric::Alignments::AlignPoints(
      refPoints, prbPoints, trans, weights, reflect, maxIterations);
  ssr /= (prbPoints.size());
  return sqrt(ssr);
}
```
And put the conformer transformation under the condition
```c++
double alignMol(ROMol &prbMol, const ROMol &refMol, int prbCid, int refCid,
                const MatchVectType *atomMap,
                const RDNumeric::DoubleVector *weights, bool reflect,
                unsigned int maxIterations, bool doAlignment) {
  RDGeom::Transform3D trans;
  double res = getAlignmentTransform(prbMol, refMol, trans, prbCid, refCid,
                                     atomMap, weights, reflect, maxIterations, doAlignment);
  // now transform the relevant conformation on prbMol
  if (doAlignment) {
      Conformer &conf = prbMol.getConformer(prbCid);
      MolTransforms::transformConformer(conf, trans);
  }
  return res;
}
```
Would it be possible to either add some day such parameter or a separate function that computes RMSD with symmetry matchings and without alignment to the official release?

**Comment by greglandrum** [comment]
In principle this sounds completely logical and would make sense to add. I'm sure we'll want to have a bit of discussion about it, but that shouldn't be too difficult. 

A pull request would be a great way to start that conversation. :-)

**Comment by chmnk** [comment]
Thank you! I will update my RDKit to the latest version and make a pull request.
