### ISSUE TITLE
Smarts conversion failed

### ISSUE THREAD

**Issue by sshojiro** [rdkit/rdkit#1823]
**Description:**

- RDKit Version: 2017.09.2
- Platform: Windows, python 3.5.4

I expected the Mol objects built both from Smiles and from Smarts are exactly the same; however, they seem different and Mol created from Smarts went wrong w/ MACCS fingerprint calculation as follows:

```python
>>> m_smiles = Chem.MolFromSmiles('Cc1ccccc1')
>>> rdMolDescriptors.GetMACCSKeysFingerprint(m_smiles)# work correctly

>>> m_smarts = Chem.MolFromSmarts('Cc1ccccc1')
>>> rdMolDescriptors.GetMACCSKeysFingerprint(m_smarts)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-46-1d65f00d0d45> in <module>()
      3 
      4 m_smarts = Chem.MolFromSmarts('Cc1ccccc1')
----> 5 rdMolDescriptors.GetMACCSKeysFingerprint(m_smarts)

RuntimeError: Pre-condition Violation
	getNumImplicitHs() called without preceding call to calcImplicitValence()
	Violation occurred on line 153 in file Code\GraphMol\Atom.cpp
	Failed Expression: d_implicitValence > -1
	RDKIT: 2017.09.2
	BOOST: 1_59
```

Sorry that my question may not make the point because I am a beginner in the chemoinformatics field, but I hope someone would answer my question.

Is it better for me to input the correct one with the correct method? For instance, are only `Chem.MolFromSmiles(<correct SMILES syntax>)` and `Chem.MolFromSmarts(<correct SMARTS syntax>)` acceptable?

Best regards,

**Comment by bp-kelley** [comment]
While they are related, SMARTS and SMILES are quite different in practice.
SMARTS is like a chemistry regular expression and allows you to search for
structures in a molecule including very non-chemically sensical structures,
like five bonds to a carbon.

> q = MolFromSmarts("C(*)(*)(*)(*)*")

This means that the Chemical Sanitization that RDKit normally uses cannot
be applied to a smarts pattern.  Taking the same structure and trying to
make a molecule (via MolFromSmiles) shows this:

> q = MolFromSmiles("C(*)(*)(*)(*)*")

[23:03:38] Explicit valence for atom # 0 C, 5, is greater than permitted

The downside is that any downstream operation that requires real chemistry
won't have the data that it needs from a smarts pattern.

Again thinking of SMARTS as a regular expression that searches for
structures in a chemically sane molecule is  a useful conceit.  For more
information, this link may be useful:

http://www.daylight.com/dayhtml/doc/theory/theory.smarts.html

Now if you have a molecule and extract the structure matched by the smarts
pattern, then you might be able to do what you want.

Hopefully this make sense,  let us know if you need more assistance.

**Comment by sshojiro** [comment]
Dear @bp-kelley, I appreciate your very quick response.
I've got the picture by your saying that 'Again thinking of SMARTS as a regular expression that searches for
structures in a chemically sane molecule is  a useful conceit.'

I don't have the right person who knows about the differences between SMARTS and SMILES nearby and it is so great help.

Thank you so much.

Best regards,
