### ISSUE TITLE
rdFreeSASA on arbitrary molecules

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#1827]
**Description:**

- RDKit Version: 2017.9.3
- Platform: MacOS; python3

I want to calculate the polar SASA for a set of small molecules, however a call like this always returns 0:

`rdFreeSASA.CalcSASA(mol, radii=radii, confIdx=id, query=rdFreeSASA.MakeFreeSasaAPolarAtomQuery())`

I tracked the cause of this behavior to the rdFreeSASA.classifyAtoms function. This function checks the monomerInfo via getMonomerInfo(), and then refuses to classify atoms if they don't have any monomerInfo. This behavior limits polar SASA calcs to protein molecules. Is there someway to get around this to make the calculation on any arbitrary molecule? Perhaps by manually assigning the monomerInfo of all atoms to be Methionine or something similar?

**Comment by paconius** [comment]
Sorry. I realize that this is a question for the original author -- which would appear to be this fellow here: https://github.com/mittinatten/freesasa. I am closing this question.

**Comment by bp-kelley** [comment]
@paconius The freesasa project only does have the polar/apolar designations for protein informations.  We supply a separate interface that may help:

```
double calcSASA(const RDKit::ROMol &mol, const std::vector<double> &radii,
                int confIdx = -1, const RDKit::QueryAtom *query = NULL,
                const SASAOpts &opts = SASAOpts());
```

Where "query" is an RDKit query atom to limit the calculation to the surface area of the matched atoms.

This may not be satisfying as only supply the query-atom classifiers from FreeSASA.  However, if you wanted to supply your own, I believe the following will work (python code below)

```
from rdkit.Chem import rdFreeSASA

atom.SetProp("SASAClassName", "Apolar") # mark as apolar
atom.SetProp("SASAClassName", "Polar") # mark as polar
opts = rdFreeSASA.SASAOpts()
apolar = rdFreeSASA.CalcSASA(mol, radii, query=rdFreeSASA.MakeFreeSasaAPolarAtomQuery(), opts=opts);
polar = rdFreeSASA.CalcSASA(mol, radii, query=rdFreeSASA.MakeFreeSasaPolarAtomQuery(), opts=opts);

```

However, you would need to write your own classifier.  Hopefully this helps.

**Comment by paconius** [comment]
Thanks or the pointer. Given your input, this was really straightforward. Mimicking the TPSA protocol, I assigned [N,O,S,P] as polar and the rest as apolor with a simple loop:

```
for atom in mol.GetAtoms():
    if atom.GetAtomicNum() in [7,8,15,16]:
        atom.SetProp("SASAClassName", "Polar") # mark as polar
    else:
        atom.SetProp("SASAClassName", "Apolar") # mark as apolar
```

Then then used the polar query as you showed. Seems to work.

Thanks!

**Comment by paconius** [comment]
One more question: I notice that the function still requires the radii parameter, however for atoms with no monomerInfo, the radius is calculated to be 0 by classifyAtoms(). If I pass the all-zero radii object to calcSASA, it still generated seemingly reasonable output, but I'm wondering if it might be incorrect since I didn't provide valid radii.

**Comment by paconius** [comment]
After some more investigation, I confirm that calcSASA will calculate and return values even if you supply it with a radii list containing all zeroes.  I observe that if you manually calculate and supply a correct radii list, the calculated SASA values are about 2-fold higher than the all-zero radii case. My current best guess is that when radii are zero, the function returns the VDW surface area; when you supply non-zero radii values, the function calculates the solvent accessible surface area.

**Comment by paconius** [comment]
Here is my final classifier for calculating SASA values for small molecules. Radii are entered explicitly (As opposed to using rdkit's own radii values) due to the questionable values provided by rdkit. Polar atoms are defined as [O,N,S,P], but that is flexible.

```
def classifyAtoms(mol, polar_atoms=[7,8,15,16]):
	#Taken from https://github.com/mittinatten/freesasa/blob/master/src/classifier.c
	symbol_radius = {"H": 1.10, "C": 1.70, "N": 1.55, "O": 1.52, "P": 1.80, "S": 1.80, "SE": 1.90,
	"F": 1.47, "CL": 1.75, "BR": 1.83, "I": 1.98,
	"LI": 1.81, "BE": 1.53, "B": 1.92,
	"NA": 2.27, "MG": 1.74, "AL": 1.84, "SI": 2.10,
	"K": 2.75, "CA": 2.31, "GA": 1.87, "GE": 2.11, "AS": 1.85,
	"RB": 3.03, "SR": 2.49, "IN": 1.93, "SN": 2.17, "SB": 2.06, "TE": 2.06}

	radii = [] 
	for atom in mol.GetAtoms():
		atom.SetProp("SASAClassName", "Apolar") # mark everything as apolar to start
		if atom.GetAtomicNum() in polar_atoms: #identify polar atoms and change their marking
			atom.SetProp("SASAClassName", "Polar") # mark as polar
		elif atom.GetAtomicNum() == 1:
			if atom.GetBonds()[0].GetOtherAtom(atom).GetAtomicNum() in polar_atoms:
				atom.SetProp("SASAClassName", "Polar") # mark as polar
		radii.append(symbol_radius[atom.GetSymbol().upper()])
	return(radii)
```

**Comment by hadim** [comment]
> After some more investigation, I confirm that calcSASA will calculate and return values even if you supply it with a radii list containing all zeroes. I observe that if you manually calculate and supply a correct radii list, the calculated SASA values are about 2-fold higher than the all-zero radii case. My current best guess is that when radii are zero, the function returns the VDW surface area; when you supply non-zero radii values, the function calculates the solvent accessible surface area.

Can someone confirm this?

If it is then I beleive those functions are correct:

```python
from rdkit.Chem import rdFreeSASA

def compute_sasa(mol):
    """Compute Solvent Accessible Surface Area.
    """
    mol = Chem.AddHs(mol)

    # Get Van der Waals radii (angstrom)
    ptable = Chem.GetPeriodicTable()
    radii = [ptable.GetRvdw(atom.GetAtomicNum()) for atom in mol.GetAtoms()]

    # Compute solvent accessible surface area
    sa = rdFreeSASA.CalcSASA(mol, radii, confIdx=-1)
    
    return sa

def compute_vdwsa(mol):
    """Compute Van der Waals Surface Area.
    """
    mol = Chem.AddHs(mol)
    radii = rdFreeSASA.classifyAtoms(mol)
    sa = rdFreeSASA.CalcSASA(mol, radii, confIdx=-1)
    return sa
    
# `mol` is a small molecule (not coming from a PDB file)

compute_sasa(mol), compute_vdwsa(mol)
```

**Comment by bp-kelley** [comment]
The shrake rupley surface is computed by taking the vanderwalls radius and
adding the probe_radius.  So a radii of zero is really just the probe
radius.

https://en.wikipedia.org/wiki/Accessible_surface_area

The default probe radius is 1.4 angstrom and can be changed in SASAOpts

Cheers,
 Brian

**Comment by hadim** [comment]
Sorry but I am still confused. `radii` is supposed to be the radius of an atom right? In the case of SASA computation this radius the VDW radius.

So is it the correct way to set up `radii`?

```python
radii = [ptable.GetRvdw(atom.GetAtomicNum()) for atom in mol.GetAtoms()]
```

I am fine keeping the probe radius to default (water radius).

**Comment by hadim** [comment]
Ok, it explains why I was confused then :-) Thank you!

**Comment by bp-kelley** [comment]
@paconius  Sorry for the long delay, the problem was that you were commenting on a closed issue which I tend to miss.  Feel free to reopen issues in the future :)

**Comment by sunhwan** [comment]
>     mol = Chem.AddHs(mol)

@hadim Just wanted comment here that the newly added hydrogens have no coordinates by default. You want to make this as `Chem.AddHs(mol, addCoords=True)` if you want to compute SASA of protonated molecule.
