### ISSUE TITLE
RDKit crashes when MolsToGridImage function is called with an empty iterable

### ISSUE THREAD

**Issue by martin-sicho** [rdkit/rdkit#1829]
Hello everyone,

I just came across this probably buggy behavior in the current RDKit release. 

**Details:**

- RDKit Version: `2017.09.3`
- Platform: `Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux`

The following code:

```Python
from rdkit.Chem.Draw import MolsToGridImage
MolsToGridImage(tuple()) # can also be an empty list or something else like that
```
causes the Python interpreter to die with exit code 11 (most probably result of a segfault). Can anyone confirm this behavior or is it just my setup? Thanks a lot!

**Comment by greglandrum** [comment]
I can confirm it and it's really a bug.
Fortunately it's almost certainly a very simple fix.
This will be in the upcoming release.

**Comment by martin-sicho** [comment]
Yup, nothing too serious, but thanks for the very quick fix anyway!
