### ISSUE TITLE
VDW Radius Lookup Values?

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#1831]
**Description:**

- RDKit Version: 2017.09.3
- Platform: MacOS; python3.6

I am wondering why the PeriodicTable.GetRvdw() (vdw radius) lookup produces values that differ so much from other sources. The values for C, N & O are compiled here:

atom:  | rdkit | wikipedia
       C: | 1.95 | 1.70
       N: | 1.85 | 1.55
       O: | 1.70 | 1.52

The wikipedia values can be confirmed elsewhere on the web including in rdkit's own FreeSASA module where the radii agree with wikipedia (https://github.com/mittinatten/freesasa/blob/master/src/classifier.c)

```
PeriodicTable.GetRvdw(rdkit.Chem.GetPeriodicTable(),6)
PeriodicTable.GetRvdw(rdkit.Chem.GetPeriodicTable(),7)
PeriodicTable.GetRvdw(rdkit.Chem.GetPeriodicTable(),8)
```

**Comment by paconius** [comment]
The title of this entry should be "VDW Radius Lookup Values?" not "DSW...."
I'm still learning how to type apparently.

**Comment by greglandrum** [comment]
The origin of the RDKit values is, unfortunately, "lost in antiquity".
Updating these values to something that has a reference would be a nice enhancement for a future RDKit version.

**Comment by thegodone** [comment]
For your information, in 3d descriptors dragon, i have to include new versions based on Dragon.

Envoyé de mon iPhone

**Comment by paconius** [comment]
Interesting. I've been looking around to see where that vdw radius of 1.95 for carbon may have come from. RDKit is the only place I have found a value that big. My best guess is that RDKit is mixing up the atomic number index when looking up atoms. For example, the vdwR for carbon gives the value expected for bromine; the vdwR for oxygen gives the expected value for carbon, and so on.

**Comment by bp-kelley** [comment]
Previous similar discussion

https://github.com/rdkit/rdkit/issues/1037

**Comment by UnixJunkie** [comment]
By the way, where is the actual periodic table stored?
Is this in Data/rddata.sql?
I was looking for a csv file or some hardcoded values in a header file without success.

**Comment by UnixJunkie** [comment]
Probably it's here:
rdkit/Chem/PeriodicTable.py

**Comment by greglandrum** [comment]
It's defined here: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/atomic_data.cpp

**Comment by greglandrum** [comment]
and, yes, that python file should be removed

**Comment by UnixJunkie** [comment]
Thanks for the info, I will look into it.

**Comment by UnixJunkie** [comment]
Can this issue be assigned to me?

**Comment by greglandrum** [comment]
I would take the reference values from the blue obelisk data repository, then we have something convenient to reference: https://www.re3data.org/repository/r3d100000013

**Comment by UnixJunkie** [comment]
The Blue Obelisk Data Repository has no VdW radii for those:
Ds Rg Cn Uut Uup Fl Uus Uuo

**Comment by greglandrum** [comment]
I’d suggest taking 2.0 for those (for consistency with the others) and commenting it. It’s not like there is ever likely to be an experimental determination of these values! :-)

**Comment by UnixJunkie** [comment]
Ok, done.
Note that atomic number 113 appears two times in the very long string I updated.

**Comment by marcabrus** [comment]
I would like to step in and add another issue. I was also looking for a reference of van der waals radius of atoms, but also I found some differences in implementation of calculation of P_VSA from original Labute paper (2000). It seems to me that RDkit doesn't rely on the paper values for bond calculation, but on rB0 column of periodic table,  and  I don't find any reference for that column.
Moreover It seems that in original publication there is a difference for acid and oxide Oxygen (it's very unclear to me how to classify oxygen to me though). This difference is lost in RDkit implementation. I don't know if it's the same in the original Moe software, because I don't have it.

**Comment by marcabrus** [comment]
here the reference I cited, table 1 has some van der waals radius:
https://eurekamag.com/pdf/010/010106729.pdf

![2019-02-08](https://user-images.githubusercontent.com/335108/52488165-89abdb00-2bbf-11e9-9fc2-f1386cba56b4.png)

**Comment by UnixJunkie** [comment]
@marcabrus maybe this should be a separate issue: you want that P_VSA uses specific VdW radii from the corresponding publication

**Comment by marcabrus** [comment]
@UnixJunkie actually I brought the values from publication as an example. I've been diggin up and it seems that rb0 values are the ideal bond lenght reported in Mmff94 optimization data. Actually also labute extract ed the same values, but for the radii used another technique. Of course it's all explained in the publication. What is difficult to me is to understand the method underlying the vsa calculation for Rdkit.

**Comment by diogomart** [comment]
Hi all, posting here because it's related: covalent radius of phosphorous (0.75) is too small, should be similar to that of sulfur (~1)
https://github.com/rdkit/rdkit/blob/f8c78eaeb928b2707ced0dea329c5eff94126098/Code/GraphMol/atomic_data.cpp#L54

**Comment by UnixJunkie** [comment]
@diogomart those values come from the blue obelisk project. You can double check. If there is indeed a problem, maybe they would first have to update this radius value. Then, we might reflect the change in rdkit. And, you should really open a specific issue, if you are confident about it.

**Comment by diogomart** [comment]
Hi @UnixJunkie, thank you for your reply. I'm very confident the covalent radius for P should be closer to 1, but I won't be opening further issues.

**Comment by joseerlang** [comment]
Hello everyone,

Can it be that this ticket is resolved?

**Comment by UnixJunkie** [comment]
This issue should be closed.
The current values come from the blue obelisk project.
