### ISSUE TITLE
MaxMinPicker.LazyPick should support iterator interface

### ISSUE THREAD

**Issue by aparamon** [rdkit/rdkit#1833]
Currently, MaxMinPicker.LazyPick returns integer vector:
````python
indices = MaxMinPicker().LazyPick(dist, len(mols), 2000)
for i in indices:
    ...
````
Sometimes, however, the total number of picks is not known beforehand. It is proposed that MaxMinPicker additionally supports iterator interface, like so:
````python
for i in MaxMinPicker().GetPicks(dist, len(mols)):
    ...
````
which would yield the pick indices really lazily.

**Comment by greglandrum** [comment]
I'm going to have to think about this one for a bit. Though I'm pretty sure it's possible to do with the new code that we added in the 2017.09 release cycle, we haven't thought about allowing it to be used this way.
I suspect it's somewhat non-trivial, but it could certainly be interesting.

**Comment by bp-kelley** [comment]
Isn’t it somewhat “trivial” by feeding in the previous selection to the next pick?  It’s not optimal but it should work, and now that the lazy pick is faster, I expect it is a good 90% solution

----
Brian Kelley
