### ISSUE TITLE
RWMol::addAtom(Atom,bool) missing from Java wrappers

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1837]
There are some
This was an unintended side effect of #1713 and is because of this code that still remains in RWMol.i but which should have been removed:
```
%ignore RDKit::RWMol::addAtom(Atom *atom);
%ignore RDKit::RWMol::addAtom(Atom *atom,bool updateLabel);
%ignore RDKit::RWMol::addBond(Atom *beginAtom, Atom *endAtom, Bond::BondType order);
%ignore RDKit::RWMol::addBond(Atom *beginAtom, Atom *endAtom);
%ignore RDKit::RWMol::addBond(Bond *bond);
```

Thanks to @sroughley for noticing.

**Comment by sroughley** [comment]
Thanks @greglandrum .  The inevitable question... Do you know when this will transfer over to the KNIME nightly build?
