### ISSUE TITLE
Illegal instruction (popcnt) in a call to TanimotoSimilarity function

### ISSUE THREAD

**Issue by martin-sicho** [rdkit/rdkit#1840]
I am sorry if I have been posting here way too often in the last few days, but the new release is giving me a hard time :)

I realized that some of my C++ code that depends on rdkit no longer works with the `2018.03.1` release and exits with SIGILL (interestingly, all libraries and the binary was built on the target system with g++ 6.3.0):

```c++
#include <GraphMol/RWMol.h>
#include <GraphMol/SmilesParse/SmilesParse.h>
#include <DataStructs/BitOps.h>
#include <GraphMol/Fingerprints/MorganFingerprints.h>

int main() {
	RDKit::RWMol* mol1 = RDKit::SmilesToMol("CC");
	RDKit::RWMol* mol2 = RDKit::SmilesToMol("CCO");
	ExplicitBitVect* fp1 = RDKit::MorganFingerprints::getFingerprintAsBitVect(*mol1, 2, 2048);
	ExplicitBitVect* fp2 = RDKit::MorganFingerprints::getFingerprintAsBitVect(*mol2, 2, 2048);
	TanimotoSimilarity(*fp1, *fp2);

	return 0;
}
```

```
Process finished with exit code 4
```

Same happens in Python (binaries obtained from the conda distribution this time):

```python
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit import DataStructs

bz = Chem.MolFromSmiles("CC")
fp_bz = AllChem.GetMorganFingerprintAsBitVect(bz,radius=2,nBits=2048)
pyr = Chem.MolFromSmiles("CCO")
fp_pyr = AllChem.GetMorganFingerprintAsBitVect(pyr,radius=2,nBits=2048)
print("Similarity:",DataStructs.TanimotoSimilarity(fp_bz,fp_pyr))
``` 

```
Illegal instruction
```

Upon disassembly I tracked it down to the `popcnt` instruction, which the ancient CPU of my desktop (Intel Core 2 vPro) probably does not have as I came to conclude after a [quick google search](http://www.tomshardware.co.uk/answers/id-3128208/popcnt.html). 

I know this is a long shot, but has anyone ran into this problem? Is there a way for me to compile RDKit using an older instruction set so that I can run the code on my dinosaur of a computer? Maybe with an older version of g++? Any tips are much appreciated. Thanks and sorry for spamming here again.

**Comment by rvianello** [comment]
I don't know if with time any additional dependency from popcnt creeped into more parts of the toolkit, but if everything is still working as originally intended, passing `-D RDK_OPTIMIZE_NATIVE=OFF` on the cmake command line should disable the usage of the builtin popcnt instruction.

**Comment by greglandrum** [comment]
Since it can have a big performance impact and the majority of CPUs on systems people will be using the RDKit do provide the popcnt instruction, we opted to make it the default (and to build the conda recipes with that option turned on).
As @rvianello said: you should be able to disable this in your own RDKit builds by doing passing `-DRDK_OPTIMIZE_NATIVE=OFF" to cmake.
