### ISSUE TITLE
Changing fingerprint size

### ISSUE THREAD

**Issue by cgoliver** [rdkit/rdkit#1845]
**Description:**

 '
- RDKit Version:'2018.03.1'
- Platform: OSX 10.13.4

Trying to create fingerprints of different sizes using the `fpSize` keyboard argument. However when passing that argument I get the following error:

```
Traceback (most recent call last):
  File "mol_fingerprints.py", line 18, in <module>
    f = finger_dict("Ligands_noHydrogens_noMissing_1263_Instances.sdf")
  File "mol_fingerprints.py", line 14, in finger_dict
    fpSize=2048).ToBitString()
  File "/Users/carlosgonzalezoliver/anaconda/envs/my-rdkit-env/lib/python3.6/site-packages/rdkit/Chem/Fingerprints/FingerprintMols.py", line 72, in FingerprintMol
    fp = fingerprinter(mol, fpArgs['minPath'], fpArgs['maxPath'], fpArgs['fpSize'],
KeyError: 'minPath'
```
The error can be seen even when setting the fpSize to the default value:
```
ms = [x for x in Chem.SDMolSupplier(sdf)]
fps = [FingerprintMols.FingerprintMol(x, fpSize=2048) for x in ms]
```
I tried passing the `minPath` argument with its default value but then it asks for `maxPath` and when I pass that value it asks for another argument.

It seems that when I pass a keyword argument the defaults for the rest of the arguments are erased.

Thanks!

**Comment by greglandrum** [comment]
I will try to look into what's causing this particular problem, but I would recommend that you don't use the FingerprintMols() function (or anything else in the rdkit.Chem.Fingerprints.FingerprintMols module) and instead just call Chem.RDKFingerprintMol() directly.

It was reasonable for you to assume that the function would work, but in this case you chanced upon a piece of code that wasn't really intended to be used by users. Sorry about that.

**Comment by cgoliver** [comment]
Thanks, that works!
