### ISSUE TITLE
bivariate_normal deprecation in mlab.py of matplotlib

### ISSUE THREAD

**Issue by telukir** [rdkit/rdkit#1851]
Need to rewrite rdkit.Chem.Draw import SimilarityMaps

def [calcAtomGaussians](https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/Draw/__init__.py) (mol, a=0.03, step=0.02, weights=None): 

As  mlab.bivariate_normal​​is deprecated.

I was using latest RDKit 2018.03.1. With anaconda 4.5 in virtual environment. This error exists in rdkit 2017.09.3. And this problem exists for all the functions which use matplotlib 2.2 version. For deprecated functions refer [this page](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mlab.py)

- RDKit Version: 2018.03.1
- Platform: Ubuntu 16.04

```
from rdkit.Chem import AllChem as Chem
# from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem.Draw import SimilarityMaps
 

DB00641_Simvastatin = "[H][C@]12[C@H](C[C@@H](C)C=C1C=C[C@H](C)[C@@H]2CC[C@@H]1C[C@@H](O)CC(=O)O1)OC(=O)C(C)(C)CC"
StDB1098_Pravastatin = "CCCCNS(=O)(=O)c1ccccc1"

mol1 = Chem.MolFromSmiles(DB00641_Simvastatin)
mol2 = Chem.MolFromSmiles(StDB1098_Pravastatin)
 
fig, maxWeight = SimilarityMaps.GetSimilarityMapForFingerprint(mol2, mol1, SimilarityMaps.GetMorganFingerprint)
```
Running above code would produce this error: 

`/home/kiran/anaconda3/envs/rdkit-2018_03_1/lib/python3.5/site-packages/rdkit/Chem/Draw/__init__.py:285: MatplotlibDeprecationWarning: The bivariate_normal function was deprecated in version 2.2.
  Z = mlab.bivariate_normal(X, Y, a, a, mol._atomPs[0][0], mol._atomPs[0][1]) * weights[0]
/home/kiran/anaconda3/envs/rdkit-2018_03_1/lib/python3.5/site-packages/rdkit/Chem/Draw/__init__.py:287: MatplotlibDeprecationWarning: The bivariate_normal function was deprecated in version 2.2.
  Zp = mlab.bivariate_normal(X, Y, a, a, mol._atomPs[i][0], mol._atomPs[i][1])
`
This is working fine in the RDKit 2016.03.4 version.

Solution suggestions could be availabe in this [thread](https://sourceforge.net/p/rdkit/mailman/message/36309725/)

**Comment by greglandrum** [comment]
A straightforward way to do this would be to just bring over the implementation that's currently in `mlab.py`: https://github.com/matplotlib/matplotlib/blob/81e8154dbba54ac1607b21b22984cabf7a6598fa/lib/matplotlib/mlab.py#L1866
