### ISSUE TITLE
Same file name but different case

### ISSUE THREAD

**Issue by JLVarjo** [rdkit/rdkit#1876]
In Code/GraphMol/Descriptors/testdata are two files named with same name but with different case: "GETAWAY.out" and "getaway.out". This causes funny business in Windows: other one is overridden already in extracting the package, subsequently showing deletion in git.

The content of the files is similar, but I did not found any reference to either one in the code, so I don't know which one to remove. Or maybe both are deprecated, since "GETAWAY.new.out" seems to be used in testGETAWAY()?

**Comment by bp-kelley** [comment]
This is an issue on OS X as well, I’ll take a look.

----
Brian Kelley

**Comment by johnmay** [comment]
+1

**Comment by bp-kelley** [comment]
Well, didn’t this fall off my radar.  Thanks @johnmay for the poke.

**Comment by JLVarjo** [comment]
It seems to me that this is fixed since neither of the files mentioned are no longer present.
