### ISSUE TITLE
EmbedMultipleConf returns empty list

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#1878]
I have an instance where EmbedMultipleConfs returns an empty list and I can't figure out why. Searching around the web, I see that this is the expected behavior when the function is passed a molecules with nonsensical stereochemistry. However, I believe the stereochemistry to be valid in this example. I confirm that ChemAxon software also believes the SMILES to be valid.

- RDKit Version: 2017.09.3
- Platform: MacOS; python3.6

```
m = Chem.MolFromSmiles('O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O') 
ids = AllChem.EmbedMultipleConfs(m)
list(ids)
```

**Comment by greglandrum** [comment]
Hi.
You need to add hydrogens to the molecule:
```
In [13]: m = Chem.MolFromSmiles('O[C@H]1OC[C@@H](O)[C@H](O)[C@H]1O')
    ...: ids = AllChem.EmbedMultipleConfs(m)
    ...: list(ids)
    ...:
    ...:
Out[13]: []

In [14]: mh = Chem.AddHs(m)

In [15]: list(AllChem.EmbedMultipleConfs(mh))
Out[15]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

It is almost always a good idea to add hydrogens before generating conformations.

**Comment by paconius** [comment]
Yes! So simple. Thank you.
