### ISSUE TITLE
Is there a way to match atoms with range query?

### ISSUE THREAD

**Issue by greatlse** [rdkit/rdkit#1881]
**Description:**

I want to match C{2,3} like D{2,3}  using rdkit.
C{2,3} means a molecule that has a carbon link with 2 or 3 C atoms.
I have found the similar match method like z{2-} or D{2,4}. Can it be ported to  any atom type using smarts definition?

- RDKit Version: 2018.3
- Platform: win7

```
Your code sample here
```

**Comment by greatlse** [comment]
like CCCCC or CCCC can be matched by C{2-3}

**Comment by greglandrum** [comment]
Unfortunately not. The current substructure search functionality requires that all atoms be explicitly present.

**Comment by greatlse** [comment]
Thanks for your reply, Greg.
Neither smarts nor SLN can be used to solve the problem?

**Comment by greglandrum** [comment]
Not at the moment.
I have some thoughts on things that you could do, but I need to play a little bit before I can give a real answer
