### ISSUE TITLE
CanonicalizeConformer fails for Methane

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#1883]
Hi all. I'm looking to calculate the molecular volume for methane and I keep getting an error. Hoping someone can point out my mistake.

- RDKit Version: 2017.09.3
- Platform: MacOS, python3.6

```
m = Chem.MolFromSmiles('C')
m =Chem.AddHs(m)
AllChem.EmbedMolecule(m)
AllChem.ComputeMolVolume(m, confId=0)

RuntimeError: Invariant Violation
	
	Violation occurred on line 293 in file Code/GraphMol/MolTransforms/MolTransforms.cpp
	Failed Expression: dim >= 1
	RDKIT: 2017.09.3
	BOOST: 1_63
```

**Comment by greglandrum** [comment]
The problem is in `CanonicalizeConformer()`

**Comment by paconius** [comment]
It also seems to fail for water, ammonia, and any other single-heavy atom molecule.

**Comment by greglandrum** [comment]
yeah, I found that too

**Comment by greglandrum** [comment]
Ah, ok, this is easy to fix.
`CanonicalizeConformer()` ignores Hs by default.
