### ISSUE TITLE
Customizing AtomCompare

### ISSUE THREAD

**Issue by kristofarkas** [rdkit/rdkit#1899]
During MCS search is there a way to extend the `AtomCompare` option to include more sophisticated matching criterion. In my specific case I would like two atoms to match only if their partial charge difference is lower then a given threshold.

Or if there isn't, then how would I go about implementing something like this?

**Comment by kristofarkas** [comment]
The exact property to compare is `_TriposPartialCharge`.

**Comment by greglandrum** [comment]
This is a great suggestion. Making it easy to add new atom-atom or bond-bond comparison functions would be really helpful.

It's not easy to do this (and can't really be done at all without doing C++ work), but it's something I will try and find some time to do.

There's a connection here to #509

**Comment by kristofarkas** [comment]
Writing code for a generic algorithm that can take any property is probably hard as you said, but implementing this specific comparison (`_TriposPartialCharge`) should be easier, right? If yes, where in the code could I add this?
