### ISSUE TITLE
FingerprintMol does not work anymore ?

### ISSUE THREAD

**Issue by lfnothias** [rdkit/rdkit#1911]
- RDKit Version:  2018.03.2        py27h4ce040e_0    install with conda from conda-forge 
- Platform: MacOS X 10.13.4

For some reason, I cannot get FingerprintMols to work now  ? It used to work well before. It seems that other Fingerprint function are not showing up in the Chem package. I tried on a linux as well, and with Python3 as well.

Thank you for your help,

Here is the code I used:
```
from rdkit import Chem

mol_1 = Chem.MolFromSmiles("O=C(NCc1cc(OC)c(O)cc1)CCCC/C=C/C(C)C")
mol_2 = Chem.MolFromSmiles("CC(C)CCCCCC(=O)NCC1=CC(=C(C=C1)O)OC")
fp_A = FingerprintMols.FingerprintMol(mol_1)
fp_B = FingerprintMols.FingerprintMol(mol_2)
fp_A
sim_vector = []
sim_vector.append(DataStructs.FingerprintSimilarity(fp_A,fp_B))
sim_vector
```

**Comment by greglandrum** [comment]
What is the error message that you see?

**Comment by lfnothias** [comment]
Thank you. Here is the error.
```
NameErrorTraceback (most recent call last)
<ipython-input-21-d513a3b0543f> in <module>()
      3 #fp_A = FingerprintMols.FingerprintMol(mol1)
      4 #Fingerprint(mol_1,mol_2)
----> 5 fp_A = FingerprintMols.FingerprintMol(mol_1)
      6 fp_B = FingerprintMols.FingerprintMol(mol_2)
      7 fp_A

NameError: name 'FingerprintMols' is not defined
```

**Comment by greglandrum** [comment]
That looks like you forgot to do:
`from rdkit.Chem.Fingerprints import FingerprintMols`

**Comment by lfnothias** [comment]
Thank you for your help. It works.
I dont know why, but before it was working well without it.
