### ISSUE TITLE
Library .so names missing RDKit?

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1913]
@mcs07 mentioned to me that the library names may have accidentally changed.

When I do a make install on Linux with the git master I see:
```
libAlignment.so 
libRDKitAlignment_static.a
```

Is the first one also supposed to be libRDKitAlignment.so?

**Comment by mcs07** [comment]
Here's the commit: https://github.com/rdkit/rdkit/commit/0959261f37a152fbe958ccbd1e3beeaaac464329#diff-6723d700feb530b6415fce82e355cf5cL88

(Accidentally?) reverses #1349?

**Comment by greglandrum** [comment]
Yeah, those changes have ended up causing some ripples that it’s taking a while to sort out. The name changes were not intentional. Thanks for the report!

**Comment by greglandrum** [comment]
Fixed by #1915
