### ISSUE TITLE
anaconda, python2 & pyspark

### ISSUE THREAD

**Issue by cassar1** [rdkit/rdkit#1922]
I installed rdkit using conda:
conda create -c rdkit -n my-rdkit-env rdkit python=2.7 then I installed pyspark.

However running spark application (local mode), results in warning: 
depickling from a version number (9.0) that is higher than our version (7.2)

The warning seems that it is coming from a call to zipWithIndex of pyspark, however a similar function is already called previously with no warning.

I am running in ubuntu 16.04

**Comment by bp-kelley** [comment]
We'll need more information here but this error doesn't appear to be coming from rdkit.
