### ISSUE TITLE
memory leak in Get3DDistanceMatrix

### ISSUE THREAD

**Issue by jaechanglim** [rdkit/rdkit#1924]
- RDKit Version: 2018.03.1
- Platform: centos

I found that memory is accumulated when I ran the following simple code

from rdkit import Chem
from rdkit.Chem.rdmolops import Get3DDistanceMatrix
from rdkit.Chem.rdmolfiles import MolFromMol2File, MolFromPDBFile, PDBWriter
m = MolFromPDBFile('../autodock/complex.pdb')
while True:
    Get3DDistanceMatrix(m)

you can use your own pdb file

any body can fix it?

**Comment by greglandrum** [comment]
Confirmed on Windows as well.
Thanks for reporting the problem!
