### ISSUE TITLE
Atom with bond to itself is accepted by the SMILES parser.

### ISSUE THREAD

**Issue by tblaschke** [rdkit/rdkit#1925]
**Description:**

- RDKit Version: 2018.03.1
- Platform: Linux x86_64 (CentOS 7)

The RDKit SMILES parser accept SMILES where an atom has a bond to itself. However, according to the opensmiles specs we should reject these SMILES
http://opensmiles.org/opensmiles.html 

```
from rdkit import Chem
mol = Chem.MolFromSmiles("C11")
if mol:
    print("We shouldn't parse this")
else:
    print("Illegal SMILES. Atom bond to itself") 
```

**Comment by bp-kelley** [comment]
@undeadpixel I just tested the same issue :)  Yeah, that is bad, I'll put it on the list.

**Comment by bp-kelley** [comment]
The current implementation looks to silently ignore these (except for the single atom case)

```
>>> m = Chem.MolFromSmiles("C1CCCCC22334455661778899")
>>> Chem.MolToSmiles(m)
'C1CCCCC1'
```

**Comment by undeadpixel** [comment]
@bp-kelley I think they should not be silently ignored, as they are plainly wrong (and, as @tblaschke has said before, do not comply with the specification)... Would it be possible to add a "strict" flag or something similar?

**Comment by greglandrum** [comment]
I don't think it should be silently ignored or require a strict flag. These are clearly errors and we should generate errors for them.

**Comment by bp-kelley** [comment]
Agreed, I was just referring to the current behavior.
