### ISSUE TITLE
Would you please make rdkit support chirality diagnosis from SDF format?

### ISSUE THREAD

**Issue by Kael-the-Mad** [rdkit/rdkit#1926]
**Description:**

 '2018.03.2'
- RDKit Version:
- Platform: Windows Anaconda x64

When loading a chiral molecule with 
m1 = Chem.MolFromMolFile('*.sdf')
then, to get its isomeric SMILES code
Chem.MolToSmiles(m1)
It will return a canonical SMILES without any chiral marks

After I use OpenBabel to turn the SDF format into MOL
It can normally diagnose the chirality
When I use OpenBabel
obabel *.sdf -O *.smi
It will generate a SMILES code with chiral marks

Could you please improve the RDKit Chem module to make it capable of diagnose the chirality from SDF files? 

Yours sincere

Kael Wang

```
Your code sample here
```

**Comment by Kael-the-Mad** [comment]
Sorry it should be 
m1 = Chem.MolFromMolFile('*.sdf')

**Comment by greglandrum** [comment]
Hi,
In order for us to be able to figure out what's going on, we need to see one of the files where you're having the problem.

This is not a general problem with the RDKit. Here's a short sample that shows that:
```
In [49]: print(mb)

     RDKit          2D

  7  7  0  0  0  0  0  0  0  0999 V2000
    3.8660    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3660    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3660    1.5000    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
    2.3660   -1.5000    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.8660    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4330    0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4330   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  6
  2  3  1  0
  2  4  1  0
  2  5  1  0
  5  6  1  0
  6  7  1  0
  7  5  1  0
M  END


In [50]: nm = Chem.MolFromMolBlock(mb)

In [51]: Chem.MolToSmiles(nm)
Out[51]: 'C[C@](F)(Cl)C1CC1'
```

**Comment by Kael-the-Mad** [comment]
Hi, 
Sorry for this slow reply (diff. time zones)
I would like to describe my steps as follows:
1. to download a proper SDF (with 3D coords) from the Pubchem Port (https://pubchem.ncbi.nlm.nih.gov/).
Specifically, I've tried 3 molecules: Lindane, Dieldrin and Endrin, whose Pubchem CIDs are 727, 969491, and 12358480, respectively. Then, I downloaded the 3D SDF file provided at the 3D Conformer section of corresponding pages.
For your convenience, allow me to paste the content of the SDF file of Endrin (whose downloaded file name shall be 'Structure3D_CID_12358480.sdf')
-----the content of this sdf file------ (do not include this line!)
12358480
  -OEChem-06201822163D

 27 31  0     1  0  0  0  0  0999 V2000
   -1.4562   -0.4263    2.7709 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -1.4576   -0.4286   -2.7702 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -3.4595    0.2328    0.0006 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -2.3100   -2.3954    0.0012 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.6441    2.5691    1.7010 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.6455    2.5678   -1.7030 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    3.4895    0.7398   -0.0004 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.3637   -1.0916    0.7901 C   0  0  1  0  0  0  0  0  0  0  0  0
    0.3634   -1.0920   -0.7896 C   0  0  2  0  0  0  0  0  0  0  0  0
    1.8488   -0.8030    1.1335 C   0  0  2  0  0  0  0  0  0  0  0  0
    1.8483   -0.8031   -1.1337 C   0  0  1  0  0  0  0  0  0  0  0  0
    2.2717    0.6001    0.7449 C   0  0  2  0  0  0  0  0  0  0  0  0
    2.2714    0.6001   -0.7452 C   0  0  1  0  0  0  0  0  0  0  0  0
    2.5055   -1.6494   -0.0002 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8753   -0.2056    1.1331 C   0  0  1  0  0  0  0  0  0  0  0  0
   -0.8760   -0.2064   -1.1327 C   0  0  2  0  0  0  0  0  0  0  0  0
   -1.8803   -0.6506    0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6787    1.2215    0.6698 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6791    1.2210   -0.6707 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1667   -2.1179    1.1351 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1664   -2.1185   -1.1340 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1444   -1.0930    2.1434 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1436   -1.0933   -2.1437 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.9506    1.4227    1.3526 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.9500    1.4227   -1.3528 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.6000   -1.6053   -0.0004 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1990   -2.7018    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1 15  1  0  0  0  0
  2 16  1  0  0  0  0
  3 17  1  0  0  0  0
  4 17  1  0  0  0  0
  5 18  1  0  0  0  0
  6 19  1  0  0  0  0
  7 12  1  0  0  0  0
  7 13  1  0  0  0  0
  8  9  1  0  0  0  0
  8 10  1  0  0  0  0
  8 15  1  0  0  0  0
  8 20  1  0  0  0  0
  9 11  1  0  0  0  0
  9 16  1  0  0  0  0
  9 21  1  0  0  0  0
 10 12  1  0  0  0  0
 10 14  1  0  0  0  0
 10 22  1  0  0  0  0
 11 13  1  0  0  0  0
 11 14  1  0  0  0  0
 11 23  1  0  0  0  0
 12 13  1  0  0  0  0
 12 24  1  0  0  0  0
 13 25  1  0  0  0  0
 14 26  1  0  0  0  0
 14 27  1  0  0  0  0
 15 17  1  0  0  0  0
 15 18  1  0  0  0  0
 16 17  1  0  0  0  0
 16 19  1  0  0  0  0
 18 19  2  0  0  0  0
M  END
> <PUBCHEM_COMPOUND_CID>
12358480

> <PUBCHEM_CONFORMER_RMSD>
0.6

> <PUBCHEM_CONFORMER_DIVERSEORDER>
1

> <PUBCHEM_MMFF94_PARTIAL_CHARGES>
16
1 -0.29
10 0.09
11 0.09
12 -0.05
13 -0.05
15 0.43
16 0.43
17 0.58
2 -0.29
24 0.1
25 0.1
3 -0.29
4 -0.29
5 -0.14
6 -0.14
7 -0.3

> <PUBCHEM_EFFECTIVE_ROTOR_COUNT>
0.6

> <PUBCHEM_PHARMACOPHORE_FEATURES>
3
1 7 acceptor
7 8 9 15 16 17 18 19 rings
8 7 8 9 10 11 12 13 14 rings

> <PUBCHEM_HEAVY_ATOM_COUNT>
19

> <PUBCHEM_ATOM_DEF_STEREO_COUNT>
8

> <PUBCHEM_ATOM_UDEF_STEREO_COUNT>
0

> <PUBCHEM_BOND_DEF_STEREO_COUNT>
0

> <PUBCHEM_BOND_UDEF_STEREO_COUNT>
0

> <PUBCHEM_ISOTOPIC_ATOM_COUNT>
0

> <PUBCHEM_COMPONENT_COUNT>
1

> <PUBCHEM_CACTVS_TAUTO_COUNT>
1

> <PUBCHEM_CONFORMER_ID>
00BC935000000001

> <PUBCHEM_MMFF94_ENERGY>
117.2959

> <PUBCHEM_FEATURE_SELFOVERLAP>
15.242

> <PUBCHEM_SHAPE_FINGERPRINT>
10863032 1 18413107281522386483
10948715 1 18410574002347365453
12423570 1 15391942997041076917
13024252 1 16805602572741264110
14142880 1 18411139130282463200
144361 1 18342465806910831488
14787075 74 16982366873856762698
14817 1 10909682566451094624
15881359 60 18198041617486731197
16945 1 17985856768210034674
22344851 341 16155647074877348423
23419403 2 17690251113051503535
2748010 2 17750537198163722650
296302 2 17168431570258529934
5845 1 7844923449003039521
81228 2 17822581507799420661

> <PUBCHEM_SHAPE_MULTIPOLES>
396.36
3.88
2.29
2.26
1.29
0.9
0
-0.77
0
-0.66
0
-1.11
0.34
0

> <PUBCHEM_SHAPE_SELFOVERLAP>
848.092

> <PUBCHEM_SHAPE_VOLUME>
224.9

> <PUBCHEM_COORDINATE_TYPE>
2
5
10

$$$$
--------end of the file ------ (do not include this line)
2. Now we can either 
m1 = Chem.MolFromMolBlock(the_sdf_string_above)
or
m1 = Chem.MolFromMolFile('Structure3D_CID_12358480.sdf')
Then, let's test:
Chem.MolToSmiles(m1, isomericSmiles=True)
it gives:
'ClC1C(Cl)C(Cl)C(Cl)C(Cl)C1Cl'
That does not include any isomeric or chirality info.
3. Use OpenBabel to translate the SDF into MOL format (with windows cmd terminal)
obabel  Structure3D_CID_12358480.sdf -O endrin.mol
-------this is the content of the endrin.mol file -----(do not include this line!)
12358480
 OpenBabel06221808403D

 27 31  0  0  1  0  0  0  0  0999 V2000
   -1.4562   -0.4263    2.7709 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -1.4576   -0.4286   -2.7702 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -3.4595    0.2328    0.0006 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -2.3100   -2.3954    0.0012 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.6441    2.5691    1.7010 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.6455    2.5678   -1.7030 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    3.4895    0.7398   -0.0004 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.3637   -1.0916    0.7901 C   0  0  1  0  0  0  0  0  0  0  0  0
    0.3634   -1.0920   -0.7896 C   0  0  2  0  0  0  0  0  0  0  0  0
    1.8488   -0.8030    1.1335 C   0  0  2  0  0  0  0  0  0  0  0  0
    1.8483   -0.8031   -1.1337 C   0  0  1  0  0  0  0  0  0  0  0  0
    2.2717    0.6001    0.7449 C   0  0  2  0  0  0  0  0  0  0  0  0
    2.2714    0.6001   -0.7452 C   0  0  1  0  0  0  0  0  0  0  0  0
    2.5055   -1.6494   -0.0002 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8753   -0.2056    1.1331 C   0  0  1  0  0  0  0  0  0  0  0  0
   -0.8760   -0.2064   -1.1327 C   0  0  2  0  0  0  0  0  0  0  0  0
   -1.8803   -0.6506    0.0005 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6787    1.2215    0.6698 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6791    1.2210   -0.6707 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1667   -2.1179    1.1351 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1664   -2.1185   -1.1340 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1444   -1.0930    2.1434 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1436   -1.0933   -2.1437 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.9506    1.4227    1.3526 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.9500    1.4227   -1.3528 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.6000   -1.6053   -0.0004 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1990   -2.7018    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1 15  1  0  0  0  0
  2 16  1  0  0  0  0
  3 17  1  0  0  0  0
  4 17  1  0  0  0  0
  5 18  1  0  0  0  0
  6 19  1  0  0  0  0
  7 12  1  0  0  0  0
  7 13  1  0  0  0  0
  8  9  1  6  0  0  0
  8 20  1  0  0  0  0
  9 11  1  6  0  0  0
  9 21  1  0  0  0  0
 10  8  1  6  0  0  0
 10 14  1  0  0  0  0
 10 22  1  0  0  0  0
 11 13  1  1  0  0  0
 11 14  1  0  0  0  0
 11 23  1  0  0  0  0
 12 10  1  1  0  0  0
 12 24  1  0  0  0  0
 13 12  1  1  0  0  0
 13 25  1  0  0  0  0
 14 26  1  0  0  0  0
 14 27  1  0  0  0  0
 15  8  1  6  0  0  0
 15 17  1  0  0  0  0
 15 18  1  0  0  0  0
 16  9  1  1  0  0  0
 16 17  1  0  0  0  0
 16 19  1  0  0  0  0
 18 19  2  0  0  0  0
M  END
------end of the file -----(do not include this line)
Then I did the similar steps
m2 = Chem.MolFromMolFile('endrin.mol')
Then, test the m2 SMILES code
Chem.MolToSmiles(m2)
which gives
Out[7]: 'ClC1=C(Cl)[C@]2(Cl)[C@H]3[C@H]([C@@H]4C[C@H]3[C@H]3O[C@@H]43)[C@@]1(Cl)
C2(Cl)Cl'
That is satisfactory!
***
I have noticed that you have a MOL format in your reply. But we must be careful that the SDF and MOL
are indeed different in details, although both format can be legally read into a RDKit molecule from the MolFromMolFile/Block functions. Probably this issue can originate from the MolFromMolFile mechanisms. I hope that you can make it capable of handling the chirality from SDF file (the MOL format has been supported well).
*
Or you should add some warnings in the tutorials or websites to warn about this issue. 

We must notice that althought the sdf coords downloaded from the PubChem portal show distinct conformations of Dieldrin and Endrin. The RDKit read these SDF files and generate the same SMILES code for them, due to the failure to recognize chirality directly from the SDF format. This could be a problem!

Yours sincere,

Kael Wang.

**Comment by greglandrum** [comment]
The RDKit only does automatic stereo perception if there is at least one bond in the molecule that has stereochemistry indicated via bond wedging information. This is probably not the right thing for molecules with 3D coordinates.

In your case, you should be able to do:
```
m1 = Chem.MolFromMolFile('Structure3D_CID_12358480.sdf')
Chem.AssignAtomChiralTagsFromStructure(m1) 
```
and get a SMILES that has the correct stereo information indicated.

**Comment by Kael-the-Mad** [comment]
It worked!
I have learned a lot from this dialog. (I know) I really need to do some homework on it.
But posting this issue accelerated my learning process ...

Thank you for your kind and informative reply!

Best regards

Kael

**Comment by greglandrum** [comment]
Glad to hear that things are working.
I'm going to close this now that the question is answered.
