### ISSUE TITLE
Possibly incorrect aromatic SMILES generated for structure

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#1928]
Using RDKit 2018.03, given the following Kekule SMILES:
```
C12=C3C=CC=C1CCC(=O)C2=C4OC5=CC=CC6=C5C(=C(N4)O3)C(=O)CC6
```
...RDKit will generate the following aromatic SMILES:
```
c12c3cccc1CCC(=O)c2c1oc2cccc4c2c(c(o3)-n-1)C(=O)CC4
```
The problem is the "-n-". How many hydrogens are on the nitrogen? It's neither pyrrole-type nor pyridine-type.

Off-tangent sidenote: It's probably a bug in this case, but in my ACS talk I think I had a bonus slide about this particular syntax in the context of "c1cc-n-c1", which I think would be a great way to represent pyrrole radical. Everyone else in the office disagreed, naturally.

**Comment by greglandrum** [comment]
Yep, that looks like a bug.
Here's a slightly simpler version:
```
In [11]: Chem.CanonSmiles('N1C2=CC3=CC=CC=C3OC1=CC1=C(O2)C=CC=C1')
Out[11]: 'c1ccc2oc3cc4ccccc4oc(cc2c1)-n-3'
```

**Comment by baoilleach** [comment]
Great.
