### ISSUE TITLE
license confusion

### ISSUE THREAD

**Issue by skearnes** [rdkit/rdkit#1931]
Some of the recently added modules have unclear licensing. For instance:

- rdkit/Chem/EnumerateHeterocycles.py is copyright DE Shaw Research (including "all rights reserved") without any reference to the BSD governing the rest of RDKit.
- Contrib/Fastcluster and Contrib/IFG have no license information, but do mention specific authors

**Comment by bp-kelley** [comment]
I can ask Brian Cole to update the code.   This is our fault for not checking the license before being accepted.

----
Brian Kelley

**Comment by bp-kelley** [comment]
@coleb can we get a license PR for enumerateheterocycles?

**Comment by greglandrum** [comment]
It's certainly good to be explicit, but I've just been assuming that things are covered by the license.txt that's in the top-level directory.
We should be a bit more careful with checking license in the future.

**Comment by greglandrum** [comment]
The two contrib changes are in: #1932 and #1933

**Comment by skearnes** [comment]
Thanks!

**Comment by coleb** [comment]
@bp-kelley and @greglandrum , on vacation this week, but will definitely follow up when I'm back. So I know what is being asked, just asking that the copyright in rdkit/Chem/EnumerateHeterocycles.py be updated to reference the parent BSD license? or just removal of 'DE Shaw Research' entirely to make it easier going forward?

Would like to get it straightened out as I'd like to make a similar contribution to EnumerateHeterocycles for aliphatic systems by the UGM. :-)

**Comment by greglandrum** [comment]
@coleb : I think it would be fine to just add:
```
#  This file is part of the RDKit.
#  The contents are covered by the terms of the BSD license
#  which is included in the file license.txt, found at the root
#  of the RDKit source tree.
```

**Comment by skearnes** [comment]
ping?

**Comment by coleb** [comment]
I've started the leg work on my side.

**Comment by skearnes** [comment]
Any updates?

**Comment by coleb** [comment]
Just created pull request #1970 to include Greg's text after getting the internal clearance. Sorry for the delay!

**Comment by skearnes** [comment]
Thanks!

**Comment by bp-kelley** [comment]
Merged :)

**Comment by bp-kelley** [comment]
Is that all of them so far?
