### ISSUE TITLE
blank Murcko scaffolds for certain smiles

### ISSUE THREAD

**Issue by sabrihamad** [rdkit/rdkit#1947]
Hi,
I get blank Murcko scaffold for the following smiles:

ONC(=O)CCCCCCC(=O)NO

N[C@H](CS)CCCC(=O)NO
```
In [1]: from rdkit.Chem.Scaffolds import MurckoScaffold

In [2]: MurckoScaffold.MurckoScaffoldSmiles('ONC(=O)CCCCCCC(=O)NO')
Out[2]: ''

In [3]: MurckoScaffold.MurckoScaffoldSmiles('N[C@H](CS)CCCC(=O)NO')
Out[3]: ''
```
any idea why?
Thanks

**Comment by gedeck** [comment]
Hello,

Your structures have no ring system. Murcko scaffolds are what is left over if you remove the side chains. There is no definition for acyclic structures

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by sabrihamad** [comment]
@gedeck Thanks a lot for the clarification. I am sorry if that was a stupid question as I don't have a chemistry background.

Sabri
