### ISSUE TITLE
RuntimeError when importing rdkit.Chem.Descriptors with Python 3.7

### ISSUE THREAD

**Issue by drkeoni** [rdkit/rdkit#1948]
**Description:**

- RDKit Version: 2018.09.1dev1 (installed with brew install --with-python3)
- Platform: MacOS High Sierra 10.13.5, python 3.7.0

I've been encountering the following traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/rdkit/Chem/Descriptors.py", line 208, in <module>
    _setupDescriptors(locals())
  File "/usr/local/lib/python3.7/site-packages/rdkit/Chem/Descriptors.py", line 37, in _setupDescriptors
    for nm, thing in namespace.items():
RuntimeError: dictionary changed size during iteration
```
when running `from rdkit.Chem import Descriptors`.

I also have access to a Linux system running python 3.6.5, rdkit 2018.03.2 and don't see this problem.

I was able to patch the problem and get Descriptors to load by copying the namespace before iterating (in file `rdkit/Chem/Descriptors.py`):
```
_namespace = dict(namespace)
for nm, thing in _namespace.items():
  if nm[0] != '_' and _isCallable(thing):
    _descList.append((nm, thing))
```

Reporting here in case anyone else sees this and if this patch is generally useful for incorporating into rdkit.  Looks pretty innocent to me, but I also don't know why this would be broken just in my environment and not generally broken.

**Comment by bp-kelley** [comment]
It looks like this is a change in behavior for python 3.7.

Thanks for letting us know!

----
Brian Kelley
