### ISSUE TITLE
There should be some transparent way to call MergeQueryHs() on reactants in a reaction.

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#1951]
As an example, the H in this SMARTS: `[H][C:1]#[C:2][C:3].[O:4]>>[O:4]-[C:1]#[C:2][C:3]` is unlikely to actually match anything when the reaction is applied, so we really should be able to get to the reaction that's equivalent to: `[H][C:1]#[C:2][C:3].[O:4]>>[O:4]-[C:1]#[C:2][C:3]` automatically.

This applies to reactions built from SMARTS and RXN blocks.

Maybe we just need a version of `MergeQueryHs()` that takes a reaction?

**Comment by bp-kelley** [comment]
SanitizeRxn is the current mechanism that does this.

```
typedef enum {
  SANITIZE_NONE = 0x0,
  SANITIZE_RGROUP_NAMES = 0x1,
  SANITIZE_ATOM_MAPS = 0x2,
  SANITIZE_ADJUST_REACTANTS = 0x4,
  SANITIZE_MERGEHS = 0x8,
  SANITIZE_ALL = 0xFFFFFFFF
} SanitizeRxnFlags;
```

Note the SANITIZE_MERGEHS.  It also attempts to aromatize as well which is a more subtle issue.

**Comment by bp-kelley** [comment]
Example: ```>>> r = Chem.ReactionFromSmarts("[H][C:1]#[C:2][C:3].[O:4]>>[O:4]-[C:1]#[C:2][C:3]")
>>> Chem.SanitizeRxn(r)
rdkit.Chem.rdChemReactions.SanitizeFlags.SANITIZE_NONE
>>> Chem.ReactionToSmarts(r)
'[C&!H0:1]#[C:2]-,:[C:3].[O:4]>>[O:4]-[C:1]#[C:2]-,:[C:3]'
```

**Comment by greglandrum** [comment]
Ah, that makes sense. Cool. In that case I will close this.
