### ISSUE TITLE
import error of rdkit after updating to latest version

### ISSUE THREAD

**Issue by enryH** [rdkit/rdkit#1957]
Hey,

after running an update of all conda packages, importing rdkit throws an error... I tried to create a new environment only installing rdkit and its dependencies (as describe as standard installation using anaconda), but I still get the same error.  Any clue how to fix it?

```python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import rdkit
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6b72bd8913ab> in <module>()
----> 1 import rdkit

~/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/rdkit/__init__.py in <module>()
      1 try:
----> 2   from .rdBase import rdkitVersion as __version__
      3 except ImportError:
      4   __version__ = 'Unknown'
      5   raise

ImportError: libboost_python3.so.1.65.1: cannot open shared object file: No such file or directory

```

I'm using Ubuntu 16.04 LTS.

Cheers,
Henry

**Comment by enryH** [comment]
... 5min too early... libboost was automatically installed as version 1.67.0 using 
```python
conda create -n rdkit-env -c rdkit rdkit 
```
and then it does not work. So to close this, installing works using:

```python
conda create -n rdkit-env -c rdkit rdkit libboost=1.65.1
```
I do not know well how packaging works, but I guess this can be set as an requirement somewhere.

Best, Henry

**Comment by greglandrum** [comment]
This is a bug, but it's in the conda-rdkit system. I added a report there, and it's linked above.

**Comment by soerendip** [comment]
Just got a similar error 

> ImportError: libboost_python3.so.1.65.1: cannot open shared object file: No such file or directory
