### ISSUE TITLE
make install does not install anything ?

### ISSUE THREAD

**Issue by mboisson** [rdkit/rdkit#1960]
**Description:**

Trying to compile RDKit from source and install it on a cluster. I run 

cmake /dev/shm/mboisson/avx2/RDKit/2018.03.2/GCC-5.4.0/rdkit-Release_2018_03_2/ -DCMAKE_INSTALL_PREFIX=/home/mboisson/.local/easybuild/software/2017/avx2/Compiler/gcc5.4/rdkit/2018.03.2 -DCMAKE_C_COMPILER='gcc' -DCMAKE_Fortran_FLAGS='-O3 -march=core-avx2 -fno-math-errno' -DCMAKE_CXX_FLAGS='-O3 -march=core-avx2 -fno-math-errno' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_Fortran_COMPILER='gfortran' -DCMAKE_C_FLAGS='-O3 -march=core-avx2 -fno-math-errno' -DCMAKE_VERBOSE_MAKEFILE=ON  -DBOOST_ROOT=$EBROOTBOOST -DCMAKE_SKIP_RPATH=ON -DPYTHON_EXECUTABLE=$EBROOTPYTHON/bin/python  -DPYTHON_INCLUDE_DIR=$EBROOTPYTHON/include/python2.7 -DPYTHON_LIBRARY=$EBROOTPYTHON/lib/libpython2.7.so -DPYTHON_NUMPY_INCLUDE_PATH=$EBROOTSCIPYMINSTACK/lib/python2.7/site-packages/numpy/core/include

then
make -j 8

and it compiles fine. When I run "make install" however, it outputs a lot of text, but nothing gets installed in /home/mboisson/.local/easybuild/software/2017/avx2/Compiler/gcc5.4/rdkit/2018.03.2  which is where the CMAKE_INSTALL_PREFIX is set to.

Am I missing something ?

**Comment by mboisson** [comment]
Thanks. That worked. Although it does not make sense not to honour CMAKE_INSTALL_PREFIX when it is provided without this flag.
  

  
  

  
  
>

**Comment by mboisson** [comment]
Another problem I ran into is that it only compiles static libraries for `libRDKit*`   I looked through the cmake options, but I'm not quite what option to enable.

**Comment by bp-kelley** [comment]
Here is the basics of how I build rdkit for python distributions (on osx):  ```CXXFLAGS="-std=c++11" cmake \
    -D RDK_INSTALL_INTREE=OFF \
    -D RDK_INSTALL_STATIC_LIBS=OFF \
    -D RDK_BUILD_INCHI_SUPPORT=ON \
    -D RDK_BUILD_AVALON_SUPPORT=ON \
```

Hope this helps

**Comment by greglandrum** [comment]
@mboisson : I'm surprised that you would only find static libraries. Unless you're building on Windows, I believe that dynamic libraries are always created.

**Comment by mcs07** [comment]
The lack of the “RDKit” prefix on the libraries in 2018.03.2 may make it look like they are missing?

**Comment by mboisson** [comment]
Mmm, did the RDKit prefix get removed in 2018 for the shared objects ? I have
```
[mboisson@build-node MySQL]$ ls /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/rdkit/2018.03.2/lib
libAlignment.so          libForceField.so           libRDGeneral.so                    libRDKitFMCS_static.a                 libRDKitPartialCharges_static.a       libShapeHelpers.so
libCatalogs.so           libFragCatalog.so          libRDGeometryLib.so                libRDKitForceFieldHelpers_static.a    libRDKitRDBoost_static.a              libSimDivPickers.so
libChemicalFeatures.so   libGraphMol.so             libRDKitAlignment_static.a         libRDKitForceField_static.a           libRDKitRDGeneral_static.a            libSLNParse.so
libChemReactions.so      libhc.so                   libRDKitCatalogs_static.a          libRDKitFragCatalog_static.a          libRDKitRDGeometryLib_static.a        libSmilesParse.so
libChemTransforms.so     libInfoTheory.so           libRDKitChemicalFeatures_static.a  libRDKitGraphMol_static.a             libRDKitReducedGraphs_static.a        libStructChecker.so
libcoordgenlib.so        libmaeparser.so            libRDKitChemReactions_static.a     libRDKithc_static.a                   libRDKitRGroupDecomposition_static.a  libSubgraphs.so
libDataStructs.so        libMMPA.so                 libRDKitChemTransforms_static.a    libRDKitInfoTheory_static.a           libRDKitShapeHelpers_static.a         libSubstructLibrary.so
libDepictor.so           libMolAlign.so             libRDKitcoordgenlib_static.a       libRDKitmaeparser_static.a            libRDKitSimDivPickers_static.a        libSubstructMatch.so
libDescriptors.so        libMolCatalog.so           libRDKitDataStructs_static.a       libRDKitMMPA_static.a                 libRDKitSLNParse_static.a             libTrajectory.so
libDistGeometry.so       libMolChemicalFeatures.so  libRDKitDepictor_static.a          libRDKitMolAlign_static.a             libRDKitSmilesParse_static.a          python2.7
libDistGeomHelpers.so    libMolDraw2D.so            libRDKitDescriptors_static.a       libRDKitMolCatalog_static.a           libRDKitStructChecker_static.a        python3.5
libEigenSolvers.so       libMolHash.so              libRDKitDistGeometry_static.a      libRDKitMolChemicalFeatures_static.a  libRDKitSubgraphs_static.a            python3.6
libFileParsers.so        libMolInterchange.so       libRDKitDistGeomHelpers_static.a   libRDKitMolDraw2D_static.a            libRDKitSubstructLibrary_static.a     rdkit-config.cmake
libFilterCatalog.so      libMolTransforms.so        libRDKitEigenSolvers_static.a      libRDKitMolHash_static.a              libRDKitSubstructMatch_static.a       rdkit-config-version.cmake
libFingerprints.so       libOptimizer.so            libRDKitFileParsers_static.a       libRDKitMolInterchange_static.a       libRDKitTrajectory_static.a           rdkit-targets.cmake
libFMCS.so               libPartialCharges.so       libRDKitFilterCatalog_static.a     libRDKitMolTransforms_static.a        libReducedGraphs.so                   rdkit-targets-release.cmake
libForceFieldHelpers.so  libRDBoost.so              libRDKitFingerprints_static.a      libRDKitOptimizer_static.a            libRGroupDecomposition.so
``` 

In previous versions, our script was checking for the presence of 
```
		"lib/libRDKitEigenSolvers.so", "lib/libRDKitRDBoost.so", "lib/libRDKitRDGeneral.so"
```

**Comment by greglandrum** [comment]
There was a bug that was introduced in 2018.03.2 (#1913) that has been fixed (#1915) in master and for 2018.03.3.
@mboisson : can you please try the most recent version and see if that fixes the problem?

**Comment by mboisson** [comment]
Thanks @greglandrum, it does seem to fix the issue.

**Comment by greglandrum** [comment]
Excellent. so it's probably ok to close this then, right?

**Comment by mboisson** [comment]
Yes, although I would still recommend to honour `CMAKE_INSTALL_PREFIX` when it is specified rather than requiring to specify another application-specific flag.
