### ISSUE TITLE
assigned chirality wrongly (SDF -> SMILES)

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [rdkit/rdkit#1962]
I tried to distinguish these two molecules in a SDF file.
```

  C[C@@H](O)N	

  5  4  0  0  0  0            999 V2000
    0.0000    0.0000    0.0000 C   0  0  2  0  0  0
    0.0000    0.0000    0.0000 C   0  0
    0.0000    0.0000    0.0000 N   0  0
    0.0000    0.0000    0.0000 O   0  0
    0.0000    0.0000    0.0000 H   0  0
  1  2  1  0
  1  3  1  0
  1  4  1  0
  1  5  1  1
M  END

$$$$

  C[C@H](O)N	

  5  4  0  0  0  0            999 V2000
    0.0000    0.0000    0.0000 C   0  0  1  0  0  0
    0.0000    0.0000    0.0000 C   0  0
    0.0000    0.0000    0.0000 N   0  0
    0.0000    0.0000    0.0000 O   0  0
    0.0000    0.0000    0.0000 H   0  0
  1  2  1  0
  1  3  1  0
  1  4  1  0
  1  5  1  1
M  END

$$$$
```

these two molecules have different chirality (expressed as an atom information), however, `MolToSmiles(mol, isomericSmiles=True)` shows same results.
I also checked openbabel's output, it returns different chirality.

My environment is:
- RDKit Version: 2017.09.2
- Python Version: 2.7.13 (Anaconda custom (64-bit))
- Platform: Linux (SUSE Linux Enterprise Server 12 SP2)

**Comment by greglandrum** [comment]
It would be relatively easy to support this flag in cases where the coordinates are all zero, but it's not currently done.

**Comment by keisuke-yanagisawa** [comment]
Thank you for your comment. I understand RDKit does not parse it currently. 

I faced the problem when I parse a compound library provided by a compound vendor, thus I hope RDKit will support it.
