### ISSUE TITLE
rdkit doesn't handle Germanium?

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#1976]
Hello,

While reading a smiles string with Ge:
```
UFFTYPER: Unrecognized atom type: Ge2 (0)
```
I read UFF is a full periodic table force field, so I was surprised.
I checked, and there is no atomic number 32 in there:
rdkit/Code/GraphMol/ForceFieldHelpers/UFF/AtomTyper.cpp

Is it the only place where it should be handled?

Thanks a lot,
Francois

**Comment by greglandrum** [comment]
Hi Francois,

The UFF only has parameters for `Ge3`, which corresponds to an sp3 hybridized Ge. But when you have that everything seems to work fine:
``
In [4]: m = Chem.AddHs(Chem.MolFromSmiles('C[Ge](C)C'))

In [5]: AllChem.EmbedMolecule(m)
Out[5]: 0

In [6]: AllChem.UFFOptimizeMolecule(m)
Out[6]: 0
```

**Comment by UnixJunkie** [comment]
OK, the molecule has an sp2 Ge, sorry.
