### ISSUE TITLE
Error of one SMARTS matching another SMARTS

### ISSUE THREAD

**Issue by simonmb** [rdkit/rdkit#1978]
**Description:**

- RDKit Version: 2017.09.3
- Platform: Windows

When matching one SMARTS with another SMARTS that includes zero hydrogens, a match is returned for a SMART including hydrogens.

Following code:
```
p = Chem.MolFromSmarts('[CH3][OH]')
p.UpdatePropertyCache()
p2 = Chem.MolFromSmarts('[CH3][O;H0]')
p2.UpdatePropertyCache()

p.HasSubstructMatch(p2)  returns False
p2.HasSubstructMatch(p) returns True
```

In my opinion the second result should also be False.

**Comment by greglandrum** [comment]
Doing SMARTS-SMARTS matches is a delicate thing and, as you are discovering, the RDKit doesn't do a very good job of it.

I'm pretty sure that I agree that this is not the correct behavior, but I'm going to have to think about it a bit longer. :-)

**Comment by simonmb** [comment]
I'm trying to find out whether one SMARTS is a subset of another SMARTS.
Let's say for example:
'**[CH2][NH]**' is a subset of '**[CH2][NH2]**'

**Comment by greglandrum** [comment]
@simonmb: I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by simonmb** [comment]
What I did is a workaround to what I would call a bug. My workaround also only works for simple SMARTS.

**Comment by simonmb** [comment]
```
p = Chem.MolFromSmarts('[c][CH1;X4;A]')
p.UpdatePropertyCache()
p2 = Chem.MolFromSmarts('[CH1;X4;A]')
p2.UpdatePropertyCache()

p.HasSubstructMatch(p2) returns False
p2.HasSubstructMatch(p) returns False
```
Found this one. Maybe you can point me in the correct direction why this is happening so I can write a workaround.

**Comment by greglandrum** [comment]
I'm not quite sure what's going on here, but I think you should be getting a match.
I will try to figure out what's going on.

**Comment by simonmb** [comment]
I did some digging, the number of implicit and explicit Hs is set in a way that the match is false.
This explains the behaviour of the first example '[CH3][O;H0]' and of the second example '[CH1;X4;A]'  as well.

- In the first example the number of implicit Hs it is set to 1

- In the second example it is set to 4, while the number of explicit Hs is set to 0

The number of explicit Hs should be set correctly and the number of implicit Hs needs to be handled appropiately in a way the substructure matches give the correct result.
