### ISSUE TITLE
Error in sanitization of SMARTS with nitrogen

### ISSUE THREAD

**Issue by simonmb** [rdkit/rdkit#1979]
**Description:**

- RDKit Version: 2017.09.3
- Platform: Windows

```
p = Chem.MolFromSmarts('[CH3]N(=O)=O')
p.UpdatePropertyCache()
```

Gives an ERROR:
ValueError: Sanitization error: Explicit valence for atom # 1 N, 5, is greater than permitted

I think there was already a similar problem for SMILES.

**Comment by greglandrum** [comment]
The N is 5 coordinate and neutral, that is, according to the RDKit, not a valid valence state.
Nitro groups in molecules constructed from SMILES are cleaned up as part of the standard sanitization process, which is described here: http://www.rdkit.org/docs/RDKit_Book.html#molecular-sanitization

Doing this kind of operation on molecules constructed from SMARTS is somewhat unusual (you mention something similar in #1978), and there may be another way to solve your problem. What exactly are you trying to do?

**Comment by simonmb** [comment]
I want to match the CH2NO2 group from e.g. 1-nitropropane. I just realized, that the SMARTS should probably by be '[CH3]N(=O)=O'. Nevertheless, rdkit returns an error for the updated SMARTS

**Comment by simonmb** [comment]
if I execute the following:
```
q = Chem.MolFromSmarts('[CH2][N+](=O)[O-]')
q.UpdatePropertyCache()
```

I get following error:
```
ValueError: Sanitization error: Explicit valence for atom # 1 N, 4, is greater than permitted
```
Is this supposed to be that way, or am I missing something?

**Comment by greglandrum** [comment]
You want to do: ‘q.UpdatePropertyCache(strict=False)’
