### ISSUE TITLE
How to obtain Cartesian (x,y,z) coordinates of each atom of a molecule (after Compute2dCoords() or EmbedMolecule())?

### ISSUE THREAD

**Issue by Kael-the-Mad** [rdkit/rdkit#1982]
**Description:**
When I tried to get the Cartesian coordinates in x,y,z form of an atom within a molecule, I searched the online python document (http://rdkit.org/docs/api/module-tree.html) especially the Atom Class, but could not find a Class method that can obtain the Cartesian coords of the atom. 
But I think the Cartesian coordinates (x,y,z) tuple or list should be an important attribute of an atoms.
Does RDKit have a method to access these information?

- RDKit Version: '2018.03.2'
- Platform: Windows 8.1

I have an idea that by parsing the string returned by Chem.MolToMolBlock, we can actuall obtain the (x,y,z) coords. However, does RDKit has a built-in method to handle the issue?

```
Your code sample here
```

**Comment by bp-kelley** [comment]
>>> from rdkit.Chem import AllChem

>>> AllChem.Compute2DCoords(m)

0

(<rdkit.Chem.rdchem.Conformer object at 0x110345c80>,)

>>> for c in m.GetConformers():

...      print c.GetPositions()

array([[  1.50000000e+00,   0.00000000e+00,   0.00000000e+00],

       [  7.50000000e-01,  -1.29903811e+00,   0.00000000e+00],

       [ -7.50000000e-01,  -1.29903811e+00,   0.00000000e+00],

       [ -1.50000000e+00,   1.83697020e-16,   0.00000000e+00],

       [ -7.50000000e-01,   1.29903811e+00,   0.00000000e+00],

       [  7.50000000e-01,   1.29903811e+00,   0.00000000e+00]])

**Comment by Kael-the-Mad** [comment]
I see how it works. Thank you very much! @bp-kelley

**Comment by MKorablyov** [comment]
This does not solve how to get coordinates that were in MolBlock

**Comment by 0ut0fcontrol** [comment]
you can try to build mol from mol block, and then get positions.
mol = Chem.MolFromMolBlock(MolBlock)

**Comment by MKorablyov** [comment]
Thanks, this solved the problem: conf = reference.GetConformer(confId) Maybe, I am not clear about the reason why an atom object does not reference coordinates of this atom what seems natural. Thanks @0ut0fcontrol

**Comment by greglandrum** [comment]
The library is designed the way it is so that molecules can have multiple conformers.

**Comment by aced125** [comment]
How can I get 3D coords of a conformer? Minimised by the UFFOptimize method?

**Comment by pcko1** [comment]
would be excellent to have a similar snippet of code for 3D coordinates!

**Comment by bp-kelley** [comment]
This is a good start for conformation generation and minimization:

https://www.rdkit.org/docs/GettingStartedInPython.html#working-with-3d-molecules

**Comment by dianagarnicaacevedo** [comment]
> would be excellent to have a similar snippet of code for 3D coordinates!

This might help explaining why: https://greglandrum.github.io/rdkit-blog/posts/2023-02-04-working-with-conformers.html
