### ISSUE TITLE
RingInfo of SMARTS is not initialized

### ISSUE THREAD

**Issue by simonmb** [rdkit/rdkit#1984]
**Description:**

- RDKit Version: 2017.09.3
- Platform: Windows

RingInfo seems not initialized in SMARTS

```
q2 = Chem.MolFromSmarts('n1[c][cH][cH][cH][cH]1')
q2.UpdatePropertyCache()
q2.GetRingInfo().NumRings()

```
Throws following error:

RuntimeError: Pre-condition Violation
	RingInfo not initialized
	Violation occurred on line 76 in file Code\GraphMol\RingInfo.cpp
	Failed Expression: df_init
	RDKIT: 2017.09.3
	BOOST: 1_66

**Comment by greglandrum** [comment]
Since SMARTS are not sanitized by default, you need to do ring perception:
```
n [3]: q2 = Chem.MolFromSmarts('n1[c][cH][cH][cH][cH]1')

In [4]: q2.UpdatePropertyCache()

In [5]: Chem.GetSymmSSSR(q2)
Out[5]: <rdkit.rdBase._vectSt6vectorIiSaIiEE at 0x7f237ac03db0>

In [6]: q2.GetRingInfo().NumRings()
```

**Comment by simonmb** [comment]
OK, thanks. I guess sanitizing SMARTS in the same way that SMILES are sanitized doesn't make sense. But would it be possible to include at least some of the steps to compute some of the properties?

**Comment by greglandrum** [comment]
It’s possible to do just about anything, but we’ve chosen to do a minimum amount of work (to keep things efficient) since that calculation is not necessary the vast majority of the time.
