### ISSUE TITLE
installing rdkit on anaconda 

### ISSUE THREAD

**Issue by aebk2015** [rdkit/rdkit#1996]
I am confused on how to install rdkit and deepchem. Here I am listing the problems I am having and I appreciate your help.

rdkit: After several trials, I finally figured out rdkit is only available on python2. Following the recommendation on their site, I installed rdkit:

```
$ conda create -n rdkit -c rmg rdkit
$ source activate rdkit 
```

I made sure the rdkit is successfully installed as I got the right version when invoking from the terminal window:

```
>>> rdkit.__version__
'2016.03.4'
```
However, when I open the jupyet notebook, and import the rdkit, I got the error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-6b72bd8913ab> in <module>()
----> 1 import rdkit

ImportError: No module named rdkit
```

**Comment by bp-kelley** [comment]
You are probably using the wrong kernel inside Jupyter, there should be a drop down menu at the top ( named Kernel I believe ) where you can select the environment you just made “rmg”.

**Comment by aebk2015** [comment]
Thanks! under kernel, I have python2 and python37 (where I have python 3 installation) and i tried both but still it returns the same error (No module name rdkit). I don't see 'rmg'  under kernel drop down menu nor do I see in the env folder (weird)

**Comment by greglandrum** [comment]
Try installing jupyter in the same environment where you've installed the rdkit.

**Comment by aebk2015** [comment]
Thanks, it worked

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
