### ISSUE TITLE
Converting mol ToBinary and back leads to negative mapping numbers for very large molecules

### ISSUE THREAD

**Issue by kovasap** [rdkit/rdkit#1999]
I noticed on some very large compounds, if I map the atoms in the compound (canonically in the example below), and then convert it to binary and back, I don't recover all the same mapping numbers.  In fact, I get some negative mapping numbers back - which were definitely not in the original molecule!  

Here is my example case.  I have seen this on ~10-20 other molecules if other examples are needed.  

```
import rdkit
from rdkit import Chem

print(rdkit.__version__)

smi = 'C/C=C(/C)CC/C=C(/C)CC/C=C(/C)CC/C=C(/C)CC/C=C(/C)CC/C=C(/C)CC/C=C(/C)CC/C=C(/C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)COP(=O)(O)OP(=O)(O)OC1OC(CO)C(OC2OC(CO)C(O)C(OC3OC(CO)C(O)C(O)C3OC3OC(C(=O)O)C(OC4OC(COC5OC(CO)C(O)C(O)C5O)C(O)C(O)C4O)C(O)C3O)C2O)C(O)C1O'
mol = Chem.MolFromSmiles(smi)
# remove all atom numbers beforehand, as the CanonicalRankAtoms function
# takes into account existing mapping numbers while doing it's mapping (!)
# (I assume this is intentional)
for atom in mol.GetAtoms():
    if atom.HasProp('molAtomMapNumber'):
        atom.ClearProp('molAtomMapNumber')
ranks = list(Chem.CanonicalRankAtoms(mol, breakTies=True))
for j, i in enumerate(ranks):
    i += 1
    mol.GetAtomWithIdx(j).SetIntProp('molAtomMapNumber', i)
b = mol.ToBinary()
mol = Chem.Mol(b)
for a in mol.GetAtoms():
    mn = a.GetIntProp('molAtomMapNumber')
    if mn < 0:
        print(a.GetSymbol(), mn)

-------------------OUTPUT-------------------------

2018.03.2
P -126
P -125
C -127
C -128
```

**Comment by greglandrum** [comment]
Atom map numbers are currently stored in the binaries using a signed char, so anything over 127 ends up being stored incorrectly:
```
n [1]: from rdkit import Chem

In [2]: m = Chem.MolFromSmiles('CC')

In [3]: m.GetAtomWithIdx(0).SetAtomMapNum(127)

In [4]: m.GetAtomWithIdx(1).SetAtomMapNum(128)

In [5]: nm = Chem.Mol(m.ToBinary())

In [6]: nm.GetAtomWithIdx(0).GetAtomMapNum()
Out[6]: 127

In [7]: nm.GetAtomWithIdx(1).GetAtomMapNum()
Out[7]: -128
```
We can easily change this to use an unsigned 32bit value, which allows much larger atom map numbers. This will make pickle files that use atom maps larger (keep the files small is the reason the 8bit number was used in the first place) but that probably isn't that much of a problem.
@bp-kelley : do you see any problem with me switching the serialized type of the `molAtomMapNum` to `uint32_t`?

**Comment by bp-kelley** [comment]
How about a different compromise.  We could store as a “signed char” but if the sign bit is set, ignore it and read the next uint32, this would keep the same size except for unusual cases and be backwards compatible-ish

**Comment by greglandrum** [comment]
to be clear on backward compatibility:

**Comment by greglandrum** [comment]
To be clear on cross-version compatibility:
The reader will continue to successfully parse files from older versions.
We would just bump the version number of the pickle format (which we would have to do anyway with your proposal), which will cause older versions of the RDKit to not be able to read the pickle.
