### ISSUE TITLE
Unrecognised atom type in UFF for S atom

### ISSUE THREAD

**Issue by malteseunderdog** [rdkit/rdkit#200]
I have two molecules `CS(C)(C)=O` and `O=S1(S)C[NH2+]C2CC3=C(C=C21)OC=CC3`.  I think there is nothing out of the ordinary with these molecules, in fact I can read them without a problem in the RDKit.  However I get the following warning:

``` python
>>> mol = Chem.MolFromSmiles('CS(C)(C)=O')
>>> molH = Chem.AddHs(mol)
>>> AllChem.EmbedMolecule(molH)
[17:40:13] UFFTYPER: Unrecognized atom type: S_5+6 (1)
0
```

Which leads to my first question -  should this throw a UFF warning/error considering I might not use UFF and decide to minimize using MMFF ?

Of course when I try to UFF minimize, this fails (since the atom type is not supported):

``` python
>>> AllChem.UFFOptimizeMolecule(molH)
[17:46:02] UFFTYPER: Unrecognized atom type: S_5+6 (1)
[17:46:02] 

****
Pre-condition Violation
bad params pointer
Violation occurred on line 52 in file /opt/RDKit_2013_09_1/Code/ForceField/UFF/AngleBend.cpp
Failed Expression: at2Params
****

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Pre-condition Violation
```

I guess my second question is: is this a general deficiency with the UFF forcefield? or is this defined in UFF but not implemented in RDKit?  Is a try catch the best way to test for this condition coming up (and perhaps in the catch do an MMFF minimization if this happens before giving up)?

Thanks
JP

**Comment by JLVarjo** [comment]
Hi, some extra input on this issue. It seems that if the atom type parameters are missing in UFF, the geometry optimization may end up to rather exploded results, still returning 0 (GO converged). See the following snippet, in which the test molecule has a six-valent sulfur (-SF5 group), which is also unparametrized in UFF.

```
from rdkit import Chem
from rdkit.Chem import AllChem

mol=Chem.MolFromSmiles("COC(=O)[C@@H](O)C(C)(C)NC(=O)Nc1ccc(S(F)(F)(F)(F)F)cc1")
mol=Chem.AddHs(mol)
print ("Embedding return value (S=SP3D2): ", AllChem.EmbedMolecule(mol))
print (Chem.MolToMolBlock(mol), file=open("SF5_embedded_sp3d2.mol",'w+'))
print ("UFF return value (S=SP3D2): ", AllChem.UFFOptimizeMolecule(mol, maxIters=400))
print (Chem.MolToMolBlock(mol), file=open("SF5_opt_sp3d2.mol",'w+'))

mol.GetAtomWithIdx(17).SetHybridization(Chem.rdchem.HybridizationType.SP3)
print ("Embedding return value (S=SP3): ",AllChem.EmbedMolecule(mol))
print (Chem.MolToMolBlock(mol), file=open("SF5_embedded_sp3.mol",'w+'))
print ("UFF return value (S=SP3): ", AllChem.UFFOptimizeMolecule(mol, maxIters=400))
print (Chem.MolToMolBlock(mol), file=open("SF5_opt_sp3.mol",'w+'))
```

This looks like a bug to me: even though the missing atom parameter warning is given, the geometry (in SF5_opt_sp3d2.mol) shouldn't end up that bad? The GO apparently fails to pick up any default parameterization in this case. If the sulfur hybridization is manually changed to SP3, the result looks better (of course, the sulfur coordination is still wrong due to wrong hybridization).

In OpenBabel/Avogadro implementation of UFF they seem to have done some patches to fix the parameter deficiencies. Don't know if this helps, but anyway, here's one mailing list thread about it:

https://sourceforge.net/p/openbabel/mailman/message/24792558/

**Comment by EtienneReboul** [comment]
Hi, 
I encountered the same problem for some molecules i generated.  there is actually a relatively thread-safe way to get the warning as string it is based on rdkit blog :  http://rdkit.blogspot.com/2016/03/capturing-error-information.html
Here is my implementation , to solve the issue : 

`import os 
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
import multiprocessing as mp
import subprocess
from io import StringIO
import sys


def write_mol(path,mol):
    with open(path,'w+') as file:
        file.write(Chem.MolToMolBlock(mol))
        file.close()

def smiles2molfile(pair):
    smiles= pair[0]
    path=pair[1]
    failure_status = False
    mol= Chem.MolFromSmiles(smiles)
    sio = sys.stderr = StringIO()
    AllChem.EmbedMolecule(mol)
    error_log =sio.getvalue()
    if error_log:
        error_list=error_log.split()
        index=int(error_list[-1].replace("(","").replace(")",""))
        atom_type= error_list[-2]
        if atom_type == "S_5+6":
            mol.GetAtomWithIdx(index).SetHybridization(Chem.rdchem.HybridizationType.SP3)
            AllChem.EmbedMolecule(mol)
        else:
            failure_status= True

    if  not failure_status :
        write_mol(path,mol)
    else: 
        pass
 
    return failure_status
    

def molfile2pdbqtfile(path,pH=7.4):
    new_path= path.replace(".mol",".pdbqt")
    subprocess.run(f"obabel {path} -O {new_path} -p {pH} --partialcharge gasteiger".split())
    os.remove(path)


df = pd.read_csv("some_csvfile.csv")
output_dir= "structures_3D/"
os.makedirs(output_dir,exist_ok=True)
pair_list= [[smiles, os.path.join(output_dir,f"ligand_{i}.mol")] for i,smiles in enumerate(df["smiles"][:100])]

with mp.Pool(mp.cpu_count()) as pool:
    failure_status_list=pool.map(smiles2molfile,pair_list)
    pool.close()
    pool.join()
_,path_list=zip(*pair_list)
path_list= [ path for i,path in enumerate(path_list) if not failure_status_list[i] ]
for path in path_list:
    molfile2pdbqtfile(path)

`
Hope , it will help someone who stumbles on the same issue

**Comment by d-b-w** [comment]
Thanks for posting those ideas!

**Comment by mainguyenanhvu** [comment]
Hi, I want to try catch this sort of error in python instead of exiting my code. How could I do that?
