### ISSUE TITLE
Error while parsing empty atom list in Mol files.

### ISSUE THREAD

**Issue by drkeoni** [rdkit/rdkit#2000]
- RDKit Version: 2018.03.2
- Platform: Linux, python2.7 or python3.5 (bug appears in both)

Iterating over ForwardSDMolSupplier is causing a seg fault for the SDF file attached here.

```
import rdkit.Chem as Chem
infile = open('one_mol.sdf','rb')
reader = Chem.ForwardSDMolSupplier(infile)
for mol in reader:
    print('here')
```
SDF file is [one_mol.sdf.gz](https://github.com/rdkit/rdkit/files/2276271/one_mol.sdf.gz)

I removed various sections in this file and changed the weird looking atoms to carbons (this is a Markush structure).  In that process I was able to identify the offending section to be the lines
```
M  ALS   5  0 F
M  RGP  6  21   6  23   5  30   1  31   2  32   3  33   4
M  STY  5   1 SRU   2 SRU   3 SRU   4 SRU   5 SRU
M  SCN  1   1 HT
```

**Comment by greglandrum** [comment]
Here's a shorter demonstration:
```
In [2]:  Chem.MolFromMolFile('./one_mol.sdf')
Segmentation fault (core dumped)
```
This is actually the result of an overly zealous bit of inconsistency checking inside the Mol file parsing code. If you provide an atom list that has zero atoms, the current parser interprets that as an error from which it can't recover and errors out. Here's the line in question:
https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/FileParsers/MolFileParser.cpp#L860

The behavior should be to just ignore the line.

Thanks for the detailed report!

**Comment by drkeoni** [comment]
Awesome, thanks for the quick fix!
