### ISSUE TITLE
CanonicalRankAtoms gives different ranking for same molecule generated from different SMILES

### ISSUE THREAD

**Issue by ChayaSt** [rdkit/rdkit#2006]
**Description:**

When I generate molecules from different SMILES that represent the same molecule and then use `CanonicalRankAtoms`, the ranking on the atoms are (seemingly) different. Below is some example code:

- RDKit Version: 2018.03.3
- Platform: MacOS 10.13.6

```
import rdkit
from rdkit import Chem

print(rdkit.__version__)

smiles = 'CC(c1c(ccc(c1Cl)F)Cl)OC'
rd_mol = Chem.MolFromSmiles(smiles)
can_smiles = Chem.MolToSmiles(rd_mol, canonical=True)
print(can_smiles)

# new molecule from canonical smiles
new_mol = Chem.MolFromSmiles(can_smiles)
print(Chem.MolToSmiles(new_mol, canonical=True))

# Get ranking for atoms in both molecules
ranked_1 = list(Chem.CanonicalRankAtoms(rd_mol, breakTies=True))
for i, j in enumerate(ranked_1):
    rd_mol.GetAtomWithIdx(j).SetIntProp('molAtomMapNumber', i + 1)
print(Chem.MolToSmiles(rd_mol, canonical=True))

ranked_2 = list(Chem.CanonicalRankAtoms(new_mol, breakTies=True))
for i, j in enumerate(ranked_2):
    new_mol.GetAtomWithIdx(j).SetIntProp('molAtomMapNumber', i + 1)
print(Chem.MolToSmiles(new_mol, canonical=True))
```

Below is the output:

```
2018.03.3
COC(C)c1c(Cl)ccc(F)c1Cl
COC(C)c1c(Cl)ccc(F)c1Cl
[CH:1]([O:3][CH3:2])([c:10]1[c:11]([Cl:8])[cH:9][cH:6][c:5]([F:4])[c:12]1[Cl:7])[CH3:13]
[CH3:1][O:4][CH:11]([CH3:7])[c:13]1[c:5]([Cl:3])[c:6]([F:12])[cH:10][cH:2][c:9]1[Cl:8]
```

**Comment by greglandrum** [comment]
Hi,
`Chem.CanonicalRankAtoms()` returns the ranks of the atoms, so you have the logic of the assignment reversed here. Try:
```
# Get ranking for atoms in both molecules
ranked_1 = list(Chem.CanonicalRankAtoms(rd_mol, breakTies=True))
for i, j in enumerate(ranked_1):
    rd_mol.GetAtomWithIdx(i).SetIntProp('molAtomMapNumber', j + 1)
print(Chem.MolToSmiles(rd_mol, canonical=True))

ranked_2 = list(Chem.CanonicalRankAtoms(new_mol, breakTies=True))
for i, j in enumerate(ranked_2):
    new_mol.GetAtomWithIdx(i).SetIntProp('molAtomMapNumber', j + 1)
print(Chem.MolToSmiles(new_mol, canonical=True))
```
And you will get the expected result:
```
[CH3:1][O:8][CH:13]([CH3:2])[c:12]1[c:10]([Cl:4])[cH:7][cH:6][c:9]([F:3])[c:11]1[Cl:5]
[CH3:1][O:8][CH:13]([CH3:2])[c:12]1[c:10]([Cl:4])[cH:7][cH:6][c:9]([F:3])[c:11]1[Cl:5]
```

**Comment by ChayaSt** [comment]
Thanks! 
I thought the order was reversed (the order of the list was the ranking of the atom indices)

**Comment by MKorablyov** [comment]
Is this an intended behavior of  "CanonicalRankAtoms"?

import rdkit
from rdkit import Chem

print(rdkit.__version__)

smiles = 'CC(c1c(ccc(c1Cl)F)Cl)OC'
rd_mol = Chem.MolFromSmiles(smiles)
can_smiles = Chem.MolToSmiles(rd_mol, canonical=True)
print(can_smiles)

# new molecule from canonical smiles
new_mol = Chem.MolFromSmiles(can_smiles)
print(Chem.MolToSmiles(new_mol, canonical=True))

# canonical reordering
rd_mol_canon = Chem.RenumberAtoms(rd_mol,Chem.CanonicalRankAtoms(rd_mol))
new_mol_canon = Chem.RenumberAtoms(new_mol,Chem.CanonicalRankAtoms(new_mol))

# smiles reordering
rd_order = rd_mol.GetPropsAsDict(includePrivate=True, includeComputed=True)['_smilesAtomOutputOrder']
new_order = new_mol.GetPropsAsDict(includePrivate=True, includeComputed=True)['_smilesAtomOutputOrder']
rd_mol_smi = Chem.RenumberAtoms(rd_mol,rd_order)
new_mol_smi = Chem.RenumberAtoms(new_mol,new_order)

print([atom.GetSymbol() for atom in rd_mol_canon.GetAtoms()])
print([atom.GetSymbol() for atom in new_mol_canon.GetAtoms()])

print([atom.GetSymbol() for atom in rd_mol_smi.GetAtoms()])
print([atom.GetSymbol() for atom in new_mol_smi.GetAtoms()])

**Comment by ndattani** [comment]
@ChayaSt, @greglandrum, @MKorablyov, @kovasap Does this thread address the problem in [this question](https://mattermodeling.stackexchange.com/q/12279/5) at MMSE?

**Comment by pradipchm** [comment]
I would love to get any suggestion or reason, following the last reply,  why the canonical ranking provides different ranking for two conformers of a molecule just differ by a rotational bond. Also here is post [https://github.com/rdkit/rdkit/discussions/7062](url)

**Comment by bp-kelley** [comment]
You are misunderstanding how CanonicalRank atoms works, it returns the canonical rank FOR the atoms.  To use these in OrderAtoms you need to do the following:

```
ranks = [(rank, atom_idx) for atom_idx, rank in enumerate(Chem.CanonicalRankAtoms(rd_mol))]
ranks.sort()
new_ranks = [(rank, atom_idx) for atom_idx, rank in enumerate(Chem.CanonicalRankAtoms(new_mol))]
new_ranks.sort()

rd_mol_canon = Chem.RenumberAtoms(rd_mol,[atom_idx for _,atom_idx in ranks])
new_mol_canon = Chem.RenumberAtoms(new_mol,[atom_idx for _,atom_idx in new_ranks])
```

Then your code produces
```
COC(C)c1c(Cl)ccc(F)c1Cl
COC(C)c1c(Cl)ccc(F)c1Cl
['C', 'C', 'F', 'Cl', 'Cl', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'C']
['C', 'C', 'F', 'Cl', 'Cl', 'C', 'C', 'O', 'C', 'C', 'C', 'C', 'C']
['C', 'O', 'C', 'C', 'C', 'C', 'Cl', 'C', 'C', 'C', 'F', 'C', 'Cl']
['C', 'O', 'C', 'C', 'C', 'C', 'Cl', 'C', 'C', 'C', 'F', 'C', 'Cl']
```

Also, you are using a quite old version of the RDKit (2018) I highly suggest upgrading.

**Comment by pradipchm** [comment]
Thanks. I am usimg '2022.09.4' version. I did the same with `rdmolfiles.CanonicalRankAtoms(mol_to_transform, includeChirality=False )`. initially I was using `ncludeChirality=True` as default. Now It give similar ranking to your code. Still there is mismatch in ranking for Hs for few structures, but other atoms are fine.
