### ISSUE TITLE
ERROR SMARTS matching SMILES

### ISSUE THREAD

**Issue by simonmb** [rdkit/rdkit#2011]
**Description:**

- RDKit Version: 2017.09.3
- Platform: Windows

When matching one SMARTS with a specific SMILES somehow one match is missing.

Following code:
```
smiles = 'C1=CC=C2C(=C1)C3=CC=CC4=C3C5=C(C=C4)C(C(C=C25)O)O'
mol = Chem.MolFromSmiles(smiles)

q = Chem.MolFromSmarts('[cH]')

mol.GetSubstructMatches(q)

returns:
((0,), (1,), (2,), (5,), (7,), (8,), (9,), (14,), (15,))
```
It returns 9 hits, although it should find 10. Atom with index 18 is missing. If I draw the image the aromaticity looks correct:

![clipboard01](https://user-images.githubusercontent.com/6115499/44574612-2ef60280-a78a-11e8-8c58-f7c4c7cca0ca.png)

**Comment by simonmb** [comment]
Found another one:

``
mol = Chem.MolFromSmiles('CN1C2=CC=CC=C2C=C3C1=CC4=CC=CC=C43')
mol.HasSubstructMatch(Chem.MolFromSmarts('[CH3]N'))
``

returns False (should be True)


Again image suggests it should work:
![test](https://user-images.githubusercontent.com/6115499/44583653-712d3d00-a7a6-11e8-864e-c21998c66942.png)

**Comment by simonmb** [comment]
Yes, in the 2nd example it is due to aromaticity. Thank you for your help. But why doesn't **this** work?

`
Chem.MolFromSmiles('C=C1C=CC=CC1=C').HasSubstructMatch(Chem.MolFromSmarts('[#6&H]=[#6&H]'))
`

![test](https://user-images.githubusercontent.com/6115499/44585013-22ce6d00-a7ab-11e8-9dea-be9cc4e4b805.png)

**Comment by simonmb** [comment]
I actually ment to match this:

![unbenannt](https://user-images.githubusercontent.com/6115499/44590242-fae70580-a7ba-11e8-99fb-3bc6320337c8.png)

**Comment by bp-kelley** [comment]
This is subtler, the ring is aromatic.  RDKit doesn't store both the
aromatic and double bond types, they are independent.  The matching
patterns are:

pat = Chem.MolFromSmarts("[#6&H1]:[#6&H1]")

or

pat = Chem.MolFromSmarts("[#6&H1]~[#6&H1]")

~ is any bond, : is aromatic.

Or you could use,

pat = Chem.MolFromSmarts("[#6&H1]-,=,:[#6&H1]")

depending.

Cheers,
 Brian

**Comment by bp-kelley** [comment]
I will say this is one of those corner cases where if you draw the ring as
aromatic, it sure looks like there are five bonds to a carbon which makes
some of my medicinal chemistry friends look a bit queasy.


Cheers,
 Brian

**Comment by simonmb** [comment]
Thank you for clarifying this, I was not aware of this fact:
> RDKit doesn't store both the aromatic and double bond types, they are independent.

The problem with the first example imho is one of aromaticity.
I found another smiles:
`C1=CC=C2C(=C1)C=C3C4=CC=CC4=CC5=C3C2=CC=C5`

for which the SMARTS '[cH]' gives less matches than I would expect. It returns 9 instead of the expected 12. Or am I commiting some mistake?

**Comment by simonmb** [comment]
I found a workaround. If I match:
`[$([#6&H1](=[#6])[#6])]`

I get the missing matches. But isn't this an error? Somehow some atoms are not beeing marked as aromatic.

**Comment by simonmb** [comment]
I found another error for a SMARTS equal to the SMILES:
```
mol = Chem.MolFromSmiles('C1=COC(=C1)C=O)
patt = Chem.MolFromSmarts('C1=COC(=C1)C=O')
mol.GetSubstructMatches(patt)
returns empty
```

![clipboard01](https://user-images.githubusercontent.com/6115499/44649795-2f3e0a00-a9e5-11e8-8b12-b406cd0b018a.png)

**Comment by simonmb** [comment]
Thanks Brian, I see what the problem is. Thanks for the link.

**How does rdkit decide which atoms to aromatize?** 

Shouldn't all of the atoms in the following SMILES be considered aromatic?
`C1=CC=C2C(=C1)C=C3C4=CC=CC4=CC5=C3C2=CC=C5`
I dont get all the matches for '[cH1]', as I described above. The same applies to the furfural (which you referred to in your las comment).

**Comment by bp-kelley** [comment]
There is one five membered ring that doesn't look like it to me (hopefully
the image transfers)

[image: image.png]

>>> from rdkit import Chem

>>> m = Chem.MolFromSmiles("C1=CC=C2C(=C1)C=C3C4=CC=CC4=CC5=C3C2=CC=C5")

>>> Chem.MolToSmiles(m)

'C1=Cc2cc3cccc4c5ccccc5cc(c2=C1)c34'

**Comment by simonmb** [comment]
Unfortunately, the image did not transfer. 
I was reading about the aromaticity [here](https://www.rdkit.org/docs/RDKit_Book.html).
Looking at the examples shown there I would think all the atoms in the molecule should be aromatic. But I am no expert...
What do you say?

**Comment by bp-kelley** [comment]
As I said, RDKit doesn't consider the five membered ring to be aromatic.
I'm attaching a PNG, hopefully you can see this.

[image: aromaticity.png]

**Comment by simonmb** [comment]
Unfortunately, again the image did not transfer.
I'm sorry if I have been unclear. I know that the five membered ring is not considered as aromatic. 
**What I want to know is if RDKit is right by not considering it to be aromatic.**

Again I am no expert in chemistry but I'd like to know if RDKit is making a mistake by not considering it aromatic. Maybe I'm just wrong. But I think it should be considered aromatic.

The example above: C1=CC=C2C(=C1)C=C3C4=CC=CC4=CC5=C3C2=CC=C5
![test2](https://user-images.githubusercontent.com/6115499/44837457-f8146680-ac39-11e8-9621-0871832c1c79.png)

A second example: C1=CC2=C3C(=CC=C4C3=C1C=C4)C=C2 (**where the 5 membered ring is aromatic**)

![test](https://user-images.githubusercontent.com/6115499/44837419-ddda8880-ac39-11e8-88b0-d92b6f361afb.png)

**Comment by jasondbiggs** [comment]
@bp-kelley How do the 5-membered rings in C1=CC2=C3C(=CC=C4C3=C1C=C4)C=C2 obey Hückel's rule?  RDKit::MolOps::countAtomElec says every carbon atom in the molecule has 1 electron to donate to aromaticity, and I can't see a fused ring containing those atoms with 4n+2 atoms.

**Comment by bp-kelley** [comment]
It's not 4n+2 atoms, it's 4n+2 pi-electrons. n=0 is valid for n here.

Cheers,
 Brian

**Comment by jasondbiggs** [comment]
@bp-kelley I understand it's about pi-electrons, but isn't that the same thing in this case?  There are 14 pi electrons and 14 carbon atoms, and `countAtomElec` returns 1 for each carbon atom.  

As to `n=0` - where is a ring with only 2 pi electrons?

**Comment by bp-kelley** [comment]
Apologies, n=0 was a red herring, I was answering a different question.  In this case I believe that the 4n+2 comes from the outer fused ring.  If you remove one of the five members rings, the other becomes non aromatic.

I can double check whether my intuition matches the source code tonight.

----
Brian Kelley

**Comment by jasondbiggs** [comment]
@bp-kelley if nothing comes to your mind I might just put a bunch of print statements in `assignAromaticity` to figure this out.  I set up a step-by-step aromaticity [here](http://www.wolframalpha.com/input/?i=what+is+the+aromatic+structure+of+4-methoxytriphenylamine) that uses a simple Huckel model (but doesn't use the RDKit yet).  

But when I try [with this compound](http://www.wolframalpha.com/input/?t=crmtb01&f=ob&i=SMILES+C1%3DCC2%3DC3C(%3DCC%3DC4C3%3DC1C%3DC4)C%3DC2+aromatic+atoms) it doesn't mark the five-membered rings aromatic, so I'm curious to see where the logic diverges.

**Comment by greglandrum** [comment]
Let me try and help some.

The "outer" atoms and bonds of the 5 membered rings in `C1=CC2=C3C(=CC=C4C3=C1C=C4)C=C2` are aromatic because the outer envelope of the ring system, indicated in blue here:
![image](https://user-images.githubusercontent.com/540511/45028632-187f5f00-b046-11e8-83b0-3abbfd35688a.png)
has 12 pi electrons (12 carbons, each contributing one pi electron).
The "inner" atoms and bonds of those 5 membered rings (the ones not colored blue in the picture above) are aromatic because they are also involved in the aromatic 6 rings.

With `C1=CC=C2C(=C1)C=C3C4=CC=CC4=CC5=C3C2=CC=C5`, there's no fused ring system that involves the 5 ring and that satisfies the 4n+2 pi electron rule for Hueckel aromaticity, so the "outer" 3 atoms and 4 bonds are not aromatic.

**Comment by jasondbiggs** [comment]
Greg,
Going off-list here because I feel there is probably something simple that
I'm missing.

If the outer ring has 12 pi electrons and is considered aromatic, then what
is the criteria for deciding if a ring is aromatic?  12 != 4n + 2 for any
integer n, is why I'm confused.

Before replying to the thread I looked at all the cycles in the graph, and
the only ones I found with 4n+2 electrons were the 2 six-membered rings and
the fused ring containing the six-membered rings:




Thanks for your help,
Jason

Jason Biggs

**Comment by greglandrum** [comment]
hmm, you're right. I thought myself into a stupid-corner on that one. That was an example of "solving" a problem a bit too quickly. Let me attempt that again a bit later. Sorry about that.
I'm likely to just delete that stupid answer above.

**Comment by greglandrum** [comment]
Ok, after removing an answer that was blatantly wrong (sorry, again, about that), here's another attempt to get this right.

The standard RDKit aromaticity model looks for aromatic "candidate ring systems". For the purposes of this explanation, a candidate ring system is either a simple ring where all the atoms are candidates for aromaticity or a set of fused rings containing at most 24 atoms where all the atoms are candidates for aromaticity.  The pi electron count is evaluated for each candidate ring system and compared to Hueckel's 4n+2 rule.

In your case `C1=CC=C2C(=C1)C=C3C4=CC=CC4=CC5=C3C2=CC=C5` has 20 atoms and is thus not aromatic as a full ring system. The various fused ring combinations involving the 5-membered ring have either 9, 13 (two different ways), or 16 electrons. none of those are 4n+2.

`C1=CC2=C3C(=CC=C4C3=C1C=C4)C=C2`, on the other hand, has 14 electrons as a full ring system. That's aromatic (the other possible combinations have 9 or 12 electrons, so none are aromatic).

**Comment by jasondbiggs** [comment]
Thanks @greglandrum, that makes sense.  This is then a kind of short-circuiting, looking at the ring systems as a whole first, to avoid checking all the constituent rings.

**Comment by greglandrum** [comment]
hmm, I'm not sure I understand that. It checks all the simple rings first, then moves on to the fused rings.

**Comment by d-b-w** [comment]
Please move further questions to the "discussion" tab.
