### ISSUE TITLE
How to ignore warning

### ISSUE THREAD

**Issue by zealseeker** [rdkit/rdkit#2017]
**Description:**

RDKit may generate warning like `mapped atoms in the reactants were not mapped in the products.`
Here is a good example in #1387 
```
>>> rxn = AllChem.ReactionFromSmarts("([C:1][C:3][C:2])>>([C:1].[C:2])")
>>> p = rxn.RunReactants([Chem.MolFromSmiles("CCC")])
[09:15:56] mapped atoms in the reactants were not mapped in the products.
  unmapped numbers are: 3 
>>> Chem.MolToSmiles(p[0][0])
'C.C'
>>> p = rxn.RunReactants([Chem.MolFromSmiles("C1CC1")])
>>> Chem.MolToSmiles(p[0][0])
'C.C'
```

1. I don't understand what the warning tells. The two of the three atoms in the reactants are matched to the product as far as I know. But it tells me "3 cannot be mapped".

2. The most important is **how to ignore it**?
I have tried `warnings.filterwarnings('ignore')` but it doesn't help.

When I tried reacting thousands of compounds in Jupyter, it generated a large size of warning and destroyed my browser...

I've no idea whether the "warning" in [Advanced Topics/Warnings](http://rdkit.org/docs/GettingStartedInPython.html#advanced-topics-warnings) is the same as the program warning. I think it'll be better if tutorial contains how to switch off the warning like `warnings.filterwarnings('ignore')`.

**Comment by gncs** [comment]
In your example, it looks like you are matching three atoms `[C:1][C:3][C:2]` in your reactant but in your product, there are only two (`[C:1][C:2]`). What is supposed to happen to `[C:3]`?

**Comment by zealseeker** [comment]
Hi @gncs ,
I got the meaning. `unmapped numbers are: 3` indicates that the atom tagged as '3' is unmapped instead of that 3 atoms are unmapped.

The `[C:3]` in the example is supposed to be removed to an unimportant product. For example oxygen is always removed to be water. So we should use `[C:1][C][C:2]>>[C:1][C:2]` instead.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by greglandrum** [comment]
One final detail: it's not currently possible to reliably disable warning messages from the RDKit. This is a problem that we're aware of but has proven "nontrivial" to fix

**Comment by sorenwacker** [comment]
Will this change in the forseeable future?

**Comment by bp-kelley** [comment]
from rdkit import rdBase
blocker = rdBase.BlockLogs()

should disable logging while the blocker variable is in scope.

you can use this in a with statement as well.
