### ISSUE TITLE
compute2DCoords not canonicalizing conformer for certain molecules

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#2027]
From the docs:

> canonOrient      canonicalize the orientation so that the long axes align with the x-axis etc.

```
m1=Chem.MolFromSmiles("C1=CC=CC2=CC3=CC=CC=C3C=C12");
AllChem.Compute2DCoords(m1,canonOrient = True);
m1
```
![image](https://user-images.githubusercontent.com/16337306/45182325-85315f80-b1e6-11e8-83de-4f141ee6b96e.png)

the conformation doesn't change based on the setting for `canonOrient`.  

As a workaround, I am calling `MolTransforms::canonicalizeConformer` on the result from `compute2DCoords`

**Comment by jasondbiggs** [comment]
On a slightly related note, is there any way to make the depiction canonical in the sense that it does not depend on the order of the atoms, or is this a fundamental limitation of `compute2DCoords`?  For example, these two SMILES represent the same molecule but give a different depiction:

```
Chem.MolFromSmiles("c1(C#Cc2ccc(OC)cc2)ccc(C(=O)N2CCC[C@@H](O)C2)c(F)c1")
Chem.MolFromSmiles("O[C@@H]1CCCN(C(=O)c2ccc(C#Cc3ccc(OC)cc3)cc2F)C1")
```

![image](https://user-images.githubusercontent.com/16337306/45185254-2f14ea00-b1ef-11e8-956b-68792b170664.png)

I can solve this by using the CoordGen method, but it's much slower than `compute2DCoords` so I'd rather not have it be the default.

**Comment by bp-kelley** [comment]
The quick solution is to canonicalize the smiles string and make a new molecule.

----
Brian Kelley

**Comment by greglandrum** [comment]
About the canonicalization of the orientation: this seems to be a bug that shows up for molecules that are composed of a single ring system.
So this:
```
m1=Chem.MolFromSmiles("C1=CC=CC2=CC3=CC=CC=C3C=C12");
m2 = Chem.Mol(m1)
rdDepictor.Compute2DCoords(m1,canonOrient = False);
rdDepictor.Compute2DCoords(m2,canonOrient = True);
Draw.MolsToGridImage((m1,m2))
```
produces:
![image](https://user-images.githubusercontent.com/540511/45199839-21527980-b26e-11e8-8c65-a4bd4846be76.png)

But adding a sidechain does what you'd expect:
```
m1=Chem.MolFromSmiles("CC1=CC=CC2=CC3=CC=CC=C3C=C12");
m2 = Chem.Mol(m1)
rdDepictor.Compute2DCoords(m1,canonOrient = False);
rdDepictor.Compute2DCoords(m2,canonOrient = True);
Draw.MolsToGridImage((m1,m2))
```
![image](https://user-images.githubusercontent.com/540511/45199850-2fa09580-b26e-11e8-8799-b1e37fdc3f60.png)

**Comment by jasondbiggs** [comment]
@greglandrum thanks for the quick fix!

@bp-kelley That is not a bad idea - I can make a canonical copy of the molecule, compute its 2D coordinates, and copy the conformer back to the original mol using the ordering in `_smilesAtomOutputOrder`.  It's inefficient, but the additional time is small compared with the rest of the rendering code.  Thank you.

**Comment by greglandrum** [comment]
It’s probably quicker to copy the molecule and then use renumberAtoms. I can paste sample code tomorrow morning.
