### ISSUE TITLE
MCS: add test for ring--non-ring matches at the atom level

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2034]
**Description:**

Here's a very simple example:
```
In [11]: ms = [Chem.MolFromSmiles(x) for x in ('C1CC1N2CC2','C1CC1N')]

In [12]: rdFMCS.FindMCS(ms,ringMatchesRingOnly=True).smartsString
Out[12]: '[#6]1-[#6]-[#6]-1-[#7]'
```
The actual parameter structure does have `ringMachesRingOnly` in the `BondMatchParamters`, so there's some logic to the behavior - it's not really a bug, but it's confusing and it would be nice to be able to get the desired result (`[#6]1-[#6]-[#6]-1`) here.

This is connected to (but not a full duplicate of) #945

**Comment by martinex** [comment]
Latest release still returns open MCS for
mol1=Chem.MolFromSmiles("c1cc2cnccc2cn1")
mol2=Chem.MolFromSmiles("c1cnc2cnccc2c1")
mcs=Chem.MolFromSmarts(rdFMCS.FindMCS([mol1,mol2],ringMatchesRingOnly=True,completeRingsOnly=True).smartsString)

**Comment by martinex** [comment]
Would it be possible to implement also complete ring systems only?

**Comment by martinex** [comment]
2018.09.1 version still returns an open MCS for
mol1=Chem.MolFromSmiles("C1=CC2=C(C=CN=C2)C=N1")
mol2=Chem.MolFromSmiles("C1=CC2=C(C=NC=C2)N=C1")
mcs=Chem.MolFromSmarts(rdFMCS.FindMCS([mol1,mol2],completeRingsOnly=True,ringMatchesRingOnly=True).smartsString)
