### ISSUE TITLE
Improve build process and docs regarding building deb and rpm packages, and cartridge

### ISSUE THREAD

**Issue by tdudgeon** [rdkit/rdkit#2038]
**Description:**

- RDKit Version: git master
- Platform: centos and/or debian

The process for building RPM and DEB packages is a bit opaque and difficult to follow.
It also seems impossible to build packages for the cartridge?

Would be good to use the hackathon at the 2018 UGM to better understand this and improve the process and its documentation.

For instance see:
https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg08004.html

**Comment by greglandrum** [comment]
cleanup of old issues
