### ISSUE TITLE
Get things building with python 3.7

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2043]
The idea is to set up conda builds for the RDKit and python 3.7. Oh, and to make sure that everything works with python 3.7 along the way. :-)

This probably means adapting the recipes in https://github.com/rdkit/conda-rdkit

**Comment by thegodone** [comment]
Any one has an idea on this ?

**Comment by bp-kelley** [comment]
Anaconda just rollled our python 3.7 by default.  The first step is to remove python 2.7 from our Travis build matrix and make it 3.7.

Then we can update the conda recipes.

I expect this to certainly happen by the new year,  probably before.

**Comment by greglandrum** [comment]
I'm likely to do something here sometime in the next week or so.

**Comment by bp-kelley** [comment]
I've made a branch replacing the travis build for python 2.7 to 3.7 in my fork, when it works, I'll make a PR.

**Comment by greglandrum** [comment]
yeah, well, this one is done
