### ISSUE TITLE
MolVS Java wrapper and MolVS Integration KNIME Node

### ISSUE THREAD

**Issue by sroughley** [rdkit/rdkit#2049]
Hackathon idea - incoporate the GSoC MolVS implementation as a KNIME node (or possibly set of KNIME nodes for the various parts?)

**Comment by greglandrum** [comment]
Great idea. But we need a java wrapper first. I hope to be able to do this "real soon now"

**Comment by sroughley** [comment]
Thanks @greglandrum  - I posted the idea before the question at the end of the talk (otherwise the suggestion might have been Java wrapper + KNIME nodes!)
