### ISSUE TITLE
Add additional filter sets to the FilterCatalog

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2050]
Pat Walters curated the ChEMBL filter sets here: https://github.com/PatWalters/rd_filters
These could be integrated into the RDKit set of filter catalogs.

- [ ] BMS
- [ ] Dundee
- [ ] Glaxo
- [ ] Inpharmatica
- [ ] LINT
- [x] MLSMR (=NIH)
- [x] PAINS
- [ ] SureChEMBL

**Comment by bp-kelley** [comment]
I'd be happy to add these.

**Comment by aced125** [comment]
Are these in yet?

**Comment by bp-kelley** [comment]
No, should be by next year.

**Comment by theabhijitdn** [comment]
What happened with this filters? are they now a part of RDKIT?

**Comment by greglandrum** [comment]
@theabhijitdn not yet.
@bp-kelley : do you want me to do this one?

**Comment by bp-kelley** [comment]
We should probably add the Novartis set as well.  I’ll add pat’s sets for now.
