### ISSUE TITLE
Check/update data for atomic masses

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2056]
**Description:**
It's been a while since the current values were checked. They should be compared to what's currently available from BODR and updated.

Suggestion from @thegodone

**Comment by thegodone** [comment]
What is BODR please ?
There is an activity report in IUPAC about recent changes :
https://iupac.org/who-we-are/committees/committee-details/?body_code=210

**Comment by greglandrum** [comment]
"Blue obelisk data repository"
https://sourceforge.net/projects/bodr/

It actually looks like it's been quite a while since this was updated, so it may no longer be the best thing to use

**Comment by jasondbiggs** [comment]
@greglandrum is there a preference for the precision these numbers have?  

I can scrape the atomic weights as well as the atomic masses from here, https://www.ciaaw.org/atomic-weights.htm, and was hoping to update the strings in atomic_data.cpp, but I'm not familiar with this method of storing data (in a string in compiled code).  

For example right now rdkit lists the atomic weight of cesium as 132.905, but when I grab the current data I could put that as 132.90545196.  Would this extra precision cause any problems?
