### ISSUE TITLE
Find externally installed maeparser and coordgenlibs dynamic libraries

### ISSUE THREAD

**Issue by smoe** [rdkit/rdkit#2104]
Hello,

I upgraded the Debian+Ubuntu package to the latest release and spotted the automated download of the Schrödinger maeparser and coordgenlibs source trees. The Linux distros want to share as much as possible between applications and hence kindly ask all libraries of general interest to be packaged independently. I have hence prepared Debian+Ubuntu packages for [maeparser](https://salsa.debian.org/science-team/schroedinger-maeparser) and [coordgenlibs](https://salsa.debian.org/science-team/schroedinger-coordgenlibs) that shall in near future make it into the distribution.

The current CMake configuration does not spot the system-wide installation of these libraries and their header files. Could that possibly be added? The coordgenlibs CMake setup for instance autodetects the maeparser, so one could borrow from there?

To get it all to build on my side I was [mostly removing CMake instructions](https://salsa.debian.org/debichem-team/rdkit/blob/master/debian/patches/NoDownloads.patch). There is certainly someone out there for whom this would be straightforward and easy to add. Otherwise, I you would accept a pull request in this matter, I would eventually address that.

Cheers,

Steffen

**Comment by greglandrum** [comment]
Makes perfect sense. I'd be happy to accept a PR or I could also do this myself, but it will probably need to wait until after I finalize the 2018.09 release (should happen soon). 
If we fix this afterwards we can always incorporate it in the first patch release.

**Comment by smoe** [comment]
@greglandrum ,
Have many thanks for your kind and swift reply. There is no immediate urgency in the sense that the Schrödinger libraries still need to find their way into the archive. I would happily see you doing that change yourself.

What just flashed me and you may want to address this while working on the above issue, the situation is similar with rapidjson which exists as a Debian package offering include files in /usr/include/rapidjson which are not detected. 

Many, many thanks

Steffen

**Comment by ricrogz** [comment]
Hey @greglandrum, I am having a look at this issue right now, I will probably have a PR ready in a few days.

**Comment by smoe** [comment]
Thank you @ricrogz, excellent news. There is some notion on an API change on https://github.com/schrodinger/maeparser/pull/27, https://github.com/schrodinger/maeparser/pull/29 and https://github.com/schrodinger/maeparser/issues/5 . (upward-)compatible APIs should have the same sonames which then affects the name of the library in Debian. And since from what I understand there is some ambition to soon have also OpenBabel depend on it, these sonames need to work. Hence, please kindly also keep @lorton in sync / get some direction on what version you should possibly use which then should be the ones that I upload to the distribution.

**Comment by ricrogz** [comment]
Thanks for the heads up, @smoe. I intended to start by just implementing the ability to find the current releases of maeparser and coordgen (the ones that are currently downloaded and built by RDKit).

I will check with @lorton, but since there isn't any release yet that includes the change in the interface and the sonames, and also RDKit does not support them, in order to keep this PR simple, I think that support for different versions should be added later on, once a release is available.

**Comment by greglandrum** [comment]
I agree with that plan.

**Comment by ricrogz** [comment]
@smoe, @greg: I just put up the PR for this issue.

I had a look at release v1.1 of CoordGen, and found out that the install target in the CMake files was missing some files, so I decided to ask @lorton and @torcolvin for a new release.

Please let me know how these changes work for you. I don't have much experience with packaging and library discovery, so any comment will be welcome!
