### ISSUE TITLE
Error #include <GraphMol/MolDrawing/DrawingToSVG.h>

### ISSUE THREAD

**Issue by HongjianLi** [rdkit/rdkit#2105]
**Description:**

C++ #include <GraphMol/MolDrawing/DrawingToSVG.h> produces the following errors:

/rdkit-2018.03.4/include/rdkit/GraphMol/MolDrawing/MolDrawing.h: In function ‘std::vector<int> RDKit::Drawing::DrawMol(const RDKit::ROMol&, int, const std::vector<int>*, bool, unsigned int, double, double, double)’:
/home/jackylee/rdkit-2018.03.4/include/rdkit/GraphMol/MolDrawing/MolDrawing.h:161:60: error: request for member ‘get’ in ‘(& mol)->RDKit::ROMol::operator[](((boost::iterators::detail::iterator_facade_base<boost::range_detail::integer_iterator<long unsigned int>, long unsigned int, boost::iterators::random_access_traversal_tag, long unsigned int, long int, false, false>*)(& bAts))->boost::iterators::detail::iterator_facade_base<boost::range_detail::integer_iterator<long unsigned int>, long unsigned int, boost::iterators::random_access_traversal_tag, long unsigned int, long int, false, false>::operator*())’, which is of pointer type ‘const RDKit::Atom*’ (maybe you meant to use ‘->’ ?)
     boost::tie(nbr, endNbrs) = mol.getAtomBonds(mol[*bAts].get());
                                                            ^~~
/home/jackylee/rdkit-2018.03.4/include/rdkit/GraphMol/MolDrawing/MolDrawing.h:165:13: error: ‘BOND_SPTR’ does not name a type; did you mean ‘ROMOL_SPTR’?
       const BOND_SPTR bond = mol[*nbr];

- RDKit Version: 2018.03.4
- Platform: Linux

```
#include <GraphMol/MolDrawing/DrawingToSVG.h>
int main() {}
```

**Comment by greglandrum** [comment]
The code in`GraphMol/MolDrawing` is deprecated and should not be used (this needs to be documented somewhere, but it isn't yet).
If you'd like to produce SVGs, the code to use is in `GraphMol/MolDraw2D/MolDraw2DSVG.h`
Sorry for the confusing state of things.

**Comment by HongjianLi** [comment]
Thank you. I can now successfully use GraphMol/MolDraw2D/MolDraw2DSVG.h to draw a SVG
