### ISSUE TITLE
Allow ctest to run memcheck on tests

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#2107]
As far as I know, the only infrastructure in RDKit to memcheck the code is the "test-valgrind" test. Since that test most probably does not cover all the code, we might potentially miss some problems.

To improve coverage of memtesting, I am working on enabling the "-T memtest" option in ctest, so that most of the tests can be automatically run through valgrind. BasicalIy, memtest will run on all tests which are built, with the exception of python-wrapped ones. I plan on excluding those because python code is slow to debug and leaks are difficult to interpret. In case there are some other tests (i.e. Java-wrapped ?) that should be excluded too, these might also be ignored in the same way I am implementing for python.

Ideally, I would also include a suppressions file to ignore the currently existing problems (if there are any), even though these will be machine and GLIBC and/or compiler dependant.

**Comment by greglandrum** [comment]
This is a really worthy goal and something I'm happy to help with, but I'm afraid it's going to be a non-trivial amount of work. There are a bunch of tests, some of them a fairly long, and most of them were written without paying attention to cleaning up memory (in retrospect clearly not the best thing to ignore, but it's where we are...)

We may want to start with a really broad exclusion list and then go more or less a (Code) directory at a time in doing the cleanups.

A bit more history: A lot of the code has been tested for leaks already, just not in an automated way and not on a regular basis. I have historically just written individual tests that I then ran manually with memcheck. As you've observed, these unfortunately normally didn't get checked in

**Comment by d-b-w** [comment]
Yeah, I was thinking that we add a suppressions file to ignore all current errors. That way we could at least figure out if we add _new_ errors.

**Comment by bp-kelley** [comment]
Perhaps we could configure the build to opt out of cmake during testing by default and reenable it on a case by case basis for new tests and fixing old ones.

**Comment by ricrogz** [comment]
Added a new PR, #2123 addressing mem problems found by valgrind.
