### ISSUE TITLE
Adopt EnumerateStereoisomers to use extended stereo

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2109]
**Description:**

It would be super useful to be able to generate all the stereoisomers that are encoded in an enhanced stereo bundle.

Since EnumerateStereoisomers is currently in Python, this depends on #2108 being completed first.

**Comment by d-b-w** [comment]
I think this was addressed in https://github.com/rdkit/rdkit/pull/2193, and we can close this issue.
