### ISSUE TITLE
Port EnumerateStereoisomers to C++

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2110]
**Description:**

It would be nice to have access to this from the cartridge and the Java wrappers (so we could, e.g. create a KNIME node for it).

**Comment by d-b-w** [comment]
Ohh, this is also only my to do list. If you don't already have work on this, I'll probably start on it in the next couple of weeks.

**Comment by greglandrum** [comment]
Nope, I haven’t started yet; just wanted to capture it

**Comment by d-b-w** [comment]
I've scheduled time to work on this. I'll probably put the implementation in a file associated with MolBundle.h.

**Comment by greglandrum** [comment]
My two cents: I think the implementation goes in a separate source file in `$RDBASE/Code/GraphMol`. The declaration should be in the namespace `MolOps`.
Creating a separate test file for this would be a good idea, and the tests would ideally use the new catch2-based testing style (take a look at  https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/catch_tests.cpp for an example of what these look like).

**Comment by d-b-w** [comment]
@greglandrum - I've started on this in truth now.

One thing that I'm curious about - do you think that the randomization feature is important? I haven't been able to find anyone using it on Github, and it adds complexity and size, as well as making the interface slightly larger.

 It feels like if you had enough stereoisomers to actually want to randomly sample them, you'd have to be looking at something like a polymer, in which case I'd imagine that there might be some defined relationship between the centers.

**Comment by greglandrum** [comment]
I think it’s not critical to leave it out. We can always bolt it back on later if need be.

@coleb: I think you are the most likely to be using the random feature; you ok with leaving it out?

**Comment by coleb** [comment]
Provided that the C++ function still terminates when a certain number of isomers are generated I am fine leaving out the random sampling. It's not uncommon to run across drug like molecules with quite a few centers that would expand out to thousands of isomers. It's not just polymers, complex ring systems seen in drug-like natural products have quite a few. For example, heroin/morphine has 5 stereo centers in its single complex ring system. 

We typically don't want to expand sampling for a specific racemate 32-fold as this could artificially enrich racemic compounds in 3D virtual screens. So more important than the 'random' part is being able to fix the number of isomers generated for a molecule. It also makes sure the software terminates in a reasonable time frame. 

Fun fact to demonstrate why taking care with isomer sampling is important. The DUD-E docking validation dataset has more unspecified stereo centers in its actives than its decoys. So just by throwing a random number for every expanded isomer and taking the maximum value seen you can achieve an AUC ~0.6.

**Comment by mcneela** [comment]
I need this for a project I'm working on and can write the C++ for it. Can I take this on?

**Comment by d-b-w** [comment]
Go for it! I was hoping to implement the C++ version as an iterator, allowing the caller to stop at will

**Comment by mcneela** [comment]
@d-b-w  That sounds like a good idea! I'll ping everyone here once I have a working PR.

**Comment by greglandrum** [comment]
Thanks @mcneela !

**Comment by mcneela** [comment]
Hi @greglandrum and @d-b-w 

I've started a draft PR for this. It would be great if you could take a look and let me know your thoughts on how everything is structured. 

I also need a bit of help as I'm relatively new to RDKit, especially the C++ library. A few things:

1. Any ideas for how to best implement the `_RangeBitsGenerator` and `_UniqueRandomBitsGenerator` classes? Defining full C++ iterators for these seems a bit overkill, but I'm open to suggestions.
2. I'm confused on how to use the `DGeomHelpers::EmbedMolecule` class. In the Python version this returns an integer that is used for branching in the `EnumerateStereoisomers` function, but the C++ version doesn't return anything.

Please let me know any other thoughts! I'm still going to do at least a few more passes to clean things up.

**Comment by greglandrum** [comment]
Hi @mcneela thanks for the PR.
This week is super busy because of the upcoming RDKit beta release, but I will try to make some time to take a look next week.

**Comment by mcneela** [comment]
@greglandrum No worries, take your time!
