### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by shashany** [rdkit/rdkit#2112]
**Description:**
Hi,
I am using pycharm (version 2018.2) and rdkit version 2018.03.3.0 installed using anaconda3 on windows 10. 
I have successfully used the Chem functions but when I want to import AllChem I get the Dll error.
I have tried activating my environment from the anaconda prompt and then running pycharm from there but still no success. I understand it's probably a path config thing so it'll be really useful if you could describe the exact paths I need to add to my environmental variables. 
I have already tried adding all kinds of paths to path but nothing works.

Help!

Thanks,
Shany

```
Your code sample here
```

**Comment by greglandrum** [comment]
I don't use pycharm, but have you tried following these steps?
https://stackoverflow.com/questions/34898422/how-to-add-rdkit-to-project-in-pycharm

**Comment by shashany** [comment]
Hi, yeah!
That was how I got it to work in the first place. I wonder why only the Chem works then.
So what is the best configuration to work with the package on windows? I am pretty open for suggestions.

Thanks!
