### ISSUE TITLE
testEnumeration ..................***Exception: SegFault

### ISSUE THREAD

**Issue by pavlovnicola** [rdkit/rdkit#2114]
Hi,

I have installed RDkit and I am trying to test my installation using the ctest command.

It is failing on "testEnumeration" test.

Test project /opt/rdkit-Release_2018_03_4/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 52
    Start 52: testEnumeration

52: Test command: /opt/rdkit-Release_2018_03_4/build/Code/GraphMol/ChemReactions/testEnumeration
52: Test timeout computed to be: 9.99988e+06
52: 30000000000 30000000000
52: 0,0 0
52: 0,1 0
52: 1,0 0
52: 1,1 0
52: 2,0 0
52: 2,1 0
52: [17:10:51] Removed 1 non matching reagents at template 0
52: [17:10:51] Removed 1 non matching reagents at template 1
52: [17:10:51] Removed 1 non matching reagents at template 2
52: [17:10:51] -------------------------------------
52: [17:10:51] Testing github #1657: EnumerateLibrary with initFromString called twice doesn't clear the reaction
52: [17:10:51]  done
1/1 Test #52: testEnumeration ..................***Exception: SegFault  7.10 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   7.11 sec

The following tests FAILED:
         52 - testEnumeration (SEGFAULT)
Errors while running CTest

Any hint please on how to solve this?

- RDKit Version: '2018.03.4'
- Platform: Linux 4.14.62-65.117.amzn1.x86_64 #1 SMP Fri Aug 10 20:03:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bp-kelley** [comment]
I’ll need to know more about your setup.  Did you build via cmake or install a prebuilt distribution?  

What os are you running on, etc...

----
Brian Kelley

**Comment by pavlovnicola** [comment]
Hi,

I built it via cmake, cmake3 to be more specific.

I am running it on Amazon linux ami.

NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

Boost Version: boost_1_68_0

Thanks in advance.

**Comment by greglandrum** [comment]
FWIW: I have not tested the RDKit at all with boost 1.68, so it could be this.
To remove that variable, please try using boost 1.65

**Comment by bp-kelley** [comment]
package:
  name: rdkit
  # version is the last TAG + the number of commits since
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'LOCAL').replace("_", ".").replace("Release.","") }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: https://github.com/rdkit/rdkit.git
  # Can pull master for development
  git_rev: master
  patches:
    - rdpaths.patch
    - rdconfig.patch [win]

build:
  number: 1

requirements:
  build:
    - requests
    - {{ compiler('cxx') }}
    - python
    - m2-patch [win]
    - cmake
  host:
    - py-boost ==1.65.1
    - python
    - numpy ==1.12
    - pillow
    - freetype
    - nox [linux]
    - cairo_nox [linux]
    - cairo [not linux]
    - pkg-config [unix]
    - eigen
    - pandas
  run:
    - py-boost >=1.65.1
    - cairo
    - python
    - pillow
    - pandas
    - numpy >=1.12
test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
