### ISSUE TITLE
Compilation issue with RDKit on CentOs 7

### ISSUE THREAD

**Issue by poganyp** [rdkit/rdkit#2118]
I have an issue with RDKit compilation:

[ 74%] Building CXX object Code/GraphMol/Descriptors/CMakeFiles/Descriptors_static.dir/MORSE.cpp.o
../../../lib/libRDKitFilterCatalog.so.1.2018.03.4: undefined reference to `boost::archive::text_iarchive_impl<boost::archive::text_iarchive>::load_override(boost::archive::class_name_type&)'
../../../lib/libRDKitFilterCatalog.so.1.2018.03.4: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [Code/GraphMol/FilterCatalog/filterCatalogTest] Error 1
make[1]: *** [Code/GraphMol/FilterCatalog/CMakeFiles/filterCatalogTest.dir/all] Error 2

I have rebuilt most of the tools on CentOS7:
I have installed:
openmpi-3.1.2
boost_1_68_0
cairo-1.15.12
eigen from repository
Python-3.6.6
GCC is pretty old (standard from CentOS 7):
gcc 4.8.5
cmake 3.11.4

Originally I did not want to build it with python, but I could not find any solution how to avoid it.
cmake . \
-DCMAKE_INSTALL_PREFIX:PATH=/progs/rdkit \
-DPy_ENABLE_SHARED=1 \
-DRDK_BUILD_CAIRO_SUPPORT=ON \
-DRDK_INSTALL_STATIC_LIBS=ON \
-DRDK_BUILD_INCHI_SUPPORT=ON \
-DRDK_BUILD_CPP_TESTS=ON \
-DPYTHON_VERSION_MAJOR=3 \
-DPYTHON_EXECUTABLE=/progs/rdkit/bin/python3 \
-DPYTHON_INSTDIR=/progs/rdkit \
-DPYTHON_INCLUDE_DIR=/progs/rdkit/include/python3.6m \
-DPYTHON_NUMPY_INCLUDE_PATH=/progs/rdkit/lib/python3.6/site-packages/numpy/core/include \
-DBoost_INCLUDE_DIR=/progs/rdkit/include \
-DBOOST_LIBRARYDIR=/progs/rdkit/lib \
-DBOOST_ROOT=/progs/rdkit \
-DBoost_NO_SYSTEM_PATHS=ON

I was trying other definitions e.g. -DRDK_INSTALL_STATIC_LIBS=OFF or -DRDK_INSTALL_INTREE=ON or -DRDK_BUILD_PYTHON_WRAPPERS=OFF or leaving out -DBoost_NO_SYSTEM_PATHS=ON. But they all lead to either this error or if I get rid of this I have a strange error:
CMake Error at External/CoordGen/cmake_install.cmake:153 (file):
  file INSTALL cannot find
  "/progs/rdkit/rdkit_install/lib/libRDKitcoordgenlib.so.1.2018.03.4".
Call Stack (most recent call first):
  External/cmake_install.cmake:45 (include)
  cmake_install.cmake:93 (include)
After the building and before the installtion it is there, during the installation it disappears.

After I run the cmake it always gives warnings. However, it does not give what is missing:
CMake Warning at /opt/cmake-3.11/Modules/FindBoost.cmake:839 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /opt/cmake-3.11/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /opt/cmake-3.11/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:191 (find_package)

Could you please help?

**Comment by bp-kelley** [comment]
In a pinch, you can add -DRDK_USE_BOOST_SERIALIZATION=OFF

It looks as though you are finding headers but not the real boost libraries.  Your CMakeCache.txt should indicate exactly what was found.

In any case, we haven't done any testing on boost 1.68, I would try 1.65 and possibly 1.69.  Let me know if this keeps happening on the other boost versions.

**Comment by poganyp** [comment]
Thank you very much. I think the problem was with the incompatibility between cmake and boost.

With version 1.66 it works but I get different Warnings in cmake step which later causes the crash during make:

WARNING: Target "MolDraw2D" requests linking to directory "/hpc/projects/cassapps/progs/rdkit/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "MolDraw2D" requests linking to directory "/hpc/projects/cassapps/progs/rdkit/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "moldraw2DTest1" requests linking to directory "/progs/rdkit/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "moldraw2DRxnTest1" requests linking to directory "/progs/rdkit/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "rdMolDraw2D" requests linking to directory "/progs/rdkit/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "rdmolops" requests linking to directory "/progs/rdkit/lib".  Targets may link only to libraries.  CMake is dropping the item.

What are these bound to?
