### ISSUE TITLE
2018_09_1b1: catch.hpp missing?

### ISSUE THREAD

**Issue by balducci** [rdkit/rdkit#2125]
hello

resending here as I failed to send this to the rdkit-devel list
(post by non member)

just tried to build 2018_09_1b1 and getting:

    ----8<----
    /usr/bin/g++  -m64  -DRDKIT_DYN_LINK -DRDKIT_FILEPARSERS_BUILD -DRDK_64BIT_BUILD -DRDK_BUILD_COORDGEN_SUPPORT -DRDK_BUILD_DESCRIPTORS3D -DRDK_HAS_EIGEN3 -DRDK_TEST_MULTITHREADED -DRDK_THREADSAFE_SSS -DRDK_USE_STRICT_ROTOR_DEFINITION -I../External/catch/catch/single_include -I../External -I/usr/python3/include/python3.7 -I/usr/python3/site_python3/lib64/numpy.egg/numpy/core/include -I../Code -isystem /usr/include/eigen3 -I/usr/Xorg/include -mpopcnt -std=c++11 -Wno-deprecated -Wno-unused-function -fno-strict-aliasing -Wall -Wextra -fPIC -O3 -DNDEBUG -MD -MT Code/GraphMol/FileParsers/CMakeFiles/fileParsersCatchTest.dir/catch_tests.cpp.o -MF Code/GraphMol/FileParsers/CMakeFiles/fileParsersCatchTest.dir/catch_tests.cpp.o.d -o Code/GraphMol/FileParsers/CMakeFiles/fileParsersCatchTest.dir/catch_tests.cpp.o -c ../Code/GraphMol/FileParsers/catch_tests.cpp
    ../Code/GraphMol/FileParsers/catch_tests.cpp:13:10: fatal error: catch.hpp: No such file or directory
     #include "catch.hpp"
              ^~~~~~~~~~~
    compilation terminated.
    ---->8----

Actually, I don't seem to find any catch.hpp header after cloning the
repository

Building on linux with (if that matters):

    ----8<----
    install:363> cmake --version
    cmake version 3.13.0-rc1

    -DCMAKE_INSTALL_PREFIX=${PREFIX}
    -DRDK_INSTALL_INTREE=OFF
    -DLIB_SUFFIX="64"
    -DPYTHON_INSTDIR=${PYTHON_INSTDIR}
    -DBoost_INCLUDE_DIR:PATH=${BOOST_ROOT}/include
    -DBoost_LIBRARY_DIR_DEBUG:PATH=${BOOST_ROOT}/lib64
    -DBoost_LIBRARY_DIR_RELEASE:PATH=${BOOST_ROOT}/lib64
    -DPYTHON_EXECUTABLE:FILEPATH=$(which python)
    -DRDK_BOOST_PYTHON3_NAME:STRING=python37

    install:364> ninja --version
    1.8.2
    install:365> gcc --version
    gcc (GCC) 8.2.0
    Copyright (C) 2018 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    ---->8----

thanks
ciao
gabriele

**Comment by greglandrum** [comment]
Hi Gabriele,

Yeah, you need to subscribe to the mailing list in order to post to it.

And, you're right, something has gone wrong with the way the build system is setup w.r.t. catch. I will take a look.

**Comment by greglandrum** [comment]
This was a really well timed question... I was planning on doing the release this evening. Thanks for pointing out the problem! :-)

Here's what happened: I had forgotten to add an explicit dependency on catch in the tests that use it. So the build system didn't know that it needed to download catch before trying to build those tests. Whether or not your builds failed depended on which order you did them in. Ugly...

Anyway, it was an easy fix and will be in the actual release.

**Comment by balducci** [comment]
thanks a lot
it now works nicely (as always!)
