### ISSUE TITLE
Cannot import name rdBase after building from source

### ISSUE THREAD

**Issue by alexbleakley** [rdkit/rdkit#2131]
**Description:**

I have a requirement to build rdkit from source on Ubuntu 16.04. I am using the following commands as per the documentation:

```
apt-get -y install flex bison build-essential python-numpy cmake python-dev sqlite3 libsqlite3-dev libboost-dev  libboost-python-dev libboost-regex-dev
wget https://github.com/rdkit/rdkit/archive/Release_2015_03_1.tar.gz
tar -xzf Release_2015_03_1.tar.gz -C /opt
export RDBASE=/opt/rdkit-Release_2015_03_1/
export LD_LIBRARY_PATH=$RDBASE/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$RDBASE:$PYTHONPATH
cd $RDBASE
mkdir build
cd build
cmake ..
make
```

After install, I launch a Python session and attempt to import Chem from rdkit and get the following error:

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rdkit-Release_2015_03_1/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import rdBase
ImportError: cannot import name rdBase
```

**Workaround:**

I noted that rdBase.so is not in /opt/rdkit-Release_2015_03_1/rdkit/ . It is in /opt/rdkit-Release_2015_03_1/build/rdkit/ . So I tried:

```
cp -r /opt/rdkit-Release_2015_03_1/build/rdkit/* /opt/rdkit-Release_2015_03_1/rdkit/
```

I was then able to run "from rdkit import Chem" in a Python session without error.

**Outstanding issue:**

For the latest release, 2018_03_04, this workaround is not successful. Before copying the files from build, I get:

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rdkit-Release_2018_03_4/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: No module named rdBase
```

After copying the files in the same manner I get:

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: /opt/rdkit-Release_2018_03_4/build/lib/libRDKitRDBoost.so.1: undefined symbol: _ZN5boost6python23throw_error_already_setEv
```

I have not spent any time trying to resolve this issue for 2018_03_04, as my priority is to get some version of rdkit working, so I am proceeding with 2015_03_01.

**Comment by greglandrum** [comment]
You need to do a ‘make install’ after you do the ‘make’

**Comment by greglandrum** [comment]
That last one looks like it could be due to your LD_LIBRARY_PATH being set so that you are getting the wrong boost libraries, but I'm not sure.
Try doing: `ldd /opt/rdkit-Release_2018_03_4/build/lib/libRDKitRDBoost.so.1` and see if it's finding the boost libs you expect.

**Comment by alexbleakley** [comment]
`ldd /opt/rdkit-Release_2018_03_4/build/lib/libRDKitRDBoost.so.1` outputs:

```
        linux-vdso.so.1 =>  (0x00007ffdf4559000)
        libRDKitRDGeneral.so.1 => /opt/rdkit-Release_2018_03_4/build/lib/libRDKitRDGeneral.so.1 (0x00007f1e9aac2000)
        libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f1e9a52d000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1e9a1ab000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1e99f94000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1e99bca000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1e998c1000)
        /lib64/ld-linux-x86-64.so.2 (0x000055fed5560000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1e996a3000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1e99489000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1e99285000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f1e99081000)
```

**Comment by alexbleakley** [comment]
Solved issue by installing additional boost libraries as per https://github.com/rdkit/rdkit/issues/762

Thanks again for your help Greg.

**Comment by UnixJunkie** [comment]
@alexbleakley if you have a complete script working to get rdkit installed from sources, I would be happy to see it.
I am trying to maintain a script
(https://github.com/rdkit/rdkit/blob/master/Scripts/create_deb_packages.sh)
to produce deb packages from the source tree, but for systems
without deb packages, this script is useless.
I know we have instructions in the documentation on how to build rdkit, but I prefer a working script to an always outdated documentation (I am not criticizing our documentation, it is just the fate of documentation to be so).

**Comment by greglandrum** [comment]
To be honest, I don't really see the difference. If it's possible to keep a script up to date, then it's possible to keep the documentation up to date. The docs need to be there anyway, because it's the logical first place for people to look.

**Comment by UnixJunkie** [comment]
If the script is up to date, then it's easy to update the doc.
Also, the doc could then just point to that script and not need anymore to be maintained, concerning that particular topic.
