### ISSUE TITLE
Program freezing on enumerate stereochemistry

### ISSUE THREAD

**Issue by b-mahjour** [rdkit/rdkit#2132]
**Description:** Program freezing on enumerate stereochemistry.

- RDKit Version: '2018.03.3'
- Platform: Windows Subsystem Linux Ubuntu

The smiles string it freezes on: CC1CCCC(C(=O)NC2CCC3CC3C2)C1

```
	opts = StereoEnumerationOptions(tryEmbedding=True)
	for p in final_set2:
		print(Chem.MolToSmiles(p))
		for x in tuple(EnumerateStereoisomers(p,options=opts)):
			print(Chem.MolToSmiles(x))
			prods.append((Chem.MolToSmiles(x)))
```

**Comment by greglandrum** [comment]
It's probably not frozen, it's doing the enumeration but the `tryEmbedding` option can be quite computationally intensive.
If you switch that off you'll get results quite quickly.
It would be nice if the enumeration could could filter out unreasonable stereoisomers without the embedding step, but I haven't figured out how to do that yet.
