### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [rdkit/rdkit#214]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](http://en.wikipedia.org/wiki/Smart_pointer#unique_ptr)"?

Update candidates:
- [Atom](https://github.com/rdkit/rdkit/blob/dcbceede737a6953c64bbc2a069b3c841e3e8ea1/Code/GraphMol/Atom.h#L32)
- [FragCatalogEntry](https://github.com/rdkit/rdkit/blob/2114db094118c710505fdac31e8f2d8e161703a3/Code/GraphMol/FragCatalog/FragCatalogEntry.h#L26)
- [InfoBitRanker](https://github.com/rdkit/rdkit/blob/0407268aa858c12d2c33fe994cb44b6bf6154932/Code/ML/InfoTheory/InfoBitRanker.h#L121)
- [MolCatalogEntry](https://github.com/rdkit/rdkit/blob/0407268aa858c12d2c33fe994cb44b6bf6154932/Code/GraphMol/MolCatalog/MolCatalogEntry.h#L17)
- [O3A](https://github.com/rdkit/rdkit/blob/c73792bb213a772acf35cf81e07e3174e5b1f6b8/Code/GraphMol/MolAlign/O3AAlignMolecules.h#L195)
- [ROMol](https://github.com/rdkit/rdkit/blob/387406f657ebcb56c4a23d86bb71ef7efb815265/Code/GraphMol/ROMol.h#L74)

**Comment by PascalSoveaux** [comment]
Hello,

(6 years later) we will be pleased to help if you are now interested to use smart ptrs or modern C++ to allocate memory. Our application was leaking a lot until we found that unhandled exceptions were responsible for the leaks. 

Plus Smart ptrs make the code clearer and reduce the risk to leak even when exceptions are handled :
`
  RWMol *res = nullptr;
  res = toMol(lsmiles, smiles_parse, lsmiles);

  if (res && params.allowCXSMILES && !cxPart.empty()) {
    std::string::const_iterator pos = cxPart.cbegin();
    try {
      SmilesParseOps::parseCXExtensions(*res, cxPart, pos);
    } catch (const SmilesParseException &e) {
      if (params.strictCXSMILES) {
        throw; // res SHOULD BE RELEASED HERE ?
      }
    }
`

Pascal

**Comment by d-b-w** [comment]
RDkit currently (mostly) uses smart pointers for internal data structures. There is a major project (API2) to update external API to use smart pointers and other memory safe constructs in a backwards compatible way.
