### ISSUE TITLE
SMARTS roundtrip failure

### ISSUE THREAD

**Issue by mcs07** [rdkit/rdkit#2142]
I just came across a SMARTS that reads fine with `MolFromSmarts`, but then `MolToSmarts` fails:

```python
>>> m = Chem.MolFromSmarts('[C;H1&$(C([#6])[#6]),H2&$(C[#6])]')
>>> print(Chem.MolToSmarts(m))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: unidentifiable C++ exception
```

It seems to be something to do with the branching in the first recursive part. `DescribeQuery` looks fine:

```python
>>> print(m.GetAtoms()[0].DescribeQuery())
AtomAnd
  AtomType 6 = val
  AtomOr
    AtomAnd
      AtomHCount 1 = val
      RecursiveStructure val in ()
    AtomAnd
      AtomHCount 2 = val
      RecursiveStructure val in ()
```

`MolToSmarts` also works fine if I rewrite it as `[$([CH1]([#6])[#6]),$([CH2][#6])]` (I think this is equivalent).

- RDKit Version: 2018.09.1
- Platform: Linux

**Comment by mcs07** [comment]
Another example that seems to have a similar problem: `[N;$(NC),H2&$(NC[C,N])]`

Fails as soon as the `[C,N]` is introduced in the second recursive part. Likewise can be fixed by bringing the H count inside the `$()`.

**Comment by greglandrum** [comment]
Wow, great catch. I'm amazed this has never come up before.
The failure is happening here: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/SmilesParse/SmartsWrite.cpp#L54

I will fix it (and get rid of the fact that it's raising an exception by throwing a `char *`, that's gross)
