### ISSUE TITLE
Error thrown in rdMolStandardize.ChargeParent

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#2144]
**Description:**

- RDKit Version: '2018.09.1'
- Platform: MacOS High Sierra

rdMolStandardize.ChargeParent gives error with no helpful info. This is reproducible if you feed the output of one call to ChargeParent back into the same function.

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: unidentifiable C++ exception

```
molx = Chem.MolFromSmiles("c1ccccn1")
moly = rdMolStandardize.ChargeParent(molx)
molz = rdMolStandardize.ChargeParent(moly)
```

**Comment by greglandrum** [comment]
Confirmed. I will take a look at it.
