### ISSUE TITLE
SMILES parsing inconsistency based on input order

### ISSUE THREAD

**Issue by coleb** [rdkit/rdkit#2148]
Another test case for @baoilleach SMILES benchmark. 

Changing the order of fragments separated by dots and then connected with a digit shouldn't change the molecule. But in the case whenever one of the closure digits has a bond stereo marker, and the other has a bond order, the order of the fragments matters to RDKit.

```python
In [1]: import rdkit

In [2]: rdkit.__version__
Out[2]: '2018.09.1'

In [3]: from rdkit import Chem

In [4]: Chem.CanonSmiles(r'O=C1C=4CCc2ccccc21.C(=C\F)\4')
Out[4]: 'O=C1C(=C=CF)CCc2ccccc21'

In [5]: Chem.CanonSmiles(r'C(=C\F)\4.O=C1C=4CCc2ccccc21')
Out[5]: 'O=C1c2ccccc2CCC1/C=C\\F'
```

Note, this is inconsistent with other tools: 

```
$ ./count-hydrogens 'C(=C\F)\4.O=C1C=4CCc2ccccc21'
RDKit: 25 atoms 11 hydrogens
OEChem: 23 atoms 9 hydrogens
ChemAxon molconvert: 23 atoms 9 hydrogens
pybel impHs: 23 atoms 9 hydrogens
pybel AddHs: 23 atoms 9 hydrogens
babel gen3D: 23 atoms 9 hydrogens
$ ./count-hydrogens 'O=C1C=4CCc2ccccc21.C(=C\F)\4'
RDKit: 23 atoms 9 hydrogens
OEChem: 23 atoms 9 hydrogens
ChemAxon molconvert: 23 atoms 9 hydrogens
pybel impHs: 23 atoms 9 hydrogens
pybel AddHs: 23 atoms 9 hydrogens
babel gen3D: 23 atoms 9 hydrogens
```

Other tools make the double bond marker 'win' regardless of when it occurs. There are two exceptions among the tools I have access to: MOE fails to parse the SMILES entirely; corina reports a reasonable error message about inconsistency in the SMILES string: 

```
corina     4.1.0 0026  01.08.2017  coleb     03. 11. 2018 13:08  enlogin43.en.desres.deshaw.com

Input file type  SMILES
   allowing dummy atoms
   Reading SMILES from column 1
   Reading name from column 2
Output file type MDL SDFile
   Writing compact SDFiles
...
ERROR smilesct(): Conflicting ring closure bond types
   O=C1C=4CCc2ccccc21.C(=C\F)\4
                              ^
ERROR smilesct(): General error while interpreting this character
   O=C1C=4CCc2ccccc21.C(=C\F)\4
...
ERROR smilesct(): Conflicting ring closure bond types
   C(=C\F)\4.O=C1C=4CCc2ccccc21
                   ^
ERROR smilesct(): General error while interpreting this character
   C(=C\F)\4.O=C1C=4CCc2ccccc21
``` 

Also note RDKit is fine whenever switching input order with the presence of either a bond order marker or a bond stereo marker: 

```python
In [6]: Chem.CanonSmiles(r'C(=CF)4.O=C1C=4CCc2ccccc21')
Out[6]: 'O=C1C(=C=CF)CCc2ccccc21'

In [7]: Chem.CanonSmiles(r'O=C1C=4CCc2ccccc21.C(=CF)4')
Out[7]: 'O=C1C(=C=CF)CCc2ccccc21'

In [8]: 

In [8]: Chem.CanonSmiles(r'C(=C\F)\4.O=C1C4CCc2ccccc21')
Out[8]: 'O=C1c2ccccc2CCC1/C=C\\F'

In [9]: Chem.CanonSmiles(r'O=C1C4CCc2ccccc21.C(=C\F)\4')
Out[9]: 'O=C1c2ccccc2CCC1/C=C\\F'
```

**Comment by greglandrum** [comment]
This was one I couldn't figure out from the Daylight docs and where the user intent is really not clear, so I picked an easy-to-explain option: take the first bond order specified. 

I'm curious why the double bond should "win" over the other user-specified bond order. Does triple take priority over double? What about aromatic and double? Why is this "more correct" than taking the first-specified choice?

**Comment by greglandrum** [comment]
Ah, now after reading the SMILES theory manual again I see that directional bonds - '\` or `/` - are "default" bond types (i.e. single or aromatic). So they aren't explicitly indicating "single".
That's a bug.

**Comment by greglandrum** [comment]
There's still a good question about which bond order should be taken when the two are inconsistent, but a directional bond isn't inconsistent.
