### ISSUE TITLE
Found a structure RDKit cannot embed

### ISSUE THREAD

**Issue by ThomasDutschmann** [rdkit/rdkit#2165]
While calculating the volumes of numerous screening compounds, I came across a molecule the RDKit just can't handle.

RDKit Version: 2018.09.1 (running in miniconda3, with Python 3.6.5)
Platform: macOS Mojave

Within the screening compound library I am currently filtering, there is a compound defined by the SMILES string **O=c1cccc2n1C[C@@H]1CNC[C@@H]2C1** for which my volume calculation script simply crashes. I visualized the compound in an IPython notebook and even generated conformers using MMFFOptimizeMolecule. Everything looks good, but the EmbedMolecule function fails and I can't get the volume of it:

```
>>> mol = MolFromSmiles('O=c1cccc2n1C[C@@H]1CNC[C@@H]2C1')
>>> mol_with_Hs = AddHs(mol)
>>> EmbedMolecule(mol_with_Hs)
-1
>>> ComputeMolVolume(mol_with_Hs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Thomas/miniconda3/envs/my-rdkit-env/lib/python3.6/site-packages/rdkit/Chem/AllChem.py", line 96, in ComputeMolVolume
    conf = mol.GetConformer(confId)
ValueError: Bad Conformer Id
```

So far, it is the only molecule in my library that produces this error.

**Comment by greglandrum** [comment]
I suspect that the problem here is that the stereoisomer encoded by that SMILES can't actually exist. It encodes a structure where an H atom would have to point inside the cage of a fused ring system. 
The SMILES `O=c1cccc2n1C[C@@H]1CNC[C@H]2C1` embeds without problems and is probably what you intended.

**Comment by ThomasDutschmann** [comment]
Thank you for the immediate answer. I agree, the SMILES is flawed. I will inform the provider of the screening compound library.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
