### ISSUE TITLE
get empty tuple from GetConformers()

### ISSUE THREAD

**Issue by AustinApple** [rdkit/rdkit#2170]
**Description:**
I want to transform the smile string into the 3D molecule. But, I get the empty tuple.  

- RDKit Version: 2018.09.1
- Platform: macOS High Sierra 10.13.6

```
from rdkit import Chem 
m = Chem.MolFromSmiles('C1CCC1OC')
conforms = m.GetConformers()
print(conforms)
```

**Comment by bp-kelley** [comment]
A smiles string doesn't contain conformations, it simply describes the molecular graph.  You'll need to create conformations:

```
from rdkit import Chem
from rdkit.Chem import AllChem
m = Chem.MolFromSmiles('C1CCC1OC')
conforms = m.GetConformers()
print(conforms)

mh = Chem.AddHs(m)
AllChem.EmbedMolecule(mh)
print(mh.GetConformers())
```

**Comment by AustinApple** [comment]
It works. Thanks for your prompt reply.

**Comment by UnixJunkie** [comment]
this issue can be closed
