### ISSUE TITLE
Problem installating rdkit ModuleNotFoundError: No module named 'rdkit'

### ISSUE THREAD

**Issue by sbhakat** [rdkit/rdkit#2171]
I installed rdkit in my Ubuntu using the following command

`sudo apt-get install python-rdkit librdkit1 rdkit-datapython`

Looking at the output it seems like everything went well

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libbonobo2-0 libbonobo2-common libgconf2-4 libgnome2-0 libgnome2-bin
  libgnome2-common libidl-common libidl0 liborbit-2-0 liborbit2
  linux-headers-3.13.0-119 linux-headers-3.13.0-119-generic
  linux-headers-3.13.0-139 linux-headers-3.13.0-139-generic
  linux-headers-3.13.0-52 linux-headers-3.13.0-52-generic
  linux-headers-3.13.0-77 linux-headers-3.13.0-77-generic
  linux-headers-3.13.0-79 linux-headers-3.13.0-79-generic
  linux-headers-3.13.0-83 linux-headers-3.13.0-83-generic
  linux-headers-3.13.0-85 linux-headers-3.13.0-85-generic
  linux-headers-3.13.0-87 linux-headers-3.13.0-87-generic
  linux-headers-3.13.0-93 linux-headers-3.13.0-93-generic
  linux-headers-3.13.0-95 linux-headers-3.13.0-95-generic
  linux-image-3.13.0-119-generic linux-image-3.13.0-139-generic
  linux-image-3.13.0-52-generic linux-image-3.13.0-77-generic
  linux-image-3.13.0-79-generic linux-image-3.13.0-83-generic
  linux-image-3.13.0-85-generic linux-image-3.13.0-87-generic
  linux-image-3.13.0-93-generic linux-image-3.13.0-95-generic
  linux-image-extra-3.13.0-119-generic linux-image-extra-3.13.0-139-generic
  linux-image-extra-3.13.0-52-generic linux-image-extra-3.13.0-77-generic
  linux-image-extra-3.13.0-79-generic linux-image-extra-3.13.0-83-generic
  linux-image-extra-3.13.0-85-generic linux-image-extra-3.13.0-87-generic
  linux-image-extra-3.13.0-93-generic linux-image-extra-3.13.0-95-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libboost-regex1.54.0
Suggested packages:
  rdkit-doc
The following NEW packages will be installed:
  libboost-regex1.54.0 librdkit1 python-rdkit rdkit-data
0 upgraded, 4 newly installed, 0 to remove and 260 not upgraded.
Need to get 8 054 kB of archives.
After this operation, 25,7 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://se.archive.ubuntu.com/ubuntu/ trusty-updates/main libboost-regex1.54.0 amd64 1.54.0-4ubuntu3.1 [261 kB]
Get:2 http://se.archive.ubuntu.com/ubuntu/ trusty/universe librdkit1 amd64 201309-1 [1 420 kB]
Get:3 http://se.archive.ubuntu.com/ubuntu/ trusty/universe python-rdkit amd64 201309-1 [1 897 kB]
Get:4 http://se.archive.ubuntu.com/ubuntu/ trusty/universe rdkit-data all 201309-1 [4 476 kB]
Fetched 8 054 kB in 0s (12,0 MB/s)                                             
Selecting previously unselected package libboost-regex1.54.0:amd64.
(Reading database ... 715051 files and directories currently installed.)
Preparing to unpack .../libboost-regex1.54.0_1.54.0-4ubuntu3.1_amd64.deb ...
Unpacking libboost-regex1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Selecting previously unselected package librdkit1.
Preparing to unpack .../librdkit1_201309-1_amd64.deb ...
Unpacking librdkit1 (201309-1) ...
Selecting previously unselected package rdkit-data.
Preparing to unpack .../rdkit-data_201309-1_all.deb ...
Unpacking rdkit-data (201309-1) ...
Selecting previously unselected package python-rdkit.
Preparing to unpack .../python-rdkit_201309-1_amd64.deb ...
Unpacking python-rdkit (201309-1) ...
Setting up libboost-regex1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Setting up librdkit1 (201309-1) ...
Setting up rdkit-data (201309-1) ...
Setting up python-rdkit (201309-1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
```

However when importing rdkit in Pythin I am getting the following error

```
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rdkit'

```

Any help?

**Comment by UnixJunkie** [comment]
try this instead, maybe
```
import rdkit
from rdkit import Chem
```

**Comment by greglandrum** [comment]
I just tried this on ubuntu 18.04 and everything worked fine. Are you sure that your PYTHONPATH is set properly and that you're running the correct version of Python?

**Comment by sbhakat** [comment]
First thing:

I activated a python environment like 

source activate py36 followed by
sudo apt-get install python-rdkit librdkit1 rdkit-datapython

I tried as suggested by @UnixJunkie which is giving error like

```
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rdkit'
```
My python path is here `/home/sbhakat/miniconda2/envs/py36/bin/python` 

Am I installing it in a  wrong way? I am not sure what is going wrong here.

**Comment by UnixJunkie** [comment]
I guess source activate is conda-related.
But then you use apt to install rdkit system-wide.
I guess you need to follow the instructions on how to install rdkit in a conda environment.
https://www.rdkit.org/docs/Install.html

**Comment by monk1337** [comment]
@greglandrum @sbhakat @UnixJunkie  I am also facing the same problem, I just installed rdkit by this command :

`sudo apt-get install python-rdkit librdkit1 rdkit-data`

While importing the module it's giving error 

```
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rdkit'
```

I tried to install again and getting this message  

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
librdkit1 is already the newest version (201603.5+dfsg-1ubuntu1).
python-rdkit is already the newest version (201603.5+dfsg-1ubuntu1).
rdkit-data is already the newest version (201603.5+dfsg-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
```

**Comment by e-kwsm** [comment]
Are you using Python3?

**Comment by monk1337** [comment]
@e-kwsm  it was python issue. I solved it. 

Thank you !

**Comment by UnixJunkie** [comment]
this issue can be closed

**Comment by jiachangliu** [comment]
@e-kwsm @monk1337 What is the issue with python? I'm also Python3 and getting the same error. How can I import the library successfully?

**Comment by UnixJunkie** [comment]
@jiachangliu what are the exact commands you used to install rdkit?

**Comment by jiachangliu** [comment]
@UnixJunkie I used the command:
`sudo apt-get install python-rdkit librdkit1 rdkit-data`

**Comment by UnixJunkie** [comment]
Ok, this is probably an old version of rdkit, so only python-2 will work with it.
If you want to use python-3, you can create packages from source using: Scripts/create_deb_packages.sh.
Just remove all the system-wide installed rdkit packages before installing those new ones.

**Comment by jiachangliu** [comment]
@UnixJunkie Hi, I have tried your command, the installation I think was successful. However, I am still not able to import rdkit. By the way, I am using a virtual environment for python3. Does this affect how the above command `Scripts/create_deb_packages.sh` would run?

**Comment by jiachangliu** [comment]
@UnixJunkie I have started using Anaconda3 and everything can be installed properly now. Thanks for answering my question though.

**Comment by SaiSandeepKantareddy** [comment]
> I just tried this on ubuntu 18.04 and everything worked fine. Are you sure that your PYTHONPATH is set properly and that you're running the correct version of Python?

Hi, I am unable to install it on 18.04, can you please help me in the process, even I used create debian packages.sh, not working though.

**Comment by UnixJunkie** [comment]
probably related to https://github.com/lehy/ocaml-sklearn

**Comment by mainguyenanhvu** [comment]
Please tried the solution in  [this link](https://stackoverflow.com/questions/37242189/rdkit-installation-issues-with-anaconda/76127780#76127780)
