### ISSUE TITLE
four unit tests failing on master in my build

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#2172]
The following tests FAILED:
	 64 - pyChemReactions (Failed)
	 71 - pyFilterCatalog (Failed)
	151 - pythonTestDbCLI (Failed)
	157 - pythonTestDirChem (Failed)

**Comment by UnixJunkie** [comment]
full log there:
https://gist.github.com/UnixJunkie/8150b2e5d905740e3937c95e37e17bf2

**Comment by UnixJunkie** [comment]
Not sure if that helps, but I am on Linux.

**Comment by greglandrum** [comment]
To do anything with this, we need to know what cmake command you used and which boost libraries you have installed

**Comment by UnixJunkie** [comment]
Too old so closing.
