### ISSUE TITLE
Add Text to drawings

### ISSUE THREAD

**Issue by LivC193** [rdkit/rdkit#2180]
I am trying to add some text to my drawings. I don't care where on the picture it is.

Currently I generate drawings using :
Chem.Draw.MolToFile(mol_new, ligand + '.svg', size = (800,500))

I tried using the rdMolDraw2D class but when I try : 

mol_new = Chem.MolFromSmiles(smiles_rep)
rdDepictor.Compute2DCoords(mol_new)
d2d = rdMolDraw2D.MolDraw2D(300,250)
d2d.DrawMolecule(mol_new)
d2d.DrawString('Title')
d2d.FinishDrawing()
but I get : "This class cannot be instantiated from Python" in line 3
      

I use python 2.7, on ubuntu 16.04 LTS

**Comment by sirbiscuit** [comment]
Hi @LivC182,

after reading #2194, I assume that you have found a way to add text to molecule drawings. So this issue can be closed.
