### ISSUE TITLE
how to speed up python (rdkit) scripts

### ISSUE THREAD

**Issue by rmrmg** [rdkit/rdkit#2187]
Standard Python implementation (CPython) is not extremely fast and I'm looking for something which allow to speed up my scripts. I guess my scripts are quite usual: many RDkit operations on mols like GetAtom(), GetBond(), GetSubstruct() and so on  and 'standard' python operation (no heavy numeric calculation, no big matrices and so on). The following option I found on internet:
-) pypy in general the best (the easier) way to speed up python execution but it doesn't work with rdkit. AFAIK the most reasonable workaround if to wrap needed RDkit function in separate python module 
-) numba which allow just-in-time compilation of specified function(s) look nice but it doesn't work with try,catch block 
-)Cython which allow to compile whole script but AFAIK if one want to have any speed up some modification is needed (static typing)
Do you have any other solution? Do you have any hand-on experience with any of above? Any suggestions or tips?

**Comment by bp-kelley** [comment]
Without knowing what you are trying to optimize, this is a challenging problem.

Do you have an example?

In python one generally wants to minimize function calls if possible.  I.e. using iterations like GetAtoms versus GetAtomWithIdx.

However,  I’ve found that using multiprocessing is by far the easiest way to speed up performance with minimal effort.

Do you have an example of the type of things you want to optimize?

**Comment by rmrmg** [comment]
@bp-kelley: Nope, I don't have any simple example which I can publish. My question is not about how to optimize particular code it is rather general question how exchange CPython with something faster in scripts with rdkit (where pypy is not a easy option). 
I know the trick with minimization function call (e.g. instead of many GetAtoms.. I do buffer result in list), of course I use multiprocessing but  still CPython is slow, in 'regular' python scripts one can observed significant speed up when pypy is used instead of CPython, and there is some other solution to execute python code faster. So this is my question: Have you tried to go beyond pure, standard CPython? Do you have any suggestion, experience in this field?

**Comment by UnixJunkie** [comment]
You can probably parallelize the processing, since usually molecules can be processed independently.
For example using the python multiprocessing module.

**Comment by rmrmg** [comment]
@UnixJunkie: Yes of course, nowadays paralelization is a must (all cpus now are multicore) and of course I use it in scripts where execution time is important. My problem is rather that I have code with many functions without one (few, limited) well visible bottleneck(s) (ie all functions take comparable amount of time) I believe the algorithms in the code all are at least reasonable (e.g. no O(n^2) sorting). Normally you can run your python code in pypy instead of CPython and in most cases you can observed significant speedup. When you use rdkit it is not so easy to use pypy. I asked the question because I thought I'm not the only one who want to use something to speedup python execution  and thought there are some people who have some experience in this field

**Comment by greglandrum** [comment]
It may be that you are hitting a bottleneck caused by the RDKit itself, which is mostly written in C++ (so pypy and numba won’t help), but without more info it’s really hard to tell.
What are you doing and what makes you think that the performance you are seeing is unreasonably slow?

**Comment by rmrmg** [comment]
@greglandrum: I dont think that RDKit is bottleneck. I talk about scripts where most of logic is in pure python (ie not in rdkit functions, in other words it is not rdkit script with python as a glue but python script which occasionally use rdkit and other libraries).  In many other situations (python without rdkit) pypy gave my significant speedup for free (no code modification and no side effects) therefore I asked the question.
I dont want to say that rdkit or CPython is unreasonable slow. I am sure that rdkit is fast (as all well written code in C/C++/fortran) and in case of scripts where Rdkit is bottleneck I never cry and believe that the performance is close to theoretical limits. Default CPython is not as fast as compiled code and there is room for improve performance. This is the intention of the question. I dont want to reinvent the wheel therefore I asked the question but now it seems to me that for all other RDKit users speed of CPython is not an issue and all time-consuming are performed within RDKit.

**Comment by greglandrum** [comment]
I would bet that you can pretty easily find people in the RDKit community too who would prefer faster performance from CPython. :-)

My usual strategy when doing method development in Python is to be as careful as I can to follow good Python programming practices (and avoid antipatterns) so that the code starts as fast as I can make it and then move the bottlenecks into C++. This obviously isn't an option that works for every Python programmer, but careful Python coding can actually produce quite speedy code. Another thing to look into might be Cython (https://cython.org/). I've not spent much time looking at that in the past, but have read a bunch of positive stuff about it.

I've never spent much time investigating PyPy because its support for extension modules like the RDKit was minimal/non-existent for quite a while and now they say that extension modules "take a large hit in performance" (https://pypy.org/performance.html).

**Comment by rmrmg** [comment]
@greglandrum: For sure no one will complaint about faster CPython but (seems to me) no one try to find way to execute python's code faster.
Yes, porting bottlenecks to C++ is an option which gives the best performance but its good when you have only few and rather small such places in code. Similar options is to use Jython and porting important fragment to java (coding in Java is faster than in C++)
I mentioned Cython (together with pypy and numba) in the first post. 
Ok, it seems there is no free lunch for this case (ie. no speed without code modification and reading documentation) and Cython and/or numba is what I need to learn.

**Comment by peastman** [comment]
I found this issue while looking for a way to use rdkit under pypy.  I was wondering if any progress has been made on it?

I have a very slow script I want to accelerate.  I'm not worried about accelerating rdkit itself.  It isn't the bottleneck.  But my script does use it, so it's preventing me from using pypy to speed up other parts of the code.

The support for extension modules in pypy has gotten a lot better.  If you just enable pypy builds on conda-forge, you might find everything just works with no further changes required.
