### ISSUE TITLE
Rdkit.Chem.Draw.savefig() creates empty figures

### ISSUE THREAD

**Issue by sorenwacker** [rdkit/rdkit#2190]
**Description:**
I can draw a molecule in a jupyter notebook with RDKit. Though, when I use the savefig() method only a white canvas is saved. No molecule is saved.

    %pylab inline
    from rdkit import Chem
    from rdkit.Chem import Draw

    smiles = 'CCC'
    m = Chem.MolFromSmiles(smiles)
    fig = Draw.MolToMPL(m)
    title('Test')
    fig.savefig('mol.jpeg')

Any idea what goes wrong here?

**Comment by soerendip** [comment]
Apparently, I have to add `bbox_inches='tight'` to `savefig`. Is there a reason why `False` instead of `True` is the default here?
