### ISSUE TITLE
Figures in documentation look better than the ones actually produced.

### ISSUE THREAD

**Issue by sorenwacker** [rdkit/rdkit#2191]
**Description:**
The figures described [here](https://www.rdkit.org/docs/GettingStartedInPython.html#drawing-molecules) have way better quality than the figures actually produced. The figures in the documentation are nice and clean. The figures that are produced look bad. They are pixely and the atom labels are unreadable, because they overlap with the molecule structure.  Some settings might be missing in the documentation.

- RDKit Version: '2018.09.1'
- Platform: Python 3.6.5, in WSL (Windows Subsystem for Linux (Ubuntu)
Linux C3PO 4.4.0-17134-Microsoft #345-Microsoft Wed Sep 19 17:47:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

Referring to this part of the documentation:
>>> suppl = Chem.SDMolSupplier('data/cdk2.sdf')
>>> ms = [x for x in suppl if x is not None]
>>> for m in ms: tmp=AllChem.Compute2DCoords(m)
>>> from rdkit.Chem import Draw
>>> Draw.MolToFile(ms[0],'images/cdk2_mol1.o.png')
>>> Draw.MolToFile(ms[1],'images/cdk2_mol2.o.png')

        smiles = 'FC=1\\C=N/C(=O)NC=1N'
        m = Chem.MolFromSmiles(smiles)
        fig = Draw.MolToMPL(m,size=(200,200))
        title(antib, fontsize='20')
        #fig.savefig(f'./output/figures/{antib}.jpeg', bbox_inches='tight')
        Draw.MolToFile(m, 'mol.png')

**Comment by soerendip** [comment]
The figures look somewhat like [this](https://i.stack.imgur.com/gMDmg.jpg).
