### ISSUE TITLE
Change color of DrawString func

### ISSUE THREAD

**Issue by LivC193** [rdkit/rdkit#2194]
The default color is red. How can I change it ?

**Comment by sirbiscuit** [comment]
You found an interesting "feature" of RDKit: the color that is used for DrawString depends on elements occurring in the molecule:

![image](https://user-images.githubusercontent.com/8418161/50692821-72645580-1035-11e9-9873-e30a398d66b2.png) ![image](https://user-images.githubusercontent.com/8418161/50692810-69738400-1035-11e9-8dc4-bc7edff27e2f.png)

I am not sure whether there is a solution for your problem using RDKit only. As a workaround, you could use a third-party library for adding text to a rendered molecule image. For example, svgutils does the job for SVG images:

```python
from rdkit import Chem
from IPython.display import SVG
from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D

mol = Chem.MolFromSmiles('c1cccnc1O')
rdDepictor.Compute2DCoords(mol)
drawer = rdMolDraw2D.MolDraw2DSVG(450, 150)
drawer.DrawMolecule(mol)
drawer.FinishDrawing()

# svg to text
s = drawer.GetDrawingText()
s = s.replace('svg:','')

# use svgutils to add text to svg
import svgutils.transform as sg
fig = sg.fromstring(s)
label = sg.TextElement(165, 81, "Awesome!", size=14, 
                       font='sans-serif', anchor='middle', color='#119933')
fig.append(label)
SVG(fig.to_str())
```

Result:
![image](https://user-images.githubusercontent.com/8418161/50690405-72605780-102d-11e9-9e37-449c406f0a3d.png)

I hope this helps!

**Comment by xg590** [comment]
> You found an interesting "feature" of RDKit: the color that is used for DrawString depends on elements occurring in the molecule:
> 
> ![image](https://user-images.githubusercontent.com/8418161/50692821-72645580-1035-11e9-9873-e30a398d66b2.png) ![image](https://user-images.githubusercontent.com/8418161/50692810-69738400-1035-11e9-8dc4-bc7edff27e2f.png)
> 
> I am not sure whether there is a solution for your problem using RDKit only. As a workaround, you could use a third-party library for adding text to a rendered molecule image. For example, svgutils does the job for SVG images:
> 
> ```python
> from rdkit import Chem
> from IPython.display import SVG
> from rdkit.Chem import rdDepictor
> from rdkit.Chem.Draw import rdMolDraw2D
> 
> mol = Chem.MolFromSmiles('c1cccnc1O')
> rdDepictor.Compute2DCoords(mol)
> drawer = rdMolDraw2D.MolDraw2DSVG(450, 150)
> drawer.DrawMolecule(mol)
> drawer.FinishDrawing()
> 
> # svg to text
> s = drawer.GetDrawingText()
> s = s.replace('svg:','')
> 
> # use svgutils to add text to svg
> import svgutils.transform as sg
> fig = sg.fromstring(s)
> label = sg.TextElement(165, 81, "Awesome!", size=14, 
>                        font='sans-serif', anchor='middle', color='#119933')
> fig.append(label)
> SVG(fig.to_str())
> ```
> 
> Result:
> ![image](https://user-images.githubusercontent.com/8418161/50690405-72605780-102d-11e9-9e37-449c406f0a3d.png)
> 
> I hope this helps!

You should add " s = s.replace(b'svg:', b'')  " before the last line "  SVG(fig.to_str())  "
