### ISSUE TITLE
Inconsistent treatment of `[as]` in SMILES and SMARTS

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2197]
**Description:**

Here's the reproducible showing the problem:
```
In [10]: Chem.MolToSmiles(Chem.MolFromSmiles('[as]1ccccc1'))
Out[10]: 'C1=CC=[As]C=C1'

In [11]: Chem.MolToSmarts(Chem.MolFromSmarts('[as]1ccccc1'))
Out[11]: '[a&s]1ccccc1'
```
These should at least be consistent with each other; probably it makes sense to go with the (probably) clear intent that `[as]` in a SMARTS means `[a&#33]`

When fixing this, should also check other inconsistencies

**Comment by sroughley** [comment]
Nice to see this one fixed - thanks Greg!
