### ISSUE TITLE
RDKit python on MacOS High Sierra from source

### ISSUE THREAD

**Issue by Szirenke** [rdkit/rdkit#2201]
I have compiled RDkit on a MacOS high sierra (10.13.6) from source. The compilation must have been succseful since I have no issue using the c++ libraries and my c++ code compiles and runs and all the provided c++ examples compiled and run. However when I try to use RDKit in a python script:

#!/usr/bin/env python
from __future__ import print_function
from rdkit import Chem
m2 = Chem.MolFromSmiles('C1CCC1')
print(Chem.MolToMolBlock(m2))     

then I get the following error:

Traceback (most recent call last):
  File "./test.py", line 4, in <module>
    from rdkit import Chem
  File "/Users/me/data/rdkit-master/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: dlopen(/Users/me/data/rdkit-master/rdkit/rdBase.so, 2): Library not loaded: @rpath/libRDKitRDBoost.1.dylib
  Referenced from: /Users/me/data/rdkit-master/rdkit/rdBase.so
  Reason: image not found

The $RDBASE is in the PYTHONPATH!

Does this mean the python wrappers have not been built?

Thanks!

**Comment by Szirenke** [comment]
using cmake version 3.13.2 on High Sierra (10.13.6) the pyhtontest fail the ctest:
          2 - pyCoordGen (Failed)
	  4 - testRDValue (Child aborted)
	  5 - testDataStructs (Child aborted)
	  6 - testFPB (Child aborted)
	  7 - testMultiFPB (Child aborted)
	  8 - pyBV (Failed)
	  9 - pyDiscreteValueVect (Failed)
	 10 - pySparseIntVect (Failed)
	 11 - pyFPB (Failed)
	 13 - testGrid (Child aborted)
	 14 - testPyGeometry (Failed)
	 17 - pyAlignment (Failed)
	 20 - testMMFFForceField (Child aborted)
	 21 - pyForceFieldConstraints (Failed)
	 23 - pyDistGeom (Failed)
	 27 - graphmolMolOpsTest (Child aborted)
	 29 - graphmoltestChirality (Child aborted)
	 30 - graphmoltestPickler (Child aborted)
	 33 - hanoiTest (Child aborted)
	 35 - resMolSupplierTest (Child aborted)
	 38 - graphmolTestsCatch (Failed)
	 39 - testDepictor (Child aborted)
	 40 - pyDepictor (Failed)
	 46 - fileParsersTest1 (Child aborted)
	 47 - testMolSupplier (Child aborted)
	 48 - testMolWriter (Child aborted)
	 49 - testTplParser (Child aborted)
	 50 - testMol2ToMol (Child aborted)
	 52 - testExtendedStereoParsing (Child aborted)
	 53 - fileParsersCatchTest (Failed)
	 54 - testSubstructMatch (Child aborted)
	 55 - testReaction (Child aborted)
	 59 - pyChemReactions (Failed)
	 60 - pyChemReactionEnumerations (Failed)
	 61 - pyChemReactionSanitize (Failed)
	 62 - testChemTransforms (Child aborted)
	 65 - filterCatalogTest (Child aborted)
	 66 - pyFilterCatalog (Failed)
	 67 - testFragCatalog (Child aborted)
	 68 - pyFragCatalog (Failed)
	 69 - testDescriptors (Child aborted)
	 70 - testAUTOCORR2D (Child aborted)
	 71 - testEEM (Child aborted)
	 72 - testPBF (Child aborted)
	 73 - testRDFcustom (Child aborted)
	 74 - testRDF (Child aborted)
	 75 - testMORSE (Child aborted)
	 76 - test3D (Child aborted)
	 77 - testWHIM (Child aborted)
	 78 - testGETAWAY (Child aborted)
	 79 - testAUTOCORR3D (Child aborted)
	 80 - pyMolDescriptors (Failed)
	 81 - pyMolDescriptors3D (Failed)
	 82 - testFingerprints (Child aborted)
	 83 - testFingerprintGenerators (Child aborted)
	 84 - pyTestGenerator (Failed)
	 86 - pyPartialCharges (Failed)
	 87 - testMolTransforms (Child aborted)
	 88 - pyMolTransforms (Failed)
	 89 - testMMFFForceFieldHelpers (Child aborted)
	 90 - testUFFForceFieldHelpers (Child aborted)
	 92 - pyForceFieldHelpers (Failed)
	 93 - testDistGeomHelpers (Child aborted)
	 94 - pyDistGeomHelpers (Failed)
	 95 - testMolAlign (Child aborted)
	 96 - pyMolAlign (Failed)
	 97 - testFeatures (Child aborted)
	 98 - pyChemicalFeatures (Failed)
	 99 - testShapeHelpers (Child aborted)
	100 - pyShapeHelpers (Failed)
	102 - pyMolCatalog (Failed)
	103 - moldraw2DTest1 (Child aborted)
	105 - pyMolDraw2D (Failed)
	107 - pyFMCS (Failed)
	110 - pyMolHash (Failed)
	112 - pyMMPA (Failed)
	113 - testStructChecker (Child aborted)
	114 - pyStructChecker (Failed)
	116 - pyReducedGraphs (Failed)
	117 - trajectoryTest (Child aborted)
	118 - substructLibraryTest (Child aborted)
	119 - pySubstructLibrary (Failed)
	121 - pyRGroupDecomposition (Failed)
	122 - molInterchangeTest1 (Child aborted)
	123 - pyMolInterchange (Failed)
	125 - pySLNParse (Failed)
	126 - pyGraphMolWrap (Failed)
	127 - pyTestConformerWrap (Failed)
	128 - pyTestTrajectory (Failed)
	129 - pyTestThreads (Failed)
	130 - molStandardizeTest (Child aborted)
	131 - molNormalizeTest (Child aborted)
	132 - molValidateTest (Child aborted)
	133 - molChargeTest (Child aborted)
	134 - molTautomerTest (Child aborted)
	135 - molStandardizeSmallTest (Child aborted)
	136 - molFragmentTest (Child aborted)
	137 - pyMolStandardize (Failed)
	140 - pyMatCalc (Failed)
	142 - pySimDivPickers (Failed)
	143 - pyRanker (Failed)
	145 - pyFeatures (Failed)
	146 - pythonTestDbCLI (Failed)
	147 - pythonTestDirML (Failed)
	148 - pythonTestDirDataStructs (Failed)
	149 - pythonTestDirDbase (Failed)
	150 - pythonTestDirSimDivFilters (Failed)
	151 - pythonTestDirVLib (Failed)
	152 - pythonTestDirChem (Failed)
	153 - pythonTestSping (Failed)

**Comment by bp-kelley** [comment]
This generally means you don’t have your dyld path configured properly.  I tend to use the anaconda on OS X which really helps with these issues.

**Comment by bp-kelley** [comment]
Here is the template we use in Conda

https://github.com/rdkit/conda-rdkit/blob/master/rdkit/build.sh

**Comment by Szirenke** [comment]
Thanks,

I will look into the DYDL paths because I really want to avoid using anaconda (another layer of python version hell)!

**Comment by thegodone** [comment]
Me too!

Envoyé de mon iPhone

**Comment by Szirenke** [comment]
@UnixJunkie I just upgraded to Mojave and trying out different set-ups for the DYLD_LIBRARY_PATH & PYTHONPATH but I have not found a good set-up yet. I am quite new to Macs and I have some problem understanding the @rpath buisness and even if I ues the install_name tool tohether with the otool I still get the above error. 

Any has a suggestion of how to set up the library path on Macs?
