### ISSUE TITLE
Feature Request: extend 3d conformation useBasicKnowledge to force chair\boat\twisted conformation for heterocycles 

### ISSUE THREAD

**Issue by shayakhmetov** [rdkit/rdkit#2204]
Is there any way to force a cycle, for example in `C1CCN(CCCC)CC1`, to be always in 3D chair conformation? Currently, different conformers have different conformations even after optimizing each conformer with UFF and\or MMFF optimization. 

I guess that `useBasicKnowledge` in conformer generation should be extended to include this option.

**Comment by YoavShamir5** [comment]
Is there a built-in way to do this? Thanks!
