### ISSUE TITLE
RDKit segfaults on macOS

### ISSUE THREAD

**Issue by ericmjl** [rdkit/rdkit#2207]
**Description:**

- RDKit Version:
```
$ python -c "import rdkit; rdkit.__version__"
Segmentation fault: 11
```

- Platform: macOS, anaconda Python, fresh environment.

Conda environment spec:
```
# packages in environment at /Users/ericmjl/anaconda/envs/rdkit_test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
boost                     1.68.0           py37h3e44d54_1    conda-forge
boost-cpp                 1.68.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              hc4e6be7_4  
certifi                   2018.11.29               py37_0  
fontconfig                2.13.0               h5d5b041_1  
freetype                  2.9.1                hb4e5f40_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
icu                       58.2                 h4b95b61_1  
intel-openmp              2019.1                      144  
jpeg                      9b                   he5867d9_2  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.35               ha441bb4_0  
libtiff                   4.0.9                hcb84e12_2  
libxml2                   2.9.8                hab757c2_1  
mkl                       2019.1                      144  
mkl_fft                   1.0.6            py37h27c97d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
ncurses                   6.1                  h0a44026_1  
numpy                     1.15.4           py37hacdab7b_0  
numpy-base                1.15.4           py37h6575580_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1a               h1de35cc_0  
pandas                    0.23.4           py37h6440ff4_0  
pcre                      8.42                 h378b8a2_0  
pillow                    5.3.0            py37hb68e598_0  
pip                       18.1                     py37_0  
pixman                    0.34.0               hca0a616_3  
pycairo                   1.18.0           py37ha54c0a8_0  
python                    3.7.2                haf84260_0  
python-dateutil           2.7.5                    py37_0  
pytz                      2018.7                   py37_0  
rdkit                     2018.09.1       py37hdb4e85a_1000    conda-forge
readline                  7.0                  h1de35cc_5  
setuptools                40.6.3                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.26.0               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
wheel                     0.32.3                   py37_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  
```

Code sample:

```
$ python -c "import rdkit; rdkit.__version__"
Segmentation fault: 11
```

It appears that segfault issues on macOS has been happening for quite a while now:

- https://github.com/rdkit/rdkit/issues/1649, late 2017
- https://github.com/rdkit/rdkit/issues/1617, early 2017

**Comment by bp-kelley** [comment]
The boost version is wrong ( we need to fix the recipe )

conda install boost=1.65.0

Should fix it.

**Comment by greglandrum** [comment]
This isn't a problem with the RDKit recipe. That's a conda-forge build.

@ericmjl there's not really anything we can do about this directly on the RDKit side since it's caused by the way the conda-forge build was done. There is a discussion of what I think is the same problem on the rdkit-feedstock tracker: https://github.com/conda-forge/rdkit-feedstock/issues/22
And it *might* be solved. Waiting for my test mac to finish updating so that I can try it out.

**Comment by greglandrum** [comment]
It looks like the problem is now solved. I just created a conda environment for python 3.7 and then installed the RDKit from conda-forge using `conda install conda-forge::rdkit`.
That seems to work:
```
(py37_rdkit) $ python -c 'import rdkit;from rdkit import Chem;print(rdkit.__version__)'
2018.09.1
```

And here's the environment:
```
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
boost                     1.68.0          py37h9888f84_1001    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.12.5                     0  
cairo                     1.16.0            h9247486_1000    conda-forge
certifi                   2018.11.29               py37_0  
fontconfig                2.13.1            h1e4e890_1000    conda-forge
freetype                  2.9.1                hb4e5f40_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.58.2            h2836805_1001    conda-forge
icu                       58.2                 h4b95b61_1  
intel-openmp              2019.1                      144  
jpeg                      9b                   he5867d9_2  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.36               ha441bb4_0  
libtiff                   4.0.10            hcb84e12_1001  
libxml2                   2.9.9                hab757c2_0  
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py37h5e564d8_0  
mkl_random                1.0.2            py37h27c97d8_0  
ncurses                   6.1                  h0a44026_1  
numpy                     1.15.4           py37hacdab7b_0  
numpy-base                1.15.4           py37h6575580_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1a               h1de35cc_0  
pandas                    0.23.4           py37h6440ff4_0  
pcre                      8.42                 h378b8a2_0  
pillow                    5.4.1            py37hb68e598_0  
pip                       18.1                     py37_0  
pixman                    0.34.0               hca0a616_3  
pycairo                   1.18.0           py37ha54c0a8_0  
python                    3.7.2                haf84260_0  
python-dateutil           2.7.5                    py37_0  
pytz                      2018.9                   py37_0  
rdkit                     2018.09.1       py37h4e14f70_1001    conda-forge
readline                  7.0                  h1de35cc_5  
setuptools                40.6.3                   py37_0  
six                       1.12.0                   py37_0  
sqlite                    3.26.0               ha441bb4_0  
tk                        8.6.8                ha441bb4_0  
wheel                     0.32.3                   py37_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by ericmjl** [comment]
@greglandrum thank you for getting back! 

Just wondering about future release channels for rdkit: are you all planning to move to conda-forge/rdkit, or will you be maintaining your own rdkit/rdkit version too?

I am hoping to encourage more package devs who release conda-installable packages to move to conda-forge where possible, as that is where the PyData community is heading. I myself have committed to releasing my own Python packages (admittedly less complex than rdkit) via pip, with conda-forge being auto-updated from pip releases. Not having to maintain my own ericmjl/pyjanitor or ericmjl/nxviz channel, while also benefiting from the conda-forge auto-updating bot capabilities, has been pretty awesome!

**Comment by ericmjl** [comment]
As a side note, I also can confirm that conda-forge RDKit works! :smile: :smile: :smile:

**Comment by greglandrum** [comment]
Yeah, conda-forge is awesome and an amazing service to the community. It can, however, be pretty heavyweight if you don't know about doing `conda install conda-forge::rdkit` instead of `conda install -c conda-forge rdkit` and can sometimes lead to a bit of dependency hell with projects that *aren't* in conda-forge.

We discussed what to do here briefly on the mailing list a while ago and decided that we need to keep the rdkit channel alive for testing purposes and to make sure that there's an option for people who don't want to (or can't) switch over to conda-forge.

I should update the RDKit documentation to suggest installation via the conda-forge channel before the rdkit channel.

**Comment by mcs07** [comment]
On a related note, conda-forge has finally done the big compiler migration to match the `defaults` compilers. So mixing `defaults` and `conda-forge` packages is much safer, and `conda install conda-forge::rdkit` works more reliably. You can tell if you are using a `conda-forge` package built with the new compilers if it has a build number 1000+, which you can see in Greg's `conda list` output above.

**Comment by ericmjl** [comment]
@mcs07 @greglandrum thanks for your responses! Understood about the rdkit channel.

I had noticed that there were two installation syntaxes that both of you alluded to.

One was this:

```
conda install conda-forge::rdkit
```

The other was this:

```
conda install -c conda-forge rdkit
```

The first one is foreign to me: when was this introduced? Is there documentation on this syntax? As far as I can remember, the `-c` flag has been the only way I've known to specify a channel for a package.

**Comment by greglandrum** [comment]
I don't remember who introduced me to the `conda-forge::rdkit` syntax (was it you @mcs07?) and I have never been able to find documentation for it, but I think of it as "install the bare minimum required, but don't move everything to conda-forge". That may be wrong. :-)
Now that conda-forge is using the defaults compilers, this should be less critical.

**Comment by mcs07** [comment]
Not sure where I first saw the double-colon notation, maybe from @pstjohn. I just looked for some documentation now, and couldn't find much. It seems to be part of the "MatchSpec package query language".  These conda 4.4 release notes have some info: https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/

> Conda has a built-in query language for searching for and matching packages, what we often refer to as MatchSpec. The MatchSpec is what users input on the command line when they specify packages for create, install, update, and remove operations. ... We have also substantially enhanced our MatchSpec query language.
> For example,
>
> conda install conda-forge::python
>
> is now a valid command, which specifies that regardless of the active list of channel priorities, the python package itself should come from the conda-forge channel. ... The canonical string form for a MatchSpec is thus
>
>(channel::)name(version(build_string))
>
> environments track user-requested state: Building on our enhanced MatchSpec query language, conda environments now also track and differentiate (a) packages added to an environment because of an explicit user request from (b) packages brought into an environment to satisfy dependencies. For example, executing
>
>conda install conda-forge::scikit-learn
>
> will confine all future changes to the scikit-learn package in the environment to the conda-forge channel, until the spec is changed again. A subsequent command conda install scikit-learn=0.18 would drop the conda-forge channel restriction from the package. And in this case, scikit-learn is the only user-defined spec, so the solver chooses dependencies from all configured channels and all available versions.

So essentially I think you are pinning only `rdkit` specifically to the `conda-forge` channel, but all other dependencies continue to be resolved using the regular channel priority order in `.condarc`, which may just be the `defaults` channel.

**Comment by rasbt** [comment]
Also getting the segfaults on macOS Catalina when installing it via

    conda install -c conda-forge rdkit

in my default env.

However, when I installed it in a new env, i.e., 

    conda create -c rdkit -n my-rdkit-env rdkit
    conda activate my-rdkit-env
    conda install -c conda-forge rdkit

it works just fine. I suppose there's something in my default env that causes that issue. So for those who have problems, maybe try creating a fresh env for the installation.

**Comment by bp-kelley** [comment]
In my experience it is usually conflicting boost libraries.

----
Brian Kelley

**Comment by jamesmkrieger** [comment]
@rasbt, the answer is in there. I solved it by using the rdkit channel for installing rdkit in my main environment:

```
conda remove rdkit
conda install -c rdkit rdkit
```

This then installs the boost libraries it needs:
```
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /anaconda3

  added / updated specs:
    - rdkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    py-boost-1.67.0            |   py37h6440ff4_4         317 KB
    rdkit-2020.03.3.0          |   py37h65625ec_1        23.1 MB  rdkit
    ------------------------------------------------------------
                                           Total:        23.4 MB

The following NEW packages will be INSTALLED:

  libboost           pkgs/main/osx-64::libboost-1.67.0-hebc422b_4
  py-boost           pkgs/main/osx-64::py-boost-1.67.0-py37h6440ff4_4
  rdkit              rdkit/osx-64::rdkit-2020.03.3.0-py37h65625ec_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
py-boost-1.67.0      | 317 KB    | ######################################################################################### | 100% 
rdkit-2020.03.3.0    | 23.1 MB   | ######################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by rasbt** [comment]
@jamesmkrieger Thanks. That's what I tried at first. I think it didn't work because I already had the boost libraries installed in my main environment (probably was needed by another package that I installed some time ago)

**Comment by jamesmkrieger** [comment]
ok. Maybe you could remove boost then install rdkit from its channel then update the other package that needs boost and see if it integrates better.

**Comment by ericmjl** [comment]
@rasbt are you using isolated environments? I know it’s a bit more work and possibly a bit more hassle, but it might be helpful maybe?

**Comment by jamesmkrieger** [comment]
@ericmjl that doesn't help when we want to use multiple tools together. That said it is helpful for troubleshooting.
