### ISSUE TITLE
testEnumeration hangs/takes where long on 32bit architectures

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#2209]
**Description:**

The test case `testEnumeration` hangs and/or takes a long time (hours) on 32bit machines, see e.g. https://buildd.debian.org/status/logs.php?pkg=rdkit&ver=201709.3%2Bdfsg-1 for 201709.3, which has the same issue. All of Debian's 32bit architectures are red.

I stepped through `testEnumeration` and it seems to take a long time in `RDKit::EvenSamplePairsStrategy::initializeStrategy`, via `testEvenSamplers` and `RDKit::EnumerationStrategyBase::initialize`.

I guess `nmonomers` is 16500 from looking at `m_permutationSizes[0,1,2]`, but the value is optimized out.

Anyway the loop in `./Code/GraphMol/ChemReactions/Enumerate/EvenSamplePairs.cpp` lines 56-59 takes about 5 seconds per `std::fill(pair_used[i].begin(), pair_used[i].end(), 0);` on my Thinkpad T470, so would take an estimated 22 hours if my calculations of `nmomnomers` is correct. I have not investigated yet how this behaves on 64bit, but that whole testcase finished in 13.5 seconds in https://buildd.debian.org/status/fetch.php?pkg=rdkit&arch=amd64&ver=201709.3%2Bdfsg-1%2Bb1&stamp=1542478341&raw=0 so there clearly must be something different there.
 

- RDKit Version: 201803.4
- Platform: Linux ia32

**Comment by greglandrum** [comment]
Would it be a problem for the Debian builds if we decide that supporting legacy 32 bit architectures is not a priority? Could they be marked as “do not build” or something?

**Comment by mbanck** [comment]
Can do but is that really the case? I don't think every ARM computer will be 64bit in the near future, and somebody might want to run rdkit on them? 201603.5 still built fine on i386 (https://buildd.debian.org/status/logs.php?pkg=rdkit&arch=i386) so this is apparently a regression and not something that never worked.

**Comment by greglandrum** [comment]
The older builds may have worked because the enumeration code is a relatively new feature (on my phone at the moment, so it’s work to do the research there). I will take a look at fixing it, but building in code complication to support 32 bit architectures isn’t likely to be a high priority.

**Comment by mbanck** [comment]
I've disabled that test now so that I can get a Debian package built, but it would be nice if the test would work.

**Comment by bp-kelley** [comment]
I expect we can make it work, but it will take me a bit.

**Comment by bp-kelley** [comment]
The EvenSampler overflows internally on 32bit which causes issues :)  We have two options, (1) make the test not overflow as a stop-gap and (2) fix the overflow issue.
