### ISSUE TITLE
Look into pybind11

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2214]
**Description:**

Boost::python is quite heavyweight and introduces runtime installation requirements that it would be nice not to have. Pybind11 (https://github.com/pybind/pybind11) seems to be mature/maturing is worth considering as a possible alternative.

Actually switching would be a "non-trivial" amount of work.

**Comment by rmrmg** [comment]
After 4 years is there any plans for migration to pybind11?

**Comment by greglandrum** [comment]
Nothing concrete. I wouldn't mind moving off Boost Python since I'm not convinced that it's got a long-term future, but migrating would be a massive amount of work.
Some additional concerns:
- It looks like the runtime performance of pybind11 vs boost may not be great (https://nanobind.readthedocs.io/en/latest/benchmark.html)
- I'm not sure how to interpret this fork: https://github.com/google/pywrapcc

But really the major barrier is the amount of effort it would require.
