### ISSUE TITLE
Bug in C# Wrapper RDKit.Initialize()

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#2222]
**Description:**

- RDKit Version: RDKit2DotNet.2017.9.1-alpha1
- Platform: Windows

I am trying to use the C# wrapper from a VSTO Excel COM add-in. I include the RDKit2DotNet NUGet package and compile without issue. When run, a NullObject exception is thrown by RDKit.Initialize(). Looking at the code it appears that the problem is that RDKit.Initialize() makes a call to Assembly.GetEntryAssembly(), which returns NULL and results in the NULLObject exception. I believe it is expected behavior that GetEntryAssembly() returns NULL in some cases and so this should be more gracefully handled. The code should make a subsequent call to GetCallingAssembly() or GetExecutingAssembly() in cases where GetEntryAssembly() returns NULL.

```
    public static void Initialize()
    {
      if (!RDKit.SetDllDirectory(Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), IntPtr.Size == 8 ? "x64" : "x86")))
        throw new Win32Exception();
    }
```

**Comment by bp-kelley** [comment]
This function was designed to work with managed code, so we didn't explicitly check for this.

I expect if we can't find the Assembly location, in practice RDKit won't know where the dlls are.  Some functions will work ( I was too aggressive with packing the dlls ) but I expect some won't.

Since this is the only thing Initialize does, what happens when you *don't* call it.

You may still have to call the SetDllDirectory though to the appropriate location though.

**Comment by paconius** [comment]
Hi, I called all three from the Intermediate Window of the Debugger and got the following results:
GetEntryAssembly -> Nothing (NULL)
GetCallingAssembly -> points to my .dll
ExecutingAssembly -> points to my .dll

Both of the later calls pointed to the same assembly.

Thanks.

**Comment by bp-kelley** [comment]
When you say "your .dll" I'm assuming that

```
Assembly.GetCallingAssembly().Location
```

Points to the dll from the installed nuget package.  I could be a bit more pedantic and search for the x64 and/or x86 directories as well.  I'll see if I can make these changes in the next few days.

**Comment by paconius** [comment]
Yes, when I say "my .dll" I was referring to the fact that Assembly.GetCallingAssembly().Location points to the .dll containing my VSTO COM add-in which is calling RDKit.Initialize(). This dll should live in the same folder as the other assemblies from the project (which contains the x86 and x64 subdirectories).

**Comment by bp-kelley** [comment]
This is being fixed in the rdkit-csharp build repo:  https://github.com/bp-kelley/rdkit-csharp.git

When I have a beta I'll up load it to nuget and you can test it.
