### ISSUE TITLE
incorrect EEM charges for ionic compounds

### ISSUE THREAD

**Issue by rmrmg** [rdkit/rdkit#2232]
I have newest rdkit installed thru conda . For ionic compounds overall EEM charges for molecule has opposite sign that molecule itself, ie: Sum(AtmCharges) = -(moleculeCharge). Minimal code and examples below:

Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
>>> rdkit.__version__
'2018.09.1' 
>>> def getEEM(smi):
...       mol=Chem.MolFromSmiles(smi)
...       mol=Chem.AddHs(mol)
...       AllChem.EmbedMolecule(mol)
...       AllChem.MMFFOptimizeMolecule(mol)
...       ch=AllChem.CalcEEMcharges(mol)
...       return {'sum':sum(ch), 'charges':ch}

>>> getEEM('CC[NH3+]')
{'charges': [-0.6381553081841209, -0.22090152029881335, -0.8564473593044781, 0.08134597892268643, 0.08134570560801523, 0.06179027753406128, 0.031123837051455824, 0.03112384293919871, 0.14960869814654104, 0.12955704064162357, 0.1496088069438307], 'sum': -0.9999999999999999}

>>> getEEM('[B-](F)(F)(F)F')
{'charges': [-10.385293669856887, 2.860032065705684, 2.822324250065206, 2.867156652126143, 2.8357807019598544], 'sum': 1.0}
by the way the values are rather too high

**Comment by thegodone** [comment]
Not really 

Envoyé de mon iPhone

**Comment by thegodone** [comment]
In fact it’s related to the other bug I guess 

Envoyé de mon iPhone

**Comment by thegodone** [comment]
issue 1: B is not part of the atoms that have been optimized
which are only H 1, C 6, N 7, O 8, F 9, P 15, S 16, Cl 17, Br 35 
same bug reported last time need to fix this
issue 2: we have an issue with the sign that's true need to make a testcase and check equation for charge
