### ISSUE TITLE
rdkit.Chem.Draw.rdMolDraw2D.MolDraw2D does not support setLineWidth

### ISSUE THREAD

**Issue by felixekn** [rdkit/rdkit#2251]
**Description:**
`rdkit.Chem.Draw.rdMolDraw2D.MolDraw2D` does not support `setLineWidth` even though the [documentation](https://www.rdkit.org/docs/source/rdkit.Chem.Draw.rdMolDraw2D.html?highlight=rdmoldraw2d#module-rdkit.Chem.Draw.rdMolDraw2D) claims it does.
It currently only supports: `FontSize`, `GetDrawCoords`, `Height`, `Offset`, `SetFontSize`, `SetOffset`, `SetScale`, and `Width`. It does not support `LineWidth` and `SetLineWidth`.

**Package and system versions:**
RDKit version 2018.03.3 
Anaconda2.7 version 4.6.1
MacOS 10.14.3

**Code that replicates bug:**
```
from rdkit.Chem import Draw
print(dir(Draw.rdMolDraw2D.MolDraw2D)) # <-- prints list of available functions and options

drawer = Draw.rdMolDraw2D.MolDraw2DCairo(500,500) # setting up .png chemical structure figure
drawer.setFontSize(1) # <-- works as expected: atom label fontsize changes
drawer.setLineWidth(2.5) # <-- does not work: code errors out
```

**Comment by greglandrum** [comment]
I think you have a typo in your sample code; the methods are called `SetFontSize()` and `SetLineWidth()`.

The error that I get when calling `SetLineWidth()` actually explains what the problem is, though it it is somewhat cryptic:
```
In [6]: drawer.SetLineWidth(2.5)                                                                                                         
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-6-21a1b9ecf090> in <module>
----> 1 drawer.SetLineWidth(2.5)

ArgumentError: Python argument types in
    None.SetLineWidth(MolDraw2DCairo, float)
did not match C++ signature:
    SetLineWidth(RDKit::MolDraw2D {lvalue}, int)
```
This is saying that I've called `SetLineWidth()` with a float for an argument, but it's expecting an integer. If I change 2.5 to 2 everything works fine:
```
In [7]: drawer.SetLineWidth(2)                                                                                                           

In [8]:  
```
