### ISSUE TITLE
Wrong Chirality due to bad CIP ranking for cycles

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#2252]
- RDKit Version: 2019.03.1dev1 (current master, commit 4d14a81)
- Platform: built with conda on linux x64.

When importing the attached SDF file (just trim the ".txt" extension at the end) using the code below, the resulting output is:
```
S
[(0, '6'), (2, '4'), (5, '3')]
```
This means that C atom with index 5 (part of a 4 member ring) gets a lower ranking that C atom 2 (part of the 3 member ring).

Shouldn't C-5 be ranked higher than C-2?

---

**Sample SDF file:** [rdkit_bad_CIP_ranking.sdf.txt](https://github.com/rdkit/rdkit/files/2823200/rdkit_bad_CIP_ranking.sdf.txt)

**Import code:**
```
from rdkit import Chem
mol = Chem.MolFromMolFile("rdkit_bad_CIP_ranking.sdf")
Chem.AssignStereochemistryFrom3D(mol)
chiral_atom = mol.GetAtomWithIdx(1)
neighbors_ranks = ((at.GetIdx(), at.GetProp('_CIPRank')) for at in chiral_atom.GetNeighbors())
cip_sorted_neighbors = sorted(neighbors_ranks, key=lambda x: -int(x[1]))

print(chiral_atom.GetProp("_CIPCode"))
print(cip_sorted_neighbors)

```

**Comment by greglandrum** [comment]
Here's a shorter reproducible for this:
```
In [1]: from rdkit import Chem                                                                                     

In [2]: m = Chem.MolFromSmiles('N[C@H](C1CC1)C1CCC1')                                                              

In [3]: Chem.FindMolChiralCenters(m)                                                                               
Out[3]: [(1, 'S')]
```
Marvin agrees with you that this should be `R`

**Comment by greglandrum** [comment]
Though this is clearly a bug, due to the way the current algorithm works it may not be a fixable one.
