### ISSUE TITLE
Specifying a hydrogen bond with electronegative atoms

### ISSUE THREAD

**Issue by uditgupta0912** [rdkit/rdkit#2274]
I am wondering if a hydrogen bond can be specified between molecules. For e.g., if I have water molecules, a hydrogen bond exists between a hydrogen atom of one molecule and oxygen of another molecule. Is there a way in rdkit to specify such a bond?

My rdkit version is 2018.03.2

**Comment by greglandrum** [comment]
The RDKit does support a "HYDROGEN" bond type, but there's currently not really any way to do anything with that bond once it exists. Given that V3000 mol files do support hydrogen bonds, we could theoretically add support for reading and writing them that way.

What would you want to do with the molecules containing H bonds once you have them?

**Comment by uditgupta0912** [comment]
I am interested in using this for heterogeneous reactions where I have a bronsted acid site and ethanol. I want to show an interaction between the slightly electropositive hydrogen and the electronegative oxygen atom.  

`RdkitMol_r1 = Chem.Mol()
RdkitMol_r1 = Chem.RWMol(RdkitMol_r1)
a1 = Chem.Atom(np.int(8))
a1.SetNoImplicit(True)
a1i = RdkitMol_r1.AddAtom(a1)
print(a1i)
h1 = Chem.Atom(np.int(1))
h1.SetNoImplicit(True)
h1i = RdkitMol_r1.AddAtom(h1)
print(h1i)
RdkitMol_r1.AddBond(a1i, h1i,order=Chem.rdchem.BondType.HYDROGEN)
smi1 = Chem.MolToSmiles(RdkitMol_r1)
print(smi1)`

I tried using the above code as a starter to add a hydrogen bond between an O and H atom but I got the following error:

`RuntimeError: Incomplete Code
	This routine is still under development
	Violation occurred on line 235 in file Code\GraphMol\Bond.cpp
	Failed Expression: Bad bond type
	RDKIT: 2018.03.2
	BOOST: 1_66`

Is anything wrong with my implementation of the hydrogen bond?

**Comment by greglandrum** [comment]
An aside: if you want to quote multiple lines of code, enclose it in triple back quotes: \`\`\`
I just updated your previous comment to make it readable

**Comment by greglandrum** [comment]
By "show an interaction", do you mean show a drawing of the molecule(s) with the H bond indicated?

**Comment by uditgupta0912** [comment]
Ultimately I want to represent it as a reaction, so basically generating a SMILES string for the structure and then viewing it in ChemDraw.

**Comment by uditgupta0912** [comment]
![hydrogenbondreaction](https://user-images.githubusercontent.com/20133044/52799685-57c7c800-3048-11e9-94f3-ccf24d977e19.PNG)
I have added an image of what I am looking for.

**Comment by greglandrum** [comment]
There's not a great solution to this at the moment. I can take a look into making it a bit more functional, but I'm not sure when that will happen

**Comment by uditgupta0912** [comment]
Thanks, Greg, I will try and work around bond order = ZERO. I think it does the work.
