### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit.Contrib'

### ISSUE THREAD

**Issue by sayred1** [rdkit/rdkit#2279]
**Description:**
I installed rdkit using conda and can activate my environment just fine.

- RDKit Version: 2018.09.1
- Platform: MacOS

I am attempting to run already existing code that makes use of the contrib module, however, the import below won't work for me. I get the following error:
ModuleNotFoundError: No module named 'rdkit.Contrib'

```
import rdkit
from rdkit.Contrib.SA_Score.sascorer import calculateScore
```

**Comment by iwatobipen** [comment]
Hi Dean,

I think rdkit can not load Contrib directly, so I should append the path to
sys.path.
Example is below.

from rdkit import Chem
from rdkit.Chem import RDConfig
import os
import sys
sys.path.append(os.path.join(RDConfig.RDContribDir, 'SA_Score'))
# now you can import sascore!
import sascorer
mol = Chem.MolFromSmiles('NC(=O)c1ccccc1')
s = sascorer.calculateScore(mol)
s
> Out[12]: 1.1592175456870955

I will be happy if the code will help you.
Kind regards,

Taka

2019年2月17日(日) 4:39 Dean Lewis Sayre Jr. <notifications@github.com>:

**Comment by sayred1** [comment]
@iwatobipen worked like a charm! I am curious about something though. Why can't one directly import Contrib ('from rdkit import Contrib') as Chem is imported ('from rdkit import Chem')?

**Comment by iwatobipen** [comment]
That sounds good! Thank you for your prompt reply.
From readme of rdkit, Contrib folder with useful community-contributed
software harnessing the power of the RDKit.
So I think the folder is just contribution of rdkit and not main class of
rdkit.

2019年2月17日(日) 9:29 Dean Lewis Sayre Jr. <notifications@github.com>:

**Comment by greglandrum** [comment]
@iwatobipen is completely right here. The contrib modules aren’t generally as well tested and aren’t “supported” per se, so they aren’t automatically made available on PYTHONPATH

**Comment by sayred1** [comment]
@iwatobipen @greglandrum, thank you both for your quick help, cheers!

**Comment by wholeexperts** [comment]
Thank you . The answer helped me to solve the problem.
