### ISSUE TITLE
error LNK2001: unresolved external symbol

### ISSUE THREAD

**Issue by DongqiangHe** [rdkit/rdkit#2287]
**Description:**

- RDKit Version: 20180901
- Platform: Windows10 64

I installed rdkit on windows, and I tried to use it in my VS2015 C++ project, I had included the .lib file.  But  I always got errors like this:

error LNK2001: unresolved external symbol "private: void __cdecl RDKit::ROMol::initMol(void)" (?initMol@ROMol@RDKit@@AEAAXXZ)

```
Your code sample here
```

**Comment by DongqiangHe** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <GraphMol/RDKitBase.h>
#include <GraphMol/MolOps.h>
#include <GraphMol/ROMol.h>
#include <iostream>
#include <boost\lambda\lambda.hpp>

//#define Atom RDKit::Atom
//#define Bond RDKit::Bond
//#define Mol RDKit::RWMol

int main() {

	RDKit::Atom *atom = new RDKit::Atom("C"); //ok. 
        RDKit::Bond *bond = new RDKit::Atom(); //ok
	//RDKit::RWMol *mol = new RDKit::RWMol(); //error 
	
	atom->getMass();

	std::cout << atom->getSymbol() << std::endl;

	system("PAUSE");

	return 0;
}
This is my test code.  Atom and Bond Class is OK, but when use other class like RWMol, I got this error message. I don't konw why . These classes are all in GraphMol.lib, I add it to  additional dependencies. why would this error be caused? Thanks

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "private: void __cdecl RDKit::ROMol::initMol(void)" (?initMol@ROMol@RDKit@@AEAAXXZ)	TestRDKit2	D:\RDKit\TestRDkit\TestRDKit2\main.obj	1

**Comment by greglandrum** [comment]
Hi,
The github issue tracker is not going to be a good place to resolve this.
Please subscribe to the rdkit-discuss mailing list and ask your question there.
When you do so, please include the actual code you tried to work with (the example above is full of basic syntax errors and would never compile).

**Comment by DongqiangHe** [comment]
@greglandrum thanks for you help, I had found the reason from rdkit-discuss mailing list.
