### ISSUE TITLE
Question about FindMCS

### ISSUE THREAD

**Issue by uditgupta0912** [rdkit/rdkit#2288]
**Trying to identify maximum common structure between two molecules.**

- RDKit Version: 2018.03.2

I am trying to find the common substructure within two SMILES strings. I have included the code that I am trying to run.

```
mol1 = Chem.MolFromSmiles('[H]C([H])([H])[H]')
mol2 = Chem.MolFromSmiles('[H][C]([H])([H])~[Pt]')
mols = [mol1, mol2]
res = rdFMCS.FindMCS(mols)
```
I do not get any matches even though 'C(H)(H)(H)' is a common substructure. Do I have to sanitize or cleanup the structures before doing MCS function?

**Comment by uditgupta0912** [comment]
Also, another question is whether FindMCS only looks for non-heavy atoms? So if 
'''
mol1 = Chem.MolFromSmiles('[H][H]')
mol2 = Chem.MolFromSmiles('[H]~[Pt]')
mols = [mol1, mol2]
res = rdFMCS.FindMCS(mols) 
'''
Would the above give a common substructure of [H]?

**Comment by greglandrum** [comment]
By default the RDKit removes Hs from molecules when you read them in. If you want to keep the Hs when reading from SMILES, you need to request that:
```
In [3]: ps = Chem.SmilesParserParams()

In [4]: ps.removeHs = False

In [5]: m = Chem.MolFromSmiles('[H]C([H])([H])F',ps)

In [6]: Chem.MolToSmiles(m)
Out[6]: '[H]C([H])([H])F'
```
Here's what that yields for your first example:
```
In [15]: mol1 = Chem.MolFromSmiles('[H]C([H])([H])[H]',ps)
    ...: mol2 = Chem.MolFromSmiles('[H][C]([H])([H])~[Pt]',ps)
    ...: mols = [mol1, mol2]
    ...: res = rdFMCS.FindMCS(mols)

In [16]: res.smartsString
Out[16]: '[#1]-[#6](-[#1])-[#1]'
```

The second example won't return an MCS because the algorithm requires that at least one bond be present. So single-atom MCSs are not found:
```
In [17]: m1 = Chem.MolFromSmiles('CC')

In [18]: m2 = Chem.MolFromSmiles('C')

In [19]: rdFMCS.FindMCS((m1,m2)).smartsString
Out[19]: ''
```

**Comment by uditgupta0912** [comment]
Thank you, Greg.  

For the single-atom MCS, a crude way of checking would be to go over each atom and check if that atom exists in the other molecule.

Once I have the MCS, should I follow with a GetSubstructureMatch to get atom and bond indices that are common?

**Comment by greglandrum** [comment]
Yes, you convert the smartsString into a molecule and then use that to query:
```
In [7]: p = Chem.MolFromSmarts(res.smartsString)

In [9]: mol1.GetSubstructMatches(p)
Out[9]: ((0, 1, 2, 3), (0, 1, 2, 4), (0, 1, 3, 4), (2, 1, 3, 4))
```
