### ISSUE TITLE
Unable to convert SMILES to Molecule objects

### ISSUE THREAD

**Issue by vmarkovnikov** [rdkit/rdkit#2289]
**Unable to convert SMILES to Molecule object**

- RDKit Version: 2019.03.1dev1
- Platform: macOS

I have set of molecules in SMILES format. I know that molecules are right and exists (also have known PubChem IDs), but unable to convert it to RDKit Molecule objects. What I am doing wrong?

```
from rdkit import Chem

mols = [
    'C(c1ccccc1)N(C)(C)C', # 5964
    'C(=O)(c1ccccc1)N(C)(C)C', # 406960
    'C(c1c(C)cc(C)cc1C)N(C)(C)C', # 406961
    'N(CCC)(CCC)(CCC)Cc1ccccc1', # 406963
    'C(c1ccccc1)N(C)(C)Cc2ccccc2', # 101570
    'C(c1ccc(cc1)[N+](=O)[O-])N(C)(C)C', # 406966
    'C(c1cccc(c1)[N+](=O)[O-])N(C)(C)C', # 406967
    'C(c1c(C)cc(C)c(C)c1C)N(C)(C)C', # 406968
]

for smiles in mols:
    mol = Chem.MolFromSmiles(smiles)
```

Gets following output:
[19:48:09] Explicit valence for atom # 7 N, 4, is greater than permitted
[19:48:09] Explicit valence for atom # 8 N, 4, is greater than permitted
[19:48:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[19:48:09] Explicit valence for atom # 0 N, 4, is greater than permitted
[19:48:09] Explicit valence for atom # 7 N, 4, is greater than permitted
[19:48:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[19:48:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[19:48:09] Explicit valence for atom # 11 N, 4, is greater than permitted

**Comment by greglandrum** [comment]
The error messages are pretty explicit about the problem: there's are neutral four-coordinate N atoms (which is something you don't see in real molecules).
What do you expect to happen?

**Comment by vmarkovnikov** [comment]
I want is to work with these molecules, for example convert to InChI or split this molecules into R-groups.

**Comment by greglandrum** [comment]
But the molecules, at least in the form that you currently have them, are not chemically reasonable. For what it's worth, the SMILES you provide above do not match what the PubChem compound page shows. For example: https://pubchem.ncbi.nlm.nih.gov/compound/406968#section=Canonical-SMILES 
There you'll see that the four-coordinate N has a positive charge; that is processed by the RDKit without complaint.

**Comment by vmarkovnikov** [comment]
Thank you, @greglandrum!

**Comment by rirai1973** [comment]
I have met the same problem, can any body help me ?
I got SMILES from pubchem 
cid=20035775,SMILES: CCN[Cl-]S(=O)(=O)O,  
cid= 20035797,SMILES: CC1=CC=C(C=C1)N[Cl-]S(=O)(=O)O
and I use Chem.MolFromSmiles() to change SMILES to Molecule, 
there are error like below:
Explicit valence for atom # 3 Cl, 3, is greater than permitted.

**Comment by greglandrum** [comment]
@rirai1973 the same answer I gave above applies here: the structure are not chemically correct and the RDKit is telling you exactly what the problem is.

**Comment by rirai1973** [comment]
Thank you, @greglandrum!
but the SMILES :CCN[Cl-]S(=O)(=O)O  is directly from pubchem,  so do you think Pubchem's SMILES is incorrect, so how should it be corrected? 
Thank you again.
