### ISSUE TITLE
how to confirm whether one bond is in ring (or whether two atoms  are in the same ring)

### ISSUE THREAD

**Issue by wangzihao6255** [rdkit/rdkit#2294]
I tried to confirm whether one bond is in ring with rdkit, however I didnot find that which function can achieve my goal.
Another way is to identify whether two atoms connected by the bond are in the same ring, I thought it could be done but it is really tough.

I'm new in rdkit and not familiar with all the functions.
Is there a function in rdkit can easily achieve my purpose? Or some relatively complex methods can?

Thanks a lot :)

**Comment by UnixJunkie** [comment]
http://www.rdkit.org/docs-beta/api/rdkit.Chem.rdchem.Bond-class.html
has an IsInRing method.
If that answers your question, then you can close this issue.

**Comment by wangzihao6255** [comment]
Thank you for the assistance!

**Comment by wangzihao6255** [comment]
sasas

**Comment by wangzihao6255** [comment]
dsdsa
