### ISSUE TITLE
atom index

### ISSUE THREAD

**Issue by xiaohongniua** [rdkit/rdkit#2296]
are there some way to change the atom index?
it seems that rdkit.Chem.MolFromSmiles assigns atom index by the sequence of smiles str,
e.g. NCO,the N is 0,C is 1and O is 2,what should I do if I want to get N:2,C:0,O:1?

**Comment by jasondbiggs** [comment]
On Wed, Feb 27, 2019 at 4:11 AM Hong <notifications@github.com> wrote:

> are there some way to change the atom index?
> it seems that rdkit.Chem.MolFromSmiles assigns atom index by the sequence
> of smiles str,
> e.g. NCO,the N is 0,C is 1and O is 2,what should I do if I want to get
> N:2,C:0,O:1?
>
You can use the RenumberAtoms method:
http://rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.RenumberAtoms

**Comment by xiaohongniua** [comment]
Thanks a lot!
