### ISSUE TITLE
libboost-python doesn't appear linked : LD_PRELOAD required

### ISSUE THREAD

**Issue by PhilipDeegan** [rdkit/rdkit#2313]
Here there folks

I'm very new to this tool, and I tried to give this a while

```
cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m    -DRDK_BUILD_AVALON_SUPPORT=ON   -DRDK_BUILD_CAIRO_SUPPORT=ON   -DRDK_BUILD_INCHI_SUPPORT=ON -DPYTHON_NUMPY_INCLUDE_PATH=/home/philix/.local/lib/python3.6/site-packages/numpy/core/include  -D RDK_BUILD_AVALON_SUPPORT=ON -D RDK_BUILD_INCHI_SUPPORT=ON -DRDK_BUILD_THREADSAFE_SSS=on -DRDK_TEST_MULTITHREADED=on -DRDK_INSTALL_STATIC_LIBS=ON -DRDK_BUILD_SWIG_WRAPPERS=OFF -DRDK_SWIG_STATIC=OFF -DRDK_BUILD_PYTHON_WRAPPERS=ON -DRDK_BUILD_FREESASA_SUPPORT=ON ..
```

make install doesn't appear to set things in a system directory, I'm guessing this is intentional, not quite convention but w/e I guess

Now to use the python code I have to do something like this 

```
LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libpython3.6m.so /usr/lib/x86_64-linux-gnu/libboost_python3.so" LD_LIBRARY_PATH=$PWD/lib python3 run.py 
```

Is there a better way?

**Comment by e-kwsm** [comment]
Add `LD_LIBRARY_PATH=rdkit_install_location/lib:$LD_LIBRARY_PATH` to e.g. `~/.bashrc` (https://github.com/rdkit/rdkit/blob/ba7bd316f9f5d1c2ba815e39f5558b1b48e5d55b/Docs/Book/Install.md#building-the-rdkit).

**Comment by Dekken** [comment]
I think the problem is bigger than that.

LD_LIBRARY_PATH implies the library was linked,

by needing LD_PRELOAD this would suggest that it wasn't.
