### ISSUE TITLE
Method-chain-able construction of fingerprints from a pandas dataframe.

### ISSUE THREAD

**Issue by ericmjl** [rdkit/rdkit#2316]
Short summary: I had to implement a wrapper API in pyjanitor.chemistry to make this happen in a nice, declarative, and method-chain-able fashion.

https://pyjanitor.readthedocs.io/api.html#module-janitor.chemistry

I think RDKit + Pandas users would love it if this were native to RDKit, rather than having to install my package to obtain that API :smile:.

**Comment by bp-kelley** [comment]
We may jigger the API a bit, but this looks quite doable.  To clarify, you are using the counts in separate columns for each molecule.  But you don't want the molecule itself just the fp data?

**Comment by bp-kelley** [comment]
@ericmjl (referencing Eric so he sees the update)

You are also welcome to fork and do a PR if you want more control :)

**Comment by ericmjl** [comment]
> To clarify, you are using the counts in separate columns for each molecule. But you don't want the molecule itself just the fp data?

That is right. Each row is a 2048-long counts or bit vector.
