### ISSUE TITLE
Cannot disable RDKit logging

### ISSUE THREAD

**Issue by Andy-Wilkinson** [rdkit/rdkit#2320]
**Description:**

- RDKit Version: 2018.09.1
- Platform: Windows

I am running a Jupyter notebook which uses the rdkit.Chem.MolStandardize.rdMolStandardize.ChargeParent(...) function for cleaning a large number of molecules. Unfortunately, this seems to slow down significantly due to the outputting of a large number of logging messages to the console (this seems to be the bottleneck, not the actual cleaning of molecules).

I have tried to disable logging using RDLogger.logger.setLevel(...), but this does not seem to work (either within Jupyter, or from the python console). Is there something I'm doing wrong here?

For example in the following code, the call to 'ChargeParent(...)' outputs a number of lines of informational log messages.

```
from rdkit.Chem import MolFromSmiles
from rdkit.Chem.MolStandardize.rdMolStandardize import ChargeParent
from rdkit import RDLogger

lg = RDLogger.logger()
lg.setLevel(RDLogger.CRITICAL)

mol = MolFromSmiles('CCN(CC)CC')
ChargeParent(mol)
```

**Comment by greglandrum** [comment]
Apologies that this is not as obvious as it should be.
The verbose output from the MolStandardize code are actually coming from the C++ side, so you have to use a different approach to disable them:

```
In [4]: RDLogger.DisableLog('rdApp.info')                                                                                                 

In [5]: mol = MolFromSmiles('CCN(CC)CC') 
   ...: ChargeParent(mol)                                                                                                                 
Out[5]: <rdkit.Chem.rdchem.Mol at 0x7fb5cd840530>
```

**Comment by Andy-Wilkinson** [comment]
Thanks Greg for the quick response. Unfortunately I've tried inserting the
RDLogger.DisableLog(...) call and I'm still getting the console output. Not
sure if this is a Windows only issue? I'll look into it some more.

**Comment by bp-kelley** [comment]
To disable everything try:

“rdApp.*”

**Comment by Andy-Wilkinson** [comment]
So, I've been looking into this further and I'm still a bit confused. I've created a repository with some test code at https://github.com/Andy-Wilkinson/RDKit-Logging-Test. There are two scripts in the repo - logging_test_disabled.py & logging_test_enabled.py (identical apart from the 'disabled' script calls `RDLogger.DisableLog('rdApp.info')`).

On all OSs I see the expected behaviour with logging_test_enabled.py (i.e. verbose output).

The results I'm getting for logging_test_disabled.py,

- Ubuntu (via Azure Pipelines CI): No log messages shown 😄
- Mac OS X (via Azure Pipelines CI): No log messages shown 😄
- Windows (local PC): I still see log messages 😞 

It does seem to be a Windows specific issue - is there something about the conversion of 'rdApp.info' from Python to std::string that is different on this OS?

**Comment by jannisborn** [comment]
The following works for me (`rdkit` version `'2019.09.1'`), on MacOS 10.15.1 (Catalina)

```
def disable_rdkit_logging():
    """
    Disables RDKit whiny logging.
    """
    import rdkit.rdBase as rkrb
    import rdkit.RDLogger as rkl
    logger = rkl.logger()
    logger.setLevel(rkl.ERROR)
    rkrb.DisableLog('rdApp.error')

```

**Comment by hioymaci** [comment]
This issue still exist. I could not disable logging on Windows via `RDLogger.DisableLog('rdApp.*')` or others code you mentioned in this post.

**Comment by hadim** [comment]
Same here. The logs are correctly disabled when calling rdkit functions directly below the disabling code but fail when the rdkit functions are called downstream in a function of function of ... (you get the idea). Will try to make a minimal reproducible example.

**Comment by hadim** [comment]
I am trying to understand how the rdkit C++ logging works. I tried.

```python
from rdkit import RDLogger
from rdkit.rdBase import DisableLog

for level in RDLogger._levels:
    DisableLog(level)
```

That is supposed to disable all logs generated by RDKit and indeed it works if I execute a rdkit function just below this code. But when the rdkit function is embedded within my codebase (and my bad on this I can't find a snippet that reproduces it.

Could that be due to multithreading? For example, a python thread disable the logs while new rdkit threads created won't "see" it?

I will try to reproduce it with python multihreads.

**Comment by hadim** [comment]
Well after more investigations it looks like rdkit wasn't doing anything wrong but my custom context manager was not restoring the previous correct rdkit log state. I have fixed it and everything works now. Here is the context manager code in case it can be useful to someone:

```python
class without_rdkit_log:
    """Context manager to disable RDKit logs. By default all logs are disabled."""

    def __init__(
        self,
        mute_errors: bool = True,
        mute_warning: bool = True,
        mute_info: bool = True,
        mute_debug: bool = True,
    ):
        # Get current log state
        self.previous_status = self._get_log_status()

        # Init the desired log state to apply during in the context
        self.desired_status = {}
        self.desired_status["rdApp.error"] = not mute_errors
        self.desired_status["rdApp.warning"] = not mute_warning
        self.desired_status["rdApp.debug"] = not mute_debug
        self.desired_status["rdApp.info"] = not mute_info

    def _get_log_status(self):
        """Get the current log status of RDKit logs."""
        log_status = rdBase.LogStatus()
        log_status = {st.split(":")[0]: st.split(":")[1] for st in log_status.split("\n")}
        log_status = {k: True if v == "enabled" else False for k, v in log_status.items()}
        return log_status

    def _apply_log_status(self, log_status):
        """Apply an RDKit log status."""
        for k, v in log_status.items():
            if v is True:
                rdBase.EnableLog(k)
            else:
                rdBase.DisableLog(k)

    def __enter__(self):
        self._apply_log_status(self.desired_status)

    def __exit__(self, *args, **kwargs):
        self._apply_log_status(self.previous_status)
```

**Comment by bp-kelley** [comment]
We recently added a similar baked in functionality to rdBase that might be useful here.  It keeps a checkpoint of the initial log state which I believe is hard to do from python.

from rdkit.rdBase import BlockLogs

block = BlockLogs()
... do stuff, all logs are blocked
del block
... logs are restored to their initial state

**Comment by kexul** [comment]
@bp-kelley 's solution not working in windows.

**Comment by linminhtoo** [comment]
> We recently added a similar baked in functionality to rdBase that might be useful here. It keeps a checkpoint of the initial log state which I believe is hard to do from python.
> 
> from rdkit.rdBase import BlockLogs
> 
> block = BlockLogs() ... do stuff, all logs are blocked del block ... logs are restored to their initial state

i confirm that this works. 
if your problematic code is running within a function, you have to do the blocking **inside** that function. I was parallelising that function using `joblib.Parallel` and just instantiating the `BlockLogs()` in my main program flow didn't disable the logs.

**Comment by David-Araripe** [comment]
I also wrote a context manager based on the comments above, here's the code in case it helps:

``` python
from contextlib import contextmanager

from rdkit import RDLogger, rdBase
from rdkit.Chem import inchi

@contextmanager
def rdkit_log_controller(level):
    """Context manager for controlling the RDKit logger level.

    Args:
        level: desired logging level. One of `debug, info, warning, error, critical`.
    """
    lg = RDLogger.logger()
    lvl = level.upper()
    # in case no logging is enable, it will be set to critical
    lvl_list = rdBase.LogStatus().split("\n") + ["rdApp.critical:enabled"]
    lg.setLevel(getattr(RDLogger, lvl))
    init_lvl = [lev.split(":")[0] for lev in lvl_list if "enabled" in lev.lower()][0]
    yield
    lg.setLevel(getattr(RDLogger, init_lvl.split(".")[1].upper()))  # restore the level
```

**Comment by d-b-w** [comment]
Please move further questions to the "discussion" tab.
