### ISSUE TITLE
Mentioned in PySmiles

### ISSUE THREAD

**Issue by pckroon** [rdkit/rdkit#2323]
Hi,

I have a project on github called PySmiles (https://github.com/pckroon/pysmiles/), and since RDKit can also read and write SMILES I thought it would be decent to mention RDKit in my readme.
I made this issue to notify you of this, so that you have the opportunity to change (by making a PR) or complain about (by making an issue, or replying to this one)  the description I gave of your project.

Cheers,
Peter

**Comment by greglandrum** [comment]
Thanks for letting us know!
