### ISSUE TITLE
How to set the AtomMapNumber in your reaction?

### ISSUE THREAD

**Issue by Frank-LIU-520** [rdkit/rdkit#2325]
What if part of the molecules like `C1(C)C=CC=CC=1 and C1(P(=[CH:38][C:39]([O:41][CH2:42][CH3:43])=[O:40])(C2C=CC=CC=2)C2C=CC=CC=2)C=CC=CC=1`  in your reaction like
`C1(C)C=CC=CC=1.[CH2:1]([O:8][C:9]1[CH:10]=[C:11]([CH:12]=[CH:38][C:39]([O:41][CH2:42][CH3:43])=[O:40])[CH:14]=[C:15]([O:17][CH3:18])[CH:16]=1)[C:2]1[CH:7]=[CH:6][CH:5]=[CH:4][CH:3]=1>>[CH2:1]([O:8][C:9]1[CH:10]=[C:11]([CH:14]=[C:15]([O:17][CH3:18])[CH:16]=1)[CH:12]=O)[C:2]1[CH:7]=[CH:6][CH:5]=[CH:4][CH:3]=1.C1(P(=[CH:38][C:39]([O:41][CH2:42][CH3:43])=[O:40])(C2C=CC=CC=2)C2C=CC=CC=2)C=CC=CC=1`  does not have the mapped atom numbers?
Which function should I use to get a reaction where all atoms are mapped?
If there is no such function, what should I do?Much thanks!

**Comment by greglandrum** [comment]
The RDKit does not currently have code to automatically map reactions.
If you'd like to map them yourself (by setting the mapping numbers manually on each atom), let me know and I can share a code snippet to do this.

**Comment by Mario-Liu** [comment]
Thanks，@greglandrum  here is my reaction to set the mapping numbers
`‘CCC(=O)C1=C(O)CC(C2=CCCOC2)CC1=O.ClCCl.O=C(OO)c1cccc(Cl)c1>>CCC(=O)C1=C(O)CC(C23COCCC2O3)CC1=O’`

**Comment by autodataming** [comment]
> ion to set the mapping numbers

You can try Indigo TK or RDT  to automatically map the reaction.
