### ISSUE TITLE
Switch Draw.MolToImage and Draw.MolsToImage to use new drawing code when possible

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2336]
**Description:**

The functions `Draw.MolToImage()` and `Draw.MolToFile()` currently use the old drawing code. They can, under some circumstances, use the new code instead.

Here's when the new code can be used:

- `Draw.MolToImage()`
  - if the RDKit has been built with cairo support enabled (i.e. `rdMolDraw2D.MolDraw2DCairo` exists)
  - If no canvas is provided, or if the canvas is an `rdMolDraw2D.MolDraw2DCairo`
- `Draw.MolToFile()`
  - if the filetype is SVG
  - if the filetype is PNG and the RDKit has been built with cairo support enabled (i.e. `rdMolDraw2D.MolDraw2DCairo` exists)

There's a bunch of code in `rdkit/Draw/__init__.py` (functions like `_moltoimg` and `_moltoSVG`) that will be helpful here.

**Comment by joseerlang** [comment]
Hi Greg,
I'm looking for a ticket to get started but I think this one is solved too, right? at least I've already seen the implementation of the _legacy* functions in both contexts.
