### ISSUE TITLE
<< python tests failed >>

### ISSUE THREAD

**Issue by icamps** [rdkit/rdkit#2342]
Hello, 

I am trying to use PyBioMed that uses RDKit. The error I got running PyBioMed was:
`ls Traceback (most recent call last):

  File "./BiEntropy_PyBioMed.sh", line 3, in <module>
    from PyBioMed import Pymolecule
  File "/usr/lib/python2.7/site-packages/PyBioMed/Pymolecule.py", line 27, in <module>
    from PyMolecule import kappa
  File "/usr/lib/python2.7/site-packages/PyBioMed/PyMolecule/kappa.py", line 30, in <module>
    from rdkit.Chem import pyPeriodicTable as PeriodicTable
ImportError: cannot import name pyPeriodicTable`

Which I think is related to RDKit. So, I cloned the GIT repo and configured/compile RDKit without any error message using the command:
`cmake -D PYTHON_LIBRARY=/usr/lib64/python2.7/config/libpython2.7.so -D PYTHON_INCLUDE_DIR=/usr/include/python2.7/ -D PYTHON_EXECUTABLE=/usr/bin/python ..`

The environment variables are set correctly relative to RDKit download folder.

My setup:
- RDKit Version: 2019.03.1dev1
- Platform: OpenSUSE Leap 15 64 bits

Running the `ctest` I got several Python errors.
` The following tests FAILED:

          9 - pyDiscreteValueVect (Failed)
         42 - pyDepictor (Failed)
         61 - testEnumeration (Child killed)
         63 - pyChemReactions (Failed)
         64 - pyChemReactionEnumerations (Failed)
         84 - pyMolDescriptors (Failed)
        131 - pyGraphMolWrap (Failed)
        134 - pyTestThreads (Failed)
        149 - pyRanker (Failed)
        151 - pyFeatures (Failed)
        152 - pythonTestDbCLI (Failed)
        153 - pythonTestDirML (Failed)
        154 - pythonTestDirDataStructs (Failed)
        155 - pythonTestDirDbase (Failed)
        156 - pythonTestDirSimDivFilters (Failed)
        157 - pythonTestDirVLib (Failed)
        158 - pythonTestDirChem (Failed)
        159 - pythonTestSping (Failed)`

I appreciate any help.

Regards,

Camps

**Comment by greglandrum** [comment]
We need more info to be able to help here.
Please try running `ctest --output-on-failure` and sending part of the output (enough to see one or two full sets of error messages).

**Comment by icamps** [comment]
Hi @greglandrum, I am attaching the output files here.
[LastTest.log](https://github.com/rdkit/rdkit/files/2961198/LastTest.log)
[LastTestsFailed.log](https://github.com/rdkit/rdkit/files/2961199/LastTestsFailed.log)
[ctest_output.txt](https://github.com/rdkit/rdkit/files/2961200/ctest_output.txt)
[CTestCostData.txt](https://github.com/rdkit/rdkit/files/2961201/CTestCostData.txt)

**Comment by greglandrum** [comment]
Ah! I got it! Apologies that this took me so long.
You are building against master with Python2. The master version of the RDKit no longer supports Python2: https://github.com/rdkit/rdkit/blob/master/ReleaseNotes.md#really-important-announcement

If you want a python2 build, the most recent version you can use is the Release_2018_09 branch.

**Comment by greglandrum** [comment]
we'll fix the build system so that it raises an error if you're using Python2
