### ISSUE TITLE
Potentially a bug in reactions on molecules with more than one fragment

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2344]
**Description:**

If you apply a reaction to a molecule with more than one fragment, any fragment that has no atoms involved in the reaction will not be transferred to the products:
```
In [25]: rxn = AllChem.ReactionFromSmarts('[NH3+:1]>>[NH2+0:1]')                                               

In [26]: ps = rxn.RunReactants((Chem.MolFromSmiles('CC.C[NH3+]'),))                                            

In [27]: ps                                                                                                    
Out[27]: ((<rdkit.Chem.rdchem.Mol at 0x7f5ed79175b0>,),)

In [28]: Chem.SanitizeMol(ps[0][0])                                                                            
Out[28]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [29]: Chem.MolToSmiles(ps[0][0])                                                                            
Out[29]: 'CN'
```

The behavior is easy enough to explain, but it feels like a bug to me. Anyone else have opinions about this? @bp-kelley ?

**Comment by jasondbiggs** [comment]
@greglandrum this also feels like a bug to me but it isn't clear what the right answer is.  The way the code works now, the only unmatched atoms from the reactants that are copied over to the products are those that are bonded to matched-and-mapped atoms.  

If the unmatched disconnected part of a reactant were to be carried over to the products, how do you decide *which* product to add it to?  For a unimolecular reaction like this it seems clear it should go to the only product, but in a general reaction with multiple reactants and products it is less clear.
