### ISSUE TITLE
/usr/lib/python3/dist-packages/rdkit/rdBase.so: undefined symbol: _ZN5boost6python6detail11init_moduleEPKcPFvvE

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#2348]
Hello,

Any idea on how to solve this problem?

I am building from sources using this script:
```
mkdir -p build
cd build
cmake \
    -DRDK_INSTALL_INTREE=OFF \
    -DRDK_BUILD_INCHI_SUPPORT=ON \
    -DRDK_BUILD_AVALON_SUPPORT=ON \
    -DRDK_BUILD_PYTHON_WRAPPERS=ON \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DPYTHON_EXECUTABLE=/usr/bin/python3.6 \
    -DBOOST_ROOT=/usr \
    ../
nprocs=`getconf _NPROCESSORS_ONLN`
make -j $nprocs
cpack -G DEB
```

Then I install the created debs.

```
python3
import rdkit
```

triggers the error.

Thanks,
F.

**Comment by UnixJunkie** [comment]
This is on a Ubuntu 18.04.2 LTS computer.

**Comment by UnixJunkie** [comment]
The boost version is 1.65.1.

**Comment by greglandrum** [comment]
A couple of questions:
1) It looks like you didn't run the tests after doing the build, but just in case: did the tests work?
2) if you do `ldd /usr/lib/python3/dist-packages/rdkit/rdBase.so` do you see the correct boost library? (i.e. the same one you built/linked against).

**Comment by UnixJunkie** [comment]
No, I did not run the tests, because I am trying to install a tagged version of rdkit (Release_2018_09_2).

Here is the ldd output:
```
# ldd ./build/rdkit/rdBase.so
        linux-vdso.so.1 (0x00007ffc593c1000)
        libgtk3-nocsd.so.0 => /usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0 (0x00007f67baa03000)
        libRDKitRDBoost.so.1 => /home/berenger/src/rdkit/build/lib/libRDKitRDBoost.so.1 (0x00007f67ba800000)
        libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f67ba283000)
        libboost_python3-py36.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so.1.65.1 (0x00007f67ba044000)
        libRDKitRDGeneral.so.1 => /home/berenger/src/rdkit/build/lib/libRDKitRDGeneral.so.1 (0x00007f67b9e29000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f67b9aa0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f67b9888000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f67b9497000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f67b9293000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f67b9074000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f67b8e57000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f67b8c54000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f67b88b6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f67baf0c000)
```
I think this line is problematic and have no idea on how to fix it:
libpython2.7.so.1.0
I was trying to build a version for python-3.6...

**Comment by greglandrum** [comment]
Ah, it built against python2. Cute. You need to make sure that cmake picks up the correct python version when you run it (and the output of cmake will tell you which one it's using).
This may be as easy as including `-DPYTHON_EXECUTABLE=/path/to/python3`.
If that doesn't work let me know and I will try to do an ubuntu build using the "native" python3

**Comment by UnixJunkie** [comment]
I was already using -DPYTHON_EXECUTABLE=/usr/bin/python3.6

**Comment by greglandrum** [comment]
This docker container just built for me (and the tests passed) without problems:
https://github.com/rdkit/rdkit_containers/blob/master/docker/ubuntu_bionic/Dockerfile

**Comment by UnixJunkie** [comment]
ok, the fix looks like this statement must be before other statements.
I'll update the build script for deb packages once I have confirmed this.
