### ISSUE TITLE
MolToSmiles(sanitize=True) is not the same as MolToSmiles + SanitizeMol

### ISSUE THREAD

**Issue by drkeoni** [rdkit/rdkit#2361]
**Description:**

- RDKit Version: 2018.09.2, also 2019.03.dev1
- Platform: Linux/python 3.6.8, also MacOS 10.14.3/python 3.7.2

I was surprised that the results of `AllChem.MolFromSmiles` with `sanitize=True` can differ subtly from the results of `AllChem.MolFromSmiles` with `sanitize=False` followed by `AllChem.SanitizeMol`.  

This can be demonstrated by the following example with InChI keys:
```
In [44]: m = AllChem.MolFromSmiles('[O-][n+]1onc2cc(/C=C/c3ccc(Cl)cc3)ccc21', sanitize=True)

In [45]: AllChem.MolToInchiKey(m)
Out[45]: 'AALOGNDNCMFSSI-OWOJBTEDSA-N'

In [46]: m = AllChem.MolFromSmiles('[O-][n+]1onc2cc(/C=C/c3ccc(Cl)cc3)ccc21', sanitize=False)

In [47]: AllChem.SanitizeMol(m, Chem.rdmolops.SanitizeFlags.SANITIZE_ALL)
Out[47]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [48]: AllChem.MolToInchiKey(m)
Out[48]: 'AALOGNDNCMFSSI-UHFFFAOYSA-N'
```

These InChI keys are different because the former procedure correctly preserves the stereochemistry of the SMILES string.

The underlying behavior relates to the call of `assignStereochemistry` in the C++ code iff `sanitize=True` or `removeHs=True`.

For the case of calling `SanitizeMol` after `MolFromSmiles` you can force `rdkit` to calculate the correct InChI key by calling `AllChem.AssignStereochemistry(m1, cleanIt=True, force=True)` before calculating the key.

This behavior was unexpected since it would seem that `sanitize=True` should be equivalent to the results of calling `SanitizeMol`.  My question here is if this is a bug or an issue for further documentation.

Thanks!

**Comment by tduigou** [comment]
Hello, I am interested into the outcomes of this thread. The difference does not happen when using the MolFromInchi import method:

```
In  [1]: m = MolFromInchi('InChI=1S/C14H9ClN2O2/c15-12-6-3-10(4-7-12)1-2-11-5-8-14-13(9-11)16-19-17(14)18/h1-9H/b2-1+', sanitize=True)
In  [2]: MolToInchiKey(m)
Out [2]: 'AALOGNDNCMFSSI-OWOJBTEDSA-N'

In  [3]: m = MolFromInchi('InChI=1S/C14H9ClN2O2/c15-12-6-3-10(4-7-12)1-2-11-5-8-14-13(9-11)16-19-17(14)18/h1-9H/b2-1+', sanitize=False)
In  [4]: MolToInchiKey(m)
Out [4]: 'AALOGNDNCMFSSI-OWOJBTEDSA-N'
```

Thanks

**Comment by bp-kelley** [comment]
The documentation in MolFromInchi (and MolFromSmiles) is a bit incorrect.
It states:

```
   * \param sanitize Whether to sanitize the generated molecule before
returning
```

But this means sanitize AND assign stereo.  The order of operations is
normally:

```
if(sanitize) {
    MolOps::sanitizeMol(*res);
    bool cleanIt = true, force = true, flagPossible = true;
    MolOps::assignStereochemistry(*res, cleanIt, force, flagPossible);
}
```

The documentation here does not seem to be quite accurate (although the C++
docs are better in this regard).

I'll flag this as an issue.  In the meantime, here is the python code that
does the same thing:

```
>>> m = AllChem.MolFromSmiles('[O-][n+]1onc2cc(/C=C/c3ccc(Cl)cc3)ccc21',
sanitize=False)
>>> AllChem.SanitizeMol(m)
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
>>> cleanIt = True;force = True;flagPossible = True
>>> AllChem.AssignStereochemistry(m, cleanIt, force, flagPossible)
>>> AllChem.MolToInchiKey(m)
'AALOGNDNCMFSSI-OWOJBTEDSA-N'
```

Cheers,
 Brian

**Comment by tduigou** [comment]
That was fast, thanks!

**Comment by RishalAggarwal** [comment]
I'm facing a similar inconsistency issue when loading in molecules from SDF files and calculating Synthetic Accessibility score. Code block:

`file='aa2ar_pharm_29.sdf'
suppl = Chem.SDMolSupplier(file,sanitize=True)
for mol in suppl:
    if mol is not None:
        sa=sascorer.calculateScore(mol)
        print(sa)
        break
suppl = Chem.SDMolSupplier(file,sanitize=False)
for mol in suppl:
    if mol is not None:
        Chem.SanitizeMol(mol)
        cleanIt = True;force = True;flagPossible = True
        Chem.AssignStereochemistry(mol, cleanIt, force, flagPossible)
        sa=sascorer.calculateScore(mol)
        print(sa)
        break`
        
 Output:
 `2.8103038751849
3.6304131409973355
`
 
 I've attached the sdf file along with the issue, 
[aa2ar_pharm_29.zip](https://github.com/user-attachments/files/17367098/aa2ar_pharm_29.zip)

 
 any help is appreciated :)
