### ISSUE TITLE
Query regarding reaction search using atom maps.

### ISSUE THREAD

**Issue by sahertariq07** [rdkit/rdkit#2367]
I want to filter some reactions using reaction SMARTS from USPTO dataset.
I'm using python 3.5 and rdkit Release 2018.03.4 on Linux.
From different discussions I've used given code but unable to get desired results.
Code is:
#Fischer esterification
rxn = rdChemReactions.ReactionFromSmarts('[CH3:19][CH2:20]O.[CH3:1][O:2][c:3]1[cH:4][c:5]([CH2:6][C:7](=[O:9])[OH:8])[cH:10][cH:11][c:12]1[OH:13].O=S(=O)(O)O>>[CH3:20][CH2:19][O:9][C:7](=[O:8])[CH2:6][c:5]1[cH:10][cH:11][c:12]([OH:13])[c:3]([O:2][CH3:1])[cH:4]1',useSmiles=True)

qrxn = rdChemReactions.ReactionFromSmarts('[C:23]O[H].[O:9]=[C:8]([OH:10])[CH:7].O=S(=O)(O)O>>[C:23][O:9][C:8](=[O:10])[CH:7]',useSmiles=True)

for r in rxn.GetReactants(): Chem.SanitizeMol(r)
for p in rxn.GetProducts(): Chem.SanitizeMol(p)

print(rdChemReactions.HasReactionSubstructMatch(rxn,qrxn,includeAgents=False))

Output: True
It gives me correct output for given reaction but when i use it for the entire dataset it gives me 8885 hits but i only have 2000 reactions of the query in dataset(from known dataset sample). When i dig deep i get that, it is only looking for substructures on both side of the reaction and do not involve atom maps. I've also tried fingerprinting but didn't end at desired results yet.
I'm new to rdkit, kindly share any solution or suggestions regarding this issue. Any help will be appreciated in advance. 

Thank you.

**Comment by greglandrum** [comment]
Hi,
The RDKit does not use atom-mapping information when determining whether or not things are substructure matches.
You can, I think, accomplish what you want by modifying the reactions before doing the searches and using the atom map numbers to set the isotopes of atoms:
https://gist.github.com/greglandrum/3f3dae4897042a6f0800a2ce1f2e4eeb

Note that this presumes that you don't already have isotopes set on atoms in the reactants or products. You might want to confirm this.
