### ISSUE TITLE
PandasTools.FrameToGridImage() fails with SVG output

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2380]
**Description:**

Reported by Bakary N’tji DIALLO

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-8faa0d458cbe> in <module>
----> 1 PandasTools.FrameToGridImage(df)

/scratch/RDKit_git/rdkit/Chem/PandasTools.py in FrameToGridImage(frame, column, legendsCol, **kwargs)
    516         else:
    517             kwargs['legends'] = [str(c) for c in frame[legendsCol]]
--> 518     return Draw.MolsToGridImage(frame[column], **kwargs)
    519 
    520 

/scratch/RDKit_git/rdkit/Chem/Draw/IPythonConsole.py in ShowMols(mols, maxMols, **kwargs)
    187                 kwargs[prop] = kwargs[prop][:maxMols]
    188 
--> 189     res = fn(mols, **kwargs)
    190     if kwargs['useSVG']:
    191         return SVG(res)

/scratch/RDKit_git/rdkit/Chem/Draw/__init__.py in MolsToGridImage(mols, molsPerRow, subImgSize, legends, highlightAtomLists, highlightBondLists, useSVG, **kwargs)
    468     return _MolsToGridSVG(mols, molsPerRow=molsPerRow, subImgSize=subImgSize, legends=legends,
    469                           highlightAtomLists=highlightAtomLists,
--> 470                           highlightBondLists=highlightBondLists, **kwargs)
    471   else:
    472     return _MolsToGridImage(mols, molsPerRow=molsPerRow, subImgSize=subImgSize, legends=legends,

/scratch/RDKit_git/rdkit/Chem/Draw/__init__.py in _MolsToGridSVG(mols, molsPerRow, subImgSize, legends, highlightAtomLists, highlightBondLists, **kwargs)
    450   d2d = rdMolDraw2D.MolDraw2DSVG(fullSize[0], fullSize[1], subImgSize[0], subImgSize[1])
    451   d2d.DrawMolecules(mols, legends=legends, highlightAtoms=highlightAtomLists,
--> 452                     highlightBonds=highlightBondLists, **kwargs)
    453   d2d.FinishDrawing()
    454   res = d2d.GetDrawingText()

~/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in __nonzero__(self)
   1477         raise ValueError("The truth value of a {0} is ambiguous. "
   1478                          "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
-> 1479                          .format(self.__class__.__name__))
   1480 
   1481     __bool__ = __nonzero__

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by hellerm2** [comment]
I got a similar traceback just now with the following RDkit version:

$ conda list | grep rdkit
# packages in environment at /home/mheller/anaconda3/envs/rdkit:
rdkit                     2019.03.4.0      py37hc20afe1_1    rdkit

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-136-f94cd85df621> in <module>
      5 print(top5_sim_df)
      6 
----> 7 MolsToGridImage(top5_sim_df.mol, molsPerRow=5, legends=["%.2f" % x for x in top5_sim_df.sim_mrgn2])

~/anaconda3/envs/rdkit/lib/python3.7/site-packages/rdkit/Chem/Draw/IPythonConsole.py in ShowMols(mols, maxMols, **kwargs)
    190                 kwargs[prop] = kwargs[prop][:maxMols]
    191 
--> 192     res = fn(mols, **kwargs)
    193     if kwargs['useSVG']:
    194         return SVG(res)

~/anaconda3/envs/rdkit/lib/python3.7/site-packages/rdkit/Chem/Draw/__init__.py in MolsToGridImage(mols, molsPerRow, subImgSize, legends, highlightAtomLists, highlightBondLists, useSVG, **kwargs)
    468     return _MolsToGridSVG(mols, molsPerRow=molsPerRow, subImgSize=subImgSize, legends=legends,
    469                           highlightAtomLists=highlightAtomLists,
--> 470                           highlightBondLists=highlightBondLists, **kwargs)
    471   else:
    472     return _MolsToGridImage(mols, molsPerRow=molsPerRow, subImgSize=subImgSize, legends=legends,

~/anaconda3/envs/rdkit/lib/python3.7/site-packages/rdkit/Chem/Draw/__init__.py in _MolsToGridSVG(mols, molsPerRow, subImgSize, legends, highlightAtomLists, highlightBondLists, **kwargs)
    450   d2d = rdMolDraw2D.MolDraw2DSVG(fullSize[0], fullSize[1], subImgSize[0], subImgSize[1])
    451   d2d.DrawMolecules(mols, legends=legends, highlightAtoms=highlightAtomLists,
--> 452                     highlightBonds=highlightBondLists, **kwargs)
    453   d2d.FinishDrawing()
    454   res = d2d.GetDrawingText()

~/anaconda3/envs/rdkit/lib/python3.7/site-packages/pandas/core/generic.py in __nonzero__(self)
   1553             "The truth value of a {0} is ambiguous. "
   1554             "Use a.empty, a.bool(), a.item(), a.any() or a.all().".format(
-> 1555                 self.__class__.__name__
   1556             )
   1557         )

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by greglandrum** [comment]
@hellerm2 : you can’t call `MolsToGridImage()` directly with a column of a DataFrame. Try: `MolsToGridImage(list(top5_sim_df.mol),...)`

**Comment by hellerm2** [comment]
Thanks for your reply, Greg.  

Actually, restarting the notebook did the trick for me without having to change my code (it worked before, so I assume that something went wrong with the Jupyter notebook).

Also, out of curiosity, isn't this what the [fix above](https://github.com/greglandrum/rdkit/commit/e92337415d47dc760b8c12960eae6235e7cbde59) does?  Adding the `list` to `Draw.MolsToGridImage`?

Again, after restarting my Jupyter notebook, this works with or without the `list`, so including it shouldn't hurt.

**Comment by greglandrum** [comment]
@hellerm2 Interesting that it works after restarting the notebook. I wonder what that was.

> 
> Also, out of curiosity, isn't this what the [fix above](https://github.com/greglandrum/rdkit/commit/e92337415d47dc760b8c12960eae6235e7cbde59) does? Adding the `list` to `Draw.MolsToGridImage`?
> 

Yeah. The fix there was to to modify the call to `Draw.MolstoGridImage()` in the `FrameToGridImage()` function.

> Again, after restarting my Jupyter notebook, this works with or without the `list`, so including it shouldn't hurt.

Yeah, I just checked in jupyter (I was replying from my phone yesterday and "guessed") and see that it can work without including `list`. Sorry about that, I can never remember when you can use a `Series` like a sequence or tuple and when not.
