### ISSUE TITLE
Compute2DCoords gives inconsistent coordinates when not removing hydrogens

### ISSUE THREAD

**Issue by stefdoerr** [rdkit/rdkit#2386]
**Description:**

- RDKit Version: 2018.09.3
- Platform: conda

Here is the sdf with the molecule
[failing.sdf.zip](https://github.com/rdkit/rdkit/files/3030200/failing.sdf.zip)
```python
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw

suppl = Chem.SDMolSupplier('failing.sdf', removeHs=False)
ms = [x for x in suppl if x is not None]
AllChem.Compute2DCoords(ms[0])
Draw.MolToFile(ms[0],'mol.png')
```
This gives
![mol](https://user-images.githubusercontent.com/7935362/55340170-6c4f0b00-54a4-11e9-9f8a-e9e66fffe716.png)

Removing the hydrogens with `RemoveHs(ms[0])` we get:
![mol](https://user-images.githubusercontent.com/7935362/55340368-d49dec80-54a4-11e9-8a25-321007b3e21e.png)

Loading without hydrogens `suppl = Chem.SDMolSupplier('failing.sdf', removeHs=False)` we get:
![mol2](https://user-images.githubusercontent.com/7935362/55340438-fac38c80-54a4-11e9-9b82-648578e41949.png)

**Comment by stefdoerr** [comment]
FYI this issue starts with version 2017.09.3

**Comment by greglandrum** [comment]
Confirmed. I can reproduce this and will look into it.

**Comment by stefdoerr** [comment]
Just an update for myself since I reran the tests, the issue persists in 2019.03.3
