### ISSUE TITLE
Chiral Morgan Fingerprints should differ for geometric isomers

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#2388]
Example code showing the issue:

```
from rdkit.Chem import AllChem
smi1 = "C[C@H]1C[C@@H](C1)O"
smi2 = "C[C@H]1C[C@H](C1)O"

m1 = AllChem.MolFromSmiles(smi1)
m2 = AllChem.MolFromSmiles(smi2)

print(AllChem.MolToSmiles(m1, isomericSmiles=True))
print(AllChem.MolToSmiles(m2, isomericSmiles=True))
c1 = AllChem.GetHashedMorganFingerprint(m1, 3, useChirality=True)
c2 = AllChem.GetHashedMorganFingerprint(m2, 3, useChirality=True)
print(c1==c2)
```

I would have expected that the fingerprints would be different.

**Comment by bp-kelley** [comment]
I think these are geometric isomers and not really chiral.

**Comment by greglandrum** [comment]
Yeah, this is "ring stereochemistry", not true chirality.
The Morgan invariants use the "R"/"S" tags on chiral centers to modify the fingerprint bits, and that doesn't apply here.
It would be logical to change the way that chirality is incorporated into fingerprint bits (and to use something other than "R"/"S"); something to think about.
