### ISSUE TITLE
Please support pip install

### ISSUE THREAD

**Issue by tamuhey** [rdkit/rdkit#2389]
Thanks for this great tool!

I want to install rdkit for python with not "conda" but "pip", because it is easier to management virtual environments with pip than conda.

**Comment by greglandrum** [comment]
Hi. I would be happy to be able to do pip distributions of the RDKit, but to the best of my knowledge no one has managed to figure out how to make it actually work.

I'd be happy to accept a PR from someone who has figured this out, but I am not likely to have the time to do this myself anytime in the near future.

**Comment by greglandrum** [comment]
Please move any further discussion of this to #1812
