### ISSUE TITLE
Incorrect 2D drawing of a molecule

### ISSUE THREAD

**Issue by shayakhmetov** [rdkit/rdkit#2397]
```
rdkit.__version__ == '2018.09.1'
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole
Chem.MolFromSmiles('CNC2(CCc1ccccc1)COC2')
```
the code above draws the molecule correctly, but if I decrease the length of the central chain by only one ('CNC2(Cc1ccccc1)COC2'), the drawing smashes two unrelated atoms together.

![Screenshot from 2019-04-05 14-08-32](https://user-images.githubusercontent.com/4422605/55623794-b38f1180-57ac-11e9-92e7-fe6549a9fa88.png)
![Screenshot from 2019-04-05 14-09-10](https://user-images.githubusercontent.com/4422605/55623793-b2f67b00-57ac-11e9-9500-c507ab12b2b3.png)

Moreover, the structure of the latter is incorrect when writing to sdf\mol file

**Comment by shayakhmetov** [comment]
The issue remains the same in the `2018.09.3` version

**Comment by shayakhmetov** [comment]
The issue remains the same in the `2019.03.2` version

**Comment by DavidACosgrove** [comment]
Using
rdDepictor.SetPreferCoordGen(True)
rdDepictor.Compute2DCoords(mol)
with 2020.03.1dev1
I get 
![Screenshot 2020-02-04 at 09 34 45](https://user-images.githubusercontent.com/9198870/73732208-b262a400-4731-11ea-8afc-5f952372cbf3.png)
