### ISSUE TITLE
AssignStereochemistry is removing valid cis/trans bond stereo

### ISSUE THREAD

**Issue by yphillip** [rdkit/rdkit#2404]
**Description:**
I am having similar issues to what was presented in #1614 where AssignStereochemistry seems to be removing valid CIS/TRANS stereochemistry from a double bond.

- RDKit Version:2018.09.1.0

```
mol = Chem.MolFromSmiles('CC(Cl)=CF')
mol.GetBondWithIdx(2).SetStereoAtoms(2,4)
mol.GetBondWithIdx(2).SetStereo(Chem.BondStereo.STEREOTRANS)
print(Chem.MolToSmiles(mol))
Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
print(Chem.MolToSmiles(mol))

........

C/C(Cl)=C\F
CC(Cl)=CF
```

Additionally, I am able to still recapitulate the original problem presented in #1614, namely:

```
m = Chem.MolFromSmiles('CC(F)=CC(Cl)C')
m.GetAtomWithIdx(4).SetChiralTag(Chem.ChiralType.CHI_TETRAHEDRAL_CW)
assert m.GetBondWithIdx(2).GetBondType() == Chem.BondType.DOUBLE
m.GetBondWithIdx(2).SetStereoAtoms(2, 4)
m.GetBondWithIdx(2).SetStereo(Chem.BondStereo.STEREOCIS)
smi = Chem.MolToSmiles(m, True)
print(smi)
Chem.AssignStereochemistry(m)
print(Chem.MolToSmiles(m, True))
Chem.AssignStereochemistry(m, cleanIt=True)
print(Chem.MolToSmiles(m, True))
Chem.AssignStereochemistry(m, force=True)
print(Chem.MolToSmiles(m, True))
Chem.AssignStereochemistry(m, cleanIt=True, force=True)
print(Chem.MolToSmiles(m, True))
...
C/C(F)=C/[C@H](C)Cl
C/C(F)=C/[C@H](C)Cl
C/C(F)=C/[C@H](C)Cl
C/C(F)=C/[C@H](C)Cl
CC(F)=C[C@H](C)Cl 
```
In the final line, the valid CIS/TRANS stereochemistry gets removed.
Is this bug still present? Or maybe have I misunderstood something? Thanks for the help.

**Comment by bp-kelley** [comment]
Try:

> print(Chem.MolToSmiles(mol, isomericSmiles=True))
I think this is the default now, but it didn’t use to be.
----
Brian Kelley

**Comment by yphillip** [comment]
Hmm, still getting the same behavior.

```
mol = Chem.MolFromSmiles('CC(Cl)=CF')
mol.GetBondWithIdx(2).SetStereoAtoms(2,4)
mol.GetBondWithIdx(2).SetStereo(Chem.BondStereo.STEREOTRANS)
print(Chem.MolToSmiles(mol, isomericSmiles=True))
Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
print(Chem.MolToSmiles(mol, isomericSmiles=True))
.............
C/C(Cl)=C\F
CC(Cl)=CF
```

**Comment by d-b-w** [comment]
I think that `AssignStereochemistry` is getting the bond stereo from the directions of the bonds adjacent to the double bond. I don't currently understand which of these two mechanisms should be considered canonical:

    >>> from rdkit import Chem
    >>> mol = Chem.MolFromSmiles('CC(Cl)=CF')
    >>> mol.GetBondWithIdx(2).SetStereoAtoms(2,4)
    >>> mol.GetBondWithIdx(2).SetStereo(Chem.BondStereo.STEREOTRANS)
    >>> print(Chem.MolToSmiles(mol))
    C/C(Cl)=C\F
    >>> Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
    >>> print(Chem.MolToSmiles(mol, isomericSmiles=True))
    CC(Cl)=CF
    >>> mol.GetBondBetweenAtoms(1, 2).SetBondDir(Chem.rdchem.BondDir.ENDDOWNRIGHT)
    >>> mol.GetBondBetweenAtoms(3, 4).SetBondDir(Chem.rdchem.BondDir.ENDUPRIGHT)
    >>> print(Chem.MolToSmiles(mol))
    CC(Cl)=CF
    >>> Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
    >>> print(Chem.MolToSmiles(mol))
    C/C(Cl)=C\F
    >>> Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
    >>> print(Chem.MolToSmiles(mol))
    C/C(Cl)=C\F

**Comment by yphillip** [comment]
That's good insight, d-b-w, thanks for that.
I'm hoping that STEREOTRANS/STEREOCIS + setting the stereoatoms will become fully supported, and that I won't need to resort to dealing with the ENDDOWNRIGHT/ENDUPRIGHT system.

There's a thread in the mailing list that discusses the different ways double bond stereochem is handled: https://sourceforge.net/p/rdkit/mailman/message/36484682/. My impression from that thread is there might still be some bugs with using STEREOTRANS/STEREOCIS to set double bond stereochemistry.

**Comment by d-b-w** [comment]
Heh, I responded to that thread... Also I posted https://sourceforge.net/p/rdkit/mailman/message/36635528/ more recently about issues specifically with reactions.

**Comment by greglandrum** [comment]
I think the current behavior of `AssignStereochemistry()` - clearing the stereo of double bonds that have `STEREOCIS` or `STEREOTRANS` set but that don't have wedged bonds - is a bug.

Of course this is one of those things where fixing it may open a giant can of worms and result in me immediately deciding that it's "by design". ;-)

**Comment by greglandrum** [comment]
The historical reason this happens is because the old `STEREOE/STEREOZ` approach is kind of stupid and we bolted the `STEREOCIS/STEREOTRANS` thing (which is theoretically much simpler) on later. Clearly we still haven't managed to get all the bolts completely tight.
