### ISSUE TITLE
RDKit fails to build on ppc64le with conda-rdkit

### ISSUE THREAD

**Issue by cwhidden** [rdkit/rdkit#2405]
**Description:**

- RDKit Version: 2018.03.4
- Platform: RHEL 7.5 ppc64le Power8

RDKit failed to build on a Power8 system running RHEL Linux because the -mpopcnt optimization set in CMakeLists.txt is not supported. I was building with conda-rdkit, hence the old version, but this option appears unchanged in newer versions. My workaround was to add a patch in conda-rdkit that changed this option from -mpopcnt to -mpopcntb. Ideally, CMakeLists.txt would detect ppc64le and use the alternative optimization.

This is a possible duplication of #916 which discusses detecting architecture but as that issue is nearly 3 years old and did not discuss build failure on little endian power systems I thought it better to create a new issue.

**Comment by greglandrum** [comment]
Worst case you can always disable the native optimization to get things to build.

As for automating the detection of that: I'm generally uncomfortable making changes to the code that I can't test at all. I don't have access to a PPC based machine to build on, so I would be reluctant to just start hacking stuff into the main CMakeLists.txt in the hopes that it will work.

I'd be happy to get a PR from someone who does have access to a PPC and who has tested the changes. :-)

**Comment by jaimergp** [comment]
Hi Greg, we are seeing the same issue in this conda-forge PR: https://github.com/conda-forge/rdkit-feedstock/pull/54

We needed something similar in OpenMM and found these two services that can provide free access to PPC machines:

* https://openpower.ic.unicamp.br/minicloud/
* https://osuosl.org/services/powerdev/request_powerci/

I have requested access to OpenPower @ UniCamp. Let me know how I can help!

**Comment by greglandrum** [comment]
@jaimergp : if you can get access and find a cmake configuration that works I would be happy to merge the PR. 
Just as a reminder: it’s always possible to just doable the usage of the popcnt optimization when you build on those systems. The price you pay is only going to be noticeable if you do a bunch of similarity calculations

**Comment by jaimergp** [comment]
I got `conda` to build `rdkit` for both [`ppc64le`](https://travis-ci.com/github/conda-forge/rdkit-feedstock/builds/174972145) and [`aarch64`](https://cloud.drone.io/conda-forge/rdkit-feedstock/8)!

Sadly running the tests on Travis/Drone exceed the allocated 60 mins, so I am debugging "locally" thanks to the @Unicamp-OpenPower team!

I'll upload the logs once I got the results, but I think they all will pass.

This is the block I added to deal with the different archs:

```
if(NOT MSVC)
  if(RDK_OPTIMIZE_POPCNT)
    if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
      message("RDK_OPTIMIZE_POPCNT is not available on aarch64")
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "ppc64le")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mpopcntb")
    else()
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mpopcnt")
    endif()
  endif()
endif()
```

**Comment by jaimergp** [comment]
Hi again Greg, I have [some results](https://github.com/conda-forge/rdkit-feedstock/pull/54#issuecomment-656306489) for the unit tests.  Copying here for easier tracking:

***

Local tests for `ppc64le` and Python 3.7:  [build.log.zip](https://github.com/conda-forge/rdkit-feedstock/files/4899060/build.log.zip)

Two errors:

```
99% tests passed, 2 tests failed out of 180

Total Test time (real) = 538.96 sec

The following tests FAILED:
	 91 - test3D (Child aborted)
	 96 - pyMolDescriptors (Failed)
```

I have access to a PowerPC machine until June 12th if you want to take a look.

**Comment by greglandrum** [comment]
@jaimergp : thanks for that.
The second failure (in pyMolDescriptors) is due to a subtle problem in the way the tests are written.
The first is unclear.
I created a branch that fixes the second problem and provides extra output for the first one:
https://github.com/greglandrum/rdkit/tree/dev/fix_ppc_builds
Would you mind switching to that branch and running just those two tests again? `pyMolDescriptors` should hopefully work and `test3D` will generate output that may help diagnose the problem

**Comment by jaimergp** [comment]
This branch causes no test errors at all, so this means that:

* 96 is fixed!
* But 91 is not being run, right? You [commented out the assertions](https://github.com/rdkit/rdkit/compare/master...greglandrum:dev/fix_ppc_builds#diff-0747839683e4489121ac770ad46d6e31). Since I ran `ctest --output-on-failure`, I did not get the debugging messages. I am rerunning now with `ctest -VV`, which will hopefully provide enough info.

**Comment by jaimergp** [comment]
While it runs, one question. GCC defines two `popcnt` optimizations, but I can't find whether they are compatible or exclusive:

> The `-mpopcntb` option allows GCC to generate the popcount and double-precision FP reciprocal estimate instruction implemented on the POWER5 processor and other processors that support the PowerPC V2.02 architecture. 

> The `-mpopcntd` option allows GCC to generate the popcount instruction implemented on the POWER7 processor and other processors that support the PowerPC V2.06 architecture.

I am using `popcntb` because that's what the error suggested to use instead of x64's `popcnt`, but I don't know if we should consider the other one too?

**Comment by greglandrum** [comment]
@jaimergp : yes, I commented out the test asserts so that we can see the output. I, of course, forgot that since there are now no tests failing we won't see output.

ctest -V -R test3D

should show you what we need

> While it runs, one question. GCC defines two `popcnt` optimizations, but I can't find whether they are compatible or exclusive:
> 
> > The `-mpopcntb` option allows GCC to generate the popcount and double-precision FP reciprocal estimate instruction implemented on the POWER5 processor and other processors that support the PowerPC V2.02 architecture.
> 
> > The `-mpopcntd` option allows GCC to generate the popcount instruction implemented on the POWER7 processor and other processors that support the PowerPC V2.06 architecture.
> 
> I am using `popcntb` because that's what the error suggested to use instead of x64's `popcnt`, but I don't know if we should consider the other one too?

I guess the answer depends on the PPC architecture that you have installed.
It looks like doing `-mcpu=native` may work to pick the right one:
https://gcc.gnu.org/onlinedocs/gcc/RS_002f6000-and-PowerPC-Options.html

**Comment by jaimergp** [comment]
Looks like `conda-forge` [is already handling ](https://travis-ci.com/github/conda-forge/rdkit-feedstock/jobs/359271390#L639) `-mcpu=xxxx` (flags set up by the compiler activation scripts), so we shouldn't add these instructions in `conda-forge`. As a result, I think we should set `RDK_OPTIMIZE_POPCNT=OFF` in the feedstock (since it's on by default anyway) but will still submit the PR so it's addressed with the `rdkit` channel builds.

However, if I add `-mcpu=native` we might enable other optimizations that are not as portable though, as you mentioned in https://github.com/rdkit/rdkit/issues/916#issuecomment-230350873. What's the preferred way forward?

**Comment by greglandrum** [comment]
In the case of conda-forge, I would assume that they've thought about the issue and just follow whatever their standard practice is.

**Comment by jaimergp** [comment]
Output from  `ctest -VV -R test3D`:

```
test 94
    Start 94: test3D

94: Test command: /opt/conda/conda-bld/rdkit_1594375720151/work/Code/GraphMol/Descriptors/test3D
94: Test timeout computed to be: 1500
94: [07:41:37] -------------------------------------
94: [07:41:37]     Basic PMI tests.
94: [07:41:38]   done
94: [07:41:38] -------------------------------------
94: [07:41:38]     More PMI/NPR tests.
94: [07:41:38]   done
94: [07:41:38] -------------------------------------
94: [07:41:38]     Basic NPR tests.
94: [07:41:38]   done
94: [07:41:38] -------------------------------------
94: [07:41:38]     PMI edge cases.
94: [07:41:38]   done
94: [07:41:38] -------------------------------------
94: [07:41:38]     NPR edge cases.
94: [07:41:38]   done
94: [07:41:38] -------------------------------------
94: [07:41:38]     3D descriptors.
94: [07:41:38]   done
94: [07:41:38] -------------------------------------
94: [07:41:38]     3D descriptor edge cases.
94: val1: nan
94: val2: 0
94: val3: 1
94: val0: 0
94: val1: 0
94: val2: 0
94: val3: 0
94: val4: 0
94: [07:41:38]   done
94: [07:41:38] -------------------------------------
94: [07:41:38]     Inertial shape factor.
94: [07:41:38]   done
1/1 Test #94: test3D ...........................   Passed    0.69 sec
```

**Comment by greglandrum** [comment]
That `nan` is obviously the problem. I'll look into it

**Comment by greglandrum** [comment]
@jaimergp I just added more verbose output to the eccentricity calculation. Could you please update from my branch and run `test3D` again?

**Comment by jaimergp** [comment]
New output:

```
test 94
    Start 94: test3D

94: Test command: /opt/conda/conda-bld/rdkit_1594391552689/work/Code/GraphMol/Descriptors/test3D
94: Test timeout computed to be: 1500
94: [20:39:49] -------------------------------------
94: [20:39:49]     Basic PMI tests.
94: [20:39:49]   done
94: [20:39:49] -------------------------------------
94: [20:39:49]     More PMI/NPR tests.
94: [20:39:49]   done
94: [20:39:49] -------------------------------------
94: [20:39:49]     Basic NPR tests.
94: [20:39:50]   done
94: [20:39:50] -------------------------------------
94: [20:39:50]     PMI edge cases.
94: [20:39:50]   done
94: [20:39:50] -------------------------------------
94: [20:39:50]     NPR edge cases.
94: [20:39:50]   done
94: [20:39:50] -------------------------------------
94: [20:39:50]     3D descriptors.
94:   evals: 89.1431 89.1458 178.289
94:   evals: 6.6164 150.43 150.43
94:   evals: 303.087 303.091 303.096
94: [20:39:50]   done
94: [20:39:50] -------------------------------------
94: [20:39:50]     3D descriptor edge cases.
94:   evals: 4.032 4.032 4.032
94: val1: nan
94: val2: 0
94: val3: 1
94: val0: 0
94: val1: 0
94:   evals: 0 0 0
94: val2: 0
94: val3: 0
94: val4: 0
94: [20:39:50]   done
94: [20:39:50] -------------------------------------
94: [20:39:50]     Inertial shape factor.
94: [20:39:50]   done
1/1 Test #94: test3D ...........................   Passed    0.69 sec
```

**Comment by greglandrum** [comment]
@jaimergp Ok, I have a guess as to what the problem might be.
Just added a commit to my branch that might fix it.
That also re-enables all the tests, so if there is a problem you will get a failure.

**Comment by jaimergp** [comment]
So, if I am reading this correctly, that commit indeed fixed it!

```
test 94
    Start 94: test3D

94: Test command: /opt/conda/conda-bld/rdkit_1594459023256/work/Code/GraphMol/Descriptors/test3D
94: Test timeout computed to be: 1500
94: [07:02:14] -------------------------------------
94: [07:02:14]     Basic PMI tests.
94: [07:02:15]   done
94: [07:02:15] -------------------------------------
94: [07:02:15]     More PMI/NPR tests.
94: [07:02:15]   done
94: [07:02:15] -------------------------------------
94: [07:02:15]     Basic NPR tests.
94: [07:02:15]   done
94: [07:02:15] -------------------------------------
94: [07:02:15]     PMI edge cases.
94: [07:02:15]   done
94: [07:02:15] -------------------------------------
94: [07:02:15]     NPR edge cases.
94: [07:02:15]   done
94: [07:02:15] -------------------------------------
94: [07:02:15]     3D descriptors.
94:   evals: 89.1431 89.1458 178.289
94:   evals: 6.6164 150.43 150.43
94:   evals: 303.087 303.091 303.096
94: [07:02:15]   done
94: [07:02:15] -------------------------------------
94: [07:02:15]     3D descriptor edge cases.
94:   evals: 4.032 4.032 4.032
94: val1: 0
94: val2: 0
94: val3: 1
94: val0: 0
94: val1: 0
94:   evals: 0 0 0
94: val2: 0
94: val3: 0
94: val4: 0
94: [07:02:15]   done
94: [07:02:15] -------------------------------------
94: [07:02:15]     Inertial shape factor.
94: [07:02:15]   done
1/1 Test #94: test3D ...........................   Passed    0.70 sec
```

**Comment by greglandrum** [comment]
Yep, that looks good. I will clean up that branch and do a PR

**Comment by greglandrum** [comment]
@jaimergp one confirmation. 
Is the bit you're using in your CMakeLists.txt this:
```
if(NOT MSVC)
  if(RDK_OPTIMIZE_POPCNT)
    if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
      message("RDK_OPTIMIZE_POPCNT is not available on aarch64")
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "ppc64le")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mpopcntb")
    else()
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mpopcnt")
    endif()
  endif()
endif()
```
or did you modify it?

**Comment by jaimergp** [comment]
Yep, just to make sure, this is the relevant fragment in the current `HEAD` that provided those results:

```

option(RDK_BUILD_FUZZ_TARGETS "build the fuzz targets" OFF)

set(RDK_BOOST_VERSION "1.58.0")

if(NOT MSVC)
  if(RDK_OPTIMIZE_POPCNT)
    if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
      message("RDK_OPTIMIZE_POPCNT is not available on aarch64")
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "ppc64le")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mpopcntb")
    else()
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mpopcnt")
    endif()
  endif()
endif()

if(NOT UNIX OR APPLE)
  if(RDK_USE_BOOST_STACKTRACE)
    MESSAGE("Disabling boost::stacktrace on non-linux platform")
    set(RDK_USE_BOOST_STACKTRACE OFF)
  endif(RDK_USE_BOOST_STACKTRACE)
endif()
```

**Comment by jaimergp** [comment]
Greg, I am trying to build the new release for PPC now that the PR was merged, but I see this other error with CMake (maybe a build script mistake on my end):

```
CMake Error in CMakeLists.txt:
  Target "rdkit_base" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/conda/feedstock_root/build_artifacts/rdkit_1597318572834/work/PYTHON_NUMPY_INCLUDE_PATH-NOTFOUND"

  which is prefixed in the build directory
```

[More details here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=196853&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=350df31b-3291-5209-0bb7-031395f0baa1&l=682). Any idea?

**Comment by greglandrum** [comment]
@jaimergp it looks like it's having a problem finding/using numpy?
That's a bit odd because earlier in the build log it looks like it actually did install numpy.
I don't see anything obvious either in the build output or in the script.

**Comment by jaimergp** [comment]
FYI it's fixed now. I had to [manually specify the include path](https://github.com/conda-forge/rdkit-feedstock/blob/master/recipe/build.sh#L15) under `ppc64le` 🤷
