### ISSUE TITLE
Change coordinates for a molecule

### ISSUE THREAD

**Issue by francoep** [rdkit/rdkit#2413]
**Description:**

- RDKit Version: 2019.03.1dev1
- Platform: Linux 16.04

I have a molecule imported from a sdf file (mol), and I wish to set its coordinates to a different array. Is there a way to do this painlessly? Notably, I have an array of exact positions of which I want to set the array of positions of the atoms in mol to be this array of exact positions.

**Comment by greglandrum** [comment]
You would do this using the molecule's conformer... here's some untested pseudocode that may help:
```
  from rdkit.Geometry import Point3D
  conf = mol.GetConformer()
  for i in range(mol.GetNumAtoms()):
     x,y,z = new_atom_ps[i]
     conf.SetAtomPosition(i,Point3D(x,y,z))
```

**Comment by francoep** [comment]
Thanks for the pseudocode, it worked brilliantly (much better than a hacky workaround involving text replacements via MolToMolBlock)!

**Comment by testst2002** [comment]
Can I ask a question about it? I just started learning rdkit and would like to ask can I somehow make a Mol or MolBlock from Conformer after changing its cords. 
I need to make sdf file molecule before and after chaging coords, but I don't know how to do it.  And when I 'm trying to write molecule with changed coords,  it's with cords before changing.
Mb someone can help me with that.

**Comment by greglandrum** [comment]
@testst2002 please use the discussion tab to ask RDKit questions
