### ISSUE TITLE
can't import cPickle from rdkit.six.moves

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#2415]
`from rdkit.six.moves import cPickle` fails due to a recent change included in #2315 and affecting the bundled six module at line https://github.com/rdkit/rdkit/blob/master/rdkit/six.py#L209

Removing this module might be planned for the next patch release, so this issue may be just FYI (the change applied to rdkit.six looks like may have been unintended).

- RDKit Version: 2019.03.1
- Platform: linux

**Comment by greglandrum** [comment]
We almost certainly should remove `rdkit.six`, but that would probably be for the 2019.09 release.
How did you encounter this?

**Comment by rvianello** [comment]
Some internal rdkit addons have been importing six from rdkit for historical reasons and convenience, but I guess they could be quickly ported to use an independently installed six package (for now, until support for python 2 is dropped there too).

**Comment by ssrb19** [comment]
What is the final solution to this error? Is there an alternative command to import cPickle. I'm working on someone else's code where they used this import command. What would be an appropriate replacement?

**Comment by gedeck** [comment]
I don't think there is any good reason to use cpickle today. If you are using python 3, replace it with pickle.

https://stackoverflow.com/a/37138791

**Comment by gedeck** [comment]
@greglandrum Is there a reason to have this issue still open?

**Comment by greglandrum** [comment]
Nope. Closing it.
