### ISSUE TITLE
Compile failure on ArchLinux

### ISSUE THREAD

**Issue by baerbock** [rdkit/rdkit#2418]
**Description:**

- RDKit Version: 2019.03.1dev1
- Platform: ArchLinux w gcc 8.3.0 and Python 3.7.3 (which has LTO [by default](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/python))

Compilation fails due to:
`
lto1: fatal error: bytecode stream in file '/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a' generated with LTO version 7.0 instead of the expected 7.1`

More complete log at [Pastebin](https://pastebin.com/Wz9hu85u)

**Comment by greglandrum** [comment]
I don't use Arch, so it's hard to be sure, but that looks more like a problem with ArchLinux itself and not with the RDKit. The fact that it's complaining about a file provided by the system is an indicator for this

**Comment by baerbock** [comment]
@greglandrum I'm building in a clean chroot. This only contains the base system, python is installed freshly from repository before every installation.
