### ISSUE TITLE
Link to InChI is missing

### ISSUE THREAD

**Issue by chazanov** [rdkit/rdkit#2419]
As far as I know http://www.inchi-trust.org/download/105/INCHI-1-API.zip is needed for compiling RDKIT. Sadly the link is offline and I've couldn't find replacement.

May you please tell me the current link?

**Comment by bp-kelley** [comment]
It looks like they changed the url to:

https://www.inchi-trust.org/download/105/INCHI-1-SRC.zip

I won’t be able to test this until this evening.

If so that’s particularly annoying.
----
Brian Kelley
