### ISSUE TITLE
RemoveHs() does not remove all hydrogens.

### ISSUE THREAD

**Issue by paulaju** [rdkit/rdkit#2422]
**Description:**

- RDKit Version: 2019.03.1.
- Platform: Ubuntu 16.04 LTS
- Conda, Python 3.6.8

I have encountered a problem when removing hydrogen atoms from a molecule. The flag removeHs=True in functions for reading molecules from files sometimes leads to a different result than Chem.RemoveHs(). 

I have created a minimal working example:
https://gist.github.com/paulaju/0191760a4662373eeb3ff9ffc0019e2e

In my case, this led to problems when writing a molecule with supposedly all hydrogens removed to an SD file and reading it back in with PandasTools.LoadSDF, which actually does remove all hydrogens. The number of atoms then does not match the length of the atom property list which I have created using Chem.CreateAtomStringPropertyList().

**Comment by bp-kelley** [comment]
RemoveHs creates a new molecule with the hydrogens removed.

mol = Chem.RemoveHs(mol)

**Comment by greglandrum** [comment]
@paulaju : though I agree that it's confusing, this isn't completely unexpected behavior.
Here's a very simple example:
https://nbviewer.jupyter.org/gist/greglandrum/ac37dd84852b1c9eadb3445dc474cf1d

Essentially what's happening is that the perception of stereochemistry from 3D coordinates causes the bond to the H atom attached to the doubly bonded carbon to be wedged. `RemoveHs()` does not remove H atoms that have wedged bonds to them in case they are involved in setting stereochemistry.

In this case stereochemistry is not possible at the double bond, and there should be an easy way to clean this up. I don't think that there is, but I need to look into it a bit more.

**Comment by paulaju** [comment]
Hi @greglandrum,
thank you for your quick response. But why does this hydrogen get removed when reading the molecule from a file? Shouldn't these functions be consistent?

**Comment by greglandrum** [comment]
The hydrogen is removed before the stereochemistry perception that leads to the directional bond is done.
