### ISSUE TITLE
Check Smiles

### ISSUE THREAD

**Issue by Flora-Feng** [rdkit/rdkit#2430]
Hi
I am new in rdkit and I need some help here.
It costs a lot to catch unrecognized smiles by try except. Therefore, I wonder if there is a function to check whether the smiles can be recognized/processed by rdkit.
Example code:
try:
    Chem.SanitizeMol("O=C1NCNc2nc(C)nc12")
except:
    pass

**Comment by greglandrum** [comment]
If you're just trying to check whether or not the SMILES is syntactically valid (i.e. all rings/branches closed, no illegal atom types, etc), you can do:
```
m = Chem.MolFromSmiles(smi,sanitize=False)
if m is None:
  print('invalid')
```
If you want to know if the molecule is chemically reasonable by the RDKit's definition, the simplest is:
```
m = Chem.MolFromSmiles(smi)
if m is None:
  print('invalid')
```
The one that will likely run the fastest, but you'll only see real differences for molecules with multiple stereocenters, is:
```
m = Chem.MolFromSmiles(smi,sanitize=False)
if m is None:
  print('invalid SMILES')
else:
  try:
    Chem.SanitizeMol(m)
  except:
    print('invalid chemistry')
```

**Comment by autodataming** [comment]
could RDKit check the FormalCharge ?
```py
smi1 ="Cc1ccc(Br)c2c1CCC([NH2+2]Cc1ccccc1)C2"
smi2 ="Cc1ccc(Br)c2c1CCC([NH2+1]Cc1ccccc1)C2"
```


The above methods can't check the FormalCharge.
