### ISSUE TITLE
Issues about handling rings with multiple N

### ISSUE THREAD

**Issue by Flora-Feng** [rdkit/rdkit#2433]
I removed the protecting group of  "O=C(OC(C)(C)C)N1c2ccccc2C=N1"( using rxn.RunReactants((R,))) and I got this : 'c1ccc2nncc2c1'. This is a wrong smiles and I can't use it for further reaction or property calculations. 
Is there any good way to deal with it?

**Comment by greglandrum** [comment]
Did you run `Chem.SanitizeMol()` on the output of the reaction?http://rdkit.org/docs/GettingStartedInPython.html#chemical-reactions

**Comment by Flora-Feng** [comment]
No. 
Here is the code:
smi = "O=C(OC(C)(C)C)N1c2ccccc2C=N1"
mol = Chem.MolFromSmiles(smi)
smarts = 'O[C](=O)[#7:1]>>[#7:1]'
rxn=AllChem.ReactionFromSmarts(smarts)
ps = rxn.RunReactants((mol,))
Chem.MolToSmiles(ps[0][0]) 

And I got 'c1ccc2nncc2c1'

**Comment by Flora-Feng** [comment]
> Did you run `Chem.SanitizeMol()` on the output of the reaction?http://rdkit.org/docs/GettingStartedInPython.html#chemical-reactions

No.
Here is the code:
smi = "O=C(OC(C)(C)C)N1c2ccccc2C=N1"
mol = Chem.MolFromSmiles(smi)
smarts = 'OC[#7:1]>>[#7:1]'
rxn=AllChem.ReactionFromSmarts(smarts)
ps = rxn.RunReactants((mol,))
Chem.MolToSmiles(ps[0][0])

And I got 'c1ccc2nncc2c1'

**Comment by greglandrum** [comment]
Please do try doing that.

**Comment by Flora-Feng** [comment]
> Please do try doing that.

Work! Thanks a lot!
