### ISSUE TITLE
[Doc] Signatures of constructors of some classes are missing

### ISSUE THREAD

**Issue by e-kwsm** [rdkit/rdkit#2436]
**Description:**

- RDKit Version: 2019.03.1
- Platform: independent

For example, the docstring of `rdkit.Chem.rdmolfiles.SmilesMolSupplier.__init__` provides the following signature info: https://github.com/rdkit/rdkit/blob/89f769cd88e202de683b19dbcd50129e671e7af1/Code/GraphMol/Wrap/SmilesMolSupplier.cpp#L66-L85
But [its documentation page](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.SmilesMolSupplier) does not.

Also, the page wrongly renders (`blockquote` ends at the first line) the following line: https://github.com/rdkit/rdkit/blob/89f769cd88e202de683b19dbcd50129e671e7af1/Code/GraphMol/Wrap/SmilesMolSupplier.cpp#L61-L63

**Comment by greglandrum** [comment]
Confirmed. It looks like this is a Sphinx misconfiguration issue.
Should be pretty easy to fix.

**Comment by e-kwsm** [comment]
Thank you for your reply.

Additionally, I found another rendering error in "Examples of replacements" of [`rdkit.Chem.rdmolfiles.MolFromSmiles`](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.MolFromSmiles): EOLs are removed
https://github.com/rdkit/rdkit/blob/89f769cd88e202de683b19dbcd50129e671e7af1/Code/GraphMol/Wrap/rdmolfiles.cpp#L750-L754

Is this also due to Sphinx configuration?

**Comment by greglandrum** [comment]
Nope, that's a formatting problem in the docstring.
It's fine to capture it here though. I will try to fix all of these at once.

**Comment by e-kwsm** [comment]
Signatures of class constructors like [`rdkit.Chem.rdmolfiles.SmilesMolSupplier`](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.SmilesMolSupplier) are not still shown.
Due to lag?

**Comment by greglandrum** [comment]
Yes, I have not rebuilt the documentation. I will try to remember to do that after the 2019_03_3 release.
