### ISSUE TITLE
RDKit fails to parse SMILES if dot follows opening parenthesis

### ISSUE THREAD

**Issue by e-kwsm** [rdkit/rdkit#2442]
**Description:**

- RDKit Version: 2019.03.1
- Platform: Debian 9.9

[OpenSMILES](http://opensmiles.org/opensmiles.html#_disconnected_structures) specifies that 
> the syntax allows a dot most places a regular bond could appear (the exception is that a dot can’t appear before a ring-closure digit).

and allows a dot immediately after an opening parenthesis, e.g. `Oc1cc(.NCCO)ccc1`.
However, RDKit fails to parse it:

```python
from rdkit.Chem import MolFromSmiles, MolToSmiles
## All of the following SMILES represent phenol and 2-amino ethanol
# print(MolToSmiles(MolFromSmiles("Oc1ccccc1.NCCO")))    # OK
# print(MolToSmiles(MolFromSmiles("c1cc(O.NCCO)ccc1")))  # OK
print(MolToSmiles(MolFromSmiles("Oc1cc(.NCCO)ccc1")))    # error
```
gives
```
[17:34:48] SMILES Parse Error: syntax error while parsing: Oc1cc(.NCCO)ccc1
[17:34:48] SMILES Parse Error: Failed parsing SMILES 'Oc1cc(.NCCO)ccc1' for input: 'Oc1cc(.NCCO)ccc1'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolfiles.MolToSmiles(NoneType)
did not match C++ signature:
    MolToSmiles(RDKit::ROMol mol, bool isomericSmiles=True, bool kekuleSmiles=False, int rootedAtAtom=-1, bool canonical=True, bool allBondsExplicit=False, bool allHsExplicit=False, bool doRandom=False)
```

**Comment by greglandrum** [comment]
The RDKit does not currently claim to support OpenSMILES, so this isn't overly surprising.
Thanks for capturing it though.

**Comment by adalke** [comment]
There is an internal disagreement in the OpenSMILES spec. The grammar doesn't allow `C(.C)` even though it's present in the text.

This is because the person who wrote the text is different from the person who wrote the grammar.
