### ISSUE TITLE
Too-closed geometry is generated when molecule is constructed from SMILES with period (disconnected structures)

### ISSUE THREAD

**Issue by e-kwsm** [rdkit/rdkit#2446]
**Description:**

Built from [tarball](https://github.com/rdkit/rdkit/archive/Release_2019_03_1.tar.gz), with GCC 6.3.0, Python 3.7.3, NumPy 1.16.3, boost 1.70.0, and SWIG 3.0.10.

- RDKit Version: 2019.03.1
- Platform: Debian 9.9

```python
from rdkit import Chem
from rdkit.Chem import AllChem

m = Chem.AddHs(Chem.MolFromSmiles('N.N'))
AllChem.EmbedMolecule(m)
r = AllChem.MMFFOptimizeMolecule(m, maxIters=1000)
if r != 0:
    raise RuntimeError('not converged')
print(Chem.MolToMolBlock(m))
```

gives, e.g.,

```

     RDKit          3D

  8  6  0  0  0  0  0  0  0  0999 V2000
    0.0007   -0.0052    0.2955 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0003    0.0005    0.2956 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.8972   -0.2768   -0.1056 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6903   -0.6360   -0.1082 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2076    0.9181   -0.0817 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5062   -0.7918   -0.0978 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4323    0.8341   -0.1004 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.9388   -0.0428   -0.0974 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  3  1  0
  1  4  1  0
  1  5  1  0
  2  6  1  0
  2  7  1  0
  2  8  1  0
M  END


```

Two ammonia molecules are too close:
![two-ammonias](https://user-images.githubusercontent.com/11627708/57613725-9111c480-75b2-11e9-90f6-6e30b3fa8b47.png)

**Comment by greglandrum** [comment]
This is by design.
The RDKit's conformation generation process for molecules with disconnected fragments embeds the fragments independently and then recombines their coordinates into a single molecule. It makes no attempt to take one fragment's location into account when embedding the other.

**Comment by e-kwsm** [comment]
I see.
But then  `MMFFOptimizeMolecule` etc should warn that disconnected fragments are not supported; at present they just return `0`.
