### ISSUE TITLE
ReadTheDocs is not up-to-date

### ISSUE THREAD

**Issue by e-kwsm** [rdkit/rdkit#2447]
The [Documentation](http://www.rdkit.org/docs/index.html) is versioned as 2019.03.1, but [ReadTheDocs](https://rdkit.readthedocs.io/en/latest/) is 2017.09.1.dev1.

**Comment by greglandrum** [comment]
Thanks for pointing that out. I've made the 2019_03 build the default:
https://rdkit.readthedocs.io/

**Comment by e-kwsm** [comment]
Thank you!
