### ISSUE TITLE
Error using GetImplicitValence

### ISSUE THREAD

**Issue by agdecm** [rdkit/rdkit#2448]
**Description:**

- RDKit Version: 2019.03.1
- Platform: Windows 10

```
Mol = Chem.MolFromSmarts('[CH3;X4]')

for atom in Mol.GetAtoms():
    print(atom.GetImplicitValence())
    
0

```

**Comment by greglandrum** [comment]
Implicit valence is a property that is perceived based on standard chemistry rules for normal atoms. These rules do not apply for atoms constructed from SMARTS.

**Comment by simonmb** [comment]
Somehow for the following setup it works:

- Version: 2017.09.3
- Platform: Windows 10
- Python 2.7


```
mol = Chem.MolFromSmarts('[CH3;X4]')
mol.UpdatePropertyCache(strict = False)
mol.GetAtomWithIdx(0).GetImplicitValence() #returns 4
```

**Comment by greglandrum** [comment]
That behavior was changed as part of this PR: https://github.com/rdkit/rdkit/pull/1716
It is still possible to get the RDKit to assign implicit Hs to atoms constructed from SMARTS if the atom doesn't contain any type of H query:
```
In [11]: m = Chem.MolFromSmarts('[C;X4]')                                                              

In [12]: m.UpdatePropertyCache(strict=False)                                                           

In [13]: m.GetAtomWithIdx(0).GetImplicitValence()                                                      
Out[13]: 4
```
I view this is a bug, but we won't ever be able to catch every possible "you're doing something you shouldn't do" case.

It is, almost always, a bad idea to do chemistry perception on molecules constructed from SMARTS.

**Comment by simonmb** [comment]
@greglandrum 
Is there an rdkit way to get the implicit valence of an atom from a molecule constructed based on a SMARTS ignoring the Hs in the query? Obviously I could try to parse it myself, but maybe there is a more elegant way to do it.

**Comment by greglandrum** [comment]
I'm not sure I understand the first question.

What would you expect the implicit valence of the first atom in this SMARTS to be?
`[C]N`
What about this one:
`[C;$(C(=O)O)]N`

**Comment by simonmb** [comment]
```
[C]N : I would expect 3
[C;$(C(=O)O)]N: I would expect 0
```

As for the conditional example, you are right, it is not possible to say in these cases.

@agdecm and I are working on a project together were we need to know the number of available bonds. That is actually our goal.
e.g.
```
[CH3;X4] => 1
[BrH0] => 1
[CH0](=O)[OH0] = > 2
[CH0]=[CH0] => 4
```

This is actually also related to what I found on issue: #1978

**Comment by greglandrum** [comment]
@simonmb The queries you've provided are all relatively simple; the problem may be solvable here.

Do all of your SMARTS look like that or do you have more complex examples that include `or` queries (i.e. commas) or recursion?

**Comment by simonmb** [comment]
We have decided not to support `or` queries. But we have recursion.
e.g.
```
[$(Cl[C]=[C])]
[OH0;!$(OC=O);!R][CH2;!R][CH2;!R][OH]
```

**Comment by greglandrum** [comment]
The recursion is going to be harder to manage, but for the others you can use the DescribeQuery() method on atoms and then parse that (easy) to figure out if there's an H query:
```
>>> m = Chem.MolFromSmarts('[CH3;X4][$(OCO)]')                                                         
>>> a0 = m.GetAtomWithIdx(0)                                                                           
>>> a1 = m.GetAtomWithIdx(1)                                                                           
>>> print(a0.DescribeQuery())                                                                          
AtomAnd
  AtomAnd
    AtomType 6 = val
    AtomHCount 3 = val
  AtomTotalDegree 4 = val
```
for recursion you're probably going to have to do something like this:
```
>>> sma = a1.GetSmarts()                                                                               
>>> print(sma)                                                                                         
[$(OCO)]
>>> nsma = re.search(r'\$\((.*?)\)',sma).groups()[0]                                                   
>>> print(nsma)                                                                                        
OCO
>>> nmol = Chem.MolFromSmarts(nsma)                                                                    
>>> na0 = nmol.GetAtomWithIdx(0)                                                                       
```
and then work with that.

To figure out the "accounted for" valence you'll need to call `m.UpdatePropertyCache(strict=False)` and then use the `GetExplicitValence()` method on the atoms. This is mostly safe with SMARTS since it doesn't require chemistry perception. The biggest risk with this is that contributions of unspecified bonds to the explicit valence. In SMARTS an unspecified bond is "single or double". The RDKit mostly handles this properly, but it's very easy to find cases where it's wrong.
```
>>> m2 = Chem.MolFromSmarts('ccc')                                                                     
>>> m2.UpdatePropertyCache(strict=False)                                                               
>>> m2.GetAtomWithIdx(1).GetExplicitValence()                                                          
3
>>> m3 = Chem.MolFromSmarts('CCC')                                                                     
>>> m3.UpdatePropertyCache()                                                                           
>>> m3.GetAtomWithIdx(1).GetExplicitValence()                                                          
2
>>> m4 = Chem.MolFromSmarts('cCc')                                                                     
>>> m4.UpdatePropertyCache()                                                                           
>>> m4.GetAtomWithIdx(1).GetExplicitValence()                                                          
2
```


That was a bunch of information, hopefully it points in the right direction and has some useful bits... follow up if not.

**Comment by simonmb** [comment]
Thanks, we had been developing something similar also iterating over the atoms, but your way is a bit safer. Especially about how to get the number of Hs in a query.

Have you been able to look into the related issue #1978? If I understand correctly, this should be fixable in a similar manner.

**Comment by bp-kelley** [comment]
I’ve dealt with a similar issue in the past, we cheated and ran the queries on our internal dB and a sampling from pub chem and used the hydrogen counts of the hits as a proxy.

We then took the complicated ones and filtered them by hand to modify the original queries by looking at the h counts of the hits.  This is probably not what you want, but we found it 90+% effective.

**Comment by simonmb** [comment]
But you are talking about SMILES, right? We are more interested in SMARTS.

Gesendet mit TypeApp<http://www.typeapp.com/r?b=14870>
Am 14. Mai 2019, um 18:22, Brian Kelley <notifications@github.com<mailto:notifications@github.com>> schrieb:

I’ve dealt with a similar issue in the past, we cheated and ran the queries on our internal dB and a sampling from pub chem and used the hydrogen counts of the hits as a proxy.

We then took the complicated ones and filtered them by hand to modify the original queries by looking at the h counts of the hits. This is probably not what you want, but we found it 90+% effective.

**Comment by bp-kelley** [comment]
No, we took our smarts patterns, ran them against “real” molecules and then back propagated the implicit hydrogens of the matches.  This data was used to modify the smarts pattern’s acceptable Hs to only except the hits we liked.   I’m making an assumption of what you really want here, and I could easily be wrong.

**Comment by bp-kelley** [comment]
( actually back propagated  both implicit and explicit )

**Comment by greglandrum** [comment]
I think the right answer here would really be to implement the atom-type fingerprints that are used in the SMARTS matching work from the Rarey group (this really is a nice piece of work). I believe the details of the algorithm are in the supplementary material. The paper has apparently been accepted; once it's online we can take a look and think about how much work it would be.

**Comment by greglandrum** [comment]
@simonmb: I haven't had a chance to look into #1978 
I will try to do that today/tomorrow, but no guarantees.

**Comment by simonmb** [comment]
Yes, since I am based in Hamburg, I have also been in contact with them and I know they will publish soon. It would be good if the Valence/Hydrogens could be set according to the SMARTS. In the case of conditional SMARTS have them return something like `None `or `-1` or `Unspecified` and in the case the value can be calculated set the property to the correct value.

I am working on an algorithm that uses the calculated properties of the SMARTS, for example to match if one SMARTS is a subset of another SMARTS. Something also the Rarey group is working on. This is the relation to #1978, as it also has to do with the correct setting of the Hs.

**Comment by simonmb** [comment]
**Description**
- Version: 2019.03.1
- Platform: Windows 10
- Python 3.7

I noticed the following while testing what you recommended:
```
m = Chem.MolFromSmarts('[C;X4]')
m.UpdatePropertyCache(strict=False)
m.GetAtomWithIdx(0).GetImplicitValence()
returns 4
```
However, the following behaves differently:
```
m = Chem.MolFromSmarts('[CH;X4]')
m.UpdatePropertyCache(strict=False)
m.GetAtomWithIdx(0).GetImplicitValence()
returns 0
```

How can I get the implicit valence in the second case?

**Comment by greglandrum** [comment]
If anything I think the first result is the problem here.
Atoms in a SMARTS really shouldn't have implicit valences.

**Comment by simonmb** [comment]
Just for your Info, the paper by Rarey's group is out:
https://pubs.acs.org/doi/10.1021/acs.jcim.9b00250

Another one interesting:
https://pubs.acs.org/doi/10.1021/acs.jcim.8b00704

**Comment by d-b-w** [comment]
Please move further questions to the "discussion" tab.
