### ISSUE TITLE
Undefined symbol rdchem.so (_ZNK5RDKit14SubstanceGroup13getIndexInMolEv)

### ISSUE THREAD

**Issue by cddt** [rdkit/rdkit#2456]
**Description:**

- RDKit Version: 2018.03.2
- Platform: Fedora 29, kernel 5.0.16

Error indicates an undefined symbol in rdchem.so (_ZNK5RDKit14SubstanceGroup13getIndexInMolEv). It is not clear how to troubleshoot this error. 

```
In [1]: import rdkit.Chem.rdchem                                                
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-bc1424dcc0c9> in <module>
----> 1 import rdkit.Chem.rdchem

~/temp/rdkit/rdkit/Chem/__init__.py in <module>
     18 from rdkit import DataStructs
     19 from rdkit.Geometry import rdGeometry
---> 20 from rdkit.Chem import rdchem
     21 _HasSubstructMatchStr = rdchem._HasSubstructMatchStr
     22 from rdkit.Chem.rdchem import *

ImportError: /home/cddt/temp/rdkit/rdkit/Chem/rdchem.so: undefined symbol: _ZNK5RDKit14SubstanceGroup13getIndexInMolEv

```

**Comment by cddt** [comment]
Additional information: 

    $ ldd /home/cddt/temp/rdkit/rdkit/Chem/rdchem.so
	linux-vdso.so.1 (0x00007ffff87f0000)
	libRDKitChemTransforms.so.1 => /lib64/libRDKitChemTransforms.so.1 (0x00007f33210c7000)
	libRDKitSubstructMatch.so.1 => /lib64/libRDKitSubstructMatch.so.1 (0x00007f332109e000)
	libRDKitRDBoost.so.1 => /lib64/libRDKitRDBoost.so.1 (0x00007f3321099000)
	libpython3.7m.so.1.0 => /lib64/libpython3.7m.so.1.0 (0x00007f3320d1e000)
	libboost_python3.so.1.66.0 => /lib64/libboost_python3.so.1.66.0 (0x00007f3320cd6000)
	libboost_serialization.so.1.66.0 => /lib64/libboost_serialization.so.1.66.0 (0x00007f3320c93000)
	libRDKitSmilesParse.so.1 => /lib64/libRDKitSmilesParse.so.1 (0x00007f3320c1e000)
	libRDKitGraphMol.so.1 => /lib64/libRDKitGraphMol.so.1 (0x00007f3320abb000)
	libRDKitRDGeometryLib.so.1 => /lib64/libRDKitRDGeometryLib.so.1 (0x00007f3320a9a000)
	libRDKitDataStructs.so.1 => /lib64/libRDKitDataStructs.so.1 (0x00007f3320991000)
	libRDKitRDGeneral.so.1 => /lib64/libRDKitRDGeneral.so.1 (0x00007f3320974000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3320952000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f33207b8000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f3320634000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3320619000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f3320453000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f33213b9000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f3320417000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f3320411000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f332040a000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f3320400000)

**Comment by greglandrum** [comment]
It's suspicious that the python module is in `/home/cddt/temp/rdkit/rdkit/Chem/` but it's picking up RDKit libraries from `/lib64/`. Could it be that you have an older version of the RDKit installed on your machine but that you're using a newer build? 

If so, try updating your LD_LIBRARY_PATH so that it points to ``/home/cddt/temp/rdkit/lib`

**Comment by cddt** [comment]
Thanks, turns out I did have an old version from the distribution. I removed it and updated LD_LIBRARY_PATH. 

Now I have the error: 
```
In [1]: import rdkit.Chem.rdchem                                                
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-bc1424dcc0c9> in <module>
----> 1 import rdkit.Chem.rdchem

~/temp/rdkit/rdkit/__init__.py in <module>
      1 try:
----> 2   from .rdBase import rdkitVersion as __version__
      3 except ImportError:
      4   __version__ = 'Unknown'
      5   raise

ImportError: libRDKitRDBoost.so.1: cannot open shared object file: No such file or directory
```

However it seems to be linked correctly: 
```
$ ldd /home/cddt/temp/rdkit/rdkit/rdBase.so
	linux-vdso.so.1 (0x00007ffeb7f32000)
	libRDKitRDBoost.so.1 => /home/cddt/temp/rdkit/lib/libRDKitRDBoost.so.1 (0x00007f3db79ab000)
	libpython3.7m.so.1.0 => /lib64/libpython3.7m.so.1.0 (0x00007f3db7606000)
	libboost_python3.so.1.66.0 => /lib64/libboost_python3.so.1.66.0 (0x00007f3db75be000)
	libboost_serialization.so.1.66.0 => /lib64/libboost_serialization.so.1.66.0 (0x00007f3db757b000)
	libRDKitRDGeneral.so.1 => /home/cddt/temp/rdkit/lib/libRDKitRDGeneral.so.1 (0x00007f3db755e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3db753c000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f3db73a2000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f3db721e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3db7203000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f3db703d000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f3db7001000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f3db6ffb000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f3db6ff4000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f3db6fea000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3db7ab4000)
```

Is it necessary to rebuild?

**Comment by greglandrum** [comment]
I don't think a rebuild would help.
Is the file `/home/cddt/temp/rdkit/lib/libRDKitRDBoost.so.1` actually there?
Try an `ls -l` on that file

**Comment by cddt** [comment]
It's a symlink to `libRDKitRDBoost.so.1.2019.09.1dev1`: 

```
$ ls -l libRDKitRDBoost.so*
lrwxrwxrwx. 1 cddt cddt    20 May 19 20:07 libRDKitRDBoost.so -> libRDKitRDBoost.so.1
lrwxrwxrwx. 1 cddt cddt    34 May 19 20:07 libRDKitRDBoost.so.1 -> libRDKitRDBoost.so.1.2019.09.1dev1
-rwxr-xr-x. 1 cddt cddt 18536 May 19 19:56 libRDKitRDBoost.so.1.2019.09.1dev1
```

**Comment by cddt** [comment]
I fixed the above by updating PYTHONPATH, LD_LIBRARY_PATH, and RDBASE in `~./bashrc` - I had failed to make the changes permanent previously. 

Thank you for your help @greglandrum , I would not have been able to solve this without it!

**Comment by greglandrum** [comment]
Glad you cleared it up.
