### ISSUE TITLE
module 'rdkit.Chem' has no attribute 'Draw'

### ISSUE THREAD

**Issue by dingye18** [rdkit/rdkit#2458]
**Description:**

- RDKit Version: 2019.03.02
- Platform: macOS Mojave

When I used 'rdkit.Chem.Draw.MolToFile(mol)' , it returns an error of moduld 'rdkit.Chem' has no attribute 'Draw'

```
import rdkit
mol = Chem.MolFromSmiles('c1ccc2c(c1)c(ncn2)Nc3cccc(c3)C(F)(F)F')
rdkit.Chem.Draw.MolToFile(mol)
```

**Comment by greglandrum** [comment]
Try doing: `from rdkit.Chem import Draw`

**Comment by dingye18** [comment]
Wow, thanks very much. It works.
