### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by yshen22** [rdkit/rdkit#2468]
I was going to install rdkit for my native python in Ubuntu by following the steps in https://www.rdkit.org/docs/Install.html:
```
 Linux x86_64: Python 3 environment
The following commands will create a development environment for Linux x86_64 and Python 3.

Start by downloading the latest anaconda installer from Anaconda and install it. Then, install the required packages:

bash Anaconda3-5.2.0-x86_64.sh
conda install -y cmake cairo pillow eigen pkg-config
conda install -y boost-cpp boost py-boost
Numpy and matplotlib are already part of the base installation of anaconda. Due to the latest boost libraries being currently built with a GLIBC version higher than the default in anaconda, we need to update to a more recent version:

conda install -y gxx_linux-64
At this point, you should be able to clone the RDKit repository to the desired build location, and start the build. Please consider that it is necessary to indicate the path to the numpy headers for RDKit to find them, since anaconda hides them inside the numpy package:

git clone https://github.com/rdkit/rdkit.git
cd rdkit
mkdir build && cd build
cmake .. -DPy_ENABLE_SHARED=1 \
	-DRDK_INSTALL_INTREE=ON \
	-DRDK_INSTALL_STATIC_LIBS=OFF \
	-DRDK_BUILD_CPP_TESTS=ON \
	-DPYTHON_NUMPY_INCLUDE_PATH="$CONDA_PREFIX/lib/python3.6/site-packages/numpy/core/include" \
	-DBOOST_ROOT="$CONDA_PREFIX"
And finally, make, make install and ctest
```  
I have successfully complete cmake and make step. But I failed in make install step.
Here is the information:
 Install the project...
-- Install configuration: "Release"
CMake Error at CoordGen/cmake_install.cmake:136 (file):
  file INSTALL cannot find
  "/media/MyDataStor1/rdkit/lib/libRDKitcoordgen.so.1.2019.03.1b1".
Call Stack (most recent call first):
  cmake_install.cmake:40 (include)
 Very thankful for your help

**Comment by greglandrum** [comment]
Can you please share the exact command you used when you did `make install` and the name of the directory where you executed that command?
Also the output of: `ls -l /media/MyDataStor1/rdkit/` and `ls -l /media/MyDataStor1/rdkit/lib` just to make sure that those exist.

**Comment by yshen22** [comment]
Actually libRDKitcoordgen.so.1.2019.03.1b1 exists after make. But was deleted during make install, I use brute force method to set it as only readable file. And the problem resolved. The install is complete. But is there any bug in make install?

**Comment by greglandrum** [comment]
I haven't seen a problem like this before. When you did `make install` it must have copied the file somewhere. If you want to track it down, you could do `VERBOSE=1 make install` to see where it put the file.
