### ISSUE TITLE
Make Chem.PropertyPickleOptions.AllProps default

### ISSUE THREAD

**Issue by ericmjonas** [rdkit/rdkit#2470]
In the latest version of RDKit, I find that setting
```
Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)
```
is necessary to get both my Pickle and `mol.ToBinary()` properties to be saved. I find this behavior counterintuitive, and am curious if there's a reason for it. I had expected `ToBinary()` especially to provide a forwards-compatible representation of everything in my molecule, including a lot of the metadata I'm sticking onto these molecules. 

Would it be possible to set the default properties to pickle all properties, or is there a reason for this _not_ being the default?

**Comment by greglandrum** [comment]
There are really two reasons for the current behavior:
1) You didn't used to be able to pickle properties and we didn't want to change the behavior of old code when we added that feature
2) Including properties in the output results in larger pickle files and longer pickling/depickling times.

We could certainly change the default behavior, but it's worth thinking about carefully and seeing how much of a factor point 2 above really is.

**Comment by bp-kelley** [comment]
We could make the default not pickle private data, just public.  This shouldn’t make the pickles bigger unless someone explicitly added data

**Comment by greglandrum** [comment]
It will affect every molecule that comes out of an SD file that has data in it.

**Comment by ericmjonas** [comment]
I'm incredibly sympathetic to the backwards compatibility concerns. I just have found it surprising that `pickle.loads(pickle.dumps(mol))` discards all my carefully hand-added metadata, which is the main thing I care about.

**Comment by bp-kelley** [comment]
@greglandrum Perhaps we could not pickle public string values in RDProps to avoid duplication?

**Comment by mikemhenry** [comment]
Are these two caveats true still? 

> 1. You didn't used to be able to pickle properties and we didn't want to change the behavior of old code when we added that feature
> 2. Including properties in the output results in larger pickle files and longer pickling/depickling times.

We are considering setting `Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)` to fix some issues we have when using rdkit objects with multiprocess loosing some properties on pickling. We just wanted to double-check to make sure other things didn't change in the last ~7 years.

**Comment by bp-kelley** [comment]
Both of those statements are true.  There is one caveat, some properties will actually be “double pickled” with this setting.  At some point we should remove this behavior and make property pickling the default and have it be opt out.   I have always found the default behavior surprising
