### ISSUE TITLE
 ERROR: Could not find a version that satisfies the requirement rdkit

### ISSUE THREAD

**Issue by aslankims** [rdkit/rdkit#2478]
I am trying to install rdkit on my platform (PycharmProjects).

Even if I spent a whole day thru googling, I cannot figure out the following error.

(tensorflow_study) C:\Users\aslan\PycharmProjects\Textbook2>pip install rdkit
Collecting rdkit
  ERROR: Could not find a version that satisfies the requirement rdkit (from versions: none)
ERROR: No matching distribution found for rdkit

conda version: 4.6.14
python version: 3.7.3
PyCharm release: 2019.1.1

Please help me to continue my tensorflow study.
Many thanks,
Dong-Ho

**Comment by CKannas** [comment]
Hi Dong-Ho,

If I'm correct RDKit does not have a package distributed with pip.
The best approach is to get it via conda if you work with a conda
environment.
Otherwise you will have to build it from source.

Best Regards,

Christos

Christos Kannas

Scientific Software Developer (Cheminformatics)

**Comment by aslankims** [comment]
Hi, Christos

Thank you for the comment.
Now I am trying to install rdkit with conda as follows,
================================================================
(tensorflow_study) C:\Users\aslan\PycharmProjects\Textbook2>conda install --use-local rdkit
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - rdkit

Current channels:
=================================================================

Still, I am struggling to figure out.
Could you help to go further?

Thanks a lot!
Dong-Ho

**Comment by bp-kelley** [comment]
You may need to install from the rdkit channel:

conda install -c rdkit rdkit

**Comment by aslankims** [comment]
Dear bp-kelley,

Thank you! now, I can play with rdkit and deepchem.

**Comment by gabyshrivastava** [comment]
using this command on anaconda prompt (as an administrator) 

conda install -c rdkit rdkit 


still i am getting error 

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - rdkit -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|3.4.*']

Your python: python=3.8

**Comment by greglandrum** [comment]
We are now suggesting that you install the rdkit from the conda-forge channel: `conda install -c conda-forge rdkit`.
The conda forge builds are automated and are available for more versions of python and operating systems.
