### ISSUE TITLE
computeGasteigerCharges quality of life improvement for python api

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#2480]
**Description:**

- RDKit Version:
- Platform:

An overload of computeGasteigerCharges takes a raw pointer:

```
void computeGasteigerCharges(const ROMol *mol, int nIter,
                             bool throwOnParamFailure) {
  PRECONDITION(mol, "bad molecule");
  computeGasteigerCharges(*mol, nIter, throwOnParamFailure);
}
```

This causes some bad confusions in python land:

```
>>> AllChem.ComputeGasteigerCharges(None)
[17:35:02] 
****
Pre-condition Violation
bad molecule
```

I suggest we deprecate this function or, at a minimum, change the python wrapper to use the const reference to reject Nones as input.  I think this will be more understandable to the end-users.

**Comment by greglandrum** [comment]
Agreed. Switching the python wrapper to use the const reference would make sense.

**Comment by bp-kelley** [comment]
@greglandrum Did this every get resolved?

**Comment by greglandrum** [comment]
Nope
