### ISSUE TITLE
What does it mean to kekulize a molecule?

### ISSUE THREAD

**Issue by nbro** [rdkit/rdkit#2483]
I am completely new to RDKit. I am reading the [documentation](https://www.rdkit.org/docs/GettingStartedInPython.html). At a certain point, it states

> displays something like: [12:20:41] Can't kekulize mol

What does it mean to kekulise a molecule?

**Comment by jir322** [comment]
http://bfy.tw/O08U

first hit is a nice slideshare

John Irwin
UCSF Pharmaceutical Chemistry
http://irwinlab.compbio.ucsf.edu

**Comment by nbro** [comment]
@jir322 I know how to search on Google. However, note that I am not the only one satisfied with Google's answers: https://chemistry.stackexchange.com/q/116498/79033. It would be more useful if you provide your own answer with your own words.

**Comment by greglandrum** [comment]
github issues are not a great place for questions like this, which is why the issue template suggests asking support questions on the mailing list.
If the answer on stackexchange doesn't answer the question for you, please subscribe to the rdkit-discuss mailing list and ask there.

**Comment by nbro** [comment]
@greglandrum I think it is a great place to discuss this, given that the documentation of RDKit does not explain this.

**Comment by greglandrum** [comment]
It's unfortunate that we disagree, but this is the model that I've chosen for providing RDKit support.

**Comment by Pixelatory** [comment]
This post is old, but I was able to find it as the first result of a search "what is kekulization". For any future viewers, the following may be of help: http://archive.today/qSx2d (archived the article for consistency). The follow-up to that article is here: http://archive.today/Fr2IP.
