### ISSUE TITLE
2D Depiction clipped atom highlighting

### ISSUE THREAD

**Issue by DavidACosgrove** [rdkit/rdkit#2486]
When highlighting atoms in the 2D depiction, atoms that are close to the edge of the picture have the circles of the highlight clipped.  The scale of the picture isn't taking account of the extra space required by the circles.

- RDKit Version: 2019.03.1
- Platform: MacOS, Linux

Example code:
![test1](https://user-images.githubusercontent.com/9198870/59147841-85ba8900-89f8-11e9-9a44-c7f19871208c.png)

#!/usr/bin/env python

from rdkit import Chem
from rdkit.Chem import rdDepictor, Draw

mol = Chem.MolFromSmiles('c1ccccc1Cl')

rdDepictor.SetPreferCoordGen(True)
rdDepictor.Compute2DCoords(mol)
d = Draw.MolDraw2DCairo(250, 200)

highlight_atoms = mol.GetSubstructMatch(Chem.MolFromSmarts('c1ccccc1'))
d.DrawMolecule(mol, highlightAtoms=highlight_atoms)
d.FinishDrawing()

with open('test1.png', 'wb') as f:
    f.write(d.GetDrawingText())

**Comment by greglandrum** [comment]
Fixed in #2487
