### ISSUE TITLE
The SMART pattern in pattern fingerprints

### ISSUE THREAD

**Issue by Wenbo723** [rdkit/rdkit#2494]
Hi there,

As mentioned in a submitted issue before, the pattern fingerprint was recommended for screening substructures.  And it seems to me that the structural pattern of each bit in fingerprint should be pre-defined, like MACCS fingerprints. However, I could not find useful information about the exact definition of each bit in pattern fingerprints. So is there a way to understand the SMART pattern corresponding to each bit?

By the way, here is my code to generate pattern fingerprint:

```
from rdkit import Chem
from rdkit.Chem.rdmolops import PatternFingerprint
smi = 'CCCc1nn(C)c2C(=O)NC(=Nc12)c3cc(ccc3OCC)S(=O)(=O)N4CCN(C)CC4'
m = Chem.MolFromSmiles(smi)
fp = PatternFingerprint(m)
print (fp.ToBitString())

```
Thanks a lot!

**Comment by greglandrum** [comment]
Hi,
The Pattern fingerprint works differently from MACCS. Instead of having a fixed SMARTS for each bit, the Pattern fingerprint has a small number of very generic patterns. When one of these matches the molecule, the specific atoms and bonds it matches are hashed to give a bit ID. There's an added complication that bits are also set for the generic patterns themselves . This last part makes it more or less impossible to provide reliable information about which atoms contribute to a particular bit.
I really should write this up for the documentation.

**Comment by Wenbo723** [comment]
Okay, I see. Much appreciate for your rapidly answer.

However, sometimes there is a need to generate as many substructures/patterns as possible, and then find out whether these substructures exist in a set of molecules.  I think using fingerprints that are pre-defined for each bit is the fastest way. But MACCS only has 166 bits, which carries little information. Another way I think about it is that, artificially define a number of substructures, and find whether they exist in molecules. But how to define is still a problem. Or maybe there exists a database of all kinds of SMART patterns? Anyway, this way should be time-consuming. So I wonder whether there is a way to implement this function...

Many thanks again! And hope you can share some ideas about this.

**Comment by greglandrum** [comment]
I'm not quite sure what you're trying to do, but there are many ways to generate libraries of fragments to search through. Finding interesting ones is a different matter entirely. :-)

Here's one piece from the RDKit documentation that might be helpful in terms of starting to find a collection of fragments: https://www.rdkit.org/docs/GettingStartedInPython.html#molecular-fragments

**Comment by Wenbo723** [comment]
Got it, thank you!

**Comment by biingxiing** [comment]
@greglandrum hello，Could you tell us more about how this PatternFingerprint was generated, thank you very much

**Comment by biingxiing** [comment]
> Hi, The Pattern fingerprint works differently from MACCS. Instead of having a fixed SMARTS for each bit, the Pattern fingerprint has a small number of very generic patterns. When one of these matches the molecule, the specific atoms and bonds it matches are hashed to give a bit ID. There's an added complication that bits are also set for the generic patterns themselves . This last part makes it more or less impossible to provide reliable information about which atoms contribute to a particular bit. I really should write this up for the documentation.

Have you finish your documentation of PatternFingerprint? It is really hard for me to read the source code, hope to get your documentation.

**Comment by greglandrum** [comment]
> > Hi, The Pattern fingerprint works differently from MACCS. Instead of having a fixed SMARTS for each bit, the Pattern fingerprint has a small number of very generic patterns. When one of these matches the molecule, the specific atoms and bonds it matches are hashed to give a bit ID. There's an added complication that bits are also set for the generic patterns themselves . This last part makes it more or less impossible to provide reliable information about which atoms contribute to a particular bit. I really should write this up for the documentation.
> 
> Have you finish your documentation of PatternFingerprint? It is really hard for me to read the source code, hope to get your documentation.

https://www.rdkit.org/docs/RDKit_Book.html#pattern-fingerprints
