### ISSUE TITLE
GetHybridization() producing incorrect hybridization when using GetAtomWithIdx()

### ISSUE THREAD

**Issue by ghost** [rdkit/rdkit#2503]
**Description:**
![testImg](https://user-images.githubusercontent.com/38115070/59725619-1f491e00-91e3-11e9-9140-c2e741e2785f.png)

When using the Chem.rdchem sub module and selecting an atom, using the GetHydribization() function returns the incorrect hybridization value. I drew the same mol object using rdkit.Chem.Draw. The attachted image shows the correct molecule, but still returns the incorrect hybridization of the final oxygen in the SMILES chain.

- RDKit Version: 2019.03.2
- Platform: Ubuntu 18.04

```
import rdkit
from rdkit import Chem
from rdkit.Chem import rdchem
from rdkit.Chem import Draw


mol = Chem.MolFromSmiles("Cc1ccc(cc1)C(=O)O")

index = 0 
while index <= mol.GetNumAtoms()-1:
    atomObj = mol.GetAtomWithIdx(index) 
    symbol = str(atomObj.GetSymbol())
    Hybridization = str(atomObj.GetHybridization())
    print(symbol + " hybridization: " + Hybridization)
    index+=1

img = Draw.MolToFile(mol,"testImg.png")

```

The output was 
```
C hybridization: SP3
C hybridization: SP2
C hybridization: SP2
C hybridization: SP2
C hybridization: SP2
C hybridization: SP2
C hybridization: SP2
C hybridization: SP2
O hybridization: SP2
O hybridization: SP2
```

I surmise this is a bug because this has occurred for many different SMILES codes, unless it is something incorrect in my code or implementation of rdkit.

**Comment by greglandrum** [comment]
This is the intended behavior. The RDKit considers both C-O bonds to be conjugated (actually all the bonds in this molecule are conjugated), and so it assigns SP2 hybridization to both O atoms.
