### ISSUE TITLE
Error in SDMolSupplier with isocyano - note previous issue closed due to accident

### ISSUE THREAD

**Issue by wgmallard** [rdkit/rdkit#2505]
**Description:**
he Chem.SDMolSupplier seems to fail when there is an isocyano group in the molecule. The data is in the SDF file in a form of -N#C, so the valence of the N is 4 and the C is 3. In a set of 38285 compounds, only 38278 were read and all of the missing molecules had the isocyano group.

- RDKit Version:2019.03.2
- Platform:Windows 10

he Chem.SDMolSupplier seems to fail when there is an isocyano group in the molecule. The data is in the SDF file in a form of -N#C, so the valence of the N is 4 and the C is 3. In a set of 38285 compounds, only 38278 were read and all of the missing molecules had the isocyano group.

```
The code is not useful without the data file.  But please send a note and I can create a small data file and send it along.
```
The code itself is:
from rdkit import Chem
from rdkit.Chem.rdMolDescriptors import CalcMolFormula
from rdkit.Chem.rdmolfiles import SDWriter
suppl = Chem.SDMolSupplier('C:/NIST17B/new.sdf')
count=0
writer=SDWriter('C:/NIST17B/newOut.sdf')
for mol in suppl:
    if mol is None: continue
    count=count+1
    print(Chem.MolToSmiles(mol,isomericSmiles=False))
    print(mol.GetNumAtoms())
    print(CalcMolFormula(mol))
    writer.write(mol)
print('Done')
print(count)
writer.close()

**Comment by greglandrum** [comment]
Without an example structure, it's impossible to be sure, but it sounds like the RDKit is working as designed: a structure with a five-coordinate neutral nitrogen is chemically unreasonable, so it is rejected by the toolkit.

**Comment by wgmallard** [comment]
Greg,
I am attaching a small SDF file with the examples that failed.  The way
that isocyanides are often represented is -N#C, so the Nitrogen is 4
coordinate and the C is 3.  It is also represented as -N(+)#C(-) as a
zwitterion and that might be a reasonable way to convert it for standard
storage.  A colleague with whom I discussed this created a file that was
corrected and I am also attaching it to this email.  He noted that " The
fifth one has an error. It has a negative charge marked on the carbon, but
no corresponding positive charge on the nitrogen.", so it may make sense
just to look at the first 4 in the set.

I am attaching Original-isocyan.sdf which is the file that had the failures
in RDKit.  The isocyan_chg.SDF is my colleague's correction.

It is reasonable to fail for the cases shown, but the drawing convention
shown is one that is used and it may be that just automatically converting
it in the same way that other automatic conversions are done would be
valuable.

Thanks for your time.

Gary

Below is a very brief note on the a simple example with the mol file
The drawing of the group looks like this.
[image: isocyano.gif]
And the mol file (as saved by ACD labs drawing program) looks like:

  ACD/Labs06201908592D

  8  8  0  0  0  0  0  0  0  0  1 V2000
   23.5478  -12.9613    0.0000 N   0  0  0  0  0  4  0  0  0  0  0  0
   24.6983  -12.2940    0.0000 C   0  0  0  0  0  3  0  0  0  0  0  0
   22.3927  -13.6239    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   21.2423  -12.9613    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.0918  -13.6239    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.0918  -14.9539    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   21.2423  -15.6212    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   22.3927  -14.9539    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  3  0  0  0  0
  1  3  1  0  0  0  0
  3  4  1  0  0  0  0
  3  8  1  0  0  0  0
  4  5  1  0  0  0  0
  5  6  1  0  0  0  0
  6  7  1  0  0  0  0
  7  8  1  0  0  0  0
M  END

**Comment by greglandrum** [comment]
@wgmallard : attachments don't seem to work when you reply via email.
You'll need to add the files through the github UI and, unforunately, rename them to .sdf.txt

**Comment by wgmallard** [comment]
Greg,
I think that this will work.  I have created zip files of the two files I discussed earlier and it appears that they are attached.  If not let me know and I will try again.
Thanks,
Gary
[Original-isocyan.zip](https://github.com/rdkit/rdkit/files/3310613/Original-isocyan.zip)
[isocyan_chg.zip](https://github.com/rdkit/rdkit/files/3310615/isocyan_chg.zip)

**Comment by greglandrum** [comment]
Yep. Those look good.

**Comment by wgmallard** [comment]
Great, I was hoping that this problem could become one of the standard
molecular santization process that you do when bringing in SDF files to
convert to mol objects.
Gary

**Comment by greglandrum** [comment]
I will need to check. We try to keep those minimal and only do them for cases that are reasonably common and where it's really unambiguous what is meant.
We prefer to fail on the side of caution since you always notice a bad structure that fails to process but it's hard to detect a structure that has been "fixed" incorrectly.

**Comment by wgmallard** [comment]
I agree, I think that this is a unique case and can be fixed by looking for
exactly the 3 valence on C and 4 valence on N when they are connected.  It
is also one that is a common method of showing the group.

**Comment by greglandrum** [comment]
I agree that it's pretty unambiguous. I did a bit of googling and all the hits I found had it drawn as the zwitterion. It's not like I looked through hundreds of papers though, can you point me to a few published examples (just for reference)

**Comment by wgmallard** [comment]
I am about to leave town for my grandson's graduation from high school.
The quickest thing I can point to is the NIST Mass Spectral Database, which
is where the data I sent you is taken from.  I will try to find some other
examples in the literature and get back to you with pdfs next week if that
is OK.  The newer literature usually has the zwitterion but the older
literature uses the -N#C without the zwitterion, so I will need to go back
and find some older citations.  The mol files created by both ChemSketch
and Marvin do support the 4/3 coordination and do not add H atoms.
Gary

**Comment by wgmallard** [comment]
Greg,
Finding modern examples of this problem is not all that easy.  The older literature often simply use R-NC with no reference to the structure - I am attaching a paper that illustrates this.  I am also attaching a screen shot of the way the NIST Mass Spectral Database shows these.  The SDF file that results from these structures is an illustration of the problem.  These are legacy structures and as a result may not represent the nature of the bonding - they are in effect a short hand, much like -N(=O)(=O) for the nitro group (which is the way it is represented in the NIST database.
Gary
[RNCFromNIST.pdf](https://github.com/rdkit/rdkit/files/3346366/RNCFromNIST.pdf)
[1-s2.0-S0040403999010497-main.pdf](https://github.com/rdkit/rdkit/files/3346367/1-s2.0-S0040403999010497-main.pdf)

**Comment by wgmallard** [comment]
Greg,
I put a paper, as noted in the note with the paper, it is not really what
you are looking for, and I put a screen shot of the NIST Mass Spectral
database to illustrate the way that the isocyanides are displayed.  I also
closed the issue - that was accidental, but I think reasonable.  I think it
would be valuable to have this added to your automatic transformations, but
if it you think it is not worth it I would understand.
Thanks,
Gary
