### ISSUE TITLE
Cannot add hydrogens on rdkit.Mol from SMARTS

### ISSUE THREAD

**Issue by shayakhmetov** [rdkit/rdkit#2512]
```
from rdkit import Chem
smarts = '[#6]12:[#6](:[#6]:[#7]:[#7]:1-[#6]):[#6](-[#7]):[#7]:[#6]:[#7]:2'
mol = Chem.MolFromSmarts(smarts)
Chem.AddHs(mol)
```
fails on AddHs with
```
RuntimeError: Pre-condition Violation
	getNumImplicitHs() called without preceding call to calcImplicitValence()
	Violation occurred on line 152 in file Code/GraphMol/Atom.cpp
	Failed Expression: d_implicitValence > -1
	RDKIT: 2019.03.2
	BOOST: 1_67
```

Chem.SanitizeMol doesn't help - `Sanitization error: Explicit valence for atom # 0 C, 5, is greater than permitted`, whereas the code with SMILES 'Cn1ncc2c(N)ncnc21' works well.
Is it possible to get a valid rdkit.Mol from SMARTS?

![Screenshot from 2019-06-26 17-23-59](https://user-images.githubusercontent.com/4422605/60188054-564cae80-9837-11e9-8e2e-26ab45e10a14.png)
![Screenshot from 2019-06-26 17-20-52](https://user-images.githubusercontent.com/4422605/60188068-5cdb2600-9837-11e9-859d-30cbe0eb3bbd.png)

**Comment by shayakhmetov** [comment]
rdkit.Mol from SMARTS assigns incorrect aromaticity flags for some atoms and bonds (GetIsAromatic), which may be the cause of the problem

**Comment by greglandrum** [comment]
`MolFromSmarts()` does return a valid molecule, it just returns a molecule that includes query atoms and bonds. These are different from the standard atoms and bonds that you get from `MolFromSmiles()`.

It generally doesn't make sense to do something like add Hs to a molecule constructed from SMARTS. What are you trying to do?

**Comment by shayakhmetov** [comment]
I am trying to obtain SMILES from SMARTS for some molecular fragments. Is there a way to sanitize SMILES 'CN1:N:C:C2:C(N):N:C:N:C:2:1' to 'Cn1:n:[cH]:c2:c(N):n:[cH]:n:c12' or 'Cn1ncc2c(N)ncnc21' as, for example, https://cactus.nci.nih.gov/cgi-bin/translate.tcl does? So far, I've encountered that rdkit doesn't sanitize the SMILES 'c1cc2cccnc2n1' into valid 'c1cc2ccc[nH]c2n1', or there are some problems with kekulization.
Is it possible to add more powerful sanitization and kekulization of SMILES, e.g. https://cactus.nci.nih.gov/cgi-bin/translate.tcl seems to sanitize/kekulize partially valid SMILES pretty well?
