### ISSUE TITLE
GetSubstructMatch overlay display incorrectly highlights ring bonds not in the substructure

### ISSUE THREAD

**Issue by btcooooper** [rdkit/rdkit#2514]
Description: 
Substructure overlays for Mol objects rendered in the IPythonConsole (or produced by Chem.Draw.MolToImage) incorrectly highlight ring bonds in the Mol object that should be open in the overlaid substructure. 

I think the code assumes that, if both the begin and end atoms of a bond are in the substructure, then the bond itself must be, too. But this might not be true for substructures with opened rings. I wrote a function that (I think) correctly identifies bonds that should be highlighted; I attached my Jupyter notebook as a zip file. Minimal code to reproduce the bug is shown below.

- RDKit Version: 2019.03.2
- Platform: Windows (using Jupyter notebook)

Code sample:

```
from rdkit import Chem
from rdkit.Chem import rdDepictor
rdDepictor.SetPreferCoordGen(True)
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG, Image
IPythonConsole.molSize = (400,400)
```

```
que_smiles = "O=c1cc(-c2ccc(O)cc2)oc2cc(O)c(C3OC(CO)C(O)C(O)C3O)c(O)c12"
que_mol = Chem.MolFromSmiles(que_smiles)
rdDepictor.Compute2DCoords(que_mol)
que_mol
```
![image](https://user-images.githubusercontent.com/52256904/60212732-e850b900-982f-11e9-9cd1-4116aea1330f.png)

```
mcs_smarts = "[#8]-[#6]1:[#6](:[#6]:[#6](:[#6]:[#6]:1):[#6](=[#8]):[#6]:[#6](:[#8])-[#6])-[#6]1-[#8]-[#6](-[#6]-[#8])-[#6](-[#6](-[#6]-1-[#8])-[#8])-[#8]"
mcs_mol = Chem.MolFromSmarts(mcs_smarts)
rdDepictor.Compute2DCoords(mcs_mol)
mcs_mol
# note ring opened at O-C bond to the phenyl ring
```
![image](https://user-images.githubusercontent.com/52256904/60212772-028a9700-9830-11e9-809b-778f9e8328db.png)

```
que_mc = Chem.Mol(que_mol.ToBinary())  # make a copy of the Mol object
que_mc.GetSubstructMatch(mcs_mol)
que_mc
# note that this incorrectly highlights what should be the open O-C bond
```
![image](https://user-images.githubusercontent.com/52256904/60212788-0d452c00-9830-11e9-9c4f-7e63b1156a37.png)

```
que_mc = Chem.Mol(que_mol.ToBinary())  # make a copy of the Mol object
img = Chem.Draw.MolToImage(que_mc, highlightAtoms=que_mc.GetSubstructMatch(mcs_mol), highlightColor=[0.5,0,0.5]) 
img
# note that this too incorrectly highlights what should be the open O-C bond 
# also fails using Chem.Draw.MolToFile
```
![image](https://user-images.githubusercontent.com/52256904/60212793-1504d080-9830-11e9-843d-def5161096ca.png)

My overlay function (attached) correctly produces this (note the correctly non-highlighted O-C bond):
![image](https://user-images.githubusercontent.com/52256904/60212903-601ee380-9830-11e9-9554-a01beccad53c.png)

[overlay_bug_report.zip](https://github.com/rdkit/rdkit/files/3331602/overlay_bug_report.zip)

**Comment by greglandrum** [comment]
I agree that it would be good to fix this.
There are two ways we can do that:
1. I can integrate your changes
2. You can do a pull request with the changes and I'll integrate it.
The nicer thing with option 2 is that you get credit for the changes instead of me. :-)

**Comment by btcooooper** [comment]
Glad I can contribute a little! I'll see if I can figure out how to create a pull request. I'm not sure exactly where in the code (and I assume there are at least two places) the changes need to be made, though.

**Comment by greglandrum** [comment]
Great!
As for finding the right place to make the changes: After you've had a chance to look at it, feel free to ask for help here.

**Comment by btcooooper** [comment]
OK, for what I think is the "old" drawing code (used in `Chem.Draw.MolToImage` and `Chem.Draw.MolToFile`), I think the questionable assumption is in the bond coloring section of the `AddMol` function, starting on line 516 of rdkit/rdkit/Chem/Draw/MolDrawing.py (specifically the first `elif` case on line 525):
```
    for bond in mol.GetBonds():
      atom, idx = bond.GetBeginAtom(), bond.GetBeginAtomIdx()
      nbr, nbrIdx = bond.GetEndAtom(), bond.GetEndAtomIdx()
      pos = self.atomPs[mol].get(idx, None)
      nbrPos = self.atomPs[mol].get(nbrIdx, None)
      if highlightBonds and bond.GetIdx() in highlightBonds:
        width = 2.0 * self.drawingOptions.bondLineWidth
        color = self.drawingOptions.selectColor
        color2 = self.drawingOptions.selectColor
      elif highlightAtoms and idx in highlightAtoms and nbrIdx in highlightAtoms:
        width = 2.0 * self.drawingOptions.bondLineWidth
        color = self.drawingOptions.selectColor
        color2 = self.drawingOptions.selectColor
      elif highlightMap is not None and idx in highlightMap and nbrIdx in highlightMap:
        width = 2.0 * self.drawingOptions.bondLineWidth
        color = highlightMap[idx]
        color2 = highlightMap[nbrIdx]
```
However, I don't see any way to fix this within the `AddMol` function, because it is not passed any information about the substructure used to find the list of highlighted atoms. `GetSubstructMatch` returns only a tuple of atoms (not bonds) in the original molecule, and to get this to work we need to test for bonds in the substructure Mol object. 

I'm far from fluent in C++, but I think the culprit in the "new" drawing code starts on line 38 of rdkit/Code/GraphMol/MolDraw2D/MolDraw2D.cpp, in `void getBondHighlightsForAtoms()`. I think it has the same fundamental problem: no information about the substructure used to generate the atom indexes gets passed to this function.

If I'm right, the only way around this is to explicitly pass a tuple of highlighted bonds to the drawing code, as in the overlay function I wrote. This would be easier if `GetSubstructMatch` also returned a tuple of bonds, or if there were separate `GetSubstructMatchAtoms` and `GetSubstructMatchBonds` methods. Another thing I don't fully understand is how the substructure information becomes associated with the Mol object, as it must because the highlighting appears automatically when you invoke the Mol object in an IPython console. 

If we took out the code that highlights bonds when only atom indexes are provided, then only atoms will be highlighted unless the user provides bond indexes explicitly. This might be less convenient in many cases, but seems preferable to highlighting a bond that shouldn't be highlighted without any warning that there could be an error.

**Comment by greglandrum** [comment]
Answering pieces out of order...

**Comment by greglandrum** [comment]
We currently only have information about the atoms that match the query. We could also store information about the bonds, but that would slow down every substructure match done when using the notebook

I see two straightforward fixes:

1. Switch to only highlighting atoms when showing substructure matches by default.
2. Instead of storing the matching atoms when doing a substructure search, store the query (only if it matches, of course). Then, when drawing a molecule use that query again to find the atoms and bonds that matched and highlight both atoms and bonds.


Since we only have information about the atoms that matched the query

**Comment by btcooooper** [comment]
OK, the old drawing code does not highlight atoms represented only as vertices. If I take out the bond highlighting (as in the revision shown below), then only explicit atom symbols are highlighted.
https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/Draw/MolDrawing.py#L516
```
    for bond in mol.GetBonds():
      atom, idx = bond.GetBeginAtom(), bond.GetBeginAtomIdx()
      nbr, nbrIdx = bond.GetEndAtom(), bond.GetEndAtomIdx()
      pos = self.atomPs[mol].get(idx, None)
      nbrPos = self.atomPs[mol].get(nbrIdx, None)
      if highlightBonds and bond.GetIdx() in highlightBonds:
        width = 2.0 * self.drawingOptions.bondLineWidth
        if highlightMap is not None and idx in highlightMap and nbrIdx in highlightMap:
          color = highlightMap[idx]
          color2 = highlightMap[nbrIdx]
        else:
          color = self.drawingOptions.selectColor
          color2 = self.drawingOptions.selectColor
   #  elif highlightAtoms and idx in highlightAtoms and nbrIdx in highlightAtoms:
   #    width = 2.0 * self.drawingOptions.bondLineWidth
   #    color = self.drawingOptions.selectColor
   #    color2 = self.drawingOptions.selectColor
   #  elif highlightMap is not None and idx in highlightMap and nbrIdx in highlightMap:
   #    width = 2.0 * self.drawingOptions.bondLineWidth
   #    color = highlightMap[idx]
   #    color2 = highlightMap[nbrIdx]
      else:
        width = self.drawingOptions.bondLineWidth
        if self.drawingOptions.colorBonds:
          color = self.drawingOptions.elemDict.get(atom.GetAtomicNum(), (0, 0, 0))
          color2 = self.drawingOptions.elemDict.get(nbr.GetAtomicNum(), (0, 0, 0))
        else:
          color = self.drawingOptions.defaultColor
          color2 = color
      self._drawBond(bond, atom, nbr, pos, nbrPos, conf, color=color, width=width, color2=color2,
                     labelSize1=labelSizes[idx], labelSize2=labelSizes[nbrIdx])
```
Produces: 
![image](https://user-images.githubusercontent.com/52256904/60389105-f8fc6b80-9a89-11e9-9c1f-a12aa5630ae7.png)

**Comment by btcooooper** [comment]
As for the new drawing code, I can always do a PR that removes the getBondHighlightsForAtoms function and all calls to it, but I do not currently have a C++ build set up so I can't easily test it myself.

**Comment by btcooooper** [comment]
And as for a longer-term solution for identifying the bonds to highlight, the `GetSubstructMatch` method already returns a tuple of atom indices (and apparently stores them with the Mol object when using the console). Isn't the slow part identifying the match in the first place? Does it really take that long to use the atom indices to find the correct bonds? 

I assume that changing `GetSubstructMatch` to make it also return a tuple of bonds would break a lot of existing code. But that seems like a better long-term solution to me. A separate `GetSubstructMatchBonds` function would have to repeat the match identification step.

I can certainly write a convenience function in Python that finds the correct bonds to highlight (like in the overlay code I originally attached). But I'm not currently prepared to implement that in C++ by myself.

**Comment by greglandrum** [comment]
I’m away from the computer until the middle of the week, so I can’t provide a lot of help on this right now.

A quick one: you should be able to turn off the automatic drawing of connecting bonds using the drawOptions structure that is part of the MolDraw2D object. No need to use C++ for that. The option is: continuousHighlight

**Comment by bp-kelley** [comment]
I think we can have our cake and eat it too.  If we store the atom matches (in query order) and the query, it is a quick lookup to ask the query if the bond between the matched atoms should be highlit.
