### ISSUE TITLE
CMake Error: Wrap directories being used when python build is turned off

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#2516]
I downloaded the 2019.03.3 release, extracted, and followed the build instructions.  This is my CMake command,

```
cmake .. \
  -DRDK_BUILD_PYTHON_WRAPPERS=OFF \
  -DRDK_INSTALL_STATIC_LIBS=ON \
  -DBOOST_INCLUDEDIR=$Boost1_68IncDir \
  -DBOOST_LIBRARYDIR=$Boost1_68LibDir \
  -DRDK_BUILD_AVALON_SUPPORT=ON \
  -DEIGEN3_INCLUDE_DIR=$EigenIncDir \
  -DBoost_NO_SYSTEM_PATHS=ON \
  -DRDK_BUILD_DESCRIPTORS3D=ON \
  -DCMAKE_INSTALL_PREFIX=$RDInstallDir \
  -DRDK_BUILD_COMPRESSED_SUPPLIERS=ON
```

and this is the end of the output (I can paste the full output if helpful)

```
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
== Updating Filters.cpp from pains file
== Done updating pains files
Downloading https://github.com/Tencent/rapidjson/archive/v1.1.0.tar.gz...
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   iostreams
--   regex
CMake Error at Code/GraphMol/Wrap/CMakeLists.txt:63 (set_target_properties):
  set_target_properties Can not find target to add properties to: rdmolfiles
```

I'm confused by why anything in the Wrap directory is being built since I'm turning off the python wrappers.  Any help is most appreciated.

**Comment by greglandrum** [comment]
That *is* a bit odd.
What is the last release you used that cmake command with?

**Comment by greglandrum** [comment]
I'm pretty sure there's no reason for cmake to be looking in the Wrap directory at all if the python wrappers aren't being built. That's something I think we can fix.

**Comment by jasondbiggs** [comment]
I can get everything to compile if I turn off the compressed-suppliers build, or if I comment out line 63 of `Code/GraphMol/Wrap/CMakeLists.txt`.  Am I correct that this shouldn't have an effect if I'm not building the python wrappers?

Maybe unrelated, but in the subsequent test run, `graphmoltestCanon` appears to run forever.  I quit it after 20 minutes.

**Comment by jasondbiggs** [comment]
@greglandrum - For the previous versions I was not doing the compressed mol suppliers build, and so that `If` statement doesn't get triggered.

**Comment by greglandrum** [comment]
Aside I was going to suggest that you not do the compressed suppliers build anyway. That's old functionality and in newer code you can provide a compressed boost::iostream to the ForwardSDMolSupplier.

**Comment by greglandrum** [comment]
You should actually be able to comment out this line:
https://github.com/rdkit/rdkit/blob/Release_2019_03/Code/GraphMol/CMakeLists.txt#L99
That's a more direct solution and should work

**Comment by greglandrum** [comment]
`graphmoltestCanon` should be pretty quick.
You can always look at the test output for the CI builds to get a sense for how long the individual tests take. One example:
https://dev.azure.com/rdkit-org/RDKit-main-build/_build/results?buildId=157

**Comment by jasondbiggs** [comment]
Thanks for the quick fix, and the suggestion to avoid that build component altogether.  I will lookup how to use boost to create a `std::istream` from a gzipped sdf file.

**Comment by greglandrum** [comment]
No need to spend too much time searching there. Here's an example: https://github.com/rdkit/rdkit/blob/Release_2019_03/Code/GraphMol/FileParsers/testMolSupplier.cpp#L2114

**Comment by jasondbiggs** [comment]
@greglandrum is it expected that the `RDStreams` directory isn't copied to the same directory as `GraphMol` etc, when doing an out-of-tree build?  After I copied it from the `Code` directory everything compiled, and reading from gzipped sd files works great.  

Also the `RDKitRDStreams` library was in its own directory inside the libs directory, instead of just in the same folder as `RDKitRDGeneral` and others.

**Comment by greglandrum** [comment]
Those are both due to oversights. I'll fix them at the same time I clear up the problem with the Wrap directories still being used when the Python wrappers are disabled
