### ISSUE TITLE
FindMCS is not idempotent ([a,b,a] yields different result from [a,b])

### ISSUE THREAD

**Issue by timholy** [rdkit/rdkit#2525]
**Description:**

- RDKit Version: 2019.03.3
- Platform: Linux (Ubuntu 18.04) via Anaconda

Here's an example where `FindMCS([a,b,a], options...)` returns a smaller substructure than `FindMCS([a,b], options...)` (the last line is the problematic one):

```python
>>> from rdkit.Chem import rdFMCS
>>> E1050 = Chem.MolFromSmiles("S(=O)(=O)(O[C@@H]1[C@@]2([C@H]([C@H]3[C@H](CC2)c2c(CC3)cc(OS(=O)(=O)[O-])cc2)CC1)C)[O-]")
>>> A7864 = Chem.MolFromSmiles("C4[C@]1(C(=CC[C@@H]2[C@@H]1CC[C@]3([C@H]2CC[C@@H]3O[S](=O)(=O)[O-])C)C[C@H](C4)O[S](=O)(=O)[O-])C")
>>> rdFMCS.FindMCS([E1050,A7864], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms
28
>>> rdFMCS.FindMCS([A7864,E1050], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms
28
>>> rdFMCS.FindMCS([E1050,E1050], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms
28
>>> rdFMCS.FindMCS([E1050,A7864,A7864], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms
28
>>> rdFMCS.FindMCS([E1050,A7864,E1050], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms
24
```

**Comment by timholy** [comment]
Here's another related case. `E1103` essentially *is* a substructure of E1050, yet:
```python
>>> E1103 = Chem.MolFromSmiles("S(=O)(=O)(O[C@@H]1[C@@]2([C@H]([C@H]3[C@H](CC2)c2c(CC3)cc(O)cc2)CC1)C)[O-]")
>>> rdFMCS.FindMCS([E1050,A7864,E1103], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms
20
>>> rdFMCS.FindMCS([E1050,E1103], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms
24
>>> E1103.GetNumAtoms()
24
>>> rdFMCS.FindMCS([A7864,E1103], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms
24
```

**Comment by greglandrum** [comment]
Confirmed.

**Comment by greglandrum** [comment]
This is somehow connected to the chiral matching:
```
>>> rdFMCS.FindMCS([E1050,A7864,E1050], matchChiralTag=True, bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms                                                                      
24
>>> rdFMCS.FindMCS([E1050,A7864,E1050], bondCompare=rdFMCS.BondCompare.CompareOrder).numAtoms                                                                                           
28
```

.... just because tracking down MCS bugs isn't fun enough we get to add chirality to the mess... <sigh>

**Comment by greglandrum** [comment]
@timholy : thanks for the bug report
To properly set expectations here: bugs in the MCS code tend to be non-trivial to track down and fix.  They generally require a good size chunk of uninterrupted time, so it may be a while before this one is resolved.

**Comment by timholy** [comment]
I am not surprised. Thanks for confirming it so quickly. In my case I may be able to hack something together that uses a rather simpler algorithm: these are all steroids, so in a sense perhaps I only care about MCS that preserves the [gonane](https://en.wikipedia.org/wiki/Gonane) carbon id. Being a [Julia](https://julialang.org/) developer ("walks like Python, runs like C") I can probably write that myself using [LightGraphs.jl](https://github.com/JuliaGraphs/LightGraphs.jl). It seems the main thing missing would be a bit of vertex metadata indicating chirality---is there a good reference (publication or particular piece of the source code) on how that's implemented in RDKit and/or other computational chemistry toolboxes?
