### ISSUE TITLE
Python Multiprocessing for computing descriptors

### ISSUE THREAD

**Issue by lorenzoFabbri** [rdkit/rdkit#2529]
I'm trying to compute all the molecular descriptors from `Chem.Descriptors.descList` for a large number of compounds. For this reason, I'm trying to using Multiprocessing (more precisely, the `map` function from `pathos.pools.ProcessPool()`.

At the moment, I wrote the following:
```
...
mol_descriptors = [desc[1] for desc in Descriptors.descList]

with pathos.pools.ProcessPool() as pool:
    result_pool = pool.map(self.generate_mol_descriptor, smiles, mol_descriptors)
...
```

where `smiles` is a list of SMILES codes, and `self.generate_mol_descriptor` simply computes one descriptor for all the SMILES codes.

Unfortunately, I keep getting the following error: `TypeError: can't pickle Boost.Python.function objects`. I never used Multiprocessing with RDKit, so I'm not really sure what that means. Is it because I'm trying to pickle C++ functions?

**Comment by bp-kelley** [comment]
I can’t speak for the pathos library ( it appears to use dill instead of pickle ) however, I have had great success with python multiprocess.

https://github.com/bp-kelley/descriptastorus
(Note the code below hasn’t been tested)
from descriptastorus.descriptors.DescriptorGenerator import MakeGenerator 

import multiprocessing

generator = MakeGenerator(("RDKit2D", "Morgan3Counts")) 

jobs = ["c1ccccc1" ]

pool = multiprocessing.Pool()

results = pool.map(generator.process, jobs)



----
Brian Kelley

**Comment by greglandrum** [comment]
@bp-kelley is faster than me... but that's because I actually tested my code. ;-)

I would also suggest rethinking how you are doing this. It looks like your proposed solution is going to reconstruct every molecule for every descriptor. That is *incredibly* inefficient.

This snippet uses multiprocessing and generates all the descriptors for each molecule in parallel:
```
from rdkit import Chem
from rdkit.Chem import Descriptors

def calc_descrs_for_smiles(smi,descList):
    m = Chem.MolFromSmiles(smi)
    if m is None:
        return dict(zip(descList,[None]*(len(descList))))
    fns = [(x,y) for x,y in Descriptors.descList if x in descList]
    res = {}
    for x,y in fns:
        res[x] = y(m)
    return res

if __name__=='__main__':
    descList = [desc[0] for desc in Descriptors.descList]

    smis = [x.split()[0] for x in r'''Br\C=C\1/CCC(C(=O)O1)c2cccc3ccccc23	23
COc1cc2nc(nc(N)c2cc1OC)N3CCN(CC3)C(=O)c4occc4	97
CN1CCC[C@H]1c2cccnc2	115
CC1COc2c(N3CCN(C)CC3)c(F)cc4C(=O)C(=CN1c24)C(=O)O	146
CCN1C=C(C(=O)O)C(=O)c2ccc(C)nc12	147
Oc1cc2C(=O)Oc3c(O)c(O)cc4C(=O)Oc(c1O)c2c34	148
COc1ccc2c(c1)c(CC(=O)O)c(C)n2C(=O)c3ccc(Cl)cc3	173
CC1(C)[C@@H](N2[C@@H](CC2=O)S1(=O)=O)C(=O)O	194
Cn1cc(C2=C(C(=O)NC2=O)c3cn(CCCSC(=N)N)c4ccccc34)c5ccccc15	213
CN1CCN(CC1)c2cc3N(C=C(C(=O)O)C(=O)c3cc2F)c4ccc(F)cc4	205
C[C@]1(Cn2ccnn2)[C@@H](N3[C@@H](CC3=O)S1(=O)=O)C(=O)O	207
CN1CCN(CC1)c2c(F)cc3C(=O)C(=CN(CCF)c3c2F)C(=O)O	210
CCc1cc2c(Sc3nnc(N)s3)ncnc2s1	236'''.split('\n')]

    for i in range(8):
        smis += smis
    from multiprocessing import Pool
    def func(x):
        return calc_descrs_for_smiles(x,descList)
    with Pool(processes=4) as pool:
        res = pool.map(func,smis)
    print(len(res))
```

**Comment by lorenzoFabbri** [comment]
Thank you both, @bp-kelley and @greglandrum ! I'll test both solutions before closing the issue.

**Comment by tawe141** [comment]
I'm getting the same error but with GetAdjacencyMatrix and joblib. Commenting out my GetAdjacencyMatrix line works (albeit the function fails because it depends on the adjacency matrix). Multiprocessing also doesn't work as the function is not pickleable. Do you have any suggestions?

**Comment by bp-kelley** [comment]
Python can't pickle boost related functions for a similar reason that it
can't pickle lambda functions.

However, it *CAN* pickle functions that call boost functions:

import multiprocessing
from rdkit import Chem

def foo(x):
    return Chem.GetAdjacencyMatrix(x)

if __name__ == "__main__":
    with multiprocessing.Pool() as pool:
        print(pool.map(foo, [Chem.MolFromSmiles("c1ccccc1")]))


I will point out that if you can all of the molecule creation in the
process it can be quite a bit faster.  The above example reads and creates
the molecule, serializes the molecule via pickle and then the process has
to unpickle it.

Compare this against the alternative which should consume less memory and
get faster as the number of molecules increases.

import multiprocessing
from rdkit import Chem

def foo(smiles):
    m = Chem.MolFromSmiles(smiles)
    if m:
        return Chem.GetAdjacencyMatrix(m)
    return None

if __name__ == "__main__":
    with multiprocessing.Pool(4) as pool:
        pool.map(foo, ["c1ccccc1"])

Cheers,
 Brian

**Comment by tawe141** [comment]
Wrapping the function and using joblib does not work for me, and throws the same error. 

```
from rdkit.Chem import MolFromSmiles, AddHs
...
    def molify(self, smiles_string):
        """
        Wrapper function to return rdkit mol from smiles string
        """
        m = MolFromSmiles(smiles_string)
        m = AddHs(m)
        return m

...
        with Parallel(n_jobs=-1) as pool:
        # data['mols'] = [AddHs(MolFromSmiles(s)) for s in data['smiles']]
            data['mols'] = pool(delayed(self.molify)(i) for i in data['smiles'])
```

Why doesn't this work?
