### ISSUE TITLE
postgres part of rdkit with out installing postgres also

### ISSUE THREAD

**Issue by dpwildboar** [rdkit/rdkit#2535]
the installation docs http://rdkit.org/docs/Install.html are missing instructions on how to install the postgres part of rdkit with out installing postgres also.

for example, we already have postgres 11 installed on the machine, and would like to install rdkit in such a way that it uses that vs installing postgres 9.

I tried to get it to stop installing postgres also. but, the several things I tried seemed to be of no avail.

it would seem to me that this would be a somewhat common issue and the docs should address this.

**Comment by greglandrum** [comment]
Yeah, the docs for the postgresql install are definitely overly reliant on conda; sorry about that.

The "short" form of the answer is that you need to do an RDKit build with the cartridge build enabled via the `-DRDK_BUILD_PGSQL=ON` argument.

Here's a command I just did from a `builds/build_pgsql directory inside the source tree` (if you have a recent version of boost installed on your system, you can skip the `-DBOOST_ROOT` part):
```cmake -DBOOST_ROOT=/opt/boost_1_67_0_cxx14/ -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DRDK_BUILD_CPP_TESTS=OFF -DRDK_BUILD_PGSQL=ON --PostgreSQL_CONFIG=/usr/bin/pg_config -DRDK_BUILD_INCHI_SUPPORT=ON ../..```

After that finishes, you build with (replace 4 with however many threads you want to use):
```
make -j4
```
And then install and test the binaries with:
```
sh ./Code/PgSQL/rdkit/pgsql_install.sh
sh ./Code/PgSQL/rdkit/pgsql_regress.sh 
```

At that point users should be able to install the extension in their own databases using `create extension rdkit` from the psql prompt.

Here's a quick demo of that:
```
(base) glandrum@otter:/scratch/RDKit_git/builds/build_psql$ psql my_test_db
psql (10.9 (Ubuntu 10.9-0ubuntu0.18.04.1))
Type "help" for help.

my_test_db=# create extension rdkit;
CREATE EXTENSION
my_test_db=# select 'c1ccccc1O'::mol;
    mol    
-----------
 Oc1ccccc1
(1 row)

my_test_db=# 
```
