### ISSUE TITLE
EmbedMultipleConfs Python argument types error

### ISSUE THREAD

**Issue by tonyyzy** [rdkit/rdkit#2536]
**Description:**

- RDKit Version: 2019.03.2
- Platform: CentOs 7 / MacOS X

Using **EmbedMultipleConfs** for conformer generation, RDKit gives Boost.Python.ArgumentError: Python argument types did not match C++ signature
error.

```
from rdkit.Chem import AllChem
import rdkit.Chem as Chem

mol = Chem.MolFromInchi(r"InChI=1S/C18H24O2/c1-18-9-8-14-13-5-3-12(19)10-11(13)2-4-15(14)16(18)6-7-17(18)20/h3,5,10,14-17,19-20H,2,4,6-9H2,1H3/t14-,15-,16+,17+,18+/m1/s1")
ids=AllChem.EmbedMultipleConfs(mol, numConfs=50, params=AllChem.ETKDG(), maxAttempts=10)
```

**Comment by greglandrum** [comment]
The error messages you get are not necessarily easy to read, but they can be pretty informative. If you look at your case:
```
In [14]: ids=AllChem.EmbedMultipleConfs(mol, numConfs=50, params=AllChem.ETKDG(), maxAttempts=10)
    ...:
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-14-51eecd3d3ce3> in <module>
----> 1 ids=AllChem.EmbedMultipleConfs(mol, numConfs=50, params=AllChem.ETKDG(), maxAttempts=10)

ArgumentError: Python argument types in
    rdkit.Chem.rdDistGeom.EmbedMultipleConfs(Mol)
did not match C++ signature:
    EmbedMultipleConfs(class RDKit::ROMol {lvalue} mol, unsigned int numConfs, struct RDKit::DGeomHelpers::EmbedParameters {lvalue} params)
    EmbedMultipleConfs(class RDKit::ROMol {lvalue} mol, unsigned int numConfs=10, unsigned int maxAttempts=0, int randomSeed=-1, bool clearConfs
=True, bool useRandomCoords=False, double boxSizeMult=2.0, bool randNegEig=True, unsigned int numZeroFail=1, double pruneRmsThresh=-1.0, class b
oost::python::dict {lvalue} coordMap={}, double forceTol=0.001, bool ignoreSmoothingFailures=False, bool enforceChirality=True, int numThreads=1
, bool useExpTorsionAnglePrefs=True, bool useBasicKnowledge=True, bool printExpTorsionAngles=False)
```

You can see that the form of the `EmbedMultipleConfs()` function that takes a parameters argument only accepts a molecule, the `numConfs` argument, and the parameters:
`EmbedMultipleConfs(class RDKit::ROMol {lvalue} mol, unsigned int numConfs, struct RDKit::DGeomHelpers::EmbedParameters {lvalue} params)`

If you want to set the maxAttempts, you should do that in the params object:
```
In [15]: ps = AllChem.ETKDG()

In [16]: ps.maxIterations = 10

In [17]: ids=AllChem.EmbedMultipleConfs(mol, numConfs=50, params=ps)

```
It's a confusing that the name is different, but we tried to make the parameter names more rational and consistent when we added the parameter types. The documentation for that is here:
https://www.rdkit.org/docs/source/rdkit.Chem.rdDistGeom.html#rdkit.Chem.rdDistGeom.EmbedParameters

**Comment by tonyyzy** [comment]
@greglandrum Thanks! I kept thinking the data type I provided to `maxAttempts` is wrong but didn't realise the parameters should be groups!

Thanks for your help, works a charm. Closing this issue now.
