### ISSUE TITLE
Compiling JAVA wrapper error - Syntax error in input(1).

### ISSUE THREAD

**Issue by CamAnNguyen** [rdkit/rdkit#2537]
**Description:**

Error while trying to compile the latest `master` source code with JAVA wrapper.

**`rdkit/Code/GraphMol/StereoGroup.h:28: Error: Syntax error in input(1)`**

Error details:

```
/home/annguyen/rdkit/Code/GraphMol/StereoGroup.h:28: Error: Syntax error in input(1).
Code/JavaWrappers/gmwrapper/CMakeFiles/GraphMolWrap_swig_compilation.dir/build.make:141: recipe for target 'Code/JavaWrappers/gmwrapper/CMakeFiles/GraphMolWrap.dir/GraphMolJavaJAVA.stamp' failed
make[2]: *** [Code/JavaWrappers/gmwrapper/CMakeFiles/GraphMolWrap.dir/GraphMolJavaJAVA.stamp] Error 1
make[2]: *** Deleting file 'Code/JavaWrappers/gmwrapper/CMakeFiles/GraphMolWrap.dir/GraphMolJavaJAVA.stamp'
CMakeFiles/Makefile2:16152: recipe for target 'Code/JavaWrappers/gmwrapper/CMakeFiles/GraphMolWrap_swig_compilation.dir/all' failed
make[1]: *** [Code/JavaWrappers/gmwrapper/CMakeFiles/GraphMolWrap_swig_compilation.dir/all] Error 2
```

Installing under `conda` environment:

- cmake version 3.14.0
- python 3.7.3
- boost 1.67.0
- SWIG 3.0.8

`cmake` configuration:
```
  cmake ../ -DRDK_BUILD_SWIG_WRAPPERS=ON \
                   -DPYTHON_NUMPY_INCLUDE_PATH="$CONDA_PREFIX/lib/python3.7/site-packages/numpy/core/include" \
                   -DBOOST_ROOT="$CONDA_PREFIX"
```

- RDKit Version: latest `master` branch
- Platform: Ubuntu 16.04

**Comment by greglandrum** [comment]
Which version of SWIG are you using?

**Comment by CamAnNguyen** [comment]
@greglandrum , i'm using SWIG 3.0.8

**Comment by greglandrum** [comment]
Then that's not the problem.
Which g++ version?
Can you please do:
`VERBOSE=1 make GraphMolWrap` and send the part that shows how swig is being called?

Just as a reference: the AzureDevOps builds that we do using SWIG 3.0.8 on Ubuntu 16.04 and those work fine:
https://dev.azure.com/rdkit-org/RDKit-main-build/_build/results?buildId=199

**Comment by CamAnNguyen** [comment]
@greglandrum  Thank you for the link of AzureDevOps. If I turned off the `RDK_BUILD_PYTHON_WRAPPERS` flag, then it's compiling without any error. Is `rdkit` suppose to have 1 wrapper at a time? Or because `boost::Python` does not work with SWIG ?

**Comment by greglandrum** [comment]
Neither of those should be relevant, but there is clearly something odd going on here

**Comment by CamAnNguyen** [comment]
There is another issue, compiling `rdkit` with SWIG 4.0.0 has errors:

```
[ 99%] jar cf org.RDKitDoc.jar -d doc
cd /home/annguyen/rdkit/Code/JavaWrappers/gmwrapper && /usr/bin/cmake -E make_directory build
cd /home/annguyen/rdkit/Code/JavaWrappers/gmwrapper && /usr/bin/cmake -E make_directory build-test
cd /home/annguyen/rdkit/Code/JavaWrappers/gmwrapper && /usr/bin/javac -d build src/org/RDKit/*.java
src/org/RDKit/BitInfoMap.java:57: error: incompatible types: SWIGTYPE_p_std__mapT_unsigned_int_std__vectorT_std__pairT_boost__uint32_t_boost__uint32_t_t_t_std__lessT_unsigned_int_t_t__iterator
 cannot be converted to Iterator
    Iterator itr = find((Long) key);
                       ^
src/org/RDKit/BitInfoMap.java:66: error: incompatible types: SWIGTYPE_p_std__mapT_unsigned_int_std__vectorT_std__pairT_boost__uint32_t_boost__uint32_t_t_t_std__lessT_unsigned_int_t_t__iterator
 cannot be converted to Iterator
    Iterator itr = find((Long) key);
```

Those are error log with `VERBOSE=1`, do you want to create a new issue to keep track of this one @greglandrum ?

**Comment by greglandrum** [comment]
I haven’t tried swig 4.0 and could imagine that it has problems. It’s probably best to create a separate issue there
