### ISSUE TITLE
HasSubstructMatch fails unexpectedly

### ISSUE THREAD

**Issue by gedeck** [rdkit/rdkit#2539]
**Description:**

- RDKit Version: 2019.03.2
- Platform: Mac, Python 3.7.3, Anaconda install

I would expect this code snippet to print True and not False
```
parent = Chem.MolFromSmiles('O=C(c1n[nH]c2ccccc12)N1C2COCC1C2')
child = Chem.MolFromSmiles('O=CN1C2COCC1C2')
print(parent.HasSubstructMatch(child))

False
```
This is the structure:
![image](https://user-images.githubusercontent.com/8720575/60971499-4bdbeb80-a2f2-11e9-9ee0-f81c64da2e8c.png)

Replacing the parent with the following SMILES gives the expected `True`, so I assume it has to do with the bicyclic ring system and with a ring connected to the carbonyl
```
parent = Chem.MolFromSmiles('O=C(c1n[nH]c2ccccc12)N1CCOCC1')
parent = Chem.MolFromSmiles('O=C(CCCCCCCC)N1C2COCC1C2')
```
![image](https://user-images.githubusercontent.com/8720575/60972178-ba6d7900-a2f3-11e9-8ca0-c4dd0e12b5bc.png)

Other cases that return False:
```
parent = Chem.MolFromSmiles('O=C(C1CCCCCCC1)N1C2COCC1C2')
parent = Chem.MolFromSmiles('O=C(c1ccccc1)N1C2COCC1C2')
```

**Comment by bp-kelley** [comment]
Interestingly, the smarts version matches.
```
>>> sma_child = Chem.MolFromSmarts('O=CN1C2COCC1C2')
>>> print(parent.HasSubstructMatch(sma_child))
True
```

**Comment by greglandrum** [comment]
Here's a further simplification of the example:
```
In [31]: child2 = Chem.MolFromSmiles('N1C2COCC1C2')                             

In [32]: parent2 = Chem.MolFromSmiles('C1CC1CN1C2COCC1C2')                      

In [33]: parent2.HasSubstructMatch(child2)                                      
Out[33]: False

In [34]: parent2 = Chem.MolFromSmiles('CCCCN1C2COCC1C2')                        

In [35]: parent2.HasSubstructMatch(child2)                                      
Out[35]: True
```

**Comment by complext** [comment]
Hi, this is likely because when SMILES parses strings, it treats them almost as if complete string literals, looking for bond and ring closure identifiers. In the example in question, it will encounter the cyclopropyl group at "1", close it at "1", and thereafter expect a "2" to read. However, there is another ring, also labeled "1", and instead of closing that one, it opens "2". Hence, SMILES fails here.

However, SMARTS does not have this problem. It opens and closes rings sequentially & correctly. It is generally advisable to use SMARTS for functional group/fragment recognition.

**Comment by greglandrum** [comment]
That's not really an accurate description of the way the RDKit parsers work. I haven't tracked this bug down yet, but I think it's unlikely to be due to problems with the SMILES parser

**Comment by complext** [comment]
> That's not really an accurate description of the way the RDKit parsers work. I haven't tracked this bug down yet, but I think it's unlikely to be due to problems with the SMILES parser

Oops. My bad. Just trying to look for problems, I know FROWNS parsed SMILES in a fashion somewhat like this, just might have thought that was the cause for the issue. Don't listen to me! :d
