### ISSUE TITLE
unneeded chirality was assigned by AssignAtomChiralTagsFromStructure

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [rdkit/rdkit#2540]
## Environment

- RDKit Version: 2019.03.2
- OS: CentOS Linux release 7.4.1708 (Core)
- Python: 3.7.3 (Anaconda3-2019.03 with pyenv)

## Simple scripts to reproduce a bug

```py
from rdkit.Chem import AllChem, Draw
from rdkit import Chem

mol = Chem.MolFromSmiles("C1CC1C")
mol = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol)
mol = Chem.RemoveHs(mol)
Chem.AssignAtomChiralTagsFromStructure(mol)
AllChem.Compute2DCoords(mol)
Draw.MolToImage(mol)
```

Then, I got below image

![download](https://user-images.githubusercontent.com/6902135/61033647-ddd11a80-a3fe-11e9-8090-8383ada3ea52.png)

Obviously, methylcyclopropane should not have chirality. I'll appreciate if you fix it.

**Comment by greglandrum** [comment]
I'm aware that it's confusing, but this is actually doing what it's supposed to do.
`AssignAtomChiralTagsFromStructure()` just looks at the 3D arrangement of the bonds around an atom and sets the chiral tag appropriately.
If you then want to cleanup chiral specifications that are not valid, you need to call
`Chem.AssignStereochemistry(mol,cleanIt=True,force=True)`  after the call to `AssignAtomChiralTagsFromStructure()`

The better solution is to call `Chem.AssignStereochemistryFrom3D(mol2)`. This will assign double bond stereochemistry and atomic stereochemistry based on the conformation and do the call to `AssignStereochemistry()` that removes invalid specifications.

**Comment by keisuke-yanagisawa** [comment]
I confirmed that `Chem.AssignStereochemistryFrom3D(mol)` do assign them naturally. Thank you for the lecture!

**Comment by greglandrum** [comment]
I'm glad that helped
