### ISSUE TITLE
Expand types of Fingerprints available in PandasTools

### ISSUE THREAD

**Issue by aparente** [rdkit/rdkit#2543]
Is there a way to specify the type of fingerprinting used when calling PandasTools.AddMoleculeColumnToFrame(smilescol, molcol, includeFingerprints=True)? I'd prefer to use Morgan fingerprints.

**Comment by greglandrum** [comment]
The fingerprints added by `AddMoleculeColumnToFrame()` are used to speed up substructure searching. As such, they need to be "substructure fingerprints" (i.e. have the property that all bits found in a substructure are also found in the molecule it matches). The Morgan fingerprints are not substructure fingerprints, so they can't be used for this purpose.

**Comment by greglandrum** [comment]
If you are looking to do similarity searching in pandas DataFrames, this might be helpful: https://gist.github.com/greglandrum/045ccf8009fde91fc985864e70ee72a1

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
