### ISSUE TITLE
LazyBitVectorPick: Python C++ arguments do not match

### ISSUE THREAD

**Issue by gdreiman1** [rdkit/rdkit#2544]
**Description:**

- RDKit Version: '2019.03.1'
- Platform: Ubuntu 18.04.2
- Python: 3.7

I'm trying to use LazyBitVectorPick on a list of bit vectors, but get the following error: 
`ArgumentError: Python argument types in
    None.LazyBitVectorPick(list, int, int)
did not match C++ signature:
    LazyBitVectorPick(RDPickers::MaxMinPicker* self, boost::python::api::object objects, int poolSize, int pickSize, boost::python::api::object firstPicks=(), int seed=-1, boost::python::api::object useCache=None)`

From the following code:

```
import glob
from rdkit import Chem
from rdkit.Chem import Draw,rdMolDescriptors,AllChem
from rdkit.SimDivFilters.rdSimDivPickers import MaxMinPicker
path_to_sdf = glob.glob(AID_path+'/*.sdf')[0]
suppl = Chem.SDMolSupplier(path_to_sdf)
new_mfp = []
for mol in suppl:
    if mol is not None:
        new_mfp.append(rdMolDescriptors.GetMorganFingerprintAsBitVect(mol,2))
indexs = MaxMinPicker.LazyBitVectorPick(new_mfp,len(new_mfp),150)
```
I think that the list containing the fingerprints isn't the right type? But there are multiple tutorials that use essentially identical code and presumably work.

**Comment by greglandrum** [comment]
If you look at the online examples, you will notice that they create a MaxMinPicker object first, and then use its LazyBitVectorPick() method. You're trying to call the method directly from the class.

**Comment by gdreiman1** [comment]
Got it, thank you.
