### ISSUE TITLE
Set Bounds Matrix for Embedding

### ISSUE THREAD

**Issue by gncs** [rdkit/rdkit#2549]
I would like to provide a bounds matrix for the DG algorithm. Is there a way of doing that?

I know of the `AllChem.GetMoleculeBoundsMatrix(mol)` function but from I understand from looking through the source code manipulating this matrix has no effect on conformer generation.

Could anybody point me to the relevant (Python?) functions that would allow me to do that? Thank you very much!

**Comment by greglandrum** [comment]
Hi,
At the moment there's no easy way to do this. I'm working on a feature addition for the next release so that this will be straightforward.

**Comment by gncs** [comment]
That would be great, thank you! :)

**Comment by gncs** [comment]
Thank for adding this feature in 116cebf3. I will try it out right away!

One thing: is there a reason why the method starts with a upper-case S?
https://github.com/rdkit/rdkit/blob/116cebf3853d6deb245be5d3c4f40827aeaed657/Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp#L372

**Comment by bp-kelley** [comment]
Most wrapped python class methods in the RDKit are upper case.  This is just following that style guide.

**Comment by gncs** [comment]
OK, I understand. I guess the reason why I stumbled over that was that the other settings are accessible through properties (e.g, `clearConfs`), whereas this "setting" is only accessible through a method call (and assigning a matrix to the variable `boundsMat` has no effect).

Anyway, thank you very much for implementing this - I works like charm! :)
