### ISSUE TITLE
[SOLVED] RDKit fails to parse SMILES string with an aromatic iodonium salt

### ISSUE THREAD

**Issue by apahl** [rdkit/rdkit#2550]
**Description:**

- RDKit Version: 2019.03.2
- Platform: Linux, conda

RDKit fails to parse this SMILES string with an aromatic iodonium salt into a valid molecule:
```Python
mol = Chem.MolFromSmiles('[i+]1c2c(cccc2)c(cccc3)c13.[Cl-]')
type(mol)  # --> NoneType
```
and gives the following warnings:
```
RDKit ERROR: [12:58:23] SMILES Parse Error: syntax error while parsing: [i+]1c2c(cccc2)c(cccc3)c13.[Cl-]
RDKit ERROR: [12:58:23] SMILES Parse Error: Failed parsing SMILES '[i+]1c2c(cccc2)c(cccc3)c13.[Cl-]' for input: '[i+]1c2c(cccc2)c(cccc3)c13.[Cl-]'

```
The SMILES was generated by a different tool and the molecule looks like this (generated with Peter's [JSME](https://www.peter-ertl.com/jsme/JSME_2017-02-26/JSME.html) out of the same SMILES):  
![image](https://user-images.githubusercontent.com/9406836/61289645-13dd1880-a7ca-11e9-8bc3-c8656537999c.png)

While writing this down I noticed that the fix is to use the upper case `I` instead of the `i`, so the SMILES should read: `[I+]1c2c(cccc2)c(cccc3)c13.[Cl-]`. JSME also returns the uppercase `I` when generating the SMILES out of the molecule again.

I'm leaving this here for documentation, but will close later.

Kind regards,  
Axel

**Comment by danielmanu93** [comment]
Hi I'm having similar issue. I'm trying to generate molecules from smiles with the attached generate function but I get the "SMILES parse error" in the terminal when I call the function. How can I fix this issue?

![1](https://user-images.githubusercontent.com/67971334/121855620-cbc61980-ccb0-11eb-9b03-851181c6e748.jpeg)
![2](https://user-images.githubusercontent.com/67971334/121855626-cec10a00-ccb0-11eb-8470-cc2ef1df6c91.jpeg)

**Comment by apahl** [comment]
Well,

looking at the code and at the error message, it looks like you are trying to generate the molecules directly from the binary pickle files.  
This does not work, you need to unpickle the file first.

KR Axel

**Comment by danielmanu93** [comment]
Thanks for the reply, but I haven't really tried unpickling SMILES data before. Can you give me a sample code of how it should look like in this case?

**Comment by apahl** [comment]
Where did you get the pickle (`.pkl`) file from? You should not open binary pickle files from untrusted sources, that is a security risk.  
As to how to read pickle files, please have a look at the [Python documentation](https://docs.python.org/3/library/pickle.html).

And finally, your issue is not at all "similar" to the original issue and it is not a bug of the RDKit.  
I recommend posting on the RDKit mailing list or in the `discussions` section of this repo, instead, then your request will also reach more people.

KR Axel
