### ISSUE TITLE
BRICSDecomposition result

### ISSUE THREAD

**Issue by OnlyBelter** [rdkit/rdkit#2554]
**Description:**

- RDKit Version: 2019.03.1
- Platform: Windows 10

As the [document](https://www.rdkit.org/docs/source/rdkit.Chem.BRICS.html) shows, if we use `BRICSDecomposition` to fragment a molecule, we can get:
```
>>> m = Chem.MolFromSmiles('CCCOCC')
>>> res = list(BRICSDecompose(m,keepNonLeafNodes=True))
>>> sorted(res)
['CCCOCC', '[3*]OCC', '[3*]OCCC', '[3*]O[3*]', '[4*]CC', '[4*]CCC']
```

I would like to ask, if the fragments are represented by valid `Dayligth SMARTS` format? If so, what's the meaning of `[3*]` and `[4*]`? 

I checked the [document](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html) of `SMARTS`, [35*] means any atom of mass 35. 

Does `3` and `4` in `[3*]` and `[4*]` mean mass 3 and mass 4 as well?

**Comment by bp-kelley** [comment]
There is no chemical meaning in this case.  The isotopes are being used as
a convenient way to annotate/label the atoms.  This technique is used
fairly liberally in the RDKit.

In this case, the BRICs algorithm makes use of the isotope labelling when
rebuilding molecules from the fragmentations.

Cheers,
 Brian

**Comment by OnlyBelter** [comment]
Thanks a lot! By the way, do you know if there is a way that we can define the bond-breaking rules by ourselves?

**Comment by OnlyBelter** [comment]
I find it, we can use [FragmentOnBonds](http://rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.FragmentOnBonds).
