### ISSUE TITLE
templates.mae is required by Findcoordgen.cmake but never used

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#2555]
**Description:**

- RDKit Version: 2019.3
- Platform: Debian

Upstream coordgen does not install `templates.mae` but `Findcoordgen.cmake` insists on finding it as `coordgen_TEMPLATE_FILE` - I guess that is fine for the locally built one in `External/Coordgen` but means that `find_package(coordgen)` won't work for finding a system-installed coordgen even if coordgen shipped a cmake file (see https://github.com/schrodinger/coordgenlibs/issues/31).

Is `templates.mae` used by RDKit and/or RDKit's use of maeparser/coordgenlib? If not, maybe it needs not be installed and/or `coordgen_TEMPLATE_FILE` can be removed?

**Comment by greglandrum** [comment]
I believe that `templates.mae` is important to the proper functioning of coordgen. Not installing that is probably a bug/oversight in the upstream.

**Comment by mbanck** [comment]
I was looking at an earlier coordgen release, the current one does install it, so closing this.
