### ISSUE TITLE
RingInfo Cannot Be Instantiated

### ISSUE THREAD

**Issue by complext** [rdkit/rdkit#2561]
**Description: RDKit for Python fails to instantiate RingInfo module**

- RDKit Version: 2016.03.5
- Platform: Ubuntu 18.04.2 TLS over Windows 10

Hi, I am trying to instantiate the RingInfo.cpp class in RDKit for Python as there are functions of interest, as well as ones I have created in RingInfo.cpp that I would like to call from a Python script. When I go to call it after importing it, it cannot be used because as the API notes, all RingInfo class functions can be called only after instantiating the object. So, I try to do this, but I see that the compiler cannot instantiate it.

```
>>> from rdkit.Chem import RingInfo
>>> m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
>>> x = RingInfo(m)
Traceback (most recent call last):
   File "<stdin>", line 1, in module <module>
RuntimeError: This class cannot be instantiated from Python
```
Is this because RingInfo has not been added to the BOOST Library when RDKit was built? I installed my current RDKit by simply installing via the installation instructions' recommended one-line command:
```
sudo apt-get install python-rdkit librdkit1 rdkit-data
```
And I am using Python 2.7.15. I'm willing to try building from source on another PC that will actually achieve this (Ubuntu over Windows has not worked out for me after 3 days of trying to build from source) and modify the CMake instructions accordingly to include RingInfo in the Python wrapper if it hasn't been already--but my necessary and first questions are:

-Why is this happening? Why can't I instantiate RingInfo?
-Has RingInfo been properly included in the BOOST library that creates the C++ Pythonic wrapper?
-How can I go about fixing this myself? I'm really just a novice, unfamiliar with many high-level details, so please explain. 

My thanks to all in advance.

**Comment by bp-kelley** [comment]
You can get the ring info directly from the molecule:

>>> m = Chem.MolFromSmiles('OC1C2C1CC2') >>> ri = m.GetRingInfo()
>>> ri.NumAtomRings(0)
This is detailed in the starting guide.

https://www.rdkit.org/docs/GettingStartedInPython.html


----
Brian Kelley

**Comment by complext** [comment]
Well, this is the simplest answer to meet a dumb question that wasted the most time on it. Thank you sir!!!
As a final follow-up, does this mean if I introduced my own method into RingInfo.cpp and RingInfo.h, I have to rebuild from this "newly edited" source so that the wrapper will include the method, assuming I wish to call it from Python? And perhaps edit the cmake config file too?

**Comment by bp-kelley** [comment]
No you would have to expose it manually in the boost python wrappers.  It’s not terribly hard but it is initially confusing.

The wrapper is here:

https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Wrap/RingInfo.cpp

----
Brian Kelley

**Comment by bp-kelley** [comment]
@complext if you have any more questions on this, feel free to reopen the issue or open a new one.
