### ISSUE TITLE
Generate drawable SMILES from molecule fragment

### ISSUE THREAD

**Issue by aaron-barbieriaghib** [rdkit/rdkit#2564]
Hi, 

I am relatively new to Rdkit and I apologize if this isn't the right place to ask this. I am dealing with molecule fragments in SMILES notation, such as 'cC(=O)N(C)C', and when I try to draw the molecule, I get the following error: `ERROR: non-ring atom 0 marked aromatic`. Now, of course I could set `sanitize=False` in my `Chem.MolFromSmiles()` function, but then I lose information in my drawing. 

Is there a way to intelligently interpret the SMILES fragment, and create the simplest molecule that is valid, and highlight the parts that were in the original fragment? So in the 'cC(=O)N(C)C' example, I would want the first carbon to be part of an aromatic ring, and for the actual 'cC(=O)N(C)C' fragment to be highlighted. Is this at all possible?

Other examples are more complicated and involve multiple aromatic rings, such as 'cnnc' (or perhaps both nitrogens here are part of the same aromatic ring?).

Best, 
Aaron

**Comment by CKannas** [comment]
Hi Aaron,

I think to do what you are looking for, using SMARTS is more suitable. I.e.
"[c]-[C;X3](=[O;X1])[N;X3]([C;X4])[C;X4]",
"[c]-[CH1](=[O;X1])[N;X3]([CH3])[CH3]"
From my limited knowledge of SMILES, you can define fragments by having
dummy atoms at the connection points, i.e. "[*]C(=O)N(C)C"

Best,

Christos

Christos Kannas

**Comment by bp-kelley** [comment]
Aaron,
  Depicting from a smiles fragment is problematic.  As you discovered, you can't actually make a molecule.  Using a smarts pattern helps somewhat, however you loose some important things, like knowing that a set of carbons were in a ring.

You CAN however, depict a portion of a molecule that has been extracted.

```
from rdkit.Chem import AllChem
m = AllChem.MolFromSmiles("Cc1ccncc1")
AllChem.Compute2DCoords(m)
path = m.GetSubstructMatch(Chem.MolFromSmarts("Ccccn"))
submol = AllChem.PathToSubmol(m, path)
````

It's not perfect, but works ok.

![image](https://user-images.githubusercontent.com/9888416/61911393-58bd2980-af05-11e9-8b4f-e102e5f44deb.png)

**Comment by aaron-barbieriaghib** [comment]
Thank you so much for the responses! Although I like the second approach, unfortunately, I don't have access to the original molecules from which the fragments were extracted. I was hoping it would be possible to "reconstruct" the simplest form of the molecule which the fragment could be embedded in. Oh well, thanks again for responding though!
