### ISSUE TITLE
Retain pdb atom names from maestro file in RDkit/pandas dataframe

### ISSUE THREAD

**Issue by aparente-nurix** [rdkit/rdkit#2566]
I have a 3D multi-structure maestro file that has been run through LigPrep. I'd like to load this into RDkit/pandas to do fingerprinting and select a diverse set of molecules out of this set of structures using the MaxMinPicker(). 

I'd then like to write these selected molecules to a maestro/pdb file, ideally retaining their pdb atom names and 3D conformation (the 3D conf is less important, but would be helpful). 

I have the MaxMinPicker() and fingerprinting parts working with an SDFile, but am still trying to figure out if its even feasible to retain the pdb atom names if I use a maestro or pdb file. I haven't been able to find anything about doing this in the documentation.

**Comment by aparente-nurix** [comment]
I found a workaround for this for my use case, but am still generally interested in how to incorporate pdb atom names into rdkit molecules. Is it possible to create  a dictionary that stores the atom name and atom indices?

**Comment by greglandrum** [comment]
If you construct a molecule from a PDB file or sequence, you end up with residue information:
```
In [2]: m = Chem.MolFromPDBFile('1CRN.pdb')                                                                                                                     

In [3]: at = m.GetAtomWithIdx(0)                                                                                                                                

In [4]: ri = at.GetPDBResidueInfo()                                                                                                                             

In [5]: ri.GetName()                                                                                                                                            
Out[5]: ' N  '

In [6]: ri.GetResidueName()                                                                                                                                     
Out[6]: 'THR'                                                                                                                          

In [13]: m2 = Chem.MolFromSequence('GYLG')                                                                                                                      

In [14]: at = m2.GetAtomWithIdx(0)                                                                                                                              

In [15]: at.GetPDBResidueInfo().GetName()                                                                                                                       
Out[15]: ' N  '

In [16]: at.GetPDBResidueInfo().GetResidueName()                                                                                                                
Out[16]: 'GLY'
```

It looks like residue information is not read from MAE files, but this may be something that can be added.

**Comment by greglandrum** [comment]
@lorton : think that it would be reasonable to read in residue information (when available) from MAE files?

**Comment by lorton** [comment]
This seems completely reasonable to me (and pretty easy), I'll see if I can get a PR up later this week.

**Comment by lorton** [comment]
Not quite "later this week", but finally got a PR up for this.
