### ISSUE TITLE
EmbedMolecule random seed control

### ISSUE THREAD

**Issue by PikachuSauvage** [rdkit/rdkit#2575]
Hi,
We are having troubles to fix the random component in EmbedMolecule and want to ask for some help.

What we are tring to do is to fix every random factor in EmbedMolecule() so that we can reproduce exactly the same structure once again and we constantly failed to do so after useRandomCoords=False, randomSeed = 0. 

our codes looks like this:
m2 = Chem.MolFromSmiles(com)
m3 = Chem.AddHs(m2)
AllChem.EmbedMolecule(m3, useRandomCoords=False,  randomSeed = 0)
Chem.MolToMolFile(m3,'CheckMol'+str(index)+'.sdf')

As greglandrum is mentioning earlier, there is a random component. Is there any parameters we are missing in this case?

_Originally posted by @PikachuSauvage in https://github.com/rdkit/rdkit/issues/963#issuecomment-516272274_

**Comment by PikachuSauvage** [comment]
One SMILES that can reproduce this issue: CCCCCNCCCC

**Comment by greglandrum** [comment]
Try setting the randomSeed (which is the seed used by the random number generator) to a value >0:
```
In [13]: AllChem.EmbedMolecule(m,randomSeed=42)                                                                             
Out[13]: 0

In [14]: print(Chem.MolToMolBlock(Chem.RemoveHs(m)))                                                                        

     RDKit          3D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -1.7765    0.4690   -0.7247 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3589   -0.3929    0.4218 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1079   -0.7665    0.3015 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8555    0.4401    0.3048 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.2793    0.2728    0.1969 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
M  END


In [15]: AllChem.EmbedMolecule(m,randomSeed=42)                                                                             
Out[15]: 0

In [16]: print(Chem.MolToMolBlock(Chem.RemoveHs(m)))                                                                        

     RDKit          3D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -1.7765    0.4690   -0.7247 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3589   -0.3929    0.4218 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1079   -0.7665    0.3015 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8555    0.4401    0.3048 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.2793    0.2728    0.1969 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
M  END
```

**Comment by PikachuSauvage** [comment]
The problem is fixed now with randomseed > 0.

We tried to reproduce the same issue on another system with randomseed =0 and we couldn't reproduce it. 

I am closing this issue. Thanks very much for your help.
