### ISSUE TITLE
Broken bonds generated in PrepareMolForDrawing with addChiralHs=True

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#2577]
**PrepareMolForDrawing generates broken bonds**

- RDKit Version: 2019.03.3 (it was fine on 2018.03.04, I think got introduced in 2018.09)
- Platform: Ubuntu 16.04 and Windows Server 2012 R2
- Python: 3.6, 3.7 (2018.03.04 were issue is not present was on 3.5)

I ran into this issue when batch generating svg images. Some questionably drawn "legacy" structures converted to molfiles are causing an issue in `PrepareMolForDrawing` with `addChiralHs=True`.

The issue is that chiral Hs and bonds are generated but the bonds have a bond length of `nan`. 
I'm using this for scaling the images.
It seems like the Hs are added but then fail to be placed correctly and have `nan` for all coordinates.

Working around this issue the image can still be generated and displayed in Jupyter notebook but these bonds are present in the raw svg text also with nan values. Certain svg code doesn't play nice with this (namley KNIME String to SVG node).

It's important to note that it really depends on the coordinates (2D conformer) of the molecule. The same molecule I will use as example works just fine if generated from inchi. (Note there are quiet a few structures affected, this is not a sinlge incident). 

As mentioned above this issue did not occur in 2018.03.04 and Python 3.5. Due to playing around I updated the environment on Windows machine but I'm fairly certain (but not 100%) that was running 2018.09 (on python 3.6) and already had the issue. 

Example (copy&pasted from Jupyter notebooks cells):
```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.Draw import rdMolDraw2D
import math

molblock = """Untitled Document
  ChemDraw01412500423620482D

 17 19  0  0  0  0  0  0  0  0999 V2000
   -0.4569    0.0949    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
    0.9044   -0.6601    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
   -0.4569   -0.6601    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
    0.9044    0.0949    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
    0.2238    0.5611    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
    0.9044    0.9433    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
   -0.4569    0.9154    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
    0.2331    1.3908    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
   -1.8179   -0.6601    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
   -1.1373    0.5611    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
   -1.8179    0.0949    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
    0.9417   -1.6578    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
    1.8179   -0.5949    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
   -1.1373    1.3861    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
   -0.4569   -1.4851    0.0000 H   0  0  0  0  0  0  0  2  0  0  0  0
    1.3169    1.6578    0.0000 O   0  0  0  0  0  0  0  2  0  0  0  0
    1.7013    0.7298    0.0000 C   0  0  0  0  0  0  0  2  0  0  0  0
  2  3  1  0      
  3  1  1  0      
  4  5  1  6      
  1  5  1  6      
  6  8  1  0      
  7  1  1  0      
  8  7  1  0      
  9  3  1  0      
 10  1  1  0      
 11 10  1  0      
 12  2  1  0      
 13  2  1  0      
 11  9  1  0      
  4  2  1  0      
  4  6  1  0      
 10 14  1  1      
  3 15  1  1      
  6 16  1  1      
  6 17  1  6      
M  END
"""

def check_bonds(mol):
    
    bonds = mol.GetBonds()    

    for bond in bonds:

        ai = bond.GetBeginAtomIdx()
        aj = bond.GetEndAtomIdx()
        bl = AllChem.GetBondLength(mol.GetConformer(), ai, aj)
        if math.isnan(bl):# invalid bonds            
            print("Broken Bond: Atom {} {} to {} {}".format(mol.GetAtomWithIdx(ai).GetSymbol(), ai, mol.GetAtomWithIdx(aj).GetSymbol(), aj))


mol = Chem.MolFromMolBlock(molblock)
check_bonds(mol) # not output

mol_prepared = rdMolDraw2D.PrepareMolForDrawing(mol, kekulize=True, addChiralHs=True)
check_bonds(mol_prepared) # 2 broken bonds with length nan

pos = mol_prepared.GetConformer().GetAtomPosition(16)
print("x: {}, y: {}, z: {}".format(pos.x, pos.y, pos.z)) #nan for all
```

**Comment by greglandrum** [comment]
Confirmed. Thanks for the bug report @kienerj

**Comment by greglandrum** [comment]
I'm not sure when it was fixed, but this no longer appears to be an issue in v2024.03.1
