### ISSUE TITLE
MaeMolSupplier cannot handle certain properties even if they are in the right format

### ISSUE THREAD

**Issue by aparente-nurix** [rdkit/rdkit#2579]
**Description:**

- RDKit Version:
'2019.03.1'
- Platform:
Windows 10
Python 3.7 (anaconda)

MaeMolSupplier generates an error when loading a mae file containing the property "i_f3d_flags". I'm not sure what this property actually corresponds to, my best guess is it may be related to fast3D and/or ligprep. Manually deleting this property name and its value from the mae file fixes the issue. 

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-8d26cd3400fa> in <module>
----> 1 tier_1_ligand = rdmolfiles.MaeMolSupplier(gzip.open('pom_pos1_NRX-0390468-R-S_43_388934_pos1-S-R.maegz'))
      2 tier_1_ligand

RuntimeError: Line 30, column 6: Bad format for property; must be (b|i|r|s)_<author>_<name>.
<!-- If applicable, please provide code that can reproduce your issue -->

```
```
tier_1_ligand = rdmolfiles.MaeMolSupplier(gzip.open('test.maegz'))
```

**Comment by ricrogz** [comment]
Hi, @aparente-nurix. The issue you have reported is not related to RDKit, but to [maeparser](https://github.com/schrodinger/maeparser), the library used to parse .mae files. I have just submitted a pull request there to fix this problem. As soon as there is a new release of maeparser, I will add a PR here to update to it.
