### ISSUE TITLE
rdkit ImportError: cannot import name 'Chem

### ISSUE THREAD

**Issue by tszjqgs** [rdkit/rdkit#2580]
**Description:**

- RDKit Version: 2019.03.3.0
- Platform: windows anaconda 

I run the code in anaconda ,jupyternotebook ,
when I run import rdkit ,it can get through,but when running from rdkit import Chem ,it gives me 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-3a181df69616> in <module>
----> 1 from rdkit import Chem

ImportError: cannot import name 'Chem'

```
conda list env:

my-rdkit-env) C:\Users\Thinkpad>conda list
# packages in environment at E:\program_files\Anaconda3\envs\my-rdkit-env:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2019.5.15                     0
cairo                     1.14.12              hf171d8a_3
certifi                   2019.6.16                py37_1
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
intel-openmp              2019.4                      245
jpeg                      9b                   hb83a4c4_2
libboost                  1.67.0               hd9e427e_4
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.0.10               hb898794_2
mkl                       2019.4                      245
mkl_fft                   1.0.12           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
numpy                     1.16.4           py37h19fb1c0_0
numpy-base                1.16.4           py37hc3f5095_0
olefile                   0.46                     py37_0
openssl                   1.1.1c               he774522_1
pandas                    0.25.0           py37ha925a31_0
pillow                    6.1.0            py37hdc69c19_0
pip                       19.1.1                   py37_0
pixman                    0.38.0               he774522_0
py-boost                  1.67.0           py37h8300f20_4
python                    3.7.3                h8c8aaf0_1
python-dateutil           2.8.0                    py37_0
pytz                      2019.1                     py_0
rdkit                     2019.03.3.0      py37h3d1ada6_1    rdkit
setuptools                41.0.1                   py37_0
six                       1.12.0                   py37_0
sqlite                    3.29.0               he774522_0
tk                        8.6.8                hfa6e2cd_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wheel                     0.33.4                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

python version 3.7.3
and I used this following way intall :

$ conda create -c rdkit -n my-rdkit-env rdkit

$ conda activate my-rdkit-env

It really a tough job to get rdkit running , since I started try to install from version 2018  and tried
conda install -c rdkit rdkit , dont work either . already several hours been put into the different error pops up . appreciated if anything ring a bell 


![image](https://user-images.githubusercontent.com/14088515/62258662-dd480480-b43d-11e9-8639-66a5b6ca98f9.png)

**Comment by greglandrum** [comment]
You don't have jupyter installed in that environment, so when you run `jupyter` it is using the one from your base environment.
Try installing jupyter in `my-rdkit-env` and the problem should go away.

**Comment by tszjqgs** [comment]
thanks ,I installed jupyter ,and still got the same problem . my conda list is as follow:

my-rdkit-env) C:\>conda list
# packages in environment at E:\program_files\Anaconda3\envs\my-rdkit-env:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                   pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
blas                      1.0                         mkl
bleach                    3.1.0                    pypi_0    pypi
ca-certificates           2019.5.15                     0
cairo                     1.14.12              hf171d8a_3
certifi                   2019.6.16                py37_1
colorama                  0.4.1                    pypi_0    pypi
decorator                 4.4.0                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
intel-openmp              2019.4                      245
ipykernel                 5.1.1                    pypi_0    pypi
ipython                   7.7.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.14.1                   pypi_0    pypi
jinja2                    2.10.1                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
json5                     0.8.5                    pypi_0    pypi
jsonschema                3.0.1                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            5.3.1                    pypi_0    pypi
jupyter-console           6.0.0                    pypi_0    pypi
jupyter-core              4.5.0                    pypi_0    pypi
jupyter-echarts-pypkg     0.1.5                    pypi_0    pypi
jupyterlab                1.0.4                    pypi_0    pypi
jupyterlab-server         1.0.0                    pypi_0    pypi
libboost                  1.67.0               hd9e427e_4
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.0.10               hb898794_2
lml                       0.0.9                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2019.4                      245
mkl_fft                   1.0.12           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
nbconvert                 5.5.0                    pypi_0    pypi
nbformat                  4.4.0                    pypi_0    pypi
notebook                  6.0.0                    pypi_0    pypi
numpy                     1.16.4           py37h19fb1c0_0
numpy-base                1.16.4           py37hc3f5095_0
olefile                   0.46                     py37_0
openssl                   1.1.1c               he774522_1
pandas                    0.25.0           py37ha925a31_0
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.5.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    6.1.0            py37hdc69c19_0
pip                       19.1.1                   py37_0
pixman                    0.38.0               he774522_0
prometheus-client         0.7.1                    pypi_0    pypi
prompt-toolkit            2.0.9                    pypi_0    pypi
py-boost                  1.67.0           py37h8300f20_4
pyecharts-jupyter-installer 0.0.3                    pypi_0    pypi
pygments                  2.4.2                    pypi_0    pypi
pyrsistent                0.15.4                   pypi_0    pypi
python                    3.7.3                h8c8aaf0_1
python-dateutil           2.8.0                    py37_0
pytz                      2019.1                     py_0
pywinpty                  0.5.5                    pypi_0    pypi
pyzmq                     18.0.2                   pypi_0    pypi
qtconsole                 4.5.2                    pypi_0    pypi
rdkit                     2019.03.3.0      py37h3d1ada6_1    rdkit
send2trash                1.5.0                    pypi_0    pypi
setuptools                41.0.1                   py37_0
six                       1.12.0                   py37_0
sqlite                    3.29.0               he774522_0
terminado                 0.8.2                    pypi_0    pypi
testpath                  0.4.2                    pypi_0    pypi
tk                        8.6.8                hfa6e2cd_0
tornado                   6.0.3                    pypi_0    pypi
traitlets                 4.3.2                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.4                   py37_0
widgetsnbextension        3.5.1                    pypi_0    pypi
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

(my-rdkit-env) C:\>

**Comment by tszjqgs** [comment]
issue fixed, and I found the following link really helped.
http://davies-lee.com/index.php/2018/10/06/rdkit-in-jupyter-notebooks/

**Comment by greglandrum** [comment]
Thanks for pointing to that blog post. That’s super helpful for windows users who want to start Jupyter via a shortcut

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by insilico-ai** [comment]
> issue fixed, and I found the following link really helped.
> http://davies-lee.com/index.php/2018/10/06/rdkit-in-jupyter-notebooks/

Thanks a lot, Davies. It worked.
