### ISSUE TITLE
Chem.rdFMCS.FindMCS hangs for certain ligand pairs

### ISSUE THREAD

**Issue by lohedges** [rdkit/rdkit#2581]
RDKit version: 2019.03.2
Platform: Python 3.7, Linux

We've been using RDKit to generate MCS mappings within [BioSimSpace](https://github.com/michellab/BioSimSpace) with great success. However, for certain ligand pairs the `Chem.rdFMCS.FindMCS` algorithm appears to hang indefinitely, completely ignoring the timeout. I can't even kill it with CTRL+C, having to manually terminate the process.

The following example illustrates the problem, using [ligand1](https://github.com/rdkit/rdkit/files/3457194/ligand1.txt) and  [ligand2](https://github.com/rdkit/rdkit/files/3457197/ligand2.txt) as input. (These are Cathepsin PDB files from the D3R2018 challenge, where the extension has been changed to `txt` to allow upload.)

```python
import rdkit.Chem as Chem
import rdkit.Chem.rdFMCS as rdFMCS

# Load the ligands.
mols = [Chem.MolFromPDBFile("ligand1.txt", False, False, 0),
        Chem.MolFromPDBFile("ligand2.txt", False, False, 0)]

# Run a very short MCS. (One second)
mcs = rdFMCS.FindMCS(mols, atomCompare=rdFMCS.AtomCompare.CompareAny,
    bondCompare=rdFMCS.BondCompare.CompareAny, completeRingsOnly=True,
    ringMatchesRingOnly=True, matchChiralTag=False, matchValences=False,
    maximizeBonds=False, timeout=1, verbose=True)
```

This returns the following before hanging. (There is no change in memory during the hang and my iPython session is using only 140 MiB.)

```
Query [H]C1C([H])C(C(SC([H])([H])C([H])([H])[N+]2([H])C([H])([H])C([H])([H])C([H])(C(F)(F)F)C([H])([H])C2([H])[H])C([H])C1C1NN(C2C1C([H])([H])N(C([H])([H])C2([H])[H])S(O)(O)C([H])([H])[H])C([H])([H])C([H])([H])C([H])([H])[N+]1([H])C([H])([H])C([H])([H])C([H])(N2C(O)C([H])([H])C([H])([H])C2([H])[H])C([H])([H])C1([H])[H])C(F)(F)F 99(99) atoms, 104(104) bonds
1 Seeds:105 MCS 5 atoms, 4 bonds for 0.0016 seconds. bond[0]=0
2 Seeds:106 MCS 10 atoms, 10 bonds for 0.0016 seconds. bond[0]=0
3 Seeds:107 MCS 21 atoms, 21 bonds for 0.0017 seconds. bond[0]=0
4 Seeds:108 MCS 31 atoms, 33 bonds for 0.0018 seconds. bond[0]=0
5 Seeds:109 MCS 41 atoms, 43 bonds for 0.0018 seconds. bond[0]=0
6 Seeds:110 MCS 53 atoms, 55 bonds for 0.0019 seconds. bond[0]=0
7 Seeds:111 MCS 62 atoms, 64 bonds for 0.0020 seconds. bond[0]=0
8 Seeds:112 MCS 70 atoms, 73 bonds for 0.0021 seconds. bond[0]=0
9 Seeds:113 MCS 78 atoms, 81 bonds for 0.0023 seconds. bond[0]=0
10 Seeds:114 MCS 85 atoms, 89 bonds for 0.0024 seconds. bond[0]=0
11 Seeds:115 MCS 92 atoms, 96 bonds for 0.0025 seconds. bond[0]=0
```

A 92 atom match for this system seems perfectly reasonable to me: `ligand1` contains 99 atoms, and `ligand2` has 102.

[Here's](https://github.com/michellab/BioSimSpace/issues/100) the BioSimSpace issue where this is referenced.

**Comment by lohedges** [comment]
Possibly related to [this](https://github.com/rdkit/rdkit/issues/1585) issue. In our own internal MCS code we would also experience cases where the search space was large. However, this doesn't explain why the timeout option is clearly ignored.

**Comment by lohedges** [comment]
Looking at this part of [MaximumCommonSubgraph.cpp](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp):

```cpp
// Find MCS -- SDF Seed growing OPTIMISATION (it works in 3 times faster)
  while (!Seeds.empty()) {
    if (getMaxNumberBonds() == QueryMoleculeMatchedBonds)  // MCS == Query
      break;
    ++steps;
#ifdef VERBOSE_STATISTICS_ON
    VerboseStatistics.TotalSteps++;
#endif
    auto si = Seeds.begin();

    si->grow(*this);
    {
      const Seed& fs = Seeds.front();
      // bigger substructure found
      if (fs.CopyComplete) {
        bool possibleMCS = false;
        if ((!Parameters.MaximizeBonds &&
             (fs.getNumAtoms() > getMaxNumberAtoms() ||
              (fs.getNumAtoms() == getMaxNumberAtoms() &&
               fs.getNumBonds() > getMaxNumberBonds())))) {
          possibleMCS = true;
        } else if (Parameters.MaximizeBonds &&
                   (fs.getNumBonds() > getMaxNumberBonds() ||
                    (fs.getNumBonds() == getMaxNumberBonds() &&
                     fs.getNumAtoms() > getMaxNumberAtoms()))) {
          possibleMCS = true;
        }
        // #945: test here to see if the MCS actually has all rings closed
        if (possibleMCS && Parameters.BondCompareParameters.CompleteRingsOnly) {
          possibleMCS = checkIfRingsAreClosed(fs);
        }
        if (possibleMCS) {
          mcsFound = true;
#ifdef VERBOSE_STATISTICS_ON
          VerboseStatistics.MCSFoundStep = VerboseStatistics.TotalSteps;
          VerboseStatistics.MCSFoundTime = nanoClock();
#endif
          McsIdx.Atoms = fs.MoleculeFragment.Atoms;
          McsIdx.Bonds = fs.MoleculeFragment.Bonds;
          McsIdx.AtomsIdx = fs.MoleculeFragment.AtomsIdx;
          McsIdx.BondsIdx = fs.MoleculeFragment.BondsIdx;
          if (Parameters.Verbose) {
            std::cout << VerboseStatistics.TotalSteps
                      << " Seeds:" << Seeds.size() << " MCS "
                      << McsIdx.Atoms.size() << " atoms, "
                      << McsIdx.Bonds.size() << " bonds";
            printf(" for %.4lf seconds. bond[0]=%u\n",
                   double(VerboseStatistics.MCSFoundTime - To) / 1000000.,
                   McsIdx.BondsIdx[0]);
          }
        }
      }
    }
    if (NotSet == si->GrowingStage)  // finished
      Seeds.erase(si);
    if (Parameters.ProgressCallback && (steps >= 377)) {
      steps = 0;
      Stat.NumAtoms = getMaxNumberAtoms();
      Stat.NumBonds = getMaxNumberBonds();
      if (!Parameters.ProgressCallback(Stat, Parameters,
                                       Parameters.ProgressCallbackUserData)) {
        canceled = true;
        break;
      }
    }
  }
```

It looks like either:

* It has got stuch in the seed growing stage:
* The timeout is never triggered because it hasn't reached the hard-coded lower limit of 377 steps.

Comparing with our internal MCS code, 92 atoms seems like a perfectly fine mapping for this ligand pair so it would be desirable to be able to trigger the timeout at an earlier stage.

**Comment by lohedges** [comment]
Having built RDKit myself the issue is indeed the uncommented 377 lower bound on the number of steps. Is there any reason for this number?  (Without any context it seems completely arbitrary.) If not, then I'll remove it and issue a pull request.

**Comment by greglandrum** [comment]
Thanks for identifying that and proposing a fix.
The origin of the `steps >= 377` test can be safely considered as 'lost in antiquity'. I don't see any reason for it to be there and would be happy to merge a PR that removes it (assuming that it doesn't break any of the existing tests in an unexpected way)!

**Comment by lohedges** [comment]
Thanks, @greglandrum. I assumed it was a long forgotten fix or debugging addition. (I was scratching my head trying to figure out why 377 was a magic number.)

Once the pull request is merged, do you have a rough idea for how long it'll be before it appears in an updated Conda package? For now I can generate manual mappings for the problem ligands using my own local RDKit fork, then share them with our users.

**Comment by greglandrum** [comment]
Given that this is a bug, it will show up in the next patch release after the PR is merged. I'm planning on doing the 2019.03.4 release next week.
