### ISSUE TITLE
Catch v2.1.2 master.tar.gz empty?

### ISSUE THREAD

**Issue by complext** [rdkit/rdkit#2586]
**Catch v2.1.2 gzipped manifest appears empty**

- RDKit Version: Building 2019_03_3, Python 2.7
- Platform: Debian 10.0.0 (VM)

```
debian@debian:/usr/local/src/rdkit-Release_2019_03_3/build$ sudo cmake -S $RDBASE -DRDK_BUILD_INCHI_SUPPORT=ON -DRDK_BUILD_CAIRO_SUPPORT=ON
-- Catch not found in /usr/local/src/rdkit-Release_2019_03_3/External/catch/catch
Downloading https://github.com/catchorg/Catch2/archive/v2.1.2.tar.gz...
CMake Error at Code/cmake/Modules/RDKitUtils.cmake:218 (MESSAGE):
  The md5 checksum for
  /usr/local/src/rdkit-Release_2019_03_3/External/catch/master.tar.gz is
  incorrect; expected: 4c5740d7446d9b4e3735dcff0951aaca, found:
  d41d8cd98f00b204e9800998ecf8427e
Call Stack (most recent call first):
  External/catch/CMakeLists.txt:16 (downloadAndCheckMD5)


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/rdkit-Release_2019_03_3/build/CMakeFiles/CMakeOutput.log".

```
What's going on?? MD5 hash for the downloaded catch2 master.tar.gz is empty (hash corresponds to empty file, confirmed file is 0 bytes).

I've tried now unsuccessfully to build in Windows 10, Ubuntu over Windows 10, and now Debian 10.0.0 in VirtualBox. I have followed all instructions prescribed in the Install.md, and have installed all necessary prerequisites. Someone please help, because I am beyond frustrated at just trying to build this darn thing.

**Comment by greglandrum** [comment]
This is an unusual problem: the download of the catch libraries from github that cmake does there is normally quite reliable. I don't think I've ever seen it fail.

Is it possible that you were not online when you ran cmake those times? I'm not sure what exactly the errors there would be, but I could imagine that the result would be an empty file.

**Comment by complext** [comment]
> This is an unusual problem: the download of the catch libraries from github that cmake does there is normally quite reliable. I don't think I've ever seen it fail.
> 
> Is it possible that you were not online when you ran cmake those times? I'm not sure what exactly the errors there would be, but I could imagine that the result would be an empty file.

I will check again today, making sure all modules in my Debian have loaded, I know I was having trouble with my VM just to get the XServer to correctly boot up to my desktop. But for the record, I did have complete internet access through NAT connection via my host PC--in fact, I was streaming music on the guest system as I tried this. If it doesn't work after correctly trying this all again, I'll be pretty dumbfounded, but whatever.

**Comment by complext** [comment]
Confirmed: this is still happening even after my Debian has verified internet access. Any ideas as to what I can do while I give up on building RDKit from source? I've tried almost every option available to me at this point and wasted hours on this.

**Comment by complext** [comment]
So it turns out the issue continues thereafter with other packages, I don't know what's happening, if my rdkit Release .zip was good to begin with or not at this point.
````
sudo cmake -S $RDBASE
-- Found Catch2 source in /usr/local/src/rdkit-Release_2019_03_3/External/catch/catch
CATCH: /usr/local/src/rdkit-Release_2019_03_3/External/catch/catch/single_include
-- Could NOT find InChI in system locations (missing: INCHI_LIBRARY INCHI_INCLUDE_DIR) 
Downloading http://www.inchi-trust.org/download/105/INCHI-1-SRC.zip...
CMake Error at Code/cmake/Modules/RDKitUtils.cmake:218 (MESSAGE):
  The md5 checksum for
  /usr/local/src/rdkit-Release_2019_03_3/External/INCHI-API/INCHI-1-SRC.zip
  is incorrect; expected: ccc497c7e6ced1521a6953d859e49af4, found:
  d41d8cd98f00b204e9800998ecf8427e
Call Stack (most recent call first):
  Code/cmake/Modules/FindInchi.cmake:50 (downloadAndCheckMD5)
  CMakeLists.txt:216 (find_package)


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/rdkit-Release_2019_03_3/build/CMakeFiles/CMakeOutput.log".
````

Maybe I'm just uniquely bad at this stuff. I give up.

**Comment by greglandrum** [comment]
This is very, very unlikely to be a problem with the rdkit package. It looks like something is misconfigured on your machine.

**Comment by complext** [comment]
:(

**Comment by alanbchristie** [comment]
@greglandrum Was there a resolution to your problem? I'm encountering the same problem when trying to build RDKit in an ubuntu Docker container and suspect `cmake` relies on something that's not in the image. I've built `cmake` from source (3.15.5).
