### ISSUE TITLE
Can't kekulize 2-Propylpiperazine

### ISSUE THREAD

**Issue by complext** [rdkit/rdkit#2588]
**Rather simple heterocycle can't be kekulized.**

- RDKit Version: 2019_03_3
- Platform: Ubuntu 18.02 over Win10, Python2.7

```
CCCC1CNCCN1
[12:13:11] Can't kekulize mol

[12:13:11] ERROR: Could not sanitize molecule on line 442
[12:13:11] ERROR: Can't kekulize mol

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: 'NoneType' object has no attribute 'GetRingInfo'
```

For reference, I was reading from a SmilesMol suppl that encountered line 442 as the correct SMILES representation for 2-propylpiperazine: CCCC1CNCCN1. I confirmed this in my read-in file.

I was instantiating a RingInfo object for each SMILES I read-in. Any idea why this is going on?

**Comment by complext** [comment]
A nearly 2-decade old fork of FROWNS apparently resolves the structure--it looks like I'll be taking my business elsewhere on this one.

**Comment by bp-kelley** [comment]
Having written it, you really, really don't want to use FROWNS.  The
publically released aromaticity model is braindead, but it does do some
transformations that rdkit doesn't.

But the oddity here is that 2-Propylpiperazine isn't aromatic, and I can
parse it just fine in the RDKit.

```
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles("CCCC1CNCCN1")
>>> Chem.MolToSmiles(m)
'CCCC1CNCCN1'
```

You may be seeing an off by one error in that line (1 offset) 442 might be
at index 441 (0 offset)

Cheers,
 Brian

**Comment by greglandrum** [comment]
Can you share a code snippet+input that shows the problem?
That input SMILES shouldn't produce a kekulization failure (since there's no aromaticity present, it isn't really kekulized at all).

**Comment by complext** [comment]
Thanks, Brian. I hadn't thought about this.

I went back to my batch input and did in fact realize that while the string literals are okay as the Mol from SMILES parser is reading them, it is encountering more general difficulties in failing to generate the mol for any structure, including non-aromatic, or even acyclic compounds for that matter.

I may be butchering everything at this point as a general newcomer, so in light of this, I am supplying a subset of the molecules that are the source of this problem. Please see if you can, using my method in Python 2.7.15, attempt to do the following:

-Read in carriage-stripped lines
-Instantiate RingInfo
-Using the method of your choice, print-out or to separate file the molecules from the input that are cyclic (containing at least 1 heterocyclic ring of 3 members or more)

If there's a problem with kekulization, it probably has to do with the input file at this point--I just have scanned the entire characters of it and can't find anything funky or out of place around the (multiple) SMILES-containing lines that fire back issues. 

[github_test.txt](https://github.com/rdkit/rdkit/files/3475556/github_test.txt)

**Comment by greglandrum** [comment]
Here's a simple demo of two ways to do what you want, along with a look at the two molecules that fail kekulization: https://gist.github.com/greglandrum/a6d0af50f622147f37157ea08ba2b4f0

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
