### ISSUE TITLE
some b3lyp smiles can not convert to ecfp(morgan fingerprint)

### ISSUE THREAD

**Issue by ms860309** [rdkit/rdkit#2590]
in GDB-17 smiles is CN=C1C=CNN=N1
in B3LYP smiles is C[N]c1cc[nH]nn1
here is a simple script
mol = Chem.MolFromSmiles('C[N]c1cc[nH]nn1')
fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=512)

it can convert GDB-17 's smiles but B3LYP can't.
I know it  may have some high valence or hetercycle proble about Nitrogen, but how to figure out it.
use Sanitize = false ?  it will print RingInfo not initialized

**Comment by greglandrum** [comment]
That "B3LYP smiles" doesn't correspond to a stable molecule and, as such, the RDKit isn't going to deal with it happily by default. There are ways around that, but it would be good to be sure that what you're doing makes sense.

Where did that "B3LYP smiles" come from and what do you want to do with the molecules?

**Comment by ms860309** [comment]
B3LYP smiles come from this paper called : Quantum chemistry structures and
properties of 134 kilo molecules
Not all data have problem, about 750 molecules have problems.
I want to convert smiles to ecfp fingerprint whether it have problem or not, can rdkit ignore wrong molecules or not to check?

**Comment by greglandrum** [comment]
It's easy to ignore molecules that are chemically wrong. Here's some pseudocode:
```
for smiles in list_of_smiles:
  m = Chem.MolFromSmiles(smiles)
  if m is None:
    continue
  do_whatever_else_you_want_to_do()
```

**Comment by ms860309** [comment]
Thank you, that's helpful!!
Is these smiles can still convert to ecfp? or maintain smiles.

**Comment by greglandrum** [comment]
What do you want to do with the fingerprints of molecules that are not chemically reasonable?

**Comment by ms860309** [comment]
I know it is not reasonable, but I just want to try how big the impact of these error data on machine learning.
If it can not be converted maybe I should remove these bad data.

**Comment by greglandrum** [comment]
you can try:
```
if m is None:
  m = Chem.MolFromSmiles(smiles,sanitize=False)
  m.UpdatePropertyCache(strict=False)
  Chem.FastFindRings(m)
```
After that the molecule should be ready to be fingerprinted

**Comment by greglandrum** [comment]
But, again, in my experience there are rarely situations where it makes sense to be doing that.

**Comment by ms860309** [comment]
thank you very much, I try and it work perfectly!!!!
yesterday i just stun and ringinfo not initial.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
