### ISSUE TITLE
ResonanceMolSupplier potentially stuck in infinite loop

### ISSUE THREAD

**Issue by tawe141** [rdkit/rdkit#2597]
**Description:**

- RDKit Version: 2019.03.2
- Platform: Ubuntu 18.04

ResonanceMolSupplier takes an extremely long time (or possibly is stuck in an infinite loop) when trying to process the Mol object with SMILES string 
`ClC1=NC(NC2=CC=CC3=C2C(=O)C2=CC=CC=C2C3=O)=NC(NC2=CC=CC3=C2C(=O)C2=CC=CC=C2C3=O)=N1`

```
from rdkit.Chem import MolFromSmiles
from rdkit.Chem.rdchem import ResonanceMolSupplier

m = MolFromSmiles(insert_smiles_string_here)
sup = ResonanceMolSupplier(m)
next(sup)
```

**Comment by bp-kelley** [comment]
I'm going to label this as a bug, there should be some max number of resonance structures to prevent this behavior.  This might take some time to resolve, however.

**Comment by bp-kelley** [comment]
Here is a more detailed reason why I consider this a bug:

```
>>> insert_smiles_string_here="ClC1=NC(NC2=CC=CC3=C2C(=O)C2=CC=CC=C2C3=O)=NC(NC2=CC=CC3=C2C(=O)C2=CC=CC=C2C3=O)=N1"
>>> m = MolFromSmiles(insert_smiles_string_here)
>>> sup = ResonanceMolSupplier(m)
>>> for i,m in enumerate(sup):
...   print(Chem.MolToSmiles(m))
```

This code hangs in that the user can't terminate after, say, 1000 structures are generated.

**Comment by thegodone** [comment]
it's true that a limit can be useful to avoid infinite loops

**Comment by greglandrum** [comment]
@ptosco : I just noticed that this is still here and seems to still be a problem.
I just tried @tawe141's sample molecule like this and got a hang:
```
In [2]: m = Chem.MolFromSmiles('ClC1=NC(NC2=CC=CC3=C2C(=O)C2=CC=CC=C2C3=O)=NC(NC2=CC=CC3=C2C(=O)C2=CC=CC=C2C3=O)=N1')    

In [3]: suppl = Chem.ResonanceMolSupplier(m,maxStructs=10)                                                               

In [4]: next(suppl)                                                                                                      
```
Trying with the SMILES `O=C(Nc1ccc(Nc2ccc(NC(=O)c3ccccc3)c4C(=O)c5ccccc5C(=O)c24)c6C(=O)c7ccccc7C(=O)c16)c8ccccc8` leads to similar behavior (though there the memory used grows for quite a while).

Is this something you'd be able to look at?

**Comment by ptosco** [comment]
@greglandrum Yes, I'll try and take a look over the weekend.

**Comment by thegodone** [comment]
maybe also a memory leak somewhere ?
