### ISSUE TITLE
Possible Garbage Collection Bug in Pharmacophore Generation

### ISSUE THREAD

**Issue by cing** [rdkit/rdkit#2603]
I've encountered a bug involving the Python API when a `FeatureFactory` is defined inside a method and the output features are returned and accessed by the caller. Specifically, this results in `MemoryError` when you try to access the family name with `GetFamily()`, but for some reason `GetType()`/`GetFactory()` doesn't result in an error. I haven't tried the latest source, so this may be now fixed. Thanks!

- RDKit Version: 2018.03.02
- Platform: Fedora 29 (Installed from package manager)

```
from rdkit import Chem
from rdkit.Chem import ChemicalFeatures

def extract_features_from_mol(m, factory):
    return factory.GetFeaturesForMol(m)

def extract_features_from_mol_memory_error(m):
    factory = ChemicalFeatures.BuildFeatureFactory("BaseFeatures.fdef")
    return factory.GetFeaturesForMol(m)

m = Chem.MolFromSmiles('OCc1ccccc1CN')

# No error
factory = ChemicalFeatures.BuildFeatureFactory("BaseFeatures.fdef")
feats = extract_features_from_mol(m, factory)
print(feats[0].GetFamily())

# Memory error
feats = extract_features_from_mol_memory_error(m)
print(feats[0].GetFamily())
```

**Comment by greglandrum** [comment]
Confirmed that there's a problem here with v2019.03.4 as well.
What's going on is that the lifetime of the factory isn't being tied to the lifetime of the features themselves.
This should be fixable.
