### ISSUE TITLE
Speed Comparison of Standardizers

### ISSUE THREAD

**Issue by ZacharyKaplan** [rdkit/rdkit#2615]
**Description:**

- RDKit Version: 2019.03.3
- Platform: OSX, Linux

Examining the runtime of the standardization function rdkit.Chem.MolStandardize.rdMolStandardize.Cleanup() and comparing it to the runtime of the original standardizer at rdkit.Chem.MolStandardize.Standardizer.standardize(), we found that the cleanup function is 2-3 times slower than the function it replaces. Below is a plot showing the comparative runtimes, along with the runtimes of a modification to the original standardizer to retain mol properties (Custom Standardizer) and an implementation of the original standardizer's functionality in terms of functions from rdkit.Chem.MolStandardize.rdMolStandardize. Is this behavior expected? 

![Stand_speed](https://user-images.githubusercontent.com/53836758/63177627-55095800-c016-11e9-9488-68284da1f07c.png)

Thank you,
Zach Kaplan

Prompted by:
https://github.com/rdkit/rdkit/pull/2431#issuecomment-493090584

python script to reproduce plot and associated data:
[speed_test.zip](https://github.com/rdkit/rdkit/files/3510145/speed_test.zip)

 

```
Your code sample here
```

**Comment by greglandrum** [comment]
Nope. That's not expected at all and I will look into it.

**Comment by ZacharyKaplan** [comment]
Thanks for looking it over!

**Comment by bp-kelley** [comment]
I'm going to close this issue due to the merge.
