### ISSUE TITLE
Speeding up EmbedMultipleConfs function

### ISSUE THREAD

**Issue by ValeryPolyakov** [rdkit/rdkit#2618]
Is there a way to speed up EmbedMultipleConfs function without sacrificing the quality of  generated conformers? I am talking beyond increasing CPU count. Maybe doing it on GPUs?

**Comment by greglandrum** [comment]
In theory parts of the algorithm could be run on GPUs, but it needs someone who has the knowledge and time to do the work.
There's also certainly some optimization work that could be done by refactoring the code and tuning the parameters/constants that are used. That too is a matter of someone having the motivation and time

**Comment by ValeryPolyakov** [comment]
Thanks Greg, how much faster would it run on a GPU? Valery

**Comment by greglandrum** [comment]
That's not a question that can really be answered in advance.
