### ISSUE TITLE
why the fragment descriptor is stored in a csv file?

### ISSUE THREAD

**Issue by kexul** [rdkit/rdkit#2622]
It's not consistent with other descriptors.

**Comment by greglandrum** [comment]
Which files are you talking about?

**Comment by kexul** [comment]
https://github.com/rdkit/rdkit/blob/79735d91d218ab34b419f67e6ab00c10e6326aac/rdkit/Chem/Fragments.py#L20
the descriptor was saved  a FragmentDescriptors.csv .

**Comment by bp-kelley** [comment]
Apparently the answer is that it is not a csv file.  It is actually similar to the other files except for the extension.  It should be named ".txt" but that is a pretty low priority :)
