### ISSUE TITLE
Can't kekulize molecule after removal of functional group

### ISSUE THREAD

**Issue by nhstanley** [rdkit/rdkit#2629]
**Description:**

- RDKit Version: 2019.03.4 (Anaconda Python 3.7)
- Platform: CentOS 7 and Mac OS X 10.14.6

I'm opening this as an issue as I think this may fall into the gray area between a possible bug and just me not knowing how to get the software to do what I want. I see there are other "Can't Kekulize" issues open, but I think this may be unique (none of the other seem to describe this issue specifically).

I have been trying to automate the removal of certain functional groups from a set of molecules, and I happened upon one molecule for which it is just not working. As a test case to illustrate the issue, I have chosen the molecule N-methyl-2-pyridone.

```
from rdkit.Chem import AllChem as Chem
from rdkit.Chem import Draw

# N-methyl-2-pyridone
m = Chem.MolFromSmiles('CN1C=CC=CC1=O')
m = Chem.AddHs(m)

Draw.MolToImage(m, includeAtomNumbers=True)
```
So far, so good. Now, I would like to be able to remove the methyl on the nitrogen. 

```
patt = '[H]C([H])[H]' # methyl group
patt = Chem.MolFromSmarts(patt)
rm = Chem.DeleteSubstructs(m,patt)

Draw.MolToImage(rm)
```
At this point, I get an error. 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-e0becfd000ad> in <module>
     14 rm = Chem.DeleteSubstructs(m,patt)
     15 
---> 16 Draw.MolToImage(rm)

~/anaconda/envs/chem/lib/python3.7/site-packages/rdkit/Chem/Draw/__init__.py in MolToImage(mol, size, kekulize, wedgeBonds, fitImage, options, canvas, **kwargs)
    116     from rdkit import Chem
    117     mol = Chem.Mol(mol.ToBinary())
--> 118     Chem.Kekulize(mol)
    119 
    120   if not mol.GetNumConformers():

ValueError: Sanitization error: Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4
```
This is easy enough to fix for this individual test case by doing...
```
rm.GetAtomWithIdx(0).SetNumExplicitHs(1)
Draw.MolToImage(rm)
```
... but ideally, I would be able to automate this. I thought I could take a slightly different tack, and just replace the methyl with a hydrogen.

```
patt = '[H]C([H])[H]'
patt2 = '[H]'

patt = Chem.MolFromSmarts(patt)
patt2 = Chem.MolFromSmarts(patt2)

rms = Chem.ReplaceSubstructs(m, patt, patt2)

Draw.MolToImage(rms[0])
```
That doesn't work, and gives the same error as before. 

I decided to go back to trying to detect when an atom needs a hydrogen. I was thinking to utilized the valence, number of hydrogens, looking for radicals, etc., before I finally trying to do something with the bond orders:
```
>>> [x.GetBondTypeAsDouble() for x in rm.GetAtomWithIdx(5).GetBonds()]
[1.5, 1.5]
```
But I realized the only way that would work is if the bond order matched the visual/kekule bond order of the starting molecule, which it does not with the aromatic bond orders of 1.5.  (As an aside: Is there a way I can set the bond order to that of the "as drawn" starting molecule, i.e. with integer bond order?)

So, my question is, is this a bug/deficiency, or can you think of "correct" way to handle this problem?

**Comment by nhstanley** [comment]
Another option would be to identify what the removed group is bound to before the removal and add the hydrogen to that atom after the removal. I haven't tried to implement that, but one issue I can see immediately is that the atom numbering can (and does in my above example) change between the starting structure and the structure with the removed group. It would not necessarily change in an easily predictable way.

**Comment by bp-kelley** [comment]
I think what you want is best described in a reaction.  What you are trying to do is to replace methyl with a hydrogen, so let's do that explicitly.

```
>>> rxn = AllChem.ReactionFromSmarts("[CH3:1]>>[H:1]")
>>> products = rxn.RunReactants([Chem.MolFromSmiles("CN1C=CC=CC1=O")])[0]
>>> for mol in products:
...    mol = Chem.RemoveHs(mol)
...    Chem.SanitizeMol(mol)
...    print(Chem.MolToSmiles(mol))
... 
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
O=c1cccc[nH]1
```

Alternative, you might have tried ReplaceSubstructs

```
>>> rm = Chem.ReplaceSubstructs(m, Chem.MolFromSmarts("[CH3]"), Chem.MolFromSmiles("[H]"))
>>> Chem.MolToSmiles(rm[0])
'[H]n1ccccc1=O'
>>> Chem.MolToSmiles(rm[0])
'[H]n1ccccc1=O'
>>> m = Chem.RemoveHs(rm[0])
>>> Chem.MolToSmiles(m)
'O=c1cccc[nH]1'
```

**Comment by bp-kelley** [comment]
@nhstanley do any of these suggestions help your issue?

**Comment by nhstanley** [comment]
Hey Brian, yes. The reaction method works. I am less familiar with that part of the code, and I had not thought of that.

As you can see from my first post, the ReplaceSubstructs didn't work for me. Not clear why but probably not important.

**Comment by nhstanley** [comment]
Thanks for your assistance, by the way!
