### ISSUE TITLE
problem in activation of both tensorflow and rdkit in anaconda win

### ISSUE THREAD

**Issue by fi000** [rdkit/rdkit#2634]
I have a problem in activation of both tensorflow and rdkit(2019.03.4) in anaconda  windows (10) 
The activation of one of them leads to deactivation of another!

**Comment by bp-kelley** [comment]
I expect that there is a conflict with lib boost.  We may need some more information.  Could you send/post the environment file?

```
conda env export > environment.yml
```

**Comment by bp-kelley** [comment]
@fi000 any update on this?
