### ISSUE TITLE
How to  canonicalize a mol object with RDKit 

### ISSUE THREAD

**Issue by chf42** [rdkit/rdkit#2637]
**Description:**

- RDKit Version: 2018.09.3
- Platform: Python 2.7.16 on Linux

Hi all,

I wonder if the RDKit provide a way to canonicalize a mol object without converting to SMILES, and back to mol. e.g. Chem.MolFromSmiles(Chem.MolToSmiles('mol')))

What I expected is mol_canonicalized = canonical_func (mol), where canonical_func is a rdkit bulit-in function.

I checked the module "rdkit.Chem.MolStandardize.rdMolStandardize", but couldn't figure it out. Would you mind help us check with that?

Thanks,
Cheng

```
Your code sample here
```

**Comment by bp-kelley** [comment]
I'm assuming that by "Canonicalize" you want a molecules atoms in a canonical order.  If this is the case, see this thread:

https://sourceforge.net/p/rdkit/mailman/message/34923617/

**Comment by chf42** [comment]
Hi Brian,

Thank you for your kind response. But the webpage was corrupted from my end. I can't access to that. Would you mind provide another link?

Thanks
Cheng

**Comment by bp-kelley** [comment]
Sure, here is a copy of the webpage:

```
Yes, I actually exposed that function to Python  in Rdkit :)

Be aware that the canonical rank and the output order aren't the same thing.  The rank is what is used during graph traversal, when making the smiles string, to choose what atom to go to next.  The output order is what atoms where output first, second, third in the output smiles string.  They are not necessarily the same.  

Both should, however, be unique for the input graph, but in either case explicit hydrogens should be added.

For reference:

order = Chem.CanonicalRankAtoms(m, includeChirality=True)

Is the function being discussed.

And as a bonus:

mol_ordered = Chem.RenumberAtoms(m, list(order))

Will make a copy in canonical atom order, but not canonical smiles output order.
```

**Comment by chf42** [comment]
Hi Brian,

Thank you for your kind information. I tried the codes as follows:

order = Chem.CanonicalRankAtoms(m, includeChirality=True)
mol_ordered = Chem.RenumberAtoms(m, list(order))

However, it doesn't do the same as the following codes did, which was what I expected. 

smil = Chem.MolToSmiles(mol)
mol_new = Chem.MolFromSmiles(smi)

I would like to know whether there is a way (direct operation on a mol object) to convert a molecule to a new one with canonicalized smiles (i.e. in order to be unique). Also, if it allows the direct operation on a mol object, this can potentially keep all the properties associated with the mol object. 

Thank you!
Cheng

**Comment by bp-kelley** [comment]
Chem.RenumberAtoms will keep the properties.

The atoms in CanonicalRankAtoms will end up in canonical order, but won't end up in the smiles order.  This is a combination of the canonical order and the graph traversal algorithm.  You can use a "hack" to resolve this order.


```
m = Chem.MolFromSmiles("c1ccccc1CN=O")
for a in m.GetAtoms():
    a.SetProp("foo", str(a.GetIdx()))
smi = Chem.MolToSmiles(m)
# get the atoms in the smiles string order
order = m.GetPropsAsDict(True,True)["_smilesAtomOutputOrder"]
print("canonical order:", list(order))
m_canonical = Chem.RenumberAtoms(m, order)
for a in m_canonical.GetAtoms():
    print("idx:", a.GetIdx(), "orig: idx", a.GetProp("foo"))
```

output:

```
canonical order: [8, 7, 6, 5, 0, 1, 2, 3, 4]
idx: 0 orig: idx 8
idx: 1 orig: idx 7
idx: 2 orig: idx 6
idx: 3 orig: idx 5
idx: 4 orig: idx 0
idx: 5 orig: idx 1
idx: 6 orig: idx 2
idx: 7 orig: idx 3
idx: 8 orig: idx 4
```

Hope this helps.

**Comment by bp-kelley** [comment]
To answer another question, RDKit has no current method to reorder atoms and bonds without creating a new molecule.

Let me know if this helps solve your issue.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
