### ISSUE TITLE
MACCS Keys

### ISSUE THREAD

**Issue by mti193** [rdkit/rdkit#2640]
Hi. I wanted to use RDKit for my Data (Compounds from KEGG) but wanted to first see if everything was "working correctly" so I aimed to use MACCS Keys using 4 few simple mock molecule since MACCS keys are a simple Atom - Atom comparison and then a Simple Tanimoto coefficient is used (DataStructs.FingerprintSimilarity in RDKit): (shared atoms)/ (Shared in mol a) + (shared in mol b) - (shared atoms)

However there seems to be a problem when comparing 2 molecules, with varying amounts of Carbon as seen below. 

One would expect a comparison between (CCCCCN", "CCCCCCN") to be the most similar between each other as compared to ("CCN", "CCCN")  due to more Carbon atoms being in common between each so a difference of remove one would change the similarity very little, which is the case. 

**However,** when removing one carbon at a time from each molecule, there is a reversal in the trend. Comparing the similarity between ("CCCCN", "CCCCCN") = 0.85 and ("CCCN", "CCCCN") = 0.8823529411764706, when in fact the similarity between the latter should be lower than the former.

Please let me know if I am missing something, Thanks.

My simple code is:
import rdkit
from rdkit import Chem
from rdkit.Chem import MACCSkeys
from rdkit import DataStructs
from rdkit.Chem.Fingerprints import FingerprintMols

def calculation(a,b):
    ms = [Chem.MolFromSmiles(a), Chem.MolFromSmiles(b)]
    fps = [MACCSkeys.GenMACCSKeys(x) for x in ms]
    return DataStructs.FingerprintSimilarity(fps[0],fps[1])

print(calculation("CCCCCN", "CCCCCCN"))
print(calculation("CCCCN", "CCCCCN"))
print(calculation("CCCN", "CCCCN"))
print(calculation("CCN", "CCCN"))

----------------------------------------------------------------------------------------------
The results are: 
0.9523809523809523
0.85
0.8823529411764706
0.6666666666666666

**Comment by bp-kelley** [comment]
This isn’t quite the way MACCS kegs work.  They are a collection of 166 predetermined features selected because they have been seen to vary biological results ( these were selected a while ago I might add ).

I expect you will find results you expect using the Morgan or RDKit fingerprints.  These are designed to not require a predefined set of interesting features.

https://www.rdkit.org/docs/GettingStartedInPython.html#morgan-fingerprints-circular-fingerprints

**Comment by bp-kelley** [comment]
Here is a small change to use the default fingerprinted:

```
from rdkit import Chem
from rdkit.Chem import MACCSkeys
from rdkit import DataStructs
from rdkit.Chem.Fingerprints import FingerprintMols
print(help(FingerprintMols.FingerprintMol))
def calculation(a,b):
    ms = [Chem.MolFromSmiles(a), Chem.MolFromSmiles(b)]
    fps = [FingerprintMols.FingerprintMol(x) for x in ms]
    return DataStructs.FingerprintSimilarity(fps[0],fps[1])

print(calculation("CCCCCN", "CCCCCCN"))
print(calculation("CCCCN", "CCCCCN"))
print(calculation("CCCN", "CCCCN"))
print(calculation("CCN", "CCCN"))
```

And the results which are probably more to your liking:

```
0.85
0.8235294117647058
0.7142857142857143
0.6
```

**Comment by adalke** [comment]
Minor point: the MACCS keys were defined (in the 1970s) as substructure screens. They only indirectly correspond to specific biological results because they are trying to partition the query space, and people generally make queries correlated with biology/chemistry.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
