### ISSUE TITLE
EmbedMolecule() and EmbedMultipleConfs() very slow for monoatomic species

### ISSUE THREAD

**Issue by BvB93** [rdkit/rdkit#2642]
**Description:**

Conformer generation for monoatomic species seems to be incredible slow, the process taking multiple orders of magnitude longer than for molecules.
For example, generating a conformer for monoatomic oxygen takes 7-8 seconds while the same operation takes about half a millisecond for dioxygen (see **Example**).
The issue affects both the ``rdkit.Chem.rdDistGeom.EmbedMolecule()`` and ``rdkit.Chem.rdDistGeom.EmbedMultipleConfs()`` functions.

- RDKit Version: 2019.03.1
- Platform: macOS 10.14.5

**Example:**
```
>>> from rdkit.Chem import AllChem

>>> mol1 = AllChem.MolFromSmiles('O')
>>> mol2 = AllChem.MolFromSmiles('O=O')

>>> %timeit AllChem.EmbedMolecule(mol1)
7.74 s ± 518 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

>>> %timeit AllChem.EmbedMolecule(mol2)
613 µs ± 56.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by denfromufa** [comment]
Any update on this issue?
