### ISSUE TITLE
Chem.MolToSmiles throw runtime error

### ISSUE THREAD

**Issue by Minys233** [rdkit/rdkit#2644]
**Description:**

- RDKit Version: 2019.03.4
- Platform: Ubuntu 18.04

When process `.sdf.gz` file download from PubChem with `Chem.MolToSmiles`, RDKit raise `RuntimeError: Pre-condition Violation` (details in code section). 

Data download from: ftp://ftp.ncbi.nlm.nih.gov/pubchem/Compound/CURRENT-Full/SDF/Compound_054300001_054325000.sdf.gz
(github does not support ftp link 👎)

The error is from the molecule in which PUBCHEM_COMPOUND_CID = 54308763, at line 1429268 in the above sdf file after unzip. 

Details are as follows.

```python
In [1]: from rdkit import Chem
   ...: from rdkit.Chem import AllChem
   ...: import gzip

In [2]: ms = [x for x in Chem.ForwardSDMolSupplier(gzip.open('Compound_054300001_054325000.sdf.gz')) if x is not None]

In [3]: error = ms[6481]

In [4]: Chem.MolToSmiles(error)
[21:57:28]

****
Pre-condition Violation
bad bond type
Violation occurred on line 62 in file /opt/conda/conda-bld/rdkit_1565675972125/work/Code/GraphMol/Canon.cpp
Failed Expression: bond->getBondType() == Bond::SINGLE || bond->getIsAromatic()
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-e62f4278bb1a> in <module>
----> 1 Chem.MolToSmiles(error)

RuntimeError: Pre-condition Violation
        bad bond type
        Violation occurred on line 62 in file Code/GraphMol/Canon.cpp
        Failed Expression: bond->getBondType() == Bond::SINGLE || bond->getIsAromatic()
        RDKIT: 2019.03.4
        BOOST: 1_67

```
However, I can get the canonical SMILES with `error.GetProp('PUBCHEM_OPENEYE_CAN_SMILES')`.
I'm new to SDF format files, and currently haven't figure out what was wrong and if any other molecules suffer from the same problem.

**Comment by sirbiscuit** [comment]
Hey @Minys233,

thanks for your detailed error report! The problem does not occur on the current dev version of rdkit (2019.09.1dev1). I ran your code and got as output:
'N#CC(c1ccccc1)=P(=C(C#N)c1ccccc1)C(C#N)c1ccccc1'

Your SDF file is correct since you can load all molecules without running into problems. The error occurs because of a bug in the MolToSmiles function. The new implementation of Chem.MolToSmiles (2019.09.1dev1) works on all molecules in your data set:
```python
supplier = Chem.ForwardSDMolSupplier(gzip.open('Compound_054300001_054325000.sdf.gz'))
smiles = [Chem.MolToSmiles(x) for x in supplier if x is not None]
# no error
```

**Comment by Minys233** [comment]
Thank you so much for testing. I'm glad to hear this problem have been solved, looking forward for the new release at conda channel (now still 2019.03.4) XD
