### ISSUE TITLE
Add support for .{get,set}Query() on both Atoms and Bonds to SWIG wrappers.

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#265]
This will require exposing at least part of the Query infrastructure.

**Comment by d-b-w** [comment]
There has been no discussion or further requests for this enhancement in the past 5 years. Closing as "won't fix"

**Comment by DavidACosgrove** [comment]
@d-b-w actually I was meaning to bring that up this meeting. I had a use case a few weeks ago where I wanted to be able to change the way a query bond was drawn and the obvious thing to do was to change the bond query properties. There didn’t seem to be a way in Python to do this in the same way you can amend atom queries.
