### ISSUE TITLE
Create a tool to turn E/Z stereochemistry into Cis/Trans

### ISSUE THREAD

**Issue by d-b-w** [rdkit/rdkit#2659]
**Description:**
I think it would be useful to have a tool or function to turn E/Z stereochemistry into Cis/Trans stereochemistry.

E/Z bond stereochemistry is not deprecated, but it is not the way of the future. It would be able to tell RDKit to update a molecule to use Cis/Trans labels instead of E/Z. Maybe this would ultimately become an option to the sanitization code.

**Comment by rachelnwalker** [comment]
Closing this by @d-b-w's suggestion since we are planning to make the new stereo the default.
