### ISSUE TITLE
Include enhanced stereo labels in RDKit depictions

### ISSUE THREAD

**Issue by d-b-w** [rdkit/rdkit#2660]
**Description:**
It would be useful to include the information from the enhanced stereochemistry labels (stereo groups) in the depictions of molecules generated by RDKit.

I'd imagine that these would be small labels near the atom in question, e.g.:

![reactant_to_destroy](https://user-images.githubusercontent.com/3013277/65729487-c1b84d80-e0be-11e9-82e5-c8dfb624ad01.png)

**Comment by aparente-nurix** [comment]
Has anything happened with this? Would be very useful!

**Comment by greglandrum** [comment]
@aparente-nurix Yes, the work is already merged and it will be available in the 2020.09 RDKit release, which should happen mid-October.

**Comment by d-b-w** [comment]
@greglandrum -
I think that this can be closed, it's done.

**Comment by greglandrum** [comment]
@d-b-w thanks for pointing that out

**Comment by jones-gareth** [comment]
@greglandrum Not sure if there has been a regression, but I am not seeing these labels.  For example, using `two_centers_or.mol`.  

```
with open('two_centers_or.mol', 'r') as fh:
    mol_block = fh.read()
mol = Chem.MolFromMolBlock(mol_block)
drawer = rdMolDraw2D.MolDraw2DSVG(300,300)
rdMolDraw2D.PrepareAndDrawMolecule(drawer, mol);
# drawer.DrawMolecule(mol)
drawer.FinishDrawing()
mol
```
 I see
![Screenshot 2022-03-17 171021](https://user-images.githubusercontent.com/24233741/158908837-c2834836-35fe-40ba-8fa7-385fc2e3cad5.png)

Whereas I'd expect something like

![Screenshot 2022-03-17 171107](https://user-images.githubusercontent.com/24233741/158908884-9d346eba-6967-4016-950a-efd65a9ca203.png)
