### ISSUE TITLE
RGroupDecomp:: the std::map interfaced exposed via swig doesn't expose key iterator

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#2661]
This means you can't iterate through the RGroups.

We either need to add this iterator, or provide a mechanism for getting the used rgroup labels.

Note, this appears to be intentional in the swig wrapper for std::map

https://stackoverflow.com/questions/9465856/no-iterator-for-java-when-using-swig-with-cs-stdmap

**Comment by greglandrum** [comment]
Seems like manually adding some kind of mechanism to get the labels is a reasonable solution for the moment?

**Comment by bp-kelley** [comment]
Yeah, there are two options.   I’ll do easy ( add method to the class ) and then hard fix the map in java.

**Comment by greglandrum** [comment]
Closed in #2681
