### ISSUE TITLE
Mol rendering within DataFrames in a Jupyter Notebook is broken with Pandas 0.25.1

### ISSUE THREAD

**Issue by mrcblt** [rdkit/rdkit#2673]
**Description:**

- Python Version: 3.7.4
- RDKit Version: 2019.03.4
- Pandas Version: 0.25.1
- Platform: macOS/Linux

Starting with Pandas version 0.25.1, Mol objects within DataFrames are no longer drawn in a Jupyter notebook. The HTML string is displayed instead of the drawn molecule (`<img src="data:image/png;base64,iVBORw0KGgoAAA...`). With version 0.25.0 and below everything works fine.

**Code to reproduce in a Jupyter Notebook:**
```
from rdkit.Chem import PandasTools
df = PandasTools.LoadSDF('example.sdf')
df.head()
```

**Current workaround aside from the switch to Pandas 0.25.0:**
```
from rdkit.Chem import PandasTools
from IPython.core.display import HTML

def show(df):
    return HTML(df.to_html(notebook=True))

df = PandasTools.LoadSDF('example.sdf')
show(df.head())
```

**Comment by greglandrum** [comment]
Confirmed. This is due to some change in pandas v0.25.x
Now we just need to figure out how to work around it.

**Comment by hellerm2** [comment]
Hi Greg,

the current workaround from above needs, at least in my hands, the following line:

`PandasTools.RenderImagesInAllDataFrames(images=True)`

Without that line, only a string gets displayed.

**Comment by fredrikw** [comment]
I looked at the Pandas code and they no longer call `to_html` from `_repr_html_` but instead go directly to a "DataFrameFormatter". So, the patched to_html will not be called for repr. The best solution might be to patch the DataFrameFormatter.to_html() instead.

**Comment by fredrikw** [comment]
Or on second thought, that would probably be too harsh since it will patch every dataframe, not only the ones with structures.
So maybe patching _repr_html_ in addition to to_html?

**Comment by greglandrum** [comment]
Some additional info here, as I collect it:
- Things work fine with pandas 0.25.0, the breakage first appears in 0.25.1
- This snippet works with pandas 0.25.3 `from IPython.display import HTML;HTML(df.head().to_html())`
