### ISSUE TITLE
check if SMILES prefix valid

### ISSUE THREAD

**Issue by chaoyan1037** [rdkit/rdkit#2675]
Basically, I have a SMILES prefix, which may be not complete, and I would like to check if this prefix is valid. The prefix is valid means that it is the prefix of at least one valid SMILES. Is there any way to do it?

**Comment by greglandrum** [comment]
It depends on what you mean by "valid".
If you want to define something with partially specified rings or branches, like `C1C(`, as "valid" then the RDKit does not have anything that can help. @baoilleach's partial smiles project can probably do what you're looking for: https://baoilleach.blogspot.com/2019/09/partialsmiles-validating-parser-for.html

**Comment by baoilleach** [comment]
Thanks for the shoutout, Greg. This is exactly the use case for the [partialsmiles](https://github.com/baoilleach/partialsmiles) project.

**Comment by chaoyan1037** [comment]
Thanks for your reply! By saying "valid", I mean there is at least one valid SMILES that starts with the prefix. I will check the partialsmiles project.
