### ISSUE TITLE
Add MolHash to Java Wrappers

### ISSUE THREAD

**Issue by sroughley** [rdkit/rdkit#2677]
Could the new MolHash code (#2636) be added to the Java wrappers?

Thanks

Steve

**Comment by greglandrum** [comment]
Yep. I'm surprised it didn't end up there automatically, but it looks like I never wrapped the hashing stuff. I'll get that fixed.

**Comment by sroughley** [comment]
Thanks Greg - that would be really useful.  I started writing my own version in Java based on Noel's post a while back and then other things came up - this way will be much nicer!
