### ISSUE TITLE
Uncharger does not neutralize azide

### ISSUE THREAD

**Issue by rmrmg** [rdkit/rdkit#2688]
>>> from rdkit import Chem
>>> from rdkit.Chem.MolStandardize import rdMolStandardize 
>>> uncharger = rdMolStandardize.Uncharger()
>>> m = Chem.MolFromSmiles('[N-]=[N+]=[N-]')
>>> p=uncharger.uncharge(m)
[09:15:16] Running Uncharger
>>> Chem.MolToSmiles(p)
'[N-]=[N+]=[N-]'

I expected N=[N+]=[N-] as a uncharged product.
Rdkit version 2019.03.4 on Linux (from conda)
By the way IHMO logs from *normal* works of uncharger should by disable by default.

**Comment by greglandrum** [comment]
I understand the request and agree that this is something worth thinking about.
To explain the current behavior: the uncharger does not modify anions that are directly bonded to cations (or vice versa).
