### ISSUE TITLE
Postgres 12 support

### ISSUE THREAD

**Issue by ValeryPolyakov** [rdkit/rdkit#2700]
Hi Greg,

Are you planning to implement Postgres 12 support any time soon? The main advantage of v12 is the ability to simultaneously update indexes when adding new rows without causing a delay.

Thanks,

Valery

**Comment by greglandrum** [comment]
We haven't needed to make changes to the cartridge code to adapt to a particular PostgreSQL version in quite a while, so I imagine that things ought to work with PostegreSQL 12.

If you are asking about whether or not we plan to provide conda binaries: That's a question for the rdkit-conda repo

**Comment by rvianello** [comment]
conda-based binaries will also need to wait for PostgreSQL 12 to become available from the upstream anaconda distribution.

**Comment by greglandrum** [comment]
Yep, but that's still something for the conda-rdkit repo, not this one. :-)

**Comment by mbanck** [comment]
I am getting a lot of regression failures with Postgres v12, possibly due to the new floating point logic ("Improve performance by using a new algorithm for output of real and double precision values" from https://www.postgresql.org/docs/12/release-12.html), e.g.:

```
-   id    |   tanimoto_sml    
----------+-------------------
- 3761688 | 0.441860465116279
+   id    |    tanimoto_sml    
+---------+--------------------
+ 3761688 | 0.4418604651162791
```

and

```
-   id    |     dice_sml      
----------+-------------------
- 3761688 | 0.612903225806452
+   id    |      dice_sml      
+---------+--------------------
+ 3761688 | 0.6129032258064516
```

Are you getting those as well?

**Comment by greglandrum** [comment]
Hi @mbanck , I still haven’t tried with v12; I will take a look at that when I am back in the office mid-week

**Comment by greglandrum** [comment]
@mbanck: I'm able to reproduce the problem and will take a look into fixing it.

**Comment by mbanck** [comment]
@greglandrum https://salsa.debian.org/debichem-team/rdkit/blob/master/debian/patches/postgres_alternative_test_outputs.patch has a crude patch that just duplicates the test output with the alternative numerical results from v12, I have not investigated whether maybe setting `extra_float_digits` explicitly would make it possible to have one set of expected output for all.
