### ISSUE TITLE
Where can find RDGeneral/export.h from rdkit code file?

### ISSUE THREAD

**Issue by YuYaoYang2333** [rdkit/rdkit#2706]
**Description:**

- RDKit Version:
- Platform:

```
Your code sample here
```

**Comment by greglandrum** [comment]
That file is not created until after you do a build.
Why do you need it?

**Comment by YuYaoYang2333** [comment]
Thank you for your quickly reply. I want to carry out the Bemis and Murcko’s algorithm. While I found that your MurckoDeCompose function could not give me separated ring system and linker of a molecule. So I trend to seek more information from rdmolops module. And it is hard for me to understand this module for my limited C++ operation, I am used to python language . If there are some more convenient methods to get the ring, linker, chain using BM methods? I am hoping for your reply! Thanks very very much!

--------------原始邮件--------------
发件人："Greg Landrum "<notifications@github.com>;
发送时间：2019年10月9日(星期三) 中午1:23
收件人："rdkit/rdkit" <rdkit@noreply.github.com>;
抄送："Yuyao Yang "<yangyy75@mail2.sysu.edu.cn>;"Author "<author@noreply.github.com>;
主题：Re: [rdkit/rdkit] Where can find RDGeneral/export.h from rdkit code file? (#2706)
-----------------------------------

 
That file is not created until after you do a build.
 Why do you need it?

**Comment by d-b-w** [comment]
Please move further questions to the "discussion" tab.
