### ISSUE TITLE
"FilterCatalogEntry" uses "Clone" not "copy",  causes Warnings

### ISSUE THREAD

**Issue by Chaosschaf** [rdkit/rdkit#2720]
**Configuration:**

- RDKit Version: 2019.03.3
- Operating system: linux/Gnome
- Python version (if relevant): No, but: 3.7.3.final.0
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? -c rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**
Creating a Filter causes Warnings:
FilterMatcherBase::Clone is deprecated, use copy instead

**Minimalcode python:**
from rdkit.Chem import FilterCatalog
two_phenyls = FilterCatalog.SmartsMatcher("at least two phenyls","[cD3]1[cD2][cD2][cD2][cD2][cD2]1",2)
fc = FilterCatalog.FilterCatalog()
fc.AddEntry(FilterCatalog.FilterCatalogEntry("matcher",two_phenyls))

**Suggested Solution:**
Update FilterCatalogEntry.h, line 63:
        : RDCatalog::CatalogEntry(), d_matcher(matcher.Clone()) {
To:
        : RDCatalog::CatalogEntry(), d_matcher(matcher.copy()) {

**Comment by bp-kelley** [comment]
Just fixed yesterday:

#2711

**Comment by Chaosschaf** [comment]
Thanks
