### ISSUE TITLE
rdkit make install issue

### ISSUE THREAD

**Issue by rd0102** [rdkit/rdkit#2730]
I was doing the installation of rdkit in ubuntu 16.04 from the source.
RDKit Version -rdkit-Release_2019_03_3

I have successfully completed cmake and make steps but unfortunately, I am facing issues in make install command.
My below error:

**CMake Error at External/CoordGen/cmake_install.cmake:148 (file):
  file INSTALL cannot find
  "/opt/rdkit/rdkit/build/lib/libRDKitcoordgen.so.1.2019.03.2".
Call Stack (most recent call first):
  External/cmake_install.cmake:40 (include)
  cmake_install.cmake:88 (include)**

After  the make command **libRDKitcoordgen .so.1.2019.03.2**" is present under lib in rdkit but during make install libRDKitcoordgen .so.1.2019.03.2". is being removed.

Can anyone help me to resolve this issue.

**Comment by joaocarmo** [comment]
Feels related to https://github.com/rdkit/rdkit/issues/2468
