### ISSUE TITLE
rdFMCS Bond Flag "Compare Order" only matches single and aromatic bonds (not double bonds)

### ISSUE THREAD

**Issue by frakruger** [rdkit/rdkit#2734]
**Configuration:**
- RDKit Version: 2019.03.4
- Operating system: Centos7

**Description:**
The issue concerns the treatment of bonds in the MCS calculation ( rdFMCS module). As described in the documentation, it is possible to set a flag bondCompare=rdFMCS.BondCompare.CompareOrder, which allows the matching of single and aromatic bonds, but double bonds are not matched. Is there an application where this setting is particularly useful? I would consider it more useful to have a flag that allows the matching of single and double bonds on aromatic bonds in rings. This would still be different than the flag rdFMCS.BondCompare.CompareAny, since single and double bonds should not match (or at least not outside rings). 
See below a simple example. In the second MCS, due to the presence of double bonds, the resulting MCS is only a chain of C atoms with query bonds (:,-). I would like to obtain a ring with query bonds (:,-) and (:,=).

**Example:**
from rdkit import Chem
from rdkit.Chem import rdFMCS

mol1=Chem.MolFromSmiles('C1CCCCC1')
mol2=Chem.MolFromSmiles('c1ccccc1')
mol3=Chem.MolFromSmiles('C1=CC=CCC1')

MCS12=rdFMCS.FindMCS([mol1,mol2],bondCompare=rdFMCS.BondCompare.CompareOrder).smartsString
print(MCS12)

MCS23=rdFMCS.FindMCS([mol2,mol3],bondCompare=rdFMCS.BondCompare.CompareOrder).smartsString
print(MCS23)

**Comment by greglandrum** [comment]
I'm reluctant to change the existing behavior, but adding a new option which allows aromatic bonds to match single and double bonds in rings seems like a reasonable thing to do.

**Comment by ptosco** [comment]
@greglandrum I'd very much like to add the possibility to use custom compare functions from Python (currently that can only be done in C++). If you like it I'll add an enhancement for this one too and take both in charge.

**Comment by greglandrum** [comment]
@ptosco : If we had the custom compare parameters working in a sensible way from Python, then we wouldn't even need this additional option. I would be extremely happy if you wanted to take this on. :-)

**Comment by ptosco** [comment]
@greglandrum It should be doable - I know it will be a fun one, that's why I am volunteering to take it on :-) And yes, that would avoid the additional option.

**Comment by greglandrum** [comment]
This was added in #3023
