### ISSUE TITLE
How to prevent bond order from changing chirality

### ISSUE THREAD

**Issue by kheyer** [rdkit/rdkit#2736]
Setup Info:
- RDKit Version: 2019.03.4
- Operating system: Ubuntu 16.04.6
- Python version (if relevant): 3.6.5
- Are you using conda? - Yes
- If you are using conda, which channel did you install the rdkit from? - conda install -c rdkit rdkit

**Description:**

I'm working on a project that involves using graph convolutional neural networks to generate molecules. An important step in this process is converting a graph to a molecule using RDKit. The graph has nodes classified as atoms with a specific charge, chirality and number of hydrogen atoms, as well as edges classified as bond types.

Molecules are reconstructed using `Chem.RWMol()`, adding atoms sequentially, then adding bonds. Reconstruction works great for assembling atoms correctly, but I've run into an issue where the *order* in which bonds are added changes the *orientation* of chiral centers in the final molecule.

Putting graphs and all that aside, here's a test case using only RDKit that shows the issue:

```
from rdkit import Chem
import random

def smile_to_mol(smile):
    # convert SMILES string to Mol object
    mol = Chem.MolFromSmiles(smile)
    new_order = Chem.rdmolfiles.CanonicalRankAtoms(mol)
    mol = Chem.rdmolops.RenumberAtoms(mol, new_order)
    
    return mol

def get_atom_properties(mol):
    # Get atom properties from a Mol object
    # Properties used are atom symbol, charge, number of hydrogens and chirality
    atoms = [atom.GetSymbol() for atom in mol.GetAtoms()]
    charge = [atom.GetFormalCharge() for atom in mol.GetAtoms()]
    hydrogens = [atom.GetTotalNumHs() for atom in mol.GetAtoms()]
    chirality = [atom.GetChiralTag() for atom in mol.GetAtoms()]
    
    return atoms, charge, hydrogens, chirality

def get_bond_properties(mol, shuffle=False):
    '''
    Get bond properties
    
    The bond_pairs list contains lists of [[u,v], bond_type]
    
    Where [u,v] correspond to the index of beginning and ending atoms
    within the Mol object, and bond_type is the bond's type class
    
    If shuffle is set to True, the order of items is shuffled, triggering the issue
    '''

    bond_pairs = []
    bonds = []

    num_bonds = mol.GetNumBonds()

    for i in range(num_bonds):
        bond = mol.GetBondWithIdx(i)
        u = bond.GetBeginAtomIdx()
        v = bond.GetEndAtomIdx()
        bond_type = bond.GetBondType()
        bond_pairs.append([[v,u], bond_type])
        
    if shuffle:
        random.shuffle(bond_pairs)
        
    return bond_pairs

def reconstruct_molecule_from_data(atoms, charge, hydrogens, chirality, bond_pairs):
    '''
    Reconstructs a molecule from atom and bond information
    '''
    
    new_mol = Chem.RWMol()
    node_to_idx = {}

    for i in range(len(atoms)):
        '''
        For each atom in the list of atoms, a Chem.Atom object is created and 
        populated with the corresponding charge, hydrogen and chirality data.
        
        Then the atom is added to the new_mol object
        '''
        atom = atoms[i]
        atom = Chem.Atom(atom)

        atom_charge = charge[i]
        atom.SetFormalCharge(atom_charge)

        hydrogen = hydrogens[i]
        atom.SetNumExplicitHs(hydrogen)

        atom_chirality = chirality[i]
        atom.SetChiralTag(atom_chirality)

        molIdx = new_mol.AddAtom(atom)
        node_to_idx[i] = molIdx

    for i in range(len(bond_pairs)):
        '''
        For each set of [[u,v], bond_type] values, a bond is added to the molecule
        '''
        idx_pairs, bond = bond_pairs[i]
        bond_src, bond_dest = idx_pairs

        new_mol.AddBond(node_to_idx[bond_src], node_to_idx[bond_dest], bond)

    new_mol = new_mol.GetMol()
    
    return new_mol

def run_test(smile, shuffle=False):
    '''
    Run test to reproduce the issue. Set shuffle=True to see the chirality flipping issue
    '''
    
    # create Mol object
    mol = smile_to_mol(smile)
    
    # Get atom data
    atoms, charge, hydrogens, chirality = get_atom_properties(mol)
    
    # Get bond data
    bond_pairs = get_bond_properties(mol, shuffle=shuffle)
    
    # Reconstruct molecule
    new_mol = reconstruct_molecule_from_data(atoms, charge, hydrogens, chirality, bond_pairs)
    
    # Generate new SMILES
    new_smile = Chem.MolToSmiles(new_mol)
    
    # Compare input SMILES to reconstruction 
    if new_smile == smile:
        print('Reconstruction successful')
    else:
        print("Reconstruction failed")
        
    print(f'Input\t{smile}')
    print(f'Output\t{new_smile}')
    

# run the test
smile = 'C=CCN1CC[C@]23c4c5ccc(O)c4O[C@@H]2C(=O)CC[C@]3(O)[C@H]1C5'
run_test(smile, shuffle=False)
run_test(smile, shuffle=True)
```

The `shuffle` parameter only changes the bond order during reconstruction. Running the test with `shuffle=False` reconstructs the molecule using the same bond order as the original molecule. Running the test with `shuffle=True` randomly shuffles the bond order before reconstruction. 

Note that the only thing being shuffled is the order in which bonds are added to the new molecule. The bond type and the beginning/ending atom indices (as well as the atom order during reconstruction) are not changed.

Running the test should yield the following output:

```
run_test(smile, shuffle=False)

Reconstruction successful
Input	C=CCN1CC[C@]23c4c5ccc(O)c4O[C@@H]2C(=O)CC[C@]3(O)[C@H]1C5
Output	C=CCN1CC[C@]23c4c5ccc(O)c4O[C@@H]2C(=O)CC[C@]3(O)[C@H]1C5

run_test(smile, shuffle=True)

Reconstruction failed
Input	C=CCN1CC[C@]23c4c5ccc(O)c4O[C@@H]2C(=O)CC[C@]3(O)[C@H]1C5
Output	C=CCN1CC[C@@]23c4c5ccc(O)c4O[C@@H]2C(=O)CC[C@@]3(O)[C@H]1C5
```

Notice that shuffling the bond order does not change the order of atoms in the final molecule. The only thing that is changed is the chiral orientation of different atoms. In this case, `[C@]` became `[C@@]` in several places. The specific chirality change depends on the random shuffle of the bond order, so running the test with `shuffle=True` multiple times will yield a variety of results.

Is there a way to make chiral orientation robust to bond order in reconstruction? I know that bonds have a `stereo` property, but these appear to be `STEREONONE` by default. Any assistance on this is appreciated.

**Comment by greglandrum** [comment]
I understand the pain point here and appreciate what you are trying to do, but the current RDKit stereo representation is relative to the ordering of the bonds around an atom, not the ordering of neighboring atoms. So CHI_TETRAHEDRAL_CW means that when you look down the first bond towards the central atom you rotate clockwise to move from the second bond to the third.

I realize that this isn't the most obvious thing and that it makes things painful for your use case; sorry about that. :-( It doesn't help you right now, but we are currently re-thinking how the stereochemistry model works and may be making some changes here for a future release (that will, of course, have to be done very carefully).

There is a manual way to figure out whether or not the atomic chirality needs to change based on the numberings of atoms and bonds. I will post a Python function for this in a bit.

**Comment by Dicksonchin93** [comment]
Hi @greglandrum when atom order changes the chiralty also changes, even when bond order is fixed. Any chance there is a script for handling both random atom order and random bond order?

**Comment by greglandrum** [comment]
> Hi @greglandrum when atom order changes the chiralty also changes, even when bond order is fixed. 

I don't believe that's the case, so I'm probably misunderstanding you.
Please provide an example which demonstrates what you mean.

**Comment by Dicksonchin93** [comment]
```
import random
from rdkit import Chem

        
def test_reproducing_mol(
    random_atom_order=True,
    random_bond_order=True,
    random_bond_end_begin_idx=True,
    update_mol_chiralty=True,
):

    inchi_target = 'InChI=1S/C16H28O/c1-10-14-8-12(16(10,2)3)9-15(14)11-5-4-6-13(17)7-11/h10-15,17H,4-9H2,1-3H3/t10-,11+,12-,13-,14+,15-/m1/s1'
    mol_two = Chem.MolFromInchi(inchi_target)

    all_symbols = []
    all_chiral_tags = []
    for atom in mol_two.GetAtoms():
        all_symbols.append(atom.GetSymbol())
        all_chiral_tags.append(atom.GetChiralTag())

    atom_order = list(range(17))

    if random_atom_order:
        random.shuffle(atom_order)

    atom_order_map = {}
    for idx, odr in enumerate(atom_order):
        atom_order_map[odr] = idx  


    all_begin_atoms = []
    all_end_atom = []
    all_bond_type = []
    for bond in mol_two.GetBonds():
        choice = 0 if not random_bond_end_begin_idx else random.choice([0, 1])
        if choice == 0:
            begin_atom = bond.GetBeginAtomIdx()
            end_atom = bond.GetEndAtomIdx()
        else:
            begin_atom = bond.GetEndAtomIdx()
            end_atom = bond.GetBeginAtomIdx()
        all_begin_atoms.append(begin_atom)
        all_end_atom.append(end_atom)
        all_bond_type.append(bond.GetBondType())

    bond_order = list(range(len(all_bond_type)))
    if random_bond_order:
        random.shuffle(bond_order)

    em = Chem.RWMol()
        
    for order_idx in atom_order:
        a = Chem.Atom(all_symbols[order_idx])
        a.SetChiralTag(all_chiral_tags[order_idx])
        em.AddAtom(a)

    for bo in bond_order:
        em.AddBond(
            atom_order_map[all_begin_atoms[bo]],
            atom_order_map[all_end_atom[bo]],
            all_bond_type[bo]
        )

    reconstructed_mol_two = em.GetMol()
    if update_mol_chiralty:
        update_all_atom_stereo(reconstructed_mol_two)
    return Chem.MolToInchi(reconstructed_mol_two) == inchi_target
    
    
print(
    test_reproducing_mol(
        random_atom_order=True, random_bond_order=True, random_bond_end_begin_idx=True, update_mol_chiralty=True
    )
)
print(
    test_reproducing_mol(
        random_atom_order=False, random_bond_order=True, random_bond_end_begin_idx=False, update_mol_chiralty=True
    )
)
print(
    test_reproducing_mol(
        random_atom_order=False, random_bond_order=True, random_bond_end_begin_idx=True, update_mol_chiralty=True
    )
)
print(
    test_reproducing_mol(
        random_atom_order=True, random_bond_order=True, random_bond_end_begin_idx=True, update_mol_chiralty=True
    )
)
print(
    test_reproducing_mol(
        random_atom_order=False, random_bond_order=False, random_bond_end_begin_idx=False, update_mol_chiralty=False
    )
)
```


the above returns
```
False
True
True
False
True
```

**Comment by Dicksonchin93** [comment]
so 
`print(
    test_reproducing_mol(
        random_atom_order=True, random_bond_order=False, random_bond_end_begin_idx=False, update_mol_chiralty=True
    )
)` returns False

while `print(
    test_reproducing_mol(
        random_atom_order=True, random_bond_order=False, random_bond_end_begin_idx=False, update_mol_chiralty=False
    )
)` returns True

it seems that using update_all_atom_stereo with different atom order provides different results
