### ISSUE TITLE
postgresql cartridge with the lastest rdkit 2019.03.4 version for Windows users

### ISSUE THREAD

**Issue by nanhuayu** [rdkit/rdkit#2745]
**Configuration:**

- RDKit Version: 2019.03.4
- Operating system: Windows 10
- Python version (if relevant): 3.7.4
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit channel
- If you are not using conda: how did you install the RDKit?

**Description:**

I've tried to install the postgresql cartridge in windows, and I need some help. I tried to use the conda to install the rdkit-postgresql cartridge, however, it seems that the cartridge didn't support the windows platform. Then, I tried to compile the rdkit from source by myself, I tried to follow the tutorials from "https://www.rdkit.org/docs/Install.html" and the other websites, it seems a little hard to compile it under the latest version of VS or mingw-w64. 

The rdkit toolkit is really powerful. Is there any tutorials or ways to install postgresql cartridge? I would really appreciate your help.   

```
Your code sample here
```

**Comment by ptosco** [comment]
@nanhuayu Hello, the PostgreSQL conda recipe for Windows seems a bit broken at the moment. I'll find some time to fix it over the next few days.

**Comment by nanhuayu** [comment]
@ptosco Thank you for your kind reply, I'm looking forward to the windows version.

**Comment by kienerj** [comment]
I'm also referencing this yet empty topic in discussions:

https://github.com/rdkit/rdkit/discussions/4073

Are there any plans to make this work again? It's still on the very old 2019 version for Windows.
