### ISSUE TITLE
Can I calculate term-wise forcefield?

### ISSUE THREAD

**Issue by yy692** [rdkit/rdkit#2746]
**Configuration:**

- RDKit Version: 2019.03.2
- Operating system: MacOS Mojave 10.14.6
- Python version (if relevant): Python 3.7.4
- Are you using conda? No
- If you are using conda, which channel did you install the rdkit from? --
- If you are not using conda: how did you install the RDKit? Homebrew

**Description:**

Hi,

I am wondering if I can get the individual terms in the UFF forcefield (e.g. the 2-body energy between all the atom pairs, the 3-body energy between all the connected 3-atom angles, etc.). As I see in the python wrapper, it seems that we are unable to call the energy calculation function for individual terms directly from Python... So I'm wondering if you guys can help to make it possible. Thanks a lot.

Best,

Yang

**Comment by ptosco** [comment]
@yy692 Hi, from Python you may retrieve the parameters for individual force-field terms given the atom indices, but then you'd need to apply the force-field equations on those parameters yourself. Adding Python wrappers for computing individual energy terms is certainly doable - I'll create a GitHub issue for it and try to get it done as soon as I have some time.

**Comment by yy692** [comment]
Hi @ptosco , thanks a lot for your reply. Yes, as you said, the individual forcefield terms can be calculated by using the parameters. But it still requires the determination of the atom type (e.g. the geometry environment of a certain atom...), which is a little bit tricky now since RDkit doesn't have the corresponding wrapper for "AtomTyper" function... Anyway, thanks for your help and I'm looking forward to the newer version of RDkit. :)

**Comment by yy692** [comment]
Hi, 

I was trying to deal with this issue by modifying the source code recently. However, I met a problem and don't know what the reason is.

Here is the general strategy I used:

### Strategy 1:
In file **Code/ForceField/Contrib.h**:
I added a new pure virtual function as
`virtual void getEnergyTerms(double *pos, std::vector<double> &resvec) const = 0;`

and in all the derived classes (both in the header files and the .cpp files), I defined and override the above virtual function. These functions basically do the same thing as "double getEnergy(double *pos) const" functions, but just return a vector containing the indexes of involved atoms and a double type number denoting the type of the interaction.

For example:
In file **Code/ForceField/UFF/BondStretch.h**:

`void getEnergyTerms(double *pos, std::vector<double> &resvec) const;`

In file **Code/ForceField/UFF/BondStretch.cpp**:

`void BondStretchContrib::getEnergyTerms(double *pos, std::vector<double> &resvec) const {`
  `PRECONDITION(dp_forceField, "no owner");`
  `PRECONDITION(pos, "bad vector");`

 ` double distTerm =`
 `     dp_forceField->distance(d_end1Idx, d_end2Idx, pos) - d_restLen;`
  `double res = 0.5 * d_forceConstant * distTerm * distTerm;`
  `resvec.push_back(1.0);`
  `resvec.push_back(double(d_end1Idx));`
  `resvec.push_back(double(d_end2Idx));`
  `resvec.push_back(res);`
  `resvec.push_back(0.0);`
  `resvec.push_back(0.0);`
`}`

The problem is that by doing this, I never compiled successfully... (poping up some dynamic library linking issues).

### Strategy 2:
Since the first strategy doesn't work, I came to this one.
For every derived class (both in the header files and the .cpp files), I defined the function "void getEnergyTerms(double *pos, std::vector<double> &resvec) const" derictly without inhereting it from the base class. 

I can compile successfully with this strategy only when I add "void getEnergyTerms(double *pos, std::vector<double> &resvec) const" function to some specific derived classes who have functions in their Private section originally (eg. AngelBend). For those classes with only variables in the Private section, I cannot define new functions in them (eg. BondStretch).

Can anyone help to explain this problem? Thanks a million. 

Best,

Yang
