### ISSUE TITLE
Chem.CanonSmiles seems to output SMILES far from canonical

### ISSUE THREAD

**Issue by Minys233** [rdkit/rdkit#2747]
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: Ubuntu 18.04
- Python version (if relevant): 3.7.4
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from?
Install by `conda install -c rdkit rdkit`
- If you are not using conda: how did you install the RDKit?

**Description:**
Recently I find `Chem.CanonSmiles()` function may return smiles that violates multiple normalization rules addressed in OpenSMILES, ref at [here](http://opensmiles.org/opensmiles.html#_cycles). It seems 3 rules are frequently not fulfilled:

 - Try to make "side chains" short; pick the longest chains as the "main branch" of the SMILES.
 - Start on a heteroatom if possible.
 - Avoid starting a ring system on an atom that is in two or more rings, such that two ring-closure bonds will be on the same atom.

Among them, short main branch problem is occur more than the rest two. Here are some examples of canonical SMILES generated by `Chem.CanonSmiles` compared to my hands. 

For every example, the first `smi` variable is canonical SMILES returned by `Chem.CanonSmiles`, the second `smi` variable is written by myself.

Some examples are shown below.

```python
import rdkit
print(rdkit.__version__)
from rdkit import Chem
from rdkit.Chem import Draw

# Example 1.
# smi = "CC1COC(Cn2cncn2)(c2ccc(Oc3ccc(Cl)cc3)cc2Cl)O1"
# No -- main branch is too short, 6 atoms
# No -- not start on a heteroatom

# smi = "n1cnn(c1)CC2(OC(C)CO2)c3c(Cl)cc(cc3)Oc4ccc(Cl)cc4"
# OK -- try to make main branch long, 17 atoms
# OK -- start on a heteroatom


# Example 2.
# smi = "CC(C)C(Nc1ccc(C(F)(F)F)cc1Cl)C(=O)OC(C#N)c1cccc(Oc2ccccc2)c1"
# NO -- main branch is too short, 10 atoms
# NO -- not start on a heteroatom

# smi = "FC(F)(F)c1cc(Cl)c(cc1)NC(C(C)(C))C(=O)OC(C#N)c2cccc(c2)Oc3ccccc3"
# OK -- try to make main branch long, 23 atoms
# OK -- start on a heteroatom


# Example 3.
# smi = "NC(Cc1c[nH]c2ccccc12)C(=O)O"
# NO -- main branch is too short, 4 atoms
# NO -- starting a ring system on an atom that is in two or more rings

# smi = "OC(=O)C(N)C-c1c2ccccc2[nH]c1"
# OK -- try to make main branch long, 13 atoms
# OK -- not break multiple rings on one atom


# Example 4.
# smi = "COCC(C)N(C(=O)CCl)c1c(C)csc1C"
# OK -- try to make main branch long, 10 atoms
# NO -- Starting from a heteroatom
# This is fine for 2 rules conflict with each other

mol = Chem.MolFromSmiles(smi)
print(Chem.CanonSmiles(smi))
Draw.MolToImageFile(mol, 'tmp1.png')
```

In addition, I compiled a rdkit debug build myself (main version is 2020) to see what is going on when output SMILES from a `ROMol` instance inside the function `RDKit::MolToSMILES`, in source file `Code/GraphMol/SmilesParse/SmilesWrite.cpp`. But there are too many functions and classes to read, for now I have no ideas on neither locate nor solve this problem.

**Comment by greglandrum** [comment]
In the context of SMILES, "canonical" just means that if you provide the same molecule as input you will always get the same SMILES as output, i.e. the output SMILES is not dependent on the order of the input atoms or bonds. The canonical SMILES that you get for a particular molecule is determined by the toolkit that you are using (and sometimes the version of the toolkit).

The OpenSMILES recommendations that you include above are a series of suggestions from some of the OpenSMILES contributors as to how they prefer to have SMILES formatted. The RDKit does not follow these recommendations, but that does not in anyway mean that the SMILES that the RDKit generates are not canonical.

Does that clarify things?

**Comment by Minys233** [comment]
> In the context of SMILES, "canonical" just means that if you provide the same molecule as input you will always get the same SMILES as output, i.e. the output SMILES is not dependent on the order of the input atoms or bonds. The canonical SMILES that you get for a particular molecule is determined by the toolkit that you are using (and sometimes the version of the toolkit).
> 
> The OpenSMILES recommendations that you include above are a series of suggestions from some of the OpenSMILES contributors as to how they prefer to have SMILES formatted. The RDKit does not follow these recommendations, but that does not in anyway mean that the SMILES that the RDKit generates are not canonical.
> 
> Does that clarify things?

Thanks, this is what I'm confused, thank you for explanation!
