### ISSUE TITLE
Error information no longer showing up on the console on Windows

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2760]
Here's the output of a simple python command running in the git bash shell on windows 10:

v2018.03:
```
glandrum@GregL-KNIME MINGW64 ~
$ python -c 'from rdkit import Chem;Chem.MolFromSmiles("C1C")'
[08:54:08] SMILES Parse Error: unclosed ring for input: 'C1C'
```

v2018.09:
```
glandrum@GregL-KNIME MINGW64 ~
$ python -c 'from rdkit import Chem;Chem.MolFromSmiles("C1C")'
[09:00:32] SMILES Parse Error: unclosed ring for input: 'C1C'
```

v2019.03:
```
glandrum@GregL-KNIME MINGW64 ~
$ python -c 'from rdkit import Chem;Chem.MolFromSmiles("C1C")'

glandrum@GregL-KNIME MINGW64 ~
```

v2019.09:
```
glandrum@GregL-KNIME MINGW64 ~
$ python -c 'from rdkit import Chem;Chem.MolFromSmiles("C1C")'

glandrum@GregL-KNIME MINGW64 ~
```

This is, of course, "somewhat unfortunate" for those of us working on windows.

**Comment by ptosco** [comment]
@greglandrum Hi Greg, this works for me on a current RDKit master branch checkout from the Git bash shell on Windows 10:
```
paolo@CRESSET45 MINGW64 ~
$ C:/build/cresset/third-party/Python/bin/trunk/win32-x86_64/python -c "from rdkit import Chem; Chem.MolFromSmiles('C1C')"
[11:38:45] SMILES Parse Error: unclosed ring for input: 'C1C'
```
but I am using a Python 3.6 interpreter built with MSVC and RDKit built with MSVC. Are you experiencing this on a MinGW build of RDKit/Python?

**Comment by greglandrum** [comment]
I'm using the rdkit conda packages.

**Comment by ptosco** [comment]
OK, I'll try the same. I am beginning to suspect the conda python interpreter.

**Comment by greglandrum** [comment]
in the examples I was showing above, the python version/install remains constant.
at least I think it does.

**Comment by bp-kelley** [comment]
A stupid solution is to call

Chem.WrapLogs()

To also print to python stdout.  I’m a bit unclear when this gets flushed though.  It also doesn’t make a lot of sense why c++ stdout a getting squashed.  Is there a boost difference?

**Comment by ptosco** [comment]
I can reproduce the problem using the conda rdkit install on Windows 10, but it definitely works on our internal Python/boost builds. I'll investigate what happens downgrading boost to earlier versions.

**Comment by greglandrum** [comment]
This is std::cerr, not std::cout.
I don't think that's an actual solution unless we understand what happened. 

There does seem to be a boost version difference: I get 1.65.1 with v2018.09.x (where things work), but 1.67.0 with v2019.03.x (where things don't work).
It seems odd to me that boost should be involved in any way for the error messages, unless the user takes some active step, which I don't think we're doing here, right?

**Comment by ptosco** [comment]
I am happy to have a look at this - my impression is that the `std::cerr` channel is redirected to be intercepted (possibly by boost for logging), and it is not then restored properly. As the console on Windows works quite differently from Unix, that would explain the platform specificity of the issue.

**Comment by greglandrum** [comment]
I'd be thrilled not to do this one. :-)

**Comment by bp-kelley** [comment]
Sorry, it wraps boost::cerr to python stderr.  We did this because it was the only way to get errors in ipython notebooks.

We should make sure that this isn't being called after I made the change to detect if we are running in an ipython notebook.  To check, you can raise an exception in IPythonConsole.py

**Comment by greglandrum** [comment]
@ptosco : I started looking into this one this morning since it was blocking forward progress on another project. I think I should be able to fix it this morning.

**Comment by greglandrum** [comment]
Ok, so here's the problem: 
#2123 switched the type of the global log pointers to be `std::shared_ptr` instead of naked pointers.

This has the unintended consequence of causing those objects to be duplicated in every Python extension module on windows instead of being global objects defined in the RDBase object.

Consequently whatever changes are made to those objects (like calls to `InitLogs()` or `WrapLogs()`) only have an effect in the python extension module where those calls are made.

A straightforward solution would be to go back to using naked pointers on windows and accepting that there might be very small memory leaks connected to the global log pointers. I'm going to give this a try to make sure it works, submit a PR, and then we can decide whether or not it's worth the effort to try and find a correct solution.

**Comment by ptosco** [comment]
@greglandrum FWIW, the issue does not show up on my Windows DLL build. The `conda` build is static, and the problem shows up. I am wondering if this is not a static vs shared rather than a Windows vs Unix problem.

**Comment by greglandrum** [comment]
Almost certainly. The Windows python builds link all the RDKit dependent libraries statically.

**Comment by ptosco** [comment]
@greglandrum I don't see an easy solution for the static linkage case other than the "leaky" one. You could make usage of naked pointer subject to a `#ifndef RDKIT_DYN_LINK`.

**Comment by ptosco** [comment]
Side note: what about defaulting to DLL builds on Windows? I can't see any compelling reason to stick to the static ones.

**Comment by greglandrum** [comment]
I really fear changing the way those builds are done. :-S

I suppose that I could give it a try and check to see how that works on the conda side

**Comment by d-b-w** [comment]
It would be totally reasonable to go back to the "leaked" logger (and add a valgrind suppression so it doesn't irritate us).

I tend to only worry about leaks that accumulate through a program - the loggers are singletons; they won't accumulate. My understanding is that using a `shared_ptr` is really just a way to clear the object before valgrind's final analysis.

Another possibility would be to declare/export the loggers?

**Comment by greglandrum** [comment]
@ptosco, @bp-kelley, @ricrogz : I've finally had enough with this one and want to fix it.

I don't think there is a fix which allows logs to be enabled/disabled from one module while affecting another one as long as the logging code is being statically linked into every module (note this happens only on windows).
So I think we need to follow @ptosco's original suggestion and switch the windows python builds, including the conda builds, over to using DLL linkage. At that point everything should "just work".

This just puts the windows python wrappers into the same boat as the Mac and linux ones... shouldn't be a problem.

**Comment by ptosco** [comment]
@greglandrum That looks like the cleanest solution to me. Other than the venerable "historical reasons", I don't see problems in switching to dynamic linking on Windows too.

**Comment by bp-kelley** [comment]
I like easy.  We should verify with gareth that this is okay with the c#
builds just in case.  I'm pretty sure they are dll links though.

**Comment by greglandrum** [comment]
I was only planning on changing the Python builds;  No code changes, so it
shouldn’t have any impact on builds someone else is doing
