### ISSUE TITLE
Cartesian to internal coordinates

### ISSUE THREAD

**Issue by pcko1** [rdkit/rdkit#2761]
Not really an issue, but more of a feature request (in case it doesn't exist).

Is there any way to convert conformations from cartesian to internal coordinates (z-matrix) using rdkit?

**Comment by ptosco** [comment]
@pcko1 I don’t believe there is one at the moment, but quick googling suggests a number of solutions, such as https://pypi.org/project/chemcoord/ (Python), OpenBabel (C, C++)

**Comment by pcko1** [comment]
thanks, I have seen the existing implementation but was wondering whether it is also implemented in our favourite library

**Comment by pcko1** [comment]
thanks, I have seen the alternative implementations but was wondering whether it is also implemented in our favourite package

**Comment by tarungog** [comment]
@ptosco While this extension is nice, https://pypi.org/project/chemcoord/, is there a way to get MMFF gradients with respect to the internal coordinates? Or might I have to program this myself?

Also seconding the feature request to build this into RDKit!

**Comment by ptosco** [comment]
@tarungog you can check currently available functionality in the C++ and Python API docs. There is a `calcGrad` accessor on the `ForceField` object accessible from both C++ and Python that will give you gradients at the position of each force field particle. From C++ you can also access gradients of individual force field contributions through `ForceFields::ForceFieldContrib::getGrad()`.

**Comment by wutobias** [comment]
Not sure if this is still relevant, but I implemented Zmatrix retrieval from an rdkit object in python: https://github.com/wutobias/r2z
Maybe it is of use to someone. If there is interest, I also have code to project gradients on the internals.
