### ISSUE TITLE
Could not generate conformers for `C1=CC2=CC=C1C2` or similar molecules

### ISSUE THREAD

**Issue by alongd** [rdkit/rdkit#2763]
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: Ubuntu
- Python version (if relevant): 3.7.5
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit (py37hc20afe1_1)

**Description:**

I could not generate conformers for fused cyclics such as `C1=CC2=CC=C1C2` (or when adding a tail, e.g.: `C1=CC2=CC=C1C2CCO`). Below is the sample code I used:

```python
from rdkit import Chem

smiles = 'C1=CC2=CC=C1C2'
rd_mol = Chem.MolFromSmiles(smiles)
Chem.AllChem.EmbedMultipleConfs(rd_mol, numConfs=100, randomSeed=1)
energies, xyzs = list(), list()
Chem.AllChem.MMFFOptimizeMolecule(rd_mol, mmffVariant='MMFF94s', confId=0,
                             maxIters=500, ignoreInterfragInteractions=False)
mp = AllChem.MMFFGetMoleculeProperties(rd_mol, mmffVariant='MMFF94s')
ff = AllChem.MMFFGetMoleculeForceField(rd_mol, mp, confId=0)
conf = rd_mol.GetConformer(0)
coords0 = conf.GetAtomPosition(0)
print([coords0.x, coords0.y, coords0.z])
```

For the molecules in question, I get the following error:
`ValueError: Bad Conformer Id`
when I do `Chem.AllChem.MMFFOptimizeMolecule`.

The code does work for most other cases I tried.

**Comment by bp-kelley** [comment]
It looks like the Eigen vector initial coordinate generation is failing.
If you embed with random coords, it appears to work:

```
AllChem.EmbedMultipleConfs(rd_mol, numConfs=100, randomSeed=1,
useRandomCoords=True)
```

Cheers,
 Brian

**Comment by alongd** [comment]
Thanks for the quick respond!
It fixed the problem for me. I'm keeping this issue open in case you think the distance matrix eigenvalues method should be fixed for cases like this.
