### ISSUE TITLE
MCS Alignment analysis problem

### ISSUE THREAD

**Issue by mti193** [rdkit/rdkit#2765]
- RDKit Version: 2019.03.2
- Operating system: Windows
- Are you using conda? Yes, Spyder

Hi, my ultimate goal of my research is to analyze the electronegativity of 2 molecules, Molecule A and Molecule B. I already having a SDF file containing the electronegativity (3d coordinates generated from Open Babel).

Now as far as the "problem" is concerned: I want to only compare electronegativity of atoms present in both molecules so I need an alignment.
I am using RDkit to align for example these 2 molecules:

    Molecule A: CCCCC\\C=C\\C(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12
    Molecule B: CCCCC[C@H](O)CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12

    Aligned molecule: C(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@@H](n2cnc3c(N)ncnc23)[C@H](O)[C@@H]1OP(O)(O)=O

As you can see Molecule A has a double bonded C=C in the beginning which if I use MCS for, finds the MCS 'to the right' of this molecule and I "lose" the data on the left (the carbons on the left). 
How can I account for this? Is there a way around this? Obviously the C=C and C-C is different but the other C-C bonds to the left are the same. I can see other problems arising in using the MCS and don't want to lose valuable electronegativity information for atoms which are in common. 

Thanks!

    import rdkit
    from rdkit import Chem
    from rdkit.Chem import MCS
    from rdkit.Chem.Draw import IPythonConsole
    from rdkit.Chem import Draw
    from rdkit.Chem.Draw import rdMolDraw2D
    from rdkit.Chem import AllChem 

    def label(a): 
        return 100*int(a.GetHybridization())+a.GetAtomicNum()
    smis=["CCCCC\\C=C\\C(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12",
      "CCCCC[C@H](O)CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(O)(=O)OP(O)(=O)OC[C@H]1O[C@H]([C@H](O)[C@@H]1OP(O)(O)=O)n1cnc2c(N)ncnc12"]

    ms = [Chem.MolFromSmiles(x) for x in smis]
    nms = [Chem.Mol(x) for x in ms]
    for nm in nms:
        for at in nm.GetAtoms():
            at.SetIsotope(label(at))
    mcs=MCS.FindMCS(nms,atomCompare='isotopes')
    mcs.smarts
    mcsp = Chem.MolFromSmarts(mcs.smarts)
    match = nms[0].GetSubstructMatch(mcsp)
    smi=Chem.MolFragmentToSmiles(ms[0],atomsToUse=match,isomericSmiles=True,canonical=False)
    ms3 = [Chem.MolFromSmiles(smi)]
    print(smi)

    Draw.MolToImageFile(ms[0], 'testmol1.png')
    Draw.MolToImageFile(ms[1], 'testmol2.png')
    Draw.MolToImageFile(ms3[0], 'test3.png')

**Comment by greglandrum** [comment]
Hi @mti193, I'm not sure I understand the question. What would you like the result to be?
Are you trying to do an MCS which ignores bond order?

**Comment by mti193** [comment]
Sort of. I Just want to know which atoms in common are present in both molecules so I can compare the electronegativity of these molecules. MCS will only return the longest chain so it can be "broken" in terms of what I want quite easily. 2 examples:

    Molecule A: OCCCCSCCCCON
    Molecule B: OCCCCOCCCCON
    MCS:              CCCCON

Problem: OCCCC is present in both molecules also but since in the backbone of the molecule So I would ideally want an alignment like OCCC_CCCON or some sort of 'gap'. 
With this ideal alignment, i would index the specific 'missing atom' in my other which in this case is the S-->O and remove the value from calculation with the other common 11 atoms from the file below:

    12
       1	 O	-2.901601
       2	 C	 0.219892
       3	 C	 0.884880
       4	 C	 0.120961
       5	 C	 1.051107
       6	 S	-2.855861
       7	 C	 1.773802
       8	 C	 0.120961
       9	 C	 1.051107
       10	 O	-2.255861
       11	 O	 1.793802
       12	 N	 1.903802


As for my question above, I modified my python script to 'simplify' my smiles input (removing sterochemistry and chirality) to account for a much more accurate and hopefully longer MCS which will return more atoms in common between both molecules. My ultimate question is, Is there some other function or Module I can use which will return atoms in common? 

    def remove_stereochemistry(smiles):
        return smiles.replace("@", "").replace("/", "-").replace("\\", "-").replace("C=C", "CC")
