### ISSUE TITLE
Displaying Structures in DataFrame using PandasTools module

### ISSUE THREAD

**Issue by dmoccia** [rdkit/rdkit#2769]
**Configuration:**

Used "conda create -c rdkit -my-rdkit-env rdkit anaconda" to create my env
MacOS High Sierra
Python 3.6.9
Running rdkit 2019.09.1

**Description:**

Hello, I recently upgraded to rdkit 2019.09.1 (I am not sure which version I upgraded from) and noticed that when I use the Pandas Tool module to either LoadSDF or the AddMoleculeColumnToFrame function, I get a DataFrame with a string of the format 

<img data-content="rdkit/molecule" src="data:image/png;base64,ETC.....alt="Mol"/>'

In the past the DataFrame would show a small PNG of the molecule, but perhaps this is the new desired effect to reduce the size of the dataframe while retaining the molecule object?  

The image link is ok, but was wondering if this is just something happening in my env.   I tried a couple of things to get the image to display such as ChangeMoleculeRendering and RenderImagesInAllDataFrames but I still see the HTML string.  I can see an image if I check a single entry

```
df.iloc[0]['Molecule']
```
or if I run the following I see the molecule images for the full df.  

```
from IPython.display import display, Image
from IPython.core.display import HTML
display(HTML(df.to_html()))
```

Not sure if I am simply missing something in setup?  Thank you for the assistance

**Comment by greglandrum** [comment]
There's a discussion of this in #2673
