### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit'

### ISSUE THREAD

**Issue by zineb1202** [rdkit/rdkit#2772]
I  installed rdkit with conda as described in the installation guide:
conda create -c rdkit -n my-rdkit-env rdkit
After activating the environment and trying to import rdkit, I get a :
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-3cb0497809fb> in <module>
----> 1 import rdkit
      2 import rdkit.Chem
      3 from rdkit.Chem import AllChem
      4 from rdkit.Chem import Draw
      5 

ModuleNotFoundError: No module named 'rdkit'

conda version: 4.7.12
python version: 3.7.5
rdkit: 2019.09.1.0
windows: 10

**Comment by dmoccia** [comment]
@zineb1202 are you running this in python shell or jupyter notebook?

**Comment by zineb1202** [comment]
@dmoccia thank you for your response. I have run it in jupyter notebook

**Comment by dmoccia** [comment]
@zineb1202 , it is likely not an issue with the rdkit install but jupyter itself.  I have seen this before in a similar capacity.  

First just make sure you have installed rdkit successfully in your env, open a new command prompt and activate your "my-rdkit-env" environment.  Then do a 

`conda list`

to see your installed packages.   If you see rdkit (I suspect you will) try reinstalling jupyerlab via 

`pip install jupyterlab`

Then try your notebook import again.  Not sure if this will work for you but it is worth a try upfront.  
The issue stems from jupyter not loading the environment you activated.  You can likely start a python shell at the command line and import rdkit just fine.  In jupyter you can see what environment is activated in the upper right corner of the tool/menu bar.

**Comment by UnixJunkie** [comment]
this can be closed; old user install problem, not an rdkit bug

**Comment by kally2588** [comment]
Under the AiZynthFinder.ipynb page, run start, there is no SMILES dialog window, and the following error always appears:
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-014284b04960>](https://localhost:8080/) in <module>
      4 get_ipython().system('pip install --quiet https://github.com/MolecularAI/aizynthfinder/archive/v2.2.1.tar.gz')
      5 get_ipython().system('mkdir --parents data && download_public_data data')
----> 6 from rdkit.Chem.Draw import IPythonConsole
      7 from aizynthfinder.interfaces import AiZynthApp
      8 application = AiZynthApp("./data/config.yml")
ModuleNotFoundError: No module named 'rdkit'
I have tried many methods but cannot solve the above problem, please let me know how to solve the above problem.

**Comment by greglandrum** [comment]
@kally2588 : please ask RDKit questions using the Discussions tab, not here in the issues.
