### ISSUE TITLE
Anaconda Distribution 2019.10 / Python 3.7 64 bits has an impatibility with Windows 10 release 1903.  I installed successful releases on Windows 10 64 bits releases 1709 and 1809, but on release 1903 the install process fails.  

### ISSUE THREAD

**Issue by asfalcao** [rdkit/rdkit#2779]
**Configuration:**

- RDKit Version:
- Operating system:
- Python version (if relevant):
- Are you using conda?
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit?

**Description:**

```
Your code sample here
```

**Comment by asfalcao** [comment]
In a PC WIndows 10 64 bits release 1903, the insatall log show the problem:

.........
Extract: seaborn-0.9.0-py37_0.conda
Extract: anaconda-2019.10-py37_0.tar.bz2
##
## After extracting task was completed 
##       unpacking task wasn't executed
##
Delete file: C:\ProgramData\Anaconda3\pkgs\env.txt
................

I repeat in two PCs using the same Anaconda package  on a Windows 10 release 1709 and 1809 and I was successul on both devices.

..................
Extract: seaborn-0.9.0-py37_0.conda
Extract: anaconda-2019.10-py37_0.tar.bz2
Unpacking : alabaster-0.7.12-py37_0.conda
Unpacking : anaconda-client-1.7.2-py37_0.conda
..................
Extract: history
Creating Anaconda3 menus...
Processed C:\Users\AdSFalcao\Anaconda3\Menu\anaconda-navigator.json successfully.
Processed C:\Users\AdSFalcao\Anaconda3\Menu\console_shortcut.json successfully.
Processed C:\Users\AdSFalcao\Anaconda3\Menu\notebook.json successfully.
Processed C:\Users\AdSFalcao\Anaconda3\Menu\powershell_shortcut.json successfully.
Processed C:\Users\AdSFalcao\Anaconda3\Menu\spyder_shortcut.json successfully.
Execute: "C:\Users\AdSFalcao\Anaconda3\pythonw.exe" -E -s "C:\Users\AdSFalcao\Anaconda3\Lib\_nsis.py" mkdirs
Running post install...
Execute: "C:\Users\AdSFalcao\Anaconda3\pythonw.exe" -E -s "C:\Users\AdSFalcao\Anaconda3\Lib\_nsis.py" post_install
Execute: "C:\Users\AdSFalcao\Anaconda3\pythonw.exe" -E -s "C:\Users\AdSFalcao\Anaconda3\pkgs\.cio-config.py" "F:\aa_Extras\Anaconda3-2019.10-Windows-x86_64.exe"
Created uninstaller: C:\Users\AdSFalcao\Anaconda3\Uninstall-Anaconda3.exe
Completed

I send the problem to the developer site, the ticket was created but 5 minutes late the ticket was finished. 
They refused it.

May somebody help me?

**Comment by greglandrum** [comment]
Are you having problems installing the anaconda distribution itself (which is hard for us to help you with) or installing the RDKit in an anaconda installation?

**Comment by asfalcao** [comment]
The problem is when installing a Anaconda Distribution 64 bits package. In the PC with Windows 10 release 1903. 
I only installed usccessful a 32 bits but it works slow.
