### ISSUE TITLE
add NumSpiroCenters and NumBridgeheadAtoms descriptors

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#278]
Implementation is in the $RDBASE/Contrib/SA_Score code

**Comment by thegodone** [comment]
Can we have a c++ version ? 

I modify one c++ version in found for RDKitjs, I'm but not sure of the results compare to your python code

vector<int> Molecule::getSpiroBridgeMacrocycles()
{
    RDKit::VECT_INT_VECT rings = rdmol->getRingInfo()->atomRings();

    int macroCycleCount = 0;
    int bridgeAtomCount = 0;
    int spiroAtomCount = 0;
    int i=0;
    for (RDKit::VECT_INT_VECT_CI ringIter = rings.begin();ringIter != rings.end();ringIter++) {
        if (ringIter->size()>8) {
            macroCycleCount++;
        }
        std::sort(rings[i].begin(),rings[i].end());
        int x=1;
        for (RDKit::VECT_INT_VECT_CI ringIter2 = ringIter+1; ringIter2 != rings.end(); ringIter2++) {
            vector<int> v;
            RDKit::Intersect(rings[i],rings[i+x],v);
            if (v.size() == 1) {
                spiroAtomCount++;
            } else if (v.size() > 2) {
                bridgeAtomCount++;
            }
            x++;
        }
        i++;
    }

    vector<int> result(3);
    result[0]=spiroAtomCount;
    result[1]=bridgeAtomCount;
    result[2]=macroCycleCount;

    return result;
}

**Comment by greglandrum** [comment]
See #617
