### ISSUE TITLE
Sanitization aromatizes outer ring but not inner ones (extra single bond)

### ISSUE THREAD

**Issue by mwojcikowski** [rdkit/rdkit#2781]
- RDKit Version: 2019.09
- Operating system: MacOS/Linux

**Description:**

I encountered weird behaviour of RDKit lately, where there are two adjacent aromatic rings, but the tautomer is not exactly the ideal one for RDKit (e.g. purines). If the hydrogens are located on 6-member ring the kekule structure gets aromatized for outer ring, with one extra single bond in the middle.

![image](https://user-images.githubusercontent.com/2325645/68764942-f145f980-061b-11ea-84a6-83991dcb6e09.png)
```
In [1]: from rdkit import Chem

In [2]: Chem.MolToSmiles(Chem.MolFromSmiles('N1C=NC=C2N=CN=C12'))
Out[2]: 'c1nc2cnc[nH]c-2n1'

In [3]: Chem.MolToSmiles(Chem.MolFromSmiles('N1C=NC2=NC=NC=C12'))
Out[3]: 'c1nc2ncncc2[nH]1'
```

If you start from the other tautomer with proton on 5-member ring the generated structure is as expected.
![image](https://user-images.githubusercontent.com/2325645/68765377-edff3d80-061c-11ea-95f6-7501dad78c46.png)

While I understand why both 6- and 5- member rings separately do not fit RDKit aromatic model it the first case, should RDKit mark the outer ring as explicitly aromatic, or should it leave the kekule structure in such cases?

**Comment by greglandrum** [comment]
Hi @mwojcikowski : the first tautomer is the same situation as azulene (https://rdkit.org/docs/RDKit_Book.html#the-rdkit-aromaticity-model): the individual rings are not aromatic, but the envelope is.
If you'd rather turn this behavior off, so that aromaticity perception across the envelope of fused rings is not considered, you can use the RDKit's "simple" aromaticity model:
```
In [2]: m = Chem.MolFromSmiles('N1C=NC=C2N=CN=C12',sanitize=False)                                                                                                                       

In [3]: Chem.SanitizeMol(m,Chem.SANITIZE_ALL^Chem.SANITIZE_SETAROMATICITY)                                                                                                               
Out[3]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [4]: Chem.SetAromaticity(m,Chem.AROMATICITY_SIMPLE)                                                                                                                                   

In [5]: Chem.MolToSmiles(m)                                                                                                                                                              
Out[5]: 'C1=NC=C2N=CN=C2N1'

In [6]: m2 = Chem.MolFromSmiles('N1C=NC2=NC=NC=C12',sanitize=False)                                                                                                                      

In [7]: Chem.SanitizeMol(m2,Chem.SANITIZE_ALL^Chem.SANITIZE_SETAROMATICITY)                                                                                                              
Out[7]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [8]: Chem.SetAromaticity(m2,Chem.AROMATICITY_SIMPLE)                                                                                                                                  

In [9]: Chem.MolToSmiles(m2)                                                                                                                                                             
Out[9]: 'c1ncc2ncnc2n1'
```

**Comment by mwojcikowski** [comment]
Thanks for suggestion, it works like a charm. We could use such samples in the Book. Simple aromaticity paragraph is a bit short ;)

**Comment by greglandrum** [comment]
Glad it worked.

> We could use such samples in the Book. Simple aromaticity paragraph is a bit short ;)

Pull requests are always welcome! :-)
