### ISSUE TITLE
addHs() fails on atoms with "bad" valences

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2782]
Here's what currently happens:
```
In [10]: m = Chem.MolFromSmiles('C=C1=CC=CC=C1',sanitize=False)                                                                                                                          

In [11]: m.UpdatePropertyCache(strict=False)                                                                                                                                             

In [12]: Chem.AddHs(m)                                                                                                                                                                   
[16:04:22] Explicit valence for atom # 1 C, 5, is greater than permitted
---------------------------------------------------------------------------
AtomValenceException                      Traceback (most recent call last)
<ipython-input-12-c1c20d587653> in <module>
----> 1 Chem.AddHs(m)

AtomValenceException: Explicit valence for atom # 1 C, 5, is greater than permitted

```
This is because `addHs()` is calling `atom->updatePropertyCache()` with default arguments (which is to be strict).
There's no need for this and it just makes things difficult for people who want to work with molecules where some atoms are in odd valence states.

**Comment by bp-kelley** [comment]
Since this is indirectly an API change (AddHs won't throw AtomValenceExceptions anymore) this should probably be documented at least in the release notes.

**Comment by greglandrum** [comment]
I agree that wouldn't hurt to add something to the release notes (though I suspect that we would have seen bug reports if others had encountered this edge case), but I disagree that it's an API change. It's a bug fix: we shouldn't have been throwing this exception from this function and now we aren't.

**Comment by skearnes** [comment]
FYI just ran across this when my tests that were expecting failure started failing :)

**Comment by greglandrum** [comment]
glad we could help. :-)
