### ISSUE TITLE
MolToSmiles(kekuleSmiles=True) gives SMILES with aromatic bonds

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#2788]
```
>>> import rdkit
>>> rdkit.__version__
'2019.09.1'
```
- Operating system: Mac
- Python version (if relevant): 3.7
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda-forge

**Description:**

The documentation for [MolToSmiles](http://rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.MolToSmiles) says: 

> kekuleSmiles: (optional) use the Kekule form (no aromatic bonds) in the SMILES. Defaults to false.

If I try it out with caffeine, it produces a SMILES with aromatic bonds:
```
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles("Cn1c(=O)c2c(ncn2C)n(C)c1=O")
>>> kekule = Chem.MolToSmiles(mol, kekuleSmiles=True)
>>> kekule
'CN1:C(=O):C2:C(:N:C:N:2C):N(C):C:1=O'
```
Given the documentation, I expected it to use single and double bonds instead of ":".

The above is almost certainly an error as the resulting SMILES cannot be processed by the RDKit:
```
>>> Chem.MolFromSmiles(kekule)
[21:22:34] Explicit valence for atom # 1 N, 4, is greater than permitted
```
I can generate a Kekule output by first calling Kekulize():
```
>>> Chem.Kekulize(mol)
>>> Chem.MolToSmiles(mol, kekuleSmiles=True)
'CN1C(=O)C2=C(N=CN2C)N(C)C1=O'
```

My suggestion is either that kekuleSmiles=True call Kekulize() itself (perhaps in a form which does not modify the molecule?) or the documentation be updated to point out that Kekulize() must be called first.

**Comment by greglandrum** [comment]
I like the idea of calling `Kekulize()` in the background here.

**Comment by bp-kelley** [comment]
What happens when kekulize fails?  Throw the exception or fall back to the current behavior?

**Comment by ptosco** [comment]
Throwing the exception seems the safest option to me, as the user has a chance to take actions in response, even just skipping the molecule.

**Comment by greglandrum** [comment]
We would need to document the fact that it can fail/throw an exception, but that's no big deal

**Comment by jvansan** [comment]
In my search to look for contributions to make (possibly helping with the 2020_09 release), I came across this.
It looks to me like this feature has been completed?

**Comment by greglandrum** [comment]
Hi @jvansan : apologies for the months-late reply... I didn't notice this your offer until today.

If you're still interested in doing this (it hasn't been implemented yet) please let me know; otherwise I will go ahead and do it.
