### ISSUE TITLE
Get neighbors error

### ISSUE THREAD

**Issue by bdaves12** [rdkit/rdkit#2789]
**Configuration:**

 
- RDKit Version: '2019.09.1'
- Operating system: Windows
- Python version (if relevant): 3.7
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? https://anaconda.org/rdkit/rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

I am trying to be able to read all of the bonds in the molecule Furan. When using [x.GetAtomicNum() for x in atom.GetNeighbors()] it is returning [1, 6, 8] when it reads oxygen which tells me it thinks oxygen is bonded to H and C but it really is only bonded two carbons. My understanding is that vector is that the first elements are bonds, and the last element is the atomic number of the atom you are reading. My guess would be it should return [6,6,8]. Am I missing something?

https://gist.github.com/bdaves12/b3861a73b1d3ae855d127b19317e3f3d
Your code sample here
```
for atom in m.GetAtoms():
    print(atom.GetAtomicNum())
    n = n+1
for x in range(0, n):
    symbol = m.GetAtomWithIdx(x).GetSymbol()
    print(symbol, x)
    if symbol == 'O':
        print(f'symbol = {symbol}')
        atom2 = m.GetAtomWithIdx(x)
        bonds2 = [x.GetAtomicNum() for x in atom.GetNeighbors()]
        bonds2.sort()
        bond_oxygen.append(bonds2)
        print(f'bond_oxygen = {bonds2}')
    if symbol == 'C':
        print(f'symbol = {symbol}')
        atom = m.GetAtomWithIdx(x)
    # print([x.GetAtomicNum() for x in atom.GetNeighbors()])
        bonds = [x.GetAtomicNum() for x in atom.GetNeighbors()]
        bond_structure.append(bonds)
        print(f'bonds = {bonds}')

Any help would be appreciated thank you.

**Comment by ptosco** [comment]
Could you please attach the SDF molblock of your molecule?
You can obtain it with
```
print Chem.MolToMolBlock(m)
```
Thanks.

**Comment by bdaves12** [comment]
9  9  0  0  0  0  0  0  0  0999 V2000
    1.2760   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3943    1.2135    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0323    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0323   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3943   -1.2135    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.7760    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.8578    2.6401    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2458   -1.6317    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.8578   -2.6401    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  1  0
  4  5  2  0
  5  1  1  0
  1  6  1  0
  2  7  1  0
  4  8  1  0
  5  9  1  0
M  END

**Comment by ptosco** [comment]
Can you please paste the molblock between
\`\`\`
\`\`\`
otherwise multiple spaces are collapsed to a single space.

**Comment by bp-kelley** [comment]
I think there is something wrong with our code, here is a simpler version
that looks ok to me:

```

>>> for atom in m.GetAtoms():

...     print(atom.GetIdx(), atom.GetSymbol(), [(nbr.GetIdx(),
nbr.GetSymbol()) for nbr in atom.GetNeighbors()])

...

atom.  atom neighbors

0 C [(1, 'C'), (4, 'C'), (5, 'H')]

1 C [(0, 'C'), (2, 'O'), (6, 'H')]

2 O [(1, 'C'), (3, 'C')]

3 C [(2, 'O'), (4, 'C'), (7, 'H')]

4 C [(3, 'C'), (0, 'C'), (8, 'H')]

5 H [(0, 'C')]

6 H [(1, 'C')]

7 H [(3, 'C')]

8 H [(4, 'C')]

```

**Comment by bp-kelley** [comment]
(Typo, I meant to write a problem with **_your_** code not a problem with our code)

And now with markdown!

```
for atom in m.GetAtoms():
  print(atom.GetIdx(), atom.GetSymbol(), [(nbr.GetIdx(), nbr.GetSymbol()) 
          for nbr in atom.GetNeighbors()])



atom.  atom neighbors
0 C [(1, 'C'), (4, 'C'), (5, 'H')]
1 C [(0, 'C'), (2, 'O'), (6, 'H')]
2 O [(1, 'C'), (3, 'C')]
3 C [(2, 'O'), (4, 'C'), (7, 'H')]
4 C [(3, 'C'), (0, 'C'), (8, 'H')]
5 H [(0, 'C')]
6 H [(1, 'C')]
7 H [(3, 'C')]
8 H [(4, 'C')]
```

**Comment by bdaves12** [comment]
Okay that's what I figured do you have any idea why the way I formatted the code did not work? Also how exactly are you using that nbr? I apologize for the questions I am new to using this software.

**Comment by ptosco** [comment]
Simplified version of your code that yields the expected result:
```
for n, atom in enumerate(m.GetAtoms()):
    print(atom.GetAtomicNum())
bond_oxygen = []
bond_structure = []
for x, atom in enumerate(m.GetAtoms()):
    symbol = atom.GetSymbol()
    print(symbol, x)
    if symbol == 'O':
        print(f'symbol = {symbol}')
        bonds2 = [nbr.GetAtomicNum() for nbr in atom.GetNeighbors()]
        bonds2.sort()
        bond_oxygen.append(bonds2)
        print(f'bond_oxygen = {bonds2}')
    if symbol == 'C':
        print(f'symbol = {symbol}')
        bonds = [nbr.GetAtomicNum() for nbr in atom.GetNeighbors()]
        bond_structure.append(bonds)
        print(f'bonds = {bonds}')
6
6
8
6
6
1
1
1
1
C 0
symbol = C
bonds = [6, 6, 1]
C 1
symbol = C
bonds = [6, 8, 1]
O 2
symbol = O
bond_oxygen = [6, 6]
C 3
symbol = C
bonds = [8, 6, 1]
C 4
symbol = C
bonds = [6, 6, 1]
H 5
H 6
H 7
H 8
```
The reason why your code fails is here:
```
    if symbol == 'O':
        print(f'symbol = {symbol}')
        atom2 = m.GetAtomWithIdx(x)
        print('*** atom', atom.GetIdx(), atom.GetSymbol())
        bonds2 = [x.GetAtomicNum() for x in atom.GetNeighbors()]
```
You define `atom2`, but then access `atom` in the following line, and `atom` still has the value that you assigned in the `if symbol == 'C'` `if` clause, so it is actually the last carbon that you met while looping through the atoms.

**Comment by bdaves12** [comment]
Ahhh I did not even realize that thank you so much this was extremely helpful!

**Comment by bp-kelley** [comment]
Following up, the 'nbr' is being used in a list comprehension:

```
[(nbr.GetIdx(), nbr.GetSymbol()) for nbr in atom.GetNeighbors()]
```

This makes a new list of (atom_idx, atom_symbol) by iterating through atom.GetNeighbors using the temporary variable nbr.

More info here;

https://www.pythonforbeginners.com/basics/list-comprehensions-in-python

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
