### ISSUE TITLE
Building error on Windows

### ISSUE THREAD

**Issue by rubenvdvijver** [rdkit/rdkit#2809]
**Configuration:**

- RDKit Version: rdkit-Release_2019_09_1
- Operating system: windows10
- Python version (if relevant): Python 
- Are you using conda? No, and I am trying not to use it
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit? from source
- Boost version: 1_65_1 (also tried 1_71_0)
- cmake compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
- Microsoft Visual Studio 2017

**Description:**

I am trying to install RDKit on my laptop but keep getting errors. I tried different RDKit releases and different boost versions. The command I use to run cmake: 
```
cmake -D CMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe" -DRDK_BUILD_PYTHON_WRAPPERS=ON -DBOOST_ROOT=C:/Users/ruvdvijv/workspaces/boost_1_65_1 -DRDK_BUILD_INCHI_SUPPORT=ON -DRDK_BUILD_AVALON_SUPPORT=ON -G"Visual Studio 15 2017 Win64" ..
```
This runs fine and gives no errors, and to build: 
```
"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe" /m:4 /p:Configuration=Release INSTALL.vcxproj
```
When I run the last command, 80 warnings and 90 errors occur. This is the example of one of the errors, they all look similar:
```
       "C:\Users\ruvdvijv\pyprogs\rdkit-Release_2019_09_1\build\INSTALL.vcxproj" (default target) (1) ->
       "C:\Users\ruvdvijv\pyprogs\rdkit-Release_2019_09_1\build\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\Users\ruvdvijv\pyprogs\rdkit-Release_2019_09_1\build\Code\GraphMol\MolStandardize\Wrap\rdMolStandardize.vcxp
       roj" (default target) (122) ->
         rdMolStandardize.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) struct _object * __cde
       cl boost::python::detail::init_module(struct PyModuleDef &,void (__cdecl*)(void))" (__imp_?init_module@detail@py
       thon@boost@@YAPEAU_object@@AEAUPyModuleDef@@P6AXXZ@Z) referenced in function PyInit_rdMolStandardize [C:\Users\r
       uvdvijv\pyprogs\rdkit-Release_2019_09_1\build\Code\GraphMol\MolStandardize\Wrap\rdMolStandardize.vcxproj]
         C:\Users\ruvdvijv\pyprogs\rdkit-Release_2019_09_1\build\rdkit\Chem\MolStandardize\Release\rdMolStandardize.pyd
        : fatal error LNK1120: 1 unresolved externals [C:\Users\ruvdvijv\pyprogs\rdkit-Release_2019_09_1\build\Code\Gra
       phMol\MolStandardize\Wrap\rdMolStandardize.vcxproj]
```
Any idea why this occurs and how to solve it? 
A small remark, when unzipping the RDKit releases, I always get a prompt saying that the file Code/GraphMol/Descriptors/test_data/GETAWAY.out will be replace with file Code/GraphMol/Descriptors/test_data/getaway.out. I'm not sure what these files do and whether this leads to any failures when compiling RDKit.

**Comment by ptosco** [comment]
@rubenvdvijver Things to check:
1) Did you build RDKit and Boost against the same Python installation? You can check which Python was picked up by looking into the RDKit `cmake` logs and the Boost `bjam` logs.
2) Did you build Boost and RDkit with the same VS 2017 version?
3) What `bjam` flags did you use to build Boost? Here's how I build my own Boost on Windows:

Download zlib and libbz2 sources:
```
C:\msys64\usr\bin\curl.exe -L https://www.zlib.net/zlib-1.2.11.tar.gz -o zlib-1.2.11.tar.gz
C:\msys64\usr\bin\curl.exe -L https://sourceforge.net/projects/bzip2/files/bzip2-1.0.6.tar.gz/download -o bzip2-1.0.6.tar.gz
```

Untar `zlib` and `libbz2` sources:
```
"C:\Program Files\CMake\bin\cmake.exe" -E tar xzf zlib-1.2.11.tar.gz
"C:\Program Files\CMake\bin\cmake.exe" -E tar xzf bzip2-1.0.6.tar.gz
```

Run `bootstrap.bat`:
```
bootstrap.bat --without-icu
```

Create `user-config.jam` in the Boost directory and add.
```
using python 
    : 3.6                   # Version
    : C:\\path\\to\\Python\\python.exe      # Python Path
    : C:\\path\\to\\Python\\Include         # include path
    : C:\\path\\to\\Python\\libs            # lib path(s)
    ;
```

Run `b2`:
```
b2 --clean-all
b2 --user-config=user-config.jam --stagedir=win32-x86_64 address-model=64 architecture=x86 threading=multi variant=release link=shared stage --with-regex --disable-icu --with-thread --with-serialization --with-iostreams --with-python -sBZIP2_SOURCE=%cd%\bzip2-1.0.6 -sZLIB_SOURCE=%cd%\zlib-1.2.11 -sNO_LZMA=1 python-debugging=off
```

**Comment by rubenvdvijver** [comment]
Thank you for your reply @ptosco.

Initially, I build boost with an executable, not from source, and when running cmake for RDKit, if found everything it needed as far as I could see from the log. When running MSBuild.exe is when the error occurred. 

I only have one python version, and I have two VS versions, but didn't have to specify the version for boost (using the executable). How can I specify this when installing boost?

I tried what you propose and with this I can build boost successfully (version 1_71_0). However, when running cmake for RDKit, it says it cannot find boost (even though I added the -DBOOST_ROOT option with the correct path).

**Comment by ptosco** [comment]
@rubenvdvijver Try adding the following switch to your the RDKit `cmake` command: `-DBoost_NO_BOOST_CMAKE=ON`.

**Comment by rubenvdvijver** [comment]
@ptosco, I added the -DBoost_NO_BOOST_CMAKE=ON but nothing changed, it still says BOOST cannot be found.

**Comment by ptosco** [comment]
Can you post  the output of a `dir` command on your `BOOST_ROOT`? Please put it between
\`\`\`
\`\`\`

**Comment by rubenvdvijver** [comment]
Here it is:
```
 Volume in drive C is EA12C267
 Volume Serial Number is 88D1-FF3A

 Directory of C:\Users\ruvdvijv\workspaces\boost\boost_1_71_0

22/11/2019  13:20    <DIR>          .
22/11/2019  13:20    <DIR>          ..
22/11/2019  13:15           861,184 b2.exe
22/11/2019  13:26    <DIR>          bin.v2
14/08/2019  13:29    <DIR>          boost
14/08/2019  13:02               850 boost-build.jam
14/08/2019  13:02               989 boost.css
14/08/2019  13:02             6,308 boost.png
14/08/2019  13:02            19,167 boostcpp.jam
14/08/2019  13:02             2,450 bootstrap.bat
22/11/2019  13:15             2,925 bootstrap.log
14/08/2019  13:02            10,629 bootstrap.sh
14/08/2019  13:09    <DIR>          doc
14/08/2019  13:02               769 index.htm
14/08/2019  13:29             5,654 index.html
14/08/2019  13:02               291 INSTALL
14/08/2019  13:02            11,934 Jamroot
14/08/2019  13:29    <DIR>          libs
14/08/2019  13:02             1,338 LICENSE_1_0.txt
14/08/2019  13:02    <DIR>          more
22/11/2019  13:15               154 project-config.jam
14/08/2019  13:02               541 README.md
14/08/2019  13:02             2,608 rst.css
14/08/2019  13:02    <DIR>          status
14/08/2019  13:02    <DIR>          tools
22/11/2019  13:25               366 user-config.jam
22/11/2019  13:20    <DIR>          win32-x86_64
              17 File(s)        928,157 bytes
              10 Dir(s)  189,443,907,584 bytes free
```

**Comment by ptosco** [comment]
Add to your `cmake` command `-DBOOST_LIBRARYDIR=C:\Users\ruvdvijv\workspaces\boost\boost_1_71_0\win32-x86_64`.

**Comment by rubenvdvijver** [comment]
Thanks @ptosco, but I still get the same error.

**Comment by ptosco** [comment]
```
del CMakeCache.txt
```
Re-run `cmake`. Post the full output.

**Comment by rubenvdvijver** [comment]
Here it is:

[logfile.log](https://github.com/rdkit/rdkit/files/3880364/logfile.log)

**Comment by ptosco** [comment]
Make sure that `-DBOOST_LIBRARYDIR` is set to the absolute path to the folder that contains the `.lib` and `.dll` boost libraries. Are they actually in `C:\Users\ruvdvijv\workspaces\boost\boost_1_71_0\win32-x86_64`?

**Comment by rubenvdvijver** [comment]
No, they are in a subdirectory called lib, but adding this in the command doesn't change anything:

```
cmake -D CMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe" -DRDK_BUILD_PYTHON_WRAPPERS=ON -DBOOST_ROOT="C:\Users\ruvdvijv\workspaces\boost\boost_1_71_0" -DBOOST_LIBRARYDIR="C:\Users\ruvdvijv\workspaces\boost\boost_1_71_0\win32-x86_64\lib" -DBoost_NO_BOOST_CMAKE=ON -DRDK_BUILD_INCHI_SUPPORT=ON -DRDK_BUILD_AVALON_SUPPORT=ON -G"Visual Studio 15 2017 Win64" ..
```
the boost libraries are not found by cmake.

The ones that are missing according to the error message are the boost_python, boost_system and boost_iostream. I can see the boost_python and boost_iostream in that lib/ directory, but not the boost_system. All libraries have names similar to `boost_python36-vc141-mt-x64-1_71`

**Comment by ptosco** [comment]
@rubenvdvijver What version of `cmake` are you using? You might be hitting this:
https://gitlab.kitware.com/cmake/cmake/issues/19658

**Comment by rubenvdvijver** [comment]
I was using 3.10, and updating it to the most recent release (3.14) didn't fix the issue.

**Comment by ptosco** [comment]
@rubenvdvijver I'll try to build the RDKit myself using that Boost version and see if I hit the problem. I'll get back to you.

**Comment by rubenvdvijver** [comment]
Thanks!

**Comment by JLVarjo** [comment]
Comment on the GETAWAY.out side issue, it is already filed at #1876

**Comment by greglandrum** [comment]
Did you guys resolve this? It may be that the version of cmake just isn't new enough for that version of boost. Try switching to 1.69, that definitely works with cmake 3.14

**Comment by SPKorhonen** [comment]
FWIW: I've managed to compile rdkit with Boost 1.71.0 and both Python 3.6.8 and Python 3.7.5 (both x64 versions). Python 3.8 seems to be problematic. It compiles but loading of python extensions fails with "DLL load failed" for some unknown reason as the dependency walker doesn't show any missing dlls.

Anyways the versions with Boost 1.71.0 pass all tests after you change line 316 in Code/GraphMol/Substruct/vf2.hpp from "++pair.nbrbeg;" to "if (pair.nbrbeg < pair.nbrend) ++pair.nbrbeg;"

**Comment by rubenvdvijver** [comment]
I was able to resolve the problems with boost 1.69. 
RDKit is now build, but when I try to run it I get: 

```
In [1]: from rdkit import Chem
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-3a181df69616> in <module>
----> 1 from rdkit import Chem

~pyprogs\rdkit-Release_2019_09_1\rdkit\__init__.py in <module>
      1 try:
----> 2   from .rdBase import rdkitVersion as __version__
      3 except ImportError:
      4   __version__ = 'Unknown'
      5   raise

ImportError: DLL load failed: The specified module could not be found.

```

**Comment by ptosco** [comment]
@rubenvdvijver for this last issue you only need to make sure that:
1) the location where Boost DLLs are stored is in your `PATH`
2) the location where RDKit DLLs are stored (if you are building DLLs) is in your `PATH`

For the Boost 1.71 issue, I managed to reproduce it on my Windows laptop.
To get the build to work you need to add `system` to the list of Boost libraries to be built by `b2`:
```
b2 --clean-all
b2 --user-config=user-config.jam --stagedir=win32-x86_64 address-model=64 architecture=x86 threading=multi variant=release link=shared stage --with-regex --with-system --disable-icu --with-thread --with-serialization --with-iostreams --with-python -sBZIP2_SOURCE=%cd%\bzip2-1.0.6 -sZLIB_SOURCE=%cd%\zlib-1.2.11 -sNO_LZMA=1 python-debugging=off
```
and then make sure that you use the following switches in your RDKit `cmake` command:
```
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_INSTALL_PREFIX=C:\build\cresset\rdkit
  -DBoost_NO_BOOST_CMAKE=OFF
  -DBOOST_ROOT=C:\build\rubenvdvijver\boost_1_71_0
  -DBOOST_LIBRARYDIR=C:\build\rubenvdvijver\boost_1_71_0\win32-x86_64\lib
  -DBoost_NO_SYSTEM_PATHS=ON ^
```
The RDKit will then build correctly.

**Comment by rubenvdvijver** [comment]
I got it to work, thanks for the help!
