### ISSUE TITLE
computing a "stereo code" for each atom of a molecule

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#2817]
**Description:**

I would be interested in adding the following functionality to rdkit:

"[...] includes stereoinformation in the atom identifiers by using an integer following the CIP-rules. The integer  is zero if the atom is not a stereocenter, and one if it is a  stereocenter but not specified in the input data describing the  molecule. If it is a stereocenter in R or S form, the integer is two or  three. If the atom is part of a bond in E or Z form, the integer is four  or five."

Biblio:
Bellmann, L., Penner, P., & Rarey, M. (2019). Connected  Subgraph Fingerprints: Representing Molecules Using Exhaustive Subgraph  Enumeration. Journal of chemical information and modeling.

Where should I start / which files should be impacted by this feature?

Maybe we should have a mol.EncodeStereo() or mol.GetStereoCodes()
that would return an atom index to stereo code dictionary?

Regards,
F.

**Comment by mwojcikowski** [comment]
I think `Chem.FindMolChiralCenters(mol, includeUnassigned=True)` does what you need here, at least for tetrahedral stereo.

**Comment by UnixJunkie** [comment]
Thanks, I'll look into it.

**Comment by UnixJunkie** [comment]
In the C++ interface, RDkit::Bond.getStereo() returns some useful info too.

**Comment by UnixJunkie** [comment]
For the record, this is useful to molecular encodings which somewhat abstract
away bonds upon encoding.

The code will look something like that:
```
from enum import Enum

# stereo information encoding, at the atom level and using integers
class AtomStereoCode(Enum):
    NONE = 0
    ANY_CENTER = 1
    R_CENTER = 2
    S_CENTER = 3
    ANY_BOND_END = 4
    Z_BOND_END = 5
    E_BOND_END = 6
    CIS_BOND_END = 7
    TRANS_BOND_END = 8

to_atom_stereo = { '?': AtomStereoCode.ANY_CENTER,
                   'R': AtomStereoCode.R_CENTER,
                   'S': AtomStereoCode.S_CENTER,
                   rdkit.Chem.rdchem.BondStereo.STEREONONE: AtomStereoCode.NONE,
                   rdkit.Chem.rdchem.BondStereo.STEREOANY: AtomStereoCode.ANY_BOND_END,
                   rdkit.Chem.rdchem.BondStereo.STEREOZ: AtomStereoCode.Z_BOND_END,
                   rdkit.Chem.rdchem.BondStereo.STEREOE: AtomStereoCode.E_BOND_END,
                   rdkit.Chem.rdchem.BondStereo.STEREOCIS: AtomStereoCode.CIS_BOND_END,
                   rdkit.Chem.rdchem.BondStereo.STEREOTRANS: AtomStereoCode.TRANS_BOND_END }

def get_stereo_codes(m):
    # by default, each atom has no stereo
    res = [AtomStereoCode.NONE for i in range(m.GetNumAtoms())]
    # unless detected otherwise for stereo bonds
    for b in m.GetBonds():
        bstereo = b.GetStereo()
        if bstereo != rdkit.Chem.rdchem.BondStereo.STEREONONE:
            i = b.GetBeginAtomIdx()
            j = b.GetEndAtomIdx()
            k = to_atom_stereo[bstereo]
            res[i] = k
            res[j] = k
    # or for chiral centers
    for i, k in Chem.FindMolChiralCenters(m):
        res[i] = to_atom_stereo[k]
    return res
```

And you can play with it like this:
```
cis = Chem.MolFromSmiles('C/C=C\C')
trans = Chem.MolFromSmiles('C/C=C/C')
l_ala = Chem.MolFromSmiles('N[C@@H](C)C(=O)O')
d_ala = Chem.MolFromSmiles('N[C@H](C)C(=O)O')

get_stereo_codes(cis)
get_stereo_codes(trans)
get_stereo_codes(l_ala)
get_stereo_codes(d_ala)
```

Now, where should I put this code when I send a PR?

I think it belongs to the molecule class. The same which provides GetBonds().

**Comment by UnixJunkie** [comment]
@mwojcikowski any thoughts on my proposal?

**Comment by UnixJunkie** [comment]
@gedeck maybe?

**Comment by greglandrum** [comment]
An aside: I really don't like expanding the reliance upon R/S or E/Z labels. Those are computationally expensive to generate and are often wrong.

Let me explain "wrong" above: The RDKit will always generate the same CIP labels for a given molecule (no matter how it's represented), but because the algorithm used is approximate, the labels aren't necessarily correct according to the CIP rules.

**Comment by greglandrum** [comment]
To address the actual question: what do you plan to do with these labels?

**Comment by UnixJunkie** [comment]
Create chemical fingerprints which are stereo-chemistry sensitive.
I.e. upon encoding, if stereo is present in the input file (SMILES or else), this information is preserved upon molecular encoding.

**Comment by UnixJunkie** [comment]
Should I send a PR or is this useless?

**Comment by UnixJunkie** [comment]
@NadineSchneider might also have an opinion on this.

**Comment by UnixJunkie** [comment]
Greg "doesn't like expanding the reliance upon R/S or E/Z labels", so closing.
