### ISSUE TITLE
Molecules not rendered in Pandas DF in Jupyter Lab

### ISSUE THREAD

**Issue by fredrikw** [rdkit/rdkit#2825]
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: Windows 10
- Python version (if relevant): 3.7.3
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit?

**Description:**

I have a problem with the rendering of Pandas DataFrames with molecule columns in Jupyter Lab. The regular `display` method renders the molecules as `<img data-content="rdkit/molecule" src="data:image/png;base64,iVBORw0KGgoAAAANSUh...hYRAgKFhHi/wF2ILyj6HM4zwAAAABJRU5ErkJggg==" alt="Mol"/>` (abbreviated by me) instead of showing the molecule. If I instead use `HTML(df.to_html())` the structure images show up.

```python
from rdkit.Chem import PandasTools
import pandas as pd
import os
from rdkit import RDConfig
antibiotics = pd.DataFrame(columns=['Name','Smiles'])
antibiotics = antibiotics.append({'Smiles':'CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C',
    'Name':'Penicilline G'}, ignore_index=True)#Penicilline G
antibiotics = antibiotics.append({
    'Smiles':'CC1(C2CC3C(C(=O)C(=C(C3(C(=O)C2=C(C4=C1C=CC=C4O)O)O)O)C(=O)N)N(C)C)O',
    'Name':'Tetracycline'}, ignore_index=True)#Tetracycline
antibiotics = antibiotics.append({
    'Smiles':'CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O)O)C',
    'Name':'Ampicilline'}, ignore_index=True)#Ampicilline
print([str(x) for x in  antibiotics.columns])
print(antibiotics) # doctest: +ELLIPSIS
PandasTools.AddMoleculeColumnToFrame(antibiotics,'Smiles','Molecule',includeFingerprints=True)
print([str(x) for x in  antibiotics.columns])
antibiotics
```
outputs
``` md

  | Name | Smiles | Molecule
-- | -- | -- | --
0 | Penicilline G | CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C | <img data-content="rdkit/molecule" src="data:i...
1 | Tetracycline | CC1(C2CC3C(C(=O)C(=C(C3(C(=O)C2=C(C4=C1C=CC=C4... | <img data-content="rdkit/molecule" src="data:i...
2 | Ampicilline | CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O... | <img data-content="rdkit/molecule" src="data:i...
```
while
``` python
from IPython.display import HTML
HTML(antibiotics.to_html())
```
gives the table below
![image](https://user-images.githubusercontent.com/86855/70157428-debc5e80-16b5-11ea-81f9-b9d23f7b5697.png)

I don't know if there is something weird with my setup or if there is something with how Pandas is integrated with Jupyter Lab.

**Comment by fredrikw** [comment]
I reran the code in a Jupyter Notebook and it didn't work there either so I'm guessing that there is something with my setup. I cannot figure out what though... What's the mechanism that should be handling this?

**Comment by greglandrum** [comment]
I'm going to guess that this is the same problem as this one:
https://github.com/rdkit/rdkit/issues/2673
Something changed on the backend in pandas and no one has had time to track it down yet.

In the meantime you can try switch back to pandas 0.24 to see if that helps

**Comment by fredrikw** [comment]
Looks like you're right...

**Comment by aishenri** [comment]
I have this problem too 14-7-2020
Is there any improving ?

**Comment by greglandrum** [comment]
@aishenri if you do not tell us which operating system, python version, rdkit version, pandas version, etc. you are using we can't help you

**Comment by andresilvapimentel** [comment]
You may switch on molecule image visualization on a per-DataFrame basis with:
PandasTools.ChangeMoleculeRendering(df)
or for all DataFrames in your Jupyter session with:
PandasTools.RenderImagesInAllDataFrames()
