### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit'

### ISSUE THREAD

**Issue by asmelzene** [rdkit/rdkit#2832]
**Configuration:**

I don't know where to use the above commands. they don't work in jupyter because the module can't be found. They don't work in the terminal either.

- RDKit Version: 2019.09.2.0
my-rdkit-env) Melihs-MacBook-Pro:~ melih$ conda list|grep rdkit
'''packages in environment at /Users/melih/opt/anaconda3/envs/my-rdkit-env:'''
rdkit 2019.09.2.0 py37h65625ec_1 rdkit

(my-rdkit-env) Melihs-MacBook-Pro:~ melih$ python -c "import rdkit"
(my-rdkit-env) Melihs-MacBook-Pro:~ melih$
above command returns nothing.

- Operating system: MacOS Catalina Version 10.15.1
- Python version (if relevant): 3.7
"which python"returns different paths before and after activating the rdkit, I'm not sure if it's normal.
(base) Melihs-MacBook-Pro:~ melih$ which python
/Users/melih/opt/anaconda3/bin/python
(base) Melihs-MacBook-Pro:~ melih$ conda activate my-rdkit-env
(my-rdkit-env) Melihs-MacBook-Pro:~ melih$ which python
/Users/melih/opt/anaconda3/envs/my-rdkit-env/bin/python

(my-rdkit-env) Melihs-MacBook-Pro:bin melih$ pwd
/Users/melih/opt/anaconda3/bin
(my-rdkit-env) Melihs-MacBook-Pro:bin melih$ ls -lrt|grep python
-rwxrwxr-x  2 melih  staff   4183940 Aug 13 22:22 python3.7
lrwxr-xr-x  1 melih  staff         9 Dec  5 22:23 python -> python3.7
lrwxr-xr-x  1 melih  staff         9 Dec  5 22:23 python3 -> python3.7
lrwxr-xr-x  1 melih  staff        17 Dec  5 22:23 python3-config -> python3.7m-config
lrwxr-xr-x  1 melih  staff        17 Dec  5 22:23 python3.7-config -> python3.7m-config
lrwxr-xr-x  1 melih  staff         9 Dec  5 22:23 python3.7m -> python3.7
-rwxrwxr-x  1 melih  staff      1951 Dec  5 22:23 python3.7m-config
-rwxrwxr-x  1 melih  staff       139 Dec  5 22:23 python.app
-rwxrwxr-x  1 melih  staff       139 Dec  5 22:23 pythonw
-rwxrwxr-x  1 melih  staff       249 Dec  5 22:23 ipython
-rwxrwxr-x  1 melih  staff       249 Dec  5 22:23 ipython3

- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? 
Conda commands (https://www.rdkit.org/docs/Install.html):
$ conda create -c rdkit -n my-rdkit-env rdkit
$ conda activate my-rdkit-env

**Description:**
I reinstalled everything but it didn't help and I can't find a clear explanation related to that subject. Is there any way you can recommend to fix this error?

```
import pandas as pd
import numpy as np
smiles_df = pd.read_csv('training_smiles.csv')
smiles_df.info()

import rdkit 
from rdkit import Chem
import rdkit.Chem.rdMolDescriptors as rdMolDesc
rdMolDesc.CalcExactMolWt(m)
```

**Comment by greglandrum** [comment]
This usually happens because you do not have jupyter installed in your `my-rdkit-env` environment.
Try `which jupyter` and see what you get

**Comment by asmelzene** [comment]
I have jupyter installed. I also execute the commands in jupyter notebook

(base) melih@Melihs-MacBook-Pro ~ % which jupyter
/Users/melih/opt/anaconda3/bin/jupyter
(my-rdkit-env) melih@Melihs-MacBook-Pro ~ % which jupyter              
/Users/melih/opt/anaconda3/envs/my-rdkit-env/bin/jupyter

**Comment by asmelzene** [comment]
I figured out the problem...

After activating the rdkit, instead of running the command 'jupyter notebook', I was running the jupyter notebook from the graphical interface of anaconda navigator... apparently, I have to open the jupyter notebook from the command line that I activated the rdkit...

**Comment by greglandrum** [comment]
yes, you need to launch jupyter from the same environment where you installed the rdkit.
We need to add a FAQ for this.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
