### ISSUE TITLE
2D layout of two molecules

### ISSUE THREAD

**Issue by lpfSTX** [rdkit/rdkit#2835]
Dear All,

In rdkit, how to let the selected parts of two molecules have the same direction (2D layout) in one 2D depiction? Are there some APIs which can be used to reach at it?

Thanks a lot!

**Comment by bp-kelley** [comment]
There is an example in the rdkit book:

https://www.rdkit.org/docs/GettingStartedInPython.html#working-with-2d-molecules-generating-depictions

Let us know if you have any issues!

----
Brian Kelley
