### ISSUE TITLE
CMake and Boost problem to build RDkit 2019.09.2 code

### ISSUE THREAD

**Issue by jmechua-itsrdc** [rdkit/rdkit#2841]
Hi all,

I need serious help in fixing this (using Windows). Already installed all prerequisites as written by Greg, but this message keeps on appearing whenever I perform cmake on the rdkit build folder so it always ends up that the configuration is always incomplete.

> CMake Warning at C:/CMake/share/cmake-3.16/Modules/FindBoost.cmake:2006 (message):
>   No header defined for python-py37; skipping header check (note: header-only
>   libraries have no designated component)
> Call Stack (most recent call first):
>   CMakeLists.txt:246 (find_package)
> 
> CMake Error at C:/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
>   Could NOT find Boost (missing: python) (found suitable version "1.56.0",
>   minimum required is "1.56.0")
> Call Stack (most recent call first):
>   C:/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
>   C:/CMake/share/cmake-3.16/Modules/FindBoost.cmake:2165 (find_package_handle_standard_args)
>   CMakeLists.txt:254 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/rdkit-Release_2019_03_1/build/CMakeFiles/CMakeOutput.log".

This message only appears from boost 1.56 to 1.71. For 1.72, there is additional incompatibility such as cmake 3.16 cannot read 1.72 yet.. I cannot proceed with the building of the vcxproj code and test the build before I use it in iPython. I hope anyone can help me out here. Thank you.

**Comment by ptosco** [comment]
Things to check:
1) Did you build RDKit and Boost against the same Python installation? My impression is that this might be the problem here.
You can check which Python was picked up by looking into the RDKit `cmake` logs and the Boost `bjam` logs.
2) Did you build Boost and RDkit with the same VS version?
3) What `bjam` flags did you use to build Boost? Here's how I build my own Boost on Windows:

Download `zlib` and `libbz2` sources:
```
C:\msys64\usr\bin\curl.exe -L https://www.zlib.net/zlib-1.2.11.tar.gz -o zlib-1.2.11.tar.gz
C:\msys64\usr\bin\curl.exe -L https://sourceforge.net/projects/bzip2/files/bzip2-1.0.6.tar.gz/download -o bzip2-1.0.6.tar.gz
```

Untar `zlib` and `libbz2` sources:
```
"C:\Program Files\CMake\bin\cmake.exe" -E tar xzf zlib-1.2.11.tar.gz
"C:\Program Files\CMake\bin\cmake.exe" -E tar xzf bzip2-1.0.6.tar.gz
```

Run `bootstrap.bat`:
```
bootstrap.bat --without-icu
```

Create `user-config.jam` in the Boost directory and add.
```
using python 
    : 3.7                   # Version
    : C:\\path\\to\\Python\\python.exe      # Python Path
    : C:\\path\\to\\Python\\Include         # include path
    : C:\\path\\to\\Python\\libs            # lib path(s)
    ;
```

Run `b2`:
```
b2 --clean-all
b2 --user-config=user-config.jam --stagedir=win32-x86_64 address-model=64 architecture=x86 threading=multi variant=release link=shared stage --with-regex --disable-icu --with-thread --with-serialization --with-iostreams --with-python --with-system -sBZIP2_SOURCE=%cd%\bzip2-1.0.6 -sZLIB_SOURCE=%cd%\zlib-1.2.11 -sNO_LZMA=1 python-debugging=off
```

Make sure that you use the following switches in your RDKit `cmake` command:

```
  -DCMAKE_BUILD_TYPE=Release
  -DBoost_NO_BOOST_CMAKE=OFF
  -DBOOST_ROOT=C:\build\boost_1_71_0
  -DBOOST_LIBRARYDIR=C:\build\boost_1_71_0\win32-x86_64\lib
  -DBoost_NO_SYSTEM_PATHS=ON
  -DPYTHON_LIBRARY=C:\build\Python\libs\python37.lib
  -DPYTHON_INCLUDE_DIR=C:\build\Python\include
  -DPYTHON_EXECUTABLE=C:\build\Python\python.exe
```
I have tested this recipe not later than last week and it was working.
