### ISSUE TITLE
Add MolFromSDFBlock function

### ISSUE THREAD

**Issue by pyeguy** [rdkit/rdkit#2842]
**Configuration:**

- RDKit Version: 2019.09.2
- Operating system: Ubuntu 19.10
- Python version (if relevant): 3.7
- Are you using conda? :yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit? `$conda install -c rdkit rdkit`

**Description:**

I'm working with an API that returns SDF blocks as results and would like to be able to instantiate a molecule directly from the string. 

`MolFromMolBlock` with `strictParsing=False` will parse the block but looses the properties and name defined in the string. 

`SDMolSupplier` does note support file-like objects such as a `io.StringIO` which would also be an option. 

Right now I have to make a temporary file on the filesystem and then provide that path to `SDMolSupplier` which is obviously less than ideal. 

Seems like this would be quick to create for someone with C++ chops (aka not me!) by borrowing code from the two above functions to create the proposed `MolFromSDFBlock` function. Even easier would be allowing `io.StringIO` objects as arguments for `SDMolSupplier` 

example sdf block:
```
CCO
  Some API Name

  9  8  0  0  0  0  0  0  0  0999  V2000
    0.9111   -0.0580    0.0833 C   0  -0.539850  0  0  0  0  0  0  0  0  0  0
   -0.5645   -0.3943   -0.0668 C   0   0.052144  0  0  0  0  0  0  0  0  0  0
   -1.3951    0.7270    0.2733 O   0  -0.556284  0  0  0  0  0  0  0  0  0  0
    1.1128    0.3865    1.0677 H   0   0.172888  0  0  0  0  0  0  0  0  0  0
    1.2517    0.6586   -0.6717 H   0   0.157527  0  0  0  0  0  0  0  0  0  0
    1.5381   -0.9524   -0.0063 H   0   0.163812  0  0  0  0  0  0  0  0  0  0
   -0.8972   -1.1630    0.6576 H   0   0.138112  0  0  0  0  0  0  0  0  0  0
   -0.8158   -0.7181   -1.0929 H   0   0.106288  0  0  0  0  0  0  0  0  0  0
   -1.1410    1.5140   -0.2440 H   0   0.305363  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  4  1  0  0  0  0
  1  5  1  0  0  0  0
  1  6  1  0  0  0  0
  2  3  1  0  0  0  0
  2  7  1  0  0  0  0
  2  8  1  0  0  0  0
  3  9  1  0  0  0  0
M  END

> <Id>
939090603255

> <SMILES>
CCO

> <Atoms>
9

> <Bonds>
8

> <Chiral>
false

> <Energy>
-14261.901904236434

> <Enthalpy (kcal/mol @ 298 K)>
47.3436630758052

> <Gibbs energy (kcal/mol @ 298 K)>
29.8354953675966

> <Zero point energy (kcal/mol @ 0 K)>
44.196874495459795

> <Molecular dipole (X, Y, Z)>
-1.761841, 0.283414, 1.207075

> <Source energy>
-14259.552636725288

$$$$
```

**Comment by ptosco** [comment]
@pyeguy Hi Cameron, check here:
https://gist.github.com/ptosco/e4fd19a0ed5adb03c65e86290491dffc
for two ways to do what you describe.
