### ISSUE TITLE
ROC / AUC Calculation Bug

### ISSUE THREAD

**Issue by xavierholt** [rdkit/rdkit#2843]
In the Python `rdkit.ML.Scoring.Scoring` module, the `CalcROC()` and `CalcAUC()` functions return incorrect results when multiple inputs have the same score.  The correct behavior would be to consider all these inputs together to generate a single point on the ROC curve, but these functions don't know about the scores - they only know the ground truth - so the results are order dependent.

```python
# Using (score, truth) pairs:
CalcAUC([(0.5, 1), (0.5, 0)], 1) # Returns 1.0 (should be 0.5)
CalcAUC([(0.5, 0), (0.5, 1)], 1) # Returns 0.0 (should be 0.5)
```

This is mainly a problem with classifiers that return discrete scores.  For example, a random forest classifier where the score is simply the percentage of trees returning true.

**Comment by xavierholt** [comment]
The other functions in the `Scoring` module seem to have this order-dependent behavior as well, but I'm not sure how the math is supposed to work for those.

**Comment by sdvillal** [comment]
Known problem. See #1306.
