### ISSUE TITLE
How could I get the SMARTS of each ring including fused ring or single ring, respectively?

### ISSUE THREAD

**Issue by caiyingchun** [rdkit/rdkit#2844]
Here is an example compound.
CN1CCN(CC1)C2=CC=CC(NC3=NC4=C(C(CCC5CC5)=C(CC6CCCCCCC6)C=C4C=N3)C7CCC(OCC#N)C7)=C2

Thanks.

**Comment by greglandrum** [comment]
I don't understand the question. What would you expect as output for that example compound?

**Comment by caiyingchun** [comment]
The problem has been solved. Thanks.
