### ISSUE TITLE
Can't kekulize mol : murcko scaffold

### ISSUE THREAD

**Issue by Ljohn89** [rdkit/rdkit#2845]
I am using rdkit (version, '2018.09.1') for generating the murcko fragments from smiles. It does work but for some molecules, error is obtained (**Can't kekulize mol.  Unkekulized atoms: 8 10 11**) and the job is terminated without proceeding to next input.

Is there anyway to solve this problem ?

**Comment by Ljohn89** [comment]
Is there any way to skip the kekulization steps while calling MurckoScaffoldSmiles(mol,includeChirality=False)

**Comment by bp-kelley** [comment]
I think you want to use the MurckoDecompose function.  I believe it has
superseded the MurckoScaffoldSmiles.

```

>>> from rdkit.Chem import AllChem

>>> m = AllChem.MolFromSmiles("c1ccc(=O)ccc1CC2CC2CCC")

>>> scaffold = AllChem.MurckoDecompose(m)

>>> Chem.MolToSmiles(scaffold)

>>> AllChem.MolToSmiles(scaffold)

'O=c1cccc(CC2CC2)cc1'

```


Cheers,

 Brian

**Comment by Ljohn89** [comment]
Thanks Brain for the reply. 
 I was wondering if there is any way to skip the kekulization step ?
For example, I am trying to get the fragments for a set of molecules. 

As soon as the below 'mol' is encountered, it shows attribute error and my script is stopped. 
mol='OC1C2=CC=CC1=c1[c]2snc1'
m = Chem.MolFromSmiles(mol)
bis = m.GetSubstructMatches(Chem.MolFromSmarts('[!R]~[R]'))

Error message:
AttributeError: 'NoneType' object has no attribute 'GetSubstructMatches'

**Comment by bp-kelley** [comment]
In this case just use the molecule as returned from MurckoDecompose

m = AllChem.MurckoDecompose(m)
m.GetSubstructMatches(Chem.MolFromSmarts('[!R]~[R]'))

If you need to save the decomposition, you can pickle it which saves the current state.

If you must use smiles for the scaffold, that’s a bit trickier, but we can help you out.

**Comment by Ljohn89** [comment]
Yes, I need to use smiles for generating scaffold
m = AllChem.MolFromSmiles("OC1C2=CC=CC1=c1[c]2snc1")
scaffold = AllChem.MurckoDecompose(m)
ArgumentError

**Comment by Ljohn89** [comment]
One more thing !

mol='OC1C2=CC=CC1=c1c2snc1'
m = AllChem.MolFromSmiles(mol)
print(m)
None

mol='COc1ccc(CN(C)c2ncnc3sc4CC(C)CCc4c23)c(OC)c1OC'
m = Chem.MolFromSmiles(mol)
print(m)
<rdkit.Chem.rdchem.Mol object at 0x2b912d35f260>

Why there is difference in both the output ?

**Comment by bp-kelley** [comment]
Are you asking why the first molecule can't be interpreted?

The RDKit is pretty opinionated about what is chemically sensible and what isn't.

In this case, the ring you have in the first case doesn't appear to be aromatic and can't be kekulized.

The structure you are trying to work with is this:

![image](https://user-images.githubusercontent.com/9888416/70937003-94ba6d80-2011-11ea-95c6-8483789436c0.png)

Which doesn't look aromatic to me.
