### ISSUE TITLE
Feature proposal: add remove_stereochemistry=False flag for RemoveHs()

### ISSUE THREAD

**Issue by shayakhmetov** [rdkit/rdkit#2848]
RemoveHs() does not delete some hydrogens that are important for stereochemistry https://github.com/rdkit/rdkit/issues/2422.
This is inconvenient to use, as the majority of users would expect that **all** hydrogens will be removed.

I propose to add at least a parameter `remove_stereochemisty=False`, which will remove **all** hydrogens if it is True. Otherwise, to remove all hydrogens, one must call `Chem.RemoveStereochemistry(mol)` before calling `RemoveHs(mol)`

**Comment by greglandrum** [comment]
Agreed that we should do something here. Perhaps a better option is to include a `forceRemoval` option which causes all Hs to be removed (i.e. one which ignores all the current exceptions on H removal).
