### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [rdkit/rdkit#2857]
Greetings rdkit developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by bp-kelley** [comment]
@greglandrum I'm all for this!  The results should be very interesting...

**Comment by greglandrum** [comment]
@bp-kelley I cmpletely agree

**Comment by greglandrum** [comment]
Ok. I read through a bunch of docs and I'm now at: "seems like a great idea, but I'm really not sure how we'd do it".
I guess we could create structure-aware fuzzers (https://github.com/google/fuzzing/blob/master/docs/structure-aware-fuzzing.md) that target the parsers or to build molecules/queries to target the substructure matcher (or other pieces of code), but at the moment it seems like a daunting amount of work.

**Comment by bp-kelley** [comment]
I have a *long* time for break that I was going to do some RDKit specific
stuff.  I can start looking at this as well.

**Comment by Google-Autofuzz** [comment]
We can help you initiate the integration to OSS-Fuzz. We just need an **email address** that you want the bugs to be reported to. After this initial integration, you can add more fuzzers when you have the time. @greglandrum @bp-kelley

**Comment by greglandrum** [comment]
@Google-Autofuzz : That's awesome. Probably easiest to start this by just sending them to me: greg.landrum at gmail dot com

**Comment by greglandrum** [comment]
@Google-Autofuzz : do you need any additional info from me here?

**Comment by Google-Autofuzz** [comment]
> @Google-Autofuzz : do you need any additional info from me here?

Been upstreaming another project. If you have time, you can start it too. Thanks.

**Comment by Google-Autofuzz** [comment]
I am trying to install rdkit through a Docker but I am getting some issues. 

My build.sh file:
```
# build project
cd rdkit
mkdir -p build && cd build
cmake -DRDK_BUILD_PYTHON_WRAPPERS=OFF ..
make
make install
```

The following is the error:
```
+ cd rdkit
+ mkdir -p build
+ cd build
+ cmake -DRDK_BUILD_PYTHON_WRAPPERS=OFF ..
-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is Clang 10.0.0
-- Check for working C compiler: /usr/local/bin/clang
-- Check for working C compiler: /usr/local/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/clang++
-- Check for working CXX compiler: /usr/local/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (install):
  install FILES given no DESTINATION!


CMake Error at CMakeLists.txt:16 (add_pytest):
  Unknown CMake command "add_pytest".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/src/rdkit/rdkit/build/CMakeFiles/CMakeOutput.log".
Fuzzers build failed.
```

**Comment by greglandrum** [comment]
Perhaps as a useful pattern, here’s a Dockerfile for a relatively minimal container that does a python build: https://github.com/rdkit/rdkit_containers/blob/master/docker/ubuntu_bionic/Dockerfile

**Comment by Google-Autofuzz** [comment]
As what you suggested, I used the Dockerfile you given as a guide and failed when it tried to install rdkit around 66%. Here is the error:

````
In file included from /src/rdkit/Code/RDGeneral/Dict.h:23:
/src/rdkit/Code/RDGeneral/Exceptions.h:28:12: warning: address of stack memory associated with local variable 'msg' returned [-Wreturn-stack-address]
    return msg.c_str();
           ^~~
/src/rdkit/Code/RDGeneral/Exceptions.h:66:12: warning: address of stack memory associated with local variable 'msg' returned [-Wreturn-stack-address]
    return msg.c_str();
           ^~~
2 warnings generated.
2 warnings generated.
2 warnings generated.
[ 66%] Linking CXX static library libRDKitChemReactions_static.a
[ 66%] Built target ChemReactions_static
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c make -j3 .. install' returned a non-zero code: 2
docker build failed.
````

**Comment by greglandrum** [comment]
hmmm, that unfortunately doesn't go back far enough to show the actual error.

**Comment by greglandrum** [comment]
FWIW I just did a full build of that container without problems including `--build-arg RDKIT_BRANCH=master`

**Comment by Google-Autofuzz** [comment]
After make install rdkit, do you know what the static library called or how I get the static library? I am trying to compile fuzz targets with rdkit static library, as shown below. I need to know the `/path/to/library.a` in this. 

````
$CXX $CXXFLAGS -std=c++11 -Iinclude \
     /path/to/name_of_fuzzer.cc -o $OUT/name_of_fuzzer \
     $LIB_FUZZING_ENGINE /path/to/library.a
````

**Comment by greglandrum** [comment]
The static libs are all in the $RDBASE/lib directory. The best bet to figure out which ones to use and in which order is to do VERBOSE=1 before making one of the tests

**Comment by Google-Autofuzz** [comment]
I am getting the following error: 
```
../../lib/libRDKitmaeparser.so.1.2020.09.1dev1: undefined reference to `boost::iostreams::zlib::default_compression'
```
Apparently, it can't find boost. I did ```apt install libboost-all-dev``` and ```cmake -DBOOST_ROOT=/usr/include/boost .. ``` in my build file. Is this the right way to cmake with indication of the boost library. Thank you.

**Comment by greglandrum** [comment]
It looks like it found boost, but it may be that you also need to link against zlib

**Comment by intrigus-lgtm** [comment]
I'm trying to work on this :)

@Google-Autofuzz fuzz targets should **not** have dependencies on shared libraries, right?

**Comment by Google-Autofuzz** [comment]
@intrigus-lgtm Yes, the fuzz targets should link to static libraries. 

I started the integration and running into some linking errors. You can take a look and see if you want to pick up from where I left off. Here is the my repo link: https://github.com/Google-Autofuzz/oss-fuzz/tree/add_rdkit/projects/rdkit

**Comment by intrigus-lgtm** [comment]
I'm currently not having any linking errors.
I'm building it like this:
````
FROM gcr.io/oss-fuzz-base/base-builder
RUN apt-get update && apt-get install -y make wget cmake \
  libeigen3-dev python3 libpython3-all-dev \
  zlib1g-dev \
  libbz2-dev

# We're building `rdkit` using clang, but the boost package is built using gcc.
# For whatever reason, linking would fail.
# (Mismatch between libstdc++ and libc++ maybe?)
# It works if we build `rdkit` using gcc or build boost using clang instead.
# We've opted for building boost using clang.
RUN printenv CXXFLAGS
RUN wget https://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2
RUN tar --bzip2 -xf boost_1_58_0.tar.bz2
WORKDIR boost_1_58_0
RUN ./bootstrap.sh --with-toolset=clang --with-libraries=serialization,system,iostreams,regex
RUN ./b2 toolset=clang cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" install
WORKDIR ..

ENV RDBASE=rdkit
RUN git clone https://github.com/rdkit/rdkit.git $RDBASE
#ADD rdkit $RDBASE
WORKDIR $RDBASE
COPY build.sh $SRC/
````

Now the only problem I have is that somehow when building the fuzz targets (using cmake) it still dynamically links to shared boost libraries...
But I'll figure that out and I'll try to do an "ideal integration" :)
My very simple `RDKit::SmilesToMol(fuzzString)` already found crashes.

**Comment by Google-Autofuzz** [comment]
I am happy to hear that you are also working on this. When I said I have linking problems, I meant the part when I tried to link my fuzz targets to the **_./Code/GraphMol/FileParsers/libRDKitFileParsers_static.a_** library. After you figure it out or finish the integration, you can go ahead and upstream your version to OSS-Fuzz. Want to get RdKit usptream to OSS-Fuzz soon. Thanks :)
