### ISSUE TITLE
Provide some error message when failing to parse CXSMILES data

### ISSUE THREAD

**Issue by i-tub** [rdkit/rdkit#2878]
I'm using RDKit Version: 2019.09.2 on Linux.

Chem.MolFromSmiles returns None when there is a syntax error. That's all well and good. When the syntax error is in the SMILES itself, error messages are printed, too:

```
print(Chem.MolFromSmiles('X'))
[11:16:36] SMILES Parse Error: syntax error while parsing: X
[11:16:36] SMILES Parse Error: Failed parsing SMILES 'X' for input: 'X'
None
```

but when the input is a CXSMILES and the error is in the CXSMILES extension, the function silently returns None:

```
print(Chem.MolFromSmiles('O |bad stuff'))
None
```

Would it be possible to provide some information about what went wrong with the parsing of the CXSMILES? Or at least some way for the caller to tell whether the issue was with the SMILES as opposed to the CXSMILES extension?

**Comment by greglandrum** [comment]
@i-tub : I think #2880 addresses this: I added a new SMILES parsing parameter which causes errors in parsing CXSMILES to be ignored (instead of leading to an empty molecule).

This doesn't improve the quality of the error information provided (that's more difficult), but I think it shold help address the underlying problem.

Look reasonable?

**Comment by i-tub** [comment]
@greglandrum , that helps, thank you. I thought of splitting the string and calling MolFromSmiles again, but now I won't have to do that. :-)

**Comment by greglandrum** [comment]
@i-tub : well, it will be a while until that's in a released version of the RDKit....

**Comment by danielmanu93** [comment]
Hi I'm having similar issue. I'm trying to generate molecules from smiles with the attached generate function but I get the "SMILES parse error" in the terminal when I call the function. How can I fix this issue?
![1](https://user-images.githubusercontent.com/67971334/121929139-1fab1f80-ccfe-11eb-94d8-e32aa482b956.jpeg)

![2](https://user-images.githubusercontent.com/67971334/121929155-22a61000-ccfe-11eb-94f3-64055bdf9343.jpeg)

**Comment by greglandrum** [comment]
@danielmanu93 : this isn't a similar issue. If you look at the strings which are being displayed it's pretty clear that those are not SMILES. So they generate syntax errors.
It looks like you're trying to read text directly from a pickle file, which is never going to work. Normally one uses python's `pickle` module to read from those.
