### ISSUE TITLE
Bug in UFF Geometry Optimization with unrecognized atom types (Se2+2)

### ISSUE THREAD

**Issue by AustinT** [rdkit/rdkit#2892]
**Configuration:**

- RDKit Version: **2019.09.2**
- Operating system: **Ubuntu Linux 18.04**
- Python version (if relevant): **3.7.5**
- Are you using conda? **Yes**
- If you are using conda, which channel did you install the rdkit from? **rdkit**

**Description:**

I am trying to do geometry optimization (GO) for some selenium-containing organic compounds.
The Se is sp2 hybridized, which UFF doesn't have parameters for.
I have read on other threads (#200) that in this case it should fall back on "more relaxed defaults",
however I've found that it often ends up producing unrealistic geometries with ridiculous bond lengths (even when the GO runs for many iterations and returns `0`).

I'm working with rather large molecules, and this bug only occurs sometimes (due to the randomness of configuration generation), so instead I've written a script (_see below_) that distorts simple molecules in a way similar to the GO results I've observed.

Specifically, I take furan (https://en.wikipedia.org/wiki/Furan) and selenophene (https://en.wikipedia.org/wiki/Selenophene), which are analogous sp2 hybridized aromatic molecules. The only difference is the type of heteroatom (Se vs O). UFF has all parameters for furan but not for selenophene. The script moves the heteroatom progressively farther outside of the ring, and records the change in energies. These are before/after pics (for furan; selenophene looks analogous):

_Before distortion_ (should be low energy):
![Screenshot from 2020-01-22 10-44-35](https://user-images.githubusercontent.com/22754579/72887971-9956fd80-3d04-11ea-8f63-ec9e57fdb189.png)

_After distortion_ (high energy):
![Screenshot from 2020-01-22 10-44-57](https://user-images.githubusercontent.com/22754579/72887984-a07e0b80-3d04-11ea-82e4-70bcf9381d48.png)

(the script also saves these as `.mol` files for you to visualize if you want)

_The results of this code are that:_

- furan behaves as expected, with the energy in the second image being much higher than the first.
- selenophene shows almost **no energy difference** between the 2 configurations shown, which is very unphysical. This is similar to the observation by @JLVarjo in #200 where the potential gradients are approximately 0 for the improperly parametrized atom.
- if I manually change the hybridization of the Se atom to sp3 (which UFF has parameters for), then the Se atom behaves similar to oxygen. This suggests that the GO isn't falling back on Se3+2 geometry when the hybridization is not manually changed.

I think this is a bug, similar to #200, and that the fallback behaviour for unrecognized atoms should be different. @greglandrum can you comment on this?

**My code**
```python
from rdkit import Chem
from rdkit.Chem import AllChem


def get_uff_energy(mol, confId):
    return AllChem.UFFGetMoleculeForceField(mol, confId=confId).CalcEnergy()


def stretch_5ring_heteroatom(mol, mol_name):
    """
    Function to distort the ring and get the energies from the distortion
    """

    # Track the energies
    energy_dict = dict()

    # Embed the molecule and export embedding
    AllChem.EmbedMolecule(mol)
    Chem.MolToMolFile(mol, f"{mol_name}_E0_reference.mol")
    energy_dict['E0'] = get_uff_energy(mol, 0)

    # Calculate the vector displacement to move the 5th atom out
    #######################################
    print(f"Atom type being displaced: {mol.GetAtomWithIdx(4).GetSymbol()}")
    conf = mol.GetConformer(0)
    atom_positions = conf.GetPositions().copy()  # Just to prevent modification

    # Average the positions of atoms 1-2 to get the vector position on
    # the ring across from the heteroatom
    # (details not important, just visualize the resulting molecules
    # if you are confused by this procedure)
    point_across = (atom_positions[1] + atom_positions[2]) / 2
    displacement_vec = atom_positions[4] - point_across

    # Displace the hetero atom in 2 rounds
    for alpha in [1, 2]:
        conf.SetAtomPosition(4, atom_positions[4] + alpha * displacement_vec)
        Chem.MolToMolFile(mol, f"{mol_name}_E{alpha}_displaced.mol")
        energy_dict[f"E{alpha}"] = get_uff_energy(mol, 0)

    return energy_dict

# Test with Furan (which should show heavy response to displacement)
furan = Chem.AddHs(Chem.MolFromSmiles("c1ccco1"))
print(f"Furan Energies: {stretch_5ring_heteroatom(furan, 'furan')}")
# ^^ something like:
# Furan Energies: {'E0': 36.290385123719425, 'E1': 3570.7886473008466, 'E2': 16626.470844761654}
# this is expected since its a huge stretch (see resulting mol files to check geometries)

selenophene = Chem.AddHs(Chem.MolFromSmiles("c1ccc[se]1"))
print(f"selenophene Energies: {stretch_5ring_heteroatom(selenophene, 'selenophene')}")
# ^^ throws error: UFFTYPER: Unrecognized atom type: Se2+2 (4)
# ^^ Energies DON'T CHANGE WITH DISTANCE
# {'E0': 26.92499940076006, 'E1': 26.92499940076159, 'E2': 26.92499940076264}

# Try changing the hybridization of the Se to sp3, which is in the UFF model
selenophene.GetAtomWithIdx(4).SetHybridization(
    Chem.rdchem.HybridizationType.SP3)
print(f"sp3 selenophene Energies: {stretch_5ring_heteroatom(selenophene, 'sp3-selenophene')}")
# ^^ Shows expected behaviour
# {'E0': 30.208983893823742, 'E1': 2939.3392928450435, 'E2':
# 12475.228375067853}
```

**Comment by JLVarjo** [comment]
> 
>     * selenophene shows almost **no energy difference** between the 2 configurations shown, which is very unphysical. This is similar to the observation by @JLVarjo in [Unrecognised atom type in UFF for S atom #200](https://github.com/rdkit/rdkit/issues/200) where the potential gradients are approximately 0 for the improperly parametrized atom.
> 

Just reminding that the abovementioned side-note-bug (exploded conformations with lacking UFF parameters) of #200 still remains (tested with RDKit 2024.03.6), even though that ticket was closed as the main issue was apparently fixed.
