### ISSUE TITLE
acepentalene aromaticity perception

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#2895]
**Configuration:**
```
>>> import rdkit
>>> rdkit.__version__
'2019.09.1'
```

**Description:**

Take a look at the following, which uses the SMILES from https://en.wikipedia.org/wiki/Acepentalene :
```
>>> from rdkit import Chem
>>> Chem.CanonSmiles("C1=CC2=CC=C3C2=C1C=C3")
'c1cc2ccc3ccc1-c=3-2'
```

Why is there an aromatic "c" in the fused center of the 3 5-membered rings. It's connected by non-aromatic bonds to the rest of the system.

This broke some code of mine which expects that every aromatic atom must have at least two aromatic bonds. I thought that all aromatic atoms had to be in aromatic rings, and that all aromatic rings had to have aromatic bond.

I searched for "acepentalene" and "antiaromatic" in the issue tracker and the mailing list but found nothing relevant.

I brought this up on the mailing list. Peter Shenkin further commented:

> Since the entire system is antiaromatic, why are any carbons at all shown as aromatic in the SMILES?

There was no other response to the thread, so I'm posting here for when someone has time to look into it further.

**Comment by greglandrum** [comment]
Sorry I didn't manage to get to this on the mailing list. I agree that what's currently happening is definitely not right.

**Comment by greglandrum** [comment]
I didn't understand the discussion about antiaromaticity on the list or in the wikipedia article. That's a 10 pi electron system and, based on the way the RDKit counts electrons, should be aromatic.

**Comment by adalke** [comment]
I've emailed Peter about your response, since he's the one who made that comment. And because I still don't know enough about aromaticity perception to provide reasonable feedback.

**Comment by greglandrum** [comment]
probably better to have the discussion on the list. I will reply there now

**Comment by gedeck** [comment]
Publication by Paul v.R. Schleyer (https://pubs.acs.org/doi/pdf/10.1021/jo980089f) demonstrates anti-aromaticity of acepentalene using ab-initio NMR shift calculations. (NICS). Abstract also mentions that acepentalene is non-planar.

**Comment by greglandrum** [comment]
Quick summary of the discussion on the list:
The key here is that there is no ring (constructed of fused rings or simple ring) in acepentalene that has 4n+2 electrons. The envelope (outer) ring has 9 electrons and the central atom shouldn't be included with this when counting electrons. This is the bit that the RDKit is getting wrong.
