### ISSUE TITLE
Dockerfile build for javascript not working

### ISSUE THREAD

**Issue by mc-robinson** [rdkit/rdkit#2902]
- RDKit Version: 2019.09.3.0
- OS: Mac
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit

ALSO: Docker version 19.03.5,

Hi, while trying to use `rdkit/Code/MinimalLib/docker/Dockerfile`, I ran into the following error around step 26/28

```
Removing intermediate container dbe2e8d54182
 ---> ca78db9b5857
Step 26/28 : RUN make -j2 RDKit_minimal &&   cp Code/MinimalLib/RDKit_minimal.* ../Code/MinimalLib/demo/
 ---> Running in 08503fd839d4
Adding directories to PATH:
PATH += /opt/emsdk
PATH += /opt/emsdk/upstream/emscripten
PATH += /opt/emsdk/node/12.9.1_64bit/bin

Setting environment variables:
EMSDK = /opt/emsdk
EM_CONFIG = /root/.emscripten
EMSDK_NODE = /opt/emsdk/node/12.9.1_64bit/bin/node

make: *** No rule to make target 'RDKit_minimal'.  Stop.
The command '/bin/bash -c -l make -j2 RDKit_minimal &&   cp Code/MinimalLib/RDKit_minimal.* ../Code/MinimalLib/demo/' returned a non-zero code: 2
```

This error was preceded by many warnings regarding cmake. For example, 

```
CMake Warning (dev) at Code/cmake/Modules/RDKitUtils.cmake:47 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
```
and also,

```
CMake Warning:
  Manually-specified variables were not used by the project:

    RDK_BUILD_MINIMAL_LIB
    RDK_USE_BOOST_IOSTREAMS
```

Any help would be much appreciated.

**Comment by greglandrum** [comment]
@mc-robinson : the version of the Dockerfile that's currently on the release branch contains a mistake here:
https://github.com/rdkit/rdkit/blob/Release_2019_09/Code/MinimalLib/docker/Dockerfile#L38
it references my fork of the RDKit repository instead of the main repo.
If you replace that Dockerfile with the version that's currently on master (https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/docker/Dockerfile)
things should work.

If you want to build the wrappers corresponding to the current production version of the RDKit instead of those from master, you can invoke docker build like this:
`docker build -t minimallib --build-arg RDKIT_BRANCH=Release_2019_09 docker`

**Comment by greglandrum** [comment]
This was fixed on master in #2751

**Comment by mc-robinson** [comment]
Thanks. Got much further this time with new Dockerfile, but now ran into following error when using either `docker build -t minimallib --build-arg RDKIT_BRANCH=Release_2019_09 .` or 
`docker build -t minimallib .`

```
2020.03.1dev1
5886608
5886608
/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js:1
(function (exports, require, module, __filename, __dirname) { var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locat

RuntimeError: abort(5886608). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js:1:14816)
    at process.emit (events.js:189:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)

The command '/bin/bash -c -l nodejs tests.js' returned a non-zero code: 7
```

**Comment by greglandrum** [comment]
I just managed to get to this today and can reproduce the problem.
That's just a test failing and shouldn't impact the function of the library.
I'll look into it in order to see if I can figure out what's causing this particular problem.

**Comment by greglandrum** [comment]
I believe this is now resolved.
