### ISSUE TITLE
Platform-dependant differences in MCS output in Java

### ISSUE THREAD

**Issue by sroughley** [rdkit/rdkit#2905]
**Configurations:**
_Windows_ 10 v1909
KNIME 3.7.2
org.rdkit.knime.types_4.0.0.v201911280715
org.rdkit.knime.bin.win32.x86_64_4.0.0.v201911060821

_Ubuntu_ 18_04
KNIME 4.1.0
org.rdkit.knime.types_4.0.0.v201911280715
org.rdkit.knime.bin.linux.x86_64_4.0.0.v201911060821

**Description:**

When finding MCS of structures using the `RDKit MCS` node, the results are different between Windows and Linux.  (This is not a problem specific to the node, I have confirmed the same behaviour when using my own code calling the MCS code, but this is a simple way to demonstrate it)

For example, the following two input SMILES structures:
```
C1CCCCN1CCCN
C1C=CCCN1CCCN
```
with the following settings in the `RDKit MCS` node:
```
Threshold: 1.0
Ring matches ring only: false
Complete rings only: true
Match valences: false
Atom comparison: Compare Any
Bond comparison: Compare Any
Timeout: 300s
```
gives:

_Windows_:   `[#7]-&!@[#6]-&!@[#6]-&!@[#6]-&!@[#7]` (5 atoms, 4 bonds)
_Ubuntu_:   `[#6]1-&@[#6]-,=;@[#6]-&@[#6]-&@[#6]-&@[#7]-&@1-&!@[#6]-&@[#6]-&@[#6]-&!@[#7]` (10 atoms, 10 bonds)

Changing he settings to
```
Complete rings only: false
```
gives: 
_Windows_:   `[#6](-[#6]-[#6])-[#7](-[#6]-[#6])-[#6]-[#6]-[#6]-[#7]` (10 atoms, 9 bonds)
_Ubuntu_:   `[#6]1-[#6]-,=[#6]-[#6]-[#6]-[#7]-1-[#6]-[#6]-[#6]-[#7]` (10 atoms, 10 bonds)

I'm not sure exactly what I think the correct output should be in either case(!), but clearly it should be the same on both Windows and Linux platforms.

Steve

**Comment by ptosco** [comment]
@sroughley Hi Steve, thanks for the report, I'll have a look over the weekend and let you know.

**Comment by ptosco** [comment]
@sroughley I couldn't reproduce this in a Jupyter notebook running on the current RDKit `master` GitHub branch.
On both Linux and Windows I get 10 atoms and 10 bonds, as expected:
https://gist.github.com/ptosco/f33f00eb4792f3d7e9e39463b758da69

Also compiling a small Java test program on both Linux and Windows I get identical results:
```
import org.RDKit.ROMol;
import org.RDKit.ROMol_Vect;
import org.RDKit.RWMol;
import org.RDKit.RDKFuncs;
import org.RDKit.RDKFuncsJNI;
import org.RDKit.AtomComparator;
import org.RDKit.BondComparator;
import org.RDKit.MCSResult;

class FMCSPlatformDep {
    public static void main(String args[]){
        System.loadLibrary("GraphMolWrap");
        ROMol m1 = RWMol.MolFromSmiles("C1CCCCN1CCCN");
        ROMol m2 = RWMol.MolFromSmiles("C1C=CCCN1CCCN");
        ROMol_Vect mols = new ROMol_Vect();
        mols.add(m1);
        mols.add(m2);
        boolean maximizeBonds = true;
        double threshold = 1.0;
        long timeout = 300;
        boolean verbose = false;
        boolean matchValences = true;
        boolean ringMatchesRingOnly = false;
        boolean completeRingsOnly = true;
        boolean matchChiralTag = false;
        AtomComparator atomComp = AtomComparator.AtomCompareAnyHeavyAtom;
        BondComparator bondComp = BondComparator.BondCompareAny;
        MCSResult mcs = RDKFuncs.findMCS(mols, maximizeBonds, threshold, timeout,
            verbose, matchValences, ringMatchesRingOnly, completeRingsOnly,
            matchChiralTag, atomComp, bondComp);
        System.out.println("1) mcs.numAtoms " + mcs.getNumAtoms());
        System.out.println("1) mcs.numBonds " + mcs.getNumBonds());
        System.out.println("1) mcs.smartsString " + mcs.getSmartsString());
        ringMatchesRingOnly = true;
        mcs = RDKFuncs.findMCS(mols, maximizeBonds, threshold, timeout,
            verbose, matchValences, ringMatchesRingOnly, completeRingsOnly,
            matchChiralTag, atomComp, bondComp);
        System.out.println("2) mcs.numAtoms " + mcs.getNumAtoms());
        System.out.println("2) mcs.numBonds " + mcs.getNumBonds());
        System.out.println("2) mcs.smartsString " + mcs.getSmartsString());
    }
}

$ javac FMCSPlatformDep.java
$ java FMCSPlatformDep
1) mcs.numAtoms 10
1) mcs.numBonds 10
1) mcs.smartsString [#6]1-&@[#6]-,=;@[#6]-&@[#6]-&@[#6]-&@[#7]-&@1-&!@[#6]-&!@[#6]-&!@[#6]-&!@[#7]
2) mcs.numAtoms 10
2) mcs.numBonds 10
2) mcs.smartsString [#6&R]1-&@[#6&R]-,=;@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#7&R]-&@1-&!@[#6&!R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#7&!R]
```

**Comment by sroughley** [comment]
@ptosco Thanks for this.  I've been able to reproduce on several different machines with fresh KNIME installs, so that's quite strange.  Did you build the Java wrappers yourself, or did you lift them out of a KNIME install?  I'm wondering whether there is something slightly broken with the KNIME RDKit release  at the source of this.

**Comment by ptosco** [comment]
@sroughley I built them out of the RDKit `master` branch. Later today I will try and have a look at KNIME.

**Comment by ptosco** [comment]
@sroughley I can reproduce this lifting the jar from a Windows KNIME build:
```
> set CLASSPATH=c:\Program Files\KNIME\plugins\org.rdkit.knime.types_4.0.0.v201911280715\lib\org.RDKit.jar;.
> set PATH=c:\Program Files\KNIME\plugins\org.rdkit.knime.bin.win32.x86_64_4.0.0.v201911060821\os\win32\x86_64;%PATH%
> javac.exe FMCSPlatformDep.java
> java FMCSPlatformDep
1) mcs.numAtoms 5
1) mcs.numBonds 4
1) mcs.smartsString [#7]-&!@[#6]-&!@[#6]-&!@[#6]-&!@[#7]
2) mcs.numAtoms 5
2) mcs.numBonds 4
2) mcs.smartsString [#7&R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#7&!R]
```
Later I'll investigate further.

**Comment by greglandrum** [comment]
uh oh

**Comment by sroughley** [comment]
Well, 'uh oh' but also phew (sort of)

**Comment by ptosco** [comment]
I'll try and get to the bottom of this tonight.

**Comment by ptosco** [comment]
Linux, `org.rdkit.knime.bin.linux.x86_64_4.0.0.v201911060821`:
```
rdkitVersion: 2019.09.1
1) mcs.numAtoms 10
1) mcs.numBonds 10
1) mcs.smartsString [#6]1-&@[#6]-,=;@[#6]-&@[#6]-&@[#6]-&@[#7]-&@1-&!@[#6]-&!@[#6]-&!@[#6]-&!@[#7]
2) mcs.numAtoms 10
2) mcs.numBonds 10
2) mcs.smartsString [#6&R]1-&@[#6&R]-,=;@[#6&R]-&@[#6&R]-&@[#6&R]-&@[#7&R]-&@1-&!@[#6&!R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#7&!R]
```

Windows, org.rdkit.knime.bin.win32.x86_64_4.0.0.v201911060821:
```
rdkitVersion: 2019.09.1b1
1) mcs.numAtoms 5
1) mcs.numBonds 4
1) mcs.smartsString [#7]-&!@[#6]-&!@[#6]-&!@[#6]-&!@[#7]
2) mcs.numAtoms 5
2) mcs.numBonds 4
2) mcs.smartsString [#7&R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#6&!R]-&!@[#7&!R]
```

Looks like the Windows build is based on a beta of release `2019.09.1`.

**Comment by greglandrum** [comment]
huh, sure enough

**Comment by sroughley** [comment]
Thanks @ptosco - I'm glad at least that I'm not either totally losing the plot or managing to consistently create wierd KNIME installations.

**Comment by greglandrum** [comment]
nope, that would be me

**Comment by sroughley** [comment]
Hi @greglandrum  - is there any plan to fix this on the KNIME build? (Do I need to create a new issue on rdkit/knime-rdkit?)

**Comment by greglandrum** [comment]
aiee... slipped off my radar again.
I'll do an up-to-date build of the binaries tomorrow morning and push them to master
