### ISSUE TITLE
Comments about the new tautomer canonicalization

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2908]
Please read the blog post for more information: https://rdkit.blogspot.com/2020/01/trying-out-new-tautomer.html

Here's the corresponding jupyter notebook: https://github.com/greglandrum/rdkit_blog/blob/master/notebooks/Trying%20the%20Tautomer%20Canonicalization.ipynb

**Comment by jhjensen2** [comment]
m = Chem.MolFromSmiles('O=C(C1=C[NH+]=CC=C1)[O-]')
tauts = enumerator.Enumerate(m)

gives

KekulizeException: Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7

**Comment by jhjensen2** [comment]
Starting with C=C1CSC2=C(N=C(O)C(N)C3C=CC(=O)C=C3)C(O)N2C1=C(O)O doesn't recover the "canonical" tautomer O=C2N1/C(=C(\CS[C@@H]1[C@@H]2NC(=O)[C@@H](c3ccc(O)cc3)N)C)C(=O)O (https://en.wikipedia.org/wiki/Cefadroxil).

Not sure if that's right or wrong, but it struck me as odd

**Comment by greglandrum** [comment]
> Starting with `C=C1CSC2=C(N=C(O)C(N)C3C=CC(=O)C=C3)C(O)N2C1=C(O)O` doesn't recover the "canonical" tautomer `O=C2N1/C(=C(\CS[C@@H]1[C@@H]2NC(=O)[C@@H](c3ccc(O)cc3)N)C)C(=O)O` (https://en.wikipedia.org/wiki/Cefadroxil).

@jhjensen2 : I don't understand this one.
This bit of code:
```
m1 = Chem.MolFromSmiles('C=C1CSC2=C(N=C(O)C(N)C3C=CC(=O)C=C3)C(O)N2C1=C(O)O')
m2 = Chem.MolFromSmiles(r'O=C2N1/C(=C(\CS[C@@H]1[C@@H]2NC(=O)[C@@H](c3ccc(O)cc3)N)C)C(=O)O')
cm1 = enumerator.Canonicalize(m1)
cm2 = enumerator.Canonicalize(m2)
print(Chem.MolToSmiles(cm1)==Chem.MolToSmiles(cm2))
```
prints `True`: the two molecules produce the same canonical tautomer.
What are you seeing that's wrong there?

**Comment by greglandrum** [comment]
> m = Chem.MolFromSmiles('O=C(C1=C[NH+]=CC=C1)[O-]')
> tauts = enumerator.Enumerate(m)
> 
> gives
> 
> KekulizeException: Can't kekulize mol. Unkekulized atoms: 3 4 5 6 7

Yep, I will look into this one.

**Comment by jhjensen2** [comment]
> > Starting with `C=C1CSC2=C(N=C(O)C(N)C3C=CC(=O)C=C3)C(O)N2C1=C(O)O` doesn't recover the "canonical" tautomer `O=C2N1/C(=C(\CS[C@@H]1[C@@H]2NC(=O)[C@@H](c3ccc(O)cc3)N)C)C(=O)O` (https://en.wikipedia.org/wiki/Cefadroxil).
> 
> @jhjensen2 : I don't understand this one.
> This bit of code:
> 
> ```
> m1 = Chem.MolFromSmiles('C=C1CSC2=C(N=C(O)C(N)C3C=CC(=O)C=C3)C(O)N2C1=C(O)O')
> m2 = Chem.MolFromSmiles(r'O=C2N1/C(=C(\CS[C@@H]1[C@@H]2NC(=O)[C@@H](c3ccc(O)cc3)N)C)C(=O)O')
> cm1 = enumerator.Canonicalize(m1)
> cm2 = enumerator.Canonicalize(m2)
> print(Chem.MolToSmiles(cm1)==Chem.MolToSmiles(cm2))
> ```
> 
> prints `True`: the two molecules produce the same canonical tautomer.
> What are you seeing that's wrong there?

Sorry, my bad. I checked visually using MolToGridImage and didn't notice that it only displayed the first 50 out of 410 tautomers.

**Comment by greglandrum** [comment]
@mcs07: I have a question for you about @jhjensen2's failing example.

Here's the example molecule with atom ids (indexed from 1):
![image](https://user-images.githubusercontent.com/540511/73820752-b73b5c80-47f2-11ea-93e5-61ae597daa0c.png)
This fails with a kekulization failure in RDKit master and with MolVS 0.1.1. Here's the molvs failure:
```
In [6]: molvs.enumerate_tautomers_smiles('O=C(C1=C[NH+]=CC=C1)[O-]')                                     
[08:34:04] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7

[08:34:04] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7

[08:34:04] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7

Out[6]: {'O=C([O-])c1ccc[nH+]c1'}
```
This is happening as the 1,5 aromatic heteroatom H shift transformation is applied: `[#7,#16,#8;!H0]-[#6,#7]=[#6]-[#6,#7]=[#7,#16,#8;H0]`. The problem, which is easy to fix, is that the aromaticity flags on atoms and bonds need to be removed on potential tautomers before they are sanitized.

However, once I've fixed that I get the following tautomers for Jan's molecule:
![image](https://user-images.githubusercontent.com/540511/73821073-68da8d80-47f3-11ea-8432-ebbca9a1c69d.png)
The first of those (which is the canonical one) looks reasonable, but I don't particularly like the others with the `C=[N+]=C` moiety. But I don't think I actually understand tautomerism, so I'm wondering if producing this seems sensible to you. Otherwise I'm sure we can tweak the rule to not produce these tautomers.

**Comment by sroughley** [comment]
From the blog post:

```
Draw.MolsToGridImage(reorderTautomers(Chem.MolFromSmiles('CN=c1nc[nH]cc1')))
```

The preference for the exocyclic imino tautomer `CN=C1C=CNC=N1` does make my chemist eyes burn somewhat.  A 'quick' look in the reference supplied in one of the comments to the post (https://figshare.com/articles/The_Prediction_of_Tautomer_Preference_in_Aqueous_Solution_Version_1_0_/8966276/1) - pg 517  or pdf page no 529:

> Aromatisation leads, in almost al l cases, to an overwhelming predominance of the endo- imine (exo-amino) st ructure, as seen for 1066 and (1088, Z = S) above

would seem to concur that the amino-aromatic (`CNC1=CC=CC=N1`) tautomer is preferred.  I know preferred != canonical, but that one seems to be an obvious chemist-eye-burner

Steve

**Comment by greglandrum** [comment]
@sroughley : making it possible to see the scores is a good idea. I will try to get that in.
In the meantime, here are the scores for the tautomers of the aminopyrimidine and aminopyridine:
```
aminopyrimidine
  CN=c1cc[nH]cn1 102
  CN=c1ccnc[nH]1 102
  CNc1ccncn1 101

aminopyridine
  CN=c1cccc[nH]1 102
  CNc1ccccn1 101
```

Notice that all the rings are aromatic, so there's no difference in score due to that. The minor difference comes down to fact that the preferred form gets an extra point because of the `[#6]=[#7]` bond.
I'm going to explore making that particular SMARTS pattern `[C]=[!#1;!#6]` and adding a bonus for aromatic rings where none of the heteroatoms have Hs. Or maybe I'll add a penalty for `[a;!c;!H0]`. Let's see what those do

**Comment by greglandrum** [comment]
@sroughley A demonstration of the problem with making this change is that it shifts the preference in these two pairs from the left (current) to the right (with the new penalty)
example 1:
![image](https://user-images.githubusercontent.com/540511/74544298-30e7ee80-4f47-11ea-89e5-868ecd85e07a.png)
example 2:
![image](https://user-images.githubusercontent.com/540511/74544333-3e9d7400-4f47-11ea-8e8c-a5a06ae514fc.png)

Given that the goal here is just to get a canonical form that's reasonable, I would really rather avoid endless parameter tuning to cover every weird case. Which option burns your eyes less: the current behavior and the ugly amino-pyridines, or the proposed new behavior with the hydroxy form of 2-pyridone?

**Comment by sroughley** [comment]
Given it is only exocyclic N which prefers the NH2 what happens if you amend the rule to only favour `c=!@[!N]`.  The bottom one is an interesting case though.  Although the structure on the right looks superificially 'nicer', I'd guess that the one on the left, or indeed the other options below has a significant population (I'm not going to stick my neck out and say 'dominates', but...) due to intramolecular hydrogen-bonding...

![image](https://user-images.githubusercontent.com/8321832/74546162-0c3d4800-4f42-11ea-94f8-909e4ad5a31a.png)

It's probably in the 700 or so pages of that PDF somewhere... :-)

**Comment by greglandrum** [comment]
I can leave the bonus as is and add a penalty for '[c]=!@[N]`, which gives things like this (old preferred form left, new preferred form right):
![image](https://user-images.githubusercontent.com/540511/74548056-698ac680-4f4d-11ea-8184-e7e8a862fdc0.png)
and
![image](https://user-images.githubusercontent.com/540511/74548067-74455b80-4f4d-11ea-9bf4-025e7c2f95c5.png)

you ok with those?

**Comment by greglandrum** [comment]
@sroughley forgot to mention you in the comment above so that you'd see it

**Comment by sroughley** [comment]
Ah, I can feel the healing ointment soothing my poor eyes already :-)

Yes, that works for me (until someone shows me the hideous breakage that comes about elsewhere as a result!)

**Comment by greglandrum** [comment]
It actually didn't trigger anything that looked particularly bad in any of the tests. Most things that I had to change look like the examples that are here. I will take a look again over the weekend and do a PR

**Comment by greglandrum** [comment]
Thanks for the suggestions @sroughley !
