### ISSUE TITLE
allow PF6-

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#291]
The anion occurs often enough that it should be allowed.

**Comment by wangyingxie** [comment]
Hi Greg, why PF6-is still not working, please refer to the #5145 . Thank you!

> The anion occurs often enough that it should be allowed.

Hi Greg, why PF6-is still not working, please refer to the #5145 . Thank you!

**Comment by greglandrum** [comment]
@wangyingxie This bug, which should have been marked closed a long time ago, is about being unable to read in PF6-. That is fixed:
```
In [3]: Chem.MolToSmiles(Chem.MolFromSmiles("F[P-](F)(F)(F)(F)F"))
Out[3]: 'F[P-](F)(F)(F)(F)F'
```
