### ISSUE TITLE
How can I use rdkit with Pycharm and Anaconda?

### ISSUE THREAD

**Issue by giupardeb** [rdkit/rdkit#2914]
**Configuration:**
- RDKit Version: 2019.03.3
- Operating system: Fedora 
- Python version (if relevant): python 3.7.6
- Are you using conda? No
- If you are not using conda: how did you install the RDKit? ```sudo dnf install python3-rdkit.x86_64```

**Comment by bp-kelley** [comment]
This looks like a pycharm configuration issue:

https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html

**Comment by giupardeb** [comment]
I tried to remove ```python3-rdkit.x86_64``` and install rdkit from conda with this command: ``` conda install -c rdkit rdkit ```. Then I configured Pycharm conda interpreter, but the reference of rdkit is unresolved.

**Comment by giupardeb** [comment]
I already resolved with the following steps:

1. install conda
2. create environment conda on Pycharm
3. install rdkit in Pycharm's terminal: `conda install -c rdkit rdkit`
