### ISSUE TITLE
How to calculate the MQN descriptors in rdkit?

### ISSUE THREAD

**Issue by Lihua1990** [rdkit/rdkit#2915]
**Configuration:**

- RDKit Version: '2019.09.1'
- Operating system: Windows 10
- Python version (if relevant): Python 3.7.4
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? 
- conda install -c rdkit rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

```
Your code sample here
```
 I know it's possible to do that in knime with rdkit nodes (RDKit Descriptor Calculation), but can we do it in python using some code similar to Chem.Descriptors.TPSA(Chem.MolFromSmiles('O=C(C)Oc1ccccc1C(=O)O'))

**Comment by greglandrum** [comment]
For reasons I don't quite remember, we didn't end up making a super-simple way to get these from Python, but you can still get them using the function `rdMolDescriptors.MQN_`:
```
In [15]: from rdkit.Chem import rdMolDescriptors                                                           

In [16]: ds = rdMolDescriptors.MQNs_(m)                                                                    

In [17]: len(ds)                                                                                           
Out[17]: 42

```

**Comment by Lihua1990** [comment]
Thank you so much! It worked!

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
