### ISSUE TITLE
RDKit exceptions do not override the default `what()` method

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#2920]
Many of RDKit's exceptions don't override the standard `what()` method provided by the STL exceptions, and, instead, define a custom `message()` one (or also `index()` or `key()`) that returns the specific information about what caused the exception to be thrown.

This means that any exception handling that relies in the use of `what()` (e.g., in a "catch call" block) won't get any specific information from RDkit's exceptions. In example, a sanitization error, which raises exceptions subclassing `std::exception`, will just return a "std::exception" message (the default string that gets returned for `std::exception::what()`), which is not too useful.

Would it make sense to rename RDKit's `message()` methods to `what()`, or at least, add  a `what()` alias, in case we do not want to break current implementations?

**Comment by bp-kelley** [comment]
yes!  I've always been curious why the message isn't propagated to the
python wrappers, this may be the reason.

**Comment by ricrogz** [comment]
> yes! I've always been curious why the message isn't propagated to the python wrappers, this may be the reason.

That's exactly how I found it: investigating a "RuntimeError: std::exception" error message in Python :D

**Comment by bp-kelley** [comment]
I'll try this over the weekend and see if it works.

**Comment by greglandrum** [comment]
I’d rather not break existing code, but making what() the primary implementation and having message() call that makes a ton of sense to me
