### ISSUE TITLE
NameError: name 'BRICSDecompose' is not defined

### ISSUE THREAD

**Issue by yipy0005** [rdkit/rdkit#2922]
**Configuration:**

- RDKit Version: 2019.09.1.0
- Operating system: Mac OS Catalina
- Python version (if relevant): 3.7.6
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

I tried the code from https://www.rdkit.org/docs/source/rdkit.Chem.BRICS.html. When it came to the step: res = list(BRICSDecompose(m)), it gave: NameError: name 'BRICSDecompose' is not defined.

```
from rdkit import Chem
m = Chem.MolFromSmiles('CCCOCc1cc(c2ncccc2)ccc1')
res = list(BRICSDecompose(m))
```

**Comment by greglandrum** [comment]
That function is defined in the module rdkit.Chem.BRICS, which you need to import

**Comment by yipy0005** [comment]
Oh yah! Silly me, thanks! :D
