### ISSUE TITLE
Chem.MolFromMolFile() does not work with pathlib.PoxisPath object

### ISSUE THREAD

**Issue by khoivan88** [rdkit/rdkit#2923]
**Configuration:**

- RDKit Version: '2019.09.3'
- Operating system: CentOS 7 64-bit
- Python version (if relevant): 3.8.1
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit? N/A

**Description:**

Hi, first of all, thank you for a great program. 

I recently discovered rdkit so I might be completely wrong but I think rdkit, specifically `Chem.MolFromMolFile()` cannot work with `pathlib.Path` object. 

Specifically, this following code does not work: 

```python
from rdkit import Chem
from molvs import Standardizer
from pathlib import Path

def standardize_mol(mol_file):
    mol = Chem.MolFromMolFile(mol_file)

    s = Standardizer()
    smol = s.standardize(mol)

    with open(mol_file, 'w') as f:
        f.write(Chem.MolToMolBlock(smol))

if __name__ == '__main__':   
    mol_file = Path('/home/khoi/programs_for_OE/update_sql_mol/update_sql_mol_v7') / '159857-81-5.mol'
    standardize_mol(mol_file=mol_file)
```
It gives the following error on my system:
```bash
Traceback (most recent call last):
  File "standardize_mol.py", line 24, in <module>
    standardize_mol(mol_file=mol_file)
  File "standardize_mol.py", line 6, in standardize_mol
    mol = Chem.MolFromMolFile(mol_file)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolfiles.MolFromMolFile(PosixPath)
did not match C++ signature:
    MolFromMolFile(char const* molFileName, bool sanitize=True, bool removeHs=True, bool strictParsing=True)
    MolFromMolFile(char const* molFileName, bool sanitize=True, bool removeHs=True, bool strictParsing=True)
```
</br></br>
However, the following versions work fine:
```python
...
if __name__ == '__main__':
    mol_file = Path('/home/khoi/programs_for_OE/update_sql_mol/update_sql_mol_v7') / '159857-81-5.mol'
    standardize_mol(mol_file=str(mol_file))
```
or 
```python
...
if __name__ == '__main__':
    import os
    mol_file = os.path.join('/home/khoi/programs_for_OE/update_sql_mol/update_sql_mol_v7', '159857-81-5.mol')
    standardize_mol(mol_file=mol_file)
```
That is the reason why I think that `Chem.MolFromMolFile()` does not work with `pathlib.PoxisPath object`. I just want  to let you know the issue.
Thank you!

**Comment by ptosco** [comment]
@khoivan88 The fact is that `mol_file` is a `pathlib.PosixPath` object, whereas `Chem.MolFromMolFile` expects a string-like object. if you pass `mol_file.as_posix()` to `Chem.MolFromMolFile` it will work fine, just as it does when you call its `__str__` method.

**Comment by greglandrum** [comment]
@khoivan88, @ptosco is completely right here: we don't currently support this because we expect a string to be provided to the functions.

We could change this though, and support anything that has an `__str__()` method (like the `PosixPath`). I think this is pretty easy, and it would make things more "pythonic", so I'm going to look into it.

**Comment by khoivan88** [comment]
hi Drs. @greglandrum and @ptosco , Thank you for confirming that. I was just caught off guard by the error message when my test code (simply passing string) worked by then got error message when plugged into a bigger program with `mol_file` was passed in as a `PoxisPath` object.

On a side note, I was just trying to have a small function of converting explicit hydrogens into implicit hydrogens for my bigger program (python3) (searching for mol file and then upload into our chemical inventory system). I was hoping that all of the libraries could be install with pip for easy usage for non technical people (instead of having to install conda and then rdkit and molvs) for my program. Do you know of any such library to convert explicit hydrogens to implicit hydrogen with easy installation (pip)? or that is just a lot of work?

Again, thank you very much for your help and for writing this extremely useful library!

**Comment by greglandrum** [comment]
@khoivan88 : you can probably do this with openbabel, which I'm pretty sure you can do "pip install" for.

**Comment by khoivan88** [comment]
Dr. @greglandrum, I tried with openbabel and I had issue with it too. It could be because I am new to this field but openbabel has to be installed onto the system before i can install the python-openbabel library for python. Also, with the newest openbabel (3.0), I have to compile from source (instead of `yum install openbabel` for CentOS). And even after having successfully compiled and installed, I had trouble installing the python openbabel lirary in virtual environment created with venv.
For now, I think I will just have to include instruction for installing conda and use conda to install rdkit. Thank you very much for your help!

**Comment by greglandrum** [comment]
@khoivan88 : I don't use openbabel, so I can't help you there.
The RDKit is really super easy to use from conda and we really suggest people use that. There are many good reasons to use conda aside from it being easy to use the RDKit!

There's some more text about why the RDKit isn't available via pip here: http://rdkit.blogspot.com/2019/11/why-rdkit-isnt-available-on-pypi.html

**Comment by jaimergp** [comment]
@greglandrum any progress on this? We can help if needed!
