### ISSUE TITLE
A problem in calculating molecular descriptor 'PBF' with rdMolDescriptors

### ISSUE THREAD

**Issue by ZihaoWang1995** [rdkit/rdkit#2924]
**Configuration:**

- RDKit Version: 2019.09.3
- Operating system: Win10
- Python version (if relevant): 3.6

**Description:**

```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdMolDescriptors

mol = Chem.MolFromSmiles('C[C@H]1CC[C@@H]([C@H](C1)C)C')
AllChem.EmbedMolecule(mol)
print(rdMolDescriptors.CalcFractionCSP3(mol))
print(rdMolDescriptors.CalcPBF(mol))
```
> **Error line**: print(rdMolDescriptors.CalcPBF(mol))

```
RuntimeError: Pre-condition Violation
	molecule has no conformers
	Violation occurred on line 132 in file Code\GraphMol\Descriptors\PBF.cpp
	Failed Expression: mol.getNumConformers() >= 1
	RDKIT: 2019.09.3
	BOOST: 1_67
```

It seems that there is no 3D information in RDKit in regard of this molecule.

Download the SDF information from PubChem and load it into the program could be a feasible way. However, in this way, I need to program the calculation algorithm of this descriptor accoring to the published paper.

Is there a simpler way to solve this problem?
Many thanks in advance.

**Comment by greglandrum** [comment]
@ZihaoWang1995 : it's important to look at the return value from `AllChem.EmbedMolecule()`. It returns the ID of the conformation that was added to the molecule, or -1 if the embedding fails.
In your case the embedding fails.

It is almost always a very good idea to add hydrogens to a molecule before doing the embedding, as you can see for your molecule:
```
>>> mol = Chem.MolFromSmiles('C[C@H]1CC[C@@H]([C@H](C1)C)C')                                                             
>>> molh = Chem.AddHs(mol)                                                                                               
>>> AllChem.EmbedMolecule(molh)                                                                                          
0
```
You need to decide on your own if you want to remove the Hs again before calculating descriptors though:
```
>>> rdMolDescriptors.CalcPBF(molh)                                                                                       
0.6591537712941734
>>> mol = Chem.RemoveHs(molh)                                                                                            
>>> rdMolDescriptors.CalcPBF(mol)                                                                                        
0.2733927739880608
```

**Comment by ZihaoWang1995** [comment]
@greglandrum Thank you very much. It helped me a lot.

Previously, I didn't notice the output of `AllChem.EmbedMolecule()`.
Now, I have thoroughly understand the usage of embedding.

Thanks again for your detailed descriptions and examples.
