### ISSUE TITLE
Molecule image got cut off when drawn in jupyter notebook

### ISSUE THREAD

**Issue by yipy0005** [rdkit/rdkit#2930]
**Configuration:**

- RDKit Version: 2019.09.3.0
- Operating system: Windows 10
- Python version (if relevant): 3.7.6
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

I executed Draw.MolsToGridImage and the bottom of the molecule image was a little bit cut off. I tried changing the dimensions of the image but it doesn't work. What can I do to resolve this problem?

Thanks. :D

```
img=Draw.MolsToGridImage(mol_list[:],
                         molsPerRow=len(mol_list),
                         subImgSize=(450,150),
                         highlightAtomLists=[mol.GetSubstructMatch(core) for mol in mol_list],)
```

**Comment by kjelljorner** [comment]
I also get this error, for example:

```python
smiles_p_endo = "O=C1CC([C@@H]2[C@@H]3C=C[C@@H](C3)[C@@H]21)=O"
smiles_p_exo = "O=C1CC([C@H]2[C@@H]3C=C[C@@H](C3)[C@H]21)=O"
mol_p_endo = Chem.MolFromSmiles(smiles_p_endo)
mol_p_exo = Chem.MolFromSmiles(smiles_p_exo)
Chem.Draw.MolsToGridImage([mol_p_endo, mol_p_exo], legends=["Endo", "Exo"], molsPerRow=2)
```

![image](https://user-images.githubusercontent.com/36157530/136986479-79dbf941-7f95-4762-97a6-1df6df725d4f.png)
