### ISSUE TITLE
MolDraw2D: support drawing radicals

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2943]
At the moment there's no indication in the rendering that a particular atom is a radical.

The old Python renderer handles this using a unicode character: `  radicalSymbol = u'\u2219'` 
Trying to include that would be a place to start.

**Comment by eloyfelix** [comment]
I think this one got fixed here? https://github.com/rdkit/rdkit/pull/4948 We were aware of this one but it now seems to work :D 

<img width="397" alt="Screenshot 2022-11-29 at 11 38 55" src="https://user-images.githubusercontent.com/1122541/204519540-3b32ac75-1ef7-4751-8b64-8cf178103034.png">

**Comment by greglandrum** [comment]
@eloyfelix : right you are. Thanks for pointing it out
