### ISSUE TITLE
No error on incorrect valency of an aromatic atom

### ISSUE THREAD

**Issue by shayakhmetov** [rdkit/rdkit#2944]
The following molecule should be considered as invalid and the sanitization should fail with valence violation.

```Chem.MolFromSmiles('c1ccccc#1C')```

In `rdkit.__version__='2019.09.3'` `Chem.SanitizeMol` considers the molecule as valid.

**Comment by bp-kelley** [comment]
Believe it or not, this is a valid molecule that one can make and the Huckle rule says it is indeed aromatic:

cyclohexa-1,3-dien-5-yne

https://pubchem.ncbi.nlm.nih.gov/compound/135083447

**Comment by bp-kelley** [comment]
More interesting structures here:  

https://pubchem.ncbi.nlm.nih.gov//#query=Cyclohexa-1_3-dien-5-yne

**Comment by shayakhmetov** [comment]
@bp-kelley , thanks for the reference! You are referring to the 'c1ccccc#1' SMILES, which is indeed correct. My concern is that if an additional atom is appended to the last carbon, the result is 'c1ccccc#1C', which should be considered as invalid, as the valency of that carbon becomes 5.

**Comment by shayakhmetov** [comment]
What about another example with S atom 'O[SH]1=NNC=C1'. Should it be invalid also, considering S has the valency of 5?

**Comment by greglandrum** [comment]
`c1ccccc#1C` should not pass sanitization. That's a clear bug

`O[SH]1=NNC=C1` is fine: S has a valence of 5 when it's allowed to be up to 6 (e.g. `[O-]S([O-])(=O)=O`). Because you've used square brackets, the S actually has a radical on it:
```
In [6]: m = Chem.MolFromSmiles('O[SH]1=NNC=C1')                                                                               

In [7]: m.Debug()                                                                                                             
Atoms:
	0 8 O chg: 0  deg: 1 exp: 1 imp: 1 hyb: 4 arom?: 0 chi: 0
	1 16 S chg: 0  deg: 3 exp: 5 imp: 0 hyb: 3 arom?: 0 chi: 0 rad: 1
	2 7 N chg: 0  deg: 2 exp: 3 imp: 0 hyb: 3 arom?: 0 chi: 0
	3 7 N chg: 0  deg: 2 exp: 2 imp: 1 hyb: 3 arom?: 0 chi: 0
	4 6 C chg: 0  deg: 2 exp: 3 imp: 1 hyb: 3 arom?: 0 chi: 0
	5 6 C chg: 0  deg: 2 exp: 3 imp: 1 hyb: 3 arom?: 0 chi: 0
Bonds:
	0 0->1 order: 1 conj?: 0 aromatic?: 0
	1 1->2 order: 2 conj?: 1 aromatic?: 0
	2 2->3 order: 1 conj?: 1 aromatic?: 0
	3 3->4 order: 1 conj?: 1 aromatic?: 0
	4 4->5 order: 2 conj?: 1 aromatic?: 0
	5 5->1 order: 1 conj?: 0 aromatic?: 0
```
