### ISSUE TITLE
Empty molecule has non-zero LabuteASA

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#2948]
It probably doesn't matter what property values are returned for empty molecules, but it struck me as odd:

```
Chem.rdMolDescriptors.CalcLabuteASA(Chem.Mol())

1.3684777599037141
```

Seems to come from here, https://github.com/rdkit/rdkit-orig/blob/master/Code/GraphMol/Descriptors/MolSurf.cpp#L76-L78

**Comment by bp-kelley** [comment]
Hah!  That is a pretty funny result.  Good sleuthing!

**Comment by greglandrum** [comment]
Yeah, nice catch and thanks for pointing out exactly where the problem is!

**Comment by jasondbiggs** [comment]
@greglandrum thanks for the quick fix.  Our QA found this one ("A QA engineer walks into a bar ...").
