### ISSUE TITLE
rdvalue_tostring has high performance overhead

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#2951]
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: macOS 10.14.4
- Python version (if relevant): 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? conda-forge

**Description:**

In my project I record the mapping from the atom indices in the input SMILES to the atom indices in the canonical SMILES using  `s = mol.GetProp("_smilesAtomOutputOrder")`.

My profiling shows that 10% of my total run-time is spent in that call, which is pinpointed to rdvalue_tostring's use of locale:

```
339 RDKit::Dict::getValIfPresent(std::__1::basic_string ...) const
  | +   328 RDKit::rdvalue_tostring(RDKit::RDValue, std::__1::basic_string ...&)
    | +   ! 277 std::__1::basic_string... RDKit::vectToString<unsigned int>(RDKit::RDValue) 
      | +   ! : 275 std::__1::locale::locale(char const*)  (in libc++.1.dylib) + 199  [0x1067ce4c7]
```
Here is a reproducible which shows that MolFromSmiles()+MolToSmiles() takes 945 usecs while adding mol.GetProp() takes an additional 115 usecs, to 1060 usecs. That's about 12% of the parse+canonicalization time: 
```
% python -m timeit -r 10 -s 'from rdkit import Chem' 'mol = Chem.MolFromSmiles("Cl.O=C(Nc1ccc2c(c1)c1ccccc1n2CCCCN1CCN(CC=Cc2ccccc2)CC1)c1ccccc1"); Chem.MolToSmiles(mol)'
500 loops, best of 10: 945 usec per loop
% python -m timeit -r 10 -s 'from rdkit import Chem' 'mol = Chem.MolFromSmiles("Cl.O=C(Nc1ccc2c(c1)c1ccccc1n2CCCCN1CCN(CC=Cc2ccccc2)CC1)c1ccccc1"); Chem.MolToSmiles(mol); mol.GetProp("_smilesAtomOutputOrder")'
200 loops, best of 10: 1.06 msec per loop
```
A look at rdvalue_tostring() shows that it uses the RAII instance`Utils::LocaleSwitcher ls` to handle locale issues in a thread-safe, recursive way. However, locale doesn't affect RDTypeTag::VecIntTag, RDTypeTag::VecUnsignedIntTag, or several other tag types. These could be called without preserving locale.

Further, vectToString<T> sets the ostringstream() locale directly, so I don't think there's any need to preserve the thread's locale.

Lastly, a specialization for vectToString<int> and vectToString<unsigned int> could probably skip the:
```
  sstr.imbue(std::locale("C"));
  sstr << std::setprecision(17);
```
steps entirely.

**Comment by bp-kelley** [comment]
Nice analysis, Is your default locale non "C"?  This might be why I haven't seen the issue

```
 % python -m timeit -r 10 -s 'from rdkit import Chem' 'mol = Chem.MolFromSmiles("Cl.O=C(Nc1ccc2c(c1)c1ccccc1n2CCCCN1CCN(CC=Cc2ccccc2)CC1)c1ccccc1"); Chem.MolToSmiles(mol)'
500 loops, best of 10: 731 usec per loop
% python -m timeit -r 10 -s 'from rdkit import Chem' 'mol = Chem.MolFromSmiles("Cl.O=C(Nc1ccc2c(c1)c1ccccc1n2CCCCN1CCN(CC=Cc2ccccc2)CC1)c1ccccc1"); Chem.MolToSmiles(mol); mol.GetProp("_smilesAtomOutputOrder")'
500 loops, best of 10: 796 usec per loop
``` 

You might get a performance boost using GetPropsAsDict which returns an int vector

```
python -m timeit -r 10 -s 'from rdkit import Chem' 'mol = Chem.MolFromSmiles("Cl.O=C(Nc1ccc2c(c1)c1ccccc1n2CCCCN1CCN(CC=Cc2ccccc2)CC1)c1ccccc1"); Chem.MolToSmiles(mol); mol.GetPropsAsDict(True,True)["_smilesAtomOutputOrder"]'
```

Although if your molecule has a lot of junk on it this can be very slow.  I could make some think like:

```
GetPyProp(tag)
```

which will do the same thing as GetPropsAsDict but only for the specified tag.

**Comment by adalke** [comment]
```
% printenv LANG
en_US.UTF-8
```
I can try GetPropsAsDict(). Decoding the odd-ball "[1,2,3,0,]" string (odd-ball because of the terminal ",") isn't my performance bottleneck, but the internal-object->string->my function->decoded object is one of the somewhat annoying things about the API.

Personally, I would like to pass in a vector which is filled with the information, rather than the current API, which feels decidedly non-thread-safe.

**Comment by bp-kelley** [comment]
The API isn't really thread safe, we currently only have CanonOrder which is the canonical labelling but NOT the smiles output order which you probably know.

We could make a SmilesOutputOrder trivially pthread safe by making an internal copy, but this will probably be slower.  I'll have to time it.

In any case, I've removed the unnecessary locale switches here #2958, but I haven't really noticed any differences in timing on my system.  GetPropsAsDict is currently my fastest timing.
