### ISSUE TITLE
Mixed licenses, again

### ISSUE THREAD

**Issue by skearnes** [rdkit/rdkit#2956]
This is a follow-up to #1931; there at least 8 files that have licenses that don't match BSD-3-Clause. Note that mismatches like this make it hard to import rdkit into Google (presumably our detection tools have gotten better, since some of these are quite old).

* rdkit/Chem/MCS.py (BSD-2-Clause)
* rdkit/Chem/fmcs/fmcs.py (BSD-2-Clause)
* Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake (GPL-3.0)
* Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake (GPL-3.0)
* rdkit/six.py (MIT)
* Code/GraphMol/Descriptors/EEM.cpp (BSD-2-Clause)
* Code/GraphMol/Substruct/ullmann.hpp (BSL-1.0)
* Code/GraphMol/Descriptors/EEM.h (BSD-2-Clause)

Our internal workaround includes adding all of these licenses to license.txt explicitly, but it would be nice if everything was consistent or if that addendum was done here at upstream.

**Comment by skearnes** [comment]
Unfortunately the GPL licenses require me to recategorize rdkit as "restricted" internally. See https://opensource.google/docs/thirdparty/licenses/#restricted

**Comment by greglandrum** [comment]
It would indeed be worrisome if there were parts of the code that were covered by the GPL, but that is not the case here. The output from bison - which also includes the `smiles.tab.{c,h}pp.cmake` and `sln.tab.{c,h}pp.cmake` files - includes the following text just below the bit mentioning the GPL:
```
/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */
```

**Comment by greglandrum** [comment]
If you have suggestions for modifications to `license.txt` to make it more descriptive/complete, I'd be happy to take a look at merging them.

**Comment by skearnes** [comment]
Ah, thank you for reading more carefully than I did :)

**Comment by greglandrum** [comment]
yeah, there's not much as scary as hearing that there might be a GPL infection of the code. :scream:
