### ISSUE TITLE
intramolecular clashes in 2D conformation of molecule CC1CCC2C(C(=O)OC3C24C1CCC(O3)(OO4)C)C

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#2960]
**Configuration:**

- RDKit Version:
- Operating system:
- Python version (if relevant):
- Are you using conda?
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit?

**Description:**

the 2D image of the molecule (CC1CCC2C(C(=O)OC3C24C1CCC(O3)(OO4)C)C ) drawed by RDKit as below:
![图片](https://user-images.githubusercontent.com/7656130/74618854-6f132700-516e-11ea-8db8-9e5a89fa1f2b.png)

intramolecular clashes in 2D conformation of molecule.

when I paste the smiles to ChemDraw.
The image as the below:

![图片](https://user-images.githubusercontent.com/7656130/74618937-bf8a8480-516e-11ea-848a-355185f189c6.png)

The image is more clear.

```
Your code sample here
```

**Comment by greglandrum** [comment]
Hi @autodataming,
This is a good example of the RDKit doing a bad job generating coordinates in a difficult system.
There may be some easy ways to deal with this, but since you haven't provided any of the information that we ask for in order to help answer your questions, I can't tell.

**Comment by autodataming** [comment]
> 
> 
> Hi @autodataming,
> This is a good example of the RDKit doing a bad job generating coordinates in a difficult system.
> There may be some easy ways to deal with this, but since you haven't provided any of the information that we ask for in order to help answer your questions, I can't tell.

Thank you for your reply.
I thought this problem had nothing to do with the version of RDKit
I am sorry for that I am lazy and did not give relevant information.
my enviroments as the bellow:
```
    RDKit Version: 2018.03.4
    Operating system: Linux-3.10.0-327.13.1.el7.x86_64-x86_64-with-centos-7.2.1511-Core CENTOS
    Python version (if relevant): 3.5.5
    Are you using conda?  yes anaconda3
    If you are using conda, which channel did you install the rdkit from? rdkit
    If you are not using conda: how did you install the RDKit?
```
I'm run the above code in the jupyter notebook
```py
from rdkit.Chem.Draw import IPythonConsole #Needed to show molecules
Chem.MolFromSmiles('CC1CCC2C(C(=O)OC3C24C1CCC(O3)(OO4)C)C')
```

**Comment by greglandrum** [comment]
We do ask for that information for a reason. Thanks for providing it.

A first thing is that I would suggest that you update to a newer version of the RDKit if you can. That version is almost two years old at this point and is missing a lot of bug fixes (and new features).
However, even the newer versions won't do a great job on this molecule.

One solution when the RDKit does a poor job of drawing a molecule is to use the coordgen library from Schrodinger to create the coordinates. This is part of RDKit conda builds and can be enabled as the default algorithm for generating coordinates by doing:
```
from rdkit.Chem import rdDepictor
rdDepictor.SetPreferCoordGen(True)
```
You only have to do this once in a notebook and coordgen will be used from that point forward.
Coordgen does a much better job on your molecule:
![image](https://user-images.githubusercontent.com/540511/74917105-4a65bc00-53c7-11ea-95e5-06354fc31770.png)

**Comment by autodataming** [comment]
> 
> 
> We do ask for that information for a reason. Thanks for providing it.
> 
> A first thing is that I would suggest that you update to a newer version of the RDKit if you can. That version is almost two years old at this point and is missing a lot of bug fixes (and new features).
> However, even the newer versions won't do a great job on this molecule.
> 
> One solution when the RDKit does a poor job of drawing a molecule is to use the coordgen library from Schrodinger to create the coordinates. This is part of RDKit conda builds and can be enabled as the default algorithm for generating coordinates by doing:
> 
> ```
> from rdkit.Chem import rdDepictor
> rdDepictor.SetPreferCoordGen(True)
> ```
> 
> You only have to do this once in a notebook and coordgen will be used from that point forward.
> Coordgen does a much better job on your molecule:
> ![image](https://user-images.githubusercontent.com/540511/74917105-4a65bc00-53c7-11ea-95e5-06354fc31770.png)

Thank you for your help! It does a much better job on my molecule. 

If rdkit can use the coordgen library from chemdraw, the 2D image of the molecule will be more beautiful.

**Comment by autodataming** [comment]
> 
> 
> We do ask for that information for a reason. Thanks for providing it.
> 
> A first thing is that I would suggest that you update to a newer version of the RDKit if you can. That version is almost two years old at this point and is missing a lot of bug fixes (and new features).
> However, even the newer versions won't do a great job on this molecule.
> 
> One solution when the RDKit does a poor job of drawing a molecule is to use the coordgen library from Schrodinger to create the coordinates. This is part of RDKit conda builds and can be enabled as the default algorithm for generating coordinates by doing:
> 
> ```
> from rdkit.Chem import rdDepictor
> rdDepictor.SetPreferCoordGen(True)
> ```
> 
> You only have to do this once in a notebook and coordgen will be used from that point forward.
> Coordgen does a much better job on your molecule:
> ![image](https://user-images.githubusercontent.com/540511/74917105-4a65bc00-53c7-11ea-95e5-06354fc31770.png)

Thank you for your help! It does a much better job on my molecule.

**Comment by autodataming** [comment]
```py
from rdkit.Chem import rdDepictor
rdDepictor.SetPreferCoordGen(True)
Chem.MolFromSmiles('C12C3C4C1C5C2C3C45')
```
the image is confusing. 
![图片](https://user-images.githubusercontent.com/7656130/76312264-9c866700-630d-11ea-8049-9fa88e61e671.png)

when I pasted the smiles in the chemdraw, it will get a beautiful image.
![图片](https://user-images.githubusercontent.com/7656130/76312226-84aee300-630d-11ea-8854-a6d9f95e9146.png)
