### ISSUE TITLE
Same substructures may have different Morgan fingerprint bits

### ISSUE THREAD

**Issue by Minys233** [rdkit/rdkit#2961]
**Configuration:**

- RDKit Version: **2019.09.1**
- Operating system: **Ubuntu 18.04**
- Python version (if relevant): **3.7.4**
- Are you using conda? **Yes**
- If you are using conda, which channel did you install the rdkit from? **rdkit**
- If you are not using conda: how did you install the RDKit?

**Description:**

```python
from rdkit import Chem
from rdkit.Chem import AllChem
bitinfo = {}
AllChem.GetMorganFingerprintAsBitVect(Chem.MolFromSmiles(Chem.CanonSmiles('C1C2CCC3(CCO3)C12')), 2, bitInfo=bitinfo)
print(bitinfo[926])
print(80 in bitinfo)

bitinfo = {}
AllChem.GetMorganFingerprintAsBitVect(Chem.MolFromSmiles(Chem.CanonSmiles('OCCC1NC12COC2')),2, bitInfo=bitinfo)
print(bitinfo[926])
print(bitinfo[80])
```
Above code will output:
```
((0, 0), (1, 0), (3, 0), (4, 0), (6, 0))
False
((6, 0), (8, 0))
((1, 0), (2, 0))
```
However, seems bits `926` and `80` all correspond to `-CH2-` substructure. I know Morgan fingerprint has a possibility of hash collision, but shouldn't it be **different structure but same bits**? However, I got **same structures but different bits** here.

To validate this, I also plot the substructures.
```python
Draw.DrawMorganBit(Chem.MolFromSmiles(Chem.CanonSmiles('C1C2CCC3(CCO3)C12')), 926, bitinfo)
```
![image](https://user-images.githubusercontent.com/23317405/74660400-08732500-51d1-11ea-9234-9397cbd01810.png)

```python
Draw.DrawMorganBit(Chem.MolFromSmiles(Chem.CanonSmiles('OCCC1NC12COC2')), 926, bitinfo)
```
![image](https://user-images.githubusercontent.com/23317405/74660995-1d03ed00-51d2-11ea-84c2-36c664ab89a9.png)

```python
Draw.DrawMorganBit(Chem.MolFromSmiles(Chem.CanonSmiles('OCCC1NC12COC2')), 80, bitinfo)
```
![image](https://user-images.githubusercontent.com/23317405/74660453-1e80e580-51d1-11ea-8623-9864f54e6562.png)

They are just same structures! In the first molecule, only `926` exists, but in the second molecule, `80` also exists for the same substructure. I wonder if Morgan fingerprint is designed for this or there is a bug. 

Thank you so much!

**Comment by greglandrum** [comment]
Hi @Minys233 
By default the morgan fingerprint includes information about whether or not an atom is in a ring in the information about the bits. In your case bit 926 is the CH2 in a ring, while bit 80 is the CH2 in a chain.

**Comment by Minys233** [comment]
Thanks so much for pointing out the direction for me. For others who have the same question, I did some source code reading, the default atom invariants are defined at [MorganFingerprints.h](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Fingerprints/MorganFingerprints.h), which `includeRingMembership` has a default value of true. Check corresponding cpp file for implementation details.

If you do not want to this information included in the morgan fingerprint, just pass your own `invariant` parameter to `AllChem.GetMorganFingerprint` function.

**Comment by greglandrum** [comment]
I'll also point out that the atom invariants used are the ones described in the original paper, which is referenced in the RDKit documentation: https://doi.org/10.1021/ci100050t

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
