### ISSUE TITLE
EnumerateStereoisomers in multiprocessing

### ISSUE THREAD

**Issue by DrrDom** [rdkit/rdkit#2962]
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: Ubuntu 18.04
- Python version (if relevant): 3.6
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

If I pass SMILES to a function which generate stereoisomers in multiprocessing pool it works as expected. If I pass RDKit Mol objects the function returns one unsteric compound as output. In the single thread it works with Mol objects correctly.

```
from rdkit import Chem
from multiprocessing import Pool
from rdkit.Chem.EnumerateStereoisomers import EnumerateStereoisomers

smiles = ['CC(N)C(O)=O', 'CC(C)C(N)C(O)=O']
mols = [Chem.MolFromSmiles(s) for s in smiles]

for m in mols:
    print([Chem.MolToSmiles(q) for q in EnumerateStereoisomers(m)])
```
output - OK
```
['C[C@H](N)C(=O)O', 'C[C@@H](N)C(=O)O']
['CC(C)[C@H](N)C(=O)O', 'CC(C)[C@@H](N)C(=O)O']
```
Create two functions and a pool
```
def f1(smi):
    mol = Chem.MolFromSmiles(smi)
    return [Chem.MolToSmiles(q) for q in EnumerateStereoisomers(mol)]

def f2(mol):
    return [Chem.MolToSmiles(q) for q in EnumerateStereoisomers(mol)]

p = Pool(2)
```
from SMILES
```
for res in p.imap_unordered(f1, smiles):
    print(res)
```
Output - OK
```
['C[C@H](N)C(=O)O', 'C[C@@H](N)C(=O)O']
['CC(C)[C@H](N)C(=O)O', 'CC(C)[C@@H](N)C(=O)O']
```
from Mols
```
for res in p.imap_unordered(f2, mols):
    print(res)
```
Output - not OK
```
['CC(N)C(=O)O']
['CC(C)C(N)C(=O)O']
```

**Comment by ptosco** [comment]
@DrrDom Hi Pavel, I can reproduce the problem also outside the `Pool` by roundtripping the molecule through `pickle`, which is what `Pool` will do to pass `mol` to the process it spawns:
```
for m in mols:
    m = pickle.loads(pickle.dumps(m))
    print([Chem.MolToSmiles(q) for q in EnumerateStereoisomers(m)])
['CC(N)C(=O)O']
['CC(C)C(N)C(=O)O']
```

This is happens because pickling clears atom properties, in this case the `_ChiralityPossible` property that `EnumerateStereoisomers` uses:
```
for m in mols:
    print("Before pickling")
    print ([(a.GetIdx(), a.GetProp("_ChiralityPossible"))
            for a in m.GetAtoms()
            if a.HasProp("_ChiralityPossible")])
    print("After pickling")
    m = pickle.loads(pickle.dumps(m))
    print ([(a.GetIdx(), a.GetProp("_ChiralityPossible"))
            for a in m.GetAtoms()
            if a.HasProp("_ChiralityPossible")])
    print([Chem.MolToSmiles(q) for q in EnumerateStereoisomers(m)])
Before pickling
[(1, '1')]
After pickling
[]
['CC(N)C(=O)O']
Before pickling
[(3, '1')]
After pickling
[]
['CC(C)C(N)C(=O)O']
```

To avoid the problem, modify `f2()` as follows:
```
def f2(mol):
    Chem.AssignStereochemistry(mol, flagPossibleStereoCenters=True)
    return [Chem.MolToSmiles(q) for q in EnumerateStereoisomers(mol)]
```

**Comment by DrrDom** [comment]
Thank you, Paolo!
I expected loss of some atom/molecular properties but did not guessed to re-assign stereoinformation.

**Comment by bp-kelley** [comment]
Another solution is to call:

```
Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)
```

To enable pickling all properties.  See:  

https://github.com/rdkit/rdkit/issues/2470

**Comment by DrrDom** [comment]
Thank you, Brian! Nice! I did not know about this feature.
