### ISSUE TITLE
Increase count of shown molecules for rdkit.Chem.Draw.MolsToGridImage

### ISSUE THREAD

**Issue by pcko1** [rdkit/rdkit#2963]
When displaying a list of molecules with `rdkit.Chem.Draw.MolsToGridImage`, a maximum of 50 are shown regardless of `molsPerRow`. Is it possible to increase the overall number of molecules shown?

**Comment by bp-kelley** [comment]
What version of rdkit are you using?  The newer ones show a handy error here (although I'm not sure if we have them working on windows):

```/Users/bkelley/anaconda3/lib/python3.7/site-packages/rdkit/Chem/Draw/IPythonConsole.py:188: UserWarning: Truncating the list of molecules to be displayed to 50. Change the maxMols value to display more.
  % (maxMols))```

**maxMols** is the variable you want to set.

**Comment by pcko1** [comment]
I am using rdkit `v2018.09.1` and VSCode `1.41.1` on Windows 10 but my python kernel runs on a remote CentOS machine. In particular, I run my Jupyter notebook within VSCode but it is executed remotely, yet visualized on Windows.

I tried setting `molsPerRow` to 256 but I still get 50 mols shown :/

**Comment by bp-kelley** [comment]
As mentioned use maxMols to increase the limit

**Comment by pcko1** [comment]
apologies, I meant `maxMols`. After fixing another bug in my script, the desired `maxMols` are now shown, thanks!

**Comment by autodataming** [comment]
rdkit.Chem.Draw.MolsToGridImage(mols,maxMols=999999)
