### ISSUE TITLE
Molecule properties not retained with MolStandardize.rdMolStandardize.Cleanup()

### ISSUE THREAD

**Issue by ZacharyKaplan** [rdkit/rdkit#2965]
**Configuration:**

- RDKit Version: 2019.09.3.0
- Operating system: Centos 7
- Python version (if relevant): 3.6, 3.7
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit? N/A

**Description:**

Rdkit Team,
Certain molecules do not retain their properties when standardized with the rdkit.Chem.MolStandardize.rdMolStandardize.Cleanup function. This updated function was changed in an earlier release for speed improvements and to fix this very issue. We did not experience this molecular property dropping problem in the 2019.09.2.0 release, but it seems to have appeared again. Running on a collection of a million smiles, we found that the molecular properties are dropped on about 5% of the constructed molecules. Here are some examples of smiles that fail:

Cl.c1cnc(OCCCC2CCNCC2)cn1
C[C@@H](O)[C@H]1C(=O)N2C(C(=O)O)=C(S[C@@H]3CN[C@H](C(=O)N(C)C)C3)[C@H](C)[C@H]12.O
C=C[C@H]1CCC[NH2+]1.[Cl-]
CN1CCC2CCN(C(=O)C3CNC3)C2C1.Cl
COc1cc(NC(=O)CNC(=O)[C@@H](N)C(C)C)ccc1NS(C)(=O)=O.Cl
CNC(=O)C(c1ccccc1)n1cnc2c([NH2+]C)ncnc21.[Cl-]
C=CC[N+](C)(C)CC=C.[Cl-].[Cl-]
CN1C(=C2C(=[NH2+])N3CSCC3C2=O)N(C)c2ccccc21.[Cl-]

```
from rdkit.Chem.MolStandardize import rdMolStandardize
from rdkit.Chem import MolFromSmiles

smiles = "COc1cc(NC(=O)CNC(=O)[C@@H](N)C(C)C)ccc1NS(C)(=O)=O.Cl"
mol = MolFromSmiles(smiles)
mol.SetProp("testing_prop", str(1234))

print("Smiles", smiles)

print("Props Before CleanUp")
print(mol.GetPropsAsDict())

standard_mol = rdMolStandardize.Cleanup(mol)

print("Props After CleanUp")
print(standard_mol.GetPropsAsDict())
```

Thank you,
Zach Kaplan

**Comment by greglandrum** [comment]
Hi Zach,
Thanks for reporting this. I'll take a look and try and get this fixed
