### ISSUE TITLE
cannot read SMILES which has been canonized

### ISSUE THREAD

**Issue by AustinApple** [rdkit/rdkit#2967]
**Configuration:**

- RDKit Version: 2018.09.1
- Operating system: Mac OS
- Python version (if relevant): 3.6.7
- Are you using conda? yes

**Description:**

Hi,
I canonize the SMILES 'So1cccc1' by using the function below. 
Next, I try to read this SMILES which has been canonized, then a error message appears.

```
def canonize(smi):
    return Chem.MolToSmiles(Chem.MolFromSmiles(smi), isomericSmiles=True, canonical=True)
smi_canon = canonize('So1cccc1')
Chem.MolFromSmiles(smi_canon)
```
```
Explicit valence for atom # 1 O, 3, is greater than permitted
```
Dose anyone have any idea to fix this problem?

**Comment by greglandrum** [comment]
I’m on my phone and can’t check right now, but I would be surprised if smi_canon works at all with this molecule. I would expect So1cccc1 to produce the error you see when you call MolFromSmilea

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by AustinApple** [comment]
Yes, I update RDKit from 2018.09.1 to 2019.09.3, and the problem is solved.
