### ISSUE TITLE
MolFromInChI always removes hydrogens

### ISSUE THREAD

**Issue by jthorton** [rdkit/rdkit#2969]
**Configuration:**
linux 
rdkit version 2019.09.2
Python 3.7.5
installed via `conda install -c rdkit rdkit`

**Description:**
When making an RDKit molecule from InChI the hydrogens always seem to be removed despite setting `removeHs=False`, is there a different method in the toolkit I should be using to make the molecules without removing the hydrogens? 

Example
```python
from rdkit import Chem

ref_mol = Chem.MolFromSmiles('[H]c1c(c(c(c2c1[C@@]3([C@]([C@]4([C@@](C(=O)C(C4([H])[H])([H])[H])(C(C3([H])[H])([H])[H])C([H])([H])[H])[H])(C(C2([H])[H])([H])[H])[H])[H])[H])OS(=O)(=O)[O])[H]', sanitize=False)

# now make the inchi string for this molecule
inchi = Chem.MolToInchi(ref_mol, options='-FixedH')
print(inchi)
```
> InChI=1/C18H22O5S/c1-18-9-8-14-13-5-3-12(23-24(20,21)22)10-11(13)2-4-15(14)16(18)6-7-17(18)19/h3,5,10,14-16H,2,4,6-9H2,1H3,(H,20,21,22)/t14-,15-,16+,18+/m1/s1/f/h20H

```python
# now make a molecule from the inchi
inchi_mol = Chem.MolFromInchi(inchi, sanitize=False, removeHs=False)

# compare the amount of atoms in the molecules

print(ref_mol.GetNumAtoms(), inchi_mol.GetNumAtoms())
```
> 45 27

**Comment by greglandrum** [comment]
@jthorton : the InChI itself doesn't actually include hydrogens (just the count of the number of Hs per atom). If you want the Hs to be added back to the graph, you need to call AddHs on the molecule after you construct it from InChI.

A general point: creating molecules from InChIs is almost always a bad idea unless you really have no other choice. InChI was not designed as an molecule interchange format and using it as one is not recommended.

**Comment by jthorton** [comment]
@greglandrum Thanks for the quick reply, this was my assumption but I was confused with the function parameters. 

Ah yes thanks for the advice in my round trip tests I have noticed that they fail more than other formats, I'll be sure to add a warning with this functionality.

Thanks for the help!
