### ISSUE TITLE
Force field minimization is unstable for lower values of non-bonded threshold

### ISSUE THREAD

**Issue by drkeoni** [rdkit/rdkit#2971]
**Configuration:**

- RDKit Version: 2020.03, also seen with 2019.03
- Operating system: Mac OS X 10.14 (also seen with Linux 4.15.0)
- Python version: 3.7
- Are you using conda? No
- If you are not using conda: how did you install the RDKit? `brew install --HEAD` (but also not using HEAD)

**Description:**

I've been tracking down some odd behavior when minimizing the energy for molecule conformations, and I believe I isolated it to how ForceField Minimize behaves when the non-bonded threshold is kicking in.  You don't have to have very low settings of `nonBondedThreshold` to see this; in the example below a threshold of `15.0` will start to show this behavior.

What I observe is that minimization seems to be calculating the energy (perhaps the gradients?) incorrectly when this setting is in force and the result is that the resulting structures can be quite high energy...even though the force field thinks that the energy is quite low.  If you reinitialize the force field with the current geometry after minimization you'll get back the correct high energy.

Here's a test case that's pretty minimal that will show this behavior:

```
import logging
import rdkit.Chem as Chem
from rdkit.Chem import AllChem
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG = True
logging.getLogger().setLevel(logging.INFO)

SMILES = "CCS(CCOc1ccc(cc1)S(N1CCN(CC1)S(NC(C)C)(=O)=O)(=O)=O)(=O)=O"
CONF_ID = 0
NB_THRESH = 15.0
# embed
mol = Chem.MolFromSmiles(SMILES)
mol3d = Chem.AddHs(mol)
AllChem.EmbedMultipleConfs(mol3d, randomSeed=43)
# minimize conformer CONF_ID
props = AllChem.MMFFGetMoleculeProperties(mol3d)
ff = AllChem.MMFFGetMoleculeForceField(mol3d, props, nonBondedThresh=NB_THRESH, confId=CONF_ID)
logging.info(f"Initial energy = {ff.CalcEnergy()}")
ff.Initialize()
converged = ff.Minimize(700)
logging.info(f"Now calc energy = {ff.CalcEnergy()}")
ff = AllChem.MMFFGetMoleculeForceField(mol3d, props, nonBondedThresh=NB_THRESH, confId=CONF_ID)
logging.info(f"True calc energy = {ff.CalcEnergy()}")
# remove Hs and only leave the conformer that we minimized (for display)
mol3d = Chem.RemoveHs(mol3d)
for i in range(mol3d.GetNumConformers()):
    if i != CONF_ID:
        mol3d.RemoveConformer(i)
mol3d
```
Output:
```
INFO:root:Initial energy = -69.06276221875777
INFO:root:Now calc energy = -165.35957909182883
INFO:root:True calc energy = -161.57848439516923
```

So at a threshold of 15 A (fairly far!) we already see a difference between what the final minimize step calculates and the true answer.  (and you won't see this for threshold=16)

This behavior gets progressively worse as `NB_THRESH` is dropped.  At 5 A:

Output:
```
INFO:root:Initial energy = -76.43062619374757
INFO:root:Now calc energy = -215.4414079704094
INFO:root:True calc energy = 4677.846457352935
```
![Screen Shot 2020-02-25 at 9 15 05 AM](https://user-images.githubusercontent.com/851085/75270396-55e22a00-57af-11ea-9f42-d6879fb45aed.png)

It's not totally surprising to me that minimization with a non-bonded threshold is unstable because of the sharp discontinuities in the function but I also think there's a bug in how the energy is calculated in this process.  Even if minimization is unstable, I don't think the routine should have thought it got to an energy of -215 when the actual energy for that geometry is 4678.

I initially saw this behavior in `rdkit 2019.03`.  By fiddling with the random seed and/or conformer ID you can get this behavior to show up there too.

**Comment by ptosco** [comment]
The reason why this happens is that both in the UFF and in the MMFF implementation non-bonded lists are not updated at all during the minimization. Therefore, if the molecule folds or extends significantly during the minimization compared to its original geometry. when you re-create the force field after minimization, non-bonded lists will be recomputed afresh on the new geometry, hence the rather different numbers.
For the time being I would recommend that on small, flexible molecules that are likely to change significantly their geometry during the minimization you use a large non-bonded cutoff, in order to avoid or minimize this artifact. Given the number of atoms is quite small, you should not suffer a major impact on performance.

**Comment by drkeoni** [comment]
That makes sense, and I'm certainly moving to that answer in my own work.  I actually had set a lower non-bonded threshold because I was trying to minimize the formation of intramolecular bonds---i.e. with MMFF/UFF being gas-phase force fields, there's a strong tendency for floppy molecules to fold in on themselves with intramolecular electrostatic or H-bonds, and that doesn't seem physical for bioactive conformations.

Early testing had suggested that could work, but I didn't realize that `Minimize` was going in very wrong directions at this point.

My current approach is to not play with non-bonded threshold and to instead try to get some of my desired behavior with a dielectric of 80.  I was previously using `MMFFOptimizeMoleculeConfs` and hadn't realized until this investigation that I could reproduce this function with the calls I show above, and that gives the ability to set a dielectric using the `MMFFProperties` object.

**Comment by bp-kelley** [comment]
In practice, you might find success with simply turning intramolecular electrostatics off, or perhaps generating structures with it on and off.  This has been the omega (OpenEye) approach for a while.  The thought is that protein electrostatics swamp intramolecular electrostatics most of the time.

----
Brian Kelley
