### ISSUE TITLE
Reaction rendering always shows molecules in aromatic form

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2976]
`get2DCoordsForReaction()` calls `get2DCoordsMol()`, which always sanitizes the reactants, agents, and products. There needs to be some control over this so that it's possible to draw reactions in kekule form (if desired).

**Comment by ChongLu121** [comment]
Hello, 

I'd like to draw reactions in kekule form. Do you have any solution to convert the dashed line to  kekulized ring? 

rxn = AllChem.ReactionFromSmarts('CN.OC(=O)CCC1C2=C(C=CC=C2)C2=C1C=CC=C2>>CNC(=O)CCC1C2=C(C=CC=C2)C2=C1C=CC=C2',
                                 useSmiles=True)
d = Draw.MolDraw2DSVG(600,200)
d.SetFontSize(0.6)
d.DrawReaction(rxn)
d.FinishDrawing()
svg = SVG(d.GetDrawingText())
display(svg)


Thanks.
