### ISSUE TITLE
RDKit misplaces stereochemistry/chirality information for small ring

### ISSUE THREAD

**Issue by d-b-w** [rdkit/rdkit#2984]
**Configuration:**
- RDKit Version: 2019.09.02 and 2020.03.1dev1
- Operating system: Linux and Mac
- Python version (if relevant): 3.6.2
- Are you using conda? Nope
- If you are not using conda: Local build and Schrodinger bundled build of 2019.09.02.

**Description:**
RDKit seems to misplace the stereochemical descriptions of this moeity. In this example, a bond stereochemistry is required to break symmetry for an atom parity, and the atom parity is required to break symmetry for the bond stereochemistry. One of the double bond's stereoatoms needs to be in a ring.

![examples3](https://user-images.githubusercontent.com/3013277/75928368-1bb5ff80-5e23-11ea-8f56-2637d86faf8b.png)

```
>>> from rdkit import Chem
>>> Chem.MolToSmiles(Chem.MolFromSmiles(r'CCC=C1CC(O)C1'))
'CCC=C1CC(O)C1'
# this seems incorrect to me, and disagrees with Marvin and Canvas
>>> Chem.MolToSmiles(Chem.MolFromSmiles(r'CC/C=C1\C[C@H](O)C1'))
'CCC=C1CC(O)C1'
>>> Chem.MolToSmiles(Chem.MolFromSmiles(r'CC/C=C1\CC[C@H]1O'))
'CC/C=C1\\CC[C@H]1O'
```

**Comment by greglandrum** [comment]
Huh. This is a new one to me. I was going to complain that that isn't a stereocenter, but it really isn't superimposable on its mirror image, so I guess it is.

I don't think this is going to be trivial to fix, but it's been a while since I looked at the code that handles the ring stereochemistry special cases, so who knows...

**Comment by d-b-w** [comment]
In discussions in #3234 and #3324 , it seems like a fix for this issue would need to go in the atom canonicalization code
