### ISSUE TITLE
Tautomer enumeration should remove stereo in all tautomers 

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#2990]
The enumeration code does a good job of removing stereo from atoms/bonds directly affected by a tautomer transformation, but it should really remove stereo from all bonds/atoms that are affected in *any* tautomer.

Here's a simple example:
```
m = Chem.MolFromSmiles('COC(=O)[C@@H](N)CO')
tauts = enum.Enumerate(m)
```
The results are:
![image](https://user-images.githubusercontent.com/540511/76218822-269ed480-6215-11ea-95c8-1720642fd1cf.png)

**Comment by greglandrum** [comment]
@mcs07 does this assessment seem reasonable to you?

**Comment by mcs07** [comment]
Yeah, that's a good point.
