### ISSUE TITLE
RDKit cannot install version 2020.03.1dev1

### ISSUE THREAD

**Issue by danielfllaneza** [rdkit/rdkit#2991]
I am trying to install the beta version 2020.03.1dev1 from conda as per: https://rdkit.blogspot.com/2020/01/trying-out-new-tautomer.html?_sm_au_=iVV4J11D74FtN7PJpGsWvKttvN1NG, but it proves not to work. Any suggestion on what to do?

**Comment by greglandrum** [comment]
In order to be able to help we need more information that that.
Which operating system are you on?
What commands did you run?
What error messages are you seeing that cause you to say that it does not work?

**Comment by danielfllaneza** [comment]
I am using CentOS Linux 7 (Core) and I have run the following commands in the terminal:

```
conda create -n py37_tautomer_beta python=3.7 jupyter
conda activate py37_tautomer_beta
conda install -c rdkit/label/beta rdkit
```
However, upon running it and getting no errors, conda list does not update the rdkit version:
![image](https://user-images.githubusercontent.com/44854593/76225950-7aadb700-621d-11ea-8d02-a0be344c4259.png)

**Comment by greglandrum** [comment]
If you had just created a new environment as shown in those commands, then you shouldn't have RDKit installed at all in the environment.

That's a bit strange.

Can you try removing the environment (should be safe if you just created it):
```
conda env remove -n py37_tautomer_beta
```
then doing these commands:
```
conda create -n py37_tautomer_beta python=3.7 jupyter
conda activate py37_tautomer_beta
conda list | grep rdkit
```

**Comment by danielfllaneza** [comment]
The RDKit was already installed in the environment and the picture shows a second time trying to reinstall the package - I can edit the comment so that the situation is described more accurately.
I have followed your recommendation and the last command does not display anything (rdkit has not been installed yet). 

I have then run:
```
conda install -c rdkit/label/beta rdkit
conda list | grep rdkit
```
yielding similar results:
![image](https://user-images.githubusercontent.com/44854593/76233208-28be5e80-6228-11ea-8d79-929a4e56b0fd.png)

**Comment by greglandrum** [comment]
I'm afraid I don't know conda is misbehaving like that and installing from the wrong channel.
You might try, at least in the short term, to comment out conda-forge in your `.condarc` file and see if that helps.
But if you start from an environment where the rdkit isn't installed (as the commands I show above will produce) and then issue those commands, it *really* should install from the rdkit beta channel.

**Comment by iiitmjay** [comment]
@danielfllaneza 
Hi Daniel,
I also faced the same error while installing the 2020.03 version of rdkit. But works well once I removed the already installed  rdkit i.e 2019 version and again follow the same steps as mentioned on the documentation site.
or else you can either try for the **upgradation  step.**

**Comment by iiitmjay** [comment]
@greglandrum 
Sir, Myself Jay Dev , wanted to solve some of the issues if possibly can be done by me.
I feel great when be able to  solve any issue regarding rdkit.
