### ISSUE TITLE
TypeError: No registered converter was able to produce a C++ rvalue of type class 

### ISSUE THREAD

**Issue by abuhaby** [rdkit/rdkit#2994]
- RDKit Version: '2019.03.4'
- Operating system: windows 10, 64bits
- Python version (if relevant): 3.7
- Are you using conda? YES
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit?

**Description:**
When I try to below code in jupyter notebook:

smiles_list = ['C(C(=O)O)N' , 'N[C@@H](CC1=CC=CC=C1)C(O)=O']
mol_list = []
for smiles in smiles_list:
    mol = Chem.MolFromSmiles(smiles_list)
    mol_list.append(mol)
img = Draw.MolsToGridImage(mol_list)
img

I get the following error message:

TypeError: No registered converter was able to produce a C++ rvalue of type class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > from this Python object of type list

KINDLY HELP ME FIX THE ABOVE ERROR.

**Comment by bp-kelley** [comment]
You appear to be sending the list into MolFromSmiles:

mol = Chem.MolFromSmiles(smiles_list)

----
Brian Kelley

**Comment by abuhaby** [comment]
that is fine, because, i need to get molecules from those smiles.

**Comment by ptosco** [comment]
@abuhaby Brian is right. You are looping on `smiles_list` but then pass `smiles_list` to `Chem.MolFromSmiles` rather than `smiles`. Your code should be:
```
smiles_list = ['C(C(=O)O)N' , 'NC@@HC(O)=O']
mol_list = []
    for smiles in smiles_list:
    mol = Chem.MolFromSmiles(smiles)
    mol_list.append(mol)
img = Draw.MolsToGridImage(mol_list)
```
or, more concisely and efficiently:
```
mol_list = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
img = Draw.MolsToGridImage(mol_list)
```

**Comment by abuhaby** [comment]
@Ptosco, Thank you Ptosco. It worked after I applied your fix. 
I am trying to learn python and rdkit on the fly. Any suggestion for good learning material for a starter. Especially good resources for cheminformatics related stuff where i can utilize databases, molecular finger and biological activities.

**Comment by bp-kelley** [comment]
The RDKit blog is a good start:

http://rdkit.blogspot.com

It doesn't talk about databases, but it will give you a head start on some techniques.

**Comment by abuhaby** [comment]
I will try that. Thanks.

**Comment by seyonechithrananda** [comment]
@ptosco Thanks for the fix! Ran into the same issue and realized I had accidentally called the list, not the SMILES string itself :)

> @abuhaby Brian is right. You are looping on `smiles_list` but then pass `smiles_list` to `Chem.MolFromSmiles` rather than `smiles`. Your code should be:
> 
> ```
> smiles_list = ['C(C(=O)O)N' , 'NC@@HC(O)=O']
> mol_list = []
> for smiles in smiles_list:
>     mol = Chem.MolFromSmiles(smiles)
>     mol_list.append(mol)
> img = Draw.MolsToGridImage(mol_list)
> ```
> 
> or, more concisely and efficiently:
> 
> ```
> mol_list = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
> img = Draw.MolsToGridImage(mol_list)
> ```

**Comment by Inioluwajeremiah** [comment]
I had the same issue but later discovered that it was because some rows didn't have the canonical smiles notation but rather  **NaN**. This makes it impossible to iterate through the column successfully while trying to generate descriptors using the for loop.

**Comment by Inioluwajeremiah** [comment]
Do a data clean up to resolve the issue. In my case, the line of code below solved it
<pre> df2 = df[df.canonical_smiles.notna()]

**Comment by charlesxu90** [comment]
> I had the same issue but later discovered that it was because some rows didn't have the canonical smiles notation but rather **NaN**. This makes it impossible to iterate through the column successfully while trying to generate descriptors using the for loop.

This explains my problem. There's a Nan in the smiles list, which causes my problem.

**Comment by Inioluwajeremiah** [comment]
Trust you were able to resolve the issue

**Comment by acchu69** [comment]
facing the same issue 
for this part of the code 
 df = pd.DataFrame(load_data[0])
    smiless=df.astype(str)
    smiles_list = [smiless]
    mol_list = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
    img = Draw.MolsToGridImage(mol_list)
    st.write(img)
error message :
TypeError: No registered converter was able to produce a C++ rvalue of type class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > from this Python object of type DataFrame
traceback:
File "C:\Users\Admin\Desktop\alzheimers dd app\app.py", line 101, in <module>
    mol_list = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Admin\Desktop\alzheimers dd app\app.py", line 101, in <listcomp>
    mol_list = [Chem.MolFromSmiles(smiles) for smiles in smiles_list]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ptosco** [comment]
@acchu69 Please do not post on closed issues - post in Discussions if you have a question as it may help others.
In your code above, `smiless` is a `DataFrame`, as you call `astype(str)` on the whole `DataFrame`:
```
import pandas as pd

df = pd.DataFrame({"index": [1,2], "smiles": ["C", "CC"]})
type(df.astype(str))
pandas.core.frame.DataFrame
```
If you want a list of SMILES as strings, you need something like:
```
smiles_list = df.smiles.astype(str).to_list()
smiles_list
['C', 'CC']
```
