### ISSUE TITLE
Warning about RDKit jupyter extensions. 

### ISSUE THREAD

**Issue by mhangaard** [rdkit/rdkit#3006]
**Configuration:**

- RDKit Version: '2019.09.2'
- Operating system: Ubuntu 18.04
- Python version: Python 3.8.2
- I am using Conda.
- conda-forge

**Description:**
When RDKit is imported in a jupyter notebook or in jupyter-lab, a warning is thrown for merely enabling an extension. It is here in the code:
https://github.com/rdkit/rdkit/blob/master/rdkit/__init__.py#L15

Could this warning be removed? Why do we need to be warned? It does not look nice to have this unnecessary output in the notebook every single time I want to use RDKit in a notebook.

To reproduce, open jupyter-lab or jupyter notebook and import rdkit.
```
import rdkit
```

**Comment by bp-kelley** [comment]
The reason this was done is that it is a change in behavior.  I.e. you no longer need to install the rdkit jupyter extensions yourself.

That being said, we could change it from an error message to a standard message.

----
Brian Kelley

**Comment by mhangaard** [comment]
Can I install this extension manually to deactivate the warning?

**Comment by bp-kelley** [comment]
We will change the behavior in the next release to use pythons standard logging module as opposed to rdkit’s.   This will move it from a warning to an Info and allow you to turn it off.

----
Brian Kelley
