### ISSUE TITLE
failing test in pyGraphMolWrap testCrambin

### ISSUE THREAD

**Issue by smoors** [rdkit/rdkit#3009]
**Configuration:**

- RDKit Version: 2019.09.3
- Operating system: CentOS 7.7
- Python version (if relevant): 3.7.4
- Are you using conda? no
- If you are not using conda: how did you install the RDKit? installed from source (with custom easybuild script)

**Description:**

On certain CPU architectures, there is one test that fails with the error message given below. I suspect that this failure can be ignored, since (320, 326, 321) is equivalent to (320, 321, 326)? If so, maybe the test should be adapted to allow for this result to pass?

```
...
FAIL: testCrambin (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "rough_test.py", line 3994, in testCrambin
    self.assertEqual(matches, ((166, 167, 168), (298, 299, 300), (320, 321, 326)))
AssertionError: Tuples differ: ((166, 167, 168), (298, 299, 300), (320, 326, 321)) != ((166, 167, 168), (298, 299, 300), (320, 321, 326))

First differing element 2:
(320, 326, 321)
(320, 321, 326)

- ((166, 167, 168), (298, 299, 300), (320, 326, 321))
?                                             -----

+ ((166, 167, 168), (298, 299, 300), (320, 321, 326))
?                                          +++++


----------------------------------------------------------------------
Ran 183 tests in 4.841s

FAILED (failures=1)
```

code:
```
python rough_test.py
```

**Comment by greglandrum** [comment]
Interesting.  @smoors , can you share which architecture you had the problem on?

**Comment by smoors** [comment]
@greglandrum this failure happened on a Broadwell CPU. I did not see this on both Ivybridge and Skylake. it is also the only test that failed.

**Comment by smoors** [comment]
these are the compiler flags I used: `-O2 -ftree-vectorize -mavx2 -fno-math-errno`

**Comment by greglandrum** [comment]
Can you please try just doing -O2 and seeing if they works?

**Comment by smoors** [comment]
`-O2` gives the same result. but is it really a problem?

**Comment by greglandrum** [comment]
Don’t think it’s a problem, I’m mainly curious
