### ISSUE TITLE
Chem.MolFromSmiles failure to import correct structure

### ISSUE THREAD

**Issue by ErikCVik** [rdkit/rdkit#3017]
**Configuration:**

- RDKit Version: 2019.09.03
- Operating system: Windows 10
- Python version (if relevant): 3.7
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from?

**Description:**

Chem.MolFromSmiles(O=C1C2C(C3C4=CC=CC=C4C2C5C3C=CC=C5)C(N1C6=C(C)C=CC=C6)=O)
should give this strucutre ...
![anthracene_correct](https://user-images.githubusercontent.com/50182107/76979497-626d2480-690e-11ea-9c44-9e9862374295.png)

instead, I get this structure ...
![anthracene](https://user-images.githubusercontent.com/50182107/76979246-115d3080-690e-11ea-9c59-1d8297bd3e4d.png)

I tried reorienting the molecule to get different smiles codes but none work. I also double-checked this smiles code using "https://pubchem.ncbi.nlm.nih.gov/edit3/index.html" and the correct structure is almost outputted, one of the aromatic rings is missing its third double bond.

```
Your code sample here
```

**Comment by jasondbiggs** [comment]
This is a coordinate generation issue - the SMILES string was parsed correctly.  RDKit is giving identical coordinates for two pairs of atoms.  I assume this is what the red boxes mean.  This has probably been reported as a bug.

To get a bettter depiction you can evaluate `Chem.rdDepictor.SetPreferCoordGen(True)`, and the coordgen library will be used to generate coordinates.

**Comment by ErikCVik** [comment]
Thanks @jasondbiggs that seemed to fixed the problem
