### ISSUE TITLE
Draw.DrawMorganBits(Pyrene) gives error

### ISSUE THREAD

**Issue by ErikCVik** [rdkit/rdkit#3020]
**Configuration:**

- RDKit Version: 2019.09.3
- Operating system: Win 10
- Python version (if relevant): 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from?

**Description:**

If I run 

```
mol = Chem.MolFromSmiles(smiles)
dic = {}
fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=5000, bitInfo=dic)
fp_arr = np.zeros(1,)
DataStructs.ConvertToNumpyArray(fp, fp_arr)
fp_arr = np.nonzero(fp_arr)
prints = [(mol_list[num], x, dic) for x in fp.GetOnBits()]
img = Draw.DrawMorganBits(prints, molsPerRow=10, legends=[str(x) for x in fp.GetOnBits()])
img.save('bits.png')
```

on > 100 different molecules I can extract the finger print bits and visualize the images of them, but once I try to get the fingerprints for a molecule containing a pyrene in it I recieve an error like the one below...

```
Traceback (most recent call last):
  File "C:/Users/computer/PycharmProjects/untitled5/venv/rdkit_test.py", line 42, in <module>
    img = Draw.DrawMorganBits(prints, molsPerRow=10, legends=[str(x) for x in fp.GetOnBits()])
  File "C:\Users\computer\Anaconda3\envs\my-rdkit-env\lib\site-packages\rdkit\Chem\Draw\IPythonConsole.py", line 248, in DrawMorganBits
    return _DrawBit(fn, *args, drawOptions=drawOptions, **kwargs)
  File "C:\Users\computer\Anaconda3\envs\my-rdkit-env\lib\site-packages\rdkit\Chem\Draw\IPythonConsole.py", line 206, in _DrawBit
    res = fn(*args, **kwargs)
  File "C:\Users\computer\Anaconda3\envs\my-rdkit-env\lib\site-packages\rdkit\Chem\Draw\__init__.py", line 600, in DrawMorganBits
    return DrawMorganEnvs(envs, **kwargs)
  File "C:\Users\computer\Anaconda3\envs\my-rdkit-env\lib\site-packages\rdkit\Chem\Draw\__init__.py", line 724, in DrawMorganEnvs
    highlightBondColors=bondColors, highlightAtomRadii=highlightRadii, **kwargs)
rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 5 6 7 8 9 11 12 13
```

```
Your code sample here
```

**Comment by bp-kelley** [comment]
MolFromSmiles can fail, in this case it’s because of the kekulization error as shown in your error message.

When it does, it returns None, so you should check for this and move on to the next molecule.

**Comment by ErikCVik** [comment]
@bp-kelley MolFromSmiles and GetMorganFingerprintAsBitsVect both worked fine. It is only when I try to create the images of the fingerprints using DrawMorganBits do I get an error.

**Comment by greglandrum** [comment]
@ErikCVik: is it possible for you to share a specific molecule where you have the problem?

**Comment by jat9292** [comment]
Hello I get the same problem as author using:

````
mol=Chem.MolFromSmiles('CN1Cc2c(C(=O)OC(C)(C)C)ncn2-c2ccsc2C1=O')
Draw.DrawMorganBit(mol, 1928, bi, useSVG=True)
````

I also tried to add kekulization before the DrawMorganBit function with : `mol=Chem.Kekulize(mol)` but the returned mol is empty...

**Comment by greglandrum** [comment]
@jat9292 which version of the RDKit are you using and how did you install it?

**Comment by jat9292** [comment]
I am using '2020.09.4' rdkit version, installed via conda-forge.

**Comment by Tong-Du** [comment]
> @jat9292 I suspect the problem here is the same as what was reported as #3796. That should be fixed in versions 2020.09.5 and later.
> Can you please try updating your installation and see if you have the same problem?
> 
> Also: `Chem.Kekulize(mol)` modifies the molecule in place, so it doesn't return anything.

@greglandrum I also encountered a similar problem. On the latest version of rdkit (2021.03.5), this problem still exists.

```
from rdkit import Chem
from rdkit.Chem import Draw, AllChem
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG = True
from rdkit import rdBase
print(rdBase.rdkitVersion)  

# 2021.03.5
# install by conda install rdkit -c conda-forge

mol = Chem.MolFromSmiles('c1ccn2ccnc2c1')
bi = {}
fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, bitInfo=bi)
Draw.DrawMorganBit(mol, 1494, bi, useSVG=True)
```
----Output---
```
2021.03.5
RDKit ERROR: [13:45:23] Can't kekulize mol.  Unkekulized atoms: 0 1 2 7 8
RDKit ERROR: 
[13:45:23] Can't kekulize mol.  Unkekulized atoms: 0 1 2 7 8

---------------------------------------------------------------------------
KekulizeException                         Traceback (most recent call last)
```

**Comment by DavidACosgrove** [comment]
Hi @Tong-Du. In this case the error message is correct. It’s a strange feature of SMILES that aromatic nitrogens in 5-membered rings require an explicit hydrogen. The correct string in this case is   
c1ccn2cc[nH]c2c1.

**Comment by Tong-Du** [comment]
> Hi @Tong-Du. In this case the error message is correct. It’s a strange feature of SMILES that aromatic nitrogens in 5-membered rings require an explicit hydrogen. The correct string in this case is
> c1ccn2cc[nH]c2c1.

Thank you! But, when I added an explicit hydrogen, the molecule could not be read correctly by rdkit.
```
from rdkit import Chem
mol1 = Chem.MolFromSmiles('c1ccn2ccnc2c1')
mol1
```
[Output]
![Snipaste_2021-09-23_09-04-10](https://user-images.githubusercontent.com/85542937/134441134-ce8de3bf-8b48-4244-9c3b-0f005fcaaba6.png)

```
mol2 = Chem.MolFromSmiles('c1ccn2cc[nH]c2c1')
print(mol2)
```
[Output]
```
None
RDKit ERROR: [09:04:47] Can't kekulize mol.  Unkekulized atoms: 0 1 2 4 5 7 8
RDKit ERROR: 
```

**Comment by jhjensen2** [comment]
I am getting the same problem for this molecule with version 2021.09.4 installed using `pip install rdkit-pypi`

```
mol = Chem.MolFromSmiles('[O-]c1cc(C[C@H]2C[NH2+]CCO2)nc2nc(-c3ccccc3Cl)nn12')
bi = {}
fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048, bitInfo=bi)
tpls = [(mol,x,bi) for x in fp.GetOnBits()]
Draw.DrawMorganBits(tpls,molsPerRow=8,legends=[str(x) for x in fp.GetOnBits()], useSVG=True)
```
RDKit ERROR: [09:26:54] Can't kekulize mol.  Unkekulized atoms: 1 2 3 5 6

I can visualise individual bits with `Draw.DrawMorganBit(mol,1089,bi, useSVG=True)`

**Comment by ptosco** [comment]
@jhjensen2 Hi Jan, here's a monkey patch you can use to avoid the problem:
```
from rdkit import Chem
from rdkit.Chem import Draw, rdMolDescriptors

_getMorganEnv = Draw._getMorganEnv
def _getMorganEnvPatched(*args, **kwargs):
    menv = _getMorganEnv(*args, **kwargs)
    menv_dict = menv._asdict()
    try:
        _submol = Draw.PrepareMolForDrawing(menv.submol)
    except Chem.KekulizeException:
        _submol = Draw.PrepareMolForDrawing(menv.submol, kekulize=False)
    menv_dict['submol'] = _submol
    return Draw.FingerprintEnv(**menv_dict)
Draw._getMorganEnv = _getMorganEnvPatched

mol = Chem.MolFromSmiles('[O-]c1cc(C[C@H]2C[NH2+]CCO2)nc2nc(-c3ccccc3Cl)nn12')
bi = {}
fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048, bitInfo=bi)
tpls = [(mol,x,bi) for x in fp.GetOnBits()]
drawOptions = Draw.rdMolDraw2D.MolDrawOptions()
drawOptions.continuousHighlight = False
drawOptions.includeMetadata = False
drawOptions.prepareMolsBeforeDrawing = False
Draw.DrawMorganBits(tpls,molsPerRow=8,legends=[str(x) for x in fp.GetOnBits()], useSVG=True, drawOptions=drawOptions)
```
![image](https://user-images.githubusercontent.com/5244385/152676850-5c015dbe-9258-47ed-804a-732d81106a4b.png)

**Comment by jhjensen2** [comment]
Thank you!

**Comment by jhjensen2** [comment]
Just FYI: if I run the same cell again in a notebook (Google Colab) I get the following error: 
`RecursionError: maximum recursion depth exceeded`
But I can work around that
