### ISSUE TITLE
Draw.MolToFile not working

### ISSUE THREAD

**Issue by Marcosuff** [rdkit/rdkit#3046]
Hello,
I have a pipeline to draw molecule's images using Draw.MolToFile and it was working just fine until a few hours ago. However, when I tried to run now it shows this error:

```
/usr/local/lib/python3.7/site-packages/rdkit/Chem/Draw/__init__.py in MolToFile(mol, filename, size, kekulize, wedgeBonds, imageType, fitImage, options, **kwargs)
    256   else:
    257     raise ValueError("unsupported output format")
--> 258   data = drawfn(mol,size,kwargs.get('highlightAtoms',[]),
    259                   kwargs.get('legend',''),highlightBonds=kwargs.get('highlightBonds',[]),
    260                   drawOptions=options,kekulize=kekulize,wedgeBonds=wedgeBonds,returnPNG=True)

UnboundLocalError: local variable 'drawfn' referenced before assignment
```

I took a look at `__init__.py `and realised the lines of code below are creating a variable called data instead of drawfn. I changed it to data and it now works properly. 
```
        elif imageType=='svg':
            data = _moltoSVG
            mode = 't'
```
Could you please revise this?

Here's the full function

```
def MolToFile(mol, filename, size=(300, 300), kekulize=True, wedgeBonds=True, imageType=None,
              fitImage=False, options=None, **kwargs):
  """ Generates a drawing of a molecule and writes it to a file
  """
  # original contribution from Uwe Hoffmann
  if not filename:
    raise ValueError('no filename provided')
  if not mol:
    raise ValueError('Null molecule provided')

  if imageType is None:
    imageType = os.path.splitext(filename)[1][1:]

  if imageType not in ('svg','png'):
    _legacyMolToFile(mol,filename,size,kekulize,wedgeBonds,imageType,fitImage,options,
                       **kwargs)
  
  if type(options)==DrawingOptions:
    warnings.warn("legacy DrawingOptions not translated for new drawing code, please update manually",DeprecationWarning)
    options = None
  if imageType=='png':
    drawfn = _moltoimg
    mode = 'b'
  elif imageType=='svg':
    data = _moltoSVG
    mode = 't'
  else:
    raise ValueError("unsupported output format")
  data = drawfn(mol,size,kwargs.get('highlightAtoms',[]),
                  kwargs.get('legend',''),highlightBonds=kwargs.get('highlightBonds',[]),
                  drawOptions=options,kekulize=kekulize,wedgeBonds=wedgeBonds,returnPNG=True)
 # print(data)
  with open(filename,'w+'+mode) as outf:
    outf.write(data)
    outf.close()
```

**Comment by ptosco** [comment]
@Marcosuff Hi, thanks for reporting this!
As you have already observed, replacing
```
  elif imageType=='svg':
    data = _moltoSVG
    mode = 't'
```
with
```
  elif imageType=='svg':
    drawfn = _moltoSVG
    mode = 't'
```
in `rdkit/Chem/Draw/__init__.py` will fix the problem.

**Comment by Marcosuff** [comment]
By the way, @ptosco how can I change Drawinoptions no the new version? I was using RDKit 2019.09.3 and my pipeline does `DrawingOptions.atomLabelFontSize = 30`, which is not working on the new update. The new codes gives a warning the warning below:
`if type(options)==DrawingOptions:
    warnings.warn("legacy DrawingOptions not translated for new drawing code, please update manually",DeprecationWarning)` 

How can I change drawing options on this version?

**Comment by greglandrum** [comment]
Closed in #3049

**Comment by danpol** [comment]
Hi, @greglandrum! Did you plan to include this fix in 2020_03_2 release? I see the fix in master, but it is not available in the latest release

**Comment by danpol** [comment]
Hi, @greglandrum! Do you plan to include this fix into a release any time soon?

**Comment by waltonseymour** [comment]
Is there a reason this was not included in the most recent release?

**Comment by TermeHansen** [comment]
I agree, why is this bug still here in 2020.03.6 ?
