### ISSUE TITLE
 org.RDKit.GenericRDKitException from org.RDKit.RDKFuncs.chargeParent()

### ISSUE THREAD

**Issue by tdudgeon** [rdkit/rdkit#3053]
- RDKit Version: 2020.03.1
- Operating system: Debian, Fedora
- Python version (if relevant): N/A
- Java version: 11

**Description:**

Following on from #2970 I'm still having problems with RDKFuncs.chargeParent(). It's now throwing a GenericRDKitException whenever its called.

Here is a Spoc test that I'm using to illustrate this
```
    void "uncharge vanilla rdkit"() {

        when:
        def mol1 = RWMol.MolFromSmiles("O=C([O-])c1ccccc1")
        println("mol1: " + mol1)
        def mol2 =  RDKFuncs.chargeParent(mol1, RDKFuncs.getDefaultCleanupParameters(), true)
        println("mol2: " + mol2)
        def smiles = mol2.MolToSmiles()

        then:
        smiles == "O=C(O)c1ccccc1"
    }
```

Result is:

```
mol1: org.RDKit.RWMol@7fbdb894

org.RDKit.GenericRDKitException
	at org.RDKit.RDKFuncs.chargeParent(RDKFuncs.java:5407)
	at org.squonk.fragnet.chem.MolStandardizeSpec.uncharge vanilla rdkit(MolStandardizeSpec.groovy:69)
```

Similar is seen when running from plain Java. 
It makes no difference whether the standardize param is true or false.

**Comment by greglandrum** [comment]
I can't reproduce this:
```
	public void testChargeParent() {
		RWMol m = RWMol.MolFromSmiles("[O-]C(=O)c1ccccc1");
		RWMol m2 = RDKFuncs.chargeParent(m,RDKFuncs.getDefaultCleanupParameters(),true);
		assertEquals("fail", m2.MolToSmiles(),"O=C(O)c1ccccc1");
	}
```
works fine for me from java using v2020.03.1

**Comment by tdudgeon** [comment]
OK, it's working for me too now.
I rebuilt RDKit so maybe there was something inconsistent in my environment.
Sorry for the false alarm

**Comment by tdudgeon** [comment]
I'm re-opening this issue as I can reproduce this in some circumstances. This prevents me building fully functional docker images.

First, as mentioned above, if you do a build from a git checkout (I've using Release_2020_03 branch) and then set LD_LIBRARY_PATH and CLASSPATH to the build artifacts all works OK.

But if instead I build debian packages using `cpack -G DEB` and then install those into a debian buster release then I do get that GenericRDKitException when using various bits of the standardizer code. The vast majority of other RDKit functions work OK. 

Detail of how this is assembled can be found here: https://github.com/InformaticsMatters/docker-rdkit/blob/master/Dockerfile-java-debian

AFAIK all the RDKit libraries are installed and everything is in the expected place. And as I mention most of RDKit works fine from Java.

Any pointers to what might be wrong? The GenericRDKitException doesn't give any useful info. Does standardizer use any additional dependencies that I might be missing?

**Comment by greglandrum** [comment]
@tdudgeon : The standardization code does need access to the default data files. I suspect that the problem is that you are setting $RDBASE$ incorrectly: it needs to be set to whatever directory contains the RDKit's Data directory (likely `/usr/share/rdkit` or something like that, but you'll need to verify that)

**Comment by tdudgeon** [comment]
Thanks. That probably explains it. I'll dig around and find out if the data files are not installed, or just not in the expected place.

**Comment by tdudgeon** [comment]
Yes, that indeed was the problem. The deb packages install those files to `/usr/share/RDKit` and setting `RDBASE` to that location fixes the problem. 

Just for reference this is what is installed into that dir:

`Data  Docs  README  Scripts  license.txt`

Thanks for your help with this. Container images are being pushed to DockerHub with this fix.
