### ISSUE TITLE
 RDKFuncs.cleanUp() does not seem to be cleaning up

### ISSUE THREAD

**Issue by tdudgeon** [rdkit/rdkit#3054]
RDKit Version: 2020.03.1
Operating system: Debian, Fedora
Python version (if relevant): N/A
Java version: 11

**Description:**

My understanding is that ` RDKFuncs.cleanUp(mol)` is expected to fix standard problems with a molecule, one of which is covalently bonded metals.

This does not seem be happening. Here is a Spoc test 

```
    void "cleanup vanilla rdkit"() {

        when:
        def mol = RWMol.MolFromSmiles("[Na]OC(=O)c1ccccc1")
        RDKFuncs.cleanUp(mol)
        def smiles = mol.MolToSmiles()

        then:
        smiles == "O=C([O-])c1ccccc1.[Na+]"
    }
```

It fails because the smiles that is generated is `O=C((O)[(Na)])c1ccccc1`

**Comment by greglandrum** [comment]
Hi @tdudgeon, `RDKFuncs.cleanup()` returns a new `RWMol` instead of modifying the molecule in place. This code works:
```
	public void testCleanup() {
		RWMol m = RWMol.MolFromSmiles("[Na]OC(=O)c1ccccc1");
		RWMol m2 = RDKFuncs.cleanup(m);
		assertEquals("fail", m2.MolToSmiles(),"O=C([O-])c1ccccc1.[Na+]");
	}
```

**Comment by tdudgeon** [comment]
That's strange. In my version the return type of `RDKFuncs.cleanup(m)` is `void`.

**Comment by greglandrum** [comment]
> That's strange. In my version the return type of `RDKFuncs.cleanup(m)` is `void`.

Odd, the version in the release definitely returns an RWMol:
https://github.com/rdkit/rdkit/blob/Release_2020_03/Code/GraphMol/MolStandardize/MolStandardize.h#L85
and the Java wrappers should just bring that directly across:
https://github.com/rdkit/rdkit/blob/Release_2020_03/Code/JavaWrappers/MolStandardize.i

**Comment by tdudgeon** [comment]
Fro the JavaDocs it looks like we're both right:

![Screenshot from 2020-04-03 10-17-26](https://user-images.githubusercontent.com/647419/78356233-16291200-75a7-11ea-9886-bae99ae6ad91.png)

In fact I don't think that is legal - two methods with the same name with different return types. It's definitely confusing my compiler:

```
groovy.lang.MissingMethodException: No signature of method: static org.RDKit.RDKFuncs.cleanUp() is applicable for argument types: (org.RDKit.RWMol, org.RDKit.CleanupParameters) values: [org.RDKit.RWMol@6b53bcc2, org.RDKit.CleanupParameters@180da663]
Possible solutions: cleanup(org.RDKit.RWMol, org.RDKit.CleanupParameters), cleanUp(org.RDKit.RWMol), cleanup(org.RDKit.RWMol)
```

**Comment by greglandrum** [comment]
That wouldn't be legal in C++, so I can easily imagine that it's also illegal in Java. 
But I'm not sure how you ended up with that at all. It definitely doesn't match what is in the actual Java files, at least not when I build them.
Here's a quick grep through those files on my system:
```
(base) glandrum@Badger:/scratch/RDKit_git/Code/JavaWrappers/gmwrapper/src/org/RDKit$ grep "cleanup(" *.java
RDKFuncs.java:  public static RWMol cleanup(RWMol mol, CleanupParameters params) {
RDKFuncs.java:  public static RWMol cleanup(RWMol mol) {
```
Both of those are returning an `RWMol`.
How did you generate the version of the wrappers you are using?

**Comment by tdudgeon** [comment]
1. clean checkout
2. switch to `Release_2020_03` branch
3. mkdir build; cd build
4. cmake\
  -DPYTHON_EXECUTABLE=/usr/bin/python3\
  -DRDK_BUILD_INCHI_SUPPORT=ON\
  -DRDK_BUILD_AVALON_SUPPORT=ON\
  -DRDK_BUILD_PYTHON_WRAPPERS=ON\
  -DRDK_BUILD_SWIG_WRAPPERS=ON\
  ..
5. make -j 8

**Comment by greglandrum** [comment]
can you please execute the same `grep` that I did?

**Comment by tdudgeon** [comment]
Same results as you get.
But if you look in the JavaDocs that are generated there is a 3rd cleanup() method with a signature of:
`static void cleanUp​(RWMol mol)`

and that has a description of 'Designed to be called by the sanitizer to handle special cases before anything is done'

**Comment by greglandrum** [comment]
that's `cleanUp()`, not `cleanup()`, which is clearly not the same.
Confusing, but not the same.

This mess is an unfortunate consequence of the different C++ namespaces getting crammed into a single namespace in Java.
On the C++ side these are: `MolOps::cleanUp` and `MolStandardize::cleanup`, so it's harder to mix them up with each other.

**Comment by tdudgeon** [comment]
Arrrggghhh! I didn't spot the difference in case. All working OK now.
Thanks for point out the (not so) obvious!
