### ISSUE TITLE
rdkit on win10, anaconda, DLL load failed

### ISSUE THREAD

**Issue by seal9** [rdkit/rdkit#3057]
Hi, 
I installed rdkit to its own environment on Anaconda according to the instructions here.
https://www.rdkit.org/docs/Install.html
However, importing the module gives the error in the title.  
- RDKit Version:  2019.09.3.0 
- Operating system: Windows 10
- Python version (if relevant): 3.7.6
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from?
Default channel(?), installed with commands:
$ conda create -c rdkit -n rdkit2 rdkit

Using Jupyter notebook, with the correct kernel. Calling 
import rdkit
gives error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-6b72bd8913ab> in <module>
----> 1 import rdkit

~\.conda\envs\rdkit2\lib\site-packages\rdkit\__init__.py in <module>
      1 try:
----> 2   from .rdBase import rdkitVersion as __version__
      3 except ImportError:
      4   __version__ = 'Unknown'
      5   raise

ImportError: DLL load failed: The specified module could not be found.

Below is the full list of packages in the relevant conda environment:

# packages in environment at C:\Users\____\.conda\envs\rdkit2:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                    py37_0    anaconda
blas                      1.0                         mkl
ca-certificates           2020.1.1                      0    anaconda
cairo                     1.14.12              hf171d8a_3
certifi                   2019.11.28               py37_0    anaconda
colorama                  0.4.3                      py_0    anaconda
decorator                 4.4.2                      py_0    anaconda
freetype                  2.9.1                ha9979f8_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
intel-openmp              2020.0                      166
ipykernel                 5.1.4            py37h39e3cac_0    anaconda
ipython                   7.13.0           py37h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py37_0    anaconda
jedi                      0.16.0                   py37_0    anaconda
jpeg                      9b                   hb83a4c4_2
jupyter_client            5.3.4                    py37_0    anaconda
jupyter_core              4.6.1                    py37_0    anaconda
libboost                  1.67.0               hd9e427e_4
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0    anaconda
libtiff                   4.1.0                h56a325e_0
mkl                       2020.0                      166
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.0.15           py37h14836fe_0
mkl_random                1.1.0            py37h675688f_0
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
olefile                   0.46                     py37_0
openssl                   1.1.1                he774522_0    anaconda
pandas                    1.0.1            py37h47e9c7a_0
parso                     0.6.1                      py_0    anaconda
pickleshare               0.7.5                    py37_0    anaconda
pillow                    7.0.0            py37hcc1f983_0
pip                       20.0.2                   py37_1
pixman                    0.38.0               he774522_0
prompt_toolkit            3.0.3                      py_0    anaconda
py-boost                  1.67.0           py37h8300f20_4
pygments                  2.5.2                      py_0    anaconda
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
pywin32                   227              py37he774522_1    anaconda
pyzmq                     18.1.1           py37ha925a31_0    anaconda
rdkit                     2019.09.3.0      py37h3d1ada6_1    rdkit
setuptools                46.0.0                   py37_0
six                       1.14.0                   py37_0
sqlite                    3.31.1               he774522_0
tk                        8.6.8                hfa6e2cd_0
tornado                   6.0.4            py37he774522_1    anaconda
traitlets                 4.3.3                    py37_0    anaconda
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.8                      py_0    anaconda
wheel                     0.34.2                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.4                h2fa13f4_4
zeromq                    4.3.1                h33f27b4_3    anaconda
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

**Comment by greglandrum** [comment]
Hi. In the example above it looks like you are running jupyter in a different python environment than the one you installed the RDKit in.
Could it be that you forgot to install jupyter in your new `my-rdkit-env` environment?

**Comment by seal9** [comment]
Ah, yeah sorry about that, I changed the name of the environment my-rdkit-env to rdkit2.  I edited the original post to show this. Both the error and the environment are for the rdkit2 environment (this is the second rdkit install I made, the first one had the same problem). Jupyter is definitely in the environment list.

**Comment by greglandrum** [comment]
Does it work if you do:
`python -c 'from rdkit import Chem`
on the command line?

**Comment by seal9** [comment]
I haven't added Anaconda/Python to the command line path (work computer+not recommended for Anaconda isntall anymore) but calling that in the Anaconda command prompt works! So it does look like this is a problem with Jupyter notebook somehow?

(rdkit2) C:\Users\joakat>python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles('[C@H](Cl)(F)Br')
>>> FindMolChiralCenters(mol)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'FindMolChiralCenters' is not defined
>>> mol
<rdkit.Chem.rdchem.Mol object at 0x000001B85CD27C60>
>>> from rdkit.Chem import FindMolChiralCenters
>>> FindMolChiralCenters(mol)
[(0, 'R')]
>>>

**Comment by greglandrum** [comment]
Ok, please try ensuring that you're using the right python environment inside jupyter:
```
import sys
print(sys.executable)
print(sys.path)
```

**Comment by seal9** [comment]
![rdkit](https://user-images.githubusercontent.com/16454035/78148264-566c8100-743d-11ea-9681-002d2b72e5c6.PNG)

**Comment by seal9** [comment]
And here just to show it works in the Anaconda prompt for the same evironment.

![Uploading rdkit.PNG…]()

**Comment by seal9** [comment]
![rdkit2](https://user-images.githubusercontent.com/16454035/78148631-c418ad00-743d-11ea-9f73-92c96fd60a78.PNG)

**Comment by greglandrum** [comment]
Hmm, this is perplexing. I can't reproduce the problem and am not sure how to further debug things.
You could do the "quick" test of creating a new environment, installing just the rdkit and jupyter into that, and see if that works.
Another shot in the dark is to try doing the following command from inside your running jupyter notebook:
`python -c "from rdkit import Chem;print(Chem.__file__)"`

**Comment by cebasfu93** [comment]
I am facing the same problem. rdkit loads normally when imported from the python prompt but not from the jupyer notebook

**Comment by greglandrum** [comment]
This almost always means that you have not installed Jupyter in the environment where you installed the RDKit and a version of Jupyter from you base environment is being used. Please check that
