### ISSUE TITLE
MolToSmiles() does not work as expected

### ISSUE THREAD

**Issue by m-miy** [rdkit/rdkit#3059]
**Configuration:**

- RDKit Version: 2018.09.1
- Operating system: Ubuntu 16.04
- Python version (if relevant): 3.6.10
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from?
conda install -y -c rdkit rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

MolToSmiles() does not work as expected.
I want to sort in the order smiles atoms that I specified.
So, I use Chem.RenumberAtoms() and Chem.MolToSmiles() .
However, sometimes can't get correct Renumbered smiles.

```
from rdkit import Chem

smiles = "C1c2ccccc2C(N)C1"
mol = Chem.MolFromSmiles(smiles)
reorder = [3, 2, 1, 0, 9, 7, 8, 6, 5, 4]
reorder_mol = Chem.RenumberAtoms(mol, reorder)
reorder_smiles = Chem.MolToSmiles(reorder_mol, canonical=False, isomericSmiles=True)
print(re_order_smiles)
>>> c1cc2c(cc1)C(N)CC2
```
This is not smiles order that I specified.
Looking at this smiles order with the smiles order before rearrange is [3, 2, 1, 6, 5, 4, 7, 8, 9, 0]
The smiles I assumed is "c1cc2CCC(N)c2cc1".
I confirmed that reorder_mol seemms to be the order that I specified.
The smiles' unique atom N is in the spesified position.
```
reorder_mol.GetAtomWithIdx(6).GetAtomicNum()
>>> 7
```

**Comment by greglandrum** [comment]
`MolToSmiles()` does not write the atoms out in the order they are found in the molecule. Even if you aren't generating canonical SMILES, the RDKit uses some rules to traverse the molecule graph in an order that produces reasonably simple SMILES.

If your goal is to have a SMILES where the ordering of the atoms is the same as the ordering in the molecule you generate the SMILES from: the RDKit can't do that, so you'd have to write that code yourself.

What exactly are you trying to do?

**Comment by m-miy** [comment]
My goal is  " to have a SMILES where the ordering of the atoms is the same as the ordering in the molecule I generate the SMILES from " as you guessed.
I'll write that code.

Thanks.

**Comment by greglandrum** [comment]
@m-miy : if you can provide a bit of detail as to why you want that (i.e. what you're going to use it for), we might be able to suggest an alternative approach that doesn't require you to write that code
