### ISSUE TITLE
Bad double bond placement in polycyclic aromatics

### ISSUE THREAD

**Issue by DavidACosgrove** [rdkit/rdkit#3061]
In 2020.03.1, the SVG (and most likely the PNG) drawing of chembl54228 is:
![image](https://user-images.githubusercontent.com/9198870/78256370-57121f80-74f0-11ea-99c2-27f60e7241bd.png)
The double bonds on the outside of the rings look pretty unsavoury.  I will fix it.

**Comment by greglandrum** [comment]
Fixed by #3068
