### ISSUE TITLE
Java builds broken on Release_2019_09 branch

### ISSUE THREAD

**Issue by tdudgeon** [rdkit/rdkit#3067]
- RDKit Version: Release_2019_09 branch
- Operating system: Debian (buster)

**Description:**

Though this maybe considered historical as the 2020_03 release is now available, I've found that I cannot build the Java wrappers for the Release_2019_09 branch (and the Release_2019_09_3 tag). This prevents me from updating the Docker container images for these versions.

It seems like some URL for Maven central is wrong?

```
-- Found Java: /usr/lib/jvm/java-11-openjdk-amd64/bin/java (found version "11.0.6") 
-- Found JNI: /usr/lib/jvm/java-11-openjdk-amd64/lib/libjawt.so  
Downloading http://central.maven.org/maven2/junit/junit/4.10/junit-4.10.jar...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: central.maven.org
CMake Error at Code/cmake/Modules/RDKitUtils.cmake:218 (MESSAGE):
  The md5 checksum for /rdkit/External/java_lib/junit.jar is incorrect;
  expected: 68380001b88006ebe49be50cef5bb23a, found:
  d41d8cd98f00b204e9800998ecf8427e
Call Stack (most recent call first):
  Code/JavaWrappers/gmwrapper/CMakeLists.txt:21 (downloadAndCheckMD5)
```

**Comment by ptosco** [comment]
@tdudgeon Hi Tim, that's indeed the `md5` checksum for that file:
```
$ curl -L https://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10.jar | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  247k  100  247k    0     0  3340k      0 --:--:-- --:--:-- --:--:-- 3340k
68380001b88006ebe49be50cef5bb23a  -
```
Which is the same checksum which is encoded in `./Code/JavaWrappers/gmwrapper/CMakeLists.txt`:
```
paolo@build /tmp/rdkit-Release_2019_09_3$ grep 68380001b88006ebe49be50cef5bb23a ./Code/JavaWrappers/gmwrapper/CMakeLists.txt
    set(JUNIT_MD5SUM "68380001b88006ebe49be50cef5bb23a")
paolo@build /tmp/rdkit-Release_2019_09_3$ grep maven ./Code/JavaWrappers/gmwrapper/CMakeLists.txt
    set(JUNIT_URL "http://central.maven.org/maven2/junit/junit/4.10/junit-4.10.jar")
paolo@build /tmp/rdkit-Release_2019_09_3$
```
So it looks like something is going wrong with your download.

**Comment by tdudgeon** [comment]
It's not a download. I'm building from the source on that branch.

**Comment by tdudgeon** [comment]
The error seems to be:
```
Could not resolve host: central.maven.org
```

**Comment by ptosco** [comment]
Ah, OK, edit `./Code/JavaWrappers/gmwrapper/CMakeLists.txt` and replace `http://central.maven.org` with `https://repo1.maven.org`. It looks like the URL changed meanwhile.

**Comment by tdudgeon** [comment]
@ptosco You are right. Only the location of Maven needs changing.
I proposed a fix for this, but as this is a historical release you may choose not to accept the change.
There is a simple workaround. Add this to the cmake arguments:
```
-DJUNIT_URL="https://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10.jar"
```

**Comment by intrigus-lgtm** [comment]
`http://central.maven.org` has probably been discontinued along with the other `http` maven repositories.
This has happened at the start of 2020 so rdkit 2019_09 wasn't affected.
The repositories are now only accessible using `https`.

I think this issue can be closed?

**Comment by greglandrum** [comment]
agreed, thanks
