### ISSUE TITLE
Reactions setting unspecified double-bond stereo to STEREOANY

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#3078]
After #2890 was solved, I found another similar problem where `EnumerateStereoisomers()`failed on a bond marked as `STEREOANY` (also no StereoAtoms were set), only that in this case the bond was aromatic instead of double.

Since I think we don't expect ring bonds to be marked as stereo bonds (`findPotentialStereoBonds()` actually ignores double bonds in rings), I tracked it down to the reactions code. Basically, if a reaction introduces a double bond into a ring, there is a chance that it ends up being marked as STEREOANY:

```python
from rdkit import Chem
from rdkit.Chem import rdChemReactions

reaction = "[C:1][C:2]1[C:3][C:4]1>>[C:1][C:2]1=[C:3][C:4]1"
smiles = 'CC1CC1'

rxn = rdChemReactions.ReactionFromSmarts(reaction)
mol = Chem.MolFromSmiles(smiles)
prods = rxn.RunReactants([mol])

bond = prods[0][0].GetBondWithIdx(1)
print(bond.GetBondType())  # DOUBLE
print(bond.GetStereo()) # STEREOANY
```

At this point, the ring bond is not aromatic. In my example, with a different molecule, the ring was aromatized in the sanitization after the reaction, but the stereo came from here.

I'll shortly attach a PR that prevents ring bonds being marked STEREOANY.

**Comment by greglandrum** [comment]
**comment in progress** I am going to save this a few times as I'm editing it. I will remove this block when I'm done editing

Ok, we're swimming in complexity and contradictions here. No big surprise there.

Here's an attempt to take stock:
- I believe the behavior of `findPotentialStereoBonds()` is wrong. `assignBondStereoCodes()`, which is what's used by `assignStereochemistry()` is happy assigning stereo in rings with >7 members. One can argue about the cutoff (based on the numbers here https://pubs.acs.org/doi/pdf/10.1021/ed082p1334 I think 8 is a defensible value), but larger rings definitely can have trans double bonds in them.

**Comment by ricrogz** [comment]
As long as we do it in a proper way, I don't think it is wrong that the reaction code sets `STEREOANY` on the bonds that are newly created in reactions. After all, if we are setting `STEREOCIS` or `STEREOTRANS`, I'd also expect `STEREOANY` to be present.

On the other hand `findPotentialStereoBonds()` is definitely not doing the right thing, since the comment in it specifically mentions it is ignoring stereo bonds in rings.

Still, that leaves us with two problems instead of one:
1. Reactions setting `STEREOANY` on rings smaller than 8 members. Which also means we'd still need to find rings in the reaction.
2. `findPotentialStereoBonds()` cannot handle stereo bonds in rings.

**Comment by greglandrum** [comment]
> As long as we do it in a proper way, I don't think it is wrong that the reaction code sets `STEREOANY` on the bonds that are newly created in reactions. After all, if we are setting `STEREOCIS` or `STEREOTRANS`, I'd also expect `STEREOANY` to be present.

The problem I have with this is that `STEREOANY` is not the "zero information state" for a bond, that's `STEREONONE`. So if you construct a molecule from the SMILES `CC=CC` you get `STEREONONE`, not `STEREOANY`. I think the reaction semantics should, absent any other information, reproduce this behavior.

**Comment by ricrogz** [comment]
I agree in that it makes sense that a double bond in a mol constructed from such SMILES and one newly created in a reaction should have the same markings (and I guess this settles the discussion). But it feels weird to mark these as not having any stereochemistry (that's what `STEREONONE` sounds like), when it is clearly visible that there are neighbors on both ends that will have a stereo configuration, whatever that is.

**Comment by greglandrum** [comment]
Before spending too much time discussing #3729, I'd like to review the current state of things and what we think should happen. I'm picking simple examples which don't have the problem of double bond stereochemistry in rings.

These examples are all using the current status of master (commit d00dcc29fb)
Start simple with a reaction which creates a double bond where no information is provided about stereo:
```
>>> from rdkit import Chem
>>> from rdkit.Chem import rdChemReactions
>>> makes_dbl_bond = rdChemReactions.ReactionFromSmarts('[C:1][C:2]-[C:3][C:4]>>[C:1][C:2]=[C:3][C:4]')
>>> m1 = Chem.MolFromSmiles('CCCC')
>>> ps = makes_dbl_bond.RunReactants((m1,))
>>> Chem.SanitizeMol(ps[0][0])
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
>>> ps[0][0].GetBondWithIdx(1).GetStereo()
rdkit.Chem.rdchem.BondStereo.STEREOANY
>>> list(ps[0][0].GetBondWithIdx(1).GetStereoAtoms())
[]
```
In this case I believe the code is doing the wrong thing: we don't have any information about the stereochemistry of that new double bond, so its stereo should be set to the "no information state" which is `STEREONONE`

What about a reaction which passes a double bond from reactants to products without providing any info about stereo in the reaction definition?
```
>>> matches_dbl_bond = rdChemReactions.ReactionFromSmarts('[C:1][C:2]=[C:3][C:4]>>[C:1][C:2]=[C:3][C:4]O')
>>> m2_unspec = Chem.MolFromSmiles('CC=CC')
>>> m2_any = Chem.MolFromSmiles('CC=CC')
>>> m2_any.GetBondWithIdx(1).SetStereoAtoms(0,3)
>>> m2_any.GetBondWithIdx(1).SetStereo(Chem.BondStereo.STEREOANY)
>>> ps = matches_dbl_bond.RunReactants((m2_any,))
>>> Chem.SanitizeMol(ps[0][0])
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
>>> ps[0][0].GetBondWithIdx(1).GetStereo()
rdkit.Chem.rdchem.BondStereo.STEREOANY
>>> list(ps[0][0].GetBondWithIdx(1).GetStereoAtoms())
[]
```
Seems ok to me. We started STEREOANY and ended up STEREOANY.
Of course, since the bonds *always* end up STEREOANY this isn't a particular surprise.

What about if we start with specified stereo?
```
>>> m2_spec = Chem.MolFromSmiles('CC=CC')
>>> m2_spec.GetBondWithIdx(1).SetStereoAtoms(0,3)
>>> m2_spec.GetBondWithIdx(1).SetStereo(Chem.BondStereo.STEREOCIS)
>>> ps = matches_dbl_bond.RunReactants((m2_spec,))
>>> Chem.SanitizeMol(ps[0][0])
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
>>> ps[0][0].GetBondWithIdx(1).GetStereo()
rdkit.Chem.rdchem.BondStereo.STEREOANY
```
I'm not particularly thrilled about that.
The same thing happens if the stereo is specified starting from the SMILES (just wanted to be sure it wasn't a bond dir problem):
```
>>> m2_spec2 = Chem.MolFromSmiles('C/C=C/C')
>>> ps = matches_dbl_bond.RunReactants((m2_spec2,))
>>> Chem.SanitizeMol(ps[0][0])
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
>>> ps[0][0].GetBondWithIdx(1).GetStereo()
rdkit.Chem.rdchem.BondStereo.STEREOANY
```

**Comment by ricrogz** [comment]
What the code is doing now is that if the double bond is fully specified in the reaction (as it is in these examples), we replace the reactant's stereo with whatever is specified in the reaction's products. Since in these examples the products do not specify any particular stereo, the reactant's stereo is just reset to `STEREOANY`. And that's what this last patch addresses: since there is no stereo information in the products, the double bond should be `STEREONONE`, and not `STEREOANY`.

I just ran these examples on my branch, and in all cases the bond is reset to `STEREONONE`:

```
In [3]: from rdkit import Chem 
   ...: from rdkit.Chem import rdChemReactions 
   ...: makes_dbl_bond = rdChemReactions.ReactionFromSmarts('[C:1][C:2]-[C:3][C:4]>>[C:1][C:2]=[C:3][C:4]') 
   ...: m1 = Chem.MolFromSmiles('CCCC') 
   ...: ps = makes_dbl_bond.RunReactants((m1,)) 
   ...: print(Chem.SanitizeMol(ps[0][0])) 
   ...: print(ps[0][0].GetBondWithIdx(1).GetStereo()) 
   ...: print(list(ps[0][0].GetBondWithIdx(1).GetStereoAtoms()))                                                                                                                    
SANITIZE_NONE
STEREONONE
[]

In [4]: matches_dbl_bond = rdChemReactions.ReactionFromSmarts('[C:1][C:2]=[C:3][C:4]>>[C:1][C:2]=[C:3][C:4]O') 
   ...: m2_unspec = Chem.MolFromSmiles('CC=CC') 
   ...: m2_any = Chem.MolFromSmiles('CC=CC') 
   ...: m2_any.GetBondWithIdx(1).SetStereoAtoms(0,3) 
   ...: m2_any.GetBondWithIdx(1).SetStereo(Chem.BondStereo.STEREOANY) 
   ...: ps = matches_dbl_bond.RunReactants((m2_any,)) 
   ...: print(Chem.SanitizeMol(ps[0][0])) 
   ...: print(ps[0][0].GetBondWithIdx(1).GetStereo()) 
   ...: print(list(ps[0][0].GetBondWithIdx(1).GetStereoAtoms()))                                                                                                                    
SANITIZE_NONE
STEREONONE
[]

In [5]: m2_spec = Chem.MolFromSmiles('CC=CC') 
   ...: m2_spec.GetBondWithIdx(1).SetStereoAtoms(0,3) 
   ...: m2_spec.GetBondWithIdx(1).SetStereo(Chem.BondStereo.STEREOCIS) 
   ...: ps = matches_dbl_bond.RunReactants((m2_spec,)) 
   ...: print(Chem.SanitizeMol(ps[0][0])) 
   ...: print(ps[0][0].GetBondWithIdx(1).GetStereo())                                                                                                                               
SANITIZE_NONE
STEREONONE

In [6]: m2_spec2 = Chem.MolFromSmiles('C/C=C/C') 
   ...: ps = matches_dbl_bond.RunReactants((m2_spec2,)) 
   ...: print(Chem.SanitizeMol(ps[0][0])) 
   ...: print(ps[0][0].GetBondWithIdx(1).GetStereo())                                                                                                                               
SANITIZE_NONE
STEREONONE

```
