### ISSUE TITLE
how to set callback for the findmcs when the timeout?

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3085]
**Configuration:**

- RDKit Version: 2019.03.4
- Operating system: linux 
- Python version (if relevant): python3.6
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

how to set callback for the findmcs when the timeout?

```py
%%time

smi1 = 'CC1(OB(OC1(C)C)c2c(OCCCN3CCN(CC3)c4c(F)cc5c(=O)c(C(O)=O)cn(C6CC6)c5c4)cccc2C=O)C'
smi2 = 'O=C(c(cn(C7CC7)c8c9cc(F)c(N%10CCN(CC%10)CCCOc%11c(B(OC%12C[N+]([O-])=O)O)c%12ccc%11)c8)c9=O)O'
mol1 = Chem.MolFromSmiles(smi1)
mol2 = Chem.MolFromSmiles(smi2)

mols = [mol1,mol2]
res=rdFMCS.FindMCS(mols,timeout=10)
res.smartsString
```

if time out, I wish to run my custom function(custom_timeout) and return the result.
```
def custom_timeout(timeout):
    return "Time out %s"%timeout
```

could you support an example? Thank you.

**Comment by ptosco** [comment]
@autodataming Hi, you can find an example of custom FMCS progress callback usage in `test17MCSProgressCallbackCancel`:
https://github.com/rdkit/rdkit/blob/60566aa35fcba88789be24d70e122e48995bd3ca/Code/GraphMol/FMCS/Wrap/testFMCS.py#L836
You need to subclass `rdFMCS.MCSProgress` and define the `callback()` method in the derived class:
https://github.com/rdkit/rdkit/blob/60566aa35fcba88789be24d70e122e48995bd3ca/Code/GraphMol/FMCS/Wrap/testFMCS.py#L162

**Comment by autodataming** [comment]
Thank you. How to set timeout event to triger callback?

```py rdkit 2020
import unittest
from rdkit import Chem
from rdkit.Chem import rdFMCS

class ProgressCallback(rdFMCS.MCSProgress):
    def __init__(self):
        super().__init__()
        self.callCount = 0
    def callback(self, stat, params):
        self.callCount += 1
        print("hello,world")
        return (self.callCount < 3)




ps = rdFMCS.MCSParameters()
smis = ['CCCC(C)CC(CC)CC', 'OC(N)CC(C)CC(CC)CC']
ms = [Chem.MolFromSmiles(x) for x in smis]
# ps.AtomTyper = CompareElements()
ps.ProgressCallback = ProgressCallback( )
ps.timeout =10
mcs = rdFMCS.FindMCS(ms, ps)


smi1 = 'CC1(OB(OC1(C)C)c2c(OCCCN3CCN(CC3)c4c(F)cc5c(=O)c(C(O)=O)cn(C6CC6)c5c4)cccc2C=O)C'
smi2 = 'O=C(c(cn(C7CC7)c8c9cc(F)c(N%10CCN(CC%10)CCCOc%11c(B(OC%12C[N+]([O-])=O)O)c%12ccc%11)c8)c9=O)O'
mol1 = Chem.MolFromSmiles(smi1)
mol2 = Chem.MolFromSmiles(smi2)

mols = [mol1,mol2]
mcs = rdFMCS.FindMCS(mols,ps)
```

**Comment by ptosco** [comment]
@autodataming You could do something along these lines:

```
from rdkit import Chem
from rdkit.Chem import rdFMCS
import datetime

class ProgressCallback(rdFMCS.MCSProgress):
    def __init__(self):
        super().__init__()
        self._timeout_delta = None
        self._timeout_start = None
    def callback(self, stat, params):
        res = True
        if (self._timeout_delta is None):
            self._timeout_start = datetime.datetime.now()
            self._timeout_delta = datetime.timedelta(seconds=params.Timeout)
        else:
            res = (datetime.datetime.now() - self._timeout_start) < self._timeout_delta
        return res

ps = rdFMCS.MCSParameters()
ps.ProgressCallback = ProgressCallback()
ps.Timeout = 10

smi1 = 'CC1(OB(OC1(C)C)c2c(OCCCN3CCN(CC3)c4c(F)cc5c(=O)c(C(O)=O)cn(C6CC6)c5c4)cccc2C=O)C'
smi2 = 'O=C(c(cn(C7CC7)c8c9cc(F)c(N%10CCN(CC%10)CCCOc%11c(B(OC%12C[N+]([O-])=O)O)c%12ccc%11)c8)c9=O)O'
mol1 = Chem.MolFromSmiles(smi1)
mol2 = Chem.MolFromSmiles(smi2)

mols = [mol1,mol2]
mcs = rdFMCS.FindMCS(mols, ps)

if mcs.canceled:
    print("Timeout occurred")
```

**Comment by autodataming** [comment]
> @autodataming You could do something along these lines:
> 
> ```
> from rdkit import Chem
> from rdkit.Chem import rdFMCS
> import datetime
> 
> class ProgressCallback(rdFMCS.MCSProgress):
>     def __init__(self):
>         super().__init__()
>         self._timeout_delta = None
>         self._timeout_start = None
>     def callback(self, stat, params):
>         res = True
>         if (self._timeout_delta is None):
>             self._timeout_start = datetime.datetime.now()
>             self._timeout_delta = datetime.timedelta(seconds=params.Timeout)
>         else:
>             res = (datetime.datetime.now() - self._timeout_start) < self._timeout_delta
>         return res
> 
> ps = rdFMCS.MCSParameters()
> ps.ProgressCallback = ProgressCallback()
> ps.Timeout = 10
> 
> smi1 = 'CC1(OB(OC1(C)C)c2c(OCCCN3CCN(CC3)c4c(F)cc5c(=O)c(C(O)=O)cn(C6CC6)c5c4)cccc2C=O)C'
> smi2 = 'O=C(c(cn(C7CC7)c8c9cc(F)c(N%10CCN(CC%10)CCCOc%11c(B(OC%12C[N+]([O-])=O)O)c%12ccc%11)c8)c9=O)O'
> mol1 = Chem.MolFromSmiles(smi1)
> mol2 = Chem.MolFromSmiles(smi2)
> 
> mols = [mol1,mol2]
> mcs = rdFMCS.FindMCS(mols, ps)
> 
> if mcs.canceled:
>     print("Timeout occurred")
> ```

Thank you very much. I got it.

**Comment by chmnk** [comment]
I was so happy to find this code snippet! Thank you @ptosco and @autodataming.

Would like to add that if the same `MCSParameters` object is used multiple times, `ProgressCallback` should be reinitialized between each MCS call.

For the `ProgressCallback()` defined above,
```python
ps = MCSParameters()
ps.Timeout = 2
```
```python
for i in range(3):
    t = time.time()
    # ps.ProgressCallback.__init__()
    mcs = FindMCS([mol1, mol2], parameters=ps)
    print('Num atoms & time', mcs.numAtoms, time.time() - t)
    if mcs.canceled:
        print("Timeout occurred")
```
will result in an early stopping:
```
Num atoms & time 39 2.0076920986175537
Timeout occurred
Num atoms & time 4 0.004143238067626953
Timeout occurred
Num atoms & time 4 0.001249074935913086
Timeout occurred
```
And
```python
for i in range(3):
    t = time.time()
    ps.ProgressCallback.__init__()
    mcs = FindMCS([mol1, mol2], parameters=ps)
    print('Num atoms & time', mcs.numAtoms, time.time() - t)
    if mcs.canceled:
        print("Timeout occurred")
```
will give the correct result.
```
Num atoms & time 39 2.0075180530548096
Timeout occurred
Num atoms & time 39 2.0098705291748047
Timeout occurred
Num atoms & time 39 2.009474754333496
Timeout occurred
```
