### ISSUE TITLE
Feature Request: Multiline legend in MolsToGridImage

### ISSUE THREAD

**Issue by gmseabra** [rdkit/rdkit#3093]
RDKit 2019.09.2

Thanks a lot for this great work guys!

This is actually a feature request. It would be nice to have the possibility to add multi-line legends when drawing molecules.

I did try what's described [here]|(https://sourceforge.net/p/rdkit/mailman/message/35561198/), but that doesn't seem to work, and a blank rectangle is printed in place of the newline symbols.

I presented this issue in the mailing list [here](https://sourceforge.net/p/rdkit/mailman/message/36975490/), and was advised by @greglandrum to open this issue here.

Also, as @DavidACosgrove reminded, it it would be important that the legend fond should also scale, and have its own part in the drawing area, so that the molecule does not covers the legend.

All the best,
Gustavo.

**Comment by autodataming** [comment]
```py
display(img)
print(legend1)
print(legned2)
```

**Comment by elcaceres** [comment]
Below is a work-around function I made in the interim using matplotlib. You may need to play around with figsize, but it worked for n=22 molecules for me

 Note: if y-offset is large in the positive direction, the bottom of your last legends will be cut off. You can check the annotation 'correctness' by turning on legends=labels in MolsToGridImage.

```
import matplotlib.pyplot as plt
from rdkit.Chem.Draw import MolsToGridImage


def grid_mols_with_annotation(mols, labels, sub_img_size=250, mols_per_row=5, title="", annotation_size=20, title_size=25, y_offset=-20):
    """Annotates a MolsToGridImage given a set of labels for each mol with better font size options and title"""
    
    img = MolsToGridImage(mols, molsPerRow=mols_per_row, subImgSize=(sub_img_size, sub_img_size), returnPNG=False)
    
    fig, ax = plt.subplots(figsize=(40,40))
    plt.title(title, fontsize=title_size)
    text_pos = (sub_img_size/2, sub_img_size+y_offset)
    pos_ctr = 0
    plt.axis("off")
    for cmpd_text in labels:
        plt.annotate(cmpd_text, text_pos, fontsize=30, horizontalalignment='center')
        pos_ctr += 1
        text_pos = (text_pos[0]+sub_img_size, text_pos[1])
        if (pos_ctr % mols_per_row) == 0:
            text_pos = (sub_img_size/2, text_pos[1] + sub_img_size)

    ax.imshow(img, origin="upper")

```

**Comment by DavidACosgrove** [comment]
Hi @elcaceres,
This should now be possible in the latest version of RDKit.  Just put a newline in the string you are using as the legend. 
Regards,
Dave

**Comment by MachineGUN001** [comment]
> This should now be possible in the latest version of RDKit. Just put a newline in the string you are using as the legend.
> Regards,

hi, Dave,

could you please provide examples to show how to show multiline legends in MolsToGrid, by using the lates version of rdkit you mentioned?
many many thanks,

best,
Sh_y

**Comment by MachineGUN001** [comment]
> leg\nend

many thanks for your example.

**Comment by MachineGUN001** [comment]
> ```
> from rdkit import Chem
> from rdkit.Chem import Draw
> from rdkit.Chem.Draw import rdMolDraw2D, rdDepictor
> from rdkit.Chem.Draw import IPythonConsole
> from IPython.display import SVG
> from rdkit import rdBase
> print(rdBase.rdkitVersion)
> rdDepictor.SetPreferCoordGen(True)
> 
> 
> smis = ["F[Pd]1(Cl)<-Cl[Pd](Cl)(Cl)Cl->1",
>        "F[Pd]1(Cl)<-Cl[Pd](Cl)(Cl)Cl->1", "F[Pd]1(Cl)Cl->[Pd](Cl)(Cl)<-Cl1"]
> legs = ['leg\nend', 'multi\nline', 'single line']
> 
> mols = [Chem.MolFromSmiles(smi) for smi in smis]
> Draw.MolsToGridImage(mols,subImgSize=(300,250), legends=legs)
> ```

hi, Dave, 

Do you have a way to adjust the font size of the legends? while  the multiline legends were implements, they looks  much smaller than normal.

many thanks,

Shengyang

**Comment by DavidACosgrove** [comment]
Hi Shengyang,
You can increase the legend font size using the legendFontSize draw option, but the issue here is that the bottom 10% of the image is given over to the legend, and the font size is reduced so that the legend fits into that area.  If you want a bigger legend, you have to increase both the font size and the legend area:
```
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import rdMolDraw2D, rdDepictor
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG
from rdkit import rdBase
print(rdBase.rdkitVersion)
rdDepictor.SetPreferCoordGen(True)

smis = ["F[Pd]1(Cl)<-Cl[Pd](Cl)(Cl)Cl->1",
       "F[Pd]1(Cl)<-Cl[Pd](Cl)(Cl)Cl->1", "F[Pd]1(Cl)Cl->[Pd](Cl)(Cl)<-Cl1"]
legs = ['leg\nend', 'multi\nline', 'single line']
opts = Draw.MolDrawOptions()
opts.legendFraction = 0.25
opts.legendFontSize = 25
mols = [Chem.MolFromSmiles(smi) for smi in smis]
Draw.MolsToGridImage(mols,subImgSize=(300,250), legends=legs, drawOptions=opts)
```

HTH,
Dave

**Comment by MachineGUN001** [comment]
> Hi Shengyang, You can increase the legend font size using the legendFontSize draw option, but the issue here is that the bottom 10% of the image is given over to the legend, and the font size is reduced so that the legend fits into that area. If you want a bigger legend, you have to increase both the font size and the legend area:
> 
> ```
> from rdkit import Chem
> from rdkit.Chem import Draw
> from rdkit.Chem.Draw import rdMolDraw2D, rdDepictor
> from rdkit.Chem.Draw import IPythonConsole
> from IPython.display import SVG
> from rdkit import rdBase
> print(rdBase.rdkitVersion)
> rdDepictor.SetPreferCoordGen(True)
> 
> smis = ["F[Pd]1(Cl)<-Cl[Pd](Cl)(Cl)Cl->1",
>        "F[Pd]1(Cl)<-Cl[Pd](Cl)(Cl)Cl->1", "F[Pd]1(Cl)Cl->[Pd](Cl)(Cl)<-Cl1"]
> legs = ['leg\nend', 'multi\nline', 'single line']
> opts = Draw.MolDrawOptions()
> opts.legendFraction = 0.25
> opts.legendFontSize = 25
> mols = [Chem.MolFromSmiles(smi) for smi in smis]
> Draw.MolsToGridImage(mols,subImgSize=(300,250), legends=legs, drawOptions=opts)
> ```
> 
> HTH, Dave

hi, Dave,

that looks much better! works for me. many thanks,
This problem of legend fontsize has been bothering me for a long time. Thank you for helping me to solve this problem. Thanks again.

Best,

Shengyang
