### ISSUE TITLE
Canonical smiles is unexpectedly different after standardization

### ISSUE THREAD

**Issue by mc-robinson** [rdkit/rdkit#3094]
RDKit Version:
'2019.09.3' 

I am not sure if I should post this in https://github.com/chembl/ChEMBL_Structure_Pipeline or here, but I figured this is the best place to ask since that uses a lot RDKit code:

Essentially I am getting a weird error where the "canonical" output of Chem.MolToSmiles is not the same.

I have tried to produce a reproducible example below:

```
s1 = Chem.MolToSmiles(standardizer.standardize_mol(Chem.MolFromSmiles('CC(=O)N1CCN(Cc2c(Cl)c(F)c(-c3ncnc(C)c3)cc2)CC1')))
s1
[Out] 'CC(=O)N1CCN(Cc2c(Cl)c(F)c(-c3ncnc(C)c3)cc2)CC1'

s2 = Chem.MolToSmiles(standardizer.standardize_mol(Chem.MolFromSmiles('CC(=O)N1CCN(Cc2ccc(-c3cc(C)ncn3)c(F)c2Cl)CC1')))
s2
[Out] 'CC(=O)N1CCN(Cc2ccc(-c3cc(C)ncn3)c(F)c2Cl)CC1'

s1 == s2
[Out] False
```

However, the code below gives the same SMILES

```
s11 = Chem.MolToSmiles(Chem.MolFromSmiles(s1))
s22 = Chem.MolToSmiles(Chem.MolFromSmiles(s2))

s11 == s22
[Out] True
```

Thanks, and sorry if this is a dumb oversight of something simple on my part.

**Comment by bp-kelley** [comment]
I agree that the output from the standardizer should be canonical.  I would tend to label this as a bug.

**Comment by greglandrum** [comment]
What's going on here is that the molecules that come back from the standardizer have not been sanitized. If you do sanitize them everything works fine:
```
In [3]: m1 = standardizer.standardize_mol(Chem.MolFromSmiles('CC(=O)N1CCN(Cc2c(Cl)c(F)c(-c3ncnc(C)c3)cc2)CC1'))

In [4]: m2 = standardizer.standardize_mol(Chem.MolFromSmiles('CC(=O)N1CCN(Cc2ccc(-c3cc(C)ncn3)c(F)c2Cl)CC1'))

In [5]: Chem.MolToSmiles(m1)==Chem.MolToSmiles(m2)
Out[5]: False

In [6]: Chem.SanitizeMol(m1)
Out[6]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [7]: Chem.SanitizeMol(m2)
Out[7]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [8]: Chem.MolToSmiles(m1)==Chem.MolToSmiles(m2)
Out[8]: True
```
@eloyfelix : we should probably document this in the standardizer docs.

**Comment by greglandrum** [comment]
@eloyfelix : Another alternative, which probably makes the most sense long-term, would be for us to include an optional "sanitize" argument to `standardize_mol()` that defaults to True.
I will create an issue for that.

**Comment by eloyfelix** [comment]
it definitely makes sense to us to add this argument, already replied our repo. 
thanks all for looking into it :)

**Comment by mc-robinson** [comment]
Thanks all, nice to wake up and see lots of responses. Glad I now know what the cause is, and will look forward to the new PR
