### ISSUE TITLE
bug: the MCS of the molecules CH4 and CH3OH is empty. how to return C? 

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3095]
**Configuration:**

- RDKit Version:2020.03
- Operating system:linux
- Python version (if relevant): 3.7
- Are you using conda?yes
- If you are using conda, which channel did you install the rdkit from?rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

the MCS of the molecules CH4 and CH3OH is empty. how to return C? 

```
from rdkit import Chem
from rdkit.Chem import rdFMCS
import rdkit
mol1 = Chem.MolFromSmiles("C")
mol2 = Chem.MolFromSmiles("OC")

mols = [mol1,mol2]
res=rdFMCS.FindMCS(mols,bondCompare=rdkit.Chem.rdFMCS.BondCompare.CompareAny)
common=Chem.MolFromSmarts(res.smartsString)
common
print(res.smartsString)
```

**Comment by ptosco** [comment]
@autodataming Thanks for reporting this bug; I'll fix it as soon as I have a bit of time.

**Comment by autodataming** [comment]
> @autodataming Thanks for reporting this bug; I'll fix it as soon as I have a bit of time.

Thank you!

**Comment by greglandrum** [comment]
Though I agree that it makes sense to change the behavior, we should be clear that it's not really a bug. The current code operates on bonds, not atoms, so not returning single-atom matches is intended.

**Comment by autodataming** [comment]
> 
> 
> Though I agree that it makes sense to change the behavior, we should be clear that it's not really a bug. The current code operates on bonds, not atoms, so not returning single-atom matches is intended.

Thank You!
