### ISSUE TITLE
drawOptions().addStereoAnnotation = True Does not work on with rdMolDraw2D.MolDraw2DSVG

### ISSUE THREAD

**Issue by ValeryPolyakov** [rdkit/rdkit#3103]
I am using the latest RDkit on Windows with Python 3.8.1 (64bit). The following function ignores drawer.drawOptions().addStereoAnnotation = True, on the other hand, drawer.drawOptions().addAtomIndices = True work. Here is the function:

def Mol2svg(mol, molSize=(450,250), kekulize=True, fontSize = 0.8, LineWidth = 1):
	
	from rdkit.Chem import rdDepictor
	from rdkit.Chem.Draw import rdMolDraw2D
	svg = None
	
	#sometimes, I may have a defective molecule 
	if mol is None:
		return None

	mol = rdMolDraw2D.PrepareMolForDrawing(mol, kekulize)
	mc = Chem.Mol(mol.ToBinary())
			
	drawer = rdMolDraw2D.MolDraw2DSVG(molSize[0], molSize[1])
	drawer.SetFontSize(fontSize)
	drawer.drawOptions().addStereoAnnotation = True
	drawer.drawOptions().addAtomIndices = True

	try:
		drawer.SetLineWidth(LineWidth)
	except:
		pass

	drawer.DrawMolecule(mc)
	drawer.FinishDrawing()
	svg = drawer.GetDrawingText()
	return svg

**Comment by greglandrum** [comment]
Hmm. it certainly works on linux:
https://gist.github.com/greglandrum/33d8bd8149ec35999b2c70af9e4a0811
(I made a few small changes to your function, but those shouldn't make a difference)

**Comment by greglandrum** [comment]
Just tested that gist on windows and it works fine there too.
Are you sure that you are using the 2020.03 version of the RDKit?

**Comment by ValeryPolyakov** [comment]
Hi Greg, 

Your modified code works now for me! 
Thanks a lot for the prompt response and for your help. 

Valery
