### ISSUE TITLE
how to ignore the bond order in the HasSubstructMatch method?

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3104]
**Configuration:**

- RDKit Version:   2019.03
- Operating system:  linux
- Python version (if relevant): 3.6
- Are you using conda?  YES
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

how to ignore the bond order in the HasSubstructMatch method?
example: 
```
I wish 'C[Si](C)(C)C#N'  contain the 'CN' fragemnt return True.


```
does 

```py
mol = Chem.MolFromSmiles('C[Si](C)(C)C#N')
frag = Chem.MolFromSmiles('CN')

matched = mol.HasSubstructMatch(frag)
print(matched)  #False 
```

how to ignore the bond order in the HasSubstructMatch method as the following?
```
matched = mol.HasSubstructMatch(frag,ignorebondoreder=True)
```

**Comment by zealseeker** [comment]
You can use `C~N` , where `~` means "any bond".
```
mol = Chem.MolFromSmiles('C[Si](C)(C)C#N')
frag = Chem.MolFromSmiles('C~N')

matched = mol.HasSubstructMatch(frag)
print(matched)  # True 
```

A more complex way might be to modify all bonds in `frag` into "any bond". But I don't think there is any reason to do so.

**Comment by autodataming** [comment]
> 
> 
> You can use `C~N` , where `~` means "any bond".
> 
> ```
> mol = Chem.MolFromSmiles('C[Si](C)(C)C#N')
> frag = Chem.MolFromSmiles('C~N')
> 
> matched = mol.HasSubstructMatch(frag)
> print(matched)  # True 
> ```
> 
> A more complex way might be to modify all bonds in `frag` into "any bond". But I don't think there is any reason to do so.
Thank you. It's a trick solution.
