### ISSUE TITLE
RDKit references

### ISSUE THREAD

**Issue by shiyu22** [rdkit/rdkit#3105]
My article uses RDKit, how do I add references?

**Comment by thegodone** [comment]
we generally use this reference in papers
Landrum, G. 2010. “RDKit.” Q2. https://www.rdkit.org/.

**Comment by greglandrum** [comment]
Yeah, there's no official reference. 
My usual suggestion is to do something like:
"RDKit: Open-source cheminformatics. https://www.rdkit.org"
It's a good idea to cite the specific version that you used. For that there's also always a DOI available for each version. You can look those DOIs up here:
https://zenodo.org/record/3732262

**Comment by shiyu22** [comment]
Thanks for your suggestions, by the way, this is a great project！

**Comment by greglandrum** [comment]
Thanks for the positive feedback! :-)

**Comment by SebastianWellig** [comment]
How has this excellent tool no publication of its own yet?

**Comment by greglandrum** [comment]
@SebastianWellig thanks for the positive feedback!
There’s no RDKit paper because I’m not fond of writing papers and because I don’t think it will make the RDKit any better. :-)

**Comment by gmaikelc** [comment]
Thanks for the suggestion for the citation. A great project and excellent tool!
