### ISSUE TITLE
No hydrogens (neither implicit nor explicit) are added to mol2 file

### ISSUE THREAD

**Issue by and-tos** [rdkit/rdkit#3106]
When loading a binding site mol2 file (see attached example, change .txt to .mol2), no hydrogens are added (neither implicit, nor explicit).
Also, trying to manually add hydrogens does not work.

[13GS_013.txt](https://github.com/rdkit/rdkit/files/4514803/13GS_013.txt)

```
import rdkit
rdkit.__version__
'2020.03.1'

m = Chem.MolFromMol2File('13GS_013.mol2')
[10:18:31] 13GS_013: Warning - no explicit hydrogens in mol2 file but needed for formal charge estimation.
m.GetAtomWithIdx(4).GetTotalNumHs()
0
m_h = Chem.AddHs(m)
m_h.GetAtomWithIdx(4).GetTotalNumHs()
0


```

**Comment by bp-kelley** [comment]
RDKit strips hydrogens by default in most cases, you need to add removeHs=False.

```
>>> help(Chem.MolFromMol2File)
MolFromMol2File(...)
    MolFromMol2File( (str)molFileName [, (bool)sanitize=True [, (bool)removeHs=True [, (bool)cleanupSubstructures=True]]]) -> Mol :
        Construct a molecule from a Tripos Mol2 file.
        
          NOTE:
             The parser expects the atom-typing scheme used by Corina.
            Atom types from Tripos' dbtranslate are less supported.
            Other atom typing schemes are unlikely to work.
        
          ARGUMENTS:
                                          
            - fileName: name of the file to read
        
            - sanitize: (optional) toggles sanitization of the molecule.
              Defaults to true.
        
            - removeHs: (optional) toggles removing hydrogens from the molecule.
```

**Comment by andt88** [comment]
Thank you for your comment. I don't think I was clear in my first comment. There are neither implicit, nor explicit hydrogens added to the molecule. Furthermore it is not possible to add them subsequently to the RDKit molecule object.

**Comment by xuqinghan** [comment]
Same bug for  2020.09.1. (ubuntu20.04 anaconda3 + python3.7 x64).


mol.file:(aspirin  from nmrshiftdb2 )

_2-acetoxybenzoic acid; acenterine; acetosal; acetylsalicylic acid; acylpyrin; as
     RDKit          3D

 13 13  0  0  0  0  0  0  0  0999 V2000
   -0.9036   -0.0927   -0.4190 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9821    0.7608   -0.6792 C   0  0  0  0  0  3  0  0  0  0  0  0
   -1.7883    2.1213   -0.9161 C   0  0  0  0  0  3  0  0  0  0  0  0
   -0.5031    2.6537   -0.9046 C   0  0  0  0  0  3  0  0  0  0  0  0
    0.5864    1.8260   -0.6570 C   0  0  0  0  0  3  0  0  0  0  0  0
    0.3804    0.4682   -0.3987 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1661   -1.5469   -0.1670 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8264   -0.4898    1.0859 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1839   -1.1854    1.3253 C   0  0  0  0  0  1  0  0  0  0  0  0
    1.5242   -0.3172   -0.2405 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2881   -2.0077   -0.5343 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2358   -2.1971    0.4036 O   0  0  0  0  0  1  0  0  0  0  0  0
    1.3657    0.0068    2.1016 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  1  6  1  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  1  7  1  0
  7 11  2  0
  7 12  1  0
  6 10  1  0
 10  8  1  0
  8 13  2  0
  8  9  1  0
M  RAD  6   2   2   3   2   4   2   5   2   9   2  12   2
M  END_





**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import AllChem

mol1 = Chem.MolFromMolFile('2244.mol', removeHs=False, strictParsing=False)
AllChem.Compute2DCoords(mol1)
#not work
mh = Chem.AddHs(mol1)
#print('', mh)
print(Chem.MolToMolBlock(mh))
```

output is still without any H atom.

_2-acetoxybenzoic acid; acenterine; acetosal; acetylsalicylic acid; acylpyrin; as
     RDKit          2D

 13 13  0  0  0  0  0  0  0  0999 V2000
   -1.2691   -0.2007    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3827    0.8043    0.0000 C   0  0  0  0  0  3  0  0  0  0  0  0
   -2.0691    2.2711    0.0000 C   0  0  0  0  0  3  0  0  0  0  0  0
   -0.6420    2.7330    0.0000 C   0  0  0  0  0  3  0  0  0  0  0  0
    0.4715    1.7281    0.0000 C   0  0  0  0  0  3  0  0  0  0  0  0
    0.1580    0.2612    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5826   -1.6676    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.6987   -0.2818    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8123   -1.2868    0.0000 C   0  0  0  0  0  1  0  0  0  0  0  0
    1.2716   -0.7438    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4690   -2.6725    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0097   -2.1295    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
    3.0122    1.1850    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  1  6  1  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  1  7  1  0
  7 11  2  0
  7 12  1  0
  6 10  1  0
 10  8  1  0
  8 13  2  0
  8  9  1  0
M  RAD  6   2   2   3   2   4   2   5   2   9   2  12   2
M  END_

**Comment by danny305** [comment]
RDKit version  2021.03.2
I just copied the codes from ^^ and I do not get any atoms added. 

Is this going to get resolved??

**Comment by josejimenezluna** [comment]
Still an issue in `2022.03.4`.
