### ISSUE TITLE
Each time SMILES and Mol are converted, the SMILES string is rotated.

### ISSUE THREAD

**Issue by yiino** [rdkit/rdkit#3107]
**Configuration:**

- RDKit Version:2020.03.1
- Operating system:windows10
- Python version (if relevant):3.6.9
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit? conda install -c conda-forge rdkit

**Description:**

Each time converting SMILES string into Mol object and then converting it back, SMILES string changed between pattern A and B. 
The code below generates the following outputs (slash and backslash altered before the 8th capital C ) :

 rdkit version:  2020.03.1
 pandas version:  1.0.3
C1=C2\N=C(/C=c3/c4ccccc4/c4n3[Ni]n3c/1c1ccccc1c3/C=C1\N=C(\C=4)c3ccccc31)c1ccccc12
C1=C2\N=C(/C=c3/c4ccccc4/c4n3[Ni]n3c/1c1ccccc1c3/C=C1\N=C(/C=4)c3ccccc31)c1ccccc12
C1=C2\N=C(/C=c3/c4ccccc4/c4n3[Ni]n3c/1c1ccccc1c3/C=C1\N=C(\C=4)c3ccccc31)c1ccccc12
C1=C2\N=C(/C=c3/c4ccccc4/c4n3[Ni]n3c/1c1ccccc1c3/C=C1\N=C(/C=4)c3ccccc31)c1ccccc12

```
from rdkit import rdBase, Chem, DataStructs
from rdkit.Chem import AllChem, Draw
import pandas as pd
 
print('rdkit version: ',rdBase.rdkitVersion)
print('pandas version: ', pd.__version__)

sm='C1=C2\\N=C(/C=c3/c4ccccc4/c4n3[Ni]n3c/1c1ccccc1c3/C=C1\\N=C(\\C=4)c3ccccc31)c1ccccc12'
print(sm)
mol = Chem.MolFromSmiles(sm)
sm = Chem.MolToSmiles(mol)
print(sm)
mol = Chem.MolFromSmiles(sm)
sm = Chem.MolToSmiles(mol)
print(sm)
mol = Chem.MolFromSmiles(sm)
sm = Chem.MolToSmiles(mol)
print(sm)
```

**Comment by bp-kelley** [comment]
This is still an issue in 2024.09, it looks like stereo is being inverted which is certainly a bug, bug perhaps a hard to fix one.

<img width="527" alt="image" src="https://github.com/user-attachments/assets/502bb4ea-4c9d-45a7-a1c2-bd64c4efa5f0">
