### ISSUE TITLE
Add support for multiple-line strings when drawing

### ISSUE THREAD

**Issue by and-tos** [rdkit/rdkit#3112]
When drawing strings, line breaks are replaced by blank space.

```
>>>rdkit.__version__
'2020.03.1'
>>>d = rdMolDraw2D.MolDraw2DCairo(250, 250)
>>>d.drawOptions().addAtomIndices = True
>>>rdMolDraw2D.PrepareAndDrawMolecule(d, mol, highlightAtoms=unmatched_atoms, legend='line1\nline2')
```
![mol_0](https://user-images.githubusercontent.com/36545428/80197388-d9d55880-861e-11ea-8130-4e8ac7f1cdc5.png)

**Comment by greglandrum** [comment]
Yes, this is a known shortcoming of the current code: it doesn't properly handle line breaks.
