### ISSUE TITLE
Installation impossible with Windows 10 and Python

### ISSUE THREAD

**Issue by JurajMa** [rdkit/rdkit#3113]
I couldn't install rdkit on Windows 10 following the installation procedure described in:
https://rdkit.org/docs/Install.html#installation-of-rdkit-binaries
for the installation from binaries.

On a side note, I don't understand this line of the instructions:

> PATH: add ;%RDBASE%\lib to the end

considering that `\lib` doesn't exist in the complete file structure of the latest release (rdkit-Release_2020_03_01).

Upon importing rdkit there are many issues finding the modules being imported.
The main one is that on several locations in the code, the Python module `rdBase` cannot be found. It doesn't seem to exist within the `rdkit` module. The issue has been raised by others, already in 2017  #1634 .

There are other similar import problems, for example:

`from rdkit.DataStructs import cDataStructs` in `DataStructs\__init__.py`, where `cDataStructs` also doesn't exist.

These seem to be critical errors.

**Comment by greglandrum** [comment]
Just to be sure I understand: you built the code yourself on windows?

Given that it's much easier to just `conda install` the rdkit, particularly on windows, do you have some reason that you need to build the code?

**Comment by JurajMa** [comment]
No, I did the installation from the zipped binaries, sorry I used the wrong link above, I corrected it now.

I cannot use conda unfortunately, as I have to run it in a different virtual environment.
The zipped release seems to have these issues I am mentioning above.

**Comment by greglandrum** [comment]
Oh, it's been years since we updated the zipped binaries since they are basically impossible to support. We really should get that section out of the docs.

I'm afraid that there aren't currently any good options for a windows binary install unless you can use conda.

**Comment by JurajMa** [comment]
I tried compiling from source now. No success. 
It would be really great if you could supply windows 10 binaries or make installation possible with pip somewhere in the future.

But ofc, I understand the time requirement.

**Comment by autodataming** [comment]
> I cannot use conda unfortunately,

conda can create different virtual environment.

```
conda create -n env2rdkt python=3.7
conda activate env2rdkit
```
why not try to use conda install rdkit?

**Comment by JurajMa** [comment]
Because I cannot use a conda virtual environment. I am running a web server with different specifications, with `rdkit` being only a part of the setup.

If conda is a requirement for rdkit, it should probably be added to the requirements list.

**Comment by greglandrum** [comment]
Conda is absolutely not a requirement for the RDKit. 
Conda makes it easy to install the RDKit.

Since the RDKit team is a small group of volunteers, we can't possibly support providing binaries without all the infrastructure that conda provides to handle dependencies.

Since we've not been able to make the RDKit work with pip, if you are not able to use conda, your options are basically to either build the toolkit yourself (which I realize is non-trivial), or find someone to build it for you.
