### ISSUE TITLE
fixedBondLength ignored by MolDraw2D::drawMolecules

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3114]
This seems to be an oversight in the implementation.

Here's a quick illustration:
![image](https://user-images.githubusercontent.com/540511/80207810-26c12b00-862f-11ea-9526-9b7f14b8d1b9.png)

note that things work fine with `drawMolecule()`

**Comment by manangoel99** [comment]
@greglandrum can I take this up?
