### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by yyou1996** [rdkit/rdkit#3118]
**Configuration:**

- RDKit Version: 2019.03.1
- Operating system: Ubuntu 16.04.5 LTS
- Python version (if relevant):
Name |                   Version |                  Build | Channel                                                                                                                                           
python |                   3.6.10 |              h191fe78_1     |                                                                                                                                               
python-dateutil  |         2.8.1       |               py_0     |                                                                                                                                               
python_abi         |       3.6               |      1_cp36m  |  conda-forge
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from?
Name        |            Version             |      Build | Channel                                                                                                                                           
rdkit            |         2019.03.1    |    py36h9c20d5c_0 |   conda-forge
- If you are not using conda: how did you install the RDKit?

**Description:**

Traceback (most recent call last):                                                                                                                                                                             
File "pretrain_graphcl.py", line 3, in <module>                                                                                                                                                                
from loader import MoleculeDataset                                                                                                                                                                         
File "/home/tlchen/yuning_dir/pretrain-gnns/chem/loader.py", line 9, in <module>                                                                                                                               
from rdkit import Chem                                                                                                                                                                                     
File "/home/tlchen/anaconda3/envs/gnnrdkit/lib/python3.6/site-packages/rdkit/Chem/__init__.py", line 18, in <module>                                                                                           
from rdkit import DataStructs                                                                                                                                                                              
File "/home/tlchen/anaconda3/envs/gnnrdkit/lib/python3.6/site-
packages/rdkit/DataStructs/__init__.py", line 13, in <module>                                                                                    
from rdkit.DataStructs import cDataStructs

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/tlchen/anaconda3/envs/gnnrdkit/lib/python3.6/site-packages/rdkit/DataStructs/../../../../libRDKitDataStructs.so.1)

**Comment by greglandrum** [comment]
Hi @yyou1996 : 
Can you please try:
```
conda install -c conda-forge libgcc
```
and see if that clears up the problem?

**Comment by yyou1996** [comment]
Hi @greglandrum :

Thank you for your reply. However, it does not work for me.

**Comment by greglandrum** [comment]
@mcs07 I think this could be a problem with the dependencies of the conda-forge rdkit build. Any thoughts?

**Comment by mcs07** [comment]
It's odd that `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` is being loaded. It should be using the one provided by conda at `$CONDA_PREFIX/lib/libstdc++.so.6`.

I did the following to roughly replicate the environment:

```bash
$ docker run --rm -it continuumio/miniconda3 /bin/bash
$ conda install python=3.6
$ conda install -c conda-forge rdkit
```

Then did `ldd` on `libRDKitDataStructs.so.1`:

```bash
$ cd $CONDA_PREFIX/lib
$ ldd libRDKitDataStructs.so.1
	linux-vdso.so.1 (0x00007ffd83fa8000)
	libRDKitRDGeneral.so.1 => /opt/conda/lib/././libRDKitRDGeneral.so.1 (0x00007f5fb7f54000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5fb7f2f000)
	libstdc++.so.6 => /opt/conda/lib/././libstdc++.so.6 (0x00007f5fb7dbb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5fb7c38000)
	libgcc_s.so.1 => /opt/conda/lib/././libgcc_s.so.1 (0x00007f5fb7c24000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5fb7a63000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5fb8073000)
```

This lib comes from the `libstdcxx-ng` package which should show up in `conda list`. If not, you could `conda install libstdcxx-ng` but it really should already be there?

Is it possible that `LD_LIBRARY_PATH` or `RDBASE` are set in a way that is resulting in the wrong dynamic library being resolved? Both should be left unset when installing RDKit from conda.

**Comment by yyou1996** [comment]
> It's odd that /usr/lib/x86_64-linux-gnu/libstdc++.so.6 is being loaded. It should be using the one provided by conda at $CONDA_PREFIX/lib/libstdc++.so.6.
> I did the following to roughly replicate the environment:
> $ docker run --rm -it continuumio/miniconda3 /bin/bash
> $ conda install python=3.6
> $ conda install -c conda-forge rdkit
> Then did ldd on libRDKitDataStructs.so.1:
> $ cd $CONDA_PREFIX/lib
> $ ldd libRDKitDataStructs.so.1
> 	linux-vdso.so.1 (0x00007ffd83fa8000)
> 	libRDKitRDGeneral.so.1 => /opt/conda/lib/././libRDKitRDGeneral.so.1 (0x00007f5fb7f54000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5fb7f2f000)
> 	libstdc++.so.6 => /opt/conda/lib/././libstdc++.so.6 (0x00007f5fb7dbb000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5fb7c38000)
> 	libgcc_s.so.1 => /opt/conda/lib/././libgcc_s.so.1 (0x00007f5fb7c24000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5fb7a63000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007f5fb8073000)
> This lib comes from the libstdcxx-ng package which should show up in conda list. If not, you could conda install libstdcxx-ng but it really should already be there?
> Is it possible that LD_LIBRARY_PATH or RDBASE are set in a way that is resulting in the wrong dynamic library being resolved? Both should be left unset when installing RDKit from conda.

Thanks a lot. I solve it by adding $CONDA_PREFIX/lib path into LD_LIBRARY_PATH following https://stackoverflow.com/questions/46826497/conda-set-ld-library-path-for-env-only.

You can close this issue anytime you want. Thanks! @mcs07 @greglandrum
