### ISSUE TITLE
Problems related with implicit hydrogen in SMARTS reaction. 

### ISSUE THREAD

**Issue by jungsdao** [rdkit/rdkit#3121]
**Configuration:**

- RDKit Version: 2018.09.1
- Operating system: Ubuntu 18.04.4 LTS 
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda-forge

**Description:**

I'm trying to describe reaction involving radicals using SMARTS. 
One of the reactant is radical and product should be radical as well. 
However, when I do RunReactants, I get a closed shell molecule. 
`Chem.MolFromSmiles('C=C(CC(CC(CC(CC(CCc1ccccc1)c1ccccc1)c1ccccc1)c1ccccc1)c1ccccc1)c1ccccc1')`
Is there anything  wrong with my SMARTS string?
There had been no problem with other kinds of reaction with radical but it doesn't work for this problem. 
Any hints or comment would be appreciated. 

```
[rxn = rdChemReactions.ReactionFromSmarts('[CH2:1]-[CH1&v3:2].[CH2:3]=[C:4]>>[CH2:1]-[CH1:2]-[CH2:3]-[CH0&v3:4]')
rxn

ps = rxn.RunReactants((Chem.MolFromSmiles('C=C(CC(C[CH]c1ccccc1)c1ccccc1)c1ccccc1'),
                       Chem.MolFromSmiles('C=C(CC(CCc1ccccc1)c1ccccc1)c1ccccc1')))
print("Num products : ", len(ps))
Chem.MolToSmiles(ps[0][0])
#uniq = set([Chem.MolToSmiles(x[0],isomericSmiles=True) for x in ps])
#print(uniq)
print(Descriptors.NumRadicalElectrons(ps[0][0]))
#print("Unique products:",sorted(uniq))
Chem.MolToSmiles(ps[0][0])]
```

**Comment by greglandrum** [comment]
@jungsdao : the products of reactions have not been sanitized, which means that the presence/absence of radicals has not yet been re-calculated.
Try doing `Chem.SanitizeMol(ps[0][0])` before you generate the SMILES.

**Comment by jingxingzhi** [comment]
> @ jungsdao：尚未对反应产物进行消毒，这意味着尚未重新计算自由基的存在/不存在。生成SMILES之前先
> 尝试做`Chem.SanitizeMol(ps[0][0])`。

same issues, how to express atom without H by smarts(some times was free radicals)
[CH0], [OH0]，[NH0] not works
