### ISSUE TITLE
Getting the right sequence of atoms in a ring

### ISSUE THREAD

**Issue by ethan0879** [rdkit/rdkit#3122]
When I run this in UNIX,
m = Chem.MolFromMolFile('B2C6H2F6.mol')
ssr = Chem.GetSymmSSSR(m)
list(ssr[0])

I get that,
[0, 1, 2, 3, 4]

But I am interested in getting the right sequence of atoms of such molecule, i.e. 1,2,3,4,5
How can I get it?

**Comment by ptosco** [comment]
@ethan0879 Do you mean 1-based as opposed to 0-based?
If that's the case, replace
```
list(ssr[0])
```
with
```
[i+1 for i in ssr[0]]
```

**Comment by ethan0879** [comment]
Thanks! One more question, how can I list all the rings at the same time? I have tried,

`[i+1 for i in ssr[len(ssr)]] `

But did not work.

**Comment by ptosco** [comment]
```
[[i+1 for i in r] for r in ssr]
```

**Comment by ethan0879** [comment]
Thanks!!

**Comment by ethan0879** [comment]
I noticed that for heterocycles, the Chem.GetSymmSSSR function does not give the write sequence of the ring. Instead of taking the heteroatom, it takes a hydrogen. 

You can see an example here (https://ibb.co/2kkT2Xx). The function gives me,
[1, 11, 6, 5, 4, 3, 2]

instead of

[1, 19, 6, 5, 4, 3, 2]

Any solution for that?
