### ISSUE TITLE
how  to consider   Aromatic of atom in FindMCS ? 

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3123]
**Configuration:**

- RDKit Version: 2020.03
- Operating system: LINUX
- Python version (if relevant): 3.7
- Are you using conda? YES
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?  

**Description:**

how  to consider   Aromatic of atom in atomcompore of FindMCS ? 

```py
from rdkit import Chem
import rdkit
mol1 = Chem.MolFromSmiles('COc1cc(CC(=O)O)ccc1NC(=O)Nc1ccccc1Br')
mol2 = Chem.MolFromSmiles('COc1ccccc1C(=O)ON1CCCC1')
mols =[mol1,mol2]
res = rdFMCS.FindMCS(mols)

maxcom = Chem.MolFromSmarts(res.smartsString)
print(res.smartsString)
display(maxcom)
select_leftpmol(mol1,maxcom)
select_leftpmol(mol2,maxcom)
display(mol1)
display(mol2)
```

![图片](https://user-images.githubusercontent.com/7656130/80565954-623f6900-8a24-11ea-917f-88e256e76b3d.png)

strict bondCompare.
```PY
from rdkit import Chem
import rdkit
mol1 = Chem.MolFromSmiles('COc1cc(CC(=O)O)ccc1NC(=O)Nc1ccccc1Br')
mol2 = Chem.MolFromSmiles('COc1ccccc1C(=O)ON1CCCC1')
mols =[mol1,mol2]
res = rdFMCS.FindMCS(mols,bondCompare=rdkit.Chem.rdFMCS.BondCompare.CompareOrderExact)

maxcom = Chem.MolFromSmarts(res.smartsString)
print(res.smartsString)
display(maxcom)
select_leftpmol(mol1,maxcom)
select_leftpmol(mol2,maxcom)
display(mol1)
display(mol2)
```
![图片](https://user-images.githubusercontent.com/7656130/80566120-ca8e4a80-8a24-11ea-8512-913454ec684f.png)

I try to  consider   Aromatic of atom in FindMCS,but it failed.
The code as following.

```py
class CompareElementsAndAromatic(rdFMCS.AtomCompare):
    def compare(self, p, mol1, atom1, mol2, atom2):
        a1 = mol1.GetAtomWithIdx(atom1)
        a2 = mol2.GetAtomWithIdx(atom2)

        if (a1.GetAtomicNum() != a2.GetAtomicNum()):
            return False
        if a1.GetIsAromatic() != a2.GetIsAromatic():
            return False

        return True
car = CompareElementsAndAromatic()

from rdkit import Chem
import rdkit
mol1 = Chem.MolFromSmiles('COc1cc(CC(=O)O)ccc1NC(=O)Nc1ccccc1Br')
mol2 = Chem.MolFromSmiles('COc1ccccc1C(=O)ON1CCCC1')
mols =[mol1,mol2]
res = rdFMCS.FindMCS(mols,atomCompare=car)

maxcom = Chem.MolFromSmarts(res.smartsString)
print(res.smartsString)
display(maxcom)
select_leftpmol(mol1,maxcom)
select_leftpmol(mol2,maxcom)
display(mol1)
display(mol2)
```

![图片](https://user-images.githubusercontent.com/7656130/80566328-4ee0cd80-8a25-11ea-9578-dbca5cb430b7.png)

**Comment by sirbiscuit** [comment]
Hey @autodataming,

in the [RDKit cookbook](https://rdkit.readthedocs.io/en/latest/Cookbook.html#using-custom-mcs-atom-types), you can find a (really ugly) hack to use custom atom types in the MCS method:

```python
from rdkit import Chem
from rdkit.Chem import rdFMCS, Draw

mol1 = Chem.MolFromSmiles('COc1cc(CC(=O)O)ccc1NC(=O)Nc1ccccc1Br')
mol2 = Chem.MolFromSmiles('COc1ccccc1C(=O)ON1CCCC1')
mols =[mol1,mol2]

# for each atom, compute a value that contains all properties we care for
# and store the computed value in the isotope field
for mol in mols:
    for atom in mol.GetAtoms():
        value = 500*atom.GetIsAromatic() + atom.GetAtomicNum()
        atom.SetIsotope(value)

# compute MCS by comparing isotopes!
res = rdFMCS.FindMCS(mols, atomCompare=rdFMCS.AtomCompare.CompareIsotopes)

maxcom = Chem.MolFromSmarts(res.smartsString)
print(res.smartsString)
display(maxcom)
highlight_1 = mol1.GetSubstructMatch(maxcom)
highlight_2 = mol2.GetSubstructMatch(maxcom)
Draw.MolsToGridImage([mol1, mol2], 
                     highlightAtomLists=[highlight_1, highlight_2], 
                     subImgSize=(400,250))
```

![image](https://user-images.githubusercontent.com/8418161/80791131-fa5a6100-8b90-11ea-8355-9fe4be84075a.png)

Note: this code permanently changes the isotope values of the molecules (which also affects the molecule drawings). The cookbook also explains how to avoid this.

I hope this helps.

**Comment by autodataming** [comment]
> 
> 
> Hey @autodataming,
> 
> in the [RDKit cookbook](https://rdkit.readthedocs.io/en/latest/Cookbook.html#using-custom-mcs-atom-types), you can find a (really ugly) hack to use custom atom types in the MCS method:
> 
> ```python
> from rdkit import Chem
> from rdkit.Chem import rdFMCS, Draw
> 
> mol1 = Chem.MolFromSmiles('COc1cc(CC(=O)O)ccc1NC(=O)Nc1ccccc1Br')
> mol2 = Chem.MolFromSmiles('COc1ccccc1C(=O)ON1CCCC1')
> mols =[mol1,mol2]
> 
> # for each atom, compute a value that contains all properties we care for
> # and store the computed value in the isotope field
> for mol in mols:
>     for atom in mol.GetAtoms():
>         value = 500*atom.GetIsAromatic() + atom.GetAtomicNum()
>         atom.SetIsotope(value)
> 
> # compute MCS by comparing isotopes!
> res = rdFMCS.FindMCS(mols, atomCompare=rdFMCS.AtomCompare.CompareIsotopes)
> 
> maxcom = Chem.MolFromSmarts(res.smartsString)
> print(res.smartsString)
> display(maxcom)
> highlight_1 = mol1.GetSubstructMatch(maxcom)
> highlight_2 = mol2.GetSubstructMatch(maxcom)
> Draw.MolsToGridImage([mol1, mol2], 
>                      highlightAtomLists=[highlight_1, highlight_2], 
>                      subImgSize=(400,250))
> ```
> 
> ![image](https://user-images.githubusercontent.com/8418161/80791131-fa5a6100-8b90-11ea-8355-9fe4be84075a.png)
> 
> Note: this code permanently changes the isotope values of the molecules (which also affects the molecule drawings). The cookbook also explains how to avoid this.
> 
> I hope this helps.

it's ugly but useful. Thank you very much!
