### ISSUE TITLE
MolDraw2DCairo does not do atom/bond annotations on Windows

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3141]
**Configuration:**

- RDKit Version: 2020.03 and master
- Operating system: Windows

**Description:**

Due to "cross-platform font fun" we disabled these annotations in PNGs on Windows. So this is a bug, but it's an intentional one (for the moment at least).

We should address this at some point in the future, but it will be tricky without adding our own font-handling code.

**Comment by DavidACosgrove** [comment]
The font-handling is coming!
