### ISSUE TITLE
The number of atoms read is different from the original file

### ISSUE THREAD

**Issue by yuyang-0825** [rdkit/rdkit#3144]
- RDKit Version:2019.09.1.0
- Operating system:win10
- Python version (if relevant):3.7.3
- Are you using conda?Yes

**Description:**
I used Chem.MolFromPDBFile() to read mol from the PDB file, but the number of atoms in the resulting mol was different from that in the original PDB, missing the atoms in the red box in the picture. Why did I get this result?

![ad85ea1225b7947b88d5df2013abb3c](https://user-images.githubusercontent.com/52021992/81285309-eaabb280-9091-11ea-8cb2-d596bec2bd79.png)

It will be appreciated if you have time to reply.

**Comment by bp-kelley** [comment]
We'll need the pdf file to validate here.

**Comment by yuyang-0825** [comment]
This is the PDB file shown in the picture .



Thank you and look forward to your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brian Kelley"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 凌晨1:36
收件人:&nbsp;"rdkit/rdkit"<rdkit@noreply.github.com&gt;;
抄送:&nbsp;"于洋"<29314133@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rdkit/rdkit] The number of atoms read is different from the original file (#3144)





 
We'll need the pdf file to validate here.

**Comment by bp-kelley** [comment]
@yuyang-0825 there doesn't appear to be a pdb file attached.

**Comment by yuyang-0825** [comment]
[2jk5.zip](https://github.com/rdkit/rdkit/files/4607246/2jk5.zip)
I sent it to you in the attachment of the email before, and the corresponding file has been added in this reply.
Thank you and look forward to your reply!

**Comment by DavidACosgrove** [comment]
Hi @yuyang-0825.  I think the issue here is that there are 2 alternative sets of coords for ARG40.  This happens when the crystallographer can see density consistent with having the ARG in 1 position or the other - crudely, half of the molecules in the crystal have ARG40 in 1 conformation, half have the other.  See the bottom of http://pdb101.rcsb.org/learn/guide-to-understanding-pdb-data/dealing-with-coordinates for more details.  I guess RDKit is giving you just the A conformation.  If you want to examine both possibilities, you could make 2 copies and remove 1 conformation from each with a text editor.  The Biopython (https://biopython.org) package has ways of dealing with this more elegantly.

**Comment by bp-kelley** [comment]
@yuyang-0825 You can read in every atom by setting the pdb flavor, but you most likely will need to set sanitize=False as when reading alternate conformations you will likely have too many bonds.

```
>>> m = MolFromPDBFile("2jk5.pdb", flavor=2)
>>> m.GetNumAtoms()
4324
>>> m = MolFromPDBFile("2jk5.pdb", flavor=1, sanitize=False)
>>> m.GetNumAtoms()
4420
```

But as @DavidACosgrove mentions, this is perhaps not what you want as you will have to deal with the alternative confirmations yourself, but in case you do, here is a small example:

```
data = """HETATM 4179  N1 ATBA C1133      -0.063   0.013  -7.530  0.13 24.23           N  
HETATM 4180  C11ATBA C1133       0.905  -0.713  -8.297  0.13 23.63           C  
HETATM 4181  C12ATBA C1133       1.432  -1.890  -7.498  0.13 23.61           C  
HETATM 4182  C21ATBA C1133      -0.798  -0.901  -6.712  0.13 24.37           C  
HETATM 4183  C22ATBA C1133      -1.752  -1.671  -7.607  0.13 24.28           C  
HETATM 4184  C31ATBA C1133      -1.031   0.739  -8.297  0.13 23.53           C  
HETATM 4185  C32ATBA C1133      -1.558   1.915  -7.498  0.13 23.60           C  
HETATM 4186  C41ATBA C1133       0.672   0.926  -6.711  0.13 24.41           C  
HETATM 4187  C42ATBA C1133       1.626   1.696  -7.607  0.13 24.24           C  
HETATM 4188  C13ATBA C1133       2.868  -1.792  -7.089  0.13 23.22           C  
HETATM 4189  C14ATBA C1133       3.509  -3.136  -6.995  0.13 23.22           C  
HETATM 4190  C23ATBA C1133      -1.946  -3.033  -7.015  0.13 24.02           C  
HETATM 4191  C24ATBA C1133      -3.337  -3.549  -7.046  0.13 24.00           C  
HETATM 4192  C33ATBA C1133      -2.994   1.818  -7.090  0.13 23.15           C  
HETATM 4193  C34ATBA C1133      -3.635   3.162  -6.995  0.13 23.38           C  
HETATM 4194  C43ATBA C1133       1.819   3.058  -7.015  0.13 24.02           C  
HETATM 4195  C44ATBA C1133       3.211   3.574  -7.046  0.13 23.98           C  
HETATM 4196  N1 BTBA C1133      -0.092  -0.052  -7.534  0.12 21.70           N  
HETATM 4197  C11BTBA C1133       0.547   0.847  -8.511  0.12 21.01           C  
HETATM 4198  C12BTBA C1133       1.885   1.359  -7.989  0.12 21.12           C  
HETATM 4199  C21BTBA C1133       0.931  -0.720  -6.713  0.12 21.75           C  
HETATM 4200  C22BTBA C1133       1.920  -1.484  -7.590  0.12 21.49           C  
HETATM 4201  C31BTBA C1133      -0.883  -1.040  -8.280  0.12 21.32           C  
HETATM 4202  C32BTBA C1133      -1.952  -1.632  -7.370  0.12 21.43           C  
HETATM 4203  C41BTBA C1133      -0.964   0.724  -6.635  0.12 21.50           C  
HETATM 4204  C42BTBA C1133      -2.063   1.428  -7.429  0.12 20.97           C  
HETATM 4205  C13BTBA C1133       1.748   2.763  -7.408  0.12 20.74           C  
HETATM 4206  C14BTBA C1133       3.082   3.278  -6.909  0.12 20.98           C  
HETATM 4207  C23BTBA C1133       2.809  -2.363  -6.718  0.12 21.25           C  
HETATM 4208  C24BTBA C1133       3.619  -3.340  -7.542  0.12 21.31           C  
HETATM 4209  C33BTBA C1133      -1.924  -3.153  -7.436  0.12 21.13           C  
HETATM 4210  C34BTBA C1133      -3.302  -3.736  -7.204  0.12 21.13           C  
HETATM 4211  C43BTBA C1133      -2.571   2.654  -6.679  0.12 20.55           C  
HETATM 4212  C44BTBA C1133      -3.799   3.242  -7.344  0.12 20.52           C """

>>> m = Chem.MolFromPDBBlock(data, flavor=1, sanitize=False)
>>> for atom in m.GetAtoms():
...     print(atom.GetPDBResidueInfo().GetName(), atom.GetPDBResidueInfo().GetAltLoc())
... 
 N1  A
 C11 A
 C12 A
 C21 A
 C22 A
 C31 A
 C32 A
 C41 A
 C42 A
 C13 A
 C14 A
 C23 A
 C24 A
 C33 A
 C34 A
 C43 A
 C44 A
 N1  B
 C11 B
 C12 B
 C21 B
 C22 B
 C31 B
 C32 B
 C41 B
 C42 B
 C13 B
 C14 B
 C23 B
 C24 B
 C33 B
 C34 B
 C43 B
 C44 B
>>> 
```
