### ISSUE TITLE
Strange error when running a reaction back to a single component grouping

### ISSUE THREAD

**Issue by mc-robinson** [rdkit/rdkit#3147]
Version '2019.09.3'

I am just noting this strange behavior where the intramolecular reaction does not seem to be allowed when disconnecting a bond to an atom that is part of a separate double bond.

**Example to reproduce**
```
mol = Chem.MolFromSmiles('Cc1ccc(C(=O)/C=C/c2cnc3ccccc3n2)cc1')
rxn = AllChem.ReactionFromSmarts('[c:1][C:2](=[O])[C:3]>>([*:1][C:2]#[N].[*:3][Mg][Cl])')
p = rxn.RunReactants((Chem.AddHs(mol),))
```

gives 
```
RuntimeError: Pre-condition Violation
	bgnIdx not connected to begin atom of bond
	Violation occurred on line 283 in file Code/GraphMol/Bond.cpp
	Failed Expression: getOwningMol().getBondBetweenAtoms(getBeginAtomIdx(), bgnIdx) != nullptr
	RDKIT: 2019.09.3
	BOOST: 1_67
```

Though removing the outer parentheses to give `rxn = AllChem.ReactionFromSmarts('[c:1][C:2](=[O])[C:3]>>[*:1][C:2]#[N].[*:3][Mg][Cl]')` makes the reaction work perfectly fine. I am somewhat confused by this and appreciate any help with the issue. Thanks!

**Comment by autodataming** [comment]
![图片](https://user-images.githubusercontent.com/7656130/81463744-6458b300-91ee-11ea-8131-41e58ac1aa18.png)

**Comment by mc-robinson** [comment]
Interesting, thanks. So the main difference seems to be the version?

**Comment by autodataming** [comment]
> 
> 
> Interesting, thanks. So the main difference seems to be the version?

You could try to run the code in the different version.

**Comment by bp-kelley** [comment]
This does look like a bug, but it isn't with the components, it appears to be with chirality:

This fails:

```
mol = Chem.MolFromSmiles('C(=O)/C=C/C')
rxn = AllChem.ReactionFromSmarts('[C:2](=[O])[C:3]>>[C:2]#[N][*:3]')
rxn.RunReactants([mol])
```

This passes:

```
mol = Chem.MolFromSmiles('C(=O)C=CC')
rxn = AllChem.ReactionFromSmarts('[C:2](=[O])[C:3]>>[C:2]#[N][*:3]')
rxn.RunReactants([mol])
```

**Comment by bp-kelley** [comment]
@greglandrum Chirality issues should get auto assigned to you :)
