### ISSUE TITLE
how to pass the MolDrawOptions parameter to MolToImage function?

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3148]
**Configuration:**

- RDKit Version: 2020.03
- Operating system: linux
- Python version (if relevant): 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

how to pass the MolDrawOptions parameter to MolToImage function?
I want to custom atom labels in the  MolToImage.
the atom label can be set in the MolDrawOptions  not DrawOptions.

```py
mol = Chem.MolFromSmiles('COc1ccc(Cn2nc(CN3CCN(c4ccccc4OC)CC3)c3cc(OC)c(OC)cc32)cc1OC')
options = Draw.DrawingOptions()
options.dotsPerAngstrom = 50
max_size=(1000, 1000)
img =Draw.MolToImage(mol,size=max_size,options=options,highlightColor=[0,0,0],highlightBonds=list(range(100)))
TrimImgByWhite(img)
```

```py
mdo =  Draw.MolDrawOptions()

for i in range(len(mdo.GetAoms()):
    mdo.atomLabels[i]= mol.GetAtoms()[i].GetIdx()+"custom"
```

**Comment by greglandrum** [comment]
You need to use a `MolDraw2DOption` object. `DrawingOptions` is the old drawing code.
More info in my answer to #3149

**Comment by greglandrum** [comment]
And, yes, this should be better documented and/or the old drawing code should just be removed (but we do try to be careful about breaking backwards compability)/
