### ISSUE TITLE
how to show AtomNumbers and atom symbols in the image?

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3149]
**Configuration:**

- RDKit Version: 2020.03
- Operating system: linux
- Python version (if relevant): 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

how to show AtomNumbers and atom symbols in the image?
![图片](https://user-images.githubusercontent.com/7656130/81466419-3716ff80-9204-11ea-9562-3cc672c6a425.png)

```py
mol = Chem.MolFromSmiles('COc1ccc(Cn2nc(CN3CCN(c4ccccc4OC)CC3)c3cc(OC)c(OC)cc32)cc1OC')
options = Draw.DrawingOptions()
options.dotsPerAngstrom = 50
max_size=(1000, 1000)
options.includeAtomNumbers=True
img =Draw.MolToImage(mol,size=max_size,options=options,highlightColor=[0,0,0],highlightBonds=list(range(100)))
TrimImgByWhite(img)
```
![图片](https://user-images.githubusercontent.com/7656130/81466401-164eaa00-9204-11ea-88a9-fc28f67eb63a.png)
atom symbol is  not in the image.

```py
mol = Chem.MolFromSmiles('COc1ccc(Cn2nc(CN3CCN(c4ccccc4OC)CC3)c3cc(OC)c(OC)cc32)cc1OC')
options = Draw.DrawingOptions()
options.dotsPerAngstrom = 50
max_size=(1000, 1000)
options.includeAtomNumbers=False
img =Draw.MolToImage(mol,size=max_size,options=options,highlightColor=[0,0,0],highlightBonds=list(range(100)))
TrimImgByWhite(img)

```
![图片](https://user-images.githubusercontent.com/7656130/81466397-0767f780-9204-11ea-87ae-5ea6106104e3.png)

atom numbers is  not in the image.

**Comment by greglandrum** [comment]
Hi @autodataming : you do this by creating a `MolDraw2DOptions` object and passing that to `MolToImage()`:
```
dos = Draw.MolDrawOptions()
dos.addAtomIndices=True
Draw.MolToImage(m,options=dos)
```

Produces:
![image](https://user-images.githubusercontent.com/540511/81524858-16a98b00-9353-11ea-9dca-6180130c2fec.png)

More about the options is available in a recent blog post:
http://rdkit.blogspot.com/2020/04/new-drawing-options-in-202003-release.html

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
