### ISSUE TITLE
MolOps::removeHs() removes hydrides

### ISSUE THREAD

**Issue by jhjensen2** [rdkit/rdkit#3150]
RDKit version 2020.03.1 from condaforge in Google Colab
```
m = Chem.MolFromSmiles('[H-]')
print(Chem.GetFormalCharge(m))
m = Chem.MolFromSmiles('[OH+][H-]')
print(Chem.GetFormalCharge(m))
m = Chem.MolFromSmiles('[Fe+2]<-[H-]')
print(Chem.GetFormalCharge(m))
m = Chem.MolFromSmiles('[Fe+2]<-[OH-]')
print(Chem.GetFormalCharge(m))
````
-1 (correct)
1 (wrong)
2 (wrong)
1 (correct)

**Comment by greglandrum** [comment]
What's happening here is that `MolOps::removeHs()` is removing hydrides. It shouldn't be doing that.

**Comment by manangoel99** [comment]
@greglandrum can I take this up?

**Comment by greglandrum** [comment]
Please do!

**Comment by manangoel99** [comment]
@greglandrum My approach is that hydrides would have a formal charge of -1 and atomic number 1 so in the``` removeHs``` function, we can just add a continue statement on the atoms that satisfy these. However, this clashes with the higher degree case like "F[H-]F". One way around is too add another condition that hydrides must have degree less than or equal to 1 but I'm not sure if that's desirable.

**Comment by greglandrum** [comment]
@manangoel99 The approach sounds good. Don't forget to add an option to `RemoveHsParameters()` too.

> However, this clashes with the higher degree case like "F[H-]F". One way around is too add another condition that hydrides must have degree less than or equal to 1 but I'm not sure if that's desirable.

I don't think it clashes. The H in `F[H-]F` is both higher degree *and* negatively charged, so if either of the options `ps.removeHigherDegrees` or `ps.removeHydrides` is `false` it will not be removed.

**Comment by jhjensen2** [comment]
has this change made it into the nightly build? If so, it doesn't appear to solve the problem. Using vesion '2020.09.1dev1'

**Comment by greglandrum** [comment]
Since the "nightly" is actually manual and I haven't done one recently: nope
Thanks for the reminder though, I will do one now.

It is in the 2020.03.3 patch release, which ought to either already be on conda-forge or will be there soon

**Comment by greglandrum** [comment]
@jhjensen2 the new nightly builds are there in the conda repo now

**Comment by jhjensen2** [comment]
I seem to get the same version number and the same error
[code](https://colab.research.google.com/drive/1a_CDeBaBjr6pIAnCLtNZegUr8Rl7y98A?usp=sharing
)

**Comment by greglandrum** [comment]
Ah, figured it out.
The fix was to add a parameter to `RemoveHsParameters` which allows hydride removal to be disabled. The default was picked to not change the current behavior of the code, which probably wasn't the best idea. I will fix that.

In the meantime, you can do the following:
```
In [6]: parse_ps = Chem.SmilesParserParams()                                                                                                                                             
In [7]: parse_ps.removeHs=False                                                                                                                                                          
In [9]: remove_ps = Chem.RemoveHsParameters()                                                                                                                                            
In [10]: remove_ps.removeHydrides = False                                                                                                                                                
In [11]: m = Chem.RemoveHs(Chem.MolFromSmiles('[OH+][H-]',parse_ps),remove_ps)                                                                                                           
In [12]: Chem.MolToSmiles(m)                                                                                                                                                             
Out[12]: '[H-][OH+]'
In [13]: Chem.GetFormalCharge(m)                                                                                                                                                         
Out[13]: 0
In [14]: m = Chem.RemoveHs(Chem.MolFromSmiles('[H][O+][H-]',parse_ps),remove_ps)                                                                                                         
In [15]: Chem.MolToSmiles(m)                                                                                                                                                             
Out[15]: '[H-][OH+]'
```
Sorry about that confusion.

**Comment by jhjensen2** [comment]
The problem is still there with 2020.03.5 from conda-forge

**Comment by greglandrum** [comment]
@jhjensen2 I can't reproduce it:
```
In [1]: import rdkit

In [2]: print(rdkit.__version__)
2020.03.5

In [3]: from rdkit import Chem

In [4]: parse_ps = Chem.SmilesParserParams()
   ...: parse_ps.removeHs=False
   ...: remove_ps = Chem.RemoveHsParameters()
   ...: remove_ps.removeHydrides = False
   ...: m = Chem.RemoveHs(Chem.MolFromSmiles('[OH+][H-]',parse_ps),remove_ps)
   ...: Chem.MolToSmiles(m)
   ...: 
Out[4]: '[H-][OH+]'
```

**Comment by jhjensen2** [comment]
Sorry, I was very unclear. I

**Comment by greglandrum** [comment]
I'm guessing that you're unhappy that the formal charge is 1 after removing the hydride?
