### ISSUE TITLE
For heterocycles, the Chem.GetSymmSSSR function does not give the write sequence of the ring

### ISSUE THREAD

**Issue by ethan0879** [rdkit/rdkit#3151]
I noticed that for heterocycles, the Chem.GetSymmSSSR function does not give the right sequence of the ring. Instead of taking the heteroatom, it takes a hydrogen. 

You can see an example here (https://ibb.co/2kkT2Xx). The function gives me,
[1, 11, 6, 5, 4, 3, 2]

instead of

[1, 19, 6, 5, 4, 3, 2]

Any solution for that?

_Originally posted by @ethan0879 in https://github.com/rdkit/rdkit/issues/3122#issuecomment-626317825_

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
