### ISSUE TITLE
Chem.GetSymmSSSR function not working properly for heterocycles

### ISSUE THREAD

**Issue by ethan0879** [rdkit/rdkit#3152]
**Configuration:**

- RDKit Version: 2018.09.3
- Operating system: CentOS Linux 7 (Core)
- Python version (if relevant): 2.7.14
- Are you using condo? Yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit? -

**Description:**

I noticed that for heterocyclic molecules, the Chem.GetSymmSSSR function does not give the right sequence of the ring. Instead of taking the heteroatom, it takes a hydrogen.

You can see an example here (https://ibb.co/2kkT2Xx). The function gives me,
[1, 11, 6, 5, 4, 3, 2]

instead of

[1, 19, 6, 5, 4, 3, 2]

Any solution for that?

```
from __future__ import print_function
from rdkit import Chem
m = Chem.MolFromMolFile('molecule1.mol')
ssr = Chem.GetSymmSSSR(m)
list=[[i+1 for i in r] for r in ssr]
repr(list)
```

**Comment by greglandrum** [comment]
I don't think it's relevant here, but it's worth pointing out that that is a pretty old version of the RDKit

you haven't provided the input mol file, so I can't be 100% sure, but I guess from looking at the image you link to that what is confusing you here is the fact that hydrogen atoms are removed from molecule when it's read in. This changes the atom indices of higher-numbered atoms.
If you have some reason for wanting to keep the Hs, you can pass the argument `removeHs=False` to `Chem.MolFromMolFile()`

**Comment by ethan0879** [comment]
Aha! I did not know that the Hs are removed when reading the mol file. That helped me!
