### ISSUE TITLE
Kekulization error from CreateScaffoldNetwork

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3153]
**Configuration:**

- RDKit Version: 2020.03.2 (also master)
- Operating system: all
- Python version (if relevant): all

**Description:**
```
In [10]: m = Chem.MolFromSmiles('[O-][C+]1C=CC(CC2=CC=CC2)=CC=C1')

In [11]: ps = rdScaffoldNetwork.ScaffoldNetworkParams()

In [12]: rdScaffoldNetwork.CreateScaffoldNetwork([m],ps)
---------------------------------------------------------------------------
KekulizeException                         Traceback (most recent call last)
<ipython-input-12-1e83c5d98959> in <module>
----> 1 rdScaffoldNetwork.CreateScaffoldNetwork([m],ps)

KekulizeException: Can't kekulize mol.  Unkekulized atoms: 0 2 3 4 5 6 7
```
Using a more "standard" representation of the molecule works fine:
```
In [13]: m = Chem.MolFromSmiles('O=C1C=CC(CC2=CC=CC2)=CC=C1')

In [14]: rdScaffoldNetwork.CreateScaffoldNetwork([m],ps)
Out[14]: <rdkit.Chem.Scaffolds.rdScaffoldNetwork.ScaffoldNetwork at 0x23733a1e5d0>
```

Thanks to an anonymous reviewer of the scaffold network application note for pointing this out. :-)

**Comment by manangoel99** [comment]
Can I take this up?

**Comment by greglandrum** [comment]
@manangoel99 : sure. Tracking down the source of the problem and coming up with a fix will be a good chance to learn more about the code.

**Comment by manangoel99** [comment]
@greglandrum I wanted to know if ideally, the workflow for both the examples should be identical or not. I've found that the point where the workflow diverges for the two is in ```MurckoDecompose``` function in ```Code/GraphMol/ChemTransforms/ChemTransforms.cpp```.

**Comment by greglandrum** [comment]
@manangoel99 : I agree that the problem is in that function. It’s connected to whether or not implicit Hs are allowed to be added to atoms (this is what setNoImplicit() does). This isn’t working properly with the C+ when it is aromatic. So some logic needs to be added for that. Similar to what is done when you call that function on c1cccn1CC. (At least I think that works).

FYI: I am away from the computer and will be mostly out of email contact until Monday.

**Comment by manangoel99** [comment]
In the ```MurckoDecompose function``` for adding Explicit Hydrogens to aromatic heteroatoms, the following code snippet is used
``` 
if (nbr->getIsAromatic() && nbr->getAtomicNum() != 6) {
            // fix aromatic heteroatoms:
            nbr->setNumExplicitHs(1);
          }
```
So one way of doing this could be to add another condition that if it's a C+, then 1 explicit H should be added.

**Comment by manangoel99** [comment]
@greglandrum In the above-mentioned approach, would I be missing any cases that would need to be handled?

**Comment by greglandrum** [comment]
@manangoel99 this is one of those "gifts that keeps on giving" in terms of there seeming to always been additional special cases, but adding a condition to that test for C+ seems like a reasonable way to fix this particular example. And it's fine to fix this particular example.
