### ISSUE TITLE
Unexpected errors within the substructure matching routine caused by hydrogens

### ISSUE THREAD

**Issue by marcusstamm** [rdkit/rdkit#3155]
If there are specific inconsistencies between the search query and the query within the database (e.g., explicit hydrogens), then the reaction substructure search routine fails with an error and the expected hit is not present in the results list. Interestingly, a search of the query against itself works fine and also a match of the corresponding DB content against itself works fine. 

![RDkit-search-error (1)](https://user-images.githubusercontent.com/62539055/81541529-87609f80-9373-11ea-952c-bc4fbd131754.png)

I've tried to sanitize these queries but this did not help since the hydrogen did not get removed. How can I ensure that my search finds all relevant hits in the database?

**Comment by bp-kelley** [comment]
Here is a test case:

```
rxn1 = ReactionFromSmarts("CCCN.O=C(Cc1ccccc1)c1ccccc1>>CCNC(Cc1ccccc1)c1ccccc1")
rxn2 = ReactionFromSmarts("C[C:1](=O)c1ccccc1>>C[CH:1](N)c1ccccc1")

q1 = list(rxn1.GetProducts())[0]
q2 = list(rxn2.GetProducts())[0]
q1.HasSubstructMatch(q2)
```

A stupid fix is to Sanitize the product, but I'm not sure this is a good idea, but it may help in the short run.

```
SanitizeMol(q1)
HasReactionSubstructMatch(rxn1, rxn2)
```

**Comment by bp-kelley** [comment]
You can do the same thing programmatically via,

```
for product in rxn.GetProducts():
   Chem.SanitizeMol(product)
```

**Comment by marcusstamm** [comment]
Thanks a lot for this work-around. If it's applied to all substances included in the reaction (starting materials and products) and also to all substances of the reactions in the database, it might be a good solution. 

I had something similar in mind which did not work. My first idea was to sanitize each of the products and use the sanitized SMILE string of each product: 

`x=  ReactionFromSmarts(">>C[CH:1](N)c1ccccc1")
q1 = list(x.GetProducts())[0]
Chem.SanitizeMol(q1)
smiles = Chem.MolToSmiles(q1)
print (smiles)`

This results in the same SMILES "C[CH:1](N)c1ccccc1" as before. Why does the sanitization does not have an impact on the SMILES string?

**Comment by bp-kelley** [comment]
Sanitization is a method for validating that a molecule is what you say it is.  Smiles has a quirk that if an atom is in brackets, the hydrogens must be explicit:

```
>>> print(Chem.CanonSmiles("C"))
C
>>> print(Chem.CanonSmiles("[C:1]"))
[C:1] 
```

Are not the same, the later is a radical.  Sanitization won't fix this.  The issue you are seeing is actually an internal state of the molecule, RDKit simply has not figured out the implicit versus explicit hydrogens yet for the reaction, the main reason is that it simply doesn't need to until the reaction is completed.

We can get a better idea through RDKit's Debug facility:

```
Chem.MolFromSmiles("C").Debug()
Atoms:
	0 6 C chg: 0  deg: 0 exp: 0 imp: 4 hyb: 4 arom?: 0 chi: 0
Bonds:
```

and the non sanitized:

```
>>> Chem.MolFromSmiles("C", sanitize=False).Debug()
Atoms:
	0 6 C chg: 0  deg: 0 exp: 

[15:21:59] 
****
Pre-condition Violation
getExplicitValence() called without call to calcExplicitValence()
Violation occurred on line 196 in file /Users/glandrum/anaconda3/conda-bld/rdkit_1585463137433/work/Code/GraphMol/Atom.cpp
Failed Expression: d_explicitValence > -1
****

N/A imp: -1 hyb: 0 arom?: 0 chi: 0
Bonds:
```

Now, as to why the smiles strings aren't different is that RDKit doesn't need the implicit hydrogen to write the smiles string out in this case, it just needs it for searching.
