### ISSUE TITLE
 How to correct smiles of the fragment mol ?

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3160]
**Configuration:**

- RDKit Version:  2020.03
- Operating system: linux
- Python version (if relevant): 3.7
- Are you using conda?  yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

How to correct smiles of the fragment mol ?
The smiles of fragment **CCOC(=O)c1cc(C)nn1** may be error as the mol is NONE.

```py
def select_leftpmolbyatmidx(psmi,atomids):
    pmol = Chem.MolFromSmiles(psmi)
    atomids_use=set(atomids)
    fragsmi = AllChem.MolFragmentToSmiles(pmol, atomids_use)
    return fragsmi
psmi = 'CCOC(c5nn(Cc6cnc(N7CCN(CC7)C8CC8)cc6)c(C)c5)=O'
atomids = [0, 1, 2, 3, 4, 5, 6, 23, 24, 25, 26]
fragsmi = select_leftpmolbyatmidx(psmi,atomids)
print("result fragsmi",fragsmi)
fragmol = Chem.MolFromSmiles(fragsmi)
print(fragmol)
fragmol2 = Chem.MolFromSmiles(fragsmi,sanitize=False)
print(fragmol2)
newsmi=Chem.MolToSmiles(fragmol2)
print(newsmi)
```
output:
```
result fragsmi CCOC(=O)c1cc(C)nn1
None
<rdkit.Chem.rdchem.Mol object at 0x7f4df27c6260>
CCOC(=O)c1cc(C)nn1

```
pmol is :

**Comment by bp-kelley** [comment]
What is your goal here?  When you extract a fragment, it could very well make a molecule that doesn't have valid chemistry.

If you want to keep the molecule properties, you might need to save the molecule as something besides smiles.  Your options here are smarts, which you can use to search other molecules, or pickle.

```
import pickle
def select_leftpmolbyatmidx(psmi,atomids):
    pmol = Chem.MolFromSmiles(psmi)
    atomids_use=atomids
    frag = Chem.PathToSubmol(pmol, atomids_use)
    return frag
psmi = 'CCOC(c5nn(Cc6cnc(N7CCN(CC7)C8CC8)cc6)c(C)c5)=O'
atomids = [0, 1, 2, 3, 4, 5, 6, 23, 24, 25, 26]
frag = select_leftpmolbyatmidx(psmi,atomids)
print("result frag",frag)
print(Chem.MolToSmiles(frag))
dump = pickle.dumps(frag)
frag2 = pickle.loads(dump)
print(Chem.MolToSmiles(frag2))
```

**Comment by autodataming** [comment]
> 
> 
> What is your goal here? When you extract a fragment, it could very well make a molecule that doesn't have valid chemistry.
> 
> If you want to keep the molecule properties, you might need to save the molecule as something besides smiles. Your options here are smarts, which you can use to search other molecules, or pickle.
> 
> ```
> import pickle
> def select_leftpmolbyatmidx(psmi,atomids):
>     pmol = Chem.MolFromSmiles(psmi)
>     atomids_use=atomids
>     frag = Chem.PathToSubmol(pmol, atomids_use)
>     return frag
> psmi = 'CCOC(c5nn(Cc6cnc(N7CCN(CC7)C8CC8)cc6)c(C)c5)=O'
> atomids = [0, 1, 2, 3, 4, 5, 6, 23, 24, 25, 26]
> frag = select_leftpmolbyatmidx(psmi,atomids)
> print("result frag",frag)
> print(Chem.MolToSmiles(frag))
> dump = pickle.dumps(frag)
> frag2 = pickle.loads(dump)
> print(Chem.MolToSmiles(frag2))
> ```

Thank you!
![图片](https://user-images.githubusercontent.com/7656130/81764403-156b9000-9504-11ea-9f4e-59131c8ced80.png)
My goal is to get the fragment mol if the fragment mol is chemistry valid.
For the example, I wish to get the fragment as the following.
![图片](https://user-images.githubusercontent.com/7656130/81764725-c5d99400-9504-11ea-8767-5bd9a1a71c5f.png)

the fragmol2 figured as the following.
![图片](https://user-images.githubusercontent.com/7656130/81764799-f7525f80-9504-11ea-97a3-f1bdfbca96ae.png)

**Comment by bp-kelley** [comment]
When you are fragmenting here, you are chopping a bond off the nitrogen and leaving it in a bad valence state.  RDKit then can't figure out how to eke the kekule form of the aromatic bond without guessing and RDKit hates to guess.

One way to solve this is using the FragmentOnBonds function (this is what MMPs and BRICS uses).

![image](https://user-images.githubusercontent.com/9888416/81818776-768f6580-94fc-11ea-8193-5afbbe303213.png)

Not how the nitrogens connectivity is fine now.  

Some tricks: you can split the result here using "Chem.GetMolFrags" or simply smiles.split(".").  The isotope will be the atom index of the split bond, here the bond was split between atom index 3 and 4

Hopefully this helps.

**Comment by autodataming** [comment]
> 
> 
> When you are fragmenting here, you are chopping a bond off the nitrogen and leaving it in a bad valence state. RDKit then can't figure out how to eke the kekule form of the aromatic bond without guessing and RDKit hates to guess.
> 
> One way to solve this is using the FragmentOnBonds function (this is what MMPs and BRICS uses).
> 
> ![image](https://user-images.githubusercontent.com/9888416/81818776-768f6580-94fc-11ea-8193-5afbbe303213.png)
> 
> Not how the nitrogens connectivity is fine now.
> 
> Some tricks: you can split the result here using "Chem.GetMolFrags" or simply smiles.split("."). The isotope will be the atom index of the split bond, here the bond was split between atom index 3 and 4
> 
> Hopefully this helps.

Thank you very much! It's very useful.
