### ISSUE TITLE
RDStreams CMakeLists error?

### ISSUE THREAD

**Issue by johnmay** [rdkit/rdkit#3163]
Our internal NextMove CI started failing for RDKit with a build error due to the boost version changes - I think those are fine and just need an upgrade. However I spotted this possible mistake in the RDStreams build:

https://github.com/rdkit/rdkit/blob/master/Code/RDStreams/CMakeLists.txt#L25-L26

If RDK_USE_BOOST_IOSTREAMS is turned off it now tries to link the hard coded Boost::iostreams, is this correct? It used to be a variable https://github.com/rdkit/rdkit/commit/45bf58754aeafc828f19c29c79b25a6524076373#diff-a172b149660c65e75018097b59df30fbL5 which was safe as it would just be uninitialised.

**Comment by bp-kelley** [comment]
@johnmay It does look like an error, and my formatting of the if statements probably didn't help.  Thanks for pointing this out.
