### ISSUE TITLE
Compilation is not well-formed if RDK_THREADSAFE_SSS is not defined.

### ISSUE THREAD

**Issue by roccomoretti** [rdkit/rdkit#3164]
It looks like there's compilation issues if the RDK_THREADSAFE_SSS build macro isn't defined. 

For example, in [Code/GraphMol/SubstructLibrary/PatternFactory.cpp:57](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/SubstructLibrary/PatternFactory.cpp#L57) the function uses a `lib` variable that isn't actually set anywhere else

Similarly, in Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp  the inclusion of the <future> header is guarded by the macro, but the actual usage of std::future (e.g. [line 196](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp#L196) ) isn't.

I'm not sure if the non-RDK_THREADSAFE_SSS build is a feature that's worth maintaining or not, but it doesn't seem to be working as-is (I personally don't have a particular need of it - I stumbled across the issue accidentally.)

**Comment by greglandrum** [comment]
Fixed in #3557
