### ISSUE TITLE
S-groups: PARENT field should reference index

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3175]
Here's what `index` says in the docs:
![image](https://user-images.githubusercontent.com/540511/82190097-ca30f300-98f0-11ea-8187-a66fd6cd6079.png)

and `PARENT`:
![image](https://user-images.githubusercontent.com/540511/82190125-d321c480-98f0-11ea-8b18-2fbf25c9c75b.png)

Since we can avoid altering the input data here, I think it makes sense to do so and to preserve the `index` and `PARENT` fields from SGroups in mol blocks. When we do that, the PARENT should reference an `index` property, not an index in the vector of `SubstanceGroup`s.

**Comment by ricrogz** [comment]
This is a bit more clear after reading through #3170

(Had a bit of trouble understanding this without looking at your last comments there)

**Comment by greglandrum** [comment]
@ricrogz : does the last paragraph I just added help?

**Comment by ricrogz** [comment]
> @ricrogz : does the last paragraph I just added help?

Sorry, I missed this. Yeah, that helped. Somehow I missed that this was also about preserving the value of the "index" field on input.
