### ISSUE TITLE
rdScaffoldNetwork causes segmenation fault upon None molecule

### ISSUE THREAD

**Issue by AnsgarSchuffenhauer** [rdkit/rdkit#3177]
**Configuration:**

- RDKit Version: 2020.03.1
- Operating system: linux (CentOS7)
- Python version (if relevant): 3.8
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? 
- If you are not using conda: how did you install the RDKit?

**Description:**
When feeding a None molecule to rdScaffoldNetwork.CreateScaffoldNetwork() this systemtcially ends up in asegmenation fault. Other regular molecules are processed OK. 
 

```
>>> from rdkit.Chem.Scaffolds import rdScaffoldNetwork
params = rdScaffoldNetwork.ScaffoldNetworkParams()
params.flattenIsotopes=True
params.includeGenericBondScaffolds=False
params.includeGenericScaffolds=False
params.includeScaffoldsWithAttachments = False
params.includeScaffoldsWithoutAttachments = True
params.pruneBeforeFragmenting = True
sn = rdScaffoldNetwork.CreateScaffoldNetwork([None],params)

```
==> Segmentation fault

I fully appreciate that I should have checked for proper parsing of the molecule record first, with the mol is not None, and that of course a None molecule cannot generate a valid scaffold network. However,  still I would have expected to get an exception in this situation (which I could have contained within a try -except clause), and not a segmentation fault right away. 

The issue is not burning, as now that I am aware of the problem, I can prevent the feeding of None molecules.

**Comment by greglandrum** [comment]
Simple reproducible here:
```
In [2]: from rdkit.Chem.Scaffolds import rdScaffoldNetwork
In [3]: rdScaffoldNetwork.CreateScaffoldNetwork([None],rdScaffoldNetwork.ScaffoldNetworkParams())

crash!
```

**Comment by greglandrum** [comment]
Thanks for reporting this Ansgar. The code should not, under any circumstances, seg fault and crash like this.
