### ISSUE TITLE
Do references to Atoms persist after removing bonds from Mol?

### ISSUE THREAD

**Issue by nigelnnk** [rdkit/rdkit#3181]
**Configuration:**
- RDKit Version: 2020.03.2.0
- Operating system: Windows 10
- Python version (if relevant): 3.7
- Are you using conda? Yes

**Description:**

I am trying to split molecules via the RemoveBond() method and will like to see if Atoms persist (still exist) in the Mol object that was originally associated with it. As seen here, I have removed a bond and stored both of the Atoms associated with the bond. However, the original Mol object does not contain either of these Atoms. 

Motivation: I intend to break random bonds in the molecule and only keep the largest submolecule, hence will like to know which atom of the broken bond is left in said largest submolecule. 

* May I know if this is intended behaviour?
* If possible, is there a way for me to link the Atoms (in the Mol before splitting) to the Mol object after splitting?

```
>>> from rdkit import Chem
>>> mol = Chem.RWMol(Chem.MolFromSmiles("CCC(=O)OCC"))
>>> [(x.GetBeginAtomIdx(), x.GetEndAtomIdx()) for x in mol.GetBonds()]
[(0, 1), (1, 2), (2, 3), (2, 4), (4, 5), (5, 6)]
>>> present = mol.GetAtomWithIdx(2)
>>> removed = mol.GetAtomWithIdx(4)
>>> mol.RemoveBond(2,4)
>>> [(x.GetBeginAtomIdx(), x.GetEndAtomIdx()) for x in mol.GetBonds()]
[(0, 1), (1, 2), (2, 3), (4, 5), (5, 6)]
>>> present in mol.GetAtoms()
False
>>> removed in mol.GetAtoms()
False
```

**Comment by ptosco** [comment]
`Mol.GetAtoms()` returns a read-only sequence of molecule atoms:
http://rdkit.org/docs/source/rdkit.Chem.rdchem.html?highlight=getatoms#rdkit.Chem.rdchem.Mol.GetAtoms

The following snippet shows that the atoms obiects returned by `Mol.GetAtoms()` do not coincide with those returned by `Mol.GetAtomWithIdx()`, which is why your code doesn't work as you expect:
```
from rdkit import Chem

mol = Chem.RWMol(Chem.MolFromSmiles("CCC(=O)OCC"))
get_atoms_set = set(mol.GetAtoms())
get_atoms_set
{<rdkit.Chem.rdchem.Atom at 0x7fd373725f80>,
 <rdkit.Chem.rdchem.Atom at 0x7fd373732030>,
 <rdkit.Chem.rdchem.Atom at 0x7fd373732080>,
 <rdkit.Chem.rdchem.Atom at 0x7fd3737320d0>,
 <rdkit.Chem.rdchem.Atom at 0x7fd373732120>,
 <rdkit.Chem.rdchem.Atom at 0x7fd373732170>,
 <rdkit.Chem.rdchem.Atom at 0x7fd3737321c0>}

get_atom_with_idx_set = {mol.GetAtomWithIdx(i) for i in range(mol.GetNumAtoms())}
get_atom_with_idx_set
{<rdkit.Chem.rdchem.Atom at 0x7fd373734170>,
 <rdkit.Chem.rdchem.Atom at 0x7fd373734210>,
 <rdkit.Chem.rdchem.Atom at 0x7fd373734300>,
 <rdkit.Chem.rdchem.Atom at 0x7fd3737343f0>,
 <rdkit.Chem.rdchem.Atom at 0x7fd3737344e0>,
 <rdkit.Chem.rdchem.Atom at 0x7fd3737345d0>,
 <rdkit.Chem.rdchem.Atom at 0x7fd3737346c0>}

get_atoms_set.intersection(get_atom_with_idx_set)
set()
```

To easily relate atoms to their original fragment after splitting you can set a property on the atoms belonging to the bond you split with `Atom.SetProperty()`:

```
mol.GetAtomWithIdx(2).SetIntProp("__split", 2)
mol.GetAtomWithIdx(4).SetIntProp("__split", 4)
mol.RemoveBond(2,4)
frags = Chem.GetMolFrags(mol, asMols=True)

len(frags)
2

for i, frag in enumerate(frags):
    for a in frag.GetAtoms():
        if a.HasProp("__split"):
            print("frag", i, "idx", a.GetIdx())
frag 0 idx 2
frag 1 idx 0
```

**Comment by bp-kelley** [comment]
Some more details:  In Python land what you are seeing is a "wrapper" around an atom, not the atom itself.  You can see that you get a new python object every time you access atoms:

```
>>> m = Chem.MolFromSmiles("CC")
>>> atom1 = list(m.GetAtoms())
>>> atom2 = list(m.GetAtoms())
>>> atom1
[<rdkit.Chem.rdchem.Atom object at **0x11ee0dee0**>, <rdkit.Chem.rdchem.Atom object at **0x11ee0df30**>]
>>> atom2
[<rdkit.Chem.rdchem.Atom object at **0x11ee0df80**>, <rdkit.Chem.rdchem.Atom object at **0x11ee0c030**>]
111
```

The object that these wrap *is* the same, but there is no way for you to know that in python, and holding on to an atom that is deleted in the future is a recipe for a segmentation fault.

```
# they ARE the same atom
>>> atom1[0].SetIsotope(1)
>>> atom2[0].GetIsotope()
1
# But they are NOT the same python object
>>> atom1[0] is atom2[0]
False
```

However, if you *KNOW* you only delete bonds, then hanging on the atoms is safe but not recommended, but you need to have your own indexing scheme.  To be sure that you have the same object, Paolo's tagging strategy is the safest overall, and you can even pickle atom properties now for serialization purposes.

```
>>> atom1[0].SetIntProp("MyTag", 1)
>>> atom2[0].GetIntProp("MyTag")
1
```

**Comment by bp-kelley** [comment]
I'll also add, that atom properties survive copying or fragmentation of molecules which is what Paolo is showing here, so they are doubly useful.

**Comment by nigelnnk** [comment]
This was enlightening. Thank you all!
