### ISSUE TITLE
rdFMCS.FindMCS  generate different outcomes for the same molecules ( ccanonical smiles and non-canonical smiles)

### ISSUE THREAD

**Issue by autodataming** [rdkit/rdkit#3186]
**Configuration:**

- RDKit Version:2020.03
- Operating system:linux
- Python version (if relevant): 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

rdFMCS.FindMCS  generate different outcomes for the same molecules ( canonical smiles and non-canonical smiles).

for the non-canonical smiles case:

```py
from rdkit import Chem 
from rdkit.Chem import rdFMCS,AllChem
import rdkit  
from rdkit.Chem.Draw import IPythonConsole 

def setIsotopeMolsbyMethodA(mols):
    for mol in mols:
        for atom in mol.GetAtoms():
            value =  atom.GetAtomicNum()
            atom.SetIsotope(value)

rxnsmi = 'COC(C(C)(Oc(cc1)c(Br)c2c1cncc2)C)=O.C[Sn](C)(C)C>>COC(C(C)(Oc(cc3)c(C)c4c3cncc4)C)=O'
rs,psmi = rxnsmi.split(">>") 
rsmi = rs.split('.')[0]

pmol = Chem.MolFromSmiles(psmi)
rmol = Chem.MolFromSmiles(rsmi)




pmol_label = Chem.Mol(pmol)
rmol_label = Chem.Mol(rmol)

mols=[pmol_label,rmol_label]

setIsotopeMolsbyMethodA(mols)

res = rdFMCS.FindMCS(mols,timeout=10,bondCompare=rdkit.Chem.rdFMCS.BondCompare.CompareAny,atomCompare = rdkit.Chem.rdFMCS.AtomCompare.CompareIsotopes )
     
Chem.MolFromSmarts( res.smartsString)
```
outcome: 

![图片](https://user-images.githubusercontent.com/7656130/82775077-383d6300-9e79-11ea-9d42-f3535618b8d5.png)

for the canonical smiles case:

```py
from rdkit import Chem 
from rdkit.Chem import rdFMCS,AllChem
import rdkit  
from rdkit.Chem.Draw import IPythonConsole 

def setIsotopeMolsbyMethodA(mols):
    for mol in mols:
        for atom in mol.GetAtoms():
            value =  atom.GetAtomicNum()
            atom.SetIsotope(value)

rxnsmi = 'COC(C(C)(Oc(cc1)c(Br)c2c1cncc2)C)=O.C[Sn](C)(C)C>>COC(C(C)(Oc(cc3)c(C)c4c3cncc4)C)=O'
rs,psmi = rxnsmi.split(">>") 
rsmi = rs.split('.')[0]

pmol = Chem.MolFromSmiles(psmi)
rmol = Chem.MolFromSmiles(rsmi)

psmi = Chem.MolToSmiles(pmol)
rsmi = Chem.MolToSmiles(rmol)
pmol = Chem.MolFromSmiles(psmi)
rmol = Chem.MolFromSmiles(rsmi)




pmol_label = Chem.Mol(pmol)
rmol_label = Chem.Mol(rmol)

mols=[pmol_label,rmol_label]

setIsotopeMolsbyMethodA(mols)

res = rdFMCS.FindMCS(mols,timeout=10,bondCompare=rdkit.Chem.rdFMCS.BondCompare.CompareAny,atomCompare = rdkit.Chem.rdFMCS.AtomCompare.CompareIsotopes )
     
Chem.MolFromSmarts( res.smartsString)
```
outcome:
![图片](https://user-images.githubusercontent.com/7656130/82775125-5d31d600-9e79-11ea-9837-e5b14e06b885.png)

**Comment by greglandrum** [comment]
This is not unexpected behavior. There is no guarantee that the MCS generated by the code will be canonical (i.e. always give the same result no matter the ordering of the input atoms); the algorithm merely guarantees that the results will be maximal. In your case there are (at least) two different MCSs that each have 18 atoms and 19 bonds. Either is correct

Here's a simplified version of your example demonstrating this: https://gist.github.com/greglandrum/b620752506f3f11382d672d9fa53bf28

**Comment by autodataming** [comment]
> 
> 
> This is not unexpected behavior. There is no guarantee that the MCS generated by the code will be canonical (i.e. always give the same result no matter the ordering of the input atoms); the algorithm merely guarantees that the results will be maximal. In your case there are (at least) two different MCSs that each have 18 atoms and 19 bonds. Either is correct
> 
> Here's a simplified version of your example demonstrating this: [gist.github.com/greglandrum/b620752506f3f11382d672d9fa53bf28](https://gist.github.com/greglandrum/b620752506f3f11382d672d9fa53bf28)

Thank you. 

For the following case, no maps betweend mol and mcs smart mol.
is this a bug?

```py
from rdkit import Chem 
from rdkit.Chem import rdFMCS,AllChem
import rdkit  
from rdkit.Chem.Draw import IPythonConsole 

def setIsotopeMolsbyMethodA(mols):
    for mol in mols:
        for atom in mol.GetAtoms():
            value =  atom.GetAtomicNum()
            atom.SetIsotope(value)

# rxnsmi = 'CC(C)(OC(N[C@@H](Cc1ccccc1)CNc(nc(c2ccncc2)n3)c4c3c(Br)cs4)=O)C.N#C[Cu]C#N>>N#Cc(cs5)c6c5c(NC[C@H](Cc7ccccc7)N)nc(c8ccncc8)n6'
rxnsmi = 'CC(C)(C)OC(=O)N[C@H](CNc1nc(-c2ccncc2)nc2c(Br)csc12)Cc1ccccc1.N#C[Cu]C#N>>N#Cc1csc2c(NC[C@@H](N)Cc3ccccc3)nc(-c3ccncc3)nc12'
# rxnsmi = 'COC(C(C)(Oc(cc1)c(Br)c2c1cncc2)C)=O.C[Sn](C)(C)C>>COC(C(C)(Oc(cc3)c(C)c4c3cncc4)C)=O'
rs,psmi = rxnsmi.split(">>") 
rsmi = rs.split('.')[0]

pmol = Chem.MolFromSmiles(psmi)
rmol = Chem.MolFromSmiles(rsmi)


pmol_label = Chem.Mol(pmol)
rmol_label = Chem.Mol(rmol)

mols=[pmol_label,rmol_label]
# mols=[rmol_label,pmol_label]

setIsotopeMolsbyMethodA(mols)

res = rdFMCS.FindMCS(mols,timeout=10,bondCompare=rdkit.Chem.rdFMCS.BondCompare.CompareAny,atomCompare = rdkit.Chem.rdFMCS.AtomCompare.CompareIsotopes )
maxcom =Chem.MolFromSmarts( res.smartsString)   
Chem.MolFromSmarts( res.smartsString)
maps = rmol_label.GetSubstructMatches(maxcom,uniquify=False)
maps
```

**Comment by greglandrum** [comment]
Why are you calling the `setIsotopeMolsByMethodA()` function?

**Comment by autodataming** [comment]
> 
> 
> Why are you calling the `setIsotopeMolsByMethodA()` function?

To custom map function, for example 

[issue 3123](https://github.com/rdkit/rdkit/issues/3123)

Now I can't find the special example for the  setIsotopeMolsByMethodA. If I find the example,I will paste it here.

**Comment by greglandrum** [comment]
Rather than asking us to try and figure out what your complex code is doing and then fix it for you, please start by simplifying things (as I did in the gist I link to above) to show only the part that you are confused about or that you think is doing the wrong thing.
Every extra bit that you include in your example is extra work for the people who you are asking to help you.

**Comment by autodataming** [comment]
> ra bit that you include in your example is extra work for the people who you

Thank you,  I will try to simplifying the above code.
