### ISSUE TITLE
Explicit valence error

### ISSUE THREAD

**Issue by panpan2** [rdkit/rdkit#3189]
**Configuration:**

- RDKit Version: 2019.09.3
- Operating system: MacOS
- Python version (if relevant): 3.7.4
- Are you using condo? Yes
- If you are using conda, which channel did you install the rdkit from? conda install -c rdkit rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

I tried to create molecules from the SMILES strings of Diborane [[BH2]1[H][BH2][H]1](https://en.wikipedia.org/wiki/Diborane) and Bifluoride [F[H][F-]](https://en.wikipedia.org/wiki/Bifluoride) and got an explicit valence error. In Bifluoride, this is possibly because hydrogen has only one valence electron, but it forms bonds with more than one atom. Similarly in Diborane, this is possibly because of the three-center two-electron bond.

```python
import rdkit.Chem as Chem
smiles = 'F[H][F-]'
mol = Chem.MolFromSmiles(smiles)
```

```python
import rdkit.Chem as Chem
smiles = '[BH2]1[H][BH2][H]1'
mol = Chem.MolFromSmiles(smiles)
```

**Comment by greglandrum** [comment]
@panpan2 The H atoms in both of these molecules are hypervalent. The RDKit will support these, but you need to turn sanitization off or do partial sanitization.
If you do some web searching you should find solutions to this. If not, please subscribe to the rdkit-discuss mailing list and ask there.
