### ISSUE TITLE
Handling of charge in SMARTS string has unexpected behaviour if using the ampersand operator

### ISSUE THREAD

**Issue by jose-mr** [rdkit/rdkit#3193]
edit: this is not a bug in rdkit, it is just the way it works, see the first reply by bp-kelley
 

**Configuration:**

- RDKit Version: '2020.03.1'
- Operating system: Ubuntu 18.04.4 LTS
- Python version (if relevant): 3.8.2
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit?

**Description:**

I think I have found some inconsistencies on how rdkit handles charged atoms in SMARTS strings. In particular, charge is not recognized when you use the & operator. Please see the code below.

```
from rdkit.Chem import MolFromSmarts, MolToSmarts

# with this notation the charge is identified
mol = MolFromSmarts("[O-]")
for atom in mol.GetAtoms():
    print(atom.GetSymbol(), atom.GetFormalCharge())

>>> O -1

# but the default notation in rdkit is using the & operator by default "[O&-]"
print(MolToSmarts(mol))

>>> [O&-]

# with & operator charge is not identified
mol = MolFromSmarts("[O&-]")
for atom in mol.GetAtoms():
    print(atom.GetSymbol(), atom.GetFormalCharge())

>>> O 0

```

I could use the first notation as input as workaround, but cannot do that when writing and then reading the same smarts string.
Thank you!

**Comment by bp-kelley** [comment]
That's not quite how smarts works in rdkit.  What you are doing in this smarts pattern is making a logic tree.  & is a boolean operation so you are asking for atoms that are oxygen AND have a negative charge.  You can think of [O-1] as an oxygen WITH a negative charge if you like.

This can be seen using the DescribeQuery feature:

```
>>> sma = Chem.MolFromSmarts("[O&-1]")
>>> for atom in sma.GetAtoms():
...     if atom.HasQuery():
...        print(atom.DescribeQuery())
... 
AtomAnd
  AtomType 8 = val
  AtomFormalCharge -1 = val
```

Of course, these an be more complicated:

```
>>> sma = Chem.MolFromSmarts("[O&-1,-2]")
>>> for atom in sma.GetAtoms():
...     if atom.HasQuery():
...        print(atom.DescribeQuery())
... 
AtomOr
  AtomAnd
    AtomType 8 = val
    AtomFormalCharge -1 = val
  AtomFormalCharge -2 = val
```

And this immediately shows you why you need high and low precedence ANDS because there brackets aren't used for operator precedence.

```
>>> sma = Chem.MolFromSmarts("[O;-1,-2]")
>>> for atom in sma.GetAtoms():
...     if atom.HasQuery():
...        print(atom.DescribeQuery())
... 
AtomAnd
  AtomType 8 = val
  AtomOr
    AtomFormalCharge -1 = val
    AtomFormalCharge -2 = val
````

Hope this helps.

**Comment by jose-mr** [comment]
@bp-kelley thank you for your explanation. It makes sense, since SMARTS is "query" language.

I have edited the title and the post to make clear that this is not a bug, in the interest of other people reading this.

As a workaround, in my code, I am using a regular expression to remove the ampersand manually.
```
import re
smarts_without_ampersand_in_charge = re.sub(r"&(\+|-)", r"\1", smarts)
```

 I need this because I am calculating the valence of the charged atom and only works correctly if the charge is explicitly set.

If you or someone thinks there is a better solution please let me know.

**Comment by bp-kelley** [comment]
It would be useful to understand your real issue.  It doesn't make a lot of sense to me to look at valence in smarts/query molecules.  I expect you are interested in the valence of the molecules the query matches.

```
>>> q = Chem.MolFromSmarts("[O&-1]")
>>> m = Chem.MolFromSmiles("[O-1]N=O")
>>> for atom_idx in m.GetSubstructMatch(q):
...     atom = m.GetAtomWithIdx(atom_idx)
...     print(atom.GetFormalCharge())
... 
-1
```

If you are interested in valence, you might consider looking at the degree/connectivity operators in smarts but be aware that you will need to handle implicit hydrogens as well.

https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html

There is a great set of examples here, you will note that most make use of the "X" operator which matches connectivity and can be used to set valences explicitly during the search.

https://www.daylight.com/dayhtml_tutorials/languages/smarts/smarts_examples.html

**Comment by jose-mr** [comment]
My starting point is a list of reaction smarts where each side of the reaction contains the entire molecules involved. I would like to create a smaller (more general) reaction smarts to looks for matches of similar reactions in other molecules. So I am  experimenting with different sizes for the reaction smarts. In particular for very small smarts patterns it is useful to have more restrictions for each atom (such as valence and charge) for the match to be meaningful.

Now that I have read the link you sent, it is probably more useful to define the degree and or connectivity operators, so I will definitely try these.
