### ISSUE TITLE
EmbedMolecule does not always respect atom index when performing embedding

### ISSUE THREAD

**Issue by ericmjonas** [rdkit/rdkit#3219]
**Configuration:**

- RDKit Version: 2020.03.1
- Operating system: Linux
- Python version (if relevant): 3.7.4
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? The RDKit Channel

**Description:**

In attempting to use `EmbedMolecule` to get sane initial values for downstream geometry processing, I've run into an issue. Sometimes, it will swap the index of atoms that I don't think should be swapped? For example: 

```
m1 = Chem.AddHs(Chem.MolFromSmiles('F/C=C'))
m2 = Chem.Mol(m1)
Chem.AllChem.EmbedMolecule(m2)
```

When we look at `m1` we see: 

![image](https://user-images.githubusercontent.com/36626/84055212-1e704580-a97a-11ea-8916-c16e12d04069.png)

and yet when we look at `m2` we see: 

![image](https://user-images.githubusercontent.com/36626/84055243-2af49e00-a97a-11ea-87cd-2a7d8883303b.png)

that is, H4 is now closer to F than H5. Now I recognize that, under traditional cis/trans isomerism, this isn't an issue -- both are the same molecule. But, for my downstream analysis, where I'm asking questions about inter-atom distances, this is a real problem -- suddenly the distance between H5 and F have shifted by a very large amount due to this embedding!

I recognize this is an edge case, but everywhere else I've seen in RDKit seems to carefully preserve atom index after various manipulations, making me think this is likely a bug/error. 

***Workarounds***
I've tried various workarounds (attempting to set stereochemistry values, setting distinct user properties for the H atoms so they are not identical, or trying template matching to recover the original ordering) without much success.

**Comment by bp-kelley** [comment]
That molecule isn't stereo (the cis and trans are superimposable - just rotate the molecule )

```
>>> Chem.MolToSmiles(Chem.MolFromSmiles('F/C=C'))
'C=CF'
```

Adding something besides hydrogen at H5 ( or H4) or making one an isotope does make it stereo:

```
>>> Chem.MolToSmiles(Chem.MolFromSmiles('F/C=C/Cl'))
'F/C=C/Cl'
```

**Comment by ericmjonas** [comment]
@bp-kelley Thank you for your response! You're right, the molecule itself is not stereo, but when you perform the rotation (as you suggested) there's a change in atom index. That is, there is no rotation of the molecule (that I can see) that will allow you to superimpose F0, H3, H4, and H5. 

I 100% agree that chemically these are the same molecule, but the fact that EmbedMolecule is permuting the indices like this makes subsequent downstream processing challenging. Is there a workaround that would let me match up the indices after the embedding?

**Comment by bp-kelley** [comment]
The problem you are going to face is that to RDKit both H4 and H5 are identical, so in either depictions or embedding, there is no constraint applied.

I think you best bet is to look for symmetry classes down stream and deal with them then:

```
>>> m1 = Chem.AddHs(Chem.MolFromSmiles('F/C=C'))
>>> list(Chem.CanonicalRankAtoms(m1, breakTies=False))
[3, 5, 4, 2, 0, 0]
```

This Indicates that the two Hs have the same symmetry and could swap with each other during the embedding process.

In fact, this process is regularly done with RMSD pruning.

**Comment by bp-kelley** [comment]
This also solves your issue for rotations around a single bond like a biphenyl.
