### ISSUE TITLE
Convert SMILES to FASTA

### ISSUE THREAD

**Issue by jannisborn** [rdkit/rdkit#3222]
**Configuration:**

- RDKit Version: `2019.09.1`
- Operating system: Mac OS
- Python version (if relevant): Python 3.7.4
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? https://conda.anaconda.org/rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

I think it would be useful to include functionalities for converting between `FASTA` and `SMILES`. While it's trivial to write a method `fasta_to_smiles` (which converts an amino acid sequence to a SMILES), the reverse operation (converting SMILES to FASTA) is challenging. 

Given that `smiles` corresponds to the canonical SMILES of an AA sequence, the naive approach would be `Chem.MolToFASTA(Chem.MolFromSmiles(smiles))`. 
This does not work and ultimately the reason is missing information in the monomer information. The [documentation of `MolToFASTA`](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.MolToFASTA) mentions this explicitly.
`NOTE: the molecule should contain monomer information in AtomMonomerInfo structures`

The difference in `Chem.MolFromSmiles` and `Chem.MolFromFASTA` is that only in the latter case, the monomer information is added. E.g.

```py

mol = Chem.MolFromSmiles('C[C@H](N)C(=O)O')
for k in range(mol.GetNumAtoms()):
    monomer_info = mol.GetAtomWithIdx(k).GetMonomerInfo()
```
In this case all `monomer_info` are empty, but in the case where `mol = Chem.MolFromFASTA('A')` the monomer info is available. I played with the `SetMonomerInfo` method and if I know the AA sequence already, it is possible to add the monomer info to the atoms of a `mol` object created from SMILES. This closes the loop and I can then get the fasta using `Chem.MolFromFASTA` however, in general I obviously don't know the sequence.

**My question is:**

**Is it possible to infer the monomer information when reading from SMILES?** I couldn't find any functionality and maybe it's simply impossible.

But since it's only 20 amino acids: **Would it be possible to add the needed information to the mol object, once it's read in?** I briefly tried substructure matching to match the SMILES atoms to their respective AA. I then wanted to load the monomer information from a dictionary that I computed offline but this seems very hand-crafted. Do you have any idea/advice/comment?

I think it would be a great functionality that would help many users.

**Comment by e253503** [comment]
I wish that one... I am getting empty results because of that missing monomer information. @jannisborn I know it`s so long time ago but how you found anything?

**Comment by navvye** [comment]
This would be very helpful for my current studies!
