### ISSUE TITLE
Chem.MolToSmiles(mol, doRandom=True) fails when the the mol has a salt or water

### ISSUE THREAD

**Issue by Laksh1997** [rdkit/rdkit#3225]
**Configuration:**

- RDKit Version: '2020.03.1'
- Operating system: Mac
- Python version (if relevant): 3.7
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit?

**Description:**

Title says it all really.

```
from rdkit import Chem

normal_smiles = 'CC[C@]1(O)C[C@H]2CN(CCc3c([nH]c4ccccc34)[C@@](C2)(C(=O)OC)c5cc6c(cc5OC)N(C=O)[C@H]7[C@](O)([C@H](OC(C)=O)[C@]8(CC)C=CCN9CC[C@]67[C@H]89)C(=O)OC)C1'

salt_smiles = '[Cl-].CN(C)[C@H]1[C@@H]2C[C@H]3C(=C(O)c4c(O)ccc(Cl)c4[C@@]3(C)O)C(=O)[C@]2(O)C(=O)\\C(=C(N)/O)C1=O.[H+]'

normal_mol = Chem.MolFromSmiles(normal_smiles)
salt_mol = Chem.MolFromSmiles(salt_smiles)

randomized_smiles = Chem.MolToSmiles(normal_mol, doRandom=True)  # works

randomized_salt_smiles = Chem.MolToSmiles(salt_mol, doRandom=True)  # fails

RDKit ERROR: Violation occurred on line 180 in file /usr/local/miniconda/conda-bld/rdkit_1585727826018/work/Code/GraphMol/ROMol.cpp



```

**Comment by Laksh1997** [comment]
@greglandrum Ever seen this before?

**Comment by thegodone** [comment]
True, You need  to split fragments before calling the fonction.

Envoyé de mon iPhone

**Comment by Laksh1997** [comment]
@thegodone How do you split fragments?

**Comment by mgarort** [comment]
Hi @Laksh1997 , I think what @thegodone means is to split the SMILES string by dots. In Python, you can split a string `my_string` using `my_character` as a separator with `my_string.split(my_character)`.

So in your case you need to do `salt_smiles.split('.')`.

Hope this helps.

**Comment by Y-H-Joe** [comment]
If I split the string, the SMILES_split will be no same as the original SMILES. Say we will have mol1 and mol2 from split SMILES (SMILES1 and SMILES2). How can I combine the mol1 and mol2 back to remain unchange?

**Comment by sunhwan** [comment]
You can join two SMILES strings by using period (.) as a delimiter. For your example, `'.'.join([Chem.MolToSmiles(mol1), Chem.MolToSmiles(mol2)])`.

**Comment by Y-H-Joe** [comment]
Sounds a good idea. Thanks! @sunhwan
