### ISSUE TITLE
Error in cmake build.

### ISSUE THREAD

**Issue by jcminerlanl** [rdkit/rdkit#3229]
I am trying to install rdkit after a recent git pull:
(Version: f45aef8effb618d5f2b42b1d7437221be5b56bcb)

When I attempt to run the following commands:
cmake -DPy_ENABLE_SHARED=1 \
  -DRDK_INSTALL_INTREE=ON \
  -DRDK_INSTALL_STATIC_LIBS=OFF \
  -DRDK_BUILD_CPP_TESTS=ON \
  -DPYTHON_NUMPY_INCLUDE_PATH="$(python -c 'import numpy ; print(numpy.get_include())')" \
  -DBOOST_ROOT="$CONDA_PREFIX" \
  ..

(This comes from https://www.rdkit.org/docs/Install.html).

I get the error:
Downloading https://github.com/catchorg/Catch2/archive/v2.12.1.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
CMake Error at Code/cmake/Modules/RDKitUtils.cmake:213 (MESSAGE):
  The md5 checksum for
  /home/jcminer/anaconda3/rdkit/External/catch/v2.12.1.tar.gz is incorrect;
  expected: 05c1b743773e546db9cb65b3b9315b02, found:
  d41d8cd98f00b204e9800998ecf8427e
Call Stack (most recent call first):
  External/catch/CMakeLists.txt:16 (downloadAndCheckMD5)

-- Configuring incomplete, errors occurred!

My machine has the correct proxies established, and the most up-to-date version of 'curl'. So I am not sure why this is happening.

Anyone know how to fix this problem?

Thanks.

**Comment by greglandrum** [comment]
Has doing a build worked for you before or is this the first time you’ve tried it?

**Comment by jcminerlanl** [comment]
This is a first time on this particular github repository.
I got around the earlier problem by downloading a copy of Catch2 myself and placing it where it was supposed to be, but now the problem has extended to the 'maeparser'.

....
-- maeparser include dir set as 'maeparser_INCLUDE_DIRS-NOTFOUND'
-- maeparser libraries set as 'maeparser_LIBRARIES-NOTFOUND'
-- Could NOT find maeparser (missing: maeparser_INCLUDE_DIRS maeparser_LIBRARIES) 
Downloading https://github.com/schrodinger/maeparser/archive/v1.2.3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
CMake Error at Code/cmake/Modules/RDKitUtils.cmake:213 (MESSAGE):
....

I could call the rdkit git repository from this machine, but it does not seem to accept the other calls made since.
