### ISSUE TITLE
drawOptions().addStereoAnnotation shows same stereolabel for all isomers

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#3230]
- RDKit Version: 2020.03.01
- Operating system: Windows 10
- Python version (if relevant): 3.6.5
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit

**Description:**
When adding stereochemical labels to SVG drawings using the addStereoAnnotation option, the output shows the same label for all stereocenters for all molecules. One would expect the label to vary in correspondence to the R/S configuration of the stereocenter. In the example below, 8 stereoisomers are generated with appropriate dashed and solid wedge bonds -- however all stereocenters are labelled (S). Actually, the label for one of the stereocenters is not visible, so I cannot confirm that this last stereocenter is also showing (S).
```
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import EnumerateStereoisomers
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG
print( rdkit.__version__ )
#make mol
mol = Chem.MolFromSmiles('C[C@H](OC1=C(N)N=CC(C2=CN(C3C[C@H](C)NCC3)N=C2)=C1)C4=C(Cl)C=CC(F)=C4Cl')
#generate stereoisomers
AllChem.Compute2DCoords(mol)
Chem.AssignStereochemistry(mol,force=True,flagPossibleStereoCenters=True)
enumsi_opt = EnumerateStereoisomers.StereoEnumerationOptions(maxIsomers=20, onlyUnassigned=False, tryEmbedding = True)
isomers = list(EnumerateStereoisomers.EnumerateStereoisomers(mol, enumsi_opt))
#draw isomers
for isomer in isomers:
    prep_mol = rdMolDraw2D.PrepareMolForDrawing(isomer, kekulize=True)
    drawer = rdMolDraw2D.MolDraw2DSVG(300, 300)
    opts = drawer.drawOptions()
    opts.addStereoAnnotation = True
    drawer.DrawMolecule(prep_mol)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()
    display(SVG(svg.replace('svg:','')))
```

**Output:**
![image](https://user-images.githubusercontent.com/309160/84559938-2a0e9400-ad0d-11ea-92db-fbede7dc2dbe.png)
![image](https://user-images.githubusercontent.com/309160/84559942-34c92900-ad0d-11ea-8db0-b398ed7e44e6.png)
![image](https://user-images.githubusercontent.com/309160/84559949-3abf0a00-ad0d-11ea-9a81-3bbf0715b53c.png)
![image](https://user-images.githubusercontent.com/309160/84559952-414d8180-ad0d-11ea-93ae-19849bd2f0e1.png)
![image](https://user-images.githubusercontent.com/309160/84559955-46aacc00-ad0d-11ea-9363-95a2e22084c3.png)
![image](https://user-images.githubusercontent.com/309160/84559957-4b6f8000-ad0d-11ea-9bbf-ff42c7959fe1.png)
![image](https://user-images.githubusercontent.com/309160/84559961-51fdf780-ad0d-11ea-95cc-db577c641563.png)
![image](https://user-images.githubusercontent.com/309160/84559964-59bd9c00-ad0d-11ea-8285-89ad2ea8ddb9.png)

**Comment by greglandrum** [comment]
You probably need to call AssignStereochemistry with the force argument set to True on each of the stereoisomers returned from EnumerateStereoisomers.
That function, for efficiency reasons, just sets the stereochemistry flags on the atoms/bonds, it does not automatically recalculate R/S labels since that is computationally expensive.

What should happen (need a github issue for this) is that EnumerateStereoisomers should clear the R/S flags on atoms.

**Comment by paconius** [comment]
Thank you for the suggestion. I modified the above code to include the recommended AssignStereochemistry call like so:
```
#draw isomers
for isomer in isomers:
    **Chem.AssignStereochemistry(isomer,force=True) #NEW!!!**
    prep_mol = rdMolDraw2D.PrepareMolForDrawing(isomer, kekulize=True)
    drawer = rdMolDraw2D.MolDraw2DSVG(300, 300)
```
With this change, we now observe that the missing stereolabel for the third stereocenter is now visible and shows (R) or (S) depending on the stereoconfiguration! Progress! :) 
Note however, that the original two stereocenters are still marked as (S) in every isomer.

***Output***:
![image](https://user-images.githubusercontent.com/309160/84573080-64f3e480-ad6c-11ea-8c45-42b525f4665c.png)
![image](https://user-images.githubusercontent.com/309160/84573091-71783d00-ad6c-11ea-899b-f8d4eb3224f5.png)
![image](https://user-images.githubusercontent.com/309160/84573100-7d63ff00-ad6c-11ea-89fb-aaa1405098b4.png)
![image](https://user-images.githubusercontent.com/309160/84573105-83f27680-ad6c-11ea-8ce5-9f71ce2a4dc6.png)
![image](https://user-images.githubusercontent.com/309160/84573113-8ce34800-ad6c-11ea-9d72-acb0c8a69a32.png)
![image](https://user-images.githubusercontent.com/309160/84573119-940a5600-ad6c-11ea-8281-b8a10ab6ce2d.png)
![image](https://user-images.githubusercontent.com/309160/84573129-9c629100-ad6c-11ea-9d26-0a460f427a0d.png)
![image](https://user-images.githubusercontent.com/309160/84573133-a1bfdb80-ad6c-11ea-885b-ec085c5d9f0f.png)

**Comment by greglandrum** [comment]
You need to provide the `cleanIt` argument to `AssignStereochemistry()` so that it will replace existing labels:
`Chem.AssignStereochemistry(isomer,force=True,cleanIt=True)`
The documentation for `AssignStereochemistry()` isn't clear about this, which we should fix.
