### ISSUE TITLE
MolFromMol2File: O.co2 atom type correctness check ignores phosphate groups

### ISSUE THREAD

**Issue by chmnk** [rdkit/rdkit#3246]
**Configuration:**
RDKit version 2020.09.1dev1, Ubuntu 18.04, python 3.6, RDKit compiled from sources

**Description:**
I was parsing a mol2 version of [this ligand](https://www.rcsb.org/ligand/TPI) that contains a phosphonate group, and catched the warning that terminated molecule parsing and lead to None instead of a molecule:
`warning - O.co2 with non C.2 or S.o2 neighbor.`  

It is thrown in the lines 324 -- 350 of ./Code/GraphMol/FileParsers/Mol2FileParser.cpp
```
      if (tATT == "C.2" || tATT == "S.o2") {
        // this should return only the bond between C.2 and O.co2
        Bond *b = res->getBondBetweenAtoms(idx, *nbrIdxIt);
        if (!isFixed[*nbrIdxIt]) {
          // the first occurrence is negatively charged and has a single bond
          b->setBondType(Bond::SINGLE);
          b->setIsAromatic(false);
          at->setFormalCharge(-1);
          at->setIsAromatic(false);
          nbr->setIsAromatic(false);
          isFixed[idx] = 1;
          isFixed[*nbrIdxIt] = 1;
        } else {
          // the other occurrences are not charged and have a double bond
          b->setBondType(Bond::DOUBLE);
          b->setIsAromatic(false);
          at->setIsAromatic(false);
          isFixed[idx] = 1;
        }
      } else {
        std::string nm;
        res->getProp(common_properties::_Name, nm);
        BOOST_LOG(rdWarningLog)
            << nm << ": warning - O.co2 with non C.2 or S.o2 neighbor."
            << std::endl;
        return false;
      }
```
Looks like phosphate/phosphonate groups are completely ignored here. However, the TRIPOS mol2 format specification (http://chemyang.ccnu.edu.cn/ccb/server/AIMMS/mol2.pdf) 
defines O.co2 as "oxygen in carboxylate and phosphate groups". Which is actually also strange, as it omits sulfur. 
May I add phosphorus to this check or there is a reason for its current sulfur-and-carbon-only design?

**Comment by hadim** [comment]
I am also having the same issue as well while trying to parse ligand files from PDBBind v2015.

**Comment by greglandrum** [comment]
Since the mol2 format is a bit of an inconsistent mess, where different toolkits/packages use different dialects of the format (or different meanings for the atom types), we chose to support the dialect generated by corina.

I no longer have access to corina, so I can't check how it handles this situation, but if someone else can do so and verify that this behavior is wrong, we can go ahead and fix it.

**Comment by chmnk** [comment]
> Any feedback?
I changed the condition in my local version if you are interested how to fix the particular phosphorus issue https://github.com/chmnk/rdkit/commit/10f4a54b902681379ca22c6a58449acd94653165
But that's not super convenient.

**Comment by chmnk** [comment]
> I no longer have access to corina, so I can't check how it handles this situation, but if someone else can do so and verify that this behavior is wrong, we can go ahead and fix it.

Ahh, I see! Sad, wanted to fix this in some global sense, but I don't have access either and corina seems to be fully non-free now...

**Comment by chmnk** [comment]
Seems that it was already discussed in a closed issue! Wasn't able to find it when I opened this one, but with 'corina' I accidentally googled it :)
#https://github.com/rdkit/rdkit/issues/1806
There is an example of corina behaviour. 
All oxygens in Cc1nc2ccc(cc2s1)P(=O)([O-])[O-] converted to O.co2.
In CCOP(=O)(=O)[O-], there was a valence warning and explicit O.2, O.2, and O.3 oxygens.

**Comment by chmnk** [comment]
@tbalius  Dear Trent, in a similar issue you have shared some tests with Corina's behaviour. If you still have access to Corina, may I ask you to run a simple test of reading the mol2 file that contains the smiles->mol2 conversion of Cc1nc2ccc(cc2s1)P(=O)([O-])[O-] and converting it back from mol2->smiles to check Corina's rules related to P-O.co2 parsing in mol2 files?

**Comment by tbalius** [comment]
Hi Maria, 

Here is input smiles file for corina:
>> cat temp.smi
Cc1nc2ccc(cc2s1)P(=O)([O-])[O-] temp

Here is the corina comand I ran to convert the smiles file to mol2:
>> corina -i t=smiles -o t=mol2 -d rc,flapn,de=6,mc=1,wh temp.smi temp.mol2

Here is the mol2 file produced by corina:
>> cat temp.mol2
#       Name: temp
#       Creating user name:     baliuste
#       Creation time:  12. 03. 2021 13:50

#       Modifying user name:    baliuste
#       Modification time:      12. 03. 2021 13:50

#       Program:        corina 4.3.0 0026  30.10.2019

# @<TRIPOS>ENERGY
#       0.00

# @<TRIPOS>FOOTER
# DeltaE 0.0
@<TRIPOS>MOLECULE
temp
  20   21    0    0    0
SMALL
NO_CHARGES


@<TRIPOS>ATOM
   1 C1            -1.2321    -0.8688     0.0096 C.3
   2 C2             0.0021    -0.0041     0.0020 C.2
   3 N3             1.1984    -0.4572    -0.0118 N.2
   4 C4             2.2083     0.4335    -0.0167 C.ar
   5 C5             3.6010     0.2154    -0.0311 C.ar
   6 C6             4.4640     1.2688    -0.0342 C.ar
   7 C7             3.9918     2.5739    -0.0227 C.ar
   8 C8             2.6369     2.8170    -0.0080 C.ar
   9 C9             1.7390     1.7516    -0.0051 C.ar
  10 S10           -0.0211     1.7022     0.0114 S.3
  11 P11            5.1612     3.9606    -0.0264 P.3
  12 O12            6.4827     3.5313     0.6973 O.co2
  13 O13            5.4837     4.3678    -1.5044 O.co2
  14 O14            4.5270     5.1805     0.7248 O.co2
  15 H15           -1.5398    -1.0718    -1.0162 H
  16 H16           -1.0139    -1.8089     0.5163 H
  17 H17           -2.0352    -0.3512     0.5342 H
  18 H18            3.9859    -0.7936    -0.0402 H
  19 H19            5.5284     1.0865    -0.0460 H
  20 H20            2.2703     3.8328     0.0010 H
@<TRIPOS>BOND
   1    1    2 1
   2    1   15 1
   3    1   16 1
   4    1   17 1
   5    2   10 1
   6    2    3 2
   7    3    4 1
   8    4    9 ar
   9    4    5 ar
  10    5    6 ar
  11    5   18 1
  12    6    7 ar
  13    6   19 1
  14    7    8 ar
  15    7   11 1
  16    8    9 ar
  17    8   20 1
  18    9   10 1
  19   11   12 ar
  20   11   13 ar
  21   11   14 ar

#       End of record

I hope that this helps. 

Take care,
Trent

**Comment by tbalius** [comment]
Hi Maria, 

If I read in the smiles file: 
```
>> cat temp.py
import rdkit
from rdkit import Chem

#--------------------------------------------------------------------------------------------------------------------------

def main():
    mol2file = "temp.mol2"
    smifile = "temp.smi"
    fhsmi = open(smifile,'r')
    smi = fhsmi.readlines()[0].split()[0]
    print(smi)

    #smifile = "temp2.smi"
    #m = Chem.rdmolfiles.MolFromMol2File(mol2file)
    m = Chem.rdmolfiles.MolFromSmiles(smi)
    netcharge = rdkit.Chem.rdmolops.GetFormalCharge(m)
    print("netcharge = %6.1f"%(netcharge))

    return

#################################################################################################################
main()

```

```
>> python temp.py
Cc1nc2ccc(cc2s1)P(=O)([O-])[O-]
netcharge =   -2.0
```

If I read in the mol2 file created with corina: 
```
>> cat temp.py
import rdkit
from rdkit import Chem

#--------------------------------------------------------------------------------------------------------------------------

def main():
    mol2file = "temp.mol2"
    smifile = "temp.smi"
    #fhsmi = open(smifile,'r')
    #smi = fhsmi.readlines()[0].split()[0]
    #print(smi)

    #smifile = "temp2.smi"
    m = Chem.rdmolfiles.MolFromMol2File(mol2file)
    #m = Chem.rdmolfiles.MolFromSmiles(smi)
    netcharge = rdkit.Chem.rdmolops.GetFormalCharge(m)
    print("netcharge = %6.1f"%(netcharge))

    return

#################################################################################################################
main()

``` 

```
 python temp.py
[14:37:09] temp: warning - O.co2 with non C.2 or S.o2 neighbor.
Traceback (most recent call last):
  File "temp.py", line 22, in <module>
    main()
  File "temp.py", line 16, in main
    netcharge = rdkit.Chem.rdmolops.GetFormalCharge(m)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.GetFormalCharge(NoneType)
did not match C++ signature:
    GetFormalCharge(RDKit::ROMol)
```

I hope that this helps,
Trent

**Comment by chmnk** [comment]
Hi Trent! Thank you for the swift reply! 
And what will happen if you open temp.mol2 with Corina? Will it produce the initial SMILES string, without any error in protonation and etc? Just wondering what's its exact behavior when handling P.3-O.co2 in the mol2 file to reproduce it in RDKit. To be sure that Corina doesn't crash nor show a warning.

**Comment by tbalius** [comment]
Hi Maria, 

It does not seem that Corina can convert molecules from mol2 to smiles: 
```
corina -i t=mol2 -o t=smiles temp.mol2 temp.mol2.smi
ERROR options(): Handling argument "t=smiles" of option -o
Type "corina -h" for online help
```

Here is a excerpt from the the command:

` corina -h all ` 

```
       -o - Output file type and options
           t=<value> - File type (sdf, sdf2, sdf3, rdf, rdf2, rdf3, mol, mol2, pdb, ctx, mmod, mae, top, par, odb, cif, dic, dyana, mopacxyz)
           a - Append output to output file
```

Take care,
Trent

**Comment by tbalius** [comment]
If I convert the mol2 to a sdf file it works just fine: 

`corina -i t=mol2 -o t=sdf temp.mol2 temp.mol2.sdf`

here is the sdf file: 
```
cat temp.mol2.sdf
temp
  corina  03152107263D 1   1.00000     0.00000     0
CORINA 4.3.0 0026  30.10.2019
 20 21  0  0  0  0            999 V2000
   -1.1951   -0.9194    0.0090 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0021   -0.0041    0.0020 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2464   -0.3604   -0.0118 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.2300    0.5616   -0.0162 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.6299    0.3960   -0.0309 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4538    1.4801   -0.0333 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.9472    2.7723   -0.0220 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5810    2.9716   -0.0075 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7360    1.8813   -0.0044 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0206    1.6698    0.0112 S   0  0  0  0  0  0  0  0  0  0  0  0
    5.0751    4.1930   -0.0257 P   0  0  0  0  0  0  0  0  0  0  0  0
    6.4086    3.8030    0.6982 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.3857    4.6094   -1.5037 O   0  5  0  0  0  0  0  0  0  0  0  0
    4.4051    5.3937    0.7253 O   0  5  0  0  0  0  0  0  0  0  0  0
   -1.4939   -1.1345   -1.0170 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9381   -1.8498    0.5153 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0191   -0.4358    0.5336 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.0520   -0.5981   -0.0406 H   0  0  0  0  0  0  0  0  0  0  0  0
    5.5234    1.3314   -0.0446 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1772    3.9732    0.0010 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1 15  1  0  0  0  0
  1 16  1  0  0  0  0
  1 17  1  0  0  0  0
  2 10  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  9  2  0  0  0  0
  4  5  1  0  0  0  0
  5  6  2  0  0  0  0
  5 18  1  0  0  0  0
  6  7  1  0  0  0  0
  6 19  1  0  0  0  0
  7  8  2  0  0  0  0
  7 11  1  0  0  0  0
  8  9  1  0  0  0  0
  8 20  1  0  0  0  0
  9 10  1  0  0  0  0
 11 12  2  0  0  0  0
 11 13  1  0  0  0  0
 11 14  1  0  0  0  0
M  CHG  2  13  -1  14  -1
M  END
$$$$
```

I hope that this helps,
Trent

**Comment by chmnk** [comment]
Thank you Trent!

@greglandrum so it seems that at least in this particular case Corina is able to handle the P.3-O.co2 pair of atom types. Probably I could add a fix for that warning if it reproduces the Corina's resulting sdf? Or it will be better to do more tests?

**Comment by LanceWesterhoff** [comment]
As of rdkit version '2022.09.3' this bug appears to still be happening. All of our phosphate O's (type O.co2) are being flagged with the following warning even though according to the mol2 spec, O.co2 is correct (and it would seem from the above-noted discussion that corina also sets these phosphate O's to O.co2):

 warning - O.co2 with non C.2 or S.o2 neighbor.

Would it be possible to merge this patch going forward? https://github.com/chmnk/rdkit/commit/10f4a54b902681379ca22c6a58449acd94653165

Thank you!
