### ISSUE TITLE
Draw.MolsToGridImage repeating atom indices

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3258]
Here's a demo:
![image](https://user-images.githubusercontent.com/540511/85848503-88298580-b7a9-11ea-982c-5b64f91425b0.png)

Applies to at least master and 2020.03.3

**Comment by DavidACosgrove** [comment]
Mmmm. Off the top of my head, I’d guess that’s not clearing the annotations when it starts preparing the new molecule. It’s cool that it avoids the first set of notes, though😀. 
I can look at it over the weekend.

**Comment by greglandrum** [comment]
I think I have an easy solution. PR coming soon.
