### ISSUE TITLE
Can't get SMILES

### ISSUE THREAD

**Issue by bokertof** [rdkit/rdkit#3264]
- RDKit Version: 2020.03.3
- Operating system: Windows 10
- Are you using conda? Yes

Hello! I try to get random SMILES for a molecule but faced the issue. And this problem occurs only in case of random SMILES, canonical SMILES is generated normally.
```
from rdkit import Chem

mol = 'CC1O[Ru]234(O)OC(C)O[Ru+]2(O)(O1)(OC(C)O3)OC(C)O4.F[B-](F)(F)F'
print(Chem.MolToSmiles(Chem.MolFromSmiles(mol), doRandom = True))
```
The issue:
```
    print(Chem.MolToSmiles(Chem.MolFromSmiles(mol), doRandom = True))
RuntimeError: Range Error
	idx
	Violation occurred on line 183 in file Code\GraphMol\ROMol.cpp
	Failed Expression: 5 < 5
	RDKIT: 2020.03.3
	BOOST: 1_72
```

**Comment by EBjerrum** [comment]
Seem to be related to molecules with separate entities (with a dot "."). You can randomize them with the doRandom flag if you split them first. Alternatively scramble the atom order and create a non-canonical SMILES.

**Comment by bokertof** [comment]
@EBjerrum Thank You! By the way, what is the difference between such two strings?
```
SMILES_1 = Chem.MolToSmiles(mol, doRandom = True)
SMILES_2 = Chem.MolToSmiles(mol, canonical = False, doRandom = True)
```
Because, in both cases we'll get random non-canonical SMILES

**Comment by linminhtoo** [comment]
Got this issue in both rdkit 2020.03.6 (windows x64) and 2020.09.1.0 (linux 64). Is there no possible fix other than splitting the reactants into individual molecules?

**Comment by EBjerrum** [comment]
It's two lines if you come from SMILES.

mols = [Chem.MolFromSmiles(smiles) for smiles in my_smiles.split(".")]
smiles_aug = ".".join([Chem.MolToSmiles(mol, doRandom = True) for mol on mols])
