### ISSUE TITLE
MinimalLib Dockerfile is broken at HEAD

### ISSUE THREAD

**Issue by skearnes** [rdkit/rdkit#3267]
```shell
$ docker build ./docker --no-cache
```
(Note that I was required to replace `emconfigure` with `emcmake` in the Dockerfile.)

```shell
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindFreetype.cmake:156 (find_package_handle_standard_args)
  Code/GraphMol/MolDraw2D/CMakeLists.txt:42 (find_package)
```

Various modifications to the Dockerfile and CMakeLists.txt also give boost errors (even when RDK_USE_BOOST_IOSTREAMS is `OFF`):

```shell
CMake Error at Code/cmake/Modules/RDKitUtils.cmake:55 (add_library):
  Target "RDStreams_static" links to target "Boost::iostreams" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  Code/RDStreams/CMakeLists.txt:25 (rdkit_library)
```

**Comment by greglandrum** [comment]
<sigh> I guess versions changed again. I will take a look.
Thanks for the error report @skearnes

**Comment by greglandrum** [comment]
@skearnes : I believe this is fixed in https://github.com/greglandrum/rdkit/tree/dev/update_emscripten_build
I will do a PR from this, but it would be great if you could check to see if that branch works for you as well.

**Comment by skearnes** [comment]
Thanks Greg! Would it make sense to add the minimal lib to the build tests?

**Comment by greglandrum** [comment]
yep. Just requires that someone set up the Azure DevOps config. :-)
