### ISSUE TITLE
cmake issue with target "Boost::system"

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#3271]
**Configuration:**

- RDKit Version: 202003.4
- Operating system: Debian unstable
- Python version (if relevant): 3.8.2
- Are you using conda? no
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit? 

**Description:**

I've started looking at updating the Debian package to 202003, from 201909.

I get the following errors during cmake configure:

```
-- Configuring done
CMake Error at Code/cmake/Modules/RDKitUtils.cmake:153 (add_executable):
  Target "testCoordGen" links to target "Boost::system" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
[hundreds more of those]
CMake Error at Code/cmake/Modules/RDKitUtils.cmake:49 (add_library):
  Target "ScaffoldNetwork" links to target "Boost::iostreams" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  Code/GraphMol/ScaffoldNetwork/CMakeLists.txt:3 (rdkit_library)


-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LOCALSTATEDIR
    CMAKE_INSTALL_SYSCONFDIR
    RDK_OPTIMIZE_NATIVE


CMake Generate step failed.  Build files cannot be regenerated correctly.
	cd obj-x86_64-linux-gnu && tail -v -n \+0 CMakeCache.txt
```

Does that ring a bell? I didn't change anything so far in the packaging

**Comment by greglandrum** [comment]
@mbanck : this looks like the class of problem which can be solved by adding `-DBoost_NO_BOOST_CMAKE=TRUE` to the arguments to cmake.

**Comment by mbanck** [comment]
Many thanks, running cmake went fine now and it started the build process.
