### ISSUE TITLE
Issue with correct chemical features calculation

### ISSUE THREAD

**Issue by pkiruba** [rdkit/rdkit#3272]
**Configuration:**

- RDKit Version: '2020.03.1'
- Operating system: macOS Catalina
- Python version (if relevant): 3.7.7
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit

**Description:**
Hi, I am trying to calculate the chemical features for a given molecule that comes from **3EYG** PDB (**MI1** as ligand ID). The H-bond donor seems not correct in this case. It’s finding 3 donors, one is correct (Donor at atom _N12_), but one seems N acceptor (Donor at atom _N17_ wrong feature calculation) and one is a flat N (Donor at atom _N3_ wrong feature calculation) that’s not a donor.  The code is shown below.

``` 
from rdkit import Chem 
from rdkit.Chem.rdchem import HybridizationType, BondType 
from rdkit.Chem import ChemicalFeatures 
from rdkit import RDConfig 
import os 

mol = Chem.MolFromMol2File("./ligand.mol2", removeHs=False) 
mol = Chem.AddHs(mol, addCoords=True) 

fdefName = os.path.join(RDConfig.RDDataDir, 'BaseFeatures.fdef') 
factory = ChemicalFeatures.BuildFeatureFactory(fdefName) 

feats = factory.GetFeaturesForMol(mol) 
for feat in feats: 
    idx = feat.GetAtomIds() 
    print(feat.GetFamily(), idx, mol.GetAtomWithIdx(idx[0]).GetPropsAsDict()['_TriposAtomName']) 
``` 
Here is an output from the above code

```
Donor (13,) N3
Donor (36,) N12
Donor (39,) N17
Acceptor (14,) O21
Acceptor (39,) N17
Acceptor (42,) N19
Aromatic (31, 32, 34, 36, 38) C15
Aromatic (30, 31, 38, 39, 40, 42) C10
Hydrophobe (8,) C5
Hydrophobe (11,) C6
Hydrophobe (16,) C22
Hydrophobe (21,) C7
Hydrophobe (31,) C15
Hydrophobe (32,) C16
```

Thanks in advance,
Kiruba

**Comment by greglandrum** [comment]
@pkiruba there is no 100% accurate definition of which atoms can and cannot be H-bond donors/acceptors. What you're seeing are the results of using the RDKit's default definitions. These may not be suited to your purposes, but they are fortunately pretty easy to modify. Here's the documentation for how features are defined:
https://www.rdkit.org/docs/RDKit_Book.html#the-feature-definition-file-format

**Comment by pkiruba** [comment]
@greglandrum Thank you for the clarification.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
