### ISSUE TITLE
Question: how to avoid large number in ring closure to be compatible with other software

### ISSUE THREAD

**Issue by ljn917** [rdkit/rdkit#3274]
**Configuration:**

- RDKit Version: 2019.09.03
- Operating system: Fedora 32
- Python version (if relevant): 3.6
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit?

**Description:**

I wonder if there is a way to avoid large number in ring closure, e.g. `%(N)`. Currently, RDKit allows up to 5 digits of N, but other software only allow max two digits. The Daylight [specification](https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html) only mentions two digits for ring closure, and the openSMILES [specification](http://opensmiles.org/spec/open-smiles-3-input.html) explicitly states "Three-digit numbers and larger are never permitted." This issue makes some of the rare long SMILES (usually for polymers) not parsable by other software.

**Comment by greglandrum** [comment]
@ljn917 : there's not currently any way to tell the SMILES-generation algorithm to attempt to minimize the number of rings open at any particular time.
