### ISSUE TITLE
Python unit tests do not pass on conda-forge for Python 3.8

### ISSUE THREAD

**Issue by jaimergp** [rdkit/rdkit#3282]
**Configuration:**

- RDKit Version: 2020.03.4
- Operating system: Linux, 64 MacOS
- Python version (if relevant): Python 3.8
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit?

**Description:**

While running the test suite to debug #2405, I found out some tests (`pythonTestDirChem`) do not pass for Python 3.8 on Linux 64 and MacOS. Windows is unaffected. 

* [Relevant lines for Linux 64](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=182678&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c7d0fcb4-3a10-5b26-dfea-e879a93fc2ab&l=6253)
* [Relevant lines for MacOS](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=182678&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=d9dbf137-9a7f-5666-c60c-9e1b2fc31445&l=7077)

**Comment by greglandrum** [comment]
I believe this is a duplicate with #2757 (but please confirm that)
It was fixed in #3268 and will be in the 2020.03.5 release.

**Comment by jaimergp** [comment]
Both reports sound super similar, indeed! I'll run the same configuration from master and will let you know!

**Comment by jaimergp** [comment]
Yep, confirmed. `master` reports no errors on py38.
