### ISSUE TITLE
Molecule drawn outside canvas

### ISSUE THREAD

**Issue by lpravda** [rdkit/rdkit#3297]
**Configuration:**

- RDKit Version: 2020.03.4
- Operating system:
- Python version (if relevant): 3.7.7.
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? rdkit

**Description:**

Dear rdkiters, I've encountered two problems while drawing molecule images from 2D template. First, a portion of the molecule is drawn outside the canvas (i.e. coordinates are there, but are not visible because of the set canvas size).

Second one of the wedged hydrogens gets [nan, nan] coordinates. 

Can anyone have a look into it?

Minimal code required to reproduce this issue 
[used data files](https://github.com/rdkit/rdkit/files/4943638/data.zip)

```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw

width = 500
zpn = Chem.MolFromMolFile('ZPN_ideal.sdf')
template = Chem.MolFromMolFile('ZPN_flat.sdf')

AllChem.GenerateDepictionMatching2DStructure(zpn, template)

drawer = Draw.rdMolDraw2D.MolDraw2DSVG(width, width)
options = drawer.drawOptions()

Draw.rdMolDraw2D.PrepareMolForDrawing(zpn, wedgeBonds=True, kekulize=True, addChiralHs=True)

drawer.DrawMolecule(zpn)
drawer.FinishDrawing()

with open('2d_mol.svg', 'w') as f:
    svg = drawer.GetDrawingText()
    f.write(svg)

print('done')
```

**Default image that comes out of rdkit**
<img width="476" alt="Screenshot 2020-07-19 at 13 43 56" src="https://user-images.githubusercontent.com/16133456/87873945-0c94b000-c9c6-11ea-8f15-b8c6cdb09f0f.png">

**Image with extended canvas 700x700**
<img width="638" alt="Screenshot 2020-07-19 at 13 46 16" src="https://user-images.githubusercontent.com/16133456/87873979-52517880-c9c6-11ea-9a76-208eb12bb41d.png">

**Comment by DavidACosgrove** [comment]
Interestingly, if you draw with atom indices (drawer.drawOptions().addAtomIndices = True), the picture is scaled correctly, though the extra hydrogen still goes missing.  This is also a problem with a recent fork of the code.  I have yet to try with the current master.

**Comment by DavidACosgrove** [comment]
Atom 36 (the stray hydrogen) comes into the drawing code with coords of (nan, nan).  I think it's probably not a big surprise in that case that the drawing scale is wrong.  I suggest that the problem is somewhere in AllChem.GenerateDepictionMatching2DStructure().  I think I pass the buck at this point.
