### ISSUE TITLE
Loss of double bonds symmetry with dative bonds

### ISSUE THREAD

**Issue by IvanChernyshov** [rdkit/rdkit#3303]
There is no possibility to encode with SMILES E/Z stereochemistry of a double bond, if one of its atoms forms a dative bond:

```python
from rdkit import Chem
print(Chem.rdBase.rdkitVersion)
> 2020.03.1
print(Chem.rdBase.rdkitBuild)
Windows|10.0.18363||MSVC|64-bit

mol = Chem.MolFromSmiles('CC=[C-]->[*])
b = mol.GetBondWithIdx(1)
b.SetStereo(Chem.BondStereo.STEREOZ)
b.SetStereoAtoms(0,3)
mol
```
![image](https://user-images.githubusercontent.com/17598902/88437422-1c215800-ce0f-11ea-85ae-86cb14533455.png)

```python
print(Chem.MolToSmiles(mol))
> *<-[C-]=C\\C
print(Chem.MolToSmiles(mol), canonical = False)
> C/C=[C-]->*
print(Chem.MolToSmiles(Chem.MolFromSmiles(Chem.MolToSmiles(mol))))
> *<-[C-]=CC
```

I guess, "/>", "\\>", "</", and "<\\" symbols should be added for coordination bonds (and hydrogen bonds).

**Comment by greglandrum** [comment]
Confirmed. It’s not currently possible to provide info about double bond stereo in SMILES.
I will take a look at supporting `/>` and `\>`.

**Comment by greglandrum** [comment]
As a general comment: as you have discovered, it is possible to set the double bond stereo yourself. When doing that I would recommend using STEREOCIS or STEREOTRANS instead of the Z or E variants. This is more explicit and you don’t need to worry about CIP ordering

**Comment by IvanChernyshov** [comment]
Oh, that's how it works. Thanks for the advice
