### ISSUE TITLE
Using SubStructureMatch ignored explicit hydrogens!

### ISSUE THREAD

**Issue by jcminerlanl** [rdkit/rdkit#3304]
I am trying to comb through the ZINC database and find molecules with a substructure that is not substituted (not linked with carbons or other atoms).
Essentially I want to avoid molecules that have my substructure of interest as an internal moiety.

I tried setting up a pattern for guanidine (NC(=N)N) by running the following code:
```
patt = Chem.MolFromSmiles('[H]N([H])C(=[N+]([H])([H]))N([H])')
smiles = Chem.SmilesMolSupplier('zinc-for-sale.txt', delimiter='\t',titleLine=False)
zincs = [x.split('\t')[1] for x in open('zinc-for-sale.txt')]
for i in range(len(smiles)):
   if (smiles[i].HasSubstructMatch(patt)):
      strng = 'Patt' + str(i) + '.pdb'
      mol=smiles[i]
      molH=Chem.AddHs(mol)
      em=AllChem.EmbedMolecule(molH,randomSeed=i)
      if(em==0):
         val=500
         val2=AllChem.UFFOptimizeMolecule(molH,maxIters=val)
         while (val2==1):
            val+=100
            val2=AllChem.UFFOptimizeMolecule(molH,maxIters=val)
         print(Chem.MolToPDBBlock(molH), file=open(strng,'w+'))      
         print('Success: Patt5: ',i, zincs[i].strip('\n'))
      else:
         print('Fail: Patt5: ',i, zincs[i].strip('\n'))
```

I only found a single molecule in my list that matched this criteria:
CCN(CC)C1=[N+](CC)CCN1CC 

As you can see, the moiety:
N(...)C1(=N+)...N1
Is in the center of the molecule based on the SMILES string.

I even test it in a one-liner:
```
Chem.MolFromSmiles('CCN(CC)C1=[N+](CC)CCN1CC').HasSubstructMatch(Chem.MolFromSmiles('[H]N([H])C(=[N+]([H])([H]))N([H])'))
```
...which returns 'True'.

Why did the program fail to account for the protonation state of the pattern, and why has it identified this SMILES string as a match when I explicitly declared hydrogens as part of my pattern?

Is there a way to make the program identify ONLY molecules with terminal groups (not alkylated or otherwise substituted)?

**Comment by greglandrum** [comment]
The hydrogens are removed by default when you parse molecules. This is well documented.

Using SMARTS instead of SMILES is a convenient way to express queries. In your case you could add degree queries (D in SMARTS) to each atom where you want to ensure that there are no additional connections.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
