### ISSUE TITLE
Inconsistent molecule recreation by converting from mol to smarts, then smarts to mol.

### ISSUE THREAD

**Issue by Sun694** [rdkit/rdkit#3306]
- RDKit Version: 2020.03.1
- Operating system: Win10
- Python version (if relevant): 3.7
- Are you using conda? Yes.
- If you are using conda, which channel did you install the rdkit from? conda install rdkit

If I convert a given molecule from mol, then to smarts, then back to mol, I get a different molecule. 

Sometimes this causes odd valence exceptions, such as oxygens having 2 bonds (two carbons), yet RDKIT seeing this as being illegal once I convert to smarts and back.

```python
from rdkit import Chem
from rdkit.Chem import Draw

def remol_smarts(m):
    return Chem.MolFromSmarts(Chem.MolToSmarts(m))

mol = Chem.MolFromSmiles("NC(CO~c1ccoc(=O)c1)C~c1cccc(~C(CC2CC2)SC~c2ccccc2)c1")
Chem.SanitizeMol(mol) # No errors.
plt.imshow(Chem.Draw.MolToImage(mol))
plt.pause(.5)
mol = remol_smarts(mol)
plt.imshow(Chem.Draw.MolToImage(mol))
Chem.SanitizeMol(mol) # AtomValenceException: Explicit valence for atom # 7 O, 3, is greater than permitted

print(Chem.MolToMolBlock(mol))
# snipped unneccessary details. the only two bonds for oxygen # 7 are these two, between the O and two carbons.
 6  7  4  0
  7  8  4  0

```

Other times, I will calculate SA score of a molecule (or QED, or molecular weight), then convert to smiles and back, I will get completely different values.

```python

from rdkit.Chem import QED
import sys
from rdkit import RDConfig
sys.path.append(os.path.join(RDConfig.RDContribDir, 'SA_Score'))
import sascorer

def light_analysis(mol):
    mol.UpdatePropertyCache(strict=False)
    Chem.GetSymmSSSR(mol)
    print("Mol wt: ", Descriptors.ExactMolWt(mol))
    print("QED: ",  QED.qed(mol))
    print("SA: ", sascorer.calculateScore(mol))

mol_a = Chem.MolFromSmiles('CC~c1ccccc1')

light_analysis(mol_a) # WT: 108, QED: .47, SA Score: 5.3 (EXTREMELY high)

mol_b = remol_smarts(mol_a)
light_analysis(mol_b) # Mol wt: 106. QEDL .51, SA Score: 1 (as it should be)
```

What is the cause of this? I cannot find anything in the documentation.

I initially was simply using the `remol_smarts` function to fix the second issue, but I recently started running into these (seemingly invalid) errors.

**Comment by greglandrum** [comment]
@Sun694 you're already fairly far down a path that's really confusing to me. So let's start at the beginning.
What is the main problem you are trying to solve?

It's worth pointing out that `~` in SMILES is an RDKit extension involving a zero-order bond. That's not going to be something recognized by things like the QED or SA calculations. Why are you using those bonds at all?

**Comment by Sun694** [comment]
> @Sun694 you're already fairly far down a path that's really confusing to me. So let's start at the beginning.
> What is the main problem you are trying to solve?
> 
> It's worth pointing out that `~` in SMILES is an RDKit extension involving a zero-order bond. That's not going to be something recognized by things like the QED or SA calculations. Why are you using those bonds at all?

Your comment on the zero-order bonds was the solution. I thought that default bond from mol.AddBond() would be single, and did not read the documentation correctly. Selecting "single" as the bond type solved all my issues.

**Comment by greglandrum** [comment]
glad to hear it!
