### ISSUE TITLE
BRICS fragment not a substructure of overall molecule (link atom removed)

### ISSUE THREAD

**Issue by PjFlan** [rdkit/rdkit#3307]
- RDKit Version: 2020.03.1
- Operating system: MacOS Catalina
- Python version (if relevant): 3.7.7
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda install rdkit

**Description:**
If you perform BRICSDecompose() on ``mol`` then one of the fragments you get back is ``rogue_frag``. This fragment is not a substructure of the overall molecule according to rdkit. I made sure to remove the link atom.

```
import rdkit.Chem as Chem
from rdkit.Chem import BRICS
import re

mol = Chem.MolFromSmiles('Cc1ccc2cc3c4ccc(-c5ccc(-c6ccc(C=C(C#N)C(=O)O)s6)s5)cc4c4ccccc4n3c2c1')
frags = list(BRICS.BRICSDecompose(mol))
rogue_frag = re.sub('\[[0-9]+\*\]', '', frags[0]) #remove link atom
rogue_frag = Chem.MolFromSmiles(rogue_frag)

print(mol.HasSubstructMatch(rogue_frag)) #False
```

**Comment by bp-kelley** [comment]
There are probably other oddities I'm not touching, but the main one is that BRICS uses isotopes to "store" information.  These isotopes aren't in the original structure, so any match is going to fail.  You can use the following to turn this off:

```
print(mol.HasSubstructMatch(rogue_frag, useChirality=False))
```

or you can strip the isotopes from the molecule.

```
for atom in rouge_frag.GetAtoms():
  atom.SetIsotope(0)
```

**Comment by PjFlan** [comment]
Hi Brian,

Thanks for getting back to me. Unfortunately the above hasn't worked. I am only extracting the raw SMILES of the fragments using ``BRICSDecompose()`` and then creating a fresh fragment molecule using the SMILES, so I wouldn't expect there to be any isotopes.

This is the only molecule in a database of ~4,000 that has caused this issue - all others work fine (i.e. the fragments are substructures of the molecule) so I'm guessing it's something specific to the structure of this molecule?

**Comment by bp-kelley** [comment]
It does look like you are stripping them:

```
print(frags)
['[16*]c1ccc2c(c1)-c1ccccc1-n1c-2cc2ccc(C)cc21', '[14*]c1ccc([14*])s1', '[7*]C(C#N)C(=O)O', '[7*]C[8*]']
```

**Comment by bp-kelley** [comment]
The are in the original structure.

**Comment by bp-kelley** [comment]
I think I might have had a different ordering for the brick output.  Here are my results from your set:

```
(1) [7*]C[8*] C
True
(2) [7*]C(C#N)C(=O)O C(C#N)C(=O)O
True
(3) [16*]c1ccc2c(c1)-c1ccccc1-n1c-2cc2ccc(C)cc21 c1ccc2c(c1)-c1ccccc1-n1c-2cc2ccc(C)cc21
False
(4) [14*]c1ccc([14*])s1 c1ccc()s1
```

For (4) you are generating an invalid smiles string.
It's unclear what is happening with (3) But I expect that the single bonds between aromatic rings might be the issue.

If I set all bonds to be generic, the substructure match works, but I agree it should work with the single bonds in (3)

Below is how I use AdjustQueryProperties to make this matches work.

```
import rdkit.Chem as Chem
from rdkit.Chem import BRICS

mol = Chem.MolFromSmiles('Cc1ccc2cc3c4ccc(-c5ccc(-c6ccc(C=C(C#N)C(=O)O)s6)s5)cc4c4ccccc4n3c2c1')
frags = list(BRICS.BRICSDecompose(mol, returnMols=True))
for i,f in enumerate(frags):
    for atom in f.GetAtoms():
        atom.SetIsotope(0)
    params = Chem.AdjustQueryParameters()
    params.makeBondsGeneric = True
    params.makeDummiesQueries = True
    rogue_frag = Chem.AdjustQueryProperties(f, params)
   
    print("(%d)"%i, Chem.MolToSmiles(rogue_frag), mol.HasSubstructMatch(rogue_frag)) #False
```

**Comment by PjFlan** [comment]
Apologies yes I was about to comment regarding the differing ordering, I forgot the fragments are returned as a set. I usually strip empty brackets also but forgot to include this line (explaining (4)).

It is indeed (3) that causes the issue for me. Thank you for your suggestion and this now works for me. Is it a bug that it does not pick up the substructure match in the first place?

Your above fix is perfect for my case though so thank you for the help.

**Comment by bp-kelley** [comment]
When using Smiles "*" is not considered a dummy atom unless you adjust the query params, I am unclear about the single bonds not matching though.

**Comment by greglandrum** [comment]
Here's a simplified version of this:
```
In [11]: mol = Chem.MolFromSmiles('Cc1ccc2cc3c4ccc(-c5cccs5)cc4c4ccccc4n3c2c1')                                                   

In [12]: frags = list(BRICS.BRICSDecompose(mol))                                                                                  

In [13]: frags                                                                                                                    
Out[13]: ['[14*]c1cccs1', '[16*]c1ccc2c(c1)-c1ccccc1-n1c-2cc2ccc(C)cc21']

In [14]: Chem.MolToSmiles(mol)                                                                                                    
Out[14]: 'Cc1ccc2cc3c4ccc(-c5cccs5)cc4c4ccccc4n3c2c1'
```
Here's mol:
![image](https://user-images.githubusercontent.com/540511/90587342-6eb91e80-e1d9-11ea-85b6-171aac6d6b2a.png)

and here's the larger fragment:
![image](https://user-images.githubusercontent.com/540511/90587375-80022b00-e1d9-11ea-947f-982cbf2dac6b.png)

The problem, as you've already identified, is that in the second fragment there are explicit single bonds in the six-membered N-containing ring in the fragment that are aromatic in the mol. For example the bond between atoms 23 and 24 in the molecule is aromatic, while the corresponding bond in the fragment (between atoms 12 and 13) is single.

I need to do some digging to figure out what's going on.

**Comment by greglandrum** [comment]
This is something odd in the aromaticity perception:
```
In [20]: mol = Chem.MolFromSmiles('Cc1ccc2cc3c4ccc(-C)cc4c4ccccc4n3c2c1')                                                         

In [21]: Chem.MolToSmiles(mol)                                                                                                    
Out[21]: 'Cc1ccc2c(c1)-c1ccccc1-n1c-2cc2ccc(C)cc21'

In [22]: mol = Chem.MolFromSmiles('Cc1ccc2cc3c4ccc(-c5cccs5)cc4c4ccccc4n3c2c1')                                                   

In [23]: Chem.MolToSmiles(mol)                                                                                                    
Out[23]: 'Cc1ccc2cc3c4ccc(-c5cccs5)cc4c4ccccc4n3c2c1'
```
