### ISSUE TITLE
Cannot Install RDKit on Google Colab

### ISSUE THREAD

**Issue by eereenah-fast** [rdkit/rdkit#3308]
- Google Colab
- Miniconda installation

Up until today I have used RDKit in Google Colab using the following Miniconda installation:

```
!wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!time bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local
!time conda install -q -y -c conda-forge rdkit

import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')
```
But now I keep getting the following error: `ModuleNotFoundError: No module named 'rdkit'`

I have tried installing RDKit with the full distribution of Anaconda as well, but no results so far. Is there any way I can fix this issue?

Thank you and apologies for the trivial question!

**Comment by bp-kelley** [comment]
I'm mildly surprised this works at all.

In any case, google collab is apparently using python 3.6.9 and miniconda is using python 3.8.  I tried this out and it does seem to work:

```
!wget -c https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!time bash ./Miniconda3-latest-Linux-x86_64.sh -b -f -p /usr/local
!time conda install -y python=3.6
!time conda install -q -y -c conda-forge rdkit
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages/')
import rdkit
from rdkit import Chem
m = Chem.MolFromSmiles("c1ccccc1")
```

Note you can get the python version with

```
sys.version
```

And then just change the 3.6 above to whatever version google collab is reporting.

Obviously, this is something we can't REALLY support, but installing miniconda with the /usr/local prefix is a bit of genius I think!

**Comment by eereenah-fast** [comment]
Thanks a lot for your help!
