### ISSUE TITLE
How to mapping a reaction

### ISSUE THREAD

**Issue by Bgiml** [rdkit/rdkit#3321]
**Configuration:**

- RDKit Version:
- Operating system:
- Python version (if relevant):
- Are you using conda?
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit?

**Description:**

I don't know how to automap a reaction :
For example:" O=S1(=O)C=Cc2ccccc12>>O=S1(=O)CCc2ccccc12 " to "[O:1]=[S:2]1(=[O:3])[CH:4]=[CH:5][c:6]2[cH:7][cH:8][cH:9][cH:10][c:11]12>>[O:1]=[S:2]1(=[O:3])[CH2:4][CH2:5][c:6]2[cH:7][cH:8][cH:9][cH:10][c:11]12"

```
Your code sample here
```

**Comment by greglandrum** [comment]
The RDKit does not currently have automatic atom-mapping capabilities available.
So, unfortunately, at the moment you either need to do it manually or use other software - bingo has an atom mapper that's supposed to be pretty good.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
