### ISSUE TITLE
Incorrect number of radical electrons calculated for metals

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3330]
Thanks to @lpravda for pointing this out:
```
In [4]: m = Chem.MolFromSmiles('[Mn+2]')                                                                                     

In [5]: m.Debug()                                                                                                            
Atoms:
	0 25 Mn chg: 2  deg: 0 exp: 0 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 3
Bonds:
```
The algorithm used really only works for main group elements.

Since it's not generally possible to calculate this value correctly, a good workaround is probably to just assign `numValenceElectrons % 2` for anything that has a default valence of -1

**Comment by jasondbiggs** [comment]
@greglandrum - is it expected that after this issue is fixed, the radical electrons no longer change when adding bonds?  

For example, the scandium atom has one unpaired electron in all three of `{"[Sc]", "[ScH]", "[ScH2]", "[ScH3]"}`.
