### ISSUE TITLE
Atom.SetNumExplicitHs method

### ISSUE THREAD

**Issue by IvanChernyshov** [rdkit/rdkit#3334]
RDKit Atom object has method "SetNumExplicitHs" which does not have any sense, and in reality, it sets a number of implicit Hs:

```python
from rdkit import Chem
mol = Chem.MolFromSmiles('[C]')
mol
```
![image](https://user-images.githubusercontent.com/17598902/90080508-78431200-dd13-11ea-8b52-f93e99ccc6ee.png)
```python
mol.GetAtomWithIdx(0).SetNumExplicitHs(4)
mol.GetAtomWithIdx(0).SetNumRadicalElectrons(0)
mol
```
![image](https://user-images.githubusercontent.com/17598902/90080450-4e89eb00-dd13-11ea-84f0-03275b860f51.png)

Should not it be renamed to "SetNumImplicitHs"?

**Comment by greglandrum** [comment]
Here's an explanation of this mess:
https://www.mail-archive.com/rdkit-devel@lists.sourceforge.net/msg00077.html

**Comment by greglandrum** [comment]
And, yes, we should change it, but doing so potentially breaks *a lot* of code, so we're trying to figure out how to do that as gently as possible.
