### ISSUE TITLE
Wrong SMILES form non-standard Inchi

### ISSUE THREAD

**Issue by jhjensen2** [rdkit/rdkit#3340]
Google Colab
conda-forge install
version 2020.03.5

m = Chem.MolFromInchi('InChI=1/C2H5NO2/c3-1-2(4)5/h1H2,3H3')
print(Chem.MolToSmiles(m))

yields `[NH3+]C[C+]([O-])[O-]` instead of `[NH3+]CC(=O)[O-]`

Same for this zwitterion: InChI=1/C6H5NO2/c8-6(9)5-2-1-3-7-4-5/h1-4,7H

**Comment by greglandrum** [comment]
Hi @jhjensen2, that's the tautomer that's encoded in the InChI.
