### ISSUE TITLE
Incorrect valence for some metals

### ISSUE THREAD

**Issue by prerpd** [rdkit/rdkit#3344]
I am using Chem.GetPeriodicTable() for getting valence of the atom in my code and while running it I found that for some of the metals (Ex, Zn), it is returning -1.

![image](https://user-images.githubusercontent.com/43773166/90475177-99a56300-e144-11ea-8b74-10192d6782f0.png)
 
I checked the 'atomic_data.cpp' file, and there valence is -1 for some of the metals. However, the correct valence can be found in the link below:
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-015-0068-4/tables/1

**Configuration:**

- RDKit Version: 2020.03.4
- Operating system: macOS Catalina 10.15.5
- Python version (if relevant): 
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit?

**Description:**

```
pt = rdkit.Chem.GetPeriodicTable()
val = pt.GetValenceList('Zn')
val2 = pt.GetDefaultValence(30)
ave = pt.GetNOuterElecs('Zn')
print(list(val), list(val), ave)
```

**Comment by greglandrum** [comment]
There isn't a "right" answer for valence numbers for many elements.
Within the RDKit `-1` indicates an atom where the maximum acceptable valence isn't clear. 
It tells the RDKit that it should not complain about excessive valence on these atoms.

If you believe that the InChI maximum valence states (those are what you link to) make sense for your application, it's pretty easy to add a post-processing test to your code to make sure that they aren't exceeded.
