### ISSUE TITLE
Incorrect resonance structures in presence of dative bonds

### ISSUE THREAD

**Issue by IvanChernyshov** [rdkit/rdkit#3349]
If an atom which is a part of a conjugated system forms a dative bond, it drops out of the resonance:

```python
from rdkit import Chem
mol = Chem.MolFromSmiles('CC(=O)[O-]')
print(len(Chem.ResonanceMolSupplier(mol)))
> 2
mol = Chem.MolFromSmiles('CC(=O)[O-]->[*]')
print(len(Chem.ResonanceMolSupplier(mol)))
> 1
```

I think, if an atom forms a dative bond as a donor, then such dative bonds must be ignored.

**Comment by greglandrum** [comment]
I agree.
@ptosco : seem right to you too?

**Comment by ptosco** [comment]
Sure. At the moment the algorithm does not account for dative bonds. I'll look into fixing this over the weekend.
@IvanChernyshov Thanks for reporting this!

**Comment by greglandrum** [comment]
I'm changing the milestone on this one because the merge to the release branch is non-trivial

**Comment by ptosco** [comment]
@greglandrum may I help?
