### ISSUE TITLE
Chem.MolToCXSmiles treats dative bonds incorrectly

### ISSUE THREAD

**Issue by IvanChernyshov** [rdkit/rdkit#3358]
Chem.MolToCXSmiles encodes dative bonds as RDKit ("->" and "<-"), whereas in CXSMILES format they must be encoded as single bonds with the corresponding comment in "info-block":

```python
from rdkit import Chem
mol = Chem.MolFromSmiles('N[Pt+2](N)([Cl-])[Cl-] |C:0.0,2.1,3.2,4.3|') # CXSmiles format, can be pasted to Marvin Sketch
Chem.MolToCXSmiles(mol)
> 'N->[Pt+2](<-N)(<-[Cl-])<-[Cl-]'  # RDKit format, cannot be pasted to Marvin Sketch
```

**Comment by greglandrum** [comment]
You're correct, but this is by design. What the RDKit calls "CXSMILES" is the standard RDKit SMILES (which, because of the inclusion of extensions like dative bonds, isn't actually SMILES) followed by a block with the CXSMILES extensions.

**Comment by IvanChernyshov** [comment]
@greglandrum Got it.
