### ISSUE TITLE
Dative bonds with boron requires negative charge

### ISSUE THREAD

**Issue by IvanChernyshov** [rdkit/rdkit#3359]
Let's try to make a molecule for BF3*OMe2 as two neutral molecules bonded with a dative bond:

```python
from rdkit import Chem
mol = Chem.MolFromSmiles('FB(F)(F)<-O(C)C')
mol
```
(None)

In this case, sanitization fails. However, if we add a negative charge to the boron atom, it works:
```python
mol = Chem.MolFromSmiles('F[B-](F)(F)<-O(C)C')
mol
```
![image](https://user-images.githubusercontent.com/17598902/91111456-3e65fa00-e689-11ea-9e28-50e1d2fcdd59.png)

In other words, the sanitization of dative and single bonds for boron is equal. It looks like a bug. Interestingly, the isoelectronic carbocation sanitizes without any problems:

```python
mol = Chem.MolFromSmiles('F[C+](F)(F)<-O(C)C')
mol
```
![image](https://user-images.githubusercontent.com/17598902/91111827-28a50480-e68a-11ea-8a97-44080e9e0031.png)

UPDATE: actually, the carbocation is also sanitized incorrectly as a radical:

```python
mol = Chem.MolFromSmiles('F[C+](F)(F)<-O(C)C')
mol.Debug()
> RDKit INFO: Atoms:
> RDKit INFO: 	0 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
> RDKit INFO: 	1 6 C chg: 1  deg: 4 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 1
> RDKit INFO: 	2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
> RDKit INFO: 	3 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
> RDKit INFO: 	4 8 O chg: 0  deg: 3 exp: 2 imp: 0 hyb: 5 arom?: 0 chi: 0
> RDKit INFO: 	5 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
> RDKit INFO: 	6 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
> RDKit INFO: Bonds:
> RDKit INFO: 	0 0->1 order: 1 conj?: 0 aromatic?: 0
> RDKit INFO: 	1 1->2 order: 1 conj?: 0 aromatic?: 0
> RDKit INFO: 	2 1->3 order: 1 conj?: 0 aromatic?: 0
> RDKit INFO: 	3 4->1 order: 17 conj?: 0 aromatic?: 0
> RDKit INFO: 	4 4->5 order: 1 conj?: 0 aromatic?: 0
> RDKit INFO: 	5 4->6 order: 1 conj?: 0 aromatic?: 0
```

**Comment by greglandrum** [comment]
@IvanChernyshov : I think you're expecting something from the RDKit's chemistry model that's just not there.
The standard sanitization/chemistry perception in the RDKit is designed for stable molecules.

For these unusual cases, you should probably expect that the sanitization isn't going to do what you want and that you'll need to write code to handle assigning H counts, radicals, and/or charges to the types of species you're working with.

**Comment by IvanChernyshov** [comment]
@greglandrum mmmm, F3B*OMe2, and similar systems are indeed stable molecules, see, e.g.:
- https://www.sigmaaldrich.com/catalog/product/aldrich/175501
- https://www.sigmaaldrich.com/catalog/product/aldrich/434280

The problem here is that RDKit can read such systems only in zwitterionic form, but not in neutral form with a dative bond (both forms are equal as they correspond to the same system):

```python
from rdkit import Chem
mol = Chem.MolFromSmiles('F[B-](F)(F)[O+](C)C')
mol
```
![image](https://user-images.githubusercontent.com/17598902/91648535-99c12f00-ea71-11ea-9d56-aff986922da3.png)
```python
mol = Chem.MolFromSmiles('FB(F)(F)<-O(C)C')
mol is None
> True
```

Undoubtedly, the zwitterionic form is the mainstream for organic chemistry. However, any chemical structure can be written in this form, including complexes of d-/f-elements. And here the question arises: why RDKit added support of dative bonds if any dative bond can be written in zwitterionic form?

Hopefully, my point is more precise now.
