### ISSUE TITLE
AssignBondOrdersFromTemplate failed in this case

### ISSUE THREAD

**Issue by pkrezel** [rdkit/rdkit#3362]
**Configuration:**

- RDKit Version: '2020.03.3'
- Operating system: Centos 7
- Python version (if relevant):3.6.8 
- Are you using conda?yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

With the molecule in the sdf attached, the function AssignBondOrdersFromTemplate failed to use the following smiles:'Cc1cc(no1)CN2CCN(CC2)c3c(cnc4c3[nH]c(n4)c5ccc(cc5)N6CCN(CC6)C)Br'.

```
Your code sample here
```

**Comment by pkrezel** [comment]
file

**Comment by bp-kelley** [comment]
@pkrezel the file appears to be missing.

**Comment by bp-kelley** [comment]
You posted this in another issue #3364 

```
AssignBondOrdersFromTemplate failed to applied the properties with AssignBondOrdersFromTemplate for this molecule:
smiles = "CC(=O)NC1C(C(C(OC1O)CO)O)O"
```

Is this essentially how you called AssignBondOrdersFromTemplate?

```
from rdkit import Chem
from rdkit.Chem import AllChem
refmol = Chem.MolFromSmiles("CC(=O)NC1C(C(C(OC1O)CO)O)O")
mol = Chem.MolFromSmiles('Cc1cc(no1)CN2CCN(CC2)c3c(cnc4c3[nH]c(n4)c5ccc(cc5)N6CCN(CC6)C)Br')
AllChem.AssignBondOrdersFromTemplate(refmol, mol)
```

**Comment by pkrezel** [comment]
Thank you for having taken into account my question. In fact, the problem doesn't happen anymore. Sorry. RDkit works correctly.
