### ISSUE TITLE
problems with the module  rdkit.Chem.MolStandardize

### ISSUE THREAD

**Issue by Npontillo** [rdkit/rdkit#3367]
**Configuration:**
- RDKit Version: 2017.09.1
- Operating system: Ubuntu 20.04
- Python version (if relevant): 3.6

**Description:** Hello everyone. I just installed RDKit  via conda to run a script (Autogrow4). I installed rdkit as recommended via conda and launched the script. I had an error in the output saying that rdkit was not installed. I found out that I had to downgrade python from 3.8 to 3.6 and also downgrade a boost library ( conda create -n rdkit-env -c rdkit rdkit libboost=1.65.1).
Now the script does not complain anymore about rdkit not being installed but it says : 
```
Traceback (most recent call last):
  File "../RunAutogrow.py", line 657, in <module>
    vars, printout = load_in_commandline_parameters(INPUTS)
  File "/home/nicola/.autogrow4/autogrow/user_vars.py", line 988, in load_in_commandline_parameters
    vars = filter_choice_handling(vars)
  File "/home/nicola/.autogrow4/autogrow/user_vars.py", line 2077, in filter_choice_handling
    import autogrow.operators.filter.execute_filters as Filter
  File "/home/nicola/.autogrow4/autogrow/operators/filter/execute_filters.py", line 10, in <module>
    from rdkit.Chem.MolStandardize import rdMolStandardize
ModuleNotFoundError: No module named 'rdkit.Chem.MolStandardize'
```
Any idea on how to fix this?

**Comment by ptosco** [comment]
The `rdMolStandardize` module was not available in RDKit 2017.09.1; I believe it was added in fall 2018. If you switch to using the latest RDKit release you won't incur in that error message anymore.

**Comment by Npontillo** [comment]
Thanks! How can I install a newer version with conda?

**Comment by greglandrum** [comment]
@Npontillo : If possible, I would suggest installing the RDKit using conda-forge: `conda install -c conda-forge rdkit`
There's a python 3.8 version there.

**Comment by Npontillo** [comment]
That was my starting point. With python 3.8 the script does not recognise the rdkit installation and gives me the following error :

``` You need to install rdkit and its dependencies.
Traceback (most recent call last):
  File "/home/nicola/.autogrow4/autogrow/user_vars.py", line 562, in check_dependencies
    import rdkit
ModuleNotFoundError: No module named 'rdkit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../RunAutogrow.py", line 657, in <module>
    vars, printout = load_in_commandline_parameters(INPUTS)
  File "/home/nicola/.autogrow4/autogrow/user_vars.py", line 986, in load_in_commandline_parameters
    check_dependencies()
  File "/home/nicola/.autogrow4/autogrow/user_vars.py", line 578, in check_dependencies
    raise ImportError("You need to install rdkit and its dependencies.")
ImportError: You need to install rdkit and its dependencies.
 ``` 

I needed to downgrade python from 3.8 to 3.6 but now I have a missing module problem.

**Comment by greglandrum** [comment]
You can install the rdkit for python 3.8 from conda forge:
```
conda create -n py38_rdkit python=3.8
conda install -c conda-forge rdkit
```
does that not work for you?

**Comment by vishnuthanki** [comment]
> You can install the rdkit for python 3.8 from conda forge:
> 
> ```
> conda create -n py38_rdkit python=3.8
> conda install -c conda-forge rdkit
> ```
> 
> does that not work for you?

Yes, I was facing the same issue and it works for me. Thank You

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
