### ISSUE TITLE
AssignBondOrdersFromTemplate fails with ligand in 2BHE

### ISSUE THREAD

**Issue by pkrezel** [rdkit/rdkit#3371]
**Configuration:**

- RDKit Version: '2020.03.3'
- Operating system: Centos 7
- Python version (if relevant):3.6.8 
- Are you using conda?yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**
AssignBondOrdersFromTemplate fails with the ligand BRY in 2BHE.

Pascal

```
Your code sample here
```

**Comment by greglandrum** [comment]
Hi, there's not enough example data or code here for us to be able to do anything with this
Please provide some sample code and data (or pointers to the data) so that we can reproduce it.
