### ISSUE TITLE
invalid sdf files sanitization problem

### ISSUE THREAD

**Issue by Frank-LIU-520** [rdkit/rdkit#3372]
**Configuration:**

- RDKit Version:2018.9.02
- Operating system:win10
- Python version (if relevant):
- Are you using conda?
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit?

**Description:**

```
mol.sdf
-442.7031923602849
     RDKit          3D

 24 24  0  0  0  0  0  0  0  0999 V2000
   -1.8463    0.1481    0.1120 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9268   -0.1176    1.1204 C   0  0  0  0  0  3  0  0  0  0  0  0
    0.6521   -0.1823    0.6140 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1945    1.1409    0.2736 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3716    1.2099   -0.3161 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0615    0.0860   -0.4443 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5688   -1.1303   -0.0487 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2918   -1.2179    0.3001 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9498   -0.8297   -1.0644 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0932   -0.8799   -0.0602 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.1580   -0.1733   -0.5462 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9276   -0.2662   -2.3117 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1353   -1.6728   -1.2641 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.0471   -2.3573    0.4784 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.3170   -2.2603   -0.4711 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.0244    0.0812   -1.1774 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6442    1.8950    0.3722 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.5121    1.9718    0.2996 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8199    0.8693    2.2716 H   0  0  0  0  0 15  0  0  0  0  0  0
   -1.0372   -1.0610    1.5292 H   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1043   -1.4822    0.7742 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5033    1.6696   -1.1309 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.5978    2.6680   -0.3033 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0161    1.5365   -0.2055 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2 20  1  0
  3  2  1  0
  4 18  1  0
  4  3  2  0
  5 23  1  0
  5  4  1  0
  6  5  2  0
  6  7  1  0
  7  8  2  0
  8 14  1  0
  8  3  1  0
  9 10  1  0
  9  1  1  0
 10  1  1  0
 10 21  1  0
 11 10  1  0
 12  9  1  0
 13  9  1  0
 15  7  1  0
 16  6  1  0
 22 24  1  0
 24  1  1  0
 24 17  1  0
M  RAD  1   2   2
M  END
$$$$
```

when i try to load a wrong sdf file (one H has no bond to any other element), the Chem.SanitizeMol(suppl[0]) cannot print out warning like 
"[11:23:40] ERROR: Could not sanitize molecule ending on line 6187
[11:23:40] ERROR: Explicit valence for atom # 8 H, 4, is less than permitted".
how can I check all sdf files if they are valid or not, and get the returned "true" or "false" flag?

```
Your code sample here
```
import sys
from io import StringIO
from rdkit import Chem
Chem.WrapLogs()

sio = sys.stderr = StringIO()

suppl = Chem.SDMolSupplier('./mol.sdf',removeHs=False)

Chem.SanitizeMol(suppl[0])
print("error message:",sio.getvalue())

**Comment by greglandrum** [comment]
@Mario-Liu : I'm not sure what you're asking about here. The SDF is perfectly valid - so parsing it doesn't generate errors - and the molecule it contains doesn't have any atoms with a valence that exceeds normal values - so sanitizing it doesn't generate errors.

The structure is certainly a bit strange, but it's not "invalid" as far as the RDKit is concerned.

It's not hard to write code to identify structures which contain features that you don't want to see. What specifically would you like to flag as "bad" in this structure?

**Comment by Mario-Liu** [comment]
when I perform “suppl = Chem.SDMolSupplier('mol-100k.sdf',removeHs=False)
hmols = [x for x in suppl if x is not None] ”

I got lots of error warnings as follow:
"[11:23:40] ERROR: Could not sanitize molecule ending on line 6187
[11:23:40] ERROR: Explicit valence for atom # 8 H, 4, is less than permitted".

So I would like to know what molecules do not have atoms whose valence is less than permitted through the messages of warning. When I exacuted the codes, those warnings just appear, and I cannot get the hints by codes like sio = sys.stderr = StringIO().

**Comment by mwisniewskidrugdesign** [comment]
Hi, Have you find out what caused it? I am facing the same problem right now

**Comment by timoleistner** [comment]
It seems like you try to load an SDF file which contains 100k molecules (assumption made from the name of the file).
The molecule block you posted does not seem to return any error, even though it looks like a weird structure.
![image](https://github.com/rdkit/rdkit/assets/38843394/6268d0fe-7b1c-48a4-bb0c-2067b0d6b565)
The problem you encounter seems, like the error says, to be on the line 6187 in this file, which most likely is a different molecule.

I would suggest to use a `try except` approach to see which molecules could not be read.
```Python
molecules = []
for mol in Chem.SDMolSupplier('mol-100k.sdf',removeHs=False):
    try:
        molecules.append(Chem.SanitizeMol(mol))
    except Exception as error:
        # one of the following
        #  molecules.append(f"{error}")
        molecules.append(None)
```
This way you can see which molecules could be sanitized and at which positions in your `molecules` list are `None` entries.
Or you can append the error message as a string.
Of course, you can also just append true or false to the list.
