### ISSUE TITLE
Does RDKit support the Canonical SMILES from PubChem as the same as that from Daylight?

### ISSUE THREAD

**Issue by swpper** [rdkit/rdkit#3373]
**Configuration:**

- RDKit Version: 2020.03.2.0
- Operating system: windows 10
- Python version (if relevant): 3.6

**Description:**
Hello, I am new to RDKit and SMILES. Because I don`t know if PubChem and Daylight use the same  canonicalization algorithm, so I want to know that, does RDKit support the Canonical SMILES from PubChem as the same result as that from Daylight, since Daylight is not opensource. And I have found that the some melocular has different SMILES like Fenfuram and most simple molecular has the same SMILES. 

SMILES for Fenfuram 
CC1=C(C=CO1)C(=O)NC2=CC=CC=C2  (PubChem, Computed by OEChem 2.1.5)
Cc1occc1C(=O)Nc2ccccc2                       (maybe from Daylight, "ESOL" dataset from DeepChem)

**Comment by greglandrum** [comment]
@swpper, what's important to remember is that any given molecule can be written as SMILES in many different ways. The idea of a canonicalization algorithm is to always write the same SMILES for the same molecule. However, there are also many different canonicalization algorithms, so a canonical SMILES from the Daylight toolkit may not be the same as the canonical SMILES from OEChem and the canonical SMILES from the RDKit may be different from both of them.

Fortunately when you're reading in the SMILES in none of this should matter. As long as the underlying molecule was the same, you should get the same results when reading any of these SMILES into the RDKit.

**Comment by swpper** [comment]
@greglandrum, thank you very much！
