### ISSUE TITLE
Issues about using MolDraw2DSVG to generate SVG

### ISSUE THREAD

**Issue by caiyingchun** [rdkit/rdkit#3374]
I have a series of similar molecules (these molecules have common substructure). Then I use the following code to generate SVG for each of them. 
```
def getMolSvg(mol):
      drawer = rdMolDraw2D.MolDraw2DSVG(300,300)
      drawer.DrawMolecule(mol, highlightAtoms=matches)
      drawer.FinishDrawing()
      svg = drawer.GetDrawingText().replace('svg:','')
      return svg
```
The code works and produces svg for each molecule. But the orientation of molecules in each svg is different from each other. I want such effect that 2D depict of molecules in svg is aligned to each other by common substructure. How to do it?
Thanks very much.

**Comment by greglandrum** [comment]
This is explained in the documentation:
https://www.rdkit.org/docs/GettingStartedInPython.html#working-with-2d-molecules-generating-depictions

**Comment by caiyingchun** [comment]
Thanks a lot.
