### ISSUE TITLE
Molecule rendering does not indicate double bonds with unknown stereo (crossed bonds)

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#338]
![image](https://cloud.githubusercontent.com/assets/540511/4500540/afdfffec-4a94-11e4-9596-2a6e5a8e387d.png)

**Comment by d-b-w** [comment]
This was fixed at some point in the last decade :)
```
m = Chem.MolFromSmiles('CC=CC')
Chem.Compute2DCoords(m)
print(Chem.MolToMolBlock(m))
Chem.MolFromMolBlock(Chem.MolToMolBlock(m))
```
<img width="816" alt="Screenshot 2024-09-13 at 1 55 59 PM" src="https://github.com/user-attachments/assets/a429b0ba-5c32-4da1-94dc-2d1d87b0e40b">
