### ISSUE TITLE
maxFontSize interacting badly with DrawMolecules

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3391]
**Configuration:**

- RDKit Version: master (this does not impact 2020.03.5)

**Description:**

This code:
```
m = Chem.MolFromSmiles('C')

drawer = Draw.MolDraw2DCairo(400,200,200,200)
drawer.drawOptions().maxFontSize=14
drawer.DrawMolecules((m,m))
drawer.FinishDrawing()
png = drawer.GetDrawingText()
Image(value=png,format='png')
```
produces this image:
![image](https://user-images.githubusercontent.com/540511/92088489-3ca8de80-edcd-11ea-9fbb-c5d020079a17.png)

Leaving out the change to `maxFontSize` we get:
![image](https://user-images.githubusercontent.com/540511/92088555-4f231800-edcd-11ea-9b8b-af8ae7296be5.png)

**Comment by DavidACosgrove** [comment]
Damn. I thought I’d fixed that one. I’ll take a look over the weekend.

**Comment by DavidACosgrove** [comment]
Thinking about this overnight, it has a ring of familiarity. I haven’t had a chance to look, but I think it is, to use a phrase popular in these parts at the moment “specific and limited.”  IIRC, it applies only to molecules with no explicit bonds drawn. Without that, the initial scale calculation has nothing to work on, and it goes a bit pear-shaped. I’ll have another go at it.

**Comment by greglandrum** [comment]
I can't reproduce this on master. There have been a bunch of code changes/fixes done since this was filed so it may well have been "accidentally" fixed.
Since I haven't tested all possible configurations, I'll just remove the milestone from this for the moment.
