### ISSUE TITLE
MinimalLib compiled from master doesnt work

### ISSUE THREAD

**Issue by rmrmg** [rdkit/rdkit#3399]
I download from master dockerfile for rdkitminimal

`wget https://raw.githubusercontent.com/rdkit/rdkit/master/Code/MinimalLib/docker/Dockerfile`
build  (I changed python to python3 in Dockerfile, otherwise builing process failed) and extract files:
`docker build ./ --no-cache`
`docker export ce9aec6beace21b7a56af4713d64bcaa23631a0dfad6d994a7790503d7192785 -o zawartosc.tar`

And the I checked demo.html and it failed with below presented errror in browser console (both chromium and firefox gives virtually the same msg):

>Navigated to file:///home/rmrmg/rdkit/zawartosc/src/rdkit/Code/MinimalLib/demo/demo.html
RDKit_minimal.js:1 both async and sync fetching of the wasm failed
abort @ RDKit_minimal.js:1
getBinary @ RDKit_minimal.js:1
Promise.then (async)
getBinaryPromise @ RDKit_minimal.js:1
instantiateArrayBuffer @ RDKit_minimal.js:1
instantiateAsync @ RDKit_minimal.js:1
createWasm @ RDKit_minimal.js:1
(anonymous) @ RDKit_minimal.js:1
RDKit_minimal.js:1 failed to asynchronously prepare wasm: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
(anonymous) @ RDKit_minimal.js:1
Promise.then (async)
instantiateArrayBuffer @ RDKit_minimal.js:1
instantiateAsync @ RDKit_minimal.js:1
createWasm @ RDKit_minimal.js:1
(anonymous) @ RDKit_minimal.js:1
RDKit_minimal.js:1 RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
abort @ RDKit_minimal.js:1
(anonymous) @ RDKit_minimal.js:1
Promise.then (async)
instantiateArrayBuffer @ RDKit_minimal.js:1
instantiateAsync @ RDKit_minimal.js:1
createWasm @ RDKit_minimal.js:1
(anonymous) @ RDKit_minimal.js:1
RDKit_minimal.js:1 Uncaught (in promise) RuntimeError: abort(RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at abort (file:///home/rmrmg/rdkit/zawartosc/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js:1:15641)
    at file:///home/rmrmg/rdkit/zawartosc/src/rdkit/Code/MinimalLib/demo/RDKit_minimal.js:1:17327`

Is this problem with rdkit(.js) or I missed something?

**Comment by greglandrum** [comment]
@rmrmg : I think the problem is likely that you can't load the files directly in your browser, they need to come from a server.
Here are some instructions for that:
https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing

**Comment by rmrmg** [comment]
True,
python3 -m http.server 8006
and then in browser: localhost:8006 works perfectly, thx.
