### ISSUE TITLE
A possible bug in 2020.03.5 release: RemoveHs+AddHs doesn't update implicit hydrogens count, leads to AtomValenceException

### ISSUE THREAD

**Issue by shayakhmetov** [rdkit/rdkit#3400]
The following code works well in 2019.09.3 release, but crashes in 2020.03.5 at the last line.
```
from rdkit import Chem
mol = Chem.MolFromSmiles('CCC')
print(mol.GetAtomWithIdx(0).GetNumImplicitHs())  # == 3
mol = Chem.AddHs(mol)  # In rdkit=2020.03.05, this line causes the last line to crash
print(mol.GetAtomWithIdx(0).GetNumImplicitHs())  # == 0
mol = Chem.RemoveHs(mol)
print(mol.GetAtomWithIdx(0).GetNumImplicitHs())  # == 3 in '2019.09.3', 0 in '2020.03.5'
mol = Chem.RWMol(mol)
mol.AddBond(0, 2, order=Chem.rdchem.BondType.SINGLE)
Chem.RemoveHs(mol)  # AtomValenceException in '2020.03.5'
```
`AtomValenceException: Explicit valence for atom # 0 C, 5, is greater than permitted`

It appears to be a bug (or a severe change in code behavior) as RemoveHs followed by AddHs does not update implicit hydrogens.

**Comment by danpol** [comment]
Hi, @greglandrum! The issue still appears in 2020.09.2

**Comment by greglandrum** [comment]
@danpol : that's because none of the volunteers who work on the project have had time to fix it and no one else from the open source community has contributed a fix
