### ISSUE TITLE
Cannot reproduce rdkit_fp with Chem.RDKFingerprint

### ISSUE THREAD

**Issue by tljm** [rdkit/rdkit#3401]
**Configuration:**

- RDKit Version: 2020.03.3
- Operating system: Ubuntu 16.04
- Python version (if relevant): 3.7.9
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit
- If you are not using conda: how did you install the RDKit? NA

**Description:**

What is the difference between fingerprints calculated using `Chem.RDKFingerprint` and PostgreSQL `rdkit_fp`?

I thought they are the same but I cannot reproduce results form PostgreSQL `rdkit_fp` using `Chem.RDKFingerprint`. This is what I have tried:

```python
def hex2bit(hex_string):
    # decodes hex string to bit string
    b = bytes.fromhex(hex_string)
    return ''.join([('0' * 8 + bin(bb)[2:])[-8:] for bb in b])

# setup DB connection - database name is dmol
import psycopg2
conn = psycopg2.connect(database="dmol")
curs = conn.cursor()

# prepare testing molecule and corresponding ctab
from rdkit import Chem
mol = Chem.MolFromSmiles("c1ccccc1NCCCO")
ctab = Chem.MolToMolBlock(mol)

# get FP using DB query
query = f"select bfp_to_binary_text(rdkit_fp(mol_from_ctab('{ctab}')))"
curs.execute(query)
fp_DB = curs.fetchone()[0]
bit_string_DB = hex2bit(fp_DB.hex())

# get FP with RDKit library, use defaults used by DB?
fp = Chem.RDKFingerprint(mol,1,6,1024,2)
bit_string = fp.ToBitString()

# compare
print(bit_string==bit_string_DB)
```

In the above example I have assumed that `Chem.RDKFingerprint` and `rdkit_fp` calculate the same type of FP. After reading some source code, I have decided to use following call to mimic behavior of `rdkit_fp`: `Chem.RDKFingerprint(mol,1,6,1024,2)`. I was inspired by the following line: <https://github.com/rdkit/rdkit/blob/6cd062a6dd9409ad8205490bbb741cd4dbabe931/Code/PgSQL/rdkit/adapter.cpp#L1226>  

Unfortunately, the last command from my example prints `False` which means FPs are not the same. What I am doing wrong?

**Comment by greglandrum** [comment]
Hi @tljm : you can convert the results of `bfp_to_binary_text()` to an ExplicitBitVect using the function `DataStructs.CreateFromBinaryText()`.

Here's a snippet showing how it works:
```
In [13]: curs.execute("select bfp_to_binary_text(rdkit_fp('c1ccc(I)cc1'::mol))")

In [14]: d = curs.fetchone()

In [15]: d
Out[15]: (<memory at 0x7f302a87c940>,)

In [16]: from rdkit import DataStructs

In [19]: bv = DataStructs.CreateFromBinaryText(bytes(d[0]))

In [20]: fp = Chem.RDKFingerprint(Chem.MolFromSmiles('c1ccccc1I'),1,6,1024,2)

In [21]: fp==bv
Out[21]: True
```

**Comment by tljm** [comment]
Thanks a lot! It works! This is what I was looking for.
