### ISSUE TITLE
[Feature Requirment] Is it possible to output ACS 1996 standard structure image with RDKit?

### ISSUE THREAD

**Issue by RuikangSun** [rdkit/rdkit#3409]
It seems that element symbols ( O, N, P, etc ) in output images are relatively small in contrast with carbon bonds. Is it possible to output ACS 1996 standard structure image with RDKit?
Examples:

![example.png](https://i.loli.net/2020/09/15/rO8RJ4SLon6pyvX.png)

**Comment by greglandrum** [comment]
The RDKit has an ACS1996 mode since the 2022.09 release cycle.
Here's more info: https://greglandrum.github.io/rdkit-blog/posts/2023-05-26-drawing-options-explained.html#acs1996-mode
