### ISSUE TITLE
[Question] Behavior of Draw.MolToImage

### ISSUE THREAD

**Issue by rajathsalegame** [rdkit/rdkit#3418]
- RDKit Version: 2020.03.5
- Operating system: macOS
- Python version (if relevant): Python 3.8.5

I see in many code snippets online that in the `Draw.MolToImage` method, there is a parameter `includeAtomNumbers=True` that is present; however, this behavior does not seem to be present in my RDKit version. Is this feature still in production mode?

**Comment by greglandrum** [comment]
An explanation/demo of how to use the various drawing options is here: https://greglandrum.github.io/rdkit-blog/posts/2023-05-26-drawing-options-explained.html
