### ISSUE TITLE
AddBond returns total number of bonds not the bond index

### ISSUE THREAD

**Issue by matteoferla** [rdkit/rdkit#3421]
**Configuration:**

- RDKit Version: 2020.03.1
- Operating system: MacOS
- Python version (if relevant): 3.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit?

**Description:**

I noticed that the documentation for `Chem.RWMol`'s `AddBond` method states that it returns the bond index. Whereas this is true for `AddAtom`, it is not true for `AddBond` in my system and instead is off by one.

This keeps tripping me up, could it be changed in the documentation (or in behaviour).

```
mod = Chem.RWMol(Chem.MolFromSmiles('CCC'))
print('Adding bond returns total number of bonds —' +
      f'returned {mod.AddBond(0,2, Chem.BondType.SINGLE)}. '+
      f'Cf. N bonds: {mod.GetNumBonds()} and Bond idx {mod.GetBondBetweenAtoms(0, 2).GetIdx()}')
print('Adding atom returns its index — '+
      f'returned {mod.AddAtom(Chem.Atom("C"))}. ' +
      f'Cf. N atoms: {mod.GetNumAtoms()}')
```
Thanks!

**Comment by Ashafix** [comment]
Just came across the same issue.
I was trying to add a bond and later change its stereochemistry representation. As @matteoferla  pointed out `AddBond` doesn't return the index of the newly created bond but it is off by one. Probably easier to fix the documentation than then implementation.
