### ISSUE TITLE
Tautomers with endocyclic double bonds should be preferred over exocyclic ones

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#3430]
Currently the tautomer scoring function does not seem to discriminate between tautomers with endocyclic double bonds vs exocyclic ones. In fact, both are aromatic according to the RDKit aromaticity model, but I still would prefer the endocyclic double bonds to score higher. After discussion with Greg we agreed this should be corrected.
This gist shows an example of the above:
https://gist.github.com/ptosco/20b06985cd8830d5e549165f6b9fc969

**Comment by bp-kelley** [comment]
Yeah, we just hit two days ago as well. If  we can fix this and the missing stereochemistry, I'll be happy.

We're ending up with structures like this which are suboptimal :)

![image](https://user-images.githubusercontent.com/9888416/94152596-c33f6180-fe49-11ea-80d9-2e0b34cdee57.png)

**Comment by ptosco** [comment]
@bp-kelley I love "suboptimal", that's going to be my euphemism of choice : )
By missing stereochemistry, are you referring to the issue addressed by the new `tautomerRemoveSp3Stereo` `CleanupParameter` or something different?
