### ISSUE TITLE
module 'rdkit' has no attribute 'Chem'

### ISSUE THREAD

**Issue by zhandn** [rdkit/rdkit#3442]
**Configuration:**

- RDKit Version: '2017.09.3'
- Operating system: macOS Catalina
- Python version (if relevant): 3.6.12
- Are you using conda? Yes

**Description:**

It seems that I can't find the Chem attribute in rdkit.
When I try:
```
import rdkit
rdkit.Chem. MolFromSmiles
```
It shows:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rdkit' has no attribute 'Chem'

If I try:
```
from rdkit.Chem import MolFromSmiles, SDMolSupplier
```

Python will show "65318 segmentation fault  python" and exit automatically.

**Comment by IchiruTake** [comment]
I think you should reinstall RDKit instead.
