### ISSUE TITLE
Link against system `rapidjson`

### ISSUE THREAD

**Issue by TheChymera** [rdkit/rdkit#3443]
Is there any easy way to link against the system rapidjson install path inside the build system?
A simple grep of the source code indicates no options like `-D*RAPIDJSON*` exist — but perhaps this is called differently?

If not, any ideas how this can best be patched? Would it suffice to turn off the downloads in `Code/GraphMol/MolInterchange/CMakeLists.txt` and point to the system directory — or does this have to be in the build tree?

Attempting to build `=rdkit-2020.03.6`

**Comment by mcs07** [comment]
The implementation in Open Babel might be a useful reference for a patch:
https://github.com/openbabel/openbabel/blob/master/CMakeLists.txt#L603-L630
and
https://github.com/openbabel/openbabel/blob/master/cmake/modules/FindRapidJSON.cmake
