### ISSUE TITLE
Configuration issues when building from source

### ISSUE THREAD

**Issue by TheChymera** [rdkit/rdkit#3444]
A source-based build fails with `-- Configuring incomplete, errors occurred!`.

**Configuration:**

- RDKit Version: 2020.03.6
- Operating system: Gentoo Linux
- Python version (if relevant): 3.7
- Are you using conda? no

**Description:**
[build.log](https://github.com/rdkit/rdkit/files/5291393/build.log)
[CMakeError.log](https://github.com/rdkit/rdkit/files/5291391/CMakeError.log)
[CMakeOutput.log](https://github.com/rdkit/rdkit/files/5291392/CMakeOutput.log)

**Comment by ptosco** [comment]
It looks like you might have old `External/catch/Catch*` and `External/RingFamilies/RingDecomposerLib-*` subdirectories in your source tree.
Try doing a `rm -rf` on those, which will trigger a fresh download by `cmake`. Then your `cmake` configuration should succeed.

**Comment by TheChymera** [comment]
@ptosco thank you :) I guess that's because I download a few of the files manually. For context, in Gentoo, all downloads are handled by the package manager and the build is done quasi-offline. This protects against build-time trickery.

```
    https://github.com/schrodinger/maeparser/archive/v1.2.3.tar.gz -> maeparser-1.2.3.tar.gz
    https://github.com/schrodinger/coordgenlibs/archive/v1.4.0.tar.gz -> coordgenlibs-1.4.0.tar.gz
    https://github.com/Tencent/rapidjson/archive/v1.1.0.tar.gz -> rapidjson-1.1.0.tar.gz
```

We also do the unpacking and place them where the build system expects them. Is there no way to make this work? Ideally all of these packages would be unbundled at some point, to prevent duplicating them, but that's only a priority for rapidjson ( https://github.com/rdkit/rdkit/issues/3443 ) since all the others are currently only needed by rdkit.

**Comment by TheChymera** [comment]
@ptosco any ideas on this? I can't seem to figure it out :(
