### ISSUE TITLE
AttributeError: module 'rdkit.Chem.Draw.rdMolDraw2D' has no attribute 'MolDraw2DCairo'

### ISSUE THREAD

**Issue by ryszard314159** [rdkit/rdkit#3445]
**Configuration:**

- RDKit Version: '2020.03.4'
- Operating system: macOS Catalina (10.15.7)
- Python version (if relevant): 3.8.5
- Are you using conda? no
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit? brew install rdkit

**Description:**

As far as I can tell installation went smoothly and everything I tried so far works fine,
but now I am getting:
AttributeError: module 'rdkit.Chem.Draw.rdMolDraw2D' has no attribute 'MolDraw2DCairo'
and when I look at rdkit.Chem.Draw.rdMolDraw2D attributes (see below) the list is
much shorter, and many described in https://www.rdkit.org/docs/source/rdkit.Chem.Draw.rdMolDraw2D.html
are missing 

```
Your code sample here
>>> drawer = rdkit.Chem.Draw.rdMolDraw2D.MolDraw2DCairo(500,500)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rdkit.Chem.Draw.rdMolDraw2D' has no attribute 'MolDraw2DCairo'
>>> rdkit.rdBase.rdkitVersion
'2020.03.4'
>>> dir(rdkit.Chem.Draw.rdMolDraw2D)
['ContourAndDrawGaussians', 'ContourAndDrawGrid', 'ContourParams', 'IntStringMap', 'MolDraw2D', 'MolDraw2DSVG', 'MolDrawOptions', 'PrepareAndDrawMolecule', 'PrepareMolForDrawing', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'map_indexing_suite_IntStringMap_entry']
>>> 

```

**Comment by thorlucas** [comment]
Having this issue as well

**Comment by thorlucas** [comment]
Fixed! I pushed a commit to the homebrew RDKit repo that fixes this issue. It turns out that it wasn't building with Cairo despite the pycairo flag. Try reinstalling RDKit from homebrew with the "--with-pycairo" flag.
