### ISSUE TITLE
ringMatchesRingOnly=True and completeRingsOnly=True don't work properly

### ISSUE THREAD

**Issue by danielzaidman** [rdkit/rdkit#3447]
**Configuration:**

- RDKit Version:
- Operating system:
- Python version (if relevant):
- Are you using conda?
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit?

RDKit version 2020.03.3.
I'm running it on Linux, installed using conda.
I don't remember the channel I used to install.

**Description:**

When using the rdFMCS.FindMCS function, the options of ringMatchesRingOnly=True and completeRingsOnly=True don't work. They give this weird error:

****
Pre-condition Violation
RingInfo not initialized
Violation occurred on line 83 in file /opt/conda/conda-bld/rdkit_1591929907781/work/Code/GraphMol/RingInfo.cpp
Failed Expression: df_init
****

Traceback (most recent call last):
  File "/home/prosettac/PRosettaC/auto.py", line 137, in <module>
    main(sys.argv[0], sys.argv[1:])
  File "/home/prosettac/PRosettaC/auto.py", line 41, in main
    Anchors.append(pl.get_mcs_sdf(Heads[i], Subs[i], protac))
  File "/gpfs01/home/prosettac/PRosettaC/protac_lib.py", line 42, in get_mcs_sdf
    Matches = NewSdf.GetSubstructMatches(NewSdf, uniquify=False)
RuntimeError: Pre-condition Violation
	RingInfo not initialized
	Violation occurred on line 83 in file Code/GraphMol/RingInfo.cpp
	Failed Expression: df_init
	RDKIT: 2020.03.3
	BOOST: 1_67

```
Your code sample here
```

Also, in a more ancient version I used, they didn't produce errors, but simply didn't give the right answers, so it may be the same bug but with a different appearance.

Hope this is enough details.
If you need more, please let me know.

**Comment by bp-kelley** [comment]
This error happens when the molecules aren’t sanitized, or at least, haven’t called the ring finding code.

Without looking at the source code that is calling the mcs, it is hard to tell.
