### ISSUE TITLE
RDkit installation on Ubuntu 20 (WSL)

### ISSUE THREAD

**Issue by ValeryPolyakov** [rdkit/rdkit#3456]
**Configuration:**

- RDKit Version: Latest?
- Operating system: Ubuntu 20 (WSL)
- Python version (if relevant): 3.6.12
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? default
- If you are not using conda: how did you install the RDKit?

**Description:**
Below is the screenshot after I installed and activated rdkit:

(my-rdkit-env) vpolyakov@vpolyakov-pc:~$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vpolyakov/anaconda3/envs/my-rdkit-env/lib/python3.6/site-packages/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: libboost_python3.so.1.65.1: cannot open shared object file: No such file or directory

**Comment by greglandrum** [comment]
To the best of my knowledge, the rdkit is not available from the default conda channel. Did you install it from conda-forge or the rdkit channel?

Please provide the rdkit version that you installed as well. It's probably easiest if you provide the output of doing `conda list` in your `my-rdkit-env` environment.

**Comment by ValeryPolyakov** [comment]
Hi Greg,

I was using the following command to install rdkit: *conda create -c rdkit
-n my-rdkit-env rdkit*

Here is the output of conda list:

# packages in environment at /home/vpolyakov/anaconda3/envs/my-rdkit-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
blas                      1.0                         mkl
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.7.22                     0
cairo                     1.14.12              h8948797_3
certifi                   2020.6.20                py36_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.10.2               h5ab3b9f_0
glib                      2.65.0               h3eb4bd4_0
icu                       58.2                 he6710b0_3
intel-openmp              2020.2                      254
jpeg                      9b                   h024ee3a_2
lcms2                     2.11                 h396b838_0
ld_impl_linux-64          2.33.1               h53a641e_7
libboost                  1.73.0              h37e3b65_11
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_1
libuuid                   1.0.3                h1bed415_2
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               he19cac6_1
lz4-c                     1.9.2                he6710b0_1
mkl                       2020.2                      256
mkl-service               2.3.0            py36he904b0f_0
mkl_fft                   1.2.0            py36h23d657b_0
mkl_random                1.1.1            py36h0573a6f_0
ncurses                   6.2                  he6710b0_1
numpy                     1.19.1           py36hbc911f0_0
numpy-base                1.19.1           py36hfa32c7d_0
olefile                   0.46                     py36_0
openssl                   1.1.1h               h7b6447c_0
pandas                    1.1.2            py36he6710b0_0
pcre                      8.44                 he6710b0_0
pillow                    7.2.0            py36hb39fc2d_0
pip                       20.2.3                   py36_0
pixman                    0.40.0               h7b6447c_0
py-boost                  1.73.0          py36h962f231_11
python                    3.6.12               hcff3b4d_2
python-dateutil           2.8.1                      py_0
pytz                      2020.1                     py_0
rdkit                     2018.03.2.0      py36h6bb024c_1    rdkit
readline                  8.0                  h7b6447c_0
setuptools                49.6.0                   py36_1
six                       1.15.0                     py_0
sqlite                    3.33.0               h62c20be_0
tk                        8.6.10               hbc83047_0
wheel                     0.35.1                     py_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.5                h9ceee32_0

**Comment by mattwthompson** [comment]
Not sure why an older version is pulled it, but I can recreate this on WSL. Using `conda-forge` (`conda create -c conda-forge
-n my-rdkit-env rdkit`) finds a 2020 version so that might be preferred

**Comment by ValeryPolyakov** [comment]
Matt and Greg,

Thanks a lot, this resolves the issue!

Valery
