### ISSUE TITLE
GetSubstructMatches get unexpected result while using explict H pattern

### ISSUE THREAD

**Issue by xiangup1** [rdkit/rdkit#3483]
**Configuration:**

- RDKit Version: 2020.03
- Operating system: Linux
- Python version (if relevant): 3.7.6

**Description:**

```
mol = Chem.AddHs(Chem.MolFromSmiles('CC(C)(C)C'))
patt1 = Chem.MolFromSmarts('C(C([H])([H])[H])(C([H])([H])[H])C([H])([H])[H]')
mol.GetSubstructMatches(patt1)
patt2 = Chem.MolFromSmarts('C([CH3])([CH3])[CH3]')
mol.GetSubstructMatches(patt2)

```
Out[1]: 
((1, 0, 5, 6, 7, 2, 8, 9, 10, 3, 11, 12, 13),
 (1, 0, 5, 6, 7, 2, 8, 9, 10, 4, 14, 15, 16),
 (1, 0, 5, 6, 7, 3, 11, 12, 13, 4, 14, 15, 16))
Out[2]: 
((1, 0, 2, 3), (1, 0, 2, 4), (1, 0, 3, 4), (1, 2, 3, 4))

**Comment by mwojcikowski** [comment]
Note that in smarts `[H]` means any atom with one implicit Hs.

**Comment by bp-kelley** [comment]
The second pattern isn’t matching the hydrogens, it is matching atoms that have a certain number of hydrogens attached.

**Comment by bp-kelley** [comment]
@xiangup1 I think this question has been answered, feel free to reopen if you need more help.
