### ISSUE TITLE
Bad UFF geometries for organometallic compounds

### ISSUE THREAD

**Issue by jhjensen2** [rdkit/rdkit#3487]
version 2020.03.3 installed on Google Colab. [Link to notebook](https://colab.research.google.com/drive/1ZBu27MOuD2STOSWcgMmKR7B4jgQoVQi-?usp=sharing)

By visual inspection of the 3D structures it appears that the embed code and UFF optimisation has problems with organometallic compounds:

```
# smiles[0]: so-so embed, very bad UFF optimisation
# smiles[1], smiles[2] embed fails
# smiles[3]: good embed, bad UFF optimisation

smiles = ['[O+]#[C-]->[Fe+2](<-OC(C)C)123<-PC=C[N-]->1CC[N-]->2C=CP->3','O->[Fe](O)(O)(<-O)(<-O)<-O','O->[Fe+2](<-O)(<-O)(<-O)(<-O)<-O',
          'CN(C)c1ccccc1[CH2-]->[Sc+3](<-[CH2-]c1ccccc1N(C)C)<-N1(C)CCCCC1']
m = Chem.MolFromSmiles(smiles[3])
mh = Chem.AddHs(m)
rdDistGeom.EmbedMolecule(mh, randomSeed=1)
AllChem.UFFOptimizeMolecule(mh)
mh
```

Let me know if you need more examples.

**Comment by jhjensen2** [comment]
Update: UFF optimisation in Open Babel works very well: [link to notebook](https://colab.research.google.com/drive/1TyBmytNLEbU7jZUvWF6N9-tg2M_bclSH?usp=sharing)
The main difference is that all bonds to transition metal are covalent

**Comment by greglandrum** [comment]
yeah, I suspect we need to update the atom typing to take dative bonds into account.
