### ISSUE TITLE
Unexpected Behavior of HasSubstructMatch for Murcko Scaffold from SMARTS

### ISSUE THREAD

**Issue by rajathsalegame** [rdkit/rdkit#3489]
I am having some unexpected behavior when checking a molecule has a substruct match with the Murcko Scaffold from SMARTS. Specifically, my problem is as follows:

This is my original mol:

`mol = Chem.MolFromSmiles('FC1=CC(F)=CC(C[C@@H](C2=NC(C#CC(S(=O)(C)=O)(C)C)=CC=C2C3=CC=C(Cl)C4=C3N(CC(F)(F)F)N=C4NS(=O)(C)=O)NC(CN5C(C(F)(F)[C@@]6([H])[C@]7([H])C6)=C7C(C(F)(F)F)=N5)=O)=C1')`

I then construct the Murcko Scaffold and the scaffold SMARTS as follows:
```
core = MurckoScaffold.GetScaffoldForMol(mol)
core_sma = Chem.MolToSmarts(core)
```

I then check for a substruct match as follows:

```
mol.HasSubstructMatch(core) --> returns True
mol.HasSubstructMatch(Chem.MolFromSmarts(core_sma)) --> returns False
```

It seems like there is some issue converting back and forth between SMARTS, or is there something I am missing here?

**Comment by greglandrum** [comment]
Hi @rajathsalegame 
You have substituted aromatic N atoms in your molecule. The scaffold for those includes an implicit H on those Ns and that shows up in the SMARTS:
![image](https://user-images.githubusercontent.com/540511/96670634-18469880-1360-11eb-9aa5-b12b45b4e540.png)
The H in the SMARTS causes the query constructed from it to not match your original molecule.

If you'd like to generate a SMARTS from the core, you can just remove those implicit Hs with this bit of code:
```
for atom in core.GetAtoms():
    if atom.GetIsAromatic() and atom.GetAtomicNum()!=6 and atom.GetTotalNumHs():
        atom.SetNoImplicit(True)
        atom.SetNumExplicitHs(0)
```
Then it works:
![image](https://user-images.githubusercontent.com/540511/96670743-6cea1380-1360-11eb-93ab-d1d6d1f02b68.png)

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
