### ISSUE TITLE
 from .rdBase import rdkitVersion as __version_ and ImportError: DLL load failed: The specified module could not be found 

### ISSUE THREAD

**Issue by TalWac** [rdkit/rdkit#3500]
**Configuration:**

- RDKit Version:  '2019.09.3'
- Operating system: win 10
- Python version (if relevant): '3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]'
- Are you using conda? YES
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit? using pycharm

**Description:**
I wrote a script on Pycharm using conda interpreter. when running the scrip on Pycharm it runs fine.

However, when the API of Compound Discoverer (software) runs the script, it shows those warnings and finally fails.

Time	Processing Node	Level	Message
11:19 AM	(49): Scripting Node	Error	The executable ran for 242.6 ms and finished with error(s), exit code was :1
11:19 AM	(49): Scripting Node	**Warning	ImportError: DLL load failed: The specified module could not be found.**
11:19 AM	(49): Scripting Node	**Warning	    from .rdBase import rdkitVersion as __ version __**
11:19 AM	(49): Scripting Node	**Warning	  File "C:\Users\BCDD\AppData\Local\Continuum\anaconda3\lib\site-packages\rdkit\__init__.py", line 2, in < module >**
11:19 AM	(49): Scripting Node	Warning	    from rdkit import Chem
11:19 AM	(49): Scripting Node	Warning	  File "D:\BCDD\Documents\Tal\CD\Scripting\cd-scripting-node-python\node\ScriptingNode1.py", line 5, in <module>
11:19 AM	(49): Scripting Node	Warning	Traceback (most recent call last):
11:19 AM	(49): Scripting Node	Info	Starting executable C:\Users\BCDD\AppData\Local\Continuum\anaconda3\python.exe with arguments D:\BCDD\Documents\Tal\CD\Scripting\cd-scripting-node-python\node\ScriptingNode1.py "C:/ProgramData/Thermo/Compound Discoverer 3.1/Scratch/Job42/Script(49)/node_args.json"

```
Your code sample here
```

I checked other discussions  :
[http://rdkit.org/docs/Install.html#cross-platform-under-anaconda-python-fastest-install](url)
[https://github.com/rdkit/rdkit/issues/1634](url)

**Comment by greglandrum** [comment]
@TalWac please try googling for "rdkit pycharm" and trying out the solutions you find there.
If those don't work, you can provide more information and reopen this issue.
