### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Mirrty** [rdkit/rdkit#3501]
**Configuration:**

- RDKit Version: 2017.09.1
- Operating system: Linux sop4070 4.18.0-193.19.1.el8_2.x86_64
- Python version (if relevant): Python 3.6.12 :: Anaconda, Inc
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda create -c rdkit -n rdkit-env rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**

I am currently  having a memory issues in a task of comparing fingerprints in rdkit. I don't know where the problem comes from, multiprocessing, rdkit or code/system, so I am writing here first. 
Relatively small dataset (100000) crashes the system due to memory overload. More than 10G is consuming while the process, though neither of the dictionaries weighs much. After %reset in python terminal, the memory is still busy. It frees only after shutting down the console.      

```
with open ('Data.pkl', 'rb') as f:
    datasmi=pickle.load(f)

manager=multiprocessing.Manager()
filtered_pharm=manager.dict()


def fpP (smi,fpP_lig, lig_smi):
    try:
        m=Chem.AddHs(Chem.MolFromSmiles(smi))
        AllChem.EmbedMolecule(m)
        fp_data=Generate.Gen2DFingerprint(m,Gobbi_Pharm2D.factory,\
                                        dMat=Chem.Get3DDistanceMatrix(m))
        value=DataStructs.DiceSimilarity(fpP_lig, fp_data)
        if value >= 0.7 :
            if smi not in filtered_pharm.keys():
                filtered_pharm[smi]={lig_smi:value}
            filtered_pharm[smi].update({lig_smi:value}) 
    except:
        pass


pool=multiprocessing.Pool()

for i in list(filter(lambda x: 'sdf' in x, os.listdir())):  # 10 sdf files, one molecule in each
    lig=Chem.SDMolSupplier(i)[0]
    lig_smi=Chem.MolToSmiles(lig)
    lig=Chem.AddHs(lig)
    AllChem.EmbedMolecule(lig)
    fpP_lig=Generate.Gen2DFingerprint(lig,Gobbi_Pharm2D.factory,\
                                      dMat=Chem.Get3DDistanceMatrix(lig))
    
    pool.map(partial(fpP,fpP_lig=fpP_lig,lig_smi=lig_smi), [smi for smi in datasmi])


```

**Comment by ricrogz** [comment]
I'm running some memory checking over the weekend, and found some problems in the resonance mol supplier. I'm not sure if that is used under the hood in your code, but if it is, it might be an explanation to the issue.

**Comment by ricrogz** [comment]
> * RDKit Version: 2017.09.1

I am sorry, I just noticed you are not using a recent version of the RDKit. Older versions of RDKit may include a certain number of memory leaks, most of which were fixed in October 2018. I would recommend you to try to update to a more recent version.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
