### ISSUE TITLE
Add mapped hydrogens

### ISSUE THREAD

**Issue by amintavakol** [rdkit/rdkit#3509]
- RDKit Version: 2018.09.3
- Operating system: linux
- Python version (if relevant): 3.7.3
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? 
- If you are not using conda: how did you install the RDKit?

I'm trying to process a molecule with a few labeled hydrogens (e.g. [H:20][CH:21](C)CCCCC.[Cl:10]).
After using `MolFromSmiles()`, I'm losing the hydrogen with label 20. Adding it back using `AddHs()` leads to a non labeled hydrogens. Is there any way to preserve the labels of hydrogens? 

For example, the code below does not print anything as it does not see the label of the added hydrogen atom.
```
mol1 = Chem.MolFromSmiles("[H:20][CH:21](C)CCCCC.[Cl:10]")
mol2 = Chem.AddHs(mol1)
for atom in mol2.GetAtoms():
    if atom.GetAtomMapNum()==20:
        print(atom.GetIdx())
```

**Comment by greglandrum** [comment]
@amintavakol :  you need to tell the RDKit not to remove Hs when you read the molecule in:
```
ps = Chem.SmilesParserParams()
ps.removeHs = False
mol1 = Chem.MolFromSmiles("[H:20][CH:21](C)CCCCC.[Cl:10]",ps)
for atom in mol1.GetAtoms():
    if atom.GetAtomMapNum()==20:
        print(atom.GetIdx())
```
If you have additional, unmapped, Hs in the molecule that you do want to remove, you can remove the Hs in a second step:
```
rhps = Chem.RemoveHsParameters()
rhps.removeMapped=False
ps = Chem.SmilesParserParams()
ps.sanitize=False    #<- skip sanitization because it will be done when we call RemoveHs()
ps.removeHs = False
mol1 = Chem.MolFromSmiles("[H:20][CH:21](C)CCCCC[H].[Cl:10]",ps)
mol2 = Chem.RemoveHs(mol1,rhps)
```
