### ISSUE TITLE
update to release 2020.09.1.0 may fail

### ISSUE THREAD

**Issue by nbehrnd** [rdkit/rdkit#3515]
**Configuration:**
Previously using RDKit 2020.03.6 successfully in Linux Debian 10 / branch unstable, installed in the Miniconda environment by `conda install -c conda-forge rdkit`, I tried to update to the about a day-old release 2020.09.1.0 which did not work.  (But I was able to get release 2020.03.6 working again.)

**Description:**

I deinstalled the elder RDKit 2020.03.6 by `conda remove rdkit` successfully.  Then, following the instruction on [Anaconda Cloud](https://anaconda.org/rdkit/rdkit), I issued the instruction `conda install -c rdkit rdkit` which triggered the installation, however the process stopped because of a current discrepancy between the version of the Python interpreter available within the conda environment, and the parameters expected by the newer RDKit.  As later checked, indeed the conda environment provides Python 3.8.3.  To quote the log completely:

```
(base) norwid@carnot2:~/Desktop$ conda install -c rdkit rdkit
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - rdkit -> python[version='2.6.*|2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.



(base) norwid@carnot2:~/Desktop$ python
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rdkit'
>>> exit()
(base) norwid@carnot2:
```

**Comment by greglandrum** [comment]
This is happening because you're grabbing the RDKit package from the rdkit channel and I'm not yet doing python 3.8 builds.
For python 3.8, you need the conda-forge RDKit builds, and those haven't yet been updated for the 2020.09.1 release.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
