### ISSUE TITLE
PostgreSQL cartridge build error with PostgreSQL 13

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#3521]
**Configuration:**

- RDKit Version: 2020.09.1
- Operating system: Linux
- PostgreSQL version: 13.0

**Description:**

The build fails for the cartridge with the error below:

```
/opt/RDKit-build/rdkit/Code/PgSQL/rdkit/low_gist.c:36:10: fatal error: access/tuptoaster.h: No such file or directory
 #include <access/tuptoaster.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This header file is no longer available in postgres 13. It looks like the include directive could be simply removed, or maybe replaced with the inclusion of `<access/detoast.h>`.

**Comment by rvianello** [comment]
I might be able to finalize some tests and send a small patch during this weekend, if nobody else is planning to work on this.

**Comment by greglandrum** [comment]
@rvianello : it's all yours. Thanks. :-)
