### ISSUE TITLE
New Fingerprints Recommendation

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#3526]
**Configuration:**

- RDKit Version: 2020.03.2
- Operating system: Windows 10 Professional
- Python version (if relevant): Python 3.7.9

**Description:**
I have just found out there are some new fingerprints, but I am wondering if they are being added to RDKit yet? which is Min-Hashed Atom-Pair Fingerprint (MAP4) and Min-Hashed Fingerprint, up to six bonds (MHFP6) or up to four bonds (MHFP4) or MACCS-322bit, PubChem Fingerprint. **Is all of that can be in bit-type?**
Source: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-00445-4
Source: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-018-0321-8
At this current time, although we have 17 fingerprints yet but I have just found 11 bit-type fingerprints on RDKit which is Morgan (useFeatures=False) (ECFP4 or ECFP6), Morgan (useFeatures=True) (FCFP4 or FCFP6), RDKit, Layered RDKit, Atom-Pair, Topological Torsion, Pattern, MACCS Keys, Avalon. Will it be added to RDKit in later update?

**Comment by adalke** [comment]
The release notes for 2020.03.1 include  "A few new descriptor/fingerprint types are available - BCUTs (#2957), Morse atom fingerprints (#1773), Coulomb matrices (#2993), and MHFP and SECFP fingerprints (#2643)" ; https://github.com/rdkit/rdkit/blob/master/ReleaseNotes.md .

Of those, I think only SECFP fingerprints are bit fingerprints. The notes I have say it works something like:
```
from rdkit.Chem import rdMHFPFingerprint
secfp_encoder = rdMHFPFingerprint.MHFPEncoder(0, 0)
fp = secfp_encoder.EncodeSECFPMol(mol, radius, rings, isomeric, kekulize, min_radius, fpSize)
```

I don't know about MACCS-322bit. "Reoptimization of MDL Keys for Use in Drug Discovery" , http://dx.doi.org/10.1021/ci010132r , mentions "both 166 bit and 960 bit keysets based on 2D descriptors" and describes an optimized version for similarity with 548 bits. I see that 322 is twice 166 but don't know the connection.

**Comment by IchiruTake** [comment]
> The release notes for 2020.03.1 include "A few new descriptor/fingerprint types are available - BCUTs (#2957), Morse atom fingerprints (#1773), Coulomb matrices (#2993), and MHFP and SECFP fingerprints (#2643)" ; https://github.com/rdkit/rdkit/blob/master/ReleaseNotes.md .
> 
> Of those, I think only SECFP fingerprints are bit fingerprints. The notes I have say it works something like:
> 
> ```
> from rdkit.Chem import rdMHFPFingerprint
> secfp_encoder = rdMHFPFingerprint.MHFPEncoder(0, 0)
> fp = secfp_encoder.EncodeSECFPMol(mol, radius, rings, isomeric, kekulize, min_radius, fpSize)
> ```
> 
> I don't know about MACCS-322bit. "Reoptimization of MDL Keys for Use in Drug Discovery" , http://dx.doi.org/10.1021/ci010132r , mentions "both 166 bit and 960 bit keysets based on 2D descriptors" and describes an optimized version for similarity with 548 bits. I see that 322 is twice 166 but don't know the connection.

In cases of MACCS 322 bits, I have found it here http://www.mayachemtools.org/docs/scripts/html/MACCSKeysFingerprints.html
I have just tried BCUT 2D as your code mentioned as well as MHFP - SECFP , but at this time, I am still struggling about the code that is there any array representations or string representations about these three fingerprints in Python. Some function in C++ is not been passed into Python when I check the source code of the author (MHFP-SECFP). In case of BCUT, I don't know what to do next, when it just gives me and _vectdouble without no function to represent it
http://rdkit.org/docs/cppapi/classRDKit_1_1MHFPFingerprints_1_1MHFPEncoder.html#ac45cdeb7eab075d43c84bb9dbecfffbd

**Comment by adalke** [comment]
It's unlikely that RDKit will include the MayaChem MACCS 322 bits implementation. It cites the same "Reoptimization of MDL Keys" paper I mentioned before, but I don't see anything related to 322 in that paper. I could try to figure it out more, but someone is going to need to test it and show that it outperforms the other fingerprint types already in RDKit. There are only a handful of publications that Google Scholar could find which use the 322 bit implementation, and nearly all were from one research group who simply used all of MayaChem's fingerprint implementations, and did not remark that they weren't using the by-far most common 166 bit version.

MHFP does not have a standard fingerprint representation.

The `_vectd` means the BCUT is a vector of doubles. This can be turned into a Python list like:
```
>>> list(BCUT)
[-9.569191070688725e-16, -0.24844104338801754, -0.1798488674638132, -2.5611396749690116, -0.03425012966629479, -2.6847019107610306, -2.2462701462792987e-16, -1.1084942735259444]
```

**Comment by fwmeng88** [comment]
> from rdkit.Chem import rdMHFPFingerprint
> secfp_encoder = rdMHFPFingerprint.MHFPEncoder(0, 0)
> fp = secfp_encoder.EncodeSECFPMol(mol, radius, rings, isomeric, kekulize, min_radius, fpSize)

Can you explain what do the two zeros mean in the following block? 
```python
secfp_encoder = rdMHFPFingerprint.MHFPEncoder(0, 0)
```

I looked at the documentation, https://www.rdkit.org/docs/source/rdkit.Chem.rdMHFPFingerprint.html. But I don't know much about C++ and didn't figure it out. 

Thank you very much for your time! 
@adalke @IchiruTake

**Comment by fwmeng88** [comment]
> > from rdkit.Chem import rdMHFPFingerprint
> > secfp_encoder = rdMHFPFingerprint.MHFPEncoder(0, 0)
> > fp = secfp_encoder.EncodeSECFPMol(mol, radius, rings, isomeric, kekulize, min_radius, fpSize)
> 
> Can you explain what do the two zeros mean in the following block?
> 
> ```python
> secfp_encoder = rdMHFPFingerprint.MHFPEncoder(0, 0)
> ```
> 
> I looked at the documentation, https://www.rdkit.org/docs/source/rdkit.Chem.rdMHFPFingerprint.html. But I don't know much about C++ and didn't figure it out.
> 
> Thank you very much for your time!
> @adalke @IchiruTake

I got it. Never mind. Thanks! 
https://github.com/reymond-group/mhfp

        # n_permutations: analogous to the number of bits ECFP fingerprints are folded into. Higher is better, lower is less exact.
        # seed: seed for the MinHash operation. Has to be the same for comparable fingerprints.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
