### ISSUE TITLE
Newest RDKIT version allowing chemically invalid smiles

### ISSUE THREAD

**Issue by GintasKam** [rdkit/rdkit#3531]
The version 2020.09.1 considers many invalid molecules to be valid, wheres older versions don't. For a particular example,
running 

    from rdkit import Chem
    s = 'CCOOOOSOSCCl=C=O'
    Chem.MolToSmiles(Chem.MolFromSmiles(s))

throws an error on the 2020.03.3 version (correctly), but returns the original smile on the 2020.09.1 version.

**Comment by greglandrum** [comment]
Agreed that this shouldn't be accepted, it'a an unintended consequence of #3486 and will be fixed.
