### ISSUE TITLE
[New Features] Instruction

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#3532]
I have just found a new type of fingerprint: doi.org/10.1186/s13321-020-00445-4
Will RDKit add to it? MinHashed

P/s: I can not find the function for MHFP and SECFP in RDKit, can you help me

**Comment by greglandrum** [comment]
I have no immediate plans to implement that fingerprint, but we are of course happy to look through the PR if someone submits an implementation.

There's an example of using MHFP and SECFP here: https://nbviewer.jupyter.org/github/rdkit/UGM_2020/blob/master/Notebooks/Landrum_WhatsNew.ipynb#MHFP-and-SECFP-fingerprints

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
