### ISSUE TITLE
 Bug in the calculation of the getaway descriptor

### ISSUE THREAD

**Issue by milanimarcel** [rdkit/rdkit#3534]
**Configuration:**

- RDKit Version: 2020.09.1
- Operating system: Windows/Linux
- Python version (if relevant): 3.9
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? conda create -c rdkit -n my-rdkit-env rdkit
- If you are not using conda: how did you install the RDKit?

**Description:**
When I use GETAWAY descriptor for calculating SMILES containing "dots", the program stops working.
The program only stops with these types of smiles, that in terms of chemistry the dots says that the molecule have their
acid/basic pair conjugated.

If the SMILES don´t containing dots the program truly works.

below I show the code that i used.

```
from rdkit.Chem import rdMolDescriptors as rdMD
from rdkit.Chem import  AllChem
from rdkit import Chem


m=Chem.MolFromSmiles('Cl.CN(c1ccc(NC(=O)Nc2cccc(c2)C(=O)N2CCN(C)CC2)cc1)c1ccnc(Nc2ccc(CS(C)(=O)=O)cc2)n1')
m

m2 = Chem.AddHs(m)
AllChem.EmbedMolecule(m2)

rdMD.CalcGETAWAY(m2, precision=0.001)

```

**Comment by thegodone** [comment]
It’s not a bug it’s a 3D descriptor for pire molecule without salt or mixture. You need to compute it for each of your components 

Envoyé de mon iPhone
