### ISSUE TITLE
New way: Will RDKit will support the use of GPU (NVIDIA) or TPU?

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#3537]
I am considering about will RDKit will support the use of GPU in the future, either being partly/all integrated into the RDKit or create a new package of RDKit but support GPU? Th

**Comment by greglandrum** [comment]
There are parts of the RDKit where it might make sense to offer GPU support (for example the conformer generation) but we have no immediate plans to do a GPU implementation.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
