### ISSUE TITLE
Behaviour of generate_aligned_coords for erroneous inputs

### ISSUE THREAD

**Issue by dskatov** [rdkit/rdkit#3539]
**Configuration:**

WASM version of RDKit as of Nov 1 2020 from: https://rdkit.org/rdkitjs/beta/GettingStartedInJS.html
Chrome Version 86.0.4240.111 (Official Build) (64-bit)
Microsoft Windows [Version 10.0.18363.1139]

**Description:**

Inconsistent behaviour with `generate_aligned_coords` function is encountered for erroneous inputs.

This isn't something provided in the docs or manual, yet it is logical to assume this function should only work if a MolBlock is provided for the molecule to which we align, s.t. we have coordinate data for alignment. However, if one tries this function to align some molecule against a smile-based molecule, the behaviour of this function varies.

Most of the runs against a smile-based molecule make the function crash with `Uncaught [7 digits number]`, e.g. `Uncaught 6091840`. May it be reasonable to offer a better way of informing on a problem if a non-MolBlock based molecule is provided for alignment? There is a string returned by `generate_aligned_coords`, yet it appears it is always empty, according to `minilib.cpp`. It could be, for instance, a bool indicating success or failure.

```
var smiles = "CC(C(=O)OCCCc1cccnc1)c2cccc(c2)C(=O)c3ccccc3";
var mol = Module.get_mol(smiles);
var template = `CC`;
var qmol = Module.get_mol(template);
mol.generate_aligned_coords(qmol,true);
var tdetails = mol.get_substruct_match(qmol);
var canvas = document.getElementById("draw-canvas-6");
mol.draw_to_canvas_with_highlights(canvas,tdetails);
```

However, for _some_ inputs the function doesn't crash, and it seems like in some cases it even aligns (I guess it chooses the default alignment of CoordGen):

```
var smiles = "c1cnc(C)nc1C(=O)O";
var mol = Module.get_mol(smiles);
var template = "C1CCC1";
var qmol = Module.get_mol(template);
mol.generate_aligned_coords(qmol, true);
var tdetails = mol.get_substruct_match(qmol);
var canvas = document.getElementById("draw-canvas-6");
mol.draw_to_canvas_with_highlights(canvas,tdetails);
```

**Comment by ptosco** [comment]
@dskatov Thanks for reporting this. I'll look into this.
