### ISSUE TITLE
Drawing artifacts in draw_to_canvas_with_offset

### ISSUE THREAD

**Issue by dskatov** [rdkit/rdkit#3540]
**Configuration:**

WASM version of RDKit as of Nov 1 2020 from: https://rdkit.org/rdkitjs/beta/GettingStartedInJS.html (v2020.09)
Chrome Version 86.0.4240.111 (Official Build) (64-bit)
Microsoft Windows [Version 10.0.18363.1139]

**Description:**

`draw_to_canvas_with_offset` brings a drawing artifact in the top-left canvas corner.

This is what we have prior to drawing the molecule to the canvas:

```
var canvas = document.getElementById("draw-canvas-2");
var ctx = canvas.getContext("2d");
ctx.fillStyle = "#00FF00";
ctx.fillRect(0,0,300,300);
```
![image](https://user-images.githubusercontent.com/67762377/97815924-adbc2380-1ca2-11eb-930f-5c37f41ee703.png)

Here is what happens if we add a molecule drawing to the canvas:

```
var smiles = "CC(=O)Oc1ccccc1C(=O)O";
var mol = Module.get_mol(smiles);
var canvas = document.getElementById("draw-canvas-2");
var ctx = canvas.getContext("2d");
ctx.fillStyle = "#00FF00";
ctx.fillRect(0,0,300,300);
mol.draw_to_canvas_with_offset(canvas, 100, -100, 150, 100);
```
![image](https://user-images.githubusercontent.com/67762377/97815917-9b41ea00-1ca2-11eb-9a09-10ebacb99062.png)

There is a clear artifact rectangle in the top-left, which is sized same as the molecule render.

**Comment by ptosco** [comment]
Having looked at the source code, this is not a bug. By default the canvas background is cleared prior to drawing a molecule, and by default the background color is white.
Your problem can be solved either setting `clearBackground` to `false`, or by setting the `backgroundColor` to the same RGB color used in `fillRect()`:

```
        var canvas = document.getElementById("rdkit-canvas");
        var ctx = canvas.getContext("2d");
        ctx.fillStyle = "#00FF00";
        ctx.fillRect(0, 0, 400, 300);
        var smiles = "CC(=O)Oc1ccccc1C(=O)O";
        var mol = Module.get_mol(smiles);
        var opts = {
            "clearBackground": false,
            // alternatively, this will clear the background
            // using the RGB color 0.0, 1.0, 0.0
            // "backgroundColour": [0.0, 1.0, 0.0],
            "offsetx": 100,
            "offsety": -100,
            "width": 250,
            "height": 100
        }
        mol.draw_to_canvas_with_highlights(canvas, JSON.stringify(opts));
```

You may see the full list of C++ `drawOptions` that can be set by passing an appropriate JSON string here:
https://github.com/rdkit/rdkit/blob/874fd5c1bddced7be257d470769b1b46c3b76e92/Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp#L120

Additionally, the JS bindings allow setting a few more parameters such as width, height, offsets and highlights:
https://github.com/rdkit/rdkit/blob/874fd5c1bddced7be257d470769b1b46c3b76e92/Code/MinimalLib/minilib.cpp#L43

So this also covers https://github.com/rdkit/rdkit/issues/3541, as you may add the offsets in the JSON string as shown above together with atom and bond highlights.

Could you please check if the above works for you and, if so, close the bug? Thanks.

**Comment by dskatov** [comment]
Thanks @ptosco, the provided options work well!
