### ISSUE TITLE
draw_to_canvas_with_highlights_and_offset in JS MinimalLib

### ISSUE THREAD

**Issue by dskatov** [rdkit/rdkit#3541]
**Configuration:**

WASM version of RDKit as of Nov 1 2020 from: https://rdkit.org/rdkitjs/beta/GettingStartedInJS.html (v2020.09)
Chrome Version 86.0.4240.111 (Official Build) (64-bit)
Microsoft Windows [Version 10.0.18363.1139]

**Description:**

There are currently `draw_to_canvas_with_highlights` and `draw_to_canvas_with_offset` functions exposed to the JS API, which are really useful. Yet there is also a practical need of drawing molecules with substructures highlights and an offset. We'd like to have such functionality in the public JS API.

**Comment by ptosco** [comment]
You can use `draw_to_canvas_with_highlights` passing

```
"offsetx": 100,
"offsety": -100,
```

as key, value pairs in the JSON string in addition to `atom` and `bond` IDs.
(More detailed explanation here: https://github.com/rdkit/rdkit/issues/3540)

Could you please check if the above works for you and, if so, close the bug? Thanks.

**Comment by dskatov** [comment]
Indeed @ptosco, the approach works, thank you for the provided info!
