### ISSUE TITLE
Error adding PNG metadata when kekulize=False

### ISSUE THREAD

**Issue by gayverjr** [rdkit/rdkit#3543]
**Configuration:**

- RDKit Version (current): 2020.09.1.0
- RDKit Version (older): 2019.09.2
- Operating system: MacOS 10.13
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? conda-forge

**Description:**
I've been using RDKit for about 2 years to render chemical structures of aromatic moieties I find in protein crystal structures; for example adenine in FAD cofactor. Our algorithm for generating the SMARTS strings is pretty simple and just assumes everything is aromatic. In older versions of RDKit we got away with this, but this year we've started to run into issues with kekulization when drawing. For instance the snippet:

```
from rdkit import Chem
from rdkit.Chem import Draw
mol = Chem.MolFromSmarts("n1cnc2c(n)ncnc12")
mol.UpdatePropertyCache()
img = Draw.MolToFile(mol, "adenine.png", kekulize=False)
```

in RDKit version 2019.09.2 resulted in this image:

![fad_adenine](https://user-images.githubusercontent.com/29463611/97928442-0f2cd280-1d35-11eb-8d69-769502e0ecdc.png)

which we were quite satisfied with. But now in 2020.09.1.0 we get:

```
rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 6 7 8 9
```

Does kekulize=False no longer work, or is RDKit just stricter with what it deems chemically acceptable in newer versions? Are there any suggested workarounds, or do we just need to rework our algorithm in order to give RDKit better SMARTS strings?

Thank you!

**Comment by greglandrum** [comment]
Hi @gayverjr : The behavior changes you're seeing were not intentional. This is a bug.

**Comment by gayverjr** [comment]
So I've updated to the latest version on conda-forge (2021.03.3), and it works now for .png, but not for .svg.

I've tried the following snippets:

```
from rdkit import Chem
from rdkit.Chem import Draw
mol = Chem.MolFromSmarts("n1cnc2c(n)ncnc12")
img = Draw.MolToFile(mol, "adenine.svg", kekulize=False)
```
and 
```
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem import rdDepictor
mol = Chem.MolFromSmarts("n1cnc2c(n)ncnc12")
d2d = rdMolDraw2D.MolDraw2DSVG(350,300)
d2d.DrawMolecule(mol)
d2d.FinishDrawing()
```

both which yield the following exception:
```
rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4 6 7 8 9
```

Are neither of these the preferred way of rendering SVGs? If not, is there some better way?
