### ISSUE TITLE
Issues in the calculation of NumHAcceptors descriptor

### ISSUE THREAD

**Issue by caiyingchun** [rdkit/rdkit#3544]
When using ```rdMolDescriptors.CalcNumHBA(mol)``` to calculate NumHAcceptors for molecule ```c1nccs1```, I got  number 2. That means both atom N and S as acceptors of h-bond. I’m curious about the result. Why atom S can be  acceptors of h-bond?
```
from rdkit.Chem import rdMolDescriptors
smi = 'c1nccs1'
mol = Chem.MolFromSmiles(smi)
print(rdMolDescriptors.CalcNumHBA(mol))
```

**Comment by bp-kelley** [comment]
There are actually two HBA's in the descriptors, CalcNumHBA and CalcLipinskiHBA

Here is the CalcNumHBA definition
```
SMARTSCOUNTFUNC(NumHBA,
                "[$([O,S;H1;v2]-[!$(*=[O,N,P,S])]),$([O,S;H0;v2]),$([O,S;-]),$("
                "[N;v3;!$(N-*=!@[O,N,P,S])]),$([nH0,o,s;+0])]",
                "2.0.1");
```

This does indeed include S (and P).  S is a weak hydrogen bond acceptors in some cases, but I think there is some debate about it in general.

**Comment by caiyingchun** [comment]
Thanks a lot. Got it.
