### ISSUE TITLE
[Bug or If-else] Fragment On Bonds

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#3548]
RDKit version: 2020.09.1 - Python 3.7.9
I have this SMILES: CNC(=O)C1CCC1 and when I break all bond, everything sense to be normal (with liitle bit tricky in SMILES <-> Molecule Conversion).
I still get this radical '[HH]' instead of '[H]'. How I can fix it? Do I need to request this as a bug or just making if else to reconvert back?

```
        Temp = []
        print('SMILES #{}: {}'.format(i, SMILES_Input[i]))
        Molecule = Chem.AddHs(Chem.MolFromSmiles(SMILES_Input[i]))
        for bond in Molecule.GetBonds():
            SwapBond = [str(bond.GetBeginAtom().GetSymbol()), str(bond.GetEndAtom().GetSymbol())]
            SwapBond.sort()
            TestMol = Chem.FragmentOnBonds(Molecule, bondIndices=[bond.GetIdx()], addDummies=False)
            try:
                RadicalA, RadicalB = Chem.GetMolFrags(TestMol, asMols=True)
                RadicalA = str(Chem.MolToSmiles(Chem.MolFromSmiles(Chem.MolToSmiles(RadicalA))))
                RadicalB = str(Chem.MolToSmiles(Chem.MolFromSmiles(Chem.MolToSmiles(RadicalB))))
                Temp.append([SMILES_Input[i], RadicalA, RadicalB, SwapBond[0] + '-' + SwapBond[1]])
            except ValueError or TypeError:
                pass
        print(Temp)
```
This is what I get
```
['CNC(=O)C1CCC1' '[CH3]' '[NH]C(=O)C1CCC1' 'C-N']
 ['CNC(=O)C1CCC1' 'C[NH]' 'O=[C]C1CCC1' 'C-N']
 ['CNC(=O)C1CCC1' 'CN[C]C1CCC1' '[O]' 'C-O']
 ['CNC(=O)C1CCC1' 'CN[C]=O' '[CH]1CCC1' 'C-C']
 ['CNC(=O)C1CCC1' '[CH2]NC(=O)C1CCC1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' '[CH2]NC(=O)C1CCC1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' '[CH2]NC(=O)C1CCC1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' 'C[N]C(=O)C1CCC1' '[HH]' 'H-N']
 ['CNC(=O)C1CCC1' 'CNC(=O)[C]1CCC1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' 'CNC(=O)C1[CH]CC1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' 'CNC(=O)C1[CH]CC1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' 'CNC(=O)C1C[CH]C1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' 'CNC(=O)C1C[CH]C1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' 'CNC(=O)C1[CH]CC1' '[HH]' 'C-H']
 ['CNC(=O)C1CCC1' 'CNC(=O)C1[CH]CC1' '[HH]' 'C-H']
```

**Comment by greglandrum** [comment]
Hi. `[HH]` is not an H radical. It's an H atom with one implicit H, i.e it corresponds to H2.
`[H]` is a radical

**Comment by bp-kelley** [comment]
I think the issue you are seeing here is that you are splitting a proton away but it has a valence of 1, this is being converted into a hydrogen count of 1.  If you add "addDummies=True" to your fragments I think you might end up with a result closer to what you want but you may want to get rid of the isotope labelling for the attachment position:

['CNC(=O)C1CCC1', '[1*]C', '*NC(=O)C1CCC1', 'C-N']
['CNC(=O)C1CCC1', '[2*]NC', '[1*]C(=O)C1CCC1', 'C-N']
['CNC(=O)C1CCC1', '[3*]=C(NC)C1CCC1', '[2*]=O', 'C-O']
['CNC(=O)C1CCC1', '[4*]C(=O)NC', '[2*]C1CCC1', 'C-C']
['CNC(=O)C1CCC1', '[8*]CNC(=O)C1CCC1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '[9*]CNC(=O)C1CCC1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '[10*]CNC(=O)C1CCC1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '[11*]N(C)C(=O)C1CCC1', '[1*][H]', 'H-N']
['CNC(=O)C1CCC1', '[12*]C1(C(=O)NC)CCC1', '[4*][H]', 'C-H']
['CNC(=O)C1CCC1', '[13*]C1CCC1C(=O)NC', '[5*][H]', 'C-H']
['CNC(=O)C1CCC1', '[14*]C1CCC1C(=O)NC', '[5*][H]', 'C-H']
['CNC(=O)C1CCC1', '[15*]C1CC(C(=O)NC)C1', '[6*][H]', 'C-H']
['CNC(=O)C1CCC1', '[16*]C1CC(C(=O)NC)C1', '[6*][H]', 'C-H']
['CNC(=O)C1CCC1', '[17*]C1CCC1C(=O)NC', '[7*][H]', 'C-H']
['CNC(=O)C1CCC1', '[18*]C1CCC1C(=O)NC', '[7*][H]', 'C-H']

**Comment by IchiruTake** [comment]
> I think the issue you are seeing here is that you are splitting a proton away but it has a valence of 1, this is being converted into a hydrogen count of 1. If you add "addDummies=True" to your fragments I think you might end up with a result closer to what you want but you may want to get rid of the isotope labelling for the attachment position:
> 
> ['CNC(=O)C1CCC1', '[1*]C', '_NC(=O)C1CCC1', 'C-N'] ['CNC(=O)C1CCC1', '[2_]NC', '[1*]C(=O)C1CCC1', 'C-N']
> ['CNC(=O)C1CCC1', '[3*]=C(NC)C1CCC1', '[2*]=O', 'C-O']
> ['CNC(=O)C1CCC1', '[4*]C(=O)NC', '[2*]C1CCC1', 'C-C']
> ['CNC(=O)C1CCC1', '[8*]CNC(=O)C1CCC1', '_[H]', 'C-H'] ['CNC(=O)C1CCC1', '[9_]CNC(=O)C1CCC1', '_[H]', 'C-H'] ['CNC(=O)C1CCC1', '[10_]CNC(=O)C1CCC1', '_[H]', 'C-H'] ['CNC(=O)C1CCC1', '[11_]N(C)C(=O)C1CCC1', '[1*][H]', 'H-N']
> ['CNC(=O)C1CCC1', '[12*]C1(C(=O)NC)CCC1', '[4*][H]', 'C-H']
> ['CNC(=O)C1CCC1', '[13*]C1CCC1C(=O)NC', '[5*][H]', 'C-H']
> ['CNC(=O)C1CCC1', '[14*]C1CCC1C(=O)NC', '[5*][H]', 'C-H']
> ['CNC(=O)C1CCC1', '[15*]C1CC(C(=O)NC)C1', '[6*][H]', 'C-H']
> ['CNC(=O)C1CCC1', '[16*]C1CC(C(=O)NC)C1', '[6*][H]', 'C-H']
> ['CNC(=O)C1CCC1', '[17*]C1CCC1C(=O)NC', '[7*][H]', 'C-H']
> ['CNC(=O)C1CCC1', '[18*]C1CCC1C(=O)NC', '[7*][H]', 'C-H']

Actually I want to like eliminate the identical set of fragment by using string comparison, which I already know that string comparison is not robust as using molecule similarity. However, I still believe that string comparison is faster in Python compared to RDKit in C++ as I have to work with a databade 290k species with 30?+ Parameters.

Thank you all of you guys. You guys are doing great. Best wishes to the RDKit Developer Team

**Comment by IchiruTake** [comment]
> > I think the issue you are seeing here is that you are splitting a proton away but it has a valence of 1, this is being converted into a hydrogen count of 1. If you add "addDummies=True" to your fragments I think you might end up with a result closer to what you want but you may want to get rid of the isotope labelling for the attachment position:
> > ['CNC(=O)C1CCC1', '[1*]C', '_NC(=O)C1CCC1', 'C-N'] ['CNC(=O)C1CCC1', '[2_]NC', '[1*]C(=O)C1CCC1', 'C-N']
> > ['CNC(=O)C1CCC1', '[3*]=C(NC)C1CCC1', '[2*]=O', 'C-O']
> > ['CNC(=O)C1CCC1', '[4*]C(=O)NC', '[2*]C1CCC1', 'C-C']
> > ['CNC(=O)C1CCC1', '[8*]CNC(=O)C1CCC1', '_[H]', 'C-H'] ['CNC(=O)C1CCC1', '[9_]CNC(=O)C1CCC1', '_[H]', 'C-H'] ['CNC(=O)C1CCC1', '[10_]CNC(=O)C1CCC1', '_[H]', 'C-H'] ['CNC(=O)C1CCC1', '[11_]N(C)C(=O)C1CCC1', '[1*][H]', 'H-N']
> > ['CNC(=O)C1CCC1', '[12*]C1(C(=O)NC)CCC1', '[4*][H]', 'C-H']
> > ['CNC(=O)C1CCC1', '[13*]C1CCC1C(=O)NC', '[5*][H]', 'C-H']
> > ['CNC(=O)C1CCC1', '[14*]C1CCC1C(=O)NC', '[5*][H]', 'C-H']
> > ['CNC(=O)C1CCC1', '[15*]C1CC(C(=O)NC)C1', '[6*][H]', 'C-H']
> > ['CNC(=O)C1CCC1', '[16*]C1CC(C(=O)NC)C1', '[6*][H]', 'C-H']
> > ['CNC(=O)C1CCC1', '[17*]C1CCC1C(=O)NC', '[7*][H]', 'C-H']
> > ['CNC(=O)C1CCC1', '[18*]C1CCC1C(=O)NC', '[7*][H]', 'C-H']
> 
> Actually I want to like eliminate the identical set of fragment by using string comparison, which I already know that string comparison is not robust as using molecule similarity. However, I still believe that string comparison is faster in Python compared to RDKit in C++ as I have to work with a databade 290k species with 30?+ Parameters.
> 
> Thank you all of you guys. You guys are doing great. Best wishes to the RDKit Developer Team

**Comment by bp-kelley** [comment]
This might work for you
```
from rdkit import Chem

Temp = []
i = 0
SMILES_Input = ['CNC(=O)C1CCC1']

def RemoveDummyIsotopes(m):
    for atom in m.GetAtoms():
        if atom.GetAtomicNum() == 0:
            atom.SetIsotope(0)
    return m
print('SMILES #{}: {}'.format(i, SMILES_Input[i]))
Molecule = Chem.AddHs(Chem.MolFromSmiles(SMILES_Input[i]))
print(Chem.MolToSmiles(Molecule))
for bond in Molecule.GetBonds():
    SwapBond = [str(bond.GetBeginAtom().GetSymbol()), str(bond.GetEndAtom().GetSymbol())]
    SwapBond.sort()
    TestMol = Chem.FragmentOnBonds(Molecule, bondIndices=[bond.GetIdx()], addDummies=True)
    try:
        RadicalA, RadicalB = [RemoveDummyIsotopes(x) for x in Chem.GetMolFrags(TestMol, asMols=True)]
        #print(RadicalB.GetNumAtoms())
        RadicalA = str(Chem.MolToSmiles(Chem.MolFromSmiles(Chem.MolToSmiles(RadicalA))))
        RadicalB = str(Chem.MolToSmiles(Chem.MolFromSmiles(Chem.MolToSmiles(RadicalB))))
        Temp.append([SMILES_Input[i], RadicalA, RadicalB, SwapBond[0] + '-' + SwapBond[1]])
    except ValueError or TypeError:
        pass

for r in Temp:
    print(r)
```

```
['CNC(=O)C1CCC1', '*C', '*NC(=O)C1CCC1', 'C-N']
['CNC(=O)C1CCC1', '*NC', '*C(=O)C1CCC1', 'C-N']
['CNC(=O)C1CCC1', '*=C(NC)C1CCC1', '*=O', 'C-O']
['CNC(=O)C1CCC1', '*C(=O)NC', '*C1CCC1', 'C-C']
['CNC(=O)C1CCC1', '*CNC(=O)C1CCC1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*CNC(=O)C1CCC1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*CNC(=O)C1CCC1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*N(C)C(=O)C1CCC1', '*[H]', 'H-N']
['CNC(=O)C1CCC1', '*C1(C(=O)NC)CCC1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*C1CCC1C(=O)NC', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*C1CCC1C(=O)NC', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*C1CC(C(=O)NC)C1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*C1CC(C(=O)NC)C1', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*C1CCC1C(=O)NC', '*[H]', 'C-H']
['CNC(=O)C1CCC1', '*C1CCC1C(=O)NC', '*[H]', 'C-H']
```

**Comment by bp-kelley** [comment]
All I'm doing is removing the isotope label from the dummy atoms added in FragmentOnBonds
