### ISSUE TITLE
[Question] Installing The latest version of RDKit on Ubuntu 20.04.01

### ISSUE THREAD

**Issue by pykao** [rdkit/rdkit#3549]
**Configuration:**

 '2019.09.1'
- RDKit Version: 2019.09.1
- Operating system: Ubuntu 20.04.1
- Python version (if relevant): 3.8.5
- Are you using conda? No
- If you are not using conda: how did you install the RDKit?
`sudo apt-get install python3-rdkit librdkit1 rdkit-data`

**Description:**

Hello,

I am trying to update my RDKit to the latest version which is 2020.09.1. But the latest version I am able to get using apt-get is 2019.09.1 at this time. When will you plan to release the latest version of RDKit on apt-get?

Best,
Ken

**Comment by greglandrum** [comment]
Hi, that's work done by the debichem community: https://debichem-team.pages.debian.net/
It's probably best to check with them.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
