### ISSUE TITLE
Bond Properties

### ISSUE THREAD

**Issue by swamidass** [rdkit/rdkit#3556]
It is great to see that RDKit supports Atom properties like this:

m = Chem.MolFromSmiles('OC')
m.GetAtomWithIdx(1).SetProp('p1','5')
m.GetAtomWithIdx(0).SetProp('atomLabel','O1')
m.GetAtomWithIdx(1).SetProp('atomLabel','C2')
m.GetAtomWithIdx(0).SetProp('p1','3')
Chem.MolToCXSmiles(m)

Is there any way to support Bond properties too? If not, are there plans to do so? Is this supported yet in the CXSmiles or would it have to be a new extension?

**Comment by greglandrum** [comment]
The RDKit Bond objects do support properties, but the CXSMILES format does not support them, so they do not show up in the output CXSMILES. If ChemAxon were to extend their format to support bond properties, I'd be happy to support it.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by swamidass** [comment]
Thanks.
