### ISSUE TITLE
Modularized WASM module

### ISSUE THREAD

**Issue by dskatov** [rdkit/rdkit#3561]
**Description:**

Currently `RDKit_minimal.wasm` is built via Emscripten as a public `Module`. This introduces a problem with such Module object being a `var`, also having a name simply as `Module`, which is confusing especially in the case several other WASM modules are used in one web app.

In particular, we currently have to alleviate loading problems of the RDKit Module with adding a preambule to your `RDKit_minimal.js` like this: https://github.com/datagrok-ai/public/blob/2cad08711f97d03104c221efa2d63c67c5c9bfca/packages/Chem/wasm/RDKit_minimal.js#L8 .

A solution to this may be using a `MODULARIZE` option in Emscripten: https://emscripten.org/docs/getting_started/FAQ.html. Having WASM and a corresponding JS built like this, we would now be able to create the module with a proper name (`RDKitModule` or alike) via a factory function with a proper name (`rdKitInitialize` or alike).

We could certainly build the module with tweaking the docker image you provide. Though it would be more uniform and correct if we use the WASM + JS set exactly the one you ship and use, for instance, at https://rdkit.org/rdkitjs/beta/GettingStartedInJS.html.

**Comment by ptosco** [comment]
I have tested this on a branch and it seems to work fine:
https://github.com/ptosco/rdkit/tree/modularize

However, I am a bit reluctant in submitting a PR as I am not sure this is necessarily an improvement, but rather another way to deploy the library. @greglandrum What's your opinion?
You can look at what I have done here: https://github.com/rdkit/rdkit/pull/3570
