### ISSUE TITLE
Uncharger does not remove explicit hydrogens

### ISSUE THREAD

**Issue by mrcblt** [rdkit/rdkit#3562]
**Configuration:**

- RDKit Version: **2020.09.1**
- Operating system: **Linux**
- Python version (if relevant): **3.8.5**
- Are you using conda? **Yes**
- If you are using conda, which channel did you install the rdkit from? **conda-forge**

**Description:**

When uncharging a positive charged nitrogen with four explicit hydrogens attached, the Uncharger does not remove an explicit hydrogen, but only removes the positive formal charge. This then leads to an invalid molecule.

```python3
from rdkit import Chem
from rdkit.Chem.MolStandardize.rdMolStandardize import Uncharger

uc = Uncharger()

m = Chem.MolFromSmiles('[NH4+]')
m
```
![m1](https://user-images.githubusercontent.com/34354523/98682544-5550ea00-2364-11eb-915d-7380a12e64b3.png)

Works without explicit hydrogens
```python3
uc.uncharge(m)
```
![m1uc](https://user-images.githubusercontent.com/34354523/98682536-541fbd00-2364-11eb-810f-f9523a55294e.png)
---
Does not work with explicit hydrogens
```python3
m2 = Chem.MolFromSmiles('[NH4+]')
m2 = Chem.AddHs(m2)
m2
```
![m2](https://user-images.githubusercontent.com/34354523/98682539-54b85380-2364-11eb-802e-bcbf4c0ffa47.png)

```python3
uc.uncharge(m2)
```
![m2uc](https://user-images.githubusercontent.com/34354523/98682540-54b85380-2364-11eb-8d06-70054b3a1b67.png)

**Expected behavior:** Uncharger should in this case remove one explicit hydrogen.

**Comment by ptosco** [comment]
@mrcblt My experience is that the `rdMolStandardizer` requires molecules with implicit hydrogens to work properly, as it extensively uses reaction SMARTS that will only work properly with implicit Hs.
If you work with 3D molecules, it isn't too hard to remove Hs upfront, and then read them afterwards restoring the original coordinates. Does that sound reasonable to you?

**Comment by mrcblt** [comment]
Yes, this is kind of the current workaround I use. If there is no way to get it to work easily with explicit hydrogens, then I would suggest that there should at least be a warning if `Uncharger` is used with molecules containing explicit hydrogens. Or it should be stated in the documentation of the class or the `uncharge` function. I may have overlooked something, but I couldn't find any indication that `Uncharger` is not working properly in this case.
