### ISSUE TITLE
PandasTools Jupyter Rendering issue

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#3563]
Hi all,

I have read the multiple issue with the PandasTools related to the pandas version. However the threads were closed and the issue [fixed as solved](https://github.com/rdkit/rdkit/issues/2673). Still I'm seeing strange behavior as that I can only make the molecules visible by calling `PandasTools.RenderImagesInAllDataFrames(images=True)` and it then only affects new dataframes.

Without this calls, molecules are never displayed. 

```python
import pandas as pd
import rdkit
from rdkit.Chem import PandasTools
from rdkit import Chem
```

```python
pd.__version__
```

    '1.1.3'

```python
rdkit.__version__
```

    '2020.09.1'

```python
m = Chem.MolFromSmiles("c1ccccc1")
```

```python
df = pd.DataFrame(data=[[m]], columns=['Molecule'])
df
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Molecule</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>&lt;img data-content="rdkit/molecule" src="data:i...</td>
    </tr>
  </tbody>
</table>
</div>

```python
PandasTools.ChangeMoleculeRendering(df)
df
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Molecule</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>&lt;img data-content="rdkit/molecule" src="data:i...</td>
    </tr>
  </tbody>
</table>
</div>

```python
PandasTools.RenderImagesInAllDataFrames(images=True)
```

```python
df = pd.DataFrame(data=[[m]], columns=['Molecule'])
df
```

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Molecule</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td><img src="https://www.chemspider.com/ImagesHandler.ashx?id=236&w=100&h=100" alt="Mol"/></td>
    </tr>
  </tbody>
</table>
</div>

**Configuration:**

- RDKit Version: 2020.09.1
- Operating system: WIndows 10
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? rdkit

**Comment by bp-kelley** [comment]
@kienerj could you let us know the pandas version as well?

**Comment by kienerj** [comment]
Hi Brian, it's 1.1.3.

**Comment by hadim** [comment]
I can confirm this bug with pandas 1.2.2 and the latest rdkit as of today.

**Comment by maclandrol** [comment]
I think there the bug is coming from https://github.com/rdkit/rdkit/blob/0370b6cc57b279cd25a677b28f766dfe2a05021d/rdkit/Chem/PandasTools.py#L447-L449

the renderer is set to the default panda renderer, while it should be `patchPandasrepr`. 

The following works and allows switching the renderer from `"String"` to `"PNG"` anytime. 


```
import types
from rdkit.Chem import rdchem
def ChangeMoleculeRendering(frame=None, renderer='PNG'):
    '''Allows to change the rendering of the molecules between base64 PNG images and string
    representations.
    This serves two purposes: First it allows to avoid the generation of images if this is
    not desired and, secondly, it allows to enable image rendering for newly created dataframe
    that already contains molecules, without having to rerun the time-consuming
    AddMoleculeColumnToFrame. Note: this behaviour is, because some pandas methods, e.g. head()
    returns a new dataframe instance that uses the default pandas rendering (thus not drawing
    images for molecules) instead of the monkey-patched one.
    '''
    if renderer == 'String':
        rdchem.Mol.__str__ = PandasTools.PrintDefaultMolRep
    else:
        rdchem.Mol.__str__ = PandasTools.PrintAsBase64PNGString
    if frame is not None:
        frame.to_html = types.MethodType(PandasTools.patchPandasHTMLrepr, frame)
    
    if PandasTools.defPandasRepr is not None and renderer == "String":
        frame._repr_html_ = types.MethodType(PandasTools.defPandasRepr, frame)
    else:
        frame._repr_html_ = types.MethodType(PandasTools.patchPandasrepr, frame)
        
```

**Comment by hadim** [comment]
I confirm @maclandrol fix works.

That being said as soon as you create a new dataframe from the patched one, the patch is lost (for example `df.head()` won't show the mol column as images).

I know this is a known issue and I don't think there is much to do about it except for using `RenderImagesInAllDataFrames`.

**Comment by drassokhin** [comment]
It looks like even the `PandasTools.RenderImagesInAllDataFrames(images=True)` method does not work with pandas 1.5.0
and RDKit 2022.03.5.

```
import pandas as pd
import rdkit
from rdkit.Chem import PandasTools
from rdkit import Chem
print(pd.__version__)
print(rdkit.__version__)

PandasTools.RenderImagesInAllDataFrames(images=True)
m = Chem.MolFromSmiles("c1ccccc1")
df = pd.DataFrame(data=[[m]], columns=['Molecule'])
df
```
produced a table with the molecule rendered as <img data-content="rdkit/molecule" src="data:image/png;base64,iVBOR ... alt="Mol">

**Comment by ptosco** [comment]
@drassokhin The following should allow you to display the dataframe in Jupyter:
`HTML(df.to_html(notebook=True))`

This and other `PandasTools` issues will be addressed in the 2022.09 release (end October 2022).

**Comment by drassokhin** [comment]
> HTML(df.to_html(notebook=True))

Did not help, the result was the same (<img data-content="rdkit/molecule"...> instead of the actual image).
```
from IPython.core.display import HTML

PandasTools.RenderImagesInAllDataFrames(images=True)
m = Chem.MolFromSmiles("c1ccccc1")
df = pd.DataFrame(data=[[m]], columns=['Molecule'])
HTML(df.to_html(notebook=True))
```

**Comment by drassokhin** [comment]
I've been thinking that, perhaps, we can work on this issue with Pandas developers/maintainers to work out a stable, documented and reliable way of rendering molecules (or, for that matter, any types of objects that can render themselves as images) within Pandas dataframes in Jupyter notebooks. What do you think?

**Comment by ptosco** [comment]
@drassokhin RDKit release 2022.09 (whose [beta was released today](https://github.com/rdkit/rdkit/releases/tag/Release_2022_09_1b1)) features a complete rewrite of `PandasTools`, which was tested on versions ranging from 0.25.3 to 1.5.0.

**Comment by drassokhin** [comment]
> @drassokhin RDKit release 2022.09 (whose [beta was released today](https://github.com/rdkit/rdkit/releases/tag/Release_2022_09_1b1)) features a complete rewrite of `PandasTools`, which was tested on versions ranging from 0.25.3 to 1.5.0.

Yes, it works now with the latest version or RDKit (if I call PandasTools.RenderImagesInAllDataFrames(images=True)). BTW, I noticed that the same code renders molecules as pictures in a table (as expected) when a Jupyter notebook is opened in Chrome or Firefox, but still shows them as <img src=.../> if the same notebook is opened in PyCharm's scientific mode viewer. I guess I will have to open a ticket with PyCharm developers and let them figure this one out. PyCharm is a very popular Python IDE (for both general and scientific programming), and it is quite likely that I am not the only one who has run into or is going to run into this issue.

**Comment by bp-kelley** [comment]
@ptosco It looks like "df.head()" won't render images anymore, the source code seems to indicate this is possible, but I'm a bit confused about the implementation.

**Comment by ptosco** [comment]
@bp-kelley TL;DR: it will, but you need to call `PandasTools.RenderImagesInAllDataFrames()` upfront.

```
import pandas as pd
from rdkit import Chem
from rdkit.Chem import PandasTools

PandasTools.RenderImagesInAllDataFrames()
test_df = pd.DataFrame({"mol": [Chem.MolFromSmiles(smi) for smi in ("CCl", "CN", "CO")]})
test_df
```
![image](https://user-images.githubusercontent.com/5244385/215054823-8c5ba2de-9b86-4173-a728-28b5ff4fc798.png)
```
test_df.head()
```
![image](https://user-images.githubusercontent.com/5244385/215055036-6e8ab1f6-e6e5-4491-b28a-73e7129d99df.png)

If you only call `PandasTools.ChangeMoleculeRendering(test_df)` on the parent DataFrame, since by default `PandasTools.RenderImagesInAllDataFrames` is set to `False` and `df.head()` is actually a different `DataFrame` instance, it will not have the rendering flag set, hence it won't render molecules as images:

```
test_df = pd.DataFrame({"mol": [Chem.MolFromSmiles(smi) for smi in ("CCl", "CN", "CO")]})
PandasTools.ChangeMoleculeRendering(test_df)
test_df
```
![image](https://user-images.githubusercontent.com/5244385/215058436-d415006f-fd3c-4923-93aa-3235d6e1a240.png)

```
test_df_head = test_df.head()
test_df_head
```
![image](https://user-images.githubusercontent.com/5244385/215058558-b6f71c64-b14c-4a9e-9202-d9ee97efd301.png)

But it will if you enable rendering also on that:
```
PandasTools.ChangeMoleculeRendering(test_df_head)
test_df_head
```
![image](https://user-images.githubusercontent.com/5244385/215058436-d415006f-fd3c-4923-93aa-3235d6e1a240.png)

**Comment by karpanGit** [comment]
With rdkit 2022.09.4 and pandas 1.5.3 I still have issues.
