### ISSUE TITLE
recursive SMARTS matching is wrong

### ISSUE THREAD

**Issue by ct-gh** [rdkit/rdkit#3566]
**Configuration:**

- RDKit Version: 2020.09.1
- Operating system: Debian GNU/Linux 10
- Python version (if relevant): 3.7.3
- Are you using conda?
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit? compiled from source code

**Description:**

I found there is something wrong when I do substructure-match of SMILES on a recursive SMARTS. The following is the sample code.

```
p = Chem.MolFromSmarts('C[$([OH0,SH0,NH0,NH1,SiH2][CX4])]')
mss = ['CCOC', 'CCO', 'CCO[H]', 'CCNC', 'CCN(C)C', 'CCN', 'CCNO']
for ms in mss:
	m = Chem.MolFromSmiles(ms)
	print(ms, m.GetSubstructMatches(p))
```
And here is the result:
1. CCOC ((1, 2), (3, 2))
2. CCO ()
3. CCO[H] ()
4. CCNC ((1, 2), (3, 2))
5. CCN(C)C ((1, 2), (3, 2), (4, 2))
6. CCN ()
7. CCNO ((1, 2),)

No. 1-6 should be correct; however, the last one, No. 7 is supposedly wrong: the [CX4] in the recursive SMARTS is mismatched. Are there any problems in my code, or is it a bug? Here is another example: I used the pattern, “C[$(O[CX4])]”, and fullfilled GetSubstructMatches(...) of the molecule "CCO" (i.e. CH3CH2OH), I also got the similar result, that is, CCO substruct-matched the pattern. But they should NOT be matched: the pattern with the recursive SMARTS "$(O[CX4])" defines (C)-O-alkyl instead of (C)-O-H.

Are there any comments on this question? Thanks.

**Comment by bp-kelley** [comment]
First

X is the total number of connections including implicit connections
D is the total number of explicit connections

Second

Recursive smarts match independently of the upper layer, consider:

```
p = Chem.MolFromSmarts("C[$(O-[CX4)]")
m = Chem.MolFromSmiles("CO")
print(m.GetSubstructMatches(p)) # ==> (0,1),1
```

So this is asking "Match me a Carbon and an oxygen attached to a carbon (attached to 4 things including hydrogens)" where the recursive carbon can match the one already matched.

So your query 

```
0.   (1                      2)
C[$([OH0,SH0,NH0,NH1,SiH2][CX4])]
```

against

```
0123
CCNO
```

Is matching, q=query, m=mol, parens are recursive:

```
q=C1: m=C1
q=(N1,C2) m = (N2,C1)
```

Note that the molecules C1 is matched twice, once normally and once in the recursive match.

If you look at the Functional_Group_Data.txt in rdkit/Data you'll note that they rarely have a starting atom that is not recursive to address this:

```
AcidChloride	C(=O)Cl	Acid Chloride
  AcidChloride.Aromatic	[$(C-!@[a])](=O)(Cl)	Aromatic
  AcidChloride.Aliphatic	[$(C-!@[A;!Cl])](=O)(Cl)	Aliphatic

CarboxylicAcid	C(=O)[O;H,-]	Carboxylic acid
  CarboxylicAcid.Aromatic	[$(C-!@[a])](=O)([O;H,-])	Aromatic
  CarboxylicAcid.Aliphatic	[$(C-!@[A;!O])](=O)([O;H,-])	Aliphatic
  CarboxylicAcid.AlphaAmino	[$(C-[C;!$(C=[!#6])]-[N;!H0;!$(N-[!#6;!#1]);!$(N-C=[O,N,S])])](=O)([O;H,-])
```

So the first match defines the root atom and its environment I.E.  "A carbon attached via a non ring bond to a aromatic atom."   This might be a good place to look for inspiration.

**Comment by bp-kelley** [comment]
@ct-gh does this explanation help at all?

**Comment by ct-gh** [comment]
@bp-kelley , many thanks for your detailed comments. I think I neglected "independently" in "Recursive smarts match **_independently_** of the upper layer". In
`0.   (1                                       2)
C[$([OH0,SH0,NH0,NH1,SiH2][CX4])]`
2 may cover 0.
That really is not what I intend as "Match me an aliphatic Carbon which bonds to an oxygen attached to ANOTHER carbon (than the parent Carbon) which is attached to 4 things including hydrogens". As the Functional_Group_Data.txt implies, I need to define the recursive environment which excludes the parent atom.

**Comment by bp-kelley** [comment]
Great!  Reopen if you need more help.
