### ISSUE TITLE
RDKIT installation on windows 10 failing

### ISSUE THREAD

**Issue by MahaveerSatra** [rdkit/rdkit#3568]
I have been trying to install RDKit 2020_09_1 (Q3 2020) Release from source on my windows 10 system. However the cmake step does not get through. The output shows configuring and generating done, but the code does not build and a "CMakeError.txt" file is generated
[CMakeError.log](https://github.com/rdkit/rdkit/files/5549515/CMakeError.log)

The generated output file is:
[CMakeOutput.log](https://github.com/rdkit/rdkit/files/5549517/CMakeOutput.log)

The cmd trace is shown below:
[cmd.txt](https://github.com/rdkit/rdkit/files/5549531/cmd.txt)

**Configuration:**

>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\RDKit\rdkit\__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ModuleNotFoundError: No module named 'rdkit.rdBase'

- RDKit Version: N.A. (2020_09_1 (Q3 2020) Release) 

- Operating system: Windows 10, 64-bit OS

- Python version (if relevant): 3.9.0

- Are you using conda? No

- If you are using conda, which channel did you install the rdkit from? N.A. 

- If you are not using conda: how did you install the RDKit? Downloaded the source files from github, installed "boost version _71_0" using the commands explained in https://github.com/rdkit/rdkit/issues/2841

using cmake version 3.19.0 and visual studio 16 2019

**Description:**

I have installed Python 3.9 and numpy package and could successfully install boost. However, when I am trying to install RDKit from source it gives me an error pertaining to "pthreads.h" as shown in the CMakeError.log. After reading through threads, I have installed vcpkg for pthreads.h and included the library and header files in the Visual studio project. However, the installation still errors out.

I have set the environment variables RDBASE, PYTHONPATH and included the other directories in the path. 

The cmake command I am using to build is given below:
cmake -DBoost_DEBUG=ON -DBoost_THREADAPI=win32 -DRDK_BUILD_SWIG_JAVA_WRAPPER="OFF" -DEigen3_DIR=C:\\Program Files (x86)\\Eigen3\\share\\eigen3\\cmake -DMSVC_RUNTIME_DLL=C:\WINDOWS\SysWOW64\msvcr100.dll -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DBOOST_ROOT=C:\boost -DRDK_BUILD_INCHI_SUPPORT=ON -DRDK_BUILD_AVALON_SUPPORT=ON -DRDK_BUILD_PGSQL=OFF -DCMAKE_BUILD_TYPE=Release -DBoost_NO_BOOST_CMAKE=OFF -DBOOST_LIBRARYDIR=C:\boost\win32-x86_64\lib -DBoost_NO_SYSTEM_PATHS=ON -DPYTHON_EXECUTABLE=C:\Users\msatra\AppData\Local\Programs\Python\Python39\python.exe -D RDK_INSTALL_STATIC_LIBS=OFF -D RDK_INSTALL_DLLS_MSVC=ON -G "Visual Studio 16 2019" -A x64 ..

Request to please assist me. I have stuck for more than a week now.

Thank you!

**Comment by greglandrum** [comment]
The `cmd.txt` file you include seems to indicate that the cmake ran without problems.
You should now have a .sln file in the directory where you ran cmake. You need to open that solution in visual studio and build the INSTALL target to actually build and install the RDKit.

**Comment by MahaveerSatra** [comment]
Hi Greg, I appreciate your quick response!

Yes, a "RDKit.sln" is generated in the build folder and I tried building the INSTALL target on Visual studio. However, it failed with the following result:
Done building project "INSTALL.vcxproj" -- FAILED.
========== Build: 13 succeeded, 170 failed, 0 up-to-date, 0 skipped ==========

I have attached the output log from visual studio in file "Visual_Studio_output.txt"
[Visual_Studio_output.txt](https://github.com/rdkit/rdkit/files/5555081/Visual_Studio_output.txt)

After digging through the output, I found the 1st error was at line 842:
>> C:\WINDOWS\SysWOW64\msvcr100.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x288

In an attempt to resolve this, I re-generated the build files by modifying the cmake command as given below:
>> cmake -DBoost_DEBUG=ON -DBoost_THREADAPI=win32 -DRDK_BUILD_SWIG_JAVA_WRAPPER="OFF" -DEigen3_DIR="C:\Program Files (x86)\Eigen3\share\eigen3\cmake" -DRDK_INSTALL_DLLS_MSVC=ON -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DBOOST_ROOT=C:\boost -DRDK_BUILD_INCHI_SUPPORT=ON -DRDK_BUILD_AVALON_SUPPORT=ON -DRDK_BUILD_PGSQL=OFF -DCMAKE_BUILD_TYPE=Release -DBoost_NO_BOOST_CMAKE=OFF -DBOOST_LIBRARYDIR=C:\boost\win32-x86_64\lib -DBoost_NO_SYSTEM_PATHS=ON -DPYTHON_EXECUTABLE=C:\Users\msatra\AppData\Local\Programs\Python\Python39\python.exe -DRDK_INSTALL_STATIC_LIBS=ON -G "Visual Studio 16 2019" -A x64 ..

Particularly, I turned the "RDK_INSTALL_STATIC_LIBS=ON" and removed this flag "-DMSVC_RUNTIME_DLL=C:\WINDOWS\SysWOW64\msvcr100.dll"

The build was successful and I tried building the INSTALL target again, the build failed with the following output:
242>Done building project "INSTALL.vcxproj" -- FAILED.
========== Build: 133 succeeded, 109 failed, 0 up-to-date, 0 skipped ==========

I have attached the output log from visual studio in file "Visual_Studio_Ouput_2.txt"
[Visual_Studio_Ouput_2.txt](https://github.com/rdkit/rdkit/files/5555163/Visual_Studio_Ouput_2.txt)

The errors are related to 
 "error C2491: definition of dllimport function not allowed" and "error C2491: definition of dllimport static data member not allowed"
which fails the project generation and the rest seems to be a cascading effect. 

I tried searching for a possible workaround or fix, but did not find any success as of yet.

Can you please provide some guidance on the same?

Thank you!

**Comment by SPKorhonen** [comment]
I'm not sure if this issue is still relevant, but I noticed some possible causes for you troubles.  It seems that CMake completes successfully but build fails. In the build log (Visual_Studio_output.txt) you have two errors:

1) C:\WINDOWS\SysWOW64\msvcr100.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x288 => Which means that the MS RT dll is invalid. I have no idea why the build process should use other MS RT than one associated with the Win SDK used to build the RDKit. So I think flag "MSVC_RUNTIME_DLL=C:\WINDOWS\SysWOW64\msvcr100.dll" is unnecessary if not outright harmful.

2) C:\RDKit\Code\GraphMol\FileParsers\PNGParser.cpp(25,10): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory => Which means that you are missing zlib source. Download it and set -DZLIB_ROOT=<ZLIB_DIR> as appropriate.

PS. I would advise against using "RDK_INSTALL_STATIC_LIBS=ON" as it causes problems (see #3712)
