### ISSUE TITLE
RDKit JS wrapper release to a registry?

### ISSUE THREAD

**Issue by hadim** [rdkit/rdkit#3576]
I am looking for a way to use the JS wrapper to bring rdkit features in a JS frontend app. Correct me if I am wrong but the current way to use the wrapper is to clone rdkit, build the JS wrapper in Code/MinimalLib and just copy-paste the output files to a given project.

Would it be possible to do that automatically during the release process of RDKit and deploy the built package to a registry (GitHub has one for example and npmjs can also be used here I guess)?

That way it will be possible to just specify the rdkitJS package in a package.json file as it is done for all the other dependencies in a regular JS codebase.

**Comment by greglandrum** [comment]
I'd be happy to do this, but I don't know how since I'm not much of a JS expert.
Are there docs anywhere describing best practices for putting artifacts in a JS registry ?

**Comment by hadim** [comment]
Pretty sure there is plenty. Here the one from npmjs.com that is (if I recall correctly) one of the biggest JS packages registry:

- Create a package.json file: https://docs.npmjs.com/creating-a-package-json-file
- Publish a package: https://docs.npmjs.com/creating-and-publishing-scoped-public-packages

To build the package locally and publishing it you'll need a small tool call `npm`. More details here https://docs.npmjs.com/downloading-and-installing-node-js-and-npm

The `package.json` file is the one describing the metadata of your package (version, name, deps, etc).

Happy to help more if you need it.

**Comment by MichelML** [comment]
+1, I might give it a shot

**Comment by MichelML** [comment]
Hi @greglandrum , I took the time to prepare an example for publishing the minimal lib to npm on this rainy Sunday.

See the PR here https://github.com/rdkit/rdkit/pull/4086  - happy to receive feedback anytime soon, hope you guys will like it!

Cheers

Michel
