### ISSUE TITLE
Release 2020.09.2 builds with old version number 2020.09.1

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#3590]
**Configuration:**

- RDKit Version: 2020.09.2

**Description:**

Far from critical and mainly FYI, but I think the RDKit Release_2020.09.2 is still configured with revision number "1"
https://github.com/rdkit/rdkit/blob/Release_2020_09_2/CMakeLists.txt#L124

**Comment by greglandrum** [comment]
damn. I forgot to change that. Thanks for noticing.
Any thoughts on how/if to fix that?
The other thing I could do is just plan to release 2020.09.3 sooner and make sure it's fixed there.

**Comment by rvianello** [comment]
I also can't think of any different solution than just waiting for the next patch revision. The only limitation with the 2020.09.2 release is that the version number returned by the code may be not sufficient to identify it, but distribution packages are usually versioned based on the git tag, and in the worst (but hopefully sufficiently unlikely) case, one could probably test some feature that changed after the 2020.09.1 release.

**Comment by greglandrum** [comment]
Closing this because we know about the problem and it's been fixed for the 2020.09.3 release.
