### ISSUE TITLE
Generate stub files for rdkit

### ISSUE THREAD

**Issue by hadim** [rdkit/rdkit#3591]
I successfully generated stub files for rdkit using `mypy` with `stubgen -p rdkit`. Then I put the generated folder into my library under a `typings` folder. The static analyzer I use (pylance here) can recognize a good proportion of rdkit types. Something failing before I used those stub files.

How would you feel about integrating those stub files into the rdkit python package?

**Comment by kexul** [comment]
Hi @hadim , would you mind sharing the hierarchy of the `typings` folder? I would like to use it in my vscode, but I'm not sure where I should put the files.

**Comment by hadim** [comment]
It used to be in a earlier version of datamol (a lib I have created and maintain) at https://github.com/datamol-org/datamol/tree/0.2.6/typings/rdkit

I removed it since then to not make the lib too heavy.

It would be nice to have this in rdkit by default.

**Comment by kexul** [comment]
Thank you~

**Comment by d-miketa** [comment]
+1 for this request. Pyright's complaining about missing `rdkit.Chem.MolFromSmiles` even though the function is accessible in the Python environment; only the stub is incomplete.

**Comment by greglandrum** [comment]
I’m not opposed to this, but it’s not a tool chain that I know (or have the time/interest to learn) so it’s not something I can help with. If someone else can do a PR which includes an automated way to generate these files and put them in the appropriate place I would be happy to review it

**Comment by ptosco** [comment]
@ATheCoder @greglandrum  I have already done this. I’ll submit a PR at the beginning of next week.

**Comment by UnixJunkie** [comment]
this feature is interesting for people who want to type check their python code using mypy

**Comment by ptosco** [comment]
I am closing this as auto-generated stubs have been available since release 2023.09.1.
