### ISSUE TITLE
Scientific notation in SDF V3000 files

### ISSUE THREAD

**Issue by mark-cresset** [rdkit/rdkit#3597]
RDKit can write SDF V3000 files with scientific notation for the coordinates e.g. an atom line of

M  V30 13 C 6.49467e-17 1.06066 0 0

The CTfile spec document contains not a single example of numbers in scientific notation, and certainly the V2000 spec definitely requies fixed-point, so this is arguably out of spec.

Probably not an issue for most people, but it did confuse our (very elderly) SDF V3000 parser which is assuming fixed-point notation.

Regards,
Mark.

**Comment by greglandrum** [comment]
Hi Mark,

That’s certainly a bug. Would you mind reporting it on github?

Regardless, I will take a look.

-greg
