### ISSUE TITLE
rdMolDraw2D, problems during generation of pictures from reaction smarts - wrong depiction of double bond geometry and no stereoannotation

### ISSUE THREAD

**Issue by wopozka** [rdkit/rdkit#3610]
**Describe the bug**
It might be one bug (or maybe a feature) or two independent. As I am not able to figure it out, I decided to open one issue for both.
1) Depicting of double bond geometry for reactions produces always E izomer regardless on the SMARTS/SMILES definition, when useSmiles option is used, eg:
```
reaction1 = AllChem.ReactionFromSmarts('CC#C.I>>C/C=C\I', useSmiles=True)
reaction1 = AllChem.ReactionFromSmarts('CC#C.I>>C/C=C/I', useSmiles=True)
```
both produce the same picture:
![image](https://user-images.githubusercontent.com/46928633/101089606-acd62480-35b5-11eb-8902-95f3f4542311.png)
when useSmiles is not used generated picture is ok:
reaction1 = AllChem.ReactionFromSmarts('CC#C.I>>C/C=C\I')
![image](https://user-images.githubusercontent.com/46928633/101089864-0f2f2500-35b6-11eb-90b9-f596ab0e1675.png)

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem import rdDepictor
rdDepictor.SetPreferCoordGen(True)
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG
import rdkit
print(rdkit.__version__)
reaction1 = AllChem.ReactionFromSmarts('CC#C.I>>C/C=C\I', useSmiles=True)
reaction1.Initialize()
d2d = rdMolDraw2D.MolDraw2DSVG(300, 300)
d2d.drawOptions().addStereoAnnotation=True
d2d.DrawReaction(reaction1)
d2d.FinishDrawing()
SVG(d2d.GetDrawingText())
```
**Expected behavior**
Double bond geometry should be depicted properly when useSmiles option is used.

2) addStereoAnnotation option does not work for reactions (it might be a feature, I am not sure)
eg: 
reaction1 = AllChem.ReactionFromSmarts('C[C@H](Cl)CCC.N>>C[C@@H](N)CCC.Cl', useSmiles=True)
does not produce any stereoannotation when generating picture
![image](https://user-images.githubusercontent.com/46928633/101090627-39351700-35b7-11eb-96b7-88eaab181199.png)

**To Reproduce**
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem import rdDepictor
rdDepictor.SetPreferCoordGen(True)
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG
import rdkit
print(rdkit.__version__)
reaction1 = AllChem.ReactionFromSmarts('C[C@H](Cl)CCC.N>>C[C@@H](N)CCC.Cl', useSmiles=True)
reaction1.Initialize()
d2d = rdMolDraw2D.MolDraw2DSVG(300, 300)
d2d.drawOptions().addStereoAnnotation=True
d2d.DrawReaction(reaction1)
d2d.FinishDrawing()
SVG(d2d.GetDrawingText())

**Expected behavior**
Absolute configuration should be generated as it works for molecules

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.1
 - OS: [e.g. Ubuntu 20.04]: MacOSX
 - Python version (if relevant): 3.7
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? rdkit

**Comment by greglandrum** [comment]
Hi @wopozka : this got lost in the end-of-year rush. I will try to take a look this week.

**Comment by wopozka** [comment]
Hi @greglandrum,
Just pinging, to be sure the bug was not lost.

**Comment by greglandrum** [comment]
Nope. Not lost. But I haven't had time to look at it yet either.

**Comment by wopozka** [comment]
@greglandrum I decided to dust off old topic. I digged a bit and found that when you do ReactionFromSmarts with useSmiles=True, the molecule is not actually sanitized nor stereochemistry is assigned (AssignStereochemistry). This is the reason why wrong cis/trans izomer is depicted. The question is whether mols should be sanitized and stereochemistry assigned in this case. In my opinion they should by default, and in case of failure they should be left unsanitized. Or we should have at least an option whether to sanitize or not mol in case of useSmiles=True.

**Comment by wopozka** [comment]
@greglandrum I've digged even more and my impression is that that calling setBondStereoFromDirections in preprocessSmiles should do the job. If I call it seperatelly in notebook, everything is depicted correctly. My impression is the function should be called somwhere after: if (res && (params.sanitize || params.removeHs)). Maybe something like below, but I am not sure for 100%, as my understanding of code might not be enough.

```
if (res && (params.sanitize || params.removeHs)) {
    try {
      if (params.removeHs) {
        bool implicitOnly = false, updateExplicitCount = true;
        MolOps::removeHs(*res, implicitOnly, updateExplicitCount,
                         params.sanitize);
      } else if (params.sanitize) {
        MolOps::sanitizeMol(*res);
      }
    } catch (...) {
      delete res;
      throw;
    }
else {
   MolOps::setBondStereoFromDirections(*res)
}
```

**Comment by greglandrum** [comment]
@wopozka : I'm generally uncomfortable making changes like this in the SMILES reader, but I will take a look

**Comment by wopozka** [comment]
@greglandrum, I fully understand and to be fair, when presently I figure out how to overcome the problem, I can live with it. In case of second problem (chirality) the thing is probably more complicated. You can't AssignStereochemistry without sanitization (at least my attempts show so), so I do not see any easy solution, apart from Sanitize=True when reaction is created with useSmiles=True. Anyway, in case it is decided not to fix it, lets leave the solution for record. The first case (double bond)

```
reaction1 = AllChem.ReactionFromSmarts('CC#C.I>>C/C=C\\I', useSmiles=True)
for mol in reaction1.GetProducts():
    Chem.SetBondStereoFromDirections(mol)
for mol in reaction1.GetReactants():
   Chem.SetBondStereoFromDirections(mol)
```

for the second case, chirality, below should do the job:

```
reaction1 = AllChem.ReactionFromSmarts('C[C@H](Cl)CC.N>>C[C@@H](N)CC.Cl', useSmiles=True)
reaction1.Initialize()
for mol in reaction1.GetProducts():
    Chem.SanitizeMol(mol)
    Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
for mol in reaction1.GetReactants():
    Chem.SanitizeMol(mol)
    Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
d2d = rdMolDraw2D.MolDraw2DSVG(300, 300)
d2d.drawOptions().addStereoAnnotation=True
d2d.DrawReaction(reaction1)
d2d.FinishDrawing()
```
