### ISSUE TITLE
Morgan Fingerprint differs between between 2020.09 and 2019.03

### ISSUE THREAD

**Issue by JanoschMenke** [rdkit/rdkit#3614]
So I found that the my Morgan Fingerprints slightly changed after finally upgrading from 2019.03. I would assume that is due to the changes made in 2019.09. But I could not find the specific change that was made to the Morgan fingerprint.

>  The default values for some of the new fingerprint generators have been changed so that they more closely resemble the original fingerprinting code. In particular most fingerprinters no longer do count simulation by default and the RDKit fingerprint now sets two bits per feature by default.

My Question was something changed with regards to the morgan fingerprint, in that time and if so which specifc changes was made to the morgan fingerprinter. I could not find it.

**Comment by greglandrum** [comment]
To the best of my knowledge nothing changed in the morgan fingerprinting code itself. It's likely that what you're observing is caused by changes elsewhere in the code. If you share the structure of a molecule where you are seeing this happen, I can point out what changed.
