### ISSUE TITLE
Draw.MolToImage() cannot highlight with highlightMap (v > '2019.09.3' )

### ISSUE THREAD

**Issue by spideralessio** [rdkit/rdkit#3616]
After rdkit  '2019.09.3' the hilightMap does not change color to bonds when drawing molecule with Draw.MolToImage().

There is another issue with the same problem but was closed, the problem still persists.

I am forced to downgrade to 2019.09.3 to make it work

**Comment by greglandrum** [comment]
Hi @spideralessio, please provide example code which used to work and no longer does and then we can try to identify and fix the problem.

**Comment by kexul** [comment]
@greglandrum I encountered the same problem. Here is some example to reproduce it. 
```
from rdkit import Chem 
from rdkit.Chem.Draw import MolToImage
mol = Chem.MolFromSmiles('CCCCC')
colormap = {0:(1, 0, 0), 1:(0, 0, 1)}
img = MolToImage(mol, highlightMap=colormap)
img.save('example.png')
```

Here is the `example.png` generated by rdkit > 2019.09.3.
![example](https://user-images.githubusercontent.com/5920217/102298820-d0717580-3f8c-11eb-9ab6-3a400f7fe3d6.png)

Here is 2019.09.3 generated:
![example](https://user-images.githubusercontent.com/5920217/102298880-f139cb00-3f8c-11eb-9807-0b32f1f4aef6.png)

**Comment by tumitran** [comment]
i have the same problem

from matplotlib.colors import ColorConverter 
img = Draw.MolToImage(mols[0], highlightAtoms=[1,2], 
                      highlightColor=ColorConverter().to_rgb('blue')) 

![image](https://user-images.githubusercontent.com/18971303/114126078-b48c3980-98c5-11eb-82eb-3d6fa546464f.png)

**Comment by greglandrum** [comment]
Confirmed that this isn't working as expected.

**Comment by greglandrum** [comment]
@kexul : yes, the `highlightMap` argument is no longer supported. I will update the documentation to support this.
