### ISSUE TITLE
Chem.MolToPDBFile() still prints out CONECT records when flavor=2

### ISSUE THREAD

**Issue by mieczyslaw** [rdkit/rdkit#3622]
**Describe the bug**
I used flavor=2 option of Chem.MolToPDBFile in order to skip CONECT records, but they are still printed out.

**To Reproduce**
Write the protein molecule to PDB using:
`Chem.MolToPDBFile(protein_mol, "file_name.pdb", flavor=2)`

**Expected behavior**
No CONECT records are present in file_name.pdb.

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.1 (py38he572eef_0, conda-forge) 
 - OS: [e.g. Ubuntu 20.04] RedHat 7.8 (Maipo)
 - Python version (if relevant): 3.8.5
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**
I followed the documnatation here: https://www.rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html

**Comment by greglandrum** [comment]
Here's a simple reproducible:
```
In [6]: m = Chem.MolFromSequence('G')

In [7]: print(Chem.MolToPDBBlock(m,flavor=2))
ATOM      1  N   GLY A   1       0.000   0.000   0.000  1.00  0.00           N  
ATOM      2  CA  GLY A   1       0.000   0.000   0.000  1.00  0.00           C  
ATOM      3  C   GLY A   1       0.000   0.000   0.000  1.00  0.00           C  
ATOM      4  O   GLY A   1       0.000   0.000   0.000  1.00  0.00           O  
ATOM      5  OXT GLY A   1       0.000   0.000   0.000  1.00  0.00           O  
CONECT    3    4    4
END
```
It seems to be connected to using repeated conect records for multiple bonds, because the bonds that are left are just multiple bonds and setting flavor=10 gets rid of them entirely:
```
In [8]: print(Chem.MolToPDBBlock(m,flavor=10))
ATOM      1  N   GLY A   1       0.000   0.000   0.000  1.00  0.00           N  
ATOM      2  CA  GLY A   1       0.000   0.000   0.000  1.00  0.00           C  
ATOM      3  C   GLY A   1       0.000   0.000   0.000  1.00  0.00           C  
ATOM      4  O   GLY A   1       0.000   0.000   0.000  1.00  0.00           O  
ATOM      5  OXT GLY A   1       0.000   0.000   0.000  1.00  0.00           O  
END
```

**Comment by greglandrum** [comment]
#3089 is also related

**Comment by mieczyslaw** [comment]
Thank you @greglandrum ! yes, 2|8 from another ticket helps, is that equivalent to 10? 

It would be worth updating the documentation... This ticket can be obviously marked as a duplicate to #3089

**Comment by greglandrum** [comment]
I had to confirm this with Roger (who actually understands the PDB format) To confirm: this is a documentation problem. It is intentional that setting flavor=2 just causes single bonds to be skipped and flavor = 2|8 is required to disable all CONECT records
