### ISSUE TITLE
Inconsistent metal disconnectors

### ISSUE THREAD

**Issue by pschwllr** [rdkit/rdkit#3625]
@Aless-T and I observed the following.  There are two ways to import the MetalDisconnector. In version 2020.09 the behaviour of one of them, "MetalDisconnector2" below (from rdkit.Chem.MolStandardize.rdMolStandardize import MetalDisconnector ), changed and they are inconsistent. 

Minimal example:
```python
import rdkit
from rdkit import Chem
from rdkit.Chem.MolStandardize.metal import MetalDisconnector
from rdkit.Chem.MolStandardize.rdMolStandardize import MetalDisconnector as MetalDisconnector2
print(rdkit.__version__)
smi = "Cl[Pd+]"
old_mol = Chem.MolFromSmiles(smi)

md = MetalDisconnector()
new_mol = md.disconnect(old_mol)
new_smi = Chem.MolToSmiles(new_mol)
print(new_smi) 
# v2020.09.1 prints: "[Cl-].[Pd+2]"
# v2020.03.3 prints:  "[Cl-].[Pd+2]"

md2 = MetalDisconnector2()
new_mol2 = md2.Disconnect(old_mol)
new_smi2 = Chem.MolToSmiles(new_mol2)
print(new_smi2) 
# v2020.09.1 prints: "[Cl-].[Pd+]" <—— charge fixed at +1
# v2020.03.3 prints:  "[Cl-].[Pd+2]"
```

The change was probably introduced in this commit (https://github.com/rdkit/rdkit/commit/f1119f3980461f3c436b6de9ab10453730bc7621), @ptosco what is the rational behind? 
It would be good if both MetalDisconnectors behaved the same. 
Would it make sense to add a flag, so that the user chooses the behaviour?

**Comment by ptosco** [comment]
@pschwllr
When you
```
from rdkit.Chem.MolStandardize.metal import MetalDisconnector
```
you import the original MolVS Python implementation by Matt Swain, while when you
```
from rdkit.Chem.MolStandardize.rdMolStandardize import MetalDisconnector as MetalDisconnector2
```
you import the C++ implementation of MolVS made by Susan Leung and Greg Landrum.
I have made a number of bug fixes and improvements to the C++ implementation, also involving the `MetalDisconnector` components, so the results are not going to be necessarily consistent with those yielded by the original MolVS implementation.
If you believe there are bugs in the C++ implementation, please do file them with reproducible test cases, but I don't think the inconsistency between the original MolVS Python implementation is a bug <i>per se</i>.
@greglandrum Any thoughts?

**Comment by pschwllr** [comment]
I agree that it is not a bug per se.

- Would be good if users were made aware of the fact that the two MetalDisconnectors differ. 
- Looking at the example above `"Cl[Pd+]" -> "[Cl-].[Pd+]"`, @ptosco why fix the charge of the metal in that case and hence, change the total charge? 

The current documentation states:
> • Disconnect N, O, F from any metal.
• Disconnect other non-metals from transition metals + Al (but not Hg, Ga, Ge, In, Sn, As, Tl, Pb, Bi, Po).
• For every bond broken, adjust the charges of the begin and end atoms accordingly.

How are the charges of the begin and end atoms adjusted in the new version? Because this behaviour clearly changed with the recent bug fixes and improvements.

**Comment by ptosco** [comment]
@pschwllr You are absolutely right. I inadvertently introduced this regression in #3465. I have just submitted a PR that fixes it and added unit tests to avoid that this happens again.

**Comment by pschwllr** [comment]
@ptosco and @greglandrum thanks for the prompt response!
