### ISSUE TITLE
Incorrect bond length for N#N in MMFF

### ISSUE THREAD

**Issue by chrisbutch** [rdkit/rdkit#3629]
After embedding and MMFF minimization the reported bond length for N#N is 1.46, longer that the N-N single bond (1.44), and much longer than the experimental value of 1.09. Probably an edge case, but I wanted to report it.

rdkit                     2020.03.3        py37hb7b3aaa_0    conda-forge

Gist:

from rdkit import Chem
from rdkit.Chem import AllChem

smiles="N#N"
m=Chem.MolFromSmiles(smiles)
m=Chem.AddHs(m)
AllChem.EmbedMolecule(m)
AllChem.MMFFOptimizeMolecule(m)
x=Chem.rdMolTransforms.GetBondLength(m.GetConformer(),0,1)

**Comment by greglandrum** [comment]
That's actually the MMFF optimizer. UFF yields 1.12.

@ptosco : is this a parameterization bug or just something we should expect for MMFF (since it probably isn't parameterized for N2)?

**Comment by ptosco** [comment]
```
from rdkit import Chem
from rdkit.Chem import AllChem

smiles="N#N"
m = Chem.MolFromSmiles(smiles)
m = Chem.AddHs(m)
AllChem.EmbedMolecule(m)
0

m.GetNumAtoms()
2
```
The force field has parameters for `N#`:
```
mp = AllChem.MMFFGetMoleculeProperties(m)
[mp.GetMMFFAtomType(i) for i in range(m.GetNumAtoms())]
[42, 42]
```
But no specific parameters for `N#N`, so the bond equilibrium length is derived using the Herschberg/Laurie parameterization of Badger's rule:
```
mp.GetMMFFBondStretchParams(m, 0, 1)
(0, 2.76308378307355, 1.46)
```
AFAICR, the implementation details were quite obscure in the MMFF94 papers and I had to comment out a number of rules described in the paper as they caused failure when running the MMFF validation suite (as if the actual reference implementation used to generate the validation data was different to what described in the paper).
`1.46` for N<sub>2</sub> seems too outrageously wrong, so I'll definitely investigate. I have assigned this to me, but please be aware I will most likely not get to it before end of next week.
