### ISSUE TITLE
Segmentation fault when parsing InChI

### ISSUE THREAD

**Issue by AnPallo** [rdkit/rdkit#3645]
-----------------------------------------

**Describe the bug**
from rdkit import Chem 
m=Chem.MolFromInchi('InChI=1S/C9H22O3SSi/c1-5-9-13(14,10-6-2,11-7-3)12-8-4/h5-9H2,1-4H3') 
or
m=Chem.MolFromInchi('InChI=1S/C8H20O3SSi/c1-5-9-12(13,8-4,10-6-2)11-7-3/h5-8H2,1-4H3')

-> if run as part of a script: Segmentation fault (core dumped), process crashes
or if in console: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Expected behavior**
An error message, that I could catch. 

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.1
 - OS: Ubuntu 18.04.4 LTS
 - Python version (if relevant): Python 3.7.6
 - Are you using conda? yes

**Additional context**
https://pubchem.ncbi.nlm.nih.gov/compound/145829279#section=2D-Structure

**Comment by greglandrum** [comment]
confirmed. Thanks for the report!
