### ISSUE TITLE
RDK_BUILD_THREADSAFE_SSS does not work as expected

### ISSUE THREAD

**Issue by pascal-soveaux** [rdkit/rdkit#3646]
**Describe the bug**
Using cmake -DRDK_BUILD_THREADSAFE_SSS=ON does not work as expected. Using make with  --trace shows that it has been redefined as "-DRDK_THREADSAFE_SSS" and is thus empty. This does not work because #if is used instead of #ifdef all over the code.
 
Adding CXX_FLAGS="-DRDK_BUILD_THREADSAFE_SSS=1" does not work either because PeriodicTable.cpp tries to include ```<mutexp>``` (I guess it is a typo)

PeriodicTable.cpp
```
#if RDK_BUILD_THREADSAFE_SSS
#include <mutexp>
#endif
```
This was introduced with "Switch from boost::thread to std::thread".

**To Reproduce**
cmake -DRDK_BUILD_THREADSAFE_SSS=ON <...> This should not compile because of the typo in periodictable.cpp but it does compile because ```#if RDK_BUILD_THREADSAFE_SSS``` is always false. 

I found this issue because my app was *sometimes* failing with  "double free or corruption (fasttop)",  the dump shows that the code is not thread safe thus the race condition. 

**Expected behavior**
Set RDK_BUILD_THREADSAFE_SSS=ON to compile a thread safe version.

**Configuration (please complete the following information):**
 - RDKit version: Release_2020_09_3 
 - OS: [e.g. Ubuntu 20.04] Not relevant
 - Python version (if relevant): Not relevant
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? source code

cmake version 3.18.4
g++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0

**Comment by greglandrum** [comment]
Confirmed. thanks for catching this (somewhat embarassing) typo in the code.
