### ISSUE TITLE
Add a callback function to EmbedParameters struct

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#3667]
**Is your feature request related to a problem? Please describe.**
The runtime environment I use RDKit in has a concept of a top-level user abort, which is nice for any computation that can take longer than expected.  When a user aborts in top level, I can detect this in c++ and issue an exception.  But I can't detect a user abort during a call to EmbedMolecule, which can take a very long time for some molecules.

**Describe the solution you'd like**
If the struct `EmbedParameters` contained a void function pointer, I could pass in my own callback function to check for user aborts.  This works quite well for the MCS code.

**Additional context**
The change in [this branch](https://github.com/rdkit/rdkit/compare/master...jasondbiggs:embedder_callback) solves my problem.  I could make a PR to this effect if no one objects. 

I imagine the callback function could be more general.  It could return take the iteration variable as an argument, to allow progress reporting, but I don't have an immediate need for this.

**Comment by greglandrum** [comment]
makes sense to me!

**Comment by greglandrum** [comment]
Closed by #3668
