### ISSUE TITLE
Documentation of Chem.rdmolops.GetMolFrags's frag argument is wrong

### ISSUE THREAD

**Issue by noncomputable** [rdkit/rdkit#3670]
The docs for Chem.rdmolops.GetMolFrags are here: http://rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.GetMolFrags

They read:
> frags: (optional, defaults to None) if this is provided as an empty list, the result will be mol.GetNumAtoms() long on return and will contain the fragment assignment for each Atom

So `Chem.rdmolops.GetMolFrags(mol, frags = [])` should return a collection of length mol.GetNumAtoms(). But passing an empty list to frags (either as a named or positional arg) doesn't do this; the frags argument doesn't seem to affect the output at all.

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.3 
 - OS: Windows 10
 - Python version: 3.7
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
Hi @noncomputable : the documentation is incorrect here; thanks for pointing that out.

The `frags` argument only does anything if `asMols` is also True.
Here's what you observe:
```
>>> mol = Chem.MolFromSmiles('CC[O-].[Na+]')
>>> fragAssignment = []
>>> mol_frags = Chem.GetMolFrags(mol,frags=fragAssignment)
>>> fragAssignment
[]
```
But if you set `asMols` you get the expected result:
```
>>> fragAssignment = []
>>> mol_frags = Chem.GetMolFrags(mol,asMols=True,frags=fragAssignment)
>>> fragAssignment
[0, 0, 0, 1]
```
I'll correct the documentation to make sure it's clear that both the `frags` and `fragsMolAtomMapping` arguments are used if `asMols=True`.

**Comment by noncomputable** [comment]
I think the docs for the `fragsMolAtomMapping` arg can be cleared up too. 

It reads:
>fragsMolAtomMapping: (optional, defaults to None) if asMols is true and this is provided as an empty list, the result will be numFrags long on return, and each entry will contain the indices of the Atoms in that fragment: [(0, 1, 2, 3), (4, 5)]

But it doesn't return that, it mutates the input list into a list of tuples as described, but it still returns a list of mols.
