### ISSUE TITLE
False Indextation when use GetSubStructMatches()

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#3671]
**Describe the bug**
False Indextation when use GetSubStructMatches(), I don't understand the index 7 ?

**To Reproduce**
```
from rdkit.Chem import *
mol = AddHs(MolFromSmiles('CC=CC'))
env = FindAtomEnvironmentOfRadiusN(mol, radius=2, rootedAtAtom=3, useHs=True)
print(list(env))
map = {}
submol = PathToSubmol(mol, path=env, atomMap=map)
print(Chem.MolToSmiles(submol))
print(map)
print(submol.GetNumAtoms())
a = mol.GetSubstructMatches(submol, uniquify=True)
print('MOL IDX: ', a[0])
print('Radical: ', a[1])

from rdkit.Chem.Draw.rdMolDraw2D import MolDraw2DCairo
d = MolDraw2DCairo(1200, 900)
d.drawOptions().addAtomIndices = True
d.DrawMolecule(mol)
d.FinishDrawing()
d.WriteDrawingText('atom_annotation_1.png')
d.ClearDrawing()
d.DrawMolecule(submol)
d.FinishDrawing()
d.WriteDrawingText('atom_annotation_2.png')
```

**Expected behavior**
Real Result:
```
MOL IDX:  (1, 2, 3, 8, 9, 10, 11)
Radical:  (2, 1, 0, 7, 4, 5, 6)
```

Expected:
```
MOL IDX:  (1, 2, 3, 8, 9, 10, 11)
Radical:  (0, 1, 2, 3, 5, 4, 6)
```

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.1
 - OS: [e.g. Ubuntu 20.04]: Windows 10
 - Python version (if relevant): 3.7.9
 - Are you using conda? Yes

**Comment by greglandrum** [comment]
Assuming that I've understood your question correctly, this is happening because the atom numbering returned by PathToSubmol is different from the atom number in the original molecule.

If you want to, you can keep track of the original atom indices using atomic properties. Here's an example of how to do that and how to get the indices of the original atoms from a substructure search:
```
>>> m = Chem.MolFromSmiles('CCOCC')
>>> for atom in m.GetAtoms():
...     atom.SetIntProp("_atidx",atom.GetIdx())
... 
>>> submol = Chem.PathToSubmol(m,[1,2])
>>> submol.GetAtomWithIdx(0).GetPropsAsDict()
{'__computedProps': <rdkit.rdBase._vectNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE object at 0x7effa7691db0>, '_atidx': 1}
>>> match = Chem.GetSubstructMatch(submol,Chem.MolFromSmarts('CO'))
Traceback (most recent call last):
  File "<ipython-input-28-822ccbed4181>", line 1, in <module>
    match = Chem.GetSubstructMatch(submol,Chem.MolFromSmarts('CO'))
AttributeError: module 'rdkit.Chem' has no attribute 'GetSubstructMatch'

>>> match = submol.GetSubstructMatch(Chem.MolFromSmarts('CO'))
>>> list(match)
[0, 1]
>>> originalIndices = [submol.GetAtomWithIdx(x).GetIntProp('_atidx') for x in match]
>>> originalIndices
[1, 2]
```

**Comment by IchiruTake** [comment]
> Assuming that I've understood your question correctly, this is happening because the atom numbering returned by PathToSubmol is different from the atom number in the original molecule.
> 
> If you want to, you can keep track of the original atom indices using atomic properties. Here's an example of how to do that and how to get the indices of the original atoms from a substructure search:
> 
> ```
> >>> m = Chem.MolFromSmiles('CCOCC')
> >>> for atom in m.GetAtoms():
> ...     atom.SetIntProp("_atidx",atom.GetIdx())
> ... 
> >>> submol = Chem.PathToSubmol(m,[1,2])
> >>> submol.GetAtomWithIdx(0).GetPropsAsDict()
> {'__computedProps': <rdkit.rdBase._vectNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE object at 0x7effa7691db0>, '_atidx': 1}
> >>> match = submol.GetSubstructMatch(Chem.MolFromSmarts('CO'))
> >>> list(match)
> [0, 1]
> >>> originalIndices = [submol.GetAtomWithIdx(x).GetIntProp('_atidx') for x in match]
> >>> originalIndices
> [1, 2]
> ```

I agree. Due to the RDKit documentation, receiving the original indices due to this implementation is a hardcore. I believe using atomMap hyper-parameters would be a easier step
