### ISSUE TITLE
Stereocenter is not preserved after canonicalization of a tautomer

### ISSUE THREAD

**Issue by ostroganov** [rdkit/rdkit#3672]
I'm using the following code to canonicalize SMILES: 
```
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize
m = Chem.MolFromSmiles('[H][C@]1(N2CCC3=C(C(N)=O)N(CC4=CC=CC=C4)N=C3C2=O)COC2=C(C=CC(Cl)=C2)N(C)C1=O')
enumerator = rdMolStandardize.TautomerEnumerator()
m = enumerator.Canonicalize(m)
print (Chem.MolToSmiles(m))
```
The code produces following result: 
`CN1C(=O)C(N2CCc3c(nn(Cc4ccccc4)c3C(N)=O)C2=O)COc2cc(Cl)ccc21`

Input molecule contains stereo center, but there is no stereo center in output SMILES. This is incorrect because canonicalization should preserve stereochemistry. 

![image](https://user-images.githubusercontent.com/7399170/103182059-ecaec580-485c-11eb-9d10-8233381cd429.png)

*Configuration:*
 - RDKit version: 2020.09.3
 - OS: Windows 10
 - Python version: 3.9.1
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by ptosco** [comment]
@ostroganov Hi Oleg, by default `TautomerEnumerator` strips stereochemistry from stereocenters involved in potential tautomeric shifts. If you wish to preserve stereochemistry you may do the following:

```
params = rdMolStandardize.CleanupParameters()
params. tautomerRemoveSp3Stereo = False
enumerator = rdMolStandardize.TautomerEnumerator(params)
```

This is documented here:
http://rdkit.org/docs/source/rdkit.Chem.MolStandardize.rdMolStandardize.html?highlight=removesp3#rdkit.Chem.MolStandardize.rdMolStandardize.CleanupParameters.tautomerRemoveSp3Stereo
