### ISSUE TITLE
Creating a method to calculate Aromatic Proportion of a compound.

### ISSUE THREAD

**Issue by msudhanshu10** [rdkit/rdkit#3680]
**Is your feature request related to a problem? Please describe.**
This molecular descriptor will add a feature in the Descriptor class- 'AromaticProportion'. This feature is not inbuilt in rdkit. We have to compute it manually. I came across this feature while I was doing computation cheminformatics analysis in Delaney's research paper which includes the calculation of solubility of molecules.

**Describe the solution you'd like**
AromaticProportion= no of aromatic atoms in a molecule/ no of heavy atoms in a molecule.
no of aromatic atoms and heavy atoms in a molecule can be calculated separately in a molecule with existing methods.

**Comment by msudhanshu10** [comment]
I am taking this issue.

**Comment by IchiruTake** [comment]
> **Is your feature request related to a problem? Please describe.**
> This molecular descriptor will add a feature in the Descriptor class- 'AromaticProportion'. This feature is not inbuilt in rdkit. We have to compute it manually. I came across this feature while I was doing computation cheminformatics analysis in Delaney's research paper which includes the calculation of solubility of molecules.
> 
> **Describe the solution you'd like**
> AromaticProportion= no of aromatic atoms in a molecule/ no of heavy atoms in a molecule.
> no of aromatic atoms and heavy atoms in a molecule can be calculated separately in a molecule with existing methods.

I am not sure is this whether this can be a solution 
```
mol = AddHs(MolFromSmiles('c1cccc1'))
AromaticProportion = len(list(mol.GetAromaticAtoms())) / Chem.GetNumHeavyAtoms(mol)
```

In case of you want to build which atomic number is the boundary to identify whether to be a heavy atom
```
n = int(input('Select atomic number boundary'))
count: int = 0
for atom in mol.GetAtoms():
      if atom.GetAtomicNum >= n:
           count += 1
AromaticProportion = len(list(mol.GetAromaticAtoms())) / count
```
