### ISSUE TITLE
MCS: extend completeRingsOnly to cover atoms as well

### ISSUE THREAD

**Issue by driesvr** [rdkit/rdkit#3693]
Hi everyone,

I'm having some issues with the MCS code. It seems to returns a partial ring, even when the option completeRingsOnly = True is set. For instance in this set of molecules:
```
m1 = Chem.MolFromSmiles('Nc1ccc(O)cc1c1ccc2ccccc2c1')
m2 = Chem.MolFromSmiles('Oc1cnc(NC2CCC2)c(c1)c1ccc2ccccc2c1')
```

I would expect the MCS with `completeRingsOnly = True` to match only the naphtalene ring, but it returns the napthalene plus the attachment point of the next ring: `'[#6]-&!@[#6]1:&@[#6]:&@[#6]:&@[#6]2:&@[#6](:&@[#6]:&@1):&@[#6]:&@[#6]:&@[#6]:&@[#6]:&@2'`. 

![image](https://user-images.githubusercontent.com/10437563/103635736-3c6e4a80-4f49-11eb-920b-49698f095dcd.png)

I've found a few older issues that reference this same problem, but those indicated it has since been fixed in PR#2421?
I'm currently using rdkit 2020.09.3. Is this the expected behaviour, and is there any way to force rdkit to omit that attachment point?

Thank you!

**Comment by greglandrum** [comment]
The behavior reported by @driesvr is actually intentional (though confusing): the `completeRingsOnly` option applies at the bond level, not the atom level.
The changes @ptosco has made in #3695 add a new option to allow `completeRingsOnly` at the atomic level too.

**Comment by driesvr** [comment]
Thanks @greglandrum and @ptosco! Looks like this change will perfectly address my usecase.
