### ISSUE TITLE
Importing rdkit.Chem still loads Qt libraries into memory

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#3694]
Even after applying #3659 rdmolops.so is still linking to Qt libraries, at least on Linux.

It seems like these are transitive dependencies brought in by MolDraw2D: even if rdmolops itself doesn't make use of Qt, it defines `MolToSVG()`, which adds a dependency on MolDraw2D, so that it gets loaded whenever rdmolops is, and this also brings in the Qt libraries. As mentioned in #3658, this causes problems in systems where Qt is not available.

The best way I can think of to solve this issue is moving `MolToSVG()` to `rdkit.Chem.Draw`. I don't love that, because all the "MolTo..." functions are collected together in `rdkit.Chem`, but it would solve the issue, and since SVG is not really a structure file format (i.e. we cannot import a molecule back from it, there's no "`MolFromSVG()`"), it kind of makes sense to put it together with the rest of the drawing stuff.

Does that make sense?

**Comment by greglandrum** [comment]
Yeah, I'm fine with this being moved to rdMolDraw2D. It shouldn't have ended up in MolOps in the first place.
