### ISSUE TITLE
Set 'bondLineWidth' has no effect on wedged bonds

### ISSUE THREAD

**Issue by mily33** [rdkit/rdkit#3699]
**Describe the bug**
Set the property 'bondLineWidth' for rdMolDraw2D.MolDrawOptions() has no effect on the bond '[C@H]'. 

**To Reproduce**
[code](https://gist.github.com/mily33/29a192395f083dfd0feda908acfe60dd)

**Expected behavior**
I want to draw molecules with some random settings to perform data augmentation. However, I find that setting the bondLineWidth has no effect on 'C[@ H]' in 2020.09.01 version.  It work in 2020.03 version. However, in version 2020.03, setting the atomlabel property did not work.   

**Screenshots**
run the code with rdkit 2020.09 results in :
![image](https://user-images.githubusercontent.com/25098671/103847529-6fe0de80-50db-11eb-8488-f42043681fc1.png)

run the code with rdkit 2020.03 results in :
![version 2020.03](https://user-images.githubusercontent.com/25098671/103847223-a8cc8380-50da-11eb-9a2c-cf73f8044bb1.png)

**Configuration (please complete the following information):**
 - RDKit version: 2020.09 / 2020.03
 - OS: Ubuntu 20.04
 - Python version (if relevant): python3.6
 - conda install -c rdkit rdkit

**Additional context**
I wonder if the 'ChemDraw'-like styles can be added as some default settings. 
![image](https://user-images.githubusercontent.com/25098671/103845608-5c337900-50d7-11eb-96db-2da91bdcd466.png)
![image](https://user-images.githubusercontent.com/25098671/103845632-66557780-50d7-11eb-9e0c-fb6f457b4b1e.png)

**Comment by greglandrum** [comment]
Confirmed that changing the bond line width does not change dashed bonds rendering.
I will see if there's a reasonable solution to this

**Comment by HBioquant** [comment]
So, are there any solutions to this problem? I have the same demand as @mily33.

**Comment by greglandrum** [comment]
As of v2024.03.1 this is no longer a problem. Here's a rendering with the default linewidth (2):
![image](https://github.com/rdkit/rdkit/assets/540511/e1f6e126-fdde-45b3-8f12-59bc58d44d2a)

and with linewidth = 6
![image](https://github.com/rdkit/rdkit/assets/540511/17254b78-8881-4f9f-9be9-0b5ee7c35908)
