### ISSUE TITLE
Double deallocation in YAeHMOP driver function

### ISSUE THREAD

**Issue by SPKorhonen** [rdkit/rdkit#3713]
**Describe the bug**
Within runMol in EHTTools.cpp local pointer parmFilePtr is initialized from buffer pointer of std::string pfName. Unfortunately within fill_atomic_parms it is released via free() leading to double deallocation and crash.

One possible fix would be to allocate buffer into parmFilePtr via malloc and copy the content of pfName into it and pass that to fill_atomic_parms. This fixes the problem. It could submit a PR to this effect if desired.

**To Reproduce**
Compile RDKit with RDK_BUILD_YAEHMOP_SUPPORT=ON and tests testEHTLib1 and pyEHTTools fail due to segmentation fault.

**Expected behavior**
Tests testEHTLib1 and pyEHTTools pass.

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.3
 - OS: Windows 10 X64
 - Python version (if relevant): Not Python related
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from? N/A
 - If you are not using conda: Build from souce

**Comment by greglandrum** [comment]
HI @SPKorhonen : I believe this is actually a yaehmop bug caused by a recent cleanup PR and that we should fix it there.
I will take a look at it

**Comment by greglandrum** [comment]
This was fixed here: https://github.com/greglandrum/yaehmop/pull/34
