### ISSUE TITLE
Sanitize/UpdatePropertyCache issue with Cl, Br valences

### ISSUE THREAD

**Issue by bdw2292** [rdkit/rdkit#3715]
**Describe the bug**
1) If I have no charges in the input file below, and the removeHs flag turned on, then I do not need to have sanitize=False flag turned on. However, if I add charges (as there should be, to Cl and Br of -1), then I am required to use sanitize=False when creating mol object, otherwise the mol object is returned as None.
2) If I use sanitize=False, with -1 on Cl, the valence is correct. However, if I then wish to do SMART string matching, then I need to call mol.UpdatePropertyCache(), which then presumably recomputes the valencies, but then it thinks valence of Cl is 2! Even though its only bonded to 1 atom and its single bond. rdkit will crash with this as soon as UpdatePropertyCache() is used. 

[test.mol.txt](https://github.com/rdkit/rdkit/files/5798263/test.mol.txt)

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.
 m=Chem.MolFromMolFile(self.molstructfnamemol,removeHs=False)

 m.UpdatePropertyCache()

**Expected behavior**
I expect no crashes and valence of 1 for Cl after UpdatePropertyCache is called.

**Comment by greglandrum** [comment]
Why do you think there should be a negative charge on the Cl atom?
In that mol file it's forming one bond to a phenyl ring:
![image](https://user-images.githubusercontent.com/540511/104321268-b1122d80-54e3-11eb-9c0e-1ccbb27d6281.png)
Typically a Cl atom which forms a single bond should be neutral

**Comment by bdw2292** [comment]
Right my bad, please close.
