### ISSUE TITLE
No stereo on trigonal pyramids with attached H atoms

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#3717]
RDkit supports trigonal pyramid chirality:

```
# https://cipvalidationsuite.github.io/ValidationSuite/?search=VS147
In [3]: Chem.MolToSmiles(Chem.MolFromSmiles('O=[S@](CC)C'))                                                                                                                         
Out[3]: 'CC[S@](C)=O'
```

If I remember correctly, the IUPAC rule for these chiral centers says that they are resolved as if they were tetrahedral centers, assuming a fourth "ghost atom" (with priority lower than H atoms) in the opposite position of the three substituents.

So, one would assume that replacing one of the substituents in the previous example with a H atom we would get a similar result, but instead the stereochemistry is stripped away:

```
In [4]: Chem.MolToSmiles(Chem.MolFromSmiles('O=[S@](CC)[H]'))                                                                                                                       
Out[4]: 'CC[SH]=O'

In [5]: Chem.MolToSmiles(Chem.MolFromSmiles('O=[S@H]CC'))                                                                                                                           
Out[5]: 'CC[SH]=O'
```
This is kind of an edge case in which a central atom with 2 heavy atom plus one Hydrogen neighbors should actually be marked as chiral.

Or is my assumption wrong, and this should not be considered a stereo center?

**Comment by greglandrum** [comment]
IUPAC does not great these as stereogenic. Here's the relevant table from the InChI technical manual:
![image](https://user-images.githubusercontent.com/540511/105799993-12cba080-5f96-11eb-8e17-c39f079adf5b.png)

Given that there's actually a reason for this - these structures can invert because the H can tunnel between the two different positions - I think this IUPAC convention makes sense and we should stick with it.

**Comment by greglandrum** [comment]
@ricrogz : if you agree with the argument about what InChI supports, shall we go ahead and close this and #3754?

**Comment by ricrogz** [comment]
Yes, it makes sense. I'm closing this issue and the associated PR.
