### ISSUE TITLE
How can i calculate logD rdkit?

### ISSUE THREAD

**Issue by cgh2797** [rdkit/rdkit#3718]
How can i calculate logD in rdkit?

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Comment by UnixJunkie** [comment]
Probably not possible because RdKit does not have a pKa model (logD is logP at a given pH; you would need a pKa model to protonate the molecule correctly for the given pH).
