### ISSUE TITLE
Question: what are the criteria to check SMILES validity?

### ISSUE THREAD

**Issue by Hyunseung-Kim** [rdkit/rdkit#3728]
Hello.

Where can I find out the criteria that RDKit determines whether SMILES strings are valid or not?

I think some of the criteria are:
1. valency check
2. ring is closed or not

Is there any other criteria? or Is there any website that informs about it (RDKit)?

**Comment by bp-kelley** [comment]
A valid smiles string and valid chemistry are two different concepts.

The rdkit breaks this into two parts, parsing and sanitization.

For parsing, rdkit uses a grammar defined in the SmilesParse module:

https://github.com/rdkit/rdkit/tree/master/Code/GraphMol/SmilesParse

This is pretty dense, you may prefer the opensmiles specification ( we don’t follow this exactly but it’s close )

http://opensmiles.org/opensmiles.html

A fairly detailed explanation of sanitization is here:

https://www.rdkit.org/docs/RDKit_Book.html

----
Brian Kelley

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.
