### ISSUE TITLE
Make testConcurrentQueue run faster

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#3739]
**Is your feature request related to a problem? Please describe.**

The 202009.1 test suite seems to run pretty fast now (<1s), except for test #5, which takes a lot of time and does not seem to do much:

```
        Start   5: testConcurrentQueue

5/179 Test   #5: testConcurrentQueue ....................   Passed  507.61 sec
```

**Describe the solution you'd like**

If possible, that test should run in a few seconds at most as well. Or is the above run-time an indication of a problem?

**Comment by greglandrum** [comment]
@mbanck I think that long runtime indicates a problem. For me that test runs in a reasonable amount of time:
```
(base) glandrum@Badger:/scratch/RDKit_git/build$ ctest -R testConcur
Test project /scratch/RDKit_git/build
    Start 10: testConcurrentQueue
1/1 Test #10: testConcurrentQueue ..............   Passed    7.76 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   7.78 sec
```

**Comment by mbanck** [comment]
What I noticed is that it just sits there for (tens of) minutes, not consuming any cpu times, probably waiting (in vain?) for something
