### ISSUE TITLE
generateDepictionMatching2DStructure clears all mol conformers

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#3745]
The C++ function `generateDepictionMatching2DStructure` calls `compute2DCoords` with `clearConfs` set to true, and `generateDepictionMatching3DStructure` likewise calls `compute2DCoordsMimicDistMat` with `clearConfs` set to true.

I think both of these functions could take a `clearConfs` option and pass it on, rather than hardcoding `true`.  The default value would be `true`, so this would be backward compatible.  

If this makes sense I can file a pull request.

**Comment by greglandrum** [comment]
@jasondbiggs : I've not encountered the need for this, but I don't see any reason not to add that option.
