### ISSUE TITLE
RGD with RGroupMatching.GA leaks memory and takes too long

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#3746]
**Describe the bug**
RGD with RGroupMatching.GA leaks memory and takes too long for just 2 cores and 2 molecules.
Monitoring the `python` process with `top` shows that memory keeps increasing until the process is eventually killed.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem.rdRGroupDecomposition import RGroupDecompositionParameters, RGroupDecomposition, RGroupMatching

core1 = Chem.MolFromSmiles('[cH:1]1[cH:2][cH:3]ccc1')
core2 = Chem.MolFromSmiles('[cH:3]1[cH:2][cH:1]cnc1')

mol1 = Chem.MolFromSmiles("c1(CO)cc(CN)ccc1")
mol2 = Chem.MolFromSmiles("c1(CO)cc(CN)cnc1")

ps = RGroupDecompositionParameters()
ps.removeHydrogensPostMatch = True
ps.onlyMatchAtRGroups = True
ps.matchingStrategy = RGroupMatching.GA
rgd = RGroupDecomposition([core1, core2], ps)

rgd.Add(mol1)
rgd.Add(mol2)
rgd.Process()
```

**Expected behavior**
I would expect the calculation to end very quickly.

**Configuration (please complete the following information):**
 - RDKit version: compiled from `master`
 - OS: CentOS 7
 - Python version (if relevant): Python 3.6
 - Are you using conda? no
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? compiled from `master`

**Comment by jones-gareth** [comment]
@ptosco I can take care of this bug, but (unless it is urgent) I will wait until the my current rgroup PR is merged.

Something is clearly wrong as the GA is supposed to delegate to exhaustive search for such a trivial case.  I know why it hangs (it can't build a population), but I don't know where the memory leak comes from.

**Comment by ptosco** [comment]
@jones-gareth Not urgent at all! I just noticed that while I was looking at another bug.
