### ISSUE TITLE
The index returned from GetSubstructMatch  can not be used in Chem.PathToSubmol

### ISSUE THREAD

**Issue by ZhitaoTian** [rdkit/rdkit#3757]
**Configuration:**

- RDKit Version: 2020.03.4
- Operating system: Windows 10
- Python version (if relevant): 3.7

**Description:**

GetSubstructMatch return an index that out of the range of the index of the molecular

```
[In]
mols=[Chem.MolFromSmiles("NCCCNCCCCNCCCN"),Chem.MolFromSmiles("CC(O)=NCCCCNCCCN"),Chem.MolFromSmiles("CC(O)=NCCCNCCCCNCCCN")]
res=rdFMCS.FindMCS(mols,bondCompare=rdFMCS.BondCompare.CompareOrderExact)
env2=mols[1].GetSubstructMatch(Chem.MolFromSmarts(res.smartsString))
map = {}
Chem.PathToSubmol(mols[1],env2,atomMap=map)

[Out]
Traceback (most recent call last):


  File "<ipython-input-176-fa85a8b9bb05>", line 1, in <module>
    Chem.PathToSubmol(mols[1],env2,atomMap=map)

RuntimeError: Range Error
	idx
	Violation occurred on line 309 in file Code\GraphMol\ROMol.cpp
	Failed Expression: 12 < 12
	RDKIT: 2020.03.4
	BOOST: 1_72
```

**Comment by mwojcikowski** [comment]
Hi @ZhitaoTian,
This is quite common misconception - `Chem.PathToSubmol` requires bond indices, while substructure matches are atom indices. Your molecule has more atoms than it has bonds, which is why there is a range error.

**Comment by ZhitaoTian** [comment]
Hi@mwojcikowski 
Thanks a lot! If I want to get the substructure (or a smiles string) from substructure matches, what I can do.

**Comment by mwojcikowski** [comment]
Checkout `Chem.MolFragmentToSmiles(...)`. It has `atomsToUse` parameter that will most probably do what you need.
https://www.rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.MolFragmentToSmiles

**Comment by ZhitaoTian** [comment]
Thanks so much! It's what I need.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
