### ISSUE TITLE
Add a delimiter argument to Chem.MolFromSmiles for parsing multiple SMILES in one string

### ISSUE THREAD

**Issue by ghiander** [rdkit/rdkit#3761]
Hi all,

I am not sure whether this should be considered a feature enhancement or a bug. Something I have recently noticed is that when creating a molecule from a string such as "c1ccccc1N\nAAA\nCCC", the object is created successfully for the molecule c1ccccc1N and the rest of the string is ignored. In the case of a SMILES string containing multiple molecules, I think it could be useful to add functionality to enable the processing of delimited structures. Also, the same functionality could be used to throw an error when the input SMILES contains escape characters (e.g. newline) which are not supposed to be there. I appreciate that some logic could be built for cleaning up the SMILES that have to be processed, but I think that RDKit should be able to figure out that something is wrong with an input such as that I reported above.

What are your thoughts?

`import rdkit.Chem as Chem`
`str1 = "c1ccccc1N\nAAA\nCCC"`
`m = Chem.MolFromSmiles(str1, sanitize=False)`
`mol1 = Chem.MolToSmiles(m)`
`mol1`

**Comment by greglandrum** [comment]
Hi @ghiander, 
By default the RDKit is permissive and ignores extra white space at the end of SMILES strings (unless you are providing CXSMILES or asking for it to also parse the molecule name).
I'd be fine with adding a "strict parsing" option which raises an error if any whitespace comes after the SMILES, but I'm wondering if that's generally useful.
If you are interested in implementing this yourself and are working in Python, it's quite easy to search the SMILES string for the regular expression `\W`. If that matches, then you know that the string contains white space and can reject it. The SMILES parser should take care of other non-whitespace characters.

**Comment by ghiander** [comment]
Hi @greglandrum,

I would like to become a contributor to RDKit at some point rather than just raising issues and wait for others to fix them. I will set up the right environment when I can, and see whether I come up with something functional.

**Comment by greglandrum** [comment]
Hi @ghiander 
 
> I would like to become a contributor to RDKit at some point rather than just raising issues and wait for others to fix them. I will set up the right environment when I can, and see whether I come up with something functional.

Makes sense. It's definitely almost always going to be faster to "scratch your own itch" and we always welcome new contributors! :-)
