### ISSUE TITLE
GetNumConformers() fails to generate conformers on bigger molecules

### ISSUE THREAD

**Issue by mieczyslaw** [rdkit/rdkit#3764]
**Describe the bug**
When calling GetNumConformers() on bigger molecules loaded from PDB (repaired in Maestro so CONECT records are correct), no conformers are generated. This happens to two types of molecules out of 11 I am testing.

**To Reproduce**
I am attaching two PDBs to illustrate the issue (with *txt extension so GitHub accepts it): 
[structure.pdb.txt](https://github.com/rdkit/rdkit/files/5879238/structure.pdb.txt)
[structure2.pdb.txt](https://github.com/rdkit/rdkit/files/5879239/structure2.pdb.txt)

Call the following simple code with the molecule pdb.txt file as a parameter (or hardcode the names):
```
import sys
from rdkit import Chem
from rdkit.Chem import AllChem

rdmol = Chem.MolFromPDBFile(sys.argv[1], removeHs=False)
cids = AllChem.EmbedMultipleConfs(rdmol, numConfs=1)
confs = rdmol.GetNumConformers()

print(cids, confs)
```

**Expected behavior**
One conformer should be generated (`confs` variable should be 1).

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.3        py37h400b6df_0    conda-forge
 - OS: Linux RedHat
 - Python version (if relevant): 3.7.8
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**
This affects other tools using RDKit like OpenFF (see discussion here: https://github.com/openforcefield/openff-toolkit/issues/822).

**Comment by greglandrum** [comment]
When working with larger molecules it is generally a good idea to use the `useRandomCoords` option. This can be more robust for handling large molecules than the standard metric matrix embedding methodology.

BTW, if you only want to generate a single conformation you can just use `EmbedMolecule`: http://www.rdkit.org/docs/source/rdkit.Chem.rdDistGeom.html?highlight=embed%20molecule#rdkit.Chem.rdDistGeom.EmbedMolecule

**Comment by mieczyslaw** [comment]
Thanks @greglandrum ! `useRandomCoords=True` seems to help!

Do I understand correctly that `useRandomCoords` somehow translates&rotates so the coordinates are different comparing with the input PDB, but the conformer is generated based on input topology?

**Comment by greglandrum** [comment]
Not exactly. The original coordinates are not used in any of the RDKit's conformation generation approaches.

`useRandomCoords` replaces steps 3 and 4 described here:
http://www.rdkit.org/docs/GettingStartedInPython.html#working-with-3d-molecules
Instead of picking a particular distance matrix and embedding it, the `useRandomCoords` option picks a random set of coordinates for the atoms and then minimizes their positions using the "distance geometry force field" (step 5 on the page above).

**Comment by mieczyslaw** [comment]
Thanks @greglandrum!

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
