### ISSUE TITLE
Incorrect stereochemistry assignment for P/As atoms

### ISSUE THREAD

**Issue by IvanChernyshov** [rdkit/rdkit#3773]
RDKit marks non-chiral P/As atoms as unassigned TH stereocenters if they have 2/3 hydrogens:

```python
from rdkit import Chem
# 3 Hs
print(Chem.FindMolChiralCenters(Chem.MolFromSmiles('[P+]C'), includeUnassigned = True))
> [(0, '?')]
# 2 Hs
print(Chem.FindMolChiralCenters(Chem.MolFromSmiles('[P+](CC)C'), includeUnassigned = True))
> [(0, '?')]
# dative bond 3Hs
print(Chem.FindMolChiralCenters(Chem.MolFromSmiles('P->[Cu+]'), includeUnassigned = True))
> [(0, '?')]
# dative bond 2 Hs
print(Chem.FindMolChiralCenters(Chem.MolFromSmiles('P(C)->[Cu+]'), includeUnassigned = True))
> [(0, '?')]
```

The bug is observed for hydrogens only, for other substituents everything works well. Boron is also OK:

```python
print(Chem.FindMolChiralCenters(Chem.MolFromSmiles('[BH3-][OH2+]'), includeUnassigned = True))
> []
```

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
