### ISSUE TITLE
Suggestion of Custom Splitting and Nuetralisation

### ISSUE THREAD

**Issue by VIGNESHinZONE** [rdkit/rdkit#3775]
Im working a Scaffold based project and it involves a lot of custom bond splitting.

I currently have a molecule " *C1CC(=O)c2ccccc2C1 "

![image](https://user-images.githubusercontent.com/45672459/106399176-1c915000-643d-11eb-970a-0073598400ae.png)

I tried filling that * location with a Hydrogen atom in order to complete the valency using this piece of code
```
>> mol.GetAtomWithIdx(n_at-1).SetAtomicNum(1)
```
![image](https://user-images.githubusercontent.com/45672459/106399236-6f6b0780-643d-11eb-8649-4bb2006cdbcd.png)

You can see that an extra Hydrogen atom is added but for some reason when I convert it to smile string it explicitly shows the Hydrogen atom - "[H]C1CC(=O)c2ccccc2C1"

Are there ways to neutralize or complete the valency of a broken bond with trivial molecules like Hydrogen?

**Comment by ptosco** [comment]
@VIGNESHinZONE That works. You can do something like:
```
for a in mol.GetAtoms():
    if (a.GetAtomicNum() == 0):
        a.SetAtomicNum(1)
        a.SetIsAromatic(False)
        a.SetIsotope(0)
```
(depending on the method you use to cleave bonds aromatic flags or isotopic labels can be left on the dummy atoms, this is why I reset those)
Finally, convert the hydrogens in the molecule graph to implicit:
```
mol = Chem.RemoveHs(mol)
```
and you'll have accomplished your goal.

**Comment by VIGNESHinZONE** [comment]
Oh great, thanks a lot!
