### ISSUE TITLE
Regression in dihedral constraints

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#3781]
In this code snippet I just use an added torsion constraint with a very high force constant to get certain dihedral angle.  It works well in version "2019.03.3" but gives very bad results in "2020.09.1".

```
m = Chem.rdmolfiles.MolFromMolFile('/Users/jasonb/butane.mol',removeHs = False)
mp = AllChem.MMFFGetMoleculeProperties(m)
ff = AllChem.MMFFGetMoleculeForceField(m, mp)
ff.MMFFAddTorsionConstraint(0,1,2,3, False, -180, -180, 10000.0)
ff.Minimize()
Chem.rdmolfiles.MolToMolFile(m,'/Users/jasonb/butane_180.mol')
```
Starting with the attached MOL file, rdkit version "2019.03.3" gives the top result, while version "2020.09.1" gives the bottom version:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/16337306/106640656-ec84a280-654b-11eb-9994-c477e9f11d67.png">

(can't seem to attach a .mol file, renamed to 'butane.txt')

[butane.txt](https://github.com/rdkit/rdkit/files/5913233/butane.txt)

edit:

To add another example, using the same MOL file and this code
```
m = Chem.rdmolfiles.MolFromMolFile('/Users/jasonb/butane.txt',removeHs = False)
mp = AllChem.MMFFGetMoleculeProperties(m)
globalFF = AllChem.MMFFGetMoleculeForceField(m, mp)
m2 = m;
res = []
for x in range(-180,180,5):
	ff2 = AllChem.MMFFGetMoleculeForceField(m2, mp)
	ff2.MMFFAddTorsionConstraint(0,1,2,3, False, x - .1, x + .1, 100000.0)
	ff2.Minimize()
	res.append(globalFF.CalcEnergy(ff2.Positions()))
res
```
I was previously able to get a nice plot like this,
<img width="307" alt="image" src="https://user-images.githubusercontent.com/16337306/106652423-0ed1ec80-655b-11eb-979c-260176ac21ad.png">
but it now returns a **very different** list

<img width="379" alt="image" src="https://user-images.githubusercontent.com/16337306/106652585-480a5c80-655b-11eb-8024-04a1eae90ade.png">

_Originally posted by @jasondbiggs in https://github.com/rdkit/rdkit/discussions/3780_

**Comment by pschmidtke** [comment]
And I was just about to get crazy with exactly the same issue over here :) And didn't try that with previous rdkit versions ... so could have continued looking for quite some time ;)

**Comment by ptosco** [comment]
Sorry, I haven’t had time to look into this yet, but it’s on my to-do list.

**Comment by pschmidtke** [comment]
It seems MMFF specific, I tested with UFF and it worked "OK", with weird energies on particular angles though

**Comment by jasondbiggs** [comment]
@ptosco Do you know what the change was that is behind this?  If it isn't something that requires a deep knowledge of the forcefield code I could take a look (even if only on our private fork).  

I am upgrading the version of rdkit we use but might be blocked because of this issue.  We had made a featured example out of the above butane torsion code so I can't break it.

**Comment by ptosco** [comment]
Hi Jason,  sorry, I haven't had time to look into this issue. The PR that broke dihedral restraints is #2732. I am not going to have time at least for the next couple of days. If you have time and wish to take a look, please go ahead. I don't expect it to be a very difficult fix; I just couldn't find the time yet.

**Comment by greglandrum** [comment]
@jasondbiggs I can also take a look tomorrow if you’d rather not deal with this

**Comment by jasondbiggs** [comment]
It isn't a huge rush, my time frame for upgrading rdkit is weeks not days.  

I like solving puzzles so if the issue is localized to the functions in that PR I might be able to find it, and will take a look.  If it also piques your curiosity and you find the issue before I do then that is no loss.

Best
Jason

**Comment by jasondbiggs** [comment]
@greglandrum I can confirm that reverting the above PR fixes the issue I was having, but I was wrong to think I could easily see what the problem is.  Nothing obvious like a mod-180 or degree/radian conversion in what I looked at.

**Comment by greglandrum** [comment]
Information collected while trying to track this down:
1. Decreasing the force constant on the torsion constraint from 10000 to 100 results in reasonable results
2. Minimizing with a force constant of 100 and then adding a constraint with force constant 10000 doesn't destroy the structure
3. Setting the target value of the constraint to -150 results in a structure with a torsion angle of -180 which has really high energy
4. Setting the target value to 0 gives a torsion of 0
5. Setting the value to -90 gives a torsion of 0 and a really high energy
<to be continued>

**Comment by jasondbiggs** [comment]
Thanks @ptosco  and @greglandrum for fixing this!
