### ISSUE TITLE
Ugly fixed-width atom coordinates in V3000 mol blocks

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3785]
A consequence of the fix for #3597 is that we now output atom coordinates to V3000 mol blocks with a fixed number of decimal points. So we get things like this:
```
M  V30 1 C -2.812500 1.919600 0.000000 0
M  V30 2 C -2.098000 2.332100 0.000100 0
```
I think that's pretty horrible and would prefer trimming off the trailing zeros:
```
M  V30 1 C -2.8125 1.9196 0. 0
M  V30 2 C -2.098 2.3321 0.0001 0
```
Before I make the change I wanted to check and see if others have opinions on this.

@mark-cresset perhaps? You filed the original bug report.

**Comment by mark-cresset** [comment]
I have no problem with trimming the results as you suggest. It was only the scientific notation that was causing problems.

Regards,
Mark
