### ISSUE TITLE
[feature request] virtualenv installation method

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#3788]
Dear rdkiters,

It would be nice if virtualenv is supported, for people who are allergic to conda/miniconda...

Regards,
F.

**Comment by greglandrum** [comment]
Doesn't that require that you use pip to install packages?

**Comment by UnixJunkie** [comment]
Maybe, in which case the pip installer feature request would be a prerequisite (https://github.com/rdkit/rdkit/issues/1812)
of this one

**Comment by greglandrum** [comment]
Since I believe that this is related to PyPi, I'm going to link to the blog post explaining why this is a problem:
http://rdkit.blogspot.com/2019/11/why-rdkit-isnt-available-on-pypi.html
and close this issue.

**Comment by UnixJunkie** [comment]
Ok, then maybe https://github.com/rdkit/rdkit/issues/1812 also can (sadly) be closed.

**Comment by greglandrum** [comment]
I disagree. It might be possible to solve #1812, and maybe someone will manage to do that at some point.
Once it is solved, if it doesn't automatically become true that you can use the rdkit in a virtualenv, then this one can either be reopened or a new issue opened.
