### ISSUE TITLE
Bug in the edges of the rmol associated to WW7 from the PDB

### ISSUE THREAD

**Issue by pkrezel** [rdkit/rdkit#3801]
**Describe the bug**
RDKit doesn't give the good edges for the  molecule WW7 from PDB.

**To Reproduce**
smiles = 'c1cc2c(cccc2Cl)c(c1)S(=O)(=O)NCCCCCCN'
mol = Chem.MolFromSmiles(smiles, sanitize=True)

![image](https://user-images.githubusercontent.com/22557979/107614798-4a4f7380-6c4b-11eb-9b46-51d50bb8c4e7.png)

the representation is correct but if we see the graph associated to mol we get:

![image](https://user-images.githubusercontent.com/22557979/107615196-06a93980-6c4c-11eb-9bb5-33f58375dccc.png)

**Configuration (please complete the following information):**
 - RDKit version: 2020.03.3.0
 - OS: Centos 7
 - Python version: 3.6.8
 - Are you using conda?Yes
 - If you are using conda, which channel did you install the rdkit from? rdkit
 - If you are not using conda: how did you install the RDKit?

**Comment by greglandrum** [comment]
I don't understand what you think the RDKit bug is here.

**Comment by pkrezel** [comment]
The problem comes from the edges obtained with mol.GetBonds().
There is a bond between 2 and 4.

**Comment by greglandrum** [comment]
I suspect you are misinterpreting that drawing. Whatever tool you are using to layout and draw the graph has set things up so that the bond between atoms 2 and 1 is drawn through atom 4.

**Comment by pkrezel** [comment]
You are right. Sorry,

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
