### ISSUE TITLE
installation via conda is installing an older version of rdkit (rdkit 2017.09.1)

### ISSUE THREAD

**Issue by ErikCVik** [rdkit/rdkit#3802]
I have rdkit installed but I noticed some functions were unavailable to me. like DrawMorganBits

when I try to use conda to activate a new environment via 
conda create -c rdkit -n my-rdkit-env2 rdkit
I notice the rdkit version is still from 2017

any suggestions on what I should do? can I just paste the newer code into the anaconda/rdkit package?

I am unsure of how to get conda to recognize a newer version of rdkit

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.

**Comment by ErikCVik** [comment]
I dont know how to reopen an issue

**Comment by greglandrum** [comment]
you can just create a new one too, then the template is there again.
