### ISSUE TITLE
MolFromSmiles('[He]') produces a diradical helium atom

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#3805]
**Describe the bug**
Creating a molecule from the smiles string "[He]" produces a molecule with one helium atom and two unpaired electrons.  This molecule is an outlier, and not very useful, but it was reported by a user.
```
In[7]:=
m = MolFromSmiles('[He]')
m.GetAtomWithIdx(0).GetNumRadicalElectrons()

Out[7]= 2
```
This is a bug for me because I take the molecule produced from the smiles string, take out the atom/bond information to create our internal Molecule object, which now has 2 unpaired electrons on the helium.  Then if I try to recreate the rdkit molecule from the atom information it fails sanitization (pardon the switch from python to c++):
```
  auto nm = std::make_shared<RDKit::RWMol>();
  auto atom = new RDKit::Atom(2);
  atom->setNumRadicalElectrons(2);
  nm->addAtom(atom, true, true);

  RDKit::MolOps::sanitizeMol(*nm); // "Explicit valence for atom # 0 He greater than permitted"
```
The from-SMILES molecule also has `SP` hybridization, but setting that doesn't fix the sanitization error.  I don't really want to put in a special case for this (in my code), but I don't see an alternative.

**Comment by greglandrum** [comment]
confirmed. Thanks for the clear and detailed report
