### ISSUE TITLE
MemoryError by repeating AddConformer and RemoveConformer

### ISSUE THREAD

**Issue by k-ujihara** [rdkit/rdkit#3817]
**Describe the bug**
Windows: "RuntimeError: vector<T> too long" or "RuntimeError: Pre-condition Violation" at  line 13 `mol.AddConformer(confs[i * 17 % 9])`.
Linux: "MemoryError" or "Segmentation fault (core dumped)".
This happens irregularly and does not happen before 2020.9.4.

**To Reproduce**
```python
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem

print(rdkit.__version__)
mol = Chem.MolFromSmiles("C#CCN(Cc1cc([O-])ncn1)c1ccccc1Cl")
mol = Chem.AddHs(mol)
AllChem.EmbedMultipleConfs(mol, numConfs=100)

confs = [conf for conf in mol.GetConformers()]
for i in range(10000):
    print("*", end="")
    mol.AddConformer(confs[i * 17 % 9])
    mol.RemoveConformer(list(mol.GetConformers())[45].GetId())
    Chem.MolToSmiles(mol)
```

**Expected behavior**
Ends without error.

**Screenshots**
```
2020.09.4
****************************************************************Traceback (most recent call last):
  File "a.py", line 13, in <module>
    mol.AddConformer(confs[i * 17 % 9])
MemoryError
```

**Configuration:**
 - RDKit version: 2020.09.4
 - OS: Ubuntu 18_04 (built by myself) / Windows (form conda-forge)

**Comment by greglandrum** [comment]
This is clearly a bug, and it's one of those complex object lifetime things, but I don't think it's a super high priority because it's trivial to work around by just copying the molecule before you start adding/removing conformers:
```
mol2 = Chem.Mol(mol)
confs = [conf for conf in mol.GetConformers()]
for i in range(10000):
    print("*", end="")
    mol2.AddConformer(confs[i * 17 % 9])
    mol2.RemoveConformer(list(mol2.GetConformers())[45].GetId())
    Chem.MolToSmiles(mol2)
```

**Comment by kazuyaujihara** [comment]
Thanks @greglandrum !
The workaround you taught is very useful and works for me. 

I suspect that the problem is with `rdkit.Chem.rdchem.Mol` object and `rdkit.Chem.rdchem.Conformer` object pointing to the same address in the below.
```python
from rdkit import Chem
from rdkit.Chem import AllChem

mol = Chem.AddHs(Chem.MolFromSmiles("C1CCCCC1"))
AllChem.EmbedMultipleConfs(mol, numConfs=1)

new_conf = Chem.Conformer(mol.GetConformer())
conf_id = mol.AddConformer(new_conf)
print(new_conf.GetOwningMol())
print(mol.GetConformer(conf_id))
```

**Comment by akaruinw** [comment]
Hi @greglandrum,  I also encountered this problem, and the `rdkit` version is `2021.03.5`.  I am wondering whether this bug has been resolved?

**Comment by greglandrum** [comment]
@akaruinw the bug has not yet been fixed (as mentioned: it's complex), but I did post a workaround. Does that work for you?

**Comment by akaruinw** [comment]
@greglandrum Yes, the workaround is helpful. I want to make the code brief. Anyway, the workaround is also good. Thanks for the prompt reply. : )
