### ISSUE TITLE
OptimizeMolecule and OptimizeMoleculeConfs Argument Bug

### ISSUE THREAD

**Issue by xiaoruiDong** [rdkit/rdkit#3824]
**Describe the bug**
I am trying to use `Chem.rdForceFieldHelpers.OptimizeMolecule` and `OptimizeMoleculeConfs` in Python. However, I keep getting `ArgumentError` when using those functions. An example is provided below (constraint part neglected):

```
# Generate molecule
mol = Chem.MolFromSmiles('CCC[O]')
mol = Chem.AddHs(mol)
Chem.AllChem.EmbedMultipleConfs(mol, numConfs=10)

# Setup forcefield
mp = Chem.rdForceFieldHelpers.MMFFGetMoleculeProperties(mol)
ff = Chem.rdForceFieldHelpers.MMFFGetMoleculeForceField(mol, mp)

# Optimize
Chem.rdForceFieldHelpers.OptimizeMoleculeConfs(mol, ff, numThreads=1, maxIters=200)
```

The error I got is
```
ArgumentError: Python argument types in
    rdkit.Chem.rdForceFieldHelpers.OptimizeMoleculeConfs(Mol, ForceField)
did not match C++ signature:
    OptimizeMoleculeConfs(RDKit::ROMol {lvalue} mol, ForceFields::ForceField {lvalue} ff, int numThreads=1, int maxIters=200)
```

From my naive investigation, `mol`, `numThreads`, and `maxIters` should be good. Then, the assigned `ff` is problematic? I guess that this function is asking for `ForceField` but `ff` is actually `pyForceField`?

**To Reproduce**
You can use the above example to reproduce.

**Expected behavior**
No ArgumentError when using mentioned functions.

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.1
 - OS: Mac OS 11.2
 - Python version (if relevant): 3.7.7
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? rdkit

**Comment by greglandrum** [comment]
@ptosco, it looks like I didn't do a very good job of reviewing #2401, when you added `OptimizeMoleculeConfs()` to the python wrappers: there are no tests for those new python functions and they don't work.
Do you have time for this one or would you prefer that I take it?

**Comment by ptosco** [comment]
@greglandrum I’ll do that.

**Comment by mainguyenanhvu** [comment]
I faced the same issue. Please help me to fix it.

My RDKit version:
```
rdkit                     2024.03.5        py39hc1ff0a3_1    conda-forge
```

**Comment by greglandrum** [comment]
> I faced the same issue. Please help me to fix it.
> 
> My RDKit version:
> 
> ```
> rdkit                     2024.03.5        py39hc1ff0a3_1    conda-forge
> ```

We can't help unless you provide a code snippet showing how to reproduce the problem you saw.

**Comment by mainguyenanhvu** [comment]
My code is that:
```
df.loc[ind, 'ROMol'] = Chem.MolFromSmiles(row[args.smi_column])
df.loc[ind, 'Mol_H'] = Chem.AddHs(df.loc[ind, 'ROMol'])
df.loc[ind, 'Mol_H'] = AllChem.EmbedMolecule(df.loc[ind, 'Mol_H'])
df.loc[ind, 'Mol_H'] = AllChem.UFFOptimizeMolecule(df.loc[ind, 'Mol_H'])
```

With smiles CCCS, the error is:
```
 df.loc[ind, 'Mol_H'] = AllChem.UFFOptimizeMolecule(df.loc[ind, 'Mol_H'])
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdForceFieldHelpers.UFFOptimizeMolecule(int)
did not match C++ signature:
    UFFOptimizeMolecule(RDKit::ROMol {lvalue} self, int maxIters=200, double vdwThresh=10.0, int confId=-1, bool ignoreInterfragInteractions=True)
```

**Comment by greglandrum** [comment]
@mainguyenanhvu The error message:
```
 df.loc[ind, 'Mol_H'] = AllChem.UFFOptimizeMolecule(df.loc[ind, 'Mol_H'])
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdForceFieldHelpers.UFFOptimizeMolecule(int)
did not match C++ signature:
    UFFOptimizeMolecule(RDKit::ROMol {lvalue} self, int maxIters=200, double vdwThresh=10.0, int confId=-1, bool ignoreInterfragInteractions=True)
```
tells you that you are calling the function UFFOptimizeMolecule() with an integer instead of a molecule.
You are using pandas incorrectly, this is not an RDKit issue.

**Comment by mainguyenanhvu** [comment]
I found that I have not to re-assign AllChem.EmbedMolecule to the object, just call it, and also not because of pandas:
```
AllChem.EmbedMolecule(mol)
AllChem.UFFOptimizeMolecule(mol)
df.loc[ind, 'Mol_H'] = mol
```
The problem is solved.

Thank you for your time and consideration.
