### ISSUE TITLE
support system-installed libinchi-1.03 on Debian/Ubuntu

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#3826]
**Is your feature request related to a problem? Please describe.**
On Debian, the rdkit package doesn't have inchi support.
Apparently, Debian will not update the supported inchi version because of some license problems.

**Describe the solution you'd like**
Apparently, being able to compile rdkit using the system-installed libinchi-dev v.1.03
instead of downloading the latest version would solve the problem.

**Describe alternatives you've considered**
Have debian ship the latest inchi version (1.05?)

**Additional context**

To show that inchi is not supported in the system-provided version that ships with Debian/Ubuntu:
```
python3
import rdkit
from rdkit import Chem
rdkit.Chem.INCHI_AVAILABLE
# False
```

**Comment by UnixJunkie** [comment]
Apparently, rdkit master doesn't even build on Ubuntu 20.04:
```
rdkit/Code/GraphMol/FileParsers/MolSGroupWriting.h:24:25: warning: '%3d' directive output may be truncated writing between 3 and 11 bytes into a region of size 4 [-Wformat-truncation=]
   24 |   snprintf(output, 5, " %3d", value);
      |                         ^~~
```

**Comment by UnixJunkie** [comment]
Also, I don't know how to build rdkit using the inchi library present on the system, rather than downloading
the latest version.

**Comment by merkys** [comment]
This issue can be divided into two orthogonal feature requests:

1. Use system-installed libinchi
2. Support both libinchi v1.03 and v1.05

Debian/Ubuntu packages build against system-provided libraries. For example, to build with system-provided rapidjson, rdkit [has to be patched](https://salsa.debian.org/debichem-team/rdkit/-/blob/master/debian/patches/NoDownloads.patch). Such patches are quite common across Debian.

What is more, software in Debian packages must adhere to [Debian Free Software Guidelines (DFSG)](https://www.debian.org/social_contract#guidelines), and libinchi is complicated in this regard. Starting with libinchi v1.04, its license has been changed to "IUPAC/InChI-Trust InChI Licence No. 1.0", which seems to forbid modifications thus violating DFSG (see [discussion](https://lists.debian.org/debian-legal/2018/02/msg00026.html)). Since rdkit [fails to build with libinchi v1.03](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964773#8), I have disabled INCHI support in rdkit in Debian. A work-around here would be to support GPL-licensed libinchi v1.03.

**Comment by greglandrum** [comment]
> Apparently, rdkit master doesn't even build on Ubuntu 20.04:
> 
> ```
> rdkit/Code/GraphMol/FileParsers/MolSGroupWriting.h:24:25: warning: '%3d' directive output may be truncated writing between 3 and 11 bytes into a region of size 4 [-Wformat-truncation=]
>    24 |   snprintf(output, 5, " %3d", value);
>       |                         ^~~
> ```

Ubuntu 20.04 is my daily work OS... the RDKit builds fine there.
What you are quoting above is a warning. Did you actually hit an error?

**Comment by greglandrum** [comment]
This is a nice idea in theory, but there is a practical problem:
InChI 1.03 is going to require a different build setup than 1.05. I don't know whether or not the API of the library has changed, but from the error report @merkys links above it looks like it has changed.

I'm not sure how the InChI group feels about people using a decade-out-of-date version of their software and still calling it InChI. But I'm less concerned about that.

If someone else is willing to do the work, I'm always willing to review PRs :-)

**Comment by UnixJunkie** [comment]
Using Scripts/create_deb_packages.sh, I get this one:
```
# Run command: /usr/bin/cmake --build . --target "preinstall"
# Directory: /home/berenger/src/rdkit/build
# Output:
[  0%] Built target catch
[  1%] Built target RDGeneral
[  2%] Built target DataStructs
[  3%] Built target RDGeometryLib
[  4%] Built target RingDecomposerLib
[  7%] Built target GraphMol
[  8%] Built target EigenSolvers
Scanning dependencies of target MolTransforms
[  8%] Building CXX object Code/GraphMol/MolTransforms/CMakeFiles/MolTransforms.dir/MolTransforms.cpp.o
[  8%] Linking CXX shared library ../../../lib/libRDKitMolTransforms.so
[  8%] Built target MolTransforms
[  8%] Built target Alignment
Scanning dependencies of target SubstructMatch
[  8%] Building CXX object Code/GraphMol/Substruct/CMakeFiles/SubstructMatch.dir/SubstructMatch.cpp.o
[  8%] Building CXX object Code/GraphMol/Substruct/CMakeFiles/SubstructMatch.dir/SubstructUtils.cpp.o
[  8%] Linking CXX shared library ../../../lib/libRDKitSubstructMatch.so
[  8%] Built target SubstructMatch
Scanning dependencies of target MolAlign
[  8%] Building CXX object Code/GraphMol/MolAlign/CMakeFiles/MolAlign.dir/AlignMolecules.cpp.o
[  8%] Linking CXX shared library ../../../lib/libRDKitMolAlign.so
[  8%] Built target MolAlign
[  9%] Built target maeparser
[ 10%] Built target coordgen
Scanning dependencies of target Depictor
[ 10%] Building CXX object Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/RDDepictor.cpp.o
[ 10%] Building CXX object Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/EmbeddedFrag.cpp.o
[ 10%] Building CXX object Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/DepictUtils.cpp.o
[ 10%] Linking CXX shared library ../../../lib/libRDKitDepictor.so
[ 10%] Built target Depictor
Scanning dependencies of target SmilesParse
[ 10%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/SmilesParse.cpp.o
[ 10%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/SmilesParseOps.cpp.o
[ 10%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/SmilesWrite.cpp.o
[ 11%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/SmartsWrite.cpp.o
[ 11%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/CXSmilesOps.cpp.o
[ 11%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/smarts.tab.cpp.o
[ 11%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/smiles.tab.cpp.o
[ 11%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/lex.yysmarts.cpp.o
[ 11%] Building CXX object Code/GraphMol/SmilesParse/CMakeFiles/SmilesParse.dir/lex.yysmiles.cpp.o
[ 11%] Linking CXX shared library ../../../lib/libRDKitSmilesParse.so
[ 11%] Built target SmilesParse
Scanning dependencies of target RDInchiLib
[ 11%] Building CXX object External/INCHI-API/CMakeFiles/RDInchiLib.dir/inchi.cpp.o
/home/berenger/src/rdkit/External/INCHI-API/inchi.cpp: In function 'std::string RDKit::MolBlockToInchi(const string&, RDKit::ExtraInchiReturnValues&, const char*)':
/home/berenger/src/rdkit/External/INCHI-API/inchi.cpp:2133:9: error: 'MakeINCHIFromMolfileText' was not declared in this scope
 2133 |         MakeINCHIFromMolfileText(molBlock.c_str(), (char*)options, &output);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [External/INCHI-API/CMakeFiles/RDInchiLib.dir/build.make:63: External/INCHI-API/CMakeFiles/RDInchiLib.dir/inchi.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3871: External/INCHI-API/CMakeFiles/RDInchiLib.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```
Probably because I managed to force using the system-installed inchi library.

**Comment by greglandrum** [comment]
yeah, it could be that the API of the library has changed. That may be in the InChI release notes

**Comment by UnixJunkie** [comment]
For the next time I come here, the solution is to get rid of system-installed inchi lib prior to compiling rdkit.
I.e.
```bash
dpkg -l | grep rdkit
sudo apt purge THE_LIST_YOU_JUST_GOT
```

**Comment by merkys** [comment]
> For the next time I come here, the solution is to get rid of system-installed inchi lib prior to compiling rdkit.

Yes, this will make rdkit built system download the latest inchi library and build against it.
Last time I checked, system-installed inchi library did not interfere with rdkit build system doing the same.
Do you really have to remove system-installed library to build rdkit now?

**Comment by UnixJunkie** [comment]
Yes, on a debian system, this is what I was forced to do so that I could build then install a rdkit with inchi support.
By the way, I was happy to see that my (contributed years ago) Scripts/create_deb_packages.sh was still working.
