### ISSUE TITLE
[BUG] Chirality reverses in some cases after adding atom map numbers

### ISSUE THREAD

**Issue by rajathsalegame** [rdkit/rdkit#3835]
When loading from an sdf using `Chem.ForwardSDMolSupplier`, and I add atom map numbers, the chirality in the resulting is SMILES. This is confusing as the heuristic used to determine chirality should not be affected by atom map numbers. The same issue seems to result when I label using isotopes as well. For example,

`[O:0]=[C:1]([OH:2])[CH2:3][N@H+:4]1[CH2:6][C@@H:7]([OH:9])[C@@H:10]([n:12]2[cH:13][cH:14][n:15][cH:16]2)[CH2:17]1` vs.
`O=C(O)C[N@@H+]1C[C@H](n2ccnc2)[C@H](O)C1`

Are there any ways to maintain consistent chirality when adding atom map numbers?

**Comment by rajathsalegame** [comment]
Adding an example file below where this occurs for molecules with stereochemistry encoded with `@` or `@@`. This issue does not occur for SMILES with stereochemistry bonds encoded by `\` or `/`.
[stereo.sdf.zip](https://github.com/rdkit/rdkit/files/6017533/stereo.sdf.zip)

**Comment by greglandrum** [comment]
If you draw the molecules you will see that the chirality hasn't changed at all, the difference is the ordering of the atoms in the output, which causes different `@` or `@@` labels.
Here's the first molecule:
![image](https://user-images.githubusercontent.com/540511/108667625-ebef8400-74d9-11eb-8d81-ad7020a574b2.png)
and the second:
![image](https://user-images.githubusercontent.com/540511/108667654-f873dc80-74d9-11eb-9931-6c05b41a73c5.png)

**Comment by rajathsalegame** [comment]
@greglandrum, thanks--I agree that the chirality of the actual molecule hasn't changed, but is there a way to make sure that the `@` and `@@` labels are the same in the SMILES regardless of whether or not we add atom map numbers?

**Comment by greglandrum** [comment]
There is not. The @ and @@ labels are determined by the ordering of the atoms, which is determined by the canonicalization algorithm. The canonicalization algorithm takes the atom map numbers into account.

Your questions lead me to ask: why are you concerned about this?
