### ISSUE TITLE
Does the java wrapper have a similar rdkit.Chem.QED module in the python API

### ISSUE THREAD

**Issue by miracle1111111** [rdkit/rdkit#3839]
I need rdkit.Chem.QED.QEDproperties (MW, ALOGP, HBA, HBD, PSA, ROTB, AROM, ALERTS) in python. Then there is no quantitative estimate of drug similarity in the java wrapper. Where is it located?
Thank you very much！

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.
