### ISSUE TITLE
Problem transforming SEQUENCE into SMILES

### ISSUE THREAD

**Issue by TrikiSadok** [rdkit/rdkit#3846]
-----------------------------------------
I have a data set of enzyme sequences and a target variable to predict.
The process I am doing is transforming sequences into smiles and then get numerical inputs for machine learning models.
Problem is: rdkit fails to transform some of the sequences but not all of them. In this case the transformation was stopped for index = 5 which corresponds to the following sequence: 'PQITLWQRPIVTIKIGGQLIEALLDTGADDTVLEXXNLPGRWKPKXIGGIGGFXKVRQYDQVPIEIXGHKTXSTVLVGPTPVNIIGRNLMTQIGCTLNFPISPIETVPVKLKPGMDGPKXKQWPLTEEKIKALMEICKELEEEGKISKIGPENPYNTPVFAIKKKNSTKWRKLVDFRELNKRTQDFWEVQLGIPHPAGLKRKKSVTVLDVGDAYFSIPLDKDFRKYTAFTIPSINNETPGIRYQYNVLPQGWKGSPAIFQSSMTKILEPFRKQNPDIVIYQYVDDLYVGSDLEIEQHRTKIKELRQYLWKWGFYTPDXKHQEEPPFHWXGYELHPDKWTVQPIVLPEKESWTVNDIQKLVGKLNWASQIYAGIKVKQLCKLLRG'
![img](https://user-images.githubusercontent.com/27930666/108810161-caaa9880-75aa-11eb-95be-8aacf68239c9.PNG)

-----------------------------------------

**Configuration (please complete the following information):**
 - RDKit version: 2018.09.1
 - OS: windows 10
 - Python version : 3.7.0
 - Anaconda version: 5.3.1
 - how did you install the RDKit? : conda install -c conda-forge rdkit

**Comment by greglandrum** [comment]
@TrikiSadok : that sequence contains multiple "X" instances. "X" isn't an amino acid abbreviation recognized by the RDKit.
