### ISSUE TITLE
Iodosobenzene smiles conversion issue

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#3850]
**Describe the bug**
Conversion of smiles for iodosobenzene to mol and back to smiles adds unwanted extra hydrogens

**To Reproduce**
mol1 = Chem.MolFromSmiles('c1ccc(cc1)I=O') # smiles from wikipedia
mol2 = Chem.MolFromSmiles('I(=O)C1=CC=CC=C1')#smiles from OPSIN

print( Chem.MolToSmiles(mol1) )
print( Chem.MolToSmiles(mol2) )

**Expected behavior**
Observed Output:
O=[IH2]c1ccccc1
O=[IH2]c1ccccc1

Output has 2 extra hydrogens on the iodine atom. This isn't what is expected. Expect no additional hydrogens on structure.

**Configuration (please complete the following information):**
 - RDKit version: 2020.03.02
 - OS: Windows 10
 - Python version (if relevant): 3.8
 - Are you using conda? Y
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
This has been addressed in the 2020.09 release series:
```
In [5]: rdkit.__version__
Out[5]: '2020.09.4'

In [6]: Chem.CanonSmiles('c1ccc(cc1)I=O')
Out[6]: 'O=Ic1ccccc1'
```
