### ISSUE TITLE
Cannot install Rdkit on Google Colab anymore.

### ISSUE THREAD

**Issue by JohnMommers** [rdkit/rdkit#3851]
From today I get an error when using my RDkit scripts on Google Colab (Python version 3.7). With these scripts I had no issues before. 

Install procedure in Google Colob:
!wget -c https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh
!chmod +x Miniconda3-py37_4.8.3-Linux-x86_64.sh
!time bash ./Miniconda3-py37_4.8.3-Linux-x86_64.sh -b -f -p /usr/local
!time conda install -q -y -c conda-forge rdkit

import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

import rdkit
from rdkit import Chem  # here I get an error !!!
m = Chem.MolFromSmiles("c1ccccc1")

Rdkit 2020.09.04 is installed  however  I get an error when importing Chem.  The error I get: ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/lib/python3.6/site-packages/rdkit/DataStructs/cDataStructs.so)

Again, this import procedure worked fine before. What could I do? 
Thanks for any help.

**Comment by JohnMommers** [comment]
The solution is downgrading of RDKIT:

%%bash
add-apt-repository ppa:ubuntu-toolchain-r/test -y
apt-get update
apt-get install gcc-4.9
apt-get upgrade libstdc++6

!wget -c https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh
!chmod +x Miniconda3-py37_4.8.3-Linux-x86_64.sh
!time bash ./Miniconda3-py37_4.8.3-Linux-x86_64.sh -b -f -p /usr/local
!time conda install -q -y -c conda-forge rdkit=2020.09.02

import sys
sys.path.append('/usr/local/lib/python3.7/site-packages/')

**Comment by hjzhang1018** [comment]
Hi @JohnMommers , I used this downgrading solution just like you shared, however the same error still exists. Do you know how to resolve this? Thanks very much.
