### ISSUE TITLE
MinimalLib: Bonds are parallel in SVG but not on an HTML5 Canvas

### ISSUE THREAD

**Issue by dskatov** [rdkit/rdkit#3852]
**Describe the bug**
In certain rotations, bonds drawn in two parallel lines have these lines actually not parallel.

**To Reproduce**
It can be seen directly on https://rdkit.org/rdkitjs/beta/GettingStartedInJS.html. Produce an SVG, then check the corresponding Canvas drawing, to notice the parallel lines (in the top bond) are slightly not parallel, while many others are actually parallel:

![image](https://user-images.githubusercontent.com/67762377/109045606-d9956600-76e4-11eb-81a3-aa57962125d6.png)

It is seen more strongly in other occasions:

![image](https://user-images.githubusercontent.com/67762377/109046133-78ba5d80-76e5-11eb-8645-62259365b797.png)

**Expected behavior**
Parallel lines remain parallel.

**Configuration (please complete the following information):**
Chrome Version 88.0.4324.182 (Official Build) (64-bit)
RDKit Minimal Lib from https://rdkit.org/rdkitjs/beta/GettingStartedInJS.html.

**Additional context**
It may be some rounding error involved in producing this behaviour.

**Comment by ptosco** [comment]
@dskatov Hi Dan, yep, this is already on my to-do list.
