### ISSUE TITLE
Under windows using CPython >3.7 RDKit import fails due to missing dll(s)

### ISSUE THREAD

**Issue by SPKorhonen** [rdkit/rdkit#3872]
**Describe the bug**
Under windows using CPython >3.7 RDKit import fails due to missing dll(s).

**To Reproduce**
Build RDKit under windows using CPython >3.7. Under python "import rdkit" fails with "ImportError: DLL load failed while importing rdBase: The specified module could not be found."

**Expected behavior**
RDKit is successfully imported.

**Configuration (please complete the following information):**
 - RDKit version: ANY
 - OS: Windows 10
 - Python version (if relevant): CPython >3.7
 - Are you using conda? NO
 - If you are using conda, which channel did you install the rdkit from? N/A
 - If you are not using conda: how did you install the RDKit? Built from source

**Additional context**
Under windows with CPython >3.7 the way dll(s) are searched has changed (see: https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew).  Among other things environmental variable PATH is not used causing the RDKit to fail due to missing dll(s), mainly python, boost, etc.

One needs to specifically add dll search paths via os.add_dll_directory. I could submit a PR fixing this issue but I'm afraid it will not be pretty, mind you.

**Comment by greglandrum** [comment]
Ugh.
Thanks for pointing out the problem @SPKorhonen
I will take a look at this and try and come up with something over the next couple of days.

**Comment by SPKorhonen** [comment]
I have several extension modules which had the same problem. I made a small utility DllImport.py which is called within extension __init__.py and adds relevant paths to so.add_dll_directory. I could implement similar solution for rdkit if you like.

The only problem is that dynamically adding paths is a bit hackish but what can you do...

**Comment by SPKorhonen** [comment]
Sorry to bother you, but any progress on this issue @greglandrum?

I'm currently using a slightly hackish workaround which just forcibly adds relevant paths when importing modules. I could submit it as a pull request if you want to take a look at it.

**Comment by SPKorhonen** [comment]
Sorry to be a pest but do you have any work on how to resolve this issue going forward @greglandrum?

**Comment by ptosco** [comment]
@SPKorhonen I'll trave and have a look over the next few days: I'll get back to you before Monday.

**Comment by greglandrum** [comment]
@SPKorhonen : I can't reproduce the problem; I regularly use my own rdkit builds on a windows 10 machine and just need to be sure that the directories containing the RDKit dlls and the boost dlls are in my PATH.

I'm using the conda python binaries... I wonder if that makes a difference

**Comment by SPKorhonen** [comment]
I think it might be due to Conda. Either I'm reading too much into this comment, or Conda has rolled back this new security feature. See: https://github.com/conda-forge/python-feedstock/issues/307#issuecomment-576040344

**Comment by ptosco** [comment]
@SPKorhonen confirmed using Python from https://www.python.org/ and compiling my own Boost. This is indeed due to the security enhancement introduced with Python 3.8. I would not attempt to address this in RDKit, as it depends on how the libraries and Python modules are packaged/installed.
A simple way not to incur in the problem is to put all Boost and RDKit DLLs into the same directory where the `python.exe` binary lives. This removes the need for calling `os.add_dll_directory()`.

**Comment by SPKorhonen** [comment]
Fair enough. I can appreciate that you do not want to touch that can of worms even with a 10 feet pole...

I need to juggle between different versions of rdkit and boost so copying everything into python install directory is not really a viable solution for me. That said I use modified version of rdkit anyways and can continue using the modified version which automatically adds the PATH via os.add_dll_directory().

So, if you want to close this I have no problems.
