### ISSUE TITLE
Compiling for python3.8 on Apple Silicon

### ISSUE THREAD

**Issue by philspence** [rdkit/rdkit#3884]
I'm trying to compile rdkit on Apple Silicon in a Conda environment that has python3.8 (necessary to work with the AS TensorFlow builds). 

I have all the dependencies in the Conda env (cmake cairo pillow eigen pkg-config boost-cpp boost pyboost numpy matplotlib yapf coverage) and my cmake command is:

```
PYROOT=path/to/conda/env
cmake -DBoost_NO_BOOST_CMAKE=ON \
-DPYTHON_INCLUDE_DIR=$PYROOT/include \
-DPYTHON_EXECUTABLE=$PYROOT/bin/python3.8 \
-DBoost_INCLUDE_DIR=$PYROOT/include \
-DRDK_BUILD_CAIRO_SUPPORT=ON \
-DRDK_BUILD_INCHI_SUPPORT=ON \
-DRDK_BUILD_AVALON_SUPPORT=ON \
..
```

which completes but when running `make` I get the following at 27% when building Code/RDBoost/CMakeFiles/RDBoost.dir/Wrap.cpp.o:

```
$PYROOT/include/boost/python/detail/wrap_python.hpp:57:11: fatal error: 'pyconfig.h' file not found
# include <pyconfig.h>
          ^~~~~~~~~~~~
1 error generated.
make[2]: *** [Code/RDBoost/CMakeFiles/RDBoost.dir/Wrap.cpp.o] Error 1
make[1]: *** [Code/RDBoost/CMakeFiles/RDBoost.dir/all] Error 2
```

The file exists in the $PYROOT/include/python3.8 directory.

Anyone have any suggestions/solutions?

**Comment by philspence** [comment]
Okay, so I have got around that error - it was a silly mistake in the cmake commands, should be `-DPYTHON_INCLUDE_DIR=$PYROOT/include/python3.8`
 
I'm now stuck at errors arising from AvalonTools:

```
/Users/philspence/Downloads/rdkit-Release_2020_09_5/External/AvalonTools/SourceDistribution/common/layout.c:3592:4: error: implicit
      declaration of function 'FloodInvertColor' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
   FloodInvertColor(mp, nbp, bp->atoms[0]-1, color, bp);
   ^
/Users/philspence/Downloads/rdkit-Release_2020_09_5/External/AvalonTools/SourceDistribution/common/layout.c:3592:4: note: did you mean
      'FloodClearColor'?
/Users/philspence/Downloads/rdkit-Release_2020_09_5/External/AvalonTools/SourceDistribution/common/layout.c:143:5: note: 'FloodClearColor'
      declared here
int FloodClearColor(struct reaccs_molecule_t *mp,
    ^
/Users/philspence/Downloads/rdkit-Release_2020_09_5/External/AvalonTools/SourceDistribution/common/layout.c:3598:7: error: implicit
      declaration of function 'ChangeAtomColors' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      ChangeAtomColors(mp, -color, color);
      ^
/Users/philspence/Downloads/rdkit-Release_2020_09_5/External/AvalonTools/SourceDistribution/common/layout.c:3619:4: error: implicit
      declaration of function 'ChangeAtomColors' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
   ChangeAtomColors(mp, -color, color);
   ^
3 warnings and 3 errors generated.
make[2]: *** [External/AvalonTools/CMakeFiles/avalon_clib_static.dir/SourceDistribution/common/layout.c.o] Error 1
make[1]: *** [External/AvalonTools/CMakeFiles/avalon_clib_static.dir/all] Error 2
```

**Comment by philspence** [comment]
Update:

This compiles and works fine if Avalon support is turned off:

```
cmake -DPYTHON_INCLUDE_DIR=$PYROOT/include/python3.8 \
-DRDK_BUILD_AVALON_SUPPORT=OFF \
-DRDK_BUILD_CAIRO_SUPPORT=ON \
-DRDK_BUILD_INCHI_SUPPORT=ON \
-DBoost_INCLUDE_DIR=$PYROOT/include \
-DPYTHON_EXECUTABLE=$PYROOT/bin/python3.8 \
-DBoost_NO_SYSTEM_PATHS=ON \
-DBoost_NO_BOOST_CMAKE=ON \
-DRDK_INSTALL_INTREE=OFF \
-DCMAKE_INSTALL_PREFIX=$PYROOT \
..
```

Running a few simple tests of code in the Conda env seems to work fine. Looks like there could be an issue with AvalonTools and Apple Silicon?

**Comment by ptosco** [comment]
```
export CFLAGS='-Wno-implicit-function-declaration'
```
should allow you to work around the build failure.

**Comment by philspence** [comment]
Thank you so much, running ` export CFLAGS='-Wno-implicit-function-declaration' && cmake ....` worked perfectly!

**Comment by brndnsy** [comment]
> Thank you so much, running ` export CFLAGS='-Wno-implicit-function-declaration' && cmake ....` with Avalon support on worked perfectly!

D'you remember which version of cmake and boost you used? Also, did you manage to install py-boost as it doesn't come up for me from conda? I'd really appreciate it.

**Comment by philspence** [comment]
I don't remember which versions, sorry. I installed py-boost with "pip install pyboost". I think there is now an official build in conda-forge, you can use mini-forge to install it as it has native support for AS.

**Comment by brndnsy** [comment]
> pyboost

Thanks for your prompt reply. That helps a lot as py-boost didn't work for me.
Managed to make and make install with no errors using: 
export CFLAGS="-Wno-implicit-function-declaration" && cmake -DPYTHON_INCLUDE_DIR=$PYROOT/include/python3.8 \
-DRDK_BUILD_AVALON_SUPPORT=ON -DRDK_BUILD_CAIRO_SUPPORT=ON -DRDK_BUILD_INCHI_SUPPORT=ON \
-DRDK_OPTIMIZE_NATIVE=OFF 

However, all the python tests are failing for some strange reason. 
![image](https://user-images.githubusercontent.com/41188975/129235479-d0d3c13b-e3ed-46e5-a669-67c7838028f2.png)

**Comment by edmondo1984** [comment]
Is conda required to compile rdkit?
