### ISSUE TITLE
Debian Bullseye (gcc 10.2) compilation fails

### ISSUE THREAD

**Issue by InnocentBug** [rdkit/rdkit#3885]
**Describe the bug**
Compilation with CMake and GCC on linux results in an error.
```
[ 12%] Building CXX object Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/RDDepictor.cpp.o
In file included from /home/ludwig/git/rdkit/Code/GraphMol/Depictor/RDDepictor.cpp:15:
/home/ludwig/git/rdkit/External/CoordGen/CoordGen.h: In function ‘unsigned int RDKit::CoordGen::addCoords(T&, const RDKit::CoordGen::CoordGenParams*)’:
/home/ludwig/git/rdkit/External/CoordGen/CoordGen.h:80:13: error: ‘class sketcherMinimizer’ has no member named ‘setTreatAllBondsToMetalAsZOBs’
   80 |   minimizer.setTreatAllBondsToMetalAsZOBs(params->treatBondsToMetalAsZeroOrder);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/build.make:82: Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/RDDepictor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6285: Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/all] Error 2
```

**To Reproduce**
Clone rdkit from github on debian bullseye. Satisfy requirements from the official debian packages and compile with cmake.

**Expected behavior**
Error free compilation
[CMakeCache.txt](https://github.com/rdkit/rdkit/files/6085621/CMakeCache.txt)
.

**Configuration (please complete the following information):**
 - RDKit version: 
 master git-hash e21e2c2af6b47f45d15ed3dbd3c70bd12b589077 (and some earlier versions)
 - OS: 
 debian bullseye
 - Python version (if relevant): 
 python 3.9.1+
 - Are you using conda?
 No
 - If you are not using conda: how did you install the RDKit?
 Compilation from source

**Additional context**
I attach the CMakeCache.txt file for a full specification of the build environment.
While you might think that it is not important to address this issue for an unstable OS, the issue seems to be either the compiler or RDKit itself. So preparing for a new GCC version won't hurt.

**Comment by ptosco** [comment]
Try doing a
```
rm -rf External/Coordgen/coordgen* External/Coordgen/maeparser*
```
to trigger a fresh download of the latest `coordgen` and `maeparser` components, then rebuild.
It looks like your local cached copies might be outdated and cause the error.

**Comment by InnocentBug** [comment]
Thank you for the quick answer.
Deleting the specified files did not solve the problem, but a fresh clone did.

I run into a python problem now, but I propably open a fresh issue for that.
Feel free to close this one.
