### ISSUE TITLE
Python 3.9 import of `rdkit.Chem` fails with undefine symbol ImportError

### ISSUE THREAD

**Issue by InnocentBug** [rdkit/rdkit#3887]
**Describe the bug**
After a build from source and appropriate PYTHON_PATH and LD_LIBRARY_PATH setting
`import rdkit` works, but a subsequent `import rdkit.Chem` fails with 
```
>>> import rdkit.Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ludwig/git/rdkit/rdkit/Chem/__init__.py", line 20, in <module>
    from rdkit.Chem import rdchem
ImportError: /home/ludwig/git/rdkit/rdkit/Chem/rdchem.so: undefined symbol: _ZNK5RDKit8RingInfo17numRelevantCyclesEv
```

**To Reproduce**
Clone rdkit from github on debian bullseye. Satisfy requirements from the official debian packages and compile with cmake.
`make install` and import rdkit and rdkit.Chem

**Expected behavior**
Error free import

**Configuration (please complete the following information):**
 - RDKit version: 
 master git-hash e21e2c2af6b47f45d15ed3dbd3c70bd12b589077 (and some earlier versions)
 - OS: 
 debian bullseye
 - Python version (if relevant): 
 python 3.9.1+
 - Are you using conda?
 No
 - If you are not using conda: how did you install the RDKit?
 Compilation from source

**Additional context**
`ldd of `rdkit/rdkit/Chem/rdchem.so` reports no missing dynamic libraries.
```
objdump -T rdchem.so | grep _ZNK5RDKit8RingInfo17numRelevantCyclesEv
0000000000000000      DF *UND*	0000000000000000              _ZNK5RDKit8RingInfo17numRelevantCyclesEv
```

**Comment by ptosco** [comment]
The impression here is that `rdchem.so` is accessing a different version of the C++ library at runtime than the one it was built against. Try to check with `ldd` that the C++ libraries `rdchem.so` looks into are actually those you have just built.

**Comment by InnocentBug** [comment]
Excellent.
Yes, that was indeed the problem.
It was binding against an old system wide installation.

Thanks a lot.
