### ISSUE TITLE
Java/C# libs installation path

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#3910]
Looking at the wrappers, I noticed these get installed into the source tree:

https://github.com/rdkit/rdkit/blob/81d3705358860d147c4b31a44b38aed910c1a1d0/Code/JavaWrappers/csharp_wrapper/CMakeLists.txt#L75-L76

https://github.com/rdkit/rdkit/blob/81d3705358860d147c4b31a44b38aed910c1a1d0/Code/JavaWrappers/gmwrapper/CMakeLists.txt#L404-L405

Is there any reason for this? Should they go into the lib installation dir (`${RDKit_LibDir}`) ?

**Comment by greglandrum** [comment]
IMO: They're likely going to need to be copied somewhere else to be used anyway (like into whatever java project is using them or added to whatever dependency manager you're using), so it doesn't really matter from a "usability" perspective. The argument against changing is that I think of the stuff in `RDKit_LibDir` as the things which end up in /usr/lib and that's not where .jar files are supposed to land.

**Comment by ricrogz** [comment]
I agree with your comments, but I think that even if it is to copy them somewhere else, it would be a good idea to put those files in some place where they are easier to spot. Having them among the sources, not even in the build directory, seems unexpected to me. I'm also not a fan of using the source tree as work dir for the wrapping, which puts all the .java files there.

Putting the wrappers into the install dir (not necessarily under `RDKit_LibDir`) makes more sense to me because that will make them easier to find (less src/build clutter) and will also make installation/bundling easier, since they will be together with other stuff that might be required (e.g. the libs, if you happen to build with `RDK_SWIG_STATIC = OFF`, or the data in `RDKit_ShareDir`).
