### ISSUE TITLE
Cookbook entries should be updated 

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#3917]
These entries aren't wrong, but there are now easier/better solutions available.

## RDKitCB_0

The easier way to add atom indices in the notebook is to do:
```
IPythonConsole.drawOptions.addAtomIndices = True
```

## RDKitCB_23

Instead of modifying the atom labels I think it would make more sense to use the `atomNote` property here:
```
for at in m2.GetAtoms():
    lbl = '%.2f'%(at.GetDoubleProp("_GasteigerCharge"))
    at.SetProp('atomNote',lbl)
```

## RDKitCB_9

There's a more efficient way to do this which is perhaps also worth mentioning:
```
from rdkit.Chem import rdqueries
mol = Chem.MolFromSmiles("c1ccccc1C=CCC")

q = rdqueries.IsAromaticQueryAtom()
print([x.GetIdx() for x in mol.GetAtomsMatchingQuery(q)])

q = rdqueries.HybridizationEqualsQueryAtom(Chem.HybridizationType.SP2)
print([x.GetIdx() for x in mol.GetAtomsMatchingQuery(q)])

qcombined = rdqueries.IsAliphaticQueryAtom()
qcombined.ExpandQuery(q)
print([x.GetIdx() for x in mol.GetAtomsMatchingQuery(qcombined)])
```

## RDKitCB_7

After the 2021.03 release this manual bond removal is better done as:
```
with Chem.RWMol(mol) as rwmol:
  for b_idx in [2, 0, 4]:
      b = rwmol.GetBondWithIdx(b_idx)
      rwmol.RemoveBond(b.GetBeginAtomIdx(),b.GetEndAtomIdx())
```

## RDKitCB_25

The block of code which shows how to change the bounds matrix should include a call to AddHs():
```
.. testcode::

   from rdkit.Chem import rdDistGeom
   import rdkit.DistanceGeometry as DG
   
   mol = Chem.MolFromSmiles("C1CCC1C")
   mol = Chem.AddHs(mol)
   bm = rdDistGeom.GetMoleculeBoundsMatrix(mol)
   bm[0,3] = 1.21
   bm[3,0] = 1.20
   bm[2,3] = 1.21
   bm[3,2] = 1.20
   bm[4,3] = 1.21
   bm[3,4] = 1.20
   DG.DoTriangleSmoothing(bm)

   params.SetBoundsMat(bm)

```

@vfscalfani : What do you think the best way to handle this is given that the "Author" and "source" may no longer be accurate? Perhaps change "Source" to "Original Source" in these cases and just leave the "Author" as-is?

**Comment by vfscalfani** [comment]
Hi @greglandrum. I agree that changing to "Original Source" and leaving Author as-is, is the best solution. This still gives credit to the idea. We have just updated the code as RDKit evolves.

For RDKitCB_0, I'm not sure if `IPythonConsole.drawOptions.addAtomIndices = True` would work for setting options before drawing to a file. I'll check, and get this all updated in the next day or two with a pull request. Thanks

**Comment by greglandrum** [comment]
HI @vfscalfani : Though I'm happy if you want to do it, I wasn't trying to shovel work over to you... I'm happy to make the changes if you're busy at the moment.

**Comment by vfscalfani** [comment]
Hi @greglandrum : No problem at all, I enjoy making the changes. Actually, it would be very helpful to continue to point me to updates/ new additions needed to the Cookbook as they come up. I'm almost done with these additions, and will submit a PR that references this issue in a few min, thanks. Vin
