### ISSUE TITLE
CMake error: Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/all] Error 2

### ISSUE THREAD

**Issue by maxjr82** [rdkit/rdkit#3921]
**Configuration:**
 - RDKit version: latest (from git)
 - OS: Fedora 31
 - Python version: 3.8.1
 - Are you using conda? No
  - If you are not using conda: how did you install the RDKit? Building from source using cmake

I am trying to compile the latest version of RDkit from the source code, but I am stuck with an error message related to "GraphMol". The error message printed in the log file is as follows:

`In file included from /home/maxjr/temp/rdkit/Code/GraphMol/Depictor/RDDepictor.cpp:15:
/home/maxjr/temp/rdkit/External/CoordGen/CoordGen.h: In function ‘unsigned int RDKit::CoordGen::addCoords(T&, const RDKit::CoordGen::CoordGenParams*)’:
/home/maxjr/temp/rdkit/External/CoordGen/CoordGen.h:80:13: error: ‘class sketcherMinimizer’ has no member named ‘setTreatAllBondsToMetalAsZOBs’
   80 |   minimizer.setTreatAllBondsToMetalAsZOBs(params->treatBondsToMetalAsZeroOrder);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/build.make:83: Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/RDDepictor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6571: Code/GraphMol/Depictor/CMakeFiles/Depictor.dir/all] Error 2
make: *** [Makefile:183: all] Error 2`
 
I have compiled the boost library 1.72 using the following options:

`./bootstrap.sh --prefix=/opt/boost-1.72 --with-libraries=python,serialization,system,filesystem,thread,iostreams
.\b2 install`

Then, to compile RDKit I used the configuration shown below:

`cmake -DPy_ENABLE_SHARED=1 \
      -DRDK_INSTALL_INTREE=ON \
      -DRDK_BUILD_CPP_TESTS=ON \
      -DRDK_INSTALL_STATIC_LIBS=ON \
      -DRDK_BUILD_AVALON_SUPPORT=ON \
      -DRDK_BUILD_CAIRO_SUPPORT=ON \
      -DRDK_BUILD_INCHI_SUPPORT=ON \
      -DRDK_BUILD_PYTHON_WRAPPERS=ON \
      -DRDK_BUILD_SWIG_CSHARP_WRAPPER=ON \
      -DPYTHON_EXECUTABLE=/home/maxjr/.pyenv/versions/3.8.1/bin/python \
      -DPYTHON_LIBRARY=/home/maxjr/.pyenv/versions/3.8.1/lib/libpython3.8.a \
      -DPYTHON_INCLUDE_DIR=/home/maxjr/.pyenv/versions/3.8.1/include/python3.8 \
      -DPYTHON_NUMPY_INCLUDE_PATH="$(python -c 'import numpy ; print(numpy.get_include())')" \
      -DBOOST_NO_SYSTEM_PATHS=ON \
      -DBOOST_ROOT=/opt/boost-1.72/ \
      -DBOOST_INCLUDEDIR=/opt/boost-1.72/include/boost \
      -DBOOST_LIBRARYDIR=/opt/boost-1.72/lib ..

make > make.log`

After many compilation attempts, I still haven't been able to identify the source of the error mentioned above. I just followed the same set of instructions I have used for another successful installation before, but now it is not working. So I can't see what could be wrong in my steps. I will really appreciate any suggestions to solve this problem.

**Comment by greglandrum** [comment]
Hi @maxjr82 : it looks like you have an older version of the coordgen source.
Try running the `$RDBASE/External/CoordGen/coordgen` directory and then running cmake again, you should see it downloading a new version of coordgen; there will be something like this in the output of cmake:
```
-- Could NOT find coordgen (missing: coordgen_LIBRARIES) 
Downloading https://github.com/schrodinger/coordgenlibs/archive/v1.4.2.tar.gz...
```
Once you've done that, run make again and everything should be fine.

**Comment by greglandrum** [comment]
Apologies for the typo in my previous reply. I meant "Try removing the `$RDBASE/ExternalCoordGen/coordgen` directory.

The RDKit needs coordgen v1.4.2 or later. If you want to continue to use a system-wide install  in /usr/local, then you will need to be sure that is updated.
Otherwise you can try forcing the RDKit to download and use a local copy by doing:
```
cmake -DCOORDGEN_DIR=/home/maxjr/temp/rdkit/Externall/CoordGen/coordgen
```

**Comment by maxjr82** [comment]
> Apologies for the typo in my previous reply. I meant "Try removing the `$RDBASE/ExternalCoordGen/coordgen` directory.
> 
> The RDKit needs coordgen v1.4.2 or later. If you want to continue to use a system-wide install in /usr/local, then you will need to be sure that is updated.
> Otherwise you can try forcing the RDKit to download and use a local copy by doing:
> 
> ```
> cmake -DCOORDGEN_DIR=/home/maxjr/temp/rdkit/Externall/CoordGen/coordgen
> ```

Hi @greglandrum. Thank you very much for the instructions! Following your previous suggestion, I just removed the old CoordGen installation, and after doing this, the RDKit was compiled successfully. Thank you again!
