### ISSUE TITLE
Boost header warnings when compiling

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#3938]
When compiling rdkit, master branch, against a new version of boost (version 1.75) I am seeing warnings like this:

```
In file included from rdkit/include/rdkit/GraphMol/ROMol.h:27:
In file included from boost/include/boost/graph/adjacency_list.hpp:255:
In file included from boost/include/boost/graph/detail/adjacency_list.hpp:37:
In file included from boost/include/boost/graph/adjacency_iterator.hpp:13:
boost/include/boost/detail/iterator.hpp:13:1: warning: This
      header is deprecated. Use <iterator> instead. [-W#pragma-messages]
BOOST_HEADER_DEPRECATED("<iterator>")
^
```
I see these with any file that includes `ROMol.h` so they really litter up the build logs.

I'm happy to add `BOOST_ALLOW_DEPRECATED_HEADERS` to my own build script, but then I get an error from [here](https://github.com/d-b-w/rdkit/blob/master/Code/RDGeneral/utils.h#L18) where that flag is set and then unset without regard for whether it was previously set.

So the minimum fix would be to change that definition in RDGeneral/utils.h to only define the flag if it isn't already set, which would allow me to silence the warnings.  Maybe a better solution is to define the flag in BoostStartInclude, I can't say.

**Comment by e-kwsm** [comment]
boostorg/graph#245

**Comment by greglandrum** [comment]
Thanks for pointing this out @jasondbiggs 
I like the idea of including this definition in `BoostStartInclude.h`
We, of course, run the risk of not seeing those warnings in our own code this way, but it seems like these warnings pop up  more often in boost itself than in the RDKit.
