### ISSUE TITLE
Incorrect reading of SMILES of heavy synthetic elements

### ISSUE THREAD

**Issue by chigozienri** [rdkit/rdkit#3948]
**Describe the bug**
Reading SMILES of heavy synthetic elements results in an off-by-one or off-by-two error (in the atom displayed in the image, and also if you convert back into SMILES or SMARTS)

**To Reproduce**
```
from rdkit import Chem
Chem.MolFromSmiles('[Nh]')  # Correctly gives Nh
# Off-by-one
Chem.MolFromSmiles('[Fl]')  # Incorrectly gives Uut (the placeholder symbol for Nh)
Chem.MolFromSmiles('[Mc]')  # Incorrectly gives Fl
Chem.MolFromSmiles('[Lv]')  # Incorrectly gives Mc
# Off-by-two
Chem.MolFromSmiles('[Ts]')  # Incorrectly gives Uup (the placeholder symbol for Mc)
Chem.MolFromSmiles('[Og]')  # Incorrectly gives Lv
```
For comparison, using the placeholder symbols does the same thing
```
Chem.MolFromSmiles('[Uut]')  # Correctly gives Nh
Chem.MolFromSmiles('[Uuq]')  # Incorrectly gives Uut (the placeholder symbol for Nh)
Chem.MolFromSmiles('[Uup]')  # Incorrectly gives Fl
Chem.MolFromSmiles('[Uuh]')  # Incorrectly gives Mc
Chem.MolFromSmiles('[Uus]')  # Incorrectly gives Uup (the placeholder symbol for Mc)
Chem.MolFromSmiles('[Uuo]')  # Incorrectly gives Lv
```

**Expected behavior**
No transmutation
`Chem.MolToSmiles(Chem.MolFromSmiles('[Mc]')) == '[Mc]'`

**Configuration (please complete the following information):**
 - RDKit version: 2019.03.3
 - OS: Mac OS X 10.15.7
 - Python version (if relevant): 3.6.12
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Enthought Deployment Manager (`edm install rdkit`)

**Comment by greglandrum** [comment]
You're using an old version of the RDKit. This was fixed in the 2019_09_2 release (#2784)
