### ISSUE TITLE
Documentation of `Chem.rdmolops.CombineMols` includes a Python fallback `repr` call

### ISSUE THREAD

**Issue by bzoracler** [rdkit/rdkit#3966]
From https://www.rdkit.org/docs/source/rdkit.Chem.rdmolops.html#rdkit.Chem.rdmolops.CombineMols

The final argument to `rdkit.Chem.rdmolops.CombineMols`, `offset`, has a default argument which looks like it was generated by a Python fallback `repr` call on both the Python and C++ calling signatures:

```
rdkit.Chem.rdmolops.CombineMols((Mol)mol1, (Mol)mol2[, (Point3D)offset=<rdkit.Geometry.rdGeometry.Point3D object at 0x7ff4c8df5f10>]) → Mol :

    Combine the atoms from two molecules to produce a third

    C++ signature :

        RDKit::ROMol* CombineMols(RDKit::ROMol,RDKit::ROMol [,RDGeom::Point3D=<rdkit.Geometry.rdGeometry.Point3D object at 0x7ff4c8df5f10>])
```

According to the source, 

https://github.com/rdkit/rdkit/blob/0f6da8d3b606264db35d4738faf1518f53e0b3d7/Code/GraphMol/Wrap/MolOps.cpp#L1247-L1251

 - The Python signature might be clearer as `offset=rdkit.Geometry.rdGeometry.Point3D(0, 0, 0)`
 - The C++ signature should use `RDGeom::Point3D(0, 0, 0)`

**Comment by greglandrum** [comment]
@bzoracler : I agree, but those signatures are generated by boost::python and I don't think we have any control over them.
