### ISSUE TITLE
Stereochemistry altered during conformer generation

### ISSUE THREAD

**Issue by kekoburgo** [rdkit/rdkit#3972]
1) Configuration:

RDKit Version: '2019.03.4.0'
Operating system: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-58-generic x86_64)
Python version (if relevant): Python 3.7.3
Are you using conda? Yes
If you are using conda, which channel did you install the rdkit from? conda create -c rdkit -n my-rdkit-env rdkit
If you are not using conda: how did you install the RDKit?

2) Description and expected behaviour:

In reference to this issue: #1513 (Stereochemistry wrongly assigned #1513)

I am trying to generate an ensemble of 3D conformers from a single input 3D structure in SDF format using AllChem.EmbedMultipleConfs and setting enforceChirality=True.
The code should read the input structure (in SDF format) produce an ensemble of conformers, minimise the energy, perform a basic alignment and print all in a SDF output file. 
However, when I check carefully the list of conformers generated, I find that the chirality of the input molecule is not preserved across the output ensemble.

Is there any known issue/bug with the EmbedMultipleConfs function?

Many thanks!!

3) To Reproduce

I am running the code (please, see below) using the next input arguments:

./conf_gen.py chiral_example_R.mol 25 500 0.2 1000

[conf_gen.py.txt](https://github.com/rdkit/rdkit/files/6199533/conf_gen.py.txt)

4) Input file containing a chiral structure:

[chiral_example_R.mol.txt](https://github.com/rdkit/rdkit/files/6199435/chiral_example_R.mol.txt)

5) Output file with a small ensemble of 25 conformers:

[chiral_example_R_conformers.sdf.txt](https://github.com/rdkit/rdkit/files/6199442/chiral_example_R_conformers.sdf.txt)

**Comment by shaoqx** [comment]
Encountered the same problem with RDKit version: 2021.09.4.

**Comment by shaoqx** [comment]
I think Chem.rdmolops.AssignAtomChiralTagsFromStructure(mol) help fix this problem
