### ISSUE TITLE
Similarity maps applying machine learning model

### ISSUE THREAD

**Issue by PARODBE** [rdkit/rdkit#3977]
Hi,

Thanks for develop so useful code for the cheminformatic community. I have a question, and I hope that you could help me. When you apply similarity maps using a machine learning model for obtain information about what part of the molecule is contribuiting to respond your question (solubility, toxicity...whatever kind of class problem). would it be possible extract a dataset where you have the parts of molecule which are contributing to a low solubility or toxicity?

Thanks,

Pablo

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.
