### ISSUE TITLE
AllChem documentation is empty on the rdkit website

### ISSUE THREAD

**Issue by benoitba** [rdkit/rdkit#3995]
**Describe the bug**
AllChem python documentation on the website is empty

**To Reproduce**
Go to https://www.rdkit.org/docs/source/rdkit.Chem.AllChem.html

**Expected behavior**
I usually check this documentation page to know more about the AllChem functions. It didn't work out today !

**Screenshots**
![Empty_allchem](https://user-images.githubusercontent.com/29234619/113156293-23202600-923a-11eb-8371-c8f213603f35.PNG)

**Comment by greglandrum** [comment]
I made a mistake when uploading the docs. This should now be fixed.
