### ISSUE TITLE
Can't import Descriptors from rdkit.Chem

### ISSUE THREAD

**Issue by rajathsalegame** [rdkit/rdkit#4008]
Running into this bug: `AttributeError: module 'rdkit.Chem' has no attribute 'Descriptors'`. Unclear how to resolve it as it seems from the source code and online examples that I should be able to do `from rdkit.Chem import Descriptors`. For reference, I am using rdkit version 2020.03.3.

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
