### ISSUE TITLE
Normalizing the molecule breaks it further down the pipeline.

### ISSUE THREAD

**Issue by jp-um** [rdkit/rdkit#4009]
Normalizing a molecule, breaks the molecule downstream.

I create a molecule (which contains a fragment) from SMILES  (i.e. `Cl.Oc1ccc(C2NCc3ccccc3-n3cccc32)cc1Cl`), I then normalize it and upon trying to generate Morgan fingerprints I get this nasty RuntimeError:

```RuntimeError: Pre-condition Violation
	RingInfo not initialized
	Violation occurred on line 45 in file Code/GraphMol/RingInfo.cpp
	Failed Expression: df_init
	RDKIT: 2021.03.1
	BOOST: 1_74
```

This error is **not** generated if either i) the molecule does not contain a fragment (`Cl.`) or ii) I skip the normalization step. 

This is, as usual, all better explained with a MWE:
https://nbviewer.jupyter.org/gist/jp-um/d4cbd1938c36c2bc1298f01f3c57863b

I was expecting that this just works (like it does for the not normalized version), or that I get a meaningful error message instead.

I am using the latest rdkit (2021.03.1) on archlinux, installed from conda (conda-forge) on Python 3.9.2.  If you need more details just ask.

**Comment by ptosco** [comment]
@jp-um Hi JP, does calling `Chem.Sanitize` on the molecule after normalization fix the problem?

**Comment by jp-um** [comment]
What a star, so fast!  Indeed it does.

**Comment by bp-kelley** [comment]
I think this is a bug,   Normalize should create useable molecules.

**Comment by greglandrum** [comment]
@bp-kelley : it's definitely not a bug.
The standardization code was designed to not sanitize things by default. The idea was that you may want to do further manipulations of the molecules after standardizing them and that it doesn't make sense to automatically sanitize.

We can certainly change that behavior and add a `sanitize` argument to the normalization/standardization code which defaults to true, but that would be an enhancement.
