### ISSUE TITLE
Similary score error for chiral

### ISSUE THREAD

**Issue by xiaohongniua** [rdkit/rdkit#4013]
C[C@H]1CC[C@@H](C)CC1
C[C@@H]1CC[C@@H](C)CC1

`DataStructs.BulkTanimotoSimilarity(AllChem.GetMorganFingerprintAsBitVect(Chem.MolFromSmiles('C[C@H]1CC[C@@H](C)CC1'),2,nBits=1024,useChirality=True), [AllChem.GetMorganFingerprintAsBitVect(Chem.MolFromSmiles('C[C@@H]1CC[C@@H](C)CC1'),2,nBits=1024,useChirality=True)])`

The similarity score is 1 though useChirality=True.

**Comment by greglandrum** [comment]
Those atoms are not actually chiral centers (it’s ring stereochemistry not chirality). The Morgan fingerprint uses information about the absolute chirality of the atoms, so these two molecules are the same

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by xiaohongniua** [comment]
> Those atoms are not actually chiral centers (it’s ring stereochemistry not chirality). The Morgan fingerprint uses information about the absolute chirality of the atoms, so these two molecules are the same
Thanks for your reply. If I want to get a different similarity score for above two molecules, are there some ways to do so?

**Comment by greglandrum** [comment]
> > Those atoms are not actually chiral centers (it’s ring stereochemistry not chirality). The Morgan fingerprint uses information about the absolute chirality of the atoms, so these two molecules are the same
> Thanks for your reply. If I want to get a different similarity score for above two molecules, are there some ways to do so?

You could create your own atom invariants which take ring stereochemistry into account and provide them.

It's probably worth it for us to take a look at supporting things other than just R/S chirality in the Morgan fingerprinting code too. I will take a look at that. Note: whatever changes we make here would not be available until the 2021.09 release.
