### ISSUE TITLE
bond.IsInRing() does not correctly identify ring bond

### ISSUE THREAD

**Issue by KramerChristian** [rdkit/rdkit#4016]
For a rather complex multi-ring natural-product like compound, bond.IsInRing() does not correctly identify one of the bonds as ring bond. The compound has 3 non-ring bonds. RDKit identifies a fourth bond (between atoms 11 and 12) as non-ring. However, this bond is part of a larger ring system. Here is a picture that highlights the bond in question 

![image (1)](https://user-images.githubusercontent.com/30893946/114140221-4a4cb680-9910-11eb-8bb9-9230318135a3.png)

Here is some code to exemplify the problem (run on Python 3.7.1 with RDKit Version 2020.03.1 on Linux):
```
In [1]: import rdkit

In [2]: from rdkit import Chem

In [3]: smi = 'C[C@]12CCC3c4c5cc(O)cc4[C@@]4(CC[C@@]1(C4)C3CC5)[C@@H]2O'

In [4]: mol = Chem.MolFromSmiles(smi)

In [5]: bond = mol.GetBondBetweenAtoms(11, 12)

In [6]: bond.IsInRing()
Out[6]: False

In [7]: [bond.IsInRing() for bond in mol.GetBonds()]
Out[7]:
[False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True]
```
I currently believe that this behaviour leads to a bug in mmpdb. That bug was reported here: https://github.com/rdkit/mmpdb/issues/30

**Comment by greglandrum** [comment]
Confirmed. This looks like a bug in the ring finding code.

**Comment by IchiruTake** [comment]
> For a rather complex multi-ring natural-product like compound, bond.IsInRing() does not correctly identify one of the bonds as ring bond. The compound has 3 non-ring bonds. RDKit identifies a fourth bond (between atoms 11 and 12) as non-ring. However, this bond is part of a larger ring system. Here is a picture that highlights the bond in question
> 
> ![image (1)](https://user-images.githubusercontent.com/30893946/114140221-4a4cb680-9910-11eb-8bb9-9230318135a3.png)
> 
> Here is some code to exemplify the problem (run on Python 3.7.1 with RDKit Version 2020.03.1 on Linux):
> 
> ```
> In [1]: import rdkit
> 
> In [2]: from rdkit import Chem
> 
> In [3]: smi = 'C[C@]12CCC3c4c5cc(O)cc4[C@@]4(CC[C@@]1(C4)C3CC5)[C@@H]2O'
> 
> In [4]: mol = Chem.MolFromSmiles(smi)
> 
> In [5]: bond = mol.GetBondBetweenAtoms(11, 12)
> 
> In [6]: bond.IsInRing()
> Out[6]: False
> 
> In [7]: [bond.IsInRing() for bond in mol.GetBonds()]
> Out[7]:
> [False,
>  True,
>  True,
>  True,
>  True,
>  True,
>  True,
>  True,
>  False,
>  True,
>  True,
>  False,
>  True,
>  True,
>  True,
>  True,
>  True,
>  True,
>  True,
>  True,
>  False,
>  True,
>  True,
>  True,
>  True,
>  True,
>  True]
> ```
> 
> I currently believe that this behaviour leads to a bug in mmpdb. That bug was reported here: [rdkit/mmpdb#30](https://github.com/rdkit/mmpdb/issues/30)

This issue was also found in Windows, too. I have checked that `bond.IsInRing() = False` but `startAtom.IsInRing() = True` and `endAtom.IsInRing() =True`. So you should convert them like `if bond.IsInRing()` to be `if startAtom.IsInRing() and endAtom.IsInRing()`. If for some reason, you found that IsInRing() costs too much time, you can split it to have two if/else logic to perform or use `atom.GetSymbol()` to have initial knowledge aforehead.

**Comment by IchiruTake** [comment]
> Hi Ichiru. I am not sure whether I understand you correctly. However, I do not think that if startAtom and endAtom are in a ring this is a sufficient criterion to state that the bond between the two also is in a ring. Consider biphenyl, where two ring systems are linked by a single, non-ring bond. For this bond, both start- and end-atom are in a ring, but the bond itself is not.

Yeah, I have just thought about that. A better option is that if you break that bond. If the result contained one structure only so it is within the bond. Otherwise, it is a non-ring bond. I am not sure is there a function to test whether two atoms are in the same ring

**Comment by adalke** [comment]
Here's another example:
```
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles("COc1cc2c3c([C@]45CC[C@@]6(C4)C(CC2)C3CC[C@]6(C)[C@H]5O)c1")
>>> pat = Chem.MolFromSmarts("[#6+0;!$(*=,#[!#6])]!@!=!#[!#0;!#1;!$([CH2]);!$([CH3][CH2])]")
>>> for match in mol.GetSubstructMatches(pat):print(match)
...
(0, 1)
(2, 1)
(6, 7)
(18, 19)
(20, 21)
>>> mol.GetBondBetweenAtoms(6, 7).IsInRing()
False
```

I'll break that bond manually by inserting "[H].[H]" and show it's still a single fragment.

```
>>> mol2 = Chem.MolFromSmiles("COc1cc2c3c([H].[H][C@]45CC[C@@]6(C4)C(CC2)C3CC[C@]6(C)[C@H]5O)c1")
>>> Chem.MolToSmiles(mol2)
'COc1ccc2c(c1)CCC1C2CC[C@]2(C)[C@@H](O)[C@H]3CC[C@@]12C3'
```
I'll annotate atoms 6 and 7 as "1" and "2" in the following:

<img width="221" alt="unperceived-ring-bond" src="https://user-images.githubusercontent.com/4743232/144433513-fdb7b94e-b4de-402c-867a-d1ec4c8fcc4b.png">

**Comment by ichcharisma** [comment]
i know its too late to comment, its similar with my case before. i use kind of code below to make sure the bond it is in ring.

```
b = m.GetBondBetweenAtoms(11, 12)
b.IsInRing() or not (b.IsInRingSize(3) or b.IsInRingSize(4) or b.IsInRingSize(5) or b.IsInRingSize(6) or b.IsInRingSize(7))
```

**Comment by greglandrum** [comment]
Some additional info on this from a quick bit of looking that I just did

This is due to the SSSR code (not the symmetrized SSSR code), which finds the right number of rings, but turns up an "extra" 6-ring while missing a 7-ring in the molecule.
Here's a demo of that using the URF code as an alternative ring-finding algorithm:
```
In [27]: m = Chem.MolFromSmiles('[C@]12CCC3c4c5cccc4[C@@]4(CC[C@@]1(C4)C3CC5)[C@@H]2')

In [28]: m2 = Chem.Mol(m)

In [29]: Chem.FindRingFamilies(m2)

In [31]: for r in m2.GetRingInfo().AtomRingFamilies():
    ...:     print(list(r))
    ...: 
[10, 11, 12, 13, 14]
[0, 10, 13, 14, 18]
[4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 13, 15]
[3, 4, 5, 15, 16, 17]
[3, 4, 9, 10, 13, 14, 15]   #<- this ring is not found by the SSSR code (below)

In [32]: m3 = Chem.Mol(m)

In [34]: Chem.GetSSSR(m3)
Out[34]: <rdkit.rdBase._vectSt6vectorIiSaIiEE at 0x7f739e7023c0>

In [35]: for r in m3.GetRingInfo().AtomRings():
    ...:     print(list(r))
    ...: 
[1, 2, 3, 15, 13, 0]
[6, 7, 8, 9, 4, 5]
[11, 10, 14, 13, 12]
[14, 13, 0, 18, 10]
[16, 17, 5, 4, 3, 15]
[11, 12, 13, 0, 18, 10]  #<- this was not found by the URF code

```

**Comment by LingjieBao1998** [comment]
> Some additional info on this from a quick bit of looking that I just did
> 
> This is due to the SSSR code (not the symmetrized SSSR code), which finds the right number of rings, but turns up an "extra" 6-ring while missing a 7-ring in the molecule. Here's a demo of that using the URF code as an alternative ring-finding algorithm:
> 
> ```
> In [27]: m = Chem.MolFromSmiles('[C@]12CCC3c4c5cccc4[C@@]4(CC[C@@]1(C4)C3CC5)[C@@H]2')
> 
> In [28]: m2 = Chem.Mol(m)
> 
> In [29]: Chem.FindRingFamilies(m2)
> 
> In [31]: for r in m2.GetRingInfo().AtomRingFamilies():
>     ...:     print(list(r))
>     ...: 
> [10, 11, 12, 13, 14]
> [0, 10, 13, 14, 18]
> [4, 5, 6, 7, 8, 9]
> [0, 1, 2, 3, 13, 15]
> [3, 4, 5, 15, 16, 17]
> [3, 4, 9, 10, 13, 14, 15]   #<- this ring is not found by the SSSR code (below)
> 
> In [32]: m3 = Chem.Mol(m)
> 
> In [34]: Chem.GetSSSR(m3)
> Out[34]: <rdkit.rdBase._vectSt6vectorIiSaIiEE at 0x7f739e7023c0>
> 
> In [35]: for r in m3.GetRingInfo().AtomRings():
>     ...:     print(list(r))
>     ...: 
> [1, 2, 3, 15, 13, 0]
> [6, 7, 8, 9, 4, 5]
> [11, 10, 14, 13, 12]
> [14, 13, 0, 18, 10]
> [16, 17, 5, 4, 3, 15]
> [11, 12, 13, 0, 18, 10]  #<- this was not found by the URF code
> ```
> 
> After looking through the code some more: this is a situation that the modified Figueras algorithm used to find the SSSRs cannot resolve.

Thank you for your code which help me a lot!
