### ISSUE TITLE
EmbedMolecule not handling trivalent iodine properly

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#4034]
Ideally this would give a T-shaped geometry around the iodine rather than trigonal pyramidal.

```
m=MolFromSmiles('[I](Cl)(Cl)Cl')
rdDistGeom.EmbedMolecule(m)
```
<img width="301" alt="image" src="https://user-images.githubusercontent.com/16337306/114788426-08c06f00-9d47-11eb-91ac-c91bedc095b5.png">

This is using the 2021.03.1 release, on MacOS.

**Comment by greglandrum** [comment]
You're right, and this is a bug, but it's more or less expected: we don't have code in place to handle hypervalent species.
