### ISSUE TITLE
TypeError: No registered converter was able to produce a C++ rvalue of type class

### ISSUE THREAD

**Issue by kursatartar** [rdkit/rdkit#4051]
I get this error, any help ?

moldata = []
for elem in smiles:
mol=Chem.MolFromSmiles(elem)
moldata.append(mol)

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
