### ISSUE TITLE
treatNonterminalBondsToMetalAsZOBs should default to true

### ISSUE THREAD

**Issue by ZontaNicola** [rdkit/rdkit#4055]
CoordGenParams has a treatNonterminalBondsToMetalAsZOBs flag that defaults to false.

I think this originally  controlled all bonds to metals and was introduced to get better images of terminal bonds. Since then thought that specific behaviour is always on in coordgen and the flag now only controls non-terminal bonds.
I think the flag should be off by default (same as for coordgen) cause it can cause ugly depiction of metal coordination systems

**Comment by greglandrum** [comment]
@ZontaNicola 
> I think the flag should be off by default (same as for coordgen) cause it can cause ugly depiction of metal coordination systems

Is this a typo? Do you mean that it should be *on* by default?
