### ISSUE TITLE
Empty smiles will cause a memory crash issue when calculating the BCUT2D descriptors.

### ISSUE THREAD

**Issue by imxj** [rdkit/rdkit#4064]
**Describe the bug**
Empty smiles will cause a memory crash issue when calculating the BCUT2D descriptors.

**To Reproduce**
from rdkit import Chem
from rdkit.Chem import Descriptors
from rdkit.ML.Descriptors import MoleculeDescriptors
mol = Chem.MolFromSmiles('') # it returns mol object and won't throw exception like the other unparsable smiles. 
if mol is None:
  raise ValueError(f"Invalid smiles")
descriptor_names = [descriptor_name for descriptor_name, _ in Descriptors.descList][18:25] # ['BCUT2D_MWLOW', 'BCUT2D_CHGHI', 'BCUT2D_CHGLO', 'BCUT2D_LOGPHI', 'BCUT2D_LOGPLOW', 'BCUT2D_MRHI', 'BCUT2D_MRLOW']
descriptor_calculator = MoleculeDescriptors.MolecularDescriptorCalculator(descriptor_names)
descriptors = descriptor_calculator.CalcDescriptors(mol) # will crash

**Expected behavior**
Instead of crash, have a better failure mode. 

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: Release_2021.03.1
 - OS: [e.g. Ubuntu 20.04]
 - Python version (if relevant): Python 2.7.15
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by bp-kelley** [comment]
Thanks!  I’ll look into this.
