### ISSUE TITLE
rdkit.Chem has no attribute Descriptors

### ISSUE THREAD

**Issue by StashOfCode** [rdkit/rdkit#4072]
**Describe the bug**
I was trying to compute molecular weight of the molecule, but there's no `Descriptor` if you `dir(rdkit)` or `dir(rdkit.Chem)`
I installed rdkit using  `conda install -c conda-forge rdkit=2021.03.1`. Am i missing something in the installation procedure?

**To Reproduce**
```
import rdkit
from rdkit import Chem

mol = Chem.MolFromSmiles('C=C(C=C=[C-]O)OC(=O)c1cc(NCCCCCC=[O+])ccc1NC1=CNC(O)C=C1')
rdkit.Chem.Descriptors.ExactMolWt(mol)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/22925108/115684360-f5715d00-a35f-11eb-89ad-09b13fe3ff5e.png)

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.1
 - OS: Windows 10
 - Python version (if relevant):  3.6
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
You need to do: `from rdkit.Chem import Descriptors`
