### ISSUE TITLE
Import error: library 'libmaeparser' not found

### ISSUE THREAD

**Issue by maxjr82** [rdkit/rdkit#4092]
**Describe the bug**
I have compiled the newest version of rdkit on my computer (linux/fedora) successfully, but I am getting an error when I try to import the rdkit.Chem module. The error is related to the 'libmaeparser.so.1' library which is not found. I checked the lib directory of the rdkit installation and, in fact, this specific library is not available there.

**To Reproduce**

Python 3.8.1 (default, Feb  3 2020, 21:42:11) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/molecular_tools/rdkit/rdkit/Chem/__init__.py", line 23, in <module>
    from rdkit.Chem.rdmolfiles import *
ImportError: libmaeparser.so.1: cannot open shared object file: No such file or directory
>>> 

For completeness, here are the instructions I have used to compile the program:

cmake -DPy_ENABLE_SHARED=1 \
      -DRDK_INSTALL_INTREE=ON \
      -DRDK_BUILD_CPP_TESTS=ON \
      -DRDK_INSTALL_STATIC_LIBS=ON \
      -DRDK_BUILD_AVALON_SUPPORT=ON \
      -DRDK_BUILD_CAIRO_SUPPORT=ON \
      -DRDK_BUILD_INCHI_SUPPORT=ON \
      -DRDK_BUILD_PYTHON_WRAPPERS=ON \
      -DRDK_BUILD_SWIG_CSHARP_WRAPPER=ON \
      -DPYTHON_EXECUTABLE=/home/maxjr/.pyenv/versions/3.8.1/bin/python \
      -DPYTHON_LIBRARY=/home/maxjr/.pyenv/versions/3.8.1/lib/libpython3.8.a \
      -DPYTHON_INCLUDE_DIR=/home/maxjr/.pyenv/versions/3.8.1/include/python3.8 \
      -DPYTHON_NUMPY_INCLUDE_PATH="$(python -c 'import numpy ; print(numpy.get_include())')" \
      -DBOOST_NO_SYSTEM_PATHS=ON \
      -DBOOST_ROOT=/opt/boost-1.73/ \
      -DBOOST_INCLUDEDIR=/opt/boost-1.73/include/boost \
      -DBOOST_LIBRARYDIR=/opt/boost-1.73/lib ..

make > make.log

**Configuration (please complete the following information):**
 - RDKit version: '2021.09.1pre'
 - OS: Fedora 31 (5.8.18-100.fc31.x86_64)
 - Python version: 3.8.1
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? Compiled from source with gcc
 
 Does anyone has experienced a similar problem or may have some insights on how to fix this bug? I will really appreciate any help you can provide.
 
 Thanks in advance!

**Comment by greglandrum** [comment]
Please try doing `make install`, that's the necessary step to get the libraries copied to the correct place.

**Comment by maxjr82** [comment]
> Please try doing `make install`, that's the necessary step to get the libraries copied to the correct place.

Sorry, I forgot to mention but I also did `make install`. What would be the name expected for the "libmaeparser" in the lib directory? I checked the build/lib directory but I couldn't see any library with "maeparser".

**Comment by greglandrum** [comment]
If `RDK_BUILD_MAEPARSER_SUPPORT` is `ON` (this is the default), then cmake should have picked up the location of the maeparser library and reported that (or it will tell you where the code is if you don't have a pre-installed version).

If you didn't have a pre-built version of the maeparser, when you run "make"  it should have built maeparser (hopefully you'll see something about this in the output of the make command) and created libRDKitmaeparser.so in the build/lib directory.

If you did have a pre-built version of the maeparser, then you should be sure that wherever it is is in your `LD_LIBRARY_PATH`.

**Comment by maxjr82** [comment]
> If `RDK_BUILD_MAEPARSER_SUPPORT` is `ON` (this is the default), then cmake should have picked up the location of the maeparser library and reported that (or it will tell you where the code is if you don't have a pre-installed version).
> 
> If you didn't have a pre-built version of the maeparser, when you run "make" it should have built maeparser (hopefully you'll see something about this in the output of the make command) and created libRDKitmaeparser.so in the build/lib directory.
> 
> If you did have a pre-built version of the maeparser, then you should be sure that wherever it is is in your `LD_LIBRARY_PATH`.

Thank you very much for the instructions! This helped me to find and fix the problem. There was an old version of the libmaeparser.so library in my /usr/local/lib directory created with an old version of the boost. So after fixing these incompatibilities of the library version, RDKit was successfully compiled and it is now working fine.

Thank you again for your patience and support!
