### ISSUE TITLE
HCount field in v2000 Mol blocks ignored

### ISSUE THREAD

**Issue by riccardosabatini** [rdkit/rdkit#4099]
Hei @greglandrum - first time posting here, so let me first share how tankful I am/we all are for the amazing job you're doing with RDKIT, thank you !!

Re issue, after few hours debugging a RNX reactions not working correctly, I found the problem in the parser file, in particular with the implicit hydrogen definition

https://github.com/rdkit/rdkit/blob/b208da471f8edc88e07c77ed7d7868649ac75100/Code/GraphMol/FileParsers/MolFileParser.cpp#L1449

In this line the number of hydrogens is lost and, making it impossible to explicitly add the hydrogens after the molecule is loaded (or in my case the RXN).

As I notices an open PR where you're restructuring the valence calculation #3542 I thought that could be a good PR to fix this implicit Hs import issue. 

I noticed that there is no method to set the NumImplicitHs so probably it's all linked to the valence model, but I think storing this info can already be useful as we can add Hs later programmatically to the atoms.

Tnx again, ciao

**Comment by greglandrum** [comment]
Hi @riccardosabatini : please provide an example reaction and inputs along with the output you observe and specifics of what you think is wrong.

**Comment by riccardosabatini** [comment]
Sure, here's a quick example.

In this block the carbon atoms are defined with 2 hydrogens in an implicit way (the fourth column definition for V2000 is hydrogen+1). This block is the result of Marvin editor, but the resulting MOL is identical with MolfileCreator and other editors tested.

`
  3  2  0  0  0  0  0  0  0  0999 V2000
    2.7500   -7.9167   -0.0000 C   0  0  0  3  0  0  0  0  0  5  0  0
    3.6160   -7.4167   -0.0000 N   0  0  0  2  0  0  0  0  0  1  0  0
    4.4821   -7.9167   -0.0000 C   0  0  0  3  0  0  0  0  0  6  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
M  END
`

When the molecule is imported this H-count is lots, and one cannot recover it neither with AddHs (you will get three H atoms per carbon) nor by looping in the atoms and adding manually the Hs as the NumImplicityHs is computed by calculateValence, which is not aware of the implicit input anymore.

This is a weird effect when you run reactions, and the lack of correct hydrogens generates substructure matches that are not wanted.

A solution is to export everything in SMARTS, with explicit hydrogens. At that point the H atoms are correctly added, and the reactions are working like a charm (ouch, pun ?!). Still, there are lots of MOL files around and I'm sure a fix would help many users when running reactions / importing molecules.

I played with the code, and my feeling is that a possible solutions would be adding explicit hydrogens while reading the block, and creating automatic bonds on the reference atom - I don't see a case where this would create weird behavior as adding "implicit" hydrogens in those editors is a very intentional procedure.

Anyway, hope it's more clear

**Comment by greglandrum** [comment]
That's not a valid mol block (there are at least some blank lines missing).
When you paste mol blocks into github comments, please make sure the whole mol block pastes in and be sure to surround them with triple back quotes so that they are rendered without formatting.

**Comment by riccardosabatini** [comment]
Yup, sorry - edited

**Comment by greglandrum** [comment]
Ok, got it, and I see the problem.

The equivalent field in V3000 mol blocks is `HCOUNT`, which is handled correctly: producing query atoms which require the specified number of Hs to be present.

I'll fix the V2000 parser to behave the same way.

**Comment by riccardosabatini** [comment]
Fantastic, thanks much !
