### ISSUE TITLE
leak in the MinimalLib?

### ISSUE THREAD

**Issue by eloyfelix** [rdkit/rdkit#4102]
MinimalLib gets memory hungry when iterating

using the same code without generating the smiles: https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/simple.py

```python
import ctypes

rdk = ctypes.cdll.LoadLibrary('./librdkitcffi.dylib')
rdk.get_mol.restype = ctypes.c_void_p
rdk.free_ptr.argtypes = [ctypes.c_void_p]

for i in range(1000000):
    sz = ctypes.c_size_t()
    mol = rdk.get_mol(b'CCC(O)C(C(=O)O)C', ctypes.byref(sz), b'')
    rdk.free_ptr(mol)
```
![image](https://user-images.githubusercontent.com/1122541/117054141-b7861880-ad11-11eb-936c-5509b60e500f.png)

**Comment by greglandrum** [comment]
Yep, that's an oversight in `get_mol()` and `get_qmol()`

**Comment by greglandrum** [comment]
Thanks for the bug report!

**Comment by MichelML** [comment]
@greglandrum any way this can be released as a patch sooner ?

I use it extensively and from time to time it makes the UI disappear because of an out-of-memory error.

**Comment by greglandrum** [comment]
@MichelML, Since this was a patch to unreleased code, I'm guessing you're asking if it's possible to do a new build of the CFFI wrappers? I just ran one and the binaries should be available here: https://dev.azure.com/rdkit-builds/RDKit/_packaging?_a=feed&feed=rdkit_cffi

**Comment by DavidACosgrove** [comment]
Hi Michel,
If this is a Javascript thing, have you tried calling the molecule delete method?  I had out-of-memory problems in my RDKit JS app, and that cured it:
'''
let mol = rdkit.get_mol('c1ccccc1');
// do some stuff
mol.delete();
'''
HTH,
Dave

**Comment by eloyfelix** [comment]
Hi Michel, 

If you build on the latest RDKit stable release the memory leak bug is not yet present. This bug appeared with the refactor to add the librdkitcffi that allows other programming languages than JS to call the MinimalLib.

Deleting the molecule as David suggests should fix this for you.

Eloy

**Comment by MichelML** [comment]
Sorry guys it was for JS usage.

Thanks @DavidACosgrove , that's probably what I needed. I was only nullifying the mol after `// do stuff` thinking it would be gargabe collected automatically, but I am probably wrong.

Thanks for all the feedback to the three of you.

**Comment by ptosco** [comment]
@MichelML As David mentioned you need to explicitly delete each C++ object calling `delete` on it from JS or the heap will grow indefinitely:
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-management

**Comment by MichelML** [comment]
Thanks @ptosco , Learned something today!
