### ISSUE TITLE
support reading SMILES that start with a branch

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#4130]
**Is your feature request related to a problem? Please describe.**
rdkit does not want to read the following SMILES:
```
(c2cc(N3CCOC[C@@H]3C)nc(N4CC5CCC(C4)O5)n2)c0cnc1ccccc1c0
```
Many program read it correctly (e.g. Chemaxon's mview).

**Describe the solution you'd like**
Understand this SMILES as the branch being attached to the first
atom right after the branch.

**Describe alternatives you've considered**
Rewriting by hand the SMILES, but that's just a workaround.

**Additional context**

I agree such a SMILES is not standard, but even opensmiles.org does not specify
that a SMILES must not start with a branch.

**Comment by greglandrum** [comment]
I'm ambivalent about this one since I think it's really confusing. 
Still, you're right that neither the Daylight SMILES page nor the OpenSMILES documentation clearly say that this form isn't allowed.

**Comment by bp-kelley** [comment]
I think it's a bad smiles and will stand behind that.

OpenSmiles looks like it enforces an atom _before_ the branch in the definition:

```
branched_atom ::= atom ringbond* branch*
```

I'm more concerned about the aromatic hydrogen

```
[C@@h]
```

out of curiosity, what package is generating these smiles?

**Comment by greglandrum** [comment]
@bp-kelley : the aromatic SMILES is just because @UnixJunkie didn't quote the SMILES string.
If you forget that then `[C@@H]` renders as [C@@H]

**Comment by UnixJunkie** [comment]
@bp-kelley just a prototype software under development. However, the fact that chemaxon's mview can read them
hints that some more software in the wilde can produce such SMILES.
I could modify my software to not produce those.
Maybe rdkit could accept those if the right boolean is turned on in the Chem.MolFromSmiles function.
I also think that rdkit could explicitely say that it does not support reading in such SMILES and throw a very explicit error about this.
@bp-kelley is right that the opensmiles specification does not say "a SMILES string cannot start with a branch" however he read their grammar more carefuly than me, and the grammar indeed says "a SMILES string cannot start with a branch".

**Comment by bp-kelley** [comment]
I’m not convinced.  OpenEye can’t read them either and have multiple employees that worked at Daylight, but I’ll leave this one up to Greg.

**Comment by rvianello** [comment]
maybe allowing leading branch components could require some explicit convention about the implied ordering of substituents around a chiral center, also in case multiple leading branches were allowed? or would the base rules still suffice? if the atoms in the smiles are ordered according to a traversal of the represented molecular graph, a leading branch wouldn't be possible (right?), so it may be not obvious if (C)[C@H](F)I would be equivalent to C[C@H](F)I or to [C@H](C)(F)I, I think the latter feels more consistent with the general rules, although the former looked nicer at first. If multiple leading branches are present then it may be not clear to me if they should be recursively repositioned after the first atom, or as a block, to preserve their order. (sorry in case the comment doesn't make sense, I would have bet the limitation was explicitly stated somewhere on the daylight site)

**Comment by vfscalfani** [comment]
From the Daylight documentation [1]: "In all cases, the implicit connection to a parenthesized expression (a "branch") is to the left."

This then suggests to me that you can't start a SMILES with a branch, since there is no atom to the left.

Also, a slightly different but related consideration is that if you enclose a SMILES in parentheses, it becomes SMARTS syntax [2], not sure if that would cause other issues.

[1] https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html
[2] https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html

**Comment by UnixJunkie** [comment]
Ok, the consensus seems to be that we should not support this case.
Thanks for the feedback from so many experts.
