### ISSUE TITLE
Parse SDF - ERROR: Problems encountered parsing data fields 

### ISSUE THREAD

**Issue by leonqli** [rdkit/rdkit#4139]
Got weird errors, some molecules will be ignored.. For example, it will ignored the record with id: 0000050000 in this file [x.sdf.gz](https://github.com/rdkit/rdkit/files/6481835/x.sdf.gz). The error message goes like:

[23:11:19] ERROR: Problems encountered parsing data fields
[23:11:19] ERROR: moving to the beginning of the next [molecule]([url](url)) 

Thanks for your help!

**Comment by ptosco** [comment]
@leonqli your SDF file is out of spec.

From the SD file spec:
"A [Data] value can extend over multiple lines containing up to 200 characters each. A blank line
terminates each data item."
http://help.accelrysonline.com/ulm/onelab/1.0/content/ulm_pdfs/direct/reference/ctfileformats2016.pdf

In your SDF files blank lines actually contain a space character at the beginning of the line:
```
$ gunzip -c x.sdf.gz | cat -A | less
[...]
> <PUBCHEM_EXT_DATASOURCE_REGID>$
0000038266$
 $  # The space at the beginning of the line should not be there
> <PUBCHEM_SUBSTANCE_COMMENT>$
Natural Product$
 $  # The space at the beginning of the line should not be there
[...]
```

If you fix that issue, the SDF file properties will be correctly parsed by RDKit:
```
import re
import gzip
from rdkit import Chem

with gzip.open("x.sdf.gz", "rb") as hnd:
    data = hnd.read().decode("utf-8")
rx = re.compile(r"^ +$", re.MULTILINE)
data = rx1.sub("", data)
suppl = Chem.SDMolSupplier()
suppl.SetData(data)
for mol in suppl:
    assert mol
```
Closing as this is not an RDKit bug but a problem with input.

**Comment by leonqli** [comment]
Thank you so much, @ptosco! Got to learn this.
