### ISSUE TITLE
Possibly wrong description of fragments in docuementation

### ISSUE THREAD

**Issue by zhikaili** [rdkit/rdkit#4141]
Hi, 

I notice that rdkit.Chem.Fragments.fr_COO and rdkit.Chem.Fragments.fr_COO2 have the same description in the documentation:
![image](https://user-images.githubusercontent.com/76140761/118387383-d9a46280-b650-11eb-983c-f4e5694991f3.png)

May I ask whether they are really the same thing?

Thank you!

**Comment by ptosco** [comment]
@zhikaili You can look up the SMARTS definitions of those functional groups in `Data/FragmentDescriptors.csv`:

```
fr_COO  "Number of carboxylic acids"    [#6]C(=O)[O;H,-1]       "[#6]C(=O)[OH] or [#6]C(=O)[O-]"
fr_COO2 "Number of carboxylic acids"    [CX3](=O)[OX1H0-,OX2H1] "[#6]C(=O)[OH] or [#6]C(=O)[O-]"
```
While the comment has probably been copy-pasted and is inaccurate, there are some differences between the two patterns.
IMHO the `fr_COO2` is more specific for carboxylic acids and also includes formic acid, (thio)carbonic acid, carbamic acid and their derivatives.
`fr_COO` only matches carboxylic groups attached to carbon and will potentially match strange things like protonated esters:
```
formic_acid = Chem.MolFromSmiles("C(=O)O")
formate = Chem.MolFromSmiles("C(=O)[O-]")
carbamic_acid = Chem.MolFromSmiles("NC(=O)O")
carbonic_acid = Chem.MolFromSmiles("OC(=O)O")

fr_COO = Chem.MolFromSmarts("[#6]C(=O)[O;H,-1]")
fr_COO2 = Chem.MolFromSmarts("[CX3](=O)[OX1H0-,OX2H1]")

formic_acid.HasSubstructMatch(fr_COO)
False

formic_acid.HasSubstructMatch(fr_COO2)
True

formate.HasSubstructMatch(fr_COO)
False

formate.HasSubstructMatch(fr_COO2)
True

carbamic_acid.HasSubstructMatch(fr_COO)
False

carbamic_acid.HasSubstructMatch(fr_COO2)
True

carbonic_acid.HasSubstructMatch(fr_COO)
False

carbonic_acid.HasSubstructMatch(fr_COO2)
True

protonated_acetate_ester = Chem.MolFromSmiles("CC(=O)[OH+]C")

protonated_acetate_ester.HasSubstructMatch(fr_COO)
True

protonated_acetate_ester.HasSubstructMatch(fr_COO2)
False
```

**Comment by zhikaili** [comment]
Hi, 

Thank you for your detailed reply!
