### ISSUE TITLE
Possible bug with Smart-Smiles with Oxygen Free-Radical

### ISSUE THREAD

**Issue by jingxingzhi** [rdkit/rdkit#4154]
**Describe the bug**
Using Chem.MolToSmarts  may change the structure  of oxygen free radicals

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.
```
from rdkit import Chem
mol = Chem.MolFromSmiles('C[O]')
Draw.MolToImage(mol)
molsmatrs=Chem.MolToSmarts(mol)
print(molsmatrs)#We get '[#6]-[#8]'
molfromsmatrs=Chem.MolFromSmarts(molsmatrs)
Draw.MolToImage(molfromsmatrs)
```
which  is different from mol.
while,
```
print(Chem.MolToSmiles(Chem.MolFromSmarts( '[#6]-[#8]')))
Draw.MolToImage(Chem.MolFromSmarts( '[#6]-[#8]'))
print(Chem.MolToSmiles(Chem.MolFromSmarts( '[#6]-[#8H0]')))
Draw.MolToImage(Chem.MolFromSmarts( '[#6]-[#8H0]'))
```
also work wrong
it is different from mol
Not only oxygen free radicals， using 'C[N]'，'C[C]' ，'C[S]'  will also get the wrong result.
but
`
Chem.MolToSmiles(Chem.MolFromSmarts( '[#6]-[#7H1]'))
`
and
`
 Chem.MolToSmiles(Chem.MolFromSmarts( '[#6]-[#6H2]'))
`
and
`
Chem.MolToSmiles( Chem.MolFromSmarts( '[#6]-[#6H]'))
`
work right
**Expected behavior**
we want get some smarts can express oxygen free radical structure as Chem.MolFromSmiles('C[O]'）
**Screenshots**
 ![1621421585(1)](https://user-images.githubusercontent.com/37572298/118801991-35325280-b8d4-11eb-8684-55f66d396aeb.png)
![1621421620](https://user-images.githubusercontent.com/37572298/118801996-36637f80-b8d4-11eb-8674-dba2692c3762.png)
![1621421660(1)](https://user-images.githubusercontent.com/37572298/118801997-36fc1600-b8d4-11eb-834c-a0e97690cc7a.jpg)
![1621421776(1)](https://user-images.githubusercontent.com/37572298/118802005-3794ac80-b8d4-11eb-80a6-29c2ccc95764.jpg)
![1621421887(1)](https://user-images.githubusercontent.com/37572298/118802007-382d4300-b8d4-11eb-85b6-b674151609ac.jpg)

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.2
 - OS: win10 20H2
 - Python version (if relevant): 3.8
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by greglandrum** [comment]
Hi @jingxingzhi : SMARTS doesn't have a way to directly encode that an atom has a radical on it, so there's no way for the RDKit to do this automatically.

**Comment by jingxingzhi** [comment]
> Hi @jingxingzhi : SMARTS doesn't have a way to directly encode that an atom has a radical on it, so there's no way for the RDKit to do this automatically.
Hi greglandrum 
actually SMARTS can encode that an atom has a radical,
`
Chem.MolToSmiles(Chem.MolFromSmarts( '[#6]-[#7H1]'))
Chem.MolToSmiles(Chem.MolFromSmarts( '[#6]-[#6H2]'))
Chem.MolToSmiles(Chem.MolFromSmarts( '[#6]-[#6H]'))
`
will works well 
![1621472801(1)](https://user-images.githubusercontent.com/37572298/118903621-bf1d0280-b94a-11eb-9cf2-051e7098c7f9.jpg)
so I want to know how to express C[O] like C[NH] in smarts
I need to write a reaction that 
`AllChem.ReactionFromSmarts('[#6]-[#8:1]-[#6:2]>>[#6:2].[#8H0:1]-[#6:2]')`
but is not wroks

**Comment by jingxingzhi** [comment]
i find it was a big issue, which was beyound my first question, i will close this issue
