### ISSUE TITLE
Odd drawing behavior with radicals and MolsToGridImage

### ISSUE THREAD

**Issue by pstjohn** [rdkit/rdkit#4156]
Occurs with rdkit version 2021.03.02, (and 2021.03.01, but this seems to be a recent change. I could try to track down an older rdkit version that didn't have this issue if that's helpful)

https://gist.github.com/pstjohn/d7887e6349009e414bd84a18fbc6b952

Including a radical in a molecule for MolsToGridImage seems to affect the scaling considerably, but oddly only if it's not in the first position. 
![Screen Shot 2021-05-19 at 9 49 02 AM](https://user-images.githubusercontent.com/2576846/118843597-72242800-b887-11eb-9321-18d269ebdd23.png)

It doesn't happen with all radicals though, smaller ones don't trigger the rescaling.
![Screen Shot 2021-05-19 at 9 49 46 AM](https://user-images.githubusercontent.com/2576846/118843710-8c5e0600-b887-11eb-9e9e-9f279fd8f7fb.png)

**Comment by DavidACosgrove** [comment]
Groan. It’s my least favourite part of the drawing code. I’ll take a look tomorrow. Thanks for the clear and concise report. 
Dave
