### ISSUE TITLE
Document new matching strategy for RGroupDecomposer (matchingMol -> then choose RGroups)

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#4168]
This will help future devs and myself when I come back in a month...

**Comment by bp-kelley** [comment]
@jones-gareth I'm happy to do this, but it is probably fresher in your mind.

**Comment by jones-gareth** [comment]
I think I've forgotten it myself!

I was going to do a PR to move code from RGroupCore.h into RGroupCore.cpp.  I can document the matching methods at the same time.

**Comment by greglandrum** [comment]
Fixed in #4189
