### ISSUE TITLE
bug in MDLParser.cpp when reading a rxn file in v3000 format that contains agents

### ISSUE THREAD

**Issue by jungb-basf** [rdkit/rdkit#4183]
Error reading rxn files in V3000 format that contains agents
-----------------------------------------------------------------

if a rxn file contains agents the function ParseV3000RxnBlock stops with the error message "BEGIN AGENT line not found", 

see line 271:

if (tempStr.length()< 14 || tempStr.substr(0, 14) != "BEGIN AGENT") {
              throw FileParseException("BEGIN AGENT line not found");
}

the string length should be compared with 11 instead of 14.

the same in line 298:

if (tempStr.length() &lt; 12 || tempStr.substr(0, 12) != "END AGENT") {
              throw FileParseException("END AGENT line not found");
}

please replace 12 by 9

Thanks
Brigitte

**Comment by bp-kelley** [comment]
Thanks good catch and diagnosis.
