### ISSUE TITLE
[MinimalLib] Add number of heavy atoms to descriptors

### ISSUE THREAD

**Issue by apahl** [rdkit/rdkit#4184]
Hi,

thanks a lot for the new MinimalLib CFFI bindings, this is a really great initiative.

I am experimenting with the bindings to interface with Rust and this is working great so far.

When looking through the available descriptors, I was missing the number of heavy atoms,  
Would it be possible to add this property to the list of descriptors?

Many thanks to all who contribute to the awesome RDKit project.

Kind regards,  
Axel

**Comment by apahl** [comment]
So I found out, that the number of heavy atoms can be retrieved from the output of `get_json`, by counting the number of atoms in the molecule:

e.g., in Rust:  
`json["molecules"][0]["atoms"].as_array().unwrap().len();`

Please let me know if I should close this issue or if it is still worth considering to put it in the descriptors, since e.g. ' NumHeteroatoms' are also part of them.

KR Axel

**Comment by greglandrum** [comment]
Hi @apahl : I agree that this should be one of the descriptors that's part of the standard set. Since it's otherwise easy to calculate this from python we've just never added it, but that can be fixed. :-)

**Comment by greglandrum** [comment]
This was added in #4200
