### ISSUE TITLE
Spacing between atom symbols and bond lines in 2d plot

### ISSUE THREAD

**Issue by HesamGit** [rdkit/rdkit#4188]
It seems to me that the distance between atom symbols and bond lines is too small sometimes in 2d plot and it becomes hard to read the symbols. I looked into some options in IPythonConsole.drawOptions but could not figure it out. Is it possible to adjust such details?

IPythonConsole.drawOptions.bondLineWidth = 1
mol = Chem.MolFromSmiles('CC(=O)O[C@H]1CC[C@@]2(C)[C@@H](CC(=O)[C@@H]3[C@@H]4CCC(=O)[C@@]4(C)CC[C@H]32)C1')
mol

**Comment by DavidACosgrove** [comment]
HI @HesamGit.  That's not a valid SMILES string (only one ring locant 2) so it's not possible to see what you mean.  Can you please provide a correct SMILES string, a picture of the drawing you object to and also the version of RDKit you're using and how you installed it.  It is very difficult to do anything without this information.

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
