### ISSUE TITLE
cannot kekulize the scaffold after MurckoDecompose

### ISSUE THREAD

**Issue by zhikaili** [rdkit/rdkit#4214]
Hi,

I try extracting the scaffold of a molecule (whose smiles string is 'Cc1c2cc(Br)ccc2nc-[n+]1=O'), but find that the output mol object unkekulized and hence cannot be drawn. Besides, applying AllChem.MolFromSmiles() to the output scaffold's smiles string also triggers an error about being unkekulized (but with different unkekulized atoms):

![image](https://user-images.githubusercontent.com/76140761/120925367-e6c1e800-c70a-11eb-9f98-d9d55e56795b.png)

Btw, the output scaffold's smiles string is 'O=[n+]1[c-]nc2ccccc2c1', and can be visualized via https://pubchem.ncbi.nlm.nih.gov/ as shown below:

![image](https://user-images.githubusercontent.com/76140761/120925373-ee818c80-c70a-11eb-833e-05d964e1fcb9.png)

May I ask whether the error (i.e., being unkekulized) means that the output scaffold is chemically invalid? If not, how to visualize it via rdkit?

Thank you!

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested informatio and reopen the issue and then we'll try to help.
