### ISSUE TITLE
Old stereochemistry perception discards ring stereo in spiro systems

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#4215]
**Describe the bug**

In some cases `assignStereochemistry()` discards stereo markers for molecules which have ring stereo and spiro linkages.
It looks like the new stereo code doesn't have this problem

Here's the demo:
```
>>> m = Chem.MolFromSmiles('C[C@H]1CCC2(CC1)CC[C@H](C)C(C)C2')
... Chem.MolToSmiles(m)
'CC1CCC2(CC1)CC[C@H](C)C(C)C2'
>>> m = Chem.MolFromSmiles('C[C@H]1CCC2(CC1)CC[C@H](C)C(C)C2',sanitize=False)
>>> Chem.SanitizeMol(m)
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
>>> Chem.FindMolChiralCenters(m,force=True,includeUnassigned=True,includeCIP=True,useLegacyImplementation=False)
[(1, 'Tet_CW'), (4, '?'), (9, 'S'), (11, '?')]
```
m without the stereo removed:
![image](https://user-images.githubusercontent.com/540511/120967440-bc524800-c767-11eb-99f1-23272f150407.png)

removing the true chiral center causes things to work again:
```
>>> m2 = Chem.MolFromSmiles('C[C@H]1CCC2(CC1)CC[C@H](C)CC2')
>>> Chem.MolToSmiles(m2)
'C[C@H]1CCC2(CC[C@H](C)CC2)CC1'
>>> Chem.FindMolChiralCenters(m2,force=True,includeUnassigned=True,includeCIP=True,useLegacyImplementation=False)
[(1, 'Tet_CW'), (4, '?'), (9, 'Tet_CCW')]
```
m2:
![image](https://user-images.githubusercontent.com/540511/120967454-c116fc00-c767-11eb-9a4d-8eed5710dc04.png)

Specified stereo on the spiro atom is discarded with the old code but preserved with the new:
```
>>> m3 = Chem.MolFromSmiles('C[C@H]1CC[C@@]2(CC[C@H](C)CC2)CC1')
>>> Chem.MolToSmiles(m3)
'C[C@H]1CCC2(CC[C@H](C)CC2)CC1'
>>> m3 = Chem.MolFromSmiles('C[C@H]1CC[C@@]2(CC[C@H](C)CC2)CC1',sanitize=False)
>>> Chem.SanitizeMol(m3)
rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
>>> Chem.FindMolChiralCenters(m,force=True,includeUnassigned=True,includeCIP=True,useLegacyImplementation=False)
[(1, 'Tet_CW'), (4, '?'), (9, 'S'), (11, '?')]
```

m3 without the stereo removed:
![image](https://user-images.githubusercontent.com/540511/120967477-c6744680-c767-11eb-9b22-c43da8c134a5.png)

**Configuration (please complete the following information):**
 - RDKit version: master and previous versions
 - OS: all

**Comment by greglandrum** [comment]
After spending a fair amount of time on this, I think I've decided not to fix it in the old stereochemistry code.
The new stereochemistry perception code works fine with these molecules (once #4279 is fixed).
I plan to use this as the "motivation" to go ahead and make the new stereochemistry code available in all the molecule parsers and explore making it the default.

**Comment by wopozka** [comment]
@greglandrum 
Hi. I wonder whether anything was done in this bug. I've just checked compound C[C@H]1C[C@]2(C1)C[C@H](N)C2 in rdkit 2022.03.01 and roundtrip Chem.MolToSmiles(Chem.MolFromSmiles('C[C@H]1C[C@]2(C1)C[C@H](N)C2')) gives C[C@H]1CC2(C1)C[C@H](N)C2 - so stereochemistry on the spiro atom is lost.

**Comment by bp-kelley** [comment]
Removing formatting from the smiles strings
```
C[C@H]1C[C@]2(C1)C[C@H](N)C2 
C[C@H]1C[C@]2(C1)C[C@H](N)C2
C[C@H]1CC2(C1)C[C@H](N)C2 
```

**Comment by wopozka** [comment]
@greglandrum
I've just check whether the problem does exist in 2022.9 version of rdkit, and it looks it is still there.

**Comment by e-kwsm** [comment]
Spiropentadiene derivatives:

```python
>>> from rdkit import __version__
>>> __version__
'2023.09.5'
>>> from rdkit import Chem
>>> # stereocenters of dichloro ones are lost
>>> Chem.MolToSmiles(Chem.MolFromSmiles("FC1=C[C@]12C=C2F"))
'FC1=CC12C=C2F'
>>> Chem.MolToSmiles(Chem.MolFromSmiles("FC1=C[C@@]12C=C2F"))
'FC1=CC12C=C2F'
>>> # stereocenters of chlorofluoro ones are kept
>>> Chem.MolToSmiles(Chem.MolFromSmiles("FC1=C[C@]12C=C2Cl"))
'FC1=C[C@]12C=C2Cl'
>>> Chem.MolToSmiles(Chem.MolFromSmiles("FC1=C[C@@]12C=C2Cl"))
'FC1=C[C@@]12C=C2Cl'
```
