### ISSUE TITLE
MolFromSmiles('c1ccccc1) illegal instruction (core dumped) -not Atom processor

### ISSUE THREAD

**Issue by Chem4ai** [rdkit/rdkit#4219]
-----------------------------------------
PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT
If you have a question about the RDKit or aren't sure if what you're seeing is the right behavior please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

Please help us help you: We normally need the information below in order to answer questions or understand bug reports. If you do not provide the information requested we may not be able to help you and will probably close the issue.
-----------------------------------------

**Describe the bug**
After installing rdkit fresh with anaconda on Ubuntu 20.04LTS, a simple test triggers a core dump with the error illegal instructure

**To Reproduce**
conda create -c rdkit -n rdk2 rdkit
conda activate rdk2
python
Python 3.7.10 (default, Feb 26 2021, 18:47:35)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>from rdkit import Chem
>>> mol = Chem.MolFromSmiles('c1ccccc1')
Illegal instruction (core dumped)

**Expected behavior**
should simply create the object

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.01
 - OS: Ubuntu 20.04.2 LTS
 - Python version (if relevant): 3.7.10
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? default (conda-forge)
 - If you are not using conda: how did you install the RDKit?

**Additional context**
A previous report of this problem was closed after concluding that it was due to running on an Atom processor. 
I attach the lscpu to show that it is an Intel Quad core Q6600. Certainly not the newest of cpu but I would hope not a problem.

[lscpu.txt](https://github.com/rdkit/rdkit/files/6611372/lscpu.txt)

**Comment by bp-kelley** [comment]
RDKit and some of it's companion packages make use of newer instructions that simply don't exist on a 14 year old processor.     Do you have issues with numpy?  I believe they also use some of the same instructions.

I think, perhaps, the best solution is for you to make your own build of the RDKit, it's pretty easy with conda and I'd be happy to show you how to do this, but I do worry that the dependencies pulled from conda-forge might also cause issues.

**Comment by Chem4ai** [comment]
Hello Brian,

Thank you for the quick reply on this. I will gladly take you up on your offer. Wow, I have not tracked how old that processor is. I have been doing all my chemistry work with MOE and SVL for a long time. I use an aging surfacebook (v1) with many problems for most office work but I have that machine there as well.  I am now looking at resuming some consulting work and wanted to see what I could do with more open source bits. I use that ubuntu machine for some routine things, and non-chemistry bits including some postgres databases I built and want to extend to CIX with rdkit.

Believe it or not, my coding experience started with Fortran in the 80s, then C, then Perl, then lots of SVL but I never really got into Python. That’s another reason to dive into rdkit. All this is to say, I don’t think I have used numpy (yet) either, but I could well imagine it is built using newer instructions.

Dominic Ryan

DRI2, LLC
Technologies and Medicinal Chemistry
Diligence, strategy and projects

Confidentiality Notice: This e-mail, including any attachments, is a confidential business communication, and contains information that is confidential, proprietary and/or privileged. This e-mail is intended only for the individual(s) to whom it is addressed, and may not be saved, copied, printed, disclosed or used by anyone else. If you are not the (an) intended recipient, please immediately delete this e-mail from your computer system and notify the sender.

**Comment by Chem4ai** [comment]
To the moderator, I repeated the install on a surface book with no problems. I suggest closing this but link it to the other related closed report and add a comment that the hardware limitations go beyond Atom processors and include at least up to Intel Q6600.
