### ISSUE TITLE
When using the Reaction module, the hydrogen on the chiral carbon cannot be eliminated correctly

### ISSUE THREAD

**Issue by Tong-Du** [rdkit/rdkit#4221]
**Describe the bug**
When using the Reaction module, the hydrogen on the chiral carbon cannot be eliminated correctly.

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem import rdChemReactions
rxn = rdChemReactions.ReactionFromSmarts("[C:1][C:2]>>[C:1]=[C:2]")

mol_1 = Chem.MolFromSmiles('CC(Cl)Br')
mol_2 = Chem.MolFromSmiles('C[C@H](Cl)Br')

products = rxn.RunReactants((mol_1, ))
p_mol = products[0][0]
Chem.SanitizeMol(p_mol)
print(Chem.MolToSmiles(p_mol)) # C=C(Cl)Br

products = rxn.RunReactants((mol_2, ))
p_mol = products[0][0]
Chem.SanitizeMol(p_mol)
print(Chem.MolToSmiles(p_mol)) # error

# Output
C=C(Cl)Br
---------------------------------------------------------------------------
AtomValenceException                      Traceback (most recent call last)
<ipython-input-21-548952798c3e> in <module>
     16 products = rxn.RunReactants((mol_2, ))
     17 p_mol = products[0][0]
---> 18 Chem.SanitizeMol(p_mol)
     19 print(Chem.MolToSmiles(p_mol))

AtomValenceException: Explicit valence for atom # 1 C, 5, is greater than permitted
```

**Expected behavior**
```
# Output
C=C(Cl)Br
C=C(Cl)Br
```

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.1
 - OS (not relevant): Red Hat / Windows10
 - Python version (not relevant):3.7.9
 - Are you using conda? Yes / channel rdkit

**Comment by bp-kelley** [comment]
To make most reactions sane, you need to deal with hydrogens which can be tricky as they are implicit in smiles.  Here you are adding a double bond but not removing hydrogen, this reaction should do what you want:

```
rxn = rdChemReactions.ReactionFromSmarts("[CH1:1][C:2]>>[CH0:1]=[C:2]")
```

**Comment by Tong-Du** [comment]
> To make most reactions sane, you need to deal with hydrogens which can be tricky as they are implicit in smiles. Here you are adding a double bond but not removing hydrogen, this reaction should do what you want:
> 
> ```
> rxn = rdChemReactions.ReactionFromSmarts("[CH1:1][C:2]>>[CH0:1]=[C:2]")
> ```
Thank you! It's great!
