### ISSUE TITLE
Topological Steric Effect Index (TSEI)

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#4229]
### Topological steric effect index (TSEI)
Cao and Liu, J Chem Inf Comput Sci 44(2), 678-687, 2004.
[dx.doi.org/10.1021/ci034266b](https://pubmed.ncbi.nlm.nih.gov/15032550/)

This is a per-atom numerical descriptor meant to describe the steric hindrance around a given atom.  

This descriptor was requested by a user of our product, and I threw together an implementation at the time.  What I put together seems to match the values in the paper given for alkyl groups, but I don't have access to another implementation in order to check the results.  ChemAxon's [website](https://docs.chemaxon.com/display/docs/topological-analysis-plugin.md) has a picture of steric effect index for some molecules and my results don't match theirs exactly (but are close).

I would be happy to contribute what I have to the RDKit, but I'd need some guidance as to which directories to add the files to and how to integrate it with the rest of the system.

It would also be helpful if someone with access to ChemAxon could compare the different results and see if I've gone wrong somewhere.

**Comment by z-linlinlin** [comment]
Is this method integrated into rdkit?
It will be very helpful for me

**Comment by greglandrum** [comment]
It hasn’t been integrated. @jasondbiggs if or have code with a prototype implementation, I could take a look

**Comment by jasondbiggs** [comment]
I have code for this, I will dust off my rdkit build and make a branch.

The interface I have in mind would be something like 
```
void computeStericEffectIndex(const RDMol &mol) {
  // compute values and store as a computed property on each atom
}
```
Just looking at the code I would think to make a header/cpp in GraphMol/Descriptors and put it there.

**Comment by greglandrum** [comment]
I think it might make sense to have the function return a vector of doubles instead of setting the atom properties. It seems like people are likely to want to have all the values at once?
