### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by blazerygy** [rdkit/rdkit#4253]
compile error：
![image](https://user-images.githubusercontent.com/16797849/122344885-d961f480-cf79-11eb-81fc-8d544d10bf3c.png)
how to fix？thx

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
