### ISSUE TITLE
[Enhancement] Allow atom searching in Chem.findAtomEnvironmentOfRadiusN (i.e atomMap hyper-parameter) & Request allow-clearing (noLimit)

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#4262]
I am thinking to expand the function Chem.findAtomEnvironmentOfRadiusN to allow further atom searching without increasing much data complexity.

* Hyper-parameter "noLimit" (bool):
If noLimit=True --> we disable result clearing that sub_radius is smaller than request. 
Example: CH4 --> If radius=4 (useHs=True), the function would return an empty list. However, we want to take every atoms in the defined 'radius'. which would return something like this [0, 1, 2, 3].
Although this may get confusing about hyper-parameter "radius" (which could be adapt to "maxRadius"), I believed this would help if we want to take 'active' environments within the specific region without worrying whether the selected molecule can reach that domain. 

Code Help:
Original:
```
if (i != radius) {    
// this happens when there are no paths with the requested radius.    
// return nothing in this case:    
   res.clear();   
   res.resize(0);  
}
```

New:
```
if (i != radius && !noLimit) {    
// this happens when there are no paths with the requested radius.    
// return nothing in this case:    
   res.clear();   
   res.resize(0);  
}
```

* atomMap hyper-parameter:
Similar to "atomMap" hyper-parameter of PathToSubmol, we saved every atom index to specific map where the key is its radius bound, counting from "rootedAtAtom"
For example, C2H6: (useHs=True)
If radius=2, rootedAtAtom=0 --> atomMap: {0: [0], 1: [1, 2, 3, 4], 2: [5, 6, 7]}
If radius=3, rootedAtAtom=0 --> atomMap: {0: [0], 1: [1, 2, 3, 4], 2: [5, 6, 7], 3: []}

For example, CH3-N=CH2: (useHs=True)
If radius=2, rootedAtAtom=1 (Nitrogen) --> atomMap: {0: [1], 1: [0, 2], 2: [3, 4, 5, 6, 7]}
If radius=3, rootedAtAtom=0 --> atomMap: {0: [0], 1: [1, 2, 3, 4], 2: [2], 3: [5, 6, 7]}

**Comment by greglandrum** [comment]
I think the idea is good, but I would prefer a different function name: findAllAtomEnvironmentsOfRadiusMtoN(), analogous to this function: https://github.com/rdkit/rdkit/blob/1702a227e243a111dfbd339b288ead09929d2880/Code/GraphMol/Subgraphs/Subgraphs.h#L68

**Comment by IchiruTake** [comment]
> I think the idea is good, but I would prefer a different function name: findAllAtomEnvironmentsOfRadiusMtoN(), analogous to this function:
> 
> https://github.com/rdkit/rdkit/blob/1702a227e243a111dfbd339b288ead09929d2880/Code/GraphMol/Subgraphs/Subgraphs.h#L68

Yes, I agree. However, adding extra parameter like this does not actually increase data & time complexity. Although I agree the current function name is somehow not represented full meaning. 

I think we have two options but there are some side effects to consider. 
* 1: Change the name of current function & adding extra hyper-parameter: This would make it clearer to understand despite backward incompatibility
* 2: Make the new function that similar with extra hyper-parameter: Although it allows backward incompatibility, it would be disaster if bug was found in old function and we have to twist both function for consistency

The best way to handle is that don't change current function name, the only thing you need to do is just adding extra hyper-parameter where default value is as same as the original. However, the below implementation may confused with some partner such as `FindAllSubgraphsOfLengthN`, `FindAllSubgraphsOfLengthMToN`, `FindAllPathsOfLengthN`; which required to fix all these three to get consistency

Example: 
Current: `FindAtomEnvironmentOfRadiusN(mol, radius, rootedAtAtom, useHs: bool = False):`
New: `FindAtomEnvironmentOfRadiusN(mol, radius, rootedAtAtom, useHs: bool = False, noLimit: bool = False, atomMap: Dict ={}):`

By the way, I am doing something with large dataset where molecular graph is in diverse range, from small molecules to large molecules. This implementation can somehow help to get data from small molecules without considering their 'current' RDKit implementation. Let's say we have a bunch of small molecules in the main circuit, to considering any bond or affection, we might need to view it as a full structure, rather than find its reachable radius to enclose the domain result.

**Comment by greglandrum** [comment]
The third option is to add the new function like I suggest and then have the original `findAtomEnvironmentOfRadiusN()` function call the new function to actually do its work.

**Comment by IchiruTake** [comment]
> The third option is to add the new function like I suggest and then have the original `findAtomEnvironmentOfRadiusN()` function call the new function to actually do its work.

Is it not easier than adding extra parameter "noLimit" and "atomMap" to the original function where its default value was equivalent to original function (purpose) that will be easier to handle? 
I believed this would ensure that no extra code test is needed or by copy-paste which would confuse the user. In my view, I prefer combining function with multi-purpose rather than making extra code and copy or call the new ones

**Comment by greglandrum** [comment]
I understand your point, but I don’t like the idea of making the function name inaccurate the way you propose to do would.

**Comment by IchiruTake** [comment]
> I understand your point, but I don’t like the idea of making the function name inaccurate the way you propose to do would.

Ok, let's do it

**Comment by IchiruTake** [comment]
Since this have a PR for it, I will close this
