### ISSUE TITLE
Fallback ring finding failing on molecules with multiple fragments

### ISSUE THREAD

**Issue by avaucher** [rdkit/rdkit#4266]
**Describe the bug**
Given the two SMILES strings `c1ccccc1` and `C123C45C16C21C34C561`, `MolFromSmiles` does not work when they are concatenated, `c1ccccc1.C123C45C16C21C34C561`.

**To Reproduce**
```python
from rdkit import Chem

m1 = Chem.MolFromSmiles('c1ccccc1.C123C45C16C21C34C561')
m2 = Chem.MolFromSmiles('c1ccccc1')
m3 = Chem.MolFromSmiles('C123C45C16C21C34C561')
m4 = Chem.MolFromSmiles('C1CCCCC1.C123C45C16C21C34C561')
m5 = Chem.MolFromSmiles('C123C45C16C21C34C561.c1ccccc1')
```
`m1` is `None`, all the others are valid.
Especially, making benzene non-aromatic (-> cyclohexane) works.
Also, inverting the order works.

RDKit prints the warnings
```
[10:40:23] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:40:23] non-ring atom 0 marked aromatic
```
It looks like the first warning is generated from the second species, and switching to the approximate ring finding algorithm then fails when there is an aromatic ring in the SMILES (?).

**Expected behavior**
`m1` should not be `None`.

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.2
 - OS: Mac
 - Python version (if relevant): 3.7
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? official rdkit

**Comment by greglandrum** [comment]
Confirmed.

**Comment by greglandrum** [comment]
This is happening because the fallback to the approximate ring-finding algorithm doesn't deal properly with molecules which have multiple fragments.
