### ISSUE TITLE
[Enhancement]: Allow every bit-vect fixed-size fingerprints can be directly embedded || attached into the (Numpy) Array or return the Numpy Array

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#4273]
I am thinking about expanding extra hyper-parameter called 'destArray' which would be used to directly embedded the bit vectors of the fixed-size fingerprint into it without surpassing "ConvertToNumpyArray". 

Hyper-parameter:
"destArray": If destArray=None, everything runs normal without performance change. If destArray is a Numpy array, check the size for verification, then do the task where result was attached on "destArray". (Default dtype: int8, uint8 is preferred)

Reason: 
---> Support Faster Data Extraction on Big Data for ML + Avoid Function Call Switching of Python. Estimated Performance Improvement: 10 - 15 %

Original approach:
```
N = 1024
mol = AddHs(MolFromSmiles("COC"))
array = np.zeros(shape=(N, ), dtype=np.uint8))
bitVect = GetMorganFingerprintAsBitVect(mol, radius=2, nBits=N)
ConvertToNumpyArray(bitVect, array)
```

New approach:
```
N = 1024
mol = AddHs(MolFromSmiles("COC"))
array = np.zeros(shape=(N, ), dtype=np.uint8))
GetMorganFingerprintAsBitVect(mol, radius=2, nBits=N, destArray=array)
```

Default Call:
```
N = 1024
mol = AddHs(MolFromSmiles("COC"))
array = np.zeros(shape=(N, ), dtype=np.uint8))
GetMorganFingerprintAsBitVect(mol, ..., destArray=None)
```

The function "GetMorganFingerprintAsBitVect" is just a sample, I hope it would be implemented for AtomPairs, TopologicalTorsion, RDKFingerprint, LayeredFingerprint, etc ....

**Comment by greglandrum** [comment]
I did an implementation of this using the fingerprint generator interface in #4523
