### ISSUE TITLE
ReplaceSubstruct is cutting molecule when substruct has two connections

### ISSUE THREAD

**Issue by cjmcgill** [rdkit/rdkit#4277]
**Describe the bug**
When I use replace substruct for a substructure that is bonded into the molecule in more than one place, it cuts the molecule at the second place. This also happens when using AllChem instead of rdmolops. This happens for both SMILES and SMARTS input.

**Expected behavior**
I would expect the replaced structure to share the same connections as the initial structure.

**Screenshots**
Used the example provided in the documentation and it appears to work differently.

![image](https://user-images.githubusercontent.com/44245643/123165523-5857a100-d442-11eb-923d-17eff1328e4a.png)

![image](https://user-images.githubusercontent.com/44245643/123165315-129ad880-d442-11eb-9a70-d3fa10862944.png)

**Configuration (please complete the following information):**
 - RDKit version:  2020.09
 - OS: Ubuntu 2020.4
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge (have also tested from rmg)

**Comment by greglandrum** [comment]
`ReplaceSubstructs` is intended to be a tool for doing simple replacements. As such, it only forms a bond from the first atom in the replacement.
If you want to handle replacements with multiple attachment points (or generally want to have more flexibility) the best approach is to use the RDKit's chemical reaction code.
Here's a quick demo for your example.

I will define this function:
```
def apply_tform(rxn,mol,completeOnly=True):
    res = []
    seen = set()
    stack = [mol]
    while stack:
        m = stack.pop(0)
        ps = rxn.RunReactants((m,))
        for p in ps:
            p = p[0]
            Chem.SanitizeMol(p)
            smi = Chem.MolToSmiles(p)
            if smi in seen:
                continue
            seen.add(smi)
            if rxn.IsMoleculeReactant(p):
                stack.append(p)
                if not completeOnly:
                    res.append(p)
            else:
                res.append(p)
    return res
```

And then use it like this:
>>> rxn = rdChemReactions.ReactionFromSmarts('[O:1][C:2]>>[N:1][C:2]')
>>> ms = apply_tform(rxn,Chem.MolFromSmiles('COCCOC'))
>>> ms
[<rdkit.Chem.rdchem.Mol object at 0x7fed9d064eb0>]
>>> [Chem.MolToSmiles(x) for x in ms]
['CNCCNC']
```
You can also get all the partial replacements as well if you want:
```
>>> [Chem.MolToSmiles(x) for x in apply_tform(rxn,Chem.MolFromSmiles('COCCOC'),completeOnly=False)]
['CNCCOC', 'CNCCNC']
```
