### ISSUE TITLE
Faild to add hydrogens for 3D mol from AllChem.ConstrainedEmbed method

### ISSUE THREAD

**Issue by dalong12** [rdkit/rdkit#4286]
-----------------------------------------
**Describe the bug**
I try to generate 3D molecule by reaction with rdkit. The AllChem.ConstrainedEmbed method is a good choice for this purpose and can solve part of my problem. But at the last step,  structures were very strange when all the hydrogen were added. So what is the problem, and is there any way to correct the output structure? 

**To Reproduce**
```
def reaction_3D(reactant_3D, rxn):
    temp_3D = Chem.RemoveHs(reactant_3D)
    reactant_2D_smi = Chem.MolToSmiles(temp_3D)
    print(reactant_2D_smi)
    reactant = Chem.MolFromSmiles(reactant_2D_smi)
    products = rxn.RunReactants((reactant,))
    uniq = set()
    for mol_tuple in products:
        smi = Chem.MolToSmiles(Chem.RemoveHs(mol_tuple[0]))
        uniq.add(smi)
        print(smi)
    
    res = []
    for i in uniq:
        mol = Chem.MolFromSmiles(i, sanitize=False)
        mol.UpdatePropertyCache()
        Chem.GetSymmSSSR(mol)
        newmol=AllChem.ConstrainedEmbed(mol, temp_3D)
        newmol = Chem.AddHs(newmol)
        res.append(newmol)
    
    return res

from rdkit import Chem
from rdkit.Chem import AllChem
smi="C1(C2CCCCC2)=CC=CC=C1"
mol = Chem.MolFromSmiles(smi)
mol_3D = Chem.AddHs(mol)
AllChem.EmbedMolecule(mol_3D, randomSeed=0xf00d)
rxn = rdChemReactions.ReactionFromSmarts("[cH:1]>>[c:1][C]")
out = reaction_3D(mol_3D, rxn)
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/72644114/123615147-9c2e1a00-d837-11eb-8a4c-cb3f5317c0c0.png)

**Configuration (please complete the following information):**
 - RDKit version:  2021.03.2
 - OS: win10
 - Python version (if relevant): 3.8
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by ptosco** [comment]
@dalong12 This is not a bug - by default all added hydrogens have `(0, 0, 0)` coordinates. If you set `addCoords=True` when calling `Chem.AddHs()` you will get the 3D coordinates that you expect.
That said, you should rather add hydrogens _before_ doing the 3D embedding, not _after_.
