### ISSUE TITLE
MMPA sample case

### ISSUE THREAD

**Issue by cchang373** [rdkit/rdkit#4294]
**Describe the bug**
Tried the sample cases contained in `rdkit/Contrib/mmpa/create_mmp_db.py` and `rdkit/Contrib/mmpa/search_mmp_db.py` with the sample dataset provided. But all of the search results are giving `"None".

**To Reproduce**
`python create_mmp_db.py -m 10 <data/sample_fragmented.txt`
`python search_mmp_db.py -t mmp -m 10 <data/sample_db_input_smi.txt > sample_db_search_smi_output.txt`
It's giving me 'None' in the output file instead of the line indicated in the example.

**Expected behavior**
The output should contain the same thing within `rdkit/Contrib/mmpa/data/sample_db_search_smi_output.txt`

**Screenshots**
![image](https://user-images.githubusercontent.com/30272503/123890838-ef7e9600-d925-11eb-879b-39b95b3df279.png)

**Configuration (please complete the following information):**
 - RDKit version: 2020.03.3
 - OS: Linux
 - Python version (if relevant): python 3.6
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda create -c conda-forge -n rdkit3 rdkit
 - If you are not using conda: how did you install the RDKit?

**Comment by cchang373** [comment]
Could somebody do the same test? or point out where my code is wrong? @giallu @greglandrum @cowsandmilk

**Comment by MaoXFujita** [comment]
Yes, I'm also having this issue. @giallu Could you help figure this out?
