### ISSUE TITLE
Sanitise error: Aromatic bonds on non aromatic atom 3

### ISSUE THREAD

**Issue by haroldgrosjean** [rdkit/rdkit#4298]
Hello,

I am trying to load a protonated molecule generated by OpenEye but rdkit is unable to Sanitize it although the molecule seems correct. It complains that the 3d atom stored in the file (which is Carbon 2) is not aromatic but it clearly is.

Here is the file: [native_ligand_protonated.mol2.txt](https://github.com/rdkit/rdkit/files/6741780/native_ligand_protonated.mol2.txt)

Input:
```
from rdkit import Chem
native_ligand = './native_ligand_protonated.mol2.txt'
test = Chem.MolFromMol2File(native_ligand)
test is None
```

Returns:
```
[15:18:48] Aromatic bonds on non aromatic atom 3
[15:18:48] sanitise
True
```
I would expect the molecule to be transformed into a rdkit.Chem.rdchem.Mol object for further processing

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.2
 - OS: Ubuntu 18.04.5 LTS - bionic
 - Python version (if relevant): 3.7
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?  conda install -c rdkit rdkit

**Comment by greglandrum** [comment]
The RDKit can only reliably process mol2 files which are created using corina atom type definitions.

**Comment by haroldgrosjean** [comment]
Hello,

Many thanks for your response. Would it be better to generate an SDF file using OpenEye and let rdkit guess the aromaticity?

Cheers,

Harold

**Comment by greglandrum** [comment]
Yeah, SDF should be parsed more successfully
