### ISSUE TITLE
Barbiturate problem

### ISSUE THREAD

**Issue by macraild** [rdkit/rdkit#4300]
**Describe the bug**
I'm not sure of this is a problem with rdMolStandardize.Uncharger or something deeper, but there are issues with the dianion of barbituric acid (CHEBI:57718), as illustrated below:

**To Reproduce**
```
>>> dianion = Chem.MolFromSmiles("O=c1[cH-]c(=O)[n-]c(=O)[nH]1")
>>> uncharger = rdMolStandardize.Uncharger()
>>> neutralized = uncharger.uncharge(dianion)
>>> neutral_smiles = Chem.MolToSmiles(neutralized)
```

`neutralized` looks reasonable, but the SMILES roundtrip fails:
```
>>> Chem.MolFromSmiles(neutral_smiles) is None
True
```

Tautomer canonicalization also fails for `neutralised`: `te.Canonicalize(neutralized)` returns `neutralized` unmodified, despite `te.Enumerate(neutralized)` containing several higher-scoring tautomers.

**Expected behavior**
uncharger.uncharge() should return a valid molecule or fail in a more obvious (and informative) way.
Likewise the MolToSmiles - MolFromSmiles roundtrip.

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.3
 - OS: Windows
 - Python version (if relevant): 3.8
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Comment by ptosco** [comment]
@macraild Molecules generated from the various MolStandardizer classes are not sanitized. In fact, you might want to apply multiple subsequent standardization operations, and some of the intermediate products might even fail sanitization, so at the moment final sanitization is delegated to the user.
Closing as this topic has already come up multiple times:
https://github.com/rdkit/rdkit/issues/4009
https://github.com/rdkit/rdkit/issues/3094
Feel free to reopen if needed.
