### ISSUE TITLE
smiles to molecule conversion issue

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#432]
The following (possibly misrepresented) smiles string

In [1]: s0 = 'OC(=O)C(=O)Nc1cccc(c1)C2=NN=N[N]2'

is converted without errors into a molecule object:

In [2]: from rdkit import Chem

In [4]: m1 = Chem.MolFromSmiles(s0)

but the issue in the initially provided smiles is highlighted if the molecule is converted back into a SMILES string

In [5]: s1 = Chem.MolToSmiles(m1)

In [6]: s1
Out[6]: 'O=C(O)C(=O)Nc1cccc(-c2[n]nnn2)c1'

In [7]: m2 = Chem.MolFromSmiles(s1)
[09:26:02] Can't kekulize mol

**Comment by rvianello** [comment]
In case it may be useful, here's another smiles displaying a similar behavior:

In [2]: mol = Chem.MolFromSmiles('C[N+]1(C)CC23C4=C5C6=C7C8=C9C%10=C%11C%12=C%13C%14=C%15C%16=C%17C%18=C%19C%20=C%21C%22C%18C%16=C%23C%14=C%11c%24c9c%25C8C%26C(=C%21c%25c%22c%23%24)c%27c%20c%28c%19c%29C%17=C%30C%15=C%13C(=C4C%12=C6%10)C2=C%30c%29c%31c%28c%32c(c5c7c%26c%27%32)C3%31C1')

In [3]: smiles = Chem.MolToSmiles(mol)

In [4]: smiles
Out[4]: 'C[N+]1(C)CC23c4c5c6c7c8c9c%10c%11c7c7c%12c%11c%11c%13c%10c%10c%14c%15c%13C%13c%11c%11c%12c(c2c75)-c2c-%11c5c7c%11c%12c%16c%17c%18c%19c(c6c8c6c%19c8c%17-c%12c(c-%15c%11C5%13)C%14C8c6c9-%10)c4-c%18c4c%16c7c2C43C1'

In [5]: m = Chem.MolFromSmiles(smiles)
[18:01:02] Can't kekulize mol

**Comment by greglandrum** [comment]
A bit of exploration around this:
```python
In [5]: m = Chem.MolFromSmiles('C2=NN=N[N]2')
In [6]: s = Chem.MolToSmiles(m)
In [7]: s
Out[7]: 'c1[n]nnn1'
In [8]: Chem.MolFromSmiles(s)
[07:34:18] Can't kekulize mol 
# ok, that's what we already saw

# can we kekulize the original molecule? 
In [9]: m = Chem.MolFromSmiles('C2=NN=N[N]2')
In [10]: Chem.Kekulize(m)
# that's curious

# look again at building from aromatic SMILES to see what's going on:
In [16]: m2 = Chem.MolFromSmiles(s,sanitize=False)
In [17]: Chem.SanitizeMol(m2,sanitizeOps=Chem.SanitizeFlags.SANITIZE_ALL^Chem.SanitizeFlags.SANITIZE_KEKULIZE)
Out[17]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
In [18]: m2.Debug()
Atoms:
	0 6 C chg: 0  deg: 2 exp: 3 imp: 1 hyb: 3 arom?: 1 chi: 0
	1 7 N chg: 0  deg: 2 exp: 3 imp: 0 hyb: 3 arom?: 1 chi: 0
	2 7 N chg: 0  deg: 2 exp: 3 imp: 0 hyb: 3 arom?: 1 chi: 0
	3 7 N chg: 0  deg: 2 exp: 3 imp: 0 hyb: 3 arom?: 1 chi: 0
	4 7 N chg: 0  deg: 2 exp: 3 imp: 0 hyb: 3 arom?: 1 chi: 0
Bonds:
	0 0->1 order: 12 conj?: 1 aromatic?: 1
	1 1->2 order: 12 conj?: 1 aromatic?: 1
	2 2->3 order: 12 conj?: 1 aromatic?: 1
	3 3->4 order: 12 conj?: 1 aromatic?: 1
	4 4->0 order: 12 conj?: 1 aromatic?: 1
# ok, that's it. None of the Ns have a radical attached.

# prove this:
In [20]: m2.GetAtomWithIdx(1).SetNumRadicalElectrons(1)
In [21]: Chem.Kekulize(m2)

```

I believe this is pretty much an unsolvable problem if we allow aromatic heteroatoms to have radicals. On reading in the aromatic SMILES, we'll never know what to do.

One possible fix would be stop allowing aromatic rings to contain Ns with radicals. I'll try this and we can see what we think.
