### ISSUE TITLE
Support toggling components of CXSMILES output

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#4320]
At the moment atom properties, conformers, etc. are always written to the CXSMILES.
It is, of course, possible to clean the molecule up and remove all that stuff first, but it would be nicer to just have an option which allows us to toggle what gets written.

**Comment by d-b-w** [comment]
yeah, an enum or something might be nice:

    smiles = MolToCXSmiles(mol, CX_ALL ^ CX_COORDINATES)
