### ISSUE TITLE
Retrieving MolToXYZBlock() for Threonine ('T') Mol object Fails

### ISSUE THREAD

**Issue by Sum02dean** [rdkit/rdkit#4324]
**Describe the bug**
After creating a Mol object using Chem.MolFromFASTA(), I am unable to get XYX block information for the amino acid 'T' - threonine. Note that this worked for all of the 19 other amino acids. 

**To Reproduce**
```  python
mol = Chem.MolFromFASTA('T')
AllChem.EmbedMolecule(mol)
block = AllChem.rdmolfiles.MolToXYZBlock(mol)
print(block)
```

**Expected behavior**
I expected to retrieve information about the mol block, and the atomic XYZ coordinates. Below is an example of running the same code on 'A" - Alanine:
``` python

mol = Chem.MolFromFASTA('A')
AllChem.EmbedMolecule(mol)
block = AllChem.rdmolfiles.MolToXYZBlock(mol)
print(block)
```
Output:

```
6

N      1.507423   -0.661875   -0.660870
C      0.838776    0.051690    0.551703
C     -0.649498   -0.269966    0.126355
O     -0.969575   -0.885810   -0.859465
C      0.884023    1.533770   -0.170798
O     -1.611147    0.232191    1.013075
```

**Screenshots**
![image](https://user-images.githubusercontent.com/36505689/125268721-444be480-e308-11eb-959f-fbfe21ed7b00.png)

**Configuration (please complete the following information):**
 - RDKit version: rdkit-pypi   2021.3.2.3
 - OS: [e.g. Ubuntu 20.04]  NAME="Ubuntu"
                                             VERSION="16.04.7 LTS (Xenial Xerus)"
 - Python version (if relevant): python  3.9.5   
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? pypi 
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by jasondbiggs** [comment]
The documentation and the warning message both clear that you need to add hydrogens before generating 3D coordinates.  Use `mol = rdmolops.AddHs(Chem.MolFromFASTA('T'))` and it works as expected.

**Comment by Sum02dean** [comment]
Hi Jasondbiggs
Thanks for the workaround.

To my knowledge adding Hs is a recommended suggestion (not necessity) to constrain the degrees of freedom and therefore generate more reliable coordinate estimates. The purpose of the post is to demonstrate an unexpected behaviour. 

In this case the unexpected behaviour is that Threonine gives a different result than expected, relative to all the other amino acid outputs. If this issue helps improve the consistency of the expected outputs, I think it is worth mentioning.

**Comment by greglandrum** [comment]
This is not a bug, you've just ignored the return value of `EmbedMolecule()`.
`EmbedMolecule()` returns -1 when it fails to generate a conformer, which is what happens in this case.
`MolToXYZBlock()` displays an error message and returns an empty string when called on a molecule with an empty conformer.
This is all what's designed to happen.

`EmbedMolecule()` fails in your case because, as @jasondbiggs mentioned, you haven't called `AddHs()`.

**Comment by Sum02dean** [comment]
I am still having issues with empty output even after adding hydrogen atoms, for example: 

```python
smi_2 = 'ARTEWYREGRV'
mol_2 = AllChem.AddHs(Chem.MolFromFASTA(smi_2))
display(smi_2)
display(mol_2)

AllChem.EmbedMolecule(mol_2)
xyz_block = AllChem.rdmolfiles.MolToXYZBlock(mol_2)
display("Block information", xyz_block)
```

<img width="618" alt="image" src="https://user-images.githubusercontent.com/36505689/127218561-b385f942-10f6-4443-8dab-920fc5b67f88.png">
