### ISSUE TITLE
MinimalLib: return fingerprints as BitSets

### ISSUE THREAD

**Issue by dskatov** [rdkit/rdkit#4329]
Currently the fingerprint functions in MinimalLib, such as a `mol.get_morgan_fp`, return a string representing a fingerprint as `0` and `1` characters.

In Datagrok [Chem](https://github.com/datagrok-ai/public/tree/master/packages/Chem) package we convert such a string to a library [BitSet](https://github.com/datagrok-ai/public/tree/master/packages/ApiSamples/scripts/data-frame/bitset). Under its implementation, `0` and `1` are actually bits stored in an array of integers. We later perform high-performance search and filtering related operations on these bitsets.

For performance reasons, it would be fruitful to receive fingerprints from MinimalLib directly as a bitset. As an example, the return type may be a `Uint8Array` with enough elements to represent the entire fingerprint vector, s.t. it may possible be used to convert to a library [BitSet class](https://github.com/datagrok-ai/public/blob/master/packages/ApiSamples/scripts/data-frame/bitset/from-bytes.js). This may be a function additional to already existing ones such as `get_morgan_fp`.

CC @ptosco it would be great if you share your thoughts on this extension.

**Comment by ptosco** [comment]
@dskatov I agree with you and I'll see if I manage to push a PR today.
