### ISSUE TITLE
call to AvalonTools::set2DCoords results in an assert violation

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#4330]
The [fix](https://github.com/rdkit/rdkit/pull/4079) for #4075 has the effect of removing not only chiral hydrogens added by avalon, but also any hydrogen atoms that were already in the molecule.

Simple example, drawing water

```
void test() {
    SmilesParserParams params;
    params.removeHs = false;
    std::string smi = "[H][O][H]";
    std::shared_ptr<ROMol> sp(RDKit::SmilesToMol(smi, params));
    auto confID = AvalonTools::set2DCoords(*sp, false);
}
```
will result in the exception
```
    Test Assert
    Expression Failed: 
    Violation occurred on line 239 in file ..../rdkit/External/AvalonTools/AvalonTools.cpp
    Failed Expression: nonHydrogenIndices.size() == mol.getNumAtoms()
    RDKIT: 2021.09.1pre
    BOOST: 1_75
```

My workaround is to pass Avalon tools a SMILES string and do a substructure match to find my original molecule in the returned MOL, like 

```
unsigned int set2DCoordsAlt(ROMol &mol) {
    auto smi = MolToSmiles(mol, true, false, 0, false, false, false, false);
    auto molString = AvalonTools::set2DCoords(smi, true);
    TEST_ASSERT(molString.size() > 0);

    std::shared_ptr<ROMol> tempMol(MolBlockToMol(molString, true, false, false));
    TEST_ASSERT(tempMol != nullptr);

    MatchVectType matchVect;
    TEST_ASSERT(SubstructMatch(*tempMol, mol, matchVect, false, true));

    const auto &tempConf = tempMol->getConformer();
    auto res = mol.addConformer(new Conformer(mol.getNumAtoms()), true);
    auto &newconf = rdmol.getConformer(res);

    for(const auto mv : matchVect) {
        newconf.setAtomPos(mv.first, tempConf.getAtomPos(mv.second));
    }
    newconf.set3D(false);
    return res;
}
```
I imagine it could be more efficient by only doing the substructure matching if `tempMol` and `mol` have different atom counts, if they have the same atom counts than just use the smiles atom order.

**Comment by greglandrum** [comment]
Thanks for pointing this out @jasondbiggs.
There is, indeed, some ugly stuff going on in the back when Hs are already present in the molecule.
Definitely fixable on the RDKit side though.
