### ISSUE TITLE
MolBlock writer gives non-stereo double bonds "unspecified" parity

### ISSUE THREAD

**Issue by d-b-w** [rdkit/rdkit#4345]
**Describe the bug**
When writing to molblock or sdf or sd or whatever you call the format :), double bonds with no stereochemistry are given the "either" bond parity. I think that this is misleading - non-stereo bonds are distinct from stereogenic bonds for which we don't know whether the bond is _E_ or _Z_.

**To Reproduce**

<img width="427" alt="unexpected_cross_bond" src="https://user-images.githubusercontent.com/3013277/126237278-73b1cddc-bfc2-4b5d-a3f4-7f9760be1051.png">

The generated molblock is:

```
     RDKit          2D

  6  5  0  0  0  0  0  0  0  0999 V2000
    0.4304    1.2508    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.4326    0.2508    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2996   -0.2474    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.4326   -0.2508    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4304   -1.2508    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -1.2996    0.2474    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  2  3
  4  5  1  0
  4  6  1  0
M  END
```

**Expected behavior**
I'd expect both of these to have flat bonds in the depiction rather than a crossed bond. I'd expect the parity of the bond between atoms 2 & 4 to be 0.

**Configuration (please complete the following information):**
 - RDKit version: 2053a98ffa93ab7e7
 - OS: Mac
 - Python version (if relevant): 3.7
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Built from source

**Comment by greglandrum** [comment]
Yeah, the output code should check to see whether or not the double bond is potentially a stereobond before deciding that the bond should be crossed.

**Comment by d-b-w** [comment]
cool, someone from sdgr will take care of this. Cross-posted in our internal bug tracker as https://jira.schrodinger.com/browse/SHARED-7988
