### ISSUE TITLE
Conformer generation for a certain molecule makes one less conformer than requested

### ISSUE THREAD

**Issue by j-wags** [rdkit/rdkit#4360]
**Describe the bug**

We've encountered a situation where, when using EmbedMultipleConfs on a particular bicyclopentane-containing molecule, we sometimes get one less conformer than requested. 

**To Reproduce**
```
>>> from rdkit import Chem
>>> from rdkit.Chem import AllChem
>>> mol = Chem.MolFromSmiles('[H][O][C](=[O])[N]([C@]12[C]([H])([H])[C@]([N]([H])[C](=[O])[C]3=[C]([H])[N]([C]([H])([H])[C]([H])([H])[H])[c]4[c]([H])[c]([H])[c]([H])[c]([C]([H])([H])[c]5[c]([H])[c]([H])[c]([C]([F])([F])[F])[c]([H])[c]5[H])[c]43)([C@@]1([H])[C]#[N])[C@@]2([H])[C]([H])([H])[c]1[c]([H])[c]([H])[c]([H])[c]([H])[c]1[H])[S](=[O])(=[O])[c]1[c]([H])[c]([H])[c]([H])[c]([H])[c]1[H]', sanitize=False)
>>> AllChem.EmbedMultipleConfs(mol, numConfs=1, randomSeed=1, pruneRmsThresh=0.25)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
0
>>> AllChem.EmbedMultipleConfs(mol, numConfs=2, randomSeed=1, pruneRmsThresh=0.25)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
1
>>> AllChem.EmbedMultipleConfs(mol, numConfs=3, randomSeed=1, pruneRmsThresh=0.25)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
2
```

**Expected behavior**

If the method can produce one conformer when two are requested, then it would make sense that it could produce that one when only one is requested (instead it produces 0 conformers when 1 is requested).

**Screenshots**

The conformers that are produced look reasonable. However the carboxylic acid group seems a little distorted (the C=O bond length is just 1 A)

<img width="583" alt="Screen Shot 2021-07-26 at 11 13 02 AM" src="https://user-images.githubusercontent.com/16329175/127038106-f5e9126a-0518-492f-94f4-c4ffeebc66a3.png">

**Configuration (please complete the following information):**
 - RDKit version: `rdkit                     2021.03.1        py38hba24be9_0    conda-forge`
 - OS: Mac OS 10.14.3
 - Python version (if relevant): `python                    3.8.6           h624753d_5_cpython    conda-forge`
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? `conda-forge`

**Comment by jasondbiggs** [comment]
Do you see the same result if you don't use a nonzero `pruneRmsThresh` value?  The RMS pruning looks to be a postprocessing step.

**Comment by j-wags** [comment]
Hi @jasondbiggs, thanks for the tip. I've dug a bit deeper today and do see the same result if I remove the `pruneRmsThresh` value. 

```python
>>> AllChem.EmbedMultipleConfs(mol, numConfs=1, randomSeed=1)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
0
```

I've tried a few other things and found:
* Picking a different `randomSeed` can generate a conformer for the `numConfs=1` case 
 
```python 
>>> AllChem.EmbedMultipleConfs(mol, numConfs=1, randomSeed=2)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
1
```

* But for `numConfs=2`, it's not until `randomSeed=7` that we get a second conformer:
```python
>>> AllChem.EmbedMultipleConfs(mol, numConfs=2, randomSeed=1)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
1
>>> AllChem.EmbedMultipleConfs(mol, numConfs=2, randomSeed=2)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
1
>>> AllChem.EmbedMultipleConfs(mol, numConfs=2, randomSeed=3)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
1
>>> AllChem.EmbedMultipleConfs(mol, numConfs=2, randomSeed=4)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
1
>>> AllChem.EmbedMultipleConfs(mol, numConfs=2, randomSeed=5)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
1
>>> AllChem.EmbedMultipleConfs(mol, numConfs=2, randomSeed=6)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
0
>>> AllChem.EmbedMultipleConfs(mol, numConfs=2, randomSeed=7)
<rdkit.rdBase._vecti object at 0x1333cf990>
>>> mol.GetNumConformers()
2
``` 

I agree that the problem is probably somewhere _after_ conformer generation. I poked around a bit in the [relevant code](https://github.com/rdkit/rdkit/blob/4144a813cafc243a0a209ffd201167cc181a2f74/Code/GraphMol/DistGeomHelpers/Embedder.cpp#L1236-L1249) but nothing popped out at me as being the obvious cause. 

Maybe there's some distorted geometry that's being created, which causes `getMolSelfMatches` or `_isConfFarFromRest` to silently discard some conformers.

**Comment by greglandrum** [comment]
This isn't connected to RMS pruning.
That's a pretty highly constrained system - the bicyclopentane group where four of the atoms have specified chirality makes things difficult for the conformer generator - and the code is having problems generating conformers for it.

In cases like this there are two things you can try:
1. Switch to using random coordinate embedding (`useRandomCoords=True`). This can (but does not always) allow things to work better for highly constrained molecules.
2. Increase `maxAttempts`. This defaults to zero which means that it internally gets set to `10*numAtoms`. The code tries this number of times to generate each conformer. You can make this value as large as you want... more tries means a longer wait (but a greater chance of success).

**Comment by j-wags** [comment]
Thanks, @greglandrum - `useRandomCoords=True` seems like the best solution here, and now that I look I see [you've recommended it before](https://greglandrum.github.io/rdkit-blog/conformers/exploration/2021/01/31/looking-at-random-coordinate-embedding.html). Thanks for the tip!
