### ISSUE TITLE
RunReactants depends on the order of molecules in list

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#4361]
I'm not sure if this is expected behavior, but it is counter-intuitive to me.

To use a documentation example for the reactions:

```
>>>rxn = AllChem.ReactionFromSmarts('[C:1](=[O:2])-[OD1].[N!H0:3]>>[C:1](=[O:2])[N:3]')
>>>ps = rxn.RunReactants((Chem.MolFromSmiles('CC(=O)O'),Chem.MolFromSmiles('NC')))
>>>len(ps)
1
```
but if I change the order of input molecules the match isn't made:
```
>>>rxn = AllChem.ReactionFromSmarts('[C:1](=[O:2])-[OD1].[N!H0:3]>>[C:1](=[O:2])[N:3]')
>>>ps = rxn.RunReactants((Chem.MolFromSmiles('NC'),Chem.MolFromSmiles('CC(=O)O')))
>>>len(ps)
0
```
Is it required to have the input molecules in the correct order for reactions to run?  If so, are there general strategies to rearrange the input list?

**Comment by bp-kelley** [comment]
This isn't a bug.

If you look at the reaction object, it has a list of reactant definitions.  In your case

```
[C:1](=[O:2])-[OD1] -> reactant 1
[N!H0:3] -> reactant 2
```

These are the same order as the reactants in RunReactants.

If you want to assemble a list of possible reactants, you can use the reagent definitions directly:

```
possible_mols = <some list>

bbs = []
for reactant in rxn.GetReactants():
   reactants = [m for m in possible_mols if m.HasSubstructMatch(reactant)]
   bbs.append(reactants)
```

Now bbs[0] are the list of mols for the first reactant and bbs[1] are for the second.

A lot of this is encapsulated in the EnumerateLibrary classes.

```
library = rdChemReactions.EnumerateLibrary(rxn, bbs)
```

will allow enumerating all products.  More details here:

https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/ChemReactions/tutorial/EnumerationToolkit.ipynb

**Comment by jasondbiggs** [comment]
@bp-kelley thank you for clarifying that.  I had looked through the enumeration classes, and now they make a lot more sense.
