### ISSUE TITLE
rootedAtAtom not found in atomsToUse when calling MolFragmentToSmiles()

### ISSUE THREAD

**Issue by nizamibilal** [rdkit/rdkit#4373]
Dear All, 

**Describe the bug**
I have encountered an issue with `MolFragmentToSmiles()` function. I'm trying to generate the SMILES for each bit of the Morgan fingerprint for a given molecule. I am using the following code snippet in a jupyter-notebook.  

```
from rdkit.Chem import AllChem as Chem
from rdkit.Chem import Draw
m = Chem.MolFromSmiles('OC(=O)C1=CC(O)=C(O)C(O)=C1')
info = {}
atoms=set()
for key in Chem.GetMorganFingerprint(m,radius, bitInfo=info).GetNonzeroElements():
     print (key)
     print('fp bit: ', info[key], ' and length is: ', len(info[key]))
     env = Chem.FindAtomEnvironmentOfRadiusN(m,info[key][0][1],info[key][0][0])
     print('Will use the atom: ', info[key][0][0], ' and radius; ', info[key][0][1])
     display(Draw.DrawMorganBit(m, key, info, useSVG=True))
     for bidx in env:
         atoms.add(m.GetBondWithIdx(bidx).GetBeginAtomIdx())
         atoms.add(m.GetBondWithIdx(bidx).GetEndAtomIdx())
     print('atom To Use: ', list(atoms), 'and rooted at atom: ', info[key][0][0])
     smiles = Chem.MolFragmentToSmiles(m,atomsToUse=list(atoms),bondsToUse=env, rootedAtAtom=info[key][0][0])
     print('Smiles is: ',smiles)

```
It generates the SMILES for first couple of bits, but afterward I get the following error. 

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-12a724ab569f> in <module>
     12         atoms.add(m.GetBondWithIdx(bidx).GetEndAtomIdx())
     13     print('atom To Use: ', list(atoms), 'and rooted at atom: ', info[key][0][0])
---> 14     smiles = Chem.MolFragmentToSmiles(m,atomsToUse=list(atoms),bondsToUse=env, rootedAtAtom=info[key][0][0])
     15     print('Smiles is: ',smiles)

RuntimeError: Pre-condition Violation
	rootedAtAtom not found in atomsToUse
	Violation occurred on line 609 in file Code/GraphMol/SmilesParse/SmilesWrite.cpp
	Failed Expression: rootedAtAtom < 0 || std::find(atomsToUse.begin(), atomsToUse.end(), rootedAtAtom) != atomsToUse.end()
	RDKIT: 2021.03.3
	BOOST: 1_74
```

However the `Draw.DrawMorganBit()` can produce the correct image of the bit fragment. Please also see an screenshot of the output below. 

![image](https://user-images.githubusercontent.com/4132740/127313482-8dd92309-bf85-4d6b-b0cd-c74b9e3b25a1.png)

**To Reproduce**
Please see the python snippet above. 

I'm not able to get why for some bits the rootedAtom are not in the atoms list. Could someone please let me know where am I making mistake or is it a bug?

**Configuration:**
Environment: RDkit version. rdkit 2021.03.3  installed via conda-forge
Python version: 3
OS: Ubuntu 20.04

Thanks in advance.

**Comment by greglandrum** [comment]
Hi. There are two problems here:
1. because `atoms` is defined outside your loop, you end up keeping the atoms from previous iterations in the environment
2. you need to be sure that the central atom (which ends up being `rootedAtAtom`) is in the `atomsToUse` list.
You can resolve both of these by moving the initialization of `atoms` into the loop and making it:
```
    atoms = {info[key][0][0]}
```

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by nizamibilal** [comment]
Hi, Thanks for the explanation. Indeed the issue is resolved.
