### ISSUE TITLE
Hiding explicit hydrogen atoms in 2D-Drawing

### ISSUE THREAD

**Issue by OmarAttraq** [rdkit/rdkit#4408]
**Is your feature request related to a problem? Please describe.**
Hiding explicit hydrogen atoms is commonly desired when showing molecules in 2D/3D. Although "Chem.RemoveHs" can be used, the changing of atoms ids makes it difficult when highlighting atoms/bonds is required. For example, I face this problem when I need to highlight a substructure match of a structure with explicit Hs but want to display it highlighted without Hs. 

**Describe the solution you'd like**
Adding an option to hide (not draw) explicit hydrogen atoms in the drawing options can be very useful.

**Describe alternatives you've considered**
Using a dictionary with atom ids (before removingHs is called) as keys and atom_ids after removing Hs as values, then update the atom_ids of the substructure match using the dictionary and excluding Hs. But this is inefficient/complex.

**Additional context**
None

**Comment by greglandrum** [comment]
Hi @OmarAttraq, thanks for the suggestion.

Given that this is a pretty specialized use case and is straightforward to implement in your code before calling the drawing code, I don't think it makes sense to complicate the drawing API or backend code with this capability.
