### ISSUE TITLE
RDKit reaction produces wrong double bond stereochemistry

### ISSUE THREAD

**Issue by mwojcikowski** [rdkit/rdkit#4410]
For a quite basic reaction RDKit since 2020.09 produces wrong stereochemistry on double bond. Last know version that worked correctly is 2020.03.

In following reaction latest RDKit (2021.03) is producing chlorines in cis position instead of trans.
![image](https://user-images.githubusercontent.com/2325645/129032086-a062fb07-2b5a-407d-87ee-4c3afced813a.png)

Code to reproduce
```python
from rdkit.Chem import AllChem
from rdkit import Chem
rxn = AllChem.ReactionFromSmarts('[N:4][C:6](/[Cl:9])=[C:7](\\[Cl:10])[C:11].[Br:5]>>[N:4].[Br:5][CX3:6](\\[Cl:9])=[CX3:7](/[Cl:10])[C:11]')
res = rxn.RunReactants((Chem.MolFromSmiles('C\\C(Cl)=C(\\N)Cl'), Chem.MolFromSmiles('[Br]')))
assert Chem.MolToSmiles(res[0][1]) == 'C/C(Cl)=C(\\Cl)Br'
```

Version info:
 - RDKit version: 2021.03
 - OS: MacOS Big Sur
 - Python version (if relevant): 3.8
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

Pinging @ricrogz

**Comment by mwojcikowski** [comment]
@ricrogz I didn't mean absolute configuration, rather relative position of chlorine atoms.
Maybe a drawing will be more precise.
Produced:
![image](https://user-images.githubusercontent.com/2325645/129036437-e8720572-7077-4349-92f5-cc42f8fcc51c.png)

Expected:
![image](https://user-images.githubusercontent.com/2325645/129036475-4877b1ef-bab6-4959-9a28-bda3771d53fd.png)

**Comment by ricrogz** [comment]
Sorry, you are right, something is wrong. I had just had a quick look at your initial message in my email, and somehow got the impression that the image depicted the problem, not the correct reaction. I'll look into it.
