### ISSUE TITLE
Br3- and ClO2 not accepted as valid chemical entities

### ISSUE THREAD

**Issue by IngvarLa** [rdkit/rdkit#4420]
Hello,

Br[Br-]Br as say part of pyridinium perbromide is a bromination reagent.  This ion gives a valence error.  Considering that I[I-]I is valid, I would expect Br3- to valid too.

O=Cl=O also gives a valence error, while an unusual valence, the chemical is widely used.

>>> from rdkit import Chem
>>> i3_ = Chem.MolFromSmiles('I[I-]I')              -- works
>>> br3_ = Chem.MolFromSmiles('Br[Br-]Br')
[08:47:49] Explicit valence for atom # 1 Br, 3, is greater than permitted
cl4 = Chem.MolFromSmiles('O=Cl=O')
[08:45:46] Explicit valence for atom # 1 Cl, 4, is greater than permitted

I use the Smiles suggested on their respective Wikipedia page
https://en.wikipedia.org/wiki/Pyridinium_perbromide
https://en.wikipedia.org/wiki/Chlorine_dioxide

I would expect both Br[Br-]Br and 0=Cl=O to be valid.
O=BrO is valid, to me this is also a trivalent Br, just as the [Br-] in the trihalide.
Maybe this issue has something to do with the choice of treating hypervalent halides as charge separated - but maybe that is another discussion.

>>> rdkit.__version__
'2021.09.1pre'
OS Linux RHEL 8.1
Python 3.8.5
Built from source

Kind Regards,
Ingvar Lagerstedt

**Comment by Bernadette-Mohr** [comment]
I recently discovered the same issue, on RDKit version 2021.03.3 and Python 3.9.5.
The canonical SMILES for the tribromide ion, Br[Br-]Br, leads to the following error: `[10:31:44] Explicit valence for atom # 1 Br, 3, is greater than permitted`.

**Comment by cottonkiet** [comment]
I also encountered similar issue on RDKit version 2022.03.3. 
The smiles for chloryl fluoride cannot be read by `mol = Chem.MolFromSmiles('F[Cl](=O)=O')`, with the following error:`Explicit valence for atom # 1 Cl, 5, is greater than permitted`

**Comment by greglandrum** [comment]
This is by design. By default the RDKit does not accept many hypervalent species.
If you would like to disable the RDKit's valence checks you can disable sanitization when parsing the SMILES and then do a partial sanitization afterwards. Like this:
```
In [61]: m = Chem.MolFromSmiles("F[Cl](=O)=O", sanitize=False)

In [62]: m.UpdatePropertyCache(strict=False)

In [63]: Chem.SanitizeMol(
    ...:     m,
    ...:     sanitizeOps=Chem.SanitizeFlags.SANITIZE_ALL
    ...:     ^ Chem.SanitizeFlags.SANITIZE_PROPERTIES,
    ...: )
Out[63]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE
```

**Comment by cottonkiet** [comment]
Thanks a lot! Would it be a future feature that these hypervalent species will be recognised then?

**Comment by IngvarLa** [comment]
OK, guess I should close this issue then.  I had already gone the route to do partial sanitization as I wanted to handle hexavalent carbons that I occasionally get when processing sketches and that is well beyond the redeems of sane valency.  (The hexavalent carbons happens if the single bond in phenylaceteylene is drawn too short.)
I think there is a case to have a mode that allows possible but rare valences.
