### ISSUE TITLE
Library pickle.load throws "RuntimeError: invalid value in pickle"

### ISSUE THREAD

**Issue by andt88** [rdkit/rdkit#4427]
Hi,

I'm trying creating a library and save it with pickle:

```
library = rdSubstructLibrary.SubstructLibrary()
for m in mols:
   m.UpdatePropertyCache()
   Chem.rdmolops.FastFindRings(m)
   m = Chem.rdmolops.AddHs(m, explicitOnly=True)
   library.AddMol(m)

with open('library.p', 'wb') as rdkit_library:
     pickle.dump(library, rdkit_library, protocol=4)
```

Trying to load it gives an error:

```
with open('library.p', 'rb') as db:
     pickle.load(db)
```
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
RuntimeError: invalid value in pickle
```

Any idea what this could mean?

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.

**Comment by andt88** [comment]
I moved the question to discussion, since it's not a bug I think. Thanks for the feedback.
