### ISSUE TITLE
SMILES representing the same molecule canonicalize into different SMILES 

### ISSUE THREAD

**Issue by alstonlo** [rdkit/rdkit#4443]
**Describe the bug**
Two SMILES representing the same molecule canonicalize into different SMILES.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem.Draw import MolsToGridImage

s1 = "CC(C)(C)COc1ccc2c(c1)C1=NC3=NC(=NC4=NC(=NC5=NC(=NC2=N1)c1ccc" \
     "(OCC(C)(C)C)cc15)c1cc(OCC(C)(C)C)ccc14)c1cc(OCC(C)(C)C)ccc13"
s2 = "CC(C)(C)COc1ccc2c(c1)C1=NC2=NC2=NC(=NC3=NC(=NC4=NC(=N1)c1ccc" \
     "(OCC(C)(C)C)cc14)c1ccc(OCC(C)(C)C)cc13)c1cc(OCC(C)(C)C)ccc12"

mol1 = Chem.MolFromSmiles(s1, sanitize=True)
mol2 = Chem.MolFromSmiles(s2, sanitize=True)

can_s1 = Chem.MolToSmiles(mol1, canonical=True)
can_s2 = Chem.MolToSmiles(mol2, canonical=True)

print(can_s1 == s1)  # True
print(can_s2 == s2)  # True
print(can_s1 == can_s2)  # False

MolsToGridImage([mol1, mol2])
```

**Expected behavior**
`s1` and `s2` (depicted below) represent equivalent molecules, so their canonical SMILES should be equivalent, if I'm not mistaken. 

![image](https://user-images.githubusercontent.com/40709307/130685103-276b5a93-102f-420b-a0b1-7a6f8b16e307.png)

**Configuration:**
 - RDKit version: 2021.03.4
 - OS: Windows 10
 - Python version: 3.8.10
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

Best regards,
alstonlo (from the SELFIES team 🙂)

**Comment by bp-kelley** [comment]
The winding of the double bonds in the center ring has a handedness because of the attachments on the benzene rings.

```
>>> Chem.MolFromSmiles(s1).HasSubstructMatch(Chem.MolFromSmiles(s2))
False
```

 Removing these attachments generates the same canonical smiles:

![image](https://user-images.githubusercontent.com/9888416/130690965-40f000b2-20fe-4137-bebb-080eabf2a08a.png)

```

**Comment by alstonlo** [comment]
Oh my mistake, the depicted graphs are indeed non-equivalent! 

Thanks! 
alstonlo
