### ISSUE TITLE
Publish the npm release of javascript minimal lib automatically everytime there's a new release of RDKit

### ISSUE THREAD

**Issue by MichelML** [rdkit/rdkit#4444]
**Is your feature request related to a problem? Please describe.**
npm release of the JavaScript minimal lib is published (by me) manually every time a new version of RDKit is released.

**Describe the solution you'd like**
Have the npm release published automatically within the CI/CD of RDKit, every time there's a new release of RDKit 

**Describe alternatives you've considered**
Currently working on having a new minimal lib rdkit-js github repository (see https://github.com/rdkit/rdkit/discussions/4124), but the release of the npm package will always be bound to the release of the main RDKit library,

**Additional context**

**Note: an NPM token will be needed in the environment variables to run the following commands successfully**

inside a CI/CD step, we would just have to run the following commands back to back from the root of the RDKit repository:

```bash
# Step 1: Set the release version in package.json
npm --no-git-tag-version version <semver version matching an RDKit release>
# --> Example npm --no-git-tag-version version 2021.3.1

# Step 2: Build the distribution files
npm run build -- <RDKit git release tag name>
# --> Example: npm run build -- Release_2021_03_1

# Step 3: Publish the package to npm
npm publish --access public

# Step 4: Set back the placeholder version in package.json
npm run resetVersion
```
For more details checkout the contributing section of the minimal lib https://github.com/rdkit/rdkit/tree/master/Code/MinimalLib#contributing

cc @greglandrum , let me know what you think and if you agree/disagree

needed in the VM running the CI: `jq` , `npm` & `node`, `docker` and `bash`, I currently build each release from a Linux machine .

**Comment by greglandrum** [comment]
@MichelML doing this definitely makes sense to me, and thanks for including the details about how to handle the npm parts.
I will try to make a chunk of time to take a look at how to set up the CI parts and get this working when I'm back from vacation (in a couple of weeks).

**Comment by MichelML** [comment]
thanks @greglandrum I tried and will continue to try to have a look too

**Comment by MichelML** [comment]
This can be closed I think as it is implemented in rdkit-js
