### ISSUE TITLE
Support multi-threaded evaluation of some obvious tasks from Python

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#445]
Doing multi-threading from python itself can be a bit of a PITA, but it's pretty easy to set something up in C++ using boost.thread. The trick will be to see if this actually works without causing problems somewhere else.

Functions to consider:
- ~~[ ] The various Bulk similarity methods~~ decided not to do this one as the current bulk implementation is already quite fast.
- ~~[ ] Substructure searching: single query against multiple targets~~ can come back to this if needed
- ~~[ ] Substructure searching: single target with multiple queries~~ can come back to this if needed
- [x] conformation generation
- [x] forcefield optimization
- [x] open3dalign

**Comment by bp-kelley** [comment]
I'm curious about the python multi-threading issue, is it a PITA because we need to manually release the GIL in all the wrapped code?  I have some patches that do this for I/O classes that help python based threaded web-apps that I've been meaning to push...

There is also a clever scope based mechanism we can use in a few places in the wrapped code (as long as in the managed scope, no Python API calls are made)

https://wiki.python.org/moin/boost.python/HowTo#Multithreading_Support_for_my_function

**Comment by greglandrum** [comment]
My PITA comment was more around the general problems with python and multithreading or parallel work. Multiprocessing is great, but doesn't work from the interactive prompt. The IPython cluster stuff is also great, but it only works in IPython and there is "some" effort involved to make sure objects can be passed to the functions.

**Comment by greglandrum** [comment]
I hadn't seen the `ScopedGILRelease` class before. That would definitely be an interesting thing to start using at least in expensive function calls. For functions/methods that already have a dedicated stub function in the wrapper, this won't be a problem. Places where the wrapper is the one automatically generated by Boost would require that stubs be added.

We could at least start with the slower functions that already have stubs... just need a definition of `ScopedGILRelease` somewhere in some place like `Code/RDBoost/Wrap.h`

**Comment by bp-kelley** [comment]
I'll put my patches up for review then which include the ScopedGILRelease, I only modified a few functions and they have to be carefully tested to make sure nothing broke.

As for multithreading, for performance reasons they do interprocess communication with pickle/cPickle which unfortunately cannot "pickle" functions/lamdas or closures.  There is a multithreading fork that can (it uses dill which can pickle functions) which looks quite interesting and is useable from the command-line:

https://github.com/uqfoundation/pathos
