### ISSUE TITLE
Compile failed 

### ISSUE THREAD

**Issue by Joezczhang** [rdkit/rdkit#4457]
Hello:

When i build rdkit,there is a error just as below.
Could you please tell me how to solve the problem.
![image](https://user-images.githubusercontent.com/89260661/131370414-4ea458dc-9304-4ad9-93b9-11572b89d4b6.png)

**Comment by greglandrum** [comment]
Those error messages are indicating that the boost libraries cannot be found during the build process.
Did you run the build in the same environment/shell where you ran cmake?

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Comment by Joezczhang** [comment]
For Please ask questions using the "Discussions" tab-> I will.
But now how to disable it?
