### ISSUE TITLE
Constructing 3D structures for many molecules in a SMILES string

### ISSUE THREAD

**Issue by ghost** [rdkit/rdkit#4480]
**Describe the bug**
I have problem with constructing 3D structures for many molecules in a SMILES string. The delivered construction is unphysical and I'd like all the molecules to be in the same structure file. 

**To Reproduce**
```
reactant_mapped= Chem.MolFromSmiles('[F:1][C:2][F:3].[CH2:4]=[CH2:5]')
reactant_mapped=Chem.AddHs(reactant_mapped)

AllChem.EmbedMolecule(reactant_mapped,randomSeed=0xf00d)
with Chem.SDWriter('./test/reactant_mapped.sdf') as w:
    w.write(reactant_mapped)
```

**Expected behavior**
3D structure of 2 separated molecules in the same `reactant_mapped.sdf` file

**Configuration (please complete the following information):**
 - RDKit version: rdkit-pypi  2021.3.4
 - OS: [e.g. Ubuntu 20.04]
 - Python version (if relevant): 3.8
 - Are you using conda? 
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? pip

**Comment by ptosco** [comment]
This is not strictly speaking a bug. If you wish that your disconnected fragments do not have overlapping coordinates you could combine them along the, say, x axis adding a progressive offset, e.g.:
```
from rdkit import Chem
from rdkit.Geometry import Point3D
from rdkit.Chem import rdDistGeom, rdMolTransforms
import numpy as np

reactant_mapped = Chem.MolFromSmiles('[F:1][CH2:2][F:3].[CH2:4]=[CH2:5].c1ccccc1.CCCCCC1CCC(CCCCCCCCCCC)CCC1')
reactant_mapped = Chem.AddHs(reactant_mapped)

rdDistGeom.EmbedMolecule(reactant_mapped,randomSeed=0xf00d)
0

combined_frag = None
DIST = 2.0
x_offset = 0.0
for frag in Chem.GetMolFrags(reactant_mapped, asMols=True):
    frag_conf = frag.GetConformer()
    rdMolTransforms.CanonicalizeConformer(frag_conf)
    pos = np.transpose(frag_conf.GetPositions())
    if combined_frag is None:
        combined_frag = frag
    else:
        x_offset += abs(np.min(pos[0])) + DIST
        combined_frag = Chem.CombineMols(combined_frag, frag, offset=Point3D(x_offset, 0., 0.))
    x_offset += abs(np.max(pos[0]))

combined_frag
```

![image](https://user-images.githubusercontent.com/5244385/132034726-c5c9238f-01d9-4cc0-8c48-2a03b45f935e.png)

```
with Chem.SDWriter("/home/toscopa1/support/github4480/reactant_mapped.sdf") as w:
    w.write(combined_frag)
```

![image](https://user-images.githubusercontent.com/5244385/132034838-16284d09-2972-41f3-bfb8-8ae06ccf41f2.png)

Of course you could think of many alternative ways to combine your molecules in 3D, this is just one.
