### ISSUE TITLE
Support a maxBondLength parameter in MolDrawOptions

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#4481]
Really small molecules, like ethane, are drawn to fill the available space:
![image](https://user-images.githubusercontent.com/540511/132025886-dd0879fe-d73b-4b0b-a236-44957f94b8c7.png)

This can end up looking pretty silly, particularly in a setting where other images have larger molecules drawn.

We could resolve this by adding an option to `MolDrawOptions` which allows the maximum bond length (in pixels?) to be set.

**Comment by greglandrum** [comment]
@DavidACosgrove : seem like a reasonable idea to you?

**Comment by DavidACosgrove** [comment]
I don’t have a computer handy at the moment so can’t check but I think you can fix a bond length in pixels. If it makes the scale such that the drawing would go outside the image, the scale is reduced so it is effectively a maximum.

**Comment by greglandrum** [comment]
> I don’t have a computer handy at the moment so can’t check but I think you can fix a bond length in pixels. If it makes the scale such that the drawing would go outside the image, the scale is reduced so it is effectively a maximum.

yeah, sorry, I got confused by the name of the `fixedBondLength` option.
