### ISSUE TITLE
Could not optimize peroxyl radicals using MMFF94

### ISSUE THREAD

**Issue by alongd** [rdkit/rdkit#4485]
**Describe the bug**

I'm unable to optimize peroxyl radicals (e.g., `CCO[O]`) using MMFF94(s) force fields in RDKit.
The problem seems to be that `MMFFGetMoleculeProperties` returns `None` for such molecules.
Note that UFF does work as expected for peroxyls.

**To Reproduce**

```python
smiles = "CCO[O]"
m = Chem.MolFromSmiles(smiles)
m = Chem.AddHs(m)
AllChem.EmbedMolecule(m)

>>> 0

m.GetNumAtoms()

>>> 9

mp = AllChem.MMFFGetMoleculeProperties(m)
[mp.GetMMFFAtomType(i) for i in range(m.GetNumAtoms())]

>>> AttributeError: 'NoneType' object has no attribute 'GetMMFFAtomType'
```

**Configuration (please complete the following information):**
 - RDKit version: 2020.03.3.0
 - OS: Ubuntu 20.04
 - Python version: 3.7.10
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? `rmg`

**Comment by ptosco** [comment]
@alongd This is not a bug. Neither UFF nor MMFF support radical species. UFF may be more lenient about atom types so it will probably optimize your structure as a non-radical peroxide, which is not what you want. You will need to use a QM method to get correct radical geometries.
