### ISSUE TITLE
ResMolSupplier results depend on the starting structure

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#4491]
This was originally reported by @gunabam:

### Discussed in https://github.com/rdkit/rdkit/discussions/4490

<div type='discussions-op-text'>

<sup>Originally posted by **gunabam** September  8, 2021</sup>
Hi there, I am trying to calculate the potential resonance structures with rdkit. This is the code that I tried:
```
from rdkit import Chem
from rdkit.Chem.rdchem import ResonanceMolSupplier

mol = Chem.MolFromSmiles('[CH2+]C1=NC=CC=C1')
flags = Chem.KEKULE_ALL | Chem.ALLOW_INCOMPLETE_OCTETS | Chem.UNCONSTRAINED_CATIONS
suppl = ResonanceMolSupplier(mol, flags=flags)
for resMol in suppl:
    print(Chem.MolToSmiles(resMol))

```
And I get the following output:
```
[CH2+]c1ncccc1
[CH2+]c1ccccn1
C=c1cc[cH+]cn1
C=c1[cH+]cccn1
C=c1cccc[nH2+]1
```
However, when I try a different input such as `C=c1cccc[nH2+]1` (one of the potential resonance structures from the previous example), I am not getting the same structures. I get the following:
```
C=C1C=CC=C[NH2+]1
```
Is there something missing from my code? Thank you in advance for your help!</div>

Here is a snippet that shows that using any of the structures bearing the positive charge on one of the ring atoms as the starting structure fails to yield the same results as using as a starting structure one bearing the charge on an exocylic atom:

```
from rdkit import Chem
from rdkit.Chem.Draw import MolsToGridImage

mol = Chem.MolFromSmiles('[CH2+]C1=NC=CC=C1')
flags = Chem.KEKULE_ALL | Chem.UNCONSTRAINED_CATIONS
suppl = Chem.ResonanceMolSupplier(mol, flags=flags)
res = set([Chem.MolToSmiles(m) for m in suppl])
res
{'C=c1[cH+]cccn1',
 'C=c1cc[cH+]cn1',
 'C=c1cccc[nH2+]1',
 '[CH2+]c1ccccn1',
 '[CH2+]c1ncccc1'}

for smi in res:
    suppl2 = Chem.ResonanceMolSupplier(Chem.MolFromSmiles(smi), flags=flags)
    res2 = set([Chem.MolToSmiles(m) for m in suppl2])
    if (res != res2):
        print(smi, res2)
C=c1cccc[nH2+]1 {'C=C1C=CC=C[NH2+]1'}
C=c1cc[cH+]cn1 {'C=C1[CH+]C=CC=N1', 'C=C1C=C[CH+]C=N1', 'C=C1C=CC=C[NH2+]1', '[CH2+]C1=NC=CC=C1', '[CH2+]C1=CC=CC=N1'}
C=c1[cH+]cccn1 {'C=C1[CH+]C=CC=N1', 'C=C1C=C[CH+]C=N1', 'C=C1C=CC=C[NH2+]1', '[CH2+]C1=NC=CC=C1', '[CH2+]C1=CC=CC=N1'}
```

**Comment by simonmb** [comment]
This also applies to the following example using the default flags on '2023.03.1':
```
'CCCC[n+]1ccn(CC)c1' -> ['CCCC[n+]1cn(CC)cc1']
'CCCCn1cc[n+](CC)c1' -> ['CCCC[n+]1cn(CC)cc1', 'CCCCn1cc[n+](CC)c1']
```
