### ISSUE TITLE
no bond direction on double bonds in molblock output?

### ISSUE THREAD

**Issue by TermeHansen** [rdkit/rdkit#4493]
Why is there no direction on the double bonds in the bond section of the output from MolToMolBlock, I'm pretty sure there used to be.

![image](https://user-images.githubusercontent.com/6922018/132686043-0558d294-c6d5-477b-b2d5-aebbad5b662d.png)

RDKIT: 2021.03.4
Ubuntu 20.04

**Comment by greglandrum** [comment]
What do you mean by bond direction in the mol block output?
Cis/trans on double bonds in mol blocks is provided by the atomic coordinates, so no bond directionality is needed (and I'm not aware of any mechanism to indicate it).

**Comment by TermeHansen** [comment]
[http://c4.cabrillo.edu/404/ctfile.pdf](http://c4.cabrillo.edu/404/ctfile.pdf)
![image](https://user-images.githubusercontent.com/6922018/132818751-46b2857f-4750-4c74-ac9b-ab541a7def11.png)


```
from rdkit import Chem
from openbabel import pybel

sdf = '''
RDKit          2D

  8  7  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  1
  4  5  2  0
  5  6  1  1
  6  7  1  0
  7  8  1  0
M  END
'''
display(Chem.MolFromMolBlock(sdf))
display(pybel.readstring('mol',sdf))
display(pybel.readstring('mol',sdf.replace('  5  6  1  1','  5  6  1  6')))
```

![image](https://user-images.githubusercontent.com/6922018/132818570-9cf921ce-5a58-45b3-a74a-7003bfb3433b.png)

**Comment by greglandrum** [comment]
Hi @TermeHansen : Those flags are connected to bond wedging, which is something that is supposed to be used for atomic chirality, not double bond stereochemistry.
Here's the relevant section from page 231 of the BioVia Chemical Representation guide (http://help.accelrysonline.com/insight/2017/content/pdf_files/bioviachemicalrepresentation2017.pdf):
![image](https://user-images.githubusercontent.com/540511/133247496-052d9524-14b9-40d0-9906-ad69ec1eba5c.png)

Based on this double bond stereochemistry cannot be accurately perceived from a CTAB if there are no coordinates available.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
