### ISSUE TITLE
contrib/RxnRoleAssignment does not load

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#4502]
**Describe the bug**
Cannot load contrib package identifyReactants from RxnRoleAssignment

**To Reproduce**
Thanks to @iwatobipen for explaining this contrib import method in issue  #2279
```
from rdkit import Chem
from rdkit.Chem import RDConfig
import os
import sys

sys.path.append(os.path.join(RDConfig.RDContribDir, 'RxnRoleAssignment'))

import identifyReactants
```

**Expected behavior**
It is expected that the package will import with no error.

**Screenshots**
Observed error:
>  from . import utils
> ImportError: attempted relative import with no known parent package

**Configuration (please complete the following information):**
 - RDKit version:  2020.09.4
 - OS: Windows 10
 - Python version (if relevant): 3.7.7
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? rdkit

**Comment by ptosco** [comment]
@paconius `RxnRoleAssignment` is a Python package (it has an `__init__.py` file), so modules which are part of the package may feature relative imports.
To import the `identifyReactants` module you may do the following:
```
from rdkit import Chem
from rdkit.Chem import RDConfig
import os
import sys

sys.path.append(RDConfig.RDContribDir)
from RxnRoleAssignment import identifyReactants
```
The above will work.
