### ISSUE TITLE
MolFromSmiles and MolFromSmarts incorrectly accepting input with spaces

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#4503]
**To Reproduce**
Here's the demo using 2021.03.5:
```
In [14]: Chem.MolFromSmiles('NON sense') is None
Out[14]: False

In [15]: Chem.MolFromSmiles('NON |sense|') is None
Out[15]: True
```
the same thing happens on master with both `MolFromSmiles` and `MolFromSmarts`.

**Expected behavior**
The default setting for `SmilesParserParams::strictCXSMILES` is `True`, so both of these should fail.

**Configuration (please complete the following information):**
 - RDKit version: master 
 - OS: all

**Comment by greglandrum** [comment]
After spending some time working on and thinking about this, I'm reluctant to make this change in the default behavior.
It's not hard to imagine that there's a lot of code out there which is perfectly happily working with having SMILES like `NON sense` parse without errors.
What I think I'm going to do is change the default value of `{Smiles,Smarts}ParseParams::parseName` to `true`, then these will both parse without problems by default, but if you want them to generate errors you can set `parseName` to false

**Comment by bp-kelley** [comment]
Historically, The RDKit used to strip any trailing whitespace, after a bit of debate, this behavior was changed here as the parser would just stop at the whitespace anyway.

The commit doesn't reflect that change in the merge

https://github.com/rdkit/rdkit/commit/efcf242151d2f18f462103ace563e1349c99c5d3

note the commented out trim_if.  We should probably just remove this line of code...
