### ISSUE TITLE
Support squiggly bonds from CXSMILES import

### ISSUE THREAD

**Issue by tdudgeon** [rdkit/rdkit#4525]
**Describe the bug**
CXSMILES allows to define the squiggly bond. RDKit ignores this information.
Squiggly bond means either R or S, but I'm not sure which.

**To Reproduce**
Import this cxsmiles:
CC(O)Cl |w:1.1|

**Expected behavior**
RDKit should recognise the bond as squiggly and should render it as such.

**Screenshots**
![Screenshot from 2021-09-16 10-22-16](https://user-images.githubusercontent.com/647419/133586688-8fe1c09f-a5e9-4ed5-8cde-ae373f5835c3.png)

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.5
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**
It also looks like this info is not handled when reading MDL Molblocks?

**Comment by greglandrum** [comment]
The RDKit does not by default leave squiggly bonds intact after parsing the molecule, so even once we've added the support to the CXSMILES parser you aren't going to see the bonds drawn as squiggly unless you do some additional work to re-apply that bond property to the molecule.
