### ISSUE TITLE
MolFromSmiles says “Can't kekulize mol” for pyrrole, indole, and other aromatic SMILES

### ISSUE THREAD

**Issue by fxcoudert** [rdkit/rdkit#4534]
**Describe the bug**
Several valid SMILES (including pyrrole, indole, and other compounds including aromaticity) are rejected by `MolFromSmiles`.

**To Reproduce**

Code to run, with rdkit 2021.03.5:

```
from rdkit import Chem
bugs = [
    'c1cccn1',
    'N#Cc3cncc3c1cccc2OC(F)(F)Oc12',
    'COc1cc(cc(OC)c1OC)/C=C/C(=O)O[C@@H]3C[C@@H]4CN5CCc2c6ccc(OC)cc6nc2[C@H]5C[C@@H]4[C@@H]([C@H]3OC)C(=O)OC',
    'c1cncn1',
    'c1cccc2nccc12',
    'Cc1cc2nnnc2cc1',
    'O=C(OC)[C@@]2(C[C@H]4C[C@@](O)(CC)C[N@@](CCc1c3ccccc3nc12)C4)c5cc9c(cc5OC)N(C=O)[C@@H]6[C@]98CCN7CC=C[C@@](CC)([C@@H](OC(C)=O)[C@]6(O)C(=O)OC)[C@H]78',
    '[O-][N+](=O)c1ccc2ncnc2c1',
    '[O-][N+](=O)c1cnc(C)n1',
    'c1cccc2ncnc12',
    'Cc2cnc1ccccc12',
    'c1cccc2nnnc12',
    'n2cnc(NCc1ccccc1)c3ncnc23',
    'n1c3ccccc3nc1c2cscn2',
    'N[C@@H](Cc1cncn1)C(=O)O',
    'Sc1nc2ccccc2n1'
]
print([Chem.MolFromSmiles(smiles) for smiles in bugs])
```

The output is `[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]`
Many messages of the following type are written to stderr:

```
RDKit ERROR: [23:53:08] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4
```

(I would have expected to throw instead of writing to stderr, but I'm new to rdkit.)

**Expected behavior**

Correct generation of molecule. PubChem for example correctly determines that `c1cccc2nccc12 ` corresponds to indole: https://pubchem.ncbi.nlm.nih.gov/#query=c1cccc2nccc12&input_type=smiles

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.5
 - OS: macOS 11.6
 - Python version: 3.8.3
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by fxcoudert** [comment]
Should have noted: all these SMILES strings come from [“ Jean-Claude Bradley Double Plus Good (Highly Curated and Validated) Melting Point Dataset”](https://figshare.com/articles/dataset/Jean_Claude_Bradley_Double_Plus_Good_Highly_Curated_and_Validated_Melting_Point_Dataset/1031638)

Out of 3041 SMILES these are the only 16 ones that error when used in `MolFromSmiles`

**Comment by greglandrum** [comment]
These SMILES all have the characteristic that they have aromatic heteroatoms which should have an H on them but where that H is not present in the SMILES.
So pyrrole should be `c1ccc[nH]1`, *not* `c1cccn1`.

The SMILES in that dataset are syntactically valid, but chemically questionable.

A web search will turn up a number of possible solutions to this problem, but the absolute best one is to just fix the dataset.

**Comment by Bernadette-Mohr** [comment]
Unfortunately, your exact example SMILES causes the same error: `c1ccc[nH]1`

**Comment by greglandrum** [comment]
@Bernadette-Mohr That's quite surprising and unlikely. Are you sure that's the SMILES which is causing the error?
Can you please try doing: `m = Chem.MolFromSmiles('c1ccc[nH]1')` directly from the Python prompt and confirm that you see the same error?

**Comment by Bernadette-Mohr** [comment]
You are right, it does work from the command line! So this issue must be caused by some other process in the code I'm using. 
Thank you, this brings me one step closer to a solution!
