### ISSUE TITLE
`GetSubstructMatch` throws if ring info is missing

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#4537]
On current master, running `SubstructMatch()` query which requires ring info on a mol which doesn't have it fails: 

```
In [46]: m = Chem.MolFromSmiles('N(=O)=O', False) 
    ...: m.GetSubstructMatch(Chem.MolFromSmarts('[#7&!R]'))                                                                                                                         
[13:56:46] 

****
Pre-condition Violation
RingInfo not initialized
Violation occurred on line 45 in file /Users/localbuildbot/runners/uyMiDz_z/0/core-infra/lib-build-scripts/build/rdkit/Code/GraphMol/RingInfo.cpp
Failed Expression: df_init
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-46-c71445ca1205> in <module>
      1 m = Chem.MolFromSmiles('N(=O)=O', False)
----> 2 m.GetSubstructMatch(Chem.MolFromSmarts('[#7&!R]'))

RuntimeError: Pre-condition Violation
	RingInfo not initialized
	Violation occurred on line 45 in file Code/GraphMol/RingInfo.cpp
	Failed Expression: df_init
	RDKIT: 2021.09.1pre
	BOOST: 1_76

```

~I think we don't have anything to explicitly initialize ring info from Python, so I'm using `AddRing()` as a workaround:~

```
In [47]: m = Chem.MolFromSmiles('N(=O)=O', False) 
    ...: m.GetRingInfo().AddRing([],[]) 
    ...: m.GetSubstructMatch(Chem.MolFromSmarts('[#7&!R]'))                                                                                                                         
Out[47]: (0,)
```

Apparently, using `AddRing()` is not a good idea, queries that do look for ring atoms don't work. Switching to `Chem.FastFindRings()` instead.

**Comment by ricrogz** [comment]
Small example of `AddRings()` not doing the right thing:

```In [17]: m = Chem.MolFromSmiles('c1ccccc1', False)
    ...: m.GetRingInfo().AddRing([],[])
    ...: m.GetSubstructMatches(Chem.MolFromSmarts('[#6&R]'))
Out[17]: ()

In [18]: m = Chem.MolFromSmiles('c1ccccc1', False)
    ...: Chem.FastFindRings(m)
    ...: m.GetSubstructMatches(Chem.MolFromSmarts('[#6&R]'))
Out[18]: ((0,), (1,), (2,), (3,), (4,), (5,))
```

**Comment by greglandrum** [comment]
Why not just call the ring finding code: `Chem.GetSymmSSSR(m)` or `Chem.FastFindRings(m)`?

**Comment by ricrogz** [comment]
> Why not just call the ring finding code: `Chem.GetSymmSSSR(m)` or `Chem.FastFindRings(m)`?

I do, I switched to `Chem.FastFindRings(m)` as soon as I noticed the `AddRing()` workaround results in the wrong answers for queries that require actual ring membership.

I initially didn't want to use `Chem.GetSymmSSSR(m)` because it is slow, and when I tried to find `Chem.FastFindRings(m)` I looked in the wrong place (for some reason I thought it was a member of Mol) , so I thought it wasn't wrapped.

**Comment by greglandrum** [comment]
It's just important to remember that FastFindRings() returns results which are useful to answer "is this atom/bond in a ring?" questions (i.e `[#6&R]` or `[#6&r]`), but not "is this atom in a ring of a particular size or in a particular number of rings" (i.e. like `[#6&R3]` or `[#6&r3]`)

**Comment by ricrogz** [comment]
Aha, interesting. I didn't know that one. Thanks!
