### ISSUE TITLE
Test FreeSASA  on the latest beta release (2.1 beta)

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#4583]
See if this fixes the windows build issues.

**Comment by ptosco** [comment]
@bp-kelley AFAIK the FreeSASA builds do work on Windows since I submitted #2402, not sure why they are disabled at the moment. I have just built them on my Windows test box. I will submit a PR that changes the flag for the Windows Azure pipeline.

**Comment by bp-kelley** [comment]
I had thought they worked as well, thanks @ptosco
