### ISSUE TITLE
Could upgrade to vf3 for subgraph isomorphism algorithm (https://github.com/MiviaLab/vf3lib)

### ISSUE THREAD

**Issue by goldwind-ting** [rdkit/rdkit#4589]
```
vf3lib is a software library containing all the currently published versions of VF3,
the fastest algorithm to solve subgraph isomorphism on large and dense graphs. 
Extremely efficient in time and memory!
                                               ---https://github.com/MiviaLab/vf3lib
```
In rdkit lib, it use vf2 algorithm to match substruct, in [here](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Substruct/SubstructMatch.cpp) and [here](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Substruct/vf2.hpp).I think it could be faster because above description with vf3 algorithm, but I have not test the performance of vf3lib.

**Comment by IchiruTake** [comment]
> _No description provided._

You should describe your feature request and make some assumption or description about the algorithm. If this feature has been available but needs upgrade to faster your requested algorithm , could you describe some basic description about the algorithm and the predicted performance (how much faster, how much less memory, etc). 

It is not a good idea to submit an issue related to feature request in title along with the ring, and expect they should understand. even though I am not the code contributor.

**Comment by goldwind-ting** [comment]
```
vf3lib is a software library containing all the currently published versions of VF3,
the fastest algorithm to solve subgraph isomorphism on large and dense graphs. 
Extremely efficient in time and memory!
                                               ---https://github.com/MiviaLab/vf3lib
```
In rdkit lib, it use vf2 algorithm to match substruct, in [here](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Substruct/SubstructMatch.cpp) and [here](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Substruct/vf2.hpp).I think it could be faster because above description with vf3 algorithm, but I have not test the performance of vf3lib.

**Comment by IchiruTake** [comment]
> ```
> vf3lib is a software library containing all the currently published versions of VF3,
> the fastest algorithm to solve subgraph isomorphism on large and dense graphs. 
> Extremely efficient in time and memory!
>                                                ---https://github.com/MiviaLab/vf3lib
> ```
> 
> In rdkit lib, it use vf2 algorithm to match substruct, in [here](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Substruct/SubstructMatch.cpp) and [here](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Substruct/vf2.hpp).I think it could be faster because above description with vf3 algorithm, but I have not test the performance of vf3lib.

Ok, I have read it. Thanks for your description. I have read article and found surprisingly result. If you are the authors of vf3, you can take this issue and make pull request to test your code.

**Comment by goldwind-ting** [comment]
Sorry, I am not the author of VF3, but I am learning VF3 and I will try to rewrite it.

**Comment by johnmay** [comment]
Just a note - chemical graphs are neither huge nor dense :)
