### ISSUE TITLE
pgsql: regression test failues for reaction_from_smarts() in reaction tests

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#4594]
**Describe the bug**

I see the following difference between the expected and actual output when running the regression tests:

```
diff -U3 /tmp/autopkgtest.kW2SZs/build.QkB/src/Code/PgSQL/rdkit/expected/reaction.out /tmp/autopkgtest.kW2SZs/build.QkB/src/Code/PgSQL/rdkit/results/reaction.out
--- /tmp/autopkgtest.kW2SZs/build.QkB/src/Code/PgSQL/rdkit/expected/reaction.out	2021-10-10 14:41:49.000000000 +0000
+++ /tmp/autopkgtest.kW2SZs/build.QkB/src/Code/PgSQL/rdkit/results/reaction.out	2021-10-10 14:42:50.446833411 +0000
@@ -20,15 +20,15 @@
 (1 row)
 
 SELECT reaction_from_smarts('[c1:1][c:2][c:3][c:4]c[c1:5]>CC(=O)O>[c1:1][c:2][c:3][c:4]n[c1:5]');
-                              reaction_from_smarts                               
----------------------------------------------------------------------------------
- c([cH:4][cH:3][cH:2][cH2:1])[cH2:5]>CC(=O)O>n([cH:4][cH:3][cH:2][cH2:1])[cH2:5]
+                       reaction_from_smarts                        
+-------------------------------------------------------------------
+ c([c:4][c:3][c:2][c:1])[c:5]>CC(O)=O>n([c:4][c:3][c:2][c:1])[c:5]
 (1 row)
 
 SELECT reaction_from_smarts('C(F)(F)F.[c1:1][c:2][c:3][c:4]c[c1:5]>CC(=O)O>[c1:1][c:2][c:3][c:4]n[c1:5]');
-                                  reaction_from_smarts                                  
-----------------------------------------------------------------------------------------
- c([cH:4][cH:3][cH:2][cH2:1])[cH2:5]>CC(=O)O.FC(F)F>n([cH:4][cH:3][cH:2][cH2:1])[cH2:5]
+                           reaction_from_smarts                           
+--------------------------------------------------------------------------
+ c([c:4][c:3][c:2][c:1])[c:5]>CC(O)=O.FC(F)F>n([c:4][c:3][c:2][c:1])[c:5]
 (1 row)
 
 SELECT reaction_from_smarts('c1ccc[n,c]c1>>c1nccnc1');
```

This looks like a functional change so wondering whether that is expected?

This test was on Postgres 14, but I'm re-running it on all supported Postgres versions via the PGDG builder now.

**To Reproduce**

Run pgsql cartridge regression suite.

**Expected behavior**

Regression suit passes.

**Configuration (please complete the following information):**
 - RDKit version: 202103.5
 - OS: Debian unstable
 - Are you using conda? no
 - If you are not using conda: how did you install the RDKit? Debian package (bug happens during build)

**Comment by mbanck** [comment]
Seems to be a problem with 202103.5 rather than the particular Postgres version, it fails for every version (I hope that link is publicly visible):
https://pgdgbuild.dus.dg-i.net/job/rdkit-binaries/23/architecture=amd64,distribution=sid/consoleFull#console-section-24

**Comment by mbanck** [comment]
This is still an open issue, and leads to rdkit no longer be shipped in Debian testing.

Can anybody (@greglandrum ?) comment on whether the above regression output change is bening (and can be ignored via an alternative test output), or should be addressed?

**Comment by ptosco** [comment]
@mbanck The [current 2021_09_2 release of RDKit](https://github.com/rdkit/rdkit/releases/tag/Release_2021_09_2) passes all Postgres tests, and I can see that the expected results are:
```
SELECT reaction_from_smarts('[c1:1][c:2][c:3][c:4]c[c1:5]>CC(=O)O>[c1:1][c:2][c:3][c:4]n[c1:5]');
                       reaction_from_smarts
-------------------------------------------------------------------
 c([c:4][c:3][c:2][c:1])[c:5]>CC(O)=O>n([c:4][c:3][c:2][c:1])[c:5]
(1 row)

SELECT reaction_from_smarts('C(F)(F)F.[c1:1][c:2][c:3][c:4]c[c1:5]>CC(=O)O>[c1:1][c:2][c:3][c:4]n[c1:5]');
                           reaction_from_smarts
--------------------------------------------------------------------------
 c([c:4][c:3][c:2][c:1])[c:5]>CC(O)=O.FC(F)F>n([c:4][c:3][c:2][c:1])[c:5]
(1 row)
```
Can you build and test that?

**Comment by mbanck** [comment]
Thanks for the hint, 2021.09.02 indeed works; I guess 2021.03 is no longer supported then?
