### ISSUE TITLE
bitinfo for morgan fp does not include some atoms, in symmetrical molecules

### ISSUE THREAD

**Issue by dehaenw** [rdkit/rdkit#4595]
**Describe the bug**
In certain symmetrical molecules, but not all, some atoms are not included where i would expect they are included in the bitinfo dict generated for Morgan fingerprints.

**To Reproduce**
I tried to generate the simplest possible molecule that shows this behavior, pyrrolidine. The below code will generate the Morgan fp, and associated info, clearly showing that the id 687543376 only has one associated atom.
```python
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem,Draw
from rdkit.Chem.Draw import IPythonConsole
m = Chem.MolFromSmiles('C1CNCC1')
IPythonConsole.drawOptions.addAtomIndices = True
display(m)
info={}
fp = AllChem.GetMorganFingerprint(m,3,bitInfo=info)
print(info)
print(info[687543376])
```
my output below:
![image](https://user-images.githubusercontent.com/66372095/136712286-370a4fbb-f069-49b3-94e3-7806c0ebaf0d.png)

```
{416356657: ((1, 1), (3, 1)), 687543376: ((0, 3),), 725338437: ((0, 2), (4, 2)), 1289643292: ((2, 1),), 2059101240: ((1, 2), (3, 2)), 2132511834: ((2, 0),), 2142032900: ((0, 1), (4, 1)), 2968968094: ((0, 0), (1, 0), (3, 0), (4, 0)), 3781885420: ((2, 2),)}
((0, 3),)
```
if the ring is opened to diethylamine (smiles CCNCC), there is no such problem, and symmetry is respected.

**Expected behavior**
Due to its symmetry, the atoms with index 0 and 4 are equivalent. I would expect that info[687543376] would return ((0,3),(4,3)). Instead, it returns ((0,3),). Hopefully I am not missing something obvious or fundamental.

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.1
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.9.2
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by dehaenw** [comment]
For the time being, I have this workaround:
```python
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem,Draw
from rdkit.Chem.Draw import IPythonConsole
m = Chem.MolFromSmiles('C1CNCC1')
IPythonConsole.drawOptions.addAtomIndices = True
display(m)
info={}
infoFull={}
fp = AllChem.GetMorganFingerprint(m,3,bitInfo=info,includeRedundantEnvironments=False)
fp2 = AllChem.GetMorganFingerprint(m,3,bitInfo=infoFull,includeRedundantEnvironments=True)
info = {key: infoFull[key] for key in info.keys()}
print(info[687543376])
```
output is:
`((0, 3), (4, 3))`
the expected value

**Comment by greglandrum** [comment]
I think you are defining terms differently than the RDKit and I do: the environments (0,3) and (4,3), which both hash to the bit 687543376, are redundant because they contain the same atoms and bonds. Therefore only one of those shows up in the fingerprint bit information by default.
