### ISSUE TITLE
Help: I'm trying to link functions to run structure similarities but getting error

### ISSUE THREAD

**Issue by RicardoMBorges** [rdkit/rdkit#4601]
Hello,
I'm trying to link functions to run structure similarities but I'm getting errors when I run more than some hundreds at a time. Could any help me?
Is there a limitation of bits going on?
The code:
fplist = [] #fplist
for mol in datafile['Molecule']: # the structures in rdkit already
    fp = Chem.GetMorganFingerprintAsBitVect(mol,2)
    fplist.append(fp)
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-110-e14a5ec78691> in <module>
      1 fplist = [] #fplist
      2 for mol in datafile['Molecule']:
----> 3     fp = Chem.GetMorganFingerprintAsBitVect(mol,2)
      4     fplist.append(fp)

ArgumentError: Python argument types in
    rdkit.Chem.rdMolDescriptors.GetMorganFingerprintAsBitVect(NoneType, int)
did not match C++ signature:
    GetMorganFingerprintAsBitVect(class RDKit::ROMol mol, unsigned int radius, unsigned int nBits=2048, class boost::python::api::object invariants=[], class boost::python::api::object fromAtoms=[], bool useChirality=False, bool useBondTypes=True, bool useFeatures=False, class boost::python::api::object bitInfo=None, bool includeRedundantEnvironments=False)

**Comment by RicardoMBorges** [comment]
Right, thanks! I saved into a csv and found the empty cells. I’ll try to implement “find empty” and skip in my process… have no idea how yet!
Thanks again

**Comment by greglandrum** [comment]
the test you're looking for is:
```
if mol is None:
  continue
```
