### ISSUE TITLE
RemoveHs behaves differently in Chem.RemoveHs() and Chem.MolFromMolBlock(removeHs=True)

### ISSUE THREAD

**Issue by diogomart** [rdkit/rdkit#4618]
The stereochemistry is different when reading a MOL file with:
 1. `Chem.MolFromMolBlock(removeHs=True)`
 2. `Chem.MolFromMolBlock(removeHs=False)` followed by `Chem.RemoveHs()`

I expected the same results using either the first or second approach. Here's Python code to reproduce:

```python
import rdkit
from rdkit import Chem

print('version:', rdkit.__version__)

mol_block = (
    "\n"
    " smiles: N=CC\n"
    "\n"
    "  8  7  0  0  0  0  0  0  0  0999 V2000\n"
    "    1.0504    0.1223    0.0075 N   0  0  0  0  0  0  0  0  0  0  0  0\n"
    "    2.3400    0.1131    0.0038 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
    "    3.1272    1.2936    0.4734 C   0  0  0  0  0  0  0  0  0  0  0  0\n"
    "    0.6918   -0.7716   -0.3481 H   0  0  0  0  0  0  0  0  0  0  0  0\n"
    "    2.9020   -0.7686   -0.3469 H   0  0  0  0  0  0  0  0  0  0  0  0\n"
    "    2.4661    2.1019    0.7949 H   0  0  0  0  0  0  0  0  0  0  0  0\n"
    "    3.7641    1.6421   -0.3437 H   0  0  0  0  0  0  0  0  0  0  0  0\n"
    "    3.7641    0.9856    1.3066 H   0  0  0  0  0  0  0  0  0  0  0  0\n"
    "  1  2  2  0\n"
    "  1  4  1  0\n"
    "  2  3  1  0\n"
    "  2  5  1  0\n"
    "  3  6  1  0\n"
    "  3  7  1  0\n"
    "  3  8  1  0\n"
    "M  END\n"
    )

mol_a = Chem.MolFromMolBlock(mol_block)
print("1st approach:", Chem.MolToSmiles(mol_a))

mol_b_h = Chem.MolFromMolBlock(mol_block, removeHs=False)
mol_b = Chem.RemoveHs(mol_b_h)
print("2nd approach:", Chem.MolToSmiles(mol_b))
```

Output:
```console
version: 2021.03.5
1st approach: CC=N
2nd approach: [H]/N=C/C
```

Note: this happens only for MOL/SDF files written by other tools (e.g. OpenBabel). MOL files written by RDKit have the stereo field of the `C=N` bond with a `3` instead of a `0`, i.e., `  1  2  2  3` instead of `  1  2  2  0`, and then RemoveHs always removes the hydrogen and the resulting molecule has stereochemistry undefined using either the first or second approach. May be related to https://github.com/rdkit/rdkit/issues/1810

Kubuntu 20.04, conda-forge rdkit 2021.03.5, Python 3.9

**Comment by bp-kelley** [comment]
@greglandrum, I didn't look at the whole code, stereo is being detected first.

**Comment by greglandrum** [comment]
This was fixed at some point and is no longer an issue
