### ISSUE TITLE
Enhanced Stereo is lost when using GetMolFrags(m, asMols=True)

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#4642]
**Describe the bug**

When calling `GetMolFrags(m, asMols=True)` the returned molecules loose their enhanced stereo information (stereogroups) and instead get R/S markers IF there are multiple fragments in the molecule. If `m` is only one fragment, the enhanced stereo is preserved. 

I assume in that case the input is just returned unmodified where as with multiple components some form of copy is used that looses information.

**To Reproduce**

```
mx = Chem.MolFromSmiles('CCCC.C[C@H](F)C[C@H](O)Cl |o1:5,o2:8|')
components = Chem.GetMolFrags(mx, asMols=True)
components[1]
```

`components[1].GetStereoGroups()[0].GetGroupType()`

Will then also lead to an IndexError as no StereoGroups are actually present anymore.

**Expected behavior**

That the enhanced stereo is preserved.

**Screenshots**

![image](https://user-images.githubusercontent.com/1567309/138891138-56481328-ed89-4f13-8f4d-1a33caaf0d05.png)

**Configuration (please complete the following information):**
 - RDKit version:  2021.03.5
 - OS:  Win 10
 - Python version (if relevant): 3.9
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by mc-robinson** [comment]
I just wanted to note that I have independently come across this bug recently. 

In particular, this functionality would be really useful when trying to de-salt molecules with enhanced stereochemistry information.
