### ISSUE TITLE
AddHs with addCoords=True generates wrong conformation on hydrogen with sulfur atom

### ISSUE THREAD

**Issue by Hong-Rui** [rdkit/rdkit#4667]
Hi developers:

I have a molecule with this SMILES: ```CO[C@@H]1C[C@@H](CN(C)C(=O)c2csc([SH](N)(=O)N3CCCCC3)c2)[N@@H+](C)C1```
It looks like
![1635915671(1)](https://user-images.githubusercontent.com/8930355/140011933-1840ed03-0a82-4398-94d0-8c97c08ff9e8.png)

There is a 6-valent sulfur atoms.

First I generated a conformation with EDKTGv3, ```AllChem.EmbedMultipleConfs(mol, 10)```.
The conformation without H looks fine:
![1635915828(1)](https://user-images.githubusercontent.com/8930355/140012093-58be1f22-ce6b-4ec0-a752-9aab2df1cea2.png)

But when I use ```AddHs(mol, addCoords=True)```, it generates wrong hydrogen conformations on the 6-valent sulfur, with a (0.0, 0.0, 0.0) positions for the hydrogen atom.
![1635915961(1)](https://user-images.githubusercontent.com/8930355/140012243-8054ade6-5af2-43b0-8ab5-17e236d0c0ac.png)

I also attached both SDF files for easy debugging.
[rdkit_addhs_issue.zip](https://github.com/rdkit/rdkit/files/7465437/rdkit_addhs_issue.zip)

btw, if I first do ```AddHs``` on the 2D molecule and then generate 3D conformers, then the conformations of hydrogen look correct.
Hope this is helpful, thanks!

**Comment by greglandrum** [comment]
The position of that H is bad, and we can take a look into that, but it is a much better idea to add the Hs before generating 3D coordinates: you will get better 3D conformers.

**Comment by Hong-Rui** [comment]
Hi, is this bug going to be fixed? @greglandrum 
For some algorithmic reason I have to use ```AddHs(mol, addCoords=True)``` and cannot add Hs on the 2D step.

Hope this would be fixed soon, many thanks!

**Comment by greglandrum** [comment]
I'm sure it will be fixed at some point, but that's dependent on one of the volunteers who work on the project having the time and interest to dig into the bug.

Again, I cannot emphasize enough: you may have an "algorithmic" reason for wanting to generate 3D conformers without Hs, but the conformers you are generating that way are not reliable. So if you care about the conformers, you should consider revising the algorithm
