### ISSUE TITLE
Substructure match is missed

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#4674]
```
from rdkit import Chem
m1 = Chem.MolFromSmiles('FC12C3CCCC1C32F')
m2 = Chem.MolFromSmiles('C12C3CCCC1C32')
m3 = Chem.MolFromSmiles('C1CC2C3C(C1)C23')
assert Chem.MolToSmiles(m2) == Chem.MolToSmiles(m3)
assert m1.HasSubstructMatch(m2)
assert m1.HasSubstructMatch(m3)
```

The last assertion fails.

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.2
 - OS: linux

Reported on the mailing list here: https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg10852.html

**Comment by IchiruTake** [comment]
> ```
> from rdkit import Chem
> m1 = Chem.MolFromSmiles('FC12C3CCCC1C32F')
> m2 = Chem.MolFromSmiles('C12C3CCCC1C32')
> m3 = Chem.MolFromSmiles('C1CC2C3C(C1)C23')
> assert Chem.MolToSmiles(m2) == Chem.MolToSmiles(m3)
> assert m1.HasSubstructMatch(m2)
> assert m1.HasSubstructMatch(m3)
> ```

Preliminary: I don't write that mailing list, but I can reproduce your result with the following code on PyCharm IDE and turns out the molecular graph generated is not correct:

```
from rdkit import Chem
m1 = Chem.MolFromSmiles('FC12C3CCCC1C32F')
m2 = Chem.MolFromSmiles('C12C3CCCC1C32')
m3 = Chem.MolFromSmiles('C1CC2C3C(C1)C23')

print(Chem.MolToSmiles(m2) == Chem.MolToSmiles(m3)) 
>>> True

print(m1.HasSubstructMatch(m2))
>>> True

print(m1.HasSubstructMatch(m3))
>>> False

print(m2.HasSubstructMatch(m3))
>>> False

print(m3.HasSubstructMatch(m2))
>>> True
```
