### ISSUE TITLE
wavybond direction cleared

### ISSUE THREAD

**Issue by jank9201** [rdkit/rdkit#4698]
the method of the following:
```
void finishMolProcessing(RWMol *res, bool chiralityPossible, bool sanitize,
                         bool removeHs)///from GraphMol\FileParsers\MolFileParser.cpp
contains the following function:

void ClearSingleBondDirFlags(ROMol &mol) {
  for (RWMol::BondIterator bondIt = mol.beginBonds(); bondIt != mol.endBonds();
       ++bondIt) {
    if ((*bondIt)->getBondType() == Bond::SINGLE) {
      if ((*bondIt)->getBondDir() == Bond::UNKNOWN) {
        (*bondIt)->setProp(common_properties::_UnknownStereo, 1);
      }
      (*bondIt)->setBondDir(Bond::NONE);
    }
  }
}///from GraphMol\FileParsers\MolFileStereochem.cpp
```
in this function，
Bond::UNKNOWN used to indicate wavy bond, here was reset to Bond::NONE. so the current MolDraw2D can not check which bond is wavy.
-----------------------------------------

If you have a question about the RDKit or aren't sure if what you're seeing is the right behavior please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

Please help us help you: We normally need the information below in order to answer questions or understand bug reports. If you do not provide the information requested we may not be able to help you and will probably close the issue.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 
 - OS: [e.g. Ubuntu 20.04]
 - Python version (if relevant):
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested informatio and reopen the issue and then we'll try to help.
