### ISSUE TITLE
molfile parse may be a warning more perfect than exception throw

### ISSUE THREAD

**Issue by jank9201** [rdkit/rdkit#4699]
-----------------------------------------
when parse a mol file  with some error in it/ from chemdraw(chemdraw allowed),
the following method throw exception to cause the program crush.
int Atom::calcExplicitValence(bool strict)///Code\GraphMol\Atom.cpp
the method chain is:
FileParserUtils::finishMolProcessing->MolOps::sanitizeMol(RWMol &mol)->sanitizeMol(mol, failedOp, SANITIZE_ALL)->ROMol::updatePropertyCache(bool strict = true)(mol.updatePropertyCache(true)->void Atom::updatePropertyCache(bool strict)->int Atom::calcExplicitValence(bool strict)

If you have a question about the RDKit please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

If you have a suggestion for a new RDKit feature or enhancement please consider starting a discussion about it using the Discussions tab above (https://github.com/rdkit/rdkit/discussions) before creating an issue. Community input on how a feature could work is often helpful and it could be that there's already a way to do what you want to do in the RDKit.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by greglandrum** [comment]
The current behavior is by design: the RDKit throws exceptions on the C++ side when you attempt to process a molecule which has chemistry problems. You can catch the exceptions in your own code and generate warnings if that fits your use case better.
