### ISSUE TITLE
MolFromSmarts bug 

### ISSUE THREAD

**Issue by SejeongPark8354** [rdkit/rdkit#4711]
**Describe the bug**
```
mol = rdkit.Chem.MolFromSmarts('')
print(mol)
```
When I use MolFromSmarts, I found the bug that the module also can convert blank. 
The result was <rdkit.Chem.rdchem.Mol object at 0x7fb3cf351030>.

**To Reproduce**
```
mol = rdkit.Chem.MolFromSmarts('')
print(mol)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/65217511/142365623-77e86f43-cd9c-45c3-8484-ee08c11f1ccc.png)

**Configuration (please complete the following information):**
 - RDKit version: 2020.03.3
 - OS: Ubuntu 16.04.5

**Comment by mwojcikowski** [comment]
Hi @SejeongPark8354,

MolFromSmiles/Smarts recently had such feature added - empty string is syntactically correct SMILES/SMARTS with zero atoms, so it converts into empty mol. You can check by calling `mol.GetNumAtoms()`.

**Comment by SejeongPark8354** [comment]
@mwojcikowski Ah! OK. Thank you for your explanation.
