### ISSUE TITLE
request for `useCounts` option for `GetMorganFingerprintAsBitVect`

### ISSUE THREAD

**Issue by ljmartin** [rdkit/rdkit#4713]
Hi RDKit, 
The native `AllChem.GetMorganFingerprint(m, 2)` has `useCounts` defaulting to True. It's great. Could we possibly have the option to turn on bit-count simulation for `GetMorganFingerprintAsBitVect` please? Looking at the docs it doesn't appear:

```
rdkit.Chem.rdMolDescriptors.GetMorganFingerprintAsBitVect((Mol)mol, (int)radius[, (int)nBits=2048[, 
(AtomPairsParameters)invariants=[][, (AtomPairsParameters)fromAtoms=[][, (bool)useChirality=False[, 
(bool)useBondTypes=True[, (bool)useFeatures=False[, (AtomPairsParameters)bitInfo=None[, 
(bool)includeRedundantEnvironments=False]]]]]]]]) 
```
https://www.rdkit.org/docs/source/rdkit.Chem.rdMolDescriptors.html#rdkit.Chem.rdMolDescriptors.GetMorganFingerprintAsBitVect

thanks :)

**Comment by greglandrum** [comment]
Hi @ljmartin : you can do count simulation for any of the supported fingerprint types by using the 
There's more information in this blog post: https://greglandrum.github.io/rdkit-blog/fingerprints/technical/reference/2021/07/06/simulating-counts.html
