### ISSUE TITLE
[ENH]: Keyword Argument should be matched into one category -> May cause broken ...

### ISSUE THREAD

**Issue by IchiruTake** [rdkit/rdkit#4714]
No bug fix or feature enhancement. Only some change to increase consistency. Although it can cause **backward incompatible** or some code attempted to define this argument to be **failed**.

The use of `GetHashedAtomPairFingerprint` and `GetHashedTopologicalTorsionFingerprint`, ... use the keyword `includeChirality` while in the case of `GetMorganFingerprint`, ... use the keyword `useChirality`.  

-> Suggestion: It should be merged/selected as either `includeChirality` or  `useChirality` to ensure consistency rather than two separate keywords.

**Comment by greglandrum** [comment]
The new interface using fingerprint generators was created to address this problem of inconsistent (and confusing) arguments to the fingeprinting functions without breaking backwards compatibility.
