### ISSUE TITLE
TorsionFingerprints raises error with S(Cl)F4 group

### ISSUE THREAD

**Issue by kazuyaujihara** [rdkit/rdkit#4720]
**Describe the bug**

`TorsionFingerprints.CalculateTorsionLists` can raise exception when molecular contains atom having more than four connections.

**To Reproduce**

```python
from rdkit import Chem
from rdkit.Chem import TorsionFingerprints

SMILES_SCHEMBL944653 ="S(F)(F)(F)(F)(Cl)c1ccccc1"
smiles = SMILES_SCHEMBL944653
mol = Chem.MolFromSmiles(smiles)
fp = TorsionFingerprints.CalculateTorsionLists(mol)
```

**Expected behavior**

Hopefully it works. At least, this error message should be fixed like "Number of connections above four is not supported.".

**Screenshots**

```
Traceback (most recent call last):
  File "./a.py", line 7, in <module>
    fp = TorsionFingerprints.CalculateTorsionLists(mol)
  File "/rdkit/rdkit/Chem/TorsionFingerprints.py", line 235, in CalculateTorsionLists
    d1 = _getIndexforTorsion(nb1, inv)
  File "/rdkit/rdkit/Chem/TorsionFingerprints.py", line 135, in _getIndexforTorsion
    at = _doMatchExcept1(inv, neighbors)  # two neighbors the same, one different
  File "/rdkit/rdkit/Chem/TorsionFingerprints.py", line 69, in _doMatchExcept1
    raise ValueError("Number of atoms must be three")
ValueError: Number of atoms must be three
```

**Configuration (please complete the following information):**
 - RDKit version: master branch (commit id:06027dcd05674787b61f27ba46ec0d42a6037540)
 - OS: Ubuntu 20.04
 - Are you using conda? No

**Additional context**

I think it is possible to define Torsion Fingerprints if the two substituents attached to one atom are different and the other substituents are the same, otherwise it is difficult to define. Preferably , `S(Cl)(F)(F)(F)(F)` group is supported.

**Comment by greglandrum** [comment]
@kazuyaujihara : I agree that this looks like a bug. But the functionality you're calling is something I haven't looked at (or maintained) in quite a while. What are you trying to do?
