### ISSUE TITLE
ImportError: /home/myname/lib/rdkit/rdkit/Chem/rdchem.so: undefined symbol: _ZN5RDKit5RWMol7destroyEv

### ISSUE THREAD

**Issue by mainguyenanhvu** [rdkit/rdkit#4728]
**Describe the bug**
When `from rdkit import Chem`, it said that:
`ImportError: /home/myname/lib/rdkit/rdkit/Chem/rdchem.so: undefined symbol: _ZN5RDKit5RWMol7destroyEv`

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import AllChem, PandasTools
from rdkit import DataStructs
from rdkit.Chem.Fingerprints import FingerprintMols
```

**Screenshots**
![image](https://user-images.githubusercontent.com/26211591/143054051-b1d8772c-8ab0-4102-ba39-a36918f02092.png)

**Configuration (please complete the following information):**
 - RDKit version: rdkit                     2021.09.2        py39hccf6a74_0    conda-forge
 - OS: Linux pop-os 5.13.0-7614-generic #14~1631647151~20.04~930e87c-Ubuntu SMP Fri Sep 17 00:26:31 UTC  x86_64 x86_64 x86_64 GNU/Linux
 - Python version (if relevant): 3.9.7
 - Are you using conda? Yes, 4.10.3
 - If you are using conda, which channel did you install the rdkit from? conda create -c conda-forge -n rdkit rdk

**Comment by greglandrum** [comment]
are you sure that you have the conda environment where you installed the rdkit activated?

What exact command did you execute to install the RDKit? The one shown above is incorrect and would not work.

**Comment by mainguyenanhvu** [comment]
Sorry for my mistake. I used this command to create a new conda enviroment:
`conda create -c conda-forge -n rdkit rdkit`

**Comment by ptosco** [comment]
The path in your `ImportError` suggests that you are not actually loading the `rdkit` module from `conda`.
```
ImportError: /home/myname/lib/rdkit/rdkit/Chem/rdchem.so: undefined symbol: _ZN5RDKit5RWMol7destroyEv
```
On my machine the path of `rdchem.so` is:
```
/home/myname/.conda/envs/rdkit/lib/python3.8/site-packages/rdkit/Chem/rdchem.so
```
So my guess is that you are picking RDKit from a non-conda installation while running the conda Python interpreter, which is why you have conflicting symbols.

**Comment by mainguyenanhvu** [comment]
Thank you for your time. I fixed it by removing other installations.
