### ISSUE TITLE
Different result between Linux and Mac for `EmbedMultipleConfs`

### ISSUE THREAD

**Issue by ElricleNecro** [rdkit/rdkit#4735]
**Describe the bug**
The `EmbedMultipleConfs` function gives different results between Mac and Linux (ubuntu 20.04), for the same seed and parameters.

**To Reproduce**
Run this snippets on a Mac and a Linux (ubuntu 20.04) computer:
```python
from rdkit.Chem import AddHs, MolFromSmiles
from rdkit.Chem.Descriptors3D import Asphericity
from rdkit.Chem.rdDistGeom import EmbedMultipleConfs

smiles = 'Cc1ccncc1-c1cccc(C(=O)Nc2ccc3nn(CC(=O)N4CCN(C)CC4)cc3c2)n1'
mol = MolFromSmiles(smiles)
mol = AddHs(mol)
EmbedMultipleConfs(mol, randomSeed=42)
print(Asphericity(mol))
```
It give `0.7611619527062681` on Linux and `0.7594155532898804` on Mac OS.

**Expected behavior**
We expect those calls to not depend on the OS.

**Configuration (please complete the following information):**
 - RDKit version: `2021.03.5`.
 - OS: Ubuntu 20.04, Mac OS 11 and Mac OS 12 (both Mac OS were using intel processors).
 - Python version (if relevant): 3.7.9 and 3.7.11 were tested.
 - Are you using conda? yes.
 - If you are using conda, which channel did you install the rdkit from? `conda-forge`.

**Comment by IchiruTake** [comment]
> **Describe the bug** The `EmbedMultipleConfs` function gives different results between Mac and Linux (ubuntu 20.04), for the same seed and parameters.
> 
> **To Reproduce** Run this snippets on a Mac and a Linux (ubuntu 20.04) computer:
> 
> ```python
> from rdkit.Chem import AddHs, MolFromSmiles
> from rdkit.Chem.Descriptors3D import Asphericity
> from rdkit.Chem.rdDistGeom import EmbedMultipleConfs
> 
> smiles = 'Cc1ccncc1-c1cccc(C(=O)Nc2ccc3nn(CC(=O)N4CCN(C)CC4)cc3c2)n1'
> mol = MolFromSmiles(smiles)
> mol = AddHs(mol)
> EmbedMultipleConfs(mol, randomSeed=42)
> print(Asphericity(mol))
> ```
> 
> It give `0.7611619527062681` on Linux and `0.7594155532898804` on Mac OS.
> 
> **Expected behavior** We expect those calls to not depend on the OS.
> 
> **Configuration (please complete the following information):**
> 
> * RDKit version: `2021.03.5`.
> * OS: Ubuntu 20.04, Mac OS 11 and Mac OS 12 (both Mac OS were using intel processors).
> * Python version (if relevant): 3.7.9 and 3.7.11 were tested.
> * Are you using conda? yes.
> * If you are using conda, which channel did you install the rdkit from? `conda-forge`.

I don't think it actually the bug but rather the random algorithm at each OS. If you search the `random algorithm in Mac and Linux`, you would see that the algorithm generator is not the same across languages and platform. Since RDKit is built on C/C++, this happened the same. This is the language and OS issue, but not for the RDKit.

Solution: You can increase the maximum number of conformers, probably 100, 500 or 1000. It may cause some extra time. Then getting the significant numbers you wants such as 3 or 4 SFS (=0.761 or 0.7594). 

https://pretagteam.com/question/why-does-rand-repeat-numbers-far-more-often-on-linux-than-mac

**Comment by ElricleNecro** [comment]
> I don't think it actually the bug but rather the random algorithm at each OS. If you search the `random algorithm in Mac and Linux`, you would see that the algorithm generator is not the same across languages and platform. Since RDKit is built on C/C++, this happened the same. This is the language and OS issue, but not for the RDKit.
> 
> Solution: You can increase the maximum number of conformers, probably 100, 500 or 1000. It may cause some extra time. Then getting the significant numbers you wants such as 3 or 4 SFS (=0.761 or 0.7594).
> 
> https://pretagteam.com/question/why-does-rand-repeat-numbers-far-more-often-on-linux-than-mac

Expect that the random number generator used, from what I got in the code, is `boost::minstd_rand`. Its implementation is system independent and should as such gives the same result for the same seed everywhere (unless I misread `boost` documentation).

I would have agreed if they were using the system `rand` function (but no one should ever use it).

**Comment by bp-kelley** [comment]
IMO this isn't a bug, this is just a fact of data science life.  For any sufficiently complicated piece of math that relies on optimizers or matrix inversions, small differences in floating point results can lead to very different results.

I don't think there is any expectation that the same seed will generate the same conformations on different architectures.  While I expect the random number generator is producing the same values, different compiler may produce slightly different eigenvalues in the matrix inversion or have slightly different floating point results in the code path of the optimizer.  These are almost impossible to resolve and probably not worth the time.  I chased this down for other conformation generators in the past and it simply wasn't worth it.

As an aside, I have the same issue with a gaussian process generating different results on linux versus osx and that doesn't use any random seeds.   So if you want the same exact result, you need to isolate the software and the hardware.  Obviously, this is just my opinion, but it is a relatively hard fought one.

**Comment by greglandrum** [comment]
To the point about the RNG: the generator should be generating consistent results cross platorms. That's why we use the boost generator.

I would expect the conformers to be very similar to each other across architectures but, as Brian points out, not exactly the same. I think this is unavoidable without expending unreasonable amounts of effort.

@ElricleNecro: if you want to see how different the conformers actually are, try writing a SDF out on one system, reading it in on the other, and doing an RMSD comparison to see what the actual difference is.

**Comment by ElricleNecro** [comment]
> @ElricleNecro: if you want to see how different the conformers actually are, try writing a SDF out on one system, reading it in on the other, and doing an RMSD comparison to see what the actual difference is.

We've done an RMSD between 6 of them, and got those values:
1. `0.04204240716229267`
1. `0.7802367476606059`
1. `0.4103210854928126`
1. `0.01971525297834144`
1. `0.10389135093933471`
1. `0.47527924760081847`

Some values seems rather high : `0.7802367476606059`

**Comment by ElricleNecro** [comment]
@greglandrum what do you think about those RMSD?
