### ISSUE TITLE
MurckoScaffoldSmiles() don't remove double bond side chains

### ISSUE THREAD

**Issue by filvaleriia** [rdkit/rdkit#4740]
**Describe the bug**
The function MurckoScaffoldSmiles() don't remove double bond side chains

**To Reproduce**
```
from rdkit.Chem.Scaffolds.MurckoScaffold import MurckoScaffoldSmiles
from rdkit import Chem
print("Original strucutre")
display(Chem.MolFromSmiles("C=C1/C(=CC=C(/CC)c2cccc(CCCCCC(C)(C)O)c2)C[C@@H](O)C(=O)[C@@H]1O"))
print("Murcko scaffold")
display(Chem.MolFromSmiles(MurckoScaffoldSmiles("C=C1/C(=CC=C(/CC)c2cccc(CCCCCC(C)(C)O)c2)C[C@@H](O)C(=O)[C@@H]1O")))
```

**Expected behavior**
I expect the murcko scaffold don't have all side chains, the double bond too, because murcko scaffold is as the union of ring systems and linkers in a molecule.
https://pubs.acs.org/doi/full/10.1021/jm9602928

**Screenshots**

![Screenshot from 2021-11-28 15-27-58](https://user-images.githubusercontent.com/61471458/143772111-5dc2ca69-3fdc-442e-a418-89219ecfe1c3.png)

**Configuration (please complete the following information):**
 - RDKit version: ```2021.03.5```
 - OS: CentOS Linux 7 (Core)
 - Python version (if relevant): Python 3.8.12
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? ```conda-forge```

**Comment by greglandrum** [comment]
Duplicate with #4093
