### ISSUE TITLE
PandasTools.LoadSDF: very verbose infinite loop on bad input

### ISSUE THREAD

**Issue by Limsande** [rdkit/rdkit#4748]
**Describe the bug**
When passing `float('nan')` to `PandasTools.LoadSDF` it seems to get stuck in an infinite loop:
```
[19:47:53] Unexpected error hit on line 1
[19:47:53] ERROR: moving to the beginning of the next molecule
[19:47:53] Unexpected error hit on line 2
[19:47:53] ERROR: moving to the beginning of the next molecule
[19:47:53] Unexpected error hit on line 3
# snip #
```
This seems to go on forever (I waited about five minutes before interrupting) with increasing line number. The stack trace after interrupting shows that the problem might be in `ForwardSDMolSupplier`:
```
[19:52:45] Unexpected error hit on line 16724731
^C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Luis/.conda/envs/rdkit/lib/python3.9/site-packages/rdkit/Chem/PandasTools.py", line 473, in LoadSDF
    for i, mol in enumerate(Chem.ForwardSDMolSupplier(f, sanitize=sanitize, removeHs=removeHs,
                                strictParsing=strictParsing))
KeyboardInterrupt
```

**To Reproduce**
```python
from rdkit.Chem.PandasTools import LoadSDF
LoadSDF(float('nan'))
```

**Expected behavior**
Raising and error informing about an invalid input file.

**Configuration (please complete the following information):**
 - RDKit version: Found with 2021.09.1 and 20121.09.2
 - OS: Fedora 34
 - Python version (if relevant): 3.9.7
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? Tested both rdkit and conda-forge

**Additional context**
I encountered this bug by looping over a list of SD file names to load. The list was actually a column of a DataFrame with some missing values, hence the `nan`s. Now I see that the error is totally preventable on my end by checking for missing values. Nevertheless this is not the behaviour one expects from a function which loads files.

If this was a Python issue I'd be happy to come up with a fix myself. But I don't know c++ to investigate ForwardSDMolSupplier.

**Comment by greglandrum** [comment]
confirmed.

**Comment by johbrob** [comment]
Something similar happened to me as I tried to load the qm8.sdf dataset from MoleculeNet (https://moleculenet.org/datasets-1) with the following code snippet:

from pathlib import Path
from rdkit.Chem.PandasTools import LoadSDF

def load_qm8(dataset_path):
    path = dataset_path.parent / Path("gdb8/qm8.sdf")
    print(path.exists())
    df = LoadSDF(path, smilesName='SMILES')
  

 The loop on line 470-471 in rdkit.Chem.PandasTools.py iterates passed the number of molecules that are supposed to exist in the dataset and all mol variables are None (line 473) so it seems like something is wrong with Chem.ForwardSDMolSupplier
