### ISSUE TITLE
rdMolStandardize.LargestFragmentChooser select an incorrect largest fragment

### ISSUE THREAD

**Issue by Tong-Du** [rdkit/rdkit#4754]
**Describe the bug**
Function `rdkit.Chem.MolStandardize.rdMolStandardize.LargestFragmentChooser` select an incorrect largest fragment.

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize
mol = Chem.MolFromSmiles('CNC[C@@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O.c1cc2c(cc1C(=O)O)oc(n2)c3cc(cc(c3)Cl)Cl')
largest_Fragment = rdMolStandardize.LargestFragmentChooser()
largest_mol = largest_Fragment.choose(mol)
print(Chem.MolToSmiles(largest_mol), "Mw:", Descriptors.MolWt(largest_mol), "NumAtoms:", largest_mol.GetNumAtoms())
```
```
--------output--------
NC[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO Mw: 195.215 NumAtoms: 13
# This is a wrong result
```

```python
from rdkit import Chem
from rdkit.Chem import rdmolops
mol = Chem.MolFromSmiles('CNC[C@@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O.c1cc2c(cc1C(=O)O)oc(n2)c3cc(cc(c3)Cl)Cl')

mol_frags = rdmolops.GetMolFrags(mol, asMols = True)
largest_mol = max(mol_frags, default=mol, key=lambda m: m.GetNumAtoms())
print(Chem.MolToSmiles(largest_mol), "Mw:", Descriptors.MolWt(largest_mol), "NumAtoms:", largest_mol.GetNumAtoms())
```
```
--------output--------
O=C(O)c1ccc2nc(-c3cc(Cl)cc(Cl)c3)oc2c1 Mw: 308.12 NumAtoms: 20
# This is a correct result
```

**Expected behavior**
These two results should be equal.

**Configuration (please complete the following information):**
 - RDKit version:  2021.03.3
 - OS: Centos
 - Are you using conda? Yes
 - conda install rdkit -c conda-forge

**Comment by bp-kelley** [comment]
The largest fragment chooser includes hydrogens as part of the "larger"

```
>>> Chem.AddHs(Chem.MolFromSmiles("CNC[C@@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O")).GetNumAtoms()
30
>>> Chem.AddHs(Chem.MolFromSmiles("c1cc2c(cc1C(=O)O)oc(n2)c3cc(cc(c3)Cl)Cl")).GetNumAtoms()
27
```

So under this definition, the result is "correct" although I think it may be incorrect for the operation at hand.

**Comment by ptosco** [comment]
The C++ port of MolVS done by Susan closely follows the original MolVS implementation, where the atom count includes hydrogens:
RDKit:
https://github.com/rdkit/rdkit/blob/6b5784c74a70c78a673d739554545d9b5501c57d/Code/GraphMol/MolStandardize/Fragment.cpp#L198
MolVS:
https://github.com/mcs07/MolVS/blob/d815fe52d160abcecbcbf117e6437bf727dbd8ad/molvs/fragment.py#L228

If you change the testing code above to include Hs in the count, you will get the same results as using `LargestFragmentChooser`:
```
largest_Fragment = rdMolStandardize.LargestFragmentChooser(True)
largest_mol = largest_Fragment.choose(mol)
print(Chem.MolToSmiles(largest_mol), "Mw:", Descriptors.MolWt(largest_mol), "NumAtoms:", Chem.AddHs(largest_mol).GetNumAtoms())
CNC[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO Mw: 195.215 NumAtoms: 30

mol_frags = Chem.GetMolFrags(mol, asMols = True)
largest_mol2 = max(mol_frags, key=lambda m: Chem.AddHs(m).GetNumAtoms())
print(Chem.MolToSmiles(largest_mol2), "Mw:", Descriptors.MolWt(largest_mol2), "NumAtoms:", Chem.AddHs(largest_mol2).GetNumAtoms())
CNC[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO Mw: 195.215 NumAtoms: 30
```

I do agree that this may be quite misleading, and I would probably add a parameter to only consider heavy atoms.
@greglandrum @bp-kelley what's your opinion?

**Comment by greglandrum** [comment]
I completely agree that we should document how largest is calculated, and I'll go ahead and do that.
The current approach compares the number of atoms, then the molecular weight, then the SMILES.

I, however, disagree that it should just be number of heavy atoms or just MW (or number of heavy atoms and then MW): I think that the largest fragment in `[NH4+].[Cl-]` is clearly the `[NH4+]`.

We can argue what should be returned for `[OH2].O=O`. The current code returns `[OH2]`, but there's a case to be made for `O=O`. I don't think it's terribly important as long as it's well documented, but we could change.

**Comment by ptosco** [comment]
@greglandrum Thanks for taking care of the documentation. I agree with you that the current method is sensible and a good default. If you agree, when time allows would add a constructor where a `LargestFragChooserParams` can be passed, in analogy with other `MolStandardize` classes, keeping the legacy constructor with the `preferOrganic` parameter for backwards compatibility. The `LargestFragChooserParams` woud have three booleans with the respective defaults:
* `preferOrganic = false`
* `allAtomsCount = true`
* `heavyAtomsCount = false`

if `allAtomsCount` and `heavyAtomsCount` are set to `false`, only MW would be used, rather than being used only for ties.
if either is set to `true`, that would be used as first criterion.
If both are set to `true`, the `allAtomsCount` would be used as first criterion.

@greglandrum let me know if you agree, then I'll put it on my to-do list.

**Comment by greglandrum** [comment]
@ptosco I agree with those changes. How about I make them at the same time I do the documentation?

**Comment by ptosco** [comment]
@greglandrum I can do both documentation and the change on Saturday 11th Dec. If you have time earlier than that, feel free to go ahead on do it.
