### ISSUE TITLE
version `GLIBCXX_3.4.26' not found when importing rdkit

### ISSUE THREAD

**Issue by jasperhyp** [rdkit/rdkit#4756]
**Describe the bug**
```
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/envs/chemprop/lib/python3.8/site-packages/rdkit/DataStructs/cDataStructs.so)
```

**To Reproduce**
```
import chemprop.data
```
Then I got:
```
File "/opt/conda/envs/chemprop/lib/python3.8/site-packages/chemprop/data/__init__.py", line 1, in <module>
    from .data import (
  File "/opt/conda/envs/chemprop/lib/python3.8/site-packages/chemprop/data/data.py", line 8, in <module>
    from rdkit import Chem
  File "/opt/conda/envs/chemprop/lib/python3.8/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import DataStructs
  File "/opt/conda/envs/chemprop/lib/python3.8/site-packages/rdkit/DataStructs/__init__.py", line 13, in <module>
    from rdkit.DataStructs import cDataStructs
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/envs/chemprop/lib/python3.8/site-packages/rdkit/DataStructs/cDataStructs.so)
```

**Expected behavior**
Imported without any issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/52191793/144272118-2023c165-cdc2-43be-8404-bda2fb40e0ab.png)

**Configuration (please complete the following information):**
 - RDKit version: Both 2020.09.5 and 2021.09.2
 - OS: Debian 10 (on a Google Cloud GPU VM)
 - Python version (if relevant): 3.8.12
 - Are you using conda: Yes (Miniconda).
 - If you are using conda, which channel did you install the rdkit from: conda-forge

**Additional context**
GCC version: 8.3.0
After `strings /lib/x86_64-linux-gpu/libstdc++.so.6 | grep GLIBCXX`, I found that I have no GLIBCXX_3.4.26.  
![image](https://user-images.githubusercontent.com/52191793/144272853-a752d9e2-8266-49f6-a7b8-6bea5fd6a855.png)
I tried to upgrade GCC, downgrade GCC (and upgrade libstdc++6 afterward), downgrade RDKit, but NONE worked.  Would greatly appreciate your help!

**Comment by jasperhyp** [comment]
I did notice this: #4010 , but am not sure if these two issues are related.  If so, shall I use the Debian channel to download 202009.4-1 version of RDKit instead?
![image](https://user-images.githubusercontent.com/52191793/144274417-1b4f3720-a8c1-4448-8153-be0147817eb2.png)

**Comment by ptosco** [comment]
@jasperhyp This is not an RDKit bug.
There is something wrong in how your `conda` environment is set up, as it is picking `libstdc++.so.6` from your OS rather than from your `conda` environment.
You do not need to upgrade your OS nor your compiler - `conda` should be picking its own version of `libstdc++.so.6`, and that's indeed what happens in a healthy `conda` env.
E.g., in my own `pyds_v0.9L` environment:
```
$ conda activate pyds_v0.9L
$ ldd /scratch/toscopa1/.conda/envs/pyds_v0.9L/lib/python3.8/site-packages/rdkit/DataStructs/cDataStructs.so
        linux-vdso.so.1 =>  (0x00007ffdbe8b8000)
        libRDKitDataStructs.so.1 => /scratch/toscopa1/.conda/envs/pyds_v0.9L/lib/python3.8/site-packages/rdkit/DataStructs/../../../../libRDKitDataStructs.so.1 (0x00007fdee3789000)
        libRDKitRDBoost.so.1 => /scratch/toscopa1/.conda/envs/pyds_v0.9L/lib/python3.8/site-packages/rdkit/DataStructs/../../../../libRDKitRDBoost.so.1 (0x00007fdee398e000)
        libRDKitRDGeneral.so.1 => /scratch/toscopa1/.conda/envs/pyds_v0.9L/lib/python3.8/site-packages/rdkit/DataStructs/../../../../libRDKitRDGeneral.so.1 (0x00007fdee396b000)
        libboost_python38.so.1.74.0 => /scratch/toscopa1/.conda/envs/pyds_v0.9L/lib/python3.8/site-packages/rdkit/DataStructs/../../../../libboost_python38.so.1.74.0 (0x00007fdee392b000)
        libstdc++.so.6 => /scratch/toscopa1/.conda/envs/pyds_v0.9L/lib/python3.8/site-packages/rdkit/DataStructs/../../../../libstdc++.so.6 (0x00007fdee35de000)
        libgcc_s.so.1 => /scratch/toscopa1/.conda/envs/pyds_v0.9L/lib/python3.8/site-packages/rdkit/DataStructs/../../../../libgcc_s.so.1 (0x00007fdee3916000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fdee3210000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdee2ff4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fdee2cf2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdee388d000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fdee2aea000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fdee28e6000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007fdee26e3000)
```
As you may see, both `libstdc++.so.6` and `libgcc_s.so.1` are the `conda` versions, not the OS versions.
Check that you have `/opt/conda/envs/chemprop/lib/libstdc++.so.6`. If not, check what's wrong in the way you set up your `conda` env.
Closing as this is not an RDKit-related issue.
Please use the Discussion section if you need more help with this.

**Comment by jasperhyp** [comment]
Thank you!  I worked it around temporarily by setting up a new dynamic link pointing to the correct libstdc++ file in the conda env.  Might be risky because I adjusted this system-wise.

**Comment by ptosco** [comment]
You really should not do that,
The correct `RPATH` should be baked into `cDataStructs.so`, as that's how `conda` works.
```
$ patchelf --print-rpath /opt/conda/envs/chemprop/lib/python3.8/site-packages/rdkit/DataStructs/cDataStructs.so
$ORIGIN/../../../..
```
As a workaround,
```
export LD_LIBRARY_PATH=/opt/conda/envs/chemprop/lib:$LD_LIBRARY_PATH
```
before running your Python script. But again, in a healthy `conda` env you do not need that.
