### ISSUE TITLE
what's the meaning of RD?

### ISSUE THREAD

**Issue by autolife** [rdkit/rdkit#476]
what's the meaning of RD in the RDkit?

**Comment by malteseunderdog** [comment]
Rational Discovery - which I think was a company Greg was involved in which shut down in 2006 (another example of a technology coming too early?).

There is a fantastic history lesson at the beginning of every RDKit which never gets old or boring.  
You can find the slides here:
http://rdkit.org/UGM/2012/Landrum_RDKit_UGM.History%20and%20Status.Final.pptx.pdf

(ps I do not think this is the correct place for this kind of question - issues should be code or documentation problems.  The mailing lists are perhaps a more appropriate medium - https://lists.sourceforge.net/lists/listinfo/rdkit-discuss The people there are really friendly.)

**Comment by autolife** [comment]
Thank you very much.
I will try the mailing list if i have these kind of questions.
