### ISSUE TITLE
GetSimilarityMapFromWeights changes behavior of parameter "colorMap" depending on whether the parameter "draw2d" is provided or not

### ISSUE THREAD

**Issue by FabioUrbina** [rdkit/rdkit#4763]
**Describe the bug**
This is more of an unexpected behavior, but wanted to put it up here anyways and will try to fix it with a pull request. When calling GetSimilarityMapFromWeights, it takes a number of arguments, including colorMap and draw2d. If draw2d is not provided and remains None, you can specify the colormap by the matplotlib id; e.g., you can specify colorMap = "coolwarm" and it will produce the correct colormap for the image. If you provide an argument to draw2d, however, colorMap no longer accepts the matplotlib id and instead only accepts a specified colormap (eg, assiging LinearSegmentedColormap.from_list('RdYlGn', [cmap(0), (1.0, 1.0, 1.0), cmap(1)], N=255) from matplotlib.colors to a variable to pass into colorMap would be necessary when draw2d is provided).

It's a fairly easy to spot bug in the SimilarityMaps.py module.

 Line 155:` if draw2d is not None:`
If draw2d is not None, the following code is run:
```
    if colorMap is not None:
      if cm is not None and isinstance(colorMap, type(cm.Blues)):
        # it's a matplotlib colormap:
        clrs = [tuple(x) for x in colorMap([0, 0.5, 1])]
      else:
        clrs = [colorMap[0], colorMap[1], colorMap[2]]
      ps.setColourMap(clrs)
```
Assuming I assign colorMap = 'coolwarm', This does not recognize "coolwarm" as a colormap, and clrs becomes ['c','o','o'].

If draw2d is not provided (that is, None) the following is run instead:
```
  if colorMap is None:
    if cm is None:
      raise RuntimeError("matplotlib failed to import")
    PiYG_cmap = cm.get_cmap('PiYG', 2)
    colorMap = LinearSegmentedColormap.from_list(
      'PiWG', [PiYG_cmap(0), (1.0, 1.0, 1.0), PiYG_cmap(1)], N=255)

  fig.axes[0].imshow(z, cmap=colorMap, interpolation='bilinear', origin='lower',
                     extent=(0, 1, 0, 1), vmin=-maxScale, vmax=maxScale)
```

essentially, if the colormap exists, it's passed in as an argument in the last line, otherwise a default colorMap is created and passed in. This will allow `colorMap = 'coolwarm'`.

**To Reproduce**
This was my exact code which I was attempting to use, which uses GetSimilarityMapForModel, but the the problems lies in the function GetSimilarityMapFromWeights and is easily traceable to there:

```
    fig, maxWeight = SimilarityMaps.GetSimilarityMapForModel(mol, SimilarityMaps.GetMorganFingerprint,
                                                             lambda x: getProba(x, model.predict_proba),
                                                            # draw2d=d,
                                                             colorMap='coolwarm',
                                                             # size=(1000, 1000),
                                                             step=0.001,
                                                             alpha=0.2)
```
 The code above works fine.

```
d = Draw.MolDraw2DCairo(600, 600)
    fig, maxWeight = SimilarityMaps.GetSimilarityMapForModel(mol, SimilarityMaps.GetMorganFingerprint,
                                                             lambda x: getProba(x, model.predict_proba),
                                                            draw2d=d,
                                                             colorMap='coolwarm',
                                                             # size=(1000, 1000),
                                                             step=0.001,
                                                             alpha=0.2)
```

 The code above does not work anymore now that I've specified the draw2d option. However, if I instead I do the below:

```
d = Draw.MolDraw2DCairo(600, 600)
    new_color_map= LinearSegmentedColormap.from_list(
        'RdYlGn', [cmap(0), (1.0, 1.0, 1.0), cmap(1)], N=255)

    fig, maxWeight = SimilarityMaps.GetSimilarityMapForModel(mol, SimilarityMaps.GetMorganFingerprint,
                                                             lambda x: getProba(x, model.predict_proba),
                                                            draw2d=d,
                                                             colorMap=new_color_map,
                                                             # size=(1000, 1000),
                                                             step=0.001,
                                                             alpha=0.2)
```

 The code now works fine.

**Expected behavior**
I expect that GetSimilarityMapFromWeights (and by extension, GetSimilarityMapForModel) would not modify the expected argument colorMap based on the presence or absence of another argument, draw2d. I expect the colorMap option should allow the matplotlib colormap id (that is, I can specify colorMap = "coolwarm)" in all situations. I can't see a reason why it shouldn't be allowed to be specified in the case of passing in a draw2d object.

**Configuration (please complete the following information):**
 - RDKit version: rdkit-2021.09.2
 - OS: [e.g. Ubuntu 20.04] Windows 10 and MacOS 
 - Python version (if relevant): 3.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
Again, this seems minor as I've just modified my drawing wrapper functions to

**Comment by greglandrum** [comment]
@FabioUrbina: thanks for the complete and well-described problem report.
Would you like to try a PR to fix it, or should I go ahead and do it?

**Comment by FabioUrbina** [comment]
@greglandrum I'll go ahead and try a PR today or tomorrow!
