### ISSUE TITLE
Highlight bond width is different for different PNG image sizes

### ISSUE THREAD

**Issue by rachelnwalker** [rdkit/rdkit#4764]
**Describe the bug**
When using `MolDraw2DFromQPainter` to generate a PNG image of a molecule with a highlighted substructure, between highlights will differ in width for different canvas sizes. For example, here is the 400x400 image:

![400_by_400](https://user-images.githubusercontent.com/39069546/144666960-5cab09b7-cdf7-4ac4-ac4e-7244f06d7d5a.png)

200x200:
![image](https://user-images.githubusercontent.com/39069546/144666984-e823fe47-1394-4aae-9c6f-8bc4ddd6f690.png)

And 1200x900:
![image](https://user-images.githubusercontent.com/39069546/144667009-4ccc65ee-5bfe-4273-8bf6-9dfb2374af9a.png)

**To Reproduce**
This is the python code I used to create the images above. It is using Schrodinger's installation of Qt.
```
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import MolDraw2DFromQPainter

from schrodinger.Qt.QtCore import QBuffer
from schrodinger.Qt.QtCore import QByteArray
from schrodinger.Qt.QtCore import QIODevice
from schrodinger.Qt.QtGui import QImage
from schrodinger.Qt.QtGui import QPainter


def draw_png_image(mol, height, width):

    qimg = QImage(width, height, QImage.Format_ARGB32)
    with QPainter(qimg) as cpp_qp:
        drawer = MolDraw2DFromQPainter(cpp_qp, width, height)
        drawer.DrawMolecule(mol, highlightAtoms=(0,1,2,3,4,5))

    byte_array = QByteArray()
    buffer = QBuffer(byte_array)
    buffer.open(QIODevice.WriteOnly)
    qimg.save(f"{width}_by_{height}.png")

mol = Chem.MolFromSmiles("C1CCC(CC1)C1=CC=CC=C1")
draw_png_image(mol, 400, 400)
draw_png_image(mol, 900, 1200)
draw_png_image(mol, 200, 200)
```

**Expected behavior**
The highlight bond thickness should scale with the rest of the image and the atom highlights.

**Configuration (please complete the following information):**
 - RDKit version: Release_2021_09_1b1
 - OS: MacOs big sur 11

**Comment by greglandrum** [comment]
@rachelnwalker : I can reproduce this and can start to look into it.
Here's what the cairo-based PNG generation does for:
```
    {
      MolDraw2DCairo drawer(200, 150);
      drawer.drawMolecule(*mol, "highlight", &highlights);
      drawer.finishDrawing();
      drawer.writeDrawingText("testGithub4764.sz1.png");
    }
    {
      MolDraw2DCairo drawer(400, 350);
      drawer.drawMolecule(*mol, "highlight", &highlights);
      drawer.finishDrawing();
      drawer.writeDrawingText("testGithub4764.sz2.png");
    }
    {
      MolDraw2DCairo drawer(800, 700);
      drawer.drawMolecule(*mol, "highlight", &highlights);
      drawer.finishDrawing();
      drawer.writeDrawingText("testGithub4764.sz3.png");
    }
```
![testGithub4764 sz1](https://user-images.githubusercontent.com/540511/146415184-eb6860ec-4abd-404a-b93b-e6e38a8842b0.png)
![testGithub4764 sz2](https://user-images.githubusercontent.com/540511/146415217-4c809014-3cae-4875-bee4-f0d9b65be5e3.png)
![testGithub4764 sz3](https://user-images.githubusercontent.com/540511/146415235-b329437d-7495-45ff-8636-6037bc84ad3e.png)

I will try to reproduce this behavior
