### ISSUE TITLE
EmbedMolecule hangs forever

### ISSUE THREAD

**Issue by xtsm** [rdkit/rdkit#4765]
**Describe the bug**
The following molecule causes embedding to hang forever (more than 5 minutes on my machine), also huge delay when trying to stop with ctrl-c:
`CCSCc1ccc2c(c1)c1c3c(c4c5cc(CSCC)ccc5n5c4c1n2[C@@H]1C[C@H](C(=O)OOC)[C@]5(C)O1)CNC3=O`

**To Reproduce**
```
mol = Chem.AddHs(Chem.MolFromSmiles('CCSCc1ccc2c(c1)c1c3c(c4c5cc(CSCC)ccc5n5c4c1n2[C@@H]1C[C@H](C(=O)OOC)[C@]5(C)O1)CNC3=O'))
Chem.EmbedMolecule(mol)
```

**Expected behavior**
Success, failure or exception in reasonable amount of time

**Configuration (please complete the following information):**
 - RDKit version: rdkit-pypi 2021.9.2.1
 - OS: Ubuntu 20.04.2 LTS
 - Python version (if relevant): 3.8.10
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? pip

**Comment by greglandrum** [comment]
@xtsm : I can't reproduce this, but the molecule is probably incorrect anyway.

On my machine it takes quite a while, and the conformer generation eventually fails, but it doesn't run for multiple minutes:
```
In [3]: mol = Chem.AddHs(Chem.MolFromSmiles('CCSCc1ccc2c(c1)c1c3c(c4c5cc(CSCC)ccc5n5c4c1n2[C@@H]1C[C@H](C(=O)OOC)[C@]5(C)O1)CNC3=O'))
In [5]: %time rdDistGeom.EmbedMolecule(mol)
CPU times: user 50.7 s, sys: 11.2 ms, total: 50.7 s
Wall time: 50.8 s
Out[5]: -1
```
What seems to be making this fail (and take so long) is generating conformers which match the chirality which you've specified; if I turn the use of chirality in the conformer generation process off then things run quite quickly:
```
In [6]: ps = rdDistGeom.ETKDGv3()

In [7]: ps.enforceChirality = False

In [8]: %time rdDistGeom.EmbedMolecule(mol,ps)
CPU times: user 167 ms, sys: 24 µs, total: 167 ms
Wall time: 166 ms
Out[8]: 0
```
When this situation occurs with a molecule which only has a few chiral centers it's often a sign that there's a problem with the molecule itself and, sure enough, looking at the molecule the stereochemistry is probably wrong. Here's your molecule, with atom numbers indicated:
![image](https://user-images.githubusercontent.com/540511/144785494-e7ccb217-8a72-4d6f-972b-e04ff8e2cd88.png)
I believe the relative chiralities of atoms 28 and 36 are incorrect; that the molecule cannot exist as specified.
Sure enough, if I flip the chirality of one of those bridgehead atoms, I end up getting a conformer quite quickly:
```
In [16]: mol2 = Chem.AddHs(Chem.MolFromSmiles('CCSCc1ccc2c(c1)c1c3c(c4c5cc(CSCC)ccc5n5c4c1n2[C@@H]1C[C@H](C(=O)OOC)[C@@]5(C)O1)CNC3=O'))

In [17]: %time rdDistGeom.EmbedMolecule(mol2)
CPU times: user 185 ms, sys: 2 µs, total: 185 ms
Wall time: 184 ms
Out[17]: 0
```
So please check your input structure.

**Comment by wehs7661** [comment]
Hi @greglandrum, I had the same issue as @xtsm. In my case, I tried the following code:
```
import time
from rdkit.Chem import AllChem
smiles = "C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](C(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](C)C(=O)N[C@H](C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](CC(C)C)C(=O)N(C)[C@@H](C(C)C)C(=O)N1C"

mol = AllChem.MolFromSmiles(smiles)
mol = AllChem.AddHs(mol)
Draw.MolToImage(mol)
options = AllChem.ETKDGv3()
options.clearConfs = False
t0 = time.time()
conf_id = AllChem.EmbedMolecule(mol, options)
print(conf_id)
print(f"\nTime elapsed for EmbedMolecule: {time.time() - t0:.2f} seconds")
```
And it turned out `conf_id` was -1 and the whole process took 30 minutes. I wonder if there is a faster way to fail the process in RDKit.
