### ISSUE TITLE
functools.partial does not work with rdkit.Chem.rdmolfiles.SmilesMolSupplier()

### ISSUE THREAD

**Issue by rczerminski-valo** [rdkit/rdkit#4768]
**Describe the bug**
I am trying to create new reader for smiles file with TAB instead of default space delimiter using functools.partial function

**To Reproduce**
```
>>> import functools
>>> rdrt = functools.partial(Chem.rdmolfiles.SmilesMolSupplier(delimiter='\t'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    SmilesMolSupplier.__init__(SmilesMolSupplier)
did not match C++ signature:
    __init__(_object*)
    __init__(_object*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > data, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > delimiter=' ', int smilesColumn=0, int nameColumn=1, bool titleLine=True, bool sanitize=True)
>>> 
```
**Expected behavior**
Should return new reader for TAB (instead of default SPACE) delimited smiles file.

**Configuration (please complete the following information):**
 - RDKit version: >>> rdkit.rdBase.rdkitVersion '2021.09.2'
 - OS: macOS Big Sur 11.2.3 (20D91)
 - Python version (if relevant): >>> sys.version 3.9.5
 - Are you using conda? yes, actually I used mamba
 - If you are using conda, which channel did you install the rdkit from? default
 - If you are not using conda: how did you install the RDKit? ```mamba install rdkit```

**Comment by bp-kelley** [comment]
You are using functools.partial incorrectly, functools.partial adds arguments to a function so using the form:

```
rdrt = functools.partial(Chem.rdmolfiles.SmilesMolSupplier(delimiter='\t'))
```

is calling the full SmilesMolSupplier function with not enough arguments, what you want is:

```
rdrt = functools.partial(Chem.SmilesMolSupplier, delimiter="\t")
```

which will magically add the delimiter='\t' to rdrt

**Comment by rczerminski-valo** [comment]
Yes, indeed - my mistake!
