### ISSUE TITLE
installation without conda

### ISSUE THREAD

**Issue by samcphee** [rdkit/rdkit#4776]
I am trying to install on windows 10, Python 3.10.0 using  pip install rdkit-pypi  and get the message:

ERROR: Could not find a version that satisfies the requirement rdkit-pypi (from versions: none)
ERROR: No matching distribution found for rdkit-pypi

prerequisites are installed.

I do not use conda.

**Comment by bp-kelley** [comment]
There is no windows pypi version, and even the non windows pypi version is not directly supported by us at this time, it is missing a few pieces of data.

**Comment by greglandrum** [comment]
This is not an rdkit bug report
