### ISSUE TITLE
`ReplaceSubstructs` alters the stereo at the connexion point

### ISSUE THREAD

**Issue by stephanielabouille** [rdkit/rdkit#4781]
**Describe the bug**
`ReplaceSubstructs` alters the stereo at the connexion point, see example below. Not sure whether this is a bug or the expected behaviour but I don't understand why it happens.

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem import AllChem


mol = Chem.MolFromSmiles('CCNC(=O)[C@@H]1C[C@@H]([NH3+])CN1C(=O)Cc1cc(C)ccc1C')
reactant = Chem.MolFromSmarts('[N+;!H0]')
product = Chem.MolFromSmiles('N')
rms = AllChem.ReplaceSubstructs(mol, reactant, product)
new_mol = rms[0]
```

**Expected behavior**
I would expect a simple replacement of `[NH3+]` by `N` neutral, without any change at the neighbouring C.

**Screenshots**
![image](https://user-images.githubusercontent.com/84319847/145367762-1f5379b8-5be1-4c61-bb48-b6618049d416.png)

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.2 and 2021.03.1
 - OS: MacOS
 - Python version (if relevant): 3.7.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
Hi @stephanielabouille, I agree that this is not what the RDKit should be doing, but it is expected. `ReplaceSubstructs()` doesn't pay attention to stereochemistry. Fixing this isn't a high priority since there are workarounds:

If you're interested in replacing a single atom you can use `mol.ReplaceAtom()` and preserve stereo:
```
In [3]: matches = mol.GetSubstructMatches(reactant)

In [4]: rwm = Chem.RWMol(mol)

In [5]: for match in matches:
   ...:     rwm.ReplaceAtom(match[0],product.GetAtomWithIdx(0))
   ...: 

In [6]: Chem.MolToSmiles(mol)
Out[6]: 'CCNC(=O)[C@@H]1C[C@@H]([NH3+])CN1C(=O)Cc1cc(C)ccc1C'

In [7]: Chem.MolToSmiles(rwm)
Out[7]: 'CCNC(=O)[C@@H]1C[C@@H](N)CN1C(=O)Cc1cc(C)ccc1C'
```

For more complex replacements you can use chemical reactions... those will also preserve stereo.

**Comment by stephanielabouille** [comment]
Hi @greglandrum, got it, I'll give it a try, thank you very much.
