### ISSUE TITLE
AttributeError: module 'rdkit.Chem' has no attribute 'QED'

### ISSUE THREAD

**Issue by rczerminski-valo** [rdkit/rdkit#4784]
I am trying to use [QED module](https://rdkit.org/docs/source/rdkit.Chem.QED.html) but apparently it is missing:
```
>>> import rdkit
>>> rdkit.Chem.QED
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'rdkit.Chem' has no attribute 'QED'
>>>
``` 

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.2
 - OS: macOS 11.2.3
 - Python version (if relevant): 3.9.5
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? default
 - If you are not using conda: how did you install the RDKit?

**Comment by greglandrum** [comment]
That's not the way Python imports work. Try doing `from rdkit.Chem import QED`
