### ISSUE TITLE
Strange boost header issue

### ISSUE THREAD

**Issue by poganyp** [rdkit/rdkit#4795]
I compiled the RDKit (2021.09.2) from source using MorganFingerprints using:

#include <GraphMol/Fingerprints/MorganFingerprints.h>

If I do not include the original headers from Boost, the compilation crashes with error message:
In file included from ../rdkit-Release_2021_09_2/Code/DataStructs/SparseIntVect.h:20:0,
                         from ../rdkit-Release_2021_09_2/Code/GraphMol/Fingerprints/MorganFingerprints.h:46,

rdkit-Release_2021_09_2/Code/RDGeneral/StreamOps.h:22:26: fatal error: boost/predef.h: No such file or directory

I can bypass this issue with including the boost, but I thought that RDKit should deal with the redirections. This problem is ongoing since the 2020 versions.

In 2018.03.4 line 21-22 in StreamOps.h:
#include <boost/cstdint.hpp>
#include <boost/detail/endian.hpp>

Whereas in new releases 2021.09.4 the same lines are:
#include <boost/cstdint.hpp>
#include <boost/predef.h>

Can you please check this, if this is some bug and could be fixed.

**Comment by bp-kelley** [comment]
RDKit absolutely needs boost to be properly installed to be compiled.
Also, boost/predef.h has been included in boost for a very long time, if it
is missing from your boost headers, I expect something is wrong there.
Finally, there seems to be a bit of information missing from your issue.


What OS are you compiling on?  What are you using to compile?   What is
your version of boost?

We will need more information to fully understand your issue.

**Comment by poganyp** [comment]
Boost is properly installed and it does not really matter which boost version I tried (1.72 and 1.66 was tried as well). Something is with the linking. The OS is CentOS 7. We have tried to ways for compilation and both give the same error, when we do not include the boost headers in the compilation of our code (after RDKit is compiled). Although adding boost headers to the compilation with g++ -I... solves the issue, since the boost is a dependency of RDKit, I am not sure that we should add this. Also boost/cstdint.hpp works without adding explicitly the boost, whereas boost/predef.h does not (both are present and they are present at the same location).
The list of options tried (without python support):
gcc 7.5.0
boost 1.72.0
cmake 3.21.1
eigen 3.3.5
openmpi 2.1.5

cmake -DBoost_NO_SYSTEM_PATH=TRUE -DBOOST_ROOT=/home/install/boost/v1.72.0 -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DRDK_BUILD_CAIRO_SUPPORT=ON -DRDK_INSTALL_DEV_COMPONENT=ON .

And (with python support):
gcc 4.8.5
boost 1.66.0
cmake 3.11.4
python 3.7 (with numpy)

cmake -DPy_ENABLE_SHARED=1 -DRDK_INSTALL_INTREE=ON -DRDK_INSTALL_STATIC_LIBS=OFF -DRDK_BUILD_CPP_TESTS=ON -DRDK_BUILD_CAIRO_SUPPORT=ON -DRDK_BUILD_INCHI_SUPPORT=ON -DRDK_USE_BOOST_SERIALIZATION=OFF -DBOOST_ROOT=/home/install/boost/v1.66.0 -DBOOST_INCLUDEDIR=/home/install/boost/v1.66.0/include/boost -DBOOST_LIBRARIES=/home/install/boost/v1.66.0/lib .

I have forgotten to add, that the header about which the compiler complains is in the boost:
/home/install/boost/v1.66.0/include/boost/predef.h

As mentioned, I can do the compilation of my code with adding -I/home/install/boost/v1.66.0/include/boost to the g++, but I do not think that this is how it should work.

**Comment by greglandrum** [comment]
It's still not clear where the compilation problems are happening.
Please share the exact command you issued and the exact error message which you saw.

**Comment by poganyp** [comment]
This crashed with a missing boost/predef.h:
g++ -c -fPIC -Wall -std=c++11 -Wc++0x-compat -I$RDBASE/Code my_code.cpp
If I include Boost headers, it works:
g++ -c -fPIC -Wall -std=c++11 -Wc++0x-compat -I$RDBASE/Code -I$BOOST/include my_code.cpp
What I wanted to tell is with the previous RDKit versions (2018) we did not need to include Boost headers for compiling our code.
In the meantime I have realized that if we use conda, then we will have a much clearer directory structure and less problem with the includes:
conda install --channel=conda-forge boost-cpp boost rdkit rdkit-dev
Were you thinking adding the headers into the rdkit conda channel (both for rdkit and boost)? I cannot see them yet, but maybe I did not look hard enough.

**Comment by greglandrum** [comment]
Hi @poganyp,
Because the RDKit headers include boost headers, you certainly need to tell both the compiler and the linker where to find boost when you build your own code which uses the RDKit.

If you've installed the RDKit using conda, you can use those builds in your own C++ programs. Here's a sample command line showing how I compiled/linked a simple program using a conda install:
```
g++ -I $CONDA_PREFIX/include -I$CONDA_PREFIX/include/rdkit -L $CONDA_PREFIX/lib  -O2 -g -o memory_usage.exe memory_usage.cpp -lRDKitGraphMol -lRDKitFileParsers -lRDKitFingerprints -lRDKitSmilesParse -lRDKitSubstructMatch -lRDKitDataStructs -lRDKitRDGeneral -lboost_iostreams
```


For what it's worth, if possible, this stuff is all a bunch easier if you use cmake to build your code: https://greglandrum.github.io/rdkit-blog/tutorial/technical/2021/07/24/setting-up-a-cxx-dev-env.html

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
