### ISSUE TITLE
ComputeProperties() fails for products from RunReactants()

### ISSUE THREAD

**Issue by rczerminski-valo** [rdkit/rdkit#4803]
**Describe the bug**

`ComputeProperties()` fails for products from `RunReactants()`
If the product is converted to SMILES and back to mol object [`MolFromSmiles(MolToSmiles(prd))`] then
`ComputeProperties()` works. Apparently molecule produced by `RunReactants()` is not "finished" in some sense.

Is there a better way to `ComputeProperties()` for reaction products than this from-to smiles conversion?

**To Reproduce**
```
from rdkit.Chem import MolFromSmiles, MolToSmiles
from rdkit.Chem import rdChemReactions, rdMolDescriptors
rxn = rdChemReactions.ReactionFromSmarts("[C:1][C:2]C>>[C:1][C:2]")
mol = MolFromSmiles("CCC")
prd = rxn.RunReactants((mol,))[0][0]
names = ["CrippenClogP", "amw", "NumRotatableBonds"]
pp = rdMolDescriptors.Properties(names)
try:
    pps = list(pp.ComputeProperties(prd))
    """
    This fails with:
    ****
    Pre-condition Violation
    getNumImplicitHs() called without preceding call to calcImplicitValence()
    Violation occurred on line 185 in file /Users/runner/miniforge3/conda-bld/rdkit_1635252265104/work/Code/GraphMol/Atom.cpp
    Failed Expression: d_implicitValence > -1
    ****
    """
except:
    print("pp.ComputeProperties(prd) FAILED")
    pps = list(pp.ComputeProperties(MolFromSmiles(MolToSmiles(prd))))
    print("pp.ComputeProperties(MolFromSmiles(MolToSmiles(prd))) WORKS")

print(f"{names} = {pps} for prd= {MolToSmiles(prd)}")
"""
['CrippenClogP', 'amw', 'NumRotatableBonds'] = [1.0262, 30.07, 0.0] for prd= CC
"""
```

**Configuration (please complete the following information):**
 - RDKit version: rdkit.rdBase.rdkitVersion = '2021.09.2
 - OS: macOS Big Sur 11.2.3 (20D91)
 - Python version (if relevant): 3.9.5
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit? N/A

**Comment by bp-kelley** [comment]
Products from reactions are not sanitized by default.

You will need to run 

Chem.SanitizeMol

On them and discard the ones that fail.

----
Brian Kelley

**Comment by greglandrum** [comment]
This is covered in the documentation: https://rdkit.org/docs/GettingStartedInPython.html#chemical-reactions

**Comment by rczerminski-valo** [comment]
@greglandrum Thanks Greg! Works like a charm.
BTW: I guess, there must be a reason why rxn products are not sanitized and deduped  by default, but I do not quite understand why - is this somewhere covered in docs? I - and probably most users - would find it rather useful.

**Comment by greglandrum** [comment]
> @greglandrum Thanks Greg! Works like a charm. BTW: I guess, there must be a reason why rxn products are not sanitized and deduped by default, but I do not quite understand why - is this somewhere covered in docs? I - and probably most users - would find it rather useful.

That's a reasonable question. The current default behavior is done in order to maximize performance: sanitization and generating SMILES takes time and there are times when it's not necessary.

I'm contemplating some changes for a future RDKit version to make the default behavior of the RDKit a bit more friendly for non-expert users, but that will take a while.

**Comment by rczerminski-valo** [comment]
If `rxn.RunReactants()` (and other relevant functions) would have some parameters to control this functionality it would be great. For example user who wants to maximize performance and does not need sanitized, unique molecules can run `RunReactants(sanitize=False, dedup=False)` and other user who wants them sanitized and unique `RunReactants(sanitize=True, dedup=True)` and skip the extra post-processing steps...

**Comment by bp-kelley** [comment]
@rczerminski-valo @greglandrum this would be pretty easy to add to the EnumerateLibrary codebase, here is a suggestion:

```
opts = rdChemReactions.EnumerationParams()
opts.uniqueProducts = True
opts.sanitizedProducts = True
en = rdChemReactions.EnumerateLibrary(rxn, bbs, params=opts)
for result in en:
    for products in result:
        for mol in products:
            ...
```

**Comment by rczerminski-valo** [comment]
@bp-kelley I will try this - thanks!

**Comment by bp-kelley** [comment]
Note that this doesn’t exist yet, a portion of it does.

**Comment by rczerminski-valo** [comment]
The below seems to work for me:
```
rxn = rdChemReactions.ReactionFromSmarts('[*:1][C:2](=[O:3])O.[N:4][*:5]>>[*:1][C:2](=[O:3])[N:4][*:5]')
bbs = ([Chem.MolFromSmiles('CCC(=O)O')], [Chem.MolFromSmiles('NCC')])
opts = rdChemReactions.EnumerationParams()
opts.uniqueProducts = True
opts.sanitizedProducts = True
en = rdChemReactions.EnumerateLibrary(rxn, bbs, params=opts)
mols = []
for result in en:
    for products in result:
        for mol in products:
              mols.append(mol)
[Chem.MolToSmiles(m) for m in mols]
>>> ['CCNC(=O)CC']
```

BTW: does something similar exist for `rxn.RunReactants()` ? With `rxn.RunReactants()` I can capture reactants on which reaction fails, which might be useful for debugging reaction and/or list of reactants. Alternatively, maybe there is a way to capture failing reactants from `EnumerateLibrary()`?

**Comment by bp-kelley** [comment]
The variable sanitizedProducts doesn’t exist yet in EnumerateLibrary.  sanitizedPartialProducts does, but it does something different in practice.
