### ISSUE TITLE
PandasTools AttributeError

### ISSUE THREAD

**Issue by schallerdavid** [rdkit/rdkit#4808]
**Describe the bug**
We use RDKit in our [TeachOpenCADD](https://github.com/volkamerlab/teachopencadd) package and also run tests via github actions to detect failures. With the new release of RDKit ([2021.09.3](https://github.com/rdkit/rdkit/releases/tag/Release_2021_09_3)) the CI [reports](https://github.com/volkamerlab/teachopencadd/runs/4556003024?check_suite_focus=true) an `AttributeError` originating from the PandasTools in RDKit:

`AttributeError: module 'pandas.io.formats' has no attribute 'html'`

Pinning RDKit to the previous release leads to successful completion of the respective tests ([#206](https://github.com/volkamerlab/teachopencadd/pull/206)). Please overlook the CI failure with MacOS and Python 3.7 for now. It is not related to anything on your end and we will address this separately.

I may have found the change in the most recent release of RDKit that causes the `AttributeError`. It is about a deleted line of a specific pandas import ([L198](https://github.com/rdkit/rdkit/pull/4744/files#diff-4d3e0e17d686a9de85fb42b78a37f8fe69e95258f4e6be45899873fa292a2090L198)).

When running the following lines in a local environment having only pandas installed I receive the same error:

```
import pandas as pd
pd.io.formats.html.HTMLFormatter._write_cell
```

When adding the additional import line that got deleted in the most recent release, there is no error reported:

```
import pandas as pd
import pandas.io.formats.html
pd.io.formats.html.HTMLFormatter._write_cell
```

**To Reproduce**
- check CI runs with RDKit [2021.09.3](https://github.com/volkamerlab/teachopencadd/runs/4556003024?check_suite_focus=true) and RDKit [2021.09.2](https://github.com/volkamerlab/teachopencadd/runs/4560920364?check_suite_focus=true)
- or install TeachOpenCADD locally and run the tests

**Expected behavior**
- all tests pass (except for the Errors with MacOS and Python 3.7 mentioned already above)

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.3
 - OS: Ubuntu, Windows, MacOS
 - Are you using conda? Yes, installation via mamba ([test_env.yaml](https://github.com/volkamerlab/teachopencadd/blob/master/devtools/test_env.yml))
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by schallerdavid** [comment]
Edit: We are currently rerunning the CI, so the mentioned CI failure not related to RDKit may show up on other operating systems and Python versions.

**Comment by ptosco** [comment]
@schallerdavid Apologies, that was my mistake. I did test the changes on several `pandas` versions, but now I realize that `patchPandasrepr` is only used by the  `RenderImagesInAllDataFrames` function, while I only tested `ChangeMoleculeRendering`, which is why I did not notice the problem.
Until the problem is fixed, if you wish to use the latest RDKit release, you could monkey patch `PandasTools` after importing it as follows:
```
from rdkit.Chem import PandasTools

_orig_patchPandasrepr = PandasTools.patchPandasrepr
def _new_patchPandasrepr(self, **kwargs):
    import pandas.io.formats.html
    return _orig_patchPandasrepr(self, **kwargs)
PandasTools.patchPandasrepr = _new_patchPandasrepr
```
Then your tests should pass.
Again, sorry for the inconvenience.

**Comment by schallerdavid** [comment]
@ptosco Thanks for taking a look at this and no need for apologies! We are good with pinning RDKit to the prior version for now.

**Comment by edrisranjbar** [comment]
is this issue fixed?

**Comment by ptosco** [comment]
Yes, it is. The whole `PandasTools` module has been refactored an tested recently against a wide range of versions up to the current one.
