### ISSUE TITLE
Support using the python logger

### ISSUE THREAD

**Issue by xavierholt** [rdkit/rdkit#4840]
RDKit can be pretty noisy when working with potentially-invalid molecules.  I'd like to be able to conditionally suppress these error messages from a Python script.  Specifically, I'd like to capture all `stderr` output, and then re-print it only if an unexpected error occurs.  My use case looks something like this:

```py
def process(possibly_invalid_molecule):
    capture_stderr()
    try:
        # do stuff here
    except KekulizeException:
        # expected; ignore it
        pass
    except Exception:
        # unexpected; what happened?
        print(captured_stderr)
    finally:
        release_stderr()
```

There's currently no way to do this (at least as far as I can find).  `BlockLogs` prevents all log messages from showing up anywhere.  `WrapLogs` tees the log messages; I can capture the copy sent to Python, but the other copy still ends up on the terminal.

Ideally, I'd like the RDKit logs to use the Python streams automatically whenever it's started from Python (but this might cause problems for people running combined Python/C++ apps).  Alternatively, I'd like access to an `InitLogsPy` or `RedirectLogs` function that redirects all log messages to Python, but without the teeing or prefix you get when you use `WrapLogs`.

I'm happy to put together a PR for this, but I'm not an RDKit expert.  I'd appreciate any feedback!

**Comment by greglandrum** [comment]
I think this is a great idea, but I have no idea whether or not it’s possible to access the Python logging system as a file-like object from C/C++. If that is possible then this should be doable.

**Comment by xavierholt** [comment]
If all we want to do is print C++ log messages through Python's `sys.stderr` stream, I think it'd be pretty easy.  There's already code that can do this - the `PySysErrWrite` class ([here](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Wrap/rdchem.cpp#L52-L86)) that `WrapLogs` uses.  It's just a matter of writing a different init function that creates loggers using these instead of `sys::cerr`.

Hooking into Python's `logging` module seems a bit trickier, but I found a [nice-looking example](https://gist.github.com/hensing/0db3f8e3a99590006368), which should be easy enough to replicate as long as we have access to the Python C functions.  (Does `boost::python` provide these?  I don't see `Python.h` included anywhere in the existing code.)  We could write a class very similar to `PySysErrWrite` that calls the appropriate Python logging function instead of `PySys_WriteStderr` when it sees a newline.

I'm thinking using the Python `logging` module is The Right Way, even if it's a bit more work...

**Comment by greglandrum** [comment]
The problem is that most of the logging is being done in C++ code which has no knowledge whatsoever of Python (remember: the Python wrappers are a thin boost::python layer atop a much larger C++ code base).
What we'd need is a class which is part of the python wrappers which wraps whatever the best way to call the python logging API is in something which acts like a C++ ostream. That can then be handed to the RDKit's logging code.
