### ISSUE TITLE
MMFF fails for O2 molecule

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#4841]
This seems to be the only second row diatomic that fails.
```
>>> m = Chem.MolFromSmiles('O=O')
>>> AllChem.EmbedMolecule(m)
>>> AllChem.MMFFOptimizeMolecule(m)
>> -1
```
Looking more closely I see that `MMFFGetMoleculeProperties` returns `None` for this molecule.  Not sure if this is a bug in the RDKit implementation or if O=O was never added to the MMFF

**Comment by ptosco** [comment]
@jasondbiggs the oxygen in O<sub>2</sub> is not really covered by any [MMFF94 atom type](https://github.com/openbabel/openbabel/blob/08e23f39b0cc39b4eebd937a5a2ffc1a7bac3e1b/data/mmffdef.par).

**Comment by jasondbiggs** [comment]
@ptosco thank you that makes sense.  I wouldn't expect to find a 'O=O' bond inside a molecule so it makes sense it wouldn't be parameterized.
