### ISSUE TITLE
Add support for quadruple bonds in SMILES

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#4842]
The [OpenSMILES](http://opensmiles.org/opensmiles.html) specification allows `$` to stand for quadruple bonds, with `"[Rh-](Cl)(Cl)(Cl)(Cl)$[Rh-](Cl)(Cl)(Cl)Cl"` as an example.  From testing locally it seems that Open Babel and the CDK parse this as intended and I believe OpenEye does as well.

Is there a reason not to support this in RDKit?

**Comment by greglandrum** [comment]
This change is already in on the non-tetrahedral stereo branch, but given that it's going to take a while to finish that and get it ready for merging, it probably makes sense to just merge that as a discrete change onto master.

**Comment by jasondbiggs** [comment]
Thanks @greglandrum for the speedy response!
