### ISSUE TITLE
Using the CoordGen library causes a segmentation fault for a particular SMILES

### ISSUE THREAD

**Issue by lucasmorin222** [rdkit/rdkit#4845]
**Describe the bug**
Computing the coordinates of the molecule which SMILES is 'C1C=CC=C2C1=CSC=C3C(=O)OOOC(=O)C(=CC(=O)N3)OC2=O' using CoordGen causes a segmentation fault.
Using RDKit instead, the coordinates are correctly computed.

**To Reproduce**
import rdkit
from rdkit import Chem
from rdkit.Chem import rdDepictor

Chem.rdDepictor.SetPreferCoordGen(True)
molecule = Chem.MolFromSmiles('C1C=CC=C2C1=CSC=C3C(=O)OOOC(=O)C(=CC(=O)N3)OC2=O')
rdDepictor.Compute2DCoords(molecule)

**Expected behavior**
The code above causes a segmentation fault.

**Configuration (please complete the following information):**
 - RDKit version: Release 2021 09 2
 - OS: Red Hat Enterprise Linux release 8.4 
 - Python version (if relevant): 3.8
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? Source

**Additional context**
If it is not fixable, would it be possible to detect that a molecule would cause a segmentation fault if its coordinates were computed ?

**Comment by greglandrum** [comment]
Confirmed: I can reproduce this.

**Comment by greglandrum** [comment]
I've debugged into this and verified that the seg fault is from coordgen itself. I'm going to transfer this to that bug tracker.

**Comment by jasondbiggs** [comment]
@greglandrum I've run into a similar problem with the following SMILES string and wonder if it is the same issue or if I should report it separately.  
```
>>> from rdkit import Chem
>>> params = Chem.rdmolfiles.SmilesParserParams()
>>> params.removeHs = False
>>> mol = Chem.MolFromSmiles('[H]C([H])=C1C#C/C2=C(/C#C/C3=C(\\C#CC2=C([H])[H])C(=C([H])[H])C#CCC(=C=O)C#C3)C(=C([H])[H])C#CC(=O)C1=C([H])[H]', params)
>>> Chem.rdCoordGen.AddCoords(mol)
Segmentation fault: 11

```
