### ISSUE TITLE
AttributeError: module 'pandas.io.formats' has no attribute 'html'

### ISSUE THREAD

**Issue by JosephPParker** [rdkit/rdkit#4864]
**Bug description:**
Using a conda environment (named 'CADD2', aliased 'CADD') in Jupyter Lab (on Safari), I am trying to make a dataframe with pd.DataFrame and then display; the result is an AttributeError with 'pandas.io.formats' having no 'html' attribute.
First example uses SMILES and PandasTools.AddMoleculeColumnToFrame() but, even without that column added, displaying the DataFrame produces an error.  I later tried with a simpler example dataframe containing some strings, with the same result.  I am able to display individual cells with iloc (including the molecule column in the first example) but not the dataframe as a whole.
The error message is visible in the screenshot and, hopefully, in the ipynb.txt below.

rdkit/Chem/PandasTools.py appears responsible, and I see issue #3701 had a similar problem related to it in the comments and on GitHub, although the attribute is different.  I went through the Python scripts but was unable to ascertain how to fix my issue myself.

I was hoping to simply display the dataframes (including, if possible, the molecule column) when calling that dataframe.

**Reproduction, see versions below (included all imported modules in case some are known to interfere):**
from pathlib import Path
import math
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import Draw, Descriptors, PandasTools
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import matplotlib.patches as mpatches

names = ["Joseph","Thomas","Matthew"]
jobs = ["scientist?","doctor","editor"]
test = pd.DataFrame({"name":names,"job":jobs})
test

**Versions**
Pandas version: 1.3.5
RDKit version: 2021.09.3
OS: MacOS Mojave 10.14.6
Python: 3.9.9
Using MiniConda 3, downloaded rdkit from conda-forge.

**Additional context**
Using some code from the CADD teaching package (https://github.com/volkamerlab/teachopencadd/tree/master/teachopencadd), specifically Talktorial 02.
Although I am learning, I am extremely inexperienced at all aspects of computer science and science in general.  

<img width="1440" alt="Screenshot 2022-01-06 at 20 40 28" src="https://user-images.githubusercontent.com/89361669/148449830-71946ef9-2ba4-4d5b-9680-8af36fcdcdf2.png">
[AttributeError_example.ipynb.txt](https://github.com/rdkit/rdkit/files/7824632/AttributeError_example.ipynb.txt)

**Comment by ptosco** [comment]
@JosephPParker the `AttributeError` bug has already been reported and fixed:
https://github.com/rdkit/rdkit/pull/4822
