### ISSUE TITLE
Support Swig 4.0

### ISSUE THREAD

**Issue by tdudgeon** [rdkit/rdkit#4917]
Recent Debian distros (e.g. bullseye) come with Swig 4.0.
Building RDKit requires Swig 3.0 and does not build with 4.0.
Can RDKit be updated to to support 4.0.

**Comment by greglandrum** [comment]
I'm sure this is possible; it's just a matter of someone putting in the time to figure out the differences and make things work.
Fortunately, in the meantime, it's always possible to install and use the older versions of SWIG

**Comment by tdudgeon** [comment]
@greglandrum Seems that building with swig 4.0 works OK now (on master)?

**Comment by greglandrum** [comment]
@tdudgeon yes, this was resolved on master in #5795. I forgot to link it to this issue
