### ISSUE TITLE
CMake downloading files, and wrong files

### ISSUE THREAD

**Issue by mboisson** [rdkit/rdkit#4957]
**Describe the bug**
When configuring the build, CMake fails with 
```
259 == Done updating pains files
260 Downloading https://fonts.google.com/download?family=Comic%20Neue...
261 CMake Error at Code/cmake/Modules/RDKitUtils.cmake:235 (MESSAGE):
262   The md5 checksum for
263   /tmp/mboisson/avx2/RDKit/2021.09.4/GCC-10.3.0/rdkit-Release_2021_09_4/Code/GraphMol/MolDraw2D/Comic_Neue.zip
264   is incorrect; expected: 23ed3f833c1ae0adb141a26b4a30d73e, found:
265   850b0df852f1cda4970887b540f8f333
266 Call Stack (most recent call first):
``` 

**Expected behavior**
CMake should *not* download things. Everything should be packed with the tarball release, or instructions should be provided on what to download for dependencies. 
If it is unavoidable, it should not fail on what is being downloaded. 

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.04
 - OS: [e.g. Ubuntu 20.04] Irrelevant
 - Python version (if relevant): Irrelevant
 - Are you using conda? Never

**Comment by ptosco** [comment]
This has already been reported and fixed: #4885
