### ISSUE TITLE
SHASUM for downloaded Neue_comic font during installation is wrong

### ISSUE THREAD

**Issue by hseara** [rdkit/rdkit#4967]
**Describe the bug**
The SHASUM embedded in "Code/GraphMol/MolDraw2D/CMakeLists.txt" for the Neue_comic font is wrong.
Then compilation fails. Please change sha:
```sed -i 's/23ed3f833c1ae0adb141a26b4a30d73e/850b0df852f1cda4970887b540f8f333/' ${srcdir}/${pkgname}-Release_${pkgver}/Code/GraphMol/MolDraw2D/CMakeLists.txt` ```

``

**To Reproduce**
Compilation in archlinux fails unless sha is corrected.

**Expected behavior**
Succesful compilation.

**Screenshots**
![image](https://user-images.githubusercontent.com/2016887/151534454-a1d12363-8132-49ea-84ab-cd38511fd722.png)

**Configuration (please complete the following information):**
 - RDKit version: 2021_09_4
 - OS: Archlinux
 - Python version (if relevant): Python 3.10.1
 - Are you using conda? No
 
**Additional context**

**Comment by ptosco** [comment]
This has already been reported and fixed: #4885
