### ISSUE TITLE
MolDraw2DSVG.DrawMolecule raises KekulizeException

### ISSUE THREAD

**Issue by nigel-palmer-cresset** [rdkit/rdkit#4979]
In RDKit 2021.09.4 MolDraw2DSVG.DrawMolecule is raising the exception `rdkit.Chem.rdchem.KekulizeException: Can't kekulize mol.  Unkekulized atoms: 8 12`. 

In RDKit 2020.09.4 the SVG was successfully generated.

```
from rdkit import Chem
from rdkit.Chem import Draw

mol = Chem.MolFromSmarts("[N:3]([c:2]1[c:1]cccc1)[c:4]2ncccn2")
mol.UpdatePropertyCache()
drawer = Draw.MolDraw2DSVG(100, 100)
drawer.DrawMolecule(mol) # Raises KekulizeException in RDKit 2021.09.4 
drawer.FinishDrawing()
svg = drawer.GetDrawingText()
print(svg)
```

**Configuration:**
 - RDKit version: 2021.09.4 
 - OS: Windows 10
 - Python version: 3.9.9
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Built from source

**Comment by ptosco** [comment]
@nigel-cresset 
Hi Nigel, great to hear from you! I can reproduce the issue at my end.
Here's how to avoid that RDKit attempts to kekulize that query molecule before drawing it (the `IPython` import is just for the sake of visualization in Jupyter):

```
from rdkit import Chem
from rdkit.Chem import Draw
from IPython.display import SVG

mol = Chem.MolFromSmarts("[N:3]([c:2]1[c:1]cccc1)[c:4]2ncccn2")
drawer = Draw.MolDraw2DSVG(300, 300)
drawer.drawOptions().prepareMolsBeforeDrawing = False
mol = Draw.PrepareMolForDrawing(mol, kekulize=False)
Chem.SanitizeMol(mol, Chem.SANITIZE_ALL ^ Chem.SANITIZE_KEKULIZE)
drawer.DrawMolecule(mol)
drawer.FinishDrawing()
svg = drawer.GetDrawingText()

SVG(svg)
```
![image](https://user-images.githubusercontent.com/5244385/152202601-a37e759e-cd90-4846-b0a2-c74d75627b8e.png)

**Comment by nigel-cresset** [comment]
Hi Paolo, that worked perfectly. Thanks for your help.
