### ISSUE TITLE
Latest build boost-cpp=1.74.0 causes "undefined symbol" error when importing rdkit.Chem from Python

### ISSUE THREAD

**Issue by guenp** [rdkit/rdkit#4987]
**Describe the bug**

After creating a new virtual environment in Conda with an `rdkit` dependency installed via  the `conda-forge` channel, importing `rdkit.Chem` from Python no longer works:

```python
qdk/qdk/chemistry/tests/conftest.py:6: in <module>
    from rdkit.Chem import AllChem as Chem
/usr/share/miniconda/envs/qdk/lib/python3.9/site-packages/rdkit/Chem/__init__.py:23: in <module>
    from rdkit.Chem.rdmolfiles import *
E   ImportError: /usr/share/miniconda/envs/qdk/lib/python3.9/site-packages/rdkit/Chem/../../../../libRDKitmaeparser.so.1: undefined symbol: _ZN5boost9iostreams4zlib8deflatedE
```
This error started happening in our CI builds after the latest build for `boost-cpp` was pushed.

**To Reproduce**
Install `rdkit` from `conda-forge` with `boost-cpp=1.74.0=h359cf19_6`

Run from Python:

```python
from rdkit.Chem import AllChem as Chem
```

**Expected behavior**
The import from Python should run without errors. This was working earlier today before `h359cf19_6` was pushed to `conda-forge`. See: https://anaconda.org/conda-forge/boost-cpp/files?version=1.74.0

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.4, build py39hccf6a74_0
 - OS: Ubuntu 20.04 (see `ubuntu-latest` on https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software)
 - Python version (if relevant): 3.9.10
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**

I was able to fix the issue by reverting `boost-cpp=1.74.0` to the previous build `h359cf19_5`.

The issue only happened on Ubuntu 20.04, I was unable to reproduce it on Mac OSX (Monterey 12.0.1).

**Comment by greglandrum** [comment]
@guenp : thanks for the very detailed and clear issue report.
I can reproduce this, but it s a problem with the conda-forge builds, not the rdkit itself (i.e, there's nothing that we can do here to fix the problem). 

This is something for the maintainers of the RDKit conda-forge feedstock, so I've created an issue in the rdkit conda-forge repo here:
https://github.com/conda-forge/rdkit-feedstock/issues/93

**Comment by guenp** [comment]
This issue was fixed by https://github.com/conda-forge/boost-cpp-feedstock/pull/115
Thanks @greglandrum
