### ISSUE TITLE
Add Find MCS function to MinimalLib

### ISSUE THREAD

**Issue by iwatobipen** [rdkit/rdkit#4988]
Dear,

Recently I'm interested in rdkit minimallib. Thanks for sharing the code!
By using the library, I can use RDKit from Rust. And I would like to use find MCS with rdkit minimal lib.
Find MCS is common task for medchem SAR analysis so I would like to know how to do it with the library. Is it possible to do it?
Thanks,

Taka

**Comment by xrl** [comment]
Hi @iwatobipen, please take a look at my beginners effort to make it easy to install RDKit CFFI with Rust. My crate does all the work to build RDKit from scratch inside of the rust crate (which I barely understand how it works). it does have some issues on rebuilding the rdkit library more often than it should.

The high level code I borrowed a from https://github.com/chrissly31415/rdkitcffi . Both my library and rdkitcffi are under the same license.

Find my work here: https://crates.io/crates/rdkit-sys and you can find it published to crates.io as well: https://crates.io/crates/rdkit-sys/ . I have only tested it on M1 Pro laptop, so ARM64, but I assume it will work more or less on other platforms. I do not have a good solution for how to distribute binaries from rdkit-sys, you will have to move the relevant dylibs around too.

**Comment by iwatobipen** [comment]
Hi @xrl , thanks for sharing the code.
I'll try to use it.
Thanks !!!
