### ISSUE TITLE
"Bad Conformer Id" when drawing molecules

### ISSUE THREAD

**Issue by marcossantanaioc** [rdkit/rdkit#4991]
-----------------------------------------

If you have a question about the RDKit or aren't sure if what you're seeing is the right behavior please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

Please help us help you: We normally need the information below in order to answer questions or understand bug reports. If you do not provide the information requested we may not be able to help you and will probably close the issue.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Describe the bug**
Drawing molecules is returning a "Bad Conformer Id" error. Using the `AllChem.EmbedMolecule` function before calling `DrawMolecule()` returns no error.

**To Reproduce**

diclofenac = Chem.MolFromSmiles('O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl')
d2d = rdMolDraw2D.MolDraw2DSVG(350,300)
d2d.drawOptions().addBondIndices=True
d2d.DrawMolecule(diclofenac)
d2d.FinishDrawing()
SVG(d2d.GetDrawingText())

ValueError                                Traceback (most recent call last)
<ipython-input-30-b385beab58a9> in <module>
      2 d2d = rdMolDraw2D.MolDraw2DSVG(350,300)
      3 d2d.drawOptions().addBondIndices=True
----> 4 d2d.DrawMolecule(diclofenac)
      5 d2d.FinishDrawing()
      6 SVG(d2d.GetDrawingText())

ValueError: Bad Conformer Id

**Expected behavior**
![image](https://user-images.githubusercontent.com/75497717/152781982-5884b8df-b970-4608-9945-237dae1856fb.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/75497717/152781057-bbf95283-3e7d-4541-964f-bc2545b1c310.png)

**Configuration (please complete the following information):**
 - RDKit version: 2019.09.3
 - OS: MacOS BigSur
 - Python version (if relevant): 3.8.8
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda install -c conda-forge rdkit

**Additional context**
I found this error while drawing grids using the mols2grid package.

**Comment by ptosco** [comment]
I cannot reproduce this with the current released version (`2021.09.4`):

```
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG

import rdkit
rdkit.__version__
'2021.09.4'

diclofenac = Chem.MolFromSmiles('O=C(O)Cc1ccccc1Nc1c(Cl)cccc1Cl')
d2d = rdMolDraw2D.MolDraw2DSVG(350,300)
d2d.drawOptions().addBondIndices=True
d2d.DrawMolecule(diclofenac)
d2d.FinishDrawing()
SVG(d2d.GetDrawingText())
```
![image](https://user-images.githubusercontent.com/5244385/152797457-bfbc12f7-a662-4a95-bc04-f3dab6e6b3cf.png)

If you upgrade your RDKit version you will not see the problem anymore.
Alternatively, call
```
rdDepictor.Compute2DCoords(diclofenac)
```
before calling `DrawMolecule()` to explicitly add a 2D conformation to `diclofenac`.
