### ISSUE TITLE
It should be nice to have a mol_from_inchi and a is_valid_inchi functions in PostgreSQL Cartridge

### ISSUE THREAD

**Issue by AttilaVM** [rdkit/rdkit#5005]
**Is your feature request related to a problem? Please describe.**

There are some data sources which only use InChi to represent molecule structures.

**Describe the solution you'd like**

RDKit already [supports](https://www.rdkit.org/docs/source/rdkit.Chem.inchi.html#rdkit.Chem.inchi.MolFromInchi) InChi as input format to create molecules. However no such a function [documented](https://www.rdkit.org/docs/Cartridge.html) for the PostgreSQL cartridge and I also checked the source and did not find a `mol_from_inchi` function.

It should be similar to `mol_from_smiles` by just accepting an InChi string while always sanitizing the molecule. 

and a `is_valid_inchi` function would also be nice.

and the already present `mol_inchi` function should be renamed to `mol_to_inchi` for more consistent naming, because of the `mol_to_smiles`, `mol_to_ctab` etc... functions.

**Describe alternatives you've considered**

When a data source only has structural information in InChi one can pre-process it with RDKit in python to calculate canonical SMILES or mol block, before uploading it to the db. 

**Additional context**

**Comment by dpdoughe** [comment]
Can this request be re-opened and prioritized? I think this would be a huge value-added for the database cartridge. Without this functionality, either the inchi1 binary, the Python RDKit, or some other tool (e.g. ChemDraw) is required to import to Mol in the database which is a maintenance burdon.
