### ISSUE TITLE
Bad tautomers produced for phosphorous compounds

### ISSUE THREAD

**Issue by NikSchap2107** [rdkit/rdkit#5008]
**Describe the bug**
rdMolStandardize.TautomerEnumerator().Enumerate() gives tautomers that chemically are not possible and rdMolStandardize.TautomerEnumerator().Canonicalize() assigns the chemically non-plausible tautomer as the canonical tautomer.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

lig = Chem.MolFromSmiles("NP(=O)(O)N(CCCl)CCCl")
canonicalizer = rdMolStandardize.TautomerEnumerator()
tautomers = canonicalizer.Enumerate(lig)

"""
Tautomers generated:
Tautomer 1: N=P(O)(O)N(CCCl)CCCl
Tautomer 2: N=[PH](=O)(O)N(CCCl)CCCl
Tautomer 3: NP(=O)(O)N(CCCl)CCCl
Tautomer 4: N[PH](=O)(=O)N(CCCl)CCCl
"""

canonical_tautomer = canonicalizer.Canonicalize(lig)

# Canonical tautomer: N[PH](=O)(=O)N(CCCl)CCCl
```

**Expected behavior**
Tautomers 2 and 4 should not be returned and tautomer 4 should not be picked as the canonical tautomer.

**Configuration:**
 - RDKit version: 2021.09.4
 - OS: CentOS Linux 7, GNOME Version 3.28.2
 - Python version (if relevant): 3.9.7
 - Are you using conda?: Yes
 - If you are using conda, which channel did you install the rdkit from?: conda-forge

**Comment by wopozka** [comment]
@greglandrum 
I would say the rule is not fully correct. The rule should match trivalent phosphorus atom with free OH group that converts to corresponding tautomer (even in the rule description is so). Due to the not properly defined reaction the left site matches anything, and heptavalent phosphorus is produces - which AFAIR should not really happen for tautomers. I would definitelly correct it to something at least like: [#1:1][O:2][PX3:3]>>[O:2]=[P:3][#1:1]

**Comment by rubbs14** [comment]
@wopozka is absolutely correct. This 1,3 sigmatropic shift is never observed for phosphates/phosphonates.

**Comment by NikSchap2107** [comment]
Both @rubbs14 and @wopozka are correct. As reference I can also provide point 2 on "Thermal [1,3] sigmatropic hydrogen shift" from https://www.stereoelectronics.org/webPR/PR_06.html.

**Comment by greglandrum** [comment]
@wopozka : That seems reasonable.

We don't use the SMIRKS directly, so I'm going to use the query: `[OH]-[PX3H0]` to recognize the O-P pair of interest.
