### ISSUE TITLE
Mol images in DataFrames are drawn only once in Jupyter Lab

### ISSUE THREAD

**Issue by mrcblt** [rdkit/rdkit#5017]
**Describe the bug**
With the latest RDKit version `2021.09.4`, the images of molecules in DataFrames are only drawn on the first display when using Jupyter Lab. On subsequent display attempts, the images are no longer drawn. 

I have tested it with Pandas versions `1.4.1`, `1.4.0`, `1.3.5`, `1.2.5` and `1.1.5` and the same problem occurs with all of them.

The error does not occur with RDKit version `2021.09.2` in combination with Pandas `1.4.1` or `1.1.5`, the DataFrames are all displayed correctly here. 

With RDKit version `2021.09.3`, the already fixed error mentioned in ticket #4864 occurs with Pandas `1.4.1` as well as `1.1.5`.

If you look specifically at the Jupyter notebook attached below in a text editor, you will see that on the first call, the molecule image is given as `<img data-content=\"rdkit ...`, while on the second call, the entry looks like `&lt;img data-content=\"rdkit ...`.

**To Reproduce**
Basically, all that needs to be done in a Jupyter notebook is to create any DataFrame with RDKit mol objects and then display it with e.g. `df.head()`. If the same cell is executed again, the molecules are no longer drawn.

This is an example notebook: [1.4.1_2021.09.4_bug.ipynb.txt](https://github.com/rdkit/rdkit/files/8087891/1.4.1_2021.09.4_bug.ipynb.txt)

**Expected behavior**
The molecule images should be shown correctly in every call.

**Screenshots**
How it looks like:
![bug](https://user-images.githubusercontent.com/34354523/154460209-46b5ed54-3bf9-49a3-80f0-d1376b3cc464.PNG)

How it should look:
![works](https://user-images.githubusercontent.com/34354523/154460276-fb5498e7-7a2c-4130-9818-7af5071bdb67.PNG)

**Configuration (please complete the following information):**
 - RDKit version: **2021.09.4**
 - OS: **Windows 10 and Ubuntu 18.04**
 - Python version (if relevant): **3.9.10**
 - Are you using conda? **Yes**
 - If you are using conda, which channel did you install the rdkit from? **conda-forge**

**Comment by ptosco** [comment]
@mrcblt I can reproduce the problem and will look into fixing it.
Meanwhile, you can visualize the `DataFrame` as follows:
```
from rdkit import Chem
from IPython.display import HTML
from rdkit.Chem import PandasTools
import pandas as pd

def show_df(df):
    return HTML(df.to_html(notebook=True))

df = pd.DataFrame(dict(a=[1], s=['CCN']))
PandasTools.AddMoleculeColumnToFrame(df, smilesCol='s', molCol='m')

show_df(df)
```
![image](https://user-images.githubusercontent.com/5244385/154567869-84b14523-1b4c-40ad-9a23-806d54832096.png)

```
show_df(df)
```
![image](https://user-images.githubusercontent.com/5244385/154567876-cfcaaa76-e3e7-41ac-abe7-0c5f246d22bc.png)
