### ISSUE TITLE
smiles parsing error due to erroneous ring perception

### ISSUE THREAD

**Issue by AnsgarSchuffenhauer** [rdkit/rdkit#5055]
rdkit refuses to parse the smiles below

`mol = Chem.MolFromSmiles('CC1(C)NC(=O)CN2C=C(C[C@H](C(=O)NC)NC(=O)CN3CCN(C(=O)[C@H]4Cc5c([nH]c6ccccc56)CN4C(=O)CN4CN(c5ccccc5)C5(CCN(CC5)C1=O)C4=O)[C@@H](Cc1ccccc1)C3=O)[N-][NH2+]2')`

The error message is:
RDKit ERROR: [10:26:38] non-ring atom 45 marked aromatic
[10:26:38] non-ring atom 45 marked aromatic

As @ptosco  kindly helped to find out, a ring perception issue seems to be the root cause here, failing to recognize the phenyl sidechain as a ring. 

**Configuration (please complete the following information):**
 - RDKit version:  2021.09.4
 - OS: [e.g. Ubuntu 20.04]: CentOS 7
 - Python version (if relevant): Python 3.8.12
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? internal mirror of conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
A more detailed jupyter notebook containing the issue identfication is attached as zip file
[RingPerceiptionError.zip](https://github.com/rdkit/rdkit/files/8152222/RingPerceiptionError.zip)

**Comment by AnsgarSchuffenhauer** [comment]
The credit needs to go mostly to @ptosco who really figured out what was happening

**Comment by greglandrum** [comment]
This took longer to track down than expected because the error is due to a hash collision and not an algorithmic problem.
The fix (in the PR) is to stop using hashes to determine whether or not a ring has been seen.

**Comment by AnsgarSchuffenhauer** [comment]
Thanks a lot for looking into this so quickly. The hash collision also explains why this happened so erratically
