### ISSUE TITLE
AssignChiralTypesFromBondDirs assigns chirality for achiral molecules?

### ISSUE THREAD

**Issue by wopozka** [rdkit/rdkit#5056]
It might be a feature, but who knows. 
Presently I am integrating rdkit into BKChem. Initially I am going to use it for SMILES generation and SMILES reading. The easiest way to achieve chirality is to use proper bonddir parameter for dashed/wedged bonds and calculate later proper configuration. During unitesting I realized that when you do MolToSmiles for achiral molecules created in that way, @ appears in the SMILES. The smallest possible example below screenshot (replaceExistingTags=True does not help):

![obraz](https://user-images.githubusercontent.com/46928633/156074943-0d2b6e56-6530-4dce-bf03-a8df264a0715.png)

**Describe the bug**

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import AllChem
mol_smiles = Chem.MolFromSmiles('CC(C)(F)Cl')
for bond_index in range(len(mol_smiles.GetBonds())):
    print(bond_index, mol_smiles.GetBondWithIdx(bond_index).GetBeginAtom().GetSymbol(), mol_smiles.GetBondWithIdx(bond_index).GetEndAtom().GetSymbol())

```
**0 C C
1 C C
2 C F
3 C Cl**

```
mol_smiles.GetBondWithIdx(2).SetBondDir(Chem.rdchem.BondDir.BEGINWEDGE)
mol_smiles.GetBondWithIdx(3).SetBondDir(Chem.rdchem.BondDir.BEGINDASH)
Chem.rdmolops.SanitizeMol(mol_smiles)
AllChem.Compute2DCoords(mol_smiles)
Chem.rdmolops.AssignChiralTypesFromBondDirs(mol_smiles)
Chem.MolToSmiles(mol_smiles)
```
**C[C@@](C)(F)Cl**

`Chem.MolToSmiles(Chem.MolFromSmiles('C[C@@](C)(F)Cl'))
`
**CC(C)(F)Cl**

**Expected behavior**
In my opinion results of both actions should be the same - smiles without @ should be generated.

**Configuration (please complete the following information):**
 - RDKit version: 2019.09.1 (presently I am not able to check it on the newest one, it might have been fixed already, is so, then ignore it)
 - OS: [e.g. Ubuntu 20.04] Ubuntu linux
 - Python version (if relevant): 3.8.10
 - Are you using conda? no
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? system packages, dpgk

**Comment by greglandrum** [comment]
Hi @wopozka : I agree that it seems a bit odd, but the code is behaving as intended.
`AssignChiralTypesFromBondDirs()` just sets the appropriate `@` or `@@` flags on atoms based on the bond wedging provided. If you then want to remove the chiral markers for atoms which cannot be stereocenters you should call `AssignStereoChemistry()` with the `force` and `cleanIt` arguments both set to `True`
