### ISSUE TITLE
WedgeMolBonds should add both wedge and dashed bonds for carbons with 4 heavy substituents.

### ISSUE THREAD

**Issue by wopozka** [rdkit/rdkit#5067]
Presently WedgeMolBonds adds BEGINDASH parameter for only one bond in carbons with 4 heavy substituents. It results in structures that are difficult analyse when depicted, because one have to imagine 3d situation, and place one bond below the plane, and all three other bonds above plane. Eg:

```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdCoordGen
mol1 = Chem.MolFromSmiles('CCC[C@](F)(I)C')
mol1
```
![obraz](https://user-images.githubusercontent.com/46928633/157078055-5d915550-7b17-40d5-8701-700298e8789a.png)

```rdCoordGen.AddCoords(mol1)
Chem.WedgeMolBonds(mol1, mol1.GetConformers()[0])
for bond in mol1.GetBonds():
    print(bond.GetBondDir())
```

NONE
NONE
NONE
NONE
NONE
BEGINDASH

I think it would be reasonable if two bonds were updated in this situation. One should get BEGINDASH and the second BEGINWEDGE BondDir parameter. It should resulted in easier to analyse pictures eg:
![obraz](https://user-images.githubusercontent.com/46928633/157078884-0a8ec42a-6916-47d8-9991-a5a7b9898b79.png)

I am not telling it should be default behavior, but it could be useful if there was a parameter for this options.

**Comment by greglandrum** [comment]
Hi @wopozka, this is also what the IUPAC recommends (https://www.degruyter.com/document/doi/10.1351/pac200678101897/html?lang=en):
![image](https://user-images.githubusercontent.com/540511/157167975-7b7312e6-40ba-4bff-899b-36eef4ad30c0.png)
and I agree that it can be clearer.

We need to revisit the bond wedging code anyway as part of supporting non-tetrahedral stereochemistry, which also works better with multiple wedges at atoms. This is unlikely to get done in time for the 2022.03 release, but I would like to have it in for 2022.09.

One significant complication in fully implementing the actual IUPAC recommendation is that the two wedged bonds should be closer to each other than the other two bonds, so we'd have to change the 2D coordinate generation algorithm in addition to the bond wedging. I think it'd be worth doing the partial solution.

**Comment by wopozka** [comment]
@greglandrum great to hear that. For my personal application it would be enought if I have BEGINDASH and BEGINWEDGE bonddir set for two different bonds. Otherwise I need to set them manually. I am using 2d coordinates as well, but having properly calculated coordinates is not big issue for me.

**Comment by greglandrum** [comment]
@wopozka : I'm not sure what your use case is, but what the RDKit current does is generally unambiguous and is a quite common way of depicting atomic sterochemistry (IUPAC recommendations aside).

**Comment by wopozka** [comment]
@greglandrum I am integrating rdkit into bkchem drawing software. Presently I am working on smiles/inchi reading and creation. For generation of coordinates of atoms I am using rdkit functionality and it works pritty well, apart from non IUPAC depicting of stereocenters. As I said, I can live with it, but I would like to achieve at least dashed and wedged bonds. This is why I am complaining a bit. I would love if the library could do it for me, as it is better than do it manually :D. Thanks Greg.

**Comment by vandan-revanur** [comment]
@wopozka I have built a python library called [pychemprojections](https://github.com/vandan-revanur/pychemprojections). One of the features it provides are to display **WedgeDash** structure of compounds. This library is built on top of rdkit. 

You can find an example notebook [here](https://github.com/vandan-revanur/pychemprojections/blob/master/examples/wedgedash_projection.ipynb). 
Hope it is useful for you.

**Comment by greglandrum** [comment]
We might want to think about making this the default behavior at some point, but for now the option is at least there.
