### ISSUE TITLE
AssignChiralTypesFromBondDirs depends on bond creation order?

### ISSUE THREAD

**Issue by wopozka** [rdkit/rdkit#5068]
It might be that I am wrong, but I would assume AssignChiralTypesFromBondDirs should not depend on bond creation order, but should consider only BEGINDASH BEGINWEDGE params of given bonds. See below example:

```
from rdkit import Chem
from rdkit.Chem import AllChem

def create_mol1():
    editable_mol = Chem.EditableMol(Chem.Mol())
    atoms_id = dict()
    bonds_id = dict()
    atoms_id['Cq'] = editable_mol.AddAtom(Chem.Atom('C'))
    atoms_id['Cl'] = editable_mol.AddAtom(Chem.Atom('Cl'))
    atoms_id['F'] = editable_mol.AddAtom(Chem.Atom('F'))
    atoms_id['CH3'] = editable_mol.AddAtom(Chem.Atom('C'))
    atoms_id['CH2'] = editable_mol.AddAtom(Chem.Atom('C'))
    atoms_id['I'] = editable_mol.AddAtom(Chem.Atom('I'))
    bonds_id['F-Cq'] = editable_mol.AddBond(atoms_id['F'], atoms_id['Cq'], Chem.BondType.SINGLE) # 1 n 2 0
    bonds_id['CH2-I'] = editable_mol.AddBond(atoms_id['CH2'], atoms_id['I'], Chem.BondType.SINGLE) # 1 n 3 5
    bonds_id['Cq-Cl'] = editable_mol.AddBond(atoms_id['Cq'], atoms_id['Cl'], Chem.BondType.SINGLE) # 1 n 0 1
    bonds_id['Cq-CH2'] = editable_mol.AddBond(atoms_id['Cq'], atoms_id['CH2'], Chem.BondType.SINGLE) # 1 w 0 3
    bonds_id['Cq-CH3'] = editable_mol.AddBond(atoms_id['Cq'], atoms_id['CH3'], Chem.BondType.SINGLE) # 1 h 0 4
    mol = editable_mol.GetMol()
    mol.GetBondWithIdx(bonds_id['Cq-CH3'] -1).SetBondDir(Chem.BondDir.BEGINDASH)
    mol.GetBondWithIdx(bonds_id['Cq-CH2'] -1).SetBondDir(Chem.BondDir.BEGINWEDGE)
    Chem.SanitizeMol(mol)
    AllChem.Compute2DCoords(mol)
    Chem.AssignChiralTypesFromBondDirs(mol)
    Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
    return Chem.MolToSmiles(mol)

def create_mol2():
    editable_mol = Chem.EditableMol(Chem.Mol())
    atoms_id = dict()
    bonds_id = dict()
    atoms_id['Cq'] = editable_mol.AddAtom(Chem.Atom('C'))
    atoms_id['Cl'] = editable_mol.AddAtom(Chem.Atom('Cl'))
    atoms_id['F'] = editable_mol.AddAtom(Chem.Atom('F'))
    atoms_id['CH3'] = editable_mol.AddAtom(Chem.Atom('C'))
    atoms_id['CH2'] = editable_mol.AddAtom(Chem.Atom('C'))
    atoms_id['I'] = editable_mol.AddAtom(Chem.Atom('I'))
    bonds_id['F-Cq'] = editable_mol.AddBond(atoms_id['F'], atoms_id['Cq'], Chem.BondType.SINGLE) # 1 n 2 0
    bonds_id['CH2-I'] = editable_mol.AddBond(atoms_id['CH2'], atoms_id['I'], Chem.BondType.SINGLE) # 1 n 3 5
    bonds_id['Cq-Cl'] = editable_mol.AddBond(atoms_id['Cq'], atoms_id['Cl'], Chem.BondType.SINGLE) # 1 n 0 1
    bonds_id['Cq-CH3'] = editable_mol.AddBond(atoms_id['Cq'], atoms_id['CH3'], Chem.BondType.SINGLE) # 1 h 0 4
    bonds_id['Cq-CH2'] = editable_mol.AddBond(atoms_id['Cq'], atoms_id['CH2'], Chem.BondType.SINGLE) # 1 w 0 3
    mol = editable_mol.GetMol()
    mol.GetBondWithIdx(bonds_id['Cq-CH3'] -1).SetBondDir(Chem.BondDir.BEGINDASH)
    mol.GetBondWithIdx(bonds_id['Cq-CH2'] -1).SetBondDir(Chem.BondDir.BEGINWEDGE)
    Chem.SanitizeMol(mol)
    AllChem.Compute2DCoords(mol)
    Chem.AssignChiralTypesFromBondDirs(mol)
    Chem.AssignStereochemistry(mol, force=True, cleanIt=True)
    return Chem.MolToSmiles(mol)
print(create_mol1())
print(create_mol2())
```
```
C[C@@](F)(Cl)CI
C[C@](F)(Cl)CI
```

Both functions (create_mol1, create_mol2) are actually the same, but bond: Cq-CH3 and Cq-CH2  (the two which should be hashed and wedged) are created in oposite order. As we can see as a result moles with opposite stereochemistry are created. My impression is that it is not correct behaviour and both moles should have the same configuration. If we set BEGINDASH, BEGINWEDGE for only one bond, then bonds creation order should matter, otherwise IMHO shouldn't. 

Rdkit version: 2020.09.1
Python version: 3.7
Python and rdkit source: anaconda

**Comment by wopozka** [comment]
@greglandrum. Well I do not fully agree with you. What you presented is depiction made by software due to the wrong chirality calculation. I fully agree with you, that from that type of picture everyone would have problems to assign stereochemistry, but at the begining one does not have any coordinates, any picture. There can't be any ambigouity. You have only bonds and the information which is dashed and which is wedged. For a human it is enought to sketch the molecule correctly - it might be more difficult for computer, I agree. 
I understand how it is internally calculated in rdkit, but in my opinion if two bonds are defined, and they are not ambiguous rdkit should deal with the situation. 
I agree that it is not easy to say whether it is a bug or a feature. If you think everything is OK, then please close the ticket.

**Comment by greglandrum** [comment]
I don't understand what you mean. You set which bonds were wedged in your code. The drawing just shows the wedging that you provided. You set the wedges information without paying attention to where the atoms were positioned (wedges don't make any sense without atom positions) and ended up providing contradictory information.

**Comment by wopozka** [comment]
I selected two bonds to be wedged and dashed respectively. And you are right, I did not pay attention what are atoms position, as at the time i SetBondDir this information was unknown. I assumed  Compute2DCoords would use this information for proper calculation, but apparently I was wrong (actually Compute2DCoords is used only because AssignChiralTypesFromBondDirs did not work without) which in my opinion should be the case. But if it is not considered a bug, then I do not have any problems with closing the ticket. I've just need to revrite some code due to the wrong assumptions I made, and which were not clear for me from documentation.
Thanks Greg.

**Comment by greglandrum** [comment]
Ok, now I get it. 

To be explicit:
- `Compute2DCoords()` does not currently use information about bond wedging when it works. The RDKit supports bond wedging because it's required to generate drawings and to deal with mol blocks, but the primary representation for stereochemistry that it uses are the atomic tags which lead to the `@` and `@@` in SMILES.
- `AssignChiralTypesFromBondDirs()` does in fact need a conformer since a wedged bond without coordinates (ideally 2D coordinates) carries no meaning. This is a bit part of the reason why the primary stereochemistry representation is atom-centered.
