### ISSUE TITLE
Adding MCS support for atom match distance threshold?

### ISSUE THREAD

**Issue by proteneer** [rdkit/rdkit#508]
I'm trying to allow MCS to take into account geometric information. That is, when matching two atoms A in Query and B in Target, we reject it if the distance between A and B is more than some cut-off distance d.

At a glance, this seems non straightforward because the Atom class contains no information about atom coordinates (they are stored in the Conformer class). One solution is to store the coordinates in the Atom's dp_props Dict and then implement a custom MCSAtomCompareDistance functor of sorts, but this seems hacky.

 @greglandrum if you can provide some guidance on the best way to tackle this I'd be happy to work on this and provide a PR.

**Comment by greglandrum** [comment]
You can get an Atom's position via the owning molecule's conformation:
`atom.getOwningMol().getConformer().getAtomPos(atom.getIdx())`
That returns the position in the default conformation. You can also specify a conformer ID in the call to `getConformer()`

This is an interesting idea (and not something I'd thought about before). It seems like implementing a custom atom comparison function would be the best approach.
