### ISSUE TITLE
GetSimilarityMapForModel returns 'TypeError: No registered converter was able to produce a C++ rvalue of type double from this Python object of type numpy.int64'

### ISSUE THREAD

**Issue by spadavec** [rdkit/rdkit#5087]
**Describe the bug**
I have a collection of simple XGB Classifier models that operate on morgan fingerprints. In some cases, the module `GetSimilarityMapForModel` returns the following error: 

```
Traceback (most recent call last):
  File "make_similarity_map.py", line 78, in <module>
    res = plot_similarity_map(mol, CYP_model)
  File "make_similarity_map.py", line 55, in plot_similarity_map
    figure , max_weight = SimilarityMaps.GetSimilarityMapForModel(mol, SimilarityMaps.GetMorganFingerprint, lambda x : get_pred(x, model.predict), counterLines=0,step=0.001, draw2d=d)
  File "/home/user/miniconda3/envs/p36_bk/lib/python3.6/site-packages/rdkit/Chem/Draw/SimilarityMaps.py", line 254, in GetSimilarityMapForModel
    fig = GetSimilarityMapFromWeights(probeMol, weights, **kwargs)
  File "/home/user/miniconda3/envs/p36_bk/lib/python3.6/site-packages/rdkit/Chem/Draw/SimilarityMaps.py", line 175, in GetSimilarityMapFromWeights
    Draw.ContourAndDrawGaussians(draw2d,locs,weights,sigmas,nContours=contourLines,params=ps)
TypeError: No registered converter was able to produce a C++ rvalue of type double from this Python object of type numpy.int64

```
Other models produce the expected similarity map image. I don't think its an error with the model(s) themselves, as they are able to be loaded and make the appropriate predictions, but fail just at the SimilarityMap stage. 

**To Reproduce**

Here is some simple code to reproduce the error. The code _should_ work w/ model 'cyp1a2.h5' but not model 'cyp3a4.h5' (see attached @ bottom)

```python
from rdkit import Chem
from rdkit.Chem import Draw
import numpy 
from rdkit.Chem import AllChem
from rdkit.Chem.Draw import SimilarityMaps
from rdkit.Chem.Draw import rdMolDraw2D
import xgboost as xgb
import io 
from PIL import Image


def show_png(data):
    bio = io.BytesIO(data)
    img = Image.open(bio)
    return img

def get_pred(fp, pred_function):
    fp = numpy.array([list(fp)])
    return pred_function(fp)[0]


def plot_similarity_map(mol, model):
    d = Draw.MolDraw2DCairo(900, 900)
    fig , maxweight = SimilarityMaps.GetSimilarityMapForModel(mol, SimilarityMaps.GetMorganFingerprint, lambda x : get_pred(x, model.predict), draw2d=d)
    d.FinishDrawing()
    return d

model = xgb.XGBClassifier()
model.load_model('cyp1a2.h5')

test_smiles = 'Nc5ncc(c2nc(N1CCOCC1)nc3c2CCC3c4ccncc4)cn5'
mol = Chem.MolFromSmiles(test_smiles)


test_fps = numpy.array(AllChem.GetMorganFingerprintAsBitVect(mol, 4, nBits=2048))
test_fps = test_fps.reshape(-1, 2048)

activity_prediction = model.predict(test_fps)[0]
print(f'The activity class is : {activity_prediction}')

res = plot_similarity_map(mol, model)
activity_sim_map = show_png(res.GetDrawingText())
activity_sim_map.save('SimMap.png')


```

**Expected behavior**
A SimilarityMap image should be produced, but the above Traceback Error is produced instead. 

**Configuration (please complete the following information):**
 - RDKit version: '2020.09.1'
 - OS: Ubuntu 18.04
 - Python version : 3.6
 - Are you using conda? Yes
  - If you are using conda, which channel did you install the rdkit from? coda-forge

[cyp1a2.zip](https://github.com/rdkit/rdkit/files/8237912/cyp1a2.zip)
[cyp3a4.zip](https://github.com/rdkit/rdkit/files/8237913/cyp3a4.zip)

**Comment by IchiruTake** [comment]
I found your issue. Numpy Array see all of your element is integer, thus declaring int64 datatype as default, the solution is just add 'dtype=np.float64'

**Comment by greglandrum** [comment]
For similarity maps you want to use the predicted probability of being in the class you're most interested in, not the class predictions themselves. Here's a blog post with some sample code which may help:
https://iwatobipen.wordpress.com/2020/05/06/compare-the-view-point-of-different-qsar-models-rdkit-visualize-chemoinformatics/

**Comment by spadavec** [comment]
Thank you @greglandrum and @IchiruTake
