### ISSUE TITLE
pg_restore: error: COPY failed for table "mols": ERROR:  could not create molecule from SMILES

### ISSUE THREAD

**Issue by joelduerksen** [rdkit/rdkit#5095]
**Describe the bug**
Dumped postgres database
Restored postgres database, everything seems to work except restored mols table is 0 length
Looking at logs, mols table restore stopped on a molecule, and failed entire table restore.

pg_restore: error: COPY failed for table "mols": ERROR:  could not create molecule from SMILES 'Cc1ccc2c(c1)-n1-c(=O)/c=c/c(=O)-n-2-c2cc(C)ccc2-1'
CONTEXT:  COPY mols, line 72238580, column m: "Cc1ccc2c(c1)-n1-c(=O)/c=c/c(=O)-n-2-c2cc(C)ccc2-1"

Note: I am attempting to do a simple pg_dump on one server, then pg_restore it on another.  The issue seems to be with the rdkit managed mols.m column only, what it exports it can't read back in...

**To Reproduce**
Try storing "Cc1ccc2c(c1)-n1-c(=O)/c=c/c(=O)-n-2-c2cc(C)ccc2-1"?  I can extract the original mols.m data, if needed.
The data sets going in are diverse, but sanitized, INSERTed with mol_from_smiles

**Expected behavior**
pg_restore successfully re-creates database that was pg_dump(ed)

**Configuration (please complete the following information):**
 - RDKit version: 
 - OS: Ubuntu 20.04
 - Python version 3
 - Are you using conda? yes, conda 4.11.0
 - If you are using conda, which channel did you install the rdkit from?
 - 
**environment.yml**
```
name: chemaware 
channels:
  - rdkit
  - conda-forge
  - anaconda 
dependencies:
  - pandas
  - psycopg2
  - sqlalchemy
  - flask
  - seaborn
  - gunicorn
  - flask-bootstrap
  - flask-nav
  - neo4j-python-driver
  - rdkit::rdkit==2020.03.1
  - python
  - chembl_structure_pipeline
  - py3dmol
  - chardet
  - dask
```

 - If you are not using conda: how did you install the RDKit?

**Additional context**
this is a very diverse compilation of molecules, ~1 million are dropped when loaded/sanitized in python, treating all molecules as mol (not qmol), total dataset size is ~125-200 million (depending on factors like if I keep coordinates, etc)   This failure is about half-way through the mols table restore...

**Comment by greglandrum** [comment]
This is the same molecule which is responsible for #5078 : the RDKit produces a SMILES which it cannot parse.
However, when doing pg_restore that shouldn't matter since the sanitization step which is causing the error could be skipped.
I'll take a look at this.

**Comment by joelduerksen** [comment]
And I would point out that the molecule passed through sanitization before being stored in the first place…

**Comment by greglandrum** [comment]
yeah, that's the key: the `mol_in()` function called by pg_restore doesn't need to be doing sanitization

**Comment by joelduerksen** [comment]
ah, OK. thank you, it sounds like that would help, and as luck would have it, I do have a couple of chembl subsets in the collection... I had searched tickets for pg_restore issues, so didn't stumble across [#5078](https://github.com/rdkit/rdkit/issues/5078)

agree, I would imagine what is dumped out, ought to be restored "as is" with no processing (or only what is absolutely required, if "in database" and "dumped" can't be exactly the same)

One minor concern might be over spans of time the mol format might evolve...  but I consider that a migration issue, not a dump/restore concern
