### ISSUE TITLE
ERROR: 132

### ISSUE THREAD

**Issue by curcioriccardo** [rdkit/rdkit#5111]
-----------------------------------------

If you have a question about the RDKit or aren't sure if what you're seeing is the right behavior please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

Please help us help you: We normally need the information below in order to answer questions or understand bug reports. If you do not provide the information requested we may not be able to help you and will probably close the issue.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2021.9.5.1
 - OS: Ubuntu 18.04.3 LTS
 - Python version (if relevant): 3.9
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Both via pip install rdkit-pypi and from source code

Hello, i am having trouble running rdkit in python. In particular i get ERROR: 132 by running this minimal code from the pip install tutorial, without any explanation : from rdkit import Chem; print(Chem.MolToMolBlock(Chem.MolFromSmiles('C1CCC1')))
I installed rdkit also from git and i get the same error.

Thanks for the support.
Best regards.

**Additional context**
Creating parametersdistributions-ml_app_run ... done
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem; print(Chem.MolToMolBlock(Chem.MolFromSmiles('C1CCC1')))
ERROR: 132

**Comment by greglandrum** [comment]
This is almost definitely not an RDKit problem or anything we can help you with here. Please ask on the RDkit-pypi repository, where they have the expertise to answer questions about problems with the pip installed RDKit versions; https://github.com/kuelumbus/rdkit-pypi
