### ISSUE TITLE
RDKITjs Output 2D Coordinates of Atoms/Bonds?

### ISSUE THREAD

**Issue by swamidass** [rdkit/rdkit#5112]
Great javascript bindings. How can I determine the SVG coordinates of all the atoms and bonds? At the moment, the atom-# and bond-# classes are included, which give a way to somewhat approximate the coordinates, but that does not work so well.

Is there a way to have these embedded directly in the SVG, or otherwise output?

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.
