### ISSUE TITLE
Dative bond and alkali and alkaline earth metals

### ISSUE THREAD

**Issue by marcostenta** [rdkit/rdkit#5120]
**Describe the bug**
the dative bond with group 1 and 2 metals does not work as for other metals
reading smiles/mol files generates an error on valence

**To Reproduce**
a colab link: https://colab.research.google.com/drive/19OZtX8IqICZQ4B2jLpr02owkSLc0FeZ6?usp=sharing

Steps to reproduce the behavior, feel free to paste a bit of Python in here.
Chem.MolFromSmiles('O->[Fe+2]<-O')   # works
Chem.MolFromSmiles('[O-]->[Fe+2]<-[O-]') # works

Chem.MolFromSmiles('O->[Mg+2]<-O') # it does not work
[Explicit valence for atom # 1 Mg, 4, is greater than permitted ]

Chem.MolFromSmiles('O->[K]<-O')
[Explicit valence for atom # 1 K, 2, is greater than permitted]

**Expected behavior**
I and II group metals to behave as other metals.
read in the molecule with sanitization=True leading to a functioning molecule
not splitting the molecule in fragments by breaking on the dative bond
work by reading in smiles, cxsmiles with dative bond arrows
work by reading in MDL sdfiles in V3000 format with dative as type=9 bond

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 
 - OS: windows
 - Python version (if relevant): 3.7
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by greglandrum** [comment]
Closed in #6139
