### ISSUE TITLE
mol V3000: multicenter dative bond

### ISSUE THREAD

**Issue by marcostenta** [rdkit/rdkit#5121]
**Is your feature request related to a problem? Please describe.**
I try to read and use molecular complexes where the ligand have hapticity higher than 1 (ferrocene), and keep track of the bonds
I write the structures as multi-center dative bonds, but the information is ignored by RDKIT that interprets the complex as a two-fragment molecule, with dative bond from a dummy atom to the metal

**Describe the solution you'd like**
I would like to have the the bonds between metal and donors in the bond list, and the neighbor list of all atoms correctly accounted for.
I would also have a molecular or atomic property to know which atom is part of which multicenter group, and to which atom they bond.
Iwould like to create this with molraw if necessary,
and write back a molfile, and extract a bound smiles (how?)

**Describe alternatives you've considered**
explicitating in the drawing a dative bond for each donating atom: chemist would not do it in the long term.

**Additional context**
an example:

  Mrv2115 03212217142D

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 4 2 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -15.3748 8.1666 0 0
M  V30 2 C -14.0411 7.3966 0 0
M  V30 3 Pd -16.5831 5.2082 0 0
M  V30 4 * -14.708 7.7816 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 2 1 2
M  V30 2 9 4 3 ENDPTS=(2 1 2) ATTACH=ALL
M  V30 END BOND
M  V30 END CTAB
M  END

**Comment by greglandrum** [comment]
Closed in #6139
