### ISSUE TITLE
Image Generation: Highlighting looks off when bondLineWidth is increased for PNG generation

### ISSUE THREAD

**Issue by rachelnwalker** [rdkit/rdkit#5122]
**Describe the bug**
When using `MolDraw2DFromQPainter` to generate a PNG image of a molecule with a highlighted substructure and increased bondLineWidth, the highlighting looks a little off. This does not happen when using `MolDraw2DSVG`. Here is an example, where the bond highlighting slightly sticks out past the atom highlighting:

![image](https://user-images.githubusercontent.com/39069546/159591552-f345d2eb-54c5-401a-a3c5-8486cf2c7be0.png)

For reference, here is the same structure without increased bondLineWidth:
![image](https://user-images.githubusercontent.com/39069546/159591463-5c84d0a9-b1c4-4600-92d2-38b32d08e2a4.png)

**To Reproduce**
Here is the code I used to create the above image:

```
mol = Chem.MolFromSmiles('CC1=CC=C(C=C1)C1=CC=CC=C1')
highlight = Chem.MolFromSmiles("C1=CC=CC=C1")
qimg = QImage(400, 400, QImage.Format_ARGB32)
qimg.fill(Qt.transparent)
with QPainter(qimg) as cpp_qp:
    drawer = MolDraw2DFromQPainter(cpp_qp, 400, 400)
    draw_options = drawer.drawOptions()
    draw_options.bondLineWidth = 3
    draw_options.scaleHighlightBondWidth = True
    drawer.DrawMolecule(mol,
                highlightAtoms=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                highlightBonds=[1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13])
qimg.save("img.png")
```

**Expected behavior**
It would be nice for the highlighting to match SVGs. It seems like either the bond highlight doesn't go as far in SVG generation, or the atom highlight radius is slightly scaled up. The bond highlight width doesn't look too different to me. This is what the example above looks like with the same draw options when creating an SVG image:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/39069546/159590594-0377f13f-6f7f-4ab8-a512-42afc6e95197.png">

**Configuration (please complete the following information):**
 - RDKit version: 2022_03_1b1 
 - OS: Mac
 - Are you using conda? No 

**Additional context**
I think this may be related to this that was fixed a couple months ago https://github.com/rdkit/rdkit/issues/4764

**Comment by greglandrum** [comment]
This is happening because the default Qt line capping is `Qt::SquareCap`, which extends half a line-width beyond the end of the line. We should switch to `Qt::FlatCap`
