### ISSUE TITLE
Chem.MolFromSmiles does not support % sign for ring closure digits

### ISSUE THREAD

**Issue by ghost** [rdkit/rdkit#5130]
**Configuration:**

 
Using Python 3.9.10, with ipython through terminal

- RDKit Version: 2021.09.2
- Operating system: Mac/Linux
- Python version (if relevant): 3.9.10
- Are you using conda? No
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit?  pip install rdkit-pypi

**Description:**

 I am working with molecules that have more than 9 ring closure atoms, and need to use digits 10 and above. Following SMILES grammar rules, a '%' sign needs to be added before the large digit to indicate that the atom C%10 is connected to an atom ten and not atom one and an atom zero. I get a parsing error when using a '%' in my SMILES string that doesn't occur when the '%' is absent (see below).

```
In [1]: from rdkit import Chem

In [2]: mymolecule = 'C%1CCCCC%1'

In [3]: Chem.MolFromSmiles(mymolecule)
[09:26:52] SMILES Parse Error: syntax error while parsing: C%1CCCCC%1
[09:26:52] SMILES Parse Error: Failed parsing SMILES 'C%1CCCCC%1' for input: 'C%1CCCCC%1'

In [4]: mymolecule = 'C1CCCCC1'

In [5]: Chem.MolFromSmiles(mymolecule)
Out[5]: <rdkit.Chem.rdchem.Mol at 0x7fef986460a0>
```

**Comment by bp-kelley** [comment]
From the daylight smiles page:

```
If necessary or desired, higher-numbered ring closures may be specified by prefacing a two-digit number with percent sign (%). For example, C2%13%24 is a carbon atom with a ring closures 2, 13, and 24 .
```

The smiles grammar expects more than one letter after a %.  This helps to parse C12 (two ring connections) versus C%12 (one ring connection) and C%123 (two ring connections).

**Comment by greglandrum** [comment]
Adding on to @bp-kelley's answer: it's als possible to specify the ring closures with 1-5 digits by putting them inside parentheses (this is a SMILES extension): `C%(1)CC%(1)`
This is documented here: https://rdkit.org/docs/RDKit_Book.html#ring-closures
