### ISSUE TITLE
Failure to parse directional bond "up/down or unspecified"

### ISSUE THREAD

**Issue by zacps** [rdkit/rdkit#5133]
**Describe the bug**
The following smarts fail to parse:
```
[#6]\?[#6]>>[#6]
[#6]/?[#6]>>[#6]
```
because of the `\?` indicating down or unspecified or the `/?` indicating up or unspecified bonds.

These are described in the [daylight theory smarts reference](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html).

**To Reproduce**
```python
from rdkit.Chem import AllChem
AllChem.ReactionFromSmarts(r"[#6]\?[#6]>>[#6]")
```
```python-traceback
RDKit ERROR: [time] SMARTS Parse Error: syntax error while parsing: [#6]\?[#6]
RDKit ERROR: [time] SMARTS Parse Error: Failed parsing SMARTS '[#6]\?[#6]' for input: '[#6]\?[#6]'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 2>()
----> 1 AllChem.ReactionFromSmarts(r"[#6]\?[#6]>>[#6]")

ValueError: ChemicalReactionParserException: Problems constructing reactant from SMARTS: [#6]\?[#6]
```

**Expected behavior**
The reaction parses successfully.

**Configuration (please complete the following information):**
 - RDKit version: `2021.09.5`
 - OS: Windows 10
 - If you are not using conda: how did you install the RDKit? poetry (pypi)

**Comment by greglandrum** [comment]
Hi @zacps : this is a known shortcoming in the RDKit. The toolkit does not support that kind of query
