### ISSUE TITLE
kekulize error while it's valence error

### ISSUE THREAD

**Issue by thegodone** [rdkit/rdkit#5135]
when trying to read this molecule I got a kekulize error:
```
sa = '[c:1]1[c:6][c:5][c:4][c:3][n:2]1[CH2:7][C:8]([CH3:9])=[O:10]'
```

spotting the 5 first atoms in the aromatic ring. 

But the error is indeed the "n" that needs a positive charge +.

how to reproduce ?
****
```

m = Chem.MolFromSmiles(sa,sanitize=False)
m.UpdatePropertyCache(strict=False)

ps = Chem.DetectChemistryProblems(m)              
if not ps:
    Chem.SanitizeMol(m)
    print('sol:',Chem.MolToSmiles(m))
else:
    for p in ps:
        print(p.GetType())
        if p.GetType()=='KekulizeException':
            print(p1.GetAtomIndices())
```

![image](https://user-images.githubusercontent.com/1186658/160082664-fb9e7eb1-df3d-405d-a94a-af028ce42c38.png)

****
```
m = Chem.MolFromSmiles(sa,sanitize=False)
m.UpdatePropertyCache(strict=False)

for at in m.GetAtoms():
    if at.GetAtomicNum()==7 and at.GetFormalCharge()==0 and at.IsInRing() and at.GetIsAromatic():
        at.SetFormalCharge(1)
        at.UpdatePropertyCache()

ps = Chem.DetectChemistryProblems(m)              
if not ps:
    Chem.SanitizeMol(m)
    print('sol:',Chem.MolToSmiles(m))
```

![image](https://user-images.githubusercontent.com/1186658/160082762-242e4f8e-d2b7-423d-bd42-6ebf2eabe39a.png)

****

**Comment by rapodaca** [comment]
The RDKit error is what I'd expect to see.

The nitrogen atom lacks an unpaired electron. It has 3 single bonds and therefore no "free" valence to donate to the aromatic system.

The five carbons are marked as aromatic. Each one has 2 single bonds and no hydrogens, leaving one free valence. These carbons are therefore added to the aromatic system.

However, it's impossible to derive a perfect matching on this subgraph of 5 atoms, thus the error. If this doesn't make sense [this article](https://depth-first.com/articles/2020/02/10/a-comprehensive-treatment-of-aromaticity-in-the-smiles-language/) may help.

Note that your situation is different from pyrroles, where there are only four carbons in the pi system and a perfect matching exists for that.

Also note that this is a weird SMILES in that the carbons literally have zero hydrogens. It's a pyridine ring where the carbons have no hydrogens. A penta-radical.

**Comment by greglandrum** [comment]
To elaborate on @rapodaca 's answer:
An aromatic N is "allowed" to have an extra bond, that's what converts it from a one pi electron donor to a two pi electron donor. A simple example of this is `c1cccn1C`. These can be converted into a kekule form which has all single bonds to the N.
The same is not true of your example: there's no way to convert that into a kekule form with all single bonds to the N.
