### ISSUE TITLE
estate segmentation fault

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#514]
For no real reason other than curiosity, I decided to try a function from the EState module, and ended up with a segfault:

    >>> from rdkit import Chem
    >>> mol = Chem.MolFromSmiles("C")
    >>> from rdkit.Chem.EState import EState
    >>> EState.EStateIndices(mol)
    Segmentation fault

The top of the stack trace is:

    0   rdmolops.so                   	0x000000010966e97e RDKit::getDistanceMatrix(RDKit::ROMol&, bool, bool, bool, char const*) + 110
    1   rdmolops.so                   	0x000000010968980f boost::python::detail::caller_arity<5u>::impl<_object* (*)(RDKit::ROMol&, bool, bool, bool, char const*), boost::python::default_call_policies, boost::mpl::vector6<_object*, RDKit::ROMol&, bool, bool, bool, char const*> >::operator()(_object*, _object*) + 367
    2   libboost_python-mt.dylib      	0x000000010858737e boost::python::objects::function::call(_object*, _object*) const + 766
    3   libboost_python-mt.dylib      	0x000000010858947a boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) + 26

**Comment by greglandrum** [comment]
I can't reproduce this on the Mac with either the git version of the RDKit or the most recent release.
```python
In [4]: rdkit.__version__
Out[4]: '2015.03.1'

In [5]: from rdkit import Chem

In [6]: mol = Chem.MolFromSmiles("C")

In [7]: from rdkit.Chem.EState import EState

In [8]: EState.EStateIndices(mol)
Out[8]: array([ 0.])
```

Which RDKit version are you using on which OS?

**Comment by adalke** [comment]
Hmm. 2014.09.1. Upgrading now ....  You're right, it was a false alarm, and not a problem with the most recent RDKit.
