### ISSUE TITLE
MolToSmarts does not serialize isotopes

### ISSUE THREAD

**Issue by lilyminium** [rdkit/rdkit#5150]
**Describe the bug**

I'm not sure if I should be doing this differently or have unphysical expectations, but I expected my arbitrary isotopes to get serialized with `MolToSmarts` as they are with `MolToSmiles`. However, they are not. Relates to #1472.

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

```python
from rdkit import Chem
smarts = "[C](=[O])"
rdmol = Chem.MolFromSmarts(smarts)
for atom in rdmol.GetAtoms():
    atom.SetIsotope(4)
Chem.MolToSmarts(rdmol)
```
'C=O'
```python
Chem.MolToSmiles(rdmol)
```
'[4CH2]=[4O]'

**Expected behavior**

Expected some kind of isotopic SMARTS, like '[4C]=[4O]'

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.2
 - OS: [e.g. Ubuntu 20.04]: MacOS Catalina
 - Python version (if relevant):  Python 3.8.12
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**

I tried various combinations of `SanitizeMol` and `UpdatePropertyCache`; they made no difference.

**Comment by lilyminium** [comment]
More context:

```python
smilesmol = Chem.MolFromSmiles('[4CH2]=[4O]')
smiles_smarts = Chem.MolToSmarts(smilesmol)
print(smiles_smarts)
smartsmol = Chem.MolFromSmarts(smiles_smarts)
smarts_smarts = Chem.MolToSmarts(smartsmol)
print(smarts_smarts)

for atom in smartsmol.GetAtoms():
    atom.SetIsotope(8)
    atom.UpdatePropertyCache()
smartsmol.UpdatePropertyCache()
Chem.SanitizeMol(smartsmol)
smarts_smarts8 = Chem.MolToSmarts(smartsmol)
print(smarts_smarts8)
```
```
[4#6H2]=[4#8]
[#6&4*&H2]=[#8&4*]
[#6&4*&H2]=[#8&4*]
```

I hadn't seen this way of specifying isotope before, so tried recreating a molecule with it:

```python
final_smarts_mol = Chem.MolFromSmarts("[#6&4*&H2]=[#8&4*]")
for atom in final_smarts_mol.GetAtoms():
    print(atom.GetIsotope())
```
```
0
0
```

**Comment by greglandrum** [comment]
This is expected behavior. When you construct a molecule from SMARTS the individual atoms are query atoms which include information in the query itself about what they are looking for. If you set the isotope on a query atom it will be ignored both when writing SMARTS and when doing substructure searching.

If you have a molecule constructed from SMARTS and you would like to add query information about isotopes, you can do so as follows:
```
from rdkit.Chem import rdqueries
m = Chem.MolFromSmarts('[C]=[O]')
print(Chem.MolToSmarts(m))
m.GetAtomWithIdx(0).ExpandQuery(rdqueries.IsotopeEqualsQueryAtom(14))
print(Chem.MolToSmarts(m))
```
This outputs:
```
C=O
[C&14*]=O
```

**Comment by greglandrum** [comment]
@lilyminium, a polite request: if you aren't very familiar with the RDKit and see something you don't expect, it's better to ask a question using the discussions tab (https://github.com/rdkit/rdkit/discussions) than it is to create a bug. If it turns out that you have discovered a bug, we can always open the issue from the discussion.

**Comment by lilyminium** [comment]
Apologies for jumping the gun! I was fooled by the `MolToSmiles` behaviour and thinking it was just another way to convert a molecule to string.

**Comment by greglandrum** [comment]
> Apologies for jumping the gun! I was fooled by the `MolToSmiles` behaviour and thinking it was just another way to convert a molecule to string.

`MolToSmarts()` is just another way to convert a molecule to a string. The difference here is what `MolFromSmarts()` does - construct a molecule with query atoms - vs what `MolFromSmiles()` does - construct a molecule with normal atoms.

**Comment by lilyminium** [comment]
> MolToSmarts() is just another way to convert a molecule to a string. The difference here is what MolFromSmarts() does - construct a molecule with query atoms - vs what MolFromSmiles() does - construct a molecule with normal atoms.

I think that's where my confusion lay -- `MolToSmiles` dealt with `QueryAtoms` as well, outputting `'[4CH2]=[4O]'`.
