### ISSUE TITLE
KekulizeException of molecule from Smarts pattern with new RDKit release 

### ISSUE THREAD

**Issue by schallerdavid** [rdkit/rdkit#5156]
**Describe the bug**
With the new release of RDKit (2022.03.1) we observed a KekulizeException that was not thrown by the previous RDKit release (2021.09.5), which prevents the rendering of a certain Smarts pattern with the `Draw.MolsToGridImage` functionality.

**To Reproduce**
```
from rdkit import Chem
mol = Chem.MolFromSmarts("[#6](:,-[#6]-,:[#7]-,:[#6]1:[#6]:[#6]:[#6]:[#6]:[#6]:1):,-[#6]:,-[#7]:,-[#6]")
Chem.Kekulize(m1)
```

**Expected behavior**
Both version behave consistent.

**Configuration (please complete the following information):**
 - RDKit versions: 2022.03.1 and 2021.09.5
 - OS: Ubuntu 20.04, MacOS, Windows
 - Python 3.7 - 3.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge  

**Additional context**
If the KekulizeException is correctly thrown for this Smarts pattern in the new RDKit version, it would be great to still be able to visualize it with `Draw.MolsToGridImage`. However, I cannot find a possibility to prevent the kekulization of the given molecules in this function, so the KekulizeError always gets thrown.

Thanks in a advance,
David

**Comment by greglandrum** [comment]
Hi @schallerdavid thanks for the bug report. I'll take a look and see if I can figure out what's going on and how to fix it

**Comment by ptosco** [comment]
@schallerdavid to visualize all molecules including those failing to kekulize, you can try the following:

```
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D, MolsToGridImage

mol_fails = Chem.MolFromSmarts("[#6](:,-[#6]-,:[#7]-,:[#6]1:[#6]:[#6]:[#6]:[#6]:[#6]:1):,-[#6]:,-[#7]:,-[#6]")
mol_succeeds = Chem.MolFromSmiles("c1ccccn1")

drawOptions = rdMolDraw2D.MolDrawOptions()
drawOptions.prepareMolsBeforeDrawing = False

def prepare_mol(mol):
    try:
        mol_draw = Chem.Mol(mol)
        Chem.Kekulize(mol_draw)
    except Chem.KekulizeException:
        mol_draw = rdMolDraw2D.PrepareMolForDrawing(mol, kekulize=False)
        Chem.SanitizeMol(mol_draw, Chem.SANITIZE_ALL ^ Chem.SANITIZE_KEKULIZE)
    return mol_draw

drawOptions = rdMolDraw2D.MolDrawOptions()
drawOptions.prepareMolsBeforeDrawing = False

mols = [mol_succeeds, mol_fails]

MolsToGridImage([prepare_mol(mol) for mol in mols], drawOptions=drawOptions)
[16:56:10] Can't kekulize mol.  Unkekulized atoms: 3
```
![image](https://user-images.githubusercontent.com/5244385/162229280-2b84b74d-1bc2-423c-88d2-31d2d4a8dfb3.png)

```
