### ISSUE TITLE
RDKit.pdf book outdated in 2015_03_01 release

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#516]
While it seems to be current in the github repo, the SF tarballs for the 2015Q1 release ship an apparently outdated PDF file, at least it says "Release 2013.09.1" on the title page.

I guess this is more of an SF than GitHub issue, but filing here for convenience.  Also, not sure the PDF should be checked into the GitHub repo at all.

**Comment by greglandrum** [comment]
Thanks for pointing that out.
