### ISSUE TITLE
Gasteiger Charge for organometallics are Nan

### ISSUE THREAD

**Issue by Wanyinee** [rdkit/rdkit#5160]
I want to get the Gasteiger Charge of a molecule. However, I get nan. How can I solve this problem?
```
smil = "[CH3:1][CH2:2][CH2:3][CH2:4][Sn:5]([CH2:6][CH2:7][CH2:8][CH3:9])([CH2:10][CH2:11][CH2:12][CH3:13])[c:14]1[cH:15][cH:16][c:17]([CH2:18][CH3:19])[n:20][cH:21]1"
mol = Chem.MolFromSmiles(smil)
AllChem.ComputeGasteigerCharges(mol)
for atom in mol.GetAtoms():
    value = '%.2f'%(atom.GetDoubleProp('_GasteigerCharge'))
    atom.SetProp('atomNote',value)
Draw.MolToImage(mol, size=(500, 500))

```
![图片](https://user-images.githubusercontent.com/70514121/161415370-1f63600a-728b-4e5d-b5a0-6cb19a0a7f3a.png)

**Comment by greglandrum** [comment]
The NaNs are arising because there are no Gasteiger parameters available for these metals. I'm afraid that there's nothing we can do in this case
