### ISSUE TITLE
Standardization via RDKit breaks molecules

### ISSUE THREAD

**Issue by malteseunderdog** [rdkit/rdkit#5169]
RDKit 2022.03.1
OS: 5.17.1-arch1-1 (but also reproduced under Ubuntu 20.04)
Python 3.9.12

Every four years (since my last bug report) I come across some weird behavior.  Most of the times it is my lack of understanding...

So, I have some code which standardizes a molecule (Cleanup, FragmentParent, uncharge, Reionize, Canonicalize). This works for hundreds of thousands of molecules, but occasionally a standardized molecule breaks in a round-trip (standard mol -> to smiles -> mol from smiles) and generates an error (Explicit valence for atom) and a `None` molecule.

An example, starting molecule, of which I have a handful: 

`[H]/[O+]=c\1/c(c(c1=O)[NH+]2CCCCC2)NCC3CCC(CC3)C(=O)NCCc4ccc(cc4)Cl`

This is what I get from sanitization, which when converted to smiles and read from smiles (round-trip) gives a `None` molecule.

`[H]/O=c1/c(NCC2CCC(C(=O)NCCc3ccc(Cl)cc3)CC2)c(N2CCCCC2)c1=O`

The first O atom has three bonds, but no charge (but surely the standardization process should not create broken mols).

Of course, this wouldn't be a good bug report without a MWE, so here you go:
https://nbviewer.org/urls/gist.githubusercontent.com/malteseunderdog/4609ff481d002b7354edfc28ca66b0bc/raw/cf6d28c1439a8287cee1564aa94f2b3d073bebc5/standardization_eats_mols.ipynb

Any ideas what is going on here, please?

**Comment by IchiruTake** [comment]
I am not so sure about this as the code in `Code/GraphMol/MolStandardize/Charge.cpp` is relatively complicated. 
An easier approach is to use the approach in `Chem.MolStandardize.charge.py` although I am not confident its correction. You can try add method as `SanitizeMol` to keep verifying your input as every standardizer tool.

Note: If you replace `rdMolStandardize.Uncharger(...)` by `MolStandardize.charge.Uncharger`, 
the result would be like this `[H]/[O+]=c1/c(NCC2CCC(C(=O)NCCc3ccc(Cl)cc3)CC2)c(N2CCCCC2)c1=O` when uncharge the molecule.

**Comment by malteseunderdog** [comment]
Any ideas what the differences are between the two, please? (Other than one works as you correctly pointed out and the other doesn't).

**Comment by IchiruTake** [comment]
I suppose it may related to the Smarts proposed in `pos_h` variable (I am not the RDKit developer, you can ask Greg for that). When I tested with Uncharger() in Python, the positive atom is the nitrogen N (not oxygen O)
