### ISSUE TITLE
Wrong rendering of stereochemistry from molfile

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#5179]
**Describe the bug**

RDKit renders a molfile differently and wrongly. Other editors like Marvin, ChemDraw or JSME show the same molfile correctly and it looks the same in all of these. RDKit being the exception. 

The molfile:

```
Untitled Document
  ChemDraw0000000020482D

 22 25  0  0  0  0  0  0  0  0999 V2000
   -0.7207    0.0143    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6935   -0.0131    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0383    0.4183    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3760    0.3964    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7207   -0.8103    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3923    1.2209    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1895    0.8005    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4523   -1.2034    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0383   -1.2034    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0273    1.2482    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4032   -0.4063    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6935   -0.7720    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6825    1.6413    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4523    0.4183    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7207    0.8386    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8346    1.9253    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1895   -0.7720    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1895   -0.0131    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0383   -0.2206    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7207   -1.3344    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8517   -1.9253    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0269   -1.9253    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  2  3  1  0      
  3  1  1  0      
  4  2  1  6      
  5  1  1  0      
  6 13  1  0      
  7 11  1  0      
  8  5  1  0      
  9  5  1  0      
  3 10  1  1      
  2 11  1  1      
 12  9  1  0      
 13 10  1  0      
 14  1  1  0      
  1 15  1  1      
 16  6  1  0      
 17 18  1  0      
 18 14  1  0      
  3 19  1  6      
  5 20  1  6      
  8 17  1  0      
  2 12  1  0      
  4  6  1  6      
  6  7  1  1      
  8 21  1  0      
 22  8  1  0
M  END
```

How it looks in ChemDraw (and Marvin and JSME):

![image](https://user-images.githubusercontent.com/1567309/162441071-39dc741e-5c8a-4c23-8349-69a8766f971b.png)

How RDKIt Displays it:

<img src="https://user-images.githubusercontent.com/1567309/162441473-b279b56e-b911-4a94-b1ee-ef83b85760e6.png" width=15% height=15%>

If we look at the actual molfile and how RDKIt draws the bonds, RDKit clearly ignores the molfile specification about bond type (wedges) while ChemDraw and Co. do it correctly.

**To Reproduce**

In Jupyter notebook with molblock = above molfile:

```
m = Chem.MolFromMolBlock(molblock)
m
```

**Expected behavior**

I expect it to look the same as in ChemDraw in regards to Stereochemistry and H-atom positions.

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.01 (and 2021.03.05)
 - OS: Win 10
 - Python version (if relevant): 3.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
@kienerj There are two things going on here:
1. By default the RDKit removes hydrogens when you read the molecule in. If you want to preserve the original H positions you can turn this off by passing `removeHs=False` to `MolFromMolBlock()`.
2. The RDKit chooses its own bond wedging when you write the molecules out. This is non-trivial to disable, but it's generally correct.

If I read your molecule in with `removeHs=False`, I get the following wedging:
![image](https://user-images.githubusercontent.com/540511/162603087-58da48eb-de13-49c1-86a4-af9304bd91db.png)

In your case the drawing has a couple of problems.
The wedging around atom 2 is contradictory. This case is explicitly called out in the IUPAC guidelines for drawing stereochemistry:
![image](https://user-images.githubusercontent.com/540511/162603053-69d5d80b-16d1-42a7-b032-99507b10c892.png)

The wedged bonds from oxygen 3 should not be there (and they're actually wrong). Wedged bonds are only supposed to be used to indicate stereochemistry, not to make the drawing "feel" 3D. The RDKit ignores those on input since that O isn't a chiral center, so this doesn't actually cause problems.

**Comment by kienerj** [comment]
Thanks Greg. I forwarded your reply to the reporting chemists. 

In regards to point 2, a mode "You get what you input" even if wrong could sometimes be a good option potentially with a warning. I'm not sure why it was drawn that way but it seems to be common upon agreed way (this is a molecule from the 60ties). From what I can tell it was even wrong in the original patent which matches what I posted except that H18 is missing and C15 is wedged down but the wedges to O3, O6, C10 are in the patent.

**Comment by kienerj** [comment]
> In your case the drawing has a couple of problems. The wedging around atom 2 is contradictory. This case is explicitly called out in the IUPAC guidelines for drawing stereochemistry: ![image](https://user-images.githubusercontent.com/540511/162603053-69d5d80b-16d1-42a7-b032-99507b10c892.png)
> 
> The wedged bonds from oxygen 3 should not be there (and they're actually wrong). Wedged bonds are only supposed to be used to indicate stereochemistry, not to make the drawing "feel" 3D. The RDKit ignores those on input since that O isn't a chiral center, so this doesn't actually cause problems.

@greglandrum Related to this I was wondering if there is a way to check a molecule if these rules are broken?  Or would the only way be to somehow compare  the input vs output from rdkit?
