### ISSUE TITLE
Rings containing all dummy atoms with single bonds are flagged as aromatic

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#518]
Reported by Peter Shenkin:
```python
In [30]: Chem.CanonSmiles('*-1-*-*-*-1')
Out[30]: '[*]1:[*]:[*]:[*]:1'
```

**Comment by greglandrum** [comment]
For the fix, I am going to remove the assignment of aromaticity to rings that are purely composed of dummies.

**Comment by bp-kelley** [comment]
What if the bonds are explicit?

```
Chem.CanonSmiles("*1:*:*:*:*:*:*1")
'[*]1:[*]:[*]:[*]:[*]:[*]:[*]:1'
```

Does this just affect "-" and "" bonds?

**Comment by greglandrum** [comment]
The fix no longer assigns aromaticity to the purely dummy case at all. It doesn't matter if the original bonds are specified as aromatic:
```python
In [4]: Chem.CanonSmiles('*:1:*:*:*:*:*:1')
Out[4]: '[*]1=[*][*]=[*][*]=[*]1'

In [5]: Chem.CanonSmiles('*:1:*:*:*:*:1')
Out[5]: '[*]1[*]=[*][*]=[*]1'

In [6]: Chem.CanonSmiles('*:1:*:*:*:1')
Out[6]: '[*]1=[*][*]=[*]1'

In [7]: Chem.CanonSmiles('*:1:*:*:*:*:*:*:1')
Out[7]: '[*]1[*]=[*][*]=[*][*]=[*]1'

In [8]: Chem.CanonSmiles('*:1:*:*:*:c:1')
Out[8]: '[*]1:[*]:[*]c[*]:1'
```

My original version just removed aromaticity if all the atoms were dummies *and* all the bonds where single, but I moved to simply "all atoms are dummies" because that seemed somehow less arbitrary (though both are clearly arbitrary).

**Comment by bp-kelley** [comment]
I see, I'm guessing there just isn't enough information to kekulize here, but I think I would have approached the issue by making these have the same meaning as the smarts version just for consistency.

**Comment by greglandrum** [comment]
I'm not sure what you mean. The SMARTS version is a different beast: the atoms (and bonds) are queries and molecules built from SMARTS are not normally fully sanitized, so this kind of thing is never applied to them.

**Comment by bp-kelley** [comment]
I think my mental model is stuck in separating aromaticity from bond order.  I tend to think that the input is not arbitrary and that bonds between dummy atoms shouldn't be altered:

```
m = Chem.MolFromSmiles("c1ccccc1")
 0 bondtype: 1 aromatic: true     
 1 bondtype: 2 aromatic: true     
 2 bondtype: 1 aromatic: true     
 3 bondtype: 2 aromatic: true     
 4 bondtype: 1 aromatic: true     
 5 bondtype: 2 aromatic: true     
```

now with dummies

```
m = Chem.MolFromSmiles("*1*****1")
 0 order: 1 aromatic: false     
 1 order: 1 aromatic: false    
 2 order: 1 aromatic: false    
 3 order: 1 aromatic: false    
 4 order: 1 aromatic: false    
 5 order: 1 aromatic: false    
```

now with aromatic bonds specified

```
m = Chem.MolFromSmiles("*1:*:*:*:*:*:1")
 0 order: 1 aromatic: true     
 1 order: 1 aromatic: true    
 2 order: 1 aromatic: true    
 3 order: 1 aromatic: true    
 4 order: 1 aromatic: true    
 5 order: 1 aromatic: true    
```
and as a result:

```
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles("*1:*:*:*:*:*:1")
>>> arom = Chem.MolFromSmiles("c1ccccc1")
>>> arom.HasSubstructMatch(m)
True
```

However it appears that "*" in Smiles translates to "R" in the mol block which doesn't act as a dummy atom when used as a query.  I'm beginning to lean to "it doesn't matter" but I think there is some consistency to be had and I don't think that the parsing is ambiguous at least.

**Comment by greglandrum** [comment]
I halfway agree, but given that there is a sanitization step in there where the molecule is kekulized and aromaticity is assigned and that dummies in SMILES aren't really queries anyway, I think we're ok with this behavior, so long as it's documented somewhere (which I still have to do). If it turns out to make giant problems at some point, we can always switch back to the "all dummies and all single bonds" case, but there are some subtleties there.

Oh, and "aromatic" is, still, a bond order in the RDKit's eyes. :-)

**Comment by bp-kelley** [comment]
Done.  And I'll try and unstick my brain from order != aromatic, but it may take a while.
