### ISSUE TITLE
Thread sanitizer not happy with PR #4680

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#5206]
I have been playing with sanitizers lately, and the thread sanitizer does not seem happy about the removal of the InChi mutex in PR #4680. [tsan_testOInchi_log.txt](https://github.com/rdkit/rdkit/files/8500697/tsan_testOInchi_log.txt) is the log of running `ctest -V -R testInchi` after building current master with InChi 1.06

Reverting the changes to `External/INCHI-API/inchi.cpp` in PR #4680 makes the InChi code data races go away, although the other detections are still happening. I'm still trying to figure those out.

**Comment by greglandrum** [comment]
oh, lovely. Now we have to decide if we want to revert those changes. Given that it hasn't come up as a problem yet I guess maybe not?

We should also report this to the InChI folks.
