### ISSUE TITLE
PeriodicTable initialization is not thread safe

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#5207]
More revelations thanks to the thread sanitizer:

Currently, we initialize the `PeriodicTable` like this:
https://github.com/rdkit/rdkit/blob/66476f01c014b4f0b81b2ff9851120227a5d548b/Code/GraphMol/PeriodicTable.cpp#L106-L116

but... that macro name is not correct: we do, in fact, use this one!!!:
https://github.com/rdkit/rdkit/blob/66476f01c014b4f0b81b2ff9851120227a5d548b/CMakeLists.txt#L399

Patch coming up soon.

**Comment by greglandrum** [comment]
I'm not 100% sure that this has any actual effect on code (i.e. that it's a bug).

`RDConfig.h.cmake` file has:
```
#cmakedefine RDK_BUILD_THREADSAFE_SSS
#ifdef RDK_BUILD_THREADSAFE_SSS
#define RDK_THREADSAFE_SSS
#endif
```
which ends up looking like this in `RDConfig.h`:
```
#define RDK_BUILD_THREADSAFE_SSS
#ifdef RDK_BUILD_THREADSAFE_SSS
#define RDK_THREADSAFE_SSS
#endif
```

So `#ifdef RDK_BUILD_THREADSAFE_SSS` or `#ifdef RDK_THREADSAFE_SSS` should end up being equivalent.

**Comment by ricrogz** [comment]
That's right, but it seems RDConfig.h does not get included into `PeriodicTable.h`. In fact, I don't see it included anywhere...

**Comment by greglandrum** [comment]
> That's right, but it seems RDConfig.h does not get included into `PeriodicTable.h`. In fact, I don't see it included anywhere...

Of course you're right; Ihad confused myself since that file is for use in external code.
sorry.

**Comment by ricrogz** [comment]
No problem at all :)
