### ISSUE TITLE
GarethUtil::RandomUtil is not thread safe

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#5216]
`GarethUtil::RandomUtil` is being used from multithreaded contexts, and the thread sanitizer is reporting a data race (sample log here: [tsan_testMultithreadedMolSupplier_log.txt](https://github.com/rdkit/rdkit/files/8501835/tsan_testMultithreadedMolSupplier_log.txt)). I think the problem is that different threads might be clashing while updating the internal state of the `std::mt19937 rng;` object at the same time.

I think we'd have to either:
1- Make `rng` `thread_local`, so that each thread uses its own engine.
2- Add a common mutex to all methods of the class, so that we can avoid clashes by allowing only one thread at a time to interact with the `rng`object.

I think 2 might be a better solution, since 1 implies we'd have to seed each generator independently, which might be a bit of a hassle.

**Comment by bp-kelley** [comment]
If there’s a data race though you won’t have deterministic random numbers, even with a mutex.  This is probably ok, but can be a pain for testing.
