### ISSUE TITLE
Core with query atoms and no user definded attachment points may create poor decompostions

### ISSUE THREAD

**Issue by jones-gareth** [rdkit/rdkit#5222]
**Describe the bug**
The tie breaking algorithm used in RGD can result in poor decompositions when the core has query features.

When the core is this:

![image](https://user-images.githubusercontent.com/24233741/164304524-3cd11e32-80bf-468e-bd27-8031bc545af3.png)

And we decompose these guys:
![image](https://user-images.githubusercontent.com/24233741/164304641-a7591015-764c-4a03-a280-3244d1b236e9.png)

The decomposition of the Pyrimidine is wrong:

![image](https://user-images.githubusercontent.com/24233741/164304930-1f6785f7-5d83-4f3b-bb40-236d9f744dc2.png)
 
**To Reproduce**
```python
#%%

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem.rdRGroupDecomposition import (RGroupDecomposition,
                                              RGroupDecompositionParameters,
                                              RGroupMatching, RGroupScore)

IPythonConsole.ipython_useSVG = True

import pandas as pd
from IPython.display import HTML
from rdkit.Chem import Draw, PandasTools

#%%

smi = ['COc1ccccc1']*10
smi.append('COc1ccncn1')
mols = [Chem.MolFromSmiles(smiles) for smiles in smi]
Draw.MolsToImage(mols)

#%%
block="""
  ChemDraw04112214222D

  6  6  3  0  0  0  0  0  0  0999 V2000
   -0.7145    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -0.4125    0.0000 L   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -0.4125    0.0000 L   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.8250    0.0000 L   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0      
  2  3  1  0      
  3  4  2  0      
  4  5  1  0      
  5  6  2  0      
  6  1  1  0      
  2 F    2   6   7
  4 F    2   6   7
  6 F    2   6   7
M  ALS   2  2 F C   N   
M  ALS   4  2 F C   N   
M  ALS   6  2 F C   N   
M  END
"""
core = Chem.MolFromMolBlock(block)
core
#%%

def do_decomp(groups):
    options = RGroupDecompositionParameters()
    options.matchingStrategy = RGroupMatching.GreedyChunks
    group_decomp = RGroupDecomposition([core], options)
    for mol in groups:
        group_decomp.Add(mol) 
    group_decomp.Process()
    cols = group_decomp.GetRGroupsAsColumns()
    df = pd.DataFrame(cols)
    PandasTools.ChangeMoleculeRendering(df)
    return df

#%%
df = do_decomp(mols)
HTML(df.to_html())

```

**Expected behavior**
I expect to see all methoxy groups in R1

**Configuration (please complete the following information):**
RDKit master on Ubuntu 20.04

**Additional context**

This issue arises because of the tie-breaking code.  For unindexed (not user defined) R group positions the tie breaking code will push heavy groups onto the lowest index.  For the compounds with the benzene ring that is -6.  After adding a few compounds the greedy chunks matcher will call the tie breaker and put all the methoxy groups on -6. The problem is that the pyrimidine core that matches the final compound has only 5 attachment points and doesn't have a -6 index.

I have a fix for the tie breaking code and should have a PR soon.  The fix is easy, but unfortunately breaks a number of tests.

This issue is somewhat related to issue #4505.  At least if we could solve #4505 for unindexed and user rgroups this issue would not arise.  I'm just not sure how to fix #4505.

**Comment by bp-kelley** [comment]
That's a pretty elegant fix for the greedy matcher.
