### ISSUE TITLE
TransformMol does not consider numpy.ndarray flags?

### ISSUE THREAD

**Issue by fredludlow** [rdkit/rdkit#5225]
Hi there,

I'm using `rdkit.Chem.AllChem.TransformMol` from python. This takes a molecule and a numpy array. For various reasons, I'm getting a matrix (from other code) that needs transposing before it's passed to this function, but this generates "unexpected" results.

I think what's happening is that, for a simple array, calling ndarray.T just creates a view on the original with the C_CONTIGUOUS and F_CONTIGUOUS flags swapped. I think at some point between the python and C++ code, the underlying array gets read assuming it's a 4x4 C-ordered array.

The simplest demonstration is to take a e.g. a rotation around Z with a transform of 10 (`M` in the code below) - I would expect transforming by `M` and `M.T` to produce different final coordinates, but they don't.  (Aside: I think that the way rdkit parses the array, M.T does not actually represent the inverse of M, but that's not the problem).

Given some 3D input file (e.g. ATP from RCSB: https://files.rcsb.org/ligands/view/ATP_ideal.sdf)

```python
from rdkit.Chem import MolFromMolFile
from rdkit.Chem.AllChem import TransformMol
import numpy as np
mol = MolFromMolFile("ATP_ideal.sdf")

M = np.array([[0., 1., 0., 10.], [-1., 0., 0., 10.0], [0., 0., 1., 10.0], [0., 0., 0., 1.,]])

print("Original position of first atom:")
print(mol.GetConformer().GetPositions()[0])

print("Transform by M:")
TransformMol(mol, M)
print(mol.GetConformer().GetPositions()[0])

print("Reload and transform by M.T - Would expect a different answer, even if this isn't actually a sensible thing to do")
mol = MolFromMolFile("ATP_ideal.sdf")
TransformMol(mol, M.T)
print(mol.GetConformer().GetPositions()[0])

print("array flags for M:")
print(M.flags)

print("array flags for M.T:")
print(M.T.flags)

```

My output looks like:
```
Original position of first atom:
[ 1.2   -0.226 -6.85 ]
Transform by M:
[9.774 8.8   3.15 ]
Reload and transform by M.T:
[9.774 8.8   3.15 ]
array flags for M:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

array flags for M.T:
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

```

A workaround for now is to force C-ordering in the transposed matrix, there may be a neater way but this works:

```python
M_transposed = np.zeros((4,4), dtype=float)        # C-ordered by default
np.copyto(M_transposed, M.T)                       # Still C-ordered
```

 - RDKit version: 2021.03.05  (  - rdkit=2021.03.5=py37h13c2175_0
 - OS: CentOS7
 - Python version (if relevant): 3.7.12
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by ptosco** [comment]
@fredludlow 
As you mention, the numpy documentation for [ndarray.transpose()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.transpose.html#numpy.ndarray.transpose) states that it only returns a different view on the underlying data, while the underlying data is unchanged.
RDKit's `transConformer` Python wrapper RDKit uses the underlying array data to compute the transformation; as this is unchanged, it will yield the same transformation.
Until this is is fixed in RDKit, a neater way to get the desired transformation is to force a copy of the array:
```
TransformMol(mol_copy, np.ndarray.copy(M.T))
```

**Comment by fredludlow** [comment]
Indeed, there are various ways to copy an array and the re-ordering behaviour differs:

The method on ndarray (as per your example or equivalently `(M.T).copy()`) defaults to C ordering, whereas `np.copy(M.T)`, which I'd tried first, defaults to `order='K'`, which means match original.

I got caught out as my immediate thought was "oh, this is a memory order thing" and then took me a lot longer to actually open the [docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy) and read that `np.copy` preserves memory layout by default. 🤦‍♂️
