### ISSUE TITLE
Match stereo information in the reactants for reaction.RunReactants

### ISSUE THREAD

**Issue by cottonkiet** [rdkit/rdkit#5226]
### Discussed in https://github.com/rdkit/rdkit/discussions/4096

<div type='discussions-op-text'>

<sup>Originally posted by **shuan4638** April 30, 2021</sup>

I tried to run the reaction to transform only cis double also to preserve the stereo chemistry. 

```
from rdkit import Chem
from rdkit.Chem import rdChemReactions
reactant1 = Chem.MolFromSmiles('CCOC(=O)/C=C\I')
reactant2 = Chem.MolFromSmiles('O=Cc1ccc2nc(-c3cccs3)oc2c1')
template = 'I\[C;H1;+0:1]=[C;H1:4]/[*:5].[C;H1;+0:2]=[O;H0;+0:3]>>[*:5]/[C:4]=[C;H1;+0:1]\[C;H1;+0:2]-[O;H1;+0:3]'
reaction = rdChemReactions.ReactionFromSmarts(template)
reactants = reaction.RunReactants([reactant1, reactant2])
print (Chem.MolToSmiles(reactants[0][0]))
```

**This is want I want**
For example
if the reactant is
`reactant1 = Chem.MolFromSmiles('CCOC(=O)/C=C/I')`
the reaction does not pass
if the reactant is
`reactant1 = Chem.MolFromSmiles('CCOC(=O)/C=C\I')`
the output is
`CCOC(=O)\C=C/C(O)c1ccc2nc(oc2c1)-c1cccs1`
if the reactant is
`reactant1 = Chem.MolFromSmiles('I\C=C\C(=O)OCCCCOC(=O)\C=C/I')` (two double bonds but only one cis)
the output is
`OC(\C=C/C(=O)OCCCCOC(=O)\C=C\I)c1ccc2nc(oc2c1)-c1cccs1` (not two products here)

However, **what I get** is that both cis/trans bonds in the reactant will be converted to cis bond.

**Comment by wopozka** [comment]
@cottonkiet 
But what problem is here. You want the reaction to occour only on cis double bond and it is exactly what you get.

**Comment by wopozka** [comment]
@cottonkiet 
AFAIK (if I am wrong please anybody correct me) it is the design. It is the way it works. Stereo reaction definitions (regardles if it is chirality of ZE isomerism) defines what to do in the reaction, not necesary if there should be a match in the reaction.  In general, as much as I am aware, there is no chiral match in the reaction, therefore in reality any configuration will match. In this case rdkit logic is: 
1) there is double bond match, ZE configuration does not match query, so invert it in the products
2) there is double bond match, ZE configuration matches query, leave configuration unchanged.
As fair as I am aware the same logic applies to chirality. To check whether the reaction should  or shoudn't work is unfortunatelly your responsibility. In general you need to check which atoms were used for the reaction, get  reactant template and check with useChirality=True, whether it matches the same atoms. If it does, it means the reaction is what you want, if not, then it means you need to reject the reaction. One of the possible solution of your problem might be rdchiral (https://github.com/connorcoley/rdchiral) but I've never used it.

**Comment by cottonkiet** [comment]
Thanks a lot! the rdchiral is a good resource!
