### ISSUE TITLE
Rdkit minimal js v2022.3.2 caused webAssembly error in Safari

### ISSUE THREAD

**Issue by SeongsangCHO** [rdkit/rdkit#5236]
**Describe the bug**

I just loaded through `script tag` like this
```nextjs
<Script  src="https://unpkg.com/@rdkit/rdkit/Code/MinimalLib/dist/RDKit_minimal.js"
/>
```
But In safari caused web assembly error. (In chrome it worked well)
So, I changed rdkit version `2022.3.2` to `2021.9.1` it was solved.
```nextjs
<Script  src="https://unpkg.com/@rdkit/rdkit@2021.9.1/Code/MinimalLib/dist/RDKit_minimal.js"
/>
```
I don't know what is cause of error yet.

<img width="954" alt="screen" src="https://user-images.githubusercontent.com/93111601/165266120-ee69f5b9-67a4-46c8-ad4b-f566f2dc18b0.png">

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2022.3.2
 - OS: Mac os
 - I used rdkit minimal js

**Comment by MichelML** [comment]
@SeongsangCHO I tried rdkitjs.com and react.rdkitjs.com on the latest version of Mac OS and Safari and everything seems to work.

What version of Safari and Mac OS are you using?

![image](https://user-images.githubusercontent.com/9539763/165318243-7b77a30e-6e3b-4ee6-83d6-ada810d7167a.png)

![image](https://user-images.githubusercontent.com/9539763/165318647-1603e497-8344-4d97-bbe0-7d3417ce3adb.png)

![image](https://user-images.githubusercontent.com/9539763/165318895-89350957-9469-4c9c-ad52-6860fdb0c501.png)

cc @ptosco

**Comment by SeongsangCHO** [comment]
MacOS: Big sur 11.6
Safari : 14.1.2


My test env is nextjs.
This is my codes.

```jsx
import type { AppProps } from "next/app";
import Script from "next/script";
import { useEffect, useState } from "react";

function MyApp({ Component, pageProps }: AppProps) {
  const [isLoad, setIsLoad] = useState(false);
  useEffect(() => {
    if (window !== undefined && isLoad)
      window.initRDKitModule().then((RDKit: any) => {
        console.log(RDKit);
      });
  }, [isLoad]);
  return (
    <>
      <Script
        src="https://unpkg.com/@rdkit/rdkit/Code/MinimalLib/dist/RDKit_minimal.js"
//        src="https://unpkg.com/@rdkit/rdkit@2021.9.1/Code/MinimalLib/dist/RDKit_minimal.js" -> its worked

        onLoad={() => setIsLoad(true)}
      ></Script>

      <Component {...pageProps} />
    </>
  );

export default MyApp;

```

**Comment by MichelML** [comment]
@SeongsangCHO I'll drop a few more thoughts tomorrow, but by curiosity, did you try to set 2022.3.2 explicitly too and it didn't work as well?

**Comment by SeongsangCHO** [comment]
Yes It was same.
I tried `https://unpkg.com/@rdkit/rdkit@2022.3.2/Code/MinimalLib/dist/RDKit_minimal.js`.
