### ISSUE TITLE
Thread unsafety when MolToSmiles is called on the same molecule in different threads

### ISSUE THREAD

**Issue by bddap** [rdkit/rdkit#5245]
Calling MolToSmiles on the same molecule concurrently from multiple threads can result in undefined behavior.

For me, that ub usually manifests as a process exit with `signal: 6, SIGABRT` but behavior can vary.

**To Reproduce**
I'm happy to write a test to trigger this. I just need to know where rdkit keeps its unit tests.

**Expected behavior**
- Calling MolToSmiles never segfaults, or
- the issue is mentioned in [the book](https://github.com/rdkit/rdkit/blob/ca75365c34b0db1f4c65cc31cf489e0d8171575c/Docs/Book/RDKit_Book.rst#known-problems).

**Configuration:**
 - RDKit version: a recent clone of the master branch
 - OS: Ubuntu 20.04

**Additional context**
The issue won't be replicable using python due to GIL or boost.

Before you ask, yes, I'm handling lifetimes correctly. I'm not letting the destructor for `ROMol` get called prematurely. :)

**Comment by bp-kelley** [comment]
Calling moltosmiles actually changes the molecule.  You’ll note that moltosmiles api takes a non-const ROMol and while MolToSmiles can be called safely in threads, the ROMol itself cannot.  To fix this, you’ll need to have a copy of the ROMol in each thread.

For sure, this behavior should probably be better documented.

The same is true, by the way, when using query molecules.

Cheers,
   Brian

**Comment by greglandrum** [comment]
`MolToSmiles()` actually does take a const ROMol as an argument, so it's reasonable to expect that it would be safe to call it on the same molecule from multiple threads. 
The only changes it makes to the molecule is to set the `_smilesAtomOutputOrder` and `_smilesBondOutputOrder` properties (the API allows changing properties on const objects), so I would guess that this is where the problem arises.
It's worth taking a look at whether or not we can fix this without completely destroying the performance the code.

**Comment by bp-kelley** [comment]
Yep, I was wrong about the exposed api.

It looks like the same is true for the substructure matching api which I recall to be hard to fix as well.

**Comment by greglandrum** [comment]
I'm pretty sure that the substructure matching code is thread safe (and we do test that).
Recursive queries do require modification to the underlying query atoms, but the SSS code uses mutexes to allow that to be done in a thread-safe manner.

**Comment by bp-kelley** [comment]
Yes, I think I was remembering an issue in the substructlibrary codebase since it potentially needed to add rings which is an edge case.
