### ISSUE TITLE
Conformer Generation (ETKDGv3) takes very long time and fails to generate conformers for some molecules

### ISSUE THREAD

**Issue by jp-um** [rdkit/rdkit#5250]
**Describe the bug**
I am generating conformers for the DUDE dataset. For some molecules, the conformer generation process takes a long time and then fails to generate a conformer model.  

I have reproducible examples of this (see below), but one thing I noticed is that sometimes conformer generation for a molecule fails and if I rerun it a second time it works.  I don't understand this as I fix the random seed and this should be deterministic ...  I have examples of these molecules too in my supplied file.

**To Reproduce**
I am attaching a Python program and SMILES files which reproduce this issue (had to rename everything to .txt due to a GitHub limitation).
[conf_gen_issues.py.txt](https://github.com/rdkit/rdkit/files/8596658/conf_gen_issues.py.txt)
[conf_gen_issues.smi.txt](https://github.com/rdkit/rdkit/files/8677126/conf_gen_issues.smi.txt)
[jp_env.yml.txt](https://github.com/rdkit/rdkit/files/8596660/jp_env.yml.txt)

**Expected behavior**
A conformer model is generated for these molecules in a reasonable time.

**Screenshots**
```
CN(CCCNC(=O)CCCC[C@H]1SC[C@H]2NC(=O)N[C@@H]21)CC(F)(F)F, C67164491
requesting 200 conformers ...
confs generated: 0
Traceback (most recent call last):
  File "/data/issues/./conf_gen_issues.py", line 61, in <module>
    c = generate_conformers_from_smiles(smiles, name)
  File "/data/issues/./conf_gen_issues.py", line 50, in generate_conformers_from_smiles
    raise ValueError(f"no conformers generated for molecule {name}")        
ValueError: no conformers generated for molecule C67164491
Cc1ccc2nc(CNC(=O)CCCC[C@H]3SC[C@H]4NC(=O)N[C@@H]43)cn2c1, C67233953
requesting 50 conformers ...
confs generated: 0
Traceback (most recent call last):
  File "/data/issues/./conf_gen_issues.py", line 64, in <module>
    c = generate_conformers_from_smiles(smiles, name)
  File "/data/issues/./conf_gen_issues.py", line 50, in generate_conformers_from_smiles
    raise ValueError(f"no conformers generated for molecule {name}")        
ValueError: no conformers generated for molecule C67233953
CS(=O)(=O)SCCN(CCSS(C)(=O)=O)C(=O)CCCC[C@@H]1SC[C@@H]2NC(=O)N[C@@H]12, C44699333
requesting 300 conformers ...
confs generated: 0
Traceback (most recent call last):
  File "/data/issues/./conf_gen_issues.py", line 64, in <module>
    c = generate_conformers_from_smiles(smiles, name)
  File "/data/issues/./conf_gen_issues.py", line 50, in generate_conformers_from_smiles
    raise ValueError(f"no conformers generated for molecule {name}")        
ValueError: no conformers generated for molecule C44699333
[rest is snipped for brevity]
```

**Configuration (please complete the following information):**
 - Ubuntu 20.04 with attached conda environment (jp_env.yml)
 - RDKit 2022.03.1

**Comment by jp-um** [comment]
I have another few hundred examples of molecules which fail (could they all be failing in the same way?).  I am attaching the SMILES file. You need to change the filename in the python program supplied earlier but otherwise will fail in the same way.

[conf_gen_issues_2ndbatch.smi.txt](https://github.com/rdkit/rdkit/files/8989842/conf_gen_issues_2ndbatch.smi.txt) * 

(Really taking an opportunity to bump this up!)

Thanks

_* Thankfully supplied by Tristan C._

**Comment by greglandrum** [comment]
Thanks JP

**Comment by greglandrum** [comment]
I've looked at a few of these structures and what they have in common is a fused ring system with an impossible stereochemistry arrangement. Here's the first molecule from that file:
![m1](https://user-images.githubusercontent.com/540511/180695714-a61bace0-97b8-4fe6-a548-27559d069145.png)
notice the two bridghead chiral centers with opposite stereochemistry. This is an impossible geometry.

Here's what happens if I try to embed that:
```
In [27]: mc = Chem.AddHs(Chem.MolFromSmiles("CN1[C@H]2CC[C@H](Cc3cccc(N)c3)[C@H]1CC2"))

In [28]: ps = rdDistGeom.ETKDGv3()

In [29]: t1 = time.time()
    ...: cid = rdDistGeom.EmbedMolecule(mc, ps)
    ...: t2 = time.time()
    ...: print(f"{t2-t1:.2f} {cid}")
6.86 -1
```
It doesn't work (as you've observed).

If I invert one of the bridgehead chiral centers everything is fine:
```
In [24]: mc = Chem.AddHs(Chem.MolFromSmiles("CN1[C@@H]2CC[C@H](Cc3cccc(N)c3)[C@H]1CC2"))

In [25]: t1 = time.time()
    ...: cid = rdDistGeom.EmbedMolecule(mc, ps)
    ...: t2 = time.time()
    ...: print(f"{t2-t1:.2f} {cid}")
0.06 0
```
Another option is to tell the conformer generation code that it doesn't need to enforce the chirality of the input structure:
```
In [30]: ps.enforceChirality = False

In [31]: mc = Chem.AddHs(Chem.MolFromSmiles("CN1[C@H]2CC[C@H](Cc3cccc(N)c3)[C@H]1CC2"))

In [32]: t1 = time.time()
    ...: cid = rdDistGeom.EmbedMolecule(mc, ps)
    ...: t2 = time.time()
    ...: print(f"{t2-t1:.2f} {cid}")
0.04 0
```
(but this, of course, will generate random stereoisomers).

This is something I've looked at before, but I haven't managed to come up with a good heuristic to identify systems with impossible chirality so that we could avoid this problem. Any suggestions would be very welcome. :-)
