### ISSUE TITLE
Scaffold Generated wihtout any strucure and SMILES notation

### ISSUE THREAD

**Issue by Crispae** [rdkit/rdkit#5257]
### Discussed in https://github.com/rdkit/rdkit/discussions/5256

<div type='discussions-op-text'>

<sup>Originally posted by **Crispae** May  2, 2022</sup>
I have implemented **MurckoScaffoldSmilesFromSmiles** on the database to get a common scaffold present between them. Certain molecules have been grouped together with SMILES notation "". while others are giving legitimate scaffold structure. Empty SMILES notation does not define anything is it a bug or an implementation error?

code:
from rdkit.Chem.Scaffolds.MurckoScaffold import MurckoScaffoldSmilesFromSmiles
data["framework"] = data.Structure.apply(MurckoScaffoldSmilesFromSmiles)
![Capture](https://user-images.githubusercontent.com/74324530/166256576-cad56143-0f14-4672-8a61-3fbd9c0ba560.PNG)

</div>

**Comment by greglandrum** [comment]
Let's leave this as a discussion until we're sure it's a bug
