### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Emirali007** [rdkit/rdkit#5278]
-----------------------------------------

If you have a question about the RDKit or aren't sure if what you're seeing is the right behavior please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

Please help us help you: We normally need the information below in order to answer questions or understand bug reports. If you do not provide the information requested we may not be able to help you and will probably close the issue.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 
 - OS: [e.g. Ubuntu 20.04]
 - Python version (if relevant):
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**

smiles = file['Smiles']
chembl_id = file['ChEMBL ID']
molecules = []
for molecule in smiles: 
    moleculeX = Chem.MolFromSmiles(molecule)
    molecules.append(moleculeX)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [4], in <module>
      3 molecules = []
      4 for molecule in smiles: 
----> 5     moleculeX = Chem.MolFromSmiles(molecule)
      6     molecules.append(moleculeX)

TypeError: No registered converter was able to produce a C++ rvalue of type std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > from this Python object of type float

**Comment by Emirali007** [comment]
Help me, please!

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
