### ISSUE TITLE
Random crashes while running smiTestCatch

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#5286]
**Describe the bug**
I am getting random crashes while running `Code/GraphMol/SmilesParse/smiTestCatch`; I wonder if this has to do with this recently merged PR: #5251.

**To Reproduce**
I am running `Code/GraphMol/SmilesParse/smiTestCatch` on a 40-CPU Linux machine and getting random segfaults, double free, memory corruption, etc.
`valgrind --tool=helgrind` finds a number of threading-related issues:
```
$ /opt/rh/devtoolset-11/root/usr/bin/valgrind --tool=helgrind ./Code/GraphMol/SmilesParse/smiTestCatch
```

After reverting #5251
```
git revert 4cc4dfaf6c86a4ce640a18df82de07bbbb006d5f
```
I get a completely clean `valgrind --tool=helgrind` trace.

**Configuration (please complete the following information):**
 - RDKit version: lastest `master` branch
 - OS: CentOS 7.9.2009
 - Python version (if relevant): 3.8

**Comment by bp-kelley** [comment]
That looks suspiciously related, however with that PR the multithreaded tests I put in certainly crash so I'm confused why reverting it works.

**Comment by bp-kelley** [comment]
Are you sure it's not from the new multithreaded test itself?  There could be other issues lurking besides what the mutex is preventing.  Try reverting just the SmilesWrite mutex and I bet you'll see the same issues.

**Comment by greglandrum** [comment]
FWIW: I also noticed intermittent crashes in the new tests when running things on Linux yesterday.
There’s definitely something wrong there

**Comment by bp-kelley** [comment]
I'm 99% that this isn't the mutex, it's the test.

**Comment by greglandrum** [comment]
Given that I don’t think the mutex could cause an intermittent thing like this, i fully agree

**Comment by greglandrum** [comment]
The test is triggering some other bit of thread-unsafeness

**Comment by bp-kelley** [comment]
I think at least one of the problems is here:

```
==216296==    at 0x4F7518E: size (stl_vector.h:919)
==216296==    by 0x4F7518E: operator= (Dict.h:107)
```

We are copying properties that may be being updated at the same time.

**Comment by bp-kelley** [comment]
I think the only way to Make MolToSmiles (and RDKit in general) really thread safe is to assume that properties are really const too when the molecule is const.

**Comment by bp-kelley** [comment]
One solution I hate is to have a mutex on the molecule itself.
