### ISSUE TITLE
calling ClearDrawing() with MolDraw2DCairo raises error

### ISSUE THREAD

**Issue by alexanderrich** [rdkit/rdkit#5288]
**Describe the bug**
After creating a Draw.MolDraw2DCairo object, calling ClearDrawing() raises the following error
```
RuntimeError: Pre-condition Violation
	no draw context
	Violation occurred on line 203 in file Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
	Failed Expression: dp_cr
	RDKIT: 2022.03.2
	BOOST: 1_74
```
This creates an issue when passing a MolDraw2DCairo object to the SimilarityMaps.GetSimilarityMapForFingerprint function. See examples below.

**To Reproduce**
Minimal reproduction of error
```
from rdkit.Chem import Draw
d = Draw.MolDraw2DCairo(400, 400)
d.ClearDrawing()
```
Use case that produces error:
```
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import SimilarityMaps


atorvastatin = Chem.MolFromSmiles('O=C(O)C[C@H](O)C[C@H](O)CCn2c(c(c(c2c1ccc(F)cc1)c3ccccc3)C(=O)Nc4ccccc4)C(C)C')
rosuvastatin = Chem.MolFromSmiles('OC(=O)C[C@H](O)C[C@H](O)\C=C\c1c(C(C)C)nc(N(C)S(=O)(=O)C)nc1c2ccc(F)cc2')
d = Draw.MolDraw2DCairo(400, 400)
_, maxWeight = SimilarityMaps.GetSimilarityMapForFingerprint(atorvastatin, rosuvastatin, 
                                        lambda m, i: SimilarityMaps.GetMorganFingerprint(m, i, radius=2, fpType='bv'), 
                                        draw2d=d)
d.FinishDrawing()
```
This example worked with earlier version of the code, per this blog post: http://rdkit.blogspot.com/2020/01/similarity-maps-with-new-drawing-code.html

**Expected behavior**
calling `SimilarityMaps.GetSimilarityMapForFingerprint` with an initialized `Draw.MolDraw2DCairo` object should complete successfully.

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS:  Ubuntu 18.04
 - Python version (if relevant): Python 3.9.12
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Comment by greglandrum** [comment]
Duplicate with #5383, will be fixed in #5391
