### ISSUE TITLE
Pre-condition Violation when calling RunReactants

### ISSUE THREAD

**Issue by zacps** [rdkit/rdkit#5290]
**Describe the bug**
`RunReactants` produces molecules which break in subsequent `RunReactants` calls.
```
RuntimeError: Pre-condition Violation
	getExplicitValence() called without call to calcExplicitValence()
	Violation occurred on line 306 in file Code/GraphMol/Atom.cpp
	Failed Expression: d_explicitValence > -1
	RDKIT: 2022.03.2
	BOOST: 1_75
```

**To Reproduce**
This took a while to minimise, but this works:
```python
from rdkit.Chem.rdChemReactions import ReactionFromSmarts
from rdkit import Chem

compound = ReactionFromSmarts('[#6:1]-[#17,#35,#53]>>[#6:1][H]').RunReactants([Chem.MolFromSmiles('C(CCl)Cl')])
reaction = ReactionFromSmarts("[#1:6][#6&A&!$(C(C(=O)O)CC=,-O):1]([$([#1]),$([#6&H3]),$([#6&H2]-C(-[O&-])=O):7])([#6:2]([#1])([#1])-[#6:3])[#6:8](-[#8&-:9])=[O:10]>>[#1:6][#6:1](-[$([#1]),$([#6&H3]),$([#6&H2]-C(-[O&-])=O):7])-[#6:8](-[#8&-:9])=[O:10].[#6:3]-[#6:2](-[#8&-])=O")
reaction.RunReactants([compound][0][0])
```

I have not attempted to minimise the reaction or the compound itself, I don't really have the knowledge to do so.

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - Are you using conda? no
 - If you are not using conda: how did you install the RDKit? rdkit-pypi

**Comment by bp-kelley** [comment]
Molecules output by RunReactants aren't sanitize (this is for a few reasons) to resolve this, you need to run SanitizeMol on the molecule.  Note that this can throw an exception if the molecule is not sanitizable,

```
from rdkit.Chem.AllChem import ReactionFromSmarts
from rdkit import Chem

compound = ReactionFromSmarts('[#6:1]-[#17,#35,#53]>>[#6:1][H]').RunReactants([Chem.MolFromSmiles('C(CCl)Cl')])
reaction = ReactionFromSmarts("[#1:6][#6&A&!$(C(C(=O)O)CC=,-O):1]([$([#1]),$([#6&H3]),$([#6&H2]-C(-[O&-])=O):7])([#6:2]([#1])([#1])-[#6:3])[#6:8](-[#8&-:9])=[O:10]>>[#1:6][#6:1](-[$([#1]),$([#6&H3]),$([#6&H2]-C(-[O&-])=O):7])-[#6:8](-[#8&-:9])=[O:10].[#6:3]-[#6:2](-[#8&-])=O")

# sanitize products.
Chem.SanitizeMol(compound[0][0])
reaction.RunReactants([compound][0][0])
```

**Comment by zacps** [comment]
Thanks for the quick reply!

If a molecule isn't saniitizable does that imply the molecule is unphysical? Or is it just 'rdkit can't handle this at the moment'?

Where is the need to run `SanitizeMol` documented? It doesn't appear in the example at the top of [Chem.rdChemReactions](https://www.rdkit.org/docs/source/rdkit.Chem.rdChemReactions.html) or next to `RunReactants`.

**Comment by bp-kelley** [comment]
It is documented in the rdkit manual in the Chemical Reactions section here:

https://www.rdkit.org/docs/GettingStartedInPython.html

**Comment by zacps** [comment]
I think it would be good to document on the [Chem.rdChemReactions](https://www.rdkit.org/docs/source/rdkit.Chem.rdChemReactions.html) page as well.
