### ISSUE TITLE
findMCS function in JS library

### ISSUE THREAD

**Issue by MariaDolotova** [rdkit/rdkit#5295]
Hello! I'm from Datagrok team and I'd like to ask for findMCS function in JS Minimal lib. It is required for some tool we are now developing.
Now as I I can see the function is present only in python version of the library.
I wonder, if @ptosco could help with that?
Thank you in advance!

**Comment by ptosco** [comment]
@MariaDolotova Hi Maria, this has already been asked by others in the past (see #4191). I'll take care of that as soon as I have a bit of time.
