### ISSUE TITLE
rdMolDraw2D.PrepareMolForDrawing(None) causes segmentation fault

### ISSUE THREAD

**Issue by perjo** [rdkit/rdkit#5298]
**Describe the bug**
`rdMolDraw2D.PrepareMolForDrawing(None) `  causes segmentation fault. 

**To Reproduce**
```
def test_that_causes_crash():
    pcore = rdMolDraw2D.PrepareMolForDrawing(None)
```

**Expected behavior**
A Python exception is raised instead. 

**Configuration (please complete the following information):**
 - RDKit version: 2022.3.2.1
 - OS: macOS Monterey 12.2.1, Debian GNU/Linux 10 (buster) 
 - Python version (if relevant): 3.8
 - Are you using conda? No 
 - If you are using conda, which channel did you install the rdkit from? 
 - If you are not using conda: how did you install the RDKit? rdkit-pypi through Pip

**Comment by ptosco** [comment]
Confirmed. Thanks for reporting this!
