### ISSUE TITLE
AssignAtomChiralTagsFromStructure ignores Hydrogens

### ISSUE THREAD

**Issue by proteneer** [rdkit/rdkit#5307]
**Describe the bug**

AssignAtomChiralTagsFromStructure ignores hydrogens (present in the underlying graph and 3D coordinates). Replacement of hydrogen with a halogen results in desired behavior. If any of the attached atoms is a hydrogen, chiral perception is skipped.

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

``` python
from rdkit import Chem
from rdkit.Chem import AllChem

print("Fs")
mol_a = Chem.MolFromSmiles("C(F)(F)(F)F")
AllChem.EmbedMolecule(mol_a)
Chem.rdmolops.AssignAtomChiralTagsFromStructure(mol_a)
for atom in mol_a.GetAtoms():
    print(atom.GetSymbol(), atom.GetChiralTag())

print("Hs")
mol_a = Chem.AddHs(Chem.MolFromSmiles("C"))
AllChem.EmbedMolecule(mol_a)
Chem.rdmolops.AssignAtomChiralTagsFromStructure(mol_a)
for atom in mol_a.GetAtoms():
    print(atom.GetSymbol(), atom.GetChiralTag())

print("first H replaced with F")
for atom in mol_a.GetAtoms():
    if atom.GetIdx() == 1:
        atom.SetAtomicNum(9)
Chem.rdmolops.AssignAtomChiralTagsFromStructure(mol_a)
for atom in mol_a.GetAtoms():
    print(atom.GetSymbol(), atom.GetChiralTag())
    
print("all Hs replaced with F")
for atom in mol_a.GetAtoms():
    if atom.GetIdx() > 0:
        atom.SetAtomicNum(9)
Chem.rdmolops.AssignAtomChiralTagsFromStructure(mol_a)
for atom in mol_a.GetAtoms():
    print(atom.GetSymbol(), atom.GetChiralTag())
```

Output:

```
Fs
C CHI_TETRAHEDRAL_CW
F CHI_UNSPECIFIED
F CHI_UNSPECIFIED
F CHI_UNSPECIFIED
F CHI_UNSPECIFIED
Hs
C CHI_UNSPECIFIED
H CHI_UNSPECIFIED
H CHI_UNSPECIFIED
H CHI_UNSPECIFIED
H CHI_UNSPECIFIED
first H replaced with F
C CHI_UNSPECIFIED
F CHI_UNSPECIFIED
H CHI_UNSPECIFIED
H CHI_UNSPECIFIED
H CHI_UNSPECIFIED
all Hs replaced with F
C CHI_TETRAHEDRAL_CCW
F CHI_UNSPECIFIED
F CHI_UNSPECIFIED
F CHI_UNSPECIFIED
F CHI_UNSPECIFIED
```

**Expected behavior**
```
Hs
C CHI_UNSPECIFIED should always have a chiral tag
```

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2021.03.1
 - OS: OSX
 - Python version (if relevant): 3.7
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**

The offending line is here:

https://github.com/rdkit/rdkit/blob/ca5d470b48bf95f2cbffd290f5ac82fbd8115700/Code/GraphMol/Chirality.cpp#L2238

Which skips chiral checks if there are any hydrogens attached.

**Comment by proteneer** [comment]
Was there a particular rationale for excluding hydrogens to begin with?

**Comment by greglandrum** [comment]
> Was there a particular rationale for excluding hydrogens to begin with?

Nope. That was just an inappropriate optimization.
