### ISSUE TITLE
Runtime error when writing reaction with substance group to V3000 rxnblock

### ISSUE THREAD

**Issue by rachelnwalker** [rdkit/rdkit#5324]
**To Reproduce**

When I try to write this reaction to a v3000 rxn block:
```
from rdkit.Chem import rdChemReactions

rxn = rdChemReactions.ReactionFromSmarts("[#8]-C-C-C-C-C(-[#8])=O>>O=C-1-C-C-C-C-O-1 |Sg:n:12:n:ht,Sg:n:2:n:ht|")
v2000mb = rdChemReactions.ReactionToRxnBlock(rxn) # works fine
v3000mb = rdChemReactions.ReactionToRxnBlock(rxn, forceV3000=True) # raises RuntimeError 
```

I get this error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-2c5a5d8774ba> in <module>
      1 rxn = rdChemReactions.ReactionFromSmarts("[#8]-C-C-C-C-C(-[#8])=O>>O=C-1-C-C-C-C-O-1 |Sg:n:12:n:ht,Sg:n:2:n:ht|")
      2 v2000mb = rdChemReactions.ReactionToRxnBlock(rxn) # works fine
----> 3 v3000mb = rdChemReactions.ReactionToRxnBlock(rxn, forceV3000=True) # cannot

RuntimeError: Neither beginning nor ending atoms of bond 2 is in this SubstanceGroup.
```

**Screenshots**
Here is a screenshot of the reaction:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/39069546/169907029-1cbaa1e5-a5b8-4e78-acd5-139c93c10128.png">

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: mac
 - Are you using conda? No

**Comment by d-b-w** [comment]
It looks like there is a problem with applying substance groups in products - the exception sounds like it's trying to apply product substance groups to reactant templates.

**Comment by bp-kelley** [comment]
The issue I see is that the substance group definition is treating the reactant + product as a single molecule.

I.e. n:12

Internall, RDKit reads these as independent structures to in our case the reactant only has 7 atoms and the product only has 7 atoms so when it tries to write the substance group for the 12 atom, it doesn't exist.

We would have to redo the indices on read to support this.  I double checked that this is the supported intent from chemaxon so the current behavior is indeed a bug.

**Comment by bp-kelley** [comment]
@greglandrum I think I've narrowed it down to closures and an off by one for the cxsmiles bond index

Here is a simplified failure, removing the closure is successful
```
>>O=C-1-C-C-C-C-O-1 |Sg:n:4:n:ht|
>>O=C-C-C-C-C-O |Sg:n:4:n:ht|
```

the bond index map at line 284 in CXSmilesOps looks like:

```
bondIndexMap	std::vector<int, std::allocator<int> >	size=7	
[0]	int	0
[1]	int	-1
[2]	int	1
[3]	int	2
[4]	int	3
[5]	int	4
[6]	int	5
```

for the failure and

```
bondIndexMap	std::vector<int, std::allocator<int> >	size=6	
[0]	int	0
[1]	int	1
[2]	int	2
[3]	int	3
[4]	int	4
[5]	int	5
```
for the success.

I'll keep investigating.

**Comment by bp-kelley** [comment]
Simplified test case

```
      auto mol = "C-1-C-C-C-C-O-1 |Sg:n:4:n:ht|"_smarts;
      MolOps::findSSSR(*mol);
      auto mbk = FileParserUtils::getV3000CTAB(*mol, -1);
```

Also causes the same error.  It looks like the logic for inserting this substance group may be wrong 

Here is what is getting pushed into the substance group

```
adding atom: 4
adding bond idx: 2 (atoms 2,3)
(bond idx 2==>Neither beginning nor ending atoms of bond 2 is in this SubstanceGroup)
adding bond idx: 3 (atoms 3,4)
```

**Comment by greglandrum** [comment]
@rachelnwalker this ought to be fixed; can you please take a look?
