### ISSUE TITLE
Molzip segfaults instead of throwing an error when multiple bonds are formed to the same pairs of atoms

### ISSUE THREAD

**Issue by loluwot** [rdkit/rdkit#5334]
**Describe the bug**
Molzip segfaults instead of throwing an error when multiple bonds are formed to the same pairs of atoms when chirality is explicitly expressed for one of the atoms.

**To Reproduce**
```python
from rdkit import Chem
Chem.molzip(Chem.MolFromSmiles('C([*:1])[*:2].[C@@H](Cl)([1*:1])[2*:2]'))
```

**Expected behavior**
Expected either an error to be thrown or all but one of the bonds to be ignored (which is what usually happens when chirality is not specified).

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: [e.g. Ubuntu 20.04] Windows
 - Python version (if relevant): 3.10.4
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
N/A

**Comment by bp-kelley** [comment]
Yep that's a bug.  If should throw a runtime error or precondition.

**Comment by bp-kelley** [comment]
Thanks for the issue, it should be resolved now.
