### ISSUE TITLE
MinimalLib: Some proper SMILES won't pass as arguments to .get_qmol()

### ISSUE THREAD

**Issue by dskatov** [rdkit/rdkit#5337]
**Describe the bug**
Not sure if that's a bug or a feature.
As all SMILES are proper SMARTS templates too, it's expected that `.get_qmol()` will correctly process all equivalent transcriptions of SMILES corresponding to one molecule. However, for some such SMILES this doesn't happen.

**To Reproduce**

This will return a `{}`:
```
let molQuery = RDKitModule.get_qmol('C1(=CC=CC=C1)');
let mol = RDKitModule.get_mol('C1(=CC=CC=C1)');
let match = mol.get_substruct_match(molQuery);
console.log(match);
```

In fact, it doesn't work for `substruct_match` against pretty much any molecule.

This will return a proper match:
```
let molQuery = RDKitModule.get_qmol('c1ccccc1');
let mol = RDKitModule.get_mol('c1ccccc1');
let match = mol.get_substruct_match(molQuery);
console.log(match);
```

We used such code to check if a molecule string should not be processed with `.get_qmol()` and revert to `.get_mol()` instead.

**Expected behavior**

For both `C1(=CC=CC=C1)` and `c1ccccc1` a proper `qmol` pattern is constructed.

**Configuration (please complete the following information):**

`RDKit_minimal_2022.03_1.wasm`

**Comment by dskatov** [comment]
CC @StLeonidas

**Comment by bp-kelley** [comment]
Believe it or not, this is working as designed.  Smarts is very explicit.

C1=CC=CC=C1

Is aromatic in smiles, but not in smarts so it cannot match a benzene.

There is an option to aromatize a smarts pattern if possible but I don’t know if that is exposed to minimallib.

----
Brian Kelley
