### ISSUE TITLE
Using MolField in django application

### ISSUE THREAD

**Issue by ivannnnnnnnnn** [rdkit/rdkit#5344]
Hello! I am using rdkit in django app. The ```Compound``` model has a ```MolField```. In django, when creating custom fields using method to serialize data for the database.

Now I have lagacy method writed other programmer:
```
    def get_prep_value(self, value):
        # convert the Molecule instance to the value used by the
        # db driver
        if isinstance(value, str):
            value = self.text_to_mol(value)
        if isinstance(value, Chem.Mol):
            value = memoryview(value.ToBinary())
        if value is None:
            return None
        return Func(value, function="mol_from_pkl")
```

I have trouble with using this implementation and I fix it by change implementation to:
```
   def get_prep_value(self, value):
        # convert the Molecule instance to the value used by the
        # db driver
        if isinstance(value, str):
            value = self.text_to_mol(value)
        if isinstance(value, Chem.Mol):
            value = memoryview(value.ToBinary())
        if value is None:
            return None
        return value.ToBinary() # Changes
```
Its fix my issue but I am new with rdkit and not shour what its  correct way to serialize data to db.
Can someone answer me wich of method a more correct?

**Comment by rvianello** [comment]
it looks like the `MolField` and/or the `get_prep_value` implementations were originally taken from [django-rdkit](https://github.com/rdkit/django-rdkit/blob/master/django_rdkit/models/fields.py#L55), maybe the question would be more in scope there, but I'm afraid an answer might be not possible considering the limited information available.

if `get_prep_value` was passed a string or an instance of `Chem.Mol`, the line you modified (when reached) I think should raise an `AttributeError`.

**Comment by ivannnnnnnnnn** [comment]
> it looks like the `MolField` and/or the `get_prep_value` implementations were originally taken from [django-rdkit](https://github.com/rdkit/django-rdkit/blob/master/django_rdkit/models/fields.py#L55), maybe the question would be more in scope there, but I'm afraid an answer might be not possible considering the limited information available.
> 
> if `get_prep_value` was passed a string or an instance of `Chem.Mol`, the line you modified (when reached) I think would raise an `AttributeError`.

```text_to_mol``` method return ```Mol``` 
```
    def text_to_mol(value):
        value = str(value)
        mol = (
            Chem.MolFromSmiles(value)
            or Chem.MolFromMolBlock(value)
            or Chem.inchi.MolFromInchi(value)
        )
        if mol is None:
            raise ValidationError("Invalid input for a Mol instance")
        return mol
```

**Comment by rvianello** [comment]
yes, what I meant is that if the text input is converted to `Mol`, I think `value` should be then reassigned to `memoryview(value.ToBinary())`, that I would expect to raise an `AttributeError` if `value.ToBinary()` is called by the return statement.
but I saw you opened another ticket for django-rdkit, so I think the discussion can continue there.
