### ISSUE TITLE
Minimallib: Stereo missing in SMILES when starting with 3D molblock

### ISSUE THREAD

**Issue by leguilv** [rdkit/rdkit#5346]
**Describe the bug**
Using the JS Minimallib, when loading a CTAB having 3D coordinates and stereochemistry, if I then generate the smiles out of it, the stereochemistry information is lost in the output SMILES.

**To Reproduce**
See this js file, paste it in any box [here](https://unpkg.com/@rdkit/rdkit@2022.3.2/Code/MinimalLib/dist/GettingStartedInJS.html) and see the results in the console:
[RdkitJS Stereo Issue.js.txt](https://github.com/rdkit/rdkit/files/8813119/RdkitJS.Stereo.Issue.js.txt)

**Expected behavior**
I'd say that we need to expose the function that enables stereochemistry perception from 3D coordinates in case a mol has this 3D coordinates, or make that an option upon loading a molecule. Or maybe I've missed an option / way of doing that.

**Configuration (please complete the following information):**
 - RDKit version: 2022.3.2
 - OS: Windows10
 - If you are not using conda: how did you install the RDKit? Minimallib -> npm

**Comment by ptosco** [comment]
We do not need a new flag. This bug is a consequence of #5327, which has just been fixed.
So the problem will also be fixed in MinimalLib if you rebuild it from the latest `master` branch.
I have just tested this locally with your Java snippet and I get this:
```
[H]c1c([H])c([H])c([C@]([H])(N([H])[H])C([H])([H])C(=O)[O-])c([H])c1[H]
```

**Comment by ptosco** [comment]
I am closing this as the bug has already been fixed; feel free to reopen if needed.

**Comment by MaxDNG** [comment]
Thanks for the swift response @ptosco. We'll rebuild it internally.

**Comment by ptosco** [comment]
@leguilv A patch release was released yesterday and it includes the fix for #5327:
https://github.com/rdkit/rdkit/releases/tag/Release_2022_03_3

**Comment by leguilv** [comment]
Thanks guys !!

**Comment by leguilv** [comment]
Quick Question @greglandrum: is the NPM release coming as well ?

**Comment by greglandrum** [comment]
Those normally happen after each RDKit release, so I would assume so (I don't do the distribution updates myself)

**Comment by greglandrum** [comment]
Thanks for your continued efforts here @MichelML

**Comment by MaxDNG** [comment]
Thanks to both of you! We upgraded to the latest version and it works perfectly!
