### ISSUE TITLE
Legend for colored images drawn with `rdMolDraw2D.PrepareAndDrawMolecule`?

### ISSUE THREAD

**Issue by CapFreddy** [rdkit/rdkit#5379]
Is it supported to add legend for each color to add some customized description for each color?
![image](https://user-images.githubusercontent.com/34938020/174560493-d8b3c81c-b1ba-473c-a610-b57916470553.png)

**Comment by greglandrum** [comment]
This is not currently possible and I think the API to allow it would be quite tricky
