### ISSUE TITLE
No Python interface for passing file object to `SDMolSupplier`

### ISSUE THREAD

**Issue by spolcyn** [rdkit/rdkit#5384]
**Describe the bug**

ForwardSDMolSupplier accepts a file object or a file name, but SDMolSupplier only accepts a file name. This can make it harder to use the same code for accessing SD files, especially when the SD file may be gzipped on disk.

It appears the SDMolSupplier has an `istream` interface in the C++ code.

**To Reproduce**

Pass a file object to the SDMolSupplier

**Expected behavior**

The SDMolSupplier takes the file object as an input stream and operates on it.

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2022.3.3
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.9.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? `pip`

**Additional context**

**Comment by bp-kelley** [comment]
If the file is gzipped, you pretty much have to use a ForwardMolSupplier.  SDMolSupplier has random access to molecules which isn't generally compatible with streams, especially with compressed streams.

If you don't care about random access, you can just use a ForwardSDMolSupplier which can read from a gzip.open or open

```
>>> import gzip
>>> with open("test1.sdf", 'rb') as f:
...    print(len(list(Chem.ForwardSDMolSupplier(f))))
... 
74
>>> with gzip.open("test1b.sdf.gz", 'rb') as f:
...    print(len(list(Chem.ForwardSDMolSupplier(f))))
... 
74
```

I believe SDMolSupplier, even in c++, wouldn't work with a gzip stream.

**Comment by greglandrum** [comment]
As @bp-kelley said: SDMolSuppliers provide random access, so they need to be able to seek in the stream; this isn't possible with many istream types (like ones from gzipped files).

**Comment by spolcyn** [comment]
Good points, this all makes perfect sense -- thanks for the quick reply!
