### ISSUE TITLE
Chem.ResonanceMolSupplier freezes/hangs for CC=[N+]=[N-]

### ISSUE THREAD

**Issue by sebastianmdick** [rdkit/rdkit#5406]
**Describe the bug**
Chem.ResonanceMolSupplier hangs (enters an infinite loop?) when applied to `CC=[N+]=[N-]` 

**To Reproduce**
```python
from rdkit import Chem
mol = Chem.MolFromSmiles('CC=[N+]=[N-]')
mol = Chem.AddHs(mol)
supp = Chem.ResonanceMolSupplier(mol)
supp[0]
```
**Expected behavior**
I'm not a Chemist so I'm not sure If there should be more than one resonance structure. However from a code behavior perspective I would at least expect it to not hang and possibly throw an error. 

**Configuration (please complete the following information):**
 - RDKit version: '2022.03.1'
 - OS: macOS 11.4 and Ubuntu 20.4
 - Python version (if relevant): 3.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Comment by sebastianmdick** [comment]
Thanks!

**Comment by v8git** [comment]
@ptosco, have you had any progress?

I am using Python 3.10.4, rdkit 2022.9.1 on Windows 10 within a conda environment, but rdkit was installed using pypi.

I have the same problem for the following group of molecules:
group1 = ['C1=CC=C(C=C1)N=S=O', 'C1=CC(=CC(=C1)Cl)N=S=O', 'C1=CC(=CC=C1N=S=O)Cl', 'C1=CC(=CC=C1N=S=O)Br',
                                'C1=CC(=CC=C1N=S=O)N=S=O', 'FC(F)(F)[S](=O)(=O)c1ccc(cc1)N=[S]=O', 'Cc1ccc(cc1)N=[S]=O', 'COC1=CC=C(C=C1)N=S=O',
                                'CN(C)C1=CC=C(C=C1)N=S=O']
								
group2 = ['C1=CC=C(C=C1)C(=[OH+])O', 'CC(=[OH+])C1=CC=CC=C1', 'CC1=CC=C(C=C1)C(=[OH+])O']

While these work fine:
group1_working = 'C1=CC=C(C(=C1)N=S=O)N=S=O'
group2_working = ['C1CC[OH+]C1', 'C[OH+]C1=CC=CC=C1']

**Comment by simonmb** [comment]
@ptosco, have you had any progress?

I am using Python 3.10.4, rdkit 2022.9.1 within a conda environment, but rdkit was installed using pypi.

I have the same problem for the following group of molecules:
group1 = ['C1=CC=C(C=C1)N=S=O', 'C1=CC(=CC(=C1)Cl)N=S=O', 'C1=CC(=CC=C1N=S=O)Cl', 'C1=CC(=CC=C1N=S=O)Br',
                                'C1=CC(=CC=C1N=S=O)N=S=O', 'FC(F)(F)[S](=O)(=O)c1ccc(cc1)N=[S]=O', 'Cc1ccc(cc1)N=[S]=O', 'COC1=CC=C(C=C1)N=S=O',
                                'CN(C)C1=CC=C(C=C1)N=S=O']
								
group2 = ['C1=CC=C(C=C1)C(=[OH+])O', 'CC(=[OH+])C1=CC=CC=C1', 'CC1=CC=C(C=C1)C(=[OH+])O']

While these work fine:
group1_working = 'C1=CC=C(C(=C1)N=S=O)N=S=O'
group2_working = ['C1CC[OH+]C1', 'C[OH+]C1=CC=CC=C1']

**Comment by ptosco** [comment]
@simonmb Unfortunately I could not find any time to look into that.

**Comment by bp-kelley** [comment]
@ptosco there is an infinite loop in purgeMaps

```
bool ConjElectrons::purgeMaps(CEMap &ceMap, CEDegCount &ceDegCount,
                              CEStats &ceStats) const {
  bool ok = true;
  bool changed = true;
  while (changed) {
    for (auto it = ceMap.begin(); it != ceMap.end();) {
      if (!it->second->checkMetrics(ceStats, changed)) {
```

If ceMap.size() is 0, changed is never set to false.  I expect the code should be:

```
  while (changed) {
    changed = false;
    for (auto it = ceMap.begin(); it != ceMap.end();) {
```

**Comment by ptosco** [comment]
`checkMetrics` is supposed to be setting `changed` to `false` when appropriate. I'll try and take a look during the weekend. Really no time to look into this right now, sorry.

**Comment by bp-kelley** [comment]
checkMetrics is never called if cemap is empty though which makes me think my fix is correct.
