### ISSUE TITLE
Order dependence for rdFMCS.FindMCS with MatchFusedRingsStrict

### ISSUE THREAD

**Issue by pierred5** [rdkit/rdkit#5411]
**Describe the bug**
When trying to find the MCS between two ligands I found that my results differed depending on the order of the molecules in the list passed to FindMCS.
This problem so far has only been reproduced when the `BondCompareParameters.MatchFusedRings` and `BondCompareParameters.MatchFusedRingsStrict` parameters are set to `True`.

Also besides differing results, both results don't match the nitrogen in the conserved indole moiety which I believe is wrong.

**To Reproduce**
```
suppl = Chem.SmilesMolSupplier('mols.smi')
# mols.smi SMILES file:
# [NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1cccc2ccccc12 5g
# [NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1ccc2ccccc2n1 5m
mola = next(suppl)
molb = next(suppl)

mola_id = mola.GetProp('_Name')
molb_id = molb.GetProp('_Name')

# set FMCS parameters
params = rdFMCS.MCSParameters()
params.BondCompareParameters.MatchFusedRings = True
params.BondCompareParameters.MatchFusedRingsStrict = True

# mola , molb
fmcs_res = rdFMCS.FindMCS([mola, molb], params)
print(f"FMCS [{mola_id}, {molb_id}]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")

# molb, mola
fmcs_res = rdFMCS.FindMCS([molb, mola], params)
print(f"FMCS [{molb_id}, {mola_id}]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")
```

Output:
```
FMCS [5g, 5m]: numAtoms: 29, numBonds: 30
FMCS [5m, 5g]: numAtoms: 30, numBonds: 31
```

**Expected behavior**
I expect the MCS results to be the same and the nitrogen in the indole ring to be included in the MCS.

**Screenshots**
![5g_5m_match](https://user-images.githubusercontent.com/69871498/177876941-5bfa3d0c-8d4d-4518-a39d-e700047766a3.svg)
![5m_5g_match](https://user-images.githubusercontent.com/69871498/177876956-01e08750-af2a-4e9e-a6ea-15bc774fff4d.svg)

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - OS: macOS 12.4
 - Python version (if relevant): 3.8.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? It was part of the bundled python distribution in my Schrodinger Suite installation

**Additional context**
Full script and SMILES file I used to generate the screenshots.
mols.smi:
```
smiles name
[NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1cccc2ccccc12 5g
[NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1ccc2ccccc2n1 5m
```
python script:
```
from rdkit import Chem
from rdkit.Chem import AllChem, rdFMCS, Draw

def rdkit_FindMCS(mols, seed=''):
    params = rdFMCS.MCSParameters()
    params.InitialSeed = seed
    params.BondCompareParameters.MatchFusedRings = True
    params.BondCompareParameters.MatchFusedRingsStrict = True

    return rdFMCS.FindMCS(mols, params)


def writeFMCSPairImage(mol1, mol2, fmcs_res, filename):
    AllChem.Compute2DCoords(mol1)
    AllChem.Compute2DCoords(mol2)

    matches = [list(m.GetSubstructMatch(fmcs_res.queryMol)) for m in [mol1, mol2]]

    svg = Draw.MolsToGridImage([mol1, mol2], molsPerRow=2, subImgSize=(600,600),
                               legends=[mol1.GetProp("_Name"), mol2.GetProp("_Name")],
                               highlightAtomLists=matches, highlightBondLists=None,
                               useSVG=True)

    with open(filename, mode='w') as fn:
        fn.write(svg)


""" main() """
suppl = Chem.SmilesMolSupplier('mols.smi')
# SMILES file:
# [NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1cccc2ccccc12 5g
# [NH3+]CCCCn1c(SCCc2c[nH]c3ccccc23)nnc1-c1ccc2ccccc2n1 5m
mola = next(suppl)
molb = next(suppl)

mola_id = mola.GetProp('_Name')
molb_id = molb.GetProp('_Name')

# mola , molb
fmcs_res = rdkit_FindMCS([mola, molb])
print(f"FMCS [{mola_id}, {molb_id}]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")
writeFMCSPairImage(mola, molb, fmcs_res, f"{mola_id}_{molb_id}_match.svg")

# molb, mola
fmcs_res = rdkit_FindMCS([molb, mola])
print(f"FMCS [{molb_id}, {mola_id}]: numAtoms: {fmcs_res.numAtoms}, numBonds: {fmcs_res.numBonds}")
writeFMCSPairImage(mola, molb, fmcs_res, f"{molb_id}_{mola_id}_match.svg")
```

**Comment by ptosco** [comment]
@pierred5 Thanks for the comprehensive report. I am working on a PR that addresses multiple MCS problems, and I will make sure to include this one. Thanks again!
