### ISSUE TITLE
Incorrect molecule structure by `Chem.MolFromMolFile`

### ISSUE THREAD

**Issue by yippp** [rdkit/rdkit#5418]
**Describe the bug**
The bond in the molecule constructed by `Chem.MolFromMolFile` is not the same as in the SDF file.

**To Reproduce**
SDF file data
```
NNc1ncncn1
 OpenBabel06082209373D

 13 13  0  0  0  0  0  0  0  0999 V2000
   -2.6357    0.0567   -0.0306 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5673   -0.7752    0.3412 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2048   -0.3433    0.2474 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0945    0.9010   -0.2104 N   0  0  0  0  0  4  0  0  0  0  0  0
    1.3875    1.3028   -0.2963 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3852    0.4621    0.0751 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.0898   -0.7805    0.5325 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7967   -1.1823    0.6184 N   0  0  0  0  0  2  0  0  0  0  0  0
   -2.5791    0.9260    0.5476 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4974    0.3253   -1.0315 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7769   -1.7350    0.6954 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.6226    2.2933   -0.6609 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.8849   -1.4508    0.8286 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  9  1  0  0  0  0
  2 11  1  0  0  0  0
  3  2  1  0  0  0  0
  3  8  1  0  0  0  0
  4  3  2  0  0  0  0
  5  4  2  0  0  0  0
  5  6  1  0  0  0  0
  6  7  2  0  0  0  0
  7  8  1  0  0  0  0
  7 13  1  0  0  0  0
 10  1  1  0  0  0  0
 12  5  1  0  0  0  0
M  END
$$$$
```
Use `Chem.MolFromMolFile(file_path, sanitize=False)` or `Chem.MolFromMolBlock(open(file_path, 'r').read())` to load the molecule, Will get a warn from RDkit that `[18:09:52] Explicit valence for atom # 3 N, 4, is greater than permitted`.

The actual SMILES for this molecule is `NNc1ncncn1`, but the SMILES from RDkit is `[H]C1=NC([H])=N=C(N([H])N([H])[H])N1` (remove `[H]` is `C1=NC=N=C(NN)N1`), N atom has 4 valence, but auctually only 3.

**Expected behavior**
Expected Molecule SMILES is `NNc1ncncn1`

**Configuration (please complete the following information):**
 - RDKit version: `2022.03.3   py310hc4884e0_0    `
 - OS: Windows 10
 - Python version (if relevant): Python 3.10.4
 - Are you using conda? Yes 
 - If you are using conda, which channel did you install the rdkit from? `conda-forge`

**Comment by thegodone** [comment]
This is a normal error in RDKit. I had several Time this happening. Would be nice to have a remove backbone carbones hydrogens and keep heterogenous hydrogens in Smiles to avoid those recurrent loss of knowledge specially for N atom but not only.


Envoyé de mon iPhone

**Comment by ricrogz** [comment]
I think RDKit's representation is correct. In fact, if you import your SDF file into some other tool (e.g. https://marvinjs-demo.chemaxon.com/latest/) and export it as a SMILES string, then you will get the same or an equivalent answer to the one RDKit is giving you.

Please note that even if the title of the structure in the SDF file is "NNc1ncncn1", the structure represented in the file doesn't necessarily match the title. In your case, the Nitrogen atoms with valences 2 and 4 break the required conjugation that is required for the ring to be aromatic.

Also, note that in your call to `Chem.MolFromMolFile` you have specified `sanitize=False`, which besides skipping the valence check (not disabling it, like in your call to `Chem.MolFromMolBlock`, will cause the Nitrogen atoms with non-standard valences 2 and 4 to trigger the `Explicit valence` error you mentioned, and cause the importing to fail) also skips Hydrogen atom removal, which would make the Hydrogen atoms implicit (note that these are explicitly specified in your input file).

**Comment by greglandrum** [comment]
As @ricrogz pointed out: the RDKit is doing what it's designed to do and rejecting molecules which include chemically unreasonable valences when you include sanitization. If you turn sanitization off the molecule can be processed, but that oddly drawn ring will not be perceived as aromatic... this is also consistent with the RDKit's chemistry model.
