### ISSUE TITLE
`Chem.ResonanceMolSupplier` incorrect for methyl phosphate anion. 

### ISSUE THREAD

**Issue by sebastianmdick** [rdkit/rdkit#5429]
**Describe the bug**
`Chem.ResonanceMolSupplier` does not return correct number of resonance structures for COP(-[O-])(-[O-])(=O). Expected: 3 , Returned: 1.

**To Reproduce**
```python
from rdkit import Chem
mol = Chem.MolFromSmiles('COP(-[O-])(-[O-])(=O)')
len(Chem.ResonanceMolSupplier(mol))
>>> 1 
mol = Chem.AddHs(mol)
len(Chem.ResonanceMolSupplier(mol))
>>> 1 
```
**Expected behavior**
Expected number of resonances: 3 , Returned: 1.
https://www.bartleby.com/solution-answer/chapter-26-problem-10p-organic-chemistry-9th-edition/9781305080485/30e9f0b9-a92a-11e9-8385-02ee952b546e

**Configuration (please complete the following information):**
 - RDKit version: '2022.03.1'
 - OS: macOS 11.4 and Ubuntu 20.4
 - Python version (if relevant): 3.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Comment by ptosco** [comment]
Confirmed, thanks for reporting.
