### ISSUE TITLE
Identical scaling of compounds in grids

### ISSUE THREAD

**Issue by bjartelund** [rdkit/rdkit#543]
Hi,

I am trying to use rdkit to generate grids of my compounds for publication, however since all figures are scaled to fill the "box" the figures does not look very neat.
The OEdepict-toolkit has a nice example in listing 6, but it is not clear to me from the source code how their approach could be applied to rdkit. 
http://docs.eyesopen.com/toolkits/python/depicttk/imagegrid.html#section-image-layout-grid

I apologize if this is the wrong forum for this kind of question, but I was unable to subscribe to your mailing list (problem with sourceforge?)

**Comment by greglandrum** [comment]
The mailing list would, indeed, be a better place for this. More people pay attention to that and you're more likely to get a good answer.

There were some problems with sourceforge a few weeks ago, but they should now be resolved. Please try subscribing to the rdkit-discuss list again.
