### ISSUE TITLE
Pre-condition Violation - Failed Expression: dir == Bond::ENDUPRIGHT || dir == Bond::ENDDOWNRIGHT

### ISSUE THREAD

**Issue by bjonnh-work** [rdkit/rdkit#5433]
**Describe the bug**
Trying to open a specific molfile (with sanitize=True) raises:
```
****
Pre-condition Violation
bad dir
Violation occurred on line 382 in file /project/build/temp.linux-x86_64-cpython-310/rdkit/Code/GraphMol/Chirality.cpp
Failed Expression: dir == Bond::ENDUPRIGHT || dir == Bond::ENDDOWNRIGHT
****

``` 

**To Reproduce**
I simplified the failing molecule. This python code should trigger the error:
```python
from rdkit import Chem
mol_file = """
  SomeFailingMolFile

  8  8  0  0  1  0            999 V2000
   -0.7145    1.2375    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    0.0000    0.8250    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7145   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -1.6500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7145   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  6  0  0  0
  2  3  2  0  0  0  0
  3  4  1  4  0  0  0
  3  8  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  7  1  0  0  0  0
  7  8  2  0  0  0  0
M  END
"""

Chem.MolFromMolBlock(mol_file, sanitize=False)  # This works

Chem.MolFromMolBlock(mol_file, sanitize=True) # This doesn't
``` 

**Expected behavior**
Expecting a specific error if the molfile is invalid (which is possible), but not an un-catchable error.

**Configuration (please complete the following information):**
 - RDKit version: Master and 2022.3.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
 - OS: Ubuntu 20.04 and 22.04
 - Python version (if relevant): Not relevant, seen the bug both in c++ and Python 3.10
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Pip, but same error with c++ code using rdkit from master

**Comment by bjonnh-work** [comment]
The error in c++ code is the same:
```
terminate called after throwing an instance of 'Invar::Invariant'
  what():  bad dir
```

**Comment by greglandrum** [comment]
I can reproduce this.
The mol block is not particularly sensible, but I agree that it shouldn't be throwing an exception here.

**Comment by bjonnh-work** [comment]
Appreciate the quick fix! Thanks.
