### ISSUE TITLE
Missing ringCompare parameter in rdkit.Chem.rdFMCS.MCSParameters()

### ISSUE THREAD

**Issue by colinrsmall** [rdkit/rdkit#5438]
**Is your feature request related to a problem? Please describe.**
The rdkit.Chem.rdFMCS.MCSParameters() class is missing a parameter for specifying a ring comparison type (https://github.com/rdkit/rdkit/blob/eec737b432861610387528e36b3ddbbe31d555e4/Code/GraphMol/FMCS/Wrap/rdFMCS.cpp#L664) despite having parameters for specifying bond and atom type comparison. This means users are unable to both use a ring comparator and use the additional options that can be specified by using MCSParameters() over passing parameters directly to the rdFMCS.FindMCS() function.

**Describe the solution you'd like**
The rdkit.Chem.rdFMCS.MCSParameters() class should include a parameter "ringTyper" allowing users to specify a ring comparison type.

**Describe alternatives you've considered**
I do not know of any alternatives or workarounds to this problem.

**Additional context**
None.

**Comment by ptosco** [comment]
@colinrsmall I am closing this as there is no enhancement needed - you can already specify the same ring compare behavior using `MCSParameters`.

When you call `FindMCS` with this overload:
`FindMCS((AtomPairsParameters)mols[, (bool)maximizeBonds=True[, (float)threshold=1.0[, (int)timeout=3600[, (bool)verbose=False[, (bool)matchValences=False[, (bool)ringMatchesRingOnly=False[, (bool)completeRingsOnly=False[, (bool)matchChiralTag=False[, (AtomCompare)atomCompare=rdkit.Chem.rdFMCS.AtomCompare.CompareElements[, (BondCompare)bondCompare=rdkit.Chem.rdFMCS.BondCompare.CompareOrder[, (RingCompare)ringCompare=rdkit.Chem.rdFMCS.RingCompare.IgnoreRingFusion[, (str)seedSmarts='']]]]]]]]]]]])`

the `ringCompare` parameter can be set to one of the following values:
* `rdFMCS.RingCompare.IgnoreRingFusion`
* `rdFMCS.RingCompare.PermissiveRingFusion`
* `rdFMCS.RingCompare.StrictRingFusion`

When you call `FindMCS` with this overload:
`FindMCS( (AtomPairsParameters)mols, (MCSParameters)parameters)`

you may do the same through `MCSParameters.BondCompareParameters`:
```
# this is equivalent to ringCompare=rdFMCS.RingCompare.IgnoreRingFusion
params = rdFMCS.MCSParameters()
params.BondCompareParameters.MatchFusedRings = False
params.BondCompareParameters.MatchFusedRingsStrict = False

# this is equivalent to ringCompare=rdFMCS.RingCompare.PermissiveRingFusion
params = rdFMCS.MCSParameters()
params.BondCompareParameters.MatchFusedRings = True
params.BondCompareParameters.MatchFusedRingsStrict = False

# this is equivalent to ringCompare=rdFMCS.RingCompare.StrictRingFusion
params = rdFMCS.MCSParameters()
params.BondCompareParameters.MatchFusedRings = True
params.BondCompareParameters.MatchFusedRingsStrict = True
```
As usual, there are several examples of both use cases in the [unit tests](https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/FMCS/Wrap/testFMCS.py).

**Comment by colinrsmall** [comment]
Thanks. Didn't know Ignore/Permissive/StrictRingFusion simply uses MatchFusedRings and MatchFusedRingsStrict.
