### ISSUE TITLE
Post Condition Violation Error when trying to create list of molecules from SDF File

### ISSUE THREAD

**Issue by JLaff99** [rdkit/rdkit#5441]
**Describe the bug**
Get a Post Condition Validation saying 'Element '0 C' not found
Violation occurred on line 93 in file /Users/runner/miniforge3/conda-bld/rdkit_1654409127363/work/Code/GraphMol/PeriodicTable.h
Failed Expression: anum > -1'
When trying to create list of mol from SDF file

**To Reproduce**
suppl = Chem.SDMolSupplier('/Users/johnny/Desktop/Results/new_results_B_SD')
for mol in suppl:
    print(mol.GetNumAtoms())
(This works fine)

mols = [x for x in suppl]
(This gives the error)

**Screenshots**
<img width="1122" alt="Screenshot 2022-07-22 at 04 09 15" src="https://user-images.githubusercontent.com/93328633/180354480-72560352-ace8-483c-8aa1-96361f67b48c.png">

**Configuration (please complete the following information):**
 - RDKit version: Whatever the latest is
 - If you are using conda, which channel did you install the rdkit from? Not sure

**Comment by adenkics** [comment]
I have the same error report with you, I also tried different versions of RDkit, and I installed it from conda-forge, the code was fine on the 19th, and the error started the day before yesterday.
![image](https://user-images.githubusercontent.com/56619219/180402568-91aec493-cb29-4529-a3ff-fb8716775e7b.png)

**Comment by greglandrum** [comment]
@JLaff99 can you please share the SDF which caused this error message?

**Comment by greglandrum** [comment]
@adenkics : the error you are reporting is quite different and is likely being casued because you are have not sanitized the molecules before calling the descriptor calculator.s
