### ISSUE TITLE
Capture warning/error information in JS wrapper

### ISSUE THREAD

**Issue by raunakdoesdev** [rdkit/rdkit#5444]
In RDKit Python, we are able to view the error message resulting from trying to parse an invalid SMILES string:
```
>>> Chem.MolFromSmiles("C(c1ccccc1)N(C)(C)C")
[20:39:34] Explicit valence for atom # 7 N, 4, is greater than permitted
```

However, this information isn't present in RDKit.js. It's only a binary option of valid or invalid. Is there an easy way to view this kind of an error message?
![CleanShot 2022-07-17 at 13 41 07@2x](https://user-images.githubusercontent.com/10953031/179424041-1abdbe80-1f9f-4501-bd8a-5e127d80d6bd.png)

**Comment by greglandrum** [comment]
I'm not sure that this is possible, but it would be worth looking into.

**Comment by thegodone** [comment]
Very good idea it's similar to java normally you can track them.

Le ven. 22 juil. 2022 à 16:53, Greg Landrum ***@***.***> a
écrit :
