### ISSUE TITLE
Aromatic N in non-aromatic ring can have bad valence

### ISSUE THREAD

**Issue by hogru** [rdkit/rdkit#5455]
### Discussed in https://github.com/rdkit/rdkit/discussions/5443

<div type='discussions-op-text'>

<sup>Originally posted by **hogru** July 22, 2022</sup>
I am not a heavy user of `rdkit` so it might well be that this is a based on wrong assumptions: I generate molecules and try to assess whether a molecule is valid. If it is, I canonicalize it. The issue is, that the generated molecules are checked/validated again later in the pipeline and some of those molecules seem not to be valid (can not be canonicalized)

This is a (simplified) example source code for illustration.

```py
from rdkit import Chem

smiles = "[O-]c1ccc(C[C@H]2NC(c3ccc(Cl)cc3)=n2c2nc(-c3ccco3)cs2)cc1"
print(f"The original SMILES: {smiles}")

print("Check if this is a valid SMILES...", end="")
mol = Chem.MolFromSmiles(smiles)

if mol is None:
    print("Invalid SMILES, stop here")
else:
    print("It IS valid, canonicalize...")
    canon_smiles = Chem.CanonSmiles(smiles)
    print(f"\nCanonicalized SMILES: {canon_smiles}")  # the first n became an N

    print("\nNow, canonicalize the canonicalized SMILES again...")
    print("Expectation: works, no change in canonical SMILES; in reality: raises ArgumentError exception")
    canon_smiles = Chem.CanonSmiles(canon_smiles)  # throws an exception (could handle it, but why?)
    print(f"\nCanonicalized SMILES: {canon_smiles}")
```
</div>

**Comment by greglandrum** [comment]
The input molecule has a four-coordinate neutral N. The RDKit should generate a valence error when sanitizing it, but it's being confused by the aromatic N in the input.

**Comment by hogru** [comment]
Thank you for the quick action!!

**Comment by greglandrum** [comment]
@ptosco this one has me a bit stumped
I can come up with a way of fixing it which introduces another point in the sanitization code where an exception can be thrown - in the `adjustHs()` call - but that's a pretty significant change in behavior to fix something which is really just very edge-casey bad input.

I could well be missing something obvious: any thoughts on a straightforward solution?

**Comment by hogru** [comment]
This is another example I believe. I apologize if this is of the same "type" as your much shorter example above and does not add any value; I actually can't interpret the molecule properties from the string (not a chemist): 
`C#CCN1/C(=N\C(=O)c2cccn2-c2ccccc2)=c2ccccc2=[NH+][C@@H]1C`

**Comment by bp-kelley** [comment]
@greglandrum I'm surprised this can be kekulized and keep the "aromatic" nitrogen.

**Comment by greglandrum** [comment]
This was fixed at some point. The problem no longer occurs in v2025.03.6
