### ISSUE TITLE
MolToSmiles then MolFromSmiles produces molecule with different chirality

### ISSUE THREAD

**Issue by loluwot** [rdkit/rdkit#5461]
**Describe the bug**
MolToSmiles then MolFromSmiles on a specific molecule produces a molecule with reversed chirality on certain atoms.
**To Reproduce**
Since I can't send the molecule as a SMILES string, I have attached a pickled version. [problem_mol.zip](https://github.com/rdkit/rdkit/files/9193269/problem_mol.zip)
```python
x = pickle.load(open('problem_mol', 'rb'))
display(x)
display(Chem.MolFromSmiles(Chem.MolToSmiles(x))) #not the same molecule
```

**Expected behavior**
Expected the molecule to remain the same.
**Screenshots**
![image](https://user-images.githubusercontent.com/17971923/181109663-952825d1-b104-4ce6-bf8e-e88ad0a62c2f.png)

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.3
 - OS: [e.g. Ubuntu 20.04] Windows
 - Python version (if relevant): 3.10.4 
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Comment by IchiruTake** [comment]
I think this issue is already answered in the discussion https://github.com/rdkit/rdkit/discussions/5376. You may want to check it ahead and close the issue. The problem here is that Interactive Python does not support multi-result output in the single kernel. Split them out and you would be fine
