### ISSUE TITLE
Invalid number of radical electrons calculated for [Pr+4]

### ISSUE THREAD

**Issue by bjonnh-work** [rdkit/rdkit#5462]
**Describe the bug - steps to reproduce**

```sql
SELECT mol_from_smiles('[Pr+4]');
ERROR:  molFromPickle: invalid value in pickle

SELECT mol_from_smiles('[Pr+3]');
 mol_from_smiles 
-----------------
 [Pr+3]
(1 row)

```

In Python:
```python
Chem.MolFromSmiles("[Pr+4]") 
unsupported number of radical electrons 255
```

This can be reproduced with [U+5] as well.

**Expected behavior**

Not sure, but it makes some molecules from the emolecules dataset impossible to import. 

**Configuration (please complete the following information):**
 - RDKit version: Master and 2022.03
 - OS: Ubuntu various versions
 - If you are not using conda: how did you install the RDKit? compiled myself

**Comment by greglandrum** [comment]
Confirmed. This is the result of carelessly converting an int to an unsigned int in `assignRadicals()`
