### ISSUE TITLE
CXSmiles isn't properly escaping floating point properties

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#5466]
Example structure

<img width="457" alt="image" src="https://user-images.githubusercontent.com/9888416/181307012-7313ee62-81a7-4099-95cd-5d0ba6a77b4c.png">

The Chemaxon smiles that rdkit generates is:

```
O=C(O)CCCCc1cccc2cncn12 |atomProp:1.apKa.4.2:14.apKa.7.54|
```

Note the second . should be escaped (even though the Chemaxon Docs clearly says that it doesn't for properties)

```
OC(=O)CCCCc1cccc2cncn12 |atomProp:1.apKa.4&#46;2:14.apKa.7|
```

The escape code for '.' is `&#46;`

We do parse it properly though.

```
>>> m = Chem.MolFromSmiles("OC(=O)CCCCc1cccc2cncn12 |atomProp:1.apKa.4&#46;2:14.apKa.7|")
>>> for atom in m.GetAtoms():
...   if atom.HasProp("apKa"): print(atom.GetIdx(), atom.GetProp("apKa"))
... 
1 4.2
14 7
```

**Comment by greglandrum** [comment]
@bp-kelley this is an ancient one, but after revisiting the way we quote CXSMILES, I think we actually did the wrong thing here.

According to the docs on what should be escaped (https://docs.chemaxon.com/latest/formats_chemaxon-extended-smiles-and-smarts-cxsmiles-and-cxsmarts.html#escaping), `.` is actually a non-escaped character for atom property keys and values. So `O=C(O)CCCCc1cccc2cncn12 |atomProp:1.apKa.4.2:14.apKa.7.54|` is correct.

I can't make the online version of Marvin Sketch display (or create) this kind of atom property, so I can't test it. How did you decide that this was a bug?

**Comment by bp-kelley** [comment]
This was fixed a bit ago apparently:

```
C |atomProp:0.apKa.7.54|
```

is now

```
C |atomProp:0.apKa.7&#46;54|
```

**Comment by bp-kelley** [comment]
I think that the "escaped" characters only refers to keys/CXSmiles formatting  not values and MUST be escaped in values.

**Comment by bp-kelley** [comment]
Here's kind of what I mean, there are many strings we can't round trip;  I.e. we can't round trip a string with CXSmiles in it:

```
from rdkit import Chem
m = Chem.MolFromSmiles("C")
atom = m.GetAtomWithIdx(0)
atom.SetProp("CXSMILES", "C |atomProp:0.apKa.7&#46;54|")

s = Chem.MolToCXSmiles(m)
print(s)

m = Chem.MolFromSmiles(s)
print (Chem.MolToCXSmiles(m))
```

```
C |atomProp:0.CXSMILES.C |atomProp:0&#46;apKa&#46;7&#46;54||
C |atomProp:0.CXSMILES.C |
```

**Comment by bp-kelley** [comment]
I think we either try and escape, or not save the string as a property in these cases.

**Comment by bp-kelley** [comment]
This is related to #9231

**Comment by bp-kelley** [comment]
btw - the doc you have was for MDL queries, here is the relevant one:

```
Chemaxon's extended SMILES/SMARTS does not contain non-ASCII characters, 
they are escaped in the usual form, &#n;, with their character code, n. 
The ASCII characters ,, ;, |, {, } and : in
 [Data S-group information](https://docs.chemaxon.com/latest/formats_chemaxon-extended-smiles-and-smarts-cxsmiles-and-cxsmarts.html#src-1806633-chemaxonextendedsmilesandsmarts-cxsmilesandcxsmarts-datasgroup) 
are also escaped in this way. Moreover, the symbols $, ;, |, {, } between dollar signs 
(see [Atom labels / aliases / values](https://docs.chemaxon.com/latest/formats_chemaxon-extended-smiles-and-smarts-cxsmiles-and-cxsmarts.html#src-1806633-chemaxonextendedsmilesandsmarts-cxsmilesandcxsmarts-atomlabel)) 
are coded in the above mentioned way as well.
```

**Comment by greglandrum** [comment]
> btw - the doc you have was for MDL queries, here is the relevant one:

The section of the docs that I linked to is a free-standing section, not a subsection of the "MDL Queries" section.

> 
> ```
> Chemaxon's extended SMILES/SMARTS does not contain non-ASCII characters, 
> they are escaped in the usual form, &#n;, with their character code, n. 
> The ASCII characters ,, ;, |, {, } and : in
>  [Data S-group information](https://docs.chemaxon.com/latest/formats_chemaxon-extended-smiles-and-smarts-cxsmiles-and-cxsmarts.html#src-1806633-chemaxonextendedsmilesandsmarts-cxsmilesandcxsmarts-datasgroup) 
> are also escaped in this way. Moreover, the symbols $, ;, |, {, } between dollar signs 
> (see [Atom labels / aliases / values](https://docs.chemaxon.com/latest/formats_chemaxon-extended-smiles-and-smarts-cxsmiles-and-cxsmarts.html#src-1806633-chemaxonextendedsmilesandsmarts-cxsmilesandcxsmarts-atomlabel)) 
> are coded in the above mentioned way as well.
> ```

I saw that too, but I believe that this information is incorrect for two reasons:
1. it would allow both `&` and `#`as unescaped characters. This would make fields that can include escaped characters essentially impossible to parse.
2. If you follow the link to the section on atom labels, it mentions escaping special characters and links to the section at the bottom that I referred to.

**Comment by greglandrum** [comment]
> Here's kind of what I mean, there are many strings we can't round trip; I.e. we can't round trip a string with CXSmiles in it:
> 
> ```
> from rdkit import Chem
> m = Chem.MolFromSmiles("C")
> atom = m.GetAtomWithIdx(0)
> atom.SetProp("CXSMILES", "C |atomProp:0.apKa.7&#46;54|")
> 
> s = Chem.MolToCXSmiles(m)
> print(s)
> 
> m = Chem.MolFromSmiles(s)
> print (Chem.MolToCXSmiles(m))
> ```
> 
> ```
> C |atomProp:0.CXSMILES.C |atomProp:0&#46;apKa&#46;7&#46;54||
> C |atomProp:0.CXSMILES.C |
> ```

Not being able to roundtrip the CXSMILES property is a legit problem (and related to what @DavidACosgrove reported in #9231), but it is not connected to whether or not the `.` in the `7.54` needs to be escaped.
