### ISSUE TITLE
Unexpected behavior when reading multiple molecule entries in sdf files

### ISSUE THREAD

**Issue by ijpulidos** [rdkit/rdkit#5467]
**Describe the bug**
Only one molecule is read if you try using an SDF file with multiple molecules and data items for each.

The issue is not shown if you add a line jump between the last data item and the `$$$$` delimiter. But I think it should be able to handle any combination of line jumps (or lack thereof) as long as the delimiting elements exist.

**To Reproduce**
I am attaching sample files in a tar.gz package with and without the line jumps to reproduce the issue. The python code that shows the issue is as follows:
```python
In [4]: suppl = Chem.SDMolSupplier('ligands_original.sdf')

In [5]: [x for x in suppl]
Out[5]: [<rdkit.Chem.rdchem.Mol at 0x7f47616e0b20>]

In [6]: suppl = Chem.SDMolSupplier('ligands_rdkit.sdf')

In [7]: [x for x in suppl]
Out[7]: 
[<rdkit.Chem.rdchem.Mol at 0x7f47617d15e0>,
 <rdkit.Chem.rdchem.Mol at 0x7f4761791820>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615d4460>,
 <rdkit.Chem.rdchem.Mol at 0x7f476176f160>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e59a0>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e5d60>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e5ca0>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e93a0>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e9c40>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e9700>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e96a0>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e9640>,
 <rdkit.Chem.rdchem.Mol at 0x7f47615e95e0>]
```

**Expected behavior**
I would expect that having any amount of line jumps between the last data item and the `$$$$` delimiter should work to read a multiple molecule sdf file (even including no line jumps, as long as the delimiter is there).

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.3
 - OS: ArchLinux
 - Python version (if relevant): 3.9.13 
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

Files to reproduce:
[ligands_.tar.gz](https://github.com/rdkit/rdkit/files/9202442/ligands_.tar.gz)

**Comment by greglandrum** [comment]
That SDF file is badly formatted according to the SDF specification. Here's what the documentation for the SDF file says about the format:
![image](https://user-images.githubusercontent.com/540511/181410241-fff11ad5-d8c4-4e61-ae17-4bcf903ae2ff.png)

The way you detect the end of a molecule property is the blank line, so if there is no blank line the `$$$$` is part of the property value.

The RDKit does not (and cannot) attempt to guess how to "fix" incorrectly formatted files, so this is expected behavior.

**Comment by mikemhenry** [comment]
Just for reference, page 75 
[ctfileformats2016.pdf](https://github.com/rdkit/rdkit/files/9243974/ctfileformats2016.pdf)
