### ISSUE TITLE
Unable to parse scientific notation coordinates in SDF

### ISSUE THREAD

**Issue by cdvonbargen** [rdkit/rdkit#5473]
**Describe the bug**
Reading the Biovia CTFILE FORMATS manual, it's unclear to me if this is/should be supported, but I have an SDF file containing at least one coordinate with scientific notation. The RDKit molblock parser chokes when it tries to read that coordinate.

**To Reproduce**
```
>>> mb = """
...      RDKit          2D
...
...   1  0  0  0  0  0  0  0  0  0999 V2000
...    -1.4286    1.2857    1.0E-4 C   0  0  0  0  0  0  0  0  0  0  0  0
... M  END
... """
>>> Chem.MolFromMolBlock(mb)
[11:10:23] Cannot process coordinates on line 5
```

Note line 5 contains the offending coordinate `1.0E-4`

**Comment by ptosco** [comment]
@cdvonbargen On page 40 of [CTFILE FORMATS BIOVIA DATABASES 2016](http://help.accelrysonline.com/ulm/onelab/1.0/content/ulm_pdfs/direct/reference/ctfileformats2016.pdf) there are the V2000 Atom Block specifications:

> The Atom Block
> The Atom Block is made up of atom lines, one line per atom with the following format:
> `xxxxx.xxxxyyyyy.yyyyzzzzz.zzzz aaaddcccssshhhbbbvvvHHHrrriiimmmnnneee`

where `xxxxx.xxxx`, `yyyyy.yyyy`, `zzzzz.zzzz` are fixed format floats with up to 5 figures before the decimal separator and 4 figures after the decimal separator. Scientific notation is not supported in either V2000 or V3000.
See also #3597.

**Comment by greglandrum** [comment]
I agree with @ptosco here; there is a case to be made that one should support scientific notation for V3000, but it definitely doesn't belong in the old-school Fortran-based v2000 format. You have to use the fixed format to be able parse that correctly, and that's just not compatible with scientific notation

**Comment by cdvonbargen** [comment]
Excellent, will communicate that back up. Thanks!
