### ISSUE TITLE
error C2039: 'string_view': is not a member of 'std'

### ISSUE THREAD

**Issue by blgpb** [rdkit/rdkit#5477]
When I follow the Install.md to install it on Windows 10.  I got some errors when I build the code.
Here's the command line:
C:/Windows/Microsoft.NET/Framework64/v4.0.30319/MSBuild.exe /m:4 /p:Configuration=Release INSTALL.vcxproj

![image](https://user-images.githubusercontent.com/40389895/182158702-dea1432c-fb60-40bb-af06-96347942c0c2.png)

environments:
Windows 10
Visual Studio 2017

**Comment by blgpb** [comment]
“C:\RDKit\build\INSTALL.vcxproj”(默认目标) (1) ->
       “C:\RDKit\build\ALL_BUILD.vcxproj”(默认目标) (3) ->
       “C:\RDKit\build\Code\DataStructs\Wrap\cDataStructs.vcxproj”(默认目标) (40) ->
       “C:\RDKit\build\Code\DataStructs\DataStructs.vcxproj”(默认目标) (58) ->
       “C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj”(默认目标) (61) ->
       (ClCompile 目标) ->
         c:\rdkit\code\rdgeneral\Dict.h(276): error C2039: 'string_view': is not a member of 'std' [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C2065: 'string_view': undeclared identifier [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C2923: 'std::is_same_v': 'string_view' is not a valid template type argument for parameter '_Uty' [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C3245: 'std::is_same_v': use of a variable template requires template argument list [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C2131: expression did not evaluate to a constant [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(277): error C2131: expression did not evaluate to a constant [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C2039: 'string_view': is not a member of 'std' [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C2065: 'string_view': undeclared identifier [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C2923: 'std::is_same_v': 'string_view' is not a valid template type argument for parameter '_Uty' [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C3245: 'std::is_same_v': use of a variable template requires template argument list [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C2131: expression did not evaluate to a constant [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(262): error C2131: expression did not evaluate to a constant [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C2039: 'string_view': is not a member of 'std' [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C2065: 'string_view': undeclared identifier [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C2923: 'std::is_same_v': 'string_view' is not a valid template type argument for parameter '_Uty' [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C3245: 'std::is_same_v': use of a variable template requires template argument list [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(276): error C2131: expression did not evaluate to a constant [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(277): error C2131: expression did not evaluate to a constant [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C2039: 'string_view': is not a member of 'std' [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C2065: 'string_view': undeclared identifier [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C2923: 'std::is_same_v': 'string_view' is not a valid template type argument for parameter '_Uty' [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C3245: 'std::is_same_v': use of a variable template requires template argument list [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(261): error C2131: expression did not evaluate to a constant [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]
         c:\rdkit\code\rdgeneral\Dict.h(262): error C2131: expression did not evaluate to a constant [C:\RDKit\build\Code\RDGeneral\RDGeneral.vcxproj]

    19  warnings
    24  errors

**Comment by bp-kelley** [comment]
Visual studio 2017 only supports c++14, string_view is a c++17 feature.  You will need to use a newer visual studio to compile  the current RDKit.

It looks like the build docs are wrong, and we now require c++17 not c++14.  I'll ping greg about this.

**Comment by blgpb** [comment]
> Visual studio 2017 only supports c++14, string_view is a c++17 feature. You will need to use a newer visual studio to compile the current RDKit.
> 
> It looks like the build docs are wrong, and we now require c++17 not c++14. I'll ping greg about this.

Thank you for your reply. At first, I used Visual Studio 2022. But if failed and got the same errors. So I uninstalled VS 2022 and reinstalled VS 2017. But it did not work.

**Comment by blgpb** [comment]
> Visual studio 2017 only supports c++14, string_view is a c++17 feature. You will need to use a newer visual studio to compile the current RDKit.
> 
> It looks like the build docs are wrong, and we now require c++17 not c++14. I'll ping greg about this.

Thank you for your reply. At first, I used Visual Studio 2022. But it failed. So I uninstalled VS 2022 and reinstalled VS 2017. (Since it is reported in the install.md that "the RDKit has been built with Visual Studio 2015 and 2017." )
But it did not work and got the same errors.

**Comment by bp-kelley** [comment]
I'm not sure why 2022 would be failing, but our tests are currently run on Visual Studio 2019 if that helps.  Below is the pipeline that is being run in case that helps you out.

https://github.com/rdkit/rdkit/blob/master/.azure-pipelines/vs_build.yml

**Comment by blgpb** [comment]
> I'm not sure why 2022 would be failing, but our tests are currently run on Visual Studio 2019 if that helps. Below is the pipeline that is being run in case that helps you out.
> 
> https://github.com/rdkit/rdkit/blob/master/.azure-pipelines/vs_build.yml

I have reinstalled Visual Studio 2019 but got the same errors. Maybe some errors in the phase of cmake?

**Comment by greglandrum** [comment]
I use Visual Studio 2022 on Windows to do builds of master without problems.
The error messages you are seeing are coming because the code is not being build in C++ 17 mode. Since the cmake configuration does specify C++ 17, I guess it is a cmake problem.

Did you get any error messages/warnings when running cmake?

**Comment by blgpb** [comment]
> I use Visual Studio 2022 on Windows to do builds of master without problems. The error messages you are seeing are coming because the code is not being build in C++ 17 mode. Since the cmake configuration does specify C++ 17, I guess it is a cmake problem.
> 
> Did you get any error messages/warnings when running cmake?

The messages of cmake are below. And I have reinstalled Visual Studio 2015 but got the same errors.

`C:\RDKit\build>cmake -DRDK_BUILD_PYTHON_WRAPPERS=ON -DBOOST_ROOT=C:/boost -G"Visual Studio 14 2015 Win64" ..
CMake Error: Error: generator : Visual Studio 14 2015 Win64
Does not match the generator used previously: Visual Studio 15 2017
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

C:\RDKit\build>cmake -DRDK_BUILD_PYTHON_WRAPPERS=ON -DBOOST_ROOT=C:/boost -G"Visual Studio 14 2015 Win64" ..
-- Selecting Windows SDK version  to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.0.24245.0
-- The CXX compiler identification is MSVC 19.0.24245.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Disabling boost::stacktrace on non-linux platform
-- Found Catch2 source in C:/RDKit/External/catch/catch
CATCH: C:/RDKit/External/catch/catch/single_include/catch2
-- Found PythonInterp: C:/Users/10544/anaconda3/envs/SMR/python.exe (found version "3.8.12")
-- Found PythonLibs: C:/Users/10544/anaconda3/envs/SMR/libs/python38.lib (found version "3.8.12")
CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2217 (message):
  No header defined for python-py38; skipping header check (note: header-only
  libraries have no designated component)
Call Stack (most recent call first):
  CMakeLists.txt:292 (find_package)


-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: python
nbval not found, disabling the jupyter tests
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: system serialization iostreams regex
== Using strict rotor definition
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: system iostreams regex
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: zlib
-- maeparser include dir set as 'maeparser_INCLUDE_DIRS-NOTFOUND'
-- maeparser libraries set as 'maeparser_LIBRARIES-NOTFOUND'
-- Could NOT find maeparser (missing: maeparser_INCLUDE_DIRS maeparser_LIBRARIES)
-- Found MAEParser source in C:/RDKit/External/CoordGen/maeparser
-- coordgen include dir set as coordgen_INCLUDE_DIRS-NOTFOUND
-- coordgen libraries set as 'coordgen_LIBRARIES-NOTFOUND'
-- Could NOT find coordgen (missing: coordgen_INCLUDE_DIRS coordgen_LIBRARIES)
-- Found coordgenlibs source in C:/RDKit/External/CoordGen/coordgen
-- Found RingDecomposerLib source in C:/RDKit/External/RingFamilies/RingDecomposerLib/src/RingDecomposerLib
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: iostreams regex
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: zlib
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: system iostreams regex
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: zlib
== Updating Filters.cpp from pains file
== Done updating pains files
C:/RDKit/Data/Fonts/ComicNeue-Regular.ttf already there, skipping the download
-- Found Freetype: F:/freetype-2.12.1/objs/freetype.lib (found version "2.12.1")
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: program_options
-- Found RapidJSON source in C:/RDKit/External
-- Configuring done
-- Generating done
-- Build files have been written to: C:/RDKit/build

C:\RDKit\build>cmake -DRDK_BUILD_PYTHON_WRAPPERS=ON -DBOOST_ROOT=C:/boost -G"Visual Studio 14 2015 Win64" ..
-- Selecting Windows SDK version  to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.0.24245.0
-- The CXX compiler identification is MSVC 19.0.24245.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Disabling boost::stacktrace on non-linux platform
-- Found Catch2 source in C:/RDKit/External/catch/catch
CATCH: C:/RDKit/External/catch/catch/single_include/catch2
-- Found PythonInterp: C:/Users/10544/anaconda3/envs/SMR/python.exe (found version "3.8.12")
-- Found PythonLibs: C:/Users/10544/anaconda3/envs/SMR/libs/python38.lib (found version "3.8.12")
CMake Warning at C:/Program Files/CMake/share/cmake-3.24/Modules/FindBoost.cmake:2217 (message):
  No header defined for python-py38; skipping header check (note: header-only
  libraries have no designated component)
Call Stack (most recent call first):
  CMakeLists.txt:292 (find_package)


-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: python
nbval not found, disabling the jupyter tests
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: system serialization iostreams regex
== Using strict rotor definition
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: system iostreams regex
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: zlib
-- maeparser include dir set as 'maeparser_INCLUDE_DIRS-NOTFOUND'
-- maeparser libraries set as 'maeparser_LIBRARIES-NOTFOUND'
-- Could NOT find maeparser (missing: maeparser_INCLUDE_DIRS maeparser_LIBRARIES)
-- Found MAEParser source in C:/RDKit/External/CoordGen/maeparser
-- coordgen include dir set as coordgen_INCLUDE_DIRS-NOTFOUND
-- coordgen libraries set as 'coordgen_LIBRARIES-NOTFOUND'
-- Could NOT find coordgen (missing: coordgen_INCLUDE_DIRS coordgen_LIBRARIES)
-- Found coordgenlibs source in C:/RDKit/External/CoordGen/coordgen
-- Found RingDecomposerLib source in C:/RDKit/External/RingFamilies/RingDecomposerLib/src/RingDecomposerLib
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: iostreams regex
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: zlib
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: system iostreams regex
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: zlib
== Updating Filters.cpp from pains file
== Done updating pains files
C:/RDKit/Data/Fonts/ComicNeue-Regular.ttf already there, skipping the download
-- Found Freetype: F:/freetype-2.12.1/objs/freetype.lib (found version "2.12.1")
-- Found Boost: C:/boost (found suitable version "1.66.0", minimum required is "1.58.0") found components: program_options
-- Found RapidJSON source in C:/RDKit/External
-- Configuring done
-- Generating done
-- Build files have been written to: C:/RDKit/build`

**Comment by greglandrum** [comment]
As Brian said: you need to use a version of visual studio which supports C++17. If you can use VS2022, I would suggest that, otherwise an up-to-date version of VS2019 should work. VS2017 and earlier definitely will not work.

**Comment by blgpb** [comment]
> As Brian said: you need to use a version of visual studio which supports C++17. If you can use VS2022, I would suggest that, otherwise an up-to-date version of VS2019 should work. VS2017 and earlier definitely will not work.

Thank you for your advice. I have managed to install rdkit via conda on Windows.
The install.md about "the RDKit has been built with Visual Studio 2015 and 2017."  is needed to be updated.

**Comment by blgpb** [comment]
> As Brian said: you need to use a version of visual studio which supports C++17. If you can use VS2022, I would suggest that, otherwise an up-to-date version of VS2019 should work. VS2017 and earlier definitely will not work.

By the way, I am confused about the version of 'C:/Windows/Microsoft.NET/Framework64/v4.0.30319/MSBuild.exe'. Although I have changed various versions of Visual Studio, 'C:/Windows/Microsoft.NET/Framework64/v4.0.30319/MSBuild.exe' seems no changes at all. Maybe the errors about C++17 are caused by the version of MSBuild.exe

**Comment by greglandrum** [comment]
> Maybe the errors about C++17 are caused by the version of MSBuild.exe

No, those error messages are from the compiler
