### ISSUE TITLE
Fail to generate conformers for a molecule with fused rings

### ISSUE THREAD

**Issue by jaechang-hits** [rdkit/rdkit#5481]
**Describe the bug**
Fail to generate conformers for a given molecules with fused rings

**To Reproduce**
```
from rdkit.Chem import AllChem as Chem

smiles = "C[N@@H+]1[C@H]2C[C@@H](C[C@@H]1[C@@H]1O[C@@H]12)OC(=O)[C@H](CO)C1C=CC=CC=1"
m = Chem.MolFromSmiles(smiles)
Chem.EmbedMolecule(m)
print(m.GetConformers())
```

**Expected behavior**
a conformer is generated

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2019.09.3
 - OS: Amazon Linux 2
 - Python version (if relevant): 3.7.10
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? 
 - If you are not using conda: how did you install the RDKit? conda install

**Additional context**

**Comment by bp-kelley** [comment]
This is quite an old version of RDKit.  However, you should always add hydrogens.  The following works in rdkit 2022.03.4

```
>>> import rdkit
>>> rdkit.__version__
'2022.03.4'
>>> from rdkit import Chem
>>> from rdkit.Chem import AllChem
>>> m = Chem.MolFromSmiles("C[N@@H+]1[C@H]2C[C@@H](C[C@@H]1[C@@H]1O[C@@H]12)OC(=O)[C@H](CO)C1C=CC=CC=1")
>>> m = Chem.AddHs(m)
>>> AllChem.EmbedMolecule(m)
0
>>> m.GetNumConformers()
1
>>> 
```
