### ISSUE TITLE
Six new errors occuring during build of rdkit-js (minimallib) 2022.03.5 for npm release

### ISSUE THREAD

**Issue by MichelML** [rdkit/rdkit#5485]
Automated build of rdkit-js 2022.03.5 is currently failing thus I cannot currently deploy this release to npm

See build logs here https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=30&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=15148 .

To get to the errors quickly, I recommand ctrl+f and searching for " error" (space is important).

But, here they are for quick access:
- https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=30&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=15313 
- https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=30&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=15206
- https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=30&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=15237  
- https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=30&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=15268  
- https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=30&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=15295
- https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=30&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=15148

Additional info:
- [Dockerfile](https://github.com/rdkit/rdkit/blob/Release_2022_03/Code/MinimalLib/docker/Dockerfile)
- [build script](https://github.com/rdkit/rdkit-js/blob/master/scripts/build_rdkitjs.sh)
- [Azure pipeline](https://github.com/rdkit/rdkit-js/blob/master/azure-pipelines.yml)
- [Successful 2022.03.4 azure build for comparison](https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=23&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5)

@greglandrum @ptosco any help welcome here :+1:  - currently blocking for 2022.03.5 npm release

**Comment by MichelML** [comment]
Rerunning multiple times produce the same error

**Comment by ptosco** [comment]
@MichelML I'll take a look later today and fix it.

**Comment by greglandrum** [comment]
Yeah, sorry that happened. Maybe we should figure out a way to do the JS builds as part of the standard RDKit CI

**Comment by ptosco** [comment]
@MichelML @greglandrum I don't get those errors in my local build. Maybe it depends on the emsdk version?
However, I do get a test failure (#5487).

**Comment by MichelML** [comment]
Did you do a docker build @ptosco ?

**Comment by ptosco** [comment]
@MichelML I am running it right now.

**Comment by MichelML** [comment]
@ptosco it seems to be indeed related to emsdk version as 3.1.17 seems like it will complete properly, but 3.1.18 (latest) does not.

**Comment by MichelML** [comment]
I will copy the Dockerfile to rdkit-js and fixed the version until this is resolved if the whole build with tests pass

**Comment by ptosco** [comment]
@MichelML You will probably need to comment out a line in `tests.js`:
```
//assert.equal(mol.get_smiles(),"CC1CC2(CC[C@H](C)CC2)CC[C@@H]1C");
```
(see #5487)

**Comment by MichelML** [comment]
@ptosco it doesn't seem to generate any error in the docker build with emsdk 3.1.17 :thinking: see

https://dev.azure.com/rdkit-js/rdkit-js/_build/results?buildId=34&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=19103

the new version is published, this can be closed :+1: 

https://www.npmjs.com/package/@rdkit/rdkit

**Comment by MichelML** [comment]
Also fyi @greglandrum @ptosco , I copied the Dockerfile to the rdkit-js repo https://github.com/rdkit/rdkit-js/commit/e7912b3c150702b3eed8c79784edb8dedfae1e9b

this file will be maintained for the npm release from now on if you're ok with it :+1:

**Comment by ptosco** [comment]
@MichelML confirmed, I managed to build with `emsdk 3.1.17` - no need to update `boost`.
Maybe you did not experience the problem with tests because you built the `2022_03_5` release, while I have built the current `master` branch. My `docker` build succeeded with these two changes:
```diff
diff --git a/Code/MinimalLib/docker/Dockerfile b/Code/MinimalLib/docker/Dockerfile
index 91a8428..32b1d5d 100644
--- a/Code/MinimalLib/docker/Dockerfile
+++ b/Code/MinimalLib/docker/Dockerfile
@@ -26,8 +26,8 @@ RUN git clone https://github.com/emscripten-core/emsdk.git

 WORKDIR /opt/emsdk
 RUN ./emsdk update-tags && \
-  ./emsdk install latest && \
-  ./emsdk activate latest
+  ./emsdk install 3.1.17 && \
+  ./emsdk activate 3.1.17

 #RUN source ./emsdk_env.sh

@@ -39,7 +39,7 @@ RUN git clone https://github.com/rdkit/rdkit.git
 WORKDIR $RDBASE
 RUN git fetch --all --tags && \
   git checkout $RDKIT_BRANCH
-
+RUN sed -i 's|^ *assert.equal(mol.get_smiles(),"CC1CC2(CC\[C@H\](C)CC2)CC\[C@@H\]1C");|//&|' Code/MinimalLib/tests/tests.js
 RUN mkdir build
 WORKDIR build
```
