### ISSUE TITLE
Using function GetAdjacencyMatrix() the program stops unexpectedly with no error message

### ISSUE THREAD

**Issue by JackFang0815** [rdkit/rdkit#5530]
**Describe the bug**
Using function GetAdjacencyMatrix() the program stops unexpectedly with no error message

**To Reproduce**
```
try:
    print(pdb_file)
    m = Chem.MolFromPDBFile(pdb_file)
    print(m)
    print('1')
    am= Chem.GetAdjacencyMatrix(m)
    print('2')
except Exception as e:
    print(e)
```

Output:
```
./pdbs/5nwl.pdb
<rdkit.Chem.rdchem.Mol object at 0x000002641FC718A0>
1

```

**Expected behavior**
Print 2 or print exception.

**Configuration:**
 - RDKit version: 2022.03.5, 2021.09.4 and 2020.09.5
 - OS: Windows10 and redhat.
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**
Two computers encounter different proteins when their program stops unexpectedly. I don't know why.
"

**Comment by bddap** [comment]
That [structure](https://www.rcsb.org/structure/5NWL) is huge so the matrix will be `huge**2`. You are probably running out of memory so your os is killing the process.

**Comment by bddap** [comment]
Since this is a protein you might try a sparse boolean matrix representation. Not sure if there is a function for that in rdkit but it would be possible to implement manually by iterating over bonds.
