### ISSUE TITLE
TautomerEnumerator() removes chirality by default

### ISSUE THREAD

**Issue by shortydutchie** [rdkit/rdkit#5531]
TautomerEnumerator() removes chirality on all input atoms, not only the ones involved in the tautomerisation rearrangements.

**To Reproduce**
<code>
from rdkit.Chem.MolStandardize import rdMolStandardize
mol = Chem.MolFromSmiles("C[C@@H](C(=O)N)n1ccc2c1cccc2")
te = rdMolStandardize.TautomerEnumerator()
Chem.MolToSmiles( te.Canonicalize(mol) )
'CC(C(N)=O)n1ccc2ccccc21'
**te.SetRemoveSp3Stereo(False)**
Chem.MolToSmiles( te.Canonicalize(mol) )
'C[C@@H](C(N)=O)n1ccc2ccccc21'
</code>

Same is observed with a benzylic chiral center (ie different ring): eg. CC(C(N)=O)c1ccccc1

The setting of te.SetReassignStereo() makes no difference
Full enumeration with Enumerate() shows same issue.

**Expected behavior**
Should not affect chirality of atoms not involved in tautomer changes

**Configuration (please complete the following information):**
 - RDKit version: '2022.03.5' - but this was same in my 2021 version as well
 - OS: [Ubuntu 20.04]

**Comment by nhstanley** [comment]
There are options in `rdMolStandardize.CleanupParameters` that you can pass to `TautomerEnumerator` that will likely help you achieve what you want. 

Check out the docs here: http://rdkit.org/docs/source/rdkit.Chem.MolStandardize.rdMolStandardize.html#rdkit.Chem.MolStandardize.rdMolStandardize.CleanupParameters

**Comment by shortydutchie** [comment]
Thanks. I think the behaviour as shown is not consistent.
W

**Comment by shortydutchie** [comment]
Same behaviour in 2022.09.5 - chirality is removed from centres not involved in the tautomer, these should be left alone? 

<code>
> mol = Chem.MolFromSmiles("C\[C@H\](c1ccccc1)C(=O)N")
> te = rdMolStandardize.TautomerEnumerator()
> Chem.MolToSmiles( te.Canonicalize(mol) )
'CC(C(N)=O)c1ccccc1'
> te.SetRemoveSp3Stereo(False)
> Chem.MolToSmiles( te.Canonicalize(mol) )
'C\[C@@H\](C(N)=O)c1ccccc1'
> rdkit.__version__
'2022.09.5'
</code>

**Comment by greg-osmo** [comment]
Here is another example stereo removal which I find more egregious
>>> from rdkit.Chem.MolStandardize import rdMolStandardize
>>> te = rdMolStandardize.TautomerEnumerator()
>>> mol = Chem.MolFromSmiles('CN(C)CC(NC(=O)OCC1c2ccccc2-c2ccccc12)C(=O)N[C@@H](C(O)=O)C(C)(C)C')
>>> Chem.MolToSmiles( te.Canonicalize(mol))
'CN(C)CC(NC(=O)OCC1c2ccccc2-c2ccccc21)C(=O)NC(C(=O)O)C(C)(C)C'
>>> te.SetRemoveSp3Stereo(False)
>>> Chem.MolToSmiles( te.Canonicalize(mol))
'CN(C)CC(NC(=O)OCC1c2ccccc2-c2ccccc21)C(=O)N[C@@H](C(=O)O)C(C)(C)C'
>>> rdkit.__version__
'2023.03.1'

![image](https://github.com/rdkit/rdkit/assets/131042162/6141013e-728a-4a78-aa73-2fbd6207c3a7)

and now both stereo centers removed
>>> te.SetRemoveSp3Stereo(True)
>>> mol = Chem.MolFromSmiles('CN(C)C[C@H](NC(=O)OCC1c2ccccc2-c2ccccc12)C(=O)N[C@@H](C(O)=O)C(C)(C)C')
>>> Chem.MolToSmiles( te.Canonicalize(mol))
'CN(C)CC(NC(=O)OCC1c2ccccc2-c2ccccc21)C(=O)NC(C(=O)O)C(C)(C)C'
>>> te.SetRemoveSp3Stereo(False)
>>> Chem.MolToSmiles( te.Canonicalize(mol))
'CN(C)C[C@H](NC(=O)OCC1c2ccccc2-c2ccccc21)C(=O)N[C@@H](C(=O)O)C(C)(C)C'
