### ISSUE TITLE
Problem in generated canonical SMILES for mol with sulfonamide groups

### ISSUE THREAD

**Issue by Hong-Rui** [rdkit/rdkit#5532]
Hi developers, I'm using rdkit 2022.03.5 conda installation with python 3.9.
I met a problem when donig substructure match with a rdkit generated canonical smiles.
Say, I have this molecule with SMILES: O=S(=O)(Nc1noc2ccccc12)C1CCCC1
![1662116816425](https://user-images.githubusercontent.com/8930355/188126692-e921fb7a-c9dc-4f3e-b6f3-7d97a7e5f7f2.png)
and the core SMILES:  O=S(NC1=NOC2=C1C=CC=C2)=O, converted to a canonical expression:
![1662117022922](https://user-images.githubusercontent.com/8930355/188127228-b286b7f4-8c67-4f9f-8e4c-fa7e0f32eac7.png)

Now I do a substructure match for this mol to the core, it works as expected.
![1662117197262](https://user-images.githubusercontent.com/8930355/188127688-f0803c1b-9ae1-47ad-8040-e6018c2769d5.png)

However, when I do a substructure match for the same core but read in as a SMARTS pattern, it does not match:
![1662117336070](https://user-images.githubusercontent.com/8930355/188128038-778c1bf4-33ee-4a1c-b13d-0c57667ca571.png)

and I noticed that this was because the NumExplicitHs that is causing this problem:
![1662117474783](https://user-images.githubusercontent.com/8930355/188128382-ae995e7f-742f-492a-8ddf-62527b8f20e7.png)
But it still does not work after I do some fix to the Sulfur atom:
![1662117949203](https://user-images.githubusercontent.com/8930355/188129578-077b2b33-70fa-45f1-a4f9-d10475114997.png)

It would work when I manually modified the core SMARTS as O=S(=O)Nc1noc2ccccc12:
![1662117819524](https://user-images.githubusercontent.com/8930355/188129168-46925cb1-9050-47fb-b657-2de0503ae380.png)

Let us focus on only the sulfonamide parts, we still see the same issue:
![1662118086832](https://user-images.githubusercontent.com/8930355/188129944-70be64dd-98a5-4844-a259-0a01e18c2d19.png)

Now, the problem here is, there's no reason for the S atom to label the explicit hydrogen counts in a  canonically expressed SMILES, which was generated by rdkit! The valence for S is similar to the O atom, which has no ambiguity. (For aromatic N you need this since there may be some protonation state issues)
The rdkit algorithm should automatically recognize the explicit hydrogen counts for a sulfur atom, and not let the user to deal with the SMILES string manually. For example, the `Chem.MolToSmiles()` should generated a SMILES `O=S(=O)Nc1noc2ccccc12`, and NOT `O=[SH](=O)Nc1noc2ccccc12` !!
And the more promatic issue is when I set the `NumExplicitHs` on the specified sulfur atom to 0, it still does not match the molecule.

Hope this can be fixed soon. Thanks!

**Comment by wopozka** [comment]
core_mol_smiles in the form you use here: `O=[SH](=O)Nc1noc2ccccc12` should not match mol1, and this is correct answer. Regarding generating Smiles, sulfur oxidation state for `O=[SH](=O)Nc1noc2ccccc12` is not standard one, so I think rdkit in this case need to add implicit hydrogen count.

**Comment by Hong-Rui** [comment]
Yeah, I mean in this case the rdkit `Chem.MolToSmiles()` or `rdMolStandardize.StandardizeSmiles()` should generate `O=S(=O)Nc1noc2ccccc12` and not `O=[SH](=O)Nc1noc2ccccc12`

**Comment by loluwot** [comment]
Just set explicit hs to 0 before running Chem.MolToSmiles() and using it as SMARTS:
![image](https://user-images.githubusercontent.com/17971923/188247249-67591aa9-3ba9-436e-a0c1-6d053c919802.png)
Otherwise rdkit will specify hydrogens as explicit because sulfur has multiple oxidation states.

**Comment by loluwot** [comment]
Use `SetNoImplicit(True)` on the sulfur atom before `MolToSmiles`
![image](https://user-images.githubusercontent.com/17971923/188247460-cd3f9370-387c-49ec-afdc-dfe07ff21f98.png)

Otherwise rdkit will add hydrogens on the sulfur when converting to SMILES because there is ambiguity in oxidation state.

**Comment by Hong-Rui** [comment]
@loluwot Thank you for pointing out this!
However, from my test I think you need to deal with both `ExplicitHs` and `ImplicitHs` to make this work for any pre-specified oxidation state of S atom on the core SMILES:
![1662382401273](https://user-images.githubusercontent.com/8930355/188453956-1498e029-b786-4e05-9635-256b5ff2dcd2.png)

I still think that this is a serious rdkit issue, that it should determine the correct oxidation state of sulfur atom automatically by considering its chemical environments. For instance, for a thiol group, you would have `-SH`, for sulfonamide with no R-group replacement on S, you have `O=[SH](=O)N-`, for sulfonamide with some R-group replacement, you have `O=S(=O)(R)N-`.

Similar scenario for the aromatic nitrogen case, as refer to https://github.com/rdkit/rdkit/issues/5500.
The aromatic nitrogen issue not only affects the behavior in RGD, but also in the atom mapping of substructure match. And from my inspection, they have different implementations in the C++ codes for doing the atom mapping.
