### ISSUE TITLE
Incorrect documentation for rdMolStandardize.SuperParent and rdMolStandardize.StereoParent

### ISSUE THREAD

**Issue by gedeck** [rdkit/rdkit#5541]
**Describe the bug**
The documentation for `rdMolStandardize.SuperParent` and `rdMolStandardize.StereoParent`  states `AtomPairsParameters` as the type of the configuration (https://www.rdkit.org/docs/source/rdkit.Chem.MolStandardize.rdMolStandardize.html)
<img width="862" alt="image" src="https://user-images.githubusercontent.com/8720575/188896872-5c23792c-07e5-4bbe-8b52-3fb9bcb7a93d.png">

The type of parameters for `superParent` and `stereoParent` is however `CleanupParameters`:
(https://www.rdkit.org/docs/cppapi/namespaceRDKit_1_1MolStandardize.html#ad4763a7c4d23956cb13b83b6fe571cf2)
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/8720575/188897299-66ec52f2-b700-4078-8d97-49741eedff08.png">

There might be more issues like this in the documentation. 

**To Reproduce**
Not applicable

**Expected behavior**
First website should state `CleanupParameters` 

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: latest
 - OS: not applicable
 - Python version (if relevant): not applicable
 - Are you using conda? not applicable
 - If you are using conda, which channel did you install the rdkit from? not applicable
 - If you are not using conda: how did you install the RDKit? not applicable

**Additional context**

**Comment by greglandrum** [comment]
I agree that this is wrong, but this function signature information is added automatically by boost::python and I don't think we can change it. We can disable the function signatures completely, but I think that's about it.

**Comment by gedeck** [comment]
I wouldn't disable them. Let's just close this issue.

**Comment by greglandrum** [comment]
Before closing it, I do want to check to see if there's potentially a way to fix it.

**Comment by gedeck** [comment]
Here is the code where the type information is not correct.
```
RDKit::ROMol *cleanupHelper(const RDKit::ROMol *mol, python::object params) {
  return msHelper(
      mol, params,
      static_cast<
          RDKit::RWMol *(*)(const RDKit::RWMol *,
                            const RDKit::MolStandardize::CleanupParameters &)>(
          RDKit::MolStandardize::cleanup));
}
...
  docString = "Standardizes a molecule";
  python::def("Cleanup", cleanupHelper,
              (python::arg("mol"), python::arg("params") = python::object()),
              docString.c_str(),
              python::return_value_policy<python::manage_new_object>());
```
The type information is correct for e.g. NormalizeFromData. That has this definition:
```
MolStandardize::Normalizer *normalizerFromDataAndParams(
    const std::string &data, const MolStandardize::CleanupParameters &params) {
  std::istringstream sstr(data);
  return new MolStandardize::Normalizer(sstr, params.maxRestarts);
}
...
    python::def(
        "NormalizerFromData", &normalizerFromDataAndParams,
        (python::arg("paramData"), python::arg("params")),
        "creates a Normalizer from a string containing normalization SMARTS",
        python::return_value_policy<python::manage_new_object>());
```
What would go wrong if we change the definition of cleanupHelper
```
RDKit::ROMol *cleanupHelper(const RDKit::ROMol *mol, const MolStandardize::CleanupParameters &params) {
  return msHelper(
      mol, params,
      static_cast<
          RDKit::RWMol *(*)(const RDKit::RWMol *,
                            const RDKit::MolStandardize::CleanupParameters &)>(
          RDKit::MolStandardize::cleanup));
}
