### ISSUE TITLE
Inconsistent enumeration of rooted torsions

### ISSUE THREAD

**Issue by gedeck** [rdkit/rdkit#5552]
**Describe the bug**
In special cases, the enumeration of rooted topological torsions depends on the order of atoms in the molecule. 

Topological torsions that are rooted at a specific atom and describe a cycle which starts and ends on the root are only returned if the root atom comes first in the order of atoms. 

According to closed issue #811, this should be fixed by now, however it still occurs.

**To Reproduce**
I found it originally with a larger structure, but it can be reproduced with a 3-ring as well. 
```
from rdkit import Chem
from rdkit.Chem.AtomPairs import Torsions

targetSize = 4
cases = [
    (0, 'N1CC1'),
    (1, 'C1NC1'),
    (1, 'CN1CC1'),
    (1, 'C1N(C)C1'),
]
for atom, smiles in cases:
    mol = Chem. MolFromSmiles(smiles)
    print(Chem.MolToSmiles(mol), smiles, 'rooted at', atom)
    fp = Torsions.GetTopologicalTorsionFingerprint(mol, fromAtoms=[atom], targetSize=targetSize)
    print(dict(fp.GetNonzeroElements().items()))

C1CN1 N1CC1 rooted at 0
{8732557377: 1}
C1CN1 C1NC1 rooted at 1
{}

CN1CC1 CN1CC1 rooted at 1
{8866775106: 1}
CN1CC1 C1N(C)C1 rooted at 1
{}
```

**Expected behavior**
Topological torsions are independent of atom ordering.

**Screenshots**
Not applicable

**Configuration (please complete the following information):**
 - RDKit version: rdkit-pypi 2022.3.5
 - OS: [e.g. Ubuntu 20.04] some ubuntu version
 - Python version (if relevant): 3.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from? NA
 - If you are not using conda: how did you install the RDKit? pypi

**Additional context**
None

**Comment by greglandrum** [comment]
Thanks for the bug report @gedeck; I will take a look tomorrow
