### ISSUE TITLE
KeyError: _smilesAtomOutputOrder

### ISSUE THREAD

**Issue by leowang1217** [rdkit/rdkit#5553]
**Describe the bug**
KeyError: _smilesAtomOutputOrder

**To Reproduce**
``` python
from rdkit import Chem
mol = Chem.MolFromSmiles("CCCC")
mol.GetPropsAsDict(True,True)['_smilesAtomOutputOrder']
```

KeyError: '_smilesAtomOutputOrder'

**Configuration (please complete the following information):**
 - RDKit version: 2022.3.5
 - OS: Linux
 - pip install

**Comment by greglandrum** [comment]
GetPropsAsDict() doesn’t return “private” properties (those with a name starting with _) by default. Try: mol.GetPropsAsDict(includePrivate=True, includeComputed=True)


BTW: If you want a specific property the easiest way to get it is with GetProp()

**Comment by leowang1217** [comment]
Thanks for your suggestion, but it didn't work.
I actually set the property includePrivate = True at the beginning (I used mol.GetPropsAsDict(True,True)). 
I made the following two attempts again:
```python
from rdkit import Chem
mol = Chem.MolFromSmiles("CCCC")
mol.GetPropsAsDict(includePrivate=True, includeComputed=True)['_smilesAtomOutputOrder']
```
KeyError: '_smilesAtomOutputOrder'
```python
mol.GetProp('_smilesAtomOutputOrder')
```
KeyError: '_smilesAtomOutputOrder'
I

**Comment by ptosco** [comment]
@leowang1217 The `_smilesAtomOutputOrder` property is created upon calling `MolToSmiles()`: see below:
```python
mol = Chem.MolFromSmiles("CCCC")
mol.GetPropsAsDict(includePrivate=True, includeComputed=True)['_smilesAtomOutputOrder']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 mol.GetPropsAsDict(includePrivate=True, includeComputed=True)['_smilesAtomOutputOrder']
KeyError: '_smilesAtomOutputOrder'
```
After calling `MolToSmiles()` the property is created and can be accessed:
```python
Chem.MolToSmiles(mol)
‘CCCC’
Chem.MolToSmiles(mol)
list(mol.GetPropsAsDict(includePrivate=True, includeComputed=True)['_smilesAtomOutputOrder'])
[0, 1, 2, 3]
```

**Comment by leowang1217** [comment]
> Contributor

It works, thank you very much!
