### ISSUE TITLE
mergeQueryHs merges isotopes

### ISSUE THREAD

**Issue by jones-gareth** [rdkit/rdkit#5568]
### Discussed in https://github.com/rdkit/rdkit/discussions/5554

<div type='discussions-op-text'>

<sup>Originally posted by **jones-gareth** September 10, 2022</sup>

`MergeQueryHs` will replace deuterium (and other hydrogen isotopes) by a hydrogen count constraint on the heavy neighbor, losing the isotope.

I like `mergeQueryHs` as it allows an explicit hydrogen in a query to match either explicit or implicit hydrogens in a target compound.  However, I typically don't want to merge isotopes.  If you have deuterium in a query, then you only want to mach deuterium in a target compound.

I think it would be a good idea to change `MolOps::mergeQueryHs` to have a`mergeIsotopes` argument so that you can skip merging isotopes.   I'm happy to make that change.
</div>

**Comment by greglandrum** [comment]
Closed by #5563
