### ISSUE TITLE
Unable to change the Morgan Fingerprints for Neighbour search in Aurora postgresql using RDKIT Catridge

### ISSUE THREAD

**Issue by nightcresendo** [rdkit/rdkit#5583]
**_Problem Statement:_**
We have a requirement wherein we want to perform neighbor search on SMILES (placed in database table) using RDKIT catridge. The database of our application is housed in AWS RDS as Aurora Postgresql (running version 12.8). We have the latest RDKIT extension installed in Aurora. The below functionalities are fully performed in the database.
The neighbor search functionality is housed on a Postgresql user defined function. The function is a simple one whose job is to take the schema name of the table, the smiles in question and the tanimoto_threshold. The function internally uses tanimoto_sml(morganbv_fp(mol_from_smiles('<SMILES>'))).

Bug:
It seems the Morgan fingerprints is set to 512 bits (default) and cannot be changed from that value even though its mentioned in the documentation.
We have used the below statement to change the fingerprint bits:
**_set rdkit.morgan_fp_size=2048;_**
But during execution, the above statement is raising a warning and the fingerprint bits remain at 512 bits. Warning as shown below:
**_WARNING:  parameter "rdkit.morgan_fp_size" cannot be changed_**

Our aim is to change it to 2048 before we perform the neighbor search. This change is done at session level.
On the same way we are also changing the tanimoto threshold parameter in the DB session within the function with the below statement:
**_set rdkit.tanimoto_threshold=0.7;_**

The above statement is executing fine without any problem and the threshold is indeed getting updated. But the fingerprint size cannot be altered.
We have followed the following documentation wile designing and developing:
https://www.rdkit.org/docs/Cartridge.html
https://sourceforge.net/p/rdkit/mailman/message/32599793/

But despite the documentation, the command is not behaving as expected. We also have the function based gist index created on database table (housing the SMILES) as mentioned in the documentation
I have a doubt that though the functionality is present in normal Postgresql but not present in Aurora Postgresql.
Kindly let me know the next steps.

![image](https://user-images.githubusercontent.com/47301483/191770039-bcc72be1-8612-4b5e-827b-ce8c8b981c75.png)

**Comment by greglandrum** [comment]
Sorry for the embarrassingly slow reply. 

The parameter to change fingerprint size was disabled by the AWS team since using it makes it very easy to end up with data problems: when comparing fingerprints in the cartridge all of them must be the same size.

There is a thread about this here: #6644

**Comment by greglandrum** [comment]
Removing the "bug" marker since this is a configuration change by the AWS team, not anything we did

**Comment by nightcresendo** [comment]
Thanks Greg for clarifying the issue.
