### ISSUE TITLE
Type stubs for Python bindings

### ISSUE THREAD

**Issue by swamidass** [rdkit/rdkit#5588]
Is there interest in adding type stubs to the python bindings?

If not included in RDKit proper, perhaps we can generate them and added to typeshed: https://github.com/python/typeshed . Please let me know which approach would be best.

**Comment by mattwthompson** [comment]
It'd be a pretty sizable effort to get them into PSF's typeshed (the [contribution process](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md) is not short). IMHO maintaining third-party stubs (either generated by hand or by editing the results of `stubgen`) is be preferred due the lower friction. You can make stubs and use them immediately without requiring a PR be merged into the main codebase or worrying about who would maintain them long-term.

See also https://github.com/rdkit/rdkit/issues/3591, maybe other older issues as well.

**Comment by greglandrum** [comment]
As I mentioned previously: I'm not fundamentally opposed to type stubs (though I personally dislike them) and I am happy to review, and consider merging, a PR which adds them to the RDKit Python wrappers. The pre-requisites for this to go in would be an automated process for creating the   type stubs which is robust with respect to future library additions/changes and some way of testing that the generated results are correct (this probably doesn't need to be comprehensive, but there should at least be something).

**Comment by swamidass** [comment]
That's good to hear.  

I think I can produce the stubs in an automated process, but I may need some help figuring out how to integrate this with RDKit's build process.

**Comment by swamidass** [comment]
@mattwthompson , yes that's true and an option. I just wanted to know if it should be third party or if it could be integrated as a first party feature.
