### ISSUE TITLE
Tautomer queries give the wrong type of bond

### ISSUE THREAD

**Issue by bjonnh-work** [rdkit/rdkit#5600]
**Describe the bug**
The template molecule generated from tautomer queries doesn't always correspond to the enumerated tautomeric forms.

**To Reproduce**
```
tq = rdTautomerQuery.TautomerQuery(Chem.MolFromSmiles("C#N"))
Chem.MolToSmarts(tq.GetTemplateMolecule())
```

Gives: '[#6]-,=,:[#7]'

However, if I look at the generated tautomers:
```
[Chem.MolToSmiles(i) for i in tq.GetTautomers()]
```
I get: ['C#N', '[C-]#[NH+]']

**Expected behavior**

Not sure what I would expect here, but not a bond description that omits the triple bond.

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.5 
 - OS: Ubuntu 22.04
 - Are you using conda? No

**Additional context**

**Comment by greglandrum** [comment]
Confirmed. The tautomer query produced also doesn't seem to actually match anything:
```
In [2]: m = Chem.MolFromSmiles('C#N')

In [3]: from rdkit.Chem import rdTautomerQuery

In [4]: tq = rdTautomerQuery.TautomerQuery(m)

In [5]: Chem.MolToSmarts(tq.GetTemplateMolecule())
Out[5]: '[#6]-,=,:[#7]'

In [6]: tq.GetSubstructMatches(m)
Out[6]: ()

In [7]: tq.GetSubstructMatches(Chem.MolFromSmiles('C=N'))
Out[7]: ()

In [8]: tq.GetSubstructMatches(Chem.MolFromSmiles('CN'))
Out[8]: ()

```
