### ISSUE TITLE
RGD Stereochemistry in decomposed structure is not copied to the matching core

### ISSUE THREAD

**Issue by jones-gareth** [rdkit/rdkit#5613]
**Describe the bug**

Given a core query that does not specify stereochemistry and a matching structure with stereochemistry the stereochmistry is not copied to the matching core output in the decomposition.

**To Reproduce**

```python
# %%
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.rdRGroupDecomposition import RGroupDecomposition, RGroupDecompositionParameters, \
    RGroupMatching, RGroupScore, RGroupLabels, RGroupCoreAlignment, RGroupLabelling
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG = True
from rdkit.Chem import PandasTools
from rdkit.Chem import Draw
from IPython.display import HTML
import pandas as pd

# %%
core = Chem.MolFromSmarts('[*:1]C(=O)NC1CCN([*:3])C1')
core

# %%
mol = Chem.MolFromSmiles('Cc1c(c(c([nH]1)C(=O)N[C@H]2CCN(C2)c3cc(nc(n3)Cl)C(=O)O)Cl)Cl')
mol

# %%
options = RGroupDecompositionParameters()
decomp = RGroupDecomposition([core], options)
decomp.Add(mol)
decomp.Process()
groups = decomp.GetRGroupsAsColumns()
df = PandasTools.RGroupDecompositionToFrame(groups, [mol], include_core=True)
PandasTools.ChangeMoleculeRendering(df)
HTML(df.to_html())

```

**Expected behavior**

I expect to see the chiral center in the molecule appear in the matching core.

**Screenshots**

The core query does not have a chiral center specified:

![image](https://user-images.githubusercontent.com/24233741/193469019-6646cdd7-70b0-4a9b-baa4-c93eb8336972.png)

The molecule does on the Pyrrolidine N:

![image](https://user-images.githubusercontent.com/24233741/197821924-98bae79c-7992-43f0-a784-7cb99f5a8e16.png)

but the matching core does not contain the chiral center:

![image](https://user-images.githubusercontent.com/24233741/193469237-346c0fef-a808-431d-a88d-4d83cc909c82.png)

**Configuration (please complete the following information):**

 - RDKit version: master as of 9/2022
 - OS: [e.g. Ubuntu 20.04] Ubuntu 20.04
 - Python version (if relevant):
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**

While bond and atom information is copied from the input core to the output/matching core, stereochemistry is not.

I can take a look, but if anyone could point me to existing code that does something similar that would be helpful.  I guess the issue would be that the parity/atom ordering round the chiral center in the input core and matching core could be different.

**Comment by DavidACosgrove** [comment]
Hi @jones-gareth
I don't know how the code does the decomposition (and I can't find it in a quick look in the source) but rdmolops.fragmentOnBonds() does preserve the stereo chemistry:
```
from rdkit import Chem
from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D

mol = Chem.MolFromSmiles('F[C@H](Cl)Br')

drawer = rdMolDraw2D.MolDraw2DSVG(500, 500)
drawer.drawOptions().addBondIndices = True
rdMolDraw2D.PrepareMolForDrawing(mol)
drawer.DrawMolecule(mol)
drawer.FinishDrawing()
with open('chir_mol.svg', 'w') as f:
    f.write(drawer.GetDrawingText())

    frag_mol = Chem.FragmentOnBonds(mol, [0])
drawer = rdMolDraw2D.MolDraw2DSVG(500, 500)
drawer.drawOptions().addBondIndices = True
rdMolDraw2D.PrepareMolForDrawing(frag_mol)
drawer.DrawMolecule(frag_mol)
drawer.FinishDrawing()
with open('frag_mol.svg', 'w') as f:
    f.write(drawer.GetDrawingText())
```
goes from
![image](https://user-images.githubusercontent.com/9198870/193867018-cd8a4aa9-3816-429b-a47a-09dada14d33b.png)

to
![image](https://user-images.githubusercontent.com/9198870/193867110-942228c6-43a7-470d-a867-29f51ea858e5.png)

which might be helpful.
Dave
PS. sorry about the enormous pictures.

**Comment by jones-gareth** [comment]
> Hi @jones-gareth I don't know how the code does the decomposition (and I can't find it in a quick look in the source) but rdmolops.fragmentOnBonds() does preserve the stereo chemistry:
> 

@DavidACosgrove Thanks I will check out `fragmentOnBonds()`. Atom and bond typing are copied from to the the core in `RCore::replaceCoreAtomsWithMolMatches`- I think that routine should also set stereochemistry.

**Comment by bp-kelley** [comment]
While RGroupDecomp does use fragment on bonds, if it decides to add an
rgroup, this is outside of that code base and might be where the error is
coming from.

Cheers,
 Brian

**Comment by jones-gareth** [comment]
@bp-kelley I don't understand your comment.  There is no code error, just a missing step in RGD.

We know that RGD does *not* copy stereo centers from a target molecule to the core in the decomposition. @DavidACosgrove is suggesting that we could repurpose the code in `fragmentOnBonds()` to do that missing step in `RCore::replaceCoreAtomsWithMolMatches`.

**Comment by bp-kelley** [comment]
In retrospect, I wasn't referring to fragmentOnBonds, rather the two styles
of core matching used.

**Comment by jones-gareth** [comment]
Yes, I don't believe that stereochemistry is handled at all when there is a attachment to a core atom (with stereo chemistry) that does not have a user-defined label.  That is going to be nasty to fix.

In this case the stereo center is not adjacent to an attachment point.  The core template does not have stereochemistry defined but the target does.  That  stereochemistry should be copied from the target to the output core.  Which should be relatively easy to fix.

> In retrospect, I wasn't referring to fragmentOnBonds, rather the two styles of core matching used.
>

**Comment by greglandrum** [comment]
I agree that this looks like a bug and think it should be relatively straightforward to fix.
@jones-gareth : I would be happy to fix this if you don't want to delve into that part of the bowels of how the RDKit stores/represents stereo

**Comment by greglandrum** [comment]
> @greglandrum That is an offer I'm happy to accept!

Ok; I will take it on. Likely Won't happen for the 2022.09.1 release, but we can get it in the first patch release

**Comment by bp-kelley** [comment]
I’ll look at the nastier problem of non user defined rgroups.

**Comment by jones-gareth** [comment]
I was thinking that rather than trying to  copy all the information from the target molecule to a copy of the query template/labelled core, it could be easier to build the matching core from a copy of the target molecule and the mapping to the query.

**Comment by bp-kelley** [comment]
I was thinking the same.

**Comment by jones-gareth** [comment]
@greglandrum LMK if you are working on this as I am going to try and create a the matching core from a copy of the target molecule (rather than copy atom types etc from the target to a copy of the template).

**Comment by greglandrum** [comment]
Apologies that I didn't end up doing anything here. Thanks for taking it on.

I agree that the current behavior here is confusing, but it has been there for a while and is something that people may have come to rely on, so I set the milestone here to be the 2023.03 release and have flagged it as `changes results`
