### ISSUE TITLE
ReplaceSubstructs() does not seem to generate all possibilities unless using replaceAll=True

### ISSUE THREAD

**Issue by ChemRMB** [rdkit/rdkit#5638]
**Is your feature request related to a problem? Please describe.**
When using Chem.rdmolops.ReplaceSubstructs() not all replacements are given but all are shown when using the replaceAll=True argument.

To reproduce:
```
import copy
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import rdmolops
from rdkit.Chem import rdDepictor
from rdkit import rdBase

from rdkit.Chem import Draw
from rdkit.Chem.Draw import MolsToGridImage
from rdkit.Chem.Draw import IPythonConsole
rdDepictor.SetPreferCoordGen(True)

from IPython.display import display
IPythonConsole.ipython_useSVG = True  # Change output to SVG
IPythonConsole.drawOptions.addAtomIndices = True
IPythonConsole.drawOptions.minFontSize = 18
IPythonConsole.drawOptions.prepareMolsBeforeDrawing = True

replace_CH3 = (('[CX4;H3]','[CH2-]'), ('[CX4;H3]','[CH2+]'), ('[CX4;H3]','[CH2]'))

#THC reference molecule
ref_mol = Chem.MolFromSmiles('CCCCCC1=CC2=C([C@@H]3C=C(C)CC[C@H]3C(C)(C)O2)C(O)=C1')
print('reference')
display(ref_mol)
lst_atoms = []
lst_new_mols = []

ref_mol_kekulized = copy.deepcopy(ref_mol)
Chem.Kekulize(ref_mol_kekulized,clearAromaticFlags=True)

for (smarts, smiles) in replace_CH3:
  patt1 = Chem.MolFromSmarts(smarts)
  patt2 = Chem.MolFromSmiles(smiles)
  atoms = ref_mol_kekulized.GetSubstructMatches(patt1)
            
  if len(atoms) != 0:
      [lst_atoms.append(element) for tupl in atoms for element in tupl]
      new_mol = Chem.rdmolops.ReplaceSubstructs(ref_mol_kekulized, patt1, patt2)
      single_replaced_mols = Chem.rdmolops.ReplaceSubstructs(ref_mol_kekulized, patt1, patt2)
      all_replaced_mol = Chem.rdmolops.ReplaceSubstructs(ref_mol_kekulized, patt1, patt2, replaceAll=True)
      lst_new_mols += single_replaced_mols
      lst_new_mols.append(all_replaced_mol[0])

sanitized_mols = []
for m in lst_new_mols:
  [atom.SetAtomMapNum(0) for atom in m.GetAtoms()]
  sanitized_mols.append(Chem.MolFromSmiles(Chem.MolToSmiles(m)))

display(Draw.MolsToGridImage(sanitized_mols, molsPerRow=5, subImgSize=(200,200)))
```
![Screenshot 2022-10-21 at 08 39 40](https://user-images.githubusercontent.com/97344965/197129718-3feb6f38-02f0-4bfd-8666-d0f179ee7510.png)

In this example, the molecules in the 2nd and 3rd column is the same for each row. The last one is with replaceAll=True

**Describe the solution you'd like**
It seems that Chem.rdmolops.ReplaceSubstructs() does not use stereochemistry information to determine the replacement. If there is a check for the previous replacement or if ReplaceSubstructs() adds stereochemistry to the replacement, it may generate all possible combinations.

It may be related to a drawing issue:
https://github.com/rdkit/rdkit/issues/5637

**Comment by greglandrum** [comment]
Hi @ChemRMB: please include the code which demonstrates the problem in the issue report, not in some external source like a colab notebook which may change/vanish at some point in the future.

**Comment by ChemRMB** [comment]
Hi @greglandrum: Sorry about that. I have added the code that demonstrates the issue. I hope it helps.
Let me know if you need more details.

**Comment by greglandrum** [comment]
@ChemRMB the sample code above does not work, so I can't make any progress on figuring out what's going on here.

**Comment by ChemRMB** [comment]
Hi @greglandrum. Thank you for looking into it. Sorry, forgot to add a single line of code. I Have added that now and the code works on my side. I have also updated the picture to fully show what the code produces.
