### ISSUE TITLE
Is there a way to generate native libraries that work with all Java versions

### ISSUE THREAD

**Issue by tnguy271** [rdkit/rdkit#5650]
I'm using Java 11 now and the native libraries I generated (libGraphMol) can only work with Java 11, not other versions. Is there anyways to generate native libraries to work with all Java version?

**Comment by greglandrum** [comment]
This is a question, not a big report, which we have specifically asked people not to do. On top of that, you have posted the same question in multiple places.
Please do not spam projects this way
