### ISSUE TITLE
"undefined symbol" error when importing rdkit.Chem in fresh conda installation

### ISSUE THREAD

**Issue by mgarort** [rdkit/rdkit#5652]
Dear RDKit team,

I have encountered an issue related to the Boost library that prevents me to import `Chem`. Specifically, when I attempt to run the line `import rdkit.Chem as Chem`, the following error appears:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

     10 import torch
     11 import rdkit
---> 12 import rdkit.Chem as Chem
     13 from rdkit import DataStructs
     14 from itertools import product

File ~/housekeeping/miniconda3/envs/dc_gpu/lib/python3.9/site-packages/rdkit/Chem/__init__.py:23, in <module>
     21 _HasSubstructMatchStr = rdchem._HasSubstructMatchStr
     22 from rdkit.Chem.rdchem import *
---> 23 from rdkit.Chem.rdmolfiles import *
     24 from rdkit.Chem.rdmolops import *
     25 from rdkit.Chem.rdCIPLabeler import *

ImportError: /home/mg770/housekeeping/miniconda3/envs/dc_gpu/lib/python3.9/site-packages/rdkit/Chem/../../../../libRDK
itmaeparser.so.1: undefined symbol: _ZN5boost9iostreams4zlib8deflatedE
```
As far as I can see, this is exactly the same bug as in [issue 93 of the conda-forge repo](https://github.com/conda-forge/rdkit-feedstock/issues/93). According to the issue page it is fixed, but I am still getting it in a fresh conda installation. I have encountered the error when installing RDKit in a Python 3.7, 3.8 and 3.9 environments. In a different project I fixed this error by installing RDKit in a Python 3.10 environment, but unfortunately in this project I cannot use 3.10 because of compatibility issues.

I am installing from `conda-forge`, which is the recommended channel to use in the [RDKit installation page](https://www.rdkit.org/docs/Install.html). Could you let me know if there is anything I can do to avoid this error?

Thanks a lot in advance.

-------------------------

**Specifications**
 - RDKit version:  2022.03.2
 - OS: Scientific Linux release 7.9 (Nitrogen)
 - Python version (if relevant): 3.7, 3.8, 3.9
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from?  `conda-forge`

**Comment by greglandrum** [comment]
Please report this in the rdkit conda-forge repo. There's nothing we can do about problems like this on the RDKit side.

**Comment by mgarort** [comment]
Hi @greglandrum 

Thank you for your swift response. I have reposted on the conda RDKit repo in [this issue](https://github.com/conda-forge/rdkit-feedstock/issues/111).

Thanks.
