### ISSUE TITLE
EmbedMultipleConfs without explicit H : no output and no error message

### ISSUE THREAD

**Issue by petroninflorent** [rdkit/rdkit#5664]
Hello Rdkit team and thank you for your time,

Bug description :
I'm trying to generate conformers. It fails for some molecules if I don't add the explicit hydrogens.
In these cases, the program doesn't produce any error message.

Example :

from rdkit import Chem
from rdkit.Chem import AllChem

sdf_file_in = "Ajugasterone-C.sdf"
#sdf_file_in = "20-hydroxyecdysone.sdf"
sdf_file_out = "test_out.sdf"

supplier = Chem.SDMolSupplier(sdf_file_in)

f = open(sdf_file_out, "w")
for molecule in supplier :

	numberConf=50
	param = AllChem.ETKDGv3()
	param.useSmallRingTorsions = True
	param.randomSeed = 123
	param.pruneRmsThresh = 1.25
	param.onlyHeavyAtomsForRMS = True
	param.numThreads = 0 #use all threads of the computer
	#molecule = Chem.AddHs(molecule)

	block = Chem.MolToMolBlock(molecule)
	name=block[:block.find('\n')]

	ids = AllChem.EmbedMultipleConfs(molecule,numConfs=int(numberConf),params=param)
	
	for conf_num in ids:
		block = Chem.MolToMolBlock(molecule, True, conf_num)
		block_without_id = block[block.find('\n'):]
		true_conf_num = conf_num + 1
		id_line=name + "_" + str(true_conf_num)

		f.write(id_line)
		f.write(block_without_id)
		f.write("$$$$\n")
f.close()

[20-hydroxyecdysone.sdf.gz](https://github.com/rdkit/rdkit/files/9810206/20-hydroxyecdysone.sdf.gz)
[Ajugasterone-C.sdf.gz](https://github.com/rdkit/rdkit/files/9810207/Ajugasterone-C.sdf.gz)

If you try, you'll see it works fine for 20-hydroxyecdysone.sdf, but doesn't produce anything for Ajugasterone-C.sdf. (No output, no error message, it merely suggest to add the explicit H, but the program always do that when I don't add them)
If you uncomment "molecule = Chem.AddHs(molecule)", you'll see it works for both.

Expected behavior :
-I expect the program to generate conformers, even without explicit Hydrogens.
-If the program fails, I expect an error message.

Why I don't wan't to add the hydrogens : 
-It adds noticeable generation time.
-It messes with the RMS, even though it shouldn't (param.onlyHeavyAtomsForRMS = True), which leads to a different number of conformers generated... but that's a bug for another day.

Configuration :
- RDKit version: 2022.03.5
- OS: Ubuntu 22.04.1 LTS
- Python version :  Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] on linux
- I'm using conda
- How did I installed rdkit : conda install -c conda-forge rdkit

Thank you for investigating the problem,

Florent.

**Comment by greglandrum** [comment]
This isn't a bug. Problems should be expected when trying to generate conformers for molecules which don't have hydrogens added (that's why you get the warning message). The presence of the H atoms makes it easier for the code to generate physically reasonable conformers.

The conformer generation code, by design, does not generate error messages when it fails. You can detect failures by looking at the return value: `EmbedMultipleConfs()` should return an empty list if it cannot generate any conformers and `EmbedMolecule()` returns a conformer id of -1.
