### ISSUE TITLE
PNG to mols does not work in a code

### ISSUE THREAD

**Issue by andresilvapimentel** [rdkit/rdkit#5668]
The command line 
mols = Chem.MolsFromPNGString(figure)
does not work in the code below:

smiles_list = ['N[C@H](C(=O)O)C','C[C@H](N)C(=O)O','OC(=O)[C@@H](N)C', 'OC(=O)[C@H](C)N']
mol_list = []
for smiles in smiles_list:
  mol = Chem.MolFromSmiles(smiles)
  mol_list.append(mol)
img =Draw.MolsToGridImage(mol_list, molsPerRow = 4)
img

glycine = mol_list[0]

bi = {}
fp = AllChem.GetMorganFingerprintAsBitVect(glycine, 2, nBits = 1024, bitInfo = bi)
fp_arr = np.zeros((1,))
DataStructs.ConvertToNumpyArray(fp, fp_arr)
np.nonzero(fp_arr)
list(fp.GetOnBits())

prints = [(glycine, x, bi) for x in fp.GetOnBits()]
figure = Draw.DrawMorganBits(prints, molsPerRow = 4, legends = [str(x) for x in fp.GetOnBits()])
mols = Chem.MolsFromPNGString(figure)
for mol in mols:
    figure_list.append(Chem.MolToSmiles(mol))

Is there anything wrong?

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
