### ISSUE TITLE
Are `MinPartialCharge` and `MaxPartialCharge` supposed to be within [-500, 500] ?

### ISSUE THREAD

**Issue by maclandrol** [rdkit/rdkit#5674]
The current implementation of PartialCharge Descriptor in rdkit, forces `min charge <= 500` and `max charge >= -500`, but this is not equivalent to ensuring that the partial charges are within a `[-500, 500]` range. 

https://github.com/rdkit/rdkit/blob/913a81b97a052fff4ca94c8c2df7df2de9b4070a/rdkit/Chem/Descriptors.py#L150-L160

Is this the desired behaviour ? Also is there a rational behind using `500` ?

**Comment by UnixJunkie** [comment]
I think the goal of this code is to find the min and max partial charges in the molecule.
500 is used instead of +inf; -500 is used instead of -inf.
The absolute value of any partial charge should be way lower than 500.

**Comment by UnixJunkie** [comment]
@maclandrol maybe this can be closed; unless you still have a problem with it

**Comment by UnixJunkie** [comment]
Ok, so you did find a numerical bug where this code can return inf or nan.
