### ISSUE TITLE
fp.ToList() fails for empty molecule

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#5677]
RDKit: 2021.09.5

```
from rdkit import Chem
from rdkit.Chem import AllChem
smi = ""
mol = Chem.MolFromSmiles(smi)
assert mol.GetNumAtoms() == 0
fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=1024)
print(fp.ToList())
```

I would expect this to produce a list of 1024 zeroes. Instead I get:

`IndexError: cannot fit 'int' into an index-sized integer`

**Comment by bp-kelley** [comment]
The fix is pretty simple, in wrap_ExplicitBV we don't check to see if there are no bits set:

```
    auto pos = sv.dp_bits->find_first();
    l[pos] = 1;
```

I'll make a quick PR
