### ISSUE TITLE
Use `BUILD_TEST` CMake option to allow skipping building *all* tests

### ISSUE THREAD

**Issue by giordano** [rdkit/rdkit#5680]
**Is your feature request related to a problem? Please describe.**

It'd be nice to have ***a single*** option to skip building ***all*** tests.

**Describe the solution you'd like**

Luckily CMake CTest module has already the solution: the [`BUILD_TESTING`](https://cmake.org/cmake/help/latest/module/CTest.html) option.  You only need to actually use it.

**Comment by giordano** [comment]
For what is worth, [my troubles](https://github.com/JuliaPackaging/Yggdrasil/pull/5728#issuecomment-1288210485) are solved by #5697, but I still think that a general (and standard) option may be useful next to more piecemeal options like `RDK_BUILD_CPP_TESTS` and `RDK_TEST_MULTITHREADED`.

**Comment by greglandrum** [comment]
There’s only one option which actually changes what is built: `RDK_BUILD_CPP_TESTS`
So I’m not sure what benefit this would bring

**Comment by greglandrum** [comment]
I’m closing this because I think the existing option does what this requests. Please reopen if I have missed something
