### ISSUE TITLE
202209.1 build fails on Debian unstable

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#5685]
**Describe the bug**
Build failure:
```
/usr/bin/clang-14 -xc++ -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/usr/local/include -I/<<PKGBUILDDIR>>/Code -DRDKITVER='"007300"' -DRDK_TOOLKIT_VERSION='"2021.09.02"'   -I. -I/<<PKGBUILDDIR>>/Code/PgSQL/rdkit -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -emit-llvm -c -o adapter.bc /<<PKGBUILDDIR>>/Code/PgSQL/rdkit/adapter.cpp
In file included from /<<PKGBUILDDIR>>/Code/PgSQL/rdkit/adapter.cpp:49:
In file included from /<<PKGBUILDDIR>>/Code/GraphMol/RDKitBase.h:23:
In file included from /<<PKGBUILDDIR>>/Code/GraphMol/Atom.h:25:
In file included from /<<PKGBUILDDIR>>/Code/RDGeneral/types.h:28:
/<<PKGBUILDDIR>>/Code/RDGeneral/Dict.h:261:26: error: no template named 'is_same_v' in namespace 'std'; did you mean 'is_same'?
    static_assert(! std::is_same_v<T, std::string_view>,
                    ~~~~~^~~~~~~~~
                         is_same
```

This seems to be related to c++17 and clang-14.

Recompiling 202203.2 with Postgres-15 support (Debian has recently switched) works fine and the same clang command-line is run.

**To Reproduce**
Build rdkit on Debian unstable

**Expected behavior**
Build succeeds

**Configuration (please complete the following information):**
 - RDKit version: 2209.1
 - OS: Debian unstable
 - Python version (if relevant): 3.10.6
 - Are you using conda? no
 - If you are not using conda: how did you install the RDKit? Debian unstable

**Comment by greglandrum** [comment]
Hi @mbanck, I’m not sure what we should do here. That is a valid C++17 construct and the 2022.09 release does require C++17.

Could you add a patch on your side until you can use a compiler which fully supports the standard. I can probably help come up with the patch.

**Comment by mbanck** [comment]
Ah, looks like one has to add `-std=c++17` to `COMPILE.cxx.bc` in `Code/PgSQL/rdkit/Makefile` (which isn't used by default)
