### ISSUE TITLE
rdkit Recap.RecapDecompose run speed very slow

### ISSUE THREAD

**Issue by lonngxiang** [rdkit/rdkit#5691]
Recapkit Recap.RecapDecompose runs particularly slowly on macromolecules and can get stuck

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
