### ISSUE TITLE
Thread unsafety when rdRGroupDecomposition  is called on the same molecule in different threads

### ISSUE THREAD

**Issue by KrisVolkova** [rdkit/rdkit#5713]
**Describe the bug**
Calling rdRGroupDecomposition on the same molecule from multiple threads can result in undefined behavior.

For me, that usually manifests as a process exit with signal: 6, SIGABRT but behavior can vary.

**To Reproduce**
`from rdkit.Chem import rdRGroupDecomposition as rgd
`
```
def run_rgd_yan_case():
   print("Starting rgd yan failed case")
   result = RGroupDecompositionJob(
...
        library="rdkit",
    ).run_job()
    print("Rgd completed")
    return result
```

**Expected behavior**

**Configuration:**
RDKit version: a recent clone of the master branch
OS: Widnows
Python: 3.9.5
Conda use

**Comment by bp-kelley** [comment]
@KrisVolkova there isn't quite enough data here to reproduce the issue.  What is RGroupDecompositionJob?  I'm assuming it's a thread operation.  It would be useful to know exactly what you are calling so we can track this down.

**Comment by KrisVolkova** [comment]
@bp-kelley Hello!
Information:
data 
"Nc1nc2ccc(OC(F)(F)F)cc2s1"
I ran tasks
YAN_DATASET = {"data": [
    ["6336afb188a2b21614709c07", "Nc1nc2ccc(OC(F)(F)F)cc2s1"],
def run_rgd_yan_case():
    print("Starting rgd yan failed case")
    result = RGroupDecompositionJob(
        data=YAN_DATASET["data"],
        library="rdkit",
    ).run_job()
    print("Rgd completed")
    return result

RGroupDecompositionJob:
class RGroupDecompositionJob(BaseJob):
    def calculateProperties(self, sub_type: str, mol: Any) -> dict[str, Any]:
        try:
            smiles = ""
            molfile = ""
            if self.is_mol():
                smiles = Chem.MolToSmiles(mol)
                molfile = self.__mol_to_mol_block(mol)

When I use different methods of RDKit I have Sigabort 6 - but I run it on RQ!
Thanks

**Comment by bp-kelley** [comment]
This still isn't enough for me to actually run your code to test.  Could you supply a full running example please?
