### ISSUE TITLE
Drawing molecules with the comicMode option set to True can run forever.

### ISSUE THREAD

**Issue by lucasmorin222** [rdkit/rdkit#5715]
**Describe the bug**
Calling drawer.DrawMolecule() with the option comicMode set to True can run forever.
Here is a specific example, after setting the size of a bond to a value close to 0 and the drawing option comicMode to True, the method drawer.DrawMolecule() does not return.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import rdMolTransforms, rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D

molecule = Chem.MolFromSmiles("CC")
rdDepictor.Compute2DCoords(molecule) 
rdMolTransforms.SetBondLength(molecule.GetConformer(0), 0, 1, 1e-20)

drawer = rdMolDraw2D.MolDraw2DSVG(1024, 1024, -1, -1, False)
options = drawer.drawOptions()
options.comicMode = True 
drawer.DrawMolecule(molecule) # Does not return
drawer.FinishDrawing()
image_svg = drawer.GetDrawingText()
```

**Expected behavior**
The previous example does not return. 

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2022.3.5
 - OS: Ubuntu 20.04.5
 - Python version (if relevant): 3.9.13
 - Are you using conda?  No
 - If you are using conda, which channel did you install the rdkit from?  
 - If you are not using conda: how did you install the RDKit?  pip install rdkit-pypi

**Additional context**
It would be helpful to know when setting comicMode to True is risky.

**Comment by DavidACosgrove** [comment]
Hi @lucasmorin222,
Better than guidelines about when not to use comicMode, I will fix the underlying bug. 
Thanks for the clear and concise report and example. 
Dave

**Comment by lucasmorin222** [comment]
Hello @DavidACosgrove,
Thanks a lot! It works on ubuntu too. 
Sorry, I should have tried with the latest RDKit version. 
Best regards,
Lucas
