### ISSUE TITLE
rdkit.Chem.rdmolops.PathToSubmol() return a wrong Mol object

### ISSUE THREAD

**Issue by Pang-chao** [rdkit/rdkit#5717]
**Describe the bug**
use `PathToSubmol` will get unreasonable output in some cases.

**To Reproduce**
```
test_smiles = 'c1ccc(-n2cnnn2)cc1'
mol = Chem.MolFromSmiles(test_smiles)
aid_dict = [4,5,6,7,8]
edge_indices = []
for i in range(mol.GetNumBonds()):
    bond = mol.GetBondWithIdx(i)
    begin_aid = bond.GetBeginAtomIdx()
    end_aid = bond.GetEndAtomIdx()
    if begin_aid in aid_dict and end_aid in aid_dict:
        edge_indices.append(i)
    
submol = Chem.PathToSubmol(mol, edge_indices)
subsmi = Chem.MolToSmiles(submol)  # subsmi: c1nnnn1
```
In this case above, the N atom has a bond outside the desired subgraph. The function does not add an explicit H to this N atom, resulting in the output of an unreasonable Mol object.

**Expected behavior**
subsmi should be 'c1nnn[nH]1'

**Screenshots**
![rdkit](https://user-images.githubusercontent.com/73026540/199251303-d78e0c3f-8a8a-43de-b8c9-c1081e7e3dcd.png)

**Configuration (please complete the following information):**
 - RDKit version: 2021.09.5
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.9.10
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
@Pang-chao I understand what you are asking for, but I believe that you're expecting the wrong thing from `PathToSubmol()` and  don't agree that there's a bug here.

`PathToSubmol()` is designed to extract a completely arbitrary substructure of a molecule, not just something which may be a reasonable molecule on its own. So, for example, you can do something like:
```
In [2]: m = Chem.MolFromSmiles('Cc1ccccc1')
In [3]: subm = Chem.PathToSubmol(m,[0,1])
```
which gives you back an aliphatic C connected to two aromatic Cs. That certainly can't be kekulized.

If you are just looking to generate images of the submolecules without having errors show up, you can pass the `kekulize=False` argument to `MolToImage()`:
```
In [4]: img = Draw.MolToImage(subm,size=(200,200),kekulize=False)
```
Note that `useSVG` is not a valid argument to `MolToImage()` and will just be ignored.

**Comment by Pang-chao** [comment]
Thank you for your comment! Now I understand why this case is not a bug. Sorry for adding a wrong label. But I still have a question. I want to get a substructure that can be kekulized, so is there a way to convert 'c1nnnn1' to 'c1nnn[nH]1' ? (I know there are more than one result after conversion, but it doesn't matter for my work.)

**Comment by bp-kelley** [comment]
One trick is to delete every atom not in the extracted path.  This might not always produce a valid molecule, but it will capture the context of the match.

note that deleting atoms changes their index, so either use the batch editing feature or delete atoms in reverse atom index order.
