### ISSUE TITLE
addBond return value

### ISSUE THREAD

**Issue by JLVarjo** [rdkit/rdkit#572]
Hi,

according to docs, the function RWMol::addBond should return the index of a newly added bond. 
In the function, the index of a new bond is set as follows:

unsigned int res = boost::num_edges(d_graph);
b->setIdx(res-1);

but then the function returns just "res", instead of  "res-1". Bug, right?

Best,
Juuso Lehtivarjo

**Comment by greglandrum** [comment]
It's ok in the C++ documentation, which is clear that it returns the number of bonds:
https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/RWMol.h#L132

it is, however, a problem in the python wrapper: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Wrap/Mol.cpp#L501
