### ISSUE TITLE
Missing update path for postgreSQL from 3.8 to 4.2

### ISSUE THREAD

**Issue by Deltaus** [rdkit/rdkit#5734]
**Describe the bug**
When doing the postgres major upgrade, or just upgrading rdkit itself, it'll report missing update path script for 3.8->4.2. Currently we only have scripts for 3.8->4.0 and 4.0->4.1 in 2022_03_1/2022_03_5/2022_09_1, etc.

**To Reproduce**
Upgrading rdkit in postgreSQL

**Expected behavior**
Upgrade without error.

**Configuration (please complete the following information):**
 - RDKit version: 3.8
 - OS: [e.g. Ubuntu 20.04] amazon linux 2

**Comment by greglandrum** [comment]
Yep; that was an oversight. I will fix it for the patch release.
Thanks for pointing out the problem
