### ISSUE TITLE
Full capabilities for Reaction SMARTS in Minimallib

### ISSUE THREAD

**Issue by jmyounk** [rdkit/rdkit#5744]
Request to include full capabilities for Reaction SMARTS in Minimallib.  We wish to call function from Julia.

https://www.rdkit.org/docs/source/rdkit.Chem.rdChemReactions.html

**Comment by greglandrum** [comment]
@jmyounk : the idea of minimallib is that it includes a minimal, but useful, subset of the RDKit functionality. It's not supposed to be a full wrapper of the RDKit.
We are happy to add stuff that seems broadly useful, but "include full capabilities" isn't something that we will do.

If you provide specific examples of functionality that you'd like to use, we can take a look and consider adding it.

**Comment by jmyounk** [comment]
from rdkit import Chem
from rdkit.Chem import AllChem
rxn = AllChem.ReactionFromSmarts('[Zr][CH3:1].[CH2:2]=[CH2:3]>>[Zr][CH2:2][CH2:3][CH3:1]')
reacts = (Chem.MolFromSmiles('[Zr]CCCCC(C)CCCC'),Chem.MolFromSmiles('C=C'))
products = rxn.RunReactants(reacts)

**Comment by jmyounk** [comment]
Greg,

This is an example of the C++ code I'd like to see wrapped:

https://www.rdkit.org/docs/cppapi/classRDKit_1_1ChemicalReaction.html

       std::string smi="[O:1]>>[N:1]";
       ChemicalReaction *rxn = RxnSmartsToChemicalReaction(smi);
       rxn->initReactantMatchers();

       MOL_SPTR_VECT reacts;
       reacts.clear();
       smi = "OCO";
       ROMol *mol = SmilesToMol(smi);
       reacts.push_back(ROMOL_SPTR(mol));
       std::vector<MOL_SPTR_VECT> prods;
       prods = rxn->runReactants(reacts);
       // here prods has two entries, because there are two Os in the
       // reactant.

       reacts[0]->getAtomWithIdx(0)->setProp(common_properties::_protected,1);
       prods = rxn->runReactants(reacts);
       // here prods only has one entry, the reaction at atom 0
       // has been blocked by the _protected property
