### ISSUE TITLE
Thread unsafety in initial call to `SmilesToMol`.

### ISSUE THREAD

**Issue by bddap** [rdkit/rdkit#5746]
*On program initialization*, calling `SmilesToMol` from multiple threads at the same time sometimes invokes ub. Possible manifestations of the issue include:
- `value: Kekulization somehow screwed up valence on 6: 2!=3`
- `double free or corruption (fasttop)
  malloc_consolidate(): invalid chunk size`
- `double free or corruption (fasttop)
  corrupted size vs. prev_size in fastbins`

**To Reproduce**

When calling `SmilesToMol` for the first time in a program's execution, call it simultaneously from multiple threads. Rerun the program 100 or so times until a crash occurs. `while ./program; do :; done`

**Configuration:**
RDKit version: a recent clone of the master branch
OS: Ubuntu 22.04

**Additional context**
This may not be reproducible in python due to GIL.

**Comment by bddap** [comment]
The exact smiles used doesn't seem to matter. The issue can be reproduced using `"C"` as the input to `SmilesToMol`

**Comment by bddap** [comment]
This issue is not reproducible on my friend's Mac with an m1 processor. If you are using an m1 you might have trouble reproducing the error.

**Comment by greglandrum** [comment]
@bddap : these kinds of things can be quite tricky to track down, but I would definitely like to try. Can you provide code to reproduce the problem?

**Comment by bddap** [comment]
The rust bindings I'm using to trigger this error are not open sourced yet.

I'd be happy to put together a pure c++ reproduction but it's a non-trivial task to import rdkit as c++ dependency. You wouldn't happen to have a guide somewhere? Or a sample project importing rdkit?

**Comment by bddap** [comment]
Oh, maybe these docs will do the trick. https://www.rdkit.org/docs/Install.html#linux-and-os-x
