### ISSUE TITLE
CDXML reader incorrectly sets stereo on crossed double bonds

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#5752]
RDKit: 2022.09.1

I've been playing around with pycdxml from @kienerj, and testing it by roundtripping MOL files against the RDKit's CDXML reader. Here's a failure case which seems to be due to the RDKit reader.

If you open the following MOL file in ChemDraw:
[CHEMBL4303146.mol.txt](https://github.com/rdkit/rdkit/files/9995609/CHEMBL4303146.mol.txt)
![image](https://user-images.githubusercontent.com/45337/201488538-b6b6d53c-7c28-4c8c-99e0-fa3258c65524.png)

...and save as CDXML:
[CHEMBL4303146.cdxml.txt](https://github.com/rdkit/rdkit/files/9995611/CHEMBL4303146.cdxml.txt)
...then RDKit's reader sets the stereo on the crossed double bond instead regarding it as unknown. That is,
```
from rdkit import Chem

fnames = ["CHEMBL4303146.fromcd.cdxml"]
for fname in fnames:
    mols = Chem.MolsFromCDXMLFile(fname)
    cansmi = Chem.MolToSmiles(mols[0])
    print(cansmi)
```
gives
```
Cc1cccc(C)c1NC(=O)/N=C1\CCCN1C
```

**Comment by bp-kelley** [comment]
Thanks for the report, I’ll check it this afternoon.

----
Brian Kelley

**Comment by baoilleach** [comment]
FYI, according to pycdxml code, both BS=N and DisplayStyle=Wavy are required to be set. No idea on what ChemDraw does with just one or the other.

**Comment by bp-kelley** [comment]
It looks like I was completely ignoring these and the stereo is getting set
from the drawing.  Whups.

**Comment by bp-kelley** [comment]
DisplayStyle=Wavy and BS=N are not sufficient, you need to be a double bond as well, at least in RDKit land.

**Comment by kienerj** [comment]
> DisplayStyle=Wavy and BS=N are not sufficient, you need to be a double bond as well, at least in RDKit land.

Yes it also needs `Order="2"` in cdxml to count as a double bond and be displayed as a crossed double bond. Without it it looks like the single wavy bond.

> FYI, according to pycdxml code, both BS=N and DisplayStyle=Wavy are set. No idea on how ChemDraw interprets just one or the other.

The ` Display="Wavy"` is needed so it looks wavy. Some basic testing tells me with just `BS=N`, ChemDraw determines stereochemistry from coordinates and then fixes the setting.

**Comment by bp-kelley** [comment]
BS is for cip stereo I think which we reperceive anyway.  A wavy bond with cip stereo seems wrong so I’m taking precedence on the wavy bond for now.

**Comment by kienerj** [comment]
Makes sense. ChemDraw writes it out as BS=N when drawing a crossed bond but it will read the cross-bond just fine when BS is omitted or set to say "E". eg "Display" has precedence in chemdraw as well.
