### ISSUE TITLE
rdMolStandardize

### ISSUE THREAD

**Issue by TheophileGaudin** [rdkit/rdkit#5757]
**The bug:**

I have two conformers with names:
XXIIIc_struct_0_c1.energy.mol
XXIIIc_struct_0_c2.energy.mol

I've attached them to this Issue:
[mol_files.zip](https://github.com/rdkit/rdkit/files/10005647/mol_files.zip)

I am looking for self-defined rotatable bonds in them and I want to be able to compare the rotatable bonds, so I need the indexing to be consistent. Therefore I standardize the indexing. 

RDkit gives different atom indices for identical atoms in two different conformers. I don't know if it is actually possible to have the indices matching but if it is, then I would expect that the standardization procedure from RDkit would work here.

**To reproduce**

Minimal code example below:

```
    import rdkit
    from rdkit                          import Chem
    from rdkit.Chem.MolStandardize      import rdMolStandardize
    
    print(rdkit.__version__)
    m = Chem.MolFromMolFile("XXIIIc_struct_0_c1.energy.mol")
    m = rdMolStandardize.Cleanup(m)
    rot_atom_pairs = m.GetSubstructMatches(Chem.MolFromSmarts("[!$(*#*)&!D1,H1,H2]-!@[!$(*#*)&!D1,H1,H2]"))
    rot_atom_labels = list()
    for i in range(len(rot_atom_pairs)):
        rot_atom_labels.append([m.GetAtomWithIdx(rot_atom_pairs[i][0]).GetSymbol(), m.GetAtomWithIdx(rot_atom_pairs[i][1]).GetSymbol()])
    print("XXIIIc_struct_0_c1.energy.mol", Chem.MolToSmiles(m))
    print(rot_atom_pairs)
    m2 = Chem.MolFromMolFile("XXIIIc_struct_0_c2.energy.mol")
    m2 = rdMolStandardize.Cleanup(m2)
    rot_atom_pairs = m2.GetSubstructMatches(Chem.MolFromSmarts("[!$(*#*)&!D1,H1,H2]-!@[!$(*#*)&!D1,H1,H2]"))
    rot_atom_labels = list()
    for i in range(len(rot_atom_pairs)):
        rot_atom_labels.append([m2.GetAtomWithIdx(rot_atom_pairs[i][0]).GetSymbol(), m2.GetAtomWithIdx(rot_atom_pairs[i][1]).GetSymbol()])
    print("XXIIIc_struct_0_c2.energy.mol", Chem.MolToSmiles(m2))
    print(rot_atom_pairs)
```
**Output:**

> 2022.09.1
> XXIIIc_struct_0_c1.energy.mol O=C(O)c1ccccc1Nc1ccc(CCc2ccc(Cl)c(Cl)c2)cc1
> ((1, 10), (3, 15), (3, 8), (4, 10), (12, 18), (17, 20), (17, 18))
> XXIIIc_struct_0_c2.energy.mol O=C(O)c1ccccc1Nc1ccc(CCc2ccc(Cl)c(Cl)c2)cc1
> ((1, 10), (3, 8), (3, 15), (4, 10), (12, 18), (17, 20), (17, 18))

**Expected output:**

> 2022.09.1
> XXIIIc_struct_0_c1.energy.mol O=C(O)c1ccccc1Nc1ccc(CCc2ccc(Cl)c(Cl)c2)cc1
> ((1, 10), (3, 8), (3, 15), (4, 10), (12, 18), (17, 20), (17, 18))
> XXIIIc_struct_0_c2.energy.mol O=C(O)c1ccccc1Nc1ccc(CCc2ccc(Cl)c(Cl)c2)cc1
> ((1, 10), (3, 8), (3, 15), (4, 10), (12, 18), (17, 20), (17, 18))

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.1
 - OS: Win 10 64bits
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? pip install rdkit

**Comment by bp-kelley** [comment]
This is being caused because the bonds are not in the same order in your example files.

While the mol standardizer does canonically orders atoms, it does *not* canonically order bonds so the substructure search actually follows different paths in the molecule since your query only returns a single 'bond' per match as reported by the start and end atoms.

However, in this case your results are identical, just ordered differently, so a 

```
rot_atom_pairs.sort()
```

will solve your problem.

That being said, I think canonically ordering a molecule should also canonically order the bonds.

**Comment by greglandrum** [comment]
@TheophileGaudin : @bp-kelley  is correct that the problem is the different ordering of the bonds in the two files. The standardizer doesn't do anything to canonicalize either atom or bond order, so there's no reason to expect that the substructure matches would come back in any particular order.

If you want the results in a canonical order then I would suggest using a sort function like the following:
```
def canonicalize_atom_pair_list(seq):
    res = [(min(a,b), max(a,b)) for a,b in seq]        
    return tuple(sorted(res))
```
note that you need to make sure the individual 2-tuples are also sorted since your substructure query is symmetrical.

**Comment by greglandrum** [comment]
> While the mol standardizer does canonically orders atoms

Just to be clear here for future readers: the standardizer does not canonically order atoms

**Comment by TheophileGaudin** [comment]
@greglandrum 

Hi,

Thanks for your reply.

So, 

>  The standardizer doesn't do anything to canonicalize either atom or bond order

I don't get it. Does this mean that two identical atoms in the two different structures will end up with a different index even after the rdMolStandardize.Cleanup() call?

**Comment by greglandrum** [comment]
> I don't get it. Does this mean that two identical atoms in the two different structures will end up with a different index even after the rdMolStandardize.Cleanup() call?

I'm not sure what you mean by "identical atoms in different structures", but the Cleanup() call does not attempt to reorder the atoms in any sort of canonical way.

**Comment by TheophileGaudin** [comment]
@greglandrum 
> I'm not sure what you mean by "identical atoms in different structures", but the Cleanup() call does not attempt to reorder the atoms in any sort of canonical way.

What I mean is, let's say in the non cleaned up structures the index of the N atom is 13 for one of the files and 17 for the other file. Does the Cleanup end up with the N atom having an identical index in both structures? (for example 3)

**Comment by greglandrum** [comment]
@TheophileGaudin : it does not

**Comment by greglandrum** [comment]
If the two molecules generate the same canonical SMILES (i.e they correspond to the same graph), you can get the canonical atom numbering with `Chem.CanonicalRankAtoms()` and then use that to create a dictionary mapping atom ranks to atom indices. Here's a simple example:
```
In [8]: m1 = Chem.MolFromSmiles('OCCC')

In [9]: m2 = Chem.MolFromSmiles('CCCO')

In [10]: list(Chem.CanonicalRankAtoms(m1))
Out[10]: [1, 3, 2, 0]

In [11]: dict(zip(Chem.CanonicalRankAtoms(m1),range(m1.GetNumAtoms())))
Out[11]: {1: 0, 3: 1, 2: 2, 0: 3}

In [12]: dict(zip(Chem.CanonicalRankAtoms(m2),range(m2.GetNumAtoms())))
Out[12]: {0: 0, 2: 1, 3: 2, 1: 3}
```
So the rank 0 atom in m1 is number 3 and the rank 0 atom in m2 is number 0
