### ISSUE TITLE
`R` atom label information lost in molfile if not backed by a `M RGP` entry

### ISSUE THREAD

**Issue by eloyfelix** [rdkit/rdkit#5763]
**Describe the bug**

We've encountered some molfiles in ChEBI with `R` atoms that are not backed by a `M RGP` entry. 
RDKit replaces the `R` with a star `*` and it is not possible to know, even with the `mol.Debug()` function that the original molfile had that `R` symbol/label there

**To Reproduce**

```python
from rdkit import Chem

molfile = """
  MJ221900                      

  4  3  0  0  0  0  0  0  0  0999 V2000
    2.1433    1.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4289    2.0625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.8578    2.0625    0.0000 R   0  0  0  0  0  0  0  0  0  0  0  0
    2.1433    0.8250    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  4  1  2  0  0  0  0
M  END"""

mol = Chem.MolFromMolBlock(molfile)
mol.Debug()
```

```
Atoms:
	0 6 C chg: 0  deg: 3 exp: 4 imp: 0 hyb: 3 arom?: 0 chi: 0
	1 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
	2 0 * chg: 0  deg: 1 exp: 1 imp: 0 hyb: 0 arom?: 0 chi: 0
	3 8 O chg: 0  deg: 1 exp: 2 imp: 0 hyb: 3 arom?: 0 chi: 0
Bonds:
	0 0->1 order: 1 conj?: 0 aromatic?: 0
	1 0->2 order: 1 conj?: 0 aromatic?: 0
	2 3->0 order: 2 conj?: 0 aromatic?: 0
```

**Expected behavior**
Ideally the atom symbol/label would be kept as an `R`. If this is not acceptable for any reason the original label in the molfile should be preserved somewhere.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.01
 - OS: [e.g. Ubuntu 20.04] MacOS
 - Python version (if relevant): 3.10
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? `pip install rdkit`

**Additional context**
I'm writting a library able to deal with ChEBI's way of dealing with chemistry. Current workaround is to parse the molecule twice (1 with RDKit and 1 manually).

**Comment by greglandrum** [comment]
Given that you end up with the information about what the R label was when an actual RGP spec is there, I agree that this is a bug. It should be straightforward to fix for the 2022.09.2 patch release.

**Comment by eloyfelix** [comment]
@greglandrum @bp-kelley doing a more in depth check on the whole ChEBI database I've found that we have more than 800 molfiles with `R#` symbol that are not handled by the RGP spec (this fix doesn't work for them, see: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/FileParsers/MolFileParser.cpp#L1477)

These compounds come from old Marvin and Ketcher versions. Example (CHEBI:35410):

```

  Marvin  08301217132D          

  6  5  0  0  0  0            999 V2000
    7.3491   -3.6869    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.6346   -3.2744    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
    5.9201   -3.6869    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
    6.6346   -2.4494    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.8533   -4.0696    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
    8.0660   -3.2844    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  0  0  0  0
  3  2  1  0  0  0  0
  2  4  2  0  0  0  0
  2  5  1  0  0  0  0
  1  6  1  0  0  0  0
M  CHG  2   3  -1   5  -1
M  END
```

Getting an `R` instead of a `*` is quite important for ChEBI since they have a meaning (related to the Ontology):
`*` = attaches to something
`R` = something attaches here

From [ChemAxon docs](https://docs.chemaxon.com/display/docs/mdl-molfiles-rgfiles-sdfiles-rxnfiles-rdfiles-formats.md): 
```
R-Group, R or R N , where N > 0 integer. Before version 5.9, R, without number, was written as R#
```

So I was wondering if it could be possible to keep `R#` even without having the RGP spec. If it is not I guess we'll need to try to fix the molfiles. Happy to send a PR (easy one :D) if you think so.

As extra info [Marvin](https://marvinjs-demo.chemaxon.com/latest/), [Ketcher](https://lifescience.opensource.epam.com/KetcherDemoSA/index.html) and [CDK](https://www.simolecule.com/cdkdepict/depict.html) seem to be happy about it.

**Comment by bp-kelley** [comment]
There is some code that attempts to do this for molblock reactions that may
be of use.

```
https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/ChemReactions/SanitizeRxn.h#L56
```

I could make an API to make fixRGroups work on a molecule not a reaction.

**Comment by bp-kelley** [comment]
After looking at this a bit, the reaction sanitization won’t reserve your ontology.

@greglandrum what do you think about tagging the dummy atom with its r-label in cases where we don’t match the spec so we can resolve this after the fact?

**Comment by greglandrum** [comment]
Microrant: I love that the fact that ChEBI produces files which are poorly structured is somehow an RDKit bug.

Getting that out of my system: I'm closing this one again because the bug that was reported is fixed.
I'm fine with modifying the current fix to also allow information to carry through for `R#` (the fact that it's not carried through now is very much a case of the old man yelling at the clouds), and would be happy to do it for 2022.09.3, but please create a separate issue for that (or I'll do it when I create the PR).

**Comment by eloyfelix** [comment]
thank you @greglandrum! I've just opened the new issue.
