### ISSUE TITLE
Locale dependent float for _GasteigerCharge

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#577]
On a Windows machine with the German locale the "_GasteigerCharge" atom property is formatted using the local locale, to give number like "0,34" instead of "0.34".

The function rdkit/Chem/Descriptors.py:_ChargeDescriptors then parses that string using Python's float(), which is not locale sensitive:

    chg = float(at.GetProp('_GasteigerCharge'))

This causes a ValueError. It is possible to hack around that by inserting a fake float() in the module namespace:

    def float_hack(value):
        return float(value.replace(",", "."))
    
    import rdkit.Chem.Descriptors
    rdkit.Chem.Descriptors.float = float_hack

However, it would be better if RDKit uses a locale-insensitve method to convert the float to a string property.

**Comment by greglandrum** [comment]
@adalke : have you been able to reproduce this on any other systems? I think the fix is easy, but there are some additional logistics for me in building/testing on windows at the moment.

**Comment by adalke** [comment]
I can't reproduce the exact circumstances, since I don't have a Windows box. I saw it on Paul Czodrowski's laptop. It's a bit odd, since I thought Python forced everything into the "C" locale at startup, but perhaps one of the third-party libraries was doing it for him.

I can reproduce it by setting the LC_NUMERIC myself, inside of Python:

    from locale import setlocale, LC_NUMERIC
    setlocale(LC_NUMERIC, "de_DE")
    
    from rdkit import Chem
    from rdkit.Chem import Descriptors
    mol = Chem.MolFromSmiles("CCO")
    try:
        print Descriptors.MaxPartialCharge(mol)
    except Exception:
        for i, atom in enumerate(mol.GetAtoms()):
            print "Charge on %d: %s" % (i, atom.GetProp("_GasteigerCharge"))
        raise
    else:
        print "No problems."

This produces the output:

    Charge on 0: -0,041838486154772384
    Charge on 1: 0,040220581749086423
    Charge on 2: -0,39666371478125978
    Traceback (most recent call last):
      File "charge.py", line 9, in <module>
        print Descriptors.MaxPartialCharge(mol)
      File "/usr/local/lib/python2.7/site-packages/rdkit/Chem/Descriptors.py", line 153, in MaxPartialCharge
        _,res = _ChargeDescriptors(mol,force)
      File "/usr/local/lib/python2.7/site-packages/rdkit/Chem/Descriptors.py", line 144, in _ChargeDescriptors
        chg = float(at.GetProp('_GasteigerCharge'))
    ValueError: invalid literal for float(): -0,041838486154772384

**Comment by greglandrum** [comment]
Perfect; that's the reproducible I needed.

**Comment by greglandrum** [comment]
Ok, that commit *should* have done it. Would be great if you could check.

**Comment by adalke** [comment]
I confirm that my example code runs without a problem on my Mac. Thanks for the fix!
