### ISSUE TITLE
KekulizationException in tautomer canonicalization

### ISSUE THREAD

**Issue by d-b-w** [rdkit/rdkit#5784]
**Describe the bug**
There is a KekulizationException when canonicalizing tautomers for some types of molecules. This seems to be new since the sprint release. I've seen it in a couple of places, but the commonality seems to be with non-aromatic rings with two nitrogens and one external methyl group.

Here are a couple of examples:

<img width="599" alt="examples" src="https://user-images.githubusercontent.com/3013277/203425138-8cc4b35b-3824-49c3-b0d2-0932d2f4ed71.png">

**To Reproduce**

    from rdkit import Chem 
    from rdkit.Chem.MolStandardize import rdMolStandardize  

    for smi in ['NC1=NC=NC(C)=C1',
                'CC1N=CN(C)C(=O)C=1',
                'CC1=CC=CC(=O)N1C']:
        mol = Chem.MolFromSmiles(smi)
        rdMolStandardize.TautomerEnumerator().Canonicalize(mol)

**Expected behavior**

some sort of answer :)

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2022.09 release. Also tested with a build at adfdeca5113ca5 (head of origin/master on November 20)
 - OS: Darwin, Linux and Windows
 - Using an internal Schrödinger build, also built locally

**Comment by d-b-w** [comment]
Looks caused by https://github.com/rdkit/rdkit/issues/5402 - if I revert that commit these structures give answers

**Comment by greglandrum** [comment]
Yeah, there's a problem with that change. I'm looking into it, but it's non-trivial (as one would expect with anything connected to tautomerism)

**Comment by d-b-w** [comment]
Would it make sense to catch kekulization errors and continue at this point? I think it would be best if all transformations were guaranteed to always produce valid structures, but that seems like a hard guarantee to make!
