### ISSUE TITLE
RDKit 2022.09.2 shows wrong version

### ISSUE THREAD

**Issue by eloyfelix** [rdkit/rdkit#5809]
**Describe the bug**

`rdkit.__version__` for 2022.09.2 shows 2022.09.1

**To Reproduce**

```
❯ pip freeze | grep rdkit
rdkit==2022.9.2
❯ python -c"import rdkit; print(rdkit.__version__)"
2022.09.1
```

I think this is comming from this commit: https://github.com/rdkit/rdkit/commit/bda55ac79856b1e67821d2e54ef0ba462a8df96b

**Comment by greglandrum** [comment]
Ah, crap. Sorry.
Ok, will do a 2022.09.3 release to fix that
