### ISSUE TITLE
Extremely slow rendering of chiral macrocycles when using coordgen

### ISSUE THREAD

**Issue by bjonnh-work** [rdkit/rdkit#5813]
**Describe the bug**
Performance of coordgen for chiral macrocycles is really bad (roughly 100 times slower for the given molecule).

**To Reproduce**

```python
from rdkit.Chem import rdDepictor
from rdkit import Chem

### This is slow
rdDepictor.SetPreferCoordGen(True)
mol = Chem.MolToMolBlock(Chem.MolFromSmiles("C[C@@H]1CCCCCCCCC(=O)OCCN[C@H](C)CCCCCCCCC(=O)OCCN[C@H](C)CCCCCCCCC(=O)OCCN1"))

### This is fast
rdDepictor.SetPreferCoordGen(False)
mol = Chem.MolToMolBlock(Chem.MolFromSmiles("C[C@@H]1CCCCCCCCC(=O)OCCN[C@H](C)CCCCCCCCC(=O)OCCN[C@H](C)CCCCCCCCC(=O)OCCN1"))
len(mol)
```

**Expected behavior**
Better performance.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09 and master
 - OS: Ubuntu 22.04 
 - Python version: 3.11 and below
 - Are you using conda? no
 - If you are not using conda: git and pip

**Additional context**
The issue is crossposted to coordgenlibs: https://github.com/schrodinger/coordgenlibs/issues/118

**Comment by greglandrum** [comment]
This isn't an RDKit bug, so I'm closing it.
