### ISSUE TITLE
Explicit valence check fails for certain SMILES

### ISSUE THREAD

**Issue by josh-collaborationspharma** [rdkit/rdkit#5849]
**Describe the bug**
For certain SMILES strings (examples below), I can convert to mol and back to SMILES without any issue (equivalently, I am able to canonicalize the original SMILES). However, if I try to convert to mol from the canonicalized SMILES, I receive an "Explicit valence for atom ... is greater than is permitted" warning, and a None object is returned. The same happens if I set doRandom=True and use a randomized SMILES. The only way to check validity for such a SMILES is to check whether MolFromSmiles(MolToSmiles(MolFromSmiles(SMILES))) is None.

**To Reproduce**
Here are a few example SMILES that throw this error:
c1c(ccc2NC(CN=c(c21)(C)C)=O)O
c1c(c2n(C(NC(Oc2cc1)C)c1c[nH]cn1)=O)O
c1c2C(c4c(cc(c(C(=O)O)c4)O)O)Oc(c2c(c(O)c1O)O)(=O)O
c12C(CN(C)C)CCCCN=c(c2cc2c1cc[nH]c2)(C)C

Here is some code to try:
from rdkit import Chem
smiles = 'c1c(ccc2NC(CN=c(c21)(C)C)=O)O'
mol = Chem.MolFromSmiles(smiles) # No warning
smiles_canonical = Chem.MolToSmiles(mol)
mol_new = Chem.MolFromSmiles(smiles_canonical) # "Explicit valence..." warning
print(mol) # rdkit mol object
print(smiles_canonical) # canonical smiles string
print(mol_new) # None object

**Expected behavior**
If I try to convert one of these SMILES to a mol object, I should receive the "Explicit valence..." warning and a None object should be returned. Instead, this behavior only occurs after converting SMILES -> mol -> SMILES -> mol.

**Screenshots**
![image](https://user-images.githubusercontent.com/113449207/206272186-d167af38-73be-432c-aa63-8af66e6abfbe.png)

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.1
 - OS: Ubuntu 22.04.1
 - Python version (if relevant): 3.10.6
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? rdkit (I think)

**Additional context**
I am doing validity checks for 10s of thousands of generated molecules at a time. rdkit's mol <-> smiles converters are amazingly fast, but having to convert smiles -> mol -> smiles -> mol instead of just smiles -> mol can add up for large sets of molecules. Thanks for your work on this awesome library!

**Comment by greglandrum** [comment]
Confirmed. I can reproduce this.
Here's a simple reproducible:
![image](https://user-images.githubusercontent.com/540511/206831881-a7fb577e-4af8-4c0f-b72a-b8e3eb301627.png)
The problem arises, I think, because carbon 9 is marked aromatic in the input SMILES and this allows one of the valence checks to pass:
![image](https://user-images.githubusercontent.com/540511/206831986-c76ba587-a0c0-4411-916a-434d95b11750.png)
