### ISSUE TITLE
[UGM2015] Autodetection of numThreads

### ISSUE THREAD

**Issue by mwojcikowski** [rdkit/rdkit#586]
Accept 0/-1 argument and autodetect the maximum number of threads to use.

**Comment by giallu** [comment]
I'd suggest to just use by default the max number of threads in all functions that accepts the numThreads parameter. One can use "1" to get the old beahior if needed

**Comment by mwojcikowski** [comment]
Actually I don't think that's good way to go. I guess the user wouldn't appreciate RDKit tried to take over the whole machine by default.
