### ISSUE TITLE
Generating SVG Images with Transparent Background

### ISSUE THREAD

**Issue by gungorbudak** [rdkit/rdkit#587]
I'm using following code to produce SVG depictions with transparent background. It seems SVG is getting created correctly but the background is always white. I tried setting `bgColor` to `None`, `(255, 255, 255)` and `(0, 0, 0)` but it was always white.

Is this a bug or am I doing something wrong? 

```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw


mol = "/home/gungor/Desktop/flap/flap_67.mol"

m = Chem.MolFromMolFile(mol)
AllChem.Compute2DCoords(m)

opts = Draw.DrawingOptions()
opts.bgColor = None

Draw.MolToFile(m,
            "/home/gungor/Desktop/flap_67.svg",
            size=(600, 600),
            options=opts)
```

I did the installation from Ubuntu repositories on a Linux Mint 17.2 system. Python version 2.7.6.

**Comment by gungorbudak** [comment]
I did this by slightly changing the new drawing code with the 2015.03 build given in the following URL (In [3]): http://rdkit.blogspot.com.tr/2015/02/new-drawing-code.html

My solution is to change the `fill` attribute on `rect` element of the returned SVG string. By default it is `#ffffff`, if you make it `none`, then the background becomes transparent. The only problem is that `svg` element loses some attributes, I don't know why and `xml` tag disappears. If you also put them in their place, you're good to go.

```python
import xml.etree.ElementTree as ET

from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D


def moltosvg(mol,molSize=(450,150),kekulize=True):
    mc = Chem.Mol(mol.ToBinary())
    if kekulize:
        try:
            Chem.Kekulize(mc)
        except:
            mc = Chem.Mol(mol.ToBinary())
    if not mc.GetNumConformers():
        rdDepictor.Compute2DCoords(mc)
    drawer = rdMolDraw2D.MolDraw2DSVG(molSize[0],molSize[1])
    drawer.DrawMolecule(mc)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()
    # It seems that the svg renderer used doesn't quite hit the spec.
    # Here are some fixes to make it work in the notebook, although I think
    # the underlying issue needs to be resolved at the generation step
    # return svg.replace('svg:','')

    # Make the white background transparent
    tree = ET.fromstring(svg.replace('svg:',''))
    rect = tree.find('rect')
    rect.set('style', rect.get('style').replace('#ffffff', 'none'))
    # Recover some missing attributes for correct browser rendering
    tree.set('version', '1.1')
    tree.set('xmlns:svg', 'http://www.w3.org/2000/svg')
    tree.set('xmlns:rdkit', 'http://www.rdkit.org/xml')
    tree.set('xmlns:xlink', 'http://www.w3.org/1999/xlink')
    return '<?xml version="1.0" encoding="UTF-8"?>' + ET.tostring(tree).strip()
```

**Comment by greglandrum** [comment]
Sorry I was slow replying here. I just checked in some changes to allow doing this explicitly using the new C++-based drawing code. It will be in the next release.
