### ISSUE TITLE
Chemical reactions with radicals cannot be pickled and unpickled.

### ISSUE THREAD

**Issue by sitanshubhunia** [rdkit/rdkit#5890]
**Describe the bug**
select reaction_from_ctab('$RXN

  Mrv1760     122201221618

  2  1
$MOL

  Mrv1760 12222216182D          

 21 23  0  0  0  0            999 V2000
  -10.8107    0.5496    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
  -10.0962    0.9621    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  -10.0962    1.7871    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  -10.8107    2.1996    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
   -9.3817    2.1996    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -8.6672    1.7871    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.9528    2.1996    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.2383    1.7871    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -6.5238    2.1996    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -7.2383    0.9621    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.9528    0.5496    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.9528   -0.2754    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.2383   -0.6879    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.2383   -1.5129    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.9528   -1.9254    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -7.9528   -2.7504    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -8.6672   -1.5129    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -8.6672   -0.6879    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -8.6672    0.9621    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -9.3817    0.5496    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -9.3817   -0.2754    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  3  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  7  1  0  0  0  0
  7  8  2  0  0  0  0
  8  9  1  0  0  0  0
  8 10  1  0  0  0  0
 10 11  2  0  0  0  0
 11 12  1  0  0  0  0
 12 13  2  0  0  0  0
 13 14  1  0  0  0  0
 14 15  2  0  0  0  0
 15 16  1  0  0  0  0
 15 17  1  0  0  0  0
 17 18  2  0  0  0  0
 12 18  1  0  0  0  0
  6 19  1  0  0  0  0
 11 19  1  0  0  0  0
 19 20  1  0  0  0  0
  2 20  1  0  0  0  0
 20 21  2  0  0  0  0
M  END
$MOL

  Mrv1760 12222216182D          

 12 13  0  0  0  0            999 V2000
   -2.3174    2.7504    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3174    1.9254    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6500    1.4405    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9049    0.6559    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9849    1.4405    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7299    0.6559    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2149   -0.0115    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.8793   -0.7652    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.3642   -1.4327    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.1847   -1.3464    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.5203   -0.5928    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -4.0353    0.0747    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  2  5  1  0  0  0  0
  5  6  2  0  0  0  0
  4  6  1  0  0  0  0
  6  7  1  0  0  0  0
  7  8  1  0  0  0  0
  8  9  1  0  0  0  0
  9 10  1  0  0  0  0
 10 11  1  0  0  0  0
 11 12  1  0  0  0  0
  7 12  1  0  0  0  0
M  RAD  1  11   2
M  END
$MOL

  Mrv1760 12222216182D          

 32 36  0  0  0  0            999 V2000
    4.6762   -4.4747    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.1913   -3.8073    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.3663   -3.8073    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.1113   -3.0227    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4462   -3.0227    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7788   -2.5378    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7788   -1.7128    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0643   -1.3003    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.0643   -0.4753    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7788   -0.0628    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4932   -0.4753    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    5.2077   -0.0628    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.9222   -0.4753    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.6366   -0.0628    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.6366    0.7622    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    5.9222    1.1747    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.9222    1.9997    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.2077    2.4122    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.2077    3.2372    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.9222    3.6497    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.9222    4.4747    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    6.6366    3.2372    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.6366    2.4122    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.2077    0.7622    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.3511   -0.4753    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    8.0656   -0.0628    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.7801   -0.4753    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
    8.0656    0.7622    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.7801    1.1747    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
    7.3511    1.1747    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.3511    1.9997    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.4932   -1.3003    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  2  5  1  0  0  0  0
  5  6  2  0  0  0  0
  4  6  1  0  0  0  0
  6  7  1  0  0  0  0
  7  8  1  0  0  0  0
  8  9  1  0  0  0  0
  9 10  1  0  0  0  0
 10 11  1  0  0  0  0
 11 12  1  0  0  0  0
 12 13  2  0  0  0  0
 13 14  1  0  0  0  0
 14 15  1  0  0  0  0
 15 16  1  0  0  0  0
 16 17  1  0  0  0  0
 17 18  2  0  0  0  0
 18 19  1  0  0  0  0
 19 20  2  0  0  0  0
 20 21  1  0  0  0  0
 20 22  1  0  0  0  0
 22 23  2  0  0  0  0
 17 23  1  0  0  0  0
 16 24  2  0  0  0  0
 12 24  1  0  0  0  0
 14 25  2  0  0  0  0
 25 26  1  0  0  0  0
 26 27  1  0  0  0  0
 26 28  2  0  0  0  0
 28 29  1  0  0  0  0
 28 30  1  0  0  0  0
 15 30  1  0  0  0  0
 30 31  2  0  0  0  0
 11 32  1  0  0  0  0
  7 32  1  0  0  0  0
M  END
')
Above Query getting error  "constructChemReact: Unknown exception"

**To Reproduce**
 
[Git_check.txt](https://github.com/rdkit/rdkit/files/10286270/Git_check.txt)

**Expected behavior**
I wants to generate smiles.

**Screenshots**
![image](https://user-images.githubusercontent.com/840684/209118954-731f2047-5e61-4d63-93d7-8d20f303f6cb.png)

**Configuration :**
 - RDKit version:  
             select rdkit_version()  -->  [ 0.76.0 ] 
             select rdkit_toolkit_version() --> [2022.03.4]
 - OS: [e.g. Ubuntu 20.04]
     postgres:12
 
**Note:  I have found due to radical atom this error is occurred (marked in red circle)**

![image](https://user-images.githubusercontent.com/840684/209120177-96c3b310-f22b-477c-b074-a0eb33036b1e.png)

What I have to do in this situation to generate reaction smiles.

Thanks in advance.

**Comment by lounsbrough** [comment]
I am also seeing a similar error when trying to convert a rxnfile into a rdkit reaction with `reaction_from_ctab`.

**Comment by lounsbrough** [comment]
This does not happen on version `2022.03.5`, but it does happen on `2023.09.1` for me.

**Comment by lounsbrough** [comment]
Here is a very concise example that is failing, which could be codified into a test:

```
$RXN V3000

      Mrv2117  020720241642

M  V30 COUNTS 1 1
M  V30 BEGIN REACTANT
M  V30 BEGIN CTAB
M  V30 COUNTS 3 3 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -3.85 0.6668 0 0 RAD=2
M  V30 2 C -4.62 -0.6668 0 0 RAD=2
M  V30 3 C -3.08 -0.6668 0 0 RAD=2
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 2 3
M  V30 2 1 1 3
M  V30 3 1 1 2
M  V30 END BOND
M  V30 END CTAB
M  V30 END REACTANT
M  V30 BEGIN PRODUCT
M  V30 BEGIN CTAB
M  V30 COUNTS 1 0 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 5.94 0 0 0
M  V30 END ATOM
M  V30 END CTAB
M  V30 END PRODUCT
M  END
```

**Comment by lounsbrough** [comment]
I think it's also worth noting that the problematic molecule in the reaction is able to be parsed as an individual molecule, just not in a reaction:

```sql
SELECT mol_from_ctab('
  Mrv2117 02072416532D          

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 3 3 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -3.85 0.6668 0 0 RAD=2
M  V30 2 C -4.62 -0.6668 0 0 RAD=2
M  V30 3 C -3.08 -0.6668 0 0 RAD=2
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 2 3
M  V30 2 1 1 3
M  V30 3 1 1 2
M  V30 END BOND
M  V30 END CTAB
M  END
')
```

produces -> `[CH]1[CH][CH]1 |^1:0,1,2|`

**Comment by lounsbrough** [comment]
@greglandrum - I saw you just made [updates](https://github.com/rdkit/rdkit/pull/7138) to the reaction parsing code. Is there any chance that you could check this case and see if it is working with the new code? I have very limited experience with chemistry but I could try to put up a PR if you point me in the right direction.

**Comment by greglandrum** [comment]
To trace this back to the underlying cause: this is because these reactions cannot be properly serialized/deserialized:
```
In [11]: rxn = rdChemReactions.ReactionFromRxnBlock(rxnb)  # using the rxnblock from @lounsbrough 

In [12]: r2 = pickle.loads(pickle.dumps(rxn))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 1
----> 1 r2 = pickle.loads(pickle.dumps(rxn))

ValueError: Do not know how to finalize query: 'AtomNumRadicalElectrons'
```
