### ISSUE TITLE
SMILES Recoginization issues with stereochemistry

### ISSUE THREAD

**Issue by Flora-Feng0532** [rdkit/rdkit#5893]
-----------------------------------------

If you have a question about the RDKit or aren't sure if what you're seeing is the right behavior please use the Discussions tab above (https://github.com/rdkit/rdkit/discussions) instead of posting it here.

Please help us help you: We normally need the information below in order to answer questions or understand bug reports. If you do not provide the information requested we may not be able to help you and will probably close the issue.

PLEASE DELETE THIS SECTION AFTER YOU HAVE READ IT

-----------------------------------------

**Describe the bug**
Stereochemistry changed when using Chem.MolFromSmiles

**To Reproduce**
```
mol = Chem.MolFromSmiles("O[C@]1[C@@](O)COC1")
Chem.MolToSmiles(mol,isomericSmiles=True)
->'O[C@]1COC[C@@]1O'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/57335721/209305172-3edb6649-20ef-487e-89fe-a4772b5d8c7e.png)
![image](https://user-images.githubusercontent.com/57335721/209305281-e61d87c8-389f-43dd-b4f8-c6f07bae6233.png)

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.3 
 - Python version (if relevant):3.8.8
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from?conda-forge

**Comment by greglandrum** [comment]
@Flora-Feng0532 I'm not 100% sure which molecule you are trying to reconstruct, but the SMILES you are providing doesn't match the "Actual Structure" you have drawn. Atoms in square brackets in SMILES do not have implicit Hs assigned, so the two chiral carbons in your molecule each have a radical associated with them (you can see these in the drawings the RDKit makes).

If you actually provide the Hs in the SMILES then I think you'll get what you expect:
```
In [10]: mol = Chem.MolFromSmiles("O[C@H]1[C@@H](O)COC1")

In [11]: Chem.FindMolChiralCenters(mol)
Out[11]: [(1, 'R'), (2, 'S')]
```

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
