### ISSUE TITLE
DetermineBonds assigning methyl carbon as tetrahedral center

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#5894]
The attached xyz file is for caffeine, which has no stereocenters.

```
>>> from rdkit import Chem
>>> from rdkit.Chem import rdmolfiles
>>> from rdkit.Chem import rdDetermineBonds
>>> mol = rdmolfiles.MolFromXYZFile('/Users/jasonb/caffeine.txt')
>>> rdDetermineBonds.DetermineBonds(mol)
>>> mol.GetAtomWithIdx(0).GetChiralTag()
rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW
>>> import rdkit
>>> rdkit.__version__
'2022.09.3'
```
Is this expected?  Is there a good way to remove invalid chiral tags?
[caffeine.txt](https://github.com/rdkit/rdkit/files/10296393/caffeine.txt)

**Comment by jasondbiggs** [comment]
I notice that `determineBonds` calls the following
```
void setChirality(RWMol &mol) {
  MolOps::sanitizeMol(mol);
  MolOps::setDoubleBondNeighborDirections(mol, &mol.getConformer());
  MolOps::assignStereochemistryFrom3D(mol);
  MolOps::assignChiralTypesFrom3D(mol);
}
```
Is there a reason to call `assignChiralTypesFrom3D` after `assignStereochemistryFrom3D`, when the latter already calls the former internally?  I haven't looked at the RDKit stereo code in a couple of years so I don't know what parts are the 'new' stereo perception functions and which are the legacy.

**Comment by greglandrum** [comment]
@jasondbiggs yeah, I think that's likely the problem. I will fix it.
