### ISSUE TITLE
numpy.float is no longer supported and causes exceptions 

### ISSUE THREAD

**Issue by PatWalters** [rdkit/rdkit#5895]
**Describe the bug**
The RDKit uses numpy.float to perform a type cast in many places.    Numpy no longer supports numpy.float, this must be changed to either "float" or "numpy.float64"
https://numpy.org/devdocs/release/1.20.0-notes.html

There are calls in 
```
./rdkit/Chem/Graphs.py
./rdkit/ML/EnrichPlot.py
./rdkit/ML/InfoTheory/BitRank.py
./rdkit/ML/AnalyzeComposite.py
./rdkit/ML/ScreenComposite.py
./rdkit/ML/Cluster/murtagh_test.py
./rdkit/ML/Cluster/Resemblance.py
./rdkit/ML/files.py
./rdkit/ML/Composite/AdjustComposite.py
./rdkit/ML/Composite/BayesComposite.py
```

Calling the affected functions will throw an AttributeError.

**To Reproduce**
```
>>> from rdkit import Chem
>>> from rdkit.Chem import GraphDescriptors
>>> mol = Chem.MolFromSmiles("c1ccccc1")
>>> GraphDescriptors.Ipc(mol)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pwalters/anaconda3/envs/rdkit_2022_09/lib/python3.8/site-packages/rdkit/Chem/GraphDescriptors.py", line 124, in Ipc
    cPoly = abs(Graphs.CharacteristicPolynomial(mol, adjMat))
  File "/home/pwalters/anaconda3/envs/rdkit_2022_09/lib/python3.8/site-packages/rdkit/Chem/Graphs.py", line 43, in CharacteristicPolynomial
    res = numpy.zeros(nAtoms + 1, numpy.float)
  File "/home/pwalters/anaconda3/envs/rdkit_2022_09/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
```

**Expected behavior**
Not throwing an exception

**Screenshots**
Not applicable

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.3
 - OS: Ubuntu 18.04.6 LTS
 - Python version (if relevant): 3.8
 Installed the rdkit with 
```
conda create -n rdkit_2022_09 python=3.8
pip install rdkit 
```

**Comment by PatWalters** [comment]
I'd be happy to make the fixes and submit a PR.  I just need to know whether the RDKit developers would prefer to replace numpy.float with float or numpy.float64.

**Comment by greglandrum** [comment]
@PatWalters I don't have any particular preference. Unless you see some reason to do otherwise, how about we just use `float`?

**Comment by PatWalters** [comment]
Ok, submitted a PR
