### ISSUE TITLE
Incompatibility with python 3.11

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#5911]
**Describe the bug**

There are several places in the rdkit code where we use the construct `random.shuffle(v, random=random.random)` to shuffle the contents of lists. The `random` keyword argument to `shuffle()` has been deprecated since python 3.9 and was removed in python 3.11: https://docs.python.org/3.11/library/random.html#random.shuffle

According to the documentation (https://docs.python.org/3.10/library/random.html#random.shuffle) if you don't provide the argument `random.random()` will be used, so you should get the same results. You most definitely do not:
```
$ python -c 'import random;random.seed(0xf00d);l=list(range(10));random.shuffle(l);print(l);l=list(range(10));random.seed(0xf00d);random.shuffle(l,random=random.random);print(l)'
[8, 3, 0, 5, 6, 9, 1, 4, 2, 7]
<string>:1: DeprecationWarning: The *random* parameter to shuffle() has been deprecated
since Python 3.9 and will be removed in a subsequent version.
[9, 5, 7, 3, 0, 8, 6, 2, 1, 4]
```
Dealing with this is going to require changing the expected results for numerous tests. 

Oh, what fun.

**Configuration (please complete the following information):**
 - RDKit version: master
 - OS: all
 - Python version (if relevant): 3.11+

**Comment by wopozka** [comment]
@greglandrum 
Maybe issueing bugreport for python module would be a better option? Hopefully, they will not fix it by removing one line from documentation ;).

**Comment by bp-kelley** [comment]
I think the proper way to do this is as follows:

```
>>> import random
>>> random.seed(1)
>>> l = list(range(10))
>>> random.shuffle(l)
>>> l
[6, 8, 9, 7, 5, 3, 0, 4, 1, 2]
>>> r = random.Random(1)
>>> l = list(range(10))
>>> r.shuffle(l)
>>> l
[6, 8, 9, 7, 5, 3, 0, 4, 1, 2]
```

**Comment by greglandrum** [comment]
@bp-kelley That is indeed a solution, but implementing it is still a non-trivial amount of effort.
