### ISSUE TITLE
null return :: reaction_from_ctab :: please help

### ISSUE THREAD

**Issue by sitanshubhunia** [rdkit/rdkit#5914]
**Describe the bug**
select reaction_from_ctab
('$RXN

      Mrv2219  010220230459

  1  1  1
$MOL

  Mrv2219 01022304592D          

  5  5  0  0  0  0            999 V2000
   -3.2689   -0.5308    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.9954   -0.1397    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.3866    0.5867    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.7777   -0.1397    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5983   -0.1397    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  4  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  1  0  0  0  0
  1  5  1  0  0  0  0
M  END
$MOL

  Mrv2219 01022304592D          

  6  6  0  0  0  0            999 V2000
    4.1071   -0.1956    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    4.7777   -0.5867    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.3808   -0.5867    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.7102   -0.1956    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3190    0.5309    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8719   -0.1956    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  3  1  0  0  0  0
  1  2  1  0  0  0  0
  3  4  1  0  0  0  0
  6  4  1  0  0  0  0
  4  5  1  0  0  0  0
  5  6  1  0  0  0  0
M  END
$MOL

  Mrv2219 01022304592D          

  4  1  0  0  0  0            999 V2000
   -1.4248    0.5867    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6425    0.5867    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4248   -0.1956    0.0000 H2  0  0  0  0  0  0  0  0  0  0  0  0
   -0.6425   -0.1956    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
M  STY  1   1 SUP
M  SAL   1  4   1   2   3   4
M  SMT   1 N2H4.H2O
M  END
')

return null

![err](https://user-images.githubusercontent.com/840684/210196588-3d7afc04-faf4-4d83-9588-6e8cdd196efa.png)

**To Reproduce**
[marvinjs_.rxn.txt](https://github.com/rdkit/rdkit/files/10330076/marvinjs_.rxn.txt)

**Expected behavior**
I wants to generate smiles.

**Configuration :**

RDKit version:
select rdkit_version() --> [ 0.76.0 ]
select rdkit_toolkit_version() --> [2022.03.4]
OS: [e.g. Ubuntu 20.04]
postgres:12

**Comment by greglandrum** [comment]
Closing this because there's a discussion (#5915)

@sitanshubhunia : please do not open both an issue and a discussion for the same topic. If you have a question, use the discussion section, if you believe that you have found an RDKit bug then open an issue.
