### ISSUE TITLE
`MHFPEncoder::Distance` doesn't compute a (Jaccard) distance

### ISSUE THREAD

**Issue by althonos** [rdkit/rdkit#5919]
Hi there!

## **Describe the bug**

I've been using RDKit to compute MHFP fingerprints and pairwise distances to stratify the compounds of a dataset for running a stratified cross-validation, and avoid training leakage. It came to my attention that the `MHFPEncoder::Distance` method:

1. Doesn't compute a *distance*, but a *similarity*: with the current implementation (found in `rdkit/MHFP.h`):
    ```c++
     static double Distance(const std::vector<uint32_t>& a, const std::vector<uint32_t>& b) {
       size_t matches = 0;
       for (size_t i = 0; i < a.size(); i++) {
         if (a[i] == b[i]) {
           matches++;
         }
       }
       return matches / (double)a.size();
     }
    ```
   two identical vectors will return a distance of `1.0`, while passing two distinct vectors different in every position will return a distance of `0.0`.

2. Is not a Jaccard / Tanimoto distance, but a Hamming distance: the docstring reads that this method: 
    > Calculates the Jaccard / Tanimoto distance between two MHFP fingerprints.
    
    However, the current implementation doesn't compute a Jaccard/Tanimoto distance, but a normalized Hamming distance. Jaccard/Tanimoto distances are only well defined for boolean vectors, but the MHFP fingerprint is not a bit vector but an integer vector.

## **Expected behavior**

1. `MHFPEncoder::Distance` should return a distance (`1.0 - similarity`).
2. `MHFPEncoder::Distance` documentation should mention Hamming instead of Jaccard/Tanimoto.

## **Configuration**
 - RDKit version: `2022.09.3`
 - OS: ArchLinux (Linux 6.0.10)
 - Python version (if relevant): Python 3.10
 - Are you using conda? No 
 - If you are not using conda: how did you install the RDKit? `pip install rdkit`

**Comment by greglandrum** [comment]
> 2\. However, the current implementation doesn't compute a Jaccard/Tanimoto distance, but a normalized Hamming distance. Jaccard/Tanimoto distances are only well defined for boolean vectors, but the MHFP fingerprint is not a bit vector but an integer vector.

To this point: I'm fine with the renaming that happens in the fix for this, but there are other parts of the RDKit which use a "generalized" version of Tanimoto for int vectors which we call "Tanimoto".
