### ISSUE TITLE
Inconsistent behaviour of `rdChemReactions.HasReactionSubstructMatch` with aromatic compounds

### ISSUE THREAD

**Issue by anuvc** [rdkit/rdkit#5956]
**Configuration:**

- RDKit Version: 2022.09.3
- Operating system: MacOS 13.0.1 
- Python version (if relevant): 3.8.13
- Using conda, but rdkit was installed through pip

**Description:**

I am trying to do reaction template substructure matching using `rdChemReactions.HasReactionSubstructMatch` however I ran into inconsistent behavior when trying to do substructure matching with identical reactions containing aromatic molecules when using a different representation for the same molecule. Example has been provided with the code snippet below. 

```
from rdkit import Chem
from rdkit.Chem import rdChemReactions

def has_self_match(template: str) -> bool:
    rxn = rdChemReactions.ReactionFromSmarts(template)
    for r in rxn.GetReactants(): Chem.SanitizeMol(r)
    for p in rxn.GetProducts(): Chem.SanitizeMol(p)
    return rdChemReactions.HasReactionSubstructMatch(rxn, rxn)

has_self_match('N1CCCCC1>>N1CCCCC1') # True

has_self_match('N1CCCCC1>>n1ccccc1') # False

has_self_match('C1CCCCC1>>C1CCCCC1') # True

has_self_match('c1ccccc1>>C1CCCCC1') # False
```

**Comment by bp-kelley** [comment]
One of the issues is that you are sanitizing a smarts pattern which probably doesn't do what you expect.


```
from rdkit import Chem
from rdkit.Chem import rdChemReactions

def has_self_match(template: str) -> bool:
    rxn = rdChemReactions.ReactionFromSmarts(template)
    return rdChemReactions.HasReactionSubstructMatch(rxn, rxn)

print(has_self_match('N1CCCCC1>>N1CCCCC1'))
print(has_self_match('N1CCCCC1>>n1ccccc1')) 
print(has_self_match('C1CCCCC1>>C1CCCCC1'))
print(has_self_match('c1ccccc1>>C1CCCCC1')) 
```

```
True
True
True
True
```

**Comment by anuvc** [comment]
Should I not be sanitizing SMARTS patterns in general?
As I mentioned in the initial post, I was originally trying to substructure match reaction templates (which are SMIRKS patterns) such as: 
```
[n&H1&+0&D2:1]1:[c:2]:[c:4]:[n&H0&+0&D2:5]:[c:3]:1>>[n&H1&+0&D2:1]1:[c:2]:[c:4]:[n&H0&+0&D2:5]:[c:3]:1
```
And the `rdChemReactions.HasReactionSubstructMatch()` returned the following error:
```
****
Pre-condition Violation
getNumImplicitHs() called without preceding call to calcImplicitValence()
Violation occurred on line 297 in file /project/build/temp.linux-x86_64-cpython-38/rdkit/Code/GraphMol/Atom.cpp
Failed Expression: d_implicitValence > -1
****
```
Hence I included the Sanitization step. However, with the sanitization step the substructure match returned `False` for the same template. So in that case, how do I get around to comparing the reaction templates.

**Comment by bp-kelley** [comment]
I expect that the HasReactionSubstructMatch is made for reactions with fully specified reactants and products like one would find in an ELN.

Doing these types of searches with SmartsPatterns is quite difficult as smarts can be arbitrarily complicated in a way that doesn't lend itself to easy substructure matching.

That being said, you can try and roll one by hand:

'''
def match(query_templates1, templates2):
    count = 0
    for count, q in enumerate(query_templates1):
        for t in templates2:
            count += 1
            if t.HasSubstructMatch(q, useQueryQueryMatches=True):
                return True
    return count == 0

def has_match(query_rxn, rxn2) -> bool:
    return ( match(query_rxn.GetReactants(), rxn2.GetReactants()) and
             match(query_rxn.GetAgents(), rxn2.GetAgents()) and
             match(query_rxn.GetProducts(), rxn2.GetProducts()) )
        
rxn = rdChemReactions.ReactionFromSmarts("[n&H1&+0&D2:1]1:[c:2]:[c:4]:[n&H0&+0&D2:5]:[c:3]:1>>[n&H1&+0&D2:1]1:[c:2]:[c:4]:[n&H0&+0&D2:5]:[c:3]:1")
assert has_match(rxn, rxn)
```

But even so, useQueryQueryMatches has limitations in that it ignores recursiveSmarts which can be fairly common in smarts reactions.

**Comment by bp-kelley** [comment]
I'm going to close this, if you want to follow up please add a topic in the discussions tab.

**Comment by anuvc** [comment]
Thanks a lot for the help, this code snippet served my purpose.
