### ISSUE TITLE
rdkit.Chem.rdfiltercatalog.FilterCatalogs.BRENK is still exists? or abounded. If abounded then in which version it is available?

### ISSUE THREAD

**Issue by theabhijitdn** [rdkit/rdkit#5957]
I want to FilterCatalogs. RDKit 2022.09.1 does not have BRENK, NIH, PAINS filters. but in documentation (https://www.rdkit.org/docs/source/rdkit.Chem.rdfiltercatalog.html) it is still available. I want to know that rdkit.Chem.rdfiltercatalog.FilterCatalogs.BRENK is still exists? or abounded. If abounded then in which version it is available?

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
