### ISSUE TITLE
Problems with MolFromInchi for a Pubchem compound

### ISSUE THREAD

**Issue by mapio** [rdkit/rdkit#5975]
Trying to convert to/from InChI leads to wrong results for compound with SMILES 

    C#[N+]C(=CC1=CC=C(OC)C=C1)C(=CC1=CC=C(OS(=O)(=O)O)C=C1)[N+]#C

corresponding to https://pubchem.ncbi.nlm.nih.gov/compound/163196076

The following piece of code shows the issue

    smiles = 'C#[N+]C(=CC1=CC=C(OC)C=C1)C(=CC1=CC=C(OS(=O)(=O)O)C=C1)[N+]#C'
    mol = Chem.MolFromSmiles(smiles)
    inchi = Chem.MolToInchi(mol)
    pubchem_inchi = 'InChI=1S/C19H15N2O5S/c1-20-18(12-14-4-8-16(25-3)9-5-14)19(21-2)13-15-6-10-17(11-7-15)26-27(22,23)24/h1-2,4-13H,3H3/q+1/p+1'
    print(pubchem_inchi == inchi)
    print(Chem.MolFromInchi(inchi))

it should print `True` (meaning that `MolToIni` returns the same InChI present in Pubchem) and anything different from `None` (indicating that `MolFromInchi` is not capable of recovering the molecule from the InChi generated by RDKit itself), but instead prints `True` and `None`. Moreover the `MolToInchi` conversion reports

    [07:43:34] WARNING: Proton(s) added/removed; Omitted undefined stereo

while the `MolFromInchi` reports

    [07:43:44] Explicit valence for atom # 26 S, 8, is greater than permitted
    [07:43:44] ERROR: Explicit valence for atom # 26 S, 8, is greater than permitted

The warning makes sense, but the error on the reverse conversion (given that the InChI coincides with the one in Pubchem) is unexpected (at least to me).

 - RDKit version: 2022.09.3
 - OS: Ubuntu 22.04
 - Python version: 3.10.6
 - Are you using conda: no
 - How did you install the RDKit: `pip install rdkit-pypi==2022.9.3` (in a fresh virtualenv).

**Comment by greglandrum** [comment]
It doesn't look like this is a problem with MolToInchI since it produces the same result as found in PubChem.
I agree that MolFromInChI should probably not fail though.

**Comment by greglandrum** [comment]
Actually, after looking at the tautomer which is encoded in the InChI:
![image](https://user-images.githubusercontent.com/540511/213365042-ea780fc6-7d2a-45a8-8ecd-0ac1c13dd21b.png)
I'm going to change my answer. The valence state on S in that structure is not chemically reasonable within the RDKit's valence model and I'm going to need to be convinced with some real-world examples before I add a valence of 8 for sulfur

If you want to process this kind of structure, you can disable sanitization when reading the molecule.

**Comment by mapio** [comment]
Thank you for your time and answer. 

I'm not a chemist, so unfortunately I can't provide any real-world example (beside saying that the one in my report it's not something that came out of my mind, but is an compound from PubChem).

I'll probably stick to your suggestion of disabling sanitization for the time being. Thanks for the hint!
