### ISSUE TITLE
Strange deformation of highlighted patterns during processing  molecule enumerator 

### ISSUE THREAD

**Issue by ShangChien** [rdkit/rdkit#5980]
**Describe the bug**
Strange deformation of highlighted patterns in  molecule enumerator

**To Reproduce**
I follow dear greglandrum's blog [tutorial](https://greglandrum.github.io/rdkit-blog/posts/2021-05-13-intro-to-the-molecule-enumerator.html) for learning RDkit usage. 
Smiles with wildcard character `*` pass to `Chem.MolFromMolBlock` or `Chem.MolFromSmiles` before enumrate mol, then display a Strange deformation of highlighted patterns 

**Expected behavior**
input:
```
pv1 = Chem.MolFromMolBlock('''
  Mrv2007 06232015292D          

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 9 8 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -1.7083 2.415 0 0
M  V30 2 C -3.042 1.645 0 0
M  V30 3 C -3.042 0.105 0 0
M  V30 4 N -1.7083 -0.665 0 0
M  V30 5 C -0.3747 0.105 0 0
M  V30 6 C -0.3747 1.645 0 0
M  V30 7 * -0.8192 1.3883 0 0
M  V30 8 O -0.8192 3.6983 0 0
M  V30 9 C 0.5145 4.4683 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 2 2 3
M  V30 3 1 3 4
M  V30 4 2 4 5
M  V30 5 1 5 6
M  V30 6 2 1 6
M  V30 7 1 7 8 ENDPTS=(3 1 5 6) ATTACH=ANY
M  V30 8 1 8 9
M  V30 END BOND
M  V30 END CTAB
M  END''')
pv1
```
output: 
![image](https://user-images.githubusercontent.com/48350636/212526360-90b1c931-786f-4f87-ba01-edcc1e70af5e.png)

**Screenshots**
But i get this:
![image](https://user-images.githubusercontent.com/48350636/212526013-81dc953d-49f1-4568-bc65-0aaa173cc1ce.png)

**Configuration (please complete the following information):**
 - RDKit version: 2022.9.3
 - OS:windows10
 - Are you using conda? no, i install by pip

**Additional context**
it's and same case with cxsmiles:
![image](https://user-images.githubusercontent.com/48350636/212526588-b9be940c-4877-48f4-a93b-f9739820ad1c.png)

and same case in  web **rdkit,js 2022.9.3**:
![image](https://user-images.githubusercontent.com/48350636/212526541-cd755f38-a6c0-4944-aa2b-c94ad123a182.png)

**Comment by DavidACosgrove** [comment]
Hi @ShangChien ,
Yes, sorry. This is fixed and should behave correctly in the upcoming patch release. 
Dave
