### ISSUE TITLE
Updating the C++-related dependencies in the installation guide

### ISSUE THREAD

**Issue by chmnk** [rdkit/rdkit#5985]
**Is your feature request related to a problem? Please describe.**
When I tried to build a newer version of RDKit from sources in an existing conda environment, it failed at being not able to find the \<charconv\> header in [MolFileParser.cpp](https://github.com/rdkit/rdkit/blob/286cb213026242a78b4563b60763382df0297810/Code/GraphMol/FileParsers/MolFileParser.cpp#L36).
As far as I understand, to use C++17 and thus  \<charconv\>, g++ should be >= 8.3. However, it looks like the default gcc/gxx version in (some?) conda environments is older. For example, in my environment it was 7.3.0 by default. Conda's gxx compiler is connected to other packages tightly, once installed, so `conda install -y gxx_linux-64` would not update gxx to 8.3 from an older version. It would be nice to have it mentioned explicitly in the dependencies of the [installation guide](https://github.com/rdkit/rdkit/blob/master/Docs/Book/Install.md).

When I created a new environment with gxx_linux-64=11.2.0, it turned out that `py-boost` in `conda install -y boost-cpp boost py-boost` causes conflicts, because `py-boost`'s current maximum version is lower than the `boost`'s maximum available version, and older versions were not compatible with my freshly installed g++ 11.2.0. As a result, I just skipped `py-boost` for a while. Perhaps I should have first installed boost and then install the particular versions of the compilers (as it is actually mentioned in the [installation guide](https://github.com/rdkit/rdkit/blob/master/Docs/Book/Install.md)).

**Describe the solution you'd like**
It would be nice to update the "Building from Source" and "How to build from source with Conda" Linux sections. 

- In the conda section, it would be helpful to explicitly provide and update the correct boost and gcc/gxx versions. 

- In the "Building from Source" section, the C++ standard and compiler versions are outdated and it would be nice to update them as well.

**Comment by greglandrum** [comment]
Confirmed. That documentation is in dire need of updating.
