### ISSUE TITLE
CanonicalRankAtomsInFragment example in the documentation is not reproducible

### ISSUE THREAD

**Issue by chmnk** [rdkit/rdkit#5986]
**Describe the bug**
The documentation's example of [CanonicalRankAtomsInFragment](https://rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.CanonicalRankAtomsInFragment) produces a different output compared to the documentation.

**To Reproduce**
In the documentation:
```python
>>>mol = MolFromSmiles('C1NCN1.C1NCN1')
>>>list(CanonicalRankAtomsInFragment(mol, atomsToUse=range(0,4), breakTies=False))
[0,1,0,1,-1,-1,-1,-1]
>>>list(CanonicalRankAtomsInFragment(mol, atomsToUse=range(4,8), breakTies=False))
[-1,-1,-1,-1,0,1,0,1]
```

My RDKit's behaviour:
```python
>>>mol = Chem.MolFromSmiles('C1NCN1.C1NCN1')
>>>print(list(Chem.CanonicalRankAtomsInFragment(mol, atomsToUse=range(0,4), breakTies=False)))
[4, 6, 4, 6, -1, -1, -1, -1]
>>>print(list(Chem.CanonicalRankAtomsInFragment(mol, atomsToUse=range(4,8), breakTies=False)))
[-1, -1, -1, -1, 4, 6, 4, 6]
>>>print(list(Chem.CanonicalRankAtomsInFragment(mol, atomsToUse=range(0,4), breakTies=True)))
[4, 6, 5, 7, -1, -1, -1, -1]
>>>print(list(Chem.CanonicalRankAtomsInFragment(mol, atomsToUse=range(4,8), breakTies=True)))
[-1, -1, -1, -1, 4, 6, 5, 7]
```

**Expected behaviour**
Actually I find the example not very intuitive, cause in both cases `breakTies` is set to `True`. So I don't know what behaviour is expected.

**Configuration (please complete the following information):**
 - RDKit version: both '2023.03.1pre' and '2022.09.3'.
 - OS: CentOS Linux 7
 - Python version: 3.10 and 3.8
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? '2022.09.3' from conda-forge
 - If you are not using conda: how did you install the RDKit? '2023.03.1pre' from sources inside of a conda environment

**Comment by greglandrum** [comment]
Confirmed. Thanks for the bug report

**Comment by chmnk** [comment]
What behaviour is expected by the way? The same as in [CanonicalRankAtoms](https://rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.CanonicalRankAtoms), but with -1 on unlisted atoms, or something else?

**Comment by greglandrum** [comment]
I think the behavior of the code is fine sincethe relative ranking of the atoms is correct. The documentation is incorrect and should be fixed.
