### ISSUE TITLE
Ability to conserve sGroups and transfer to other molecules from Python

### ISSUE THREAD

**Issue by bjonnh-work** [rdkit/rdkit#5989]
**Is your feature request related to a problem? Please describe.**

When using a normalizer (and a few other methods as I could see in some open issues), the Sgroups are lost.

**Describe the solution you'd like**
The ability to reapply, from Python code, the sgroups of a molecule to a transformed molecule. I understand it can be tricky if bonds and atoms change, but that's something that could eventually be the responsibility of the user.

**Describe alternatives you've considered**
Another alternative would be to make all rdkit methods keep the sgroup information. While it would be ideal, I understand that it could make things a bit complex on your side.

**Additional context**
We are using sgroups for molecule registration (through custom mol hashes) and the information is lost if the normalizer applied any transformation to the molecule.

**Comment by greglandrum** [comment]
@bjonnh-work : do you have a couple of non-proprietary examples you can provide where the transformations remove SGroups?
And just to be sure I understand: you would want to be able to transfer SGroups where atoms/bonds have been removed?

**Comment by bjonnh-work** [comment]
In this case, the bond is just transformed:
```

  Ketcher  1192314362D 1   1.00000     0.00000     0

  7  7  0  0  1  0  0  0  0  0999 V2000
    5.4250   -9.3750    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    4.4913   -9.7332    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
    4.5437  -10.7320    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    5.5096  -10.9908    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.0542  -10.1520    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.6528   -9.1886    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.8680  -11.9244    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  1  0  0  0
  3  4  1  0  0  0  0
  4  5  1  0  0  0  0
  5  1  2  0  0  0  0
  2  6  2  0  0  0  0
  4  7  2  0  0  0  0
M  STY  1   1 DAT
M  SLB  1   1   1
M  SAL   1  2   2   3
M  SDT   1 override                                              
M  SDD   1     5.3937  -11.7820    DA    ALL  1      1  
M  SED   1 somethingthatgetslost
M  END
```

This is an example.

If you run it through a normalizer, the sgroup is lost:
```
m='\n  Ketcher  1192314362D 1   1.00000     0.00000     0\n\n  7  7  0  0  1  0  0  0  0  0999 V2000\n    5.4250   -9.3750    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    4.4913   -9.7332    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0\n    4.5437  -10.7320    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    5.5096  -10.9908    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.0542  -10.1520    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    3.6528   -9.1886    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    5.8680  -11.9244    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\n  2  3  1  1  0  0  0\n  3  4  1  0  0  0  0\n  4  5  1  0  0  0  0\n  5  1  2  0  0  0  0\n  2  6  2  0  0  0  0\n  4  7  2  0  0  0  0\nM  STY  1   1 DAT\nM  SLB  1   1   1\nM  SAL   1  2   2   3\nM  SDT   1 override                                              \nM  SDD   1     5.3937  -11.7820    DA    ALL  1      1  \nM  SED   1 somethingthatgetslost\nM  END\n'
mo=Chem.MolFromMolBlock(m)
mo.Debug()
from rdkit.Chem.MolStandardize import rdMolStandardize
normalizer = rdMolStandardize.Normalizer()
normalizer.normalize(mo).Debug()
```

If the atom is removed, the s-group would probably not make sense anyway so it is fine if it is removed.
