### ISSUE TITLE
BCUT_CHGX has issues with some atoms

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#5990]
```
>>> Descriptors.BCUT2D_CHGHI(Chem.MolFromSmiles("[Na+]"))
nan
```

```
>>> Descriptors.BCUT2D_CHGHI(Chem.MolFromSmiles("[Cl-]"))
-1.0
```

**Comment by bp-kelley** [comment]
This was raised in #5824

**Comment by bp-kelley** [comment]
So the problem is that the gasteiger charges used don't have an entry for [Na+] and this error is not being reported to python.

**Comment by greglandrum** [comment]
I don't think this is a bug. The descriptors calculators do not generally throw exceptions when they cannot compute a value (for whatever reason). It's generally the responsibility of client code to detect these situations and handle them.

**Comment by greglandrum** [comment]
Closing this because I think it's expected behavior. Please reopen if you think that's wrong.
