### ISSUE TITLE
Problems with substructure search Beilstein generics groups

### ISSUE THREAD

**Issue by aigulkhkmv** [rdkit/rdkit#6001]
Dear RDKit developers,

**Description:**

I want to check containing a heterocycle with specific functional group in the molecule, for example heterocycles with amine group. 
For this purpose I use substructure search with `Beilstein` generic groups. Algorithm works perfectly, in case of bond between functional group and carbon atom in heterocycle. However, algorithm couldn't find substructure of heterocycle-amine group if molecule contains the bond between functional group and non-carbon (for example `N`) in heterocycle. 

**To Reproduce:**
```python
from rdkit import Chem
from rdkit.Chem.Draw import MolsToGridImage
from rdkit.Chem import SetGenericQueriesFromProperties

#molecule template heterocycle-hn2
heterocycle_nh2 = '\n  Mrv1918 01182311512D          \n\n  0  0  0     0  0            999 V3000\nM  V30 ' \
                             'BEGIN CTAB\nM  V30 COUNTS 2 1 1 0 0\nM  V30 BEGIN ATOM\nM  V30 1 C -7.2701 2.6042 0 ' \
                             '0\nM  V30 2 N -5.9365 3.3742 0 0\nM  V30 END ATOM\nM  V30 BEGIN BOND\nM  V30 1 1 1 2\nM ' \
                             ' V30 END BOND\nM  V30 BEGIN SGROUP\nM  V30 1 SUP 0 -\nM  V30 ATOMS=(1 1) -\nM  V30 ' \
                             'LABEL="CHC"\nM  V30 END SGROUP\nM  V30 END CTAB\nM  END\n '

# create a query molecule
query_mol = Chem.MolFromMolBlock(heterocycle_nh2)
for sgs in Chem.GetMolSubstanceGroups(query_mol):
    if sgs.GetProp('TYPE') == 'SUP':
        query_mol.GetAtomWithIdx(sgs.GetAtoms()[0]).SetProp("atomLabel", sgs.GetProp("LABEL"))
query = Chem.Mol(query_mol)
```
**Query**:
<img width="137" alt="image" src="https://user-images.githubusercontent.com/40434269/214067184-14db0aba-5dbf-4ef6-b7f4-8de3a1c8c6da.png">

``` python
# configurate parameters for substructure search with generic group
Chem.SetGenericQueriesFromProperties(query)
params = Chem.SubstructMatchParameters()
params.useGenericMatchers = True

# create list of testing molecules
mols = [Chem.MolFromSmiles(i) for i in ['N1CCC(N)CC1', 'NC1=CNC=C1', 'N1C=CC2=C1C=C(N)C=C2', 'NN1CCCCC1', 'NN1C=CC=C1', 'NN1C=CC2=C1C=CC=C2']]

MolsToGridImage(mols)
```
<img width="530" alt="image" src="https://user-images.githubusercontent.com/40434269/214062223-fc6d341b-d62d-40b8-b829-6ebfe6327719.png">

``` python
for mol in mols:
    print(mol.HasSubstructMatch(query, params))
```
**Output**: `[True, True, True, False, False, False]`

So, for first 3 molecules with C-NH2 bond algorithm found heterocycle-NH2 substructure and for 3 molecules with N-NH2 bond algorithm couldn't find heterocycle-NH2 substructure.

Could you help please, how I can use a substructure search for heterocycle-NH2 in case of  `non-carbon-atoms`-`NH2` bond in the molecule? How I can found all heterocycles with NH2-group?  

Many thanks!

**Configuration (please complete the following information):**
 - `RDKit version:` 2022.09.3
 - `OS:` MacOS 10.15.7
 - `Python version (if relevant):` 3.9.6
 - `Are you using conda?` No   
 - `If you are not using conda: how did you install the RDKit?` Via poetry (pip)

**Comment by greglandrum** [comment]
@aigulkhkmv : the atom that the generic query is attached to is a C atom in your mol file. So the query can only match molecules which have a C connected to the amine.
If you change the C to an `A` in the mol block things should work.

There's a discussion to be had about whether or not this behavior should be changed since it may be overly confusing, but it is by design. I actually think it's fine because you may very well want to have an N which is connected to a C which is in an heterocycle and this is the only way to do that.

**Comment by aigulkhkmv** [comment]
@greglandrum, thanks a lot! Yes, after your explanations, it looks fine. Maybe covering this point in the documentation/tutorials will help for another users in the future.
