### ISSUE TITLE
add maxRecursiveMatches to SubstructMatchParameters

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#6017]
The need for an independant `maxMatches` parameter for recursive SMARTS matching came up while doing the fix for #888 (PR XXX).

**Comment by greglandrum** [comment]
Fixed in #6018

**Comment by d-b-w** [comment]
I think that this may have been accidentally closed - I don't see a parameter for maximum recursive matches.

**Comment by greglandrum** [comment]
Yeah, that was a mistake. Reopening
