### ISSUE TITLE
enhanced stereo is still included in CXSMILES if isomericSmiles=False

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#6040]
**Describe the bug**
Heres' the reproducible;
```
In [6]: m = Chem.MolFromSmiles('O[C@H](Br)[C@H](F)C |&1:1,3|')

In [7]: Chem.MolToCXSmiles(m,isomericSmiles=False)
Out[7]: 'CC(F)C(O)Br |&1:1,3|'
```
This shouldn't happen.

Check the inclusion of bond wedges and cis/trans markers for ring bonds as well when fixing this.

**Configuration (please complete the following information):**
 - RDKit version: releases and master
 - OS:all

**Comment by HalflingHelper** [comment]
I'd love to take a crack at this one if no one else has started yet
