### ISSUE TITLE
Cannot identify SMILES

### ISSUE THREAD

**Issue by SouravDutta91** [rdkit/rdkit#6044]
**Configuration:**

- RDKit Version: Installed rdkit using pip
- Operating system: 
- Python version (if relevant):
- Are you using conda? Yes, but used pip to install rdkit
- If you are using conda, which channel did you install the rdkit from? Not relevant
- If you are not using conda: how did you install the RDKit? pip

**Description:**

I am using the SmilesPE library (https://github.com/XinhaoLi74/SmilesPE) which uses rdkit to generate embeddings for SMILES which I want to use later on. In my data, I have some specific SMILES (maybe around 5-6 of them) which are not parsable by rdkit. The Chem.MolFromSmiles(smiles) code returns None as it is unable to identify and parse the smile. That is why I think the next line of code (ans = list(range(m.GetNumAtoms()))) gives the error below because Nonetype does not have the GetNumAtoms() function.

One solution to this is that I remove those particular smiles from my data. However, I want to ask people here... what I need to do if I want rdkit to be able to identify and parse such smile values. One such smile value is [Cl]|[Sn](|[Cl])(|[Cl])|[Cl] foe which I have shown the error below.

This is the error I am getting: 

> [11:51:50] SMILES Parse Error: syntax error while parsing: [Cl]|[Sn](|[Cl])(|[Cl])|[Cl]
> [11:51:50] SMILES Parse Error: Failed parsing SMILES '[Cl]|[Sn](|[Cl])(|[Cl])|[Cl]' for input: '[Cl]|[Sn](|[Cl])(|[Cl])|[Cl]'

> AttributeError                            Traceback (most recent call last)
> /var/folders/v_/lk75rmrs7lj89cc5gnrrvtzh0000gn/T/ipykernel_11215/1080453894.py in <module>
>       2 
>       3 output = codecs.open('SPE_smile.txt', 'w')
> ----> 4 learn_SPE(new_smiles, output, 300, min_frequency=10, augmentation=1, verbose=True, total_symbols=True)
> 
> ~/opt/anaconda3/lib/python3.9/site-packages/SmilesPE/learner.py in learn_SPE(infile, outfile, num_symbols, min_frequency, augmentation, verbose, total_symbols)
>     215 
>     216 
> --> 217     vocab = get_vocabulary(infile, augmentation=augmentation)
>     218     sorted_vocab = sorted(vocab.items(), key=lambda x: x[1], reverse=True)
>     219 
> 
> ~/opt/anaconda3/lib/python3.9/site-packages/SmilesPE/learner.py in get_vocabulary(smiles, augmentation, exclusive_tokens)
>      77         for i in mb:
>      78             for smi in progress_bar(smiles, parent=mb):
> ---> 79                 randomized_smi = randomize_smiles(smi)
>      80                 vocab[randomized_smi] += 1
>      81 
> 
> ~/opt/anaconda3/lib/python3.9/site-packages/SmilesPE/learner.py in randomize_smiles(smiles)
>      31 
>      32     m = Chem.MolFromSmiles(smiles)
> ---> 33     ans = list(range(m.GetNumAtoms()))
>      34     np.random.shuffle(ans)
>      35     nm = Chem.RenumberAtoms(m,ans)
> 
> AttributeError: 'NoneType' object has no attribute 'GetNumAtoms'

**Comment by rapodaca** [comment]
> One such smile value is [Cl]|[Sn](https://github.com/rdkit/rdkit/issues/%7C%5BCl%5D)(|[Cl])|[Cl] foe which I have shown the error below.

That SMILES looks invalid. The pipe character (`|`) is not part of the syntax. It's part of CXSMILES, but may not be embedded *within* the SMILES part.

**Comment by greglandrum** [comment]
As @rapodaca said: these are not valid SMILES.
