### ISSUE TITLE
fix or remove FastSDMolSupplier

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#605]
Chem.FastSDMolSupplier (a module I had not heard of) has a different understanding of the SDF format than the rest of the toolkit. It is a thin wrapper on top of the SDMolSupplier which finds the record offsets in Python with the assumption that the SD contents are sufficiently clean.

The code is somewhat broken. It assume that "$$$$\n" only exists at the end of the record. This will incorrectly match a tag data line like "ABC$$$$\n". A better test is "\n$$$$\n", though this is also an approximation. The format allows that line in other parts of the record, and the terminal line need only *start* with the $$$$, so in principle  "\n$$$$" is the better choice - though I do not want to encourage people to use anything other than "$$$$\n".

As a result, it is not hard to construct an SD file which will have different result when parsed as a FastSDMolSupplier vs. an SDMolSupplier or ForwardSDMolSupplier.

The FastSDMolSupplier class exists for faster initial indexing performance. My tests show that SDMolSupplier(fname)[i] is slower than FastSDMolSupplier(fname)[i] when i> ~10,000. That is, given a file with 25K structures, the fast version (which indexes the complete file first) is about 1/4th the performance of MolSupplier for i=2000 but is 2.2x the performance for i=20000.

Molecule iteration speed across FastSDMolSupplier, SDMolSupplier, and ForwardSDMolSupplier is essentially the same.

If you want to keep FastSDMolSupplier then I suggest renaming "init() to "_init()" (as that code should not be part of the public API),  using "\n$$$$\n" as the recogTxt, and documenting that it only supports a subset of the SD file format.

Personally, I suggest that it be removed. I see no evidence that FastSDMolSupplier is in use, and the only real use case I see for it is to determine the number of records in an SD file, which is better handled (at that level of approximation) by text.count("\n$$$$")

**Comment by bp-kelley** [comment]
I agree, we could (for now) have FastSDMolSupplier alias SDMolSupplier while it is being deprecated or improved.  The only reason something like this should exist is for random indexing, IMHO and our efforts should be made at making SDMolSupplier faster.
