### ISSUE TITLE
queryMol from FindMCS doesn't match mols used to generate MCS

### ISSUE THREAD

**Issue by paconius** [rdkit/rdkit#6082]
**Describe the bug**
The queryMol generated by rdFMCS.FindMCS does not match the mol used to generate the MCS.

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import rdFMCS
refMol = Chem.MolFromSmiles("CCc1ccc2nc(CO)cn2n1")
prod = Chem.MolFromSmiles("OCc1cc2nc(C3CC3)ccn2n1")
mcs = rdFMCS.FindMCS([prod, refMol])
print(Chem.MolToSmiles(mcs.queryMol))
refMol.GetSubstructMatch(mcs.queryMol)
prod.GetSubstructMatch(mcs.queryMol)
```

Output:
```
>>> from rdkit import Chem
>>> from rdkit.Chem import rdFMCS
>>> refMol = Chem.MolFromSmiles("CCc1ccc2nc(CO)cn2n1")
>>> prod = Chem.MolFromSmiles("OCc1cc2nc(C3CC3)ccn2n1")
>>> mcs = rdFMCS.FindMCS([prod, refMol])
>>> print(Chem.MolToSmiles(mcs.queryMol))
*~*~*(~*)~*~*~*~*~*(~*)~*
>>> refMol.GetSubstructMatch(mcs.queryMol)
(0, 1, 2, 3, 12, 11, 5, 6, 7, 8, 10)
>>> prod.GetSubstructMatch(mcs.queryMol)
()
>>>
```

**Expected behavior**
Since FindMCS finds the MCS between prod and refMol, the resulting MCS queryMol is expected to match against both of those starting mols. In this case it matches against refMol, but not prod.

**Configuration (please complete the following information):**
 - RDKit version:  2022.03.1
 - OS: Windows 11
 - Python version (if relevant): 3.7.7
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? rdkit

**Comment by paconius** [comment]
I've been looking further into this and I discovered that you can get greater granularity on the found match by converting the returned queryMol to SMARTS (as compared to converting it to SMILES as I did originally). In SMARTS notation the returned match is:

`[#6]-[#6]-[#6](:[#6]):[#7]:[#7]:[#6]:[#7]:[#6](-[#6]):[#6]`

Comparing this against the original molecules confirms that this is not a valid substructure of 'prod', so it is still very much a mystery why this was returned as the MCS.

I leaning towards the fact that both ring systems contain different positioning of the same "nncn" motif that might be confusing the algorithm. However, my expectation is that FindMCS should never return a result that does not match both of the input molecules.

**Comment by greglandrum** [comment]
It's expected that the query molecule won't convert well to SMILES (as opposed to SMARTS), but the fact that `mcs.queryMol` doesn't match one of the molecules is indeed a bug.
