### ISSUE TITLE
LargestFragmentChooser removes valid StereoGroups

### ISSUE THREAD

**Issue by lavoisiermod** [rdkit/rdkit#6099]
**Describe the bug**
When `rdMolStandardize.LargestFragmentChooser().choose()` is applied to a molecule with some StereoGroups, it removes them.

**To Reproduce**
```
m3bis = Chem.MolFromSmiles('Cl.O[C@@H]1CC[C@H](Cl)C[C@@H]1O |a:5,&1:2,8|')
m3bis
```
![image](https://user-images.githubusercontent.com/77072007/219785376-e9968f88-693b-4925-98e4-b6afeef0f6a3.png)
```
len(m3bis.GetStereoGroups())
# 2
m3bislf = rdMolStandardize.LargestFragmentChooser().choose(m3bis)
m3bislf
```
![image](https://user-images.githubusercontent.com/77072007/219785575-6a11552b-b7f4-497d-a893-7ce374f7f34c.png)
```
len(m3bislf.GetStereoGroups())
# 0
Chem.MolToCXSmiles(m3bislf)
# 'O[C@@H]1CC[C@H](Cl)C[C@@H]1O'
```
**Expected behavior**
The largest fragment should still have the StereoGroups it had before, obviously renumbered as the atom indexing has changed.
So in this case:
`'O[C@@H]1CC[C@H](Cl)C[C@@H]1O |a:4,&1:1,7|'`

**Screenshots**
As per above code.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.1
 - OS: Windows 10
 - Python version (if relevant): 3.10.6 (is it relevant? not sure)
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? NA
 - If you are not using conda: how did you install the RDKit? NA

**Additional context**
I saw #4642. Perhaps related?

**Comment by greglandrum** [comment]
Yeah, this is a duplicate with #4642
