### ISSUE TITLE
Excessive (incorrect) Chirality Perception from SDF

### ISSUE THREAD

**Issue by hypnopump** [rdkit/rdkit#6104]
-----------------------------------------

**Describe the bug**
`Chem.MolFromMolFile` reads the molecule in https://files.rcsb.org/ligands/download/6IO_ideal.sdf with chirality assigned to carbon atoms in the central ring. This is incorrect as the corresponding smiles ([which can be seen here](https://www.rcsb.org/ligand/6IO)) are achiral: `c1cnc(nc1NC2CCC(CC2)Nc3ccnc(n3)C(F)(F)F)C(F)(F)F`

Extra: i have confirmed it is not an SDF error as reading it with openeye reads an achiral molecule

**To Reproduce**
```python
from rdkit import Chem
!wget https://files.rcsb.org/ligands/download/6IO_ideal.sdf 
mol = Chem.MolFromMolFile("6IO_ideal.sdf")
Chem.MolToSmiles(mol)  # incorrect, chirality assigned
````
**Expected behavior**

This is the correct molecule (smiles: `c1cnc(nc1NC2CCC(CC2)Nc3ccnc(n3)C(F)(F)F)C(F)(F)F`): 
<img width="365" alt="Captura de Pantalla 2023-02-18 a las 11 56 48" src="https://user-images.githubusercontent.com/16491423/219856622-3bb66e14-8830-4dea-aea1-2a58e5f30b64.png">
and this is the molecule one gets with rdkit (smiles: `FC(F)(F)c1nccc(N[C@H]2CC[C@@H](Nc3ccnc(C(F)(F)F)n3)CC2)n1`): 
<img width="371" alt="Captura de Pantalla 2023-02-18 a las 11 56 42" src="https://user-images.githubusercontent.com/16491423/219856633-175bb0b2-285d-4531-8cb6-e32712087293.png">

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.4
 - OS: macOS 12.6.2
 - Python version (if relevant): 3.10.8
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? `-c rdkit`

**Comment by wopozka** [comment]
Well, when you open given sdf in eg MarvinSketch, it provides molecule with defined stereochemistry, so I would assume the sdf file might be different from given there SMILES. Have you thought about it?

**Comment by bp-kelley** [comment]
The molecule certainly has stereo, here it is in maestro:

<img width="689" alt="image" src="https://github.com/rdkit/rdkit/assets/9888416/11e6f56d-d874-4c9f-97a0-da9d31901d4d">

What Marvin and the RDKit are doing are assigning stereo from the 3D coordinates which is quite reasonable.

**Comment by greglandrum** [comment]
As @bp-kelley said: stereo is being assigned because the molecule has 3D coordinates, so every potential chiral center is automatically defined unless it has a wiggly bond drawn to it to mark it is as unknown.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
