### ISSUE TITLE
Drawing in ACS1996 mode throws ValueError: Bad Conformer Id if molecule has no coords. 

### ISSUE THREAD

**Issue by DavidACosgrove** [rdkit/rdkit#6112]
-----------------------------------------

**Describe the bug**
Attempting to draw with ACS1996 mode a molecule that doesn't have coordinates throws a ValueError exception.  Since prepareMolBeforeDrawing=True is the default behaviour, and that includes creating 2D coords, this is undesirable.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D, rdDepictor
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG
from rdkit import rdBase
print(rdBase.rdkitVersion)
mol = Chem.MolFromSmiles('[*:1]N[*:2]')
drawer = rdMolDraw2D.MolDraw2DSVG(-1,-1)
rdMolDraw2D.DrawMoleculeACS1996(drawer, mol)
drawer.FinishDrawing()
SVG(drawer.GetDrawingText())
```

**Expected behavior**
Coords should be created if necessary, so long as drawOptions.prepareMolBeforeDrawing is true.

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.4
 - OS: [e.g. Ubuntu 20.04] macOS Ventura 13.2.1 Apple Silicon
 - Python version (if relevant): 3.10
 - Are you using conda? mamba
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
I think that the cause of the problem is that ACS1996 needs the mean bond length in the molecule to calculate the pixel scale, and this occurs before the drawing code generates the coords if it needs them.
Working on a fix.

**Comment by greglandrum** [comment]
Fixed by #6113
