### ISSUE TITLE
RunReactants Gives Wrong Result in Intramolecular Reaction

### ISSUE THREAD

**Issue by li-ziang** [rdkit/rdkit#6136]
-----------------------------------------

**Describe the bug**
RunReactants Give Wrong Result in Intramolecular Reaction

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem import AllChem

rxn = AllChem.ReactionFromSmarts('[C:2]-[C:1]-[O:4]-[C:3]-[C:5]>>O-[C:1]-[C:2].[C:5]-[C:3]-O')
ps = rxn.RunReactants((Chem.MolFromSmiles('C1CCOCC1'),))
[Chem.MolToSmiles(x[0],isomericSmiles=True) for x in ps]

```
Output:
```
['CCCO', 'CCCO']
```

**Expected behavior**
This is because there are two products in the Smarts string, and the function will generate two products according to this template during runtime. From the results, these two products are incorrect, and I expect the result to be 'OCCCCCO'.

Using template '[C:5]1-[C:2]-[C:1]-[O:4]-[C:3]-[C:6]1>>O-[C:1]-[C:2]-[C:5]-[C:6]-[C:3]-O' can solve this problem, but it will fail when the number of carbons in the ring changes. I would like to know if we can start from changing the RunReactants to solve this problem.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.4
 - OS: Ubuntu 18.04
 - Python version : 3.9.16
 - Are you using conda: Y
 - If you are using conda, which channel did you install the rdkit from: pypi

**Comment by jasondbiggs** [comment]
I believe this is a duplicate of #5159

**Comment by greglandrum** [comment]
I agree with @jasondbiggs, this is the same thing as #5159 and this is the expected behavior: you have asked for two products, so you get two products.
The special case for intramolecular reactions where you only want a single product would be to put the products in the SMARTS into parentheses:
```
rxn = AllChem.ReactionFromSmarts('[C:2]-[C:1]-[O:4]-[C:3]-[C:5]>>(O-[C:1]-[C:2].[C:5]-[C:3]-O)')
```

**Comment by li-ziang** [comment]
Thanks!
