### ISSUE TITLE
Something wrong about the caculation about the molecular descriptors

### ISSUE THREAD

**Issue by wei-yx18** [rdkit/rdkit#6152]
### Discussed in https://github.com/rdkit/rdkit/discussions/6151

<div type='discussions-op-text'>

<sup>Originally posted by **wei-yx18** March  2, 2023</sup>
I have used rdkit.Chem.Descriptors to calculate the molecular descriptors 2 days ago, and get 208 descriptors using Descriptors._descList. But today there are only 123 descriptors, which are the first 123 of the previous 207 descriptors. 
I use the same codes and wonder why is this happen?</div>

**Comment by greglandrum** [comment]
This is a discussion
