### ISSUE TITLE
Adding transparency parameter in c++ drawing svg

### ISSUE THREAD

**Issue by thegodone** [rdkit/rdkit#616]
In order to superpose images in RDKitjs (all white zone can be transparent) we need to modify the output of the svg using this replace method in javascript:

molsvg = molsvg.replace("<rect style='opacity:1.0", "<rect style='opacity: 0");

Can we add a opacity parameter in the c++ code in order to generate the the rect with transparency ?

bet regards

**Comment by greglandrum** [comment]
This is connected to #587 .

This morning I checked in a change (9314b3d) that allows the background to be skipped or the color to be changed. Please take a look at that commit and see if it provides enough functionality.

**Comment by thegodone** [comment]
Dear Greg, Yes it's enough thanks
