### ISSUE TITLE
GetSubstructMatches does not find all matches in large molecule

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#6163]
### Discussed in https://github.com/rdkit/rdkit/discussions/6161

<div type='discussions-op-text'>

<sup>Originally posted by **iuhgnor** March  4, 2023</sup>
`GetSubstructMatches` seems to miss matches in large molecule, and setting the parameter `maxMatches`  to a large num can't solve the proplem. Here is an example. Thanks for suggestions.

```python
import rdkit
from rdkit import Chem

print(f'RDKit version: {rdkit.__version__}\n')

smis = {
    'short chain':
    'O=C(Oc1ccc(OC(=O)c2ccc3c(c2)C(=O)N(c2ccc(N4C(=O)c5ccc(C(=O)Oc6ccc(OC(=O)c7ccc8c(c7)C(=O)N(c7ccc(N9C(=O)c%10ccc(C(=O)Oc%11ccc(OC(=O)c%12ccc%13c(c%12)C(=O)N(c%12ccc(N%14C(=O)c%15ccc(C(=O)Oc%16ccc(OC(=O)c%17ccc%18c(c%17)C(=O)N(c%17ccc(N%19C(=O)c%20ccccc%20C%19=O)cc%17)C%18=O)cc%16)cc%15C%14=O)cc%12)C%13=O)cc%11)cc%10C9=O)cc7)C8=O)cc6)cc5C4=O)cc2)C3=O)cc1)c1ccc2c(c1)C(=O)N(c1ccccc1)C2=O',
    'long chain':
    'O=C(Oc1ccc(OC(=O)c2ccc3c(c2)C(=O)N(c2ccc(N4C(=O)c5ccc(C(=O)Oc6ccc(OC(=O)c7ccc8c(c7)C(=O)N(c7ccc(N9C(=O)c%10ccc(C(=O)Oc%11ccc(OC(=O)c%12ccc%13c(c%12)C(=O)N(c%12ccc(N%14C(=O)c%15ccc(C(=O)Oc%16ccc(OC(=O)c%17ccc%18c(c%17)C(=O)N(c%17ccc(N%19C(=O)c%20ccc(C(=O)Oc%21ccc(OC(=O)c%22ccc%23c(c%22)C(=O)N(c%22ccc(N%24C(=O)c%25ccc(C(=O)Oc%26ccc(OC(=O)c%27ccc%28c(c%27)C(=O)N(c%27ccc(N%29C(=O)c%30ccc(C(=O)Oc%31ccc(OC(=O)c%32ccc%33c(c%32)C(=O)N(c%32ccc(N%34C(=O)c%35ccc(C(=O)Oc%36ccc(OC(=O)c%37ccc%38c(c%37)C(=O)N(c%37ccc(N%39C(=O)c%40ccc(C(=O)Oc%41ccc(OC(=O)c%42ccc%43c(c%42)C(=O)N(c%42ccc(N%44C(=O)c%45ccc(C(=O)Oc%46ccc(OC(=O)c%47ccc%48c(c%47)C(=O)N(c%47ccc(N%49C(=O)c%50ccc(C(=O)Oc%51ccc(OC(=O)c%52ccc%53c(c%52)C(=O)N(c%52ccc(N%54C(=O)c%55ccc(C(=O)Oc%56ccc(OC(=O)c%57ccc%58c(c%57)C(=O)N(c%57ccc(N%59C(=O)c%60ccc(C(=O)Oc%61ccc(OC(=O)c%62ccc%63c(c%62)C(=O)N(c%62ccc(N%64C(=O)c%65ccc(C(=O)Oc%66ccc(OC(=O)c%67ccc%68c(c%67)C(=O)N(c%67ccc(N%69C(=O)c%70ccc(C(=O)Oc%71ccc(OC(=O)c%72ccc%73c(c%72)C(=O)N(c%72ccc(N%74C(=O)c%75ccc(C(=O)Oc%76ccc(OC(=O)c%77ccc%78c(c%77)C(=O)N(c%77ccc(N%79C(=O)c%80ccc(C(=O)Oc%81ccc(OC(=O)c%82ccc%83c(c%82)C(=O)N(c%82ccc(N%84C(=O)c%85ccc(C(=O)Oc%86ccc(OC(=O)c%87ccc%88c(c%87)C(=O)N(c%87ccc(N%89C(=O)c%90ccc(C(=O)Oc%91ccc(OC(=O)c%92ccc%93c(c%92)C(=O)N(c%92ccc(N%94C(=O)c%95ccc(C(=O)Oc%96ccc(OC(=O)c%97ccc%98c(c%97)C(=O)N(c%97ccc(N%99C(=O)c%(100)ccc(C(=O)Oc%(101)ccc(OC(=O)c%(102)ccc%(103)c(c%(102))C(=O)N(c%(102)ccc(N%(104)C(=O)c%(105)ccc(C(=O)Oc%(106)ccc(OC(=O)c%(107)ccc%(108)c(c%(107))C(=O)N(c%(107)ccc(N%(109)C(=O)c%(110)ccc(C(=O)Oc%(111)ccc(OC(=O)c%(112)ccc%(113)c(c%(112))C(=O)N(c%(112)ccc(N%(114)C(=O)c%(115)ccccc%(115)C%(114)=O)cc%(112))C%(113)=O)cc%(111))cc%(110)C%(109)=O)cc%(107))C%(108)=O)cc%(106))cc%(105)C%(104)=O)cc%(102))C%(103)=O)cc%(101))cc%(100)C%99=O)cc%97)C%98=O)cc%96)cc%95C%94=O)cc%92)C%93=O)cc%91)cc%90C%89=O)cc%87)C%88=O)cc%86)cc%85C%84=O)cc%82)C%83=O)cc%81)cc%80C%79=O)cc%77)C%78=O)cc%76)cc%75C%74=O)cc%72)C%73=O)cc%71)cc%70C%69=O)cc%67)C%68=O)cc%66)cc%65C%64=O)cc%62)C%63=O)cc%61)cc%60C%59=O)cc%57)C%58=O)cc%56)cc%55C%54=O)cc%52)C%53=O)cc%51)cc%50C%49=O)cc%47)C%48=O)cc%46)cc%45C%44=O)cc%42)C%43=O)cc%41)cc%40C%39=O)cc%37)C%38=O)cc%36)cc%35C%34=O)cc%32)C%33=O)cc%31)cc%30C%29=O)cc%27)C%28=O)cc%26)cc%25C%24=O)cc%22)C%23=O)cc%21)cc%20C%19=O)cc%17)C%18=O)cc%16)cc%15C%14=O)cc%12)C%13=O)cc%11)cc%10C9=O)cc7)C8=O)cc6)cc5C4=O)cc2)C3=O)cc1)c1ccc2c(c1)C(=O)NC2=O'
}

for name, smi in smis.items():
    print(f'{name}:')
    mol = Chem.MolFromSmiles(smi)
    mol = Chem.AddHs(mol)
    print(f'Total atom num: {mol.GetNumAtoms()}')

    sma = '*~[#7X3$(*~[#6X3])](~*)~*'
    pat = Chem.MolFromSmarts(sma)
    matches = mol.GetSubstructMatches(pat, maxMatches=1000000)
    print(f'GetSubstructMatches num: {len(matches)}')

    count = 0
    for atom in mol.GetAtoms():
        symbol = atom.GetSymbol()
        degree = atom.GetDegree()
        if symbol == 'N' and degree == 3:
            for na in atom.GetNeighbors():
                if na.GetSymbol() == 'C' and na.GetDegree() == 3:
                    count += 1
                    break
    print(f'Total match num: {count}\n')
```

Output:
```txt
RDKit version: 2022.09.1

short chain:
Total atom num: 242
GetSubstructMatches num: 9
Total match num: 9

long chain:
Total atom num: 1258
GetSubstructMatches num: 34
Total match num: 47
```
</div>

**Comment by dessygil** [comment]
If no one claims this bug, I would like to try it after I get #6119 done.

**Comment by greglandrum** [comment]
@dessygil, let's see what happens. I'd like to leave this one open for a bit in case we get applications from students interested in doing Google Summer of Code (we ask them to fix a bug as part of the application process).

**Comment by AdityaTaware7** [comment]
I would like to contribute to #6163 issue. Would you like to guide me in making my first open source contribution

**Comment by greglandrum** [comment]
Hi @AdityaTaware7, I'm happy to help. Before we start though: do you know C++?

**Comment by AdityaTaware7** [comment]
Yes I have knowledge about C++

**Comment by greglandrum** [comment]
@AdityaTaware7 Excellent! You should start by getting a C++ development environment setup, clone the RDKit repo on your machine, and then get an RDKit build working (and the tests running) in that environment. Let me know when you've done that (or if you have questions along the way) and we can move on to how to actually fix the bug.

**Comment by AdityaTaware7** [comment]
Yeah I already have a C++ development setup and I have cloned the repo as well but I am not understanding how to get RDKit build working

**Comment by greglandrum** [comment]
I'm going to do a blog post on this in the very near future, but I will take this opportunity to beta test it on you. :-)

Here's a set of instructions for setting up a build environment on a linux system where you use conda to install the dependencies

**Comment by AdityaTaware7** [comment]
Sorry I was busy for last 2 days a bit. I think you forgot to mention the instructions... and actually I am having a windows machine so how should I proceed?

**Comment by vandan-revanur** [comment]
@greglandrum It looks like you missed adding a link to the build instructions. Could you please add that?

**Comment by greglandrum** [comment]
@vandan-revanur : thanks for the reminder!
The build instructions are here: https://greglandrum.github.io/rdkit-blog/posts/2023-03-17-setting-up-a-cxx-dev-env2.html

**Comment by HalflingHelper** [comment]
> Sorry I was busy for last 2 days a bit. I think you forgot to mention the instructions... and actually I am having a windows machine so how should I proceed?

@AdityaTaware7 I found that the easiest thing for me to do on windows was to set up the dev environment inside of [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). Then you can pretty much just follow the Linux instructions.

**Comment by joseerlang** [comment]
Hi there,
This ticket seems ok in RDKit version: 2024.09.1pre.

short chain:
Total atom num: 242
GetSubstructMatches num: 9
Total match num: 9

long chain:
Total atom num: 1258
GetSubstructMatches num: 47
Total match num: 47

**Comment by rachelnwalker** [comment]
Thank you @d-b-w and @joseerlang! Closing this issue.
