### ISSUE TITLE
Crash when parsing InChI

### ISSUE THREAD

**Issue by eloyfelix** [rdkit/rdkit#6172]
**Describe the bug**
I'm aware that parsing InChI is a risky business but RDKit is crashing when parsing some of them.

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

```python
from rdkit import Chem

mol = Chem.MolFromInchi("InChI=1S/2C18H36N3OP.2CH3.2ClH.Sn/c2*22-23(19-16-10-4-1-5-11-16,20-17-12-6-2-7-13-17)21-18-14-8-3-9-15-18;;;;;/h2*16-18H,1-15H2,(H3,19,20,21,22);2*1H3;2*1H;/q;;2*-1;;;+4/p-2")
```

```
****
Incomplete Code
This routine is still under development
Violation occurred on line 180 in file /Users/runner/work/rdkit-pypi/rdkit-pypi/build/temp.macosx-10.9-x86_64-cpython-310/rdkit/Code/GraphMol/Bond.cpp
Failed Expression: Bad bond type
****

...
...
...

RuntimeError: Incomplete Code
	This routine is still under development
	Violation occurred on line 180 in file Code/GraphMol/Bond.cpp
	Failed Expression: Bad bond type
	RDKIT: 2022.09.5
	BOOST: 1_78
```

**Expected behavior**
RDKit's default behaviour is to return `None` when failing to parse a molecule so that was the expected behavior.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.5
 - OS: OS X
 - If you are not using conda: how did you install the RDKit? pip

**Comment by wopozka** [comment]
Well, it looks the INChI is just wrong, and contains weird structures. You can read it by adding option sanitize=False, then it will create mol, which you can use for further processing. Weird enought there is still a problem, as one of the bond is defined as:

```
for bond in mol4.GetBonds():
    print(bond.GetBondType(), bond.GetBeginAtom().GetSymbol(), bond.GetEndAtom().GetSymbol())

...
rdkit.Chem.rdchem.BondType(255) O P
...
```

I would expect this bond to be UNSPECIFIED, as this one couses an error if you want to do something with it.

`Failed Expression: Bad bond type
RDKIT: 2022.09.1
BOOST: 1_74`

Anyway, corect INChI might help.

**Comment by greglandrum** [comment]
@eloyfelix as far as I can tell at least part of this is due to a bug in the InChI code: there's a bond type of 255 coming from the code, which is certainly not legal.
The RDKit should be doing a better job of reporting the problem, but the result is still going to be a failure to parse the molecule.

**Comment by greglandrum** [comment]
@eloyfelix where did that InChI come from? Do you have the mol block or SMILES that it was produced from?

**Comment by wopozka** [comment]
@greglandrum 
Marvin reads it and generates this SMILES

`[CH3-].[CH3-].Cl.Cl.[Sn+4].[O-3][P](=NC1CCCCC1)(=NC1CCCCC1)=[NH+]C1CCCCC1.O=P(NC1CCCCC1)(NC1CCCCC1)NC1CCCCC1`

**Comment by greglandrum** [comment]
> @greglandrum Marvin reads it and generates this SMILES
> 
> `[CH3-].[CH3-].Cl.Cl.[Sn+4].[O-3][P](=NC1CCCCC1)(=NC1CCCCC1)=[NH+]C1CCCCC1.O=P(NC1CCCCC1)(NC1CCCCC1)NC1CCCCC1`

yeah, but that's not a real molecule either...

**Comment by wopozka** [comment]
Yep so true, maybe generative model created it?

**Comment by greglandrum** [comment]
> sorry for the slow reply, I'm currently on leave. The InChI is from UniChem and its source is PubChem:
> 
> https://pubchem.ncbi.nlm.nih.gov/compound/139061126#section=InChI
> 

Thanks for that pointer. I've confirmed that the InChI code produces your InChI when given the mol block from PubChem, so at least we know that the problem is in the InChI library.

> I didn't expect the molecule to be correctly parsed but to point a never nice to see segfault! Many thanks for looking at it.

Agreed... it shouldn't lead to ugly error messages or crashes.
