### ISSUE TITLE
recent modification on molDraw2D affect rdkitjs rendering of molecule

### ISSUE THREAD

**Issue by thegodone** [rdkit/rdkit#618]
The last commits on molDraw2D produces an issue when transferring the svg string object from c++ into javascript.

This function was working before that time, and it's still working on 2015_3_1 RDKit version.

string Molecule::Drawing2D()
{
    RDDepict::compute2DCoords(*rdmol);
    WedgeMolBonds(*rdmol,&(rdmol->getConformer()));
    RDKit::MolDraw2DSVG drawer(300,300);
    drawer.drawMolecule(*rdmol);
    drawer.finishDrawing();
    return drawer.getDrawingText();
}

**Comment by greglandrum** [comment]
What's the error you see?

**Comment by thegodone** [comment]
I need to check if it's can from Emscripten issue... I will let you know

**Comment by thegodone** [comment]
Solved in the nightly last commits & compilation using emscripten clang 3.7
