### ISSUE TITLE
SimilarityMap(s) draw molecules differently from default molecule drawing

### ISSUE THREAD

**Issue by eguidotti** [rdkit/rdkit#6188]
**Describe the bug**
SimilarityMap(s) draw molecules that are different from the default molecule drawing. Specifically, 

1. pedix e.g. H $_2$ are converted to numbers e.g. H2
2. lines do not break and overlap with the letters of hetereoatoms
3. hetereoatoms are not aligned with bonds (e.g., bond with NH $_2$ starts from N in picture 1 but from H in picture 2 below)
4. structures are displayed differently (e.g., NH and H $_2$ N are inverted in the pictures below)

**To Reproduce**
Below an example that reproduces points 1-4:

```python
from rdkit.Chem import MolFromSmiles
from rdkit.Chem.Draw import SimilarityMaps
mol = MolFromSmiles('N=C(N)NCCc1c[nH]cn1')
```

```python
display(mol)
```
<img width="746" alt="Screenshot 2023-03-11 at 21 52 03" src="https://user-images.githubusercontent.com/24247667/224511083-64460baf-ee57-4a21-b23e-68c4b6ea3363.png">

```python
SimilarityMaps.GetSimilarityMapFromWeights(mol, [0 for i in range(mol.GetNumAtoms())], colorMap='Greys')
```
<img width="915" alt="Screenshot 2023-03-11 at 21 57 51" src="https://user-images.githubusercontent.com/24247667/224511305-7d93bbfd-a1ef-4618-8fa3-0996fb1e2329.png">

**Expected behavior**
I would expect the underlying molecular structure to be displayed in the same way.

**Screenshots**
See above.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.5
 - OS: MacOS Monterey 
 - Python version (if relevant): 3.9
 - Are you using conda? No 
 - If you are using conda, which channel did you install the rdkit from? pypi
 - If you are not using conda: how did you install the RDKit? pip install rdkit-pypi

**Comment by greglandrum** [comment]
Hi @eguidotti : this is expected behavor. `SimilarityMaps.GetSimilarityMapFromWeights()` uses old drawing code.
Here's a tutorial on how to generate similarity maps with the new code:
https://greglandrum.github.io/rdkit-blog/posts/2020-01-03-similarity-maps-with-new-drawing-code.html

Apologies on how confusing this currently is.

**Comment by eguidotti** [comment]
Thank you @greglandrum! I'm trying to move to the new code but I'm unable to reproduce the nice pictures on the blog post and I've opened #6190
