### ISSUE TITLE
can't kekulize molecule from those smiles

### ISSUE THREAD

**Issue by thegodone** [rdkit/rdkit#619]
Ive got this error message for the folllowing smiles:

Can't kekulize mol 
Could not sanitize molecule on line 2435
Can't kekulize mol 

188, 'n2c1c(cccc1)nc2c3ncsc3'
316, 'n1cccn1'
333, 'n1cnnc1'
364, 'n1cc(nc1)C'
393, 'n1cnnc1N'
463, '[O-][N+](=O)c1ncnn1'
477, 'n1ccnc1C'
746, 'n1c2ccccc2nn1'
1131, 'n2c1ccccc1nc2C'
1229, 'c1cccc2c1c(cn2)C'
2241, 'N#CN\\C(=N/C)NCCSCc1ncnc1C'
2436, 'O=C(O)[C@@H](N(C(=O)CCCC)Cc3ccc(c1ccccc1c2nnnn2)cc3)C(C)C'

I try to generate rdkit descriptors using the following code on rdkit 2015.03.1 version:
-------------
from rdkit import Chem
import cPickle,sys
from rdkit.ML.Descriptors import MoleculeDescriptors
from rdkit.Chem import Descriptors

nm=[x[0] for x in Descriptors._descList]

calc = MoleculeDescriptors.MolecularDescriptorCalculator(nm)
suppl = Chem.SmilesMolSupplier('/Users/mbp/Documents/abraham.txt',titleLine=False)

w = open('rdkitdesc.txt',"wb")
errors = open('rdkiterror.txt',"wb")

line = "Molid"
for names in nm:
	line = line+ ","+ names 
line = line+"\n";
w.write(line)
nDone=0
for mol in suppl: 
    nDone += 1
    line = str(nDone)    
    if mol is None: 
    	errors.write(line + ",Error\n" )
    	continue
    descrs = calc.CalcDescriptors(mol)
    for dec in descrs:
        line = line+ "," +str(dec)
    line = line+"\n";
    w.write(line)
w.close()
errors.close()
---------
Here the complete dataset 2465 molecules work over the complete list of 2674 molecules:
http://onschallenge.wikispaces.com/file/view/20120528CuratedData.xlsx/341079416/20120528CuratedData.xlsx

but CDK can generate the correct molecule.

**Comment by greglandrum** [comment]
These are the result of a bad/ambiguous aromatic SMILES from the CDK (I think this has been fixed in recent versions). Googling for the error message will turn up multiple mailing list descriptions of the problem and how to resolve it.
