### ISSUE TITLE
Installation hangs

### ISSUE THREAD

**Issue by d9748336** [rdkit/rdkit#6191]
**System details:**
![screenshot](https://user-images.githubusercontent.com/9325903/224721680-7ab4bf37-7644-4737-8504-33be3d9437ea.jpg)

**Expected behaviour**: rdkit installs

**Actual behaviour:** `conda install -c conda-forge rdkit` hangs indefinitely.

PS I'm attempting to install as root because I want it to be available to all users.

**Comment by greglandrum** [comment]
This is, if anything, a conda problem, not an RDKit bug.

**Comment by greglandrum** [comment]
@d9748336 you might want to try asking on the discussions tab and see if anyone else has seen this
