### ISSUE TITLE
Atom with multiple highlights has inconsistent highlight radius

### ISSUE THREAD

**Issue by ljmartin** [rdkit/rdkit#6194]
**Describe the bug**
Adding more than one highlight colour to an atom leads to having a larger highlight radius for that atom, whether or not radii are specified. It also looks like the actual highlights aren't being shown as semicircles (for two colours) or wedges (for three or more colours). 

**To Reproduce**
code here, image below.
```python
import rdkit
print(rdkit.__version__)
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
from collections import defaultdict
from IPython.display import Image


smi = 'CCC'
mol = Chem.MolFromSmiles(smi)

colors = [(0.9019607843137255, 0.6235294117647059, 0.0), 
          (0.33725490196078434, 0.7058823529411765, 0.9137254901960784),
         (0.0, 0.6196078431372549, 0.45098039215686275)]
highlightatoms = defaultdict(list)

for i in range(mol.GetNumAtoms()):
    highlightatoms[i].append(colors[0])

#KEY line: adding a second colour for one atom:   
highlightatoms[i].append(colors[1])

#can also see what happens when adding a third colour
#highlightatoms[i].append(colors[2])

#image stuff:
width=400
height=400
d2d = rdMolDraw2D.MolDraw2DCairo(width,height)
d2d.DrawMoleculeWithHighlights(mol,'mol',
                               dict(highlightatoms), #atom highlights
                               {},#bond highlights
                               {},#atom highlight radii,
                               {} #bond highlight radii
                              )
d2d.FinishDrawing()
png = d2d.GetDrawingText()
Image(png)
```

**Expected behavior**
I was expecting to see something like cell 20 in [this blog post](http://rdkit.blogspot.com/2020/04/new-drawing-options-in-202003-release.html) - half-circles for two colours with the same radius as other highlighted atoms. 

**Screenshots**
<img width="408" alt="Screenshot 2023-03-14 at 1 27 01 pm" src="https://user-images.githubusercontent.com/8262765/224877040-617a277f-49f7-40d2-9259-111e7d2fe4e6.png">

**Configuration (please complete the following information):**
 - RDKit version:  `2022.09.5`
 - OS: `Mac OS Ventura 13.2.1`
 - Install: `pip in a conda env`

Thanks for your time!

**Comment by DavidACosgrove** [comment]
Thanks.  I'll take a look at it in the next few days.  The drawings in cell 20 in that blog post are also now odd in the latest version.

**Comment by greglandrum** [comment]
Duplicate with #6200
