### ISSUE TITLE
Possible regression in the atom/bond highlighting code

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#6200]
**Describe the bug**
The highlighting code seems to misbehave when computing certain highlight radii.

**To Reproduce**
I tried to reproduce this example from a [2020 blog post by Greg](http://rdkit.blogspot.com/2020/04/new-drawing-options-in-202003-release.html).

```
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole, rdMolDraw2D
from IPython.display import HTML, SVG
from collections import defaultdict

chembl2314369=Chem.MolFromSmiles('N#CC(C#N)=C1C(=O)c2cccc3cccc1c23')
rings = chembl2314369.GetRingInfo()

colors = [(0.8,0.0,0.8),(0.8,0.8,0),(0,0.8,0.8),(0,0,0.8)]

athighlights = defaultdict(list)
arads = {}
for i,rng in enumerate(rings.AtomRings()):
    for aid in rng:
        athighlights[aid].append(colors[i])
        arads[aid] = 0.3

bndhighlights = defaultdict(list)
for i,rng in enumerate(rings.BondRings()):
    for bid in rng:
        bndhighlights[bid].append(colors[i])
    
d2d = rdMolDraw2D.MolDraw2DSVG(400,400)
d2d.DrawMoleculeWithHighlights(chembl2314369,'CHEMBL2314369',dict(athighlights),dict(bndhighlights),arads,{})
d2d.FinishDrawing()
SVG(d2d.GetDrawingText())
```
and I get this:
![image](https://user-images.githubusercontent.com/5244385/225256744-3f836498-b3ec-4ceb-bced-d7ee96107d31.png)

Some of the highlighting radii are extremely bloated for no obvious reason.
This can be reproduced in both `2022.09.3` released code and in current `master`.

**Expected behavior**
The blog post shows that I should rather be getting this:
![image](https://user-images.githubusercontent.com/5244385/225256539-413d7dc7-ed85-418b-ae0b-5e116a948b43.png)

However, setting
```
d2d.drawOptions().fillHighlights = False
```
yields the expected result:
![image](https://user-images.githubusercontent.com/5244385/225274065-1355b033-7520-4455-b600-78244df7955d.png)

**Comment by DavidACosgrove** [comment]
Hi @ptosco.  I expect this is the same as #6194.  I think I know what the problem is, and it should be a simple fix.  It does suggest that the tests for the multi-highlighting code isn't very good, as this has probably been extant for 6 months at least.  I will speak severely to the person responsible!  I should have a fix in a few days.

**Comment by ptosco** [comment]
Thanks @DavidACosgrove! And don't be too harsh with the responsible, I know him and he is a good lad.
