### ISSUE TITLE
Different numbers of HB acceptors

### ISSUE THREAD

**Issue by alexandrefassio** [rdkit/rdkit#6206]
Hi there,

I've tried to compute the number of HB acceptors using three different functions. 

According to issue #3276, the functions CalcNumLipinskiHBA() and CalcNumHBA() are expected to be different, and @greglandrum has stated he prefers results obtained with CalcNumHBA().

In fact, when trying to count the number of HB acceptors for the following molecule 

         O=C(c1cccc(C(=O)N2CC[NH+](Cc3ccccc3)CC2)c1)N1CC[NH+](Cc2ccccc2)CC1

CalcNumHBA() returned me a value of 2 as expected expecting, while CalcNumLipinskiHBA() returns 6.

I understand both functions have different methods and that's why the values differ. Ok...

However, the thing that surprised me is to find out that calling a third function Lipinski.NumHAcceptors() results in the same value as CalcNumHBA(), i.e., 2. This is surprising because I expected the results of Lipinski.NumHAcceptors() are to be equal to CalcNumLipinskiHBA() as they are presumably calculating HBAs count using the same rule, i.e., Lipinski rule.

Are these results "correct"?

**Configuration (please complete the following information):**
 - RDKit version: 2020.09.3
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.7.6
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from?  conda-forge
 - If you are not using conda: how did you install the RDKit?

**Comment by greglandrum** [comment]
`Lipinski.NumHAcceptors()` calls `CalcNumHBA()`, so that's definitely expected behavior (https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/Lipinski.py#L53)

These functions, like `NumHeteroAtoms()`, `NumRotatableBonds()`, etc. are defined in the `Lipinski` module because they are Lipinski-like: simple, interpetable physicochemical properties.

**Comment by alexandrefassio** [comment]
Hi @greglandrum, thanks for your reply.

I see... But wouldn't be the case that CalcNumLipinskiHBA() also produce the same result? 

I found it counter-intuitive because both functions have Lipinski in the name, which confused me when got two different results.
