### ISSUE TITLE
Reactions from SMARTS produce invalid molecules if the product specifies a bond ring

### ISSUE THREAD

**Issue by davidoskky** [rdkit/rdkit#6222]
**Describe the bug**
If you generate a reaction from a SMARTS string and you specify that the bond between two particular atoms must be a ring bond through the @ operator, rdkit assigns  a generic bond type to that specific bond.

**To Reproduce**
I use an imaginary reaction to show the error, I enforce that one of the bonds in the aromatic rings in the product must be a ring bond; such bond in the final product is a generic bond (~).

```
from rdkit import Chem
from rdkit.Chem import rdChemReactions

reaction = rdChemReactions.ReactionFromSmarts(
    "[c:1]@[c:2].[C:6][C:5]>>[c:1]@[c:2][#6:5][#6:6]"
)
mol1 = Chem.MolFromSmiles("c1ccccc1")
mol2 = Chem.MolFromSmiles("CCC")
product = reaction.RunReactants((mol1, mol2))
print(Chem.MolToSmiles(product[0][0]))
```
product = CC(C)c1ccccc~1

**Expected behavior**
Since the bond is in a ring, it should be treated as an aromatic bond. Note that the same problem is present with cycloexane, thus it is not about the aromaticity.
Removing the @ caracter from the product SMARTS the reaction behaves correctly.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.4
 - OS: Fedora 37
 - Python version (if relevant): 3.11
 - Are you using conda: Yes
 - If you are using conda, which channel did you install the rdkit from: conda-forge

**Comment by wopozka** [comment]
Well, on RHS of the reaction you defined ring bond, but without definition what type of bond it is (aromatic, single, double) therefore rdkit very pbobably treats it as any bond and puts ~ there. In general we should not put info like rings, atom lists etc on RHS, as rdkit does not uderstands it. You usually create RHS as simple as possible, and then from products list you select one that according to you is the best. Or create LHS in the way that you get only one match.
