### ISSUE TITLE
rdMolHash.MolHash function should allow customization of the CXSmiles via Chem.CXSmilesFields

### ISSUE THREAD

**Issue by irenazra** [rdkit/rdkit#6224]
**Is your feature request related to a problem? Please describe.**
The improvement request is related to the following ticket: https://github.com/rdkit/rdkit/pull/6175

**Describe the solution you'd like**
Currently, rdMolHash.MolHash only lets you choose whether you would like the cxsmiles extension to be returned or not through the boolean parameter useCxSmiles. However, sometimes we only want a certain part of the extension. Before the changes in #6175, we were using regex expressions to extract the part of the extension we want. This approach makes code hard to read and it not very extendable. Rdkit already has its own builtin way to customize which part of the extension gets returned. Chem.MolToCxSmiles function takes in an optional flag (see Chem.CXSmilesFields) that customizes what part of the extension gets returned. Instead of using regex, after #6175, we started using these flags. However, rdMolHash.MolHash function does NOT take in a flag parameter. It only takes in a boolean variable useCXSmiles. Therefore, it either returns the full extension or does not return it. Allowing rdMolHash.MolHash function to take in a flag and return CXSmiles accordingly should be a straight forward solution.

**Describe alternatives you've considered**
To use the flags, I tried turning the CxSmiles I get from rdMolHash.MolHash function into a mol, then back into CXSmiles using the appropriate flags. Even though this is okay, it is not ideal.

**Comment by greglandrum** [comment]
This would be super useful

**Comment by irenazra** [comment]
@greglandrum do I need to be backwards compatible? Aka can I just delete the boolean variable and replace it with cxfields? Or, do I need to keep handling the old interface?

**Comment by bp-kelley** [comment]
Seems like an overload would solve the issue here.

**Comment by greglandrum** [comment]
@irenazra on the C++ side I think you can add an overload as @bp-kelley suggests.
In Python I think you unfortunately need to add an additional optional argument

**Comment by bp-kelley** [comment]
What if you type check a pyobject?

**Comment by greglandrum** [comment]
> What if you type check a pyobject?

It's not unheard of or wrong for people to pass a nonzero int instead of a bool
