### ISSUE TITLE
MQN12 (heavy atom count) seems to be always 0.

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#623]
MQN12 according to the original publication is number of heavy atoms and footnote says heavy atoms = All non-H atoms. If I run below code, I get an MQN12 of 0 instead of 4. 

    from rdkit import Chem
    m = Chem.MolFromSmiles('CCCC')
    from rdkit.Chem import rdMolDescriptors
    mqn = rdMolDescriptors.MQNs_(m)
    mqn[11] # MQN12 = hac = heavy atom count, all non-H Atoms
    0

Index 11 is used because the returned list is 0 based. hence this means MQN12. I tried it for different simple structures and it seems to always return 0 as heavy atom count

RDKit_2015_03_1 on Windows and Python 32-bit.

**Comment by greglandrum** [comment]
Confirmed. The code is currently accumulating a count of the atoms that don't match any of the other atom types that are counted, so it's not always zero:
```python
In [22]: AllChem.MQNs_(Chem.MolFromSmiles('CCCCB'))[11]
Out[22]: 1
```
But this is still wrong.

**Comment by greglandrum** [comment]
Should be fixed now. Thanks for the report!
