### ISSUE TITLE
Add a function to translate the MDL chiral flag into enhanced stereo groups

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#6241]
The "chiral flag" is a feature that was used in MDL v2000 mol files, but was superseded by Enhanced Stereo Groups, which are much more flexible, in the v3000 format.

It would be useful to have some infrastructure that allows us to "translate" the stereochemistry read from a v2000 mol block into Enhanced Stereo Groups. If my understanding of the related documentation is correct, this code should do the following:

For all atoms which are not already included in an Enhanced Stereo Group (these might have been defined at some point after reading the original v2000 input), 
- if the `RDKit::common_properties::_MolFileChiralFlag` property is set to "1", find or create the "ABS" Enhanced Stereo Group on the mol (which must be unique), and add the atoms to it.
- if the `RDKit::common_properties::_MolFileChiralFlag` property is set to "0", create a new "AND" Enhanced Stereo Group, and add all atoms to it.

**Comment by bp-kelley** [comment]
LGTM
