### ISSUE TITLE
Drawing molecules in ipython notebook with wedgeBonds=False gives bigger lines than expected

### ISSUE THREAD

**Issue by sorenwacker** [rdkit/rdkit#625]
RDKit :  2015.03.1
notebook server 4.0.4
python: 2.7.6.final.0

```
from  rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole

mol = Chem.MolFromSmiles('[H][C@]1(NC[C@@H](CC1CO[C@H]2CC[C@H](CC2)O)N)[H]')
Draw.MolToImage(mol,wedgeBonds=False)
```

should give the same figure as

```
mol = Chem.MolFromSmiles('C1(NCC(CC1COC2CCC(CC2)O)N)')
Draw.MolToImage(mol)
```

However, the bonds in the first figure are slightly bigger.

**Comment by hsiaoyi0504** [comment]
@greglandrum I think I can reproduce this issue in the latest release (RDKit 2019.09.3).
Or is it an intentional behavior?

![image](https://user-images.githubusercontent.com/10943928/76544794-976b1880-64c3-11ea-912e-364aac31ca83.png)

**Comment by greglandrum** [comment]
It looks like you're using the old renderer. which rdkit build are you using?
