### ISSUE TITLE
Background color by feature for MolsToGridImage

### ISSUE THREAD

**Issue by Boilermaker14** [rdkit/rdkit#6256]
I'd like to be able to visualize a numeric (or categorical) feature of each molecule by background color of the individual mols in MolsToGridImage. 

e.g. I plot a list of mols for which I have experimental data, and the mols which had activity against my target are shown with green background, those that did not with red. Specific colors supplied by user. 

What I envisioned: pass a list of RGB/hex (whatever is easiest) of len(mols), same as you can pass the list of legends. Leave it to users to deal with colormaps, etc., so that it's a simple addition for now.

Thanks

**Comment by kienerj** [comment]
As shameless self-promotion, my existing project while not exactly what you want, might still be an improvement:

https://github.com/kienerj/molecule-slide-generator
