### ISSUE TITLE
Generate all stereoisomers

### ISSUE THREAD

**Issue by sorenwacker** [rdkit/rdkit#626]
Hi,

I coded a bit and have a first hack of a function that generates all stereo-isomers of a given compound. It is not optimized and well-tested yet, but it seems to work. Tell me what you think about it, which functionality should be included, how could the code be improved and fit to RDKit conventions. I will add more comments later on. This code is for an IPython notebook.

Thanks to Paolo Tosco, Axel Pahl and Toby Wright for your comments at the mailing list.

I would be happy to include it sooner or later into the RDKit code. What would be the best location?

```
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem,Draw
from rdkit.Chem.Draw import IPythonConsole

mol = Chem.MolFromSmiles('FC(Cl)C=CC(C(O)N)C=CC(Cl)Br')

def spam(n):
    out=[]
    for perm in getPerms(n):
        elem = [ int(i) for i in list(perm) ]
        out.append(elem)
    return out

def getPerms(n):
    from itertools import permutations
    for i in getCandidates(n):
        for perm in set(permutations(i)):
            yield ''.join(perm)

def getCandidates(n):
    for i in range(0, n+1):
        res = "1" * i + "0" * (n - i)
        yield res

def GetStereoIsomers(mol):
    from rdkit import Chem
    from copy import copy
    out = []   

    chiralCentres = Chem.FindMolChiralCenters(mol, includeUnassigned=True)

    #return the molecule object when no chiral centres where identified
    if chiralCentres == []:
        return [mol]

    #All bit permutations with number of bits equals number of chiralCentres
    elements = spam(len(chiralCentres))

    for isoId,element in enumerate(elements):       
        for centreId,i in enumerate(element):
            atomId = chiralCentres[centreId][0]
            if i == 0:
                mol.GetAtomWithIdx(atomId).SetChiralTag(Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW)
            elif i == 1:
                mol.GetAtomWithIdx(atomId).SetChiralTag(Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
        outmol = copy(mol        )
        out.append(outmol)
        print Chem.MolToSmiles(mol,isomericSmiles=True)
    return out

Draw.MolsToGridImage(GetStereoIsomers(mol))
```

**Comment by bp-kelley** [comment]
Enumerating stereochemistry can be a bit more than just flipping unassigned chiral centers. In some cases identifying invertible nitrogens center puckers can be useful, and other times they are a nuisance.

This also looks to ignore cis/trans which is another complication.

**Comment by soerendip42** [comment]
Thanks for your hint. You are welcome to improve the code.

**Comment by nate-russell** [comment]
I just tried some it with some under-specified allenes and it gave back only what it was given. 
An Example smiles:
CC(=C/C=C/C=C(C)\C=C\C=C(/C)C=C=C1C(C)(C)C[C@H](O)C[C@@]1(C)O)/C=C/C=C(C)\C=C\[C@@]12O[C@]1(C)C[C@@H](O)CC2(C)C
