### ISSUE TITLE
Explicit valence for atom is greater than permitted (in dissociated salt)

### ISSUE THREAD

**Issue by victoria-dos** [rdkit/rdkit#6263]
**Describe the bug**
After inserting [Na+] right after [O-] which is inside valid SMILES, there is an "Explicit valence for atom # 40 O, 3, is greater than permitted".

**To Reproduce**
I came to this when was trying to read a ligand [CGO](https://www.rcsb.org/ligand/CGO)(it is a dissociated salt) using five different SMILES from PDB compound dictionary, all failed. Then I found a similar compound on [Pubchem](https://pubchem.ncbi.nlm.nih.gov/compound/11314) (it was acid), and its SMILES was read correctly. 
I manually changed the "O" into [O-], and everything was fine, but after trying to insert [Na+], it failed. 

```python
from rdkit import Chem
Chem.MolFromSmiles("C1=CC=C2C(=C1)C(=CC(=C2N)N=NC3=CC=C(C=C3)C4=CC=C(C=C4)N=NC5=C(C6=CC=CC=C6C(=C5)S(=O)(=O)O)N)S(=O)(=O)O")
Chem.MolFromSmiles("C1=CC=C2C(=C1)C(=CC(=C2N)N=NC3=CC=C(C=C3)C4=CC=C(C=C4)N=NC5=C(C6=CC=CC=C6C(=C5)S(=O)(=O)[O-])N)S(=O)(=O)[O-]")
Chem.MolFromSmiles("C1=CC=C2C(=C1)C(=CC(=C2N)N=NC3=CC=C(C=C3)C4=CC=C(C=C4)N=NC5=C(C6=CC=CC=C6C(=C5)S(=O)(=O)[O-][Na+])N)S(=O)(=O)[O-]")
# Explicit valence for atom # 40 O, 3, is greater than permitted
```

**Expected behaviour**
The Valence for O atom should be correct

**Screenshots**
![image](https://user-images.githubusercontent.com/42894967/229212058-fa63d1a9-baf2-499f-a857-e1d84523d65e.png)

**Configuration:**
 - RDKit version: 2022.9.5
 - OS: [e.g. Ubuntu 20.04] Ubuntu 20.04.5 LTS
 - Python version (if relevant): 3.8.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? automatic installation in PyCharm

**Comment by bp-kelley** [comment]
I think your salt has been incorrectly bonded here:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/9888416/229263633-02ae342b-21db-4e8d-a922-fa0b5452b101.png">

This is not a valid rdkit structure.  To "Fix" this the Sodium should be disconnected Ala:  

"C1=CC=C2C(=C1)C(=CC(=C2N)N=NC3=CC=C(C=C3)C4=CC=C(C=C4)N=NC5=C(C6=CC=CC=C6C(=C5)S(=O)(=O)[O-])N)S(=O)(=O)[O-].[Na+]"

**Comment by greglandrum** [comment]
As @bp-kelley pointed out: this is not a bug. You need to add the Na+ as a separate fragment.
