### ISSUE TITLE
compile-time error with GCC 12.2.1 on Fedora 36

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#6274]
**Describe the bug**
Building from source code on Fedora 36 with GCC 12.2.1 fails with the following error:

/.../rdkit/Code/GraphMol/StructChecker/Utilites.cpp: In function ‘bool RDKit::StructureCheck::lessTuple(const NbrData&, const NbrData&)’:
/.../rdkit/Code/GraphMol/StructChecker/Utilites.cpp:65:12: error: ‘const RDKit::StructureCheck::NbrData’ {aka ‘const class std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int>’} has no member named ‘get’

I'm creating a PR shortly with a possible fix, using std::get.

**Configuration (please complete the following information):**
 - RDKit version: current master branch
 - OS: Fedora 36

**Comment by greglandrum** [comment]
This hasn't been picked up to this point because I never build the StructChecker code any more.
It ought to be deprecated and removed.
