### ISSUE TITLE
Reduce space overhead of enabling the inclusion of properties when serializing molecules

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#6312]
**Describe the bug**
It seems there may be a significant overhead affecting the size of the Mol binary data if the serialization of additional properties is enabled also when no properties are actually present.

**To Reproduce**
I experienced this issue using the C++ API, but this I think could be a more compact and equivalent reproducible.

```
In [10]: mol = Chem.MolFromSmiles("CCCCC")

In [11]: bin1 = mol.ToBinary()

In [12]: len(bin1)
Out[12]: 98

In [13]: bin2 = mol.ToBinary(
    Chem.PropertyPickleOptions.AtomProps |
    Chem.PropertyPickleOptions.BondProps |
    Chem.PropertyPickleOptions.PrivateProps
)

In [14]: len(bin2)
Out[14]: 146

In [15]: bin3 = mol.ToBinary(Chem.PropertyPickleOptions.AllProps)

In [16]: len(bin3)
Out[16]: 544
```

**Expected behavior**
Ideally, when properties are not assigned to the molecule, passing additional flags enabling their serialization should have no effect on the size of the serialized binary data. This would allow the client code to serialize an etherogeneous collection of molecule and just specify which properties are of interest, without checking if these flags are to be enabled on a per-molecule basis.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.5

**Additional context**
I don't know if it may be worth considering in relation to #6310 and #6311

**Comment by greglandrum** [comment]
Just taking some notes here.
It looks like this is primarily due to the computed properties vectors:
```
In [51]: len(m.ToBinary())
Out[51]: 300

In [52]: len(m.ToBinary(Chem.PropertyPickleOptions.AllProps))
Out[52]: 1778

In [53]: len(m.ToBinary(Chem.PropertyPickleOptions.AtomProps))
Out[53]: 386

In [54]: len(m.ToBinary(Chem.PropertyPickleOptions.AtomProps|Chem.PropertyPickl 
    ...: eOptions.PrivateProps|Chem.PropertyPickleOptions.ComputedProps))       
Out[54]: 1571

In [55]: len(m.ToBinary(Chem.PropertyPickleOptions.BondProps|Chem.PropertyPickl 
    ...: eOptions.PrivateProps|Chem.PropertyPickleOptions.ComputedProps))       
Out[55]: 394

In [59]: len(m.ToBinary(Chem.PropertyPickleOptions.AtomProps|Chem.PropertyPickl 
    ...: eOptions.PrivateProps))
Out[59]: 431

In [60]: len(m.ToBinary(Chem.PropertyPickleOptions.AtomProps|Chem.PropertyPickl 
    ...: eOptions.ComputedProps))
Out[60]: 386
```
It's not like there are a lot of properties present:
```
In [56]: allpropsSeen = {}

In [57]: for atom in m.GetAtoms():
    ...:     allpropsSeen.update(atom.GetPropsAsDict(includePrivate=True,includ 
    ...: eComputed=True))
    ...:

In [58]: allpropsSeen
Out[58]:
{'__computedProps': <rdkit.rdBase._vectclass std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > at 0x2835d0b76c0>,
 '_CIPRank': 8,
 '_ChiralityPossible': 1,
 '_CIPCode': 'S'}
```

**Comment by greglandrum** [comment]
I think that this doesn't have an impact on #6311 since that just includes private properties, not computed ones, so it shouldn't have the rapid increase in size.

**Comment by greglandrum** [comment]
> I think that this doesn't have an impact on #6311 since that just includes private properties, not computed ones, so it shouldn't have the rapid increase in size, but I will confirm that before merging #6311.

Ok, that was "overly optimistic".
Here's the table size for 50K ChEMBL molecules using master:
```
chembl_31=# \dt+ mols50k 
                                     List of relations
  Schema   |  Name   | Type  |  Owner   | Persistence | Access method | Size  | Description 
-----------+---------+-------+----------+-------------+---------------+-------+-------------
 pg_temp_3 | mols50k | table | glandrum | temporary   | heap          | 23 MB | 
(1 row)
```
And the same table using the branch behind #6311:
```
chembl_31=# \dt+ mols50k 
                                     List of relations
  Schema   |  Name   | Type  |  Owner   | Persistence | Access method | Size  | Description 
-----------+---------+-------+----------+-------------+---------------+-------+-------------
 pg_temp_3 | mols50k | table | glandrum | temporary   | heap          | 64 MB | 
(1 row)
```
I need to look into this a bit more carefully

**Comment by greglandrum** [comment]
When serializing standard properties we use a tremendous amount of extra space by repeating the same property names over and over again in the output file. This leads to super-compressible data:
```
In [56]: len(b''.join([gzip.compress(x.ToBinary(),compresslevel=5) for x in ms]))
Out[56]: 863243

In [57]: len(b''.join([gzip.compress(x.ToBinary(Chem.PropertyPickleOptions.AtomProps|Chem.PropertyPickleOptions.BondP
    ...: rops|Chem.PropertyPickleOptions.PrivateProps|Chem.PropertyPickleOptions.ComputedProps),compresslevel=5) for
    ...: x in ms]))
Out[57]: 1247743
```
but I don't think compressing the pickles is a good generic solution (easy enough to implement for people who want to do that).

Other options that come to mind:
1. explicitly handle common atom/bond properties when pickling/depickling instead of using the generic key-value storage
2. write atom/bond properties as a table after the atoms/bonds

I think it makes sense to pursue the first route. It's a relatively small amount of code and should make a big size difference without adversely affecting the read/write performance.
