### ISSUE TITLE
MolToSmiles(canonical=False) creates the wrong _smilesBondOutputOrder property

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#6315]
**Configuration:**

- RDKit Version: 2022.09.5
- Operating system: macOS 12.4
- Python version (if relevant): Python 3.11
- Are you using conda? No
- If you are not using conda: how did you install the RDKit? pip install rdkit

**Description:**

I get an unexpected RuntimeError when using CXSmiles on a molecule with a single atom, and with canonical=False. It appears to be due to a long-time issue that MolToSmiles(canonical=False) creates the wrong "_smilesBondOutputOrder" property.

**Reproducible:**

I'm updating my software to 2022.09.5. One of my regression tests for CXSmiles output generation of methane failed with a RuntimeError:
```
% python
Python 3.11.1 (main, Dec 23 2022, 09:40:27) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 >>> import rdkit
>>> rdkit.__version__
'2022.09.5'
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles("C")
>>> Chem.MolToSmiles(m, canonical=False)
'C'
>>> Chem.MolToCXSmiles(m, canonical=True)
'C'
>>> Chem.MolToCXSmiles(m, canonical=False)
[12:12:10]

****
Pre-condition Violation
no bonds
Violation occurred on line 337 in file /Users/runner/work/rdkit-pypi/rdkit-pypi/build/temp.macosx-10.9-x86_64-cpython-311/rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: getNumBonds() > 0
****

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Pre-condition Violation
	no bonds
	Violation occurred on line 337 in file Code/GraphMol/ROMol.cpp
	Failed Expression: getNumBonds() > 0
	RDKIT: 2022.09.5
	BOOST: 1_78
```

An older version of RDKit did not have this issue:
```
% python
Python 3.10.2 (main, Feb 15 2022, 14:27:35) [Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
>>> rdkit.__version__
'2021.09.4'
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles("C")
>>> Chem.MolToCXSmiles(m, canonical=False)
'C'
```

**Investigation:**

MolToCXSmiles has a different code path for isomeric vs. non-isomeric SMILES, but I found `Chem.MolToCXSmiles(m, isomericSmiles=False, canonical=False)` and `Chem.MolToCXSmiles(m, isomericSmiles=True, canonical=False)` both cause the RuntimeError, suggesting the issue is in SmilesWrite::getCXExtensions().

By enabling the flag bits one-by-one I narrowed the exception down to the cxflag value 512:
```
>>> from rdkit import Chem
>>> w = Chem.SmilesWriteParams()
>>> w.canonical = False
>>> m = Chem.MolFromSmiles("C")
[12:33:14]

****
Pre-condition Violation
no bonds
  ...
```

Oddly, 512 is not associated with a specific CXSmiles flag value at the Python API, being only set by CX_ALL:
```
>>> from rdkit.Chem.rdmolfiles import CXSmilesFields
>>> for k, v in CXSmilesFields.names.items():
...   if v >= 512: print(k)
...
CX_ALL
```
However, inspection of GraphMol/SmilesParse/SmilesWrite.h shows it exists at the C++ level:
```
  CX_BOND_CFG = 1 << 9,
```

**Suspicious bondOrder:**

Nothing seemed wrong about the CX_BOND_CFG path in `getCXExtensions()`. It shouldn't do anything if bondOrder is empty. ... So, is it empty? The vector comes from:
```
  const std::vector<unsigned int> &bondOrder =
      mol.getProp<std::vector<unsigned int>>(
          common_properties::_smilesBondOutputOrder);
```

but `MolFromSmiles(canonical=False)` returns a value of `[0,]` instead of the expected `[]`!

```
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles("C")
>>> Chem.MolToSmiles(m)
'C'
>>> m.GetProp("_smilesBondOutputOrder")
'[]'
>>> Chem.MolToSmiles(m, canonical=False)
'C'
>>> m.GetProp("_smilesBondOutputOrder")
'[0,]'
```

It also returns `[0,]` in 2021.09.4, and it wasn't implemented in 2020.09.5.

**Likely root cause:**

It appears MolToSmiles does not set the bond ordering correctly when canonical is False. Here's what it does:

```
  } else {  // Not canonical
    for (auto &i : allAtomOrdering) {
      flattenedAtomOrdering.insert(flattenedAtomOrdering.end(), i.begin(),
                                   i.end());
      flattenedBondOrdering.insert(flattenedBondOrdering.end(), i.begin(),
                                   i.end());
    }
```

This would appear to give flattenedBondOrdering the same value as flattenedAtomOrdering.

For example, the atom and bond output orders are identical in cubane:

```
>>> m = Chem.MolFromSmiles("C12C3C4C51.C12C3C4C51")
>>> Chem.MolToSmiles(m, canonical=False)
'C12C3C4C1C1C2C3C41'
>>> m.GetProp("_smilesAtomOutputOrder")
'[0,1,2,3,7,4,5,6,]'
>>> m.GetProp("_smilesBondOutputOrder")
'[0,1,2,3,7,4,5,6,]'
```

while if `canonical=True` the output looks reasonable:

```
>>> Chem.MolToSmiles(m, canonical=True)
'C12C3C4C1C1C2C3C41'
>>> m.GetProp("_smilesAtomOutputOrder")
'[1,0,3,2,6,5,4,7,]'
>>> m.GetProp("_smilesBondOutputOrder")
'[0,6,2,1,10,4,9,3,8,7,11,5,]'
```

**Comment by greglandrum** [comment]
Confirmed. Thanks for the report @adalke
