### ISSUE TITLE
Atom-Atom mapping error in RunReactants executing rearrangement reaction

### ISSUE THREAD

**Issue by gentle1999** [rdkit/rdkit#6322]
Dear rdkit developers
I have designed a typical 1,2 migration rearrangement reaction template and set the mapping in the SMARTS string.
```python
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import Draw
IPythonConsole.drawOptions.addAtomIndices = True
IPythonConsole.molSize = 300, 300
m0 = Chem.MolFromSmiles('[CH2+]C(C)Cc1ccccc1')
rxn = AllChem.ReactionFromSmarts(
    '[CX3H2+1:1]-[CX4H1+0:2]-[C+0:3]>>[CX4H2+0:1](-[C+0:3])-[CX3H1+1:2]')
m1 = rxn.RunReactants((m0,))[0][0]
m2 = rxn.RunReactants((m0,))[1][0]
```
where m0 shows:
![m0](https://i.328888.xyz/2023/04/27/i95Wvk.png)

I executed the `RunReactants` method to get the two correct product topologies. But their atom-atom mapping relationships are different from what I had envisioned. The diagram below shows in black the atom numbers of the products generated by rdkit, and in red the atom numbers I expected.

m1:
![m1](https://i.328888.xyz/2023/04/27/i9564o.png)
m2:
![m2](https://i.328888.xyz/2023/04/27/i95dud.png)

I have searched the official documentation for rdkit and found no discussion of this issue, and I'm not sure if this is a bug or a feature. If there is any way to implement Atom-Atom Mapping before and after the execution of `RunReactants`, I hope you can let me know.
Many thanks!

**Configuration (please complete the following information):**
 - RDKit version: 2022.9.3
 - OS: Ubuntu 20.04.2 LTS on Windows 10 x86_64
 - Python version (if relevant): 3.9.16
 - Are you using conda? no
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: PyPi

**Comment by gentle1999** [comment]
I have found a solution to this problem and learned about the possible algorithm of rdkit in dealing with this problem.

When I use
```python
rxn = AllChem.ReactionFromSmarts(
    '[CX3H2+1:1]-[CX4H1+0:2]-[C+0:3]>>[CX4H2+0:1](-[CX3H1+1:2])-[C+0:3]')
```
instead of
```python
rxn = AllChem.ReactionFromSmarts(
    '[CX3H2+1:1]-[CX4H1+0:2]-[C+0:3]>>[CX4H2+0:1](-[C+0:3])-[CX3H1+1:2]')
```
This problem is fixed. I presume that the atomic number mapping relationship before and after is determined by the order in which the templates are written. This can be achieved by controlling the order of writing in a simple 1,2 migration template problem like mine. However, if a rearrangement of several atoms at intervals such as a Claisen rearrangement occurs, controlling the writing order will make SMILES no longer legal. So this is still a problem worth thinking about. Hopefully the rdkit team will come up with a better answer!

**Comment by wopozka** [comment]
You have two matches in substrate, therefore you have two different reaction outputs. Prepare reaction smarts that would give one match only, and then it should be ok.

**Comment by gentle1999** [comment]
#4327  This issue offers a viable solution

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
