### ISSUE TITLE
ChiralTag not updated after RenumberAtoms

### ISSUE THREAD

**Issue by baoilleach** [rdkit/rdkit#6329]
- RDKit version: 2022.09.1
 - OS: Win 10
 - Python version (if relevant): 3.9
 - Are you using conda? yes - conda-forge

If I use ``RenumberAtoms()`` to swap ``F`` and ``I`` in ``Br[C@@](Cl)(F)I``, the generated SMILES is as expected: ``Br[C@](Cl)(I)F``. However, ``GetChiralTag()`` returns ``CHI_TETRAHEDRAL_CW`` in both cases, while I expected it to return ``CHI_TETRAHEDRAL_CCW`` in the second case. If I read in ``Br[C@](Cl)(I)F``, then I see the expected ``CHI_TETRAHEDRAL_CCW``.

Apologies in advance if this is user error, but I've looked at the SMILES writer source, and it seems to be using the ChiralTag to work out whether to write @/@@ - is this a disconnect between the Python and the C++ somehow?

Reproducible:
```python
from rdkit import Chem

smi = "Br[C@@](Cl)(F)I"
mol = Chem.MolFromSmiles(smi)

atom = mol.GetAtomWithIdx(1) # the C
assert atom.GetChiralTag() == Chem.ChiralType.CHI_TETRAHEDRAL_CW
# True: from Br, [Cl, F, I] are in CW order

# Reorder the F and I
# - same molecule, so same absolute stereo
# - but will invert the SMILES symbol
molB = Chem.RenumberAtoms(mol, [0,1,2,4,3])
smiB = Chem.MolToSmiles(molB, canonical=False)
assert smiB == "Br[C@](Cl)(I)F"

print(molB.GetAtomWithIdx(1).GetChiralTag())
# Prints CHI_TETRAHEDRAL_CW !!!
# - but from Br, [Cl, I, F] are in CCW order
# - also if you read in smiB, and ask the same question you get CCW as expected
```

**Comment by baoilleach** [comment]
Ah! Is it that ``CHI_TETRAHEDRAL_CW`` is a description of the relative order of the atoms, rather than the relative order of the bonds? In which case, it all makes sense as the order of the bonds is unchanged by ``RenumberAtoms``. However, when written out and read back in, the bond order *is* affected hence the change in parity.

**Comment by bp-kelley** [comment]
Renumbering atoms pretty much only changes their indices, and, as you say, it's the order of the bonds around the atom that determine chirality, changing the atom indices doesn't affect the ordering.

This can be seen using mol.Debug()

```
from rdkit import Chem
import random

m = Chem.MolFromSmiles("[C@](N)(F)(I)Br")
smi = Chem.MolToSmiles(m)
m.Debug()
idxs = list(range(5))
random.shuffle(idxs)
m2 = Chem.RenumberAtoms(m, idxs)
m2.Debug()
```

Example output where the Carbon (atom index 0) is now atom index 1

```
>>> Atoms:
	0 6 C chg: 0  deg: 4 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 2
	1 7 N chg: 0  deg: 1 exp: 1 imp: 2 hyb: 4 arom?: 0 chi: 0
	2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	3 53 I chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	4 35 Br chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
Bonds:
	0 0->1 order: 1 conj?: 0 aromatic?: 0
	1 0->2 order: 1 conj?: 0 aromatic?: 0
	2 0->3 order: 1 conj?: 0 aromatic?: 0
	3 0->4 order: 1 conj?: 0 aromatic?: 0
Atoms:
	0 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	1 6 C chg: 0  deg: 4 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 2
	2 53 I chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
	3 7 N chg: 0  deg: 1 exp: 1 imp: 2 hyb: 4 arom?: 0 chi: 0
	4 35 Br chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
Bonds:
	0 1->3 order: 1 conj?: 0 aromatic?: 0
	1 1->0 order: 1 conj?: 0 aromatic?: 0
	2 1->2 order: 1 conj?: 0 aromatic?: 0
	3 1->4 order: 1 conj?: 0 aromatic?: 0
```

**Comment by baoilleach** [comment]
Thanks. Perhaps one to clarify in the documentation for ``Atom::ChiralType``. I saw that Andrew Dalke was having similar issues back in 2016 working it out.
