### ISSUE TITLE
MolsToGridImage may produce atoms overlap for the same molecule with different SMILES

### ISSUE THREAD

**Issue by radchenkods** [rdkit/rdkit#6334]
**Describe the bug**
For two different SMILES of the same molecule two different pictures are generated, one of which have overlapping atom coordinates.

**To Reproduce**
```
from rdkit import Chem
smiles_list = ["O=C(C(N(C(c1ccccc1)=O)Cc2ccccc2)c3ncccc3)Nc4ccccc4", "O=C(Nc1ccccc1)C(c1ccccn1)N(Cc1ccccc1)C(=O)c1ccccc1"]
Chem.Draw.MolsToGridImage([Chem.MolFromSmiles(smi) for smi in smiles_list], molsPerRow=5)
```

**Expected behavior**
I believe the pictures should be the same and they should not contain overlapping atom coordinates.

**Screenshots**
![image](https://user-images.githubusercontent.com/25413723/235879594-6ea32e64-7f5c-449a-a455-baff7d4ce580.png)

**Configuration:**
 - RDKit version: 2023.03.1
 - OS: Windows 10
 - Python version (if relevant): 3.10.10
 - Are you using conda? - Yes, Anaconda 2.4.0
 - If you are using conda, which channel did you install the rdkit from? - conda-forge

**Comment by wopozka** [comment]
IMHO molecules should not be the same, as mols are created by stepwise reading of SMILES, so the bond and atom order might be different. Having said that, I think there is a bug in image generation, as overlaping should be detected and molecule should be depicted in a better way.

**Comment by lounsbrough** [comment]
We are also seeing this issue, although I cannot post examples since the molecules are not publicly known.
