### ISSUE TITLE
Query Features: Different input format leads to a different molecule

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#6349]
**Describe the bug**
When I load a simple query molecule with a single atom being a "atom list", the generated Mol behaves differently with a different import fomat, eg  different behavior when loading from Smarts vs molfile. even when round-tripping.

When loading from Smarts then writing Smiles, the query atom always is a dummy atom, "*".
When loading from molfile then writing Smiles, the query atom is always the first atom in the list. with a list of [Cl,F,Br] it will be "Cl" while for a list of [F,Cl,Br] it will be "F". 

**To Reproduce**

```python
m = Chem.MolFromSmarts("C-C(-[Cl,F,Br])-C")
Chem.MolToSmiles(m)
# *C(C)C

mb = Chem.MolToMolBlock(m, forceV3000=True)
m2 = Chem.MolFromMolBlock(mb)
Chem.MolToSmiles(m2)
# CC(C)Cl
```

![image](https://user-images.githubusercontent.com/1567309/236787457-06849e1b-e280-4386-a1d3-c4ce898a1ff3.png)

**Expected behavior**
Both cases should behave the same, preferably with the "*" as the "molblock behavior" loses completely the information that it is a query.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.05
 - OS: Windows 10
 - Python version (if relevant): 3.10
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 
EDIT:
it seems that the issues arises when setting the atomic number. In case of Smarts it is 0, in case of molfile it is the atomic number of the first element in the "query list". simply using SetAtomicNum(0) on the query atom when read from molfile "fixes" the issue.
Therefore the issue probably arises in the Molfileparser when Atomic number is set.

**Comment by greglandrum** [comment]
This feels like it's a bug in the mol file parser which should be relatively easy to fix. But there can always be surprises, so let's see.

**Comment by MarioAndWario** [comment]
Anyone working on this issue? If not, I can take a stab at it as a beginner.
