### ISSUE TITLE
AromaticRingsCount

### ISSUE THREAD

**Issue by Flora-Feng0532** [rdkit/rdkit#6351]
**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.
`from rdkit.Chem import AllChem`
`from rdkit import Chem`
`m = Chem.MolFromSmiles("NC(CNC(C1=CC=CC2=C1NN(C2=O)C3=CC=C(C=C3)C)=O)=O")`
`AllChem.CalcNumAromaticRings(a)`
**Expected behavior**
expected number of aromatic rings = 2 but get 3.
The second ring(suggested in yellow circle) favors for non-aromatic rings. Is there any methods to recognize it tobe a non-aromatic rings?
**Screenshots**
![m](https://user-images.githubusercontent.com/57335721/237015415-09db83ad-c38f-42e5-a50c-ec5b07119232.png)

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.3

**Comment by jasondbiggs** [comment]
I believe that those atoms are considered aromatic by the RDKit's aromaticity model.  I wrote a [step-by-step](https://www.wolframalpha.com/input?i=SMILES%3ANC%28CNC%28C1%3DCC%3DCC2%3DC1NN%28C2%3DO%29C3%3DCC%3DC%28C%3DC3%29C%29%3DO%29%3DO+aromatic+atoms) for this in alpha, the relevant step is below:

<img width="685" alt="image" src="https://github.com/rdkit/rdkit/assets/16337306/f1e1458f-735f-4871-8a3d-41992e4e0bc5">

**Comment by Flora-Feng0532** [comment]
> I believe that those atoms are considered aromatic by the RDKit's aromaticity model. I wrote a [step-by-step](https://www.wolframalpha.com/input?i=SMILES%3ANC%28CNC%28C1%3DCC%3DCC2%3DC1NN%28C2%3DO%29C3%3DCC%3DC%28C%3DC3%29C%29%3DO%29%3DO+aromatic+atoms) for this in alpha, the relevant step is below:
> 
> <img alt="image" width="685" src="https://user-images.githubusercontent.com/16337306/237512679-f1e1458f-735f-4871-8a3d-41992e4e0bc5.png">

Thanks a lot for your reply and it helps a lot. I have trouble accessing the link your provided earlier, and may lose some information. 
In this case, the yellow ring may not be planar at room temperature, thus it may not satisfy the planarity rule for aromaticity. Is there any functions that forces RDKit to recognize it as a non-aromatic ring?

**Comment by jasondbiggs** [comment]
With those three SP2 carbons that ring is going to be planar, right?  

From [reading the docs](https://www.rdkit.org/docs/RDKit_Book.html) I see that rdkit supports more aromaticity models, you may have luck calling the `setAromaticity` function and using the `AROMATICITY_MDL` model.

**Comment by greglandrum** [comment]
The RDKit documentation, which @jasondbiggs has linked to, explain that the aromaticity model is not intended to strictly model the physical situation. This is expected behavior.
