### ISSUE TITLE
When loading from Smarts, all atoms and bonds are queries

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#6366]
**Describe the bug**
This issue is heavily related to Issue #6349. 

When loading a moecule from Smarts, all atoms and bonds are queries, eg. return `HasQuery() == True` even if said atom or bond are clearly not queries.

**To Reproduce**
````python
m = Chem.MolFromSmarts("C-C-,=C(-[C&R1])-C")
for atom in m.GetAtoms():
    if atom.HasQuery():
        print(atom.GetSmarts())
# all atoms will be in the output

for bond in m.GetBonds():
    if bond.HasQuery():
        print(bond.GetSmarts())
# all bonds will be in the output
````

**Expected behavior**
Only atoms and bonds that are queries should return True for `HasQuery()`

**Screenshots**

![image](https://github.com/rdkit/rdkit/assets/1567309/fab9e3d7-319c-4c1f-9102-d3afd6e19ee6)

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.05
 - OS: Windows 10
 - Python version (if relevant): 3.10
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**

This is related to #6349 and with the goal to be able to compare molecules that are the same and in the case of #6349 the same query.

**Comment by wopozka** [comment]
Well, SMARTS is by definition query, so by default all elements of mol should be queries. Even if you think the bond is strictly defined by adding explicit definition (eg -, =, #) it is actually not, as that mean single, double, tripple bond in either ring or linear structure. To get this it must be a query.

**Comment by bp-kelley** [comment]
Following up, SMARTS has to be a query language because unlike SMILES it is more explicit than implicit, for example in smiles the bond in  CC is implicitly single, in SMARTS is can match a single bond OR an aromatic bond.

(also in SMILES, each atom has implicitly 3 hydrogens, in smarts you could technically match to any amount).

This is seen with the quite useful DescribeQuery() function

```
pat = Chem.MolFromSmarts("CC-C")
for bond in pat.GetBonds():
    print(bond.GetIdx(), bond.DescribeQuery()
```

```
0 SingleOrAromaticBond 1 = val
1 BondOrder 1 = val
```

**Comment by greglandrum** [comment]
Others have already explained that this is the expected behavior
