### ISSUE TITLE
non-physical radical counts being preserved

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#6370]
**Describe the bug**
Sanitization is leaving radicals on molecules where they don't make sense.

**To Reproduce**
```
In [8]: Chem.MolFromSmiles('[NH4+] |^1:0|').Debug()
Atoms:
	0 7 N chg: 1  deg: 0 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 1
Bonds:

In [9]: Chem.MolFromSmiles('[CH4] |^1:0|').Debug()
Atoms:
	0 6 C chg: 0  deg: 0 exp: 4 imp: 0 hyb: 4 arom?: 0 chi: 0 rad: 1
Bonds:

```
Neither of those should have a radical on it.

**Configuration (please complete the following information):**
 - RDKit version: all
 - OS: all

**Comment by MarioAndWario** [comment]
I'd like to take a crack at this issue if no one else is currently working on it.

**Comment by greglandrum** [comment]
@MarioAndWario I'm very sorry for how long it took for me to review this.
