### ISSUE TITLE
RMSD filtered conformers should also be tracked as failures

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#6380]
There should be an entry in `EmbedFailureCauses` and the failures should be tracked.

**Comment by Ajay-26** [comment]
Hi I would like to have a crack at this issue. This is going to be my first open source contribution

**Comment by greglandrum** [comment]
Hi @Ajay-26, thanks for volunteering to work on this. Let me know if you have questions once you get started.

**Comment by Ajay-26** [comment]
Thank you @greglandrum. I am reading through the contribution guidelines at the moment and also working through trying to reproduce the issue you mentioned. Could you provide a code example where this issue is seen ? Thank you again for guiding me through this :)
