### ISSUE TITLE
Why different versions of rdkit give different results for MolFromSmiles.

### ISSUE THREAD

**Issue by yangzhao1230** [rdkit/rdkit#6382]
I have the following code:
```
import rdkit
from rdkit import Chem

print(rdkit.version)

smiles = '[NH4+].[NH4+].[Cl-][Pt++]([Cl-])[Cl-]'
mol = Chem.MolFromSmiles(smiles)

```
I test it with two different versions of rdkit and get different results.
1：2020.09.1
<rdkit.Chem.rdchem.Mol object at 0x148fc81f8d50>

2：2022.09.1
[18:19:20] Explicit valence for atom # 2 Cl, 2, is greater than permitted
None

**Comment by MateuszJakiel** [comment]
This is due to an update that occurred in between the two versions. You can read about the 
error itself here: https://www.rdkit.org/docs/Cookbook.html#explicit-valence-error-partial-sanitization.

Also, after taking a look at your SMILES I think it might simply not be valid.

**Comment by greglandrum** [comment]
As @MateuszJakiel said: this was a change (bug fix) between RDKit versions.
