### ISSUE TITLE
No module named rdkit.Chem.Draw.rdMolDraw2DQt

### ISSUE THREAD

**Issue by lpravda** [rdkit/rdkit#6394]
Hello everyone,

I tried using function `Draw.MolToQPixmap(mol)`, however with the latest rdkit installed through pip it crashes with the following error:
```
In [3]: from rdkit import Chem 
In [4]: mol = Chem.MolFromSmiles("CCC")

In [5]: from rdkit.Chem import Draw
  
In [6]: Draw.MolToQPixmap(mol)
----> 1 Draw.MolToQPixmap(mol)

File ~/mambaforge/envs/pymol/lib/python3.8/site-packages/rdkit/Chem/Draw/__init__.py:686, in MolToQPixmap(mol, size, kekulize, wedgeBonds, fitImage, options, **kwargs)
    684 if not mol:
    685   raise ValueError('Null molecule provided')
--> 686 from rdkit.Chem.Draw.qtCanvas import Canvas
    687 canvas = Canvas(size)
    688 if options is None:

File ~/mambaforge/envs/pymol/lib/python3.8/site-packages/rdkit/Chem/Draw/qtCanvas.py:12
      1 #
      2 #  Copyright (C) 2014 Seiji Matsuoka
      3 #
   (...)
      8 #  of the RDKit source tree.
      9 #
     11 from rdkit.Chem.Draw.canvasbase import CanvasBase
---> 12 from rdkit.Chem.Draw.rdMolDraw2DQt import rdkitQtVersion
     14 if rdkitQtVersion.startswith('6'):
     15   try:

ModuleNotFoundError: No module named 'rdkit.Chem.Draw.rdMolDraw2DQt'
```

I wonder if this is not exposed to python, or if I need to install rdkit in a different way. 

Configuration
 - RDKit version:  2023.03.01
 - OS: [e.g. Ubuntu 20.04]: macOS 13.4
 - Python version (if relevant):  3.8.16
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? pip

Thank you!

**Comment by greglandrum** [comment]
@lpravda : the RDKit's Qt support is not enabled by default and neither the pip builds nor the conda packages have it enabled.

FWIW: `MolToQPixmap()` is using the very old drawing code. I would really recommend using the newer code. I'm not a Qt user, but if you are trying to get a Qt Pixmap, I guess it's probably easiest to use `MolToimage()` to get a PNG and then work with that?

**Comment by lpravda** [comment]
yes, this is what I ended up with for the time being. I just thought I could save that I/O step, if I could get pixmap directly. Thanks, @greglandrum.
