### ISSUE TITLE
Molfile Unsaturation Query Not Parsed Correctly

### ISSUE THREAD

**Issue by timothyngo** [rdkit/rdkit#6395]
I'm having trouble parsing the following molfile, which contains an unsaturation query.

unsaturated.sdf
```

MOESketch           2D                              

  5  5  0  0  1  0            999 V2000
   13.5413    2.8394    0.0000 N   0  0  0  0  0  0  0  0  0  3  0  0
   14.0120    1.4152    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   15.5120    1.4227    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   15.9683    2.8516    0.0000 N   0  0  0  0  0  0  0  0  0  2  0  0
   14.7504    3.7272    0.0000 C   0  0  0  0  0  0  0  0  0  1  0  0
  1  2  8  0  0  0  4
  2  3  8  0  0  0  0
  3  4  8  0  0  0  4
  4  5  8  0  0  0  9
  5  1  1  0  0  0  0
M  SUB  4   1   2   2   2   3   2   4   2
M  UNS  4   2   1   3   1   4   1   5   1
M  END
```

The following python script, which just reads this sdf file gives me an error.
```
from rdkit.Chem.rdmolfiles import MolFromMolFile

mol = MolFromMolFile("unsaturated.sdf")
```

`[18:45:17] Value 3 is not supported as an unsaturation query (only 0 and 1 are allowed). line: 16`

I think the issue is that in the `ParseUnsaturationLine` function in https://github.com/rdkit/rdkit/blob/3b3f6138302dba6e66d9c33c7dbc80fa5eb27b3a/Code/GraphMol/FileParsers/MolFileParser.cpp#L566-L616 there is a missing `spos += 4` at the end of the try block. The code should be parsing the 8 numbers at the end of the unsaturation line in pairs (2 1), (3 1), (4 1), (5 1), but the code is instead parsing the pair (2 1), and then parsing (1 3) [this is the 1 from the (2 1) pair] because it does not move far enough to reach the pair (3 1).

Happy to write a PR for this if this is a bug and the fix I mentioned above is correct. Let me know if I have a misunderstanding of how this code is supposed to work.

**Comment by greglandrum** [comment]
@timothyngo I agree with your description of the problem and the proposed fix. A PR would be most welcome!

To be consistent with the other related functions, it looks like the new line would go after the `expandQuery` call on line 598.

**Comment by timothyngo** [comment]
Should there also be a `spos += 4` before the continue on line 592? Otherwise, similar issues would occur with an unsaturation line like
`M  UNS  4   2   0   3   0   4   0   5   0`
(although admittedly, such a line would not do anything).

**Comment by greglandrum** [comment]
you're right. It would be better to catch that case. having it after the try/catch is a better idea

The other functions also probably ought to be updated

**Comment by timothyngo** [comment]
Okay, sounds like a plan. I can write a pr soon.

**Comment by greglandrum** [comment]
> Okay, sounds like a plan. I can write a pr soon.

Awesome. Thanks!
