### ISSUE TITLE
Support dative bonds

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#640]
Here's a mailing list thread: http://www.mail-archive.com/rdkit-discuss%40lists.sourceforge.net/msg05094.html

Input/output can currently only be done using the v3K CTAB format, so some attention will need to be paid to ensure that other formats do the right thing (probably not including any bonds at all).

**Comment by d-b-w** [comment]
RDKit supports dative bonds, including as an extension to SMILES.
