### ISSUE TITLE
Wavefunction for a monoatomic molecule

### ISSUE THREAD

**Issue by teltim** [rdkit/rdkit#6417]
https://forum.psicode.org/t/wavefunction-for-a-monoatomic-molecule/2813/6

Referring to the above question, I also estimate wavefuntion for monoatomic moleclue such as Ne, Xe, Ar ... 

But, I met the same error?
Are there any solution on this issue?

**Comment by jasondbiggs** [comment]
- When reporting an issue, please include a self-contained example of *RDKit* code that demonstrates the issue.
- "monoatomic moleclue" - so an atom?
- the RDKit message being printed from your Psi4 code clearly states that "Ar" is not a valid SMILES string, use "[Ar]"

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.

**Comment by teltim** [comment]
I understood, thank you for the comment
