### ISSUE TITLE
Wrong CIP label on sulfinamide

### ISSUE THREAD

**Issue by spparel** [rdkit/rdkit#6418]
Molecule (R)-2-methylpropane-2-sulfinamide (smiles: `CC(C)(C)[S@](N)=O`) is displayed with the correct CIP label R in MarvinSketch and Biovia Draw, but with RDKit, it is shown with the CIP label S. This happens in RDKit versions 2022.09.1 and 2023.03.1.

The following piece of code yields the attached picture:

`m = Chem.MolFromSmiles('CC(C)(C)[S@](N)=O')
m`

**Expected behavior:**
If we consider the sulfur lone pair as the lowest priority substituent, then the order O->N->C points to a clockwise arrangement, hence R.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.1 and 2023.03.1
 - OS: Windows 10
 - Python version (if relevant): 3.9.12 and 3.10.0
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**

![sulfinamide](https://github.com/rdkit/rdkit/assets/135133375/6fc47d1f-9b50-4e3b-8fa6-eb87556c1e8d)

**Comment by greglandrum** [comment]
I'm going to close this one because the new implementation is correct and we don't plan to fix the old one.
Hopefully at some point in the future we will be able to disable the default usage of the old implementation.
