### ISSUE TITLE
InChI calculation for Sulfur with valence 4 and 6 omits hydrogens

### ISSUE THREAD

**Issue by vfscalfani** [rdkit/rdkit#6436]
**Describe the bug**

For molecules with sulfur with valence 4 and 6, valence is reduced to 2 when computing an InChI and hydrogens are lost. I looked through the InChI Standard Valences, and I don't believe this is a normalization change (Appendix I in InChI technical manual) https://www.inchi-trust.org/all-downloadable-versions/

**To Reproduce**

```
mol1 = Chem.MolFromSmiles('CN(C)[SH3]')
for atom in mol1.GetAtoms():
    print(atom.GetSymbol(), atom.GetTotalValence(),  atom.GetTotalNumHs())
C 4 3
N 3 0
C 4 3
S 4 3
```

```
Chem.MolToInchi(mol1)
InChI=1S/C2H7NS/c1-3(2)4/h4H,1-2H3
```

```
mol2 = Chem.MolFromSmiles('CN(C)[SH5]')
for atom in mol2.GetAtoms():
    print(atom.GetSymbol(), atom.GetTotalValence(),  atom.GetTotalNumHs())
C 4 3
N 3 0
C 4 3
S 6 5
```

```
print(Chem.MolToInchi(mol2))
InChI=1S/C2H7NS/c1-3(2)4/h4H,1-2H3
```

**Expected behavior**

Here are the InChIs that I was expecting:

For `CN(C)[SH3]` ---> `InChI=1S/C2H9NS/c1-3(2)4/h1-2,4H3`
For `CN(C)[SH5]` ---> `InChI=1S/C2H11NS/c1-3(2)4/h1-2H3,4H5`

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.1
 - OS: Ubuntu 22.04
 - Python version (if relevant): 3.11.3
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit? N/A

**Comment by wopozka** [comment]
It is more to the inchi library authors that to rdkit itself, but on the other hand molecules you wrote are not correct, as in the form you wrote them a charge is missing.
