### ISSUE TITLE
Error when importing Draw or PandasTools

### ISSUE THREAD

**Issue by ValeryPolyakov** [rdkit/rdkit#6447]
I am getting the following error when using Python 3.10.11 on Ubuntu 2022:

Python 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
>>> from rdkit.Chem import Draw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/polyakovv/anaconda3/envs/rdk3_10/lib/python3.10/site-packages/rdkit/Chem/Draw/__init__.py", line 14, in <module>
    from rdkit.Chem.Draw import rdMolDraw2D
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory

it happens on most recent and older versions of rdkit

Thanks for you help,

Valery

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.5 and 2023
 - OS: [e.g. Ubuntu 20.04]: 2023
 - Python version (if relevant): Python 3.10.11 
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? default
 - 
**Additional context**

**Comment by phyto-coder** [comment]
Looks like the package [`libxrender1`](https://packages.debian.org/de/sid/libxrender1) is missing.

`sudo apt install libxrender1`

should hopefully resolve the `ImportError`.
