### ISSUE TITLE
Issue with standardization/Kekule form when importing rxn files

### ISSUE THREAD

**Issue by spparel** [rdkit/rdkit#6448]
In some specific cases, RDKit is unable to read an rxn file written from RDKit. This seems to happen in particular when a heteroaromatic ring with 2 nitrogens (one being N-H) is in the product. The error reported is: "Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10"

**To Reproduce**
`from pathlib import Path

from rdkit import Chem
from rdkit.Chem import AllChem

reactant_smi = 'CC1(C)CC(=O)c2c[nH]nc2C1'
product_smi = 'Cc1n[nH]cc1C=O'

reactant = Chem.MolFromSmiles(reactant_smi, sanitize=True)
product = Chem.MolFromSmiles(product_smi, sanitize=True)

reaction: AllChem.ChemicalReaction = AllChem.ChemicalReaction()
reaction.AddReactantTemplate(reactant)
reaction.AddProductTemplate(product)

reaction_block = AllChem.ReactionToRxnBlock(reaction)
Path('reaction1.rxn').write_text(AllChem.ReactionToRxnBlock(reaction))

rxn= AllChem.ReactionFromRxnFile(r"C:\KNIME\git\ldt-blueprint-devt-tk\examples\Utilities\reaction1.rxn",sanitize=True)
rxn`

When using sanitize=False, the aromatic bonds go missing.
![RXN_Error](https://github.com/rdkit/rdkit/assets/135133375/44114435-33c5-4e08-bffa-0602eb41ff5c)
The same error happens when doing a round trip with 
reaction_block = AllChem.ReactionToRxnBlock(reaction)
reaction = AllChem.ReactionFromRxnBlock(reaction_block, sanitize=True)

This doesn't happen when the very same reactant or product are written to a molfile and read back.

**Expected behavior**
The rxn file/block should be correctly imported and displayed.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.1
 - OS: Windows 10
 - Python version (if relevant): 3.9
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by bp-kelley** [comment]
Reactions are a bit tricky.  The way RDKit handles them is by using query molecules for both the reactant and the product.

If you use reaction smarts, your example works as expected:

```
rxn_smarts = 'CC1(C)CC(=O)c2c[nH]nc2C1>>Cc1n[nH]cc1C=O'
rxn = AllChem.ReactionFromSmarts(rxn_smarts)
```

By using sanitized mols you are triggering odd behavior in the reaction processing, a better way is to use smarts/query molecules which also have the expected behavior:

```
reactant_smi = 'CC1(C)CC(=O)c2c[nH]nc2C1'
product_smi = 'Cc1n[nH]cc1C=O'

reactant = Chem.MolFromSmarts(reactant_smi)
product = Chem.MolFromSmarts(product_smi)
```

That being said, dropping the explicit hydrogen from the product does seem like a bug to me.

**Comment by bp-kelley** [comment]
A simple fix, in this case, is to add hydrogens explicitly:

```
product = Chem.AddHs(Chem.MolFromSmiles(product_smi))
```
