### ISSUE TITLE
Wrong preprocessing of chlorine and bromine oxyacids

### ISSUE THREAD

**Issue by aigulkhkmv** [rdkit/rdkit#6454]
Dear RDKit developers,

I'm trying to read 4 types of chlorine oxyacids (_hypochlorous_, _chlorous_, _chloric_ and _perchloric_ _acid_) using `Chem.MolFromSmiles`, however, after reading RDKit breaks the structures. The algorithm adds charges to the oxygen and chlorine atoms, such behaviour is chemically incorrect. 
Using the `sanitize=False` option saves the chemical correctness, but it makes such molecules incorrect for RDKit methods and  it's not the best option for other (non chlorine oxyacid) molecules. 

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import Draw

chlorine_acids = {1: '[H]OCl', 3: 'O[Cl]=O', 5: 'O[Cl](=O)=O', 7: 'O[Cl](=O)(=O)=O'}
Draw.MolsToGridImage([Chem.MolFromSmiles(i) for i in chlorine_acids.values()],  molsPerRow=4)
```
_Output:_
<img width="411" alt="image" src="https://github.com/rdkit/rdkit/assets/40434269/35dc1344-e37a-443f-8555-5b359d202a07">

```
Chem.MolFromSmiles('O[Cl]=O', sanitize=False)
```
_Output:_
<img width="275" alt="image" src="https://github.com/rdkit/rdkit/assets/40434269/a551b2ff-c49b-4ff7-ba52-594e96770de3">

```
Draw.MolsToGridImage([(Chem.MolFromSmiles('O[Cl]=O', sanitize=False))])
```
_Output:_
```
RuntimeError: Pre-condition Violation
	getExplicitValence() called without call to calcExplicitValence()
	Violation occurred on line 308 in file Code/GraphMol/Atom.cpp
	Failed Expression: d_explicitValence > -1
	RDKIT: 2023.03.1b1
	BOOST: 1_78
```

**Expected behavior**
The expected behavior is to keep the original structure of the molecules and not give charges to the oxygen and chlorine atoms. 
Current behavior looks like a bug...  or maybe RDKit have a spectial options for fixing this problem?
 
Many thanks!

**Configuration:**
 - RDKit version: 2023.03.1b1 and 2022.9.5
 - OS: [masOS 10.15.7]
 - Python version (if relevant): 3.9
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit?
1. ```poetry add rdkit``` (for 2022.9.5 version)
2. ```pip install rdkit-pypi==2023.3.1b1```

**Additional context**
The bromine oxyacids have same behaviour.

**Comment by greglandrum** [comment]
This is expected behavior and is documented here: https://www.rdkit.org/docs/RDKit_Book.html#molecular-sanitization

The zwitterionic form that the RDKit uses is just an alternate, non-hypervalent, representation of the structure.

If you insist upon the hypervalent form, you can certainly use that by doing partial sanitization. Doing a web search for that will turn up a bunch of hits describing how to do this.
