### ISSUE TITLE
Chem.MolToSmiles gives invalid SMILES

### ISSUE THREAD

**Issue by LiuCMU** [rdkit/rdkit#6458]
**Describe the bug**
I converted a RDKit mol object to SMILES using `Chem.MolToSmiles`. However, when I use `Chem.MolFromSmiles` to convert the resulting SMILES back to mol, I got `None`.

**To Reproduce**
```
def add_dummy_atom(smi):
    """adding an dummy atom to each atom with at least a H"""
    mols_with_dummy, smiles = [], []
    mol = Chem.MolFromSmiles(smi)
    for atom in mol.GetAtoms():
        NumHs = atom.GetTotalNumHs()
        if NumHs > 0:
            e_mol = Chem.EditableMol(mol)
            e_mol.AddAtom(Chem.Atom(0))
            e_mol.AddBond(atom.GetIdx(), mol.GetNumAtoms(), Chem.BondType.SINGLE)
            mol_with_dummy = e_mol.GetMol()
            mols_with_dummy.append(mol_with_dummy)
            smiles.append(Chem.MolToSmiles(mol_with_dummy, canonical=True))
    return mols_with_dummy, smiles

hinge_smi = 'C1CN(CCN1S(=O)(=O)c1cn[nH]c1)C'
dummy_mols, dummy_smiles = add_dummy_atom(hinge_smi)
Chem.Draw.MolsToGridImage(dummy_mols, molsPerRow=4)
```
All molecules seem to be valid in the figure.
![image](https://github.com/rdkit/rdkit/assets/60156077/4b95f907-834c-4ddc-b6a5-cc1000deecc4)
However, when I got None when converting the SMILES back to mol:
```
mol = Chem.MolFromSmiles(Chem.MolToSmiles(dummy_mols[5]))
print(mol)  # None
```

**Expected behavior**
I expected `Chem.MolFromSmiles(Chem.MolToSmiles(dummy_mols[5]))` give me back the mol object.

**Configuration (please complete the following information):**
 - RDKit version: 2023.3.1
 - OS: [e.g. Ubuntu 20.04]: Ubuntu 20.04.5 LTS
 - Python version (if relevant):Python 3.9.16
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from? NA
 - If you are not using conda: how did you install the RDKit? PyPI

Any thoughts about this behavior will be much appreciated. Thank you!

**Comment by wopozka** [comment]
Well, it is expected befaviour. MolFromSmiles expects smiles to be valid, and you are providing invalid SMILES:
 '*[nH]1cc(S(=O)(=O)N2CCN(C)CC2)cn1'.
MolFromSmiles is not able to create valid molecule from this smiles, therefore returns None. To read this smiles add option: sanitize=False when doing MolFromSmiles.

**Comment by LiuCMU** [comment]
thanks for participating the discussion! 

The issue was solved by adding `Chem.Sanitize`. I feel if the `GetMol()` method could return `None` for invalid molecule would be a neater solution then using `try ... except...`.
```
def add_dummy_atom(smi):
    """adding an dummy atom to each atom with at least a H"""
    mols_with_dummy, smiles = [], []
    mol = Chem.MolFromSmiles(smi)
    for atom in mol.GetAtoms():
        NumHs = atom.GetTotalNumHs()
        if NumHs > 0:
            e_mol = Chem.EditableMol(mol)
            e_mol.AddAtom(Chem.Atom(0))
            e_mol.AddBond(atom.GetIdx(), mol.GetNumAtoms(), Chem.BondType.SINGLE)
            mol_with_dummy = e_mol.GetMol()
            try:
                Chem.SanitizeMol(mol_with_dummy)
                mols_with_dummy.append(mol_with_dummy)
                smiles.append(Chem.MolToSmiles(mol_with_dummy, canonical=True))
            except:
                pass
    return mols_with_dummy, smiles

hinge_smi = 'C1CN(CCN1S(=O)(=O)c1cn[nH]c1)C'
dummy_mols, dummy_smiles = add_dummy_atom(hinge_smi)
Chem.Draw.MolsToGridImage(dummy_mols, molsPerRow=4)
```
