### ISSUE TITLE
Unexpected non-matching ElementGraph hashes

### ISSUE THREAD

**Issue by jepdavidson** [rdkit/rdkit#6472]
### Discussed in https://github.com/rdkit/rdkit/discussions/6470

<div type='discussions-op-text'>

<sup>Originally posted by **jepdavidson** June 19, 2023</sup>
Dear All,

I have an example of two molecules that I believe should give the same ElementGraph hashes, but they don't (well - actually they **do** using NextMove's molhash binary, but they don't using RDKit...).

The question is - is there a setting or approach that I am missing to get these two to match?

Here's the example:
![image](https://github.com/rdkit/rdkit/assets/7816101/5f6f1359-bb69-4697-8809-69eed689c43d)

```python
from rdkit import Chem, rdBase
from rdkit.Chem import rdMolHash

print(rdBase.rdkitVersion)
m1 = Chem.MolFromSmiles("C1COC(C1)C1=NC=NC=C1")
m2 = Chem.MolFromSmiles("C1CC(N=CN1)C1=CC=CO1"
hashes = [rdMolHash.MolHash(m, rdMolHash.HashFunction.ElementGraph) for m in (m1, m2)]
print(*hashes, hashes[0] == hashes[1], sep="\t")
```
> 2023.03.1
> C1COC(C2CCNCN2)C1
> C1CC(C2CCCO2)NCN1
> False

Here are the same inputs using the molhash cli (pushing the smiles strings in with newline separator, then -t flag for to only output the hash [title only option] and -e for element graph):

```bash
echo "C1COC(C1)C1=NC=NC=C1\nC1CC(N=CN1)C1=CC=CO1" | molhash -t -e -
```
> C1CC(OC1)C2CCNCN2
> C1CC(OC1)C2CCNCN2

As always, any help/advice is greatly appreciated!

Kind regards

James</div>

**Comment by manangoel99** [comment]
@greglandrum can I take this up?
