### ISSUE TITLE
RDKit cannot read standard PDB files

### ISSUE THREAD

**Issue by peastman** [rdkit/rdkit#6501]
**Describe the bug**
The PDB file reader in RDKit does not comply with the spec.  When trying to load valid files, this leads it to either throw exceptions or else load them incorrectly.

[The PDB spec](http://www.wwpdb.org/documentation/file-format-content/format33/sect10.html#CONECT) describes how bonds should be identified when loading a file.  For standard amino acids, nucleotides, and water, they are not specified in the file.  The reader should fill in the standard bonds for those residues as specified in the Chemical Components Dictionary.  For all other residues (heterogens), bonds must be explicitly specified with `CONECT` records.

RDKit does not follow the spec.  Instead it offers a choice of two non-compliant behaviors.  If `proximityBonding=True`, it adds bonds between nearby atoms.  This sometimes leads it to incorrectly add bonds that do not exist.  If `proximityBonding=False` it does not add spurious bonds, but also does not add any bonds to standard residues.

**To Reproduce**
Put the following into a file called `error.pdb`.

```
HETATM    1  C   ACE A   1     -10.866  -2.016   6.873  1.00  0.00           C  
HETATM    2  O   ACE A   1     -10.273  -0.913   6.985  1.00  0.00           O  
HETATM    3  CH3 ACE A   1     -12.338  -1.737   6.619  1.00  0.00           C  
HETATM    4  H1  ACE A   1     -12.949  -2.622   6.234  1.00  0.00           H  
HETATM    5  H2  ACE A   1     -12.826  -1.157   7.467  1.00  0.00           H  
HETATM    6  H3  ACE A   1     -12.515  -2.419   7.456  1.00  0.00           H  
ATOM      7  N   ILE A   2     -10.560  -3.063   6.062  1.00  0.00           N  
ATOM      8  H   ILE A   2      -9.792  -3.645   6.356  1.00  0.00           H  
ATOM      9  CA  ILE A   2     -10.460  -2.557   4.689  1.00  0.00           C  
ATOM     10  HA  ILE A   2      -9.429  -2.231   4.547  1.00  0.00           H  
ATOM     11  C   ILE A   2     -11.328  -1.323   4.474  1.00  0.00           C  
ATOM     12  O   ILE A   2     -10.995  -0.451   3.672  1.00  0.00           O  
ATOM     13  CB  ILE A   2     -10.768  -3.639   3.634  1.00  0.00           C  
ATOM     14  HB  ILE A   2     -10.154  -4.510   3.870  1.00  0.00           H  
ATOM     15  CG1 ILE A   2     -10.381  -3.118   2.249  1.00  0.00           C  
ATOM     16 HG12 ILE A   2      -9.716  -2.258   2.342  1.00  0.00           H  
ATOM     17 HG13 ILE A   2     -11.269  -2.781   1.711  1.00  0.00           H  
ATOM     18  CG2 ILE A   2     -12.235  -4.051   3.700  1.00  0.00           C  
ATOM     19 HG21 ILE A   2     -12.415  -4.841   2.970  1.00  0.00           H  
ATOM     20 HG22 ILE A   2     -12.894  -3.215   3.466  1.00  0.00           H  
ATOM     21 HG23 ILE A   2     -12.474  -4.444   4.688  1.00  0.00           H  
ATOM     22  CD1 ILE A   2      -9.648  -4.093   1.418  1.00  0.00           C  
ATOM     23 HD11 ILE A   2      -9.400  -3.640   0.458  1.00  0.00           H  
ATOM     24 HD12 ILE A   2     -10.269  -4.973   1.245  1.00  0.00           H  
ATOM     25 HD13 ILE A   2      -8.725  -4.392   1.917  1.00  0.00           H  
HETATM   26  N   NME A   3     -12.075  -0.814   5.466  1.00  0.00           N  
HETATM   27  H   NME A   3     -13.030  -1.051   5.214  1.00  0.00           H  
HETATM   28  C   NME A   3     -12.111   0.618   5.811  1.00  0.00           C  
HETATM   29  H1  NME A   3     -12.739   1.147   5.094  1.00  0.00           H  
HETATM   30  H2  NME A   3     -11.105   1.039   5.742  1.00  0.00           H  
HETATM   31  H3  NME A   3     -12.486   0.808   6.816  1.00  0.00           H  
TER      32      NME A   3
CONECT    1    3    2    7
CONECT    2    1
CONECT    3    4    5    6    1
CONECT    4    3
CONECT    5    3
CONECT    6    3
CONECT    7    1
CONECT   11   26
CONECT   26   27   11   28
CONECT   27   26
CONECT   28   29   30   31   26
CONECT   29   28
CONECT   30   28
CONECT   31   28
END
```

Then try to load it with

```python
mol = Chem.MolFromPDBFile('error.pdb', removeHs=False)
```

It prints the message

```
[12:16:13] Explicit valence for atom # 2 C, 5, is greater than permitted
```

and returns `None`.  That is because the file describes a strained conformation, and RDKit incorrectly infers an extra bond for atom 2.  If you add the argument `proximityBonding=False` then it successfully loads the molecule, but there are no bonds within the ILE residue.

**Expected behavior**
This is a valid file and should be loaded without problem.  Atom 2 only has four bonds.  The ILE residue should have the standard bonds specified in the Chemical Components Dictionary.

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.1
 - OS: [e.g. Ubuntu 20.04] Ubuntu 22.04
 - Python version (if relevant): 3.10.11
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by Zebreu** [comment]
I faced this issue with pdb structures from AlphaFold. For my application, turning off the sanitization (sanitize=False) while keeping the proximityBonding true was sufficient to read in the files for torchdrug without adverse impacts.
