### ISSUE TITLE
module 'rdkit.Chem' has no attribute 'MolsFromCDXMLFile'

### ISSUE THREAD

**Issue by liushili0319** [rdkit/rdkit#6514]
-----------------------------------------
Description:
RDKit Version: 2023.03.02
Platform: windows
When I used 'MolsFromCDXMLFile' , it returns an error of moduld ''rdkit.Chem' has no attribute 'MolsFromCDXMLFile'
-----------------------------------------

**Comment by greglandrum** [comment]
How did you install the RDKit?

**Comment by liushili0319** [comment]
> How did you install the RDKit?

I installed Rdkit through conca

**Comment by liushili0319** [comment]
> > How did you install the RDKit?
> 
> I installed Rdkit through conca

I am trying to parse a chemical generation route using Rdkit, and I want to know if Rdkit can parse the complete route without losing information

**Comment by ypotier** [comment]
I installed RDKit with conda, and I have the same problem. It could be a version issue since the conda install gives me:
`rdkit.__version__` as  `2022.03.5 `

**Comment by greglandrum** [comment]
If conda doesn't automatically update, you can install the newer version by specifying it:
`mamba install rdkit=2024.03`
or
`conda install rdkit=2024.03`
