### ISSUE TITLE
Program Terminates without any error messages after attempting to generate Image from SMILEs

### ISSUE THREAD

**Issue by DanielFlockhart** [rdkit/rdkit#6530]
Bug Description -
- Program generates images from smiles fine, until it reaches specific smiles, at processing these smiles, the program terminates without any error message, does not generate the image and does not continue execution.
- Example of SMILEs with a Problem - "CCOC(=O)c1cc2OCCOCCOCCOCCOc3ccc(OCCOCCOCCOCCOc1cc2C(=O)OCC)cc3"

**To Reproduce**
Here is example code of issue.
As mentioned, it is only able to generate the first 2 smiles, once it reaches the 3rd, it terminates and the program halts without any feedback.

```

from rdkit import Chem
from rdkit.Chem import Draw
from PIL import Image

def generation(smile):
    m = Chem.MolFromSmiles(smile) # Generate Structure from smile
    if m is not None: # Check if smile is valid
        Draw.MolToFile(m, str(smile)+".png") # Generate image from structure - Execution Terminates on this line for 3rd Smile
        img = Image.open(str(smile)+".png") # Open image
        img.show() # Display image
                                                                                                
smiles = ["c1ccccc1","[N-]=[N+]=C1C(=NN=C(c2ccccc2)c2ccccc2)c2ccccc2C1=NN=C(c1ccccc1)c1ccccc1", "CCOC(=O)c1cc2OCCOCCOCCOCCOc3ccc(OCCOCCOCCOCCOc1cc2C(=O)OCC)cc3","[nH+]1ccccc1C1=NN=N[N-]1"]

for smile in smiles:
    generation(smile)
```

- Regardless of whether it is a valid smile or not, should it not output an error?

 - RDKit version: 2023.03.1
 - OS: Windows 11
 - Python version 3.11.4

**Comment by ptosco** [comment]
I cannot reproduce the problem on the current `master` branch.

**Comment by DanielFlockhart** [comment]
Problem Fixed - I updated my RDKit and The Problem fixed itself.
