### ISSUE TITLE
Create a radical on the SMART string

### ISSUE THREAD

**Issue by tungnguyen2027** [rdkit/rdkit#6532]
RDKit version: 2022.09.5

I wonder if there is a way to create a radical on a molecule on the SMART string? I tried to use ``` ^ ``` to represent a radical on a string, but it did not work. Furthermore, is it possible to run reactions and have a radical on the product side? Thanks.

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.
