### ISSUE TITLE
MolStandardizer does not clean up atomic properties

### ISSUE THREAD

**Issue by gayverjr** [rdkit/rdkit#6544]
**Describe the bug**

Reposting from [here](https://github.com/chembl/ChEMBL_Structure_Pipeline/issues/52#issuecomment-1634799498) at the suggestion of @greglandrum.

For the following SMILES, `CC1COCC[S@]1=O |&1:6|`, I have encountered some unusual behavior with the output of `MolToCXSmiles` after running `standardize_mol` from `chembl_structure_pipeline`. The output SMILES contains numerous additional features like`react_atom_idx` and `was_dummy`.

One can clean these properties using the following code:
```
for atom in mol.GetAtoms():
    for prop in atom.GetPropNames():
        atom.ClearProp(prop)
```
and get the desired SMILES `CC1COCC[S@@+]1[O-] |&1:6|`.

**To Reproduce**
```
import rdkit
from chembl_structure_pipeline import standardizer
smi = "CC1COCC[S@]1=O |&1:6|"
mol = rdkit.Chem.MolFromSmiles(smi)
mol = standardizer.standardize_mol(mol)
print(rdkit.Chem.MolToCXSmiles(mol))

> CC1COCC[S@@+]1[O-] |atomProp:0.react_atom_idx.0:1.old_mapno.4:1.react_atom_idx.1:1.was_dummy.1:2.react_atom_idx.2:3.react_atom_idx.3:4.react_atom_idx.4:5.old_mapno.1:5.react_atom_idx.5:5.was_dummy.1:6.old_mapno.2:6.react_atom_idx.6:7.old_mapno.3:7.react_atom_idx.7,&1:6
```

**Expected behavior**
I would not expect to see these additional properties in the output SMILES from MolToCXSmiles.

**Configuration:**
Installed via pip.

 - RDKit version: 2023.3.2, also observed in 2022.9.3
 - Chembl version: 1.2.0
 - OS: MacOS Ventura 13.4

**Comment by greglandrum** [comment]
Here's a simple, pure-RDKit demo:
```
In [7]: smi = "CC1COCC[S@]1=O |&1:6|"

In [8]: mol = rdkit.Chem.MolFromSmiles(smi)

In [9]: from rdkit.Chem.MolStandardize import rdMolStandardize

In [10]: Chem.MolToCXSmiles(rdMolStandardize.Normalize(mol))
Out[10]: 'CC1COCC[S@+]1[O-] |atomProp:0.react_atom_idx.0:1.old_mapno.4:1.react_atom_idx.1:1.was_dummy.1:2.react_atom_idx.2:3.react_atom_idx.3:4.react_atom_idx.4:5.old_mapno.1:5.react_atom_idx.5:5.was_dummy.1:6.old_mapno.2:6.react_atom_idx.6:7.old_mapno.3:7.react_atom_idx.7,&1:6|'
```
