### ISSUE TITLE
Chem.MolFromMolFile failed to complete loading some MOL files

### ISSUE THREAD

**Issue by Hikoyu** [rdkit/rdkit#6545]
The bug described in title occurs on RDKit 2023_03_1 or later.
For example, the mol file of ChEBI_77803 downloaded from ChEBI causes this bug.
Python process is running and does not finish.
It does not occur on RDKit 2022_09_5.
Thank you.

P.S.
The bug occurs on python3.11.x running on both Linux (Ubuntu 22.04) and macOS (13.4.1).

**Comment by m-crown** [comment]
I also experience this bug, using RDKit 2022_09_5 does not cause the same problem, using ChEBI 67122

**Comment by m-crown** [comment]
The same thing occurs with MolFromMolBlock
