### ISSUE TITLE
MMPA compile error with Microsoft Visual C++ Compiler for Python 2.7

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#655]
when building the current tip of the master branch (a783197) on windows using the Microsoft Visual C++ Compiler for Python 2.7, the following error is issued:

C:\Users\riccardo\Anaconda\conda-bld\work\Code\GraphMol\MMPA\MMPA.cpp(206) : error C2039: 'at' : is not a member of 'std::map<_Kty,_Ty>'
        with
        [
            _Kty=unsigned int,
            _Ty=unsigned int
        ]

the 'at' method of std::map is a C++11 feature and I'm afraid it's not supported by msvc 2008.

**Comment by greglandrum** [comment]
Nice catch. I had just built with VC++ 2010, which must be one version more modern.

**Comment by rvianello** [comment]
thanks for the quick fix!
