### ISSUE TITLE
Wrong AtomIdx when using bond.GetEndAtomIdx()

### ISSUE THREAD

**Issue by JanoschMenke** [rdkit/rdkit#6554]
**Describe the bug**
When using `.GetEndAtomIdx()` for a bond of a particular atom in a particular molecule, it will return the index of the start atom rather than the end atom.

**To Reproduce**
```
mol = Chem.MolFromSmiles('COc1ccccc1N1CCN(CCCCCCN2Cc3ccccc3C2)CC1')
atom = mol.GetAtomWithIdx(12)
atom.GetBonds()[0].GetEndAtomIdx()
>>> 12
```
**Expected behavior**
The resulting EndAtomIdx should be 11, as it is the bond between the 11 and 12 atom. 

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.5
 - OS: Mac OS 13.4
- Channel: conda-forge

**Comment by bp-kelley** [comment]
You can’t think about it that way, the bond index is in the order of when the bond was added based on parsing the smiles.   Even though atom 11 came first, the parser only knows about it when atom 12 is parsed.

Bonds can’t share atom indices, so a single bond between atom 11 and 12 is identical to a bond between atom 12 and 11

A useful concept is Get Other Atom which helps to find the other atom at the end of the bond: (apologies if I don’t get the function names exactly correct here)


```
def get_other_atom_idx(bond, atom):
     if atom.GetIdx() == bond.GetBeginAtomIdx():
         return bond.GetEndAtomIdx()
     return bond.GetBeginAtomIdx()
```

**Comment by JanoschMenke** [comment]
Oh okay, so then it all makes sense. Thank you. It did feel this would have caused too much chaos to go unnoticed if this behavior was not intentional.
