### ISSUE TITLE
rdkit ph and protonation

### ISSUE THREAD

**Issue by Nag-Nad** [rdkit/rdkit#6559]
Good day to The Community,

I have recently started to use rdkit for a project and I am not sure if I am on a right track. Regarding the function Chem.AddH(), I would like to know in which pH does rdkit protonate the smile molecules? Since it can solve my doubts and help me move on, I would appreciate every single help. 

Thank you.

_Originally posted by @Nag-Nad in https://github.com/rdkit/rdkit/discussions/6558_

**Comment by salvogalati** [comment]
RDKit function AddH does not take pH into account. The function simply adds the hydrogens taking into account only the valence.

**Comment by greglandrum** [comment]
This isn't an issue, it's by design. The RDKit does not have a pKa model.
