### ISSUE TITLE
usage issue with multiprocessing pool.map

### ISSUE THREAD

**Issue by pwging13** [rdkit/rdkit#6573]
**Describe the bug**
rdMolDescriptors.CalcNumAtomStereoCenters doesn't seem to work in multiprocessing pool

**To Reproduce**
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdMolDescriptors
import multiprocessing as mp

smiles_list=['CCCC','C[C@H](F)CC']
mols=[Chem.MolFromSmiles(m) for m in smiles_list]
df=pd.DataFrame(mols,columns=['mol'])

def mol_props(mol):
    NumStereocenters=rdMolDescriptors.CalcNumAtomStereoCenters(mol)
    return NumStereocenters

def mol_to_smiles(mol):
	smiles=Chem.MolToSmiles(mol)
	return smiles

for idx, compound in df.iterrows():
	print(mol_props(compound['mol']))
	print(mol_to_smiles(compound['mol']))
	
with mp.Pool(mp.cpu_count()-1) as pool:
	smiles_list = pool.map(mol_to_smiles, df.mol.tolist())

with mp.Pool(mp.cpu_count()-1) as pool:
	props = pool.map(mol_props, df.mol.tolist())

**Expected behavior**
The code above should return a list of props, in this case the number of stereocenters in each molcule

**Screenshots**
![image](https://github.com/rdkit/rdkit/assets/46912002/51855d1f-2800-4e00-99b0-79b4df6589af)

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.1
 - OS: WSL2 Ubuntu 22.04
 - Python version (if relevant): 3.11.3
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? -conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**
From the code above, passing mol objects to mol_props using a multiprocessing pool fails.  Doing the same thing to return the smiles works fine, to include returning the stereochemistry on the second molecule.  Calling each function in the for loop works fine.

**Comment by bwhall61** [comment]
This is because pickling `Mol` objects (which occurs when you use multiprocessing) does not preserve atom properties by default. You can either call: `Chem.SetDefaultPickleProperties(Chem.PropertyPickleOptions.AllProps)` before you use `pool.map` or in your `mol_props` function you can call: `Chem.AssignStereochemistry(mol, flagPossibleStereoCenters=True)`.

**Comment by j-adamczyk** [comment]
@pwging13 this is working as expected, as @bwhall61 explained. You can also use `PropertyMol` objects instead of `Mol`, without setting this globally. `PropertyMol` objects always serialize their properties. You can convert regular `Mol` by using `PropertyMol(mol)`.

Can this be closed then?
