### ISSUE TITLE
`FingeprintGenerator64` is a typo

### ISSUE THREAD

**Issue by davidegraff** [rdkit/rdkit#6576]
the base classes for fingerprint generation, `FingeprintGenerator{32,64}` are misspelled. They should be `Finge*r*printGenerator{32,64}`.

Thank you for coming to my TED talk.

**Comment by davidegraff** [comment]
it looks like this was fixed in `2023.3.2`, but there's no mention in the release notes.

**Comment by j-adamczyk** [comment]
@davidegraff can this be closed now?

**Comment by davidegraff** [comment]
Looks like it

**Comment by LucaCappelletti94** [comment]
I still see this in version `2024.3.5`

**Comment by ptosco** [comment]
It is fixed in 2024.09.1.

**Comment by LucaCappelletti94** [comment]
When I search it in the `rdkit` code base I do not get any matches, so I suppose these may be generated during the binding generation something of that sorts. Anyhow, I get several instances, such as: `FingeprintGenerator32`, `FingeprintGenerator64`. I confirm that my `rdkit.__version__` is `2024.03.5`. I do not see a `2024.09.1` version available on PyPi: https://pypi.org/project/rdkit/#history
