### ISSUE TITLE
GetPropNames()  returning an instance of 'rdkit.rdBase._vectNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE' instead of a tuple

### ISSUE THREAD

**Issue by teherin** [rdkit/rdkit#6584]
I'm reading a SDF and trying to use GetPropNames() on the mol object to validate 'column' names in the SDF. However, its returning an instance of an internal class instead of the tuple described in the docstring. 
Looks like the auto generated documentation is picking up the same internal class as the return type
https://www.rdkit.org/docs/source/rdkit.Chem.rdchem.html?highlight=getpropnames#rdkit.Chem.rdchem.Mol.GetPropNames

The data for the property names are in the returned object, just not in the way expected. Membership tests like `expected_name in mol.GetPropNames()` will work but checks against a collection of names like `[name1, name2] == mol.GetPropNames()` will not

I've tried a couple files but can't share the specific SDFs I've tried. I suspect any SDF will do to reproduce.

I'm pretty sure this is just a bug.

**To Reproduce**
```
fp = 'any_old_convenient.sdf'

with Chem.ForwardSDMolSupplier(fp) as supplier:
        for test_mol in supplier:
            if test_mol is None:
                continue
            prop_names = test_mol.GetPropNames()
            # returns <rdkit.rdBase._vectNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE object at 0x165eb11c0>
            props = test_mol.GetPropsAsDict()
            # works as expected
            formatted_prop_names = tuple([str(name) for name in prop_names])
            # the data is in there, just need to bubble it to the surface
            assert formatted_prop_names == tuple(props.keys())
            assert prop_names == tuple(props.keys())
            break
```

**Expected behavior**
Would expect a tuple of the property names from the molecule, like getting the keys from the property dictionary

**Configuration:**
 - RDKit version: 2023.3.2
 - OS: MacOSX 13.3.1 (a) 
 - Python version (if relevant): 3.10
 - Are you using conda? yep
 - If you are using conda, which channel did you install the rdkit from? n/a pip installed into the conda env

**Comment by ptosco** [comment]
@teherin This is not a bug. The C++ object, as shown in your code, is iterable and can be cast to a `tuple` or `list` if you need a Python object, e.g.:
```
prop_names = tuple(test_mol.GetPropNames())
```
