### ISSUE TITLE
Segfault when calling Atom.GetBonds()

### ISSUE THREAD

**Issue by dhroth** [rdkit/rdkit#6589]
**Describe the bug**
Segfault when calling GetBonds() on an Atom

**To Reproduce**
$ python -c "from rdkit import Chem; mol = Chem.MolFromSmiles('CCC'); Chem.AddHs(mol).GetBonds()[0].GetEndAtom().GetBonds()"
Segmentation fault (core dumped)

**Expected behavior**
Should output the bonds corresponding to whichever atom is the end atom of the molecule's first bond.

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.2       py311hc21844d_0    conda-forge
 - OS: [e.g. Ubuntu 20.04] Happens on Ubuntu 22.04.2 LTS and arch linux 6.4.4-arch1-1
 - Python version (if relevant): 3.11.0 and 3.11.3
 - Are you using conda? Yes (actually using mamba, not conda)
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit? N/A

**Additional context**
I have the same problem with any SMILES string I try. However, it works fine if I don't call Chem.AddHs() first, or if I split the code into multiple lines (the following works fine):
```
from rdkit import Chem
mol = Chem.MolFromSmiles('CCC')
mol2 = Chem.AddHs(mol)
print(mol2.GetBonds()[0].GetEndAtom().GetBonds())
```

**Comment by ptosco** [comment]
This is awell- known issue due to the object lifetime management between C++ and Python.
As you have already found, you need to assign intermediate C++ objects to a variable to avoid that they are destroyed before being used, which is what causes the segfault, e.g.:
```
python -c "from rdkit import Chem; mol = Chem.MolFromSmiles('CCC'); mol_h = Chem.AddHs(mol); mol_h.GetBonds()[0].GetEndAtom().GetBonds()"
```
Therefore, yes, this is a bug, but there is a very simple workaround and, unfortunately, no easy solution.

**Comment by dhroth** [comment]
Ah okay, I didn't realize this was well-known and difficult to solve (didn't find anything when I searched for issues with segfaults on GetBonds()). Thanks for the reply!
