### ISSUE TITLE
Exception when using SubstructLibrary.ToStream method with CachedMolHolder

### ISSUE THREAD

**Issue by chloechow** [rdkit/rdkit#6591]
**Describe the bug**
An exception is thrown when using the `SubstructLibrary.ToStream` method with `CachedMolHolder`. The error message is `terminate called after throwing an instance of 'boost::python::error_already_set'`. This error does not occur when using `CachedSmilesMolHolder`.

**To Reproduce**
Here's a snippet of Python code that reproduces the error:
```
from rdkit import Chem
from rdkit.Chem import rdSubstructLibrary
mol = Chem.MolFromSmiles('C1CCCC1')
molh = Chem.AddHs(mol)
molholder = rdSubstructLibrary.CachedMolHolder()
lib = rdSubstructLibrary.SubstructLibrary(molholder, rdSubstructLibrary.KeyFromPropHolder())
lib.AddMol(molh)

with open('rdkit.sslib', 'w') as f:
    lib.ToStream(f) # this line causes the error
```

**Expected behavior**
I expected the `SubstructLibrary` to be written to a file without any issues.

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.02
 - OS: CentOS Linux release 8.5.2111
 - Python version (if relevant): 3.11.4
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? conda-forge

**Additional context**
Interestingly, when I use a `CachedSmilesMolHolder` instead of a `CachedMolHolder`, the `ToStream` method works without any issues. This suggests that the issue might be related to how `CachedMolHolder` and `CachedSmilesMolHolder` store their data.

I was able to work around this issue by using `pickle` to save and load the `SubstructLibrary`, but this is not an ideal solution.

**Comment by bp-kelley** [comment]
I think this is, perhaps, us requiring a text mode for writing which doesn't work with the binary packing involved in the CachedMolHolders.  We should probably also support a binary read mode.

A work around, while fairly lame, is:

```
with open('rdkit.sslib', 'wb') as f:
    f.write(lib.Serialize())

lib = rdSubstructLibrary.SubstructLibrary()
with open('rdkit.sslib', 'rb') as f:
    lib.InitFromStream(f)
```

**Comment by chloechow** [comment]
Thank you for your quick response and the workaround. I've tried it and it works well for my use case.

I appreciate your help with this issue. I look forward to the potential support for a binary read mode in the future.
