### ISSUE TITLE
SIGSEGV while calculating molecular descriptors after using salt remover.

### ISSUE THREAD

**Issue by BartlomiejF** [rdkit/rdkit#6592]
**Describe the bug**
SIGSEGV while calculating molecular descriptors after using salt remover.

**To Reproduce**
```
def getMolDescriptors(mol, missingVal=None):
    from rdkit.Chem import Descriptors
    res = {}
    for nm,fn in Chem.Descriptors._descList:
        try:
            val = fn(mol)
        except:
            import traceback
            traceback.print_exc()
            val = missingVal
        res[nm] = val
    return res


mol = Chem.MolFromSmiles("CS(=O)(=O)O")
remover = SaltRemover()
stripped = remover.StripMol(mol)
getMolDescriptors(stripped)
```

**Expected behavior**
Calculate descriptors.

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.2, pip installed
 - OS: Ubuntu 22.04
 - Python version (if relevant): 3.10
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**
If visualised, the stripped mol is empty.

**Comment by bp-kelley** [comment]
The BCUT descriptors don't like empty molecules apparently.
