### ISSUE TITLE
The 3D structure of the molecule is not displayed.

### ISSUE THREAD

**Issue by okikosuke** [rdkit/rdkit#6604]
-----------------------------------------

```python
from rdkit import rdBase, Chem
from rdkit.Chem import AllChem, Draw
from rdkit.Chem.Draw import IPythonConsole
import sys, py3Dmol

smiles = "C/C(C)=C(CCC(N(C/C(C)=C(C)/C)/C(C)=C(C)\C)=O)\CC1=CC=CC=C1"
mol = Chem.MolFromSmiles(smiles)
IPythonConsole.drawMol3D(mol)
```
-----------------------------------------

**To Reproduce**
I could get no image.
![image](https://github.com/rdkit/rdkit/assets/74843794/74e9ed1a-45e6-44aa-8db8-1d087fa84c7a)

**Expected behavior**
I want 3d structure like this.
![image](https://github.com/rdkit/rdkit/assets/74843794/4cf3bcfd-9d32-4f2f-9e9a-cbbe121f0da6)

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.4
 - OS:  windows 10
 - Python version (if relevant): 3.7.13
- py3dmol: 1.8.1
 - Are you using conda? Yes

**Comment by ptosco** [comment]
This is not a bug. When you generate a molecule from SMILES, it will not have 3D coordinates since SMILES contains no 3D coordinate information. Please do not create bug reports if unsure - rather ask questions in the Discussions tab.

**Comment by okikosuke** [comment]
Sorry. I see. I will ask question  in the Discussions tab agein.
