### ISSUE TITLE
converting reactions loaded from rxn files to SMARTS results in incorrect SMARTS logic on bonds and loss of query features after a couple roundtrips

### ISSUE THREAD

**Issue by oleksii-dukhno-bayer** [rdkit/rdkit#6608]
**Describe the bug**
A valid MDL RXN file drawn in BIOVIA Draw with bond query features such as "single or aromatic" or "double or aromatic" seems to not survive a few roundtrips to SMARTS and back, losing features along the way (see code below).

There are few behaviors in here to discuss:
1) **Bug**: the "double or aromatic" bond with "ring" query from RXN file is resolved to SMARTS bond primitive `=,:&@` which is not correct as it means "double OR (in ring AND aromatic)" - should be `=,:;@` or `@;=,:` which means "(double OR aromatic) AND in ring" (see code in "To Reproduce" section).
2) **Bug**: `[!#1:2]=,:&@[#6:1](@[!#1:6])-[#1]>>[!#1:2]=,:&@[#6:1](@[!#1:6])-[#9]` after conversion to Reaction object and back to SMARTS loses some of the bond logic and becomes `[!#1:2]:&@[#6:1](@[!#1:6])-[#1]>>[!#1:2]:&@[#6:1](@[!#1:6])-[#9]`. The source of the issue seems on the ReactionToSmarts conversion step.
![image](https://github.com/rdkit/rdkit/assets/106537682/f9cf217f-b8dc-4439-80bf-da16f036c7be)

3) Questionable behavior: the "single or aromatic" bond with "ring" query from RXN file is resolved to `@` which means "default bond AND in ring". While it's true that the "single or aromatic" parts fits exactly with the definition of default bond in Daylight standard, doing this cleanup on a bond that was explicitly created with a `SingleOrAromaticBond` part obscures the original intent of the user to specify that with a query. Perhaps resolving it to `@;-,:` would be more appropriate, or adding a boolean toggle to not perform any additional "smarts sanitization" beyond the logic already described in rxn query?
4) Questionable behavior: there are at least three ways to have a bond in Reaction object that matches e.g. a "single or aromatic bond": 
    * as a `SingleOrAromaticBond=1` query element on a QueryBond, 
    * as `BondOr (BondOrder=1 BondOrder=12)` query element on a QueryBond, 
    * entirely omitted BondOrder or other related features on a QueryBond (results in parsing as a "default bond"). 
<br>Would the stricter choice of one preferred way be better?
5) Questionable behavior: after loading the MDL rxn file, some bonds are created as Bond objects, while others as QueryBond objects. This results in confusing behaviors for rendering and matching. E.g. for matching purposes a `Bond` with BondType of SINGLE is pretty much equivalent to a `QueryBond` that matches BondOrder of 1. This also is a source of inconsistencies for conversion between different formats. Would it make sense to have a boolean toggle to `ReactionFrom_[format]_` functions that forces every bond to be a QueryBond upon creation of a Reaction object?

**Expected behavior**
Described above.

**To Reproduce**
In a Jupyter notebook:
```
def describe_reactant_mol_bond_queries(rxn):
    reactant_mol = list(rxn.GetReactants())[0]
    print('Bond query descriptions of the reactant:')
    for bond_index, bond in enumerate(reactant_mol.GetBonds()):        
        print(f'bond_index: {bond_index}, bond object {bond}')
        print(bond.DescribeQuery())    
    reactant_mol.UpdatePropertyCache()  # reactants/products aren't sanitized normally so rdkit needs this for visualization purposes
    display(reactant_mol)

path_to_rxn = '/path/to/rxn/file/FluorineScan_2_Het(Ar)CH-CF.rxn'
rxn = Chem.rdChemReactions.ReactionFromRxnFile(path_to_rxn)
generated_smarts_1 = Chem.rdChemReactions.ReactionToSmarts(rxn)
rxn_from_generated_smarts_1 = Chem.rdChemReactions.ReactionFromSmarts(generated_smarts_1)
generated_smarts_2 = Chem.rdChemReactions.ReactionToSmarts(rxn_from_generated_smarts_1)
rxn_from_generated_smarts_2 = Chem.rdChemReactions.ReactionFromSmarts(generated_smarts_2)
generated_smarts_3 = Chem.rdChemReactions.ReactionToSmarts(rxn_from_generated_smarts_2)
rxn_from_generated_smarts_3 = Chem.rdChemReactions.ReactionFromSmarts(generated_smarts_3)

if (generated_smarts_1 != generated_smarts_2) or (generated_smarts_2 != generated_smarts_3):
    print('=========== MDL file contents =============')
    with open(path_to_rxn, 'r') as f:
        print(f.read())
    print('===========================================')
    print('Reaction as loaded by rdkit from MDL file (MDL rxn -> RDKit reaction object):')
    display(rxn)
    describe_reactant_mol_bond_queries(rxn)
    
    print('ReactionFromSmarts applied to original rxn (MDL rxn -> RDKit reaction object -> SMARTS):')
    print(generated_smarts_1)
    
    print('Reaction as loaded from smarts generated by rdkit (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object):')
    display(rxn_from_generated_smarts_1)
    describe_reactant_mol_bond_queries(rxn_from_generated_smarts_1)
    
    print('ReactionFromSmarts applied to rxn constructed from these smarts (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS):')
    print(generated_smarts_2)
    
    print('Reaction as loaded from smarts generated by rdkit, two roundtrips (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS -> RDKit reaction object):')
    display(rxn_from_generated_smarts_2)
    describe_reactant_mol_bond_queries(rxn_from_generated_smarts_2)        

    print('ReactionFromSmarts applied to rxn constructed from these smarts (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS):')
    print(generated_smarts_3)

    print('Reaction as loaded from smarts generated by rdkit, three roundtrips (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS -> RDKit reaction object):')
    display(rxn_from_generated_smarts_3)
    describe_reactant_mol_bond_queries(rxn_from_generated_smarts_3)        
    
    
    print()

    print('SMARTS comparison, trips 1, 2 and 3:')
    print(generated_smarts_1)
    print(generated_smarts_2)
    print(generated_smarts_3)
```

Output of the above code: 
```
=========== MDL file contents =============
$RXN
2Pyridine to 2Thiophene
SciT  ACCLDraw 012520232003

  1  1
$MOL

  ACCLDraw01252320032D

  4  3  0  0  0  0  0  0  0  0999 V2000
   10.4457   -8.2763    0.0000 A   0  0  0  0  0  0  0  0  0  2  0  0
   10.4457   -7.4453    0.0000 C   0  0  3  0  0  0  0  0  0  1  0  0
    9.7303   -7.0362    0.0000 A   0  0  0  0  0  0  0  0  0  6  0  0
   11.1602   -7.0328    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  7  0  0  1  0
  2  3  6  0  0  1  0
  2  4  1  0  0  0  0
M  END
$MOL

  ACCLDraw01252320032D

  4  3  0  0  0  0  0  0  0  0999 V2000
   15.1646   -8.2763    0.0000 A   0  0  0  0  0  0  0  0  0  2  0  0
   15.1646   -7.4453    0.0000 C   0  0  3  0  0  0  0  0  0  1  0  0
   14.4492   -7.0362    0.0000 A   0  0  0  0  0  0  0  0  0  6  0  0
   15.8791   -7.0328    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  7  0  0  1  0
  2  3  6  0  0  1  0
  2  4  1  0  0  0  0
M  END

===========================================
Reaction as loaded by rdkit from MDL file (MDL rxn -> RDKit reaction object):
```
![image](https://github.com/rdkit/rdkit/assets/106537682/c15b2c9d-fbb2-4055-a9f6-7638628a7de2)
```
Bond query descriptions of the reactant:
bond_index: 0, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783af10>
BondAnd
  DoubleOrAromaticBond 1 = val
  BondInRing 1 = val

bond_index: 1, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d87839d90>
BondAnd
  SingleOrAromaticBond 1 = val
  BondInRing 1 = val

bond_index: 2, bond object <rdkit.Chem.rdchem.Bond object at 0x2b4d8783b140>
```
![image](https://github.com/rdkit/rdkit/assets/106537682/957c0ddd-93de-4e22-a776-a7a15611a902)
```
ReactionFromSmarts applied to original rxn (MDL rxn -> RDKit reaction object -> SMARTS):
[!#1:2]=,:&@[#6:1](@[!#1:6])-[#1]>>[!#1:2]=,:&@[#6:1](@[!#1:6])-[#9]
Reaction as loaded from smarts generated by rdkit (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object):
```
![image](https://github.com/rdkit/rdkit/assets/106537682/8e674120-18c7-4352-a436-07c334773d84)
```
Bond query descriptions of the reactant:
bond_index: 0, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783b300>
BondOr
  BondOrder 2 = val
  BondAnd
    BondOrder 12 = val
    BondInRing 1 = val

bond_index: 1, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783af10>
BondInRing 1 = val

bond_index: 2, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783b300>
BondOrder 1 = val
```
![image](https://github.com/rdkit/rdkit/assets/106537682/010fc549-b935-476d-8ea6-bd1676d6a841)
```
ReactionFromSmarts applied to rxn constructed from these smarts (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS):
[!#1:2]:&@[#6:1](@[!#1:6])-[#1]>>[!#1:2]:&@[#6:1](@[!#1:6])-[#9]
Reaction as loaded from smarts generated by rdkit, two roundtrips (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS -> RDKit reaction object):
```
![image](https://github.com/rdkit/rdkit/assets/106537682/2146f0ea-bb68-4042-b164-202530a743c9)
```
Bond query descriptions of the reactant:
bond_index: 0, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783a0a0>
BondAnd
  BondOrder 12 = val
  BondInRing 1 = val

bond_index: 1, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783b8b0>
BondInRing 1 = val

bond_index: 2, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783a0a0>
BondOrder 1 = val
```
![image](https://github.com/rdkit/rdkit/assets/106537682/fea5e531-857e-4e23-9268-24293fc18d0d)

```
ReactionFromSmarts applied to rxn constructed from these smarts (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS):
[!#1:2]:&@[#6:1](@[!#1:6])-[#1]>>[!#1:2]:&@[#6:1](@[!#1:6])-[#9]
Reaction as loaded from smarts generated by rdkit, three roundtrips (MDL rxn -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS -> RDKit reaction object -> SMARTS -> RDKit reaction object):
```
![image](https://github.com/rdkit/rdkit/assets/106537682/29ac2774-3fc4-4ef6-a4fb-537954b71dd5)
```
Bond query descriptions of the reactant:
bond_index: 0, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783b8b0>
BondAnd
  BondOrder 12 = val
  BondInRing 1 = val

bond_index: 1, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783b990>
BondInRing 1 = val

bond_index: 2, bond object <rdkit.Chem.rdchem.QueryBond object at 0x2b4d8783b8b0>
BondOrder 1 = val

```
![image](https://github.com/rdkit/rdkit/assets/106537682/c920b20f-f60b-4c3c-af19-9d99022c93c5)

```
SMARTS comparison, trips 1, 2 and 3:
[!#1:2]=,:&@[#6:1](@[!#1:6])-[#1]>>[!#1:2]=,:&@[#6:1](@[!#1:6])-[#9]
[!#1:2]:&@[#6:1](@[!#1:6])-[#1]>>[!#1:2]:&@[#6:1](@[!#1:6])-[#9]
[!#1:2]:&@[#6:1](@[!#1:6])-[#1]>>[!#1:2]:&@[#6:1](@[!#1:6])-[#9]


```

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.2
 - OS: CentOS 7
 - Python version (if relevant): 3.11.4, running as a kernel of a Jupyter notebook
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
@oleksii-dukhno-bayer sorry for the super slow reply on this. I'm very behind on github issues.
Thanks for the detailed feedback!

There's a lot here, so I'm going to reply in a couple of pieces.

## On the translation of the "double or aromatic" + ring queries to SMARTS.
This seems to be a bug in the SMARTS writer. The query itself has the correct logic, as this snippet demonstrates:
```
In [8]: m = Chem.MolFromMolBlock('''
   ...:   Mrv2211 08262305392D          
   ...: 
   ...:   0  0  0     0  0            999 V3000
   ...: M  V30 BEGIN CTAB
   ...: M  V30 COUNTS 2 1 0 0 0
   ...: M  V30 BEGIN ATOM
   ...: M  V30 1 C -5.2083 3.25 0 0
   ...: M  V30 2 C -3.8747 4.02 0 0
   ...: M  V30 END ATOM
   ...: M  V30 BEGIN BOND
   ...: M  V30 1 7 1 2 TOPO=1
   ...: M  V30 END BOND
   ...: M  V30 END CTAB
   ...: M  END
   ...: ''')

In [9]: Chem.MolToSmarts(m)
Out[9]: '[#6]=,:&@[#6]'

In [10]: print(m.GetBondWithIdx(0).DescribeQuery())
BondAnd
  DoubleOrAromaticBond 1 = val
  BondInRing 1 = val

In [11]: Chem.MolFromSmiles('C=CCC').HasSubstructMatch(m)
Out[11]: False

In [12]: Chem.MolFromSmiles('C1=CCC1').HasSubstructMatch(m)
Out[12]: True
```

## On the translation of the "single or aromatic" + ring queries to SMARTS.
An unspecified bond order in SMARTS does not mean "default" bond, it's "single or aromatic" bond.
Here's what the [Daylight reference](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html) says: `A missing bond symbol is interpreted as "single or aromatic".` So the current behavior is correct. 
I see your point about distinguising between query and non-query bonds, but this isn't possible in SMARTS, where *every* bond is a query bond.
