### ISSUE TITLE
visual studio solution for CsharpWrapper

### ISSUE THREAD

**Issue by Davtomas** [rdkit/rdkit#661]
I have tried modified the CMake to turn on CSharpWrapper. Yet there is no VIsual studio project created.
Please include an example of a created VS solution or project file - at least to see how to configure the c++ and link settings for the Visual studio Csharp wrapper project file

**Comment by Davtomas** [comment]
I have followed http://ms-cheminfo.com/?q=node/24

**Comment by greglandrum** [comment]
Hi. I will take a look to see if I can find a good example or some documentation for this.

**Comment by Davtomas** [comment]
Question:1
I am using boost 1.5.5 (64bit), 
keep getting Syntax error in input(3) with boost_1_55_0\boost\smart_ptr\shared_array.hpp

**Comment by Davtomas** [comment]
Solve this problem through learning how to instal RDKit-Conda
