### ISSUE TITLE
Overlapping atoms

### ISSUE THREAD

**Issue by radchenkods** [rdkit/rdkit#6626]
**Describe the bug**
The drawing of the molecule doesn't allow to understand what is drawn. Please see an example below.

**To Reproduce**
```
from rdkit import Chem
Chem.MolFromSmiles("NC12CC(C1)(OC2C)C")
```

**Expected behavior**
![image](https://github.com/rdkit/rdkit/assets/25413723/3c57616e-c49c-4700-9d26-3cad13e88baa)

**Screenshots**
![image](https://github.com/rdkit/rdkit/assets/25413723/fa3d0b0d-c4ea-4502-9f23-cb240758f92a)

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.1
 - OS: Windows
 - Python version (if relevant): 3.11
 - Are you using conda? - Yes
 - If you are using conda, which channel did you install the rdkit from? - conda-forge

**Comment by bp-kelley** [comment]
The Coordgen depicted is slightly better, but both could use a new template for these systems:

```
from rdkit.Chem.Draw import rdDepictor
rdDepictor.SetPreferCoordGen(True)
Chem.MolFromSmiles("NC12CC(C1)(OC2C)C")
```

![image](https://github.com/rdkit/rdkit/assets/9888416/b4a66945-ce18-4b40-9b19-46790d060b88)

**Comment by radchenkods** [comment]
This depiction indeed looks better. However, it seems like there is one cycle and two wedged bonds.
As for the use of template it may be useful if one have single library with the mentioned bicyclic fragment, but what I actually have is a lot of different molecules with this fragment being just one of many. Checking each molecule for this fragment just in case may be an overkill.
