### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by jdkern11** [rdkit/rdkit#6631]
**Is your feature request related to a problem? Please describe.**
RDKit's version management makes it hard to know what changes break backwards compatibility. Currently, the versioning on PyPi uses `year.month.data`  format (e.g., [2023.3.2](https://pypi.org/project/rdkit/)).

This results in two issues:
1. If a package is using an rdkit version that clashes with an older version required by one of its dependencies, it must revert to the older version, even if backwards compatibility might not be impacted between the two and the user might prefer the new version of rdkit.
2. If a `.month` change in the current system breaks backwards compatibility, a package manager like [poetry](https://python-poetry.org/) won't automatically know that and a user may accidentally update versions.
  - As such, users are restricted to specific releases even though patches that fix bugs may be regularly released

**Describe the solution you'd like**
Please consider using [semantic versioning](https://docs.npmjs.com/about-semantic-versioning) instead. Release format would follow `major.minor.patch` conventions. Major changes would be ones that would break backwards compatibility in some way, minor changes would add new features that don't break backwards compatibility, and patches would fix bugs in a backwards compatible manner. 

For example, updating to 2.0.0 might break something in version 1.x.x , but updating to 1.2.x from from 1.1.x would not.

This would make it easier for package managers like poetry to automatically manage versions and it would actually provide information to users about what different versions are doing as opposed to the `year.month.date` format which provides no information except release date.

**Describe alternatives you've considered**
Users can just be restricted to specific releases, however, I feel this is an [antipattern](https://sourcemaking.com/antipatterns)

**Comment by greglandrum** [comment]
There's a lot of arguments out there on the web for using one versioning scheme over another and each has advantages. We won't be switching.
If you want to be very conservative about compatibility, then you can just stick to RDKit patch releases (the one where the last digit changes): 2023.0.x is a major version series, 2023.03.2 is a patch release and will only have bug fixes.
If you actually care about compatibility, you can just take a look at the release notes for a new major release (there are only two per year), which document changes that affect backwards compatibility.

**Comment by jdkern11** [comment]
I respectfully disagree with your assessment but I understand. Figured it couldn't hurt to ask. Thanks for the prompt response.
