### ISSUE TITLE
CPU Affinity Error

### ISSUE THREAD

**Issue by gcrth** [rdkit/rdkit#6635]
**Describe the bug**
After installing the newest pytorch and rdkit, the CPU affinity is set abnormally for a multiprocessing program.

**To Reproduce**
```python
import torch
from multiprocessing import Pool
import os

def process(data):
    print(f'{os.sched_getaffinity(0)}')


if __name__ == "__main__":
    pool = Pool(76)
    pool.map(process, list(range(5000)))
```
The script above will print 5000 {0}.
You do not need to import rdkit to reproduce this error, but you need to install it. You need to import pytorch.

**Expected behavior**
You can find correct behavior by deleting "import torch". I expected the script will print 5000 {0,1,2,3...}.

**Configuration (please complete the following information):**
 - RDKit version: 2022.03.2
 - PyTorch version: 2.0.1 
 - OS: CentOS8
 - Python version (if relevant): 3.10.12 

I use the following script to install the environment.
```bash
conda create -n h python=3.10 -y
conda activate h
conda install -c conda-forge rdkit -y
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia -y
```

**Comment by gcrth** [comment]
This problem may be related to rdkit because it will disappear if rdkit is not installed.

**Comment by greglandrum** [comment]
I don't believe that's possible. I guess that this is some bad interaction between pytorch and some library that is installed with the RDKit.
