### ISSUE TITLE
Incorrect most abundant isotope for Vanadium

### ISSUE THREAD

**Issue by abefrandsen** [rdkit/rdkit#6638]
The most common isotope mass returned for Vanadium is incorrect. According to [wikipedia](https://en.wikipedia.org/wiki/Isotopes_of_vanadium) and other sources, the mass of the most abundant and stable isotope of vanadium is 50.94395... (abundance > 0.99), However, rdkit returns 49.9471585. 

**To Reproduce**
```
from rdkit import Chem
tb = Chem.GetPeriodicTable()
tb.GetMostCommonIsotopeMass("V")
# returns 49.9471585
```
**Expected behavior**
Instead, it should return 50.94395... (go out to more decimals if desired).

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.2
 - If you are not using conda: how did you install the RDKit? poetry

**Additional context**
I can't for the life of me find where the actual raw data defining the masses of the atoms and their isotopes are. Would be nice to look at the raw data.

**Comment by abefrandsen** [comment]
well I found this data file https://github.com/rdkit/rdkit/blob/master/Data/rddata.sql which has the correct most abundant isotope for Vanadium. I wonder if the actual code is instead reading the data from sqlite database https://github.com/rdkit/rdkit/blob/master/Data/RDData.sqlt?

**Comment by greglandrum** [comment]
@abefrandsen the data are  here:
https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/atomic_data.cpp#L38
