### ISSUE TITLE
Crippen per-atom contributions do not sum up to descriptors

### ISSUE THREAD

**Issue by oiao** [rdkit/rdkit#6652]
**Describe the bug**
Not sure if I am missing something in the C code, but using `_CalcCrippenContribs` to calculate the atomic contributions for the Crippen logP and MR does not seem to add up to the respective molecule-level descriptor.

**To Reproduce**
```python
from rdkit import Chem
mol = Chem.MolFromSmiles('CCO')

peratom = Chem.rdMolDescriptors._CalcCrippenContribs(mol) # -> computeCrippenContribs -> getCrippenAtomContribs
logp1 = sum([i[0] for i in peratom])
mr1 = sum([i[1] for i in peratom])

logp2, mr2 = Chem.rdMolDescriptors.CalcCrippenDescriptors(mol)

assert logp1 == logp2
assert mr1 == mr2
```

**Expected behavior**
Values should be identical

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.5
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.11
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? pypi

**Comment by greglandrum** [comment]
This is expected behavior. The descriptor calculated for the entire molecule includes the contributions from the H atoms; these are not present in what you get back from `_CalcCrippenContribs()` unless you first call AddHs().

**Comment by oiao** [comment]
Great, many thanks for the clarification!
