### ISSUE TITLE
GetMorganFingerprintAsBitVect returns different submols for the same bit for two different molecules.

### ISSUE THREAD

**Issue by mjjmmj** [rdkit/rdkit#6659]
Hi!  I'm new to RDKit's  MorganFingerprintAsBitVect and I suppose that each bit corresponds to a specific submol.  
For example, let's say I have two molecules A and B. 
If I get their fingerprints using exactly the same method (i.e. radius=2, nBits=1024, useFeatures=False), it should return the same submol for the same bit(=1) in their bitinfo. 
However, I get different submols for the same bit(=1) for A and B.

[example]
m1 = Chem.MolFromSmiles('O=C1C(=C(Cl)C(=O)c2c1cccc2)Cl')
m2 = Chem.MolFromSmiles('CC(c1cc(Sc2cc(c(cc2C)O)C(C)(C)C)c(cc1O)C)(C)C')
fp1 = AllChem.GetMorganFingerprintAsBitVect(m1, radius=2, nBits=1024, useFeatures=False, bitInfo=bitinfo1))
fp2 = AllChem.GetMorganFingerprintAsBitVect(m2, radius=2, nBits=1024, useFeatures=False, bitInfo=bitinfo2))

>>> bitinfo1[1]
((8, 2), (7, 2))
>>> bitinfo2[1]
((4, 1), (6, 1))
>>>

svg1 = Draw.DrawMorganBit(m1, 1, bitinfo1, useSVG=True)
svg2 = Draw.DrawMorganBit(m2, 1, bitinfo2, useSVG=True)

![image](https://github.com/rdkit/rdkit/assets/24835935/29632e0e-303b-4ad7-8f85-aa6a497dc5a8)

-----------------------------------------

 - RDKit version: 2022.09.1
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.10.5
 - Not using conda

**Comment by bp-kelley** [comment]
It sure does.  When making a bit vector, the Morgan fingerprints invariants are "hashed" or "folded" into the vector.  It is quite common for collisions to happen at any bit-vector length.  You can think of this as an extended version of the birthday problem.  In any case, if uniqueness if your goal, using the bit vectors will disappoint.

**Comment by bp-kelley** [comment]
I'm removing the "bug" label as these collisions are expected.

**Comment by mjjmmj** [comment]
I understand. Thank you very much for your reply.
