### ISSUE TITLE
IPython integration broken with latest Jupyter

### ISSUE THREAD

**Issue by samoturk** [rdkit/rdkit#666]
```python
from rdkit.Chem.Draw import IPythonConsole
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-6fa421a38dfe> in <module>()
----> 1 from rdkit.Chem.Draw import IPythonConsole

/usr/lib/python2.7/site-packages/rdkit/Chem/Draw/IPythonConsole.py in <module>()
      7     _canUse3D=False
      8 else:
----> 9     from IPython.html.nbextensions import install_nbextension
     10     _canUse3D=True

ImportError: No module named nbextensions

```

Can be fixed by replacing relevant part with:
```python
if IPython.release.version < '0.11':
    raise ImportError('this module requires at least v0.11 of IPython')
elif IPython.release.version < '2.0':
    install_nbextension=None
    _canUse3D=False
elif (IPython.release.version >= '2.0') & (IPython.release.version < '4.0'):
    from IPython.html.nbextensions import install_nbextension
    _canUse3D=True
else:
    from notebook.nbextensions import install_nbextension
    _canUse3D=True
```

**Comment by apahl** [comment]
Hi Samo, the error seems to be Python2-specific.
For Python3 on Ubuntu15.10 and Jupyter 4.0.6, I don't get this error.
Kind regards, Axel

**Comment by samoturk** [comment]
Hi Axel, to me it doesn't look like it is python version related. The file nbextensions.py is now part of Jupyter and so it moved. I'm using ipython2 4.0.0, ipython2-notebook 4.0.6, jupyter 4.0.6 and current Git version of RDKit on Arch Linux.

**Comment by bp-kelley** [comment]
I believe that this should be updated in the next release, however I am getting a warning as opposed to an error for Anaconda Python34, OSX 10.9:

/Users/kellebr5/anaconda/envs/py34/lib/python3.4/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

This is also with Jupyter 4.0.6, perhaps you are using a more recent version?

**Comment by samoturk** [comment]
I'm also with Jupyter 4.0.6 but on python 2.7. The problem is Arch Linux related, because Arch Linux defaults to python 3.5 and Jupyter is also compiled against python 3 where you get a warning. On the other hand in python2 you get ImportError because it lacks "legacy" IPython notebook/Jupyter stuff.

**Comment by bp-kelley** [comment]
I can't duplicate the python2 ImportError, but I am testing a PR which should fix the issues.  It should be available later today.

**Comment by bp-kelley** [comment]
I have put in a pull request at #753 

This should also remove the annoying deprecated warning on older platforms.
