### ISSUE TITLE
rdMolStandardize.Normalize removes atom properties for some atoms

### ISSUE THREAD

**Issue by ljarosch** [rdkit/rdkit#6668]
**Describe the bug**
Hi, I am currently trying to prepare some input molecules using the RDKit `Normalize()` function. However, I noticed that custom atom-wise properties I set previously are removed for some substructures during the normalization.

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

mol = Chem.MolFromSmiles("CS(=O)CC")

# set "initial_index" custom property
for atom in mol.GetAtoms():
    atom.SetIntProp("initial_index", atom.GetIdx())
    
print("Before Normalize():")
for atom in mol.GetAtoms():
    print(atom.GetIntProp("initial_index"))

# only terminal carbon keeps property
print("After Normalize():")
normalized_mol = rdMolStandardize.Normalize(mol)
for atom in normalized_mol.GetAtoms():
    try:
        print(atom.GetIntProp("initial_index"))
    except KeyError:
        print("property was removed")
```
```
OUTPUT
---------------
Before Normalize():
0
1
2
3
4
After Normalize():
property was removed
property was removed
property was removed
property was removed
4
[18:00:08] Initializing Normalizer
[18:00:08] Running Normalizer
[18:00:08] Rule applied: Sulfoxide to -S+(O-)-
```
**Expected behavior**
I would have expected those properties to remain unchanged for all atoms, not just the last terminal carbon.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.1
 - OS: Ubuntu 22.04.2 LTS
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**
The reason that I need to store these "initial_index" attributes in my example is that I have a separate list of some atom-wise properties (e.g. coordinates) that correspond to the initial atom order in an un-preprocessed .mol2 file. I therefore wanted to keep track of the initial atom indexes before applying preprocessing functions (e.g. SanitizeMol, RemoveAllHs, Normalize), so that I still have the correspondence of atoms to properties even if the preprocessing removes or reorders some atoms.

If there should be no way around the behavior described above, I would also be interested in alternate solutions for that problem.

**Comment by ljarosch** [comment]
Hi, it's been a couple of weeks so I wanted to bump this issue. Would really appreciate some advice, as it's still an ongoing problem for me. Thank you! (@greglandrum )

**Comment by bp-kelley** [comment]
For this use case, you want to use NormalizeInPlace

```
# only terminal carbon keeps property
print("After Normalize():")
rdMolStandardize.NormalizeInPlace(mol)
for atom in mol.GetAtoms():
    try:
        print(atom.GetPropsAsDict())
        print(atom.GetIntProp("initial_index"))
    except KeyError:
        print("property was removed")
```

```
0
1
2
3
4
```

**Comment by bp-kelley** [comment]
Although I do consider the observed behavior a bug.

**Comment by bp-kelley** [comment]
(n.b. I'm unsure when NormalizeInPlace was added, it certainly will be in the next release)

**Comment by ljarosch** [comment]
Okay thanks, that's what I was looking for. Doesn't seem to be in the most recent RDKit version yet, but I'll keep an eye out for the next release then.

**Comment by ljarosch** [comment]
@bp-kelley Reopening this issue just for tracking, as you said the current behaviour should be considered a bug
