### ISSUE TITLE
DrawUtils module does not exist

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#6670]
I was looking at the doctests, and noticed a warning:

```
cannot import name 'DrawUtils' from 'rdkit.Chem.Draw' (/home/rodrigue/Documents/code/rdkit-install/lib/python3.8/site-packages/rdkit/Chem/Draw/__init__.py)
```

And, indeed, we are trying to import that module: from https://github.com/rdkit/rdkit/blob/891d597dc0462b66ce8e37bb5dac9f950e24ba49/rdkit/Dbase/DbReport.py#L33

But I cannot find any `DrawUtils.py` file in the sources, or a `DrawUtils` module being built in the wrappers...

**Comment by cdvonbargen** [comment]
I believe DbReport.py is gone: https://github.com/rdkit/rdkit/tree/master/rdkit/Dbase

**Comment by rachelnwalker** [comment]
Since that module is removed and DrawUtils isn't used anywhere else in RDKit, I'm closing this issue
