### ISSUE TITLE
Suspicious value for atom pair code calculation

### ISSUE THREAD

**Issue by QJ-Chen** [rdkit/rdkit#6679]
**Describe the bug**
In `Code/GraphMol/Fingerprints/FingerprintUtil.h`,  atomNumberTypes is used for calculating atom pair code.
```cpp
const unsigned int atomNumberTypes[1 << numTypeBits] = {
    5, 6, 7, 8, 9, 14, 15, 16, 17, 33, 34, 35, 51, 52, 43};
```
This list should be sorted in ascending order. The '43'(Tc) is nerver used.  As iodine(I, atomic number 53) is more common, maybe you meant 53?

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

**Expected behavior**
```python
from rdkit import Chem
mol = Chem.MolFromSmiles('CI')
atom = mol.GetAtomWithIdx(1) # I
print(bin(Chem.AllChem.GetAtomPairAtomCode(atom))) 

OUTPUT: 
'0b111100001'   # '0b111110001'(supposed)
```

**Comment by greglandrum** [comment]
Yep, that looks like a typo.

**Comment by j-adamczyk** [comment]
@greglandrum this is definitely a bug and should not be closed. Iodine would be correct according to the Atom Pair paper
