### ISSUE TITLE
Chem.ResonanceMolSupplier freezes/hangs

### ISSUE THREAD

**Issue by simonmb** [rdkit/rdkit#6704]
-----------------------------------------

**Describe the bug**
While running:
```python
from rdkit import Chem
mol = Chem.MolFromSmiles('COc1cc(-c2ccc(-[n+]3nc(-c4ccc([N+](=O)[O-])cc4)nn3-c3ccc([N+](=O)[O-])cc3)c(OC)c2)ccc1-[n+]1nc(-c2ccc([N+](=O)[O-])cc2)nn1-c1ccc([N+](=O)[O-])cc1')
resonance_mols = list(Chem.ResonanceMolSupplier(mol)) 
```
The ResonanceMolSupplier freezes.

**To Reproduce**
run the code above.

**Expected behavior**
Not freeze but return.

**Configuration (please complete the following information):**
 - RDKit version: 2023.3.1
 - OS: Windows 10
 - Python version (if relevant): 3.11
 - Are you using conda: yes
 - If you are using conda, which channel did you install the rdkit from? rdkit 2023.3.1 pypi_0 pypi

I don't know if this is related to: #4884, #2597, #5406

**Comment by simonmb** [comment]
These also lead to the ResonanceMolSupplier freezing:

COc1cc(-c2ccc(-n3nc(-c4ccc(C(N)=S)cc4)n[n+]3-c3ccc([N+](=O)[O-])cc3)c(OC)c2)ccc1-n1nc(-c2ccc(C(N)=S)cc2)n[n+]1-c1ccc([N+](=O)[O-])cc1

COc1cc(-c2ccc(-[n+]3nc(-c4ccccc4)nn3-c3ccc([N+](=O)[O-])cc3)c(OC)c2)ccc1-[n+]1nc(-c2ccccc2)nn1-c1ccc([N+](=O)[O-])cc1

**Comment by simonmb** [comment]
I know there might be similarities in the structure, it would already help what in the structure is causing it to freeze. As then I can exclude these structures until this gets fixed.

**Comment by ptosco** [comment]
@simonmb I will fix this before next release.

**Comment by simonmb** [comment]
Hi @ptosco, thank you, would you be able to tell me if there is a structure or property I can filter by to avoid the freezing? I have a huge amount of structures I need to work through and the freezing always sets me back a couple of hours.

**Comment by ptosco** [comment]
Hi, unfortunately I have no time to investigate this bug until after 20th September, sorry about that.

**Comment by simonmb** [comment]
I don't know if it helps, but I found a workaround hat works for me.

Trying around a created a derived class like so:

```python
from rdkit.Chem.rdchem import ResonanceMolSupplierCallback

class EmptyResonanceMolSupplierCallback(ResonanceMolSupplierCallback):
    def __call__(self):
        pass
```

and passed it to the ResonanceMolSupplier like so:

```python
mol = Chem.MolFromSmiles('COc1cc(-c2ccc(-[n+]3nc(-c4ccc([N+](=O)[O-])cc4)nn3-c3ccc([N+](=O)[O-])cc3)c(OC)c2)ccc1-[n+]1nc(-c2ccc([N+](=O)[O-])cc2)nn1-c1ccc([N+](=O)[O-])cc1')
rms = Chem.ResonanceMolSupplier(mol)
rms.SetProgressCallback(EmptyResonanceMolSupplierCallback())
resonance_mols = list(rms)
```
I don' know if it is giving me the usual results, but it is not freezing.

**Although I found this workaround, I would still however consider this a bug.**

**Comment by simonmb** [comment]
On a sidenote, I don't understand the use of ResonanceMolSupplierCallback, I tested it on a few molecules and it seems if the molecule only has one resonance structure it never gets called.

**Comment by simonmb** [comment]
Has this been fixed?

**Comment by wenyan4work** [comment]
This is still an issue in 2023.9.4

**Comment by simonmb** [comment]
@ptosco was this fixed?

**Comment by ptosco** [comment]
@simonmb No, it hasn’t. Sorry - I have not forgotten but finding the time is the issue.

**Comment by AlexiaJM** [comment]
Bump, I also wanted to use it, but it freezes.

**Comment by simonmb** [comment]
@ptosco this was closed by the bot as not planned? I am sure the bug is not planned, But it is still a bug.
