### ISSUE TITLE
 Range Error

### ISSUE THREAD

**Issue by glauco-endrigo** [rdkit/rdkit#6708]
-----------------------------------------
Hi, the function molecule.GetAtomWithIdx() from rdkit breaks, with certain numbers. It appears to be  random. Can someone help me please? 
Code: 
molecule.GetAtomWithIdx(12)

Error: 
[08:19:18] 

****
Range Error
idx
Violation occurred on line 206 in file /project/build/temp.linux-x86_64-cpython-39/rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: 12 < 12
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [57], in <cell line: 1>()
----> 1 molecule.GetAtomWithIdx(12)

RuntimeError: Range Error
	idx
	Violation occurred on line 206 in file Code/GraphMol/ROMol.cpp
	Failed Expression: 12 < 12
	RDKIT: 2022.03.1
	BOOST: 1_75

**Comment by DavidACosgrove** [comment]
The atoms are indexed from 0 to the number of atoms in the molecule, excluding implicit H atoms. I assume the molecule you are using has 12 atoms, based on the error message, and therefore valid indices are 0 to 11. But to be really sure you would need to provide the molecule you are looking at and some small piece of code demonstrating what you are trying to do.

**Comment by glauco-endrigo** [comment]
I just shared the txt of the pdb. For the ligand, I have [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] indexes, that i want to get info from. 
**here is the code:**


from rdkit import Chem

# Load the PDB or PDBQT file
with open(ligand_path, "r") as pdb_file:
    pdb_data = pdb_file.read()

# Assuming you have the indices of the ligand atoms you're interested in
atom_indices = ids_3gv9_pose_1  # Example atom indices

molecule = Chem.MolFromPDBFile(ligand_path)

if molecule is not None:
    for atom_index in atom_indices:
        atom = molecule.GetAtomWithIdx(atom_index)

        # Extract atom properties
        atom_name = atom.GetSymbol()
        atom_mass = atom.GetMass()
        atom_charge = atom.GetFormalCharge()

        # Print or use the properties as needed
        print(f"Atom {atom_index}: Name={atom_name}, Mass={atom_mass}, Charge={atom_charge}")
------------------------------------------------------------------------------------------
**And here is the error:**                                                                                                                  

 Atom 1: Name=C, Mass=12.011, Charge=0
Atom 2: Name=C, Mass=12.011, Charge=0
Atom 3: Name=S, Mass=32.067, Charge=0
Atom 4: Name=C, Mass=12.011, Charge=0
Atom 5: Name=N, Mass=14.007, Charge=0
Atom 6: Name=C, Mass=12.011, Charge=0
Atom 7: Name=O, Mass=15.999, Charge=0
Atom 8: Name=C, Mass=12.011, Charge=0
Atom 9: Name=C, Mass=12.011, Charge=0
Atom 10: Name=O, Mass=15.999, Charge=0
Atom 11: Name=O, Mass=15.999, Charge=0
[09:30:30] 

****
Range Error
idx
Violation occurred on line 206 in file /project/build/temp.linux-x86_64-cpython-39/rdkit/Code/GraphMol/ROMol.cpp
Failed Expression: 12 < 12
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [39], in <cell line: 12>()
     12 if molecule is not None:
     13     for atom_index in atom_indices:
---> 14         atom = molecule.GetAtomWithIdx(atom_index)
     16         # Extract atom properties
     17         atom_name = atom.GetSymbol()

RuntimeError: Range Error
	idx
	Violation occurred on line 206 in file Code/GraphMol/ROMol.cpp
	Failed Expression: 12 < 12
	RDKIT: 2022.03.1
	BOOST: 1_75

[pose_1 (cópia).txt](https://github.com/rdkit/rdkit/files/12565748/pose_1.copia.txt)

**Comment by ptosco** [comment]
Change
```
molecule = Chem.MolFromPDBFile(ligand_path)
```
Into
```
molecule = Chem.MolFromPDBFile(ligand_path, removeHs=False)
```
 `removeHs` defaults to `True`.

**Comment by glauco-endrigo** [comment]
Thank you! I did the two alterations as suggested:

`molecule = Chem.MolFromPDBFile(ligand_path, removeHs=False)`
and 
`atom = molecule.GetAtomWithIdx(atom_index-1)`
