### ISSUE TITLE
CalcNumAromaticRings calculates no aromatic rings, however Draw indicates presence of aromatic rings.

### ISSUE THREAD

**Issue by syedzayyan** [rdkit/rdkit#6724]
**Describe the bug**
CalcNumAromaticRings calculates no aromatic rings, however Draw indicates presence of aromatic rings.

**To Reproduce**
```
mol1 = Chem.MolFromSmiles('CC[C@H](C)C(=O)O[C@H]1C[C@@H](C)C=C2C=C[C@H](C)[C@H](CC[C@@H]3C[C@@H](O)CC(=O)O3)[C@H]21')
mol2 = Chem.MolFromSmiles('C=C(CCC)C1=CC=C(CC2CCCCCCC2)C2C=C(C3=CC=CC3)C=C12')

print(Chem.rdMolDescriptors.CalcNumAromaticRings(mol1))
print(Chem.rdMolDescriptors.CalcNumAromaticRings(mol2))

display(mol1)
display(mol2)
```

**Expected behavior**
I expected ring counts to be more than 1

**Screenshots**

<img width="392" alt="Screenshot 2023-09-14 at 14 45 39" src="https://github.com/rdkit/rdkit/assets/44922710/95886fa9-a1d5-41ff-adcf-b89aab288712">

**Configuration (please complete the following information):**
 - RDKit version: '2023.03.3'
 - OS: Mac OS
 - Python version (if relevant):
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit? pip

**Additional context**

**Comment by DavidACosgrove** [comment]
As far as I can see from the pictures, neither of those molecules contain an aromatic ring. Which rings do you think are?

**Comment by syedzayyan** [comment]
<img width="259" alt="Screenshot 2023-09-15 at 10 10 12" src="https://github.com/rdkit/rdkit/assets/44922710/c3186277-6d57-481b-92fa-de6f5affd10b">

I thought these might be. I mean they looked like aromatic rings. The double bonds looked like aromatic rings. :(
