### ISSUE TITLE
tostring() and fromstring() deprecated in Pillow 3.0

### ISSUE THREAD

**Issue by ChemWeezer** [rdkit/rdkit#674]
2D molecule drawing is using tostring() and fromstring() for Pillow images. These functions are deprecated in Pillow 3.0. Using tobytes() and frombytes() is now required.

**Comment by rvianello** [comment]
I thought this was fixed by #644, are you still experiencing issues with the current tip of the master branch 26622c9 or with the current release (Release_2015_09_2)?

**Comment by ChemWeezer** [comment]
Yep, this was fixed in the current release. I was still using 2015_09_1.
