### ISSUE TITLE
rdMolDescriptors.CalcNumAtomStereoCenters fails on Sanitized Molecule

### ISSUE THREAD

**Issue by C-Townsend** [rdkit/rdkit#6757]
**Describe the bug**
`rdMolDescriptors.CalcNumAtomStereoCenters` fails to find stereo centers if a molecule is sanitized (twice).
I had assumed this was deuterium-related, but it appears to affect other stereo centers as well (see https://github.com/rdkit/rdkit/discussions/6657).

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem import rdMolDescriptors

smi = "[2H][C@@](C)(N)C(=O)O"
mol1 = Chem.MolFromSmiles(smi)
cip_count1 = sum([atom.HasProp("_CIPCode") for atom in mol1.GetAtoms()])
stereocenters1 = rdMolDescriptors.CalcNumAtomStereoCenters(mol1)


mol2 = Chem.Mol(mol1)
Chem.SanitizeMol(mol2)
cip_count2 = sum([atom.HasProp("_CIPCode") for atom in mol2.GetAtoms()])
try:
    stereocenters2 = rdMolDescriptors.CalcNumAtomStereoCenters(mol2)
except: # ValueError: numStereoCenters called without stereo being assigned
    stereocenters2 = 0

assert cip_count1 == cip_count2
assert stereocenters1 == stereocenters2 # Fails. 1 != 0
```

**Expected behavior**
One stereo center should be detected for both molecules. 
The properties  `_CIPCode` and `_ChiralityPossible` are still correct so I've been counting atom CIPCodes as a workaround.

**Configuration:**
 - RDKit version: 2022.9.5 (linked discussion is on 2023.03.3)
 - OS: Ubuntu 22.04.3
 - Python version: 3.9
 - Are you using conda? No
 - How did you install the RDKit? rdkit-pypi via Poetry

**Comment by bp-kelley** [comment]
Here is a simpler trigger for this issue:

```
mol2 = Chem.Mol(mol1)
Chem.SanitizeMol(mol2, Chem.SANITIZE_CLEANUPCHIRALITY)
cip_count2 = sum([atom.HasProp("_CIPCode") for atom in mol2.GetAtoms()])
stereocenters2 = rdMolDescriptors.CalcNumAtomStereoCenters(mol2)
```

**Comment by hjuinj** [comment]
I stumbled across this issue today too, any update on this?

**Comment by greglandrum** [comment]
Sorry, this one got lost. 
Should be fixed for the next patch release.

**Comment by hjuinj** [comment]
Thank so much Greg!
