### ISSUE TITLE
OH labels incorrectly handled in rdDrawMol2D

### ISSUE THREAD

**Issue by ldomic** [rdkit/rdkit#676]
Hi,

I have noticed an issue with handling of OH and possibly other labels in the rdDrawMol2D class - they show H as being closer to carbon than O. 

The code was taken  from the blog: RDKIT: New Drawing Code and I am using 2015.03.1 version. 

```
from rdkit.Chem import rdDepictor
from rdkit.Chem.Draw import rdMolDraw2D
def moltosvg(mol,molSize=(450,150),kekulize=True):
    mc = Chem.Mol(mol.ToBinary())
    if kekulize:
        try:
            Chem.Kekulize(mc)
        except:
            mc = Chem.Mol(mol.ToBinary())
    if not mc.GetNumConformers():
        rdDepictor.Compute2DCoords(mc)
    drawer = rdMolDraw2D.MolDraw2DSVG(molSize[0],molSize[1])
    drawer.DrawMolecule(mc)
    drawer.FinishDrawing()
    svg = drawer.GetDrawingText()
    # It seems that the svg renderer used doesn't quite hit the spec.
    # Here are some fixes to make it work in the notebook, although I think
    # the underlying issue needs to be resolved at the generation step
    return svg.replace('svg:','')

n = Chem.MolFromSmiles('CC1OC(OC2C(CO)OC(OC3C(CO)OC(O)C(O)C3O)C(O)C2O)C(O)C(O)C1NC1C=C(CO)C(O)C(O)C1O')

SVG(moltosvg(n))
```

<img width="514" alt="wrong_oh_labels" src="https://cloud.githubusercontent.com/assets/14980883/11335301/1e1fdf0a-91d3-11e5-9b27-1bd3b19b6a8f.png">

**Comment by greglandrum** [comment]
Yep, those look "less than optimal". I'll put it on the list of things to look into/fix for next time I'm working on the rendering code.

**Comment by greglandrum** [comment]
I believe that this has been fixed. Here's the current rendering of that molecule:
![image](https://cloud.githubusercontent.com/assets/540511/23788116/75eab37e-0575-11e7-976a-125d1397119f.png)

**Comment by greglandrum** [comment]
I believe that this has been fixed. Here's the current rendering of that molecule:
![image](https://cloud.githubusercontent.com/assets/540511/23788116/75eab37e-0575-11e7-976a-125d1397119f.png)

**Comment by greglandrum** [comment]
This looks resolved. If you disagree please reopen
