### ISSUE TITLE
PicklingError which pickling RDKit descriptors

### ISSUE THREAD

**Issue by arunppsg** [rdkit/rdkit#6776]
**Describe the bug**
Pickling of rdkit.Chem.Descriptors in python throws PickingError.

**To Reproduce**
```py
from rdkit.Chem import Descriptors

for name, func in Descriptors.descList:
    if name == 'BCUT2D_CHGHI':
        a = pickle.dumps(func)
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
Cell In[6], line 5
      3 for name, func in Descriptors.descList:
      4     if name == 'BCUT2D_CHGHI':
----> 5         a = pickle.dumps(func)

PicklingError: Can't pickle <function BCUT2D_CHGHI at 0x11411d5e0>: attribute lookup BCUT2D_CHGHI on rdkit.Chem.ChemUtils.DescriptorUtilities failed
```

**Expected behavior**
`a` should contain the pickled object.

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.3
 - Python version (if relevant): 3.9
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? Installed via pip as `pip install rdkit`.

**Additional context**

**Comment by bp-kelley** [comment]
We can probably resolve this, but I'm curious what use-case you're trying to solve?  These pickles most likely won't be valid between rdkit versions.

For reference, some functions are thinly wrapped C++ functions and these can't be pickled directly.

**Comment by arunppsg** [comment]
I have a large csv file containing smiles strings and I need to apply the rdkit descriptor function on it. The approach which I am taking is split the csv into multiple subsets, start multiple processes which run on each csv-subset and then aggregate the results, something like this:
```py
import multiprocessing as mp

import rdkit
from rdkit.Chem import Descriptors

def apply_func(i, func):
    df = pd.read_csv('/path to a/subset of/large file')
    for idx, row in df.iterrows():
        smiles = row['smiles']
        result = func(mol)
    # aggregate result and return aggregated resulted here 
    return
    
if __name__ == '__main__':
    for name, func in Descriptors.descList:
        if name == 'BCUT2D_CHGHI':
            f = func
            break

    nproc = 8
    processes = []
    for i in range(nproc):
        p = mp.Process(target=apply_func, args=(i, f, ))
        processes.append(p)
        p.start()

    for p in processes:
        p.join()
```

**Comment by bp-kelley** [comment]
I think it's better to cache the funcnames than pickle the functions themselves,

i.e.
```
descDict={name:func for name,func in Descriptors.descList}
```

example (using NCI_regress.Lip.csv which has a SMILES column)

```
import multiprocessing as mp
import pandas as pd
import rdkit

from rdkit import Chem
from rdkit.Chem import Descriptors


def apply_func(i, funcname,
               descDict={name:func for name,func in Descriptors.descList}):
    func = descDict[funcname]
    df = pd.read_csv("NCI_regress.Lip.csv")
    for idx, row in df.iterrows():
        smiles = row['SMILES']
        mol = Chem.MolFromSmiles(smiles)
        if not mol:
            continue
        result = func(Chem.MolFromSmiles(smiles))
    # aggregate result and return aggregated resulted here 
    return
    
if __name__ == '__main__':
    nproc = 8
    processes = []
    f = "BCUT2D_CHGHI"
    for i in range(nproc):
        p = mp.Process(target=apply_func, args=(i, f, ))
        processes.append(p)
        p.start()

    for p in processes:
        p.join()
```

**Comment by arunppsg** [comment]
I agree, that's the work around which I used.

**Comment by bp-kelley** [comment]
@greglandrum should we support:

```
pool = multiprocessing.Pool()
results = pool.map(func, mols)
```

for the descriptor functions?  Quite a few aren't picklable (all lambda functions for instance)

My gut says "yes" but this might be a bit of code to refactor.

**Comment by greglandrum** [comment]
This doesn't feel like a priority to me. As you point out: it's perfectly possible to just use the function names.
