### ISSUE TITLE
Is there interest for vcpkg support?

### ISSUE THREAD

**Issue by SPKorhonen** [rdkit/rdkit#6781]
I have modified my custom RDKit source to support building using vcpkg which simplifies Windows builds dramatically,

Getting vcpkg working requires some small changes to CMakeLists.txt here and there but overall the modifications are minor and seem not to interfere with builds without vcpkg.

So @greglandrum  would there be interest for a PR?

**Comment by greglandrum** [comment]
@SPKorhonen : Definitely. This has been on my ToDo list for quite a while now.

**Comment by SPKorhonen** [comment]
Good to hear. Please find the relevant modifications in PR #6794.

**Comment by j-horner-c4x** [comment]
I raised an issue about this on vcpkg: https://github.com/microsoft/vcpkg/issues/30007 but there wasn't much interest and I didn't have time to look into it myself.

I think this would be very useful if it could be done.
