### ISSUE TITLE
Explicit valence for atom

### ISSUE THREAD

**Issue by ivannnnnnnnnn** [rdkit/rdkit#6795]
Hello. I get error with next text when try to create molecule from smiles ```FCl(F)F```:

```Explicit valence for atom # 1 Cl, 3, is greater than permitted```.

```
mol = Chem.MolFromSmiles('FCl(F)F')
```

In this case 3 is valid valence for Cl

**Comment by wopozka** [comment]
The same applies for bromine compound, iodine is ok.
