### ISSUE TITLE
rdMolAlign.GetBestRMS returns error

### ISSUE THREAD

**Issue by LiuCMU** [rdkit/rdkit#6826]
**Describe the bug**
rdMolAlign.GetBestRMS returns error when the Hs are removed in the reference and target molecules.

**To Reproduce**
The `13889b_debug.sdf` file is attached. It contains the information for 2 conformers of the same molecule. The extension `sdf` was changed to `txt` for upload.
[13889b_debug.txt](https://github.com/rdkit/rdkit/files/13061521/13889b_debug.txt)

```
from rdkit import Chem
from rdkit.Chem import rdMolAlign


mols = Chem.SDMolSupplier('13889b_debug.sdf', removeHs=False)
rms = rdMolAlign.GetBestRMS(Chem.RemoveHs(mols[0]), Chem.RemoveHs(mols[1]))
print(rms)
```
Which gives the following error message:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[/Users/liu5/Desktop/tmpry/random.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/liu5/Desktop/tmpry/random.ipynb) Cell 2 line 6
      [2](vscode-notebook-cell:/Users/liu5/Desktop/tmpry/random.ipynb#X26sZmlsZQ%3D%3D?line=1) from rdkit.Chem import rdMolAlign
      [5](vscode-notebook-cell:/Users/liu5/Desktop/tmpry/random.ipynb#X26sZmlsZQ%3D%3D?line=4) mols = Chem.SDMolSupplier('13889b_debug.sdf', removeHs=False)
----> [6](vscode-notebook-cell:/Users/liu5/Desktop/tmpry/random.ipynb#X26sZmlsZQ%3D%3D?line=5) rms = rdMolAlign.GetBestRMS(Chem.RemoveHs(mols[0]), Chem.RemoveHs(mols[1]))
      [7](vscode-notebook-cell:/Users/liu5/Desktop/tmpry/random.ipynb#X26sZmlsZQ%3D%3D?line=6) print(rms)

RuntimeError: No sub-structure match found between the reference and probe mol
```
**Expected behavior**
The function should return a RMSD value.

**Screenshots**
Note that the following methods worked, so this looks like an issue with the code rather than the conformers.
```
# Method1: do not remove the Hs, calculating RMSD with Hs
mols = Chem.SDMolSupplier('13889b_debug.sdf', removeHs=False)
rms = rdMolAlign.GetBestRMS(mols[0], mols[1])
print(rms)  # 1.02

# Method 2: remove Hs when reading the SDF file
mols = Chem.SDMolSupplier('13889b_debug.sdf', removeHs=True)
rms = rdMolAlign.GetBestRMS(mols[0], mols[1])
print(rms)  # 0.63
```

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.3
 - OS: Ubuntu 20.04.6 LTS
 - Python version (if relevant): 3.9.17
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Additional context**
I need to keep the Hs when reading the SDF file because these structures will be used for DFT calculations. So although I know that Method1 and Method2 work, it will be highly appreciated if you help me to make the original method work, too. Thank you very much!

**Comment by LiuCMU** [comment]
The "bug" label was attached automatically when I submited an issue, though I did not intend to do so. I'm sorry if that label caused unnecessary pressure...

**Comment by greglandrum** [comment]
@LiuCMU What's happening here is that `RemoveHs()` does not, by default, remove certain types of H. One of the types which isn't removed is Hs which define double bond stereochemistry. That's what's happening in your case:
```
In [4]: suppl = Chem.SDMolSupplier('/home/glandrum/Downloads/13889b_debug.txt',removeHs=False)

In [5]: ms = [x for x in suppl]

In [7]: ms_noH = [Chem.RemoveHs(x) for x in ms]

In [11]: Chem.MolToSmiles(ms_noH[0])
Out[11]: '[H]/N=C(C#CCC)\\C(CC)=N/[H]'

In [12]: Chem.MolToSmiles(ms_noH[1])
Out[12]: '[H]/N=C(/CC)C(=N)C#CCC'
```
You can force the removal of all Hs by calling `RemoveAllHs()`, and this will allow `GetBestRMS()` to work:
```
In [15]: ms_noH = [Chem.RemoveAllHs(x) for x in ms]

In [16]: rdMolAlign.GetBestRMS(ms_noH[0],ms_noH[1])
Out[16]: 0.6254844525669202
```

**Comment by greglandrum** [comment]
> The "bug" label was attached automatically when I submited an issue, though I did not intend to do so. I'm sorry if that label caused unnecessary pressure...

No worries! This does look like a bug. :-)

**Comment by LiuCMU** [comment]
Hello @greglandrum, thank you so much, this solved my puzzle! Thanks for the great work, and have a wonderful week!
