### ISSUE TITLE
MurckoScaffold.MakeScaffoldGeneric() has issues with isotopes

### ISSUE THREAD

**Issue by dehaenw** [rdkit/rdkit#6836]
**Describe the bug**
When using MakeScaffoldGeneric(), if the input molecule has explicit isotopes, this is retained in the generic scaffold. Even when the atom is not carbon. This is a less obscure problem than it seems, because e.g. ChEMBL has dozens of molecules in there with explicit isotopes (which is how I discovered this) within the CSK.

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold

smi1="[14CH2]1CCC1"
smi2="[15NH]1CCC1"
smi3="[235U]1CCC1"
mols=[Chem.MolFromSmiles(smi) for smi in [smi1,smi2,smi3]]

for m in mols:
    csk=MurckoScaffold.MakeScaffoldGeneric(MurckoScaffold.GetScaffoldForMol(m))
    print(Chem.MolToSmiles(csk))
```

this outputs:

```
C1C[14CH2]C1
C1C[15CH2]C1
C1C[235CH2]C1
```

**Expected behavior**
No isotope flags. Expected output:
```
C1CCC1
C1CCC1
C1CCC1
```

**Configuration (please complete the following information):**
 - RDKit version:  2023.03.3
 - OS: Ubuntu 20.04
 - Python version (if relevant): not relevant
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit? n/a

**Additional context**
The fix is probably to add `atom.SetIsotope(0)` after line 40 in the murcko script. https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/Scaffolds/MurckoScaffold.py#L40
Just posting the issue here to make sure this makes sense before doing a pull request.

**Comment by greglandrum** [comment]
Agreed that this looks like a bug. 
This is something which should be fixed at the C++ level, not in Python. I'm happy to do that if you aren't a c++ developer.
