### ISSUE TITLE
ImportError: cannot import name 'StructChecker' from 'rdkit.Chem'

### ISSUE THREAD

**Issue by urekam712** [rdkit/rdkit#6837]
** The bug**
ImportError: cannot import name 'StructChecker' from 'rdkit.Chem'

**To Reproduce**
Use the import " from rdkit.Chem import rdStructChecker" in any python IDE
 
 
 Is there any alternate for the structchecker in new versions?

**Comment by happyday123123** [comment]
The StructChecker module was removed from RDKit starting from version 2021.03.1, and it is no longer available in the latest versions. Therefore, if you are using a newer version of RDKit, you will encounter this error when trying to import StructChecker.

**Comment by greglandrum** [comment]
The replacement for the StructChecker can be found in `rdkit.Chem.MolStandardize.rdMolStandardize`
(Note: be sure to look at the stuff in `rdMolStandardize`, the python code in `rdkit.Chem.MolStandardize` is deprecated)

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
