### ISSUE TITLE
SMARTS reaction triggers invariant violation on chiral compounds

### ISSUE THREAD

**Issue by JamesJeffryes** [rdkit/rdkit#685]
I've run into a curious problem when using certain SMARTS patterns to run reactions on compounds. Certain compounds with chiral flags trigger an invariant violation when run but the same compound with unspecified stereochemistry reacts as expected.  (I'm aware that explicit enumeration of hydrogen in smarts reactions is a bit odd; these reactions are ported from a legacy system)

Below I've included two examples of this behavior:

    rxn = AllChem.ReactionFromSmarts('[#1;D1R0:5][#6;H1D4:4]1[#6;H1D4:6][#6;H1D4:7]([#8;H1D2R0:8])[#6;H1D4:9][#8;H0D2:1][#6;H1D4:2]1[#8;H1D2R0:3]>>[*:3]-[*:2](-[*:5])-[*:4]-1-[*:1]-[*:9]-[*:7](-[*:8])-[*:6]-1')
    mol = AllChem.MolFromSmiles('OC[C@H]1OC(O)[C@H](O)[C@H](O)[C@@H]1O')
    mol = AllChem.AddHs(mol)
    rxn.RunReactants([mol])
    [12:51:43] 
    
    ****
    Invariant Violation
    expected reactant bond not found
    Violation occurred on line 533 in file /tmp/rdkit20150904-11712-k5lp6f/rdkit-Release_2015_03_1/Code/GraphMol/ChemReactions/ReactionRunner.cpp
    Failed Expression: rBond
    ****
    
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    RuntimeError: Invariant Violation
    mol = AllChem.MolFromSmiles('OCC1OC(O)C(O)C(O)C1O')
    mol = AllChem.AddHs(mol)
    rxn.RunReactants([mol])
    ((<rdkit.Chem.rdchem.Mol object at 0x107882278>,),)

Case 2:

    rxn2 = AllChem.ReactionFromSmarts('[#1;D1R0:4][#8;H1D2R0:3][#6;H0D3R0:2](=[#8;H0D1R0:5])[#6;D4;H1,H0,H2:1]([#6:7])[#6,#1D1AR0,ClH0D1AR0,FH0D1AR0,BrH0D1AR0:6]>>[*:3]=[*:2]=[*:5].[*:4]-[*:1](-[*:6])-[*:7]')
    mol2 = AllChem.MolFromSmiles('CSCC[C@@H](N)C(=O)O')
    mol2 = AllChem.AddHs(mol2)
    rxn2.RunReactants([mol2])
    [13:06:37] 
    
    ****
    Invariant Violation
    expected reactant bond not found
    Violation occurred on line 533 in file /tmp/rdkit20150904-11712-k5lp6f/rdkit-Release_2015_03_1/Code/GraphMol/ChemReactions/ReactionRunner.cpp
    Failed Expression: rBond
    ****
    
    Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
    RuntimeError: Invariant Violation
    mol2 = AllChem.MolFromSmiles('CSCCC(N)C(=O)O')
    mol2 = AllChem.AddHs(mol2)
    rxn2.RunReactants([mol2])
    ((<rdkit.Chem.rdchem.Mol object at 0x1078822e8>, <rdkit.Chem.rdchem.Mol object at 0x1078823c8>),)

**Comment by greglandrum** [comment]
I can reproduce the problem and will look into it.

**Comment by greglandrum** [comment]
Ok, the problem is not due to chirality, that's just what triggered it.

The problem is due to a bond to a bond being added to an atom in the product template which happens to be chiral in the actual reactant.

Here's a simpler reproducible:
```python
In [2]: rxn2 = AllChem.ReactionFromSmarts('[C:1][C:2][C:3]([O:4])([N:5])[Cl:6]>>[Cl:6].[C:2][C:3]([O:4])([N:5])[C:1]')

In [4]: rxn2.RunReactants((AllChem.MolFromSmiles('CCC(O)(N)Cl'),))
Out[4]: 
((<rdkit.Chem.rdchem.Mol at 0x7f00b605e978>,
  <rdkit.Chem.rdchem.Mol at 0x7f00b605ea28>),)

In [5]: rxn2.RunReactants((AllChem.MolFromSmiles('CC[C@](O)(N)Cl'),))
[17:09:38] 

****
Invariant Violation
expected reactant bond not found
Violation occurred on line 587 in file /scratch/RDKit_git/Code/GraphMol/ChemReactions/ReactionRunner.cpp
Failed Expression: rBond
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-515c9eb8d8e3> in <module>()
----> 1 rxn2.RunReactants((AllChem.MolFromSmiles('CC[C@](O)(N)Cl'),))

RuntimeError: Invariant Violation
	expected reactant bond not found
	Violation occurred on line 587 in file Code/GraphMol/ChemReactions/ReactionRunner.cpp
	Failed Expression: rBond
	RDKIT: 2016.03.1.dev1
	BOOST: 1_58
```
