### ISSUE TITLE
partially specified chiral substructure queries don't work properly

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#688]
```python
> smi = "N[C@]1(Cl)CCCO1"
> m2 = Chem.MolFromSmiles(smi)
> m2.GetSubstructMatches(Chem.MolFromSmarts("[N][C@]1CCCO1"),useChirality=True)
()
```

The search works properly when a dummy atom is specified in the chiral query
```python
> m2.GetSubstructMatches(Chem.MolFromSmarts("[N][C@]1(*)CCCO1"),useChirality=True)
((0, 1, 2, 3, 4, 5, 6),)
```

As previously discussed, this is the offending line of code:

 https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Substruct/SubstructMatch.cpp#L79

**Comment by bp-kelley** [comment]
@greg I think this has been fixed, is this true?  I can't find the pull request.

**Comment by greglandrum** [comment]
@bp-kelley Looks like it's on this as-yet unsubmitted branch:
https://github.com/rdkit/rdkit/compare/fix/github688

I believe the problem is actually fixed (and that the tests are reasonably complete).
I'll submit the PR now.

**Comment by greglandrum** [comment]
tooooo many branches. :-)

**Comment by bp-kelley** [comment]
I have been trying to delete the ones that get merged.  Here are some useful commands regarding this:

```
git branch --merged master lists branches merged into master

git branch --merged lists branches merged into HEAD (i.e. tip of current branch)

git branch --no-merged lists branches that have not been merged
```

By default this applies to only the local branches. The -a flag will show both local and remote branches, and the -r flag shows only the remote branches.
