### ISSUE TITLE
MMP FragmentMol returns empty cores

### ISSUE THREAD

**Issue by jasondbiggs** [rdkit/rdkit#6899]
Is it expected for the MMPA code to return pairs with the core set to None?

```
from rdkit.Chem import MolFromSmiles
from rdkit.Chem import rdMMPA
mol = MolFromSmiles("O=C1NC(=O)[C@](N1)(c1ccc(cc1)O[C@@H]1O[C@H](C(=O)O)[C@H]([C@@H]([C@H]1O)O)O)c1ccccc1")
frag1 = rdMMPA.FragmentMol(mol)
print(frag1[0][0] == None)  # prints True
print(frag1[0][1] == None)  # prints False
```

**Comment by goldmannd** [comment]
rdMMPA.FragmentMol(m) returns a list of tuples with the side chains / fragments. With the single cut, you do not have the definition of the core in the current implementation of the MMP algorithm in RDKit.
