### ISSUE TITLE
Obtaining descriptors via Descriptors.descList results in duplication of SPS.

### ISSUE THREAD

**Issue by wsuzume** [rdkit/rdkit#6928]
To all the developers, thank you for providing such an excellent library.

I found that there are two `SPS` in `Descriptors.descList`. These two `SPS` have the same ID and seem to behave identically, so I think it's a duplication of the same item.

```
from rdkit.Chem import Descriptors

for x in Descriptors.descList:
    print(x)
```

```
('MaxAbsEStateIndex', <function MaxAbsEStateIndex at 0x7f004df16790>)
...
('SPS', <function SPS at 0x7f004df33a60>)
...
('SPS', <function SPS at 0x7f004df33a60>)
```

The `SPS` at the end of `descList` seems to be manually added at line 71 in `rdkit/Chem/Descriptors.py`. I believe commenting this out should resolve the issue.

https://github.com/rdkit/rdkit/blob/2957ab4576ddd422cba5d511e9e275ad69b8c628/rdkit/Chem/Descriptors.py#L70-L71

**Comment by greglandrum** [comment]
Confirmed. Thanks for the bug report!
