### ISSUE TITLE
rdqueries.ExplicitValenceEqualsQueryAtom cannot match atoms with correct Explicit Valence

### ISSUE THREAD

**Issue by HelloJocelynLu** [rdkit/rdkit#6969]
**Describe the bug**
When using `rdqueries.ExplicitValenceEqualsQueryAtom()`  to construct a query, it should be able to match an atom with GetExplicitValence() == 4, but it does not.

**To Reproduce**
```python
from rdkit import Chem
from rdkit.Chem import rdqueries

q = rdqueries.ExplicitValenceEqualsQueryAtom(4)
mol = Chem.MolFromSmiles("C[NH3+]")
key_atom = mol.GetAtomWithIdx(1)
print(key_atom.GetExplicitValence())
print(q.Match(key_atom))
```
It outputs `4`, `False`

**Expected behavior**
I expect it to output `4`, `True` as the target atom has explicit valence of 4

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.3
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.11
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from?  conda-forge
 - If you are not using conda: how did you install the RDKit? N/A

**Additional context**
N/A

**Comment by bp-kelley** [comment]
The atom's explicit valence is the explicit valence not in the context of the molecule.

The query for explicit valence is using the molecule in the graph context:

```
atom.GetExplicitValence() - atom.GetNumExplicitHs()
```

Which in this case is 1.

Admittedly, this is confusing!

**Comment by HelloJocelynLu** [comment]
> We should probably have an ExplicitValence query that matches the atom itself, but there is a hokey way to do what you want that is a useful general technique.
> 
> ```
> >>> from rdkit.Chem import rdqueries
> >>> q = rdqueries.HasIntPropWithValueQueryAtom("valence", 4)
> >>> m = Chem.MolFromSmiles("[NH3+]C")
> >>> for atom in m.GetAtoms():
> ...     atom.SetIntProp("valence", atom.GetExplicitValence())
> ... 
> >>> for atom in m.GetAtoms():
> ...     print(atom.GetIdx(), q.Match(atom))
> ... 
> 0 True
> 1 False
> >>> query_motif = Chem.RWMol(Chem.MolFromSmarts("CC"))
> >>> query_motif.ReplaceAtom(1, q)
> >>> m.GetSubstructMatch(query_motif)
> (1, 0)
> ```

Looks hacky but works, thank you!
