### ISSUE TITLE
More ChEMBL molecules that fail bounds smoothing

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#697]
```python
['C=C1NC(=O)C(C(C)C)NC(=O)C(C(C)CC)NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc1n2', 
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)CNC(=O)C(C(C)C)NC1=O', 
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)C(COC(C)=O)NC(=O)C(C(C)C)NC1=O', 
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)C(COC(=O)COCCOCCOC)NC(=O)C(C(C)C)NC1=O',
'C=C1NC(=O)C(C(C)C)NC(=O)C(C(C)CC)NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2nc1oc2C', 
'C=C1NC(=O)C(C(C)C)NC(=O)C(C(C)CC)NC(=O)c2nc(oc2-c2ccccc2)-c2nc(oc2C)-c2csc(n2)-c2coc(n2)-c2nc1oc2C',
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)C(COC(=O)COCCOC)NC(=O)C(C(C)C)NC1=O',
'C=C1NC(=O)C(C(C)C)NC(=O)C(C(C)CC)NC(=O)c2nc(oc2-c2ccccc2)-c2nc(oc2C)-c2csc(n2)-c2coc(n2)-c2coc1n2',
'CCC(C)C1NC(=O)c2nc(oc2-c2ccccc2)-c2coc(n2)-c2csc(n2)-c2coc(n2)-c2coc(n2)C(COC(=O)C(N)CCCNC(=N)N)NC(=O)C(C(C)C)NC1=O']
```

**Comment by greglandrum** [comment]
This bears a passing resemblance to #696

**Comment by greglandrum** [comment]
But then, after looking more closely, it becomes clear that these all have a S-containing aromatic heterocycle. @sriniker : we saw this problem while working on the ETKDG paper.

**Comment by sriniker** [comment]
Yes, we had problems with these three SMILES:
C[C@@H]1[C@@H]2Cc3ccc(O)cc3[C@]1(C)CCN2CCN4CCCCCC4
CCN(CC)CCN1CC[C@]2(C)[C@H](C)[C@@H]1Cc3ccc(O)cc23
C[C@@H]1[C@@H]2Cc3ccc(O)cc3[C@]1(C)CCN2CCN(C)C
where no conformation could be generated. 

If one stereocenter was changed, everything worked fine:
C[C@@H]1[C@H]2Cc3ccc(O)cc3[C@]1(C)CCN2CCN4CCCCCC4
CCN(CC)CCN1CC[C@@]2(C)[C@H](C)[C@@H]1Cc3ccc(O)cc23
C[C@@H]1[C@H]2Cc3ccc(O)cc3[C@]1(C)CCN2CCN(C)C

**Comment by greglandrum** [comment]
Weren't there some examples where an aromatic S in a five-membered ring was a problem?

**Comment by sriniker** [comment]
True. There was also an issue with the following molecule
CCOC(=O)N1N(C(=O)OCC)[C@]2(c3ccccc3)S[C@@]1(c1ccccc1)C(=O)N2c1ccccc1
where some distance bounds are not optimal. This is, however, not an aromatic ring. Nevertheless, I guess the problem is related.
