### ISSUE TITLE
Invariant Violation: 	bad lower bound 

### ISSUE THREAD

**Issue by mahuahuahua** [rdkit/rdkit#7005]
This error will appear when I run the program, and my program will stop running. Sometimes it will appear after one iteration, and sometimes it will appear after more than ten iterations. Can you help me solve this problem?

Start grammar evaluation...
Generating sample 0/10
N#CC1=CC=c2ccc(cc2=CC2=CC=C3C=Cc4ccc(cc5ccc(cc6oc(cc(nn4)C=C2)=CC=C(C=C[No])N=C6)=CC=NNC(=NNc2ccc(C#N)cc2)C=C5)O3)C=C1
Generating sample 1/10
O=C1C(=O)C1=Cc1ccc([No])s1
Generating sample 2/10
N#Cc1ccc(-c2ccc([No])cc2)cc1
Generating sample 3/10
C1=CC2=CC=C1C1=NSN=C1C1=C2C=CC2=NSN=C2N1
Generating sample 4/10
N#CC1=CC=C2C=C3C=CC(=NC([No])=[N+]=C([No])N3)N=NC(=CN2)C=C1
Generating sample 5/10
N#CC#Cc1ccc2c(c1)C=CC(=CNc1ccc(C#N)cc1)C=C2
Generating sample 6/10
[No]C=Cc1ccc(N=Nc2cc(N=Nc3ccc(C=C[No])cc3)cc(C3=CC=C4C=CC(C#Cc5ccc6cc([No])ccc6c5)=CC=C(C=C3)N=N4)c2)cc1
Generating sample 7/10
[No]c1ccc(C#Cc2ccc([No])cc2)cc1
Generating sample 8/10
N#Cc1ccc(C#Cc2nc(C#N)nc(C3=CC4=CC=C(C=C[No])C=CC(=CC5=CC=C(c6ccc(C#N)ccc7ccc(C=C[No])ccn6-7)C=CC(=C3)N=N5)C=C4)n2)cc1
Generating sample 9/10
N#Cc1ccc(-n2cc(N3C=Cc4ccc(c(=C5C=CC6=NC(c7ccc(C=C[No])cc7)=NC(Oc7ccc([No])cc7)=NC(=CC=CN5)N=N6)c4)=CC=C3c3ccc([No])cc3)nn2)cc1
Invariant Violation
	bad lower bound
	Violation occurred on line 187 in file Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
	Failed Expression: lb > DIST12_DELTA || clb > DIST12_DELTA
	RDKIT: 2023.03.3
	BOOST: 1_78

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
