### ISSUE TITLE
GetRingInfo fails after Chem.CombineMols

### ISSUE THREAD

**Issue by supersciencegrl** [rdkit/rdkit#7006]
**Describe the bug**
After using Chem.CombineMols to create a mixture object, GetRingInfo().AtomRings() returns an empty tuple even when rings are present. 

**To Reproduce**
Difference between toluene, THF, and a Chem.CombineMols mixture of the two:
```
>>> toluene = Chem.MolFromSmiles('CC1=CC=CC=C1')
>>> thf = Chem.MolFromSmiles('C1COCC1')
>>> solvents = Chem.CombineMols(toluene,thf)
>>> ri_toluene = toluene.GetRingInfo()
>>> ri_thf = thf.GetRingInfo()
>>> ri_solvents = solvents.GetRingInfo()
>>> ri_toluene.AtomRings()
((1, 6, 5, 4, 3, 2),)
>>> ri_thf.AtomRings()
((0, 1, 2, 3, 4),)
>>> ri_solvents.AtomRings()
()
```
The same happens if only one of the original components contains a ring, eg: pyrrolidine + HCl as a mixture. (However, when pyrrolidine HCl is brought in as a salt, the ring _is_ found:
```
>>> salt = Chem.MolFromSmiles('[H]Cl.C1CNCC1')
>>> ri_salt = salt.GetRingInfo()
>>> ri_salt.AtomRings()
((1, 2, 3, 4, 5),)
```

**Expected behavior**
I expected both rings to be returned from GetRingInfo().AtomRings() of the mixture of two cyclic compounds. 

**Configuration (please complete the following information):**
 - RDKit version: 2023.3.3
 - OS: Windows 10
 - Python version (if relevant): 3.11.4
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? pip

**Comment by greglandrum** [comment]
Hi @supersciencegrl 
This is expected behavior: the molecule from `CombineMols()` has not been sanitized. If you call `SanitizeMol()` the RDKit will do chemistry perception, recalculate the rings, etc:
```
In [3]: toluene = Chem.MolFromSmiles('CC1=CC=CC=C1')
   ...: thf = Chem.MolFromSmiles('C1COCC1')
   ...: solvents = Chem.CombineMols(toluene,thf)

In [4]: Chem.SanitizeMol(solvents)
Out[4]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [5]: solvents.GetRingInfo().AtomRings()
Out[5]: ((1, 6, 5, 4, 3, 2), (7, 8, 9, 10, 11))
```

**Comment by supersciencegrl** [comment]
Oh..... that's embarrassing. Thanks @greglandrum! 

I was trying to avoid sanitization as I'm dealing with organometallics/metal complexes, and I'm scared 😅 but on my test it has gone well, so I'll keep going. Thank you for your fast response; always impressive!

**Comment by greglandrum** [comment]
> Oh..... that's embarrassing. Thanks @greglandrum! 

No need to be embarrassed; it's often not clear whether or not a molecule has been sanitized.

> I was trying to avoid sanitization as I'm dealing with organometallics/metal complexes, and I'm scared 😅 but on my test it has gone well, so I'll keep going. 

It's good to be careful about the organometallics. If you just want the ring info, you can call mol.UpdatePropertyCache(strict=False) and then call the run finding code: Chem.GetSymmSSSR(mol) (I think that's how it's spelled; I'm not in front of my computer at the moment).
