### ISSUE TITLE
Ligand conversion problem from 2D to 3D

### ISSUE THREAD

**Issue by apaydinemre** [rdkit/rdkit#7022]
**Configuration:**

PC (i9 9900K RTX 2080 SUPER 32 GB DDR4 RAM)
- RDKit Version: 2023.03.3
- Operating system: Ubuntu 20.04
- Python version : 3.10.12

**Description:**

I want to convert the 2D ligands I downloaded as sdf format from the ZINC library to 3D, but almost half of them are not converted to 3D. Some of them are; ZINC000008214373, ZINC000001530666, ZINC000085545180. 208 ligands are not converted to 3D in this way. When I run the script, I do not get any warning or error in IDE. When I look at the output of my Try, Except commands, I see "ZINC000008214373.sdf : rdDistGeom.EmbedMolecule(mol, etkdgv3) = Failed
ZINC000008214373.sdf : rdForceFieldHelpers.UFFOptimizeMolecule(mol) = Failed" It outputs like this for ligands that are not translated to 3D. When I try different methods, the ligands are converted to 3D. I wonder if there is something missing or wrong with my script. I would be grateful if you can help me. Thank you!

```
from rdkit import Chem
from rdkit.Chem import rdDistGeom
from rdkit.Chem import rdForceFieldHelpers
from rdkit.Chem import rdPartialCharges
import os

ligands_dir = "ligands"
output_dir = "new_ligands"
status_file = "process_status.txt"

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

sdf_files = [f for f in os.listdir(ligands_dir) if f.endswith(".sdf")]

with open(status_file, 'w') as status:
    for sdf_file in sdf_files:
        input_path = os.path.join(ligands_dir, sdf_file)
        output_path = os.path.join(output_dir, sdf_file)
        mol = Chem.MolFromMolFile(input_path)

        # Add hydrogens
        try:
            mol = Chem.AddHs(mol, addCoords=True)
        except:
            status.write(f"{sdf_file} : Chem.AddHs(mol) = Failed\\n")
            continue

        # 3D embedding
        etkdgv3 = rdDistGeom.ETKDGv3()
        embed_status = rdDistGeom.EmbedMolecule(mol, etkdgv3)
        if embed_status == -1:
            status.write(f"{sdf_file} : rdDistGeom.EmbedMolecule(mol, etkdgv3) = Failed\\n")

        # Compute Gasteiger charges
        try:
            rdPartialCharges.ComputeGasteigerCharges(mol)
        except:
            status.write(f"{sdf_file} : rdPartialCharges.ComputeGasteigerCharges(mol) = Failed\\n")

        # UFF energy minimization
        try:
            rdForceFieldHelpers.UFFOptimizeMolecule(mol)
        except:
            status.write(f"{sdf_file} : rdForceFieldHelpers.UFFOptimizeMolecule(mol) = Failed\\n")

        Chem.MolToMolFile(mol, output_path)

```

**Comment by dehaenw** [comment]
greetings,
here is a minimal example that reproduces the embedding failure for ZINC000008214373
```python
from rdkit import Chem
from rdkit.Chem import rdDistGeom
mol=Chem.MolFromSmiles("CCCCCCCCCCCCCCCC(=O)OC[C@H](CO[P@@](=O)(O)OCC[N+](C)(C)C)OC(=O)CCCCCCCCCCCCCCC")
mol=Chem.AddHs(mol, addCoords=True)
ps = rdDistGeom.ETKDGv3()
embed_status = rdDistGeom.EmbedMolecule(mol, ps)
if embed_status == -1:
    print("failed")
```
It's true, this fails. Based on the troubleshooting presented in https://github.com/rdkit/rdkit/discussions/5841 you can add the line `ps.useRandomCoords = True` before embedding. In the case of the above molecule, that fixes the embedding failure. To look a bit deeper into why this works, you can have a look here: https://greglandrum.github.io/rdkit-blog/posts/2021-01-31-looking-at-random-coordinate-embedding.html 

In your script you could re-embed using random coords in case you get -1 status in the first instance.

**Comment by apaydinemre** [comment]
Thank you so much for your help. I managed to convert most of the molecules from 2D to 3D, but no matter which ETKDG version, which embedding parameter I try, I cannot convert these two molecules; ZINC000101210593, ZINC000196058327. Is there an alternative feature or method I can try? I would be very grateful if you can help me. Thank you!

**Comment by mainguyenanhvu** [comment]
Have you successfully converted them? Please help me. Thank you very much.

**Comment by greglandrum** [comment]
> Thank you so much for your help. I managed to convert most of the molecules from 2D to 3D, but no matter which ETKDG version, which embedding parameter I try, I cannot convert these two molecules; ZINC000101210593, ZINC000196058327. Is there an alternative feature or method I can try? I would be very grateful if you can help me. Thank you!

Those two molecules were discussed in an rdkit discuss post that you may want to read:
https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg11496.html

Note that I found this post by googling for "RDKit ZINC000196058327", something that you also could have done
