### ISSUE TITLE
`rdkit.rdBase.boostVersion` is empty string in latest release installed from PyPI using pip

### ISSUE THREAD

**Issue by radusuciu** [rdkit/rdkit#7024]
I consult `rdkit.rdBase.boostVersion` to determine what version of `boost` any given version of `rdkit` has been built with like so: `python -c "import rdkit; print(rdkit.rdBase.boostVersion)"`. With the latest release, I get back an empty string (`''`)

**Configuration**
 - RDKit version: 2023.09.3
 - OS: Ubuntu 22.04.2 LTS (under WSL2)
 - Python version: 3.10.12
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? `pip install rdkit`

**Comment by greglandrum** [comment]
This is not an RDKit bug. Please open the issue in the rdkit pypi repository: https://github.com/kuelumbus/rdkit-pypi

**Comment by radusuciu** [comment]
Thank you!

**Comment by radusuciu** [comment]
Fixed in https://github.com/kuelumbus/rdkit-pypi/issues/88, though not yet released on PyPI.
