### ISSUE TITLE
There are multiple Python2 files in the source code

### ISSUE THREAD

**Issue by whosayn** [rdkit/rdkit#7025]
After noticing some python2 syntax in the source code, I ran this script

```
import ast
import pathlib

for path in pathlib.Path(".").glob("**/*.py"):
    try:
        ast.parse(path.read_text())
    except:
        print(path)
```
 to identify these 3 files:

- Code/GraphMol/Descriptors/test3D.py
- Code/GraphMol/Descriptors/test3D_old.py
- External/Eigen/eigen/scripts/relicense.py

These all seem related to 3D descriptors and haven't seen much action since around 2017.

**Comment by rachelnwalker** [comment]
I don't think we're going to fix the Eigen file, but closing this case since @mcs07 removed the other two files!
