### ISSUE TITLE
Middle line in double bond drawn to incorrect point when a wedged bond is present

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#7036]
**Describe the bug**
![image](https://github.com/rdkit/rdkit/assets/540511/e348cb5e-1639-42a8-96e4-73b0fef9041f)

**Configuration (please complete the following information):**
 - RDKit version: master and current releases
 - OS: all

**Comment by DavidACosgrove** [comment]
I’ll take a look over the weekend. It looks like a triple bond, though?

**Comment by greglandrum** [comment]
> I’ll take a look over the weekend. It looks like a triple bond, though?

errr... yeah... sorry
