### ISSUE TITLE
`README.md`'s documentation badge is out of date.

### ISSUE THREAD

**Issue by Yoshanuikabundi** [rdkit/rdkit#7052]
The [badge](https://github.com/rdkit/rdkit/blob/73b4da2a44a297758def89dd4f9eda8cf0b4e907/README.md?plain=1#L3) at the top of [README.md](https://github.com/rdkit/rdkit/blob/master/README.md) is pointing to a ReadTheDocs project that hasn't been updated since 2019. This tripped me up today! The [documentation link](https://github.com/rdkit/rdkit/blob/73b4da2a44a297758def89dd4f9eda8cf0b4e907/README.md?plain=1#L33) further down the readme and the link in [README](https://github.com/rdkit/rdkit/blob/master/README) are both correct.

This would be a PR, but I'm not familiar with how you host your docs so I'm not sure the best way to set up a badge.

**Comment by greglandrum** [comment]
Thanks for pointing this out.
We don't use ReadTheDocs, so that link really should just be removed.
PR's are always welcome! :-)
