### ISSUE TITLE
Cannot parse SMILES generated from ketcher

### ISSUE THREAD

**Issue by bruceunx** [rdkit/rdkit#7053]
**Describe the bug**
Cannot parse SMILES generated from ketcher

**To Reproduce**
![bug-report](https://github.com/rdkit/rdkit/assets/44418848/8deb6c03-cad1-4261-b53c-2f9319ffa33d)

**Additional context**
I just used pysmiles to handle read SMILES generated from ketcher, I think rdkit can fix this bug later.

**Comment by greglandrum** [comment]
The failure here is because you are converting the SMILES to upper case. SMILES is case sensitive, so when you do this you create an illegal SMILES which contains `CL` instead of `Cl`.
