### ISSUE TITLE
Differences in AllChem.EmbedMultipleConfs Code Execution Speed by Rdkit Version

### ISSUE THREAD

**Issue by yechanjoo** [rdkit/rdkit#7057]
**Describe the bug**
To create a conformer of a compound called zotarolimus, we wrote the following code.

```python
from rdkit import Chem
from rdkit.Chem import AllChem
import time
import numpy as np

# rdkit_ver = 2023.3.3
time_list = []
for i in range(10):
    mol = Chem.MolFromSmiles('C[C@@H]1CC[C@H]2C[C@@H](/C(=C/C=C/C=C/[C@H](C[C@H](C(=O)[C@@H]([C@@H](/C(=C/[C@H](C(=O)C[C@H](OC(=O)[C@@H]3CCCCN3C(=O)C(=O)[C@@]1(O2)O)[C@H](C)C[C@@H]4CC[C@@H]([C@@H](C4)OC)N5C=NN=N5)C)/C)O)OC)C)C)/C)OC')
    mol = Chem.AddHs(mol)
    s = time.time()
    AllChem.EmbedMultipleConfs(mol, 10)
    e = time.time()
    time_list.append(e-s)
print('ver_230303:', np.mean(time_list))
```

However, the speed of code execution varied significantly depending on the version of rdkit, and rather, the speed of code execution was much slower in the latest version.
It took 12 seconds to the (2022.9.5 version & 2021.9.2 version) and 37 seconds to the 2023.3.3 version. I'm asking what difference is causing the speed difference.

```python
ver_210902: 12.803041124343872
ver_220905: 12.365700602531433
ver_230303: 37.294674682617185
``` 

  - Environment : AWS c5.4xlarge
     (https://aws.amazon.com/ec2/instance-types/c5/?nc1=h_ls)
 - Python version : 3.10.12
 - RDKit version : 21.9.2 / 22.9.5 / 23.3.3
 - Are you using conda?    - Yes
 - If you are using conda, which channel did you install the rdkit from?    - pip install rdkit==2023.3.3

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.
