### ISSUE TITLE
Consider adding support for isotopes in rdMolDescriptors.CalcMolFormula()

### ISSUE THREAD

**Issue by luperrin** [rdkit/rdkit#7061]
**Is your feature request related to a problem? Please describe.**
Isotopes are categorically ignored when calculated a molecular formula (e.g., deuterium is counted as hydrogen). This can lead to confusing discrepancies in datasets where formulae from other calculators are aggregated.

**Describe the solution you'd like**
rdMolDescriptors.CalcMolFormula() accounts for isotopes present in input mol object or mol from SMILES string. See 'Additional context' for an example.

**Describe alternatives you've considered**
May be variations in how isotopes are written in formulae. For example, observed for deuterium: '[2H]', 'D', 'Htwo', '[2^H]', and others...

**Additional context**
Currently:
```
>>> Chem.rdMolDescriptors.CalcMolFormula(Chem.MolFromSmiles("[2H]C([2H])(C=O)C([2H])([2H])CO"))
'C4H8O2'
```
Desired:
```
>>> Chem.rdMolDescriptors.CalcMolFormula(Chem.MolFromSmiles("[2H]C([2H])(C=O)C([2H])([2H])CO"))
'C4H4[2H]4O2'
```

**Comment by greglandrum** [comment]
This support is already there, you just need to ask for it:
```
In [5]: rdMolDescriptors.CalcMolFormula(Chem.MolFromSmiles('CC[17O][2H]'),separateIsotopes=True,abbreviateHIsotopes=True)
Out[5]: 'C2H5D[17O]'
```

**Comment by luperrin** [comment]
Thanks for clarifying, and sorry for the unneeded ticket. I had interpreted that argument to mean something different.
