### ISSUE TITLE
Delocalized Charges Not Seen as Substructures

### ISSUE THREAD

**Issue by rwalroth** [rdkit/rdkit#7068]
**Describe the bug**
When comparing two molecules with a delocalized charge, but with the anionic carbon in different positions, they show up as not being substructures of each other.

**To Reproduce**
```{python}from rdkit import Chem
mol1 = Chem.MolFromSmiles('CP(C)c1[cH-]ccc1')
mol2 = Chem.MolFromSmiles('CP(C)c1cc[cH-]c1')
mol1.HasSubstructMatch(mol2)
```

**Expected behavior**
Should return True, as these are the same molecule chemically speaking. The negative charge is delocalized over the whole ring.

**Screenshots**
![image](https://github.com/rdkit/rdkit/assets/31414518/4560552f-6614-40e2-aec0-1d0ce8a854e5)

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.1
 - OS: Windows 11
 - Python version (if relevant): 3.9
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? rdkit
 - If you are not using conda: how did you install the RDKit?

**Additional context**
My current workaround is to saturate the ring, so convert CP(C)c1[cH-]ccc1 to CP(C)C1CCCC1 and then do the comparison, but this is a bad workaround because I also need to get rid of the explicit hydrogen which has thrown its own hard to reproduce bugs at times. The other method I've tried is to canonicalize the atom indices and then make the first atom in the ring hold the negative charge.

**Comment by rwalroth** [comment]
This bug also applies for positive charges, as in a protonated imidazole ring:
s1 = 'N1C(C)=C[NH+]=C1'
s2 = 'N1C=C(C)[NH+]=C1'
mol1 = Chem.MolFromSmiles(s1)
mol2 = Chem.MolFromSmiles(s2)
display(mol1)
display(mol2)
mol1.HasSubstructMatch(mol2)

returns False

![image](https://github.com/rdkit/rdkit/assets/31414518/a0965887-d5be-4541-9d6b-435a425f31c8)

**Comment by ptosco** [comment]
This is not a bug, this is the expected behavior - charges are localized.
This applies to all functional groups which may exist under different resonance forms.
You can do a resonance structure-aware substructure match through `ResonanceMolSupplier`, which will enumerate all possible resonance structures and attempt a match against each. See below:
```
from rdkit import Chem
from rdkit.Chem.Draw import MolsToGridImage

mol1 = Chem.MolFromSmiles('CP(C)c1[cH-]ccc1')
mol2 = Chem.MolFromSmiles('CP(C)c1cc[cH-]c1')

# This is the expected behavior
mol1.HasSubstructMatch(mol2)
False

res_suppl = Chem.ResonanceMolSupplier(mol1)
MolsToGridImage(res_suppl)
```
![image](https://github.com/rdkit/rdkit/assets/5244385/347478e2-c2b9-4892-a704-eafcece1b0d2)

```
# structures returned by ResonanceMolSupplier are in kekulized form, so we create a kekulized copy of the query
kek_mol2 = Chem.Mol(mol2)
Chem.Kekulize(kek_mol2)
res_suppl.GetSubstructMatch(kek_mol2)
(0, 1, 2, 3, 7, 6, 5, 4)

mol1 = Chem.MolFromSmiles('N1C(C)=C[NH+]=C1')
mol2 = Chem.MolFromSmiles('N1C=C(C)[NH+]=C1')

mol1.HasSubstructMatch(mol2)
False

res_suppl = Chem.ResonanceMolSupplier(mol1)
MolsToGridImage(res_suppl)
```
![image](https://github.com/rdkit/rdkit/assets/5244385/e7a10395-eeb1-4ca8-98d1-6e349f08bfac)

```
kek_mol2 = Chem.Mol(mol2)
Chem.Kekulize(kek_mol2)
res_suppl.GetSubstructMatch(kek_mol2)
(4, 3, 1, 2, 0, 5)
```

**Comment by rwalroth** [comment]
@ptosco I see. I guess this should have been a suggested enhancement, as those charges are truly delocalized and the molecules are chemically and physically identical in every way. However, I ran into a problem with the resonance mol supplier. It seems to be dependent on the input smiles string:

```{python}
def get_all_res_smiles(mol):
    out = set()
    suppl = Chem.ResonanceMolSupplier(mol)
    for _m in suppl:
        _s = Chem.MolToSmiles(_m)
        out.add(_s)
    return out

s = 'Cc1[cH-]ccc1'
mol = Chem.MolFromSmiles(s)
suppl = Chem.ResonanceMolSupplier(mol)
res_set = get_all_res_smiles(mol)

for i in range(100):
    sr = Chem.MolToSmiles(mol, doRandom=True)
    mr = Chem.MolFromSmiles(sr)
    res_setr = get_all_res_smiles(mr)
    if res_set != res_setr:
        print(s)
        print(sr)
        print(res_set)
        print(res_setr)
        break
```
returns:
```{python}
Cc1[cH-]ccc1
c1c(C)[cH-]cc1
{'Cc1c[cH-]cc1', 'C[c-]1cccc1', 'Cc1ccc[cH-]1'}
{'Cc1c[cH-]cc1', 'Cc1ccc[cH-]1'}
```
The only way I've found to reliably avoid this is to do `Chem.MolFromSmiles(Chem.MolToSmiles(Chem.MolFromSmiles(sr)))`. Resetting the atom indices to canonical order as demonstrated in the RDKit cookbook does not help.
