### ISSUE TITLE
SanitizeRxn leads to incorrect reactant structure

### ISSUE THREAD

**Issue by MartaPasquini** [rdkit/rdkit#7108]
**Describe the bug**
After sanitizing an Rxn object, one of the reactants is assign to a wrong valence, which make impossible for RDkit to correctly parse it.

**To Reproduce**

```
from rdkit.Chem import rdChemReactions
from rdkit import Chem

reaction_string = 'CCC1=C(Br)N=C(N1)C(O)=O.Cl>>CCC1=C(Cl)N=C(N1)C(O)=O'
rdrxn = rdChemReactions.ReactionFromSmarts(reaction_string)

# here everything is still correct
print(rdChemReactions.ReactionToSmiles(rdrxn))
CCC1=C(Br)N=C(C(O)=O)N1.Cl>>CCC1=C(Cl)N=C(C(O)=O)N1

reactants = [Chem.MolFromSmiles(Chem.MolToSmiles(mol)) for mol in list(rdrxn.GetReactants())]
print(reactants)
[<rdkit.Chem.rdchem.Mol object at 0x000001F9374F0DD0>, <rdkit.Chem.rdchem.Mol object at 0x000001F9374F0E40>]

# however, when the rdrxn is sanitized...
rdChemReactions.SanitizeRxn(rdrxn)
Out[11]: rdkit.Chem.rdChemReactions.SanitizeFlags.SANITIZE_NONE

# one of the reactant is changed
print(rdChemReactions.ReactionToSmiles(rdrxn))
CCc1nc(C(O)=O)nc1Br.Cl>>CCC1=C(Cl)N=C(C(O)=O)N1

# and cannot be kekulized correctly
reactants = [Chem.MolFromSmiles(Chem.MolToSmiles(mol)) for mol in list(rdrxn.GetReactants())]
[11:37:23] Can't kekulize mol.  Unkekulized atoms: 2 3 4 8 9

```

**Expected behavior**
The sanitization should lead to correct molecules, which can be parsed by RDKit.

**Configuration (please complete the following information):**
 - RDKit version: 2023.3.3
 - OS: Windows10
 - Python version (if relevant): 3.8
 - Are you using conda? only as environment manager, not to install packages
 - If you are using conda, which channel did you install the rdkit from? - 
 - If you are not using conda: how did you install the RDKit? pip install rdkit

**Additional context**
We observed the same behavior for different reactions in which one of the reactants contains 5-members rings with nitrogen atoms.

**Comment by greglandrum** [comment]
Confirmed.
Thanks for the bug report @MartaPasquini

**Comment by bp-kelley** [comment]
Note that the sanitization done here is only "assign aromaticity" if possible.  This doesn't add hydrogens to nitrogens like a normal sanitization would.

The original intent was to make the smarts pattern work correctly during reaction processing if the input structure was kekule, it wasn't originally intended to make the reactant sanitized like a normal rdkit sanitization, this wouldn't work in a lot of cases anyway.

**Comment by bp-kelley** [comment]
I.e. the pattern was read as a smarts, not a molecule.

**Comment by greglandrum** [comment]
@bp-kelley and I discussed this in slack and we can add an option to `SanitizeRxn()` to treat the reactants/products like molecules and not queries. That will clear this up.
I will do a PR for this in the near future
