### ISSUE TITLE
Wrong stereochemistry in embedded rings from stereospecific SMILES

### ISSUE THREAD

**Issue by brje01** [rdkit/rdkit#7109]
-----------------------------------------

A stereospecific SMILES was provided to produce an ETKDGv3 rmsd pruned ensemble. Upon inspection of the returned conformers, there were stereoisomers in the ensemble that should not be part of the ensemble.

rdkit version: 2023.09.4
os: ubuntu 22.04
python: 3.10
conda install, channel: conda-forge

Function to check the stereo of the produced conformers:
```
def AnalyzeStereoInEnsemble(mol,confIds):
    stereo = []
    for c in confIds:
        m = Chem.Mol(mol)
        m.RemoveAllConformers()
        m.AddConformer(mol.GetConformer(c))
        Chem.rdmolops.AssignStereochemistryFrom3D(m)
        stereo.append((c, Chem.FindMolChiralCenters(m,force=True,includeUnassigned=True,useLegacyImplementation=False)))
    return stereo
```

Molecule used as example:
```
mol = Chem.AddHs(Chem.MolFromSmiles("C1[C@H](C#CC#C)CC[C@H](C#CC#C)C1"))
print(Chem.FindMolChiralCenters(mol,force=True,includeUnassigned=True,useLegacyImplementation=False))
```
Output: [(1, 's'), (8, 's')]

Embedding:
```
ps = AllChem.ETKDGv3()
ps.randomSeed = 0xC0FFEE
ps.pruneRmsThresh = 0.5
ps.numThreads = 8
AllChem.EmbedMultipleConfs(mol,5000,ps)
```

Analysis of the ensemble:
```
confIds = [x.GetId() for x in mol.GetConformers()]
AnalyzeStereoInEnsemble(mol,confIds)
```
Output: [(0, [(1, 's'), (8, 's')]),
 (1, [(1, 's'), (8, 's')]),
 (2, [(1, 's'), (8, 's')]),
 (3, [(1, 's'), (8, 's')]),
 (4, [(1, 's'), (8, 's')]),
 (5, [(1, 's'), (8, 's')]),
 (6, [(1, 's'), (8, 's')]),
 (7, [(1, 's'), (8, 's')]),
 (8, [(1, 'r'), (8, 'r')]),
 (9, [(1, 's'), (8, 's')]),
 (10, [(1, 's'), (8, 's')]),
 (11, [(1, 's'), (8, 's')]),
 (12, [(1, 'r'), (8, 'r')])]

8 and 12 are conformers of a different molecule (stereoisomer) and should not be in this ensemble.

**Comment by greglandrum** [comment]
The underlying cause here is that the K terms end up flipping the chirality of one of the chiral centers. This isn't caught because we do all of the "is the stereochemistry correct?" checks before the ETK part runs.

This has already been fixed in #7098 . I will add a test for the issue to that PR so that we can be sure this doesn't happen again.
