### ISSUE TITLE
wrong MW calculated for As2O3

### ISSUE THREAD

**Issue by mjszabo** [rdkit/rdkit#7120]
Dear RDKit Support,
I am kindly asking your help in the following issue.
Thank you,
Miklos Szabo

**Describe the bug**
LabCup is using RDKit service for calculating molecule weight MW.
The calculation service provides false molecular weight for As2O3 when the molecule is entered in ionic form.
For a molecule input smiles: [O-2].[O-2].[O-2].[As+3].[As+3] ,
During the MW calculation, RDKit transforms the molecule into: [AsH6+3].[AsH6+3].[O-2].[O-2].[O-2] , which is a wrong structure, and therefore the calculated molecular weight is 209.9, wrong as well.
The correct value is 197.8 
For a reference value, please find info here:
https://pubchem.ncbi.nlm.nih.gov/compound/14888

**To Reproduce**
I was able to reproduce the same behaviour in KNIME with RDKit nodes.
Please find attached screenshot.

**Expected behavior**
The expected behavior is to calculate the MW for the ionic structure, [O-2].[O-2].[O-2].[As+3].[As+3].
In my opinion, RDKit should keep the original input structure, and not to add hydrogens to As3+
The MW should be 197.8

**Screenshots**
![As2O3_false_MW_value](https://github.com/rdkit/rdkit/assets/158502011/a4e1026c-dceb-484e-a10e-4700fb308514)

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.4

**Additional context**
N/A

**Comment by greglandrum** [comment]
I'm not able to reproduce this:
```
In [9]: m = Chem.MolFromSmiles(' [O-2].[O-2].[O-2].[As+3].[As+3]')

In [10]: from rdkit.Chem import Descriptors
De
In [11]: Descriptors.MolWt(m)
Out[11]: 197.841

In [12]: Chem.MolToSmiles(m)
Out[12]: '[As+3].[As+3].[O-2].[O-2].[O-2]'
```
are you sure you started from a SMILES?

**Comment by mjszabo** [comment]
Thank you for your quick answer.
You are right, that only the initial input was in SMILES.

For the KNIME case, please find attached the KNIME workflow and the molfiles I used.
[As2O3_MW.zip](https://github.com/rdkit/rdkit/files/14129721/As2O3_MW.zip)

In case of LabCup, the drawing tool is JMSE.
I checked that the JSME editor still contains the Ar3+ without hydrogens. 
I try to gather more exact information from my colleagues.

**Comment by greglandrum** [comment]
This is not a bug, the RDKit is behaving as expected.
If you make sure that your input mol blocks actually specify that the As has no Hs attached to it (which you absolutely need to do), then everything works as expected:
```
In [2]: m = Chem.MolFromMolBlock('''
   ...:   Mrv2211 02022407462D          
   ...: 
   ...:   0  0  0     0  0            999 V3000
   ...: M  V30 BEGIN CTAB
   ...: M  V30 COUNTS 5 0 0 0 0
   ...: M  V30 BEGIN ATOM
   ...: M  V30 1 As -5.9583 2.2083 0 0 CHG=3 VAL=-1
   ...: M  V30 2 As -2.625 4.375 0 0 CHG=3 VAL=-1
   ...: M  V30 3 O 8 6.5833 0 0 CHG=-2
   ...: M  V30 4 O 2.5 7 0 0 CHG=-2
   ...: M  V30 5 O 2.625 4.125 0 0 CHG=-2
   ...: M  V30 END ATOM
   ...: M  V30 END CTAB
   ...: M  END
   ...: ''')

In [3]: Chem.MolToSmiles(m)
Out[3]: '[As+3].[As+3].[O-2].[O-2].[O-2]'
```

**Comment by mjszabo** [comment]
Thank you for your answer.
I understand now that the MW calculation works properly.

However, I still don't understand why the molecule conversion adds hydrogens to the Ar3+ .
Is there anything that can prevent this undesired transformation?

**Comment by greglandrum** [comment]
> Thank you for your answer. I understand now that the MW calculation works properly.
> 
> However, I still don't understand why the molecule conversion adds hydrogens to the Ar3+ . Is there anything that can prevent this undesired transformation?

Yes, as I indicated in the example: mark the atoms in the input molfile as not having any hydrogen atoms
