### ISSUE TITLE
Make addStereoAnnotation public

### ISSUE THREAD

**Issue by cdvonbargen** [rdkit/rdkit#7140]
**Is your feature request related to a problem? Please describe.**

Request for access to the addStereoAnnotation function in the private MolDraw2DDetails header. I'm hoping to decorate my molecule in the same way that RDKit's 2D image generation does.
https://github.com/rdkit/rdkit/blob/21b9ba16852461dddf9d53ffdb8186cf1d5e8b7b/Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp#L49

**Comment by greglandrum** [comment]
Makes sense to me. We can pull that out into the `Chirality` namespace in `Chirality.h`

**Comment by DavidACosgrove** [comment]
It's not really private at the moment though, I don't think.  The MolDraw2D_detail namespace is intended to flag that this is an implementation detail of the drawing code so may change at any time, but it is available to be used in C++ code if you accept that limitation.
Do you need it exposing in Python, which is a different thing?  It's not really anything to do with the drawing as such so there's no reason why it shouldn't be exposed as user code I guess.

**Comment by greglandrum** [comment]
> It's not really anything to do with the drawing as such so there's no reason why it shouldn't be exposed as user code I guess.

Yeah, that's what I was thinking

**Comment by DavidACosgrove** [comment]
@greglandrum Do you have time to do it at the moment?  I can probably squeeze it in in the next week or so if not.

**Comment by greglandrum** [comment]
@DavidACosgrove I can do it
