### ISSUE TITLE
Error drawing molecule with MolDraw2DSVG

### ISSUE THREAD

**Issue by dr-nate** [rdkit/rdkit#715]
Hi all,

I've been following along on [this blog post](http://rdkit.blogspot.com/2015/02/new-drawing-code.html) in a IPython notebook. However, when I get to step 4 in the blog post (using identical code), I get the following error:

```
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-13-0f637ca1e274> in <module>()
----> 1 SVG(moltosvg(m))

<ipython-input-12-f15ebd7dae1f> in moltosvg(mol, molSize, kekulize)
      9             mc = Chem.Mol(mol.ToBinary())
     10     if not mc.GetNumConformers():
---> 11         rdDepictor.Compute2DCoords(mc)
     12     drawer = rdMolDraw2D.MolDraw2DSVG(molSize[0],molSize[1])
     13     drawer.DrawMolecule(mc)

ArgumentError: Python argument types in
    rdkit.Chem.rdDepictor.Compute2DCoords(Mol)
did not match C++ signature:
    Compute2DCoords(RDKit::ROMol {lvalue} mol, bool canonOrient=True, bool clearConfs=True, boost::python::dict {lvalue} coordMap={}, unsigned int nFlipsPerSample=0, unsigned int nSample=0, int sampleSeed=0, bool permuteDeg4Nodes=False, double bondLength=-1.0)
```

If I try to use a non-SMILES pathway, using a molecule from the ZINC database [like this one](http://zinc.docking.org/substance/36634) (you can download the mol2 file from there), I get the following error:

```
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-16-0f637ca1e274> in <module>()
----> 1 SVG(moltosvg(m))

<ipython-input-15-ba161ab9d915> in moltosvg(mol, molSize, kekulize)
     12         rdDepictor.Compute2DCoords(mc)
     13     drawer = rdMolDraw2D.MolDraw2DSVG(molSize[0],molSize[1])
---> 14     drawer.DrawMolecule(mc)
     15     drawer.FinishDrawing()
     16     svg = drawer.GetDrawingText()

ArgumentError: Python argument types in
    MolDraw2D.DrawMolecule(MolDraw2DSVG, Mol)
did not match C++ signature:
    DrawMolecule(RDKit::MolDraw2D {lvalue} self, RDKit::ROMol mol, boost::python::api::object highlightAtoms, boost::python::api::object highlightBonds, boost::python::api::object highlightAtomColors=None, boost::python::api::object highlightBondColors=None, boost::python::api::object highlightAtomRadii=None, int confId=-1)
    DrawMolecule(RDKit::MolDraw2D {lvalue} self, RDKit::ROMol mol, boost::python::api::object highlightAtoms=None, boost::python::api::object highlightAtomColors=None, boost::python::api::object highlightAtomRadii=None, int confId=-1)
```
I am lost because I don't know C/C++ or python bindings very well. Any hints as to what's going wrong or what I'm doing wrong?

(Side note: I don't know what this means, but I was looking through the source code I noticed that it appears (to my naive eyes) that there is [a duplicated piece of code here.](https://github.com/rdkit/rdkit/blob/26622c92d84fbd32bde8d1adb2d3281ad54b6f4e/Code/GraphMol/MolDraw2D/MolDraw2D.h#L75-L85))

Other helpful info:
```
Platform: OS X 10.10.5
IPython Version: 4.0.1
Python version: 3.4.3
RDkit version: rdkit 2015.09.1 py34_1 (downloaded from conda)
```

**Comment by dr-nate** [comment]
The good news is, reverting to 2015.03.1 resolves the problem

`conda install --channel https://conda.anaconda.org/aschreyer rdkit=2015.03.1`

**Comment by bp-kelley** [comment]
I'll see if I can verify the problem with python 34, this code should work in both places.

**Comment by ppxasjsm** [comment]
I noticed something similar.
I installed rdkit with conda:
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    rdkit-2015.09.1            |           py27_2        19.5 MB

The following NEW packages will be INSTALLED:

    rdkit: 2015.09.1-py27_2

```
Then a very simple:
```
from rdkit.Chem import AllChem
p = Chem.MolFromSmiles('Oc1ccccc1N2C(=O)Nc3cc(ccc23)C(F)(F)F')
AllChem.Compute2DCoords(p)
```
results in the following error:
```
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-25-b55b32a7cef9> in <module>()
----> 1 AllChem.Compute2DCoords(p)

ArgumentError: Python argument types in
    rdkit.Chem.rdDepictor.Compute2DCoords(Mol)
did not match C++ signature:
    Compute2DCoords(RDKit::ROMol {lvalue} mol, bool canonOrient=True, bool clearConfs=True, boost::python::dict {lvalue} coordMap={}, unsigned int nFlipsPerSample=0, unsigned int nSample=0, int sampleSeed=0, bool permuteDeg4Nodes=False, double bondLength=-1.0)
```

**Comment by greglandrum** [comment]
Would you mind giving it a try with the 2016.03.1 release? This should be available in the rdkit conda channel.

**Comment by dr-nate** [comment]
I can confirm this now works with the 2016.03.1 release (`conda install -c rdkit rdkit`) and anaconda python 3.5 and 2.7.

**Comment by dr-nate** [comment]
Although unfortunately it seems the image quality is very pixelated/low-res. Looks nothing like the images [shown here](http://www.rdkit.org/docs/GettingStartedInPython.html#drawing-molecules).

**Comment by greglandrum** [comment]
If you are seeing low-quality PNGs (and they really do look awful!), it typically means that cairo is not installed.

You have two options:
1) Install cairo. I did this on the Mac like this: `conda install -c richlewis cairocffi` (Thanks to @richlewis42  for this. I need to add a cairocffi Mac build to the rdkit conda channel)
2) Use SVGs instead of PNGs. You can do this by setting: `IPythonConsole.ipython_useSVG=True` in the notebook.

**Comment by dr-nate** [comment]
FYI, I get an error with that Cairo version:

```
In [10]: Draw.MolToFile(mol,'test.png',size=(800, 800))
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-f73b15163fb2> in <module>()
----> 1 Draw.MolToFile(mol,'test.png',size=(800, 800))

/Users/stanlen1/anaconda/lib/python3.5/site-packages/rdkit/Chem/Draw/__init__.py in MolToFile(mol, fileName, size, kekulize, wedgeBonds, imageType, fitImage, options, **kwargs)
    155   if options is None:
    156     options = DrawingOptions()
--> 157   useAGG,useCairo,Canvas = _getCanvas()
    158   if fitImage:
    159       options.dotsPerAngstrom = int(min(size) / 10)

/Users/stanlen1/anaconda/lib/python3.5/site-packages/rdkit/Chem/Draw/__init__.py in _getCanvas()
     15   if not os.environ.get('RDKIT_CANVAS',''):
     16     try:
---> 17       from rdkit.Chem.Draw.cairoCanvas import Canvas
     18       useCairo=True
     19     except ImportError:

/Users/stanlen1/anaconda/lib/python3.5/site-packages/rdkit/Chem/Draw/cairoCanvas.py in <module>()
     20 if six.PY3:
     21   try:
---> 22     import cairocffi as cairo
     23   except ImportError:
     24     import cairo

/Users/stanlen1/anaconda/lib/python3.5/site-packages/cairocffi/__init__.py in <module>()
     44 
     45 
---> 46 cairo = dlopen(ffi, 'cairo', 'cairo-2')
     47 
     48 

/Users/stanlen1/anaconda/lib/python3.5/site-packages/cairocffi/__init__.py in dlopen(ffi, *names)
     41             except OSError:
     42                 pass
---> 43     raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
     44 
     45 

```

**Comment by richlewis42** [comment]
@greglandrum I can do a pull request with the recipe for that binary, but I was not at all thorough with it, so it would need more attention (like a lot of the packages on my channel).  I'm not surprised it isn't working for everyone - I'm surprised it works at all actually!

@dr-nate It looks like `cairocffi` can't find the `cairo` library in your path.  I installed it using homebrew: 

```brew install cairo```

This should install the relevant libraries at `/usr/local/lib/libcairo.dylib`, which `cairocffi` should then be able to find.
 
I think we should eventually have a `cairo` conda package so that this isn't a dependency external to conda.

**Comment by richlewis42** [comment]
@greglandrum Oh I've just seen that there is already a cairocffi recipe already in rdkit-conda.  I'm not even sure if this is the one that I used to build this for mac, but it looks OK so no problem I guess!

**Comment by greglandrum** [comment]
@richlewis42 Yeah, I think I just need to do the build (and make sure that I figure out the cairo dependency part, which is a bit trickier)

**Comment by bp-kelley** [comment]
As a tip, a lot of these problems go away with:

IPythonConsole.ipython_useSVG=True

There are only a few bits left that don't make svg output.  Perhaps we should make a push to convert the rest :)

----
Brian Kelley

**Comment by rvianello** [comment]
@greglandrum with the last Anaconda release, Continuum published on GitHub the recipes for most of the free packages https://github.com/ContinuumIO/anaconda-recipes/ The recipe for for cairo looks like it's based on the corresponding one from conda-forge https://github.com/conda-forge/cairo-feedstock/tree/master/recipe (so this latter might at least provide a starting point for osx and windows)

**Comment by richlewis42** [comment]
@rvianello I tried building these (they work!), unfortunately `cairocffi` doesn't automatically detect the .dylib for the conda package (`ctypes.util.find_package` doesn't work well with anaconda on OS X).  There was talk in https://github.com/conda/conda/issues/1394 of patching find_package, which would be the perfect solution.

**Comment by dr-nate** [comment]
I installed cairo via: `conda install -c RMG cairo cairocffi`. However, note that this doesn't work with python 3.5. Hopefully someday this will all be consistent.

**Comment by pyeguy** [comment]
just fyi, i've been running into this issue on Windows (64bit) python 3.6 you can install both cairo and cairocffi via a combination of `conda` and `pip`

```
conda install -c conda-forge cairo
...
pip install cairocffi
```
and it's back to pretty pictures. 
 
interestingly the `IPythonConsole.ipython_useSVG=True` flag was causing an error, i'll raise a separate issue for it.
