### ISSUE TITLE
Stereo Annotation Appears Incorrect

### ISSUE THREAD

**Issue by lounsbrough** [rdkit/rdkit#7157]
**Describe the bug**
When rendering the molecule `C[S@@](=O)C1=CC=CC=C1`, MarvinJS and Biovia ChemDraw both render `(R)` (left):
![image](https://github.com/rdkit/rdkit/assets/8313853/6a7641fd-ab49-4d3c-91d3-3e796e5d8931)

RDKit renders the same molecule with `(S)` (right):
![image](https://github.com/rdkit/rdkit/assets/8313853/0a7da460-c3cb-4a69-b22b-39f6135e13e3)

**To Reproduce**
Render the smiles string `C[S@@](=O)C1=CC=CC=C1` with RDKit.

**Expected behavior**
I expect to see an `(R)` instead of an `(S)` chirality indicator.

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: [@rdkit/rdkit 2023.9.2-1.0.0](https://www.npmjs.com/package/@rdkit/rdkit/v/2023.9.2-1.0.0)
 - OS: MacOS (Node 20)
 - Python version (if relevant): N/A
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from? N/A
 - If you are not using conda: how did you install the RDKit? npm

**Additional context**

**Comment by ptosco** [comment]
If you call
```
Chem.SetUseLegacyStereoPerception(False)
```
such that the new chirality perception code is used, you will get the correct assignment:
```
from rdkit import Chem

Chem.SetUseLegacyStereoPerception(False)
mol = Chem.MolFromSmiles("C[S@@](=O)C1=CC=CC=C1")
Chem.FindMolChiralCenters(mol)
[(1, 'R')]
```

**Comment by lounsbrough** [comment]
We will move forward on our side by simply calling `rdkit.use_legacy_stereo_perception(false)`, and if you think it makes sense to make this default in the future we can remove this setup code from our app.

Thanks!

**Comment by lounsbrough** [comment]
Interestingly when I turn legacy mode off, the stereo indicators seem to not get rendered at all anymore.

**Comment by ptosco** [comment]
@lounsbrough The new stereo perception code does not call `Chem.AssignCIPLabels`, which are required by the drawing code to render stereo indicators:
```
from rdkit import Chem
from rdkit.Chem.Draw import IPythonConsole

IPythonConsole.drawOptions.addStereoAnnotation = True
Chem.SetUseLegacyStereoPerception(False)

mol = Chem.MolFromSmiles("C[S@@](=O)C1=CC=CC=C1")
for a in mol.GetAtoms():
    print(a.GetIdx(), list(a.GetPropNames(includePrivate=True, includeComputed=True)))
0 ['_chiralAtomRank']
1 ['_chiralAtomRank', '_ChiralityPossible']
2 ['_chiralAtomRank']
3 ['_chiralAtomRank']
4 ['_chiralAtomRank']
5 ['_chiralAtomRank']
6 ['_chiralAtomRank']
7 ['_chiralAtomRank']
8 ['_chiralAtomRank']
mol
```
![image](https://github.com/rdkit/rdkit/assets/5244385/9f9f2f6a-1211-48c3-ae90-152464f9aab1)

```
Chem.AssignCIPLabels(mol)
for a in mol.GetAtoms():
    print(a.GetIdx(), list(a.GetPropNames(includePrivate=True, includeComputed=True)))
0 ['_chiralAtomRank']
1 ['_chiralAtomRank', '_ChiralityPossible', '_CIPCode']
2 ['_chiralAtomRank']
3 ['_chiralAtomRank']
4 ['_chiralAtomRank']
5 ['_chiralAtomRank']
6 ['_chiralAtomRank']
7 ['_chiralAtomRank']
8 ['_chiralAtomRank']
mol
```
![image](https://github.com/rdkit/rdkit/assets/5244385/13e22a8d-0dde-4b0e-a591-6276cb4fa540)

Unfortunately `AddCIPLabels` is currently not called by the JS code at the moment - I will submit a PR to make sure it is called when legacy stereo perception is switched off. Thanks for reporting the issue.

**Comment by lounsbrough** [comment]
That sounds great, thank you so much.

**Comment by greglandrum** [comment]
@ptosco I've assigned this to the next patch release. Please let me know if there are API changes on the JS side that should push it to 2024.03.1

**Comment by ptosco** [comment]
@greglandrum I don't think there any API changes on the JS side - I have only exposed a few JSON drawing details that previously were not exposed (`noFreetype`, `panelWidth`, `panelHeight`) and the `assignCIPLabels` detail upon molecule creation, so it is fine to include this change in the next patch release.
