### ISSUE TITLE
Error when import PandasTools

### ISSUE THREAD

**Issue by DavidACosgrove** [rdkit/rdkit#7159]
**Describe the bug**
When I import PandasTools, I get the error message:
```
Failed to find the pandas get_adjustment() function to patch
Failed to patch pandas - PandasTools will have limited functionality
```
Then when I reproduce the gist https://gist.github.com/greglandrum/3b9da87a20e9b0d4827bbf1e64f68056 the molecule column isn't rendered:
![image](https://github.com/rdkit/rdkit/assets/9198870/953c2692-2433-4982-82a4-1c7c28afb98b)

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.4 and 2023.09.5
 - OS: MacOS Ventura 14.3 and Ubuntu 22.04 under WSL2
 - Python version (if relevant): 3.12
 - Are you using conda? mamba
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit? N/A

**Additional context**
The pandas version installed as part of the rdkit env is 2.2.0.

**Comment by ptosco** [comment]
@DavidACosgrove Ouch, it looks like something has changed in the `pandas` module. I'll look into fixing it - thanks for reporting the problem.

**Comment by AAriam** [comment]
Hi @ptosco,
I was having the same issue, so I took a look, found the problem, and submitted a PR that fixes it: #7165

**Comment by ptosco** [comment]
@AAriam Thank you, just approved!
@DavidACosgrove could you please check that applying
[https://patch-diff.githubusercontent.com/raw/rdkit/rdkit/pull/7165.diff](https://patch-diff.githubusercontent.com/raw/rdkit/rdkit/pull/7165.diff)
to your RDKit installation also fixes the problem at your end?
Thanks!

**Comment by DavidACosgrove** [comment]
@ptosco @AAriam Yes, that's working for me.  Many thanks for the speedy resolution.

**Comment by AceKnightWalker** [comment]
> @AAriam Thank you, just approved! @DavidACosgrove could you please check that applying https://patch-diff.githubusercontent.com/raw/rdkit/rdkit/pull/7165.diff to your RDKit installation also fixes the problem at your end? Thanks!

Could you kindly explain how to go about this? I got a similar message as David. Thank you.

**Comment by martinj80** [comment]
I tried the following code after applying the patch:
installed with conda 
Pandas 2.2.1
rdkit 2023.09.5

```
import pandas as pd
from rdkit import Chem
from rdkit.Chem import PandasTools

smiles = ['c1ccccc1', 'c1ccccc1O', 'c1cc(O)ccc1O']
df = pd.DataFrame({'ID':['Benzene', 'Phenol', 'Hydroquinone'], 'SMILES':smiles})
df['Mol Image'] = [Chem.MolFromSmiles(s) for s in df['SMILES']]
PandasTools.SaveXlsxFromFrame(df, 'test.xlsx', molCol='Mol Image')
```

and got 

`AttributeError: module 'pandas.io.formats.format' has no attribute 'get_adjustment'`

I believe there is still one part needing correction PandasPatcher.py:

```
def patchPandas():
...
  -> if getattr(pandas_formats.format, get_adjustment_name) != patched_get_adjustment:
  ->   setattr(pandas_formats.format, get_adjustment_name, patched_get_adjustment)
  #should be like this perhaps? 
  if getattr(pandas_formats.printing, get_adjustment_name) != patched_get_adjustment:
    setattr(pandas_formats.printing, get_adjustment_name, patched_get_adjustment)
...
```

**Comment by ptosco** [comment]
@martinj80 The fix will be available starting from 2023.09.6.
To get the current RDKit `conda` package to work you need to apply [this patch](https://patch-diff.githubusercontent.com/raw/rdkit/rdkit/pull/7165.diff) to your current installation.
You can do that as follows:
```
$ curl -L https://patch-diff.githubusercontent.com/raw/rdkit/rdkit/pull/7165.diff -o /tmp/7165.diff
$ cd $CONDA_PREFIX/lib/python3.*/site-packages
$ [ -e rdkit/Chem/PandasPatcher.py ] && patch -p1 < /tmp/7165.diff
```

**Comment by martinj80** [comment]
@ptosco 
Thank you for the response.

I applied the patch file already, but for some reason it did not help 100% (before the error message was different though). Only after I modified the lines I pointed out in my post it worked without errors.

**Comment by kjelljorner** [comment]
I also cannot get this to work

**Comment by kjelljorner** [comment]
That's what I did in the end, and it works, `pandas=2.1`. Just wanted to add some weight to @martinj80's suggestion that applying the patch as outlined by @ptosco in https://github.com/rdkit/rdkit/issues/7159#issuecomment-1971637963 is not enough.

**Comment by xg590** [comment]
The problem is you have a new version Pandas that RDKit does not know how to patch(work with). Downgrade the pandas to a version that RDKit is familiar with or upgrade RDKit if [greglandrum](https://github.com/greglandrum) does something to RDKit. For example, my RDKit is '2023.09.5' and it does not work with version 2.2.2 of Pandas. So I downgrade Pandas to 2.0.0. (I use the trial-and-error method to know which version works)
```shell
pip install pandas==2.0.0
```

**Comment by mainguyenanhvu** [comment]
Hi all, 
I face the error:
```
PandasTools.WriteSDF(pp, args.output_file, molColName='ID', properties=list(pp.columns))
  File "/scratch/micromamba/envs/biotools_py39/lib/python3.9/site-packages/rdkit/Chem/PandasTools.py", line 440, in WriteSDF
    mol = Chem.Mol(row[1][molColName])
RuntimeError: Bad pickle format: unexpected End-of-File while reading
```

I updated `pandas == 2.0.0` but it still errored.

Please help me to solve it.

My code here:
```
pp = pd.read_csv(args.input_file)
PandasTools.AddMoleculeColumnToFrame(pp,'smiles')
pp["Mol_H"] = pp["ROMol"].apply(Chem.AddHs)
pp["Mol_H"].map(AllChem.EmbedMolecule)
pprint(pp)
PandasTools.WriteSDF(pp, args.output_file, molColName='ID', properties=list(pp.columns))
```

**Comment by mainguyenanhvu** [comment]
Change to `PandasTools.WriteSDF(df, args.output_file, idName='AQID', properties=list(df.columns))` to fix this error.
