### ISSUE TITLE
ROMol.h getPropList with includeComputedProps is backwards

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#716]
```
  STR_VECT getPropList(bool includePrivate = true,
                       bool includeComputed = true) const {
    const STR_VECT &tmp = dp_props->keys();
    STR_VECT res, computed;
    if (!includeComputed &&
```

Should be includeComputed not !includeComputed I think...  Unfortunately changes the behavior unless we default includeComputed to false in the update.

**Comment by greglandrum** [comment]
I think it's ok. That logic (here's the link to the source: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/ROMol.h#L558) builds the list of computed properties, which are then used to exclude things from the results list here: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/ROMol.h#L564

So you only build the list of computed properties if you *don't* want them to be included in the result. Admittedly, the logic is a "bit" contorted.

**Comment by bp-kelley** [comment]
I just noticed that myself...  if adds to the list of stuff not to add :)
