### ISSUE TITLE
Colinear bonds in depiction cause stereo to be lost when converting to mol block 

### ISSUE THREAD

**Issue by mps-hlx** [rdkit/rdkit#7177]
Hi All,

We have noticed a change in behaviour between rdkit versions when writing and reading molblocks for compounds with a fused trycyclic ring. For example, in version `2023.09.01` importing the below structure from the SMILES below and casting to and from a MolBlock gives a warning and the stereo Hydrogen is lost in the SMILES. However, carrying out the same procedure with mapping to and from SMILES does not remove the stereo Hydrogen.

When running the same code in the previous version, `2023.03.03`, we do not get the warning and the stereo Hydrogen is still present.

Additional observations:
* Adding Hs to the structure preserves the stereo annotation
* `AllChem.Compute2DCoords` does not resolve the issue
* The presence of an aromatic ring is important, removing the aromatic ring and running the same code preserves the stereo H
* Using another toolkit such as `openbabel` to write to sdf does not lose the stereo H when importing the file with RDKit

### Steps to Reproduce
```Python
In [1]: !pip install rdkit==2023.09.01
In [2]: import rdkit
   ...: from rdkit import Chem
   ...: from rdkit.Chem import AllChem
In [3]: rdkit.__version__
Out[3]: '2023.09.1'
In [4]: smi_simple = "C([C@H]1CC3CCC1CC3)(c4ccccc4)"
   ...: smi_no_issue = "C([C@H]1CC3CCC1CC3)C"
In [5]: def mol_to_molblock_and_back(mol):
   ...:     return Chem.MolFromMolBlock(Chem.MolToMolBlock(mol))
In [6]: mol_simple = Chem.MolFromSmiles(smi_simple)
In [7]: mol_issue = mol_to_molblock_and_back(mol_simple)  # creates issue
[15:06:23] Warning: ambiguous stereochemistry - linear bond arrangement - at atom 1 ignored
In [8]: Chem.MolToSmiles(mol_issue)
Out[8]: 'c1ccc(CC2CC3CCC2CC3)cc1'
In [9]: mol_with_hs = Chem.AddHs(mol_simple)  # adding Hs fixes issue
In [10]: Chem.MolToSmiles(mol_to_molblock_and_back(mol_with_hs))
Out[10]: 'c1ccc(C[C@H]2CC3CCC2CC3)cc1'
In [11]: AllChem.Compute2DCoords(mol_simple)  # Compute Coords does not get expected output
   ...: print(Chem.MolToSmiles(mol_to_molblock_and_back(mol_simple)))
[15:31:21] Warning: ambiguous stereochemistry - linear bond arrangement - at atom 1 ignored
c1ccc(CC2CC3CCC2CC3)cc1
In [12]: Chem.MolToSmiles(mol_to_smiles_and_back(mol_no_issue))  # removing aromatic ring does not have same issue
Out[12]: 'CC[C@H]1CC2CCC1CC2'
```
However, in the previous version:
```Python
In [1]: !pip install rdkit==2023.03.03
In [2]: import rdkit
   ...: from rdkit import Chem
In [3]: rdkit.__version__
Out[3]: '2023.03.3'
In [4]: def mol_to_molblock_and_back(mol):
   ...:     return Chem.MolFromMolBlock(Chem.MolToMolBlock(mol))
   ...:
In [5]: smi_simple = "C([C@H]1CC3CCC1CC3)(c4ccccc4)"
In [6]: mol_simple = Chem.MolFromSmiles(smi_simple)
In [7]: mol =  mol_to_molblock_and_back(mol_simple)
In [8]: Chem.MolToSmiles(mol)  # stereo preserved
Out[8]: 'c1ccc(C[C@H]2CC3CCC2CC3)cc1'
```

Thanks for your time!

### Expected behavior:
Stereo H should be preserved in Mol object after exporting to MolBlock and importing from MolBlock.

Configuration:
* RDKit version: 2023.9.1
* OS: MacOS and Linux
* Python version (likely not relevant): 3.10.12
* Are you using conda? No

**Comment by greglandrum** [comment]
@mps-hlx Thanks for the detailed bug report.
What's happening here is that the coordinates being generated when you convert the molecule to a mol block have a geometry at the chiral center that the RDKit cannot later interpret. Here's what the coordinates look like:
![image](https://github.com/rdkit/rdkit/assets/540511/eb3cb639-68a6-4a21-94af-be3bb98973cb)
The problem is that the bonds from atom 1 to atom 6 and atom 1 to atom 2 are co-linear

**Comment by greglandrum** [comment]
One work-around here is to switch to using coordgen to generate the 2D coordinates:
```
from rdkit.Chem import rdDepictor
rdDepictor.SetPreferCoordGen(True)
```

**Comment by mps-hlx** [comment]
Thanks for your clear explanation! 

As this appears to set a global C++ variable, should this be set immediately after the imports? We noticed the behaviour in our compound standardization pipeline so downstream depiction issues are not a problem in our use case.

Additionally, is this expected behaviour in 2023.09.x and onwards? If so I am happy to add some documentation but not sure where would be best. 

Thanks again!

**Comment by greglandrum** [comment]
I've changed this from "bug" to "enhancement" since the previous behavior was intentional.
The next major release (in a couple of weeks) will include this new behavior

**Comment by mps-hlx** [comment]
Thanks for all your efforts with this! In the meantime we have used the workaround you suggested and will update for the next major release.
