### ISSUE TITLE
EmbedMultipleConfs coordMap problem

### ISSUE THREAD

**Issue by kylin20230207** [rdkit/rdkit#7181]
**Describe the bug**

When I use the coordMap option of EmbedMultipleConfs to generate small molecule conformations, the generated small molecules are not completely aligned together as expected, but produce two clusters of conformations similar to mirror images.

**To Reproduce**
```from rdkit import Chem
from rdkit.Chem import AllChem, rdMolDescriptors
from rdkit.Chem.AllChem import AlignMol

reference_mol = Chem.SDMolSupplier("ligand.sdf")[0]
mcs_mol = Chem.MolFromSmiles("NC(NC1=CC=C(OC(F)(F)F)C=C1)=O")
cry_match = reference_mol.GetSubstructMatch(mcs_mol)
name = "alignment"
smiles = "CN(C1CCN(C(=O)Nc2ccc(OC(F)(F)F)cc2)CC1)S(C)(=O)=O"

def align(name,smiles):
    simi_mol  = Chem.MolFromSmiles(smiles)
    candi_matches = simi_mol.GetSubstructMatches(mcs_mol)
    for match_idx,candi_match in enumerate(candi_matches):
        match = list(zip(candi_match, cry_match))
        print(match)
        cmap = {pi: reference_mol.GetConformer().GetAtomPosition(xi) 
            for pi, xi in match}
        mol = Chem.Mol(simi_mol)
        mol = Chem.AddHs(mol)
        code = AllChem.EmbedMultipleConfs(mol, coordMap=cmap, numConfs=100)
        keep=[]
        for index, t in enumerate(code):
            conf = mol.GetConformer(t)
            new_mol = Chem.Mol(mol)
            new_mol.RemoveAllConformers()
            new_mol.AddConformer(Chem.Conformer(conf))
            rms = AlignMol(new_mol, reference_mol, atomMap=match)
            # print(index,rms)
            keep.append(new_mol)
        w1 = Chem.SDWriter(f"{name}.sdf")
        for m in keep:
            w1.write(m)
        w1.close()
align(name,smiles)
```

**Screenshots**
![image](https://github.com/rdkit/rdkit/assets/124643301/d8e90950-3732-4884-b541-50076ef53bd4)
---
input file:[ligand.sdf.txt](https://github.com/rdkit/rdkit/files/14371358/ligand.sdf.txt)
output file:[alignment.sdf.txt](https://github.com/rdkit/rdkit/files/14371356/alignment.sdf.txt)

**Comment by greglandrum** [comment]
@kylin20230207 there is a two-fold symmetry in the phenyl ring in your template. This can map onto your molecule two possible ways. I think that what you are seeing here is the result of the two possible mappings.

To handle this, you need to try all the symmetry-redundant matches when you do the final alignment. Something like this:

```
def align(name,smiles):
    simi_mol  = Chem.MolFromSmiles(smiles)
    candi_matches = simi_mol.GetSubstructMatches(mcs_mol)
    all_matches = simi_mol.GetSubstructMatches(mcs_mol,uniquify=False)
    for match_idx,candi_match in enumerate(candi_matches):
        match = list(zip(candi_match, cry_match))
        print(match)
        cmap = {pi: reference_mol.GetConformer().GetAtomPosition(xi) 
            for pi, xi in match}
        mol = Chem.Mol(simi_mol)
        mol = Chem.AddHs(mol)
        code = AllChem.EmbedMultipleConfs(mol, coordMap=cmap, numConfs=100)
        keep=[]
        for index, t in enumerate(code):
            bestRMS = 1e8
            bestMatch = -1
            for local_idx,local_match in enumerate(all_matches):
                local_match = list(zip(local_match, cry_match))
                rms = AlignMol(mol, reference_mol, prbCid=t, atomMap=local_match)
                if rms<bestRMS:
                    bestRMS = rms
                    bestMatch = local_idx
            # realign to the best match
            local_match = list(zip(all_matches[bestMatch], cry_match))
            rms = AlignMol(mol, reference_mol, prbCid=t, atomMap=local_match)
```
the resulting conformers are now better aligned on the core:
![image](https://github.com/rdkit/rdkit/assets/540511/b91bc026-4f57-4841-a4f8-bf32f105b910)

**Comment by qcxia20** [comment]
@greglandrum I have a question. Since all conformers are generated with a constrain on the coordinates of the substructure ("NC(NC1=CC=C(OC(F)(F)F)C=C1)=O") of an input molecule, should all conformers have a similar conformation at least in this substructure (I mean, all generated conformers are expected to superimpose together at the given single substructure conformation)? But now it seems that two different substructure conformation (one near to the input and one seems mirror to the input) were generated. Since the conformation of the substructure is different (mirror to each other), no matter how we align the substructure, they cannot superimpose.
I've used Chimera to align two representative conformers here, and the substructure conformers clearly cannot superimpose together.

![image](https://github.com/rdkit/rdkit/assets/56123242/67aea881-61a4-4581-8a4b-b2b780ac598b)

**Comment by greglandrum** [comment]
@kylin20230207 : This morning I spent some more time looking at this and realized that my answer above is not correct.

When you use ETKDG together with the coordMap, you can end up with ET terms acting within the atoms of the coordMap which distort the structure. This is wrong.

Here's a simpler demonstration of this:
```
m = Chem.MolFromSmiles('COc1ccc(NC(C)C)cc1')
template = Chem.MolFromSmiles('COc1ccc(NC)cc1')
template_h = Chem.AddHs(template)

ps = rdDistGeom.ETKDGv3()
ps.randomSeed = 0xC0FFEE
rdDistGeom.EmbedMolecule(template_h,ps)
rdMolTransforms.SetDihedralDeg(template_h.GetConformer(),0,1,2,3,120)


conf = template_h.GetConformer()

cmap = {}
match = m.GetSubstructMatch(template)
for ti,mi in enumerate(match):
    cmap[mi] = conf.GetAtomPosition(ti)

    
for ps,lbl in [(rdDistGeom.EmbedParameters(),'DG'),
              (rdDistGeom.KDG(),'KDG'),
              (rdDistGeom.ETKDGv3(),'ETKDG')]:

    m_h = Chem.AddHs(m)
    ps.randomSeed = 0xC0FFEE
    ps.verbose = True
    ps.SetCoordMap(cmap)

    rdDistGeom.EmbedMolecule(m_h,ps)

    amap = [(y,x) for x,y in enumerate(match)]
    rms = AlignMol(m_h, template_h, prbCid=0, atomMap=amap)
    print(f'{lbl}:', rms)
```
The output for me is:
![image](https://github.com/rdkit/rdkit/assets/540511/24d11e1f-1e0a-4ae7-8bea-4572fcab3f12)

The first torsion shown there should not be being applied.

**Comment by kylin20230207** [comment]
@greglandrum ：Thank you very much for your patient response.
