### ISSUE TITLE
SMARTS substructure matching failed for spiro compounds

### ISSUE THREAD

**Issue by sunghunbae** [rdkit/rdkit#7184]
`Chem.GetSubstructMatches()` using a SMARTS pattern is incomplete for the below spiro compounds.

```
from rdkit import rdBase
from rdkit.Chem import Draw

print(f"RDKit {rdBase.rdkitVersion}")

mol1 = Chem.MolFromSmiles("C12=C(C=CC=C2)C=CC3(O1)CCCCC3")
mol2 = Chem.MolFromSmiles("C12=C(C=CC=C2)N=CC3(O1)CCCCC3")

for mol in [mol1, mol2]:
    for i, atom in enumerate(mol.GetAtoms()):
        atom.SetProp("atomNote", str(atom.GetIdx()))
    
patt_1 = Chem.MolFromSmarts('[#6x3R2][#6x3R2][#6][#6]')
matches_1 = sum(mol1.GetSubstructMatches(patt_1), ())
patt_2 = Chem.MolFromSmarts('[#6x3R2][#6x3R2][#7][#6]')
matches_2 = sum(mol2.GetSubstructMatches(patt_2), ())

Draw.MolsToGridImage([mol1, mol2], highlightAtomLists=[matches_1, matches_2])
```
<img width="203" alt="Capture" src="https://github.com/rdkit/rdkit/assets/6590938/f6c36ea0-0213-495b-b9fd-8bec502f82e4">

**Expected behavior**
Atoms 6 and 7 should be in the matched atoms

**Configuration (please complete the following information):**
 - RDKit version: rdkit 2023.09.5
 - OS: Linux

**Comment by DavidACosgrove** [comment]
There’s a double bond between the N and the C in the molecule and not in the SMARTS so it’s correct that no match is reported.

**Comment by greglandrum** [comment]
I agree with @DavidACosgrove

**Comment by greglandrum** [comment]
@sunghunbae please let us know if we have misunderstood something
