### ISSUE TITLE
Expose generateOneProductSet?

### ISSUE THREAD

**Issue by DoliathGavid** [rdkit/rdkit#721]
Can we expose generateOneProductSet and other primitives in ReactionRunner.cpp? It's especially useful as an entry point for cool transformations.

**Comment by greglandrum** [comment]
@DoliathGavid : can you give a couple of examples of what you mean?

**Comment by DoliathGavid** [comment]
There's several:

-I have different ways of generating matches than ones from SubstructMatch.
-I also have different ways of generating the initial list of reactants that's passed into generateOneProductSet that's very different from RunReactants (Which generates using permutations as far as I can tell, ie. given a pattern A+B->C, and reactants A' and B' that each match A,B two ways A1 A2, B1, B2, RunReactants returns all resulting product combinations: A1B1 A2B1 A1B2 A2B2). In cases where there's many multiple reactants, ABCDE, of which each map 9 degenerate ways: you'd get something like 1953125 products back. And RunReactant can be too limiting in that it just mutates one of them.

**Comment by greglandrum** [comment]
Sounds reasonable. `generateOneProductSet()` is straightforward to call from client code and doesn't require a lot of understanding of the details of how the rest of the code works.
Any other pieces there that you think would be useful?

**Comment by DoliathGavid** [comment]
I think generateOneProduct is the only one I need for now, PR here: #722

**Comment by DoliathGavid** [comment]
actually having initProduct is also generally useful due to its ability to convert a mol comprised of QueryAtoms into a regular mol. Calling it initProduct is kind of a misnomer, I'd rather call it convertQueryMolToNormalMol or something less verbose.
