### ISSUE TITLE
CanonicalRankAtoms has a wrong C++ signature

### ISSUE THREAD

**Issue by iliqKichev** [rdkit/rdkit#7242]
**Describe the bug**
In the `Python` documentation on `rdkit.Chem.rdmolfiles.CanonicalRankAtoms` it is stated that the C++ signature is the same, but such function is nowhere to be found. This name appears only in `GraphMol/Wrap/rdmolfiles.cpp` and the function calls `rankMolAtoms`.

**Comment by greglandrum** [comment]
@iliqKichev it's not clear what you mean here.

If you are talking about the C++ signature shown in the automatically generated documentation: https://rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.CanonicalRankAtoms
![image](https://github.com/rdkit/rdkit/assets/540511/f0a1233f-617f-4018-8ead-3fe7b54e76cb)

This is the signature of the C++ function which is exposed to Python; it's not intended to document the C++ API

**Comment by iliqKichev** [comment]
Okay, I thought the C++ signatures are part of the C++ documentation. But still, in most other cases the RDKit documentation is consistent between the Python and the C++ APIs. In this instance it is not. This is not something that is guaranteed, I understand. Closing the issue.
