### ISSUE TITLE
CXSMARTS Parsing Issue in Database Cartridge

### ISSUE THREAD

**Issue by lounsbrough** [rdkit/rdkit#7276]
**Describe the bug**
There are some `CXSMARTS` strings which RDKit is not wanting to parse. RDKit throws an error: `SQL Error [22000]: ERROR: could not create molecule from SMILES '[#62,#73,#77]-[#6]-1=[#6]-[#6]=[#6]-[#6]=[#6]-1 |c:3,5,t:1|'
  Position: 8`

**To Reproduce**
Run this sql:
```sql
SELECT '[#62,#73,#77]-[#6]-1=[#6]-[#6]=[#6]-[#6]=[#6]-1 |c:3,5,t:1|'::qmol
```

**Expected behavior**
It should generate a valid qmol for the input molecule:
![image](https://github.com/rdkit/rdkit/assets/8313853/0a1cd811-e97e-4034-b8fb-346b003c370f)

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.4 (output of rdkit_toolkit_version cartridge function)
 - OS: [e.g. Ubuntu 20.04]: Postgres 16

**Comment by greglandrum** [comment]
This is actually an invalid CXSMARTS. The `t` at the end attempts to mark a single bond as trans, but this is not allowed.
You can see the specific error message from Python:
```
In [2]: m = Chem.MolFromSmarts('[#62,#73,#77]-[#6]-1=[#6]-[#6]=[#6]-[#6]=[#6]-1 |c:3,5,t:1|')
[19:49:48] bond 1 not found, cannot mark as stereo double bond.
```
