### ISSUE TITLE
Dative bond to B and Al 

### ISSUE THREAD

**Issue by jhjensen2** [rdkit/rdkit#7282]
`Chem.MolFromSmiles('CB(C)(C)<-O=C')` returns Explicit valence for atom # 1 B, 4, is greater than permitted, i.e. it is treated as a real bond.

`Chem.MolFromSmiles('C[Al](C)(C)<-O=C')` works, but a radical electron is assigned to Al.

**Comment by greglandrum** [comment]
The code is behaving as expected: the dative bond to the B atom contributes to the valence of the B, making it hypervalent.

The standard RDKit sanitization does not support hypervalent B; you need to use custom sanitization for this.
