### ISSUE TITLE
The serialization of porphyrin to mol format introduces some double bonds with bond stereo 3/either

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#7306]
**Describe the bug**
Loading a structure containing a porphyrin into an RDKit molecule instance and rewriting it to mol format introduces some  double bonds with bond stereo 3/either

**To Reproduce**

    In [1]: from rdkit import Chem
    
    In [2]: print(Chem.MolToMolBlock(Chem.MolFromMolFile('./input.mol')))

[input.zip](https://github.com/rdkit/rdkit/files/14775313/input.zip)

**Configuration (please complete the following information):**
 - RDKit version: current tip of the master branch (I presume the issue may also affect the 2024.03.1 beta)
 - OS: Fedora 39
 - If you are not using conda: how did you install the RDKit? from source code

**Comment by greglandrum** [comment]
Here's what's happening:
The ring bonds are all aromatic, so the fact that the stereochemistry is known is not used and they are unspecified.
The molecule is kekulized before writing it to a mol block and the writer then happily marks each of the new double bonds that are in the larger ring as unknown.

The solution is to modify the mol block writer to keep track of which bonds were originally aromatic and not write stereo tags for them.

**Comment by greglandrum** [comment]
resolved in #7510

**Comment by rvianello** [comment]
Thank you, @greglandrum
