### ISSUE TITLE
About the rotational orientation of branched chains？

### ISSUE THREAD

**Issue by pengxy0** [rdkit/rdkit#7310]
**Describe the bug**
We want to change the branched orientation of the left benzene ring structure to the right one, which has rotational symmetry. I would like to ask how this goal can be achieved in RDKit with a function or with another script.

![image](https://github.com/rdkit/rdkit/assets/130196652/09c4f6e9-e740-48de-beb9-8953087fdb3b)

**Comment by greglandrum** [comment]
I'm closing this because it is a question, not a bug report or enhancement request.
Please ask questions using the "Discussions" tab.
