### ISSUE TITLE
Incorrect ring information for disubstituted rings

### ISSUE THREAD

**Issue by SSNam14** [rdkit/rdkit#7333]
**Describe the bug**
Get atom indices via GetRingInfo() gives some indices that are not in ring.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import Draw

smiles = 'CCc1ccc(C)cc1'
mol = Chem.MolFromSmiles(smiles)
newsmiles = Chem.MolToSmiles(mol, canonical=True)
mol = Chem.MolFromSmiles(newsmiles)
for atom in mol.GetAtoms():
    atom.SetProp('atomNote', str(atom.GetIdx()))

ri = mol.GetRingInfo().BondRings()
print(ri)

print("Atom number 5 is in ring?", mol.GetAtomWithIdx(5).IsInRing())
print("Atom number 6 is in ring?", mol.GetAtomWithIdx(6).IsInRing())

display(mol)
```

**Expected behavior**
`ri` should be ((8, 7, 5, 4, 3, 2),)

**Screenshots**
```
((8, 7, 6, 4, 3, 2),) 
Atom number 5 is in ring? True #This is correct
Atom number 6 is in ring? False #This is correct
```
![image](https://github.com/rdkit/rdkit/assets/166084027/6a0923ee-0ccc-4b66-8fff-c9dd913d02d5)

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.5 (It also seems to happen in older versions)
 - OS: [e.g. Ubuntu 20.04] Windows
 - Python version (if relevant): 3.12
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? via pip

**Comment by greglandrum** [comment]
@SSNam14 what do you think the bug here is? You are printing out the indices of the bonds in the ring and then asking the atoms whether or not they are in a ring

**Comment by SSNam14** [comment]
Opps, I thought `BondRings()` gives atom index that are in ring, I apologize. `AtomRings()` work as I intended.
