### ISSUE TITLE
Can't kekulize mol

### ISSUE THREAD

**Issue by 1641004802** [rdkit/rdkit#7343]
Using the MolToSmiles generates this：Cc1ccc2c(c1)-n1-c(=O)/c=c\c(=O)-n-2-c2cc(C)ccc2-1
But using MolFromSmiles('Cc1ccc2c(c1)-n1-c(=O)/c=c\c(=O)-n-2-c2cc(C)ccc2-1') leading to Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5 6 10 11 15 16 17 19 20 21
and using ExactMolWt(MolFromSmiles('Cc1ccc2c(c1)-n1-c(=O)/c=c\c(=O)-n-2-c2cc(C)ccc2-1'))

ArgumentError: Python argument types in
    rdkit.Chem.rdMolDescriptors.CalcExactMolWt(NoneType)
did not match C++ signature:
    CalcExactMolWt(RDKit::ROMol mol, bool onlyHeavy=False)
[error.txt.txt](https://github.com/rdkit/rdkit/files/14926665/error.txt.txt)

**Comment by greglandrum** [comment]
The reason for this is described in the FAQ: https://github.com/rdkit/rdkit/wiki/FrequentlyAskedQuestions#cant-kekulize-mol

**Comment by 1641004802** [comment]
The point is：Mol ->SMILES, OK
SMILES->Mol, not OK
Why?
