### ISSUE TITLE
Suppress DeprecationWarning

### ISSUE THREAD

**Issue by alexub** [rdkit/rdkit#7349]
I am using Datamol to compute fingerprints:
```
fp = datamol.to_fp(mol, fp_type='ecfp-count', radius=radius, nBits=num_bits)
```
Under the hood, this calls into RDKit to generate the fingerprint. When calling this on thousands of molecules, I get thousands of lines of:
```
[23:10:23] DEPRECATION WARNING: please use MorganGenerator
```
Can I suppress these warnings?

I have tried 
```
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
```
but this doesn't work, probably because this warning is raised by a C++ extension w/o using the standard warnings module

**Comment by greglandrum** [comment]
Please ask the datamol team to update how they calculate fingerprints

**Comment by alexub** [comment]
Yes, obviously that is the best long-term solution. 

In the meantime, and in other cases where it might be temporarily necessary to use a function which raises a warning, it would be awesome if there was a way for the user to control or suppress logging verbosity from RDKit. 

I am guessing "no", but do you know if there is any way to do this?

**Comment by greglandrum** [comment]
Sure. The deprecation warnings are generated using the RDKit's standard C++ logging code and can be suppressed by disabling the warning log:
```
n [4]: fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(m,2)
[09:56:28] DEPRECATION WARNING: please use MorganGenerator

In [5]: from rdkit import rdBase

In [6]: rdBase.DisableLog('rdApp.warning')

In [7]: fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(m,2)

In [8]: 
```

**Comment by alexub** [comment]
Awesome, thank you!
