### ISSUE TITLE
SMILES output option to disable the RDKit dative bond syntax

### ISSUE THREAD

**Issue by johnmay** [rdkit/rdkit#7372]
The recent addition of ``SANITIZE_CLEANUP_ORGANOMETALLICS`` (https://github.com/rdkit/rdkit/pull/6357) means many ``->`` and ``<-`` now appear in SMILES output from RDKit and causes issues in NextMove Software tools (specifically NameRxn). We can turn this off during sanitization but I think the cleaner API is to make this a SMILES output option. Ideally this would be **OFF** by default such that the SMILES generated by RDKit can be safely consumed by other tools without modification. As it is now you will not be able paste in output in to ChemDraw or Marvin or indeed (m)any other tools.

```
>>> Chem.MolToSmiles(Chem.MolFromSmiles('[NH3][Pt][NH3]'))
'N->[Pt]<-N'
```

To emphasize my "point of view" what does RDKit make of the similar behaviour in Indigo?

```java
Indigo indigo = new Indigo();
IndigoObject mol = indigo.loadMolecule("NCCO |Sg:n:1,2:n:ht|");
indigo.setOption("smiles-saving-format", "chemaxon");
System.out.println(mol.smiles() + " chemaxon");
indigo.setOption("smiles-saving-format", "daylight");
System.out.println(mol.smiles() + " daylight");
```

```
NCCO |Sg:n:1,2:n:ht| chemaxon
NC{-}C{+n}O daylight
```

Does RDKit accept what Indigo calls "daylight" SMILES?

Other comments:
- CXSMILES has an option for dative bonds which is more widely supported
- I'm not keen on the syntax of using the '>' for anything other than reactions.
- If ``SanitizeMol`` can automatically add them in easily, what is the benefit in storing them?

**Comment by greglandrum** [comment]
I think adding support for a flag to disable this extension is completely reasonable and will get something in.
