### ISSUE TITLE
Some SMARTS patterns from CDK are not working in RDKit

### ISSUE THREAD

**Issue by j-adamczyk** [rdkit/rdkit#7392]
**Describe the bug**

I am trying to reimplement Chemistry Development Toolkit (CDK) [SubstructureFingerprinter](https://cdk.github.io/cdk/1.5/docs/api/org/openscience/cdk/fingerprint/SubstructureFingerprinter.html) in RDKit. Out of 307 SMARTS patterns there, 304 are working well, but I get `None` for:
*&#47[D2]=[D2]/*
*&#47[D2]=[D2]/*
([-1,-2,-3,-4,-5,-6,-7]).([+1,+2,+3,+4,+5,+6,+7])
```

**To Reproduce**
```
patterns = [
    "*&#47[D2]=[D2]/*",
    "*&#47[D2]=[D2]/*",
    "([-1,-2,-3,-4,-5,-6,-7]).([+1,+2,+3,+4,+5,+6,+7])"
]
for pattern in patterns:
    print(MolFromSmarts(pattern))
```

**Expected behavior**
Regular molecules created from SMARTS patterns, for substructure matching.

**Configuration (please complete the following information):**
 - RDKit version: 2023.9.5
 - OS: Ubuntu 22.04
 - Python version (if relevant): 3.11
 - Are you using conda? no
 - If you are not using conda: how did you install the RDKit? pip

**Comment by mcs07** [comment]
For the first two, this looks like an escaping issue in the CDK docs. Take a look at the CDK source directly at https://github.com/cdk/cdk/blob/main/descriptor/fingerprint/src/main/resources/org/openscience/cdk/fingerprint/data/SMARTS_InteLigand.txt

I think you want `*/[D2]=[D2]\*` and `*/[D2]=[D2]/*` which both work fine with `MolFromSmarts`.

**Comment by mcs07** [comment]
For `([-1,-2,-3,-4,-5,-6,-7]).([+1,+2,+3,+4,+5,+6,+7])`, the [RDKit docs](https://www.rdkit.org/docs/RDKit_Book.html#smarts-support-and-extensions) have a list of "SMARTS features that are not supported" which includes "component level grouping requiring matches in different components, i.e. (C).(C)".

**Comment by j-adamczyk** [comment]
@mcs07 I totally missed that, thanks!
