### ISSUE TITLE
RDKit Release_2024_03_1 not available on pypi

### ISSUE THREAD

**Issue by c-w-feldmann** [rdkit/rdkit#7399]
**Describe the bug**
It seems that the latest versions of RDKit are not available on [pypi](https://pypi.org/project/rdkit/). The last available version is 2023.9.6 

**To Reproduce**
pip install rdkit==2024.03.1

**Expected behavior**
It would be nice of the latest versions would be available on pypi

**Screenshots**  
  None

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.1
 - OS: Ubuntu
 - Using conda installing from pypi

**Comment by greglandrum** [comment]
This is not an RDKit bug. We don't provide the pypi binaries.
Check here: https://github.com/kuelumbus/rdkit-pypi

**Comment by c-w-feldmann** [comment]
I was not aware of that. Since you were there listed as first maintainer I assumed it belonged here. Thanks for the quick response!

**Comment by thegodone** [comment]
Is there a way or instructions to build pip install ?Envoyé de mon iPhoneLe 29 avr. 2024 à 10:39, c-w-feldmann ***@***.***> a écrit :﻿
I was not aware of that. Since you were there listed as first maintainer I assumed it belonged here. Thanks for the quick response!
