### ISSUE TITLE
Molecular graphics are overlaid

### ISSUE THREAD

**Issue by jaechang-hits** [rdkit/rdkit#7400]
**Describe the bug**

When I draw the molecules whose smiles are

```
Cc1cc(C(=O)O)cc2sc(N3C4CCC3CC(OCc3c(-c5ccccc5OC(F)(F)F)noc3C3CC3)C4)nc12
```

and

```
Cc1c2c(sc(n2)N2C3CC(CC2CC3)OCc2c(C3CC3)onc2-c2c(OC(F)(F)F)cccc2)cc(C(O)=O)c1
```

,
Molecular graphics are overlaid as follow:

![image](https://github.com/rdkit/rdkit/assets/81952662/020f6045-6632-4f6c-af7e-d9afbdeede84)
The same problem occurs in rdkit javascript ( [https://www.rdkitjs.com/](https://www.rdkitjs.com/))

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import Draw

m1 = Chem.MolFromSmiles(
    "Cc1cc(C(=O)O)cc2sc(N3C4CCC3CC(OCc3c(-c5ccccc5OC(F)(F)F)noc3C3CC3)C4)nc12"
)
m2 = Chem.MolFromSmiles(
    "Cc1c2c(sc(n2)N2C3CC(CC2CC3)OCc2c(C3CC3)onc2-c2c(OC(F)(F)F)cccc2)cc(C(O)=O)c1"
)

img = Draw.MolsToGridImage([m1, m2], molsPerRow=4)
img.save("test.png")

```

**Expected behavior**
Normal image

**Screenshots**

**Configuration (please complete the following information):**

- RDKit version: 2023.09.5
- OS: [e.g. Ubuntu 20.04]
- Python version (if relevant): 3.10
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? pip install
- If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by greglandrum** [comment]
These are molecules that it's really hard to generate 2D coordinates for.
Your best bet is to switch to using coordgen for 2D coordinate generation:
```
rdDepictor.SetPreferCoordGen(True)
Draw.ShowMol(m1)
```

**Comment by greglandrum** [comment]
I'm closing this since there's a workaround and we don't have immediate plans to make changes to the RDKit's base coordinate generation code.
