### ISSUE TITLE
MolsMatrixToGridImage() ignores useSVG and returnPNG arguments

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#7402]
**Describe the bug**
The arguments are not passed along to `MolsToGridImage`

**Configuration (please complete the following information):**
 - RDKit version: master and release
 - OS: all

**Comment by bertiewooster** [comment]
Thanks @greglandrum for fixing my oversight when I added `MolsMatrixToGridImage()`--I included `useSVG` and `returnPNG` in the signature and docstring, yet forgot to pass them to `MolsToGridImage()`.
