### ISSUE TITLE
Planar amide nitrogen incorrectly flagged as _ChiralityPossible

### ISSUE THREAD

**Issue by mark-cresset** [rdkit/rdkit#7434]
If you have a molecule with a lactam, where the amide nitrogen is a ring bridgehead, then Chem.AssignStereochemistry incorrectly assigns the amide nitrogen as "_ChiralityPossible" even though it's flat.

**To Reproduce**
```
from rdkit import Chem
rdmol=Chem.MolFromSmiles("O=C1CCCCC[C@@H]2CN1CCO2")
Chem.AssignStereochemistry(rdmol, force=True, flagPossibleStereoCenters=True)
for atom_idx, atom in enumerate(rdmol.GetAtoms()):
   if atom.GetChiralTag() == Chem.ChiralType.CHI_UNSPECIFIED and atom.HasProp(
                "_ChiralityPossible"
            ):
       print(atom_idx)
```
**Expected behavior**
The nitrogen is not marked as potentially chiral, as it's flat.

**Configuration (please complete the following information):**
 - RDKit version: 2022.09.03

**Additional context**
This is causing issues in OpenFF, which checks that the chirality of the molecule is fully specified and refused to proceed unless it is.

**Comment by greglandrum** [comment]
confirmed
