### ISSUE TITLE
Could not sanitize molecule ending

### ISSUE THREAD

**Issue by 1641004802** [rdkit/rdkit#7452]
When processing the NIST17 mainlib，it occurs：
<img width="491" alt="屏幕截图 2024-05-21 113112" src="https://github.com/rdkit/rdkit/assets/68485539/426c3e59-19fc-4f8b-a1aa-7f639c1b7649">
The file is showed below，I want to know that whether the format is wrong or the structure itself is wrong.
[1.txt](https://github.com/rdkit/rdkit/files/15384182/1.txt)

**Comment by bp-kelley** [comment]
The format is fine, the structure is weird

<img width="394" alt="image" src="https://github.com/rdkit/rdkit/assets/9888416/70f8fb8e-5c54-46bb-b54f-bb238de72af9">

**Comment by 1641004802** [comment]
> The format is fine, the structure is weird
> <img alt="image" width="394" src="https://private-user-images.githubusercontent.com/9888416/332558890-70f8fb8e-5c54-46bb-b54f-bb238de72af9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDA0MzgsIm5iZiI6MTcxNjM0MDEzOCwicGF0aCI6Ii85ODg4NDE2LzMzMjU1ODg5MC03MGY4ZmI4ZS01YzU0LTQ2YmItYjU0Zi1iYjIzOGRlNzJhZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDEwODU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E5MjMwZWMxMzBiZjBlOGRjMzQwMWZjYTQzNGUxZTE5OWM3ZjNiNGQyYTkyNTJkMTA1NTYwNzkyM2FmNWNiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f71qD5kjqFQM5EW-9JEZLQetRNWIv1u7-ATCgC8cM6s">

Thank you very much！

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
