### ISSUE TITLE
Memory leakage in CachedSmilesMolHolder

### ISSUE THREAD

**Issue by philipullmann** [rdkit/rdkit#7457]
**Describe the bug**
Iterative calling CachedSmilesMolHolder will result in a memory leakage as there is no way to destruct the class.
For me this leads to Out of memory error in large library searches.

**To Reproduce**

    from rdkit import Chem
    from rdkit.Chem import rdSubstructLibrary
    import pandas as pd
    import psutil

    process= psutil.Process()
    start_rss = process.memory_info().rss

    i = 0

    while i == 0:
        molholder = rdSubstructLibrary.CachedSmilesMolHolder()
        data = pd.read_csv("Test.ism", sep=" ", header=None)

        for mol, _ in data.itertuples(index=False):
            molholder.AddSmiles(mol)

        library = rdSubstructLibrary.SubstructLibrary(molholder)

        rss = process.memory_info().rss - start_rss
        print("LEAK", rss/(1024**2), "mb")

[Test_smiles.csv](https://github.com/rdkit/rdkit/files/15413816/Test_smiles.csv)

**Expected behavior**
The class should destruct itself to prevent memory leakage

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.2
 - OS: [e.g. Ubuntu 23.10]
 - Python version (if relevant): 3.12.3
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by bp-kelley** [comment]
It looks some interaction with the SubstructLibrary isn't releasing the holder, the MolHolder by itself looks to be fine:

```
from rdkit import Chem
from rdkit.Chem import rdSubstructLibrary
import pandas as pd
import psutil

process= psutil.Process()
start_rss = process.memory_info().rss

i = 0

smiles = ["CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCc"] * 10000

while i == 0:
    molholder = rdSubstructLibrary.CachedSmilesMolHolder()
    for smi in smiles:
        molholder.AddSmiles(smi)

    rss = process.memory_info().rss - start_rss
    print("LEAK", rss/(1024**2), "mb")

```

**Comment by bp-kelley** [comment]
There is some boost_python interaction that is confusing to me, a temporary fix is as follows:

```
while i == 0:
    molholder = rdSubstructLibrary.CachedSmilesMolHolder()
    for smi in smiles:
        molholder.AddSmiles(smi)
    library = rdSubstructLibrary.SubstructLibrary(molholder)
    del library
    del molholder
    rss = process.memory_info().rss - start_rss
    print("LEAK", rss/(1024**2), "mb")
```

Which, honestly, doesn't make a lot of sense to me but I'll start digging into it.
