### ISSUE TITLE
Segfault in Chem.GetAdjacencyMatrix()

### ISSUE THREAD

**Issue by rappoport** [rdkit/rdkit#747]
There seems to be a memory issue in Chem.GetAdjacencyMatrix(), which causes the following simple script to quit out with a segfault.

```
#!/usr/bin/env python
# test_rdkit.py

import openbabel
from rdkit import Chem

adj = Chem.GetAdjacencyMatrix(Chem.MolFromSmiles('CO'))
print adj
```

If openbabel is commented out, the segfault goes away, which I think points to a memory issue. Running valgrind against python with the above script shows (with default suppression file from http://svn.python.org/projects/python/trunk/Misc/valgrind-python.supp) 

```
valgrind --tool=memcheck --suppressions=valgrind-python.supp python ./test_rdkit.py
```

two errors related to Boost::Python ([valgrind output](https://github.com/rdkit/rdkit/files/101498/valgrind-output.txt.gz)).

System: Linux ... 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Python:  Python 2.7.6 |Anaconda 1.9.2 (64-bit)| (default, Jan 17 2014, 10:13:17)
RDKit 2015.09.2
Boost::Python 1.54.0

**Comment by bp-kelley** [comment]
Could you please run valgrind without "import openbabel"?  

If the program segfaults, it will certainly leak.  If there are still the uninitialized writes, this is an RDKit issue and not some weird dynamic library clobbering by using both openbabel and rdkit at the same time.

**Comment by rappoport** [comment]
Thank you for your response. Attached is the valgrind [output](https://github.com/rdkit/rdkit/files/109140/valgrind-no-openbabel-output.txt.gz) without importing openbabel. There are messages in the valgrind output concerning rdkit/Chem/rdmolfiles.so (l. 1100), although I'm not sure they explain the error.

**Comment by greglandrum** [comment]
Which RDKit version are you using?

**Comment by rappoport** [comment]
I'm using the 2015.09.2 release

**Comment by greglandrum** [comment]
And can you please try modifying your code to this:
```python
m = Chem.MolFromSmiles('CO')
adj = Chem.GetAdjacencyMatrix(m)
print adj
```
and see if you still have the problem?

**Comment by rappoport** [comment]
Yes, the problem persists with 

    #!/usr/bin/env python

    import openbabel
    from rdkit import Chem

    m = Chem.MolFromSmiles('CO')
    adj = Chem.GetAdjacencyMatrix(m)
    print adj

or with 

    m = Chem.MolFromSmiles('CO', sanitize=False)

As soon as openbabel is commented out, the code runs without errors.

**Comment by greglandrum** [comment]
Does it print the adjacency matrix before the crash?

**Comment by rappoport** [comment]
No, there is no output from the above script before the SegFault

    $ python -u ./test_rdkit2.py
    Segmentation fault

**Comment by greglandrum** [comment]
I've managed to reproduce this by installing openbabel.
Here's where the crash occurs:

```
(gdb) core core
warning: core file may not match specified executable file.
[New LWP 17596]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python crash.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f20ea48feca in RDKit::getAdjacencyMatrix (mol=..., useBO=<optimized out>, emptyVal=0, 
    force=<optimized out>, prefix=0x7f20f7cf9ae0 "")
    at /scratch/RDKit_git/Code/GraphMol/Wrap/MolOps.cpp:468
468	    res = (PyArrayObject *)PyArray_SimpleNew(2, dims, NPY_DOUBLE);
(gdb) p dims
$1 = {2, 2}
```

Note that switching the order of the imports (to pull in the RDKit first) clears up the seg fault.

I don't currently know what is causing this.

**Comment by greglandrum** [comment]
It's not connected with openbabel's use of numpy, because it doesn't seem to us it.

It's not connected with what the RDKit imports when it loads, since that doesn't seem to change (this is from results of `python -v` both with and without the openbabel import).

**Comment by joergkurtwegner** [comment]
Any further news on this one? We just stumbled into a Java segmentation fault with rdkit in a bigger package, but can mediate the issue by ensuring rdkit is loaded first thing in the __init__ of the package? Thus changing the import and putative shared library loading helps, just curious if there are more elegant ways to prevent this?

**Comment by greglandrum** [comment]
@joergkurtwegner : nope, this is one of those things that's very difficult to track down.
Whatever you're observing on the Java side is almost certainly something different. Please open a separate issue for that

**Comment by NadavQuris** [comment]
Is there any insight on this? 
I get the same behavior, and in the script I'm using openbabel isn't imported, so I don't believe it's that.
