### ISSUE TITLE
GetConformers() returns an empty list.

### ISSUE THREAD

**Issue by hxu105** [rdkit/rdkit#7470]
howdy, 

I am trying to call the GetConformers() function for an arbitrary molecule, and I have tried several different molecules, all of which cannot return a well-defined conformers sequence by calling GetConformers().

Here is a figure for an error example.
![image](https://github.com/rdkit/rdkit/assets/40327643/3f5a1fb9-d0a7-45a8-b2e9-660c7a0986e6)

Could you help to provide me with any solutions or hints?

Many thanks!

**Comment by qcxia20** [comment]
@hxu105 
You seemed to not embed the molecule with 3D coordinates.
Neither MolFromSmiles or AddHs here could give molecule the 3D information (conformer).
A simple solution...
```python
from rdkit import Chem
from rdkit.Chem import AllChem

mol = Chem.AddHs(Chem.MolFromSmiles("C1[C@H](C#CC#C)CC[C@H](C#CC#C)C1"))
AllChem.EmbedMolecule(mol)
conformer = mol.GetConformers()[0]
```

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.

**Comment by hxu105** [comment]
Hello, 

There are some SMILES return -1 for `AllChem.EmbedMolecule()` function. Please see the following image.
![image](https://github.com/rdkit/rdkit/assets/40327643/71f187aa-d0c6-419b-b7f6-02fbbe20006d)

So for those SMILES, what should I do to get their conformers?

Many thanks

**Comment by hxu105** [comment]
@greglandrum Hi, could you help to review the above problem? Many thanks!
