### ISSUE TITLE
Unexpected chirality obtained molecule loaded from sdf files using Chem.MolToSmiles(IsomericSmiles=True)

### ISSUE THREAD

**Issue by qcxia20** [rdkit/rdkit#7472]
**Describe the bug**
Unexpected chirality assignment can be done on atoms of molecules consisting of certain rings.
If you load molecules with 3D conformation from files (sdf/mol2), and transform the mol into SMILES through `Chem.MolToSmiles(IsomericSmiles=True)`, some unexpected chiral centers assigned are going to be displayed.

**To Reproduce**
```python
from rdkit.Chem import AllChem
for smi in [
    "O=C(NC1CC(C(=O)OC)C1)N",
    "O=C(NC1CC2[NH+](C(C1)CC2)Cc3ccccc3)N"
]:
    mol = Chem.MolFromSmiles(smi)
    print("smi1",Chem.MolToSmiles(mol,isomericSmiles=True))
    mol = Chem.AddHs(mol)
    AllChem.EmbedMultipleConfs(mol,numConfs=10)
    with Chem.SDWriter("test.sdf") as w:
        for cid in range(mol.GetNumConformers()):
            w.write(mol,confId=cid)
    
    mols = Chem.SDMolSupplier("test.sdf")
    print("smi2",Chem.MolToSmiles(mols[0],isomericSmiles=True))

# Output
# smi1 COC(=O)C1CC(NC(N)=O)C1
# smi2 COC(=O)[C@H]1C[C@H](NC(N)=O)C1
# smi1 NC(=O)NC1CC2CCC(C1)[NH+]2Cc1ccccc1
# smi2 NC(=O)N[C@@H]1C[C@H]2CC[C@@H](C1)[N@H+]2Cc1ccccc1
```

**Expected behavior**
These unexpectedly assigned chiral centers are disabled in the result of `Chem.MolToSmiles(IsomericSmiles=True)`.

**Screenshots**
![image](https://github.com/rdkit/rdkit/assets/56123242/b3044fc5-67a3-4ba7-b766-3ec5957e9adf)

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.2
 - OS: Centos 8

**Comment by greglandrum** [comment]
@qcxia20 this is expected behavior. There is a difference between these two structures:
![image](https://github.com/rdkit/rdkit/assets/540511/f6b28a0f-6a28-4968-95ce-f8c17f9fc299)
SMILES: `C[C@H]1C[C@H](C)C1`
and
![image](https://github.com/rdkit/rdkit/assets/540511/4a50945f-cdc2-4a78-93ec-22dfa7649980)
SMILES: `C[C@H]1C[C@@H](C)C1`

And that difference is tracked the same way as chirality.

**Comment by qcxia20** [comment]
> @qcxia20 this is expected behavior. There is a difference between these two structures: ![image](https://private-user-images.githubusercontent.com/540511/335185227-f6b28a0f-6a28-4968-95ce-f8c17f9fc299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzAxNDYsIm5iZiI6MTcxNzMyOTg0NiwicGF0aCI6Ii81NDA1MTEvMzM1MTg1MjI3LWY2YjI4YTBmLTZhMjgtNDk2OC05NWNlLWY4YzE3ZjlmYzI5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjA0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzY1NThlMmU4MmIzN2NkZjU2MTM1YjYxMzExOGU3MzYxMTJjNTAwZjA4YzJlOTE1ODU2N2I4ZDM4YjYzYTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kVLGQkvyaSda6yLLgkJjWvctUoRff6QqMQ7O_AHyZi8) SMILES: `C[C@H]1C[C@H](C)C1` and ![image](https://private-user-images.githubusercontent.com/540511/335185368-4a50945f-cdc2-4a78-93ec-22dfa7649980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzAxNDYsIm5iZiI6MTcxNzMyOTg0NiwicGF0aCI6Ii81NDA1MTEvMzM1MTg1MzY4LTRhNTA5NDVmLWNkYzItNGE3OC05M2VjLTIyZGZhNzY0OTk4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQxMjA0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGZiNjdiZGQxMDk3ZGYxOWY0YzMxMTVhODdlYWQ3ZTAzYTI1N2FlNmVhMmJmOGRmZjFiYTcyNmNkOTA3ZWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hBLvs3n-hKzohikzjz7yzdDt65GwBxrRZfd_FD-JNdU) SMILES: `C[C@H]1C[C@@H](C)C1`
> 
> And that difference is tracked the same way as chirality.

Hi, then I'm confused that why `EnumerateStereoisomers` cannot enumerate these isomers? In other words, if there are any ways to enumerate the isomers you've mentioned in RDKit?

```python
from rdkit import Chem
from rdkit.Chem.EnumerateStereoisomers import EnumerateStereoisomers, StereoEnumerationOptions

for smi in [
    "O=C(NC1CC(C(=O)OC)C1)N",
    "O=C(NC1CC2[NH+](C(C1)CC2)Cc3ccccc3)N"
]:
    mol = Chem.MolFromSmiles(smi)
    print("smi1",Chem.MolToSmiles(mol,isomericSmiles=True))
    isomers = tuple(EnumerateStereoisomers(mol))
    for smi in sorted(Chem.MolToSmiles(x, isomericSmiles=True) for x in isomers):
        print(smi)

# output
# smi1 COC(=O)C1CC(NC(N)=O)C1
# COC(=O)C1CC(NC(N)=O)C1
# smi1 NC(=O)NC1CC2CCC(C1)[NH+]2Cc1ccccc1
# NC(=O)NC1C[C@@H]2CC[C@@H](C1)[NH+]2Cc1ccccc1
# NC(=O)NC1C[C@H]2CC[C@@H](C1)[NH+]2Cc1ccccc1
# NC(=O)NC1C[C@H]2CC[C@H](C1)[NH+]2Cc1ccccc1
```
But based on your comment, the output should contain the isomers you've mentioned. Is it right?

**Comment by qcxia20** [comment]
@greglandrum
