### ISSUE TITLE
Support NumPy 2.0

### ISSUE THREAD

**Issue by jakirkham** [rdkit/rdkit#7477]
Hi All 👋

NumPy is planning to release 2.0 on June 16th ( https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448 ). NumPy 2.0.0 RC packages for conda & wheels came out at the beginning of April ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html )

If RDKit makes use of NumPy's C API (and produces wheels that use it), having a release of RDKit with wheels built against NumPy 2.0.0rc1 would be helpful to ensure NumPy 1 & 2 compatible wheels (as wheels built against NumPy 1 won't be compatible with NumPy 2). More details in [this NumPy 2 ABI doc]( https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling )

Also Boost.Python does have NumPy 2.0 support, but it is not fully in a released version as this patch is needed: https://github.com/boostorg/python/pull/432

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share RDKit current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

**Comment by greglandrum** [comment]
@jakirkham : we definitely will update the RDKit to support v2 of numpy.
Since our users can't always upgrade to the latest and greatest of everything, we're going to have to do this in a way that maintains v1 support for quite a while.

I'm not sure how much work this is going to be, so I can't estimate a completion date, but we'll take a look and set an appropriate milestone here once we've got that figured out.

**Comment by jakirkham** [comment]
Hi Greg, thanks for your reply. This certainly should be possible. Would take a look through the materials above. Please let us know if you have any questions after. Would be happy to follow up 🙂

**Comment by greglandrum** [comment]
@AnnaBruenisholz said that she's going to start taking a look at this.

**Comment by greglandrum** [comment]
Resolved in #7531
