### ISSUE TITLE
PostgreSQL cartridge: mol_to_ctab problems with v2k format and stereogroups

### ISSUE THREAD

**Issue by adam-of-barot** [rdkit/rdkit#7479]
**Describe the bug**
The `mol_to_ctab` function in the PostgreSQL cartridge returns a V3000 CTAB for chiral molecules if the molecule was generated from a V3000 CTAB, even when the V3000 option is explicitly set to false.

**To Reproduce**
```sql
select mol_to_ctab(mol_from_ctab('CHIRALTEST
Actelion Java MolfileCreator 2.0

  0  0  0  0  0  0              0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 5 4 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Br 0.0 0.0 0.0 0
M  V30 2 C -0.0117 1.5058 0.0 0 CFG=2
M  V30 3 Cl 1.4705 1.5176 0.0 0
M  V30 4 F -0.0235 3.0116 0.0 0
M  V30 5 C -1.5176 1.5176 0.0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 2 3
M  V30 3 1 2 4 CFG=1
M  V30 4 1 2 5
M  V30 END BOND
M  V30 BEGIN COLLECTION
M  V30 MDLV30/STEABS ATOMS=(1 2)
M  V30 END COLLECTION
M  V30 END CTAB
M  END
'::cstring), false, false)  -- don't output a V3000 molfile
```

**Expected behavior**
The following V2000 molfile, or equivalent, is expected
```sql
'CHIRALTEST
Actelion Java MolfileCreator 1.0

  5  4  0  0  1  0  0  0  0  0999 V2000
    0.0000   -0.0000   -0.0000 Br  0  0  0  0  0  0  0  0  0  0  0  0
   -0.0118    1.5058   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4705    1.5176   -0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.0235    3.0117   -0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5176    1.5176   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  2  4  1  1  0  0  0
  2  5  1  0  0  0  0
M  END'
```
Instead, the output is the following:
```sql
'CHIRALTEST
     RDKit          2D

  0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 5 4 0 0 0
M  V30 BEGIN ATOM
M  V30 1 Br 0.549038 2.049038 0.000000 0
M  V30 2 C 1.299038 0.750000 0.000000 0
M  V30 3 Cl 2.049038 -0.549038 0.000000 0
M  V30 4 F 2.598076 1.500000 0.000000 0
M  V30 5 C 0.000000 0.000000 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 2 1 2 3
M  V30 3 1 2 4
M  V30 4 1 2 5 CFG=3
M  V30 END BOND
M  V30 BEGIN COLLECTION
M  V30 MDLV30/STEABS ATOMS=(1 2)
M  V30 END COLLECTION
M  V30 END CTAB
M  END
'
```

**Configuration:**
 - RDKit version: 2024_03_3 (also tested with 2023_03_3)
 - OS: Ubuntu 22.04
 - Python version (if relevant): -
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit?
   - Installed using https://github.com/cyclica/rdkit-installer

**Comment by greglandrum** [comment]
The code does this because your molecule has enhanced stereo. Since this is impossible to represent in v2k format, the RDKit provides v3k as output (it does something similar if you have more than 999 atoms, bonds, or SGroups in the molecule). So this is expected behavior.

The way that you'd resolve this when using the toolkit is to remove the stereo groups from the molecule and then ask for the v2k output. This isn't currently possible in the cartridge. We could theoretically add support if there were a real use case for it.

Is there some reason that you require v2k instead of v3k?

**Comment by adam-of-barot** [comment]
Thank you @greglandrum for the explanation!

The reason that I was trying to get a v2k output is because one of our partners explicitly requested v2k instead of v3k. And since the v3k versions are already in our database, I wanted to use the cartridge to convert between the formats, without using additional tooling. The app's backend that's working with the data is written in JS, so I can't rely on rdkit there.

I suppose if I wanted to stick to cartridge-only solutions I could try going v3k -> SMILES -> v2k, but after testing it out a bit, that comes with it's own share of gotchas.

**Comment by greglandrum** [comment]
We could think about adding a separate function which always generates a v2k mol block (except for the cases with more than 999 atoms, bonds, or sgroups, where it's impossible)

That shouldn't be difficult and would not compromise the behavior of the current function, which provides v3k when v2k would result in information loss.
