### ISSUE TITLE
rdMolStandardize.Uncharger can break aromaticity without removing aromaticity flags, causing bad SMILES

### ISSUE THREAD

**Issue by zpincus** [rdkit/rdkit#7481]
**Describe the bug**
When `rdMolStandardize.Uncharger` adds a hydrogen to a carbanion that participates in an aromatic ring, it doesn't clear the aromaticity flags on the atoms; this causes SMILES output from the molecule to not be able to round-trip back into RDKit.

**To Reproduce**
```python
mol = Chem.MolFromSmiles('c1ccc(P(c2ccccc2)c2cc[cH-]c2)cc1')
uncharger = rdMolStandardize.Uncharger()
mol2 = uncharger.uncharge(mol)
smiles = Chem.MolToSmiles(mol2)
mol3 = Chem.MolFromSmiles(smiles)
```
But `mol3` is `None` and the last line prints `Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15`.

The invalid SMILES produced by the second-to-last line is `'c1ccc(P(c2ccccc2)c2cccc2)cc1'`.

**Expected behavior**
Not sure what's best: should `Uncharger` not add Hs to aromatic carbanions, or should it clear the aromaticity flags when it does? 

**Configuration (please complete the following information):**
RDKit version 2024.03.1 from conda-forge

**Comment by greglandrum** [comment]
For efficiency reasons the standardization functions do not sanitize the molecule, so you need to do that in your code.
If I do:
```
mol = Chem.MolFromSmiles('c1ccc(P(c2ccccc2)c2cc[cH-]c2)cc1')
uncharger = rdMolStandardize.Uncharger()
mol2 = uncharger.uncharge(mol)
Chem.SanitizeMol(mol2)
Chem.MolToSmiles(mol2)
```
The output is `C1=CC(P(c2ccccc2)c2ccccc2)=CC1`, which is what I think you expect.

**Comment by zpincus** [comment]
Thank you! I'd searched for a function that would automatically reassign aromaticity, but somehow `SanitizeMol` didn't come up.
