### ISSUE TITLE
No matching distribution found for rdkit==2024.3.3

### ISSUE THREAD

**Issue by 1641004802** [rdkit/rdkit#7484]
ERROR: Could not find a version that satisfies the requirement rdkit==2024.3.3 (from versions: 2023.9.1, 2023.9.2, 2023.9.3, 2023.9.4, 2023.9.5, 2023.9.6)
ERROR: No matching distribution found for rdkit==2024.3.3
<img width="707" alt="屏幕截图 2024-06-02 162539" src="https://github.com/rdkit/rdkit/assets/68485539/21e48251-9ce6-4696-96be-6a2300e3cf62">

How can I acquire the version 2024_03_3(Q1 2024)?

**Comment by greglandrum** [comment]
The availability of binary builds is not an RDKit issue.
Please open a ticket in the tracker for the project that provides the rdkit-pypi builds.

But be aware that these projects are all run by volunteers and it can take some days for new builds to be available
