### ISSUE TITLE
Index anomaly with mol @= mol operator on PostgreSQL. Exact match is extremely slow!

### ISSUE THREAD

**Issue by ergo70** [rdkit/rdkit#7493]
**Description:**
When a GiST index is present, exact searching with the @= operator is 3x slower than without the index and much slower than @> or <@.

**Reproduction:**
```
create extension rdkit;
create schema chemistry;
create table chemistry.scantest (id SERIAL primary key, smiles text, molecule mol);
```
Import e.g. current ChEMBL 34 into that table: 2409270 records/molecules.
`explain analyze select id, smiles from chemistry.scantest s where molecule @= 'C1=CC=CC=C1'::mol limit 1000;`

_Limit  (cost=1000.00..222107.52 rows=1 width=62) (actual time=27858.392..27861.224 rows=1 loops=1)
  ->  Gather  (cost=1000.00..222107.52 rows=1 width=62) (actual time=27858.390..27861.222 rows=1 loops=1)
        Workers Planned: 2
        Workers Launched: 2
        ->  **Parallel Seq Scan on scantest s**  (cost=0.00..221107.42 rows=1 width=62) (actual time=20019.098..27795.578 rows=0 loops=3)
              Filter: (molecule @= 'c1ccccc1'::mol)
              Rows Removed by Filter: 803090
Planning Time: 0.189 ms
**Execution Time: 15861.480 ms**_

`create index molidx on chemistry.scantest using gist(molecule);`
`explain analyze select id, smiles from chemistry.scantest s where molecule @= 'C1=CC=CC=C1'::mol limit 1000;`

_Limit  (cost=0.41..8.43 rows=1 width=62) (actual time=16535.737..47603.977 rows=1 loops=1)
  ->  **Index Scan using molidx on scantest s**  (cost=0.41..8.43 rows=1 width=62) (actual time=16535.736..47603.974 rows=1 loops=1)
        Index Cond: (molecule @= 'c1ccccc1'::mol)
        Rows Removed by Index Recheck: 2048413
Planning Time: 1.347 ms
**Execution Time: 47604.119 ms**_

Now a substructure search for comparison:
```
explain analyze
select id, smiles from chemistry.scantest s where molecule @> 'C1=CC=CC=C1'::mol limit 1000;
```

_Limit  (cost=0.41..4208.86 rows=1000 width=62) (actual time=0.628..42.577 rows=1000 loops=1)
  ->  **Index Scan using molidx on scantest s**  (cost=0.41..10138.57 rows=2409 width=62) (actual time=0.626..42.498 rows=1000 loops=1)
        Index Cond: (molecule @> 'c1ccccc1'::mol)
Planning Time: 0.137 ms
**Execution Time: 42.892 ms**_

**Expected behavior:**
A search with index should usually be much faster, not slower. Exact search should be faster than substructure searching, not slower.
Substructure searching with @> or <@ for 'C1=CC=CC=C1' takes about 0.04 seconds on ChEMBL 34, so the index is basically working. But exact matching is broken.

**Configuration:**
 - RDKit version: 2024.03.3 / Extension 0.76.0
 - OS: macOS 14.5 (ARM64), but we see it also on Linux x64
 - PostgreSQL 16.3 installed from homebrew
 - RDKit built and installed from source

**Comment by ergo70** [comment]
I assume, the RDKitEquals branch of gmol_consistent() should look like this:

   ```
 case RDKitEquals:
      if (!ISALLTRUE(key)) {
        /*
        ** verify the necessary condition that key should contain the query
        ** (on leaf nodes, couldn't it also verify that query contains key?)
        */
        if (siglen != SIGLEN(query)) {
          elog(ERROR, "All fingerprints should be the same length");
        }

        uint8 *k = (uint8 *)VARDATA(key);
        uint8 *q = (uint8 *)VARDATA(query);

        if (GIST_LEAF(entry)) {
          res = (memcmp(k, q, siglen) == 0);
        } else {
          res = bitstringContains(siglen, k, q);
        }
      }
      break;
    default:
      elog(ERROR, "Unknown strategy: %d", strategy);
  }
```
to avoid a recheck of _every_ entry.

_Limit  (cost=0.41..8.43 rows=1 width=62) (actual time=132.151..318.282 rows=1 loops=1)
  ->  **Index Scan using molidx on scantest s**  (cost=0.41..8.43 rows=1 width=62) (actual time=132.150..318.281 rows=1 loops=1)
        Index Cond: (molecule @= 'c1ccccc1'::mol)
Planning Time: 0.109 ms
**Execution Time: 318.719 ms**_

**Comment by ergo70** [comment]
And gmol_same() should throw an ERROR in case of fingerprints of different sizes, like the other comparison functions on fingerprints:

```
/*
 * Same method
 */

PGDLLEXPORT Datum gmol_same(PG_FUNCTION_ARGS);
PG_FUNCTION_INFO_V1(gmol_same);
Datum gmol_same(PG_FUNCTION_ARGS) {
  bytea *a = (bytea *)PG_GETARG_POINTER(0);
  bytea *b = (bytea *)PG_GETARG_POINTER(1);
  bool *result = (bool *)PG_GETARG_POINTER(2);

  if (SIGLEN(a) != SIGLEN(b)) {
    elog(ERROR, "All fingerprints should be the same length");
  }

  *result = (memcmp(VARDATA(a), VARDATA(b), SIGLEN(a)) == 0);

  PG_RETURN_BOOL(result);
}
```

**Comment by lounsbrough** [comment]
@greglandrum @ergo70 - should this issue be reopened since the PR was reverted?
