### ISSUE TITLE
MolToSVG errors out

### ISSUE THREAD

**Issue by mahnehsilla** [rdkit/rdkit#7497]
I'm using rdkit=2024 within linux/conda

Everything works quite well but this errors out:

```python
from rdkit import Chem
from rdkit.Chem.Draw import MolToSVG
MolToSVG(Chem.MolFromSmiles('c1ccc1'))
```

with error:

> ValueError: Bad Conformer Id

I was expecting to get the SVG image.

There is some other ways to plot it why doesn't this one work?

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.

**Comment by oliviercailloux** [comment]
I meet the same problem. I have just looked at the template but do not see which information is missing? The OP provides an easy to reproduce example, it seems to me.
