### ISSUE TITLE
MolToSmiles is OK but MolFromSmiles is not OK

### ISSUE THREAD

**Issue by 1641004802** [rdkit/rdkit#7500]
Using MolToSmiles(mol) generates the 'Cc1ccc2c(c1)-n1-c(=O)/c=c\c(=O)-n-2-c2cc(C)ccc2-1'.
But using MolFromSmiles('Cc1ccc2c(c1)-n1-c(=O)/c=c\c(=O)-n-2-c2cc(C)ccc2-1') leading to error.
[error.txt](https://github.com/user-attachments/files/15602626/error.txt)

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
