### ISSUE TITLE
Online Documentation: `Mol.GetAtoms` and `Mol.GetBonds` miss signatures

### ISSUE THREAD

**Issue by e-kwsm** [rdkit/rdkit#7527]
**Describe the bug**
The signatures of `Mol.GetAtoms` and `Mol.GetBonds` are missed.

- <https://www.rdkit.org/new_docs/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.Mol.GetAtoms>
- <https://www.rdkit.org/new_docs/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.Mol.GetBonds>

**To Reproduce**
Open the above links.

**Expected behavior**

Shown as `GetAtoms((Mol)self) -> rdkit.Chem._GetAtomsIterator` and `GetBonds((Mol)self) -> rdkit.Chem._GetBondsIterator`.

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.3
 - OS: irrelevant
 - Python version (if relevant):
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Comment by e-kwsm** [comment]
ping

**Comment by bertiewooster** [comment]
What would it take to add signatures for `Mol.GetAtoms` and `Mol.GetBonds`? I believe there are no user-supplied arguments, just the `Mol` that the method is called on, but other methods that act on the supplied `Mol` include that--and a method description--in the signature, for example [`GetAromaticAtoms`](https://www.rdkit.org/new_docs/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.Mol.GetAromaticAtoms):

```
GetAromaticAtoms((Mol)self) → _ROQAtomSeq :
Returns a read-only sequence containing all of the molecule’s aromatic Atoms.

C++ signature :
RDKit::ReadOnlySeq<RDKit::QueryAtomIterator_<RDKit::Atom, RDKit::ROMol>, RDKit::Atom*, RDKit::AtomCountFunctor>* GetAromaticAtoms(boost::shared_ptr<RDKit::ROMol>)
```

It seems that the [GetAtoms method is defined as](https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/__init__.py#L103)

`rdchem.Mol.GetAtoms = lambda self: _GetAtomsIterator(self)
`

[which in turn calls](https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/__init__.py#L85-L91)

```
class _GetAtomsIterator(_GetRDKitObjIterator):

  def _sizeCalc(self):
    return self._mol.GetNumAtoms()

  def _getRDKitItem(self, i):
    return self._mol.GetAtomWithIdx(i)
```
