### ISSUE TITLE
rdkit-js npm package (minimallib) - unable to build and release

### ISSUE THREAD

**Issue by MichelML** [rdkit/rdkit#7530]
**Describe the bug**
unable to build and release the minimal lib as the build is failing (and need help debugging)

**To Reproduce**
You can use the [following rdkit-js branch](https://github.com/rdkit/rdkit-js/blob/fix/debug-build/Dockerfile), and run the following command from the root of the repository:

```
docker build --no-cache -f Dockerfile --build-arg RDKIT_BRANCH=Release_2024_03_3 .
```

Note that the docker file is equivalent to the one in rdkit https://github.com/rdkit/rdkit/blob/Release_2024_03_3/Code/MinimalLib/docker/Dockerfile

Minus this line that I had to change:

```
RUN echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list.d/backports.list
```

was changed to

```
RUN echo "deb http://archive.debian.org/debian buster-backports main contrib non-free" >> /etc/apt/sources.list.d/backports.list
```

**Expected behavior**
The build succeeds and produce the expected minimallib outputs

**Screenshots**
please see rdkit-js discussion here for error logs https://github.com/rdkit/rdkit-js/discussions/456

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.3
 - OS: Ubuntu 22.04

**Additional context**
please see rdkit-js discussion here https://github.com/rdkit/rdkit-js/discussions/456

**Comment by ptosco** [comment]
@MichelML Thanks for reporting, I’ll look into this tomorrow.

**Comment by greglandrum** [comment]
I'm very curious why this particular change makes a difference

**Comment by MichelML** [comment]
@greglandrum this is what I followed https://www.cyberciti.biz/faq/the-repository-http-deb-debian-org-debian-buster-backports-release-no-longer-has-a-release-file/

**Comment by MichelML** [comment]
could it be because of a different base image version that I had to do this? We use `debian:buster` as base which can change based on new debian image releases unless I'm wrong.

**Comment by MichelML** [comment]
small bump on this @ptosco , let me know when if you had time to look at this
