### ISSUE TITLE
IndexError with computing fingerprint

### ISSUE THREAD

**Issue by AaronsonJames** [rdkit/rdkit#7533]
**Describe the bug**
With the given smiles (in the next section), rdkit throws an error when trying to compute a fingerprint.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import rdMolDescriptors
mol = Chem.MolFromSmiles('CC1C(B(C)C)S1(C)(C)=O')
rdMolDescriptors.GetMorganFingerprint(mol, 2)
```
the following error occurs:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: -1
```

**Expected behavior**
An object of type UIntSparseIntVect to be returned with no errors.

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.3
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.10.14
 - Are you using conda?
 - If you are using conda, which channel did you install the rdkit from?
 - If you are not using conda: how did you install the RDKit?

**Additional context**
The modern code `rdFingerprintGenerator.GetMorganGenerator(radius=2).GetCountFingerprint(mol)` seems to work, which makes this more mysterious. (But this is still annoying as I'm using library code which uses the rdMolDescriptors.GetMorganFingerprint method)

**Comment by greglandrum** [comment]
Confirmed.

**Comment by greglandrum** [comment]
Please do note that this function is deprecated and will be removed in a future release
