### ISSUE TITLE
Stereochemistry lost when converting to SMILES for certain molecules loaded from SDF files

### ISSUE THREAD

**Issue by qcxia20** [rdkit/rdkit#7541]
**Describe the bug**
I've tried to use rdkit to load sdf formatted files and transform the loaded mols into SMILES strings. I want to keep the stereochemistry inside the sdf file. However, for these sdf files, the stereochemistry does not keep even with AssignStereochemistryFrom3D and/or AssignAtomChiralTagsFromStructure.

**To Reproduce**
```python
for insdf in ["CHEMBL3322797.sdf","CHEMBL4578414.sdf"]:
    mols = Chem.SDMolSupplier(insdf, removeHs=True)
    mol = mols[0]
    Chem.AssignAtomChiralTagsFromStructure(mol)
    Chem.AssignStereochemistryFrom3D(mol)
    print(Chem.MolToSmiles(mol,isomericSmiles=True))

#CCCCCNC(=O)NCCCCC=CCCCCCCC(=O)OCCOCCOCCO
#O=C(Nc1ccc(C=Cc2nc3ccccc3s2)cc1)Nc1ccc(Cl)c(Cl)c1
```
[CHEMBL3322797.sdf.txt](https://github.com/user-attachments/files/15899322/CHEMBL3322797.sdf.txt)
[CHEMBL4578414.sdf.txt](https://github.com/user-attachments/files/15899323/CHEMBL4578414.sdf.txt)

**Expected behavior**
The stereochemistry does exist in the conformer. So the expected output should be 
```python
# CCCCCNC(=O)NCCCC/C=C\CCCCCCC(=O)OCCOCCOCCO
# O=C(Nc1ccc(/C=C/c2nc3ccccc3s2)cc1)Nc1ccc(Cl)c(Cl)c1
```
**Screenshots**
The illustrative 2D structure of the two molecules mentioned are shown below:
| CHEMBL3322797 | CHEMBL4578414 |
| -- | -- |
|![image](https://github.com/rdkit/rdkit/assets/56123242/848f8b8a-6527-4969-b1c2-fd61674fd1a7)|![image](https://github.com/rdkit/rdkit/assets/56123242/cdec6b00-21c1-4cf4-bf55-bbfb2cb84141) | 

**Configuration (please complete the following information):**
- RDKit version: 2023.09.2
- OS: Centos 8

**Comment by greglandrum** [comment]
If you look in the SDF files from pubchem, you will see that the double bonds in question are marked as being "either" stereo (i.e. crossed bonds). The RDKit is thus correctly not assigning stereochemistry to them.
