### ISSUE TITLE
Duplicate enhanced stereo labels when addStereoAnnotation=true

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#7543]
Enhanced stereo labels are duplicated when `MolDrawOptions.addStereoAnnotation` is `true`:

```python
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG

mol = Chem.MolFromSmiles("C[C@H](O)[C@H](C)F |&1:1,3,r|")
drawer = rdMolDraw2D.MolDraw2DSVG(300, 300)
drawOptions = drawer.drawOptions()
drawOptions.addStereoAnnotation = True
drawer.DrawMolecule(mol)
drawer.FinishDrawing()
SVG(drawer.GetDrawingText())
```
![image](https://github.com/rdkit/rdkit/assets/5244385/f924ce16-9bd2-4bae-a293-657ddd43058a)

This happens because the `addStereoAnnotation` will cause stereochemistry labels (including enhanced stereo labels) to be put into `atomNote`. However, enhanced stereo labels are already visualized by `DrawMol::extractStereoGroups`, which results in their duplication.

There is a simple fix that can be applied to `DrawMol::extractAll`:
```diff
diff --git a/Code/GraphMol/MolDraw2D/DrawMol.cpp b/Code/GraphMol/MolDraw2D/DrawMol.cpp
index d4148eedc..e5297f699 100755
--- a/Code/GraphMol/MolDraw2D/DrawMol.cpp
+++ b/Code/GraphMol/MolDraw2D/DrawMol.cpp
@@ -220,7 +220,9 @@ void DrawMol::extractAll(double scale) {
   extractHighlights(scale);
   extractAttachments();
   extractAtomNotes();
-  extractStereoGroups();
+  if (!drawOptions_.addStereoAnnotation) {
+    extractStereoGroups();
+  }
   extractBondNotes();
   extractRadicals();
   extractSGroupData();
```
However, users might still want to call `Chirality::addStereoAnnotations` to display custom stereochemistry labels with their own preferred format, potentially including enhanced stereo labels, and hence a way to prevent default enhanced stereo annotations from being added.
A possibility could be to add a `hideEnhancedStereoAnnotations` flag defaulting to `false`.

We have briefly discussed this with @greglandrum and he would like to think more carefully about this, so I am filing this issue simply to avoid forgetting about it.

**Comment by greglandrum** [comment]
When we do come back to this: I like the way that the stereo groups are added as separate annotations and don't abuse/hijack the `atomNote`. I think it would make sense to do something similar with the `addStereoAnnotations` option, but that will require some refactoring of the way `addStereoAnnotations()` works.
