### ISSUE TITLE
RDKit does not support ChemAxon generic atom extension

### ISSUE THREAD

**Issue by jpfeuffer** [rdkit/rdkit#7551]
**Describe the bug**
As opposed to the documentation (https://www.rdkit.org/docs/RDKit_Book.html#mol-sdf-support-and-extensions),
RDKit does not fully support the ChemAxon extension for generic atom types like AH (unless merely reading and writing counts as support).
The query gets lost when trying to match.

**To Reproduce**

```
from rdkit import Chem
from rdkit.Chem import rdChemReactions
from rdkit.Chem.Draw import MolsToGridImage
from IPython.display import display

if __name__ == "__main__":
    r = Chem.MolFromMolBlock("""
  MJ240100                      

  6  5  0  0  0  0  0  0  0  0999 V2000
   -0.4125   -0.7144    0.0000 A   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 B   0  0  0  0  0  0  0  0  0  0  0  0
    0.8250    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.2598    0.7364    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4125    0.7144    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0348    1.5180    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  2  5  1  0  0  0  0
  5  6  1  0  0  0  0
  3  4  1  0  0  0  0
A    4
AH
A    6
AH
M  END
""")
    mol = Chem.MolFromSmiles("[H]OB(O[H])C(C)C")
    p = mol.GetSubstructMatches(r)
    print(p)
```

**Expected behavior**
Match

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2023.9.6
 - OS: macOS 14 arm
 - Are you using conda? No

**Comment by jpfeuffer** [comment]
Hi @rachelnwalker 
Thanks for chiming in!
I think I tried that and the problem is then, that it does not recognize COB(OC)C(C)C anymore.
AFAIU the ChemAxon extension to the end of the mol block should make sure that these atoms are recognized as AH instead. 

```
...
A    4
AH
A    6
AH
M  END
```

But this does not work with RDKit, although it is described in the docs. Maybe I am using the syntax wrong?

**Comment by rachelnwalker** [comment]
Ah sorry @jpfeuffer, I didn't look at this close enough. I haven't seen the special queries after the bond block, I usually include them in the atom block like you did with the `A`. RDKit should accept the special queries defined in the Atom block.

The problem is that RDKit substructure matching doesn't match AH/QH/XH/MH to non-graph hydrogens (afiak, maybe there is an option I don't know about). The other ChemAxon atom queries should work. If you skip sanitization on your target structure,  it should work.
<img width="567" alt="image" src="https://github.com/user-attachments/assets/e578c4ce-526a-466c-bdfc-bc011e758b49">

I get around this by doing two queries: one with the AH/QH/etc, one without that atom and instead requiring a neighbor atom to have at least 1 hydrogen. Maybe this enumeration would be helpful in MolEnumerator or something if its not already somewhere in RDKit.

**Comment by bp-kelley** [comment]
In the general rdkit representation, hydrogens are suppressed (even coming from mol files)  The only way to properly handle queries that can match hydrogens or other atoms (i.e. AH) is to add hydrogens to your graph.  This can be done by not removing hydrogens from the input, or calling Chem.AddHs

```
>>> from rdkit.Chem import SmilesParserParams
>>> params = SmilesParserParams()
>>> params.removeHs = False
>>> mol = Chem.MolFromSmiles("[H]OB(O[H])C(C)C", params=params)
>>> mol.Debug()
Atoms:
	0 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: S
	1 8 O chg: 0  deg: 2 exp: 2 imp: 0 hyb: SP3
	2 5 B chg: 0  deg: 3 exp: 3 imp: 0 hyb: SP2
	3 8 O chg: 0  deg: 2 exp: 2 imp: 0 hyb: SP3
	4 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: S
	5 6 C chg: 0  deg: 3 exp: 3 imp: 1 hyb: SP3
	6 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: SP3
	7 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: SP3
Bonds:
	0 0->1 order: 1
	1 1->2 order: 1
	2 2->3 order: 1
	3 3->4 order: 1
	4 2->5 order: 1
	5 5->6 order: 1
	6 5->7 order: 1
```

or

```
>>> mol = Chem.AddHs(mol)
>>> mol.Debug()
Atoms:
	0 8 O chg: 0  deg: 2 exp: 2 imp: 0 hyb: SP3
	1 5 B chg: 0  deg: 3 exp: 3 imp: 0 hyb: SP2
	2 8 O chg: 0  deg: 2 exp: 2 imp: 0 hyb: SP3
	3 6 C chg: 0  deg: 4 exp: 4 imp: 0 hyb: SP3
	4 6 C chg: 0  deg: 4 exp: 4 imp: 0 hyb: SP3
	5 6 C chg: 0  deg: 4 exp: 4 imp: 0 hyb: SP3
	6 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
	7 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
	8 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
	9 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
	10 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
	11 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
	12 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
	13 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
	14 1 H chg: 0  deg: 1 exp: 1 imp: 0 hyb: 
Bonds:
	0 0->1 order: 1
	1 1->2 order: 1
	2 1->3 order: 1
	3 3->4 order: 1
	4 3->5 order: 1
	5 0->6 order: 1
	6 2->7 order: 1
	7 3->8 order: 1
	8 4->9 order: 1
	9 4->10 order: 1
	10 4->11 order: 1
	11 5->12 order: 1
	12 5->13 order: 1
	13 5->14 order: 1
```

However, if you are looking for functional groups and the like, there are a lot of pre-made queries in Functional_Group_Hierarchy.txt

```
BoronicAcid			[$(B-!@[#6])](O)(O)		Boronic Acid		[#6:1]-!@[B:2]([O:3])[O:4]>>[#6:1][X].[B:2]([O:3])[O:4]
  BoronicAcid.Aromatic		[$(B-!@c)](O)(O)	Aromatic	[c:1]-!@[B:2]([O:3])[O:4]>>[c:1][X].[B:2]([O:3])[O:4]
  BoronicAcid.Aliphatic		[$(B-!@C)](O)(O)		Aliphatic	[C:1]-!@[B:2]([O:3])[O:4]>>[C:1][X].[B:2]([O:3])[O:4]
```

These are also available in the rdkit as a dictionary of name:smarts_mol. These don't care if H is in the graph or not.

```
>>> from rdkit.Chem import FilterCatalog
>>> hier = FilterCatalog.GetFlattenedFunctionalGroupHierarchy()
>>> hier
{'AcidChloride': <rdkit.Chem.rdchem.Mol object at 0x154485e70>, 'AcidChloride.Aliphatic': <rdkit.Chem.rdchem.Mol object at 0x154485c40>,  ...

>>> mol.HasSubstructMatch(hier['BoronicAcid'])
True
>>> Chem.RemoveHs(mol).HasSubstructMatch(hier['BoronicAcid'])
True
```

**Comment by jpfeuffer** [comment]
Oh I was so sure that I tried adding explicit hydrogens and the other notation. I probably missed the exact combination.
I can confirm it works.
Thanks a lot to you both!
