### ISSUE TITLE
Handling of chiral sulfur in aromatic rings

### ISSUE THREAD

**Issue by spparel** [rdkit/rdkit#7556]
Hi all,

I am wondering how RDKit deals with chirality on sulfurs in aromatic rings. For instance, if I import the SMILES `CC1=CC(Cl)=CC2=C1N=[S@](C)N=C2N` (same from the corresponding mol file), the chirality at the sulfur gets "flattened":

![image](https://github.com/rdkit/rdkit/assets/135133375/9507fc9e-214f-4b93-a8a3-c5c986e1e670)

Only if I include _sanitize=False_, do I get the proper chirality depiction:
![image](https://github.com/rdkit/rdkit/assets/135133375/b435667f-bcc5-473f-b845-b2b9e3446380)

Since this piece of code should be generic, I'm a bit hesitant about importing all structures with the sanitize flag set to False.

Furthermore, I'm not sure the behavior of RDKit is correct here. Looking at the literature (e.g. [1λ4 ,2,4,6-Thiatriazines with Herbicidal Activity](https://www.chimia.ch/chimia/article/download/2003_725/3066/13751), the non-ring substituent on the sulfur is clearly pointing either up or down:
![image](https://github.com/rdkit/rdkit/assets/135133375/cf9b3eb8-d3cf-4085-868c-09f1b801d467)

What is the logic for this behavior ?

I'm using RDKit 2023.09.5 with Python 3.9.15

Thank you

**Comment by spparel** [comment]
After testing the various options from Chem.SanitizeMol, it seems that the issue is in the particular function dealing with SANITIZE_CLEANUPCHIRALITY.

**Comment by greglandrum** [comment]
Hi @spparel what's happening here is that the S is being recognized as being SP2 hybridized, which means it can't be chiral.

I'm going to have to do a bit of digging to see what we can do about this.
