### ISSUE TITLE
Release_2023_09 builds broken

### ISSUE THREAD

**Issue by tdudgeon** [rdkit/rdkit#7576]
**Describe the bug**
Builds on the 2023_09 branch (including the release tags) are currently broken because the checksum for `Comic_Neue.zip` has changed.

```
9.253 Downloading https://fonts.google.com/download?family=Comic%20Neue...
9.377 CMake Error at Code/cmake/Modules/RDKitUtils.cmake:254 (MESSAGE):
9.377   The md5 checksum for /rdkit/Code/GraphMol/MolDraw2D/Comic_Neue.zip is
9.377   incorrect; expected: b7fd0df73ad4637504432d72a0accb8f, found:
9.377   9c5b7fcbc00e6ff6c1b53c8e0f17032e
9.377 Call Stack (most recent call first):
9.377   Code/GraphMol/MolDraw2D/CMakeLists.txt:21 (downloadAndCheckMD5)
```

**To Reproduce**
Run `cmake` and `make` as usual. I do this in a dockerfile like this, but this really has nothing to do with Docker.

```
RUN cmake -Wno-dev\
  -DPYTHON_EXECUTABLE=/usr/bin/python3\
  -DRDK_INSTALL_INTREE=OFF\
  -DRDK_BUILD_INCHI_SUPPORT=ON\
  -DRDK_BUILD_AVALON_SUPPORT=ON\
  -DRDK_BUILD_PYTHON_WRAPPERS=ON\
  -DRDK_BUILD_SWIG_WRAPPERS=ON\
  -DRDK_BUILD_PGSQL=ON\
  -DPostgreSQL_ROOT=/usr/lib/postgresql/$POSTGRES_VERSION\
  -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/$POSTGRES_VERSION/server\
  -DCMAKE_INSTALL_PREFIX=/usr\
  -DCPACK_PACKAGE_RELOCATABLE=OFF\
  ..

RUN nproc=$(getconf _NPROCESSORS_ONLN)\
  && make -j $(( nproc > 2 ? nproc - 2 : 1 ))
RUN make install
  ..
```

**Expected behavior**
Build should complete as expected

**Configuration (please complete the following information):**
 - RDKit version: Code from `Release_2023_09` branch (or the Release_2023_09_?` tags).
 - OS: Debian bullseye

**Comment by dctaylor87** [comment]
I encountered this problem as well -- while trying to build coot [it builds rdkit along the way].
I discovered that the file downloaded by wget is NOT a zip but, but rather javascript.  I'm guessing
that the javascript is meant to contain an error message (when I looked at it with my browser it
just produced a blank screen).

I do not know the correct argument to give to wget.

**Comment by greglandrum** [comment]
The MD5s for the font zip files do occasionally change for reasons that are mysterious to me. 

We aren't going to go back and do a new patch release of an older RDKit version for this, but you could patch your build script to use the logic from the more recent RDKit releases: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/MolDraw2D/CMakeLists.txt#L22
