### ISSUE TITLE
Chiral flag in V2000 and V3000 MolBlock's is defaulted to 0 and results in misinterpretation by other software

### ISSUE THREAD

**Issue by GLPG-GT** [rdkit/rdkit#7594]
In common cheminformatics practice, molecules with (sp3) stereoatoms, e.g. made from SMILES with '@/@@', are intended by the originator as **stereochemically pure**.  
Similarly, in molecules with 'and'/'or' stereogroups, any stereoatoms that are not part of those groups are usually left unmarked (not made part of an explicit 'abs' stereogroup), and implicitly intended as 'absolute'.

However, as shown in the code further down, `Chem.MolToMolBlock()` _invariably sets the chirality flag of both V2000 and V3000 MolBlock's to 0 (RAC) by default_.

This is an issue, because it is not in line with the standards set by the creator of the Chemical Table format (now Biovia), and results in misinterpretation of the chemical representation.  
In practice, a chirality flag set to 0 results in the interpretation of any _non explicitly marked_ stereoatoms in a MolBlock's as being part of a single 'and' stereogroup.

The only way we found to circumvent this, was to apply `mol.SetIntProp('_MolFileChiralFlag', 1)` before creating the MolBlock, so it propagates to all unmarked stereoatoms.  
Or, for fully absolute molecules, make all stereoatoms explicitly part of an 'abs' stereogroup, so the MolBlock is V3000 and has a mandatory STEABS line (which is some substantial work and remarkable overkill, as V2000 with chirality flag 1 is perfectly adequate for such cases).

**Could you please explain the choice of leaving the chirality flag set to 0 by default, given that in an overwhelming majority of cases people assume 'abs' when no 'and'/'or' is explicitly specified, rather than the other way around?**

**Would it not be best to have instead the chirality flag set to 1 by default in the MolBlock, to ensure correct interpretation?**  
Then the only case where people would have to change it back to 0 is for molecules where all stereoatoms are part of a single 'and' group, which is much rarer than the 'all absolute' case.

It is good that one can fix the issue with 1 simple line of code, but it is very worrying that one may not even be aware of the issue in the first place (maybe simply by thinking that a SMILES without '&' groups represents an absolute molecule, and assuming that rdkit will translate that to an absolute MolBlock).  
From our abundant evidence and experience working with several companies who produce SD files, this detail is really not understood or noticed at all, which is quite unfortunate.

```
#!/usr/bin/env python
# coding: utf-8

# In[2]:

from rdkit import Chem

# In[3]:

# CASE 1
# Molecule with explicit 'abs' stereoatoms
cxsm_abs_explicit = 'C[C@H](Cl)CN1CC[C@@H](O)C1=O |a:1,7|'
m_abs_explicit = Chem.MolFromSmiles(cxsm_abs_explicit)
m_abs_explicit

# In[4]:

# Make MolBlock
mb_abs_explicit = Chem.MolToMolBlock(m_abs_explicit)
print(mb_abs_explicit)

# In[5]:

# This is interpreted as absolute by Biovia software, thanks to the STEABS line --> OK (although the chirality flag in the COUNTS line is inconsistent)

# In[6]:

# CASE 2
# Molecule with stereoatoms left unmarked (assumed 'abs' by the originator)
cxsm_abs_unmarked = 'C[C@H](Cl)CN1CC[C@@H](O)C1=O'
m_abs_unmarked = Chem.MolFromSmiles(cxsm_abs_unmarked)
m_abs_unmarked

# In[7]:

# Make MolBlock
mb_abs_unmarked = Chem.MolToMolBlock(m_abs_unmarked)
print(mb_abs_unmarked)

# In[8]:

# This is interpreted as racemic by Biovia software (due to the chirality flag 0 in the COUNTS line) --> not what the originator intended

# In[9]:

# CASE 3
# Molecule with 1 explicit 'abs' stereoatom and 1 explicit 'and' stereoatom
cxsm_mix_explicit = 'C[C@H](Cl)CN1CC[C@@H](O)C1=O |a:1,&1:7|'
m_mix_explicit = Chem.MolFromSmiles(cxsm_mix_explicit)
m_mix_explicit

# In[10]:

# Make MolBlock
mb_mix_explicit = Chem.MolToMolBlock(m_mix_explicit)
print(mb_mix_explicit)

# In[11]:

# This is correctly interpreted by Biovia software, thanks to the STEABS and STERAC lines

# In[12]:

# CASE 4
# Molecule with 1 explicit 'and' stereoatom, the other one left unmarked (assumed 'abs' by the originator)
cxsm_mix_abs_unmarked = 'C[C@H](Cl)CN1CC[C@@H](O)C1=O |&1:7|'
m_mix_abs_unmarked = Chem.MolFromSmiles(cxsm_mix_abs_unmarked)
m_mix_abs_unmarked

# In[13]:

# Make MolBlock
mb_mix_abs_unmarked = Chem.MolToMolBlock(m_mix_abs_unmarked)
print(mb_mix_abs_unmarked)

# In[14]:

# This is interpreted as 'C[C@H](Cl)CN1CC[C@@H](O)C1=O |&1:7, &2:1|' by Biovia software, because the chirality flag 0 propagates to any unmarked stereoatom

# In[15]:

# Possible fix: set the chirality flag to 1

# In[16]:

m_mix_abs_unmarked.SetIntProp('_MolFileChiralFlag', 1)

# In[17]:

# Make MolBlock
mb_mix_abs_unmarked = Chem.MolToMolBlock(m_mix_abs_unmarked)
print(mb_mix_abs_unmarked)

# In[18]:

# This is correctly interpreted by Biovia software, thanks to the STERAC line, which encodes the '&' group for atom 7, whereas the chirality flag 1 assigns 'abs' to the unmarked stereoatom 1
```

**Comment by greglandrum** [comment]
This is intentional behavior, not a bug. If you want to set (and honor) the stereo flag, the option is there for you to do so.

Despite your very dogmatic statements above, there are multiple different interpretations of what the stereo flag means and how it should be treated, so the RDKit leaves it to client code to set the flag as is appropriate for their use case.

**Comment by GLPG-GT** [comment]
Excellent, thank you very much for your quick and helpful feedback.
