### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [rdkit/rdkit#7603]
CMake Error at Code/GraphMol/MolDraw2D/Qt/Demo/CMakeLists.txt:39 (target_link_libraries):
  Target "rdkitsv" links to:

    Boost::program_options

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

**Comment by zhangfq-chemistry** [comment]
Would you like provide us one C++ example to load xyz file (no bond information available), then determine connectivity/bondtype/rings and so one. Thanks!

**Comment by greglandrum** [comment]
This doesn't look like a bug. I guess when you ran cmake, it told you that it couldn't find boost::program_options. You need to have that installed in order to run the demo.
