### ISSUE TITLE
Crash of multithreaded versions of XXXInPlace() functions

### ISSUE THREAD

**Issue by alkorolyov** [rdkit/rdkit#7613]
**Describe the bug**
I have experienced crashes with some of the XXXInPlace() functions  in multithreaded version. When a single function failes it correctly logs the error:
```
from rdkit import Chem
from rdkit.Chem.MolStandardize.rdMolStandardize import *

mols = [
    Chem.MolFromSmiles('Cc1c2no[n+]([O-])c2c(C)[n+]([O-])[n+]1[O-]'),
    Chem.MolFromSmiles('C')
]

CleanupInPlace(mols, numThreads=2)
```
output:
```
[09:17:45] Initializing MetalDisconnector
[09:17:45] Initializing MetalDisconnector
[09:17:45] Running MetalDisconnector
[09:17:45] Initializing Normalizer
[09:17:45] Running MetalDisconnector
[09:17:45] Initializing Normalizer
[09:17:45] Running Normalizer
[09:17:45] Running Normalizer
[09:17:45] Rule applied: Recombine 1,3-separated charges
[09:17:45] Can't kekulize mol.  Unkekulized atoms: 1 2 3 5 7 8
[09:17:45] FAILED sanitizeMol.
```

However when there are two subsequently failing  functions running after each other the process silently crashes with no error logs and no output.
```
from rdkit import Chem
from rdkit.Chem.MolStandardize.rdMolStandardize import *

mols = [
    Chem.MolFromSmiles('Cc1c2no[n+]([O-])c2c(C)[n+]([O-])[n+]1[O-]'),
    Chem.MolFromSmiles('C')
]

CleanupInPlace(mols, numThreads=2)
TautomerParentInPlace(mols, numThreads=2)
```

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem.MolStandardize.rdMolStandardize import *

mols = [
    Chem.MolFromSmiles('Cc1c2no[n+]([O-])c2c(C)[n+]([O-])[n+]1[O-]'),
    Chem.MolFromSmiles('C')
]

CleanupInPlace(mols, numThreads=2)
TautomerParentInPlace(mols, numThreads=2)
```

**Expected behavior**
First of all we need to fix the issues with crashing and log the errors. Also, it would be good to have a list of indices of failed molecules as an optional output of each XXXInPlace() function so we can filter out the failed molecues.

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.3
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.10.0
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge
 - If you are not using conda: how did you install the RDKit?

**Additional context**

**Comment by bp-kelley** [comment]
I can reproduce on osx, looks to be a simple fix

```
[15:08:21] Can't kekulize mol.  Unkekulized atoms: 1 2 3 5 7 8
[15:08:21] Can't kekulize mol.  Unkekulized atoms: 5
libc++abi: terminating due to uncaught exception of type RDKit::KekulizeException: Can't kekulize mol.  Unkekulized atoms: 5
zsh: abort      python molsinplace.py
```

**Comment by bp-kelley** [comment]
This isn't crashing in the latest build on the master branch, it looks to be resolved.

**Comment by bp-kelley** [comment]
@greglandrum  I'm happy to add this as a test if you like.

**Comment by alkorolyov** [comment]
> This isn't crashing in the latest build on the master branch, it looks to be resolved.

Thank you! Thats a good news. Do you think I should create a separate feature request for those XXXInPlace() functions to return indices of failed molecules?

**Comment by greglandrum** [comment]
> @bp-kelley Thank you! Thats a good news. Do you think I should create a separate feature request for those XXXInPlace() functions to return indices of failed molecules?

Yes please

**Comment by greglandrum** [comment]
The underlying problem with the exception was fixed in v2024.03.4

**Comment by alkorolyov** [comment]
Thank you! The issue with feature request has been created [#7645](https://github.com/rdkit/rdkit/issues/7645)

**Comment by greglandrum** [comment]
> Thank you! The issue with feature request has been created [#7645](https://github.com/rdkit/rdkit/issues/7645)

Thanks @alkorolyov
