### ISSUE TITLE
libRDBoost.so.1: undefined symbol

### ISSUE THREAD

**Issue by kozo2** [rdkit/rdkit#762]
I tried to build and import rdkit with Python.
But there was an error like this.

```
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/rdkit-Release_2015_09_2/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import rdBase
ImportError: /root/rdkit-Release_2015_09_2/lib/libRDBoost.so.1: undefined symbol: _ZN5boost6python23throw_error_already_setEv
```

You can reproduce this with
```
docker run -it kozo2/rdkit-notebook bash
cd
PYTHONPATH=~/rdkit-Release_2015_09_2/ LD_LIBRARY_PATH=~/rdkit-Release_2015_09_2/lib python
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/rdkit-Release_2015_09_2/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import rdBase
ImportError: /root/rdkit-Release_2015_09_2/lib/libRDBoost.so.1: undefined symbol: _ZN5boost6python23throw_error_already_setEv
```

The docker file is https://github.com/kozo2/rdkit-notebook/blob/master/Dockerfile

**Comment by bp-kelley** [comment]
Something certainly changed when we made thread safe the default.  I updated your Dockerfile (see below)
to include boost-system boost-thread and boost-serialization and everything worked as expected (the Dockerfile is below).  I think these should be your defaults, otherwise, you can't do multithreaded conformer generating or substructure searching which can be useful.

I'm still going to file this as a bug, because if system is now a dependency, cmake should fail.

```
FROM ubuntu:14.04
RUN cd; apt update; apt install -y wget flex bison build-essential python-numpy cmake python-dev sqlite3 libsqlite3-dev libboost-dev libboost-system-dev libboost-thread-dev libboost-serialization-dev libboost-python-dev libboost-regex-dev; wget https://github.com/rdkit/rdkit/archive/Release_2015_09_2.tar.gz; tar xf Release_2015_09_2.tar.gz; cd rdkit-Release_2015_09_2; mkdir build; cd build; cmake ..; make; make install
```

**Comment by kozo2** [comment]
Thanks @bp-kelley
https://hub.docker.com/r/kozo2/rdkit-notebook/builds/ works well now.

Is it possible that I send pull request to update http://www.rdkit.org/docs/Install.html#building-from-source ?
Is there public github repository for http://www.rdkit.org/docs ?

**Comment by greglandrum** [comment]
The documentation is here:
https://github.com/rdkit/rdkit/tree/master/Docs/Book

Please feel free to submit a PR against it.

**Comment by kozo2** [comment]
Thanks @greglandrum 
I sent a pull request to https://github.com/rdkit/rdkit/pull/765

**Comment by bp-kelley** [comment]
Fixed and merged.

**Comment by admed** [comment]
I tried latest version of RDKIT from GitHub and I had the same issue with cartridge. Althought I succesfully builded the rdkit and I could import Chem from rdkit but when I tried to add cartridge by:
postgres psql -c 'create extension rdkit' mydatabase
I got the same error:
rdkit.so: undefined symbol:  _ZN5boost6python2thread_data_baseE

**Comment by jt-swanson** [comment]
I just updated my Anaconda to contain rdkit.2016.03. I get basically the same error.
import Chem from rdkit
libboost_serialization.so.1.56.0: undefined symbol: _ZN5boost13serialization6detail17singleton_wrapperINS_7archive6detail12extra_detail3mapINS3_15binary_oarchiveEEEEE14m_is_destroyedE

Is their a different rdkit I should be using. I used conda install -c rdkit rdkit

**Comment by greglandrum** [comment]
@jt-swanson : What system are you installing on? It seems odd to me that you would get a version that old.

**Comment by jt-swanson** [comment]
I have a couple 'legacy' Linux systems. They run RedHat RHEL 5. I've been using them mostly for running scikit-learn. I have Anaconda 4.3.1 installed. That's all been working fine. I've been running rdkit on Windows. I am using Anaconda 4.2.0 there. When I installed rdkit on Windows through conda, it also installed 2016.03.1. On Windows rdkit is quite happily running. But if I could get it running on Linux, I could use it along with some other (legacy) software that also has a Python interface, but doesn't run on Windows.

I installed rdkit using

conda install -c rdkit rdkit

it reverted a lot of packages back to older versions to install rdkit, including boost.

I also tried

conda install -c rdkit boost=1.56.0

but conda just came back and said that was what was installed.

I can run

conda install -c rdkit rdkit=xxxx.xx

but the only one I found to work was 2016.03, though the anaconda repository claims the current version is 2016.09.

**Comment by greglandrum** [comment]
Is that system by any chance legacy enough that it's 32bit?

**Comment by jt-swanson** [comment]
I have a couple system. I was trying to get things running on the machine that has 32bit Linux installed. I do have one machine that has 64bit Linux installed. The processors are 64bit Xeon.
I did the install on the machine with 32bit Linux. I see exactly the same message trying to run on either machine (with the 32bit version of Anaconda/rdkit).

**Comment by greglandrum** [comment]
Yeah, you are getting the old RDKit builds because you have 32 bit Linux installed.

Given the effort involved and lack of demand, I have stopped doing builds for 32 bit Linux systems.

Assuming you actually need the RDKit on that old machine your best option is probably  to do a build yourself (not impossible, but not trivial).

**Comment by jt-swanson** [comment]
I'm not surprised the demand is low. An IT guy installed Linux on these systems many moons ago. Despite the fact that they have 64bit processors and 64bit Linux was available, he was quite insistent that 32bit Linux was  the way to go. I have one system with 64bit Linux (I installed that OS). It's still RHEL 5. When I ask conda to install rdkit, however, it still wants to install 2016.03.

Is this a Continuum Analytics thing- they don't have anything newer through conda? Are there any archived rdkit builds that are older and don't have the particular problem I am seeing?

**Comment by jt-swanson** [comment]
It's not just a matter of 32bit versus 64bit. I installed the 64bit Anaconda4.3.1 and then ran conda install -c rdkit rdkit. It installed boost-1.56.0-py27_3 and rdkit-2016-09.4-nplllpy27_1. The install was cleaner in that no other packages were upgraded or downgraded. However, the result is the same. When I try from rdkit import Chem, I see the same libboost_serialization.so.1.56.0: undefined symbol error.
