### ISSUE TITLE
Missing Tautomers for Zwitterions

### ISSUE THREAD

**Issue by corinwagen** [rdkit/rdkit#7621]
**Describe the bug**

Tautomer enumeration doesn't include tautomers for zwitterionic species (`C[NH+](C)C(=O)[O-]`).

**To Reproduce**

```python
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize

smiles = "C[NH+](C)C(=O)[O-]"
m = Chem.MolFromSmiles(smiles)

enumerator = rdMolStandardize.TautomerEnumerator()
tauts = enumerator.Enumerate(m)
for taut in tauts:
     print(Chem.MolToSmiles(taut))
```

output: `C[NH+](C)C(=O)[O-]` not `CN(C)C(=O)O` (both would be even better)

**Expected behavior**
It would be good to canonicalize this molecule.

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2024.3.3 (from pypi)
 - OS: Sonoma 14.3 (macOS)
 - Python version (if relevant): 3.11.9
 - Are you using conda? N/A
 - If you are using conda, which channel did you install the rdkit from? N/A
 - If you are not using conda: how did you install the RDKit? pypi

**Additional context**
This happens for other compounds too, like `C[NH+](C)S(=O)(=O)[O-]`. Putting in the "regular"/neutral tautomers doesn't generate the zwitterions in either case, also.

**Comment by greglandrum** [comment]
Hi @corinwagen
The tautomer enumeration code uses a set of rules adapted from [this paper](http://link.springer.com/10.1007/s10822-010-9346-4) for doing the enumeration. These rules do not generally handle charged atoms.

If you want to neutralize species like this you can use the Uncharger:
```
In [31]: smiles = "C[NH+](C)C(=O)[O-]"

In [32]: m = Chem.MolFromSmiles(smiles)

In [33]: uc = rdMolStandardize.Uncharger()

In [34]: Chem.MolToSmiles(uc.uncharge(m))
Out[34]: 'CN(C)C(=O)O'
```
Note that the uncharger is smart enough to not modify the molecule if you have a quaternary N that cannot be neutralized by removing an H:
```
In [35]: m2 = Chem.MolFromSmiles('C[N+](C)(C)C(=O)[O-]')

In [36]: Chem.MolToSmiles(uc.uncharge(m2))
Out[36]: 'C[N+](C)(C)C(=O)[O-]'
```

**Comment by greglandrum** [comment]
I'm going to close this since the code is behaving as expected. 

We could think about adding a tautomerization rule that moves Hs from positively charged centers to negatively charged ones, but that should probably be a discussion topic first.

**Comment by corinwagen** [comment]
good clarification. thanks for the quick response @greglandrum and for all the work over the years!
