### ISSUE TITLE
Deprecation warning from Descriptors.CalcMolDescriptors

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#7625]
**Describe the bug**
Not really a bug just an observation. When using the function `Descriptors.CalcMolDescriptors` for every call 3 warnings `DEPRECATION WARNING: please use MorganGenerator` are emitted.

**To Reproduce**
from rdkit import Chem
mol = Chem.MolFromSmiles("CCC")
desc = Descriptors.CalcMolDescriptors(mol)

**Expected behavior**
Adjust the functions used inside `CalcMolDescriptors`   so that they all uses the new way to generate Fingerprints.
And maybe there is potential for some minor optimization to not calculate it 3 times for every molecule

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.4
 - OS: Windows 10
 - Python version (if relevant): 3.12.4
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by VladaMilch** [comment]
Hi all, I am still having this issue, though I've installed rdkit with pip (on MacOS). Here is the version:
``` rdkit-2024.3.5-cp312-cp312-macosx_11_0_arm64.whl.metadata ```

**Comment by FirthMike** [comment]
I am also seeing this deprecation warning when using AllChem.GetMorganFingerprintAsBitVect. I updated Descriptors.py to the updated version from github.

**Comment by greglandrum** [comment]
> Hi all, I am still having this issue, though I've installed rdkit with pip (on MacOS). Here is the version: `rdkit-2024.3.5-cp312-cp312-macosx_11_0_arm64.whl.metadata`

The fix will be in the 2024.03.6 release, due next week

**Comment by greglandrum** [comment]
> I am also seeing this deprecation warning when using AllChem.GetMorganFingerprintAsBitVect. I updated Descriptors.py to the updated version from github.

I'm not sure what you mean @FirthMike : are you calling `GetMorganFingerprintAsBitVect()` yourself? That function is deprecated and we suggest that you use a fingeprint generator instead (https://greglandrum.github.io/rdkit-blog/posts/2023-01-18-fingerprint-generator-tutorial.html)

**Comment by FirthMike** [comment]
> > I am also seeing this deprecation warning when using AllChem.GetMorganFingerprintAsBitVect. I updated Descriptors.py to the updated version from github.
> 
> I'm not sure what you mean @FirthMike : are you calling `GetMorganFingerprintAsBitVect()` yourself? That function is deprecated and we suggest that you use a fingeprint generator instead (https://greglandrum.github.io/rdkit-blog/posts/2023-01-18-fingerprint-generator-tutorial.html)

Thank you for the lighning response!

Yes - I'm calling AllChem.GetMorganFingerprintAsBitVect - it wasn't clear that AllChem.GetMorganFingerprintAsBitVect is deprecated from the warning - so I assumed it was a similar issue to CalcMolDescriptors above.

Thank you for the URL - I will use the fingerprint generator from now on.
