### ISSUE TITLE
EnumerateLibrary.GetPosition() surprisingly slow

### ISSUE THREAD

**Issue by jpfeuffer** [rdkit/rdkit#7639]
**Describe the bug**
In a simple enumeration loop, if one is iterating over library.GetPosition() in the loop, it takes up to 40% of the runtime of the loop.
For a full enumeration, counting/calculating the position yourself everytime in python is much faster and reduces the overhead to almost zero compared to the actual work in the iterator (i.e. RunReactants).

**To Reproduce**
Will update to a full example soon.

```
    library = EnumerateLibrary(rxn, bbs)
    reagents = library.GetReagents()
    for product_template_results in library:
        # print input reactant monomers and the product
        libpos = library.GetPosition()
        for i, n in enumerate(libpos): # <- this line iterates over a vector of size_t with 3 elements and takes 40% of the runtime
            print(reagents[i][n].GetProp("_Name"))
```

**Expected behavior**
The line taking less than 1% of the runtime.

**Screenshots**
<img width="1711" alt="Screenshot 2024-07-20 at 11 26 53" src="https://github.com/user-attachments/assets/f085abe2-afde-42ff-8504-c420e179020b">

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.6
 - OS: macOS 14.5
 - Python version (if relevant): 3.11
 - Are you using conda? no

**Comment by bp-kelley** [comment]
Wow, that is amazingly slow

```
for product_template_results in library:
        # print input reactant monomers and the product
        libpos = library.GetPosition()

6.11 ms ± 13 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

```
 for product_template_results in library:
     # print input reactant monomers and the product
     libpos = library.GetPosition()
     for i, n in enumerate(libpos): 
         pass

111 ms ± 271 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

```
for template_results in library:
     # print input reactant monomers and the product
     libpos = library.GetPosition()
     pos = libpos[0], libpos[1]

6.26 ms ± 13.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

I think I can probably return a python tuple as opposed to the boost wrapped vector and see if this speeds it up.

**Comment by jpfeuffer** [comment]
Aah I actually didn't think about indexing! Good idea. This is a better workaround for now.

Yes a tuple would probably be fine here.

I hope the iteration in other registered wrapped Vect types is not so bad. Didn't check others.

**Comment by greglandrum** [comment]
Here's a simpler example that also uses on of the boost::python - generated vector proxies.

First a "longer" vector (47 entries):
```
In [55]: m = Chem.MolFromSmiles('C'*50)

In [56]: ps = Chem.FindAllPathsOfLengthN(m,3)

In [57]: len(ps)
Out[57]: 47

In [58]: %timeit [(i,x) for i,x in enumerate(ps)]
18.7 μs ± 171 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [59]: %timeit [x for x in ps]
17.5 μs ± 127 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [60]: %timeit [ps[i] for i in range(len(ps))]
27.1 μs ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [61]: lps = len(ps)

In [62]: %timeit [ps[i] for i in range(lps)]
27 μs ± 57.5 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

Now a shorter one (3 entries):
```
In [65]: ps47 = Chem.FindAllPathsOfLengthN(m,47)

In [66]: len(ps47)
Out[66]: 3

In [67]: %timeit [(i,x) for i,x in enumerate(ps47)]
8.7 μs ± 6.53 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [68]: %timeit [x for x in ps47]
8.54 μs ± 33.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [74]: %timeit [ps47[i] for i in range(len(ps47))]
1.27 μs ± 0.586 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [75]: lps = len(ps47)

In [76]: %timeit [ps47[i] for i in range(lps)]
1.17 μs ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

There clearly is overhead associated with iterating over the elements of one of the proxies as well as with repeatedly indexing into the vector (which also requires crossing into C++).

For comparison, here's the same timing if I convert the longer list to a tuple first:
```
In [78]: tpl = tuple(tuple(x) for x in ps)

In [80]: %timeit [x for x in tpl]
335 ns ± 1.41 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [81]: %timeit [(i,x) for i,x  in enumerate(tpl)]
873 ns ± 7.79 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [82]: %timeit [tpl[i] for i in range(len(tpl))]
455 ns ± 1.83 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

**Comment by greglandrum** [comment]
For cases like these where the C++ is returning a new data structure which is intended to be handed to, and owned by, Python, it probably would make sense to return tuples (since the returned objects are immutable and all of the same type) instead of the vector proxies. We already do this in some places, but writing some helper code to make it easier wouldn't be dumb.

There may be some issues with situations where we need to save ownership information (like when the members of the returned tuple need to keep the owning class alive), but we can keep an eye out for those.

**Comment by bp-kelley** [comment]
#7719 put in the framework to close this issue, the next PR will actually fix this and a few others,
