### ISSUE TITLE
AnyBond specification treated as single when joining rings in SMARTS

### ISSUE THREAD

**Issue by teaguesterling** [rdkit/rdkit#766]
SMARTS parsing treats the AnyBond (`~`) as a single bond when it is specified at a ring joining. The parsing respects other bond type specifications (aromatic, double, triple). 

I'm not sure if it's relevant, but when there is inconsistency appears to respect the first occurs.

This is with an up-to-date build from the trunk on CentOS 6.7.
```
In [2]:
m = C.MolFromSmarts('C~1~C~C~C~C~C~1')
for b in m.GetBonds():
    print b.GetBondType()
```
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> SINGLE

```
In [3]:
m = C.MolFromSmarts('C=1~C~C~C~C~C=1')
for b in m.GetBonds():
    print b.GetBondType()
```
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> DOUBLE

```
In [4]:
m = C.MolFromSmarts('C#1~C~C~C~C~C=1')
for b in m.GetBonds():
    print b.GetBondType()
```
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> UNSPECIFIED
> TRIPLE

**Comment by greglandrum** [comment]
Confirmed. Thanks for reporting this!
