### ISSUE TITLE
The old way to use MCSProgress stopped working for me after the 2024 update

### ISSUE THREAD

**Issue by chmnk** [rdkit/rdkit#7663]
**Describe the bug**
On RDKit versions up to 2023.03.3, I used to use the snippet from [this issue](https://github.com/rdkit/rdkit/issues/3085) on how to use the `rdFMCS.MCSProgress`. However, in 2024.03.1 it doesn't work anymore.

**To Reproduce**
```python
import time

from rdkit import Chem
from rdkit.Chem.rdFMCS import FindMCS, MCSParameters, BondCompare, AtomCompare, MCSProgress

class ProgressCallback(MCSProgress):
    def __init__(self):
        super().__init__()
        self._timeout_delta = None
        self._timeout_start = None

    def callback(self, stat, params):
        res = True
        if self._timeout_start is None:
            self._timeout_start = time.time()
            self._timeout_delta = params.Timeout
        else:
            res = (time.time() - self._timeout_start) < self._timeout_delta
        return res


def mcs_job(
    mol0,
    mol1,
    timeout: int = 5,
):
    ps = MCSParameters()
    ps.ProgressCallback = ProgressCallback()
    ps.Timeout = timeout
    
    ps.ProgressCallback.__init__()
    mcs = FindMCS([mol0, mol1] , ps)
    print(mcs.smartsString)

mol0 = Chem.MolFromSmiles("CCC")
mol1 = Chem.MolFromSmiles("CC")


mcs_job(mol0, mol1)
```
**Expected behavior**
I would expect MCS being computed, but I am getting the following error:
```bash
Boost.Python.ArgumentError: Python argument types in
    MCSProgress.__call__(ProgressCallback, MCSProgressData, MCSParameters)
did not match C++ signature:
    __call__(RDKit::PyMCSProgress {lvalue} self, RDKit::MCSProgressData stat, RDKit::MCSParameters parameters)
```
It doesn't look self-explanatory to me, cause I would expect `ProgressCallback` to be a child of `RDKit::PyMCSProgress` and thus I don't get why doesn't it match the signature.

**Configuration (please complete the following information):**
 - RDKit version:
 2024.03.1 vs 2024.03.5
 - OS:
 Rocky8
 - Python version (if relevant):
 3.12
 - Are you using conda? 
 yes
 - If you are using conda, which channel did you install the rdkit from?
 conda-forge

**Comment by ptosco** [comment]
@chmnk Sorry for the late reply. This is not a bug; it is actually the expected behavior.
`MCSProgress.callback()` has been deprecated for a while in favor of `MCSProgress.__call__()` and was removed in a recent release. You only need to replace `callback` with `__call__` in your `ProgressCallback` class definition.

**Comment by chmnk** [comment]
I see, thanks a lot!
