### ISSUE TITLE
rdMolAlign.GetBestRMS gets stuck 

### ISSUE THREAD

**Issue by LiuCMU** [rdkit/rdkit#7685]
Hello, while trying to get the best RMS value between 2 conformers, the code runs infinitely without returning any results. I have attached an example SDF file, and below is the reproduction code:
```python
    from rdkit.Chem import rdMolAlign


    path = '/home/jack/Auto3D_pkg/src/debug.sdf'
    supp = Chem.SDMolSupplier(path, removeHs=True)
    mol1 = supp[0]
    mol2 = supp[1]
    rmsd = rdMolAlign.GetBestRMS(mol1, mol2)
    print(rmsd)
```
[debug.sdf.txt](https://github.com/user-attachments/files/16465581/debug.sdf.txt)

**Configuration:**

- RDKit Version: 2023.9.5
- Operating system: Ubuntu 20.04.6 LTS
- Python version (if relevant): 3.9.19
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? pypi
- If you are not using conda: how did you install the RDKit? pypi

**Description:**

When my code executes the line containing `rmsd = rdMolAlign.GetBestRMS(mol1, mol2)`, it gets stuck there forever. Does anyone know the cause for this? Thanks a lot!

**Comment by phonglam3103** [comment]
Have you tried using multithreads, eg. rdMolAlign.GetBestRMS(mol1, mol2, numThreads = 0)?

**Comment by LiuCMU** [comment]
Thank you @phonglam3103 

I think it is a system issue related to RDKit and Linux, rather than a speed issue. The above reproduction code returns the RMS value normally on a Mac in one or two seconds. This indicates that the task is lightweight and can be handled by a single thread.  However, it just got stuck forever on an Ubuntu machine. My Ubuntu machine is a cluster and is much more powerful than the Mac. I am not sure if it is an issue of RDKit or the Ubuntu machine. Does anyone experience similar problem?

**Comment by LiuCMU** [comment]
I aslo tried the same code on a Google Colab, which runs Ubuntu 22.04.3 LTS but got the same issue: https://colab.research.google.com/drive/1_25d5GiggJmBkeJYtHCLX6uRV8wgnO0_?usp=sharing

**Comment by phonglam3103** [comment]
https://github.com/rdkit/rdkit/discussions/7581#discussioncomment-10082833
The problem sounds like this discussion. Likely it is something that Greg could not reproduce with his Linux system.

**Comment by LiuCMU** [comment]
Thanks @phonglam3103 This [discussion](https://github.com/rdkit/rdkit/discussions/7581) is very relevant.

It inspired me to play around the `maxMatches` argument. If I leave `maxMatches` to be the default value 1000000, it runs for 0.1 minutes on a Mac, but runs forever on an Ubuntu machine. For the Ubuntu machine, if I reduce `maxMatches` to 100000, it took 0.38 minutes. 

Here is my updated code using the same input file:
```python
import time
import rdkit
from rdkit.Chem import rdMolAlign
from rdkit import Chem


start = time.time()
print(rdkit.__version__)
path = '/home/jack/run_auto3d/debug.sdf'
supp = Chem.SDMolSupplier(path, removeHs=True)
mol1 = supp[0]
mol2 = supp[1]
rmsd = rdMolAlign.GetBestRMS(mol1, mol2, maxMatches=1000000)
print(rmsd)
end = time.time()
print(f'Elapsed time: {(end - start)/60:.2f} minutes')
```

My molecules are small, so I wasn't expecting it would take that long on an Ubuntu machine...

**Comment by greglandrum** [comment]
Hi @LiuCMU , unless you can provide the exact input you used, we cannot help you here

**Comment by LiuCMU** [comment]
Hey @greglandrum Thanks for participating our discussions! The input is the SDF file attached in my first comment. Please let me know if any additional info is needed. Thanks!

**Comment by ricrogz** [comment]
I have looked a bit into this, and it seems this depends a lot on where the example is run, probably due to the underlying C++ implementation. I have been able to reproduce it on a Rocky8 docker container, but not on Ubuntu 22.04 or on a Mac.

**Comment by thegodone** [comment]
Hi all, Can you put the file again please ?

**Comment by ricrogz** [comment]
> Hi all, Can you put the file again please ?

@thegodone, the file is linked in the first comment as "[debug.sdf.txt](https://github.com/user-attachments/files/16465581/debug.sdf.txt)'
