### ISSUE TITLE
RDKitValidation doesn't catch some valence issues

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#7689]
**Describe the bug**
The `RDKitValidation` class doesn't return an error for some valence violations that are not detected by `Atom::calcExplicitValence`.

**To Reproduce**

    In [1]: from rdkit import Chem
    
    In [2]: from rdkit.Chem.MolStandardize import rdMolStandardize
    
    In [3]: vm = rdMolStandardize.RDKitValidation()
    
    In [4]: mol = Chem.MolFromMolBlock('''
       ...:   MJ240300                      
       ...: 
       ...:   2  1  0  0  0  0  0  0  0  0999 V2000
       ...:    -4.8993    1.8410    0.0000 Br  0  5  0  0  0  0  0  0  0  0  0  0
       ...:    -5.6138    1.4285    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
       ...:   2  1  1  0  0  0  0
       ...: M  END
       ...: ''', sanitize=False)
    
    In [5]: vm.validate(mol)
    Out[5]: []

**Expected behavior**
The validation should fail with an error message like `Explicit valence for atom # 0 Br greater than permitted`

**Configuration (please complete the following information):**
 - RDKit version: current master branch
 - OS: [e.g. Ubuntu 20.04] Fedora 40
 - Python version (if relevant): not relevant
 - Are you using conda? no
 - If you are not using conda: how did you install the RDKit? from source code

**Additional context**
The expected behavior would be easily produced if, in addition to `atom->calcExplicitValence()`, `RDKitValidation` also called `atom->calcImplicitValence()` (just like I think `Atom::hasValenceViolation` does). If this is the desired solution, I would be happy to create a small PR implementing it, but I found it a bit surprising that an "Explicit valence .." error was reported by `Atom::calcImplicitValence` and is not detected by `Atom::calcExplicitValence` and wondered if I am missing something.

Moreover, the behavior apparently depends on the input format, and `C[Br-]` is sanitized without errors.

**Comment by greglandrum** [comment]
Just a reference point: the current release version (2024.03.6) *does* generate the expected warnings here.
