### ISSUE TITLE
Getting Started with Contributing to RDKit - Hackathon Project

### ISSUE THREAD

**Issue by RPirie96** [rdkit/rdkit#7702]
At last year's UGM I’d floated the idea to Greg of a guest blog on coding standards and how to contribute based on [these old slides](https://github.com/rdkit/UGM_2016/blob/master/Presentations/Landrum_Schneider_GitHub_Git_and_RDKit.pdf) of Greg and Nadine's. Having thought about it (as a relatively new contributor myself) I think there's scope for a "Getting Started with Contributing" guide similar to the existing Python/C++ ones, that would serve a couple of purposes:
- provide a starting point for newbies. Having been asked the question of "what and how do I contribute" a few times now it would be super helpful to have a concrete resource to point people to. 
- useful resource for future hackathons
- act as a reminder for more established contributors, especially those who submit irregularly
- another weapon in the arsenal against Greg's "hit by a bus" problem, and would hopefully make the maintainers lives easier by producing better first time submissions :)

There is a lot of information out there already, but scattered across various old slideshows, blog posts, wiki how-to's and (often half written) READMEs buried deep in the repo, that I think could be collated and added to in the following structure (but very open to suggestions!):
- Section 1: What to Contribute
- Section 2: Contributing to the RDKit Docs
- Section 3: Contributing to the Code - Python
- Section 4: Contributing to the Code - C++
- Section 5: Other Contributions - Java/JavaScript/Tutorials/KNIME nodes etc

**Comment by greglandrum** [comment]
I think this is a great idea.
