### ISSUE TITLE
module 'rdkit.Chem.Fragments' has no attribute 'fr_xxxx'

### ISSUE THREAD

**Issue by yang3227** [rdkit/rdkit#7710]
- RDKit version:  '2024.03.5'
 - OS: windows
 - Python version (if relevant): 3.12.5
 - Are you using conda? miniconda
 - If you are using conda, which channel did you install the rdkit from?  conda-forge
 - If you are not using conda: how did you install the RDKit?

I tried a clean env with only RDKit and jupyter notebook installed, got the same error. 

Code:
smile = "CN(CCCNC(=O)C1CCCO1)C2=NC3=CC(=C(C=C3C(=N2)N)OC)OC"
mol = Chem.MolFromSmiles(smile)
Chem.Fragments.fr_amide(mol)

**Comment by greglandrum** [comment]
You have to import the Fragments module:
```
In [1]: from rdkit import Chem

In [2]: m = Chem.MolFromSmiles('CC(=O)NC')

In [3]: from rdkit.Chem import Fragments

In [4]: Fragments.fr_amide(m)
Out[4]: 1
```

**Comment by greglandrum** [comment]
Please do not open a new issue just because you have a question.

The place to ask questions about the RDKit is in the `discussions` tab, not by opening issues.

I think you might find this one relevant:
https://github.com/rdkit/rdkit/discussions/6151
