### ISSUE TITLE
How to handle geometry initialization for molecules with ionic bond

### ISSUE THREAD

**Issue by GiacomoDG96** [rdkit/rdkit#7716]
I am trying to build a pipeline that from a molecule in SMILES format, calculates the energy through DFT using PySCF package.
The code t the moment does not work only in when the molecule contains one or multiple ionic bonds. 
The following is my code:

##########################################################################

      from rdkit import Chem
      from rdkit.Chem import AllChem
      from pyscf import gto, dft, geomopt
      from pyscf.scf import diis

### Function to generate a reasonable initial geometry using RDKit
    def generate_initial_geometry(smiles):
        mol = Chem.MolFromSmiles(smiles)
        mol = Chem.AddHs(mol)
        AllChem.EmbedMolecule(mol, AllChem.ETKDG())
        AllChem.UFFOptimizeMolecule(mol)
        return mol

### Function to convert RDKit molecule to PySCF format
    def rdkit_to_pyscf(mol):
        atom_str = ''
        conf = mol.GetConformer()
        for atom in mol.GetAtoms():
            pos = conf.GetAtomPosition(atom.GetIdx())
            atom_str += f'{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}; '
        return atom_str

### Generate initial geometry for the molecule
    smiles = 'COC1=C([N+](C)(C)C)C(=O)C([N+](C)(C)C)=C(OCc2ccccc2)C1=O.[Cl-].[Cl-]'
    rdkit_mol = generate_initial_geometry(smiles)
    pyscf_geometry = rdkit_to_pyscf(rdkit_mol)

### Define the molecule in PySCF
    mol = gto.M(
        atom=pyscf_geometry,
        basis='6-31G(d)',
        verbose=4
    )

### Set up the DFT calculation with robust SCF parameters
    mf = dft.RKS(mol)
    mf.xc = 'b3lyp'
    mf.max_cycle = 100  # Increase the number of SCF cycles
    mf.diis = diis.DIIS(mf)  # Use DIIS for better convergence
    mf.kernel()

### Check for convergence
    if not mf.converged:
        print("SCF did not converge. Trying a more robust setup.")

    mf = dft.RKS(mol)
    mf.xc = 'b3lyp'
    mf.max_cycle = 100
    mf.init_guess = 'atom'
    mf.damp = 0.5
    mf.kernel()

    mol_eq = geomopt.optimize(mf)

### Extract and print the optimized coordinates and energy
    optimized_coords = mol_eq.atom_coords()
    atom_symbols = mol_eq.atom_symbols()
    optimized_energy = mf.e_tot  # Energy after optimization
  
    print("Optimized Geometry:")
    for symbol, (x, y, z) in zip(atom_symbols, optimized_coords):
        print(f'{symbol} {x:.6f} {y:.6f} {z:.6f}')
  
    print("Energy at Optimized Geometry:")
    print(optimized_energy)
########################################################################################

As you can see the molecule that I am trying to calculate is
**COC1=C([N+](C)(C)C)C(=O)C([N+](C)(C)C)=C(OCc2ccccc2)C1=O.[Cl-].[Cl-]**
![image](https://github.com/user-attachments/assets/1890c8eb-cdf5-43d6-acb7-225597925fc1)

And I obtain the following warning before the error:

[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 C     -0.735604000000   1.387235000000  -3.641262000000 AA   -1.390090096135   2.621494220411  -6.880987927786 Bohr   0.0
[INPUT]  2 O     -1.591512000000   0.851894000000  -2.637812000000 AA   -3.007521803959   1.609846347160  -4.984742248091 Bohr   0.0
[INPUT]  3 C     -1.185262000000   0.395307000000  -1.373192000000 AA   -2.239820565854   0.747021965123  -2.594956796444 Bohr   0.0
[INPUT]  4 C     -2.113717000000   0.069083000000  -0.429903000000 AA   -3.994346234837   0.130547949863  -0.812398930129 Bohr   0.0
[INPUT]  5 N     -3.568745000000   0.278052000000  -0.624544000000 AA   -6.743950658411   0.525442128388  -1.180217112740 Bohr   0.0
[INPUT]  6 C     -4.342325000000   0.020201000000   0.622115000000 AA   -8.205804993852   0.038174357442   1.175626967984 Bohr   0.0
[INPUT]  7 C     -3.848209000000   1.689190000000  -1.005909000000 AA   -7.272061080086   3.192106472354  -1.900892516235 Bohr   0.0
[INPUT]  8 C     -4.078527000000  -0.639967000000  -1.669293000000 AA   -7.707299021644  -1.209362358760  -3.154506591654 Bohr   0.0
[INPUT]  9 C     -1.561673000000  -0.563106000000   0.806414000000 AA   -2.951134266128  -1.064116119099   1.523901603015 Bohr   0.0
[INPUT] 10 O     -2.092636000000  -1.605458000000   1.272401000000 AA   -3.954508918405  -3.033875924492   2.404489410623 Bohr   0.0
[INPUT] 11 C     -0.249629000000  -0.088838000000   1.342564000000 AA   -0.471730442749  -0.167879489454   2.537078264701 Bohr   0.0
[INPUT] 12 N      0.026726000000  -0.027157000000   2.798624000000 AA    0.050504820405  -0.051319292365   5.288632885635 Bohr   0.0
[INPUT] 13 C      0.985203000000  -1.091527000000   3.177896000000 AA    1.861763847100  -2.062687087568   6.005353092351 Bohr   0.0
[INPUT] 14 C      0.571194000000   1.306893000000   3.174813000000 AA    1.079400223995   2.469669844111   5.999527066709 Bohr   0.0
[INPUT] 15 C     -1.209152000000  -0.218623000000   3.608765000000 AA   -2.284966122970  -0.413137594531   6.819577497916 Bohr   0.0
[INPUT] 16 C      0.680267000000   0.229066000000   0.396874000000 AA    1.285518321580   0.432872004450   0.749983165961 Bohr   0.0
[INPUT] 17 O      1.999351000000   0.527976000000   0.781914000000 AA    3.778225816875   0.997730040343   1.477603312963 Bohr   0.0
[INPUT] 18 C      3.055409000000   0.989495000000  -0.061029000000 AA    5.773886208531   1.869874551627  -0.115328095656 Bohr   0.0
[INPUT] 19 C      3.741152000000  -0.156653000000  -0.758210000000 AA    7.069752670369  -0.296031266591  -1.432809244906 Bohr   0.0
[INPUT] 20 C      4.201956000000  -0.004548000000  -2.076810000000 AA    7.940546027473  -0.008594474415  -3.924602112758 Bohr   0.0
[INPUT] 21 C      4.862937000000  -1.056387000000  -2.718856000000 AA    9.189619091014  -1.996282111551  -5.137893212130 Bohr   0.0
[INPUT] 22 C      5.084119000000  -2.260163000000  -2.045101000000 AA    9.607592494698  -4.271089066875  -3.864680787074 Bohr   0.0
[INPUT] 23 C      4.651426000000  -2.411807000000  -0.725186000000 AA    8.789921228681  -4.557654695309  -1.370402929369 Bohr   0.0
[INPUT] 24 C      3.990513000000  -1.362125000000  -0.079273000000 AA    7.540976666516  -2.574043197423  -0.149804259073 Bohr   0.0
[INPUT] 25 C      0.260693000000   0.250606000000  -1.035411000000 AA    0.492638372591   0.473576705173  -1.956643216362 Bohr   0.0
[INPUT] 26 O      1.108919000000   0.098232000000  -1.950663000000 AA    2.095553204327   0.185631576668  -3.686218831322 Bohr   0.0
**[INPUT] 27 Cl     0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.000000000000 Bohr   0.0
[INPUT] 28 Cl     0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.000000000000 Bohr   0.0**
[INPUT] 29 H     -1.358984000000   1.822641000000  -4.448697000000 AA   -2.568107567666   3.444292313403  -8.406818941174 Bohr   0.0
[INPUT] 30 H     -0.097695000000   2.190369000000  -3.216251000000 AA   -0.184616793739   4.139197521737  -6.077833537859 Bohr   0.0
[INPUT] 31 H     -0.112068000000   0.583441000000  -4.084519000000 AA   -0.211777827328   1.102543699842  -7.718622260582 Bohr   0.0
[INPUT] 32 H     -5.412145000000   0.308784000000   0.510221000000 AA  -10.227471796434   0.583517191648   0.964177953002 Bohr   0.0
[INPUT] 33 H     -3.929575000000   0.598966000000   1.478693000000 AA   -7.425820535938   1.131881697926   2.794324792311 Bohr   0.0
[INPUT] 34 H     -4.366108000000  -1.059543000000   0.880368000000 AA   -8.250748350273  -2.002246087200   1.663654408831 Bohr   0.0
[INPUT] 35 H     -3.558775000000   1.919894000000  -2.048653000000 AA   -6.725110088949   3.628073848196  -3.871393094269 Bohr   0.0
[INPUT] 36 H     -3.321210000000   2.394487000000  -0.325099000000 AA   -6.276177302167   4.524924638831  -0.614348073370 Bohr   0.0
[INPUT] 37 H     -4.936767000000   1.921361000000  -0.962366000000 AA   -9.329137570791   3.630846076420  -1.818608171593 Bohr   0.0
[INPUT] 38 H     -5.184026000000  -0.555931000000  -1.770439000000 AA   -9.796389362625  -1.050557334156  -3.345644830249 Bohr   0.0
[INPUT] 39 H     -3.833538000000  -1.696261000000  -1.419147000000 AA   -7.244336908113  -3.205468725781  -2.681799160498 Bohr   0.0
[INPUT] 40 H     -3.647529000000  -0.418992000000  -2.666952000000 AA   -6.892830841409  -0.791780128384  -5.039808867361 Bohr   0.0
[INPUT] 41 H      0.613092000000  -2.090134000000   2.856892000000 AA    1.158575969162  -3.949780823642   5.398743447461 Bohr   0.0
[INPUT] 42 H      1.982509000000  -0.937298000000   2.718875000000 AA    3.746399049485  -1.771236517103   5.137929116927 Bohr   0.0
[INPUT] 43 H      1.139187000000  -1.116776000000   4.280338000000 AA    2.152751434665  -2.110400782487   8.088666540569 Bohr   0.0
[INPUT] 44 H      1.627162000000   1.444025000000   2.872301000000 AA    3.074890540300   2.728811767025   5.427862237314 Bohr   0.0
[INPUT] 45 H     -0.038491000000   2.123506000000   2.727001000000 AA   -0.072737448261   4.012844763871   5.153285031415 Bohr   0.0
[INPUT] 46 H      0.581095000000   1.454229000000   4.278314000000 AA    1.098110402354   2.748094532400   8.084841734892 Bohr   0.0
[INPUT] 47 H     -1.581670000000  -1.263470000000   3.559134000000 AA   -2.988923119441  -2.387612266604   6.725788500628 Bohr   0.0
[INPUT] 48 H     -2.013716000000   0.479043000000   3.284571000000 AA   -3.805371732655   0.905260071890   6.206939626689 Bohr   0.0
[INPUT] 49 H     -1.024833000000  -0.035582000000   4.691800000000 AA   -1.936653693416  -0.067240234964   8.866217031234 Bohr   0.0
[INPUT] 50 H      2.671693000000   1.748187000000  -0.777430000000 AA    5.048768058918   3.303594644525  -1.469129781021 Bohr   0.0
[INPUT] 51 H      3.808834000000   1.497604000000   0.575959000000 AA    7.197653113932   2.830061403053   1.088404768978 Bohr   0.0
[INPUT] 52 H      4.042951000000   0.924157000000  -2.610031000000 AA    7.640070125036   1.746403626100  -4.932243766625 Bohr   0.0
[INPUT] 53 H      5.204940000000  -0.937512000000  -3.738625000000 AA    9.835911094794  -1.771640918493  -7.064977332452 Bohr   0.0
[INPUT] 54 H      5.596480000000  -3.073316000000  -2.543180000000 AA   10.575814461606  -5.807725534244  -4.805913685471 Bohr   0.0
[INPUT] 55 H      4.832901000000  -3.341148000000  -0.200396000000 AA    9.132859277137  -6.313854661638  -0.378693556458 Bohr   0.0
[INPUT] 56 H      3.673410000000  -1.491605000000   0.947394000000 AA    6.941738843239  -2.818724936032   1.790315192056 Bohr   0.0

****WARN: Atoms [26 27] have the same coordinates**

**WARN: Atoms [27 26] have the same coordinates****

###########################################################################################

Given that, it is clear that RDKit is not able to handle to the conversion from SMILES to initial geometry for Cl- (they have both 0,0,0 coordinates).

There is a method or a trick to overcome this limitation ?
Thanks in advance

**Comment by greglandrum** [comment]
We should change the defaults so that `embedFragmentsSeperately` is true.

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
