### ISSUE TITLE
MolCanvas2D drawing upside down

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#774]
It's drawing with Y increasing towards the bottom of the image.

One could be a pedant and argue about whether or not this is a bug, but I'm not going to do that right now... it's better to just fix it.

**Comment by bp-kelley** [comment]
Isn't this correct though?  I thought 2D drawing was left hand rule in general.  x,y==0 at top left.  If you flip this, do you also need to flip the isomeric output rendering?

**Comment by greglandrum** [comment]
I think there's an argument that what it's doing is fine.

The problem is that things like Marvin render things "correctly" so that when you see an RDKit rendering next to a Marvin rendering in, for example, KNIME, the RDKit one looks wrong.
