### ISSUE TITLE
SaltRemover loses E/Z configuration

### ISSUE THREAD

**Issue by JuniorSen** [rdkit/rdkit#7750]
**Describe the bug**
When passing in a custom salt list, E/Z configuration is lost. This is a problem when differentiating between e.g. maleate and fumarate. 

In the case below, the stripped salt SMILES will always represent the first item that it finds in the salt list. You can test this by switching the list around.

**To Reproduce**
`
from rdkit.Chem.SaltRemover import SaltRemover, InputFormat
from rdkit import Chem
from tempfile import NamedTemporaryFile
from pathlib import Path

salt_dict = {'MALEATE':'OC(=O)\C=C/C(O)=O', 'FUMARATE':'OC(=O)/C=C/C(O)=O'}
fumarate_smiles = """OC(=O)\C=C/C(O)=O"""

tf = NamedTemporaryFile(mode="a+", suffix=".fdef", delete=False)
for k,v in salt_dict.items():
    line = f"{v} {k}\n"
    tf.write(line)
tf.seek(0)
tf.close()

remover = SaltRemover(defnFilename=tf.name, defnFormat=InputFormat.SMILES)
Path(tf.name).unlink()

mol = Chem.MolFromSmiles(fumarate_smiles)

_, salts = remover.StripMolWithDeleted(mol, dontRemoveEverything=False)

s = salts[0]

print(Chem.MolToSmiles(s))
print(Chem.MolToSmiles(mol))
`

**Expected behavior**
The mol list returned from SaltRemover to represent the salts that were removed in the configuration that it found them.

**Configuration (please complete the following information):**
 - RDKit version: 2024.03.1
 - OS: Windows11
 - Python version (if relevant): 3.12.3
 - Are you using conda? Yes
 - Which channel did you install the rdkit from? conda-forge

**Comment by greglandrum** [comment]
I'm going to guess that this is happening because the salt removal code does not use chirality when matching.

**Comment by JuniorSen** [comment]
Yes, that appears to be the case - running this with the default salt list will return OC(=O)C=CC(O)=O.

Is it possible to add an optional flag here to match chirality?

**Comment by greglandrum** [comment]
> Is it possible to add an optional flag here to match chirality?

Yep. That could be added as a configuration option to the `SaltRemover` class.
It's a pretty small change to add that option, update the two calls to `DeleteSubstructs()` to use the option, and add a test or two. Do you want to try this yourself?
