### ISSUE TITLE
SDWriter did not write a mol to SD File

### ISSUE THREAD

**Issue by ruslankotl** [rdkit/rdkit#7777]
**Describe the bug**
No data was written to SD File

**To Reproduce**
I ran the following code:
```
        with NamedTemporaryFile(suffix=".sdf") as path:
            writer = Chem.SDWriter(path.name)
            writer.write(mol)
```
It worked for several molecules (which were previously saved in a zipped pickled Pandas dataframe) prior but crashed at the molecule  ([problem_mol.txt](https://github.com/user-attachments/files/16819041/problem_mol.txt))

**Expected behavior**
The molecular data should have been written to file.

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2023.9.3
 - OS: Ubuntu 20.04.6 LTS
 - Python version (if relevant): 3.10.0
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from?  pypi
 - If you are not using conda: how did you install the RDKit?

**Additional context**
 For example, 
```
        with NamedTemporaryFile(suffix=".sdf") as path:
            Chem.MolToMolFile(mol, path.name)
```
worked without issues

**Comment by greglandrum** [comment]
You don't provide enough sample code for us to know exactly what you did, and I can't reproduce this with something simple:
```
In [1]: from rdkit import Chem

In [2]: m = Chem.MolFromMolFile('./problem_mol.txt')

In [3]: m
Out[3]: <rdkit.Chem.rdchem.Mol at 0x7efd68606960>

In [4]: w = Chem.SDWriter('blah.sdf')

In [5]: w.write(m)

In [6]: w = None

In [7]: !cat blah.sdf

     RDKit          3D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -1.3995    0.4492   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7555   -0.4715    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1857    0.0081   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0910    0.6898    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9068   -0.6329   -0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  4  1  0
  1  5  2  0
  2  3  1  0
  2  4  1  0
M  END
$$$$
```

**Comment by ruslankotl** [comment]
The setup was more complicated: I had a class in a file that is initialised with a path to the SD File:
```
class Molecule:
    def __init__(self, input_file: str):
        self.input_file = input_file
        self.base_name = input_file.rsplit(".", maxsplit=1)[0]
        mol = Chem.MolFromMolFile(input_file, removeHs=False)
```
However, I wanted to initialise it in a Jupyter Notebook using a `Mol` object. So, I have defined a child class

```
class MoleculeC(Molecule):
    def __init__(self, mol):
        with NamedTemporaryFile(suffix=".sdf") as path:
            writer = Chem.SDWriter(path.name)
            writer.write(mol)
            super().__init__(path.name)
```

This class should convert a `Mol` object into a temporary SD File and initialise the `Molecule` class. So I accessed a `Mol` object in a dataframe, and this worked for several molecules but failed there. 
```
def mol_from_df_row(row, mol_col='Mol', c_preds='assigned_DFT', c_inds='atom_index_DFT'):
    mol = MoleculeC(row[mol_col])
    ...
    return mol
```

Should I send a slice of a dataframe responsible?

**Comment by bp-kelley** [comment]
You are falling victim to unix buffering.  You haven't flushed the NamedTemporaryFile by the time you call super().__init__

Make the following change:

```
class MoleculeC(Molecule):
    def __init__(self, mol):
        with NamedTemporaryFile(suffix=".sdf") as path:
            with Chem.SDWriter(path.name) as writer;
               writer.write(mol)
            super().__init__(path.name)
```

And all should be well.
