### ISSUE TITLE
` libXrender.so.1: cannot open shared object file` even after installing `libxrender1` package

### ISSUE THREAD

**Issue by mariomeissner** [rdkit/rdkit#7785]
**Describe the bug**
Running `from rdkit.Chem import Draw` fails with:
```
 File "/usr/local/lib/python3.10/site-packages/rdkit/Chem/Draw/__init__.py", line 21, in <module>
    from rdkit.Chem.Draw import rdMolDraw2D
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory
```

Running `apt-get upgrade && apt-get install libxrender1` did not solve the issue.
This happens inside of a Dockerfile. I'm assuming that `libxrender1` is not enough, but I wasn't able to figure out what. 

**To Reproduce**
Steps to reproduce the behavior, feel free to paste a bit of Python in here.

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 
 2024.3.5
 - OS: [e.g. Ubuntu 20.04] 
 `python:3.10-slim`
 - Python version (if relevant): 
 3.10
 - Are you using conda? 
 No
 - If you are using conda, which channel did you install the rdkit from?
 N/A
 - If you are not using conda: how did you install the RDKit?
 poetry

**Comment by greglandrum** [comment]
This is not an RDKit bug; it's a misconfiguration of either your system or the RDKit package you installed.

Since it looks like you are using the pypi package, I would suggest asking in that GitHub repository to see if they can help figure out what is going on.

**Comment by UnMolDeQuimica** [comment]
I am finding the same issue in python:3.12-slim. Did you manage to solve this?

**Comment by mariomeissner** [comment]
I believe I used this and it ended up working, but I've stopped working on this particular project of mine long ago, so can't really help any further than this.

```
apt-get update && apt-get install -y --no-install-recommends libxrender1 libxext6 libexpat1
```
