### ISSUE TITLE
Some Questions about SMILES Generation

### ISSUE THREAD

**Issue by zengkaipeng** [rdkit/rdkit#7839]
I'm curious about why `MolToSmiles` does not output atoms in the SMILES string according to the order of atoms obtained by `GetAtoms()` when `canonical` is set to `False`. Is this a bug? Here's an example of the code:

```python
y = 'c12n(c(C(F)F)nc1cccc2)-c1cc(nc(n1)NC[C@H]1CC[C@H](NC)CC1)N1CCOCC1'
Chem.MolToSmiles(Chem.MolFromSmiles(y), canonical=False)
# Output: 'c12n(-c3cc(N4CCOCC4)nc(NC[C@H]4CC[C@H](NC)CC4)n3)c(C(F)F)nc1cccc2'
Symbols = [x.GetSymbol() for x in Chem.MolFromSmiles(y).GetAtoms()]
print(Symbols)
# Output: ['C', 'N', 'C', 'C', 'F', 'F', 'N', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'N', 'N', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C']
```

Furthermore, is there any method to output atoms in the generated SMILES according to a given atom order?

**Comment by bp-kelley** [comment]
This is simply the way SMILES works, please refer to your discussion https://github.com/rdkit/rdkit/discussions/7840 and I'm happy to talk through it more.

**Comment by bp-kelley** [comment]
I noted there was a bug in your code, you are using the original molecule not the new one in your test

```
y = 'c12n(c(C(F)F)nc1cccc2)-c1cc(nc(n1)NC[C@H]1CC[C@H](NC)CC1)N1CCOCC1'
y2 = Chem.MolToSmiles(Chem.MolFromSmiles(y), canonical=False)
# Output: 'c12n(-c3cc(N4CCOCC4)nc(NC[C@H]4CC[C@H](NC)CC4)n3)c(C(F)F)nc1cccc2'
Symbols = [x.GetSymbol() for x in Chem.MolFromSmiles(y2).GetAtoms()]
print(Symbols)
```

```
['C', 'N', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'N', 'C', 'N', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'N', 'C', 'C', 'F', 'F', 'N', 'C', 'C', 'C', 'C', 'C']
```

However, in general, we don't support arbitrary orderings of atoms in smiles strings.

**Comment by zengkaipeng** [comment]
> I noted there was a bug in your code, you are using the original molecule not the new one in your test
> 
> ```
> y = 'c12n(c(C(F)F)nc1cccc2)-c1cc(nc(n1)NC[C@H]1CC[C@H](NC)CC1)N1CCOCC1'
> y2 = Chem.MolToSmiles(Chem.MolFromSmiles(y), canonical=False)
> # Output: 'c12n(-c3cc(N4CCOCC4)nc(NC[C@H]4CC[C@H](NC)CC4)n3)c(C(F)F)nc1cccc2'
> Symbols = [x.GetSymbol() for x in Chem.MolFromSmiles(y2).GetAtoms()]
> print(Symbols)
> ```
> 
> ```
> ['C', 'N', 'C', 'C', 'C', 'N', 'C', 'C', 'O', 'C', 'C', 'N', 'C', 'N', 'C', 'C', 'C', 'C', 'C', 'N', 'C', 'C', 'C', 'N', 'C', 'C', 'F', 'F', 'N', 'C', 'C', 'C', 'C', 'C']
> ```
> 
> However, in general, we don't support arbitrary output orderings of atoms in smiles strings. I believe that the atom order will be the same as the elements in the input smiles string though.

Well there is not bug in my code. I'm just wondering if it's possible to generate a SMILES as `y` in my code using `MolToSmiles`.

**Comment by bp-kelley** [comment]
Apologies, I had thought you had wanted the atoms in order to y2 above.  Note that you can always mark the atoms with atom map numbers to track where they end up.  It's ugly, but works for these purposes:

```
 >> y = 'c12n(c(C(F)F)nc1cccc2)-c1cc(nc(n1)NC[C@H]1CC[C@H](NC)CC1)N1CCOCC1'
>>> m = Chem.MolFromSmiles(y)
>>> for atom in m.GetAtoms():
...     atom.SetAtomMapNum(atom.GetIdx())
>>> Chem.MolToSMmiles(m)
'c12[n:1](-[c:12]3[cH:13][c:14]([N:28]4[CH2:29][CH2:30][O:31][CH2:32][CH2:33]4)[n:15][c:16]([NH:18][CH2:19][C@H:20]4[CH2:21][CH2:22][C@H:23]([NH:24][CH3:25])[CH2:26][CH2:27]4)[n:17]3)[c:2]([CH:3]([F:4])[F:5])[n:6][c:7]1[cH:8][cH:9][cH:10][cH:11]2'
```
