### ISSUE TITLE
numBranchBits for Topological Torsion Fingerprint

### ISSUE THREAD

**Issue by skodape** [rdkit/rdkit#784]
The [GetAtomCode](https://github.com/rdkit/rdkit/blob/1bf6ef3d65f5c7b06b56862b3fb9116a3839b229/Code/GraphMol/Fingerprints/AtomPairs.cpp#L38) seems to be used by Topological Torsion Fingerprint.

This function utilize following code to compute an atom code:
`code = numBranches % maxNumBranches;`
`code |= nPi << numBranchBits;`
`code |= typeIdx << (numBranchBits + numPiBits);`

The constant are defined as follow:
`const unsigned int numTypeBits=4;`
`const unsigned int numPiBits=2;`
`const unsigned int numBranchBits=3;`
in [AtomPairs](https://github.com/rdkit/rdkit/blob/1bf6ef3d65f5c7b06b56862b3fb9116a3839b229/Code/GraphMol/Fingerprints/AtomPairs.h#L40).

The [Topological torsion: a new molecular descriptor for SAR applications. Comparison with other descriptors](http://pubs.acs.org/doi/abs/10.1021/ci00054a008?journalCode=jcics1) states:
`The three pieces of information concerning each of the four atoms (viz., the atom type, the number of a electrons, and the number of non-hydrogen-atom branchings) are packed into a 32-bit word. Each atom-type field occupies 4 bits; the number of a electrons and the number of non-hydrogen-atom branchings each occupy 2 bits. `

So the number of branchBits should be 2 not 3.

However the article [Atom Pairs as Molecular Features in Structure-Activity Studies: Definition and Applications](http://pubs.acs.org/doi/abs/10.1021/ci00046a002) states:
`atom property value = 64 X (atom-type value) + 16 X (number of bonding pi electrons) + number of non-hydrogen neighbors. For up to three pi-electrons and up to 15 non-hydrogen neighbors, this formula provides an unambiguous numerical represention for all three properties.`

So the number of branchBits should be 4. 

Am I missing something?

**Comment by greglandrum** [comment]
@skodape : the goal is not to exactly reproduce the original numerical values of the fingerprints exactly, so adhering to precisely what is in the paper is not necessary.

To explain why `numBranchBits` is 3: 4 bits is clearly more than necessary for the subset of chemistry that the RDKit is intended to deal with "comfortably". 2 bits (= a max of 3 neighbors) is clearly not enough for atom pairs. So I picked 3 bits (=max of 7 neighbors).

Does that help?

**Comment by skodape** [comment]
@greglandrum Thanks for explanation, you are right that it should not be problem most of the time (especially for TT). It might just be a useful info for someone who use RDKit as an implementation of TT/AP in scientific paper, where it might be interesting (also for better experiment reproducibility) to know about this.
