### ISSUE TITLE
chiral lexical order for ring closure after branch

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#786]
RDKit allows ring closures after a branch, like:

    >>> Chem.CanonSmiles("C(I)1.N1")
    'NCI'

This is not a Daylight SMILES, I think, because theory.smiles.html says "The [ring] bonds are numbered in any order, designating ring opening (or ring closure) bonds by a digit immediately following the atomic symbol at each ring closure." Nor is it a valid OpenSMILES.

There's no reason this can't be a valid extension syntax. However, I don't think it works correctly with chiral specifications.  Consider the following:

    >>> smiles = r"CC(C)[C@@](N)1CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](/C=C1)(C)O)O)C"
    >>> smiles2 = smiles.replace(r"(N)1", r"1(N)")
    >>> smiles == smiles2
    False
    >>> Chem.CanonSmiles(smiles) == Chem.CanonSmiles(smiles2)
    True

The Daylight documentation says "The chiral order of the ring closure bond is implied by the lexical order that the ring closure digit appears on the chiral atom (not in the lexical order of the "substituent" atom). " I *believe* that means C[C@@]1(N)C should have a different chirality than C[C@@](N)1C because the permutation order of the four bonds has changed.

Honestly, I don't think it's a useful extension because it's hard to even figure out what is the right solution for this case, and I don't think people use it. OpenSMILES doesn't support it.

But I see that Open Babel and SMARTSviewer both support it. OB inverts the chirality between these two cases, while SMARTSviewer shows identical images.

    >>> pybel.readstring("smi", smiles).write("smi")
    'CC(C)[C@]1(N)CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](C=C1)(C)O)O)C\t\n'
    >>> pybel.readstring("smi", smiles2).write("smi")
    'CC(C)[C@@]1(N)CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](C=C1)(C)O)O)C\t\n'

**Comment by greglandrum** [comment]
I believe that the bug here is that the SMILES is accepted at all. You're absolutely right that it's confusing.
Thanks for finding and reporting this Andrew.

**Comment by coleb** [comment]
If it helps, OEChem interprets the stereo-chemistry differently: 

```
>>> smiles = r"CC(C)[C@@](N)1CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](/C=C1)(C)O)O)C"
>>> smiles2 = smiles.replace(r"(N)1", r"1(N)")
>>> m1 = OEGraphMol()
>>> m2 = OEGraphMol()
>>> OESmilesToMol(m1, smiles)
True
>>> OESmilesToMol(m2, smiles2)
True
>>> OEMolToSmiles(m1)
'CC(C)[C@@]1(CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](C=C1)(C)O)O)C)N'
>>> OEMolToSmiles(m2)
'CC(C)[C@]1(CC[C@]2([C@@H](O2)CCC(=C)[C@H](CC[C@@](C=C1)(C)O)O)C)N'
```

Still pondering what the best course of action is.

**Comment by greglandrum** [comment]
Thanks @coleb 
If both OpenEye and OpenBabel support this, I think the RDKit should continue to.

I will fix the bug that causes the stereochemistry to be wrong when the ring closure follows the branch.
