### ISSUE TITLE
HasPropWithValueQueryBase::getPair() may leak the value of RDValue.

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#7865]
`HasPropWithValueQueryBase::getPair()` returns a `Dict::Pair()`, which contains a `RDValue` member. `RDValue` holds non-POD data in the form of pointers, and since neither `RDValue` nor `Dict::Pair()` have destructors, the values will leak if not cleaned up.

Found by running `pickleTestsCatch  "pickling HasPropWithValue queries"` under asan. It's not trivially fixable, so I'm raising it here instead of rushing a fix.

**Comment by bp-kelley** [comment]
Good catch, I'll take a look.

**Comment by bp-kelley** [comment]
the solution is pretty straightforward, I'll change the getPair API into 

```
Dict::Pair &getPair()
```

so the query can do it's own memory management.  This is a case of me not reading my own documentation.

**Comment by bp-kelley** [comment]
@ricrogz could you check #7872 to see if it fixes the leaks?

**Comment by ricrogz** [comment]
> @ricrogz could you check #7872 to see if it fixes the leaks?

Hm, after your fix I still see some leakead RDValues. I'll try to find out where these come from.

Also, regarding the fix and your comment above (`This is a case of me not reading my own documentation.`), I have to sy I was hoping we could find another way to fix this, one that would allow `getPair()` to return something "safe", as I don't trust us to read the documentation either the next time we use it
