### ISSUE TITLE
MolFromPDBFile not reading Br, Cl, etc.

### ISSUE THREAD

**Issue by Ltwicke** [rdkit/rdkit#7868]
**Describe the bug**
So it appears, that the reader just skips over the lines he cant read. The Bromine atom is not read. So are Cl atoms and i suppose all other atom types that have two letters to their names. 
I have to say that the pdb files were created by a script that _could_ be faulty, but i dont know how to correct it...

I would expect the reader to throw an error, instead of just saying nothing

**Screenshots**
![image](https://github.com/user-attachments/assets/9414c2b9-f213-4eb0-8122-03ab96d31efa)
![image](https://github.com/user-attachments/assets/22c5df82-3334-4fed-bf5c-187b6fcb8c1e)

Rdkit version: '2024.03.5'

**Comment by rwxayheee** [comment]
Hello @Ltwicke 
The issue might be related to the position of the atom name. Shifting the atom name 'Br14' one column to the left worked for me. (rdkit 2024.03.6). In a PDB file the atom name needs to be in columns 13-16, while column 17 is the identifier (usually a letter) for any alternate location

**Comment by bp-kelley** [comment]
To follow up, while a pdb looks like it's whitespace delimited, it is not.  The PDB was made back in the fortran days and as @rwxayheee mentioned, elements need to be in specific columns.

The format of the definition is here:

https://files.wwpdb.org/pub/pdb/doc/format_descriptions/Format_v32_letter.pdf

a more readable one is here:

https://www.biostat.jhsph.edu/~iruczins/teaching/260.655/links/pdbformat.pdf

Note that this is also considered a legacy format due to it's many limitations.

**Comment by bp-kelley** [comment]
Here is a way to test your single atom line

```
from rdkit import Chem
# X = ATOM/HETATOM
# S = serial number
# N = atom name
# L = alternate location
# R = residue name
# C = chain identifier (A/B/C...)
# I = Insertion code
# X =x coord
# Y =y coord
# Z =zcoord
# O = occupancy
# T = temperature factor
# G = segment identifier (optional)
# E = element symbol
# C = charge (optional)
#                    1         2         3         4         5         6         7 
#           12345678901234567890123456789012345678901234567890123456789012345678901234567890
#           XXXXXXSSSSSSNNNNLRRR#C####I   XXXXXXXXYYYYYYYYZZZZZZZZOOOOOOTTTTTT      GGGGEECC
atomline = "ATOM     36 Cl   LIG d   1      -1.819  14.472  27.463  1.00  0.00          Cl  "
m = Chem.MolFromPDBBlock(atomline)
print(Chem.MolToSmiles(m))
```

**Comment by bp-kelley** [comment]
If looks like your BR14 line is incorrect as it "bleeds over" into the alternate location, but that should still read.  If you paste in that single line using markdown's back ticks we can sort it out.  https://daringfireball.net/projects/markdown/syntax#code

**Comment by Ltwicke** [comment]
This is also a great resource i found : https://zhanggroup.org/SSIPe/pdb_atom_format.html#ATOM 

Im was using a faulty script from external authors. I did a quick and dirty fix for writing the pdb lines using formated strings and .ljust for adjusting differently, depending on wether the atomname has 1 or 2 letters. Its pretty ugly, but it works for now.

Thank you all

**Comment by bp-kelley** [comment]
You can build it up using an RWMol by adding atoms, or you can add your own Residue information to an existing molecule.


```
import numpy as np
m = Chem.RWMol()
m.AddAtom(Chem.Atom(35))
conf = Chem.Conformer(1)
conf.SetPositions(np.array([[11.810, -18.885, -5.354]]))
m.AddConformer(conf)
res = AtomPDBResidueInfo()
res.SetName("BR14")
res.SetResidueNumber(1)
res = m.GetAtomWithIdx(0).SetPDBResidueInfo(res)
print(Chem.MolToPDBBlock(m))
```

```
ATOM      1 BR14         1      11.810 -18.885  -5.354  1.00  0.00          BR  
```
