### ISSUE TITLE
Pointer freeing error when using rdkit.Chem.Draw in 2024.03.6 and 2024.09.1 conda-forge packages for ARM Macs

### ISSUE THREAD

**Issue by j-wags** [rdkit/rdkit#7890]
**Describe the error**

The following code crashes on ARM macs with the most recent two osx-arm64 rdkit packages (`2024.09.1` and `2024.03.6`). 

The older `2024.03.5` osx-arm64 package runs this code successfully on ARM macs.

All recent x86-64 rdkit packages run this code successfully on ARM macs (using MacOS's rosetta emulator to run x86 code)

Happy to move this issue to the feedstock if it's diagnosed as a build issue, but figured I should start it here. 

**To Reproduce**

Many people use rosetta by default on ARM macs now to force the use x86 packages, so sometimes reproducing will require setting `CONDA_SUBDIR` to override this and pull in native osx-arm64 packages. 

```
CONDA_SUBDIR=osx-arm64 mamba create -n temp_arm rdkit=2024.03.6
mamba activate temp-arm
```

```python
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
rdkit_molecule = Chem.MolFromSmiles('CCO')
drawer = rdMolDraw2D.MolDraw2DSVG(200, 200, 150, 200)
drawer.DrawMolecule(rdkit_molecule)
drawer.FinishDrawing()
```

> python(60508,0x1e732f240) malloc: *** error for object 0x101df5668: pointer being freed was not allocated
> python(60508,0x1e732f240) malloc: *** set a breakpoint in malloc_error_break to debug
> zsh: abort      python repro.py

**Configuration (please complete the following information):**
 - RDKit version: 2024.09.1 and 2024.03.6
 - OS: Mac OSX 15.0, on a 2020 M1 macbook air
 - Python version (if relevant): 3.12.6
 - Are you using conda? Yes
 - If you are using conda, which channel did you install the rdkit from? conda-forge

**Comment by bp-kelley** [comment]
This doesn't appear to cause a malloc error on the master branch, but I'll do some more testing.

**Comment by DavidACosgrove** [comment]
@bp-kelley @j-wags I can confirm this on my Mac mini (M1).  It's not a problem in 2024.03.5 or the current master. I will look into it, because it may just be something we're getting away with.
Dave

**Comment by DavidACosgrove** [comment]
@bp-kelley @j-wags @greglandrum 
The bare reproducible is:
```
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
drawer = rdMolDraw2D.MolDraw2DSVG(200, 200)
```
A bit more illuminating, I think, is 
```
from rdkit import Chem
from rdkit.Chem.Draw import rdMolDraw2D
drawer = rdMolDraw2D.MolDraw2DSVG(200, 200)
drawer.FinishDrawing()
print(drawer.GetDrawingText())
```
The error occurs after the SVG text is printed:
![image](https://github.com/user-attachments/assets/430e7099-6362-4ad0-b7db-08d9f7075e76)

This suggests to me that it's something occurring as the Python is clearing up.  The script runs successfully insofar as it does what was requested of it.  The equivalent code making a MolDraw2DCairo object doesn't show the problem.

I have downloaded the tarballs for the 2024.03.6 and 2024.09.1 releases and built them from scratch and they don't show the problem.  The issue therefore seems to be confined to the Conda builds for 2024.03.6 and 2024.09.1 but not 2024.03.5.  IIRC, there was a problem with the Conda 2024.03.6 build which might be relevant.

That's as far as I can go, I'm afraid, but hopefully it's enough information to point someone else in the right direction.

**Comment by bp-kelley** [comment]
It definitely is a crash bug

```
>>> from rdkit import Chem
>>> from rdkit.Chem.Draw import rdMolDraw2D
>>> rdkit_molecule = Chem.MolFromSmiles('CCO')
>>> drawer = rdMolDraw2D.MolDraw2DSVG(200, 200, 150, 200)
>>> drawer.DrawMolecule(rdkit_molecule)
>>> drawer.FinishDrawing()
>>> del drawer
python(51927,0x1f35d3240) malloc: *** error for object 0x1038c5668: pointer being freed was not allocated
python(51927,0x1f35d3240) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      python
```

But I can't reproduce it either outside of that one condo build.

**Comment by bp-kelley** [comment]
Minimum reproducible

```
>>> from rdkit.Chem.Draw import rdMolDraw2D
>>> drawer = rdMolDraw2D.MolDraw2DSVG(200, 200, 150, 200)
>>> del drawer
```

**Comment by bp-kelley** [comment]
I looked through the commit history to MolDraw2DSVG and couldn't find anything obvious.  The double free is in a ~locale object which makes me think it is very obscure and not directly RDKit related.

**Comment by j-wags** [comment]
If David was unable to reproduce with builds from source, then I'm inclined to think this is a packaging issue. Looking at [feedstock changes](https://github.com/conda-forge/rdkit-feedstock/pulls?q=is%3Apr+is%3Aclosed) between 2024.03.5 and 2024.03.6 (where the problem first started) if looks like only 3 PRs were merged:

* https://github.com/conda-forge/rdkit-feedstock/pull/166
* https://github.com/conda-forge/rdkit-feedstock/pull/169
* https://github.com/conda-forge/rdkit-feedstock/pull/173

Unfortunately they're somewhat arcane to me and the last one in particular has a bunch of changes from the conda-forge bot rerendering.

**Comment by greglandrum** [comment]
FWIW: I just tried installing the most recent 2024.09.1 conda-forge builds on my ARM Mac Mini and @bp-kelley's simple reproducible works fine:
```
(rdkit_local) Marder:osx-arm64 glandrum$ mamba list | grep arm
libblas                   3.9.0           24_osxarm64_openblas    conda-forge
libcblas                  3.9.0           24_osxarm64_openblas    conda-forge
liblapack                 3.9.0           24_osxarm64_openblas    conda-forge
(rdkit_local) Marder:osx-arm64 glandrum$ mamba list | grep rdkit
# packages in environment at /Users/glandrum/miniconda3/envs/rdkit_local:
librdkit                  2024.09.1            hfdbd54f_2    conda-forge
rdkit                     2024.09.1       py312h164cb93_2    conda-forge
(rdkit_local) Marder:osx-arm64 glandrum$ cat ~/blah.py
from rdkit.Chem.Draw import rdMolDraw2D
drawer = rdMolDraw2D.MolDraw2DSVG(200, 200, 150, 200)
del drawer
print('yay')
(rdkit_local) Marder:osx-arm64 glandrum$ python ~/blah.py
yay
```
The original reproducible also seems fine.

Maybe it was a bad build?

**Comment by DavidACosgrove** [comment]
Yep, working for me, too.  Though since I also have an ARM Mac mini (original M1), perhaps that's not a hugely significant thing.  I am hoping Santa brings me an M2 Pro this year!

**Comment by j-wags** [comment]
Oh nice, I'm also seeing everything work fine with the newest build. Thanks for checking back on this!

As a sanity check, I'm still able to reproduce the error with the 2024.03.6 osx-arm64 package, but I don't think that's a big deal since the newest conda package is working.

Thanks, everyone!

**Comment by greglandrum** [comment]
> Though since I also have an ARM Mac mini (original M1), perhaps that's not a hugely significant thing.

Yeah, that's the same hardward I have.

>  I am hoping Santa brings me an M2 Pro this year!

The rumor is that M4 Mac Minis will be announced on 1 Nov, so don't send off your wish list just yet.

**Comment by mikemhenry** [comment]
Do we want to yank that package if we know it has an issue?

**Comment by bp-kelley** [comment]
@greglandrum where are the builds being done?  It would be interesting to get the clang and Xcode releases the builds.

**Comment by greglandrum** [comment]
> @greglandrum where are the builds being done?  It would be interesting to get the clang and Xcode releases the builds.

https://github.com/conda-forge/rdkit-feedstock
