### ISSUE TITLE
MQN Implementation may differ from original paper in indices

### ISSUE THREAD

**Issue by sroughley** [rdkit/rdkit#7894]
The code provided by the authors in the Supplementary Information of the original MQN paper (https://chemistry-europe.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fcmdc.200900317&file=cmdc_200900317_sm_miscellaneous_information.pdf) seems to suggest that MQN14 is the 'thac' (Total Heavy Atom Count):

```java
...
//ATOM PROPERTIES
+ thac + ";"//total heavy atom count (= everything else than H D T) 14
...
```

However, this appears to be returned as MQN12 in the RDKit implementation, as at:

https://github.com/rdkit/rdkit/blob/ea7f51f3b19828197055298149d0d59136c7947d/Code/GraphMol/Descriptors/MQN.cpp#L136

NB I have not checked other properties, however I wonder if this intentional, accidental, or relates to the definitions within the main text of the manuscript (which I don't have access to!)

**Comment by greglandrum** [comment]
According to the paper, MQN12 is the heavy atom count and MQN14 is the number of acyclic double bonds.
Here's the table from the paper:
![image](https://github.com/user-attachments/assets/06901801-34f8-432b-b999-57d0e7919b7f)
