### ISSUE TITLE
MolToInchiKey inconsistency between rdkit versions

### ISSUE THREAD

**Issue by radchenkods** [rdkit/rdkit#7906]
**Describe the bug**
After upgrading to the newest version of toolkit there are different INCHIKeys generated for some cases.

**To Reproduce**
The code is the same for both 2023.09.1 vs 2024.03.5, this is a minimal simplified version to reproduce the behaviour:
```
import rdkit
from rdkit import Chem
print(rdkit.rdBase.rdkitVersion)
print(Chem.MolToInchiKey(Chem.MolFromSmiles("C=[At]", sanitize=False)))

### Output for 2023.09.1 ###
# FPQJPOVNMNOCOT-UHFFFAOYSA-N

### Output for 2024.03.5 ###
# AZYOCFZZNKPCCR-UHFFFAOYSA-N
```

**Expected behavior**
I expect that the INCHIKey stays the same between versions. If there are changes which results in the loss of backward compatibility, it would be nice to have a way to get the values the older version produces.

**Configuration (please complete the following information):**
 - RDKit version: 2023.09.1 + numpy 1.26.4, and 2024.03.5 + numpy 2.1.2
 - OS: Windows 10
 - Python version (if relevant): 3.12
 - Are you using conda? - No
 - If you are not using conda: how did you install the RDKit? - `pip install numpy==1.26.4 rdkit==2023.09.1` or `pip install numpy==2.1.2 rdkit==2024.03.5`

**Additional context**
My guess is that the satitization still took place, even with sanitize=False option enabled.

**Comment by radchenkods** [comment]
After checking intermediate versions I can say that the actual change was introduced in 2024.3.2 -> 2024.3.3 release. Both were checked with numpy==1.26.4.

**Comment by thegodone** [comment]
What is the Inchi version between 2024.3.2 / 2024.3.3 ?

Le mer. 9 oct. 2024 à 11:18, Dmytro Radchenko ***@***.***> a
écrit :

**Comment by radchenkods** [comment]
I am not sure, but it should be in both cases 1.06. It was mentioned here - https://github.com/rdkit/rdkit/pull/4332, while I didn't find any for 1.07. Is there a way to check inchi ver. somewhere in rdkit package?

**Comment by greglandrum** [comment]
This is due to a bug fix in the way the InChI code was being invoked: https://github.com/rdkit/rdkit/pull/7419

You can see what's actually going on by looking at the InChIs themselves instead of the InChI keys.

Here's the output before the bug fix:
```
(py312_rdkit_2024_03_1) glandrum@stoat:~$ python blah.py
2024.03.1
InChI=1S/CH3At/c1-2/h2H,1H2
```
notice that the chemical formula here is wrong. This should be `CH2At`.

Here's the output after the bug fix:
```
(rdkit_blog) glandrum@stoat:~$ python blah.py
2024.09.1
[13:51:01] WARNING: Accepted unusual valence(s): At(2)
InChI=1S/CH2At/c1-2/h1H2
```
