### ISSUE TITLE
RDK_BUILD_CAIRO_SUPPORT option misssing from CMakeLists.txt in Version Version :  2024.03.6

### ISSUE THREAD

**Issue by pippo1990** [rdkit/rdkit#7921]
Is the CAIRO support being pulled off ? Any particolar reason the : 

`option(RDK_BUILD_CAIRO_SUPPORT "build support for .. whatever " OFF)`  `(or ON)`

not in `CMakeLists.txt ` for **Version 2024.03.6** ?

I've some script using that one, shuold I move to [`class rdkit.Chem.Draw.rdMolDraw2D.MolDraw2D`](https://www.rdkit.org/docs/source/rdkit.Chem.Draw.rdMolDraw2D.html#rdkit.Chem.Draw.rdMolDraw2D.MolDraw2D) seems to have more options/controls in Python API.

**Comment by ptosco** [comment]
I have just checked release 2024.03.6 and the option is there:
```
$ grep CAIRO ./Code/GraphMol/MolDraw2D/CMakeLists.txt
option(RDK_BUILD_CAIRO_SUPPORT "build support for Cairo drawing" OFF)
```
Therefore I am closing this. Feel free to reopen if needed.
