### ISSUE TITLE
CanonicalRankAtoms doesn't output smiles atom orders

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#794]
CanonicalRankAtoms could be more useful if it output the "smiles" order (with perhaps, -1, for atoms that are not output in the smiles string like Hydrogens).  The CanonicalRank is interesting, but it isn't very useful I think.

Currently, there is no simple way to write out coordinates for the canonicalized smiles string in the atom order of the string.

I would tend to think this is a bug, but it may be an enhancement.

**Comment by greglandrum** [comment]
The SMILES output order is available from the property `"_smilesAtomOutputOrder`:
```
In [5]: m = Chem.MolFromSmiles('C1C(OC)C1CC')

In [6]: Chem.MolToSmiles(m)
Out[6]: 'CCC1CC1OC'

In [7]: m.GetProp('_smilesAtomOutputOrder')
Out[7]: '[6,5,4,0,1,2,3,]'
```

`CanonicalRankAtoms()` is useful if you just want a canonical ordering as input to some other algorithm and don't want to first have to generate SMILES.

**Comment by bp-kelley** [comment]
I might go ahead and encapsulate this.

```
vector<int> CanonicalAtomOutputOrder(ROMol &)
```

to make it more explicit.

**Comment by greglandrum** [comment]
I'd rather add an extra argument to the SMiLES generation.

**Comment by thegodone** [comment]
Hi Greg, Is Smiles generation has this extra argument specially for doRandom = True ?

**Comment by greglandrum** [comment]
@thegodone : I'm afraid I don't understand the question

**Comment by thegodone** [comment]
I try your code and yes order change correctly with doRandom:
smile = Chem.MolToSmiles(mol,doRandom=True)
order = mol.GetProp('_smilesAtomOutputOrder')
atomorder = [int(i)  for i in order.replace(bracket[0],'').replace(bracket[1],'').split(',') if i != '''''']
orderarray = np.array(atomorder)
but the order string output need to be parse

**Comment by greglandrum** [comment]
Ah, you are asking if the extra argument has been added or not?
Nope, it isn't there yet.
