### ISSUE TITLE
Wrong SMARTS pattern in O-benzyl deprotection reaction

### ISSUE THREAD

**Issue by marcobICR** [rdkit/rdkit#7989]
Hi everyone, 

I have created this issue following the discussion in https://github.com/rdkit/rdkit/discussions/7982:
I have noticed that in the benzyl deprotection reaction the SMARTS pattern is wrong, matching phenylethers instead:

```python
import rdkit
from rdkit import Chem
from rdkit.Chem import Draw, rdDeprotect

mol = Chem.MolFromSmiles("Nc1ccccc1Oc1ccccc1")
```

This is the mol:
![image](https://github.com/user-attachments/assets/0899ab60-e623-4aa1-9674-5d40a0c2e5b9)

```python
Draw.MolsToGridImage(
    mols = [rdDeprotect.Deprotect(mol = mol, deprotections = [dep]) for dep in rdDeprotect.GetDeprotections()],
    legends = [dep.full_name for dep in rdDeprotect.GetDeprotections()],
    molsPerRow = 7
)
```
This is the output:
![image](https://github.com/user-attachments/assets/2601c659-18f2-49d7-b8fb-5cd0cda83ca3)

This compound should not be deprotected by the benzyl reaction at all, since this is a phenyl ether.
Looking at the [SMARTS in the code:](https://github.com/rdkit/rdkit/blob/b16b6026e8d58ddba73a7ba6b24f5c0412fd4951/Code/GraphMol/Deprotect/Deprotect.cpp#L53)

```
      {"alcohol", "[O;!$(*C(=O)):1]c1[c;H1][c;H1][c;H1][c;H1][c;H1]1>>[O;H1:1]",
       "Bn", "benzyl", "NOc1ccccc1>>ON"}
```

It looks like the SMARTS pattern is wrong and it's missing a CH2 group between the O and the phenyl group.
Can someone confirm that this is indeed uncorrect?

_Originally posted by @marcobICR in https://github.com/rdkit/rdkit/discussions/7982_

**Comment by bp-kelley** [comment]
I believe it should be:

{"alcohol", "[OH1;!$(*C(=O)):1]c1[c;H1][c;H1][c;H1][c;H1][c;H1]1>>[O;H1:1]",
       "Bn", "benzyl", "NOc1ccccc1>>ON"},

**Comment by bp-kelley** [comment]
On inspection, though, it appears to be missing a carbon as well

<img width="843" alt="image" src="https://github.com/user-attachments/assets/bb914eab-7d12-4c96-848a-4e2a94b7a5a2">

**Comment by marcobICR** [comment]
Yes, this is what I was pointing at. It's missing the benzylic carbon in the SMARTS definition of the reaction.
It should be:

[OH1;!$(*C(=O)):1][C;H2]c1[c;H1][c;H1][c;H1][c;H1][c;H1]1>>[O;H1:1]

**Comment by bp-kelley** [comment]
@marcobICR Looks like we agree!

**Comment by bp-kelley** [comment]
I'll add the MR.  If you are using this in practice, do you know how to load your own deprotection patterns until we get the fix in?

**Comment by marcobICR** [comment]
Thanks! I wouldn't know how to do the MR anyway 😅. I've just recently started learning how GitHub works.
No, some help would be appreciated to get the local fix done. Thanks for your help!

**Comment by bp-kelley** [comment]
Here is the current results from testing
```
>>> from rdkit import Chem
>>> from rdkit.Chem import rdDeprotect
>>> new_data = []
>>> for d in data:
...   if d.abbreviation == "Bn" and d.deprotection_class == "alcohol":
...      new_data.append(rdDeprotect.DeprotectData("alcohol", "[O;!$(*C(=O)):1][CH2]c1[c;H1][c;H1][c;H1][c;H1][c;H1]1>>[O;H1:1]", "Bn", "benzyl"))
...   else:
...      new_data.append(d)
... 
>>> m = Chem.MolFromSmiles("c1ccccc1Oc1ccccc1")
>>> rdDeprotect.DeprotectInPlace(m, new_data)
False
>>> m = Chem.MolFromSmiles("c1ccccc1CO")
>>> rdDeprotect.DeprotectInPlace(m, new_data)
True
>>> m = Chem.MolFromSmiles("c1ccccc1COc1ccccc1")
>>> rdDeprotect.DeprotectInPlace(m, new_data)
True
```

**Comment by marcobICR** [comment]
> Here is the current results from testing
> 
> ```
> >>> from rdkit import Chem
> >>> from rdkit.Chem import rdDeprotect
> >>> data = rdDeprotect.GetDeprotections()
> >>> for d in data:
> >>> new_data = []
> >>> for d in data:
> ...   if d.abbreviation == "Bn" and d.deprotection_class == "alcohol":
> ...      new_data.append(rdDeprotect.DeprotectData("alcohol", "[O;!$(*C(=O)):1][CH2]c1[c;H1][c;H1][c;H1][c;H1][c;H1]1>>[O;H1:1]", "Bn", "benzyl"))
> ...   else:
> ...      new_data.append(d)
> ... 
> >>> m = Chem.MolFromSmiles("c1ccccc1Oc1ccccc1")
> >>> rdDeprotect.DeprotectInPlace(m, new_data)
> False
> >>> m = Chem.MolFromSmiles("c1ccccc1CO")
> >>> rdDeprotect.DeprotectInPlace(m, new_data)
> True
> >>> m = Chem.MolFromSmiles("c1ccccc1COc1ccccc1")
> >>> rdDeprotect.DeprotectInPlace(m, new_data)
> True
> ```

Thanks! Just reading through this comment: if the intent of this function is to deprotect protected groups, does it make sense to make it match the simple benzyl alcohol (your second example)? Would it be better to make it match a benzyl-O-something instead?
A quick example could be this SMARTS pattern: "[O;H0;!$(*C(=O)):1][CH2]c1[c;H1][c;H1][c;H1][c;H1][c;H1]1>>[O;H1:1]". Using your example:


```python
from rdkit import Chem
from rdkit.Chem import rdDeprotect
data = rdDeprotect.GetDeprotections()
for d in data:
    new_data = []
for d in data:
    if d.abbreviation == "Bn" and d.deprotection_class == "alcohol":
        new_data.append(rdDeprotect.DeprotectData("alcohol", "[O;H0;!$(*C(=O)):1][CH2]c1[c;H1][c;H1][c;H1][c;H1][c;H1]1>>[O;H1:1]", "Bn", "benzyl"))
    else:   
        new_data.append(d)

m = Chem.MolFromSmiles("c1ccccc1Oc1ccccc1")
print(rdDeprotect.DeprotectInPlace(m, new_data))
m = Chem.MolFromSmiles("c1ccccc1CO")
print(rdDeprotect.DeprotectInPlace(m, new_data))
m = Chem.MolFromSmiles("c1ccccc1COc1ccccc1")
print(rdDeprotect.DeprotectInPlace(m, new_data))
-------------------- Output --------------------
False
False
True
```

**Comment by bp-kelley** [comment]
@marcobICR In general we don't bother, but we could certainly add an option to enforce r-groups at some point.
