### ISSUE TITLE
Weird Depiction of Some Molecules after Compute2DCoords

### ISSUE THREAD

**Issue by apahl** [rdkit/rdkit#800]
Hi all,
I have observed that in v 2015.09.2 the depiction of some molecules becomes really distorted after Compute2DCoord() is called on them. Can this be fixed?
Here is an excample (also as Notebook in this [Gist](https://gist.github.com/apahl/6a9fcac1c383624c3199)):  
This renders fine:
```python3
sm = "[#6]1:[#6]:[#6]2:[#6]3-[#6]-[#16]-[#6]-[#6]-[#6]:3:[#7](:[#6]:2:[#6]:[#6]:1)-[#6](-[#6])=[#8]"
mol = Chem.MolFromSmarts(sm)
mol
```
But after generating the 2D coordinates, it looks weird:
```python3
mol.Compute2DCoords()
mol
```
Many thanks in advance for your help!

Kind regards,
Axel

**Comment by greglandrum** [comment]
Hi Axel,
There are a number of problems with rendering molecules created from SMARTS, most have to do with the fact that properties haven't been perceived.
You should be able to get decent rendering like this:
```python
sm = "[#6]1:[#6]:[#6]2:[#6]3-[#6]-[#16]-[#6]-[#6]-[#6]:3:[#7](:[#6]:2:[#6]:[#6]:1)-[#6](-[#6])=[#8]"
mol = Chem.MolFromSmarts(sm)
mol.UpdatePropertyCache(False)
Chem.SanitizeMol(mol,sanitizeOps=Chem.SANITIZE_SYMMRINGS|Chem.SANITIZE_SETCONJUGATION|Chem.SANITIZE_SETHYBRIDIZATION)
mol.Compute2DCoords()
mol
```
You can write that out a bit longer if you like:
```python
sm = "[#6]1:[#6]:[#6]2:[#6]3-[#6]-[#16]-[#6]-[#6]-[#6]:3:[#7](:[#6]:2:[#6]:[#6]:1)-[#6](-[#6])=[#8]"
mol = Chem.MolFromSmarts(sm)
mol.UpdatePropertyCache(False)
Chem.GetSymmSSSR(mol)
Chem.SetConjugation(mol)
Chem.SetHybridization(mol)
mol.Compute2DCoords()
mol
```

**Comment by apahl** [comment]
Hi Greg, 
thanks for the lightning-fast answer. Once again you saved my day!
I had tried SanitizeMol, but without using UpdatePropertyCache before and not specifying any flags and so I always ended up with: `Sanitization error: Explicit valence for atom # 2 C, 5, is greater than permitted`.
Is this something for the Cookbook? To be honest, it has driven me crazy for the better part of yesterday.

Many thanks again!
Kind regards,
Axel

**Comment by greglandrum** [comment]
A cookbook entry on how to successfully display molecules created from SMARTS would indeed be useful.
Are you volunteering to write it? ;-)

**Comment by apahl** [comment]
Yeah, I will prepare something, since I brought it up and have not contributed anything useful for a while...
Now I have to get back to the lab to my POCl3-reaction workup!
Kind regards, 
Axel
