### ISSUE TITLE
RMS pruning in conformer generation misses conformers above the threshold

### ISSUE THREAD

**Issue by fwaibl** [rdkit/rdkit#8001]
**Describe the bug**
I have an example where KDG with RMSD pruning at 1 Angstrom gives only one conformer. However, if I generate the same conformers (same settings, random seed, number of conformers) with a threshold of 0.5, I obtain 5 conformers, where one of them has an RMSD of 1.19 to the first conformer. Since the first conformer is the same that I get with 1 Angstrom pruning, the conformer with an RMSD of 1.19 should get through the pruning filter.

**To Reproduce**
```
mol = Chem.AddHs(Chem.MolFromSmiles(r"OCCCCCCC"))
params = Chem.AllChem.KDG()
params.randomSeed = 1
params.pruneRmsThresh = 0.5
mol_05 = Chem.Mol(mol)
mol_1 = Chem.Mol(mol)
Chem.AllChem.EmbedMultipleConfs(mol_05, 200, params)
print(mol_05.GetNumConformers(), "conformers at threshold 0.5")
params.pruneRmsThresh = 1.0
Chem.AllChem.EmbedMultipleConfs(mol_1, 200, params)
print(mol_1.GetNumConformers(), "conformers at threshold 1.0")
no_h = Chem.RemoveHs(mol_05)
print([Chem.rdMolAlign.GetBestRMS(no_h, no_h, 0, i) for i in range(mol_05.GetNumConformers())])
```
prints:
```
5 conformers at threshold 0.5
1 conformers at threshold 1.0
[0.0, 0.9587092899848012, 0.9274511527028224, 0.9951951943942681, 1.190260383707726]
```

**Expected behavior**
There should be at least one more conformer in mol_1 (the one at an RMSD of 1.19 to the first conformer.

**Configuration (please complete the following information):**
 - RDKit version: 2024.09.2
 - OS: Ubuntu
 - Are you using conda? yes

**Additional context**
We already discussed this with @greglandrum. Thanks a lot for your support!

**Comment by greglandrum** [comment]
Thanks for reporting this one @fwaibl!
