### ISSUE TITLE
Question Mark Drawn In Molecule

### ISSUE THREAD

**Issue by lounsbrough** [rdkit/rdkit#8026]
**Describe the bug**
When rendering a MDL Molfile with an explicitly drawn hydrogen, if you set the `mergeQueryHs` flag to true when creating the molecule, rdkit outputs a `?` in the resulting svg image.

**To Reproduce**
Navigate to https://www.rdkitjs.com/#drawing-molecules-svg

Input the following code into the code editor under `Drawing molecules`:

```js
  var molfile = `
  Mrv2114 11212416242D          

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 7 7 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C -5.1742 -0.0084 0 0
M  V30 2 C -5.1764 -1.5529 0 0
M  V30 3 C -3.8419 -2.3235 0 0
M  V30 4 C -2.5046 -1.5519 0 0
M  V30 5 C -3.8452 0.7622 0 0
M  V30 6 H -1.1792 0.7734 0 0
M  V30 7 C -2.51 -0.0016 0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 5 1
M  V30 2 2 1 2
M  V30 3 2 3 4
M  V30 4 1 2 3
M  V30 5 1 6 7
M  V30 6 2 7 5
M  V30 7 1 4 7
M  V30 END BOND
M  V30 END CTAB
M  END
`;
  var mol = RDKitModule.get_mol(molfile, JSON.stringify({ mergeQueryHs: true }));
  var dest = document.getElementById("example-1-output");
  var svg = mol.get_svg();
  dest.innerHTML = "<div id='drawing'>" + svg + "</div>";
  
```

Observe question mark in the resulting image:

![image](https://github.com/user-attachments/assets/12f181a3-fc5f-444b-b0cc-a0e8fcc876df)

**Expected behavior**
I would not expect to see a question mark `?` rendered there. I would expect to see either an attached or detached hydrogen.

**Screenshots**
![image](https://github.com/user-attachments/assets/dca3db80-f8e0-428b-a824-c8c592634b09)

**Configuration (please complete the following information):**
 - RDKit version: [@rdkit/rdkit 2024.3.5-1.0.0](https://www.npmjs.com/package/@rdkit/rdkit/v/2024.3.5-1.0.0)
 - OS: [e.g. Ubuntu 20.04]: OSX/Chrome

**Comment by lounsbrough** [comment]
Thanks for the info. The reason we are merging the query Hs when rendering is because if we do not, we have many cases where highlighting and aligning do not work if some structures have the explicit hydrogens and others do not.

**Comment by bp-kelley** [comment]
Do you have a case where the hydrogens are not being suppressed?

**Comment by bp-kelley** [comment]
Ok, I confirmed that the hydrogens are not suppressed in get_mol, this seems wrong.

**Comment by bp-kelley** [comment]
removeHs is what you want, but it does appear not to work for mol files.

**Comment by bp-kelley** [comment]
I've tracked down the issue to this call

```
MolFromMolBlock(mb, sanitize=False, removeHs=True, strictParsing=False)
```

When sanitize is False, Hydrogens are not removed.

**Comment by bp-kelley** [comment]
@ptosco @greglandrum This is a real bug where removeHs isn't removing Hs with mol blocks in some circumstances.

**Comment by ptosco** [comment]
@bp-kelley Yes, I have just carried out your same investigation and got to the same conclusion. This is indeed a real bug; I'll commit a fix later.
@lounsbrough In the meantime, you may call `mol.remove_hs_in_place()` before generating your SVG.

**Comment by lounsbrough** [comment]
Thank you both for the quick response and analysis.
