### ISSUE TITLE
RDKit postgreSQL cartridge is_valid_smiles return false

### ISSUE THREAD

**Issue by sitanshubhunia** [rdkit/rdkit#8028]
**Describe the bug**
RDKit PostgreSQL cartridge is_valid_smiles return false for the below mentioned query
May be I am doing wrong something.

**To Reproduce**
select is_valid_smiles('[CsH2+].[CsH2+].[O-]C([O-])=O')
false
  **Expected behavior**
return true 

  - Rdkit_toolkit_version :2024.03.3
 - RDKit version: 0.76.0
 - Postgresql: 15
 
Any help greatly appreciated

**Comment by greglandrum** [comment]
I can't reproduce this with a recent build of the cartridge.
How did you install the cartridge?

**Comment by sitanshubhunia** [comment]
Respected @greglandrum ,

**Extremely sorry for late reply.** 

I am using through a docker image [informaticsmatters/rdkit-cartridge-debian]
docker pull informaticsmatters/rdkit-cartridge-debian:Release_2024_03_2

**Comment by greglandrum** [comment]
I still can't reproduce this using the rdkit postgresql cartridge builds from conda-forge:
```
rdkit_issue=# select rdkit_toolkit_version();
 rdkit_toolkit_version 
-----------------------
 2024.09.2
(1 row)

rdkit_issue=# select rdkit_version();
 rdkit_version 
---------------
 0.76.0
(1 row)

rdkit_issue=# select is_valid_smiles('[CsH2+].[CsH2+].[O-]C([O-])=O');
 is_valid_smiles 
-----------------
 t
(1 row)
```
I'm not sure what's going on, but this doesn't seem to be an RDKit bug; please check with the maintainer of the docker image you are using.
