### ISSUE TITLE
install.md should be updated 

### ISSUE THREAD

**Issue by zengkaipeng** [rdkit/rdkit#8038]
I followed the instructions on https://github.com/rdkit/rdkit/blob/master/Docs/Book/Install.md to build RDKit from source, but encountered some bugs in the end. I found that in the "Linux x86_64: Python 3 environment" section for building the source with Conda, the command `conda install -y gxx_linux-64` does not install a version of libstdc++.so with a high enough GLIBCXX version. Using `conda install -y gxx_linux-64` only installs GCC-11.2 with GLIBCXX_3.4.29, but the current code requires GLIBCXX_3.4.30. The installation command should be updated to `conda install -c conda-forge gxx_linux-64=12 -y`. I have tried installing gxx_linux-64 without specifying the version, and the system will install gcc-14.2, but this version of the compiler will report errors when compiling the existing code. Specifying version 12 is a solution that I have tried and found to be successful for versions newer than release_2024_09.

**Comment by greglandrum** [comment]
This is already in progress
