### ISSUE TITLE
Divide molecule (input: SMILE) into user defined groups

### ISSUE THREAD

**Issue by Plancalkuele** [rdkit/rdkit#804]
Hi there,
I wanted to ask if it is possible to divide any given molecule into segments/groups which a user can define in a list/file with rdkit.

I'm a chemical engineer and want to apply the Marrero/Gani Group Contribution Method (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.580.6493&rep=rep1&type=pdf).
This method dissects a molecule into first, second and third order groups (the lists of these groups can be found in Table 6, 7 and 8 of the linked paper above) and counts the occurrences of the found groups in the given molecule.

I've searched the manual and came across section 3.11 Molecular Fragments.
This comes quite close to what I would like to do: Store the 1st, 2nd and 3rd order groups in a txt or cvs file with SMARTS declaration and then use the datafile to count the occurring groups in the defined molecule.

In rdkit Fragments are defined to be made up of a set of connected atoms that may have associated functional groups. For the Group Contribution method I'm only interested in dividing the molecule into specific fragments. Thus, I should create my own FragmentDescriptors.csv file (https://github.com/rdkit/rdkit/blob/master/Data/FragmentDescriptors.csv) and then I could use the fcat.GetEntryDescription() to run through the found groups. But I don't see any way to count the occurence of the groups.

I would be very thankful for some feedback on this.

**Comment by Plancalkuele** [comment]
Found the first step to the final solution:
http://ctr.wikia.com/wiki/Unique_SMARTS_matches_against_a_SMILES_string

```
from rdkit import Chem
mol = Chem.MolFromSmiles('C1CC12C3(C24CC4)CC3')
patt = Chem.MolFromSmarts('*1**1')
 
print "number of matches:", len(mol.GetSubstructMatches(patt,uniquify=False))
print "number of unique matches:", len(mol.GetSubstructMatches(patt))
```

**Comment by Plancalkuele** [comment]
Would like to reopen this issue since this could also be interesting for other people.
So the above mentioned code snippet makes it possible to find unique matches of defined SMARTS (Groups) in SMILES (Molecule).
The problem I have now is that I want to dissect molecules in its biggest possible groups. This means that unique matched groups which are part of a bigger unique matched group should be excluded.
Does rdkit already provide a solution for this problem? Otherwise I will think of a way to solve this and post the solution here.

**Comment by danilomendesdias** [comment]
Did you achieve something since then, @Plancalkuele?

Thanks!

**Comment by Plancalkuele** [comment]
@danilomendesdias 
Yes, we have developed an algorithm to solve this issue. I will post it here when I have written a publication which includes the algorithm, cleaned the code up and finished my PhD in mid April.

**Comment by simonmb** [comment]
Hi, I recently published a paper on this: https://doi.org/10.1186/s13321-019-0382-3

**Comment by ARNAOU-KT** [comment]
@Plancalkuele
Fun fact, the method was developed at my uni (DTU) and I am actually working with this group segmentation.
w have an inhouse software that does it for us (ProPred).
Would be interesting to benchmark you algorithm against ours :) 
So any updates?

**Comment by chinmoybasak** [comment]
> @Plancalkuele
> Fun fact, the method was developed at my uni (DTU) and I am actually working with this group segmentation.
> w have an inhouse software that does it for us (ProPred).
> Would be interesting to benchmark you algorithm against ours :)
> So any updates?

I am seeing "invalid smile string error" in ProPred 4.4 for small drug molecule do I have to update the software? Thanks.

**Comment by muratyalcinmy** [comment]
@Plancalkuele
I've been interested this problem for a while, so any updates? You said "I will post it here when I have written a publication..."
Thanks.

**Comment by simonmb** [comment]
> 
> 
> Hi, I recently published a paper on this: https://doi.org/10.1186/s13321-019-0382-3

@muratyalcinmy: if @Plancalkuele  publishes the algorithm it would be interesting to compare with the one I published to see whether we can learn something from each other.

**Comment by Plancalkuele** [comment]
Dear @muratyalcinmy @simonmb @arnaou @danilomendesdias sorry for my absence. I have been very busy with other projects and it's only possible to work sporadically on the algorithm.
I tested the algorithm with a data set of around 1160 molecules and there are some issues with the algorithm originating from the SMARTS identifiers and the next point on my ToDo list for this algorithm is to apply natural language processing (NLP) to generate the SMARTS (with the current SMARTS as initial guesses) to dissect the molecules into the correct groups. The following plot shows that the algorithm is not perfect and still needs work. The black spots show where the occurence of a group does not conform with the correct dissection data set.
The x-axis is the 1st and 2nd group id of the Marrero-Gani method and the y-axis is the id of the specific chemical.
![Screenshot from 2021-03-17 12-02-55](https://user-images.githubusercontent.com/8739031/117363085-61090d80-aebc-11eb-801c-4c776d3f4382.png)
So if you are interested to have a more validated dissection algorithm, I would rather recommend to go with Simon's code and see if you can construct the SMARTS identifiers for the type of group contribution method you are interested in and see if it works in your cases. But Simon's algorithm is tailored to the UNIFAC method and just substituting SMARTS will not be enough I guess. I find it interesting to have an adaptive group dissection algorithm which dissects molecules with respect to the data set available to the most necessary groups declared as SMARTS but generated via NLP. If a new chemical is introduced to retrieve a prediction and a fragment of the molecule can not be found in the NLP generated SMARTS set, then the adaptive algorithm has to be run again with the SMILES string of the new molecule. 
Happy to discuss this further, since this is just an idea and I have so far only found two papers discussing NLP and applying it to SMILES so far:
https://arxiv.org/pdf/2002.06053.pdf
https://arxiv.org/pdf/1602.06289.pdf

**Comment by simonmb** [comment]
My algorithm is not tailored for UNIFAC. There are two algorithms in my paper. The simple one would require some tweaking to work with other SMARTS than for UNIFAC.  The complete one, as I call it in the paper,  should find all possible fragmentations allowed for any kind of set of SMARTS.

**Comment by simonmb** [comment]
The idea about using NLP sounds quite interesting. I don't know much about NLP and had never thought of using it although I thought of the idea of automagically generating a predictive model for some kind of molecular property including the needed SMARTS.

**Comment by l0d0v1c** [comment]
> > Hi, I recently published a paper on this: https://doi.org/10.1186/s13321-019-0382-3
> 
> @muratyalcinmy: if @Plancalkuele publishes the algorithm it would be interesting to compare with the one I published to see whether we can learn something from each other.

very interesting. Thank you

**Comment by tyyfkpo** [comment]
Hi, anyone still working on this? I'm very interested in this work too. However, I don't know how to transfer the substructures (groups) into SMART string, since the official document of RDKit introduced the _'mol.GetSubstructMatch(patt)'_ method which would be very useful.  Can anyone help me transfer the transfer the substructures (groups) into SMART string?  Thanks~

**Comment by simonmb** [comment]
@tyyfkpo You can learn how to define SMARTS [here](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html). I can also recommend [this webpage](https://smarts.plus/) to test your SMARTS. For simple things you will be able to use GetSubstructMatch. For more complex things you'll need a better algorithm like the one I mention above.

**Comment by sardaar11** [comment]
Hi @simonmb . I read your paper on this issue. I found a list of 119 groups and their SMILES in your paper. Is is possible to extend these groups? I need to find all 1st, 2nd, and 3rd order groups of marrero and gani groups to estimate some properties for my work.

**Comment by simonmb** [comment]
Yes definetly, the code was developed to be used with whatever SMARTS groups you need. I recommend the official SMARTS documentation and having a look at [smarts.plus](smarts.plus) when you are testing your SMARTS.

**Comment by simonmb** [comment]
> Yes definetly, the code was developed to be used with whatever SMARTS groups you need. I recommend the official [SMARTS documentation ](https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html)and having a look at [smarts.plus](https://smarts.plus) when you are testing your SMARTS.

I just saw I had posted the same urls in the previous comment... :)

**Comment by simonmb** [comment]
> Hi @simonmb . I read your paper on this issue. I found a list of 119 groups and their SMILES in your paper. Is is possible to extend these groups? I need to find all 1st, 2nd, and 3rd order groups of marrero and gani groups to estimate some properties for my work.

If you look at the [paper](https://www.sciencedirect.com/science/article/pii/S0378381201004319) , you will see, that the levels of groups are relatively well defined,sonyou can search for the groups sequentially.

**Comment by sardaar11** [comment]
I have a set of 10,000 canonical SMILES and I want to estimate some properties using group contribution methods for the. I think your code can do this for me. But I have a problem while using your code. Lower case c represents aromatic carbon in the SMILES that I have, but your code returns an error which says "Flowing simles is not valid: c". Same problem with double bounds which are represented with "=" in my set of SMILES but your code can not interpret them and gives error. How can I deal with this problem?

**Comment by simonmb** [comment]
The error you describe is correct, as a single aromatic atom is not a molecule you can fragment. You probably have the 10000 molecules from somewhere and there might be errors in the SMILES. Whenever rdkit is unable to create a molecule from a SMILES you provide, you will get this error.

**Comment by simonmb** [comment]
@sardaar11 please open an issue in the [fragmenter repository](https://github.com/simonmb/fragmentation_algorithm) and provide the details. i.e. example code to reproduce the error.

**Comment by d-b-w** [comment]
Great discussion, everyone!

Please move further discussions to the "discussion" tab.
