### ISSUE TITLE
Failed to run reactions after neutralization using Uncharger

### ISSUE THREAD

**Issue by phonglam3103** [rdkit/rdkit#8064]
**Describe the bug**
I want to use SMARTS reaction to re-assign formal charges to molecules at a typical pH. Take carboxylic acid charge as an example. The first step is to use the `Uncharger` to neutralize the possibly wrongly assigned charges, the product of which will undergo SMARTS reaction to re-assign the charge. 

Take an example SMILES: 

```
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.MolStandardize import rdMolStandardize
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.drawOptions.addAtomIndices = True
IPythonConsole.molSize = 300,300
IPythonConsole.ipython_useSVG=True

smiles = 'CC(O)CN1CCN(CC(=O)[O-])CCN(CC(=O)[O-])CCN(CC(=O)[O-])CC1'
mol = Chem.MolFromSmiles(smiles)
uncharger = rdMolStandardize.Uncharger()
uncharger.unchargeInPlace(mol)

uncharged_smiles = Chem.MolToSmiles(mol)
```

return: `CC(O)CN1CCN(CC(=O)O)CCN(CC(=O)O)CCN(CC(=O)O)CC1` --> Uncharger did well on neutralizing this molecule.

But upon taking the RDMol Object `mol` to undergo the reaction:

```
rxn = AllChem.ReactionFromSmarts('[OH1&+0;$(O-C=O)!$(O~C~[-1]):1]>>[O-:1]')
product = rxn.RunReactants((mol,))[0][0]
try:
    Chem.SanitizeMol(product)
except Exception as e:
    print(e)
print(Chem.MolToSmiles(product))
```

Return: 
Explicit valence for atom # 0 O, 2, is greater than permitted
CC(O)CN1CCN(CC(=O)O)CCN(CC(=O)O)CCN(CC(=O)[OH-])CC1
![image](https://github.com/user-attachments/assets/21e61e0a-128b-4c7a-bf0d-f7a173c6ad58)

The O is turned to [OH-] implicitly, making the valence of O > 2.

My current workaround is to reperceive the uncharged_mol from the uncharged_smiles, then apply the reaction on it. The reaction did well.

```
uncharged_mol = Chem.MolFromSmiles(uncharged_smiles)
product = rxn.RunReactants((uncharged_mol,))[0][0]
try:
    Chem.SanitizeMol(product)
except Exception as e:
    print(e)
print(Chem.MolToSmiles(product))
product
```
Return: CC(O)CN1CCN(CC(=O)[O-])CCN(CC(=O)O)CCN(CC(=O)O)CC1
![image](https://github.com/user-attachments/assets/62ca2174-16c3-4b7d-bfec-9ec09566680d)

 

**Expected behavior**
I have the feeling that after the Uncharger, there is still some atom properties that have not been cleaned, requiring the Re-perception using Chem.MolFromSmiles. I wonder if there is any direct solution, so that I don't need to output SMILES to an intermediate level and take it in again.

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: 2024.9.1 and 2024.9.3
 - Are you using conda? yes
 - If you are using conda, which channel did you install the rdkit from? Conda-forge

**Comment by ptosco** [comment]
This is not a bug. You need to change your SMARTS from
```
[OH1&+0;$(O-C=O)!$(O~C~[-1]):1]>>[O-:1]
```
to
```
[OH1&+0;$(O-C=O)!$(O~C~[-1]):1]>>[OH0-:1]
```
to specify that you want to set implicit hydrogens on the deprotonated oxygen to 0, as previously there was an implicit hydrogen on the neutral oxygen.
When unsure, please ask these questions in the Discussions tab rather than raising an issue. If it turns out to be a bug, the issue can be raised later.
