### ISSUE TITLE
SMARTS atom list parsing issue

### ISSUE THREAD

**Issue by hadoth** [rdkit/rdkit#8071]
**Describe the bug**
When SMARTS template contains a list of atoms, the results are weird.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import Draw
hydrogen_bromide = Chem.MolFromSmiles('Br')

hydrogen_pattern = Chem.MolFromSmarts('[H]')
chlorine_pattern = Chem.MolFromSmarts('[Cl]')
hydrogen_or_chlorine_pattern = Chem.MolFromSmarts('[H,Cl]')

print(f'hydrogen bromide matches hydrogen pattern; expected: False; actual: {hydrogen_bromide.HasSubstructMatch(hydrogen_pattern)}')
print(f'hydrogen bromide matches chlorine pattern; expected: False; actual: {hydrogen_bromide.HasSubstructMatch(chlorine_pattern)}')
print(f'hydrogen bromide matches hydrogen or chlorine pattern; expected: False; actual: {hydrogen_bromide.HasSubstructMatch(hydrogen_or_chlorine_pattern)}')
```

**Actual Behavior**
Template with list matches hydrogen bromide.
```
hydrogen bromide matches hydrogen pattern; expected: False; actual: False
hydrogen bromide matches chlorine pattern; expected: False; actual: False
hydrogen bromide matches hydrogen or chlorine pattern; expected: False; actual: True
```

**Expected behavior**
The template with list should not match hydrogen bromide as it neither contains explicit hydrogen, nor chlorine.
```
hydrogen bromide matches hydrogen pattern; expected: False; actual: False
hydrogen bromide matches chlorine pattern; expected: False; actual: False
hydrogen bromide matches hydrogen or chlorine pattern; expected: False; actual: False
```

**Configuration (please complete the following information):**
 - RDKit version: `2024.3.6`
 - OS: `macOS Sonoma 14.7.1`
 - Python version (if relevant): `3.11.10`
 - Are you using conda? Not
 - If you are not using conda: how did you install the RDKit? `uv pip install rdkit`

**Comment by wopozka** [comment]
Accodring to SMARTS specification, H does not mean hydrogen, but the hydrogen count. In this case [H,Cl], mean anything with one hydrogen, or chlorine atom. In this case HBr will match. If you want to have explicit hydrogem, you should use #1.

**Comment by greglandrum** [comment]
This is the same as #8072 and #8073
