### ISSUE TITLE
Hydrogen parsing in atom list SMARTS

### ISSUE THREAD

**Issue by hadoth** [rdkit/rdkit#8072]
**Describe the bug**
When hydrogen is part of atom list in smarts it is parsed incorrectly.

**To Reproduce**
```
from rdkit import Chem
from rdkit.Chem import Draw
methane_explicit = Chem.AddHs(Chem.MolFromSmiles('C'))

hydrogen_pattern = Chem.MolFromSmarts('[H]')
chlorine_pattern = Chem.MolFromSmarts('[Cl]')
hydrogen_or_chlorine_pattern = Chem.MolFromSmarts('[H,Cl]')
atomic_hydrogen_pattern = Chem.MolFromSmarts('[#1]')
atomic_hydrogen_or_chlorine_pattern = Chem.MolFromSmarts('[#1,Cl]')

print(f'methane matches hydrogen pattern; expected: True; actual: {methane_explicit.HasSubstructMatch(hydrogen_pattern)}')
print(f'methane matches chlorine pattern; expected: False; actual: {methane_explicit.HasSubstructMatch(chlorine_pattern)}')
print(f'methane matches hydrogen or chlorine pattern; expected: True; actual: {methane_explicit.HasSubstructMatch(hydrogen_or_chlorine_pattern)}')
print(f'methane matches atomic hydrogen pattern; expected: True; actual: {methane_explicit.HasSubstructMatch(atomic_hydrogen_pattern)}')
print(f'methane matches atomic hydrogen or chlorine pattern; expected: True; actual: {methane_explicit.HasSubstructMatch(atomic_hydrogen_or_chlorine_pattern)}')
```

**Actual Behavior**
Template with list does not match methane with explicit atoms.
```
methane matches hydrogen pattern; expected: True; actual: True
methane matches chlorine pattern; expected: False; actual: False
methane matches hydrogen or chlorine pattern; expected: True; actual: False
methane matches atomic hydrogen pattern; expected: True; actual: True
methane matches atomic hydrogen or chlorine pattern; expected: True; actual: True
```

**Expected behavior**
The template with list should not match hydrogen bromide as it neither contains explicit hydrogen, nor chlorine.
```
methane matches hydrogen pattern; expected: True; actual: True
methane matches chlorine pattern; expected: False; actual: False
methane matches hydrogen or chlorine pattern; expected: True; actual: True
methane matches atomic hydrogen pattern; expected: True; actual: True
methane matches atomic hydrogen or chlorine pattern; expected: True; actual: True
```

**Screenshots**

**Configuration (please complete the following information):**
 - RDKit version: `2024.3.6`
 - OS: `macOS Sonoma 14.7.1`
 - Python version (if relevant): `3.11.10`
 - Are you using conda? Not
 - If you are not using conda: how did you install the RDKit? `uv pip install rdkit`

**Comment by hadoth** [comment]
Might be connected to #8071 as both issues are connected with hydrogen in SMARTS atom list, but the results are different.

**Comment by bp-kelley** [comment]
It does appear to be a bug, here is the root cause:

```
>>> Chem.MolToSmarts(hydrogen_or_chlorine_pattern)
'[H1,Cl]'
>>> Chem.MolToSmiles(methane_explicit)
'[H]C([H])([H])[H]'
>>> p = Chem.MolFromSmarts("[H1]")
>>> methane_explicit.GetSubstructMatch(p)
()
>>> p = Chem.MolFromSmarts("[H]")
>>> methane_explicit.GetSubstructMatch(p)
(1,)
```

So the smarts pattern `[H1]` doesn't match `[H]`

**Comment by bp-kelley** [comment]
I'm not sure this is a bug,  in smarts `[H#]` stands for the number of hydrogens attached to the atom, while `#1` is the hydrogen atom.  I think in this case, explicit is better than implicit.

**Comment by mwojcikowski** [comment]
Worth to mention that SMILES/SMARTS `H`  == `[HH]` and `[H]` == `[#1H0]`. If you think about the right hand side/full definitions of atoms the results of the matches you get from RDKit should be consistent, i.e. `[H] should not mach to `[H1]`.

**Comment by greglandrum** [comment]
I don't believe that this is a bug (though it is confusing). The query `[H,Cl]` is interpreted as follows:
```
In [2]: print(Chem.AtomFromSmarts('[H,Cl]').DescribeQuery())
AtomOr
  AtomHCount 1 = val
  AtomType 17 = val
```
Methane does not have 1 H, so it does not match the query. 

There was a discussion of this in PR #1339  with the key quote from the daylight documentation being:
> Hence, a single change to SMARTS interpretation, for expressions of the form: [<weight>]H<charge><map>]. In SMARTS, these expressions now are interpreted as a hydrogen atom, rather than as any atom with one hydrogen attached. All other SMARTS hydrogen expressions retain their pre-4.51 meanings.

(from here: https://www.daylight.com/dayhtml/doc/theory/theory.smirks.html)

**Comment by hadoth** [comment]
This is extremely confusing. I understand the point, but this should definitely be explicitly addressed in Daylight docs. I would argue that in the current form this leaves too much room for interpretation. Anyway, thanks for explanation and sorry for spam.

**Comment by greglandrum** [comment]
> This is extremely confusing. I understand the point, but this should definitely be explicitly addressed in Daylight docs. I would argue that in the current form this leaves too much room for interpretation. Anyway, thanks for explanation and sorry for spam.

Agreed that it's confusing. I'm suggesting that we add a section to the RDKit SMARTS documentation explaining this:
https://github.com/rdkit/rdkit/pull/8081
