### ISSUE TITLE
MergeQueryHs fails when hydrogen is one of atoms on list

### ISSUE THREAD

**Issue by hadoth** [rdkit/rdkit#8073]
**Describe the bug**
When calling `MergeQueryHs` on a template which contains a list of atoms with hydrogen, e.g.`[C,H]`, the hydrogen is parsed as an atom with at least one hydrogen atom attached - `[C,H1]`.

**To Reproduce**
```
from rdkit import Chem
print(Chem.MolToSmarts(Chem.MergeQueryHs(Chem.MolFromSmarts('[C,H]'))))
>>>[C,H1]
```

**Expected behavior**
I'm not sure. I've been trying to produce a valid testcase, but hydrogen parsing and matching seems to be bugged and I was not able to produce anything that makes sense (#8071, #8072).

**Configuration (please complete the following information):**
 - RDKit version: `2024.3.6`
 - OS: `macOS Sonoma 14.7.1`
 - Python version (if relevant): `3.11.10`
 - Are you using conda? Not
 - If you are not using conda: how did you install the RDKit? `uv pip install rdkit`

**Comment by mwojcikowski** [comment]
I guess this is correct behavior. `[C,H]` should be read as `[C,*H1]`. My guess is that you wish to query with `[C,#1]` so carbon or hydrogen atom.

**Comment by hadoth** [comment]
`[H]` correctly matches explicit hydrogen and `[C]` does so for carbon. There's no reason why or operator (`,`) should change the way `[H]` is interpreted.
![image](https://github.com/user-attachments/assets/eeb53b8f-d181-476d-983b-dda427c916f8)

**Comment by bp-kelley** [comment]
This is correct, the paren "," means or in a smarts pattern, so this query matches Carbon OR Hydrogen.

Example:

```
>>> smi = "[C,O]"
>>> m = Chem.MolFromSmarts(smi)
>>> Chem.MolFromSmiles("O").HasSubstructMatch(m)
True
>>> Chem.MolFromSmiles("C").HasSubstructMatch(m)
True
```

MergeQueryHs is intended to take explicit hydrogens and remove them from the graph but keep their meaning.  I.e.

```
>>> params = Chem.SmilesParserParams()
>>> params.removeHs = False
>>> m = Chem.MolFromSmiles("C([H])([H])[H]", params)
>>> Chem.MolToSmiles(m)
'[H]C([H])[H]'
>>> Chem.MolToSmarts(m)
'[#6](-[H])(-[H])-[H]'
>>> merged = Chem.MergeQueryHs(m)
>>> Chem.MolToSmarts(merged)
'[#6&!H0&!H1&!H2]'
```

**Comment by mwojcikowski** [comment]
@hadoth note that SMARTS specs call `[H]` explicitly as an exception from the "H in SMARTS mean the number of implicit hydrogens" rule. In any other case it means the latter.

**Comment by greglandrum** [comment]
This is the same thing as #8072: `H` in a list is, correctly, interpreted as "an atom that has 1 attached hydrogen"
