### ISSUE TITLE
MolToPDBFile() produced incorrect Hs records.

### ISSUE THREAD

**Issue by AIDDHub** [rdkit/rdkit#8125]
I run the followed code to add Hs to the pdb file, However, the generated pdb file has incorrect Hs records.
```
pdb = Chem.MolFromPDBFile('test.pdb')
pdb = Chem.AddHs(pdb, addCoords=True)
Chem.MolToPDBFile(pdb, 'temp.pdb')
```
Part of incorrect Hs records.
``
ATOM    154  ND1 HIS D 120      -0.009  14.175  22.568  1.00 22.68           N  
ATOM    155  CD2 HIS D 120      -0.780  12.207  22.008  1.00 22.88           C  
ATOM    156  CE1 HIS D 120       1.013  13.346  22.586  1.00 23.12           C  
ATOM    157  NE2 HIS D 120       0.565  12.126  22.241  1.00 23.17           N  
ATOM    158  N   SER D 121      -5.429  14.628  20.710  1.00 26.79           N  
ATOM    159  CA  SER D 121      -6.775  15.265  20.687  1.00 28.83           C  
ATOM    160  C   SER D 121      -7.867  14.191  20.515  1.00 31.04           C  
ATOM    161  O   SER D 121      -9.015  14.460  20.854  1.00 32.00           O  
ATOM    162  CB  SER D 121      -6.865  16.321  19.612  1.00 28.63           C  
ATOM    163  OG  SER D 121      -7.192  15.745  18.346  1.00 28.62           O  
HETATM  164  H1  UNL     1      20.002  21.444   9.018  1.00  0.00           H  
HETATM  165  H2  UNL     1      18.634  21.408   8.041  1.00  0.00           H  
HETATM  166  H3  UNL     1      18.342  21.895  10.556  1.00  0.00           H  
HETATM  167  H4  UNL     1      20.153  23.546  10.586  1.00  0.00           H  
HETATM  168  H5  UNL     1      19.182  24.551   9.385  1.00  0.00           H  
HETATM  169  H6  UNL     1      17.468  24.920  11.004  1.00  0.00           H  
HETATM  170  H7  UNL     1      18.353  24.202  13.480  1.00  0.00           H  
HETATM  171  H8  UNL     1      17.187  23.256  12.494  1.00  0.00           H  
HETATM  172  H9  UNL     1      18.929  22.816  12.494  1.00  0.00           H  
```

**Comment by whosayn** [comment]
@AIDDHub I think the `AddHs` call should be 

```
pdb = Chem.AddHs(pdb, addCoords=True, addResidueInfo=True)
```

**Comment by AIDDHub** [comment]
a little better, but still not correct. The new produced Hs records:
```
ATOM    153  CG  HIS D 120      -1.153  13.484  22.247  1.00 23.20           C  
ATOM    154  ND1 HIS D 120      -0.009  14.175  22.568  1.00 22.68           N  
ATOM    155  CD2 HIS D 120      -0.780  12.207  22.008  1.00 22.88           C  
ATOM    156  CE1 HIS D 120       1.013  13.346  22.586  1.00 23.12           C  
ATOM    157  NE2 HIS D 120       0.565  12.126  22.241  1.00 23.17           N  
ATOM    158  N   SER D 121      -5.429  14.628  20.710  1.00 26.79           N  
ATOM    159  CA  SER D 121      -6.775  15.265  20.687  1.00 28.83           C  
ATOM    160  C   SER D 121      -7.867  14.191  20.515  1.00 31.04           C  
ATOM    161  O   SER D 121      -9.015  14.460  20.854  1.00 32.00           O  
ATOM    162  CB  SER D 121      -6.865  16.321  19.612  1.00 28.63           C  
ATOM    163  OG  SER D 121      -7.192  15.745  18.346  1.00 28.62           O  
ATOM    164  H1  LEU D 102      20.002  21.444   9.018  1.00  0.00           H  
ATOM    165  H2  LEU D 102      18.634  21.408   8.041  1.00  0.00           H  
ATOM    166  H3  LEU D 102      18.342  21.895  10.556  1.00  0.00           H  
ATOM    167  H4  LEU D 102      20.153  23.546  10.586  1.00  0.00           H  
ATOM    168  H5  LEU D 102      19.182  24.551   9.385  1.00  0.00           H  
ATOM    169  H6  LEU D 102      17.468  24.920  11.004  1.00  0.00           H  
ATOM    170  H7  LEU D 102      18.353  24.202  13.480  1.00  0.00           H  
ATOM    171  H8  LEU D 102      17.187  23.256  12.494  1.00  0.00           H  
ATOM    172  H9  LEU D 102      18.929  22.816  12.494  1.00  0.00           H  
ATOM    173  H10 LEU D 102      19.271  25.860  12.892  1.00  0.00           H  
ATOM    174  H11 LEU D 102      20.261  25.741  11.399  1.00  0.00           H  
ATOM    175  H12 LEU D 102      18.750  26.712  11.399  1.00  0.00           H  
ATOM    176  H1  LYS D 103      17.800  23.469   7.375  1.00  0.00           H  
ATOM    177  H2  LYS D 103      15.209  24.578   7.986  1.00  0.00           H  
ATOM    178  H3  LYS D 103      16.740  25.114   6.005  1.00  0.00           H  
ATOM    179  H4  LYS D 103      16.019  23.620   5.238  1.00  0.00           H  
ATOM    180  H5  LYS D 103      13.751  24.767   5.818  1.00  0.00           H  
ATOM    181  H6  LYS D 103      14.794  26.274   5.843  1.00  0.00           H  
ATOM    182  H7  LYS D 103      15.229  26.194   3.649  1.00  0.00           H  
ATOM    183  H8  LYS D 103      14.900  24.404   3.551  1.00  0.00           H  
ATOM    184  H9  LYS D 103      12.594  24.698   3.515  1.00  0.00           H  
ATOM    185  H10 LYS D 103      12.706  26.388   4.141  1.00  0.00           H  
ATOM    186  H11 LYS D 103      13.211  27.185   2.116  1.00  0.00           H  
ATOM    187  H12 LYS D 103      14.015  25.799   1.605  1.00  0.00           H  
ATOM    188  H13 LYS D 103      12.333  25.845   1.605  1.00  0.00           H  
ATOM    189  H1  THR D 104      16.156  21.454   6.453  1.00  0.00           H  
ATOM    190  H2  THR D 104      13.458  20.448   6.001  1.00  0.00           H  
ATOM    191  H3  THR D 104      16.195  19.206   6.146  1.00  0.00           H  
ATOM    192  H4  THR D 104      14.521  20.334   4.330  1.00  0.00           H  
ATOM    193  H5  THR D 104      14.619  17.606   7.195  1.00  0.00           H  
ATOM    194  H6  THR D 104      13.675  17.615   5.667  1.00  0.00           H  
ATOM    195  H7  THR D 104      15.379  17.046   5.667  1.00  0.00           H  
ATOM    196  H1  VAL D 105      15.729  20.164   8.751  1.00  0.00           H  
ATOM    197  H2  VAL D 105      14.158  18.281  10.320  1.00  0.00           H  

```

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information, including what you expect the results to be, and we will reopen the issue and try to help
