### ISSUE TITLE
Rust port

### ISSUE THREAD

**Issue by ivnsch** [rdkit/rdkit#8141]
Hello, would porting some (for starters small) part of the project to Rust be perhaps of interest (e.g. for better/easier multi threading)? I'm looking for a side project and just asking around.

**Comment by greglandrum** [comment]
From my perspective, there would be little value in reimplementing pieces of the RDKit itself in Rust.
It feels to me like it would be a lot more useful to have good, and well supported, wrappers for using the C++ code from Rust. This would allow Rust developers to expand the available functionality in their language of choice

**Comment by ivnsch** [comment]
There is such a wrapper: https://github.com/rdkit-rs/rdkit. A full port tends to be better (provided of course it's well maintained), but it's a bit daunting task considering the scope of rdkit. There are also some more focused libraries which are semi abandoned - will give those a closer look.

Alright, I'm closing this, thanks for the quick reply!
