### ISSUE TITLE
test60RunSingleReactant() not being run

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#825]
@bp-kelley : this is something I didn't catch during the review of your chemical reaction changes

This function:
https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/ChemReactions/testReaction.cpp#L5700

isn't being called during the tests and turning it on results in errors.

Want me to take a look or are you going to have time?

**Comment by bp-kelley** [comment]
Crap, I'll look at it.

----
Brian Kelley
