### ISSUE TITLE
Boost.Python.ArgumentError after updating to RDKit 2015

### ISSUE THREAD

**Issue by leelasd** [rdkit/rdkit#866]
Hi,

After I updated my RDKit version from 2014 to 2015. I am getting the below error. Any suggestions regarding this is appreciated.  I am using Mac OSx El Capitan with Anaconda (numpy 1.11.0). It works fine on Fedora with Anaconda (numpy 1.10.4)

```
Traceback (most recent call last):
  File "Descs.py", line 4, in <module>
    print Descriptors.TPSA(m)
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/rdkit/Chem/MolSurf.py", line 421, in <lambda>
    TPSA=lambda *x,**y:rdMolDescriptors.CalcTPSA(*x,**y)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdMolDescriptors.CalcTPSA(Mol)
did not match C++ signature:
    CalcTPSA(RDKit::ROMol mol, bool force=False)

```
 
This is the program I am trying to run.

```
from rdkit import Chem
from rdkit.Chem import Descriptors
m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
print Descriptors.TPSA(m)
print Descriptors.MolLogP(m)

```

**Comment by bp-kelley** [comment]
How did you obtain RDKit?  I'm using the current release 2016.03.1 on El Capitan (new for me) and I can't duplicate this:

    >>> from rdkit import Chem
    >>> from rdkit.Chem import Descriptors
    >>> m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
    >>> Descriptors.TPSA(m)
    37.3
    >>> Descriptors.MolLogP(m)
    1.3848

**Comment by leelasd** [comment]
I used `conda install rdkit` for installation.

**Comment by bp-kelley** [comment]
I'll try that this evening.  Thanks.

**Comment by greglandrum** [comment]
Things work fine for me with the new release (2016.03.1) and conda.
@leelasd : can you update to the new version of the RDKit (released yesterday)?

**Comment by greglandrum** [comment]
I also can't reproduce this with the older version:
```
(py27_rdkit)~ % conda install -c https://conda.anaconda.org/rdkit rdkit=2015.09.2
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/glandrum/anaconda/envs/py27_rdkit:

The following NEW packages will be INSTALLED:

    rdkit: 2015.09.2-np110py27_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#######################################################################################################################| 100%
(py27_rdkit)~ % python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles('c1ccccc1C(=O)O')
>>> from rdkit.Chem import rdMolDescriptors
>>> from rdkit.Chem import Descriptors
>>> Descriptors.TPSA(m)
37.3
```

**Comment by leelasd** [comment]
Thanks a lot @greglandrum @bp-kelley. With 2016 version I got no error.

**Comment by ahseena96** [comment]
I'm getting a similar error while trying to compute Morgan Fingerprints -

`Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdMolDescriptors.GetMorganFingerprintAsBitVect(NoneType, int)
did not match C++ signature:
    GetMorganFingerprintAsBitVect(RDKit::ROMol mol, int radius, unsigned int nBits=2048, boost::python::api::object invariants=[], boost::python::api::object fromAtoms=[], bool useChirality=False, bool useBondTypes=True, bool useFeatures=False, boost::python::api::object bitInfo=None)`

RDKit is of latest version. One cause I can think of is invalid SMILES string, which results in invalid molecule object (from SMILES using MolFromSmiles method of RDKit), but I tried excluding such molecules by having an exception (even though these are drawn from a popular dataset).

I am using Ubuntu 16.04.3, and rdkit was installed using conda. Any idea where the problem is?

**Comment by bp-kelley** [comment]
The key here is this line:

```
rdkit.Chem.rdMolDescriptors.GetMorganFingerprintAsBitVect(NoneType, int)
```

You are passing a None where a molecule is expected.  Note that unparsable molecules normally return None on error, so you should check for this and not process them further.

**Comment by ahseena96** [comment]
Thank you, @bp-kelley. I have another question, which in fact was the actual problem - the following error -
```
Can't kekulize mol.  Unkekulized atoms: 11 12 20 21 22 23 25
```
while computing Morgan Fingerprints. This was the reason behind having an exception for invalid strings, but it still shows up. Could you help me with this?
