### ISSUE TITLE
Issues with Chemical Reactions

### ISSUE THREAD

**Issue by kovasap** [rdkit/rdkit#887]
Many chemical reactions I've tried recently have returned no products, and have also not thrown any errors in their execution.  Here is an example:
```
rs = '[H:9][O:1][C:2]([H:10])([*:11])[C:3]([H:4])([H:12])[O:5][C:6]([*:7])=[O:8]>>[H:9][O:5][C:3]([H:12])([H:4])[C:2]([H:10])([*:11])[O:1][C:6]([*:7])=[O:8]'
reactants = [Chem.MolToInchi(Chem.MolFromSmiles('[H:9][O:1][C:2]([H:10])([F:11])[C:3]([H:4])([H:12])[O:5][C:6]([F:7])=[O:8]'))]
rxn = AChem.ReactionFromSmarts(rs)
rm = tuple([ Chem.MolFromInchi(i) for i in reactants ])
products = rxn.RunReactants(rm)
print products
```
Giving me an empty tuple.  Any ideas what the problem could be?  I have tried this reaction with other software (ChemAxon's Reactor) with success.

**Comment by greglandrum** [comment]
The reaction definition includes hydrogens in it explicitly. Molecules do not, by default, have hydrogens attached (and Hs in the input SMILES are, by default, removed), but you can add them:
```
In [19]: rxn = AllChem.ReactionFromSmarts('[H:9][O:1][C:2]([H:10])([*:11])[C:3]([H:4])([H:12])[O:5][C:6]([*:7])=[O:8]>>[H:9][O:5][C:3]([H:12])([H:4])[C:2]([H:10])([*:11])[O:1][C:6]([*:7])=[O:8]')

In [20]: reactants = [Chem.MolFromSmiles('[H:9][O:1][C:2]([H:10])([F:11])[C:3]([H:4])([H:12])[O:5][C:6]([F:7])=[O:8]')]

In [21]: rm = tuple(Chem.AddHs(m) for m in reactants)

In [22]: ps = rxn.RunReactants(rm)

In [23]: len(ps)
Out[23]: 2

In [24]: Chem.MolToSmiles(ps[0][0])
Out[24]: '[H]OC([H])([H])C([H])(F)OC(=O)F'

In [25]: Chem.MolToSmiles(ps[1][0])
Out[25]: '[H]OC([H])([H])C([H])(F)OC(=O)F'
```
A couple comments/questions:
- The atom mapping information provided for the input molecules doesn't do anything.
- Is there any particular reason that you are using InChI here? You potentially destroy a lot of information when you do that and the InChI->molecule translation can be error-prone.

**Comment by kovasap** [comment]
Thanks for the response.  Good to know about the hydrogens!

The atom mapping I used here does switch the positions of a hydrogen and one of the fluorines (the other one is untouched), if I'm not mistaken.  A lot of the reactions I'm trying to test are stored in a database as InChI strings, which is why I'm using it here.  I can try this with just SMILES, but I'll have to convert from InChI either way for my actual application.  I was under the impression that InChI stored all the information that SMILES does?

**Comment by bp-kelley** [comment]
@kovasap, not exactly.  You should probably read the section on FixedH and mobile hydrogen layers in the Inchi docs.  http://www.inchi-trust.org/technical-faq/#6.2  If FixedH isn't turned on, hydrogens may be moved into different tautomeric states.

**Comment by greglandrum** [comment]
Even if FixedH is turned on, the InChI algorithm makes changes to the input molecules. InChI is designed to be an identifier (i.e. "have I seen this molecule before?"), not an interchange format (i.e. "what is this molecule?"). It's separate from this bug, but if you're storing a database of molecules, you really should have an additional representation (like SMILES or CTAB) of the structure.

**Comment by greglandrum** [comment]
Re: atom mapping
I meant the mapping on the SMILES that you provide for the reactants:
`In [20]: reactants = [Chem.MolFromSmiles('[H:9][O:1][C:2]([H:10])([F:11])[C:3]([H:4])([H:12])[O:5][C:6]([F:7])=[O:8]')]`
Here the atom mapping has no effect on the reaction.

**Comment by kovasap** [comment]
Ok, I understand.  Thanks for the tips!
