### ISSUE TITLE
GetSubstructMatches uniquify and maxMatches don't work well together

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#888]
I have a filter to remove structures with too many (>10) rotatable bonds. I use GetSubstructMatches() with uniquify so I don't sometimes double-count a bond. I use a limit of 11 since I only care if there's at most 11 matches before I can decide to reject.

However, as implemented, 'maxNumMatches' is the limit in the non-unique matches, which are then filtered by the uniquification code. This may return fewer than maxNumMatches even if there are additional unique matches,

The following reproducible finds only 3 matches, even though there are at least 5 unique matches:

```
>>> from rdkit import Chem
>>> mol = Chem.MolFromSmiles("CCCCCCCC")
>>> pat = Chem.MolFromSmarts("*~*")
>>> mol.GetSubstructMatches(pat, uniquify=True, maxMatches=5)
((0, 1), (1, 2), (2, 3))
```

I believe this is a bug, because the results will be implementation dependent. Some implementations may return only 3 matches, as in this case, others might return 4 or 5.

As a workaround, I use maxMatches = 2*10+1 = 21, which only works because I know I'm doing a bond match.

**Comment by greglandrum** [comment]
I agree that it's a bug.
I'll need to do some poking around to figure out how much work fixing it will be.

**Comment by jasondbiggs** [comment]
I ran up against this recently as well.  This isn't really easily fixable, is it?

One workaround that comes to mind is first determine the number of automorphisms there are for the query mol (with `uniquify=False`) and then multiply your desired max matches by that.  But I don't think that is necessarily guaranteed to work, and also getting the number of automorphisms isn't free.

**Comment by d-b-w** [comment]
This has also hit some internal use cases at Schrödinger. It can be very confusing, because it makes it not obvious that you've hit the maxMatches parameter!
