### ISSUE TITLE
bugreport: invalid handling of negation of aromaticity when parsing SMARTS

### ISSUE THREAD

**Issue by michalsta** [rdkit/rdkit#893]
```
>>> from rdkit import Chem
>>> Chem.MolToSmarts(Chem.MolFromSmarts("[#6&!a]"))
'c'

```

expected output would be "C", as the semantics of [#6&!a], according to Daylight spec is "carbon and non-aromatic". Of course a chemist probably wouldn't write "[#6&!a]" instead of "C", however such SMARTS are sometimes generated by various automatic chemoinformatics scripts, which then get confused. Same thing happens with explicit aliphatic specifications:
```

>>> Chem.MolToSmarts(Chem.MolFromSmarts("[#6&!A]"))
'C'

```
Verified on the current git repo.

**Comment by greglandrum** [comment]
Confirmed.
Thanks for reporting it.

**Comment by bp-kelley** [comment]
This fix is relatively straight forward, but I might not understand the ramifications.  However, it looks like you really keep the original smarts forms in these cases of negation, if this is the case ( and I think it is ) then I think the is low risk.
