### ISSUE TITLE
Rdkit 2016_03_1 generate SVG typo in Python bindings

### ISSUE THREAD

**Issue by maddogcz** [rdkit/rdkit#903]
RDKit fails to generate SVG from MOL containing letter-labelled atom due to typo in Python bindings in file rdkit/sping/SVG/pidSVG.py line 159:

```python
if isinstance(font.face,siz.string_types):
```

... should be six, not siz

Something like this will caue an error:

```python
from rdkit import Chem
from rdkit.Chem import Draw
Draw.MolToFile(Chem.MolFromSmiles("CCCCl"),"/tmp/mol.svg")
```

**Comment by greglandrum** [comment]
Thanks for catching this!
