### ISSUE TITLE
Is there a way to create all the deb packages from a source checkout of rdkit?

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/rdkit#911]
I'd prefer to avoid having to do 'make install' in a source tree if that's possible.

**Comment by UnixJunkie** [comment]
make package fails on me because it tries to do RPMs also. Is there a way to ask building only the .deb packages?

**Comment by greglandrum** [comment]
To be honest, I don't really know how to create .debs.  That's something that @mbanck has done as part of the DebiChem work.

Michael, can you help here?

**Comment by mbanck** [comment]
```make package``` is a CMake/CPack thing and independent of distribution-specific packaging efforts. From a quick glance at https://cmake.org/Wiki/CMake:CPackPackageGenerators it looks like ```cpack -G DEB``` might be what you are looking for, i..e ```make package``, but only for Debian packages. I haven't tried it though.

**Comment by greglandrum** [comment]
hmm, I haven't looked at the cpack configuration in a very long time.
I just played around with this a bit and it's going to take some work to get it working again. I'll take a look to see if I can get something sensible done.

**Comment by UnixJunkie** [comment]
nice!

    mkdir -p build
    cd build
    cmake ../
    cpack -G DEB

indeed produces four deb files

**Comment by UnixJunkie** [comment]
I will test these to see if they can replace the ones provided by my distro.
If this is the case, I will create a PPA to host them.
And, you will have to ping me everytime there is a new official release of rdkit.

    RDKit-2011.6.1-Linux-Development.deb
    RDKit-2011.6.1-Linux-Extras.deb
    RDKit-2011.6.1-Linux-Python.deb
    RDKit-2011.6.1-Linux-Runtime.deb

**Comment by UnixJunkie** [comment]
can I be assigned to this issue? Thx.

**Comment by greglandrum** [comment]
done.

**Comment by UnixJunkie** [comment]
the produced packages are not as good as the distro ones:

        import rdkit
    ImportError: No module named rdkit

**Comment by UnixJunkie** [comment]
@psavery

**Comment by greglandrum** [comment]
Can you find out where the files were installed and check that against your PYTHONPATH?

**Comment by UnixJunkie** [comment]
My PYTHONPATH is empty, and that works with the Ubuntu-provided packages.
It should be the same behaviour with freshly created debs from rdkit's source tree.

**Comment by greglandrum** [comment]
Where did dpkg (I guess that's how you did the install) put the files?

**Comment by psavery** [comment]
I noticed a lot of improvement when I added this cmake definition: -DRDK_INSTALL_INTREE=OFF

When I generate the .deb files now, I can see that they are actually set to install some files (unlike before when they didn't install anything). When I run dpkg -c RDKit-2011.6.1-Linux-Python.deb, for instance, I get a lot of files that look like this (note that I'm going to recompile this for Python3 soon):

/usr/local/lib/python2.7/dist-packages/rdkit/Chem/AllChem.py

But it wasn't without its problems. It appears to be missing some .so files (although it does have a lot of them). When I try to import rdkit in python, for instance:

python2
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: libRDKitRDBoost.so.1: cannot open shared object file: No such file or directory

So perhaps with a little tinkering, we can get all of the needed files to install and have it working?

I am personally interested in the C++ interface. It appears that only the Python deb file that is generated installs the .so files, and none of them install header files. These are the four .deb files that are generated when "CPack -G DEB" is ran (Development is empty, but the others do install files):

RDKit-2011.6.1-Linux-Development.deb  
RDKit-2011.6.1-Linux-Extras.deb  
RDKit-2011.6.1-Linux-Python.deb  
RDKit-2011.6.1-Linux-Runtime.deb

**Comment by UnixJunkie** [comment]
Shouldn't we pass a prefix option to cmake too ?

    cmake -DCMAKE_INSTALL_PREFIX=/usr ../

**Comment by greglandrum** [comment]
It's been a really long time since I paid any attention to the cpack definitions, so it's easy to imagine that they are wrong.
I will try to find some time to take a look and see if I can clean those up over the next few days. Someone else could do also do this, of course. ;-)

**Comment by psavery** [comment]
@UnixJunkie Indeed we should prefix it. See the PR that I put up.
