### ISSUE TITLE
RDK_OPTIMIZE_NATIVE doesn't know architecture

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#916]
We should probably check to see if the compilers support -mpopcnt, big endian certainly doesn't.

Perhaps add a TRY_COMPILE with a simple hello world?

**Comment by rvianello** [comment]
what about using -march=native instead? (there's a discussion around this at https://github.com/openbabel/openbabel/issues/184).

**Comment by bp-kelley** [comment]
That's a good idea, but it probably needs to be opt-in for standard builds like anaconda or Debian as we don't know where it will be deployed.

----
Brian Kelley

**Comment by rvianello** [comment]
Yes, I agree this option should be OFF by default

**Comment by greglandrum** [comment]
I'm a bit confused. Do you mean OFF for the Conda builds or in the standard CMakeLists.txt?
Either way, there is such a performance gain from including the -mpopcnt instruction that I would be reluctant to disable it by default unless there's a good reason.

**Comment by rvianello** [comment]
you are right. only a minority of people build the packages for redistribution, and the default settings in the CMakeLists.txt file should reflect what most users would want to use (ON). we can specify the more portable settings in the conda/rpm/deb builds.

**Comment by greglandrum** [comment]
That makes more sense to me. I'd still be somewhat concerned that things like the conda version, which lots of people use, doesn't have great performance for everyone because of a feature missing from the CPUs of a very small (I think) fraction of machines. (This is assuming that we continue to use -mpopcnt and not -march=native, of course).

**Comment by greglandrum** [comment]
My concern with this, perhaps driven by my ignorance of exactly what `-march=native` does, is that this will lower the portability/compatibility of the binaries that are built. I believe that if I build code with `-mpopcnt` the binaries I get will work on any CPU from the same broad family (i.e. any x86_64 CPU) that has the popcount instruction. I also believe that binaries built with `-march=native` are likely to be considerably less portable and may not work even across different generations of the "same" CPU, never mind across more distantly related CPUs

**Comment by rvianello** [comment]
I basically agree, `-march=native` would be an easy and effective solution, but I'm afraid it would result in binaries that are not as portable.

However, I'm having the impression that the availability of `__builtin_popcnt` should just depend on the compiler version, and it would result in using a lookup table when more optimized instructions were not supported by the architecture, or the optimization flags are not passed on the command line. If this is correct, would it make sense to have distinct configuration flags like `RDK_USE_BUILTIN_POPCNT` (on by default), `RDK_OPTIMIZE_POPCNT` (enabling `-mpopcnt`, on by default, unless big endian), `RDK_OPTIMIZE_NATIVE` (enabling `-march=native`, off by default)? Or does it sound unnecessarily complicated?

**Comment by greglandrum** [comment]
I think it's safe to close this given the changes in #2865. Please reopen if I got that wrong
