### ISSUE TITLE
useChirality flag -- SimilarityMaps.py?

### ISSUE THREAD

**Issue by elcaceres** [rdkit/rdkit#934]
Hello, rdMD.GetMorganFingerprintAsBitVect() and rdMD.GetMorganFingerprint() each have an option for useChirality when fingerprinting, but this is not included in GetMorganFingerprint() in Chem/Draw/SimilarityMaps.py. Is there a specific rationale for not including it in the kwargs list, or might it be possible to add it?

**Comment by greglandrum** [comment]
I think the reason it's not included is "we didn't think of it".
That's easy enough to remedy
