### ISSUE TITLE
Jupyter Notebooks: Issue with PyMol.MolViewer on Windows

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#936]
When trying to use PyMol Server with Jupyter Notebooks on windows (maybe also on linux?) I get following error:

	C:\Anaconda3\lib\site-packages\rdkit\Chem\PyMol.py in GetPNG(self, h, w, preDelay)
		235       except IOError:
		236         time.sleep(0.1)
	--> 237     os.unlink(fd.name)
		238     fd=None
		239     if h is not None or w is not None:

	PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Temp\\tmp7vb9hlq9.png'

This problem is very old and I'm pretty sure there is already an issue for this as I found a fix a while back (don't remember exactly where). The issue can be solved by simply removing the offending line.

This then means images are not deleted but they are in temp directory so not a huge issue.

**Comment by greglandrum** [comment]
I use the functionality pretty regularly on linux and the Mac and haven't seen this, but it's easy enough to fix generally.

Thanks for the report!
