### ISSUE TITLE
Subshape module: Not Python 3 compatible

### ISSUE THREAD

**Issue by kienerj** [rdkit/rdkit#937]
Subshape module has several issues regarding python 3.

- Use of zip which has changed in python 3

		C:\Anaconda3\lib\site-packages\rdkit\Chem\Subshape\BuilderUtils.py in CalculateDirectionsAtPoint(pt, shapeGrid, winRad)
			324 eVals,eVects = numpy.linalg.eigh(covMat)
			325 sv = zip(eVals,numpy.transpose(eVects))
		--> 326 sv.sort(reverse=True)
			327 eVals,eVects=zip(*sv)
			328 pt.shapeMoments=tuple(eVals)

		AttributeError: 'zip' object has no attribute 'sort'

Solution:

    list(zip(eVals,numpy.transpose(eVects)))

- useage of iteritems method on dict

		C:\Anaconda3\lib\site-packages\rdkit\Chem\Subshape\SubshapeAligner.py in GetTriangleMatches(self, target, query)
			126     compatEdges={}
			127     tol2 = self.edgeTol*self.edgeTol
		--> 128     for tk,tv in tgtLs.iteritems():
			129       for qk,qv in queryLs.iteritems():
			130         if abs(tv-qv)<tol2:

		AttributeError: 'dict' object has no attribute 'iteritems'

Solution:
replace with `dict.items()`

- Usage of `has_key`

		C:\Anaconda3\lib\site-packages\rdkit\Chem\Subshape\SubshapeAligner.py in GetTriangleMatches(self, target, query)
			134       tgtLocs=[tgtPts[x].location for x in tgtTri]
			135       for queryTri in _getAllTriangles(queryPts,orderedTraversal=False):
		--> 136         if compatEdges.has_key(((tgtTri[0],tgtTri[1]),(queryTri[0],queryTri[1]))) and \
			137            compatEdges.has_key(((tgtTri[0],tgtTri[2]),(queryTri[0],queryTri[2]))) and \
			138            compatEdges.has_key(((tgtTri[1],tgtTri[2]),(queryTri[1],queryTri[2]))):

		AttributeError: 'dict' object has no attribute 'has_key'

Possible Solution:
Replace with `in`

**Comment by greglandrum** [comment]
@kienerj : that's definitely a bug, thanks for finding/reporting it.

To help me think about priorities: did you discover this because you're using the subshape module or did you turn this up some other way?

**Comment by kienerj** [comment]
I was "playing" around to see if it could be useful. Followed [this notebook](http://nbviewer.jupyter.org/gist/greglandrum/4316435). I'm not using it very actively or depend on it (I can also fall back to python 2.7 if I need to). So not very high priority from my side.
