### ISSUE TITLE
MCS returning partial rings with completeRingsOnly=True 

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#945]
_Reported by Luca Fenu_

Here's the thread: http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg05651.html
Here's the simple example:

```
In [5]: mol3RA = Chem.MolFromSmiles('c1ccc2cc3ccccc3cc2c1')

In [6]: mol3RB = Chem.MolFromSmiles('c1ccc2c(c1)ccc1ccccc21')

In [7]: rdFMCS.FindMCS((mol3RA,mol3RB),completeRingsOnly=True).smartsString
Out[7]: '[#6]1:[#6]:[#6]:[#6]2:[#6](:[#6]:1):[#6]:[#6]:[#6](:[#6]:2):[#6]:[#6]:[#6]:[#6]'
```

**Comment by greglandrum** [comment]
Here's another example of a related problem (maybe not exactly the same) from an analysis of some patent data.
```
# a set of molecules from US Patent US7547691 B2
smis = ['CC1(C)CC(=CCNc2ncc(Cl)c(-c3cc4c(C(=O)NC5CC5)cccc4s3)n2)CC(C)(C)N1', 
        'Cc1cnc(NCCCN2C(C)CNCC2C)nc1-c1cc2c(C(=O)NC3CC3)cccc2s1', 
        'CC(C)(C)OC(=O)N1CCN(CCCNc2ncc(Cl)c(-c3cc4c(C(N)=O)cccc4s3)n2)CC1', 
        'Cc1cnc(NCCCN2CCN(C)C[C@@H]2C)nc1-c1cc2c(C(=O)NC3CC3)cccc2s1', 
        'Cc1cnc(C(N)CCN2CCN(C(=O)OC(C)(C)C)CC2)nc1-c1cc2ccccc2s1', 
        'NC[C@H]1CC[C@@H](CNc2nccc(-c3cc4ccccc4s3)n2)CC1', 'CNC(=O)c1cccc2sc(-c3nc(NCCCN4CCN(C)CC4)ncc3Br)cc12', 
        'CN1CCN(CCCNc2ncc(Cl)c(-c3cc4ccc(Br)cc4s3)n2)CC1', 
        'CC(C)(C)OC(=O)N1CCC(C(=O)NCCCNc2ncc(Cl)c(-c3cc4c(C(=O)NC5CC5)cccc4s3)n2)CC1', 
        'CNC(=O)c1cccc2sc(-c3nc(NCCCC4CCN(C)CC4)ncc3Cl)cc12']
mols_m = [Chem.MolFromSmiles(x) for x in smis]
```
Start by matching the full dataset, this does the right thing:
```
mcs = MCS.FindMCS(mols_m,
                  atomCompare=MCS.AtomCompare.CompareAny,
                  bondCompare=MCS.BondCompare.CompareAny,
                  timeout=30,completeRingsOnly=True)
print("Canceled?",mcs.canceled)
print("SMARTS:",mcs.smartsString)
mcsM = Chem.MolFromSmarts(mcs.smartsString)         
mcsM.UpdatePropertyCache(False)
Chem.SetHybridization(mcsM)
svg = moltosvg(mcsM,kekulize=False)
SVG(svg)
```
The output is:
```
Canceled? False
SMARTS: [#6]-[#6]-[#7,#6]-[#6]1:[#7]:[#6]:[#6]:[#6](:[#7]:1)-[#6]1:[#6,#16]:[#6]2:[#6]:[#6]:[#6]:[#6]:[#6]:2:[#16,#6]:1
```
![image](https://cloud.githubusercontent.com/assets/540511/17356465/e61d261a-5957-11e6-8f15-6e932d2ad001.png)

Do the same thing with a threshold of 80%:
```
mcs = MCS.FindMCS(mols_m,
                  threshold=0.8,
                  atomCompare=MCS.AtomCompare.CompareAny,
                  bondCompare=MCS.BondCompare.CompareAny,
                  timeout=30,completeRingsOnly=True)
print("Canceled?",mcs.canceled)
print("SMARTS:",mcs.smartsString)
mcsM = Chem.MolFromSmarts(mcs.smartsString)         
mcsM.UpdatePropertyCache(False)
Chem.SetHybridization(mcsM)
svg = moltosvg(mcsM,kekulize=False)
SVG(svg)
```
output:
```
Canceled? False
SMARTS: [#6]-,=[#6]-[#6]-[#7]-[#6]1:[#7]:[#6]:[#6](:[#6](:[#7]:1)-[#6](:[#6]):[#16]:[#6]1:[#6]:[#6](:[#6]:[#6]:[#6]:1)-[#35,#6])-[#17,#6,#35]
```
![image](https://cloud.githubusercontent.com/assets/540511/17356564/80cc9df8-5958-11e6-801a-da5a7c417c17.png)

It turns out to be traceable to the last few molecules:
```
mcs = MCS.FindMCS(mols_m[7:],
                  threshold=0.6,
                  atomCompare=MCS.AtomCompare.CompareAny,
                  bondCompare=MCS.BondCompare.CompareAny,
                  timeout=30,completeRingsOnly=True)
print("Canceled?",mcs.canceled)
print("SMARTS:",mcs.smartsString)
mcsM = Chem.MolFromSmarts(mcs.smartsString)         
mcsM.UpdatePropertyCache(False)
Chem.SetHybridization(mcsM)
svg = moltosvg(mcsM,kekulize=False)
SVG(svg)
```
output:
```
Canceled? False
SMARTS: [#6]-[#7]1-[#6]-[#6]-[#7,#6](-[#6]-[#6]-1)-[#6]-[#6]-[#6]-[#7]-[#6]1:[#7]:[#6]:[#6](:[#6](:[#7]:1)-[#6](:[#6]):[#16]:[#6]1:[#6]:[#6](:[#6]:[#6]:[#6]:1)-[#35,#6])-[#17]
```
![image](https://cloud.githubusercontent.com/assets/540511/17356536/571ca30e-5958-11e6-8b99-3678362feb52.png)

**Comment by greglandrum** [comment]
And here's that last set reduced to the minimum:
```
lsmis = ['c1cc2ccc(Br)cc2s1',
        'c1cc2c(cccc2s1)C(=O)NC1CC1',
        'CNC(=O)c1cccc2sc(cc12)']
lmols = [Chem.MolFromSmiles(x) for x in lsmis]
mcs = MCS.FindMCS(lmols,
                  threshold=0.8,
                  atomCompare=MCS.AtomCompare.CompareAny,
                  bondCompare=MCS.BondCompare.CompareAny,
                  timeout=30,completeRingsOnly=True)
print("Canceled?",mcs.canceled)
print("SMARTS:",mcs.smartsString)
mcsM = Chem.MolFromSmarts(mcs.smartsString)         
mcsM.UpdatePropertyCache(False)
Chem.SetHybridization(mcsM)
svg = moltosvg(mcsM,kekulize=False)
SVG(svg)
```
output:
```
Canceled? False
SMARTS: [#6](:[#6]):[#16]:[#6]1:[#6]:[#6](:[#6]:[#6]:[#6]:1)-[#35,#6]
Out[92]:
```
![image](https://cloud.githubusercontent.com/assets/540511/17356851/f5c1e626-5959-11e6-87d8-3076fb304878.png)

**Comment by greglandrum** [comment]
Another example from the KNIME forum (https://tech.knime.org/forum/rdkit/mcs-node-breaking-up-rings):
```
In [3]: smis = """FC(F)(F)C1=CC=CC=C1C1=CC=C2C(=C1)N=CN=C2N1CCN(CC1)C(=O)C=C
   ...: OCC#CC(=O)N1CCN(CC1)C1=C2C=C(Cl)C(=CC2=NC=N1)C1=CC=C(F)C=C1F
   ...: ClC1=CC=CC=C1C1=C2N=C(N=CC2=CC=C1)N1CCN(CC1)C(=O)C=C
   ...: ClC1=CC=C2C(=C1)N=CN=C2N1CCN(C(C1)C#N)C(=O)C=C
   ...: C=CC(=O)N1CCN(CC1C#N)C1=C2C=CC=CC2=NC=N1
   ...: ClC1=CC=C2C(=C1)N=CN=C2N1CCN(C(C1)C#N)C(=O)C=C
   ...: C=CC(=O)N1CCN(CC1)C1=C2C=CC(=CC2=NC=N1)C1=CC=CC=C1
   ...: ClC1=C(C=C2N=CN=C(N3CCC(CC3)NC(=O)C=C)C2=C1)C1=CC=CC=C1"""

In [4]: ms = [Chem.MolFromSmiles(x) for x in smis.split('\n')]

In [6]: res = rdFMCS.FindMCS(ms,timeout=100,completeRingsOnly=True,atomCompare=rdFMCS.AtomCompare.CompareAny,bondCompare=rdFMCS.BondCompare.CompareAny)

In [7]: res.canceled
Out[7]: False

In [8]: res.smartsString
Out[8]: '[#6,#8]=,#[#6]-[#6,#7]-[#7,#6]1-[#6]-[#6]-[#7](-[#6]-[#6]-1)-[#6]1:[#6,#7]:[#6](:[#6]:[#6]:[#6]:[#6]):[#7,#6]:[#6]:[#7]:1'
```

**Comment by adalke** [comment]
In case it's of any help, the original fmcs output for the first example, from Luca Fenu, is "[#6]:1:[#6]:[#6]:[#6]:2:[#6]:[#6]:[#6]:[#6]:[#6]:[#6]:[#6]:[#6]:[#6]:2:[#6]:1", which has the same number of atoms and bonds at the one RDKit returns, but which fulfills the completeRingsOnly=True criterion.

For the August 3, 2016 'lmols' example at https://github.com/rdkit/rdkit/issues/945#issuecomment-237160187 it returns '[#6]:1:[#6]:[#6]:2:[#6]:[#6]:[#6]:[#6]:[#6]:2:[#16]:1' which is one atom smaller than the RDKit result, but it contains 2 rings (and they are complete rings) so has the same number of bonds.

**Comment by greglandrum** [comment]
Here's another super simple one, demonstrating that at least part of the problem is that the code isn't looking at the ring membership of atoms, only bonds:
```
In [11]: ms = [Chem.MolFromSmiles(x) for x in ('C1CC1N2CC2','C1CC1N')]

In [12]: rdFMCS.FindMCS(ms,completeRingsOnly=True).smartsString
Out[12]: '[#6]1-[#6]-[#6]-1-[#7]'
```

**Comment by adalke** [comment]
The original fmcs code gives essentially identical results:
```
% cat y.smi
C1CC1N2CC2 first
C1CC1N second
% python fmcs y.smi --complete-rings-only
[#6]-@1-@[#6]-@[#6]-@1-!@[#7] 4 atoms 4 bonds (complete search)
```
Looking more closely, there is a difference in the documentation for "complete rings only". In fmcs the documentation says: "If a bond is a ring bond in the input structures and a bond is in the MCS then the bond must also be in a ring in the MCS."

In RDKit it says "if an atom is part of the MCS and the atom is in a ring of the entire molecule then that atom is also in a ring of the MCS. Set completeRingsOnly to True to toggle this requirement".

I remember in the original fmcs that I tried saying that ring atoms must match ring atoms, so that there was no bond in the MCS between "CO" and "C1CCCC1O" . However, that didn't seem to be useful.

**Comment by greglandrum** [comment]
Since there's a very simple fix for my current case and dealing with completeRingsOnly is trickier, I've created a new ticket for it: #2034

**Comment by luancarvalhomartins** [comment]
Hi there.

Is there any advance in this bug? I am writing an application that relies upon the use of FindMCS, and I am stuck with MCS.FindMCS because of rdFMCS.FindMCS does not honor completeRingsOnly. I don't code in C++, but I would like to help. However, I would need some directions on the code. I took a look at GraphMol/FMCS/FMCS.cpp:273 checkRingMatch, but I could not figure out what the problem is.

Thank you very much

**Comment by greglandrum** [comment]
@luancarvalhomartins :  I will take a look at this again to see if I can fix it relatively quickly, but no guarantees. This isn't the simplest bit of code to work with.
