### ISSUE TITLE
Kekulization issues post successful smiles parsing

### ISSUE THREAD

**Issue by bp-kelley** [rdkit/rdkit#962]
This was reported by Peter Gedeck.

Wildcards are parseable in smiles, but sometimes can't be kekulized

Fails:
cid:image002.png@01D1C623.0F26EFA0

>>> from rdkit import Chem
>>> s = 'C2*c1ccccc1C2'
>>> mol = Chem.MolFromSmiles(s)
>>> Chem.MolToMolBlock(mol)
[09:50:35] Can't kekulize mol
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Sanitization error: Can't kekulize mol
 
This works:
 
>>> s = 'C2*Cc1ccccc12'
 
And writing the aromatic ring as single/double bonds too:
 
>>> s = 'C2*C1=CC=CC=C1C2'
>>> mol = Chem.MolFromSmiles(s)
>>> Chem.MolToMolBlock(mol)
 
Breakdown:

![kekulization](https://cloud.githubusercontent.com/assets/9888416/16358628/ac627eaa-3ae6-11e6-96f9-fa4a6c085ccc.png)

**Comment by greglandrum** [comment]
Looks like the problem here is that the first one ends up kekulizing to a bogus structure:
```
In [20]: s = 'C2*c1ccccc1C2'

In [21]: mol = Chem.MolFromSmiles(s)

In [22]: Chem.MolToSmiles(mol)
Out[22]: '[*]1=c2ccccc2CC1'
```
