### ISSUE TITLE
Embed Molecule for minimization

### ISSUE THREAD

**Issue by AmadeusJ** [rdkit/rdkit#963]
Hello! I have a question about rdkit python function "EmbedMolecule()"... I can't find out your email, so I write here! One of the arguments used in "EmbedMolecule" named "maxAttemps", I don't know what is meaning... I can't understand that " maxAttempts : the maximum number of attempts to try embedding "... What is the things be embedded? isn't it a molecule??? or is it the conformers??...I couldn't find out the answers from the rdkit manual... Thank you!! Have a good day!﻿
_I 'm using the SDFs from pubchem. 
_molfile is the compounds in SDFs.

            try:
                mol = Chem.MolFromMolBlock(molfile)
                new_mol = AllChem.AddHs(mol)
                AllChem.EmbedMolecule(new_mol, maxAttempts=23, useRandomCoords=True)
                AllChem.UFFOptimizeMolecule(new_mol, maxIters=23)
                ff = AllChem.UFFGetMoleculeForceField(new_mol)
                print Count, "Minimizing Molecule...!"
                ff.Minimize(maxIts=23)
                E = ff.CalcEnergy()
                OutContents = Chem.MolToMolBlock(new_mol) + '\n$$$$'
                OutFile.write(OutContents + '\n')
                OutFile.flush()
                EnergyFile.write(title + ",%.2f"%float(E) + '\n')
                EnergyFile.flush()
                sdf = ""
            except:
                print "Error Molecule....!"
                ErrorFile.write(molfile)
                ErrorFile.flush()
                sdf = ""

**Comment by greglandrum** [comment]
The embedding of a conformation has a random component and does not always succeed (there are a number of reasons for possible failure). `maxAttempts` is the number of times that the algorithm will re-try the process in an attempt to get a passing conformation.

Unless you have a very specific reason to adjust this parameter, it's probably better to leave it at the default value.

**Comment by AmadeusJ** [comment]
Thank you for your answering!!
Then, how can I minimize & optimize 3D molecule using rdkit??
If "EmbedMolecule" makes the random coordinate, how can I do that?
When I use the 2D molecule, there is no problem but 3D molecule show me some strange results...
Can I ask some python code script for 3D molecule minimization & optimization?
I'm using the sdf/mol format compounds... 
Thank you!

**Comment by greglandrum** [comment]
EmbedMolecule does not generate random coordinates. It generates (mostly) reasonably coordinates but there is a random process in the algorithm.
Sereina Riniker's presentation from our last UGM summarizes the process: https://github.com/rdkit/UGM_2015/blob/master/Presentations/ETKDG.SereinaRiniker.pdf 
Our paper has more detail and a bunch of references: http://pubs.acs.org/doi/abs/10.1021/acs.jcim.5b00654

There is also a high level overview, along with sample code for doing embedding and minimization in the RDKit documentation:
http://rdkit.org/docs/GettingStartedInPython.html#working-with-3d-molecules

**Comment by PikachuSauvage** [comment]
Hi,
We came across this post and want to ask for some help.
What we are tring to do is to fix any random factor in EmbedMolecule() so that we can reproduce exactly the same structure once again and we constantly failed to do so after useRandomCoords=False, randomSeed = 0. 

our codes looks like this:
m2 = Chem.MolFromSmiles(com)
m3 = Chem.AddHs(m2)
AllChem.EmbedMolecule(m3, useRandomCoords=False,  randomSeed = 0)
Chem.MolToMolFile(m3,'CheckMol'+str(index)+'.sdf')

As greglandrum is mentioning earlier, there is a random component. Is there any parameters we are missing in this case?

**Comment by greglandrum** [comment]
I believe this has been answered in #2575 2575
