### ISSUE TITLE
Cartridge crashes on fingerprint-related operations (CentOS 6.8, pgsql 9.4.4, rdkit  0.73.0)

### ISSUE THREAD

**Issue by DmitriR** [rdkit/rdkit#981]
Hello,

I tried to index chembl21 for use with rdkit pgsql cartridge; load and indexing went fine, and e.g. substructure queries are OK. 

But fingerprint-related functionality seems broken:
at least % and <%> operators, and _fp functions. 

In trying to narrow down the issue, I downloaded the cartridge portion of the rdkit git tree and tried to run tests in /sql directory on a new database. I am getting similar crashes.  Details are below.

Dmitri

<pre>
CentOS release 6.8, 2.6.32-642.3.1.el6.x86_64
psql (PostgreSQL) 9.4.4
PostgreSQL 9.4.4 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit

Installed with 'conda install -c rdkit rdkit' : 

rdkit.__version__
'2016.03.2'
</pre>
(after writing this, I noticed a new release became available;
upgraded to 2016.03.3, but that made no difference with the crashes as the cartridge is apparently unchanged)
<pre>
select rdkit_version();
 rdkit_version 
---------------
 0.73.0
</pre>

<pre>
psql -c 'create database rdkit_test;'
psql -d rdkit_test < ./sql/rdkit-91.sql
</pre>
Output: 
<pre>
<... lots of stuff where all seems OK>
SELECT
        id,
        tanimoto_sml(rdkit_fp('C1C(OC2=CC(=CC(=C2C1=O)O)O)'::mol), f)
FROM
         (SELECT * FROM pgbfp ORDER BY id) AS t
WHERE rdkit_fp('C1C(OC2=CC(=CC(=C2C1=O)O)O)'::mol) % f
LIMIT 10;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
connection to server was lost
</pre>

Server logs:
<pre>
LOG:  server process (PID 30358) was terminated by signal 4: Illegal instruction
DETAIL:  Failed process was running: SELECT
                id,
                tanimoto_sml(rdkit_fp('C1C(OC2=CC(=CC(=C2C1=O)O)O)'::mol), f)
        FROM
                 (SELECT * FROM pgbfp ORDER BY id) AS t
        WHERE rdkit_fp('C1C(OC2=CC(=CC(=C2C1=O)O)O)'::mol) % f
        LIMIT 10;
LOG:  terminating any other active server processes
</pre>

Likewise, 
`SELECT dice_sml(rdkit_fp('c1ccccc1'::mol),rdkit_fp('c1ccncc1'::mol));`
crashes the server with 
<pre>
T:  /l
        SELECT dice_sml(rdkit_fp('c1ccccc1'::mol),rdkit_fp('c1ccncc1'::mol));
LOG:  server process (PID 30529) was terminated by signal 4: Illegal instruction
DETAIL:  Failed process was running: SELECT dice_sml(rdkit_fp('c1ccccc1'::mol),rdkit_fp('c1ccncc1'::mol));
LOG:  terminating any other active server processes
</pre>

**Comment by rvianello** [comment]
what is the output of 'grep flags /proc/cpuinfo | head -n 1' on this machine?

**Comment by DmitriR** [comment]
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 lahf_lm dtherm tpr_shadow vnmi flexpriority

**Comment by DmitriR** [comment]
I tried an essentially identical configuration (also CentOS 6.8, PostgreSQL 9.4.4, rdkit 0.73.0) in a VM on a different comuter; **no crash** (e.g. for the same statement that crashes on my direct-install, non-VM box:  `SELECT dice_sml(rdkit_fp('c1ccccc1'::mol),rdkit_fp('c1ccncc1'::mol));`

Now I will try compiling locally on the non-VM box and see if the crash goes away. 

But in any case this is probably not, strictly speaking, an issue with the cartridge. I will close the issue for now, and re-open if I see any indication this is not just a hardware or OS problem.

**Comment by rvianello** [comment]
sorry, yesterday I forgot to comment on this. the conda recipes build the cartridge with the optimization settings configured in the Makefile, and that by default include using the builtin popcnt instruction. This flag doesn't appear in the list from /proc/cpuinfo, so I suspect the pre-built packages might be not compatible with it. In building the cartridge from the source code distribution you might therefore also try disabling the POPCOUNT settings in the Makefile. (if you plan to use the conda-rdkit recipes, removing this variable from the end of [line](https://github.com/rdkit/conda-rdkit/blob/master/rdkit-postgresql/Makefile.patch#L50) could be enough).

**Comment by DmitriR** [comment]
@rvianello - Thanks! This is most likely it. In the VM I referred to, where the crash does not occur, popcnt capability *is* present.
