### ISSUE TITLE
prepareMolForDrawing(): Do not add Hs to some three-coordinate Cs

### ISSUE THREAD

**Issue by greglandrum** [rdkit/rdkit#982]
The 2006 IUPAC recommendations suggest not adding Hs in many cases. Try to capture that.

**Comment by bp-kelley** [comment]
Although this is an IUPAC recommendation, I wonder how chemists feel about the differences.  Do you want me to do a non-robust sampling?

**Comment by greglandrum** [comment]
I'd be curious to hear what the chemists you talk to say (and I'll ask on the mailing list as well), and it's not like the IUPAC recs say that you shouldn't add Hs, but there are many cases where it's not possible to add an H in a way that doesn't look stupid (="wrong" by IUPAC) without completely regenerating coordinates. For example:

![image](https://cloud.githubusercontent.com/assets/540511/17125987/efb32fa4-52f8-11e6-81ad-d299ffac10ad.png)
