### ISSUE TITLE
Right-justified elements in RCSB SDF files raise an exception

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#995]
Right-justified elements in RCSB SDF files raise an exception. As pointed out by Hannes Loeffler, the CTFile specs do not prescribe a specific justification for the element field.
This is addressed by PR #994 .

**Comment by greglandrum** [comment]
Just as an FYI: I think it's fine to just do the PR for these simple things that are immediately fixed. I can flag the PR itself as a bug.

**Comment by greglandrum** [comment]
fixed by 63b6bde

**Comment by ptosco** [comment]
Ah, OK, I thought that would save you same work as I thought you always opened a bug to back up the PR. Thanks for letting me know!

**Comment by greglandrum** [comment]
I always used to, but I've realized that it seems like extra work for these simple "open and close" bugs.
